### ISSUE TITLE
sfdx and vscode disabled in visual studio code

### ISSUE THREAD

**Issue by pratima320** [forcedotcom/salesforcedx-vscode#1000]
### Summary
I have two windows open on Visual Studio code, one of the windows everything is working great with LWC extensions, but in the other i dont see auto-suggestion, Cant refer LWC, lint is not working, bascially LWC etensions is not really working. sfdx folder looks disabled inside the project. Please see screenshot. Also I have the pre-rlease CLI installed with the LWC.
<img width="592" alt="screen shot 2019-01-31 at 11 05 37 pm" src="https://user-images.githubusercontent.com/18334211/52102176-0f6ecb80-25ad-11e9-9484-fa0397aa76eb.png">

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by pratima320** [comment]
I have two windows open on Visual Studio code, one of the windows everything is working great with LWC extensions, but in the other i dont see auto-suggestion, Cant refer LWC, lint is not working, bascially LWC etensions is not really working. sfdx folder looks disabled inside the project. Please see screenshot. Also I have the pre-rlease CLI installed with the LWC.
<img width="592" alt="screen shot 2019-01-31 at 11 05 37 pm" src="https://user-images.githubusercontent.com/18334211/52102176-0f6ecb80-25ad-11e9-9484-fa0397aa76eb.png">

**Comment by ntotten** [comment]
@lcampos Is this because of the Apex LSP? I assume both instances run on the same port. Anything we can do to support multiple windows?

**Comment by klewis-sfdc** [comment]
Hi @pratima320 - we have made improvements to the extensions since this issue was opened, and I am unable to reproduce currently.  If you are still seeing the same issue please feel free to reopen.  Thank you.
