### ISSUE TITLE
analytics metadata files should be recognized as json

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#1002]
**Is your feature request related to a problem? Please describe.**
When you pull down things in the /wave folder, many of them are JSON files.  

**Describe the solution you'd like**
.wdash, .wdf, .wdpr, .wlens should all be shown as json.  Bonus points for autoformatting them.

**Describe alternatives you've considered**
I've explained these types to vscode manually, and called Format Document on them manually

**Additional context**
Nice, huh?

{"dataSourceLinks":[],"filters":[],"gridLayouts":[],"layouts":[],"steps":{"aggregateflex":{"broadcastFacet":true,"datasets":[{"name":"opportunity"}],"isGlobal":false,"query":{"query":"{\"measures\":[[\"sum\",\"Amount\"],[\"sum\",\"Stage.IsPushed\"]],\"filters\":[[\"IsClosed\",[\"false\"],\"in\"]],\"groups\":[\"Name\"],\"order\":[[\"sum_Amount\",{\"ascending\":false}]]}","version":-1.0},"receiveFacet":true,"selectMode":"multi","type":"aggregateflex","useGlobal":true,"visualizationParameters":{"visualizationType":"pyramid"}}},"widgets":{"aggregateflex_chart":{"parameters":{"autoFitMode":"none","totalValue":"computeTotal","showValues":true,"showMeasureTitle":true,"legend":{"descOrder":false,"showHeader":true,"sorting":{"order":"asc"},"show":true,"customSize":"auto","position":"right-top","inside":false},"tooltip":{"showBinLabel":true,"measures":"","showPercentage":true,"showDimensions":true,"showMeasures":true,"customizeTooltip":false,"dimensions":""},"visualizationType":"pyramid","exploreLink":true,"title":{"fontSize":14,"subtitleFontSize":11,"label":"Explore Opportunities","align":"center","subtitleLabel":" Select new measures and add groupings and filters to get actionable insights."},"trellis":{"flipLabels":false,"showGridLines":true,"size":[100,100],"enable":false,"type":"x","chartsPerLine":4},"totalLabel":"","showMeasure":true,"columnMap":{"measureAxis2":["sum_Stage.IsPushed"],"measureAxis1":["sum_Amount"],"trellis":[],"dimensionAxis":["Name"],"plots":["sum_Amount","sum_Stage.IsPushed"]},"showActionMenu":true,"measureAxis2":{"sqrtScale":false,"title":"Stage: Pushed","customDomain":{"showDomain":false}},"measureAxis1":{"sqrtScale":false,"title":"Amount","customDomain":{"showDomain":false}},"theme":"wave","step":"aggregateflex","rightColor":"#e16032","leftColor":"#52b7d8","dimensionAxis":{"customSize":"auto","showAxis":true},"applyConditionalFormatting":true},"type":"chart"}}}

**Comment by ntotten** [comment]
Shipping in next release
