### ISSUE TITLE
Automate the creation of the meta-xml file.

### ISSUE THREAD

**Issue by jriordan22849** [forcedotcom/salesforcedx-vscode#1009]
**Is your feature request related to a problem? Please describe.**
No, proposed enhancement.

**Describe the solution you'd like**
When I create a new class/trigger/page file, I would like the relevant file type meta-xml file to be automatically generated with the latest API version.
This will reduce time creating a file and then creating the corresponding meta-xml file manually. Make the meta-xml file generation automatic.

**Additional context**
Depending on the file type been created, the relevant meta-xml file should be created.
**Examples**
For class xml-meta, something like the following should be generated.
```
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>31.0</apiVersion>
    <status>Active</status>
</ApexClass>
```

For page xml-meta, something like the following should be generated.
```
<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>31.0</apiVersion>
    <label>Test Page</label>
</ApexPage>
```

**Comment by jriordan22849** [comment]
Actually, already does it, ignore or delete this thread.

**Comment by sanketraj8** [comment]
> Actually, already does it, ignore or delete this thread.

For me, this is not happening. Did you do any additional changes/setting updates/extensions to make this work?
