### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by amitabhleo** [forcedotcom/salesforcedx-vscode#1017]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `44.18.0`
- OS Version: `Linux x64 4.18.0-14-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/amitabh/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Duplicate of #968

**Comment by ntotten** [comment]
@amitabhleo Can you please attach he file: `/home/amitabh/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`
