### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ankitrakeshsfdc** [forcedotcom/salesforcedx-vscode#1034]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `44.18.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\aravu\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by steals** [comment]
Most probably it's a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/968

**Comment by ntotten** [comment]
Duplicate of #968

**Comment by ntotten** [comment]
@ankitrakeshsfdc Can you attach the file `C:\Users\aravu\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`
