### ISSUE TITLE
SFDX: Create Lightning Web Component does not refresh the VS Code tree, so the component is not visble

### ISSUE THREAD

**Issue by amitkumarj1979** [forcedotcom/salesforcedx-vscode#1036]
### Summary

Right click on the lwc folder and select SFDX: Create Lightning Web Component. Name the component and hit Enter. The component is created but its not visible in the VS Code tree on the left side.

### Steps To Reproduce:

1.  Right click on lwc folder and select  SFDX: Create Lightning Web Component.
1.  Name the component something and hit Enter.
1. The component is created but visible on the VS Code tree on the left side.

### Expected result

The new component should show up in VSCode on the left side tree.

### Actual result

The new component does NOT show up on the tree on the left side.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.31

**SFDX CLI Version**: 45.1.2

**OS and version**: MAC OS 10.14.2

**Comment by ntotten** [comment]
I think this might be a bug in VSCode's latest release. I have seen similar issues since updating. See: https://github.com/Microsoft/vscode/issues/68361

**Comment by lcampos** [comment]
@amitkumarj1979 have you tried enabling vscode's experimental file watcher ? That solved most of the issues I was seeing on my side. Settings > Check the "Use Experimental File Watcher" Option.

**Comment by ntotten** [comment]
This appears to have been resolved by VS Code, please reopen if you are still seeing it.
