### ISSUE TITLE
VSCode doesn't see my sfdx project

### ISSUE THREAD

**Issue by patmcclellan** [forcedotcom/salesforcedx-vscode#1038]
I have a VSCode/sfdx breakdown and don’t know how to resolve. CLI still works, but VSCode command palette doesn’t seem to recognize that I have an sfdx project open. Only provides commands for Creating a project (3 variations) and Set a Default Org. 

I've uninstalled the Salesforce Extension Pack, uninstalled VSCode, manually deleted the .vscode folder from my Mac, reinstalled VSCode, reinstalled the Salesforce Extension Pack, updated sfdx. Created a pristine new sfdx project. No other extensions or changed to default user settings. 

The problem persists.

This all worked fine for me last week, till late in the day Friday when I tried pushing an lwc to my scratch org and it timed out, tried again, timed out. So I quit VSCode and restarted my Mac. Then the push to scratch org command had disappeared -- only the Create Project options and Set a Default Org in the command palette.

This situation applies to all my projects, not just the one I was working on when I did the restart. It's not a project-level corruption.

CLI commands still work.

**Comment by patmcclellan** [comment]
@muenzpraeger

**Comment by patmcclellan** [comment]
@ntotten @muenzpraeger When I uninstalled/reinstalled VSCode, I just dumped the app in the trash because there's no Uninstall command I could find in VSCode. I also trashed the .vscode folder with the extensions. However, after reinstall, as soon as I opened the app, it opened to the project I had most previously opened. That makes me think there's a vscode prefs file somewhere, but I can't find it.

**Comment by ntotten** [comment]
I am reopening this to investigate. It seems like maybe there is a bug. The resolution shouldn't be to have to delete all of VS Code and all cache files and start over. :)

**Comment by patmcclellan** [comment]
Let me know if you need anything from me to help debug. Not sure what would be left on my machine...

**Comment by patmcclellan** [comment]
@ntotten Any update on this? It has happened to me again.

**Comment by patmcclellan** [comment]
I went through the FULL uninstall/reinstall and it's working again. That's really a pain. I've kept all the files I trashed, in case they will help in debugging this.

**Comment by patmcclellan** [comment]
Now the SFDX commands show up in the VSCode command palette, and the browser icon appears in the footer and will open my default scratch org, but... when I try to push I'm getting an error:
`PROJECT PATH  ERROR
────────────  ───────
              Unknown`

**Comment by ashishy258** [comment]
@patmcclellan 
have your problem solved???

**Comment by emma-bruce** [comment]
Same issue here
