### ISSUE TITLE
extremely long retrieve / deploy [45.1.0 - February 9, 2019]

### ISSUE THREAD

**Issue by zix66** [forcedotcom/salesforcedx-vscode#1042]
extremely long retrieve / deploy [45.1.0 - February 9, 2019]

It is taking more than a minute to deploy single class:  09:24:40 → 09:25:38

for example other ide's, like Cloud9, Metaforce - taking up to 10 sec. to deploy 
same item into same project within same time range ..     

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

09:24:40.365 sfdx force:source:deploy --sourcepath c:\VS Code SF Projects\XXX\force-app\main\default\classes\XXX.cls --json --loglevel fatal
{"status":0,"result":{"deployedSource":[{"state":"Add","fullName":"XXX","type":"ApexClass","filePath":"force-app\\main\\default\\classes\\XXX.cls"},{"state":"Add","fullName":"XXX","type":"ApexClass","filePath":"force-app\\main\\default\\classes\\XXX.cls-meta.xml"}]}}
09:25:38.965 sfdx force:source:deploy --sourcepath c:\VS Code SF Projects\XXX\force-app\main\default\classes\XXX.cls --json --loglevel fatal ended with exit code 0

**VS Code Version**:
45
**OS and version**:
Win 64

**Comment by smaddox-sf** [comment]
Cleaning up old issues - We have work in process on deploy / retrieve performance - https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements
