### ISSUE TITLE
VSCode extension can't install

### ISSUE THREAD

**Issue by KevinGossentCap** [forcedotcom/salesforcedx-vscode#1043]
### Summary

I'm doing a fresh install with latest tools and it seems impossible to install salesforce.salesforcedx-vscode extension (all the others are ok ot install independentaly).
Also, if after installing the other extensions and then try to install this one, theyr all end-up uninstalled.

**VS Code Version**: 1.31.0

**SFDX CLI Version**: Latest

**OS and version**: Windows 10 x64

**Comment by Gothiname** [comment]
Same configuration here and same error

When i try with the extension manager i got the error :
`Failed to install : salesforce.salesforcedx-vscode`.
When i try with the command line way i got the error : 
`Corrupt ZIP: end of central directory record signature not found`
`Failed Installing Extensions: salesforce.salesforcedx-vscode`

**Comment by 1ktribble** [comment]
I'm also experiencing a similar issue issue. In my case, the extension pack (v. 45.1.0) installs quickly alongside the Apex Replay Debugger, the Apex Interactive Debugger, Aura Components, Lightning Web Components, and Visualforce. The Salesforce CLI Integration and Apex extensions are stuck in the 'Installing' status.

**Comment by lcampos** [comment]
@KevinGossentCap could you confirm you don't have more than one vscode installed? Also, are you trying to install the extensions using the vscode extensions sidebar or by clicking install from the market place listing ?

**Comment by KevinGossentCap** [comment]
Hi @lcampos 
I confirm I have only 1 install.
I'm personnaly trying to install from the vscode extension sidebar.

To note: there have been a big change in VScode for extensions with version 1.31 (possibility to activate extensions without reload), it might be related.

**Comment by aboninn** [comment]
Hi @lcampos 
Same issue for me (Win 10 x64, vsCode v1.31, sfdx-cli/6.52.2-c6cdc99881 (windows-x64) node-v8.9.4).
I cannot install from the vscode extension sidebar.
I tried to install with "Install from VSIX..." menu, and I got this error: "Corrupt ZIP: end of central directory record signature not found". I downloaded several times the salesforce.salesforcedx-vscode-45.1.0.vsix.

I also tried to uninstall VSCode and start with a v1.30 version to get classic extension reload button, and still the same issue, but I could launch the install with the vsix, and it seems to install all components, and works fine with a trailhead playground to test.
Regards

**Comment by gdo** [comment]
Hello, Same error for me
Visual Studio code information
Version : 1.31.1
Date 2019-02-12T02:20:54.427Z
Electron : 3.1.2
Chrome 66.0.3359.181
Node.js 10.2.0 <<<<<<<  Node 10 and not node 8 perhaps the problems
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

It's a fresh install of vscode without any extension.
I try to download the vsix but I can't use it

**Comment by elliot41** [comment]
Hello, Same error for me :/

**Comment by lcampos** [comment]
@1ktribble I think your experience might be related to an existing vscode issue where the install status doesn't get updated but the extensions do get installed. You can see that the extensions got installed by reloading vscode https://github.com/Microsoft/vscode/issues/68584. @KevinGossentCap I think you might be experiencing this as well, could you confirm ?

For the rest of the people on this thread, there seems to be a different issue where at the moment vscode unpacks the `vsix` to install the extension it throws the `Corrupt ZIP: end of central directory record signature not found`. I know this is what @Gothiname and @aboninn are running into, @gdo and @elliot41 could you clarify which of the 2 issues you're running into ?

At the moment, we're working on getting a way of replicating the `Corrupt Zip ...` on our side so we can debug it and release a fix if this is an issue with the extensions themselves. I'll keep this thread updated once we have more details to share.

**Comment by KevinGossentCap** [comment]
@lcampos unfortunately it's not the same. Some of the extensions installed by the pack have it, but others (including the pack itself) are simply reverting themselves to a uninstalled status (so install button is available before and after clicking it).

**Comment by elliot41** [comment]
@lcampos Hello !

When I click install it doesn't prompt "installed", it prompts : 
![image](https://user-images.githubusercontent.com/15812951/52779778-23a0d700-3049-11e9-9f98-c6e2e90f4982.png)

And when I click on "Download Manually" I have the issue "Corrupt ZIP: end of central directory record signature not found".

Thanks for your help !
Have a nice day

**Comment by KevinGossentCap** [comment]
Hi,
I've just tested and it worked.
Only change was to update SFDX-CLI which should not have any impact.
I had already upgraded VSCode to 1.31.1 but I think it was behaving with the same error as with 1.31.0.

**Comment by lcampos** [comment]
Glad some of you are now able to install the extensions. I haven't been able to replicate the `Corrupt Zip...` issue on my side but if someone's still running into this, could you verify the SHA for the extension by following the instructions here [Verify SHA256](https://github.com/forcedotcom/salesforcedx-vscode/blob/afdb1785e10fdf683893a21e7e1e73e4ea15ef78/SHA256.md) and let me know if it doesn't match.

**Comment by JoernBerkefeld** [comment]
have this issue on multiple company laptops right now. we are sitting behind a proxy but IT support first whitelisted the domains required by VSCode (https://code.visualstudio.com/docs/setup/network) as well as then deactivate the proxy. still getting the corrupt zip error

**Comment by lcampos** [comment]
@JoernBerkefeld I suggest you open an issue directly on the VSCode repo (https://github.com/microsoft/vscode) since they own the code that downloads extension updates.

**Comment by vai12** [comment]
i have download the updated version both java jdk and sfdx (cli) and when i am trying to install salesforce extension pack in the vs code facing below errors
<img width="956" alt="Screenshot 2021-09-03 104027" src="https://user-images.githubusercontent.com/55106242/132012417-bf8b3a59-80c5-4cb3-a44b-418ae4f802ba.png">
