### ISSUE TITLE
nodePath assigned in code-workspace settings

### ISSUE THREAD

**Issue by timothywlewis** [forcedotcom/salesforcedx-vscode#1049]
### Summary

Our project's VS Code workspace settings, which are committed to git, are being updated with a `eslint.nodePath` setting with a machine-specific path (e.g. `/Users/jdoe/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-44.17.0/node_modules`). We are not using eslint in our project but the machine-specific nature of the file change causes friction for our development experience.

This is an issue since we expect the .code-workspace files to remain machine agnostic.

If you haven't used VS Code Workspaces, here's a primer on how they work and how settings work with them:

https://code.visualstudio.com/docs/editor/multi-root-workspaces
https://vscode-docs.readthedocs.io/en/stable/customization/userandworkspace/

### Steps To Reproduce:

1.  Open a `.code-workspace` while the vscode sfdx extension is installed.

### Expected result

It should have simply opened VS Code without modifying the `.code-workspace`.

### Actual result

It adds `"eslint.nodePath": "/Users/jdoe/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-45.1.0/node_modules"` to the `.code-workspace` file.

### Additional information

**VS Code Version**: Version 1.31.1 (1.31.1)

**SFDX CLI Version**: salesforcedx 45.1.2 ; sfdx-cli/6.52.2-c6cdc99881 (darwin-x64) node-v8.9.4

**OS and version**: macOS 10.14.2

Please see attached screenshot.

<img width="811" alt="2019-02-13-sfdx-vscode-workspace-eslintnodepath-is" src="https://user-images.githubusercontent.com/25631337/52730793-33a5b180-2f8a-11e9-991a-148328d8a32d.png">

### Workaround using obscure git plumbing

In the interim, I'm using [this trick](https://stackoverflow.com/questions/28497104/how-to-ignore-any-changes-on-already-committed-file-to-git) to reduce the friction caused to our developer experience.

```
git update-index --skip-worktree *.code-workspace
```

*Note that this git option's original purpose is support for sparse checkout.*

**Comment by Szandor72** [comment]
I ran into this issue today as well while trying to setup eslint configuration for my aura components. As I am a beginner on things node, npm, eslint it took me a while to find out it goes back to here:

I tried a standard eslint setup with 
```
 "env": {
        "browser": true,
        "es6": true
    },
    "extends": "airbnb-base",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
    }
```
all dependencies installed, I still got an error that my airbnb standard could not be found. 

when I de-installed the lightning-web-components extension (disabling did not suffice), eslint would run from my local node_modules and find all necessary extensions.

My user story goes as follows:
With standard VS Code settings, the integrated Typescript Engine also works for Aura JS files.
This gives a lot of errors around $A and runtime utilities loaded wie requireScript
I found no way to disable this internal checks except for //@ts-ignore
I disabled the engine and started investigating into eslint
after lots of head cracking, I ended up here.

**Comment by mserinjane** [comment]
@Szandor72 in your globals config you can add $A (and any other global that SF uses)
"globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly",
        "$A": "readonly"
    },

**Comment by Szandor72** [comment]
Noticing this just now @mserinjane  - that's what I did / found out by now, thanks!

**Comment by ntotten** [comment]
This is resolved in today's release.
