### ISSUE TITLE
APEX Test class

### ISSUE THREAD

**Issue by pazOmer** [forcedotcom/salesforcedx-vscode#1050]
Hi,
I am new to VS Code and from some reason, I can't run test class and I see the message "There is no data provider registered that can provide view data."

Can you send some instructions on how to run test class?

Best,
Omer

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via GitHub issues. Please post your question on the [Trailblazer Community](https://success.salesforce.com), [Stackoverflow](https://salesforce.stackexchange.com/), or through other official support channels.
