### ISSUE TITLE
Deploy to source org

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1060]
16:00:12.32 sfdx force:source:deploy --sourcepath c:\HexagonSFDC\dev\force-app\main\default\classes\AccountUtility.cls --json --loglevel fatal
{"message":"Deploy failed.","status":1,"stack":"DeployFailed: Deploy failed.\n    at ALMError (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\salesforce-alm\\dist\\lib\\almError.js:44:19)\n    at MetadataRegistry.initializeMetadataTypeInfos.then.catch.e (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceApiCommand.js:67:35)\n    at tryCatcher (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Immediate.Async.drainQueues (C:\\Users\\sattir\\AppData\\Local\\sfdx\\plugins\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)","name":"DeployFailed","result":[{"columnNumber":"17","lineNumber":"171","error":"Variable does not exist: acc (171:17)","fullName":"AccountUtility","type":"ApexClass","filePath":"force-app\\main\\default\\classes\\AccountUtility.cls"}],"warnings":["All --json output, including on error, is moving to stdout. Use the SFDX_JSON_TO_STDOUT environment variable to move over to the new functionality. This will become the default in version 45."]}
16:01:25.609 sfdx force:source:deploy --sourcepath c:\HexagonSFDC\dev\force-app\main\default\classes\AccountUtility.cls --json --loglevel fatal ended with exit code 1

**Comment by lcampos** [comment]
The stack trace shows that the error is not with the tool but with the apex class not being valid `Variable does not exist: acc`.
