### ISSUE TITLE
apex.db causing issues git commit

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1061]
OS: Windows
OHmy SZh
> git ls-tree -l HEAD -- c:\HexagonSFDC\dev\.sfdx\tools\apex.db
> git show f4dac6697e7d164cb88cb051751d870e7fd433b7
> git show :force-app/main/default/classes/AccountUtility.cls
> git add -A -- .
fatal: confused by unstable object source data for 8fade9015b2a25fb08b15d9c78a840de3083c507

**Comment by ntotten** [comment]
You should not be checking in anything in the `.sfdx` folder. Add that folder to your `.gitignore`. Everything in that folder is just for local caching, etc.
