### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rajganesan** [forcedotcom/salesforcedx-vscode#1065]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.2.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/rajganesan/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@rajganesan Can you please attach the file: /Users/rajganesan/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt ?

**Comment by praksb** [comment]
@rajganesan We have made some improvements to Apex LSP performance in our latest extension update. Can you please update to the latest Apex extension (v45.3.0) and let us know if you still have any performance issues? Please open a new github issue if you still see any perf related problems.

#1092
