### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by alessiobortone2** [forcedotcom/salesforcedx-vscode#1070]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.2.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/alessiobortone/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@alessiobortone2 Thanks for reporting this issue. Can you please attach the file from: /Users/alessiobortone/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt ?

Also, if possible can you please provide what operation where you doing when you observed the high CPU usage?

**Comment by praksb** [comment]
@alessiobortone2 We have made some improvements to Apex LSP performance in our latest extension update. Can you please update to the latest Apex extension (v45.3.0) and let us know if you still have any performance issues? Please open a new github issue if you still see any perf related problems.

#1092
