### ISSUE TITLE
LightningComponentBundle not part of package.xml generated for a new project with manifest

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/salesforcedx-vscode#1072]
**FEATURE REQUEST**
When creating a project with manifest (sfdx force:project:create -n MyProject -x), the generated manifest (package.xml) doesn't include LightningComponentBundle.

**Expected**
Just add LightningComponentBundle to the generated package.xml:
```
 <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
 </types>
```

**Comment by lcampos** [comment]
Hi @FabienTaillon, I'm closing this since it's been addressed as part of the Salesforce CLI release `7.3.0`. You can start using it by running `sfdx force:project:create --projectname dxProjectLightning -x`. Thanks for the feedback.

cc @ntotten
