### ISSUE TITLE
Error on nested report folders: illegal operation on a directory

### ISSUE THREAD

**Issue by NataliaCognizant** [forcedotcom/salesforcedx-vscode#1088]
### Summary
_Error on nested report folders: illegal operation on a directory_.

### Steps To Reproduce:
1. Open XML package from your SFDX project
1. Add a report folder and a child report folder nested
1. Add some reports which are inside that nested report folder
1. Save XML package
1. Execute “SFDX: Retrieve Source from org” command 

### Expected result
A notification pop up informs in Visual Studio:
_SFDX: Retrieve Source from Org successfully ran_.

### Actual result
Console log displays the following error message in Visual Studio:
_ERROR:  EISDIR: illegal operation on a directory, read_.

### Additional information
**VS Code Version**: 1.31.1 (system setup)
**SFDX CLI Version**: 6.53.67a9cbb60c
**OS and version**: Windows 7 64-bit

**Comment by kbierbaum** [comment]
This is related to known issue https://success.salesforce.com/issues_view?id=a1p3A000000JWcfQAG and not VS Code. We have notified the appropriate team.
