### ISSUE TITLE
Move Configs to Project Templates

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1090]
Today, several of the extensions for VS Code write or update various configuration files from the extension. Examples are the jsconfig.json, .eslintrc from LWC, changing values in .vscode/settings.json from the core extension and LWC.

I find this pattern of having the extensions write config files to be jarring and unfamiliar. I can't think of any other tools that do this. We have also seen problems (https://github.com/forcedotcom/salesforcedx-vscode/issues/1049) from customers when we update these files - specifically for local settings.

Instead of writing configuration files and settings from extensions we should include those files and settings in the project or other templates and the extensions should check for their presence and provide proper warnings when they are not included.

We already have done most of this work with the updated project create template. It now will include the following out of the box:

```
├── README.md
├── .gitignore
├── .forceignore
├── .prettierrc
├── .prettierignore
├── .vscode
│   ├── extensions.json
│   ├── settings.json
│   └── launch.json
├── config
│   └── project-scratch-def.json
├── force-app
│   └── main
│       └── default
│           ├── applications
│           ├── aura
│           ├── classes
│           ├── contentassets
│           ├── flexipages
│           ├── layouts
│           ├── lwc
│           │  └── .eslintrc.json
│           ├── objects
│           ├── permissionsets
│           ├── staticresources
│           ├── tabs
│           └── triggers
└── sfdx-project.json
```

So you will already get most of what you need to have configured in an extension in the default template. If we added a few things such as the `jsconfig.json` file then we could eliminate the need for extensions to write files/settings individually.

This does bring up the problem of what happens if the settings/config files change. We have in the past discussed the idea of a CLI command called `force:project:update` that would update your project files to the latest version. This is useful for changes to the schema of the `sfdx-project.json` or updating/adding config files with new settings.

Additionally, there could be functionality in the command `fource:project:update --check` that does a check of your projects version settings. With this command, we could do a single check that your project was in the right state from the core VS Code extension - one place to manage all the configs and settings. We would then prompt people to upgrade their project if needed. This would remove the need for every extension to implement this themselves.

Additionally, we need to put local user configurations in a new place outside of `.vscode/settings.json`. That file is meant to be used for project settings, not user settings. If we do have local, extension specific settings we should adopt something like `.sfdx/settings.json` that is not checked into source control.

**Comment by dehru** [comment]
I'm just commenting on the .vscode/settings.json file, and my recent experience working within this repo.

I keep getting phantom changes magically during development.  It makes me think this should be in .gitignore.  

Looking at the content of .vscode/settings.json
```
{
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/.vscode-test": true
  },
  "search.exclude": {
    "**/out": true
  },
  "typescript.tsdk": "./node_modules/typescript/lib",
  "editor.tabSize": 2,
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "rewrap.wrappingColumn": 80
}
```

It seems like the use of the more standard/cross-editor ```.editorconfig``` file, ( with the vscode extension to support it ), and .gitignore, .prettierrc might handle most of these properties.   The only ones I'm not sure about is the "search.exclude" and "typescript.tsdk".

**Comment by lcampos** [comment]
Addressed as part of version `45.12.0`

**Comment by ntotten** [comment]
@lcampos I think there are still a few left. jsconfig and eslint.

**Comment by lcampos** [comment]
@ntotten I do see those being under the `lwc` folder. Are we talking about different ones ?

![Screen Shot 2019-04-25 at 10 49 58 AM](https://user-images.githubusercontent.com/1041842/56757028-0d4d8080-6748-11e9-8d85-5ab4b1e1e37b.png)

**Comment by ntotten** [comment]
Sorry, I should have been more clear. This issue isn't actually about having them in the template - it is about removing the behavior of the extension from writing them at all. So the first step was adding them to the template. Now we need to make it so the extension does not write these files at all but rather just checks to make sure they exist and provide so information on how to create them.

**Comment by lcampos** [comment]
Got it, thanks for clarifying 👍
