### ISSUE TITLE
Can't push lwc. Project Path error: unknown.

### ISSUE THREAD

**Issue by patmcclellan** [forcedotcom/salesforcedx-vscode#1095]
Using latest versions of everything: VSCode, CLI, Salesforce Extensions, SFDX update.

I've had an issue twice where VSCode locks up, then when reopened, it doesn't recognize that I have an SFDX project open.[ See that issue here](https://github.com/forcedotcom/salesforcedx-vscode/issues/1038) (I mention that because it might be related to this issue.)

Immediately after resolving that today for the second time, I have a new issue where I can't push. See the screen shot. I can run the status command and get a result, so it knows the project path, but when I push I get a Project Path error.

@ntotten

**Comment by patmcclellan** [comment]
![screen shot 2019-02-21 at 7 37 42 pm](https://user-images.githubusercontent.com/29382439/53256652-389aed00-367d-11e9-9078-4694a942589d.png)

**Comment by patmcclellan** [comment]
I can also pull from the scratch, but cannot push to it.
![screen shot 2019-02-22 at 8 43 00 am](https://user-images.githubusercontent.com/29382439/53256956-ed350e80-367d-11e9-8b2d-88065b0512f9.png)

**Comment by patmcclellan** [comment]
I created a fresh project and a fresh scratch org, and I was able to push; it's not VSCode application/extensions level.

I went back to my main project and tried to push to the new scratch org and got the same PROJECT PATH ERROR Unknown. So, it's not the scratch org.

I am able to run a status command between my VSCode Source and the Scratch Org, and I can pull from the scratch org. Both of those require a valid PROJECT PATH.

So... why does the PULL command not see the project path -- or give me an error on it? What is different between Pull and Push, with regard to PROJECT PATH?

If this is a Project level issue, what file might have been corrupted? 

I copied the sfdx-project.json file from my main project and used it to replace the corresponding file in my test project. The test project still pushes with no problem.

**Comment by patmcclellan** [comment]
MORE INFO: I am able to sfdx force:source:deploy from this project into my scratch org. I can deploy, but not push.

**Comment by patmcclellan** [comment]
UPDATE: I was able to deploy a Class, but when I try this: `sfdx force:source:deploy -p force-app/main/default/lwc` I get the same PROJECT PATH error. 
![screen shot 2019-02-22 at 11 31 02 am](https://user-images.githubusercontent.com/29382439/53266382-7b68bf00-3695-11e9-9995-42bdb3a7deec.png)

**Comment by patmcclellan** [comment]
Attaching the jsconfig.json (converted to txt so I can attach it here) file that's in the lwc folder. I can't see anything that looks amiss, but I'm new to lwc...

[jsconfig copy.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2895484/jsconfig.copy.txt)

**Comment by patmcclellan** [comment]
FIXED IT! One of my lwc had a CSS file that I had emptied out. Empty file. Soon as I deleted it, push resumes no problem. ARRRRGH!

**Comment by patmcclellan** [comment]
FIXED IT! One of my lwc had a CSS file that I had emptied out. Empty file. Soon as I deleted it, push resumes no problem. ARRRRGH!

**Comment by RahulThange15** [comment]
The same issue is when you use the wrong naming convention for the name of LWC component.
eg. richtextdemo should be richTextDemo

Solution : try to delete the component from org and deploy with new name. It should work.
