### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by amphi-** [forcedotcom/salesforcedx-vscode#1098]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.3.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1479,
		"activateCallTime": 3,
		"activateResolvedTime": 6705,
		"activationEvent": "onCommand:sfdx.force.project.create"
	}
}
```
Issue: actions like "create lightning web component" do not work anymore...even reinstalling the extension didn't help. No changes have been done. 
<img width="382" alt="screenshot 2019-02-22 at 20 47 50" src="https://user-images.githubusercontent.com/4158209/53267250-2fdd0200-36e3-11e9-807e-677b5ed779aa.png">
<img width="440" alt="screenshot 2019-02-22 at 20 34 21" src="https://user-images.githubusercontent.com/4158209/53267251-30759880-36e3-11e9-8004-267d805b67a7.png">

**Comment by lcampos** [comment]
Hi @amphi- , could you open the vscode Developer Tools window (Help > Developer Tools), go to the Console tab and run the script I've added below ? This will let us know if vscode is able to find your local sfdx cli path.

```
nodeRequire('child_process').exec('which sfdx', (err, stdout, stderr) => {
  if (err) {
    console.error(`exec error: ${err}`);
    return;
  }
  console.log(`SFDX CLI path: ${stdout}`);
});
```

**Comment by amphi-** [comment]
Hi @lcampos path seems to be found:

VM241:6 SFDX CLI path: /usr/local/bin/sfdx

**Comment by amphi-** [comment]
Found the error - was my own fault...didn't see the message on the button "no default org set"...sorry for that! :)
