### ISSUE TITLE
Retrieve From Source on any location finishes with code 0. Does not pull new metadata

### ISSUE THREAD

**Issue by WhoStoleMyFries** [forcedotcom/salesforcedx-vscode#1102]
### Steps To Reproduce:

1. Add new metadata to your org via dev console or an unmanaged package
2. In VS Code, navigate to the manifest > package.xml
3. Run Retrieve Source in Manifest from Org
4. Watch it run and complete with an exit code of 0 while pulling absolutely nothing new in

I have tried running the command from individual files and folders. It does not matter.

### Expected/Actual result

It should have pulled new metadata. It did not pull anything new.

### Additional information

I have reproduced this from my work and personal computer multiple times from multiple locations and other operations run just fine. This is pretty difficult to work with and basically makes the product unusable, IMO. I can't recreate a project (the current workaround) every time another dev adds something. I tried going through the CLI and had the same result (apologies if you separate that from vscode and that is where the bug should be logged)

**VS Code Version**: 45.3

**SFDX CLI Version**: 6.54.4

**OS and version**: Windows 10--up to date.

**Comment by ntotten** [comment]
@WhoStoleMyFries What type of metadata are you adding? Does the the `package.xml` contain the metadata type you just added?
