### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by peeriyagama** [forcedotcom/salesforcedx-vscode#1104]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2903466/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.3.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\peeri\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by peeriyagama** [comment]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2903465/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by praksb** [comment]
@peeriyagama Can you share more information on what operation you were performing when you observed the high cpu load? Is it during loading a new project or editing a file or applying a refactoring? Does the cpu load come down after sometime or does it just continue to stay high? How many apex classes and triggers does your project have?

It is possible that the Apex LSP which is a Java process might be the source of high CPU. In that case, can you also share a thread dump that would help us identify the problem. You can use jstack to collect this information. Here is some info on taking thread dumps:

https://blog.fastthread.io/2016/06/06/how-to-take-thread-dumps-7-options/

**Comment by paul-drozd-itechart** [comment]
having the same issue
