### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by heribertofilho** [forcedotcom/salesforcedx-vscode#1105]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.3.0`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2906817/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

Even when rebooting my PC and opening visual code without any project open, this exception will be thrown.

**Comment by praksb** [comment]
@heribertofilho Are you seeing a perf issue or an exception or both? If you are seeing an exception can you please include more details on the exception that is thrown and the call stack?

If it is a perf issue, can you share more information on what operation you were performing when you observed the high cpu load? Does the cpu load come down after some time or does it just continue to stay high? How many apex classes and triggers does your project have?

It is possible that the Apex LSP which is a Java process might be the source of high CPU. In that case, can you also share a thread dump that would help us identify the problem. You can use jstack to collect this information. Here is some info on taking thread dumps:

https://blog.fastthread.io/2016/06/06/how-to-take-thread-dumps-7-options/

**Comment by heribertofilho** [comment]
Hi, so it's really an issue, since I can't even issue a do a "SFDX: Create project with a manifest" command. I'll do this dump soon as possible.

**Comment by paul-drozd-itechart** [comment]
having the same issue
