### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by patrickhellosign** [forcedotcom/salesforcedx-vscode#1108]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.3.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/patrickledbetter/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
@patrickhellosign Please attach the file listed in the issue ^
