### ISSUE TITLE
Don't focus Output Panel

### ISSUE THREAD

**Issue by JorneVL** [forcedotcom/salesforcedx-vscode#1110]
### Summary

Don't change the focus to the Output panel when the deploy is started

### Steps To Reproduce:

1.  Save a file
1.  Start typing in a other file
3.  Focus will change to the Output panel when you type in the file.

### Expected result

Just add a notification and don't change the focus.

### Actual result

Focus Output Panel

### Additional information

**VS Code Version**: 1.31.1

**SFDX CLI Version**: 6.54.4

**OS and version**: Windows 10

**Comment by ntotten** [comment]
@lcampos Is this something we can control or is it VS Code?

**Comment by brpowell** [comment]
@ntotten This is something we can control. In the forceSourceDeploy execute we call showChannelOutput.

**Comment by ntotten** [comment]
This is something that has come up in the past. There have been arguments for and against it. Some people like it because they see what happens, others don't because of the reason in this issue. Maybe it needs to be a preference?

**Comment by celador** [comment]
Stealing focus from the dev is the worst.  The extension should work transparently to the dev, not bang them over the head when anything is done.

**Comment by davyhuijgens** [comment]
On start of a command I can live with, but on finish is annoying especially with long running processes. The Dev will be doing somerhing else in the meantime.

**Comment by ChuckJonas** [comment]
IMO it should not show by default.  My preference would be a status bar ICON that lets you know a deployment is working. Clicking the status icon would then open the output console to review details

**Comment by bvfusion1001** [comment]
Definitely a preference. I prefer not focusing because I often enter a series of commands while multitasking, so the focus gets in my way.

**Comment by ntotten** [comment]
It seems that most people feel like we should not take focus. I am inclined to not even expose it as a preference, but just change the behavior. We don't want to have 200 preferences to configure and if there is a strong consensus it seems not needed in this case.

**Comment by renatoliveira** [comment]
Preference. Focus it by default. IMO it would be great to have three options:

1. Always focus the output tab.
2. Never focus the output tab.
3. Focus only on errors (deploy command returns something other than 0).

Don't know if the third one is possible, but the first two options definitely are!

**Comment by lcampos** [comment]
We're never going to have consensus on this and I'm opposed to a proliferation of settings/prefs. VS Code comes with out of the box shortcuts and commands to focus on the terminal and output view. I think we should remove it.

**Comment by chandra2ravi** [comment]
don't focus. will continue work while processing

**Comment by MattTurnure** [comment]
Don’t focus by default. Simple notification. Make it configurable in preferences. Thanks!

**Comment by muenzpraeger** [comment]
Remove the focus. We get anyway error/success information as popup/in the status bar.

**Comment by willcobbett** [comment]
Like the idea of making this optional/configurable as suggested above

**Comment by lcampos** [comment]
This was addressed in release `45.8.0`.
