### ISSUE TITLE
Intellisense Apex/VS

### ISSUE THREAD

**Issue by mmclaughlinre** [forcedotcom/salesforcedx-vscode#1113]
Hello,

I recently started using Visual Studio Salesforce Extension and I cannot seem to figure out why Apex Intellisense is not working. Can I have support on this issue?

Thanks!
Mitchell 
mmclaughlin@Relationedge.com

**Comment by ntotten** [comment]
Do you by chance have any Java extensions installed? There are a few Java extensions that conflict with Apex and will override the Apex extension. We recommend disabling all unused extensions for the workspace. See: https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension

**Comment by mmclaughlinre** [comment]
Thank you for the quick response @ntotten - No other extensions enabled. any other suggestions?
![image](https://user-images.githubusercontent.com/46694012/53650849-5545a080-3bfa-11e9-83b0-eca6989aea61.png)

**Comment by brpowell** [comment]
Hi @mmclaughlinre. Is intellisense partially working or not at all? For SObjects, you need to run the command SFDX: Refresh SObject Definitions to have up-to-date autocompletion on your SObjects. If it's not working at all, it could be an issue with your Java home setting. In your vscode settings try setting the `salesforcedx-vscode-apex.java.home` key to your Java 8 runtime path. For example: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home

**Comment by mmclaughlinre** [comment]
@brpowell  Thank you so much! That did it!

**Comment by brpowell** [comment]
Glad to hear that @mmclaughlinre! Was the issue refreshing the SObjects or setting the Java home path? We like to get feedback on these kinds of things to improve the experience of first time set up.

**Comment by mmclaughlinre** [comment]
@brpowell  The former!

**Comment by brpowell** [comment]
Thanks for letting us know, we'll keep this in mind going forward.

**Comment by JodieM** [comment]
Thanks, that worked for me too! Refreshing the SObjects. I did not know that needed to be done! It makes such a difference!

**Comment by gab95** [comment]
it works on SObjects but i can't make it work with variables...
do you have the same problem... it only happen with triggers?
![image](https://user-images.githubusercontent.com/49696483/100486545-ab4ebd00-30da-11eb-85df-83c5259893cf.png)
