### ISSUE TITLE
Cannot use SFDX: Refresh SObject Definitions for multiple orgs

### ISSUE THREAD

**Issue by sfuser16** [forcedotcom/salesforcedx-vscode#1120]
### Summary

I have to perform dev on multiple orgs. I have a scratch org and a Developer Edition that I work on.
My default org is set to my scratch org. But when I execute **SFDX: Refresh SObject Definitions** in my Developer Edition org which also exists as a project in SFDX, I cannot sync it. I couldn't find anything in the docs as to how can I fix this. Please advice.

### Steps To Reproduce:

1.  Create a scratch org
2.  Set this as your default org using --setdefaultusername when creating and setup project in VS Code.
3. Using Command Palette, execute the command _SFDX: Refresh SObject Definitions_ on the scratch org. This should be successful 
4. Create another Dev org
5. Use SFDX and setup this dev org also in VS Code.
6. Deactivate the scratch org now.
7. Using Command Palette, execute the command _SFDX: Refresh SObject Definitions_ for this Dev org

### Expected result

The sObject definitions should have been refreshed

### Actual result

sfdx sobject definitions refresh ended with exit code 1

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.30.0

**SFDX CLI Version**: sfdx-cli/6.55.1-be0b3dc4c4 (darwin-x64) node-v8.9.4

**OS and version**:macOS Mojave 10.14.3

**Comment by ntotten** [comment]
Can you clarify that when you create the new org you have also set it as the default org before you do the refresh? I am wondering if the old org that is deactivated is still set as default.
