### ISSUE TITLE
SFDX options disappeared in context menu

### ISSUE THREAD

**Issue by nissimlevy** [forcedotcom/salesforcedx-vscode#1127]
### Summary

The Sfdx options in Visual Studio Code no longer show the Sfdx options. They appeared and suddenly disappeared. The issue titled "Show why Retrieve/Deploy commands missing from menu" does not offer a resolution. Oddly, when doing a Ctrl-shit P I do see the SFDX: Create Project option.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
I'm closing this since it doesn't have enough information to address it and because I think it is covered by issue #1196 . Feel free to re-open if that issue does not cover your scenario and add enough information for us to be able to replicate it.

**Comment by nissimlevy** [comment]
I don't see how there isn't enough information. The sfdx context menu disappears when opening another project or closing down visual studio. What other information should I include?

Sent from Yahoo Mail on Android 
 
  On Wed, 27 Mar 2019 at 4:09 PM, lcampos<notifications@github.com> wrote:   
I'm closing this since it doesn't have enough information to address it and because I think it is covered by issue #1196 . Feel free to re-open if that issue does not cover your scenario and add enough information for us to be able to replicate it.
