### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tusharbudhe0302** [forcedotcom/salesforcedx-vscode#1134]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.5.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.32.1`

:warning: Make sure to **check attachment**
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2946872/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@tusharbudhe0302 Can you share more information on what operation you were performing when you observed the high cpu load? Is it during loading a new project or editing a file or applying a refactoring to an Apex Class? Does the cpu load come down after sometime or does it just continue to stay high? How many apex classes and triggers does your project have?

It is possible that the Apex LSP which is a Java process might be the source of high CPU. In that case, can you also share a thread dump that would help us identify the problem? You can use jstack to collect this information. Here is some info on taking thread dumps:

https://blog.fastthread.io/2016/06/06/how-to-take-thread-dumps-7-options/
