### ISSUE TITLE
Update to knowledge document for mv ./tmpsrc ./src/main/default

### ISSUE THREAD

**Issue by lb14447** [forcedotcom/salesforcedx-vscode#1136]
This is in reference to the instructions listed at https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/migrate-from-forcecom-ide

The command mv ./tmpsrc ./src/main/default needs to be updated to mv ./tmpsrc/main ./src in order to make sure the folder structure from tmpsrc/main/default copies correctly to src folder.

**Comment by ntotten** [comment]
This was fixed.
