### ISSUE TITLE
Please sign language server jar

### ISSUE THREAD

**Issue by kenhuman** [forcedotcom/salesforcedx-vscode#1142]
**Is your feature request related to a problem? Please describe.**
The language server jar is blocked from execution by my company's application whitelisting software.

**Describe the solution you'd like**
Sign the jar.

**Describe alternatives you've considered**
Currently whitelisting every new version.

**Additional context**
None

**Comment by lcampos** [comment]
Hi @kenhuman, could you provide more details on why your company's whitelisting software is blocking the apex lsp jar ? We do sign the jar every time it gets updated so I'm thinking there might be certain details on the cert we're using that could be modified/added.
