### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by stradcom** [forcedotcom/salesforcedx-vscode#1149]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2963860/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.5.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.1`

**Comment by praksb** [comment]
@stradcom Can you share more information on what operation you were performing when you observed the high cpu load? Is it during loading a new project or editing a file or applying a refactoring to an Apex Class? Does the cpu load come down after sometime or does it just continue to stay high? How many apex classes and triggers does your project have?

It is possible that the Apex LSP which is a Java process might be the source of high CPU. In that case, can you also share a thread dump that would help us identify the problem? You can use jstack to collect this information. Here is some info on taking thread dumps:

https://blog.fastthread.io/2016/06/06/how-to-take-thread-dumps-7-options/

**Comment by stradcom** [comment]
@praksb - this happened consistently while trying to push my source on a newly created scratch org. the project i was working on is fairly small, no more than 10 custom objects with about 100 custom fields - including those created for the standard objects. The process spikes up probably around 50 seconds in the CLI call. i was using force:source:push with -w 10. I will try and see if i can get into the thread dump - but no promises. I've got this issue specific to this box, and is consistently occurring. I can not replicate on a PC. HTH.

**Comment by shetzel** [comment]
There is a known bug with the Salesforce CLI where source:push or source:deploy of wave analytics metadata that fails to deploy would cause this.  Possible that other types could cause this as well.  Can you confirm that the runaway process involved is sfdx (versus java)?  Can you also confirm that a deploy failure happened via the org UI, and the failing metadata type?

**Comment by SVijenSingh** [comment]
[salesforce.salesforcedx-vscode-lightning-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4923561/salesforce.salesforcedx-vscode-lightning-unresponsive.cpuprofile.txt)
facing these issues for a long time.

**Comment by rlancejohnson** [comment]
Running into this issue everytime I open a new sfdx project. The extensions are taking a very long time to load.

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4928283/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

[salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4928284/salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt)

**Comment by colinkenworthy** [comment]
This suddenly started 2 days ago for me, there were some VS Code updates around the same time.
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4937979/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

[salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4937976/salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt)
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4937977/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by rlancejohnson** [comment]
Any update on this?

**Comment by gyadav4** [comment]
Team, any updates?

**Comment by smaddox-sf** [comment]
Regarding the time to activate the extensions when opening a new project - We are tracking those improvements on #2295 .  That seems to be the majority of the discussion on this issue, so closing to consolidate the discussion.
