### ISSUE TITLE
Command Palette shortcuts missing v45.6

### ISSUE THREAD

**Issue by jstacer** [forcedotcom/salesforcedx-vscode#1161]
In the latest versions of VS Code and SFDX extension bundle (from Salesforce) on Mac OS Mojave, many of the command palette shortcuts seem to be missing. When I ran the updates last week, many of them disappeared and now there are only four:

<img width="605" alt="Screen Shot 2019-03-18 at 3 36 26 PM" src="https://user-images.githubusercontent.com/4816737/54558336-d8ede400-4993-11e9-9332-fb3d2b556688.png">

**VS Code Version**:
Version 1.32.3

**SFDX CLI Version**:
45.6

**OS and version**:
Mac OS Mojave 10.14.3

**Comment by lcampos** [comment]
Hi @jstacer can you confirm if you have a sfdx project open and have a defaultusername for it ? That would mean having a scratch org or a dev org assigned for it.
