### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by imamsaheb242689** [forcedotcom/salesforcedx-vscode#1169]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.6.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\178022\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@imamsaheb242689  Can you share more information on what operation you were performing when you observed the high cpu load? Is it during loading a new project or editing a file or applying a refactoring to an Apex Class? Does the cpu load come down after sometime or does it just continue to stay high? How many apex classes and triggers does your project have?
