### ISSUE TITLE
'No commands matching'

### ISSUE THREAD

**Issue by masHugac** [forcedotcom/salesforcedx-vscode#117]
### Summary
After installing the extension pack the command palette doesn't provide the options as described in the readme. Tried reinstalling as well as individually installing the extensions.

### Steps To Reproduce:
1. Install the extension pack
1. Reload
1. Open an empty folder
1. Open command palette
1. '>SFDX'

### Expected result
SFDX options provided by the extension.

### Actual result
No commands were found

### Additional information

**VS Code Version**: Version 1.17.0-insider (1.17.0-insider)

**SFDX CLI Version**: 40.10.0

**OS and version**: macOS High Sierra 10.13 Beta (17A360a)

**Comment by vazexqi** [comment]
You need to open a folder with a sfdx-project.json in it at the top-level.

> 1. Install the extension pack
> 1. Reload
> 1. **Open an empty folder** (if you open an empty folder, without any sfdx-project.json, then none of the SFDX commands show up)
> 1. Open command palette
> 1. '>SFDX'

See https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode#get-started-with-salesforce-development-tools-for-visual-studio-code for more information on the requirements.

The actual code that checks for this is at https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-core/package.json#L115

Anything we can do to make this more clear?

CC: @ruthemmanuelle

**Comment by masHugac** [comment]
I don't know how I could've overseen this. As I am reading it the description is clear enough.
