### ISSUE TITLE
Code coverage error

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1178]
After last update Code Coverage shows correctly on Apex Classes, but an annoying notification appears every time a class with no code coverage is opened

This happens with Test Classes, maybe it could be great to ignore this files that does not require any line to test

![testCodeCoverage](https://user-images.githubusercontent.com/10410852/54773321-a2210380-4c09-11e9-8efa-63107c8754c7.gif)

Also, the org selector is now "Lightning" Fast

_Originally posted by @mnunezdm in https://github.com/forcedotcom/salesforcedx-vscode/issues/973#issuecomment-475335340_

**Comment by ntotten** [comment]
I verified that I can reproduce this error. We'll get it fixed.

**Comment by lcampos** [comment]
Yes, this is by design for the first version of the feature. We don't do any additional checks on the content of the file other than it being apex. This is good feedback and will address it in the follow up versions.

**Comment by mnunezdm** [comment]
No plans in changing this @smaddox-sf ?

**Comment by smaddox-sf** [comment]
hi @mnunezdm - I thought this had been resolved, but see now that's it's still happening.

**Comment by jonnypetraglia** [comment]
Would like to bump this as a request. If anything I'd like this to just be a status bar thing next to the "Show Apex Code Coverage" to show the current status (e.g. "On/Off/Found/None"), but seeing the notification **every time** I change tabs back to the test file I'm writing tests for is.....well it's rather ridiculous. How difficult would it really be to NEVER display the notification for Apex files that are tests? The extension(s) obviously know it's a test file if it knows to show "Run All Tests | Debug All Tests".

Like I get that this is a non-impacting change but just how high of an effort can it be to be stale for a year? Not even asking for caching with non-tests, just Tests that....literally will NEVER have coverage to retrieve. Not showing hundreds of useless notifications every day is not an unreasonable ask.

**Comment by jonnypetraglia** [comment]
Bumping on this in hopes of a response.

**Comment by randi274** [comment]
Thanks for the bump on this @jonnypetraglia - I've also confirmed it's in our backlog, it just hasn't bubbled up yet.

**Comment by jag-sfdc** [comment]
FYI, tracked internally as bug W-5971491.

**Comment by diyer** [comment]
This issue has been fixed and released.
