### ISSUE TITLE
Syntax color issue

### ISSUE THREAD

**Issue by islimane** [forcedotcom/salesforcedx-vscode#1180]
### Summary

The syntax color for queries in Apex files are not well displayed in some cases.

### Steps To Reproduce:
Type the following query in an Apex class:
`
	[
		SELECT Id, Name
		FROM Account
		WHERE Field1__c =: value1
			AND (
				Field2__c =: value2
				OR ( Field2__c =: value3 AND (Field2__c =: value3) )
			)
			AND Field4__c =: value4
		ORDER BY Field5__c ASC
	]
`

### Expected result

![Screen Shot 2019-03-22 at 12 47 41](https://user-images.githubusercontent.com/8045962/54820857-cd0a6680-4ca0-11e9-9da1-827d0f8e2942.png)

### Actual result

![Screen Shot 2019-03-22 at 12 46 20](https://user-images.githubusercontent.com/8045962/54820801-9d5b5e80-4ca0-11e9-8bb4-b84ca4a51d6c.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.32

**SFDX CLI Version**: 45.7.0

**OS and version**: OS X El Capitan 10.11.6

**Comment by praksb** [comment]
@islimane Thanks for reporting this issue, I could repro this issue. We'll take a look.
