### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mimowae** [forcedotcom/salesforcedx-vscode#1184]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.7.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\mimow\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@Mimowae Can you share more information on what operation you were performing when you observed the high cpu load? Is it during loading a new project or editing a file or applying a refactoring to an Apex Class? Does the cpu load come down after sometime or does it just continue to stay high?
