### ISSUE TITLE
Unable to deploy component with special name

### ISSUE THREAD

**Issue by raJSN** [forcedotcom/salesforcedx-vscode#1185]
### Summary

I have created some component by appending namespace prefix before component name & is trying to deploy them. But i am getting error.

### Steps To Reproduce:

1. Create one container component.
    In my case 'ltx_TabPanel_lwc'
2. Create another child component 
    In my case 'LTX_SectionComponent'
3. Use 2nd component inside container component like below.
    <template>
        <c-l-tx_section-component_lwc></c-l-tx_section-component_lwc>
    </template>

Note: If i rename the component to simple word like 'sectioncomponent', it gets deployed without any error.
### Expected result

Component should get deployed. 

### Actual result

Facing exception.

### Additional information

_Feel free to attach a screenshot_.
$ sfdx --version
sfdx-cli/6.56.0-e3fd846a1f (windows-x64) node-v8.15.1

![image](https://user-images.githubusercontent.com/3901703/54869706-a9d7d800-4dc2-11e9-9daf-26fe94c7ba98.png)

**Comment by raJSN** [comment]
After around 1 hour of struggle, I found this behavior.

Error with LTX_ prefixed.
![image](https://user-images.githubusercontent.com/3901703/54869783-7f3a4f00-4dc3-11e9-956c-459bed54aa1e.png)

Success with no prefix
![image](https://user-images.githubusercontent.com/3901703/54869796-b7da2880-4dc3-11e9-8dca-7d01b5375635.png)

**Comment by ntotten** [comment]
LWC Components must start with a lowercase character. See this document for the full list of naming rules: https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.create_components_folder
