### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cubicrootofthee** [forcedotcom/salesforcedx-vscode#1188]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.7.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\username\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@cubicrootofthee Can you share more information on what operation you were performing when you observed the high cpu load? Is it during loading a new project or editing a file or applying a refactoring to an Apex Class? Does the cpu load come down after sometime or does it just continue to stay high?

**Comment by kbierbaum** [comment]
We recently released some performance enhancements around extension start up/initialization. Is this still happening for you?

**Comment by cubicrootofthee** [comment]
That may be why I didn't see it since when setting it up for the rest of
the team.
You may close this case.
