### ISSUE TITLE
"Running Run Apex tests(s)" message/command still running even though test run finished

### ISSUE THREAD

**Issue by NousFlux** [forcedotcom/salesforcedx-vscode#1193]
### Summary

When I am running a unit test, the message "Running Run Apex test(s)" message keeps showing. It looks like the listener on my end is not registering that a test run is completed. This is an issue with running tests through my sandbox. This was happening sporadically at first but is a constant for me now.

### Steps To Reproduce:

1.  Open a project and use Sandbox to deploy and run tests from
1.  Make changes
1.  Either select "Run Test" via code lens or "Run Single Test" from the tests tab.

### Expected result

The CLI should recognize that a unit test has finished running and display results in output.

### Actual result

The CLI is stuck running specified test doesn't seem to know that test has actually finished running.

### Additional information

![image](https://user-images.githubusercontent.com/31668400/55028596-1f67c200-4fd6-11e9-8ff4-38091c78b637.png)

**VS Code Version**: 1.32.3

**SFDX CLI Version**: 6.56.0

**OS and version**: Windows 7

**Comment by ntotten** [comment]
We are unable to reproduce this, could you provide more details. Maybe a test project?
