### ISSUE TITLE
Context that shows/hides commands is not refreshed when switching orgs

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/salesforcedx-vscode#1196]
### Summary

The context set for deploy/retrieve commands is not being refreshed when a user moves between different org types or creates a new scratch org on a new project. This is causing users not being able to access commands like `SFDX: Push Source to Default Scratch Org`, `SFDX: Deploy Source in Manifest to Org`, etc.

### Steps To Reproduce:

1.  Create a new project `SFDX : Create Project with Manifest`
2. Create a scratch org `SFDX: Create a Default Scratch Org`
3. Create valid apex code `SFDX: Create Apex Class`
4. Try and deploy the new code to the newly create scratch org by opening the command palette and looking for `SFDX: Push Source to Default Scratch Org`

### Expected result
I see the push command on the command palette and I'm able to push code to the scratch org.

### Actual result
Context is not updated and commands remain hidden to the user. The user needs to reload the vscode window in order for the commands to show.

**Salesforce VS Code Extensions Version**: 45.6.0 and above
**VS Code Version**: 1.32.3
**SFDX CLI Version**: 6.56.0-e3fd846a1f
**OS and version**: Mac OS High Sierra

**Comment by deeelan** [comment]
I'm experience the same thing. Do anyone have the voluntee of fixing this? I have this issue almost three months ago. And any thread of this issue dont solve anything or its closed and reference to another thread with no solution. I've been working on Mac OS High Sierra and Windows 10. 

My solution is: when the options are displaying in the context menu, not update VSCode. It seems that everytime that VSCode launch an update it break it.

**Comment by deeelan** [comment]
Personally I think this not should happen, cuz the coding in Salesforce it supossed to b "full-supported" on VSCode

**Comment by garviand** [comment]
I don't get any of the Push/Deploy options on right-click, I am also not getting the testing options for Apex tests.

**Comment by Patlatus** [comment]
I have the same problem. When I create a Salesforce project, deploy\push\retrieve menu items disappear randomly and I am not able to restore them and get them back. Not sure if this is connected to switching between orgs. I just created a scratch org and I didn't switch org, however, initially those options were present and suddenly they disappear and I am not able to restore them.

**Comment by Patlatus** [comment]
Also my OS is not Mac, I am using Windows.

**Comment by HernanMorgado** [comment]
Hi! I have the same issue. I have searched through all google but i do not have idea why is this happening :( It was verry difficult to run succesfully the comand sfdx authorize an org and now this happens If someone had an idea of ​​this please share in this post :(

**Comment by lcampos** [comment]
As a work-around I've been reloading vscode. Have you tried that ?

**Comment by deeelan** [comment]
I've been doing some research and its seems to have a problem in sfdx-config.json file, if u change the value with another (even inexistent alias) the options in the context meny appears. This seems a real bug.

**Comment by HernanMorgado** [comment]
My solution for this was change the enviroment variable 'Path'. 

--C:Salesfore path;C:Visual Code path;C:CMD path

Forexample:

--C:\Program Files\Salesforce CLI\bin;C:\Users\herna\AppData\Local\Programs\Microsoft VS Code\bin;C:\Windows\System32;

Before, i wrote this path with "" so i modified this and then appeared the deploy/retrieve/push option.

Please tell me if this information was useful to you :)

**Comment by Patlatus** [comment]
when I recreate a project from scratch it seems the options reappear I have not tried all the options mentioned in these comments

**Comment by Patlatus** [comment]
Yesterday I performed a workshop where I was showing how to migrate from Aura Components to Lightning Web Components. During the workshop I was just doing the same steps that everyone did.
When I forked a project with VSCode configuration setup
https://github.com/bdovhan/SimpleDataTableApp
and opened SimpleDataTable folder in VSCode I wasn't able to use deploy commands. Also creation commands were also missing. We streamlined a video from workshop and we could share those videos shot later.
Also, there are no retrieve commands which is frustrating that I have to go terminal each time and execute either force:source:push or force:source:retrieve -m ApexClass,AuraDefinitionBundle,LightningComponentBundle each time when I need to pull metadata from scratch org. However, push command doesn't seem to work correctly each time, but retrieve command works as I need.
When I recreated a project using Project Create command in VSCode, it seemed to bring back creation commands but not the deployment commands. I hope that https://github.com/forcedotcom/salesforcedx-vscode/pull/1327 pull request will solve at least the problems with deployment commands missing.

**Comment by NDaves** [comment]
Facing the same issue!!

Was able to **Deploy** and **Retrieve** from Visual Studio Code till yesterday. Today after updating the VS code, SFDX has gone from my SFDC project.

Tried all above options but still could not get SFDX options back. I have uncommitted changes in this project and want to deploy it but not sure what should I do not.

I could see my my project alias as _defaultusername_ listed if I execute _sfdx force:config:list_ and connected status as _Connected_ in _sfdx force:org:display_ command output

**Comment by lcampos** [comment]
This issue is exclusive to when scratch orgs are created or new orgs get authenticated. The root cause is a race condition between the extension and the cli, where the extension queries the cli for some auth information and the cli is still not done with the previous create org execution.

PR #1327 will only address the scenario described above, but I think people here might be running into a second issue. @Patlatus and @NDaves can you confirm you do not see an activation error by opening VSCode's Dev Tools (Help > Toggle Developer Tools) and looking at the console tab ? You should see some log lines like the ones on the following screenshot:

<img width="709" alt="Screen Shot 2019-05-13 at 8 15 01 AM" src="https://user-images.githubusercontent.com/1041842/57632851-53cc1900-7557-11e9-8c14-3c0cada23fe8.png">

**Comment by Patlatus** [comment]
I can provide a live session video where I was not able to use Deploy commands but I used workaround (I have executed manually sfdx force:source:deploy -m ApexClass,AuraDefinitionBundle,LightningComponentBundle commands from terminal) https://www.youtube.com/watch?v=TWSm6HBcQtY

@lcampos I am not sure about the question you have, I have never tried to open VSCode's Dev Tools (Help > Toggle Developer Tools) and I am even not sure if I have those tools installed

**Comment by Patlatus** [comment]
@lcampos Ok, I have tried that and I do see "Cannot find en-us, defaulting to en" message, does that mean that this will be fixed by your pull request or is this some different problem which will not be fixed by your pull request?
![image](https://user-images.githubusercontent.com/1489026/57681130-cca2a200-7637-11e9-9556-5fa959225bc0.png)

**Comment by lcampos** [comment]
@Patlatus you can ignore that error about `en-us` but the error above that one tells me you did not configure Java for the apex extension (unrelated to the commands & context issue in this thread). You can get that fixed by following the instructions in [Set Your Java Version](https://forcedotcom.github.io/salesforcedx-vscode/articles/troubleshooting.html#set-your-java-version).

Also, in the bottom-right corner I see you have 2 unread notifications (click the bell icon and you'll be able to see them). Can you tell me what those are for ?

Btw, VSCode's Dev Tools is not something you install, it comes as part of normal VSCode. This is similar to your browser's Dev Tools since VSCode is just an app that runs on top of a chromium browser (Electron).

**Comment by HernanMorgado** [comment]
I´m not sure because you are in Mac but in windows i had to configure my environment variables (JAVA_HOME and JDK_HOME) for connect vscode with java. @lcampos show you how you can configure this.

**Comment by Patlatus** [comment]
@lcampos actually I don't care about any errors there except there are some which influence inability to retrieve or deploy source, are any of these errors related to inability to deploy or retrieve?

**Comment by lcampos** [comment]
@Patlatus no

**Comment by lcampos** [comment]
Closing this since the fix is out as part of version `45.15.0` of the extensions.

**Comment by Patlatus** [comment]
@lcampos  do you say retrieve and deploy options should be restored after upgrading to version 45.15.0? How do I upgrade my Salesforce Extension Pack to 45.15.0? How do I know what is the current version of my Salesforce Extension Pack ?

**Comment by deeelan** [comment]
@Patlatus always disappear when update VSCode, I usually don't update VSCode cuz of this (oc when this options show up)

**Comment by miteshmsharma** [comment]
I am experienceing the similar issue even when I am following along the trailhead - see the SFDX commands from Default > Right Click

![image](https://user-images.githubusercontent.com/6457976/64064927-306fcb80-cc25-11e9-9022-ec5e6a8e7a91.png)


 but the same is missing from my VS code

![image](https://user-images.githubusercontent.com/6457976/64064916-10400c80-cc25-11e9-92a1-5aeb23c3a0ae.png)

I updated VSCODE with latest July 19 version and I am running windows OS. This is very rudimentary and needs to be present

**Comment by rkozlin** [comment]
Why did you close this obvious and very easily reproducible bug?  
Right click options are NOT present when you re-open VS Code and open the WS folder again. 
Originally I did the SFDX Create w/ Manifest command to pull a dev sandbox's code/config down.  Everything worked fine.  Right click options etc. 
But then close VS Code and open it again, and open the WS folder again. No right click options.

**Comment by victorng8** [comment]
@Patlatus  Click the Gear icon in "Salesforce Extension pack" - > Install Another Version.. 45.15.0
@lcampos As of today, 45.15.0 and even the latest 47.9.0 cannot work. Please reopen case?

<img width="889" alt="Screenshot_1" src="https://user-images.githubusercontent.com/1401896/70598075-f8652500-1c24-11ea-8577-5981e9b3f913.png">

**Comment by nigelhughesfairsailcom** [comment]
I agree with @victorng8  & @rkozlin this is not fixed.

**Comment by victorng8** [comment]
I posted a question related to this and it got fixed @nigelhughesfairsailcom.
You can refer to this post https://github.com/forcedotcom/salesforcedx-vscode/issues/1840.
As of now the latest version 47.10.0 and later versions are working.

**Comment by nigelhughesfairsailcom** [comment]
> I posted a question related to this and it got fixed @nigelhughesfairsailcom.
> You can refer to this post #1840.
> As of now the latest version 47.10.0 and later versions are working.

@victorng8  I have v47.15 installed and still have missing context options.

**Comment by vc4u** [comment]
Using v48.7.0 and it is not working for me either. None of the SFDX Context Menu options are showing. Is there a workaround to make them reload?

**Comment by amil-abdallah** [comment]
@vc4u Are you attempting to deploy to a scratch org? I have found a work around that works for me.  Do a new SFDX: Authorize Org and make sure to select the Test.Salesforce.Login url.  Provide the credentials for your scratch org you want to develop against.  Make sure the project is using the new auth you setup and you should be able to right click on items and see the deploy/retrieve options.

**Comment by saramorgan** [comment]
I am getting this issue in 2020 and have done everything, including re-loading VS Code, updating to the latest extension version, etc. I can see the context for creating a class, or an LWC, but not an Aura component. Is this just because you all at Salesforce have really written off Aura components. I am beginning to strongly sense that this is the case. All you care about is LWC, but your customers are still needing to create Aura components. This really needs to be resolved.

**Comment by smaddox-sf** [comment]
Hi @saramorgan - Thanks for reaching out.  Can you please open a new issue with the details of what you're seeing so we can investigate?   I assure you we still have plenty of love for Aura!

(btw, we often don't see comments on closed issues, so a new issue is best to ensure it's seen.)
