### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by utkarshugale** [forcedotcom/salesforcedx-vscode#1199]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.7.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/utkarshugale/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@utkarshugale Can you share more information on what operation you were performing when you observed the high cpu load? Does it happen during installation, similar to: https://github.com/forcedotcom/salesforcedx-vscode/issues/1156
