### ISSUE TITLE
Salesforce DX Issue

### ISSUE THREAD

**Issue by sfdcvenkata2014** [forcedotcom/salesforcedx-vscode#1203]
I am working on the Visual Studio Code IDE with Salesforce DX. 

1. Successfully created a package sfdx force:source:convert --outputdir mdapi_output_dir --packagename managed_pkg_name

2. Now I am trying to deploy in the needed ORG with this command
sfdx force:mdapi:deploy --deploydir mdapi_output_dir --targetusername me@example.com

getting the below errors

Error  mdapi_output_dir/package.xml  package.xml  You cannot install or upgrade a package that has a NetworkBranding component. remove 
components of NetworkBranding type from the package.

Error  mdapi_output_dir/package.xml  package.xml  You cannot install or upgrade a package that has a Network component. Remove
components of Network type from the package.

Error  mdapi_output_dir/package.xml  package.xml  You cannot install or upgrade a package that has a SiteDotCom component. Remove
components of SiteDotCom type from the package.

Error  mdapi_output_dir/package.xml  package.xml  You cannot install or upgrade a package that has a CustomSite component. Remove
components of CustomSite type from the package.

But I want to deploy my package along with NetworkBranding, Network,  SiteDotCom, and CustomSite.

Your help would be really appreciated.

**Comment by mnunezdm** [comment]
Hi, this problem seems to be more related to Salesforce Limitation than to the plugin, validate if you have this same issue when trying to deploy it without sfdx, for example ant migration tool or workbench, the result should be the same.

Maybe you have to delete the package (in a predestructive, with all its dependencies) and then deploy it. Try with a check only deploy

**Comment by sfdcvenkata2014** [comment]
Hi, i have deleted the package, recreated the package and deployed it. It is giving me the same error and even for Profiles i am not able to deploy. Please do suggest.

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via GitHub issues. Please post your question on the [Trailblazer Community](https://success.salesforce.com), [Stackoverflow](https://salesforce.stackexchange.com/), or through other official support channels.
