### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lposen** [forcedotcom/salesforcedx-vscode#1206]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/3020612/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `45.8.0`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.32.3`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@lposen Can you share more information on what operation you were performing when you observed the high cpu load? Does it happen during installation, similar to: #1156
