### ISSUE TITLE
Can't start debug of Extensions

### ISSUE THREAD

**Issue by abivelj** [forcedotcom/salesforcedx-vscode#1207]
### Summary

I'm trying to add to the project, but when trying to debug I cannot get the "salesforce.salesforcedx-vscode-apex" extensions to run.

In the output console I get this message:
ERROR: The process "12296" not found.

In the debug console I get this:
Cannot find en-us, defaulting to en
Cannot find en-us, defaulting to en
Application Directory:  c:\Users\abive\AppData\Local\Programs\Microsoft VS Code\resources\app\out
Application Main CSS:  c:\Users\abive\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css
%c Quokka.js Live Share integration disabled, VSLS not found. color: darkgreen
SFDX CLI Extension Activated
Cannot find en-us, defaulting to en
Cannot find en-us, defaulting to en
Aura Components Extension Activated
Activating extension 'salesforce.salesforcedx-vscode-apex' failed: undefined.
Activating extension `salesforce.salesforcedx-vscode-apex` failed:  undefined
Here is the error stack:  undefined
Cannot activate extension 'Apex Interactive Debugger' because it depends on extension 'salesforce.salesforcedx-vscode-apex', which failed to activate.
Cannot activate extension 'Apex Replay Debugger' because it depends on extension 'salesforce.salesforcedx-vscode-apex', which failed to activate.

### Steps To Reproduce:

1.  Start the "Launch Extensions" debug.

**VS Code Version: 1.32.3**:

**Latest development version of SFDX**:

**Windows 10: Windows_NT x64 10.0.17134**:

**Comment by abivelj** [comment]
Any help would be great.

**Comment by lcampos** [comment]
Hi @abivelj , are you following the steps on our [Developing](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/contributing/developing.md) guide ? If you are, one thing that could be causing the `salesforcedx-vscode-apex` extension to fail to activate is a misconfigured Java version. You can follow our [Set Your Java Version](https://forcedotcom.github.io/salesforcedx-vscode/articles/troubleshooting#set-your-java-version) for that.

Let me know if you're still blocked after going through those links.

**Comment by abivelj** [comment]
Thank you. I don't think I found that guide.

**Comment by ntotten** [comment]
Great, let us know if you still can’t get it working.
