### ISSUE TITLE
Aura Components extension is overwriting .vscode/settings.json

### ISSUE THREAD

**Issue by aheber** [forcedotcom/salesforcedx-vscode#1210]
### Summary

It seems that since yesterday's update the Aura Components plugin is overwriting the [[projectroot]]/.vscode/settings.json file with the following:
```
{
    "html.suggest.angular1": false,
    "html.suggest.ionic": false,
}
```
Maybe limited to my project only, I don't know.

### Steps To Reproduce:

1. Have a basic settings.json file already configured:
```
{
    "npm.enableScriptExplorer": true
}
```
2. With the Aura Components plugin installed, reload the vscode window
settings.json is rewritten to:
```
{
    "html.suggest.angular1": false,
    "html.suggest.ionic": false
}
```

### Expected result

It is OK to add things to the settings.json, I should not however lose existing setting values.

### Actual result

All of my existing project settings are lost and replaced. This file is tracked in source control so I was able to recover it but it is still being overwritten every time I restart.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.32.3 (user setup)
**SFDX CLI Version**:
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.8.1 (core)
├─ force-language-services 45.9.0 (core)
└─ salesforce-alm 45.10.0 (core)

sfdx-cli 7.1.3 (core)

**OS and version**:
Windows 10

**Comment by ntotten** [comment]
Fix has been checked in and will go out next week.

**Comment by AndrewRayCode** [comment]
It looks like you've overwritten my local vscode settings in every single project I've worked on. These files aren't version controlled obviously because they're local to me and the project and shouldn't be shared.

How do I get these files back? I had a lot of per-project settings that are now lost.

I've reported this extension so hopefully it gets taken down ASAP

**Comment by ntotten** [comment]
@AndrewRayCode I apologize for the problem this has caused. This was a bug and a mistake on our part. We have updated the extension and the fix will go out in a few days.

As far as restoring the file, I am not really sure. Without knowing what OS you are on or your system set up its hard to recommend an option. If you have backup software you may be able to use that.

**Comment by ntotten** [comment]
We published a prioritized release today that fixes this issue. Update to version `45.10.0`. I apologize for any issues this caused. We are doing a retro to try to ensure this sort of issue doesn't happen again.
