### ISSUE TITLE
Unable to install the Salesforce Extension Pack in Visual Studio Code latest version. Please help below are the screenshots

### ISSUE THREAD

**Issue by pkbiradar** [forcedotcom/salesforcedx-vscode#1213]
This is the error when I try to install the pack from the Marketplace:
![image](https://user-images.githubusercontent.com/49105554/55281362-554fd200-5359-11e9-988c-eb812b2b07b1.png)

Later I tried to install through the Manual process then I got the below error: 
![image](https://user-images.githubusercontent.com/49105554/55281364-67317500-5359-11e9-91d8-bbad94c1496b.png)

Kindly help, I am stuck in this and I tried reinstalling the VS Code multiple times. but didn't get any luck in that. Thanks alot in advance.

**Comment by ntotten** [comment]
Can you tell me if you are still seeing this issue on the release from this week? If so can, you please provide more details. What OS are you on, what version of vs code, etc.

**Comment by Gothiname** [comment]
duplicates from a previous closed issue #1043

**Comment by lcampos** [comment]
@pkbiradar is this still happening with release `45.9.0` of the extensions ? If so, could you try downloading the extensions directly from the marketplace and checking if SHA for the files is correct ? Instructions on how to do that can be found in our [SHA256](https://github.com/forcedotcom/salesforcedx-vscode/blob/afdb1785e10fdf683893a21e7e1e73e4ea15ef78/SHA256.md) doc.

**Comment by pkbiradar** [comment]
Hi All, post update its working now. Thanks alot for the support.

**Comment by herkura** [comment]
Hi there! I am also unable to install the salesforce extension pack on vs code.
It is showing the following error: **Error: Corrupt ZIP: end of central directory record signature not found**
Kindly help me here!!
Thanks Alot :)

**Comment by herkura** [comment]
My os: Windows 11
Vs Code Version : 1.65.0
