### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by suseenthiran** [forcedotcom/salesforcedx-vscode#1215]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.8.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\suseenthiran\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #1149
