### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [forcedotcom/salesforcedx-vscode#1217]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.8.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/sc/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #1149
