### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AkshayAry** [forcedotcom/salesforcedx-vscode#1220]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.8.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\UX012393\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by AkshayAry** [comment]
Please solve my issue

**Comment by lcampos** [comment]
Hi @AkshayAry, can you attach the log file to this thread so we can see what caused the issue. Also, can you confirm your setup meets the suggested requirements for running vscode https://code.visualstudio.com/docs/supporting/requirements.
