### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by robertwynter** [forcedotcom/salesforcedx-vscode#1226]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.8.0`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\100508468\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@robertwynter Can you please share more context on what operation you were performing when you observed the high CPU load?

**Comment by robertwynter** [comment]
I no longer have that issue. But my VS code Apex replayer no longer steps through the class file code not even setting a breakpoint works. I'v tried uninstalling VS code, deleting the .vscode extensions, even deleting vs code within Regedit. When I reinstall VS code it still remembers all my previous settings including the last file i had open

**Comment by praksb** [comment]
@robertwynter I am closing this issue then. Can you please open a new issue for the debugging problem that you are seeing?
