### ISSUE TITLE
Allow selection of multiple files/folders on Deploy/Retrieve source

### ISSUE THREAD

**Issue by ddodson3** [forcedotcom/salesforcedx-vscode#1228]
### Summary
If I select multiple files and right click>Deploy Source to org or Retrieve source from org, it only deploys the file that I right clicked on and not all files that were selected. 

The command output shows only one file that it is trying to source:deploy, so I think it is possibly an extension issue. 

### Steps To Reproduce:
1. Connect to sandbox 
2. Select two files using control click or shift click
3. Right click and select "deploy source to org" or "retrieve source from org" 

### Expected result
Both files are deployed/retrieved

### Actual result
Only the file that is right clicked on is retrieved

### Additional information
It seems like there is a multiple file command for at least the deploy part (sfdx.force.source.deploy.multiple.source.paths) but it isn't mapped to a right click action

**VS Code Version**: 1.32.3
**SFDX CLI Version**: 7.1.4-79f97a7df8
**OS and version**: Windows 10 1803

**Comment by ntotten** [comment]
Related to #862

**Comment by nomrik** [comment]
@ntotten Is there any update on that? I looked in #862 and it doesn't seem to be resolving this issue, which is critical in situations of multiple dependencies between components.

**Comment by jflowers45** [comment]
I would like to add my voice to those requesting this feature. It's very confusing from a usability perspective that only the right-clicked file is deployed.

**Comment by smaddox-sf** [comment]
Hi @jflowers45 - Thanks for weighing in.  The way we're thinking about solving this is to provide a way to select multiple metadata types or files and generate a manifest from the Org Browser.  This would then allow you to retrieve or deploy with that assortment of items at any time - no need to carefully right-click on them all each time.  (This is a similar concept to the 'working set' that Nate described in #862).  This is a roadmap item and I'd welcome any other feedback on the tentatively-planned approach.

**Comment by msrivastav13** [comment]
@smaddox-sf that would be awesome! It would be more awesome if this is taken care at the CLI via a command where one can pass in all the metadata elements and metadata type.

This way this functionality won’t be tied to this extension pack and org browser only!

Salesforce CLI retrieve command by metadata is great but gets verbose and repetitive as soon as we have more number of components and metadata types.

**Comment by magulan** [comment]
This is a must feature. With Eclipse IDE and Force.com plugin, we were able to achieve this. 
As a workaround, I am adding the components to a new project and deploying the whole project. This might not work for all.

**Comment by acmegx** [comment]
any update on this issue / feature request? Conscious that this has been raised almost 2.5 years ago...

**Comment by smaddox-sf** [comment]
Hi @acmegx - We're researching this feature to see if a VS Code bug that was stopping us has been resolved.  If it has, we'll be able to deliver this feature.

**Comment by randi274** [comment]
Hello! I noticed this open issue today, and recalled that it was actually delivered last fall with #3621 - give it a try and let us know what you think!

**Comment by adamc-skedulo** [comment]
Just tried this - and it works as expected! This will be very helpful.

But, I didn't find this ticket until I'd finished deploying a load of files.
The solution I used was to make a new package xml file in the manifest folder, with just the files to deploy, so the file can be right clicked and 'Deploy files in Manifest' used.
While it takes longer to create, it's useful when there are lots of files across different folders, where Ctrl clicking can get a bit unreliable (if one file is clicked without Ctrl/Cmd...) and it's repeatable. It could also be used while working on a ticket/project - add a new file to the XML each time you save a new file, and the whole project can be redeployed quite easily.

Hope this is useful to anyone who finds this ticket!
