### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mctufftuff** [forcedotcom/salesforcedx-vscode#1229]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.8.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\EDelorio\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mctufftuff** [comment]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/3040848/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by praksb** [comment]
@mctufftuff Can you please let us know what operation you were performing when you observed this issue? Does the CPU usage come down after a while if you observed this when you were loading a project?
