### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by davecastaneda** [forcedotcom/salesforcedx-vscode#1233]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.9.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/davidcastaneda/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@davecastaneda Can you please share more information on what operation you were performing when you observed the high cpu load?
