### ISSUE TITLE
Apex Replay will not step through class

### ISSUE THREAD

**Issue by robertwynter** [forcedotcom/salesforcedx-vscode#1238]
my VS code Apex replayer no longer steps through the class file code not even setting a breakpoint works. it just steps through the debug log instead I'v tried uninstalling VS code, deleting the .vscode extensions, even deleting vs code within Regedit. When I reinstall VS code it still remembers all my previous settings including the last file I had opened

**Comment by ntotten** [comment]
Please provide more details about your system. Which OS version, which version of vscode, etc.
