### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gdmccarty** [forcedotcom/salesforcedx-vscode#1239]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.9.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\greg\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@gdmccarty Can you share more information on what operation you were performing when you observed the high cpu load?

**Comment by gdmccarty** [comment]
I had uninstalled the sfdx plug in, and was reinstalling it in order to get the web components part.

GregM

GregM

________________________________

**Comment by smaddox-sf** [comment]
Duplicate #1149
