### ISSUE TITLE
Lightning Explorer has inconsistent open behavior

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1244]
The Lightning Explorer opens Aura files in the `cmp` and LWC files in the `js` files. While this is maybe correct - in that these files are the "main" files for each framework, the inconsistent behavior is weird.

We should default to the HTML file (`cmp`, `html`) in both cases.

**Comment by lcampos** [comment]
Closing since Lightning Explorer was deprecated/removed
