### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by adwonnacott** [forcedotcom/salesforcedx-vscode#1258]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.10.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\adam_\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
@adwonnacott Could you attach the file referenced above so we can debug.
