### ISSUE TITLE
Unable to Retrieve Code Coverage for Apex Tests

### ISSUE THREAD

**Issue by dfully0814** [forcedotcom/salesforcedx-vscode#1262]
### Summary

Per the features listed https://forcedotcom.github.io/salesforcedx-vscode/articles/apex/testing, I'm having trouble viewing test code coverage in vs code for apex classes. When I run an apex test via any means in vs code, and attempt to view the test code coverage for the apex class related to that apex test, I'm both not able to see the class in the output terminal and I receive an error when I click the "Highlight Apex Code Coverage" button in the task bar.

### Steps To Reproduce:

1. Set "salesforcedx-vscode-core.retrieve-test-code-coverage" to 'true' in vscode > settings.json.
1. Open list of apex test classes in the sidebar and run apex test from the side, invoke apex test from the command palette, or run all tests from the link inside the apex test class, invoke apext test from the command palette, or run apex tests from the link inside the apex test class.
1.  View the output for the test class run and also click the "Highligh Apex Code Coverage" button in the vs code task bar.

### Expected result

For the output in the terminal, the relevant apex class should display. I see several apex classes listed, but it appears not all of them from the org are listed with coverage. I've tried refreshing object definitions for this and that hasn't resolved the issue.

Clicking the "Highlight Apex Code Coverage" button should highlight all covered and uncovered lines in the apex class currently selected in the active vs code tab.

### Actual result

The apex class is not listed with coverage in the terminal output after running the test class, along with many other apex classes that are missing.

When clicking the highlight button, I receive the following error message

![Screen Shot 2019-04-15 at 10 10 27 AM](https://user-images.githubusercontent.com/16870544/56140211-7541e100-5f68-11e9-9d9f-63615c3841d5.png)

### Additional information

I have also tried deleting my project completely and re-creating a new one, but this has not solved the issue either.

**VS Code Version**: 1.33.1

**SFDX CLI Version**: 7.3.0-94ecf2d5ee darwin-x64 node-v10.15.3

**OS and version**: OSX High Sierra 10.13.6

**Comment by lcampos** [comment]
Hi @dfully0814 can you confirm that the Apex tests you are running do provide code coverage for the Apex class you are expecting the highlighting to be present ? You can open the Output view after running your test and scroll to the table that shows the results of code coverage per apex class/trigger (sample below).

If the class/trigger is not part of that table it means the test you are running do not provide coverage for it and get the `Not code coverage information ...` message.

![code_cov_screenshot](https://user-images.githubusercontent.com/1041842/56432851-c5c87f80-6283-11e9-98e1-2cba9d111d7a.png)

**Comment by dfully0814** [comment]
@lcampos The apex classes where I am expecting to see code coverage are also NOT in the output that you mentioned. Shouldn't code coverage be provided for any test class that is run though?

**Comment by dfully0814** [comment]
@lcampos Just wanted to follow up and see if you needed anymore information?

**Comment by lcampos** [comment]
hi @dfully0814 sorry for the late response, I took some days off. Back to your question, the code coverage output results from running one or more tests (code coverage flag enabled) will only include Apex classes/triggers which those tests exercise. If you do not see a class or trigger listed as part of that output it means the test(s) you ran do not cover it.

If you think there is a bug in that output can you provide a code sample so that I can debug in from my side ?

**Comment by lcampos** [comment]
I'm reopening this since it's still not clear this is a bug or not.

**Comment by lcampos** [comment]
@troveryor in your second screenshot where the output from the test run is present, if you scroll up a bit more do you see a line where the apex class/trigger you expect to have code coverage is listed and it includes the coverage percentage and lines that are uncovered ? You can look at the screenshot it this comment to see what I'm talking about https://github.com/forcedotcom/salesforcedx-vscode/issues/1262#issuecomment-484946580

**Comment by dfully0814** [comment]
@lcampos Same issue for me. When I run the test class in VS code, all methods pass and those methods are all calling my Gateway class. I am getting 100% code coverage in Developer Console.
<img width="1341" alt="Screen Shot 2019-05-10 at 2 55 26 PM" src="https://user-images.githubusercontent.com/16870544/57550221-bcd34700-7333-11e9-9e05-f5ff37cd71bc.png">

But when I click to highlight the code coverage in VS code, I'm getting the same error message below that pops up in the lower right corner of the screen:
![56140211-7541e100-5f68-11e9-9d9f-63615c3841d5](https://user-images.githubusercontent.com/16870544/57550281-ee4c1280-7333-11e9-8f1c-9736b4048f89.png)

**Comment by lcampos** [comment]
@dfully0814 did you enabled `"salesforcedx-vscode-core.retrieve-test-code-coverage": true` setting as @troveryor mentioned? That fixed it for him.

**Comment by eadelarosa** [comment]
@dfully0814 - given that after enabling the setting (per @lcampos follow-up question above) and ticking the "Highlight Apex Code Coverage" icon at the "status bar", could you please confirm which Apex class are you inspecting after running the test - is the Test class or the Apex class that your Test class runs against? Note that the highlights appear on the Apex class - not on the Test (Apex) class. I've known a number of people who's been confused by this - including myself in the past.

![Screen Shot 2019-05-15 at 5 16 39 pm](https://user-images.githubusercontent.com/8053470/57755913-69973500-7735-11e9-8f7b-f7186b8ae099.png)

**Comment by troveryor** [comment]
> @troveryor in your second screenshot where the output from the test run is present, if you scroll up a bit more do you see a line where the apex class/trigger you expect to have code coverage is listed and it includes the coverage percentage and lines that are uncovered ? You can look at the screenshot it this comment to see what I'm talking about [#1262 (comment)](https://github.com/forcedotcom/salesforcedx-vscode/issues/1262#issuecomment-484946580)

@lcampos Sorry, I should have included that section. At that time, with something wonky with my workspace settings I think, I was not getting any coverage information even in the Output tab. Once I got my settings sorted out everything worked as expected, including the line highlighting, so I'm in good shape now.

**Comment by tmays-awh** [comment]
I'm not so sure this is just user error. I have salesforcedx-vscode-core.retrieve-test-code-coverage set and the Highlight Apex Code Coverage on, but in my test-result-codecoverage.json it's just an empty array [] and the output panel shows this...

`Starting Run Apex test(s)

10:45:06.62 sfdx force:apex:test:run --tests UGearsTest --resultformat human --outputdir /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex --loglevel error --codecoverage
=== Test Reports
FORMAT  FILE
──────  ──────────────────────────────────────────────────────────────────────────────────────────────────────
txt     /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex/test-result.txt
txt     /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex/test-run-id.txt
junit   /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex/test-result-707g000002Ba5xz-junit.xml
json    /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex/test-result-707g000002Ba5xz.json
json    /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex/test-result-codecoverage.json

=== Apex Code Coverage
ID  NAME  % COVERED  UNCOVERED LINES
──  ────  ─────────  ───────────────

=== Test Results
TEST NAME                           OUTCOME  MESSAGE  RUNTIME (MS)
──────────────────────────────────  ───────  ───────  ────────────
UGearsTest.additionalNegativeTests  Pass              1274
UGearsTest.testUBoolean             Pass              21
UGearsTest.testUCollection          Pass              1057
UGearsTest.testUDate                Pass              7
UGearsTest.testUDateTime            Pass              6
UGearsTest.testUDebug               Pass              11
UGearsTest.testUHTTP                Pass              8
UGearsTest.testUMessage             Pass              6
UGearsTest.testUSObject             Pass              997
UGearsTest.testUStaticResource      Pass              13
UGearsTest.testUString              Pass              27
UGearsTest.testUUI                  Pass              191
UGearsTest.testUUser                Pass              2088

=== Test Summary
NAME                 VALUE
───────────────────  ───────────────────────────────────────────────
Outcome              Passed
Tests Ran            13
Passing              13
Failing              0
Skipped              0
Pass Rate            100%
Fail Rate            0%
Test Start Time      May 30, 2019 10:45 AM
Test Execution Time  5706 ms
Test Total Time      5706 ms
Command Time         21178 ms
Hostname             myhostname
Org Id               myorgid
Username             myusername
Test Run Id          707g000002Ba5xz
User Id             myuserid
Test Run Coverage    NaN%
Org Wide Coverage    69%

10:45:29.743 sfdx force:apex:test:run --tests UGearsTest --resultformat human --outputdir /Users/tmays/workspace/hastings-uat/.sfdx/tools/testresults/apex --loglevel error --codecoverage ended with exit code 0
`
Notice the === Apex Code Coverage header is printed but coverage data. Also notice in the Test Summary Test Run Coverage is not a number (NaN%)

whats up with that?

**Comment by tmays-awh** [comment]
ok, it is user error. Store Only Aggregated Code Coverage was checked off in the Apex Test Execution Options.
![Screen Shot 2019-05-30 at 11 07 27 AM](https://user-images.githubusercontent.com/42419723/58642571-9ddd2a80-82cb-11e9-8fd1-278cc7697a65.png)

**Comment by khmerforce** [comment]
@tmays-awh how do you enabled salesforcedx-vscode-core.retrieve-test-code-coverage?

**Comment by khmerforce** [comment]
@tmays-awh I did everything but it's not working for me...

**Comment by leehildebrand** [comment]
@lcampos newbie question, but where am I supposed to set "salesforcedx-vscode-core.retrieve-test-code-coverage": true? How do I get to the correct file in VS Code to enter that?

**Comment by leehildebrand** [comment]
@lcampos disregard. For anyone else searching Code->Preferences->Settings then paste "salesforcedx-vscode-core.retrieve-test-code-coverage" into search bar.

**Comment by rodrigoEclipsa** [comment]
I have a case where I receive coverage information for all classes except one, I am sure it runs because in the salesforce console if it shows coverage. This class seems to have nothing different from the others, it has the same name as the test class but without the _test. Any ideas that can be?

**Comment by sfdxlwcSs** [comment]
I am new here i have tried everything but i am not able to get code coverage information.
I always get the above error.

{
  "salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true,
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.sfdx": true
  },
  "eslint.nodePath": "c:\\Users\\SFDCL\\.vscode\\extensions\\salesforce.salesforcedx-vscode-lwc-46.16.0\\node_modules",
  "editor.formatOnSave": true,
  "salesforcedx-vscode-apex.enable-sobject-refresh-on-startup": true,
  "salesforcedx-vscode-core.retrieve-test-code-coverage": true,
  "salesforcedx-vscode-apex.java.home": "/Program Files/Java/jdk"
}
est Summary
NAME                 VALUE
───────────────────  ─────────────────────────────────────────────
Outcome              Passed
Tests Ran            2
Passing              2
Failing              0
Skipped              0
Pass Rate            100%
Fail Rate            0%
Test Start Time      Sep 26, 2019 10:34 PM
Test Execution Time  9272 ms
Test Total Time      9272 ms
Command Time         217031 ms
Hostname            
Org Id               
Username            
Test Run Id          7073F00000jeGvE
User Id              
Test Run Coverage    NaN%
Org Wide Coverage    51%
No code coverage information was found for this file. Set "salesforcedx-vscode-core.retrieve-test-code-coverage": true in your user or workspace settings. Then, run Apex tests that include methods in this file. You can run tests from the Apex Tests sidebar or using the Run Tests or Run All Tests code lens within the file.

**Comment by zerkz** [comment]
For those having issues still after the suggestions here, try this:
1) Check the aggregate test coverage box shown in the screen shot of this comment, save, and then uncheck it again, save. -- https://github.com/forcedotcom/salesforcedx-vscode/issues/1262#issuecomment-497365510  

2) make sure if you change the file in anyway, deploy it again and run tests. 

After these steps I was finally able to get the visual coverage in VScode. #1 is a very weird case of "turning it off and on again".

**Comment by scromiecaremore** [comment]
Ran into this issue just now and spent a few hours trying to resolve it, eventually thinking it was some WSL thing.  The Apex Test Execution Options (which you can get to by going to Platform Tools --> Custom Code --> Apex Test Execution) need to be adjusted.  Once you go there, click the "Options..." button and it will pull up the window:
![image](https://user-images.githubusercontent.com/48261521/95809762-6a365100-0cc4-11eb-9e53-2a8eb5a59548.png)
#Make Sure that you have that box unchecked.  Specifically this is useful for scratch orgs, because it is a default setting.
