### ISSUE TITLE
Package aliases are considered invalid JSON

### ISSUE THREAD

**Issue by ajw725** [forcedotcom/salesforcedx-vscode#1266]
### Summary

Attempting to create any component (Apex class, Lightning bundle, etc.) fails from the IDE because "all JSON input must have heads down camelcase keys," but the keys it's complaining about are package aliases in sfdx-project.json, which follow the same format as the SF documentation.

Apologies if this is the wrong place for this, but the IDE + extensions are definitely doing something the CLI isn't (see step 3 vs. step 4 below), so I figured I'd start here. If this should be somewhere else, please point me in the right direction.

This is also definitely a new thing, because I've followed these steps at other times in the past few months with no problems.

### Steps To Reproduce:

1. In VS Code, create a new SFDX project
1. From the command line, create a new unlocked package from that project's root directory
    1. `sfdx force:package:create -n TestPackage -t Unlocked -r force-app/`
    1. note that this automatically generates a "packageAliases" entry in sfdx-project.json with the key "TestPackage" (or whatever you called your package)
1. Try to create any component - Apex class, Lightning component, Lightning web component - using the IDE commands from the SF extensions (e.g. "SDFX: Create Lightning Web Component"). You will get an error like the one in the screenshot below complaining about the package alias key.
1. Try to create a component directly from the CLI using the plain CLI command (`sfdx force:lightning:component:create`), and it works as expected.

### Expected result

A component should have been created / no error should occur.

### Actual result

An error occurred because of invalid syntax in the JSON file, even though this syntax is generated automatically by the CLI/IDE and matches the examples in the documentation.

### Additional information

![Screen Shot 2019-04-15 at 3 04 55 PM](https://user-images.githubusercontent.com/2425541/56165352-f365ae00-5f8f-11e9-8d0b-cd793b5c66a7.png)

**VS Code Version**: 1.33.1

**SFDX CLI Version**: sfdx-cli/7.3.0-94ecf2d5ee darwin-x64 node-v10.15.3

**OS and version**: macOS Mojave (10.14.4)

**Comment by lcampos** [comment]
Hi @ajw725, thanks for opening this issue, it's the correct place for it. This is happening because we're using a library that parses `sfdx-project.json` as part of the code used across the commands that create metadata. We're currently looking into it and will have a fix as part of the next release.
In the meantime you can use the cli directly to create the metadata or update the name of the unlocked package.
cc @ntotten

**Comment by ajw725** [comment]
thanks for the info, @lcampos. sounds good.

**Comment by lcampos** [comment]
@ajw725 I'm closing this since the fix is out as part of version `45.12.0` of the extensions. Thanks for opening the issue and let us know if you run into anything else.

**Comment by ajw725** [comment]
will do. thanks!
