### ISSUE TITLE
No Definition Found for "Go to Definition" and "Peek Definition"

### ISSUE THREAD

**Issue by kyong-yu** [forcedotcom/salesforcedx-vscode#1269]
### Summary

Go to definition and Peek definition works occasionally for certain classes and methods. Further investigation seems to point to semantic errors, specifically inline variable casting is not understood when binding methods.

### Steps To Reproduce:

1. Create a method that takes a list of accounts. ex:
![image](https://user-images.githubusercontent.com/45047114/56313677-ff747b80-6107-11e9-97f9-3c2c50ca2f35.png)

1.  Call this method from another class, and bind the type inline.
![image](https://user-images.githubusercontent.com/45047114/56313538-ac9ac400-6107-11e9-9f38-90190509b5d4.png)

1. Right click and select "Go to definition"

### Expected result
Navigation to the class/method

### Actual result
"No definition found for [method]."

### Additional information
Go to definition/peek works when passing in a parameter of the expected type:
![image](https://user-images.githubusercontent.com/45047114/56313622-e075e980-6107-11e9-8b87-f75b385ac68a.png)

**VS Code Version**:
1.33.1 (system setup)

**SFDX CLI Version**:
sfdx-cli/7.3.0-94ecf2d5ee

**OS and version**:
Windows 10

**Comment by praksb** [comment]
@kyong-yu Can you share what the semantic error message is?

**Comment by kyong-yu** [comment]
@praksb Sure thing:
![image](https://user-images.githubusercontent.com/45047114/56322948-45890980-611f-11e9-953e-ded61d2a0c0e.png)

**Comment by praksb** [comment]
@kyong-yu Do you have a user defined Apex class called Account in your project (Account.cls)?

**Comment by kyong-yu** [comment]
@praksb No, I do not. The same error can be reproduced whenever a method accept a generic sobject or collection of generic sobjects, and concrete object(s) are passed in, and vice versa.

**Comment by praksb** [comment]
@kyong-yu Do you get the same semantic error when you do List<Account> lstAcct = lstSObj; ? Also, can you post a screenshot of what happens when you do a GoToDef on Account?

**Comment by kyong-yu** [comment]
yes, same semantic error, see below:
![image](https://user-images.githubusercontent.com/45047114/56339620-daadf180-6163-11e9-8973-f41662690723.png)

See below when I "Go to definition" on account:
![image](https://user-images.githubusercontent.com/45047114/56339724-3b3d2e80-6164-11e9-9d21-779b32bddb8f.png)

**Comment by praksb** [comment]
@kyong-yu Thanks for the screenshot! I wanted to check what happens when you don't have the explicit cast: 

List<Account> lstAcct = lstSObj; 


Also, does the error go away if you change "Account" to "Schema.Account" i.e. if you have 

List<Schema.Account> lstAccount = (List<Schema.Account>)lstObj  

This would help me understand and debug this issue since I am not able to repro this on my end.
Thank you!

**Comment by kyong-yu** [comment]
@praksb wow, that is so weird..it happens very consistently on my end. 
here are some more SS's (without explicit cast):
![image](https://user-images.githubusercontent.com/45047114/56340183-ff0acd80-6165-11e9-8207-a0a42a0e8b74.png)

SS of "List<Schema.Account> lstAccount = (List<Schema.Account>)lstObj" (note, go to definition does not work in this case): 
![image](https://user-images.githubusercontent.com/45047114/56340243-37121080-6166-11e9-8891-875471e82d46.png)

**Comment by praksb** [comment]
@kyong-yu Thanks for the screen shots it is useful in trying to understand the issue. This does look like some weird bug with respect to SObject binding since it doesn't repro for me. I'll debug and see how we could end up in this state. 

One more thing in the above screenshot, you said go-to-def on the method didn't work, can you tell if you also changed the parameter type for GotoRepro.test method to List< Schema.Account > instead of List< Account >

**Comment by kyong-yu** [comment]
@praksb no problem, here is the requested SS (go to definition does not work):
![image](https://user-images.githubusercontent.com/45047114/56341233-3a5acb80-6169-11e9-974d-eb8183de59b9.png)

**Comment by praksb** [comment]
@kyong-yu I have a repro now. It is a bug specific to Windows. I have identified the problem and working on a fix. Thanks for filing this!

**Comment by kyong-yu** [comment]
Awesome, looking forward to the fix!!
