### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by seregaone** [forcedotcom/salesforcedx-vscode#1270]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.10.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Сергей\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@seregaone Can you please share what operation you were performing when you observed the high CPU load?
