### ISSUE TITLE
Lightning Explorer Should not load on non-lightning/salesforce projects

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1271]
### Summary
The lightning explorer tab shows up even on non-lightning projects. 

### Steps To Reproduce:

1.  Open any non-salesforce project in vscode
1.  See lightning explorer tab

![image](https://user-images.githubusercontent.com/282782/56472913-6b612780-6419-11e9-92bc-b25ec37edea3.png)

### Expected result

Lightning explorer should detect when the project is a Salesforce project and only load in that case. All other types of projects should not see the tab.

### Actual result

Tab is displayed

**Comment by lcampos** [comment]
Closing since this was addressed by PR #2070 that was part of release 48.6.0.
