### ISSUE TITLE
Missing Deploy/Retrieve options in context menu

### ISSUE THREAD

**Issue by deeelan** [forcedotcom/salesforcedx-vscode#1274]
### Summary

Missing Deploy/Retrieve options in context menu after update of VSCode or create a new Scratch Org from console

### Steps To Reproduce:

1.  Update VSCode

or

1.  Create a new scratch from console

### Expected result

The options Deploy/Retrieve from source should be on the context menu

### Actual result

Dissapear the options on the context menu, Not showing this options

### Additional information

![image](https://user-images.githubusercontent.com/27895957/56514893-1e09b680-64fc-11e9-9323-c3c9223f55f6.png)

**VS Code Version**: 1.33.1

**SFDX CLI Version**: sfdx-cli/6.52.2-c6cdc99881 (windows-x86) node-v8.9.4

**OS and version**: Windows_NT x64 10.0.17134 and Mac OS High Sierra

**Comment by ntotten** [comment]
What happens if you close and reopen the project? Also, can you provide us with the extension host log output? To see the logs use: cmd-shift-p -> Search Show Logs -> Extension Host
