### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by Itsmejyoti** [forcedotcom/salesforcedx-vscode#1278]
Issue Type: <b>Bug</b>

When trying to create project gives an error command 'sfdx.force.project.create' not found.

Extension version: 45.10.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1795)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|1.89GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by lcampos** [comment]
Hi @Itsmejyoti can you open Dev tools (Help > Toggle Dev Tools) and see if there's an error under the Console tab? If so, can you add a screenshot of it.
Also, can you provide the version of the Salesforce CLI you are using ( run `sfdx --version` in your terminal) ?

**Comment by Itsmejyoti** [comment]
Hey @icampos Thank you for your prompt response, but I have solved the issue there is problem with workspace directory path.

**Comment by lcampos** [comment]
@Itsmejyoti could you add more details on how you fixed this ? I'd like to know if there's something we can change in the extensions so that other users to run into this in the future.

**Comment by Itsmejyoti** [comment]
@icampos I don't know how but I have just changed my workplace folder and its worked for me.
Is there anything which relates Salesforce extension pack and workplace folder? cz I am new to Visual Studio Code and SFDX.

**Comment by lcampos** [comment]
I see, I don't think there's much we can do in that scenario. The extensions only get activated when you are on a Salesforce DX project (e.g. it contains sfdx-project.json, etc) which means that the commands are only available once the extensions activate.

I'll close the issue for now since you are unblocked but feel free to keep providing us with feedback.
