### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sravanisfdcdev** [forcedotcom/salesforcedx-vscode#1286]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.10.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Gangadhar\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@sravanisfdcdev Can you please provide more information on what operation you were performing when you observed this issue? Does the CPU load come down after sometime or does it continue to stay high?

**Comment by sravanisfdcdev** [comment]
Hi,

When I am inserting SFDC extension, SFDC CLI integration shows installing
and then discarded. I am not to deploy project to org also

Regards
Sravani Dasari

**Comment by praksb** [comment]
@sravanisfdcdev Have you installed the CLI on your machine? This is separate from the extension installation. You can install the CLI from here: https://developer.salesforce.com/tools/sfdxcli

**Comment by sravanisfdcdev** [comment]
Yes I have installed.

**Comment by praksb** [comment]
@sravanisfdcdev what error do you get when you attempt to deploy project to org?

**Comment by sravanisfdcdev** [comment]
It's not showing any error code,  "Failed to deploy because of fatal error"
is occurring.

Regards
Sravani Dasari

**Comment by praksb** [comment]
@sravanisfdcdev In the VS Code menu bar can you select Help > Toggle Developer Tools, click Console and post any errors that you see?

**Comment by sravanisfdcdev** [comment]
Hi Team,

I am not to raise a case with Salesforce to get support on below issue:
 LWC navigation button/url not working in communities page.

 Could you please help me on this.

Regards
Sravani Dasari

**Comment by praksb** [comment]
Please use https://help.salesforce.com/login to log support questions.
