### ISSUE TITLE
Reduce steps require to Launch Log-Replay Debugger from Tests & Anonymous apex

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#1291]
**Is your feature request related to a problem? Please describe.**
Right now the current process of running the debugger is a bit tedious.  

_Current Steps:_
1. Open file
2. Set breakpoint
3. `>Turn on Apex Debug Log for Replay Debugger`
4. Run Test or Anonymous apex
5. `> Get Apex Debug Logs`
6. `Select Log`
7. `> Launch Apex Replay debugger with last log file`

**Describe the solution you'd like**

_Ideal Steps_

1. Open file
2. Set breakpoint
3. `Debug Test` or `Debug Apex`

However, I understand that the LOE is high and the value is low (relative to other work that needs to be done).

I wonder if there isn't a compromise that could be implemented with less effort.  For example,  if `Launch Apex Replay debugger with last log file` actually got the last log from the server, downloaded it and started the debugger that would make the process much smoother:

_Compromised solution:_
1. Open file
2. Set breakpoint
4. Run Test or Anonymous apex
3. `> Launch Apex Replay debugger with last log (server)`

Another potential solution would be to implement a feature where logs would automatically be downloaded (mm used to do this, but never well IMO).  This would be more work, but has additional value outside of the debugger...

**Comment by johnhutchins** [comment]
As a developer in training, streamlining the process from writing to debugging code would be a great benefit. I've found that I learn a tremendous amount from stepping through the code and if it was simpler to do this I would have been able to understand a few key concepts more quickly. I hope to see this change!

**Comment by ntotten** [comment]
Related to #946

**Comment by randi274** [comment]
@ChuckJonas update on this - we now enable single-button replay debugging with the 'Debug Test' codelens + debug button for test files. We also allow you to execute code using anonymous apex with the new command `SFDX: Launch Apex Replay Debugger with Current File` (available on right-click in the anon file or in the command palette). We still allow for the manual steps you listed here for more advanced debugging use cases, but this is something we've improved a lot recently, so I'm going to close this one as delivered. Feel free to let us know if you have any additional feedback on this one!

<img width="804" alt="Screen Shot 2022-04-14 at 1 41 36 PM" src="https://user-images.githubusercontent.com/9795193/163444298-5d3f41a2-86e0-4247-ba1b-326df1e623dd.png">
