### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#1292]
**Is your feature request related to a problem? Please describe.**
It's currently very difficult to keep up with what changes have been made to this extension

**Describe the solution you'd like**

[Keep a Changelog](https://keepachangelog.com/en/1.0.0/).  Ideally it would be at the top level so that you could quickly catch up on all the updates in one place

**Describe alternatives you've considered**
Right now to get up to date I have to do the following:

1: Go to releases
2: figure out which releases are new
3: one by one, click into the release and then look at the individual commits

**Comment by ChuckJonas** [comment]
... ya nvm you guys already have one https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode/CHANGELOG.md

duh

**Comment by ntotten** [comment]
@lcampos Can we move the changelog to the top level? This isnt the first time I have been asked about this.

**Comment by ChuckJonas** [comment]
I'm guessing it might be where it is so that the vscode extension marketplace will pick it up?  Could maybe just put a link in the readme?

**Comment by ntotten** [comment]
Ah yeah, you are right. but we should be able to copy it as a pre-publish step.
