### ISSUE TITLE
Purpose of SFDX_SET_CLIENT_IDS:sfdx-vscode

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#1295]
Could someone explain (briefly) what this setting is used for?

**Comment by lcampos** [comment]
@ChuckJonas before the extensions had it's own telemetry service, we used to rely on the cli reporting errors happening in vscode. We retired the use of `SFDX_SET_CLIENT_IDS` in version `45.5.0` (https://github.com/forcedotcom/salesforcedx-vscode/pull/1062) so if you still see it in your project's settings you can remove it. Having it in your project's settings just means you created that project with a version of the extensions prior to `45.5.0`.

I'm closing this issue but feel free to reopen it if needed.
