### ISSUE TITLE
Request: Add __test__ folder and files when a LWC is created 

### ISSUE THREAD

**Issue by jeffb-sfdc** [forcedotcom/salesforcedx-vscode#1300]
In VS Code, when I run the "sfdx: create lightning web component" command, it would be nice if a _ _ tests _ _ directory and a _ _ tests _ _/{name of component}.tests.js file are also generated.

For the generated test file, a blank file would be OK, but even better if there was boiler-plate code, something like:

`import MyComponent from 'c/myComponent';
import { createElement } from 'lwc';

describe('c-my-component', () => {
  beforeEach(() => {
  });

  afterEach(() => {
  });

  it('runs a test', () => {
  });
});`

...the important point though, is to auto-generate the __tests__ directory and the test file.

**Comment by randi274** [comment]
@jeffb-sfdc! You added this in yourself 👏 🏅 👏  #4203
