### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Astrante** [forcedotcom/salesforcedx-vscode#1303]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `45.12.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\onya\salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@Astrante Can you provide us with information on what operation you were performing when you observed the high CPU load? Does the CPU load stay high or does it come down shortly?
