### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Vijayexplorer** [forcedotcom/salesforcedx-vscode#1306]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.13.0`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/Vijay/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@Vijayexplorer Can you provide us with information on what operation you were performing when you observed the high CPU load? Does the CPU load stay high or does it come down shortly?
