### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by grushai** [forcedotcom/salesforcedx-vscode#1313]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.13.0`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Stepanko\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@grushai What operation were you performing when you saw the high cpu load? Does the cpu usage come down shortly?
