### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marceloharredondo** [forcedotcom/salesforcedx-vscode#1317]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.13.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/marce/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@marceloharredondo What operation were you performing when you saw the high cpu load? Does the cpu usage come down shortly?

**Comment by marceloharredondo** [comment]
I was creating the first project since I installed the VSC, using the command palette. After the issue, the CPU usage kept normal.

**Comment by smaddox-sf** [comment]
Duplicate #1149
