### ISSUE TITLE
Include on the fly error messages

### ISSUE THREAD

**Issue by sc5148** [forcedotcom/salesforcedx-vscode#1322]
**Incompatible types:**
illegal assignments, typically the result of **incompatible types** like assigning a contact sobject result to an Account variable. 

**Unresolvable reference:**
references that cannot be resolved to corresponding declarations like using SObject fieldnames that do not exist or using a variable that has not been declared.

Currently we get to know these only after deployment. However it should be on the fly in the problems window.

**Comment by praksb** [comment]
@sc5148 You can get some of these semantic errors in Apex by modifying your settings.json file and  set salesforcedx-vscode-apex.enable-semantic-errors to true. We don't have them enabled by default since some scenarios are not supported for local development which results in false errors showing up.

**Comment by sc5148** [comment]
I had turned on semantic errors. But it was giving wrong error messages. When I was calling a static method of a different class, the peek to show definition on the calling method did not work and on top of that the line which was calling the method was shown as 'problem'.

**Comment by praksb** [comment]
@sc5148 Did you run "Refresh SObject Definitions" command? If not, can you go to View -> Command Palette  and run that command. Hopefully, that should make your experience better.

**Comment by sc5148** [comment]
@praksb Yes I have used refresh SObject definitions but still the problem messages do not go away even after restarting VSCode. You can even see this screenshot where the .cls file generated after SObject refresh has a green underline for CASE saying the identifier name is reserved.
![image](https://user-images.githubusercontent.com/19307757/57436572-41449d80-7240-11e9-9d4a-6cb54f68fefa.png)

 Also one more example, it does not recognize the custom field on account object
![image](https://user-images.githubusercontent.com/19307757/57437139-73a2ca80-7241-11e9-92cd-c5e59c153a40.png)
I checked in the Account.cls file which got generated due to SObject refresh. That custom field is there.
![image](https://user-images.githubusercontent.com/19307757/57437307-c9777280-7241-11e9-83d4-870941ab0c81.png)

**Comment by praksb** [comment]
@sc5148 The first issue with the error you are seeing in "Case" is a minor bug. We should not be showing diagnostics on generated classes. It should not impact other features.

The second issue you are seeing looks very similar to https://github.com/forcedotcom/salesforcedx-vscode/issues/1170 which was specific to Windows and was fixed couple of weeks ago. Can you let me know which OS are you using? Also, do you have the latest Apex extension installed on your machine? The latest is v45.14.0.

**Comment by sc5148** [comment]
@praksb I am using version 45.14.0 and my OS is Windows 10

**Comment by praksb** [comment]
@sc5148 Does the error go away when you edit the file? If not, is it possible for you to zip and share your project with me since I am unable to repro this problem at my end? You could find my email on my github profile.

**Comment by sc5148** [comment]
@praksb Yes the errors related to custom fields not found went away after saving the file but I noticed some other issues too related to the semantic errors flag. I will comment that on #1331 as this one is closed

**Comment by praksb** [comment]
@sc5148 There is a known issue that diagnostics don't get refreshed until an edit happens during startup. I'll follow up with you on the issues on the other thread.
