### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lalitha-s** [forcedotcom/salesforcedx-vscode#1325]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.13.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\lalitha.selvaraj\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@lalitha-s Can you please let us know what operation you were performing when you observed the high CPU usage? If it is during startup we have a Java process that does indexing of the Apex classes and triggers and the CPU usage is expected to spike during that time but it should come down shortly after a few seconds when indexing is complete.

Is the issue you are seeing similar to either of the ones below:

https://github.com/forcedotcom/salesforcedx-vscode/issues/1317
https://github.com/forcedotcom/salesforcedx-vscode/issues/1239
