### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cah-sakis-stergioulas** [forcedotcom/salesforcedx-vscode#1335]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.14.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`D:\Users\sakis.stergioulas\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@cah-sakis-stergioulas Can you please let us know what operation you were performing when you observed the high CPU usage? If it is during startup we have a Java process that does indexing of the Apex classes and triggers and the CPU usage is expected to spike during that time but it should come down shortly after a few seconds when indexing is complete.

Is the issue you are seeing similar to either of the ones below?:

#1317
#1239

There is also a known performance issue that occurs during indexing when you have thousands of classes/triggers in your org. Is that the case in your project?
