### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mukeshkhandve** [forcedotcom/salesforcedx-vscode#1337]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `45.14.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\hp\salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@Mukeshkhandve Can you please let us know what operation you were performing when you observed the high CPU usage? If it is during startup we have a Java process that does indexing of the Apex classes and triggers and the CPU usage is expected to spike during that time but it should come down shortly after a few seconds when indexing is complete.

Is the issue you are seeing similar to either of the ones below?:

#1317
#1239

There is also a known performance issue that occurs during indexing when you have thousands of classes/triggers in your org. Is that the case in your project?

**Comment by brandonmikeska** [comment]
@praksb we are also noticing this for my entire Team. Our Org is very large, is there a work around or a timeline for the known performance issue for large orgs?

**Comment by praksb** [comment]
@brandonmikeska We are still exploring our options here for perf improvements since it involves rearchitecting our indexer. There is no timeline at the moment. I should have more information in a couple of weeks time.

**Comment by Jqda0** [comment]
@praksb any more information about this?

**Comment by praksb** [comment]
@Jqda0 We are currently testing a couple of fixes that may improve indexing for some customers. No timeline yet for the release of these fixes.
