### ISSUE TITLE
push-or-deploy-on-save

### ISSUE THREAD

**Issue by jimwaz** [forcedotcom/salesforcedx-vscode#1353]
### Summary

when deploy on save runs, and errors exist I receive no errors outside of the fact that the deploy failed.  

### Steps To Reproduce:

1.  Create a apex class with a error that would cause the deploy to fail
1.  Wait and let the deploy to fail

### Expected result

Deploy executes and errors are listed: for example:

PROJECT PATH  ERROR
────────────  ───────────────────────────────────────────────
              Annotation does not exist: AuraEnabledxx (82:5)

### Actual result

This is Output is as follows, no errors are listed:

23:27:26.293 sfdx force:source:deploy --sourcepath c:\JWDev\vsCode\zzz\src\classes\CS_ProcessStepProvider.cls --json --loglevel fatal
23:27:31.631 sfdx force:source:deploy --sourcepath c:\JWDev\vsCode\zzz\src\classes\CS_ProcessStepProvider.cls --json --loglevel fatal ended with exit code 1

_Deploy failed_

### Additional information
**VS Code Version**:  1.34

**SFDX CLI Version**: sfdx-cli/7.6.0 win32-x64 node-v8.12.0

**OS and version**: Windows 10

I have updated the CLI, I have also reinstalled the salesforce extension pack to see if the error would resolve it self to no success.  Running the following command(without the --json) at the command line will produce the results desired.

sfdx force:source:deploy --sourcepath c:\JWDev\vsCode\zzz\src\classes\CS_ProcessStepProvider.cls  --loglevel fatal

Any ideas or suggestions of settings to verify?  Errors were being produced for a short time upon a install a few weeks back but something has changed.
Thanks for any assistance.

**Comment by spavunaleaseplan** [comment]
I have the same problem since recently. It makes it quite unworkable.

**Comment by lcampos** [comment]
This was fixed on Salesforce CLI version `7.14`
