### ISSUE TITLE
Removing this repo/ Un-subscribe

### ISSUE THREAD

**Issue by freddysilber** [forcedotcom/salesforcedx-vscode#1359]
Hi, So I've been battling this issue for a few months where I can't get rid of this repo. It showed up on my home page (on the left side bar under my list of forked and owned repos) one day and I don't know why. I have been trying to delete it or remove myself from this repo so it won't show up on my home page but I can't. When I enter this repo i should be able to see a settings tab at the top where I can get rid of this but there is no settings tab. Can you as the owner possibly help me get rid of this so it goes away? This is getting annoying

**Comment by ntotten** [comment]
@freddysilber We don't have any control over your notifications or settings. I suggest maybe you contact GitHub support: https://github.com/contact
