### ISSUE TITLE
Java Version Detection doesn't work on all version strings

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1363]
Looking here 
https://github.com/forcedotcom/salesforcedx-vscode/blob/master/packages/salesforcedx-vscode-apex/src/requirements.ts
line 86
```
javaHome + '/bin/java', ['-version'], {},

      (error, stdout, stderr) => {

        if (

          stderr.indexOf('build 1.8') < 0 &&

          stderr.indexOf('build 11.') < 0

        ) {

          reject(nls.localize('wrong_java_version_text', SET_JAVA_DOC_LINK));

        } else {

          resolve(true);

        }

      }
```

I'm using openJDK and it looks like my output is different 

![openJDK](https://user-images.githubusercontent.com/10601890/58316080-ad133280-7e0a-11e9-8c49-da3248847486.PNG)

_Originally posted by @Londoner1234 in https://github.com/forcedotcom/salesforcedx-vscode/issues/930#issuecomment-495531429_

**Comment by shillem** [comment]
Please, consider adding 12 already since it's GA

**Comment by patelvir14** [comment]
when this bug will be resolved for OpenJDK 11?

**Comment by jeffb-sfdc** [comment]
The associated WI is W-6176742.

**Comment by jeffb-sfdc** [comment]
@ntotten FWIW, we also support Java 17.

**Comment by sogeisetsu** [comment]
> Please, consider adding 12 already since it's GA

@shillem OH ! NO ！I tried to use the GA version of openjdk11 and the GA version of openjdk17, but it didn't work, **I also used the build 11.0.2+9 version of openjdk, luckily it worked**. When I change to Oraclejdk11 or Oraclejdk17, it works fine.

There is one thing I don't understand, is there any logic for salesforcedx-vscode in the selection of supported openjdk versions? **Why does not support the GA version of opengdk ?** @shillem  GA clearly means General Availability, which represents the officially released version, the official began to recommend widespread use.

我是从这个网站上获取的openjdk👉https://jdk.java.net/archive/

**Comment by savage25** [comment]
Java is up to version 19 - my company won't allow lower version installed - please update to Java v19

**Comment by diyer** [comment]
@fafnirical @savage25 @sogeisetsu We believe we have fixed this issue. Can you please verify on your end and let us know ?
