### ISSUE TITLE
Java Detection and Installation UI

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1364]
Similar to what the [Java Extension is doing](https://devblogs.microsoft.com/visualstudio/java-on-visual-studio-code-april-update/?utm_source=Direct), we should adopt a similar UI to help detect and install JDK.

![image](https://user-images.githubusercontent.com/282782/58330373-c1543100-7e04-11e9-8e22-2fbf2acae42f.png)

![image](https://user-images.githubusercontent.com/282782/58330384-c618e500-7e04-11e9-842b-38aa76439ebf.png)

I did also ask @hexiaokai, who is the PM of the Java extensions if we could potentially share this via an extension that does Java detection:  https://twitter.com/ntotten/status/1131909999112916994

**Comment by ntotten** [comment]
There is also a discussion here about this issue: https://github.com/microsoft/vscode-java-pack/issues/142

**Comment by shillem** [comment]
12 is GA https://openjdk.java.net/projects/jdk/
