### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MrKaveh** [forcedotcom/salesforcedx-vscode#1369]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.15.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/*/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment]
@MrKaveh Can you let us know what operation where you performing when you observed this? Does it happen when you start VS Code? We index your sources during startup which might cause a high cpu load but it should come down shortly. Is that not the case? Also, there is a known performance issue with the indexer that affects some orgs which have a huge number of classes (>1000+) is that the case?
