### ISSUE TITLE
Explorer does not show newly created files

### ISSUE THREAD

**Issue by paustint** [forcedotcom/salesforcedx-vscode#1375]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Create a project using a manifest
1.  right click on lwc and choose new lightning web component
1. add a new file
1. the files are created, but the explorer does not show the files

### Expected result
1. files show in explorer

### Actual result
1. I have to restart VSCode for new components to show up

### Additional information
I have on occasion seen this happen with other plugins and I can usually start to create a new file manually and then press escape to exit the creation and then the other files show up. But in this case, that did not work.

![image](https://user-images.githubusercontent.com/5461649/58635404-0962d000-82ab-11e9-9e2f-6066bb30b53c.png)

**VS Code Version**:
Version 1.34.0 (1.34.0)

**SFDX CLI Version**:
sfdx-cli/7.6.0-28071a499b darwin-x64 node-v10.15.3

**OS and version**:
OSX 10.14.4 (18E226)

**Comment by ntotten** [comment]
This is an issue with VS Code itself rather than the extensions. Maybe try setting `files.useExperimentalFileWatcher: true`. See https://github.com/Microsoft/vscode/issues/31600 and https://github.com/Microsoft/vscode/issues/28432, there are also more.
