### ISSUE TITLE
Issue with salesforce org authorization

### ISSUE THREAD

**Issue by vermaajit** [forcedotcom/salesforcedx-vscode#1379]
I use VS code for salesforce project development and I always have more than one project connected to different salesforce org. e.g I have two projects, SF_Porject1 and SF_Project2 which are connected to different sandbox SF_Org1 and SF_Org2 respectively. But the problem here is that when I switch from SF_Porject1 to SF_Porject2 then salesforce org is not persistent and connection SF_Org2 is broken and it saves all changes into SF_Org1 so all my changes done in SF_Porject2 goes into SF_Org1 and I need to re-authroize the org.

Also to clarify, I used the project with manifest file and authorize my org to connect with the project.

Please advise on this bug.

**Comment by smaddox-sf** [comment]
Similar to #958
