### ISSUE TITLE
Apex Replay Debugger: Error: spawn ENOTDIR on Ubuntu 18.10

### ISSUE THREAD

**Issue by sam1730** [forcedotcom/salesforcedx-vscode#1381]
### Summary

_Apex Replay Debugger on Ubuntu doesn't seems to be working any time._.
Here's the configuration
`{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Apex Replay Debugger",
      "type": "apex-replay",
      "request": "launch",
      "logFile": "${command:AskForLogFileName}",
      "stopOnEntry": true,
      "trace": true
    }
  ]
}
`

### Steps To Reproduce:

1.  Click on Debugger icon, from the left panel.
1.  Click on the Play Icon to Launch the Apex Replay Debugger.
1.  You will get an error message saying, Error: spawn ENOTDIR

### Expected result

_On windows version of VS Code and Salesforce CLI always works fine with Apex Replay Debugger, but from last 1 year whenever I tried with the older version or the latest version I did't found any working scenario of this feature, specially on Ubuntu_.

### Actual result

_Always throw an error of spawn ENOTDIR, also tried to download the logs and launch it by clicking right button on those logs_.

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/8025897/58898781-f58af400-8718-11e9-9cf2-c13564670146.png)

**VS Code Version**:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-21-generic

**SFDX CLI Version**:
sfdx-cli/7.1.4-79f97a7df8 linux-x64 node-v10.15.3

**OS and version**:
UBUNTU OS: Linux x64 4.18.0-21-generic

**Comment by lcampos** [comment]
hi @sam1730 can you add which version of the Salesforce extensions for vscode you are using ? You can see that by going to the Extensions section and looking at the Apex extension description.

Also, which version of Java did you install ? We currently support Java JDK 8 or Java JDK 11. That is needed for the Apex language server, which is then used by the Apex debuggers.

**Comment by sam1730** [comment]
Hi @lcampos 
JAVA VERSION :
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

Extension Version:
45.15.1

**Comment by sam1730** [comment]
Hi @lcampos 
Can you please help me on this?

**Comment by lcampos** [comment]
Hi @sam1730 I haven't been able to replicate this yet. Could you open VSCode's dev tools (Help > Toggle Developer Tools), go to the `Console` tab in dev tools and see if there's any error & stack trace on it ? If you do find one could you attach it here ?

**Comment by sam1730** [comment]
Hi @lcampos 
![image](https://user-images.githubusercontent.com/8025897/59400103-ead4fc80-8db3-11e9-84f8-81453bf21f2b.png)

![image](https://user-images.githubusercontent.com/8025897/59400130-00e2bd00-8db4-11e9-9a77-e114a76926ad.png)

**Comment by lcampos** [comment]
Ok, that error means that the Apex Language Server ran into an issue while starting up. Have you tried setting up your JDK configuration for the extensions using the `salesforcedx-vscode-apex.java.home` setting like it's documented on [Set Your Java Version](https://forcedotcom.github.io/salesforcedx-vscode/articles/troubleshooting#set-your-java-version) ? We currently support using JDK 8 or JDK 11.

**Comment by sam1730** [comment]
Thanks @lcampos 
It worked for me now.
