### ISSUE TITLE
Using VSCode and SF extension unable to perform conflict resolution.

### ISSUE THREAD

**Issue by SethMagner** [forcedotcom/salesforcedx-vscode#1383]
### Summary
When performing a commit vscode is sending a file to a stage changes area instead of a merges changed area not allowing for conflict resolution.
![1](https://user-images.githubusercontent.com/28605067/59006776-b2508400-87f1-11e9-818d-129e263b4f69.png)

**Comment by ntotten** [comment]
This seems like it is related to VS Code itself rather than the extensions. I would suggest opening a bug on https://github.com/microsoft/vscode instead.
