### ISSUE TITLE
switch on trigger.operationType

### ISSUE THREAD

**Issue by gbutler61** [forcedotcom/salesforcedx-vscode#1386]
VSCode vs Developer Console in regards to trigger.OperationType and ENUM

### Summary

As shown in the attached screen shot, you can see that the same code shows that VSCode and Developer Console are not allowing the same code.  I have placed the same references in several contexts to show side by side how they differ.  

I also attempted to resolve based on issue 825...

### Steps To Reproduce:
see attached Trigger Code in VSCode and in DevConsole

### Expected result

1. VSCode is not accepting trigger.OperationType in a switch statement as introduced in '18, but the code is valid in DevConsole  
2. VSCode and DevConsole to be consistent 

### Actual result
![VSCode TriggerOperationType](https://user-images.githubusercontent.com/44989851/59173141-86970c00-8b19-11e9-8ddd-1f2467da4c1b.jpg)

[JobHistoryTrigger.trigger.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/3270619/JobHistoryTrigger.trigger.txt)

See screenshots.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:  1.35.0

**SFDX CLI Version**: sfdx-cli/7.8.1-8f830784cc win32-x64 node-v10.15.3

**OS and version**: Win7 Ultimate x64

**Comment by gbutler61** [comment]
closing as was just trying to search but entered in wrong field...  Apologies

**Comment by gbutler61** [comment]
Am reopening as the other closed bug did not resolve my issue.

**Comment by praksb** [comment]
@gbutler61 I am not able to reproduce this issue. Looking at your screenshot it seems like your error messages in VS code looks stale which could be the bug here. If you close and re-open VS Code does the error messages refresh?

**Comment by gbutler61** [comment]
I already did that multiple times…

**Comment by praksb** [comment]
@gbutler61 Please note that you'll see the errors only when "salesforcedx-vscode-apex.enable-semantic-errors"  is set to "true". You may have to restart VS code after setting it to "true". If you are still seeing this issue after doing it then is it possible for you to zip the project and share it with me to help me attempt to repro the issue? You may have to upload it somewhere and send me the link. You can find my email here: https://github.com/praksb
