### ISSUE TITLE
Failing to retrieve source from org

### ISSUE THREAD

**Issue by ruchashende** [forcedotcom/salesforcedx-vscode#1387]
Issue Type: <b>Bug</b>

Steps to produce:
Right click on package.xml file under manifest folder. Click on retrieve source from org. 

Fails to retrieve code.

Extension version: 45.15.1
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment]
Hi @ruchashende can you provide the version of the Salesforce CLI you are working with ? Did you get an error message/stack trace when the retrieve command failed ? Are you using the `package.json` file created when running `SFDX: Create Project with Manifest` or did you modify it ?

**Comment by ruchashende** [comment]
Hi @lcampos ,
Currently I am using CLI 46.1.0 version. The error that I received is - `ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined`
I am not sure which package.json you mentioned. I am using `sfdx-project.json `file and did not modify it.

Initially, when I had authorized the org, I used `sfdx force:mdapi:retrieve -r ./mdapipkg -u _username_ -k ./manifest/package.xml` command since retrieving code by right clicking on package.xml file did not work then.

![retrieve error](https://user-images.githubusercontent.com/49281006/59824166-f002f000-934d-11e9-8528-5def201f0ed6.PNG)

**Comment by lcampos** [comment]
@ruchashende my bad, I was talking about the `package.xml` file.
Do you have any cli plugins installed ? You can run `sfdx plugins` in your terminal, which will give a list of installed plugins.
Also, 46.1.0 is the version of the Salesforce vscode extensions, can you run `sfdx --version` to get the Salesforce CLI version ?
