### ISSUE TITLE
Issue with Creating Project with Manifest

### ISSUE THREAD

**Issue by radanatme** [forcedotcom/salesforcedx-vscode#1393]
[Screenprint.docx](https://github.com/forcedotcom/salesforcedx-vscode/files/3281929/Screenprint.docx)
After installing the VS Code with Salesforce Extension Pack, when trying to create a new Project with Manifest, it always throw an error "Invalid Event Target" with no other information. Cannot proceed further, please help.

**Comment by lcampos** [comment]
Hi @radanatme can you provide the following information on how you've setup your machine:
- Salesforce CLI version
- Salesforce VSCode extensions version
- VSCode version
- Operative system you are using

**Comment by radanatme** [comment]
@lcampos  apologize for the delayed response.

I have the latest version for everything - 

Salesforce CLI version - 46.2.0
Salesforce VSCode extensions version - 46.2.0
VSCode version - 1.35.1
Operative system you are using - Microsoft Windows 8.1 Enterprise

![Versions](https://user-images.githubusercontent.com/49601084/60106622-8874e800-9733-11e9-9b24-ef3b8708b250.png)

**Comment by lcampos** [comment]
Sorry for the delay, this looks similar to issue #1512. Can you update to the latest version of the Salesforce CLI (`sfdx update`) and see if that addresses the issue you were running into ?
