### ISSUE TITLE
lwc-language-server code base

### ISSUE THREAD

**Issue by girishla** [forcedotcom/salesforcedx-vscode#1395]
Is the lwc-language-server open sourced? If yes, where can I find the source code ?

**Comment by lcampos** [comment]
Hi @girishla, the `lwc-language-server` is currently not open sourced but @ntotten can provide more info regarding its roadmap.

**Comment by ntotten** [comment]
We are working on final approvals for open sourcing the LWC and Aura language servers. Should be within a month.

**Comment by girishla** [comment]
Great, thanks for the update @ntotten
