### ISSUE TITLE
Please add support for openjdk

### ISSUE THREAD

**Issue by rhyatt-qualtrics** [forcedotcom/salesforcedx-vscode#1399]
**Is your feature request related to a problem? Please describe.**
It is frustrating that be forced to use Oracle's new java 8's updated license terms instead of just using open jdk. I tried to have your plugin use openjdk, but I am getting this message:
![image](https://user-images.githubusercontent.com/50032708/59520629-9dc25a80-8e87-11e9-9c5d-354ff9edbe41.png)

**Describe the solution you'd like**
Please make openjdk supported. I'm ok with needing to tweak the config settings to make this happen.

**Describe alternatives you've considered**
Java 8 isn't going to work for my organization going forward. I need to make it use openjdk or I won't be able to use your product.

**Additional context**
Screenshot provided earlier.

**Comment by Nathorr** [comment]
AdoptOpenJDK 11 for Windows and jdk-openjdk package in extra repository for Arch Linux both work well with these extensions. No need to have Oracle's JDK.

**Comment by praksb** [comment]
@rhyatt-qualtrics OpenJDK is supported. Please follow the instructions here to set your Java 
version: https://forcedotcom.github.io/salesforcedx-vscode/articles/troubleshooting We need to update the error message though.
