### ISSUE TITLE
Unexpected file found in package directory lwc\jsconfig.json

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1410]
PS C:\SalesforceDX\HMI DX\hmidelete> sfdx force:source:push
ERROR running force:source:push:  Unexpected file found in package directory: C:\SalesforceDX\HMI DX\hmidelete\force-app\main\default\lwc\jsconfig.json

![image](https://user-images.githubusercontent.com/93057/59719831-ef9a1600-91e2-11e9-9c37-c4b1064ced90.png)

**Comment by lcampos** [comment]
@chandra2ravi do you have a `.forceignore` file at the top of your repository and does it contain an entry for ignoring that json file e.g. `**/jsconfig.json` 

Can you provide the following info:
- Salesforce cli version
- Salesforce vscode extensions version

**Comment by chandra2ravi** [comment]
.forceignore file at the top of your repository -- Yes
I'm using node npm i think issue with npm installation  is bugggggyyy( lot of other issues tooo)
sfdx-cli/7.8.1-8f830784cc
Salesforce Extension Pack 46.1

**Comment by lcampos** [comment]
@chandra2ravi is it possible for you to share a repository that I can use to replicate the issues you are experiencing ? I'm not able to replicate what you're experiencing.
Also, I'm assuming you're working on a windows machine because of the file path included in previous messages.

**Comment by chandra2ravi** [comment]
Yes, I'm using windows and npm installation of CLI. I deleted npm installation and installed windows based CLI and it's working fine now. You can close this ticket.
