### ISSUE TITLE
Cannot run SFDX commands through command palette

### ISSUE THREAD

**Issue by tannerrobinaugh** [forcedotcom/salesforcedx-vscode#1414]
### Summary

I suddenly cannot run any SFDX commands through the command palette. When I try to run a command such as Authorize an Org, nothing happens for about 30 seconds and then an error appears saying the command could not be found. Also, when I have the extensions installed, Git features in VSCode stop working. I cannot switch branches through the status bar and the Source Control section in the sidebar hangs on refreshing.

### Steps To Reproduce:

1.  VSCode and the Salesforce CLI are installed
1.  Install the Salesforce Extension Pack
1.  Open a Git repo that has a Salesforce project
1.  Run an SFDX command such as Authorize an Org

### Expected result

You are prompted to enter the parameters for the command and then a new tab opens in your web browser to open that org.

### Actual result

Nothing happens for roughly 30 seconds then an error appears in the notifications saying that the command cannot be found.

### Additional information

This issue appeared seemingly out of nowhere. Everything was working fine a few minutes before this started and no changes had been made to the system between it working and this issue starting. I have already tried reinstalling the Extension Pack, the CLI, and VSCode itself. When reinstalling VSCode, I made sure to remove any files leftover from the uninstall before reinstalling. I can also run SFDX commands from the terminal just fine so I know it's not a CLI issue.

![error](https://user-images.githubusercontent.com/21315466/59772251-6eda2900-9279-11e9-888d-32b1546cd090.PNG)
![statusbar](https://user-images.githubusercontent.com/21315466/59772260-71d51980-9279-11e9-9881-776832be92b1.PNG)

**VS Code Version**: 1.35.1

**SFDX CLI Version**: 7.11.2-4a5bf6aa97

**OS and version**: Windows 7 Service Pack 1

**Comment by tannerrobinaugh** [comment]
So this issue started on June 18th at about 2 PM and at about 10:40 AM on June 19th, it is working again. I hadn't done anything to try to make it work since I posted the issue, I just left it alone while I went to a meeting and came back to it working. So while my issue is "fixed", I can't imagine I'm the only one who's experienced this so I'm guessing there's still an underlying issue somewhere.

**Comment by lcampos** [comment]
@tannerrobinaugh have you made any changes to your machine e.g. installing OS updates, etc ? The issue you are seeing is caused by executing an `SFDX` command while the extension is still activating. That's why if you execute the same command later it works.

I wonder if something in your system's configuration changed that would make your VSCode run a bit slower than before.

**Comment by tannerrobinaugh** [comment]
@lcampos interesting, I hadn't considered that the extension hadn't completed activating yet. OS updates were installed yesterday so that very well could be it. I'll have to test it out tomorrow as it's a work laptop and I don't have it with me at the moment. I can say that there was about 10 minutes between me starting VSCode and then leaving it for my meeting so it took at least that long and probably longer for the extension to start.
