### ISSUE TITLE
Launch configuration for Debugging LWC Jest tests

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/salesforcedx-vscode#1418]
**Is your feature request related to a problem? Please describe.**
Jest is the framework suggested for writing tests when working with LWC. The extensions should provide a Launch configuration for running & debugging those tests.

Reference: [sfdx-lwc-jest:Debugging in Visual Studio Code](https://github.com/salesforce/sfdx-lwc-jest#debugging-in-visual-studio-code)

**Describe the solution you'd like**
The extensions should provide a Launch configuration for running & debugging those tests.

**Describe alternatives you've considered**
Users currently have to manually create this configuration.

**Comment by randi274** [comment]
This was delivered with #3920 and is now generally available in the extensions 🎉
