### ISSUE TITLE
Custom Metadata Type has a lookup to FieldDefinition or EntityDefinition, the generated class file in /sfdx/tools/sobjects/customObjects does not contain the reference field to the lookup.

### ISSUE THREAD

**Issue by praksb** [forcedotcom/salesforcedx-vscode#1421]
I've found another edge case. If my Custom Metadata Type has a lookup to FieldDefinition or EntityDefinition, the generated class file in /sfdx/tools/sobjects/customObjects does not contain the reference field to the lookup. 

So if MyMeta__mdt.Object__c is a lookup to EntityDefinition, then I should expect the generated class to have **global EntityDefinition Object__r**. Because it doesn't, I'm getting this error when I call my method that takes a String, with an argument of **myMetaRecord.Object__r.QualifiedApiName**.

_Originally posted by @camisotro in https://github.com/forcedotcom/salesforcedx-vscode/issues/1405#issuecomment-504067956_

**Comment by camisotro** [comment]
Thanks, following!

**Comment by jag-sfdc** [comment]
@camisotro - We have made several improvements to how we generate the cls files. Do you still see this issue?
