### ISSUE TITLE
Unable to install Salesforce Extension Pack in VS Code

### ISSUE THREAD

**Issue by maerans** [forcedotcom/salesforcedx-vscode#1431]
Unable to install Salesforce Extension Pack as it is stuck on installing.

**Comment by chiragpaliwal** [comment]
Hi, check if your internet connection is working, it actually takes longer to install since the extensions pack contains several extensions. Try waiting it out.

**Comment by maerans** [comment]
Internet is working fine.

When i tried to install it on personal desktop , it got installed within 2 minutes.

I have left it to install since 4 hours and no results yet.

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via GitHub issues. Please post your question on the [Trailblazer Community](https://success.salesforce.com), [Stackoverflow](https://salesforce.stackexchange.com/), or through other official support channels.
