### ISSUE TITLE
SFDX: Retrieve Source from Org throwing an error

### ISSUE THREAD

**Issue by nkggit** [forcedotcom/salesforcedx-vscode#1432]
I created a new project created by running SFDX: Create Project with Manifest and authorized a sandbox org.
When I right-click on default generated package.xml and run SFDX: Retrieve Source from Org, following error is displayed:

"Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm"

My project json file looks like this:
sfdx-project.json file:
{
"packageDirectories": [
{
"path": "force-app",
"default": true
}
],
"namespace": "",
"sfdcLoginUrl": "https://test.salesforce.com",
"sourceApiVersion": "46.0"
}

I am using below:
VS Code => Version1.35.1
SFDX CLI => sfdx-cli/7.12.3-bfc421fa08 win32-x64 node-v10.15.3
Windows

**Comment by Mlzelinski** [comment]
I am having the same issue!

**Comment by ntotten** [comment]
@Mlzelinski Since this issue is closed, please open a new issue with full details of the problem you are having.

**Comment by VictorFlorencio** [comment]
I have the same issue here.

**Comment by nkggit** [comment]
Hi Everyone,

Please make sure you are not right clicking on 'Manifest' folder and trying to retrieve source code. 
Make sure to right click on 'Package.xml' under 'Manifest'.
![GitIssue](https://user-images.githubusercontent.com/32768367/72136563-13a38b80-33af-11ea-8f59-f8b28796215d.PNG)

**Comment by madharamu** [comment]
@nkggit  Saved my day _/\_

**Comment by selcukgoktas** [comment]
I have the same issue. There was no problem until this day. The thing is when I right click package.xml and deploy its fine. But it deploy all the files. When I click lwc or any file apex, aura etc,  it says The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file.. I'm working nearly 1 month with this method there was no problem. 

I update sfdx cli, vscode, sfdx cli extension but still same problem. 
you can check my files from my repo. https://github.com/selcukgoktas/SalesforceDeveloperTraining


Everything is in the force-app/main/default. 
and my sfdx-project.json file  is below.

`{
  "packageDirectories": [
    {"path": "force-app","default": true}
  ],
  "name": "SalesforceDeveloperTraining",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "55.0"
}
`

**Comment by justKev93** [comment]
I am having the exact same issue.. And only happened today as well.. Yesterday everything worked perfectly.. Today it fell apart

**Comment by shivi-95** [comment]
I am also facing same issue, just started few minutes ago

**Comment by srujangurudu** [comment]
I too started facing this issue suddenly

**Comment by danicsegura** [comment]
> If you are reaching this question in July of 2022, there is an issue with the most recent Salesforce CLI Integration Extension for VS Code on Windows.
> 
> To resolve, go to your extensions, go to Salesforce CLI Integration, click the drop down next to Uninstall, and click "Install another version". Install the previous version (55.3.0)

After searching in a few forums, this solution was the one that solved the issue for me.
