### ISSUE TITLE
Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli

### ISSUE THREAD

**Issue by shashankinfy** [forcedotcom/salesforcedx-vscode#1433]
Issue Type: <b>Bug</b>

I installed the salesfroce CLI almost 10 times now but this error is keep coming to me. I want to just create a DX project and do my lightning web component development. but due to this i am stuck.

Extension version: 46.2.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

**Comment by lcampos** [comment]
Hi @shashankinfy I think this might be related to the Salesforce CLI not being part of the `PATH` environment variable in your machine. Can you verify the cli install path is part of `PATH` ? Also, are you installing the cli using `npm` or the installer  ?

**Comment by shashankinfy** [comment]
Hello,

Can you please guide me about this path? And no I am not installing using npm.

Shashank

**Comment by ntotten** [comment]
See: https://salesforce.stackexchange.com/questions/163795/sfdx-is-not-recognized-as-an-internal-or-external-command

**Comment by pratikshekokar** [comment]
Hello,
If it is showing that CLI is not installed Then the possible is you haven't set the path or set the wrong path.
to SET PATH
>>press Start Button
>>Type Environment
>>Go to System Environment setting
>>Advance
>>Environment Variables
>>there are two option user variable for admin and system variable
>> go to system variable 
>> Double click on Path
>> Add new row and paste the path of Salesforce cli in my case it is "C:\Program Files (x86)\Salesforce CLI\bin"
>>also set the path of java JDk if it is not set. in my case path of java is "C:\Program Files (x86)\Java\jdk-13.0.1\bin"
>>now click ok again ok and now you are done
>>now to check that your path is set type "win+R" type "CMD" and enter " echo %PATh% "
>>if you find your new path here then your path is successfully set
tip- If still not showing path try restarting the system.

**Comment by 09archanakumari** [comment]
@pratikshekokar i have  set the path correctly in user and system variable but still I am facing the same issue.  Can you please help me .

**Comment by Akash-Kandwal** [comment]
@pratikshekokar I am also facing the same issue, after setting the path 10 times it is still showing path not specified.

**Comment by 09archanakumari** [comment]
@Akash-Kandwal remove it from user variable and keep it in system variable that is how it worked for me .Give it a shot.

**Comment by pratikshekokar** [comment]
> @pratikshekokar I am also facing the same issue, after setting the path 10 times it is still showing path not specified.

Try archankumari's suggestion
