### ISSUE TITLE
Org Picker still selects deleted org

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1438]
### Summary

When an org is deleted or expired it should no longer be actively selected by VS Code

### Steps To Reproduce:

1.  Create org in VS Code, org will be selected by default
1. Close VS Code
1. Delete org using CLI
1. Open project in VS Code
1. See that org is still selected

### Expected result

If the org is deleted, expired, or otherwise invalid it should no longer be selected as the default org in VS Code.

### Actual result

Org is still selected

**Comment by RitamAgrawal** [comment]
@ntotten Can you please verify if this issue still exists for you?
