### ISSUE TITLE
A simple 'list orgs' command

### ISSUE THREAD

**Issue by woutersmet** [forcedotcom/salesforcedx-vscode#1439]
**Is your feature request related to a problem? Please describe.**
A command I find myself running at the start of each day, and multiple times within a day, is sfdx:force:org:list - just to see ok, this is the orgs I got, this one is active, this is the username I want to change to the default one. 

Clicking on the 'org picker' in the lower left gives something of a list, but I would love to just have a 'list orgs' command that shows in the output what I otherwise get in the terminal.

**Describe the solution you'd like**
A new command: 'sfdx: list orgs' which basically just runs sfdx:force:org:list and shows the output in the output window.

**Describe alternatives you've considered**
I'm sure vscode has plenty of ways to achieve the same / set up your own scripts/commands etc, but I think eliminating the terminal as much as possible for the sfdx extensions would be nice.

**Additional context**
Pretty new to vscode and all the salesforce extension possibilities, so this may already be in there somewhere. Also, maybe there's an even nicer spot then the 'output' window (some dialog?), but that's where I would expect it given how I'm using vscode currently.

**Comment by ChuckJonas** [comment]
As a work around, I'd recommend setting up a [tasks.json](https://code.visualstudio.com/docs/editor/tasks)

{
  "label": "List Orgs",
  "type": "shell",
  "command": "sfdx force:org:list"
}

**Comment by woutersmet** [comment]
Thanks @ChuckJonas, that does pretty much the same indeed!
