### ISSUE TITLE
Test Coverage - specific to tests ran.

### ISSUE THREAD

**Issue by PS-Dev-Luis** [forcedotcom/salesforcedx-vscode#1447]
**Is your feature request related to a problem? Please describe.**
When running Apex tests with the following setting
"salesforcedx-vscode-core.retrieve-test-code-coverage" : true
the information that is returned and then used for the line highlighting appears for the overall coverage in the org as opposed to the specific code covered by the executed test(s).  

In the Force.com IDE we were able to run a test(s) and then see the coverage per class of the execution of that specific (or group of) tests.  This meant it was very easy to work out what had executed without having to add debugs and breakpoints because if a specific area hadn't ran then you knew whatever necessary conditions hadn't been met.  

As all the coverage is now returned, you are unable to tell whether a specific piece of code was ran by the selected test or by another test in the org.  Also having the coverage for the whole org returned increases to the test execution time greatly.

**Describe the solution you'd like**
It would be great to get the class coverage and specific highlighting only for the test(s) that were executed.

**Comment by smaddox-sf** [comment]
We're making changes to this area!  Check out the spec and feel free to leave a comment with feedback - #2224 .  Closing this item to consolidate the conversion to the spec.
