### ISSUE TITLE
VSCode on Mac missing SFDX commands and menu items

### ISSUE THREAD

**Issue by foweyboy** [forcedotcom/salesforcedx-vscode#1449]
Following https://trailhead.salesforce.com/content/learn/projects/quick-start-lightning-web-components

Working on a Mac and there are some deviations in my experience compared to the instructions.

### Summary

Only 3 SFDX commands in VS Code Command Palette.
No SFDX options in context menu (right click)

### Steps To Reproduce:

1.  Installed Salesforce CLI : sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3
1.  Installed Java SKD 11
1.  Installed Visual Code (both standard and Insider) Version 1.36.0-insider (1.36.0-insider)
1.  Installed Salesforce Extension Pack 46.4.0 and dependencies, included recommended
1.  Checked running extensions, includes Lightning Web Components
1.  Created Trailhead playground, reset password, authorised Org
1.  Created new Project 'HelloWorldLightningWebComponent' (also tried new Project with Manifest)
1.  Saved locally to a folder
1.  Project includes folder structure including LWC folder

### Expected result

Should have full suite of SFDX commands in the VS Code Command Palette
Should have multiple SFDX options on context menu (right click)

### Actual result

1.  Typing SFDX into Command Palette only shows 3 options:
Create and Set Up Project for ISV Debugging
Create Project with Manifest
Create Project
1.  Therefore, unable to e.g. create Lightning Web Component as per Trailhead.
1.  Can create via Terminal (right click lwc folder in sidebar, open terminal, paste command:
`sfdx force:lightning:component:create --type lwc -n helloWorld`
1. Next step should be to deploy to Trailhead playground by right clicking the 'default' folder and clicking 'SFDX: Deploy Source to Org' - however there are no SFDX options on the right click (context menu)

### Additional information

_Feel free to attach a screenshot_.
![Screen Shot 2019-07-04 at 11 06 11 am](https://user-images.githubusercontent.com/42430002/60632950-c668bf00-9e4b-11e9-9f97-685a59523992.png)
![Screen Shot 2019-07-04 at 11 05 46 am](https://user-images.githubusercontent.com/42430002/60632951-c668bf00-9e4b-11e9-85bf-96c5761e36a3.png)
![Screen Shot 2019-07-04 at 11 05 36 am](https://user-images.githubusercontent.com/42430002/60632952-c668bf00-9e4b-11e9-8843-29ceb656f468.png)

**VS Code Version**:
Version 1.36.0-insider (1.36.0-insider)
**SFDX CLI Version**:
sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3
**OS and version**:
macIS Mojave 10.14.5 (18F132)

**Comment by alexkadis** [comment]
When this has happened to me, a workaround of reloading the window fixes it.

**Comment by lcampos** [comment]
@foweyboy can you clarify if you've authenticated to an org and set it as your project's default ? This can be done by running `SFDX: Authorize an Org`, `SFDX: Create a Default Scratch Org ...` or using the org picker feature (bottom left footer) to pick a previously authenticated org.

Assuming you've done this, there is a current issue where this does happen and one of the workarounds is the one mentioned by @alexkadis. We have a fix for that scenario coming out this week (PR #1456 ).

**Comment by foweyboy** [comment]
Hi

@alexkadis - I tried closing and reloading Visual Code many times - no change.

@lcampos - yes I have set a default org (AFAIK):
![Screen Shot 2019-07-10 at 3 02 23 pm](https://user-images.githubusercontent.com/42430002/60941923-13550580-a324-11e9-86bc-46ffccf9161a.png)

Great that there is a fix coming, thank you! Will the update install automatically or do I need to get it manually?

**Comment by lcampos** [comment]
@foweyboy if you didn't update VS Code to block automatic extension updates then you will once we release the new version to the marketplace.

**Comment by lcampos** [comment]
The fix for this is available in version `46.5.0` of the extensions.

**Comment by foweyboy** [comment]
Hi

I've open VS Code, restarted to update and checked that I am running the
latest version of the Salesforce extension:

[image: Screen Shot 2019-07-12 at 9.52.42 am.png]

Unfortunately my issue remains exactly the same.

Please let me know if you have any suggestions?

Thanks for your help

Matt

**Comment by lcampos** [comment]
@foweyboy did you test by creating a new scratch org or did you just re-open VSCode and tried using an org previously created ?
Also, are you still in version `7.8.1` of the cli ? Would it be possible for you to update to a more recent version ?

**Comment by foweyboy** [comment]
Hi

I ran the SFDX update command on Mac Terminal and it update from 7.13 to
7.14 - why am I so far behind!?

Also there was an unmet peer dependency:

[image: Screen Shot 2019-07-15 at 2.07.18 pm.png]

I connected to my existing developer org - I just found out that the org
did not have the Dev Hub enabled though? I've enabled it now and connected
again, can you check the below and let me know if this is correct or
something is wrong?

[image: Screen Shot 2019-07-15 at 2.30.31 pm.png]

It's not clear if this is successful or a failure.

Please let me know anything I can do!

Cheers

Matt

**Comment by MikeS-nth** [comment]
Hi -- I am having the exact same problem in Visual Studio Code.  I am following the Org Development Model.  After creating the project with manifest and then setting the default org, I still don't see any commands in the palette other than what @foweyboy has in last screenshot of his original post.

I've tried `Reload window`, restarting VS Code, and even completely uninstalling & reinstalling VS Code, with no luck.  

Versions:
MacOS: 10.14.6
SFDX CLI: 7.15.3
Salesforce Extension Pack v 46.7.0
Visual Studio Code 1.36.1

Any help or tricks are greatly appreciated!

**Comment by viktorvrabel** [comment]
Same here, Mac user.

**Comment by dbwelch** [comment]
Sme here, Mac user.
