### ISSUE TITLE
deploy option not coming

### ISSUE THREAD

**Issue by manvendra91** [forcedotcom/salesforcedx-vscode#1453]
Issue Type: <b>Bug</b>

I cannot find deploy option when I right click on 'default' folder in my .sfdc file uder my projet 'HELLOWORLDLIGHTNINGWEBCOMPONENT'

Extension version: 46.4.0
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ntotten** [comment]
The deploy option is only on folders that are allowed to be deploy. Try right clicking on a folder with metadata like `classes`
