### ISSUE TITLE
Rename Symbol not always working

### ISSUE THREAD

**Issue by gbreavin** [forcedotcom/salesforcedx-vscode#1454]
### Summary

I was reviewing a PR and wanted to rename a method with a clearer name. Using "Rename Symbol" did not update a reference to the method in another class.

Note that I renamed a variable (using Rename Symbol) within the method being renamed before trying to rename the method.

I restarted VS Code and it behaved as expected output below. So I've included repro steps below, but might not work. Hopefully this ticket can be a placeholder for gathering more information.

### Steps To Reproduce:

These were the steps as closely as I can get them, though not sure if it'll reproduce the problem!

1.  Create classes as per below
1.  In ```method1```, right click on ```opps``` and use Rename Symbol
1.  Now right click on ```method1``` and use Rename Symbol on the method

```
public with sharing class Class1 {
    public static List<Opportunity> method1(List<Id> ids) {
        List<Opportunity> opps = new List<Opportunity>();
        opps = [SELECT Id FROM Opportunity WHERE Id IN :ids];
        return opps;
    }
}
```

```
public interface MyInterface {
    void method2();
}
```

```
public with sharing class Class2 implements MyInterface {
    public void method2() {
        Class1.method1(new List<Id>);
    }
}
```

### Expected result

The name of ```method1``` should be updated in Class1, as well as the reference to ```method1``` in Class2.

### Actual result

The method reference in Class2 was not updated.

### Additional information

I re-started VS Code and the above repro steps did not reproduce the issue. When the issue occurred, VS Code had not been open for long, so if this does happen occur for other people, hopefully we'll get more info as to what steps reliably reproduce the issue.

**VS Code Version**: 1.36

**SFDX CLI Version**: sfdx-cli/7.14.0-bd96f098e0 darwin-x64 node-v10.15.3

**OS and version**: MacOS Mojave 10.14.5

**Comment by praksb** [comment]
@gbreavin It is possible that there were some unsaved edits that might have resulted in semantic errors which may have caused Rename to not succeed as you expected. I am going to close this issue for now since I am not able to repro as well. Please reopen if you or someone else has a reliable repro if this occurs again. Thanks!
