### ISSUE TITLE
Japanese localization

### ISSUE THREAD

**Issue by shunkosa** [forcedotcom/salesforcedx-vscode#1455]
Hello team, I'm interested in Japanese localization for this extension. Is it welcomed? If so, I just localized `package.nls.json` of `salesforcedx-vscode-core`, and I'm wondering how to determine the size of pull request. Should I localize all the `package.nls.json` and `i18n.ts` at once?

<img width="500" alt="スクリーンショット 2019-07-08 21 38 09" src="https://user-images.githubusercontent.com/1404346/60810763-c872ab00-a1c8-11e9-80ae-2123cd31dc05.png">
<img width="300" alt="スクリーンショット 2019-07-08 21 38 25" src="https://user-images.githubusercontent.com/1404346/60810759-c6105100-a1c8-11e9-8b43-4d6bde8cbadc.png">

**Comment by ntotten** [comment]
This would be amazing! We'd love to have you contribute this. I'd say it's up to you in terms of how you want to do it, but I would think doing everything in one PR is fine.

**Comment by vazexqi** [comment]
@ruthemmanuelle, @hbc-bindu  - Could you provide some guidance (or existing resources) that could help with the terminology?

I was about to point @shunkosa to https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm to ensure that we are using consistent terminology, but I just realized that was not localized into Japanese.

Thinking out loud: I want to ensure that we provide guidance first before we start localizing to avoid  wasted work.

Some context, when I first did https://github.com/microsoft/vscode-extension-samples/pull/21 it was under the assumption that an external contributor who wanted to help us localize would be able to do so easily, and we (Salesforce) would be able to provide some guidance on terminology for consistency.

**Comment by shunkosa** [comment]
Thank you! I'm going to create a single PR. Now I'm referring to Salesforce DX Developer guide, which is translated into Japanese. Release note and help articles too.
https://developer.salesforce.com/docs/atlas.en-us.218.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_develop.htm
For consistency, I'll review my work enumerating key and value from the all message files by a light script. I think it becomes a dictionary, but if there is an existing guidance, it would be really helpful.

**Comment by rbuschiazzo** [comment]
Hi @shunkosa we've just translated part of this doc into Japanese https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/migrate-from-forcecom-ide. See attached files. 

[Force.com migration pages_ja.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/3370494/Force.com.migration.pages_ja.zip)

And here is our Japanese Style Guide.

[style_guide_ja.pdf](https://github.com/forcedotcom/salesforcedx-vscode/files/3370498/style_guide_ja.pdf)

Let me know if you have any questions. I manage product localization, UI and content, and our team can certainly help you.

**Comment by shunkosa** [comment]
@rbuschiazzo I wonder if you could review or assign someone for #1551 ? Should I provide an additional explanation of this work? (like a comparison spreadsheet or something like that)
