### ISSUE TITLE
slds-* css class autocompletion for LWC

### ISSUE THREAD

**Issue by vmarasow** [forcedotcom/salesforcedx-vscode#1461]
**Describe the solution you'd like**
When editing the html file in an LWC component I find myself using lots of css classes from the lightning design system, it would be nice for the autocompletion to kick in so I don't need to look up the specific class names/variations on the design system website.

**Comment by Shababsoft** [comment]
The autocompletion for "slds-*" should be available for AURA component and Visualforce page as well.

**Comment by vc4u** [comment]
We can now use following VS Code Extension from Salesforce, it support quick checks and provide suggestions for regular custom CSS to be replaced with tokens or standard SLDS CSS class. Also, supports auto-complete of css class names as well:

https://marketplace.visualstudio.com/items?itemName=salesforce.salesforce-vscode-slds

**Comment by sagar539** [comment]
SLDS validator extension does not provide classes IntelliSense.

**Comment by smaddox-sf** [comment]
Hi @sagar539 - You are posting on a closed issue.  Please log a new issue on the SLDS repo so the team can review - https://github.com/forcedotcom/salesforcedx-vscode-slds/issues
