### ISSUE TITLE
Right click deploy/retrieve options missing when defaultusername is set to scratch org alias

### ISSUE THREAD

**Issue by haraldmayer** [forcedotcom/salesforcedx-vscode#1462]
### Summary

When being connected to a scratch org per alias, deploy/retrieve options are missing from right-click menu. When connecting to a scratch org per full username, deploy/retrieve options show as expected.

### Steps To Reproduce:

1) $ sfdx force:config:set defaultusername=myscratchorgalias
2) right click on a a resource in the package directory (let's say on force-app/main/default/classes/MyClass.cls)
3) options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" are missing
4) $ sfdx force:config:set defaultusername=myscratchorg@fullusername.com
5) right click on a a resource in the package directory (let's say on force-app/main/default/classes/MyClass.cls)
6) options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" show up

### Expected result

See the options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" when right-clicking a resource when connected to a scratch org - no matter if connected via alias or full username

### Actual result

We do **not** see the options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" when right-clicking a resource when connected to a scratch org via alias. We do so when connected to the same scratch org via full username

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.36.0

**SFDX CLI Version**:
7.14.0-bd96f098e0

**OS and version**:
Windows 10

**Comment by brpowell** [comment]
Hi @haraldmayer. The Deploy and Retrieve commands are only available through the UI when developing against a non-scratch org (i.e. sandbox or production). When a scratch org is set as the default org, you'll instead see SFDX: Push Source to Default Scratch Org in the command palette.

**Comment by haraldmayer** [comment]
@brpowell thanks for your response! I don't fully agree though: If I develop in VS code with a scratch org as default org, set as default via full username, not alias, I get the deployment option, and can deploy individual files (wich triggers a force:source:deploy), additional to being able to push source from command palette (which triggers a force:source:push). 

I agree that it is questionable if one would want to use source:deploy to a scratch org when we have source:push : my motivation was the hope that when only editing a single file, source:deploy would be faster than a source:push (which as I understand has some overhead of checking the diff and identifying what needs to be deployed).

**Comment by lcampos** [comment]
@haraldmayer as @brpowell mentioned this is done by design because using `source:push` & `source:pull` allows the user to catch potential conflicts with changes between the org and your local e.g. potentially overwriting changes done directly in the org.

Having said that, we are currently working on changes to speed up the deploy experience for single files regardless of you using `source:push` or `source:deploy`.

Regarding individual file deploys when of a larger change fails on `source:push`, that's feedback we've heard from other costumers and the CLI team is thinking about how to approach that.
