### ISSUE TITLE
Multi-line block comments do not insert an asterisk in Apex

### ISSUE THREAD

**Issue by erocheleau** [forcedotcom/salesforcedx-vscode#1469]
### Summary

When trying to document an Apex class using Javadoc comment format, there is no proper multi-line formatting being triggered or a new asterisk being added on the new line after pressing enter.

What should happen:
```
/**
 *
 */
```

What is currently happening:
```
/**

 */
```

### Steps To Reproduce:

1.  Open an Apex class.
2. Start typing `/**`
3. It will auto-complete with `/**| */` ( | is the cursor)
4. Press Enter.

### Expected result

What should happen:
```
/**
 *
 */
```

### Actual result

What is currently happening:
```
/**

 */
```

### Additional information

I have tried with other extensions that claim to handle multi-line comments for you as well. But none of them did any difference for this issue.

**VS Code Version**: `1.36.0`

**SFDX CLI Version**: `sfdx-cli/7.13.0-27dbcb37d3 win32-x64 node-v10.15.3`

**OS and version**: `WIN 10 x64`

**Comment by eclarke12** [comment]
+1 if we can also get ApexDoc/JavaDoc stub-creation (ie. auto-generate `@params` `@returns` etc that would be a bonus

**Comment by erocheleau** [comment]
@eclarke12 oh yes for sure that would be useful too!

**Comment by ralphcallaway** [comment]
fwiw, if someone is feeling like coding this could be done by cloning an existing vs code java doc extension and expanding the supporting language definitions to include apex. pre-sfdx when i used st3 i used the docblockr extension to this effect and it worked great, but with vs code you have to explicitly list which languages your extension supports which limits the ability to use plugins for this sort of things with languages they weren't explicitly designed for

**Comment by danielepiccone** [comment]
@ralphcallaway thank you for the hint! 
This issue annoyed me for a log time and decided to give it a shot today.
I have opened a PR here with the changes https://github.com/forcedotcom/salesforcedx-vscode/pull/1847/files. 
The code is entirely cloned from the vscode-java extension.

**Comment by eclarke12** [comment]
Thanks @danielepiccone ! Excited to see if this gets accepted.

**Comment by lcampos** [comment]
Closing this since it got released as part of version 47.17.1

**Comment by erocheleau** [comment]
Thank you very much!
