### ISSUE TITLE
push failed 

### ISSUE THREAD

**Issue by hellosibun** [forcedotcom/salesforcedx-vscode#1475]
push failed showing using sfdx cli command on windows 
![image](https://user-images.githubusercontent.com/34995065/61198245-8d0b3b80-a6f6-11e9-8e7c-cff4aee87be3.png)
i even update sfdx cli using command sfdx update

**Comment by lcampos** [comment]
This does not look like an issue with the tool but an issue with the way you coded the AccountMap component.
