### ISSUE TITLE
SFDX: Update Checkpoints in Org fails

### ISSUE THREAD

**Issue by wishwa** [forcedotcom/salesforcedx-vscode#1476]
### Summary

When running the SFDX: Update Checkpoints in Org command from the VS Code palette, I receive the following error in the Output window.

**Checkpoints can be set on valid line of Apex source. Invalid checkpoint location:...**

### Steps To Reproduce:

1.  Toggle a check point by using '>SFDX: Toggle checkpoint' command
2.  Then open the command pallet and type SFDX: Update Checkpoints in Org.

### Expected result

Check point should update in Org.

### Actual result

Checkpoints can be set on valid line of Apex source. Invalid checkpoint location:....

`Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
Checkpoints can be set on a valid line of Apex source. Invalid checkpoint location: URI=file:///Users/wishwa/Documents/R%20%26%20D/VSCode/debugger-project/force-app/main/default/classes/AccountService.cls, Line=11
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again.`

### Additional information

_Feel free to attach a screenshot_.
<img width="1061" alt="Screen Shot 2019-07-14 at 6 30 08 PM" src="https://user-images.githubusercontent.com/3252032/61203787-090e7f00-a709-11e9-977e-715bfba45cc7.png">

**VS Code Version**: Version 1.36.1 (1.36.1)

**SFDX CLI Version**: sfdx-cli/7.14.0-bd96f098e0 darwin-x64 node-v10.15.3

**OS and version**:  MacOS Mojave verion 10.14.5

**Comment by lcampos** [comment]
Looks like you did some edits to the class before trying to update the checkpoints. Did you push/deployed those changes to the org before running `SFDX Update Checkpoints in Org` ?

**Comment by wishwa** [comment]
Hi lcampos,

All the edits have been deployed to the Source Org be for do the `SFDX Update Checkpoints in Org`
Could you please let me know what are the information that you guys required more?

Thanks,
Wishwa

**Comment by rickyloweSP** [comment]
Hi @wishwa did you work out what the error is? I am also receiving the same error.

**Comment by wishwa** [comment]
@rickyloweSP No mate, I haven't got a resolution for it.

**Comment by wishwa** [comment]
Hi All,

I have updated to latest versions but still I get the same error
Salesforce Extension pack : 46.11.0
VSCode version: July 2019 (version 1.37)
SDFX version: sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3

Looking forward to get any workaround with this issue

Thanks in advanced,
Wishwa

**Comment by wishwa** [comment]
> Hi @wishwa did you work out what the error is? I am also receiving the same error.

Hi Ricky,

Have you able to figure out the problem? Still I'm getting the error.

Thanks ,
Wishwa

**Comment by klampert** [comment]
I've spent hours trying to determine why I'm getting the "Invalid checkpoint location" error mentioned here (when trying to run "Update Checkpoints in Org") as well as "unverified breakpoints" when running the replay debugger.  I went so far as to completely remove then reinstall VS Code, the Salesforce CLI and the Salesforce Extension Pack but still, nothing worked.  As a test I went through the Trailhead for the replay debugger, which worked.  I noticed the path for that project folder had **no spaces**, so I redid my project path to remove all spaces and **now** everything is working fine.

**Comment by wishwa** [comment]
Hi Klampert,

Thanks for informing me about the steps that you follow, My problem was with the **"&"** character in the path. 

Thanks,
Wishwa

**Comment by eltoroit** [comment]
I had "+" on the name of the root folder. There are spaces in the full path, but that does not matter... It's the name/folder of the project.

**Comment by calejohn5** [comment]
Does anyone have a recent solution to this problem? My problem is exact to this but fails on step 2 (Retrieving source and line information)
My file path is "/home/admin/1RANDOMDUMP/debuggerproject" and I spent hours redoing the project with different names/setting the checkpoint in dev console and no prevail.

**Comment by crm-ops** [comment]
This is also true for all special characters such as é è in french that get converted to & when the string is transformed in a http url ...

**Comment by JCripe-AuthorSolutions** [comment]
This problem started last week for me.

Here's an example path error:

Checkpoints can be set on a valid line of Apex source. Invalid checkpoint location: URI=file:///c:/Users/myusername/sfdxProjects/20211101%20SandboxName/force-app/main/default/classes/ClassName_Test.cls

The file paths start with "file:///".  It should be "file://" or "file:////" if it is trying to escape the slashes?

Also, I see paths generated include %20 for a space character.  Should it?

**Comment by JCripe-AuthorSolutions** [comment]
I deleted a space in the project name and that fixed the problem.

**Comment by avanmeer** [comment]
Restarting vscode worked for me.

**Comment by dhogue84** [comment]
I had a number in my project's folder name. I changed it from `Trailhead2` to `Trailhead`, and it updated as expected.

**Comment by craggleb** [comment]
It shouldn't matter what the file path is... that a space of number breaks it is rediculous. The debug feature is not working, please fix it.
