### ISSUE TITLE
After authenticating my sandbox with vsCode- error coming

### ISSUE THREAD

**Issue by rohitbhushan** [forcedotcom/salesforcedx-vscode#1477]
### Summary

_After authenticating my sandbox with vsCode- error comming

### Steps To Reproduce:

1.  Open vs code
2. Authorize the org you want to develop against. To start the login process, open the command palette and run SFDX: Authorize an Org.  
3. Browser opened but received error as below.

### Expected result

_Org should be authenticated 

### Actual result

_Error came
This site can’t be reached

localhost refused to connect.
Search Google for localhost 1717 Oauth Redirect
ERR_CONNECTION_REFUSED

### Additional information

Error message :
This site can’t be reached

localhost refused to connect.
Search Google for localhost 1717 Oauth Redirect
ERR_CONNECTION_REFUSED
_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
Please provide the following info so we can try and replicate what you're running into.

- Salesforce CLI version. Run `sfdx --version` on your terminal.
- VS Code version. e.g. 1.35.1
- Salesforce extensions for VS Code version. e.g. 46.5.0
- OS version. e.g. Windows 10

**Comment by rohitbhushan** [comment]
-sfdx-cli/7.8.1-8f830784cc win32-x64 node-v10.15.3
-Salesforce extensions for VS Code version. - . 46.5.0-
Window 10

**Comment by abuwahid16** [comment]
Duplicated issue: https://github.com/forcedotcom/salesforcedx-vscode/issues/1558
