### ISSUE TITLE
Settings should not require editing JSON for simple primitive types

### ISSUE THREAD

**Issue by paustint** [forcedotcom/salesforcedx-vscode#1494]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I have to edit the JSON version of settings for basic strings/numbers/boolean settings

**Describe the solution you'd like**
VSCode settings should be structured in a way to allow UI configuration.

**_From Docs:_**
> Entries of type number 4️⃣ , string 5️⃣ , boolean 6️⃣ can be edited directly in the Settings UI.

**Describe alternatives you've considered**
Painful settings. ;(

**Additional context**

**Comment by brpowell** [comment]
Resolved in #1502
