### ISSUE TITLE
Enabled deploy/retrieve/delete on Scratch Orgs

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1510]
Now that the CLI supports deploy/retrieve/delete on scratch orgs we should allow this option for customers who want to. Similar to Illuminated Cloud:

![image](https://user-images.githubusercontent.com/282782/61881938-78346200-aec5-11e9-943d-3c949c6ff988.png)

**Comment by lcampos** [comment]
In this scenario a user would not have conflict detection, which is one of the benefits of using push/pull. Will a user understand that's what they are giving up ?

**Comment by holapancho** [comment]
what is the status about that?

**Comment by brno32** [comment]
I want this

**Comment by aimaj-anz** [comment]
+1 for this, or at least a toggle to remove the feature suppression for scratch orgs

with the failure rate of push/pull when constantly switching large branches for reviewing and merging, this would be invaluable instead of typing out directory, path, or metadata type based deploy commands

**Comment by smaddox-sf** [comment]
We have work inflight that will make push/pull and deploy/retrieve interoperable.  As that foundational work is complete, we'll be loosening up the options exposed in VS Code.
