### ISSUE TITLE
SFDX: Create Project failed to run

### ISSUE THREAD

**Issue by pksalesforce** [forcedotcom/salesforcedx-vscode#1512]
10:58:27.680 sfdx force:project:create --projectname Zendev1 --outputdir c:\Users\UserName\Documents\VsCode --template standard --manifest
Error: Unrecognized flag: {"name":"projectname","char":"n","required":true,"description":"name of the generated project","longDescription":"The name for the new project. Any valid folder name is accepted.","type":"string","values":[]}
    at flags.forEach.flag (C:/Program Files/Salesforce CLI/client/node_modules/force-language-services/dist/common/main/LegacyCommand.js:77:31)
    at Array.forEach (<anonymous>)
    at Function.toFlagsConfig (C:/Program Files/Salesforce CLI/client/node_modules/force-language-services/dist/common/main/LegacyCommand.js:28:19)
    at Object.<anonymous> (C:/Program Files/Salesforce CLI/client/node_modules/force-language-services/dist/oclif/force/project/create.js:31:66)
    at Module._compile (C:/Program Files/Salesforce CLI/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at LazyLoader.loadModule (C:/Program Files/Salesforce CLI/client/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:139:21)
    at Function._load (C:/Program Files/Salesforce CLI/client/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:115:29)
    at require (C:/Program Files/Salesforce CLI/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at fetch (C:/Program Files/Salesforce CLI/client/node_modules/@oclif/config/lib/plugin.js:101:21)
    at Plugin.findCommand (C:/Program Files/Salesforce CLI/client/node_modules/@oclif/config/lib/plugin.js:115:21)
    at Object.load (C:/Program Files/Salesforce CLI/client/node_modules/@oclif/config/lib/plugin.js:48:72)
10:58:30.667 sfdx force:project:create --projectname Zendev1 --outputdir c:\Users\Username\Documents\VsCode --template standard --manifest ended with exit code 1

**Comment by lcampos** [comment]
@pksalesforce which Salesforce CLI version are you using? Do you have any CLI plugins installed?
You can run `sfdx --version` and `sfdx plugins` in your command line to get that info.

**Comment by pksalesforce** [comment]
sfdx --version
sfdx-cli/7.8.1-8f830784cc win32-x64 node-v10.15.3

sfdx plugins
no plugins installed

I do have Salesforce CLI not sure why it says no plugins

**Comment by lcampos** [comment]
That's an old version of the cli, we're currently in version 7.15. Can you update your cli and try again ? You can do this by running `sfdx update`

The CLI allows you to install plugins on top of it in case you want additional functionality. You don't need to install additional plugins, I just wanted to get a better idea about your cli setup.

**Comment by pksalesforce** [comment]
That worked. Thank You

**Comment by lcampos** [comment]
Glad it worked, I'll close this issue now. If you run into anything else please open a new issue.

**Comment by shivanand11totar** [comment]
Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Veeresh>sfdx plugins:install salesforcedx@latest
Successfully validated digital signature for salesforcedx.
Finished digital signature check.
warning "salesforcedx > @salesforce/sfdx-plugin-lwc-test > @oclif/command@1.5.20" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin salesforcedx... installed v48.13.1

C:\Users\Veeresh>

**Comment by shivanand11totar** [comment]
23:30:40.48 sfdx force:project:create --projectname VSCodeQuickstart --outputdir f:\SFDX --template standard
 ended with exit code 1

Starting SFDX: Create Project

23:48:48.23 sfdx force:project:create --projectname VSCodeQuickstart --outputdir f:\SFDX --template standard
ERROR running force:project:create:  Command failed with exit code 1: npm root -g --prefix f:\SFDX\.yo-repository --loglevel error
'npm' is not recognized as an internal or external command,
operable program or batch file.
23:49:30.244 sfdx force:project:create --projectname VSCodeQuickstart --outputdir f:\SFDX --template standard
 ended with exit code 1

**Comment by shivapathaql** [comment]
> 23:30:40.48 sfdx force:project:create --projectname VSCodeQuickstart --outputdir f:\SFDX --template standard
> ended with exit code 1
> 
> Starting SFDX: Create Project
> 
> 23:48:48.23 sfdx force:project:create --projectname VSCodeQuickstart --outputdir f:\SFDX --template standard
> ERROR running force:project:create: Command failed with exit code 1: npm root -g --prefix f:\SFDX.yo-repository --loglevel error
> 'npm' is not recognized as an internal or external command,
> operable program or batch file.
> 23:49:30.244 sfdx force:project:create --projectname VSCodeQuickstart --outputdir f:\SFDX --template standard
> ended with exit code 1

I am also facing the same issue and I checked for CLI update as well.

**Comment by manojkparidavzc** [comment]
Upgrading sfdx worked

**Comment by saadmohammed** [comment]
I too came across with the same issue, I mean unable to create a project in vs code.
configurations are up-to-date
Salesforce CLI
Salesforce Extension Pack
Node
npm
Java 11
VS Code
I tried lot for few days...
Problem for me is cached(old data), 
I created a new project in a new window, magic happens it worked for me...
Hope this will help.
