### ISSUE TITLE
SLDS linter not working in Lightning Web Components

### ISSUE THREAD

**Issue by DNLZ** [forcedotcom/salesforcedx-vscode#1515]
### Summary

Salesforce Lightning Design System (SLDS) linter is not working for LWCs

### Steps To Reproduce:

1.  Open a LWC
1.  Add a slds class to an element
1.  Try to manipulate it in ways to fire the linter

### Expected result

The linter should do something

### Actual result

The linter does nothing.

### Additional information

Feature I'm referring to:
![image](https://user-images.githubusercontent.com/1908828/61989528-fee45e80-afed-11e9-8823-608ddb3f3899.png)

**VS Code Version**: Version 1.36.1 (1.36.1)

**SFDX CLI Version**: sfdx-cli/7.13.0-27dbcb37d3 darwin-x64 node-v10.15.3

**OS and version**: MacOS Mojave 10.14.5 (18F132)

**Comment by ntotten** [comment]
This is just a bug in the docs. We haven’t shipped SLDS linting for LWC yet. Coming soon.
