### ISSUE TITLE
"Go to Definition" and "Peek Definition" not working for VS Code

### ISSUE THREAD

**Issue by sandynirankari** [forcedotcom/salesforcedx-vscode#1519]
### Summary

"Go to Definition" and "Peek Definition" is not working. Here is what I get on Apex Language server output ::

<img width="1093" alt="Screen Shot 2019-07-30 at 3 08 56 PM" src="https://user-images.githubusercontent.com/14543604/62118829-fb95ef00-b2db-11e9-9076-2a0c20b7f3b8.png">

Also, I have code in different folders/repo under this project, so not sure if the issue is beacuse of that.

<img width="309" alt="Screen Shot 2019-07-30 at 3 10 03 PM" src="https://user-images.githubusercontent.com/14543604/62118924-30a24180-b2dc-11e9-9531-6abbb4053629.png">

### Steps To Reproduce:

1.  Create a new project after installing the extension.
2. Create multiple folders cloning different dependent repos.
3. Go to definition doesn't work and you can see issues under "Problems" tab. However, the file when saved, complies fine.

### Expected result

"Go to Definition" and "Peek Definition" should work.

### Actual result

"Go to Definition" and "Peek Definition" doesn't work.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: Version 1.36.1 (1.36.1)

**SFDX CLI Version**:

<img width="485" alt="Screen Shot 2019-07-30 at 3 13 15 PM" src="https://user-images.githubusercontent.com/14543604/62119165-9989b980-b2dc-11e9-85a7-dfd1fa54c1f7.png">

**OS and version**: macOS Sierra 10.12.6

**Comment by praksb** [comment]
@sandynirankari The screenshot that you have posted shows logs from the OUTPUT tab of the window. It doesn't indicate any issues. The PROBLEMS tab of the window shows some errors. These are compiler errors from the Apex classes/triggers in the project. Is it possible that you are invoking "Go to Definition" and "Peek Definition" on a symbol that has errors? This may happen when compiler fails to bind for example like when an SObject type is missing. Have you tried running "Refresh SObject Definitions"?
