### ISSUE TITLE
Why is command execution time 3x test time?

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#1523]
Why would a Test complete in 7s but the command takes 21 to finish?

<img width="353" alt="BraintreePaymentProcessBatchTest_cls_—_rs-sfdc" src="https://user-images.githubusercontent.com/5217568/62271460-ef05b980-b3f5-11e9-96b2-c5bd354744da.png">

Where's the extra overhead coming from?

**Comment by ChuckJonas** [comment]
To make matter worse... this `Command Time` isn't even accurate... I'm finding that it's taking around a minute to finish a single test but the command time says only 12s.


https://drive.google.com/file/d/1wK3yvkkFA8XSR1sm5MESQ0PfNgsd34x7/view?usp=sharing

**Comment by ChuckJonas** [comment]
Looks like if I set `"salesforcedx-vscode-core.retrieve-test-code-coverage": false,` things speed up tremendously. 

However, I'm confused why retrieving code coverage would take SOOO long.  If I run the same test with code coverage from the dev console it still returns in a reasonable amount of time

**Comment by marcellcsiszar** [comment]
I experiencing the same

**Comment by diyer** [comment]
Closing this as this is an old issue and we no longer have command time displayed in output
