### ISSUE TITLE
force:source:deploy:report Error: INVALID_CROSS_REFERENCE_KEY

### ISSUE THREAD

**Issue by troveryor** [forcedotcom/salesforcedx-vscode#1529]
### Summary
Ran force:source:deploy with a manifest package.xml from bash in VSCode, with --wait 0
When it returned with an ID to check on status I ran the suggested command and was presented with an error.

Like so:
me@PC2 /Salesforce/Development/staging (branch)
$ sfdx force:source:deploy -x "[path_to]/package.xml" -u someuser --wait 0
=== Status
Status: Queued
Id: 0Af2g000003QzqHCAS

Run sfdx force:source:deploy:cancel -i 0Af2g000003QzqHCAS to cancel the deploy.
Run sfdx force:source:deploy:report -i 0Af2g000003QzqHCAS to get the latest status.

me@PC2 /Salesforce/Development/staging (branch)
$ sfdx force:source:deploy:report -i 0Af2g000003QzqHCAS
ERROR running force:source:deploy:report:  INVALID_CROSS_REFERENCE_KEY: invalid cross reference id

### Steps To Reproduce:

1.  run sfdx force:source:deploy  using a manifest with --wait 0
2.  copy/paste the report command provided and observe error

### Expected result

A status of some sort on the job with the ID provided.

### Actual result

ERROR running force:source:deploy:report:  INVALID_CROSS_REFERENCE_KEY: invalid cross reference id

### Additional information

**VS Code Version**: 1.36.1

**SFDX CLI Version**: sfdx-cli/7.18.0-ee5dc8194c win32-x64 node-v10.15.3

**OS and version**: windows 10

**Comment by lcampos** [comment]
@troveryor thanks for opening this issue. I was only able to replicate this behavior by querying for a deploy report on a project that didn't have a `defaultusername` and I didn't add the `-u` to the command (`sfdx force:source:deploy:report` -i <deploy id>`). Which means I was querying for a deploy id against a different org, in my case it was the one I globally set as my default username.

When I did run it with the username of the org I originally deployed to I got the expected output. Can you confirm this is what's happening ?

Here's what I got when I ran that command against the org that I deployed to.

```
x-machina:testproject myuser$ sfdx force:source:deploy:report -i 0Af2M00001r2Z4sSAE

=== Status
Status:  InProgress
jobid:  0Af2M00001r2Z4sSAE
Component errors:  0
Components deployed:  37
Components total:  38
Tests errors:  0
Tests completed:  0
Tests total:  0
Check only: false

Deployment finished in 8000ms

=== Result
Status:  Succeeded
jobid:  0Af2M00001r2Z4sSAE
Completed:  2019-08-07T00:57:27.000Z
Component errors:  0
Components deployed:  38
Components total:  38
Tests errors:  0
Tests completed:  0
Tests total:  0
Check only: false
```

**Comment by troveryor** [comment]
Yup, looks like that's exactly the situation: no defaultusername, and no -u switch on the command.
Providing a username solves the issue for me.

It might be nice to have something to that effect referenced in the command listed for "get latest status". As it stands the less sophisticated among us, like me, will consider it to be a usable  as-is command. 

Either way, it's not exactly difficult to open the org and check the deploy progress anyway.
thanks for checking it out @lcampos

**Comment by floralan** [comment]
@troveryor Our extension packages have changed a lot since 2019, we no longer use CLI command to do Deploy/Retrieve. Please try to use Deploy/Retrieve commands our latest extension version and it should resolve this issue.
