### ISSUE TITLE
Add in the new Org Browser feature the possibility to export selected metadata in a package.xml file

### ISSUE THREAD

**Issue by gvgramazio** [forcedotcom/salesforcedx-vscode#1538]
I'm always frustrated when use metadata (i.e. always). A lot of metadata types do not support the wildcard character and one has to rely on third part applications to simply have the list of metadata in an org.

Now, with the introduction of the new Org Browser feature, the work is more easy and less frustrating but right now it is an alternative to use package.xml files or a simple helper to compile one by hand.

Wouldn't be great if it has also the capability to export the list of selected metadata in a package.xml file?

Personally I would like it a lot but I don't think I'm alone.

**Comment by ntotten** [comment]
We will be doing this. See #862 for more details. Closing as duplicate.
