### ISSUE TITLE
Unable to Authorise salesforce org

### ISSUE THREAD

**Issue by kushal33** [forcedotcom/salesforcedx-vscode#1539]
Issue Type: <b>Bug</b>

When I try to run a command called authorize an salesforce org it is opening login in browser for oauth and then when I do login it is showing no reponse error in browser for localhost:1717 url

SFDX CLI version: sfdx-cli/7.18.0-ee5dc8194c win32-x64 node-v10.15.3
Extension version: 46.8.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Refer Below Screenshots:**
![proof_1](https://user-images.githubusercontent.com/3923184/62534047-c18d9580-b865-11e9-9113-249c683b3743.png)
![proof_2](https://user-images.githubusercontent.com/3923184/62534052-c6eae000-b865-11e9-827e-a91038bcad89.png)

**Comment by lcampos** [comment]
Are you behind a firewall or does your machine block the use of port 1717 ?

**Comment by jeromegv** [comment]
Same issue. I do not have a firewall or a proxy on Mac OS X. This used to work, I have no idea what is suddenly blocking port 1717

**Comment by kushal33** [comment]
> Are you behind a firewall or does your machine block the use of port 1717 ?

No. I am not behind firewall.
My device is not blocking the use of port 1717.
I verified that port 1717 is open in my machine via cms

**Comment by lcampos** [comment]
Ok, I haven't been able to replicate it yet but could you confirm if this still happens when you run the command directly from the terminal and not from VSCode UI. I want to see if we can pinpoint if the issue is with the extension or the cli.

**Comment by kushal33** [comment]
> Ok, I haven't been able to replicate it yet but could you confirm if this still happens when you run the command directly from the terminal and not from VSCode UI. I want to see if we can pinpoint if the issue is with the extension or the cli.

It is happening for both above scenarios.
I tried launching it from VS Code UI as well as Terminal and in both case it isnt working

**Comment by ntotten** [comment]
Likely due to https://success.salesforce.com/issues_view?id=a1p3A0000003dkDQAQ
