### ISSUE TITLE
SSO: Single Sign On: SFDX: Authorize an Org failed to run

### ISSUE THREAD

**Issue by itsunil** [forcedotcom/salesforcedx-vscode#1544]
SSO: Single Sign On: SFDX: Authorize an Org failed to run

http://localhost:1717/OauthRedirect?code=XXXXX&state=XXXXXX

This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by jeromegv** [comment]
Same issue here, just stopped working.

**Comment by joeythomaschaske** [comment]
Might be related https://status.salesforce.com/generalmessages/239

**Comment by ntotten** [comment]
Closing as this is a resolve of this issue: https://success.salesforce.com/issues_view?id=a1p3A0000003dkDQAQ
