### ISSUE TITLE
SFDX: Refresh SObject Definitions not getting standard and custom fields

### ISSUE THREAD

**Issue by jokerLu** [forcedotcom/salesforcedx-vscode#1546]
### Summary

After I run "SFDX: Refresh SObject Definitions" command, the autocompletion doesn't return standard and custom fields from objects.

### Steps To Reproduce:

1.  Initiated a custom object and create a record
`Bello_PNumber__c parentPNum1 = new Bello_PNumber__c()`
1.  This is step 2. All steps should start with '1.'
`parentPNum1.`

### Expected result

I expect to see the SObject Instance's fields (standard and custom fields)

### Actual result

<img width="474" alt="Screen Shot 2019-08-08 at 1 25 15 PM" src="https://user-images.githubusercontent.com/22925678/62724077-266cfb00-b9e0-11e9-8393-c03eaa251ea1.png">

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.36.1
**SFDX CLI Version**:
7.18.0-ee5dc8194c
**OS and version**:
macOS 10.14.1

**Comment by steals** [comment]
It looks like autocomplete works only for instance variables, i.e. Bello_PNumber__c parentPNum1 = new Bello_PNumber__c(); parentPNum1. but doesn't work if you referece object as a class.

**Comment by jokerLu** [comment]
> It looks like autocomplete works only for instance variables, i.e. Bello_PNumber__c parentPNum1 = new Bello_PNumber__c(); parentPNum1. but doesn't work if you referece object as a class.

That makes sense. Thanks!
