### ISSUE TITLE
Apex Replay Debugger couldn't run debug log in a scratch org with namespace

### ISSUE THREAD

**Issue by garychenming** [forcedotcom/salesforcedx-vscode#1553]
### Summary

You can launch the Apex Replay Debugger with a debug log file, but it just terminated when you click the continue button.

### Steps To Reproduce:

1.  Create a new Scratch org with namespace
2.  Turn on Apex Debug Log for Replay Debugger
3.  Run an apex test method 
4.  Get the test apex debug log
5.  Launch the Apex Replay Debugger with Current File
6. Click the blue continue button

### Expected result

The Replay Debugger stop at the first breakpoint.

### Actual result

The Replay Debugger terminated.

**VS Code Version**: Version: 1.37.0

**SFDX CLI Version**: sfdx-cli/7.19.0-c5be43915c darwin-x64 node-v10.15.3

**OS and version**: macOS 10.14.5

**Comment by lcampos** [comment]
Hi @garychenming , did you update your project's `sfdx-project.json` file with the org's namespace ? It should look something like this

```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "<my_namespace>",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "46.0"
}
```

**Comment by jonny-harte** [comment]
I'm running into the same issue. Yes I have added the namespace to the `sfdx-project.json`
