### ISSUE TITLE
"SFDX: Authorize an Org" not available

### ISSUE THREAD

**Issue by dennisvieth** [forcedotcom/salesforcedx-vscode#1554]
### Summary

"SFDX: Authorize an Org" command not available in VS Code

### Steps To Reproduce:

1.  Click command + shift + p and type "SFDX: Create new projekt with manifest"
2. Enter name etc.
3.  Search for "SFDX: Authorize an Org" - not found

### Expected result

"SFDX: Authorize an Org" should be offered

### Actual result

nothing

### Additional information

![image](https://user-images.githubusercontent.com/54021028/62853093-95519900-bceb-11e9-96b1-8bd1a51e67ed.png)

**VS Code Version**:
1.37.0

**SFDX CLI Version**:
![image](https://user-images.githubusercontent.com/54021028/62853164-c631ce00-bceb-11e9-925b-13958986e37c.png)

**OS and version**:
Mojave 10.14.6

**Comment by suraj07081995** [comment]
SFDX is not installed in your system.
Install Extension pack in VS Code [Salesforce Extension Pack].
If it is installed and the system is unable to recognize then run as an administrator.
Hope this hepls!

**Comment by dennisvieth** [comment]
> SFDX is not installed in your system.
> 
I think it is:



> If it is installed and the system is unable to recognize then run as an administrator.
> 

But it does recognise other sfdx commands: 



-- 
Mit freundlichen Grüssen / Kind Regards

Dennis Vieth    

+49 151 11326 805 (mobile)
+49 6196 77125.619 (fax)
dennis.vieth@entero.de <mailto:dennis.vieth@entero.de>
www.entero.de <http://www.entero.de/>

entero  |  we deliver


entero Aktiengesellschaft
Kölner Straße 12
65760 Eschborn, Germany
Amtsgericht Frankfurt, HRB 51231
Aufsichtsrat: Franco Nocera (Vorsitz)
Vorstand: Henning Heesch, Rainer Kirschnick
P Please consider the environment before printing this email

**Comment by suraj07081995** [comment]
Is Salesforce CLI  installed?

**Comment by suraj07081995** [comment]
if not then install salesforce cli and restart your vs code.

**Comment by dennisvieth** [comment]
It is, here is a screenshot from terminal (at least that’s how trailheads say how to figure it out).



I basically did the very same steps on another mac and there it did work instantly. That why I'm a bit struggling here


-- 
Mit freundlichen Grüssen / Kind Regards

Dennis Vieth    

+49 151 11326 805 (mobile)
+49 6196 77125.619 (fax)
dennis.vieth@entero.de <mailto:dennis.vieth@entero.de>
www.entero.de <http://www.entero.de/>

entero  |  we deliver


entero Aktiengesellschaft
Kölner Straße 12
65760 Eschborn, Germany
Amtsgericht Frankfurt, HRB 51231
Aufsichtsrat: Franco Nocera (Vorsitz)
Vorstand: Henning Heesch, Rainer Kirschnick
P Please consider the environment before printing this email

**Comment by suraj07081995** [comment]
@dennisvieth I didn't find screenshot!

**Comment by dennisvieth** [comment]
Right, by some reasons it was not properly pasted. But check the ticked, there is a screenshot of the terminal included was well

**Comment by suraj07081995** [comment]
Install salesforce CLI globally, using this command.

`npm install sfdx-cli --global`

**Comment by dennisvieth** [comment]
That command is not found:

Denniss-MBP-2:~ dennisvieth$ npm install sfdx-cli --global
-bash: npm: command not found

**Comment by dennisvieth** [comment]
Which is because I dont use Node.js
