### ISSUE TITLE
Mac/iOS support

### ISSUE THREAD

**Issue by xuzhang78** [forcedotcom/salesforcedx-vscode#1559]
I'm working on Salesforce lighting web development with Macbook and looking for the right tools.

Microsoft Visual Studio is the recommended code editor with Salesforce extension, but I found the extension is for Windows only.

Do you plan to release an extension for Macbook? Or any suggestions for other IDEs?

**Comment by ntotten** [comment]
Visual Studio Code is the recommended IDE. This is different than "Visual Studio" See the docs here: https://forcedotcom.github.io/salesforcedx-vscode/
