### ISSUE TITLE
Code coverage showing unknown color that isn't covered or uncovered

### ISSUE THREAD

**Issue by FishOfPrey** [forcedotcom/salesforcedx-vscode#1566]
### Summary

In addition to the expected covered/green/lime and the uncovered/red lines in the code coverage there is an additional color that is roughly between the other two. 

### Steps To Reproduce:

1.  Run all tests in the org
1.  Open the code coverage for a specific class. I was looking at the [SFDCAccessController.cls](https://github.com/forcedotcom/force-dot-com-esapi/blob/master/src/classes/SFDCAccessController.cls) from the ESAPI

### Expected result

Lines are one of:

- Covered / Green
- Uncovered / Red
- Not applicable / Uncolored

### Actual result

An additional line color measured as #5E5620 is showing up in some locations

### Additional information

Salesforce StackExchange Q - [Visual Studio Code Apex class code coverage colors](https://salesforce.stackexchange.com/q/273735/102)

![Screenshot of unknown coverage color](https://i.stack.imgur.com/E6aDh.png)

**VS Code Version**:
1.36

**SFDX CLI Version**:
7.18

**OS and version**:
Windows 10

**Comment by FishOfPrey** [comment]
It appears that [/src/codecoverage/colorizer.ts](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/src/codecoverage/colorizer.ts) isn't removing the covered lines from the uncovered lines before applying the decorations. As such, the `coveredLinesDecorationType` and `uncoveredLinesDecorationType` decoration types are being combined on lines that are covered by some tests and not others. 

That doesn't really explain why line 124 isn't affected by this...

**Comment by CristiCanizales** [comment]
Closing this issue as it's not reproducible anymore and feature is working fine.
