### ISSUE TITLE
Exceeded your licensed number of debugging sessions, scratch org

### ISSUE THREAD

**Issue by deb761** [forcedotcom/salesforcedx-vscode#1570]
### Summary

Unable to interactively debug from a Scratch organization

### Steps To Reproduce:

1.  Create scratch org using configuration file with "DebugApex" in features and DevHub org with at least one debug license available.
1.  Set up interactive debugging according to Salesfore Interactive Debugger (https://forcedotcom.github.io/salesforcedx-vscode/articles/apex/interactive-debugger).
1. Attempt to start an interactive debugging session in Visual Studio Code.
1. Get messages in console:
```
Connected to Streaming API channel /systemTopic/ApexDebuggerSystemEvent.
Connected to Streaming API channel /systemTopic/ApexDebuggerEvent.
```

### Expected result

Debug session would have started successfully and used an available license from the DevHub organization.

### Actual result

Received error message: You exceeded your licensed number of debugging sessions.  Please end other sessions or purchase more.

### Additional information

![image](https://user-images.githubusercontent.com/9601218/63202660-a712a380-c03f-11e9-91cb-02a55a8d90a8.png)

**VS Code Version**: 1.37.0

**SFDX CLI Version**: sfdx-cli/7.19.0-c5be43915c win32-x64 node-v10.15.3

**OS and version**: Windows 10 Pro, Version 1803, build 17134.472

**Comment by deb761** [comment]
I can confirm I was the ONLY person attempting a debugging session at the time.  I had created all the scratch orgs.

**Comment by Christelle-Joseph** [comment]
In case someone run into this:

go to setup --> Apex debuger --> kill session 

or 

SFDX: Stop Apex Debugger Session

**Comment by ApraChris** [comment]
I've just run into this as well.

This is from my Dev Hub:

![image](https://user-images.githubusercontent.com/18393568/99061948-81f24500-25a2-11eb-8e41-ff45f0d88949.png)

In my scratch org where I've set up debugging it looks like this:

![image](https://user-images.githubusercontent.com/18393568/99061994-95051500-25a2-11eb-90ee-f0ec9f6a5ae0.png)

I get the exact same behavior as @deb761 mentions.
Version is: sfdx-cli/7.80.0-b979aae708 win32-x64 node-v12.18.3
