### ISSUE TITLE
Reduce extension startup time 

### ISSUE THREAD

**Issue by lukecotter** [forcedotcom/salesforcedx-vscode#1575]
The vs code extension take a long time to startup compare to other extensions.
Almost a full 2 seconds for vscode-core.

Running `Developer: Show Running Extensions` in command palette and `Developer: Startup Performance` shows the following:

<img width="497" alt="Screenshot 2019-08-21 at 10 46 41" src="https://user-images.githubusercontent.com/4013877/63455090-f3951f00-c443-11e9-8e87-3e1885652155.png">

<img width="872" alt="Screenshot 2019-08-21 at 10 48 44" src="https://user-images.githubusercontent.com/4013877/63455105-fa239680-c443-11e9-956d-849c4affa580.png">

I suggest using bundling to improve the performance
https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by brpowell** [comment]
We have an on going effort of reducing the file size and startup time of the extensions. We have slowly been adding webpack to the individual packages of the project and implementing other strategies to accomplish a more nimble experience. Some packages are more complex than others to wire it up with so we're taking an incremental approach.

**Comment by smaddox-sf** [comment]
We're tracking this work under #2295
