### ISSUE TITLE
Unable to Retrieve Apex Code Coverage When Parallel Testing Disabled

### ISSUE THREAD

**Issue by cleverlemming** [forcedotcom/salesforcedx-vscode#1576]
### Summary

Running all tests from either the test sidebar or the link within the rest class results in "--codecoverage ended with exit code 1." Clicking the code coverage button for a class results in a  "no test coverage retrieved for test run..." error message. 

### Steps To Reproduce:

1.  In target org, settings --> test execution --> select Disable Parallel Apex Testing.
2.  In VSCode, run all tests either from the green arrow in the test sidebar or the run all tests link in a test class. 

### Expected result

Expect to see test coverage statistics in Output and highlighted test coverage in a covered class. 

### Actual result

Output displays "codecoverage ended with exit code 1" instead of a table of test statistics. Clicking the show coverage button for a covered class only displays a "no test coverage retrieved for test run..." error message. Classes are not highighted

### Additional information

**VS Code Version**: 1.37

**SFDX CLI Version**: sfdx-cli/7.19.0-c5be43915c darwin-x64 node-v10.15.3

**OS and version**: OS X 10.14.6

**Comment by benji1304** [comment]
I've also seen this, and I've set this in the project-scratch-def.json
```
"settings":{
 "apexSettings": {
    "enableDisableParallelApexTesting": true
}
``` 
But I get the message constantly 
`No code coverage information was found for this file. Set "salesforcedx-vscode-core.retrieve-test-code-coverage": true in your user or workspace settings. Then, run Apex tests that include methods in this file. You can run tests from the Apex Tests sidebar or using the Run Tests or Run All Tests code lens within the file.`

**Comment by mohanraj-r** [comment]
@benji1304 This is a currently a known limitation of apex compiler where code coverage cannot be calculated when tests are run in parallel (W-5251436). Unfortunately the workaround is to run the Apex test classes serially (without parallelism).

Ref: 
* [Execute Apex Tests](https://help.salesforce.com/s/articleView?id=sf.code_test_execution.htm&type=5)

**Comment by mohanraj-r** [comment]
@benji1304 @cleverlemming Sorry I misread the issue. Yes the apex compiler is not expected to produce code coverage by design when tests are run in parallel. But the extensions can do a better job of being aware of and handling that scenario. We have added this to our backlog.

**Comment by diyer** [comment]
Issue does not reproduce any more. Apex coverage can be retrieved from VS Code when parallel testing is disabled.
