### ISSUE TITLE
Avoid using workspace.rootPath

### ISSUE THREAD

**Issue by roblourens** [forcedotcom/salesforcedx-vscode#1589]
This extension appears to be using the `workspace.rootPath` API. This is a deprecated property and may not work as expected. Please use `workspaceFolders` instead. More info:  https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath

https://github.com/microsoft/vscode/issues/69335

**Comment by ntotten** [comment]
Yeah, it’s something we’ve been meaning to do. ;) We’ll try to fix this shortly. Thanks!

**Comment by lcampos** [comment]
This was fixed in version `46.12.0`
