### ISSUE TITLE
SFDX: Create project with manifest command not found

### ISSUE THREAD

**Issue by saihanuman** [forcedotcom/salesforcedx-vscode#1593]
In the Help --> Developer Tools. It is showing this error. I installed CLI, Extension pack as well.
Activating extension 'salesforce.salesforcedx-vscode-apex' failed: Class extends value undefined is not a constructor or null.

Can some one please help me with this :(

**Comment by lcampos** [comment]
Sorry I didn't provide enough context, I was referring to the settings that are saved on your project's `.vscode/settings.json` file or the global ones which you can see by running `Preferences: Open Settings` on vscode's command palette.

**Comment by lcampos** [comment]
I think you are running into 2 issues, one with the CLI configuration and another with a configuration on the Apex extension.
For the CLI issue, one thing I could think of is that Windows requires having the CLI be part of the **PATH** environment variable. Could you verify if it is part of it ? You can do this by going to the **System Properties** window, click the **Advanced** tab, and then click **Environment Variables**. In the **System Variables** section you should see an entry for **PATH**.

For the Apex extension issue, I'm assuming you've done the setup for the Apex extension [Java Setup](https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/java-setup). I think the issue might be related to a setting configuration.

**Comment by wrone** [comment]
I have the same issue and looks like some of these setting is causing this:
`
"salesforcedx-vscode-apex.java.home": "C:\\Program Files\\Java\\jdk-11.0.4",
"salesforcedx-vscode-apex.enable-sobject-refresh-on-startup": true,
"salesforcedx-vscode-core.internal-development": true,
"salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true,
"salesforcedx-vscode-core.retrieve-test-code-coverage": true,
"salesforcedx-vscode-core.show-cli-success-msg": false,
`

When I leave just one "salesforcedx-vscode-apex.java.home": "C:\\Program Files\\Java\\jdk-11.0.4" it works

**Comment by lcampos** [comment]
@wrone yeah, what's the reason you ended up enabling `"salesforcedx-vscode-core.internal-development": true"` ? We added that setting for a specific scenario we run but it's not documented to customers because it does not provide any value for you. Maybe we should remove it to avoid confusion ?

**Comment by wrone** [comment]
@lcampos I guess I enabled it accidentally. Yeah, I think it's better to remove it

**Comment by saihanuman** [comment]
@lcampos @wrone Can you guys able to help me and guide me by looking at my screen if i share? I tried to search for all those settings, couldn't find any . I uninstalled everything and again installed VS code, installed Salesforce CLI --> Added the CLI path to the user environment variables, downloaded the extensions. Still i am seeing the same issue.. All my colleagues got this done straight forward and not sure why in my machine only its keep on saying command not found and in developer tools its showing the same "Activating extension 'salesforce.salesforcedx-vscode-apex' failed: Class extends value undefined is not a constructor or null." Please help me in this( my email id: nagasaipotti@gmail.com) It would be very helpful for me and i would be very thankful if you can help me to solve this puzzle.

**Comment by saihanuman** [comment]
After lot of attempts of  reinstalling everything it worked finally. Not sure what is the difference. Now going down the line, when i use SFDX: Authorize an org it is giving me this error.
Try this: 
Kill the process running on port 1717 or use a custom connected app and update OauthLocalPort in the sfdx-project.json file.
17:30:13.286 sfdx force:auth:web:login --setalias sit --instanceurl https://test.salesforce.com --setdefaultusername ended with exit code 1

but when i check in task manager, there is nothing running on port 1717. 

if any found the same issue, please assist me.

**Comment by Vijayakumark451** [comment]
> In the Help --> Developer Tools. It is showing this error. I installed CLI, Extension pack as well.
> Activating extension 'salesforce.salesforcedx-vscode-apex' failed: Class extends value undefined is not a constructor or null.
> 
> Can some one please help me with this :(

**Comment by bawaalbhai** [comment]
same problem is happening with me evn after I have installed java 1.8
node js and vs code with salesforce cli integration extension. It does't shows authorize an or option and when I click create a project with manifest it says SFDX error

**Comment by KavyaRaoNeelagiri** [comment]
@bawaalbhai I am having same issue too. Just wanted to check if you are able to resolve this. please let me know

**Comment by bawaalbhai** [comment]
Yeah I fixed it I can help if you want.

**Comment by KavyaRaoNeelagiri** [comment]
@bawaalbhai That would be great. Please let me know if we can connect on this or you can also let me the know the steps you followed for resolving it.

**Comment by bawaalbhai** [comment]
After installing java8 and setting the environment path just open vscode
and install previous versions of the salesforce cli and Salesforce
extension pack. Hope this works for you.
