### ISSUE TITLE
@salesforce/sfdx-diff - Source Diff retrieving "(hidden)" file contents from Org

### ISSUE THREAD

**Issue by oski1993** [forcedotcom/salesforcedx-vscode#1596]
### Summary

Using the beta "Salesforce Diff" extension (0.0.2) - generally works so far, but for one class file I'm trying to diff, get an "Unexpected token "'('. [1,1]" error because the contents of the file retrieved from the org contains only the text "(hidden)"

### Steps To Reproduce:

1.  Right-click the source file in question to get the context menu.
2. Select the "SFDX: Diff File Against Org" option

### Expected result

Expected to see a diff of the remote server version and the local version of the file.

### Actual result

![Monosnap (Workspace) 2019-08-26 12-08-49](https://user-images.githubusercontent.com/4913143/63716298-80502c00-c7fa-11e9-9195-d9bddc9bbf26.png)
![Monosnap (Workspace) 2019-08-26 12-06-51](https://user-images.githubusercontent.com/4913143/63716299-80502c00-c7fa-11e9-8855-61e9c08193a6.png)
![Monosnap (Workspace) 2019-08-26 12-04-53](https://user-images.githubusercontent.com/4913143/63716300-80502c00-c7fa-11e9-854f-b341f4fc8a3a.png)

### Additional information

See screenshots in "Actual result" section

**VS Code Version**: 1.37.1

**SFDX CLI Version**: sfdx-cli/7.21.0-964f56bd1a darwin-x64 node-v10.15.3
Salesforce Extension Pack 46.11.0
@salesforce/sfdx-diff 0.0.2 ([PR #1568](https://github.com/forcedotcom/salesforcedx-vscode/pull/1568))

**OS and version**: MacOS Mojave 10.14.6 (18G87)

**Comment by lcampos** [comment]
This was fixed in version `0.0.3` of the `@salesforce/sfdx-diff` plugin.
