### ISSUE TITLE
Apex: Improve tab completion

### ISSUE THREAD

**Issue by nufsty2** [forcedotcom/salesforcedx-vscode#1611]
DISCLAIMER: I'm new to Salesforce and these Salesforce VSCode extensions.

**Is your feature request related to a problem? Please describe.**
In every language/editor I've ever used, tab completion for methods is always the same. You type in the function, a suggestion is displayed, you hit TAB and it completes to the end of the function name while still displaying the parameters above as you type them in. This extension, however, puts all of the default arguments in the function call, which means I have to go back and delete them and fill in the correct parameters.

**Describe the solution you'd like**
For example, if I have a function "public void getPerson(String firstName, String lastName, String idNumber)" and I want to call it, I should be able to type "getPe...", hit tab, and have it only autocomplete to the first "(", while still showing the parameters.

**Describe alternatives you've considered**
I've tried to see if other extensions would solve it. I've resorted to just double clicking each argument and replacing it, which is pretty annoying.

**Additional context**
Here are a couple of screenshots that describe what I'm talking about:

As of now:
![First](https://user-images.githubusercontent.com/23644068/63870461-3b053900-c977-11e9-817d-831951fa88d8.jpg)*Preparing to hit tab...*

![Second](https://user-images.githubusercontent.com/23644068/63870468-3e98c000-c977-11e9-844a-369127563905.jpg)*After hitting tab. Not helpful to have literals inserted into the function that aren't even declared or initialized.*

If I could have it my way, it would work more like:
![Third](https://user-images.githubusercontent.com/23644068/63870482-43f60a80-c977-11e9-8b3a-1c9dcae61842.jpg)*Tab completed to first "(" and parameter list still displayed. I think behavior similar to this would be more useful.*

**Comment by sfsholden** [comment]
Closing - this feature was implemented in #1913
