### ISSUE TITLE
Stop defaulting workspace "push-or-deploy-on-save.enabled" to false

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#1612]
**Is your feature request related to a problem? Please describe.**
When you create a new project, an entry is creating in the workspace settings for `"salesforcedx-vscode-core.push-or-deploy-on-save.enabled": false,`.  

This override is a CONSTANT source of confusion for new users trying to get going on vscode.  It even occasionally trips me up when starting a new project.

**Describe the solution you'd like**

Stop doing this.  Or maybe first check the User settings and don't override it if it's already set.

**Describe alternatives you've considered**

Building a file watcher that runs in the background and sends an angry tweet @ntotten every time a new `.vscode/settings.json` file is created with `push-or-deploy-on-save.enabled=false`

**Comment by lcampos** [comment]
Closing this since it was addressed on version 47.3.1 on the salesforcedx-templates plugin
