### ISSUE TITLE
Iteration Plan for September & October 2019

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#1613]
This plan captures our work in **September & October**. This is a 6-week iteration. We ship updates weekly, but features or changes may not be fully available until the end of the iteration.

Our focus this iteration is primarily around wrapping up several larger projects we have started over the past few months. We are also spending on some performance areas that we think will have a fairly large impact on the user experience.

## Schedule
* September 3, 2019: Iteration begins
* October 11, 2019: Iteration ends

## Plan Items
Below is a summary of the top-level plan items.

Legend of annotations:

Mark | Description
-- | --
🚀 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Org Browser (#862)
* [x] Retrieve all instances of a single metadata type (in progress)
* [x] Enable retrieving Standard Objects
* [x] Feature enabled by default

### Templates
* [x] Support of —json flag
* [x]  Prevent override of files during creation
* [x] Documentation for going open-source
* [x] Add plugin to CLI build process
* [x] Bug Blitz

### SOQL Language Server (#947)
* [ ] 🚀Fix performance & usage of SObject refresh
* [ ] 🚀SOQL inside of Apex 
* [ ] Additional tests

### Performance Enhancements
* [ ] 🚀 Single file deploys using Tooling API (#917)

### Org Diff Tool
* [x] Support namespaces
* [x] 🚀 Bug fixes (#1600, #1596, #1584)
* [ ] Security review
* [ ] Open source approval
* [ ] ⚫️Determine if should be shipped in CLI without diff in terminal feature
* [ ] 💪Support more metadata types
    * [x] Perm sets
    * [ ] Objects & fields
    * [ ] 🚀 Labels
    * [x] Layouts

## Endgame
* [ ] October 17, 2019: Blog Post (@ntotten)

**Comment by ChuckJonas** [comment]
@ntotten are you guys planning on adding a `soql` language type for stand alone files?

**Comment by ntotten** [comment]
@ChuckJonas yup!

**Comment by ChuckJonas** [comment]
do you have a grammar? Wondering if comments will be supported

**Comment by RandallFlagg** [comment]
Regarding the diff tool: Are you going to also fix bug #1584 ?

**Comment by msolomon802** [comment]
Regarding #862 currently in the Org Browser "Standard Objects" are listed under the "Custom Objects" folder. Should these be separated or maybe the folder should be renamed to "Objects"?

**Comment by ntotten** [comment]
> do you have a grammar yet? Wondering if comments & multiple queries per file will be supported

Not yet. We will publish it soon like we did the Apex one. I think we support comments, not sure about multiple queries. //cc @lcampos

**Comment by lcampos** [comment]
> Regarding the diff tool: Are you going to also fix bug #1584 ?

Yes, let me add it to the iteration plan since we are working on it.

**Comment by sc5148** [comment]
What is the update on SOQL inside of Apex and Single file deploys using Tooling API ?

**Comment by lcampos** [comment]
Hi @sc5148, SOQL inside of Apex is one of the things we're working on, we'll be prioritizing our roadmap in the next weeks and will publish an updated one to reflect where/when this will be delivered.
For single file deploys using Tooling API, that work is currently in progress and we'll start shipping some of those changes in the following weeks.
cc @ntotten
