### ISSUE TITLE
Salesforce Sucks

### ISSUE THREAD

**Issue by jthomas077** [forcedotcom/salesforcedx-vscode#1620]
Do not collect metrics from users automatically... The notification is VSCODE point to  an arbitrary page, that has absolutely no indication of how to respond to you. I'm not going to set a VSCODE setting to let you collect my data. Therefore, you are subject to legal action. Furthermore, GitHub has implemented a new feature with a drop down if actions in which the drop down is impossible to get rid of. It's always thee and frankly super annoying... In my experience Salesforce, is architect and too much of a burden to use... Frankly, it requires way to much to implement in which case is your revenue stream.

**Comment by jthomas077** [comment]
And of course, my message was auto-parsed with arbitrary messages.... hence my complaint.

**Comment by ntotten** [comment]
I do not understand this issue and am closing it.
