### ISSUE TITLE
Salesforce VSCode plugins are disabled. Reload button doesn't go away

### ISSUE THREAD

**Issue by shashidharkotta** [forcedotcom/salesforcedx-vscode#1622]
### Summary

_Salesforce plug-in's are stuck with 'Reload' button_.

### Steps To Reproduce:

1.  This is step 1. Just install VSCode with the the Salesforce plug-ins. All the versions are mentioned below.

### Expected result

_Plug-in's shouldn't get stuck_.

### Actual result

_Plug-ins are disabled with a 'Reload' option. On clicking 'Reload' button, it refreshes VSCode but still the plug-ins are disabled with 'Reload' option. I even restarted the system but still the issue remains_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.25.1

**SFDX CLI Version**: 7.8.1

**OS and version**: MacOS Mojave (10.14.4)

**Comment by shashidharkotta** [comment]
Attaching the screenshot.

![Screen Shot 2019-08-30 at 1 50 43 PM](https://user-images.githubusercontent.com/54721157/64042016-f4f2d580-cb2e-11e9-970a-3bd5e5643a07.png)

**Comment by lcampos** [comment]
@shashidharkotta I think this might be because you are using a version of VSCode (1.25.1) older than what the extensions require. The extensions require you to be on VSCode version 1.32.0 or above, the latest stable version being 1.37.1.

Can you try updating to a newer version of VS Code and see if that solves your issue ?

**Comment by shashidharkotta** [comment]
@lcampos , Thanks. I was using VS Code's 'Check for Updates' feature and it was saying my VSCode was update hence didn't realize my version is off. I just downloaded 1.37.1 directly and I don't see this issue anymore. Thanks again.
