### ISSUE TITLE
VSCODE > Default> (Right Click) SFDX Commands Missing 

### ISSUE THREAD

**Issue by miteshmsharma** [forcedotcom/salesforcedx-vscode#1623]
### Summary
VSCODE > Default> (Right Click) SFDX Commands Missing 
_Short summary of what is going on or to provide context_.

### Steps To Reproduce:
I am experienceing the similar issue even when I am following along the trailhead - see the SFDX commands from Default > Right Click

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result
![image](https://user-images.githubusercontent.com/6457976/64064972-94928f80-cc25-11e9-8d79-6bc2cec2f26b.png)

_Describe what should have happened_.

### Actual result
![image](https://user-images.githubusercontent.com/6457976/64064975-9ceaca80-cc25-11e9-930c-3cbb507ff4de.png)

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.37.1
**SFDX CLI Version**:
sfdx-cli/7.21.0-964f56bd1a win32-x64 node-v10.15.3
**OS and version**:
Windows 7 Home

**Comment by lcampos** [comment]
Hi @miteshmsharma, those commands are displayed when you are working with a Salesforce DX project and you are working with a non-scratch org. Can you confirm you are not using a scratch org ?
