### ISSUE TITLE
Push on save ignores .forceignore

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/salesforcedx-vscode#1625]
**Steps to reproduce**

Add this to your config:
```
"salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true
```

Add this line to your `.forceignore` file:
```
scratch.apex
```

Create `scratch.apex`, save it

**Expected behavior**
Settings to be respected and file not pushed

**Actual behavior**
Settings are discarded

**Comment by AndrewRayCode** [comment]
It appears this setting will try to push **any** file you save to your org, independent of the extension, ignored files, folder, org, manifest... uhhhhhhh

**Comment by AndrewRayCode** [comment]
Looks like it ignores files starting with a `.`, I guess? Or maybe it just ignores OS hidden files? Naming the file `.scratch.apex` is one hack to work around this

**Comment by floralan** [comment]
@AndrewRayCode Hi, please check out our new Deploy/Retrieve commands. It should resolve this issue.
