### ISSUE TITLE
Coverage showed by VScode and the Developer console are different

### ISSUE THREAD

**Issue by lokeshmupiri** [forcedotcom/salesforcedx-vscode#1630]
There are some differences between the apex code coverage showed by Visual code studio and the Developer console over the same class. Any ideas to fix this?

![image](https://user-images.githubusercontent.com/52125370/64226019-0bf24880-cede-11e9-8009-305ff7b60ab6.png)

**Comment by Gothiname** [comment]
1 month and half and still no answer ?

I got the same problem.

In console 94% covered
In vscode 73% covered

Btw the correct coverage is in the console.

**Comment by smaddox-sf** [comment]
Apologies - looks like this one slipped by us!  We're making changes to this area and would love your input on the spec.  Check it out and leave a comment there with any input - #2224   Closing this to consolidate the conversation.
