### ISSUE TITLE
Error when trying to deploy file of LWC or Aura

### ISSUE THREAD

**Issue by iFernandoSousa** [forcedotcom/salesforcedx-vscode#1635]
### Summary

The ability to make deploy using shortcode stop because after the last release is the CLI stop to detect that file send is a component to get a folder and send all folder 

### Steps To Reproduce:

1.  Open LWC folder, open any component folder
2.  Choose one file and click with the right button on it, and then select the option "SFDX: Deploy Source to Org".
3.  Look for output and you will see the error message

### Expected result

The folder component be deployed

### Actual result

Get error message on output: 

SfdxError: You must specify the Aura bundle folder, not an individual component.

### Additional information

**VS Code Version**: 1.38.0

**SFDX CLI Version**: 7.23.1-ced0ec4940

**OS and version**: Windows 10 - Version 1903 (OS Builder 18362.329)

**Comment by dbarks1024** [comment]
I am having the same issue. Have you found a workaround?

**Comment by dbarks1024** [comment]
Just figured out if you go a few folders up and deploy it seems to work for some reason.

**Comment by SalesforceBobLightning** [comment]
I am having the same issue.

sfdx --version
sfdx-cli/7.23.1-ced0ec4940 win32-x64 node-v10.15.3

VSCODE:

Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by KelvinHuangDZ** [comment]
I have same problem. I have setting auto save on- "salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true

Error message: "SfdxError: You must specify the Aura bundle folder, not an individual component."

sfdx plugins -v
sfdx-cli/7.23.1-ced0ec4940 darwin-x64 node-v10.15.3

**Comment by pranaymistry** [comment]
> Just figured out if you go a few folders up and deploy it seems to work for some reason.

Hi @dbarks1024 can you please provide more details, as in, were you able to deploy the LWC bundle on save of an individual html, JS file. what do you mean when you say "go a few folders up and deploy".

**Comment by pranaymistry** [comment]
I am having a similar issue while saving the html, js file in LWC. I created a Github issue as well 

#1640

**Comment by pranaymistry** [comment]
@ntotten this issue is similar to #1640

**Comment by scosant** [comment]
I ran into this problem as well when I upgraded sfdx-cli to 7.23.1. I was able to work around it by completely uninstalling/removing sfdx-cli and reinstalling version sfdx-cli/7.22.0 via npm.

**Comment by dbarks1024** [comment]
> > Just figured out if you go a few folders up and deploy it seems to work for some reason.
> 
> Hi @dbarks1024 can you please provide more details, as in, were you able to deploy the LWC bundle on save of an individual html, JS file. what do you mean when you say "go a few folders up and deploy".

Hi @pranaymistry In VS code I went a file up and right clicked it (/force-app/main/default/lwc) then selected deploy source to org. I had to turn off the setting where it deploys on save as well.

**Comment by pranaymistry** [comment]
> > > Just figured out if you go a few folders up and deploy it seems to work for some reason.
> > 
> > 
> > Hi @dbarks1024 can you please provide more details, as in, were you able to deploy the LWC bundle on save of an individual html, JS file. what do you mean when you say "go a few folders up and deploy".
> 
> Hi @pranaymistry In VS code I went a file up and right clicked it (/force-app/main/default/lwc) then selected deploy source to org. I had to turn off the setting where it deploys on save as well.

Hi @dbarks1024 thanks for your reply, yeah that's the manual workaround, I was really hoping that you would have figured out a way to save and deploy together. I guess we have no choice but to turn off the save and deploy, and manually deploy files, that sucks. 

@ntotten

**Comment by bruceyue** [comment]
Can not save individual file but to save the whole component folder, it will works

**Comment by swervo** [comment]
This also impacts Lightning aura and breaks the convenient 'AutoSave on focus change', 'deploy on save' workflow.

**Comment by chenjisrinivas** [comment]
Can not save individual file with Salesfoce CLI version 7.8.1.0. It was working earlier with the older version of CLI.

**Comment by vinodatschneider** [comment]
SfdxError: You must specify the Aura bundle folder, not an individual component.
This is happening only on windows.

In Linux, for the same sfdx version , It works fine.

**Comment by furucrm-anh-le** [comment]
I have same problem

ERROR running force:source:retrieve:  You must specify the Aura bundle folder, not an individual component.

My SFDX version:
sfdx-cli/7.23.1-ced0ec4940 darwin-x64 node-v10.15.3
OS: macOS Mojave 10.14.6

**Comment by brpowell** [comment]
We've identified the CLI regression and are working to have a fix soon. Stay tuned.

**Comment by brpowell** [comment]
This has been fixed in version 7.25.3 of the CLI. Run `sfdx update` to get the latest version
