### ISSUE TITLE
ERROR running force:source:push:  Push failed.

### ISSUE THREAD

**Issue by rexntb** [forcedotcom/salesforcedx-vscode#1636]
### Summary

I am trying to complete the Trailhead project "Develop an App with Salesforce CLI and Source Control" and I am getting an error when trying to push data into a scratch org. I keep getting an error.

### Steps To Reproduce:

1.  Create new sfdx project
1. Create new scratch org
1.  Push all metadata to scratch org

### Expected result

Data should be pushed to new scratch org.

### Actual result

"Push failed" error message.

### Additional information

Owner:sfdx-chan user$ sfdx force:source:push -g
PROJECT PATH                                                             ERROR
───────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────
force-app/main/default/applications/DreamHouse.app-meta.xml              In field: tab - no CustomTab named Property__c found
force-app/main/default/tabs/Broker__c.tab-meta.xml                       Property 'mobileReady' not valid in version 46.0
force-app/main/default/tabs/Property__c.tab-meta.xml                     Property 'mobileReady' not valid in version 46.0
force-app/main/default/tabs/Sample_Data_Import.tab-meta.xml              Property 'mobileReady' not valid in version 46.0
force-app/main/default/permissionsets/DreamHouse.permissionset-meta.xml  In field: tab - no CustomTab named Broker__c found
ERROR running force:source:push:  Push failed.
Owner:sfdx-chan user$ sfdx force:source:push --apiversion=45.0
PROJECT PATH                                                             ERROR
───────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────
force-app/main/default/applications/DreamHouse.app-meta.xml              In field: tab - no CustomTab named Property__c found
force-app/main/default/tabs/Sample_Data_Import.tab-meta.xml              Property 'mobileReady' not valid in version 46.0
force-app/main/default/tabs/Broker__c.tab-meta.xml                       Property 'mobileReady' not valid in version 46.0
force-app/main/default/tabs/Property__c.tab-meta.xml                     Property 'mobileReady' not valid in version 46.0
force-app/main/default/permissionsets/DreamHouse.permissionset-meta.xml  In field: tab - no CustomTab named Broker__c found
ERROR running force:source:push:  Push failed.
Owner:sfdx-chan user$ 

**VS Code Version**: Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 15.6.0

**SFDX CLI Version**: sfdx-cli/7.23.1-ced0ec4940 darwin-x64 node-v10.15.3

**OS and version**: MAC OS X El Capitan. Version 10.11.6 (15G31)

**Comment by justin4c** [comment]
@rexntb How did you resolve this? I'm having the exact same issue.

**Comment by rexntb** [comment]
> @rexntb How did you resolve this? I'm having the exact same issue.

@justin4c I just commented out the lines below in each xml file that produced the 'mobile ready' error and it worked for me afterwards (don't forget to save your changes before deploying). 

`force-app/main/default/tabs/Sample_Data_Import.tab-meta.xml Property 'mobileReady' not valid in version 46.0
force-app/main/default/tabs/Broker__c.tab-meta.xml Property 'mobileReady' not valid in version 46.0
force-app/main/default/tabs/Property__c.tab-meta.xml Property 'mobileReady' not valid in version 46.0`

**Comment by 69cuda340s** [comment]
I had this same issue, looked around, and found the following in [Summer '19 release notes](https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_api_meta.htm):

Custom Tabs
REMOVED: The deprecated field mobileReady has been removed from the CustomTab object
The mobileReady field is left over from the deprecated Salesforce Classic Mobile app. This field indicated whether a Visualforce page appeared in the Salesforce Classic Mobile app.

I removed the deprecated property from my tab-name.tab-meta.xml files and all seems to be working fine.

**Comment by baibalorenzo** [comment]
**<mobileReady> tag is not supported in later API versions.**

The problem come from the mobileReady tag in the respectives files. Try to comment the tag. It will fix the problem. It is not supported in later API versions. 
So goto to each file and remplace the mobileReady tagline __ or just remove it.
