### ISSUE TITLE
.eslint.json created even if .eslint.js already exists

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/salesforcedx-vscode#1644]
### Summary
Whenever a project is opened an `.eslint.json` file is created at the path `force-app/main/default/lwc/.eslintrc.json` even if an `.eslint.js` already exists at the same location

### Steps To Reproduce:

1.  create a project and rename the `.eslint.json` to `.eslint.js` to allow for javascript features
1.  close vscode
1. reopen VSCode for the same project
### Expected result

No new file should be created, the `.eslint.js` will be used as is appropriate

### Actual result

a new `.eslint.json` is created without fail.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.38.0, extension version: 46.13.0

**SFDX CLI Version**:
fdx-cli 7.23.1 (core)

**OS and version**:
MacOS 10.14.6

**Comment by ntotten** [comment]
ESLint files are no longer written by the extension, they come with the project templates.
