### ISSUE TITLE
Winter 20

### ISSUE THREAD

**Issue by Kxa422** [forcedotcom/salesforcedx-vscode#1645]
From vscode, in an Aura Component, right click and select SFDX: Retrieve Source from Org

The output console display:

Starting SFDX: Retrieve Source from Org

10:11:03.34 sfdx force:source:retrieve --sourcepath c:\Users\MyUser\Salesforce\MyProject\force-app\main\default\aura\MyComponent\MyComponent.cmp

ERROR running force:source:retrieve:  You must specify the Aura bundle folder, not an individual component.

10:11:08.682 sfdx force:source:retrieve --sourcepath c:\Users\MyUser\Salesforce\MyProject\force-app\main\default\aura\MyComponent\MyComponent.cmp ended with exit code 1

The workaround is to go to the console and run:

sfdx force:source:retrieve -m AuraDefinitionBundle:MyComponent

**Comment by smrobert09** [comment]
This is a similar issue to issue #1635 where the context for aura and lwc is not recognized, causing the automatic reference to the parent folder. The only difference is the deploy vs retrieve operations. @ntotten

**Comment by ntotten** [comment]
Duplicate of #1635
