### ISSUE TITLE
SFDX Command is not found

### ISSUE THREAD

**Issue by malasani90** [forcedotcom/salesforcedx-vscode#1650]
Issue Type: <b>Bug</b>

Hi Team,
I'm facing this issue for 3 days. previously it was working without any issue. please find the solution ASAP

Extension version: 46.14.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ntotten** [comment]
We need a lot more info to understand what is happen. Please provide complete reproduction steps and the full error details and reopen.
