### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by vennasrilatha** [forcedotcom/salesforcedx-vscode#1651]
Issue Type: <b>Feature Request</b>

I tried to create project in VS code, but it is throwing error as "'sfdx' is not recognized as an internal or external command,
operable program or batch file.Salesforce CLI is not installed". What could be reason i didn't understand. Please help me onthis

Extension version: 46.14.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

**Comment by brpowell** [comment]
@vennasrilatha The Salesforce CLI is required to run commands. Visit https://developer.salesforce.com/tools/vscode/articles/getting-started/install#salesforce-cli for more information and how to set it up.
