### ISSUE TITLE
Salesforce CLI Extension not working

### ISSUE THREAD

**Issue by Gunjit** [forcedotcom/salesforcedx-vscode#1654]
### Summary

Salesforce CLI Extension not working. When SFDX: Authorize an Org keeps on running and browser is not opening for authorization

### Steps To Reproduce:

1.  Run SFDX: Authorize an Org (Using Ctrl+Shift+P)
2.  Nothing happens and command keeps on running

### Expected result

It should open the browser to authenticate the org

### Actual result

Nothing happens and command keeps on running

### Additional information

<img width="692" alt="CLI Issue" src="https://user-images.githubusercontent.com/9118709/65032544-fad71c00-d960-11e9-903a-e448282ba2ee.PNG">

**VS Code Version**: 1.38.1

**SFDX CLI Version**: 46.14.0

**OS and version**:  Microsoft Windows 10 Enterprise and 10.0.16299 Build 16299

**Comment by lcampos** [comment]
Hi @Gunjit , in a Windows environment I've seen this happen if a default browser has not been configured in the System configuration. Can you confirm you do have a default browser configured in your OS ?

**Comment by Gunjit** [comment]
@lcampos : Yes, its already there. PFB screen shot for your reference.
<img width="618" alt="DefaultBrowser" src="https://user-images.githubusercontent.com/9118709/65227613-9940ba00-dae6-11e9-9d98-34fe13c456e6.PNG">

**Comment by rahulbussa** [comment]
even i'm facing the same issue. Authorize org taking an indefinite amount of time, below are the version details  sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**Comment by lcampos** [comment]
@Gunjit I'm still not able to replicate this issue on my side. Does this work for you when you run `sfdx force:auth:web:login ...` directly in the terminal ?

**Comment by Gunjit** [comment]
@lcampos : The issue got resolved, I changed the default browser from Chrome to Edge. 
Thanks

**Comment by Gunjit** [comment]
> even i'm facing the same issue. Authorize org taking an indefinite amount of time, below are the version details sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**Comment by Gunjit** [comment]
@rahulbussa : Trying changing the default browser from "Google Chrome" to something else.

**Comment by lcampos** [comment]
I'm closing this since the solution for it is to update the machine's default browser.

**Comment by rahulbussa** [comment]
> @rahulbussa : Trying changing the default browser from "Google Chrome" to something else.

@Gunjit  Thanks it worked like a charm. @lcampos  looks like setting Chrome as the default browser in Windows 10 makes this issue, I think you can recreate the bug in local by setting chrome as default.

**Comment by Bharatummadi** [comment]
Hi @lcampos ,
I tried changing my default browser from Chrome to Edge, but still SFDX: Authorize an Org keeps on running and browser is not opening for authorization.

VS Code version: 1.64.2
SFDX CLI Version:
