### ISSUE TITLE
Resolve inconsistencies relating to .gitignore and .vscode/settings.json

### ISSUE THREAD

**Issue by pchittum** [forcedotcom/salesforcedx-vscode#1656]
### Summary

The default `.gitignore` supplied by tooling omits the `.vscode/settings.json` file. This file stores a setting that is specific to the developer's machine (`eslint.nodePath`) that the vscode plugin appears to automatically generate. If a project is being committed to by multiple developers, this will likely mean commits contain the noise of machine-specific paths when developer A and developer B commit from each their own machines. This could also create unnecessary merge clashes. I discovered this whilst doing development on a project on both my Mac and Windows machines. Needless to say the paths here are vastly different. Including the syntax (backslash v forwardslash).

Removing `settings.json` could be a viable option, but doing so means the vscode plugin needs to regen the settings.json consistently. I've observed that whilst the `eslint.nodePath` prop gets added back, the `salesforcedx-vscode-core.push-or-deploy-on-save.enabled` and `search.exclude` settings do not. 

### Steps To Reproduce:

1. Create a new project using `force:project:create`. 
1. Build some stuff. Or do whatever it takes for VScode to generate the `.vscode/settings.json` file. 
1. Note the path. For instance on my one machine it is `"/Users/pchittum/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-46.14.0/node_modules"`. 
1. Add/Commit/Push to your cloud-based git provider of choice. 
1. On machine 2, perform a `git clone` on the repo. 
1. Open the project and build some more stuff or do whatever it takes for the VSCode plugin to update `settings.json` to your new local path. 
1. Note you have a new path that is completely different than it used to be. 
1. Git status: note you now have a file change that you didn't actually change and doesn't reflect the feature you're actually building. 
1. Realize maybe you shouldn't be tracking that in VCS. Add a new line to `.gitignore` for `.vscode/settings.json`. 
1. `git rm --cached .vscode/settings.json`
1. Commit any other changes and push to `origin`
1. Now let's see how that's going to work without tracking. 
1. Blow away project directory and redo `git clone`. 
1. Again, open newly cloned project and fiddle with it in VSCode until it regenerates `.vscode/settings.json`. 
1. Notice you no longer have any other settings but `eslint/nodePath`

### Expected result

Normally after I create a new project, the VSCode plugin seems to add all of the settings file itself (not added directly by the sfcli command). I would hope that upon encountering an existing project with no `.vscode/settings.json` file, it would be able to reproduce the same settings.json it did on a fresh project. 

### Actual result

As described above, my settings.json no longer has a setting to exclude certain folders from search or enable push on save. 

### Mac Version Information
**VS Code Version**:
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Salesforce Extension Pack VS Code Plugin: 46.14.0 September 12, 2019

**SFDX CLI Version**:
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/analytics 0.8.0
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.13.1 (core)
├─ force-language-services 46.18.0 (core)
└─ salesforce-alm 46.17.0 (core)

###Windows Machine Information
**VSCode Version Information**
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Salesforce Extension Pack VS Code Plugin: 46.14.0 September 12, 2019

**SFDX CLI Version**:
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.13.1 (core)
├─ force-language-services 46.18.0 (core)
└─ salesforce-alm 46.17.0 (core)

sfdx-cli 7.23.1 (core)

**Comment by ntotten** [comment]
This is the best bug report I have ever seen. Thank you!

So we are going to fix this soon - like in about 2 weeks. The plan is to remove the setting for eslint entirely. The `settings.json` should absolutely be checked into source - the whole point of it is to ensure all developers on the project have the same settings.

Apologies for the delay getting this fixed. I know it is a pain.

**Comment by jonathanwiesel** [comment]
I understand why we need to check in the `setting.json` for some aspects of the development, what I tend to disagree is that there are exceptions that shouldn't be shared across developers and which are stored in that `settings.json` file, specially when we talk about machine related paths for different extensions or simply additional extensions that one developer may have that the others doesn't.

What's your opinion on this @ntotten?
