### ISSUE TITLE
Salesforce Extention pack issue(SFDX Command not found)

### ISSUE THREAD

**Issue by malasani90** [forcedotcom/salesforcedx-vscode#1664]
Hi team,

I already installed the salesforce extension pack. previously worked on but suddenly after getting some updates. sfdx commands are not worked properly. sfdx commands do not appear on vscode.

FYR see below image

![image](https://user-images.githubusercontent.com/40070706/65113390-a5524c00-da00-11e9-874c-db74d874a511.png)

**Comment by lcampos** [comment]
Hi @malasani90, do you see any errors when you open VSCode's Dev Tools (Help > Toggle Developer Tools and select the Console tab) ?

If you do not see any errors in the Console, what do you get when you run `which sfdx` in VSCode's terminal compared to running that same command in a terminal outside of VSCode ?
