### ISSUE TITLE
"Unmet peer depencency" when installing sfdx-diff

### ISSUE THREAD

**Issue by melissajhansen** [forcedotcom/salesforcedx-vscode#1666]
### Summary
When attempting to install sfdx-diff I am getting the following warning, and I do not see the diff options in my right-click/ctrl-click menus:

warning "@salesforce/sfdx-diff > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".

### Steps To Reproduce:

1. run sfdx plugins:install @salesforce/sfdx-diff
1. Enter y when prompted with the unsigned warning
1. Get the following warnings and confirmations:
 Finished digital signature check.
warning @salesforce/sfdx-diff > @salesforce/command > @oclif/test > fancy-test > @types/nock@11.1.0: This is a stub types definition. nock provides its own type definition
s, so you do not need this installed.
warning @salesforce/sfdx-diff > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of @sinonjs/
samsam
warning "@salesforce/sfdx-diff > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin @salesforce/sfdx-diff... installed v0.0.2

### Expected result
After restarting VSCode, I'm expecting to see the SFDX: Diff File Against Org option when right clicking on open metadata.

### Actual result

Those menu options do not appear

### Additional information

I have tried updating the CLI, updating NPM, uninstalling and re-installing the CLI entirely.

**VS Code Version**: 1.38.1

**SFDX CLI Version**:sfdx-cli/7.23.1-ced0ec4940 darwin-x64 node-v10.15.3

**OS and version**: macOS Mojave 10.14.5

**Comment by lcampos** [comment]
Hi @melissajhansen, we're working on fixing the warnings but that shouldn't prevent the installation of the plugin from being successful. Do you see `@salesforce/sfdx-diff` as an option after running `sfdx plugins` ?

In the VSCode side, `SFDX: Diff Against Org` is currently only available for Apex, Visualforce, Lightning and LWC files. Can you confirm you are running version 46.11.0 or above of the Salesforce extensions for VSCode ?

**Comment by melissajhansen** [comment]
Thanks @lcampos , I've got v 46.16.0 of Salesforce Extensions, and when I run sfdx plugins I see @salesforce/sfdx-diff 0.0.2

But ctrl+click or right-click on supported matadata, like an Apex class, doesn't have the diff command

![image](https://user-images.githubusercontent.com/5881820/65807717-b576d380-e144-11e9-8f38-119e02f92a7b.png)

**Comment by lcampos** [comment]
Ah, got it. So the diff command is only available when you right click inside an open  file. It is not enabled when right-clicking the file using the File Explorer.

![diff_command](https://user-images.githubusercontent.com/1041842/65808322-72b6fa80-e148-11e9-9a8c-f0ac8dcacb9b.png)

Having said that, I think it would be a good idea to add it to the file explorer. We'll work on that in the next updates.

**Comment by melissajhansen** [comment]
Ahhhh!  Thanks @lcampos I hadn't accessed SFDX commands by clicking in an open file and it hadn't even occurred to me!

**Comment by lcampos** [comment]
No problem, thanks for the feedback, having the Diff command available by right-clicking the file in the File Explorer will go out in the next version (46.17.0).
