### ISSUE TITLE
Error activating Apex Extension (v46.15.0)

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#1671]
### Summary

With the latest release of the Salesforce Extensions (46.15.0), there is a known issue in activating the Apex extension upon download. The activation fails with the error `salesforce.salesforcedx-vscode-apex failed: Cannot find module @salesforce/core`. We are actively working on a fix.

**VS Code Version**:
Any VSCode version

**SFDX CLI Version**:
Any CLI version

**OS and version**:
MacOS & Windows

**Comment by lcampos** [comment]
This is fixed in version `46.15.1`.
