### ISSUE TITLE
Alternating between vscode push and command line push results in pushing everything

### ISSUE THREAD

**Issue by jeffhube** [forcedotcom/salesforcedx-vscode#1674]
### Summary

It seems that if you alternate between pushing to scratch orgs using the vscode command and using the command line sfdx force:source:push, you end up pushing every file instead of only the changed files.

This seems to be happening because of a casing difference in the paths in .sfdx/orgs/*/sourcePathInfos.json. When pushing using vscode, the paths are written as "**c**:\\Users\\...", but when pushing using sfdx on the command line, the paths are written as "**C**:\\Users\\...".

### Steps To Reproduce:

1.  In Visual Studio Code, pick SFDX: Push Source to Default Scratch Org from the command palette
1. In the terminal in Visual Studio Code, run "sfdx force:source:push"

### Expected result

The second push should not deploy any files because no files have been changed since the first push.

### Actual result

The second push redeploys every file.

### Additional information

**VS Code Version**:
Visual Studio Code 1.38.1 
Salesforce Extension Pack 46.14.0

**SFDX CLI Version**:
sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**OS and version**:
Windows 10 Version 1903 64-bit

**Comment by lcampos** [comment]
Hi @jeffhube, this is a known issue with Windows drive path casing and documented in https://github.com/forcedotcom/cli/issues/108

**Comment by floralan** [comment]
@jeffhube  please looked in to the previous comment and discussion there may help you. This issue was linked to Work Item @W-6208564, after a series of investigation, we decided to close this because of security concerns.
