### ISSUE TITLE
Testing Suite Fails to Actually Get tests

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/salesforcedx-vscode#1675]
### Summary

See title. It reports "No Apex Tests Found" despite having Apex tests in the system (referenced with @isTest). Yes the class has been compiled and saved to the org

### Steps To Reproduce:

See summary

### Expected result

Tests should show up

### Actual result

Tests dont show up

### Additional information

![image](https://user-images.githubusercontent.com/55202382/65342537-30158100-db90-11e9-9975-c4f4fc1b8714.png)

**VS Code Version**: 1.38.1

**SFDX CLI Version**: 7.25.3-16d54c01ee

**OS and version**: Win10. Not sure of version

**Comment by lcampos** [comment]
Hi @NuAgeDan , can you confirm if the Apex language server is running without errors ? You can do this by opening VSCode's terminal then going to the Output section and selecting `Apex Language Server` in the dropdown on the right. 

The Apex language server is the one that provides the data displayed in the Test sidebar so I wonder if there's an issue with it.

![terminal_lang_server](https://user-images.githubusercontent.com/1041842/65343237-61d71980-db89-11e9-96f9-c781a86e8956.png)

**Comment by NuAgeDan** [comment]
No errors, but a couple warnings: 
- INFO: Unsupported notification method: $/setTraceNotification
- WARNING: Unmatched cancel notification for request id 12

**Comment by lcampos** [comment]
Ok, if you open VSCode's Dev Tools (Help > Toggle Developer Tools and select the Console tab) do you see any errors ?

Is there a way you can share one of your apex tests ? We haven't been able to replicate this issue on our side.

**Comment by BrianEA** [comment]
I ultimately had to clear out the sobjects/standardObjects and apex.db files under .sfdx/tools before this appeared to be resolved here.  I had the same issue with tests being identified by the extension within the editor pages (and executable) but not listed in the Apex Tests panel.
