### ISSUE TITLE
Extension causes high cpu load / memory

### ISSUE THREAD

**Issue by zix66** [forcedotcom/salesforcedx-vscode#1677]
### Actual result
♦ Taking ALL cpu resources on loading and up to 5-10 minutes
![Screenshot_3](https://user-images.githubusercontent.com/44432865/65382690-77784a80-dd13-11e9-92f9-41096b2da8e6.jpg)

♦ And taking huge amount cpu & memory after ..
![Screenshot_2](https://user-images.githubusercontent.com/44432865/65382621-932f2100-dd12-11e9-917d-55431b267896.jpg)

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.38.1
**SFDX CLI Version**:
46.15.1
**OS and version**:
Win 10 64

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/3639388/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt.zip)

**Comment by lcampos** [comment]
Hi @zix66 , thanks for opening this issue. Could you provide more information on the type of project you are working with ? Is it a brand new project created using `SFDX: Create Project` command ? Are you constantly running into this performance issue or is it sporadic ?

I'm trying to find a way of replicating this on our end in order to debug and fix it.

**Comment by zix66** [comment]
Hi!
1. All projects [new/old]2. Only while "starting time"/initialization/indexing  - but taking up to 5-10 minutes3. After "starting stage" finished - all working correct
With best wishes, Igor Umansky
    On Tuesday, October 1, 2019, 04:31:41 AM GMT+3, lcampos <notifications@github.com> wrote:  
 
 
Hi @zix66 , thanks for opening this issue. Could you provide more information on the type of project you are working with ? Is it a brand new project created using SFDX: Create Project command ? Are you constantly running into this performance issue or is it sporadic ?

I'm trying to find a way of replicating this on our end in order to debug and fix it.

**Comment by zix66** [comment]
I think I found problem ..My org network rules blocking some of extensions for updating (and within manual download too)And probably at initialization stage VS Code trying and trying to reach them .. and probably that causes to overload of CPU
    On Tuesday, October 1, 2019, 04:31:41 AM GMT+3, lcampos <notifications@github.com> wrote:  
 
 
Hi @zix66 , thanks for opening this issue. Could you provide more information on the type of project you are working with ? Is it a brand new project created using SFDX: Create Project command ? Are you constantly running into this performance issue or is it sporadic ?

I'm trying to find a way of replicating this on our end in order to debug and fix it.

**Comment by lcampos** [comment]
@zix66 could you try disabling VSCode's auto update ([Extension auto-update](https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate)) then restart VSCode and see if you still run into that CPU issue ? I want to make sure there's no other issue during the activation of the extensions.

**Comment by zix66** [comment]
Yes, I did it .. problem still exists :(I will refresh my JAWA to newest version and will send you results with snapshots later on
    On Thursday, October 3, 2019, 03:58:18 AM GMT+3, lcampos <notifications@github.com> wrote:  
 
 
@zix66 could you try disabling VSCode's auto update (Extension auto-update) then restart VSCode and see if you still run into that CPU issue ? I want to make sure there's no other issue during the activation of the extensions.

**Comment by smaddox-sf** [comment]
Duplicate #1149
