### ISSUE TITLE
Not activating and Taking commands

### ISSUE THREAD

**Issue by himanshu371** [forcedotcom/salesforcedx-vscode#1678]
Issue Type: <b>Bug</b>

CLI is not beeing activating automatically and taking commands also 

Extension version: 46.15.1
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by frizz2310** [comment]
Had the same problem with the same version on MacOS.  Reinstalled everything, tried older versions, uninstalled all extensions, checked CLI, Java, etc.  Still no luck.  Finally, turned off Settings > Extensions > Salesforce Feature Previews > Internal-development.  Forgot I turned this on, but after turning it off and reloading, everything is working again.

**Comment by bcattaneo** [comment]
Experiencing the same issue. It was apparently after the 9/19/2019 update.

**Comment by bcattaneo** [comment]
@himanshu371 try updating/reinstalling the plugin. Mine updated automatically and now it's working again, I guess they fixed something.

**Comment by lcampos** [comment]
@himanshu371 are you still running into this ? If so, what errors do you see when you open VSCode's Dev Tools (Help > Toggle Developer Tools then select the Console tab) ?

**Comment by himanshu371** [comment]
> Had the same problem with the same version on MacOS. Reinstalled everything, tried older versions, uninstalled all extensions, checked CLI, Java, etc. Still no luck. Finally, turned off Settings > Extensions > Salesforce Feature Previews > Internal-development. Forgot I turned this on, but after turning it off and reloading, everything is working again.

this method worked for me 
thanks you very much
