### ISSUE TITLE
Can I debug interactively in sandbox?

### ISSUE THREAD

**Issue by jxzhangxing** [forcedotcom/salesforcedx-vscode#1693]
Hello I'm a beginner salesforce developer. Sorry for my poor English.

Recently in debug session I found that though we already have **replay debugger**. 
But it CAN'T satisfy the need to view the relational sobject (only show a id that make no sense) or watch expression. 

The other way **Checkpoint**  however don't work when I log in different session.

Then I saw ISV Customer debugger in doc. The first step is:

> 1.Log in to your subscriber’s sandbox via your License Management Org (LMO). If you’re not familiar with this process, see the ISVforce Guide. For information on how to obtain login access to your subscriber’s org, see Request Login Access from a Customer. For information on how to log in via the Subscriber Support Console, see Logging In to Subscriber Orgs.

But I don't have the permission to log in to the production environment to set. Only in _test.salesforce.com._ 

It makes me confused. Did I have misunderstanding?
Can I just set a sandbox like a Scratch Org and do interactive debug
which had been featured in eclipse.

Thank you in advance.

**Comment by lcampos** [comment]
Hi @jxzhangxing , the Interactive Debugger can be used in Developer Edition, Sandboxes and Scratch Orgs but it requires purchasing a license.

Could you share more details on what you are trying to debug with the Replay Debugger and not getting enough information on ? Is this around adding a breakpoint on a SOQL result ? A screenshot or code sample would help us to get a better idea on what you are running into.
Thanks.
