### ISSUE TITLE
"SFDX: Deploy Source to Org failed to run" with error message

### ISSUE THREAD

**Issue by IoanB1989** [forcedotcom/salesforcedx-vscode#1695]
Summary
When I "deploy this source to org" and the deploy fails it no longer shows the errors in the panel. Either is I use "command + s" or using "SFDX : Deploy this to source org"

**Steps To Reproduce**:
Deploy an apex class to a salesforce org using VS code with an error in the class

Link here : 
https://drive.google.com/file/d/1HRlfjopCaq2Ot5bjwTvzlQTuYF91FpPr/view?usp=sharing 

**Expected result**

Starting SFDX: Deploy Source to Org

17:20:55.219 sfdx force:source:deploy --sourcepath /Users/i.beschea/Documents/OHDEV/force-app/main/default/classes/OfficeMatchingController.cls --json --loglevel fatal
17:21:02.110 sfdx force:source:deploy --sourcepath /Users/i.beschea/Documents/OHDEV/force-app/main/default/classes/OfficeMatchingController.cls --json --loglevel fatal ended with exit code 1

Method does not exist or incorrect signature: void addAddresses() from the OfficeMatchingController class

Actual result
Starting SFDX: Deploy Source to Org

17:20:55.219 sfdx force:source:deploy --sourcepath /Users/i.beschea/Documents/OHDEV/force-app/main/default/classes/OfficeMatchingController.cls --json --loglevel fatal
17:21:02.110 sfdx force:source:deploy --sourcepath /Users/i.beschea/Documents/OHDEV/force-app/main/default/classes/OfficeMatchingController.cls --json --loglevel fatal ended with exit code 1

_I can confirm that is happens with any class_

DeployFailed: Deploy failed.
Additional information
Feel free to attach a screenshot.

VS Code Version:

Version 1.38.1 

SFDX CLI Version:

sfdx-cli/7.26.0-9118501918 darwin-x64 node-v10.15.3

OS and version:

macOS Mojave Version 10.14.6

**Comment by lcampos** [comment]
Hi @IoanB1989 , thanks for reporting this. I'm not able to replicate this by adding a missing method call or similar compilation issues and with the same CLI & VSCode version you're running. Do you get any error output when you run the deploy command directly in the terminal ?

**Comment by IoanB1989** [comment]
I forgot to mentioned that I am using a Project with Manifest, so the code is saved in my sandbox. 

if I try to run the following command to deploy in the terminal 
sfdx force:source:deploy --sourcepath /Users/i.beschea/Documents/OHDEV/force-app/main/default/classes/OfficeMatchingController.cls

I get the following result : 
https://drive.google.com/file/d/11QICCh0AJrHrFJHH-YcbJ2cfQ5wY-GrS/view?usp=sharing
And this result is expected. 

But as mentioned, using **SFDX : Deploy this to source org**, I will get 
https://drive.google.com/file/d/1HRlfjopCaq2Ot5bjwTvzlQTuYF91FpPr/view?usp=sharing

and ...for full details : 
https://drive.google.com/file/d/1sF5p4ggmi-S95J456oLw2EZQ4DjIi31-/view?usp=sharing

It would be nice if I will be able to see the details without having to use the terminal.

**Comment by lcampos** [comment]
@IoanB1989 what the extension does is that it parses the json result from that command and then format it to show results in the Output & Problems view. I'm interested in seeing the json result you are getting to see what's the parsing issue so we can fix the extension since we haven't been able to replicate the issue on our side.
Can you share the json output when you run into this situation ?

**Comment by mgetzbw** [comment]
NOTE: to anyone getting this issue as discussed [here](https://success.salesforce.com/0D53A00004dUxNr) uninstalling the CLI completely and reinstalling seems to be a workaround for this issue.

**Comment by Sukkiiiiii12** [comment]
I am trying to deploy my code to org but I receive the same error even after reinstaling the salesforce cli and vs code. There is no specification to what's the issue either. What should I do?

**Comment by randi274** [comment]
@Sukkiiiiii12 are you able to run the `sfdx force:source:deploy` command using the CLI?

**Comment by Sukkiiiiii12** [comment]
No I am not able to run this command in the terminal either.

**Comment by randi274** [comment]
@Sukkiiiiii12 it sounds like something isn't quite set up correctly with the Salesforce CLI. For more help with the CLI, you'll want to check in with that team here: https://github.com/forcedotcom/cli/issues

Or consult the troubleshooting docs again here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_troubleshoot.htm
