### ISSUE TITLE
VSCODE > Default> (Right Click) SFDX Commands Missing

### ISSUE THREAD

**Issue by rkozlin** [forcedotcom/salesforcedx-vscode#1696]
### Summary 

After closing VS Code and re-opening the SFDX Right Click options are not present for SFDX project created with SFDX Create w/ Manifest command.  
Initial create of project and options are there and retrieve / deploy works. 

Other details possibly relevant... 

- Org is a dev sandbox, not scratch. 
- Dev machine is azure vm running Windows Server 2016. 
- User has full admin privileges on the vm. 
- All installs run w/ admin privs.
- VS code when launched, launched w/ admin privs. 
- Installs are all new with latest versions available. 

### Steps To Reproduce:

1. sfdx cmd create project w/ manifest 
2. retrieve source from org. it works. 
3. try right-click option- they are there and work properly
4. close vs code
5. open vs code
6. open same ws folder again
7. no right click options available at any level / any file in the sfdx project structure 
8. attempt sfdx auth w/ org, which works, no change no right click options 
9. attempt sfdx cmd to refresh object defs, that works no issue, still no right click options 

### Expected result

Right-click options for SFDX Retrieve from Org and Deploy to Org are available after closing and reopening VS Code / WS folder. 

### Actual result

Right-click options for SFDX Retrieve from Org and Deploy to Org are NOT available after closing and reopening VS Code / WS folder.

**VS Code Version**: _(copied from VS Code -> Help -> About)_
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

**SFDX CLI Version**: _(copied from terminal)_ 
Salesforce CLI

VERSION
  sfdx-cli/7.26.0-9118501918 win32-x64 node-v10.15.3

**OS and version**: Windows Server 2016

**Comment by lcampos** [comment]
Hi @rkozlin , if you open VSCode's Dev Tools (Help > Toggle Developer Tools and select Console tab) do you see any errors ?
Also, if you open VSCode's terminal can you run sfdx commands ? e.g. `sfdx version`

**Comment by rkozlin** [comment]
Yes I can run sfdx commands in terminal- that is how I got the SFDX version text in the post. 
In case its relevant, other right-click context options show such as "SFDX: Create Apex Class" when right-clicking on the /classes folder in the explorer. 
Dev Tools Console shows this; 
![image](https://user-images.githubusercontent.com/624084/66424090-ed9ad380-e9da-11e9-84da-906a214984f0.png)

**Comment by lcampos** [comment]
Ok, so the extensions seem to be activating properly. The next thing I can think of is that somehow the evaluation of the `defaultusername` is failing and causing those commands not to show. Did you setup a `defaultusername` with special characters on it or on its alias ? You can check that in your project's `.sfdx/sfdx-config.json` file.

**Comment by rkozlin** [comment]
No... I used the default alias and username gets set to the email the SF org uses to login. 

You incorrectly flagged this as "needs more info". Pls read #8 in the Steps to Reproduce. Auth w/ Org works.  So you knew this was not the issue already based on that previously provided information.

**Comment by lcampos** [comment]
@rkozlin to clarify, my question was important because depending on the format of the `defaultusername`, there are differences in how it gets evaluated. I'm trying to figure out if that is what's causing the commands not to show even when you've stated that other operations still work. Some of this evaluations happen at startup so there's a possibility that changing a configuration will not immediately cause that code to trigger but it will once you restart the editor.

Regarding the `more information required` label, we use it internally to track the issues we're trying to debug but still need more information to be able to replicate it on our side.

I'll see if I can replicate this on our side with the new info you've provided.

**Comment by gwallaceSiriusly** [comment]
I had this issue and it was a git merge issue on the ProjectName.code-workspace file. There was some unimportant changes in the file that created a GIT conflict and I hadn't noticed them come in, giving me "<<<<<<<" GIT message in my file. Once I took those out the tools came back up right away, so another thing to check would be that file. The cause (as I understand it) is this file is the config for the DX project, so a fault in this file means VS code to fall back onto a default project. 

More information on DX projects:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_workspace_setup.htm

It'd be nice to get a warning dialog that we were trying to load a DX project but the config was invalid, but hey... if this was easy everyone would do it...

**Comment by anandsubram** [comment]
@rkozlin  - Curious if you were you able to find any resolution for this issue? I also have the same frustrating issue as you mentioned above, which force me to open a blank VS Code and got through all the steps of retrieval as workaround

**Comment by uvaiskomathsfdc** [comment]
this is a bit frustrating. it works with sandbox but it does not work with scratch org. 
![image](https://user-images.githubusercontent.com/53842192/134828539-7c691c1d-d36d-4a63-888b-c06a0af2ddf1.png)

there are no special characters in my name

**Comment by smaddox-sf** [comment]
Hi @uvaiskomathsfdc - [Please open a new issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md&title=) with the details and we'd be happy to investigate.

**Comment by henrystaples** [comment]
I had this problem when I opened VSCode in a parent directory 2 levels up from the salesforce project. It didn't seem to recognize the org settings and so I couldn't get the right-click to SFDX: Create Apex Class, etc. The window on the left is opened to the parent's parent dir (the root of the GitHub project). The window on the right is opened to the SF project dir (which has the right-click commands available). Notice that the window on the right shows the Org connection in the bottom status bar.

![image](https://user-images.githubusercontent.com/29614738/182046027-30e598f9-0b9a-4b2b-9066-163c4f7cfc40.png)

**Comment by rkozlin** [comment]
@henrystaples that option was showing for me, I mentioned it earlier, the create apex class. This was specifically for the retrieve from/deploy to org options not showing up. 
That said, your screenshots are compelling.. and iirc that project 3 years ago was probably down a few folders as yours on the left shows.. hmm.

**Comment by henrystaples** [comment]
Yeah, I feel like it's a structural issue that its pattern matching for displaying the commands either assumed would be in place or got confused by whatever you had opened and so it didn't match/display commands.

**Comment by hb-webdev** [comment]
> I had this problem when I opened VSCode in a parent directory 2 levels up from the salesforce project. It didn't seem to recognize the org settings and so I couldn't get the right-click to SFDX: Create Apex Class, etc. The window on the left is opened to the parent's parent dir (the root of the GitHub project). The window on the right is opened to the SF project dir (which has the right-click commands available). Notice that the window on the right shows the Org connection in the bottom status bar.
> 
> ![image](https://user-images.githubusercontent.com/29614738/182046027-30e598f9-0b9a-4b2b-9066-163c4f7cfc40.png)

That was it--Thank you! You need to open a directory containing `sfdx-project.json` to connect to Agentforce/see the SFDX menu options.
