### ISSUE TITLE
sfdc-diff installation issue: tunneling socket could not be established

### ISSUE THREAD

**Issue by savage25** [forcedotcom/salesforcedx-vscode#1700]
Attempting to install sfdx-diff

`sfdx plugins:install @salesforce/sfdx-diff`

I get the following error:
```
K:\>sfdx plugins:install @salesforce/sfdx-diff
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
error An unexpected error occurred: "https://registry.yarnpkg.com/@salesforce%2fsfdx-diff: tunneling socket could not be established, cause=write EPROTO 15208:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:252:
".
Installing plugin @salesforce/sfdx-diff... !
Error: yarn add @salesforce/sfdx-diff@latest --non-interactive --mutex=file:C:/Users/XXX/AppData/Local/sfdx/yarn.lock --preferred-cache-folder=C:/Users/XXX/AppData/Local/sfdx/yarn --check-files exited with code 1
    at ChildProcess.forked.on (C:/Users/XXX/AppData/Local/sfdx/client/7.27.0-714f62f9c1/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)
```

I am behind a firewall.  However, we have exceptions in place for SFDC ip's and I am able to update sfdx successfully
`sfdx update`
(connected and upgraded successfully from 7.22 to 7.27

I tried with setting HTTP_PROXY and HTTPS_PROXY environment variables too, however when those are set, it doesn't even get to the signature question:
```
K:\>sfdx plugins:install @salesforce/sfdx-diff
Error: tunneling socket could not be established, cause=write EPROTO 12788:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:/ws/deps/openssl/openssl/ssl/record/ssl3_record.c:252:
    at ClientRequest.onError (C:/Users/XXX/AppData/Local/sfdx/client/7.27.0-714f62f9c1/node_modules/tunnel-agent/index.js:177:17)
```

VERSIONS:
```
K:\>sfdx --version
sfdx-cli/7.27.0-714f62f9c1 win32-x64 node-v10.15.3
```
Microsoft Windows [Version 10.0.17763.678]

**Comment by lcampos** [comment]
Thanks for opening this issue @savage25 . The cli plugins are published and installed from the npm registry (https://www.npmjs.com/). Does your firewall allow you to install packages hosted there ?

**Comment by savage25** [comment]
I'm able to view the website in a browser and lookup the IP from the command line.

`C:\WINDOWS\system32>nslookup npmjs.com
Server:  XXXX
Address:  XXXX

Non-authoritative answer:
Name:    npmjs.com
Addresses:  2606:4700::6810:5d53
          2606:4700::6810:5c53
          104.16.92.83
          104.16.93.83
`
