### ISSUE TITLE
Namespaced orgs mess replay debugger and test running

### ISSUE THREAD

**Issue by Gkupce** [forcedotcom/salesforcedx-vscode#1701]
I've been working with a Salesforce dev org and noticed that the replay debugger couldn't find the files to show the current execution line.
One day I noticed the `sfdx-project.json` file contained a field for namespace. I modified the field and the replay debugger started working perfectly. I thought the problem solved and continued working.
Later I found that when running tests, the test sidebar would preface the classes with the namespace, while mildly annoying since it made all clases take a lot of space, it was nothing to really complain about, but when I run a test I noticed that the results were not being shown on the sidebar.

# Steps to reproduce
1. Create a dev org with a namespace
2. Create a test
3. Turn on apex log for replay debugger
4. Run the test
5. Confirm "namespace"
6. Download log
7. Launch replay debugger with log
8. Modify `namespace` value of `sfdx-project.json` to the instance's namespace
9. Run the test
10. Check test status on sidebar
11. Download log
12. Run replay debugger

**Comment by lcampos** [comment]
Thanks for opening this issue @Gkupce. This is a known gap we'll be addressing in the following releases of the extensions.
cc @ntotten

**Comment by lcampos** [comment]
This is fixed in release `v47.4.0`, thanks for opening this issue.
