### ISSUE TITLE
Including a .prettierrc File Overrides all Settings for Prettier

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/salesforcedx-vscode#1714]
### Summary

When the .prettierrc file is included in the org creation (as is done by default) it overrides all prettier settings. This means you cannot specify global defaults for your formatter--all customizations will be ignored if they are not included in the prettier file. 

### Steps To Reproduce:

See summary

### Expected result

There is an option to set global values for the formatter

### Actual result

This is not an option due to the choice to create the override file

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by klewis-sfdc** [comment]
Hi @NuAgeDan, thank you for creating the issue.  A number of improvements have been made to the Extensions since this issue was created. Please let us know if this is still an issue for you and we will review.  Thank you.
