### ISSUE TITLE
Typing causing excessive writing of jsconfig.js and high cpu usage

### ISSUE THREAD

**Issue by jeffhube** [forcedotcom/salesforcedx-vscode#1728]
### Summary

Related to https://github.com/forcedotcom/lwc-dev-server-feedback/issues/32 , it seems that the salesforce.salesforcedx-vscode-lwc extension will repeatedly write to `force-app\main\default\lwc\jsconfig.json` while typing in a lightning web component js file. If I press the spacebar in a js file 20 times at a rate of 2-3 times per second, the extension will write jsconfig.json ~20 times, which seems completely ridiculous to me. There does seem to be some debouncing, but the timing must be a few hundred milliseconds at most. My cpu usage also sits at 100% while typing which may be due to antivirus repeatedly scanning the file, this does not occur in non-Salesforce javascript projects. If I'm also running the [Local Development Server](https://developer.salesforce.com/blogs/2019/10/announcing-lwc-local-development-beta.html), typing will be noticeably laggy because the dev server sees the file changes and keeps reloading as I type.

### Steps To Reproduce:

1. Open a sfdx project in VSCode
1. Use [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to watch for WriteFile operations in the project directory
1. Start typing in a Lightning Web Component's js file
1. Observe procmon showing jsconfig.json being written over and over and over again

### Expected result

Typing in a Lightning Web Component's js file does not cause excessive writing of jsconfig.json. Maybe it doesn't cause any writing at all.

### Actual result

Typing in a Lightning Web Component's js file causes excessive writing of jsconfig.json

### Additional information

![jsconfig](https://user-images.githubusercontent.com/1283264/67304561-05d21e80-f4c2-11e9-95a0-256bfb4afccd.png)

**VS Code Version**: 1.39.2

**SFDX CLI Version**: sfdx-cli/7.28.7-7bceba6f24 win32-x64 node-v10.15.3

**OS and version**: Windows 10 Version 1903

**Comment by AndrewRayCode** [comment]
Related to https://github.com/forcedotcom/salesforcedx-vscode/issues/1578 - this plugin should never be automatically creating or writing to files

**Comment by rtm** [comment]
What is the status of this? Among other problems, it causes git merge conflicts on virtually every merge.

**Comment by smaddox-sf** [comment]
This is how the JS language server works. Our suggestion is to not commit this file to source.
