### ISSUE TITLE
"Go to Definition" and "Peek Definition" not working

### ISSUE THREAD

**Issue by Radamanf** [forcedotcom/salesforcedx-vscode#1732]
### Summary
"Go to Definition" and "Peek Definition" not working, if open Page or Component and try to quickly go to source class it's derived from. This is working in Sublime+MavensMate, but not in VS Code recommended by Salesforce - shame on you SF! [SF bug marked as NoFix](https://success.salesforce.com/issues_view?id=a1p3A00000031YtQAI)
Similar closed cases not resolved: #1269 #653 #557

### Steps To Reproduce:
1. Right click on the method/extension/controller you want to see the definition.
2. Select "Go to Definition" from menu.

### Expected result
Open Class file

### Actual result
Error, but it does work sometimes for certain classes. Definitely not for Visualforce Pages and Components.

### Additional information
![image](https://user-images.githubusercontent.com/1901746/67393418-3ab1a480-f59a-11e9-9d72-9c64316998e5.png)

### Suggested fix
I expect simple fix can solve this: System should read whole word and search class folder by file name ignoring exception, should should be enough to find class definition, at least.

**VS Code Version**: 1.39.2
**SFDX CLI Version**: sfdx-cli/7.28.7-7bceba6f24 win32-x64 node-v10.15.3
**OS and version**: Microsoft Windows [Version 6.1.7601]

**Comment by danbrycefairsailcom** [comment]
I have the same problem.

For example, in the line:

    TestData.createTestData();

I can Ctrl+Click on `TestData`, and the file is opened. However, I can't Ctrl+Click on `createTestData` ("No definition found").

Interestingly, enabling semantic errors highlights `TestData` with the error "Variable does not exist" (or in other, similar cases the error is "Invalid type").

I have refreshed the SObject definitions, no luck. No errors in the Apex Language Server output.

**Comment by prasannakumar312** [comment]
@danbrycefairsailcom  - Any luck with this? I have the same problem. Initially hovering over ClassName or Method name by holding command button did not show any references and "Go To Definition" was not working.
After enabling "Enable-semantic-errors" & "Enable-sobject-refresh-on-startup" to true, "Go To Definition" started working. Below is the path to get to above two settings" on a Mac
   Code -> Preferences -> Settings -> Extensions -> Salesforce Apex Configuration
Also ensure you have the correct version of java installed for the Salesforce Extension Pack extension (currently either java8 or java11)

But, I am not able to get the hyperlink on the "Method" of a class (ClassName.MethodName) nor  I am able to go to the exact method name, when I hit the command button and click on the method name. However, I am able to go to the other class when I hit the command button and click on the class name.

Can anyone help me figure this out?

Thanks in advance!
<img width="1003" alt="Screen Shot 2020-03-27 at 9 41 20 PM" src="https://user-images.githubusercontent.com/19479447/77815036-d4aed900-7073-11ea-885e-7862b0747aca.png">

**Comment by prasannakumar312** [comment]
Hi all - I just reverted back the above two settings to false in "Settings" and everything started working fine. I believe this is intermittent issue. Do we know the root cause for this? How can we fix this?

**Comment by OlegDobriy** [comment]
Hi all. For me "Go to Definition" is not working completely. I can't navigate neither classes nor methods. After hovering classes or methods nothing happens. Could anybody help to solve this issue?
VSCode version: 1.52.1.

**Comment by NIKHILMVS** [comment]
@OlegDobriy Thank you so much, I have been searching for this for the past week. 

The solution as suggested by @OlegDobriy: If you have installed multiple versions of any language, either keep only one version as I did or specify the language in VS Code()
