### ISSUE TITLE
SOQL Language Server - Tokens with multiple words don't always auto-complete as expected

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/salesforcedx-vscode#1749]
### Summary

When using the SOQL auto-complete on 'ORDER B' or 'GROUP B' the result is replaced by 'ORDER ORDER BY' and 'GROUP GROUP BY', respectively. This issue also happens with NULLS FIRST and NULLS LAST becoming 'NULLS NULLS FIRST' and 'NULLS NULLS LAST', respectively.

### Steps To Reproduce:

1.  Type the query `SELECT Name FROM Account ORDER B` in a .soql file.
1.  Run auto-completion with Ctr+Space.
1.  Select 'ORDER BY' as the auto-complete token.

### Expected result
My query should become `SELECT Name FROM Account ORDER BY`.

### Actual result

My query becomes `SELECT Name FROM Account ORDER ORDER BY`.

**Comment by smaddox-sf** [comment]
Combining with this duplicate - https://github.com/forcedotcom/salesforcedx-vscode/issues/1742
