### ISSUE TITLE
 self signed certificate in certificate chain

### ISSUE THREAD

**Issue by TimeMachineIdo** [forcedotcom/salesforcedx-vscode#1751]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
Not sure what this means, I'll close it for now but feel free to reopen it if you have more details that would allow us to understand the issue.
