### ISSUE TITLE
org browser with multiple open projects, requiring manual refresh to change orgs

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#1761]
# Summary

Org browser attaches to the wrong org

### Steps To Reproduce:

1. connect vscode to an org [we'll call this project A]
2. Do something in the org browser (like list the objects)
3. create another project and connect vscode to another org [call this project B]

### Expected result

Org browser in Project A pulls from Org A, Org Browser in Project B pulls from project B

### Actual result

Org browser in Project B pulls from Org A.

### Additional information
at the top of the org browser sidebar, it does at least tell you the name of the org it's connected to, and if you look carefully you'll notice it doesn't match the default org listed at the bottom.

Manually refreshing with the circle-arrow at the top of the sidebar switches to the current default org. 

VS Code Version:
1.39.2

SFDX CLI Version:
sfdx-cli/7.23.1 darwin-x64 node-v10.16.3
salesforcedx 47.3.7

OS and version:
mac mojave 10.14.6

**Comment by brpowell** [comment]
Switching to the org browser view will update it to the selected org with the latest release (47.5.0)
