### ISSUE TITLE
I am getting an error that doesnt enable highlights for my code coverage

### ISSUE THREAD

**Issue by chouloute1** [forcedotcom/salesforcedx-vscode#1762]
### Summary
I am getting this error: 
No test run information was found for this project. Set "salesforcedx-vscode-core.retrieve-test-code-coverage": true in your user or workspace settings, then run Apex tests from the Apex Tests sidebar or using the Run Tests or Run All Tests code lens within a test class file.
_Short summary of what is going on or to provide context_.

This is blocking me from seeing lines covered by my test class for my APEX classes.

### Steps To Reproduce:

1.  This is step 1. Install Salesforces extension pack
1.  This is step 2.  Sync to a sandbox and run test
3. make sure  salesforcedx-vscode-core.retrieve-test-code-coverage": true is set in settings
4. click the 3 stacked horizontal lines on bottom left which if you hover over it, it will display : Highlight Apex Code Coverage 

### Expected result
If you navaigate to apex class that should be tested there is no highlighted lines
_Describe what should have happened_.
There should be highlighted lines of code coverage
### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
Hi @chouloute1 thanks for opening this issue. I think the issue might be that you are enabling the setting after you've ran the test. Can you try running the test after you've enabled the `salesforcedx-vscode-core.retrieve-test-code-coverage: true` setting ?

To provide a little bit more background on this. The way the code coverage highlight works is based on the information we get from the test run. Every time you run a test there are test result files created under the project's `.sfdx/tools/testresults/apex/` folder. If you enable `salesforcedx-vscode-core.retrieve-test-code-coverage": true` setting the results will include a code coverage section as part of the results. If you open the latest `test-result-<test-run-id>.json` file you should see a `coverage` object that contains the coverage information of the pieces of code the test that was executed covers (example below). 

Can you confirm your test results file contains coverage data and that the lines in that data are not being reflected in the UI when enabling the code coverage highlighting feature (toggle the 3 line icon next to the org name in the footer).

![enable_ui_code_cov_highlight](https://user-images.githubusercontent.com/1041842/67984635-652bdf00-fbe4-11e9-9a13-6a39e2730e7f.png)


```
    "coverage": {
        "coverage": [
            {
                "id": "<ID>",
                "name": "Logger",
                "totalLines": 4,
                "lines": {
                    "2": 1,
                    "4": 1,
                    "5": 1,
                    "9": 0
                },
                "totalCovered": 3,
                "coveredPercent": 75
            }
        ],
```
