### ISSUE TITLE
ForceCode menu not displaying

### ISSUE THREAD

**Issue by hellosibun** [forcedotcom/salesforcedx-vscode#1770]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

Forcode Menu is not displaying
### Expected result

it should be displaying forceCode Menu but it didnt it showing error
### Additional information

On notification menu its showing this error message 

Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log.

**VS Code Version**:
vs code version 1.39
**SFDX CLI Version**:
v7.31
**OS and version**:
 win 7 32-bit
![Capture](https://user-images.githubusercontent.com/34995065/68190451-70f81680-ffd3-11e9-9151-ec36f4acb977.JPG)

**Comment by ntotten** [comment]
@hellosibun Please provide the content of the file `~/.sfdx/sfdx.log`
