### ISSUE TITLE
command 'sfdx.force.project.create' not found

### ISSUE THREAD

**Issue by sirideva** [forcedotcom/salesforcedx-vscode#1778]
I've confirmed the install of Salesforce CLI and Salesforce Extensions.

When I try to create a SFDX project in VS I get the error:

command 'sfdx.force.project.create' not found

Console gives the error:
(https://user-images.githubusercontent.com/35934937/68392896-c994f400-0138-11ea-9da8-7268f228da1c.PNG)

sfdx version at command line gives:

(https://user-images.githubusercontent.com/35934937/68392967-f47f4800-0138-11ea-8c76-163909d58af9.PNG)

Please let me know if you can help.

Thanks!
Siri

**Comment by lcampos** [comment]
Hi @sirideva , could you provide the following info on your setup:
- Salesforce Extensions for VSCode version
- OS version (e.g. Windows 10)

FYI, I've seen this happen on Windows when the System Environment variable `PATH` does not include the path for the Salesforce CLI.
