### ISSUE TITLE
Add support for JDK 13

### ISSUE THREAD

**Issue by daemonic13** [forcedotcom/salesforcedx-vscode#1781]
### Summary

OpenJDK v11.0.5 does not work with plugin (while older OpenJDK 11 did)

### Steps To Reproduce:

Install OpenJDK jdk-13.0.1
Start VS Code with Salesforce Extensions enabled

### Expected result

No errors.

### Actual result

Java 8 is required to run.
![image](https://user-images.githubusercontent.com/753286/68490839-b73db780-0217-11ea-9d53-b1ac611a1555.png)

### Additional information

**VS Code Version**: 
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**SFDX CLI Version**:  
sfdx-cli/7.31.0-6a986f8be5 win32-x64 node-v10.15.3

**OS and version**: 
Windows 10 Version 1903, Build 18362.418

**Comment by arneper** [comment]
any word on this? I know you changed heading but v11.0.5 jdk-11.0.5 not working. Thanks

**Comment by ntotten** [comment]
Java 13 is not supported. You need 8 or 11. See: https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup

**Comment by smaddox-sf** [comment]
This is not actionable for now, so closing.  When there are updates to the version Apex runs on within the platform, we'll evaluate supporting more java versions
