### ISSUE TITLE
sfdx does not recognize project is open

### ISSUE THREAD

**Issue by NuAgeDan** [forcedotcom/salesforcedx-vscode#1782]
### Summary

Editing because I found the cause and solution. Issue: You open a previously created sfdx project through VSCode. The plugin fails to recognize a project is open.

### Steps To Reproduce:

See title. Under File > Open Folder.

THE CAUSE: sfdx managed to recreate the .sfdx folder in the parent folder of the project and this somehow tripped it up (the original .sfdx folder was/is still in place in the project itself). I did not do this, nor did I open the wrong folder. It just randomly happened as I was coding. I noticed it when my deploy option disappeared (I had compiled several times since opening). 

THE FIX: delete the rouge .sfdx folder. I also re-installed the plugin and it seems fine now.

### Expected result

That the IDE that recognizes open projects and doesn't create stray .sfdx folders. This is getting really buggy. I've had 2 major issues in 4 weeks which have rendered the plugins useless. I get that this is free, but it does have bugs very frequently.

### Actual result

It only lists commands available when no project is open (Create Project options). 

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.25.3-16d54c01ee

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): 46.16

**OS and version**: Win 10, latest.

**Comment by smaddox-sf** [comment]
I believe this has been addressed
