### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by nacharya1234** [forcedotcom/salesforcedx-vscode#1795]
Salesforce CLI Extension taking way too long time to execute as a result commands like Deploy to Org or create new Project is taking hours.
Kindly help

- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `47.5.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.40.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ntotten** [comment]
Please provide the paste data as mentioned in the issue and reopen.

**Comment by nacharya1234** [comment]
Thanks Nathan for the response.
The issue was resolved  by uninstalling and re-installing VSCODE.
The CLI extension was uninstalled and the re-installed using the correct url as per salesforce training guide.
This is now closed and resolved. :)
