### ISSUE TITLE
apex "switch" command is not recognized in syntax highlight

### ISSUE THREAD

**Issue by alachmann** [forcedotcom/salesforcedx-vscode#1799]
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_switch.htm

**Comment by lcampos** [comment]
Hi @alachmann thanks for opening this issue. Could you provide more details on which scenarios you are running into where syntax highlight is not working for switch statements ? The screenshots below are from version 47.6.0 of the Salesforce extensions.

![Screen Shot 2019-11-15 at 5 50 46 PM](https://user-images.githubusercontent.com/1041842/68986065-8853b280-07d0-11ea-95b3-8a13462c1c97.png)

![Screen Shot 2019-11-15 at 5 47 46 PM](https://user-images.githubusercontent.com/1041842/68986067-8b4ea300-07d0-11ea-9697-658d9ad62dc3.png)

**Comment by alachmann** [comment]
Hi
Sorry for false alert
Indeed in latest version, it works as you say
Regards
