### ISSUE TITLE
SFDX CLI not communicating with org

### ISSUE THREAD

**Issue by jonmlinch** [forcedotcom/salesforcedx-vscode#1801]
### Summary

When trying to save/deploy or retrieve from the org, nothing happens. No warning/error message. Settings is configured to deploy on save but when document is saved no deployment occurs. Additionally, if I right click on the document and click "Deploy source to org", again nothing happens. No message or anything to indicate that anything is happening. Tested with a project in a different org and that one seems to be working fine.  

### Steps To Reproduce:

1.  Set project to deploy on save
2. make change to project
3. Save project

### Expected result

Project should save and changes should be deployed to the project's org

### Actual result

Project is saved but not deployed. No pop-up indicating it is being deployed comes up.

### Additional information

Additionally if I go to the org browser extension, normally it would show all the metadata available to retrieve for the project after a short loading period. However, currently it just keeps showing the loading animation but never actually loads the metadata.

If I restart vscode, it will work as expected for 1-2 deployment attempts but then shows the same symptoms.

**VS Code Version**: 1.40.1

**SFDX CLI Version**: 47.6.0

**OS and version**: MacOS 10.13.6

**Comment by lcampos** [comment]
Hi @jonmlinch thanks for opening this issue. Based on what you've said about deploy on save working for another project I think what might be happening is that there's a config override.

VSCode supports workspace settings and user settings. The workspace settings file is located on your project's `.vscode/settings.json` while the user settings file varies based on platform. The user settings apply globally to any instance of VSCode and the workspace settings apply only to the workspace you are working on. I think what might be happening is that you've enabled deploy on save on your user settings but this particular project has explicitly disabled it in the workspace settings. Can you confirm if this is the case ?
