### ISSUE TITLE
No support for lightning web component template syntax

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/salesforcedx-vscode#1802]
VS Code attempts to validate style attributes as valid CSS even when a template string is used. This results in an error.

```html
<template>
    <div style={myMethod}>
    </div>
</template>
```

<img width="437" alt="Screen Shot 2019-11-15 at 3 12 16 PM" src="https://user-images.githubusercontent.com/79215/68982326-63a11000-07bb-11ea-9845-11d7a90c1acc.png">

> } expectedcss(css-rcurlyexpected)

**Comment by cnaccio** [comment]
In the meantime, using the Vue-html language mode for lwc html files makes this error go away.
