### ISSUE TITLE
Authorize an Org - Keeps running

### ISSUE THREAD

**Issue by vibhudadhichi** [forcedotcom/salesforcedx-vscode#1803]
### Summary
Unable to Authorize an org through SFDX: Authorize an Org

### Steps To Reproduce:

1.  Create a Project with SFDX: Create Project with manifest
2.  Authorize an Org with SFDX: Authorize an Org
    a. Select Sandbox
    b. Enter Alias for the org

### Expected result

Browser should open which allows us to enter the credentials which authorizes an org

### Actual result

The browser never opens and the Authorize an org bar keeps going on and on
### Additional information

![image](https://user-images.githubusercontent.com/14141170/68993008-f95e9d00-0898-11ea-83b9-ab987367556d.png)

**VS Code Version**: Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**OS and version**: Microsoft Windows 10 Enterprise 64-bit

**Comment by alirizvi1992** [comment]
Even I am facing this issue. Can anyone please help us with this?

**Comment by GauravGupta810** [comment]
Any luck? I am facing the same.

**Comment by gyan0708** [comment]
I am also facing same from around past 15 days.

**Comment by lcampos** [comment]
Hi @vibhudadhichi , I think you and the rest of the people in this thread are facing the same issue as described in issue #1654 . When you run the auth command the extensions use the browser you've added as default at the OS level. It seems that in certain scenarios the Chrome browser is not responding in Windows. Can you try configuring a different browser and see it that unblocks you ?

**Comment by vibhudadhichi** [comment]
And it worked! Thank you so much :)
