### ISSUE TITLE
Couldnt start client Aura Language Server

### ISSUE THREAD

**Issue by Aldemaro14** [forcedotcom/salesforcedx-vscode#1804]
Issue Type: <b>Bug</b>

1. open VSCode 1.
1. There is a message un the right botton corner that say Coudn't start client Aura Language Server

Extension version: 47.6.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment]
Hi @Aldemaro14 could you provide more information so we can try and replicate the issue you are running into ? For example, if you open them `Output` tab on the VSCode terminal and select `Aura Language Server` in the picklist on the right do you see any error message being printed ?

**Comment by MayankDkPant** [comment]
Hi - I am also facing same issue. Error of output tab on VS Code terminal and under Aura Language Server is [Error - 15:16:39] Starting client failed
Error: spawn C:\Users\****\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

Anyone know hot to fix this?

**Comment by neelgo** [comment]
- VSCode Version: 1.40.2
- OS Version: windows 10

Steps to Reproduce:
I am using it for salesforce development and install salesforce extension pack
I am getting error from Aura Language server
[Error - 11:36:05 AM] Starting client failed
Error: spawn C:\Users\.....\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

*Tried reinstalling extension it failed shows same error
and reinstalled vscode also still same.
* Not sure but it is happening after last update. how I can go back to last version?


Does this issue occur when all extensions are disabled?: Yes/No
* Not sure how to do that and also I have to use it with extenstion for salesforce development
if it works without them still it is not useful.

![image](https://user-images.githubusercontent.com/9036100/70596788-c051e800-1c0c-11ea-95ac-05b5bf671432.png)
