### ISSUE TITLE
Stop opening the output terminal every time there is a deploy on save

### ISSUE THREAD

**Issue by sc5148** [forcedotcom/salesforcedx-vscode#1806]
At present if deploy on save is enabled, every time I press ctrl+s to deploy the file, the output terminal pops up which is really irritating. Instead it should only open up when there is an error and in all other cases the small popup box to the right (see picture) is enough to know if it was successful or not.
![Annotation 2019-11-18 094812](https://user-images.githubusercontent.com/19307757/69037663-8d8b4a00-09e8-11ea-8403-e663c10227e4.png)

**Comment by lcampos** [comment]
I'm closing this since it's been addressed on release `47.15.0`. Thanks for your feedback.
