### ISSUE TITLE
Browser not launching at SFDX: Authorize an Org

### ISSUE THREAD

**Issue by Fr33zm4n** [forcedotcom/salesforcedx-vscode#1807]
When initiating the command SFDX: Authorize an Org (default org and default alias) this command will run forever and will not launch a log-in screen in any of my browsers. 

```
Starting SFDX: Authorize an Org

21:47:49.431 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://login.salesforce.com --setdefaultusername
21:51:14.584 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://login.salesforce.com --setdefaultusername ended with exit code 1

Starting SFDX: Authorize an Org

21:53:08.424 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://login.salesforce.com --setdefaultusername
21:54:14.518 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://login.salesforce.com --setdefaultusername ended with exit code 1

Starting SFDX: Authorize an Org

21:54:20.648 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://login.salesforce.com --setdefaultusername
```

![Capture](https://user-images.githubusercontent.com/41642607/69093512-df66bb00-0a4e-11ea-8915-a6bfef130282.PNG)

**Comment by lcampos** [comment]
Hi @Fr33zm4n can you provide more information about your setup so we can try and replicate on our side ? Here's the info we need:
- VS Code version
- Salesforce extensions for VSCode version
- Salesforce CLI version
- Operative System & version e.g. Windows 10

**Comment by seanperez-salesforcegit** [comment]
> Hi @Fr33zm4n can you provide more information about your setup so we can try and replicate on our side ? Here's the info we need:
> 
> * VS Code version
> * Salesforce extensions for VSCode version
> * Salesforce CLI version
> * Operative System & version e.g. Windows 10

Hi!
Im having the same problem. The sfdx force:auth:web:login -h is working for me, smoothly but when I execute the sfdx force:auth:web:login -r https://test.salesforce.com... it takes FOREVER. i also tried to login in my devhub and other orgs.... SAME RESULT.

I did all the things (I know), nothing. same problem.

btw, here's an info with what uve asked in this issue...
vs code version = latest (coz i reinstalled my vs code)
Salesforce extensions = Salesforce CLI Integration, Salesforce Extension Pack, Apex, Apex Interactive Debugger, Apex Replay Debugger, Aura Components, ForceCode, Lightning Web Components, Visualforce (btw i tried to uninstall other exteions except for Salesforce Extension Pack and CLI Integration... SAME RESULT)
Salesforce CLI version = latest (coz i reinstalled my sf cli)
OS = Windows 10 64

Hope u can help me. thanks.

**Comment by nickytorstensson** [comment]
Maybe this is related to this open issue:
https://github.com/forcedotcom/salesforcedx-vscode/issues/1888

**Comment by keerthi019** [comment]
Have you got any solution to this?

**Comment by akumthek** [comment]
the root cause is force:auth command is not supported in new version of CLI. you can manually run the command in VS Code terminal, changing force:auth.... to auth:...

sfdx auth:web:login --setalias DevOrg --instanceurl https://login.salesforce.com --setdefaultusername

I tried this and it goes ahead, waiting on localhost forever, but could be my Ubuntu/wifi issue. i tried using wired connectivity as well, but no luck. may be downgrading to lower CLI is the best solution, no idea how to do that. TrailBlazer gives link only to latest.
