### ISSUE TITLE
UI to open a ORG on Visual Code

### ISSUE THREAD

**Issue by MarcilioDevSfdc** [forcedotcom/salesforcedx-vscode#1810]
Today we have the org browser to select and retrieve metadata, I would like some similiar to that feature to select and open several orgs that we have authenticated.

The feature I would like it is something like the ORGanizer that we have in Chrome

**Comment by smaddox-sf** [comment]
Hi @MarcilioDevSfdc - Are you seeking to browse the metadata of multiple Orgs at once?  Or looking to toggle between the authorized Orgs?  We have the Org Picker that lets you switch between authorized Orgs, but unsure if you are describing a different need here.

Here's a visual on the Org Picker and the flow is described in [this section of documentation](https://developer.salesforce.com/tools/vscode/en/user-guide/development-models/#create-project-with-manifest).

![image](https://user-images.githubusercontent.com/59572234/73899665-1d9b9b80-4842-11ea-86e7-abb17ffa2f91.png)

**Comment by MarcilioDevSfdc** [comment]
@smaddox-sf  Yes, this looks fine! I would like to click on that org and open it in the browser! Actually I need to write sfdx force:org:open -u org-name

**Comment by smaddox-sf** [comment]
Hi @MarcilioDevSfdc - There is a clickable icon right next to the Org alias that you saw in the last screenshot.  If you click this, it will open the Org.  You can then swap to another org, click it again and that Org will be opened.  here's the icon I'm referring to:

![image](https://user-images.githubusercontent.com/59572234/74371026-f175a280-4d8c-11ea-9579-181d3328f446.png)

**Comment by MarcilioDevSfdc** [comment]
@smaddox-sf  great I haven't noticed this!  thank you!
