### ISSUE TITLE
Enhance ISV debugger docs

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/salesforcedx-vscode#1811]
**Is your feature request related to a problem? Please describe.**
Customer feedback at DF19: ISV Debugger's initial setup steps are difficult to follow and made it difficult to get to use the debugger
(https://developer.salesforce.com/tools/vscode/en/apex/isv-debugger)

**Describe the solution you'd like**
Should re-write the setup steps to make it easier to follow them and get the ISV Debugger up and running.

**Comment by diyer** [comment]
I am going to close this one as this does not have enough data on what needs improvements. We are setting up ISV debugger as part of fixing few bugs in this area. As part of that we will update the doc as needed.
