### ISSUE TITLE
Error on running tests

### ISSUE THREAD

**Issue by oriolete** [forcedotcom/salesforcedx-vscode#1813]
### Summary

When I run an apex test  an error show on output:

13:52:16.575 sfdx force:apex:test:run --tests GlobalUtilsLabelsTest.testUpdate --resultformat human --outputdir /xxxxx/.sfdx/tools/testresults/apex --loglevel error --codecoverage
Unhandled rejection CodeCoverageRetrievalFailed: Cannot read property 'Id' of null
    at records.forEach.record (/xxxxx/.local/share/sfdx/client/7.33.2-045d48473e/node_modules/salesforce-alm/dist/lib/apex/apexTestApi.js:906:54)
    at Array.forEach (<anonymous>)
    at force.getApexCodeCoverage.then.coverageResponse (/xxxxxx/.local/share/sfdx/client/7.33.2-045d48473e/node_modules/salesforce-alm/dist/lib/apex/apexTestApi.js:905:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR running force:apex:test:run:  Cannot read property 'message' of undefined
13:52:32.866 sfdx force:apex:test:run --tests GlobalUtilsLabelsTest.testUpdate --resultformat human --outputdir /xxxxx/.sfdx/tools/testresults/apex --loglevel error --codecoverage ended with exit code 1

### Steps To Reproduce:

1.  Run a test in a test class

### Expected result

No error 🤷🏽‍♂️ and the result of the test executed

### Actual result

When a test is executed an error appears on output and no result showed instead the result is ok o ko

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**SFDX CLI Version**:

sfdx-cli/7.33.2-045d48473e darwin-x64 node-v10.15.3

**OS and version**:

macOS Catalina | 10.15.1

**Comment by lcampos** [comment]
I haven't been able to replicate this yet. Looking at the stack trace it seems like the issue is with the response from the server/org is missing info expected by the CLI. Can you confirm you can successfully log into the org ? I want to discard that the issue is related to authorization.

Assuming you have access to the org, can you tell us what are the test results generated under `/xxxxx/.sfdx/tools/testresults/apex` (filename = `test-result-<test run id>.json`) ?

**Comment by oriolete** [comment]
Hi, you can close this issue. Now I'm able to run tests on all orgs. Thanks

**Comment by lcampos** [comment]
@oriolete that's great. Could you add what you did to get it to work in case someone else runs into the same issue ? Thanks

**Comment by oriolete** [comment]
I think the cli version do the trick 😉
