### ISSUE TITLE
Unable to create a Salesforce DX Project

### ISSUE THREAD

**Issue by morsecodemedia** [forcedotcom/salesforcedx-vscode#1816]
### Summary
Going through the tutorial here: [trailhead.salesforce.com](https://trailhead.salesforce.com/content/learn/projects/quick-start-lightning-web-components/create-a-hello-world-lightning-web-component) to set up a Salesforce DX project. When I try to create the project via the Salesforce VS Code extension or the Salesforce CLI, I am getting the same error saying "**A name parameter is required to create a storage**".

Also checks the steps here: [developer.salesforce.com](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_create_new.htm) to ensure I wasn't missing something, and ending with the same result.

### Steps To Reproduce:
**Via VS Code Extension**
1. Open VS Code
1. `cmd + shift + p`
1. `>sfdx: Create Project`
1. `Standard` for template
1. `test` for project name
1. choose a director and click "Create Project"

**Via Command Line**
1. `sfdx force:project:create --n test --template standard`

### Expected result

A project should have been created.

### Actual result

**Via VS Code Extension**
<img width="736" alt="Screen Shot 2019-11-26 at 2 44 52 PM" src="https://user-images.githubusercontent.com/5315124/69667399-f2374c00-105b-11ea-917a-967857f73535.png">

**Via Command Line**
<img width="614" alt="Screen Shot 2019-11-26 at 2 47 06 PM" src="https://user-images.githubusercontent.com/5315124/69667428-00856800-105c-11ea-8fc7-ef5724b2eae8.png">

### Additional information

**VS Code Version**: Version: 1.40.2

**SFDX CLI Version**: sfdx-cli/7.33.2-045d48473e darwin-x64 node-v10.15.3

**OS and version**: macOS Sierra 10.12.6

**Comment by brpowell** [comment]
Hi @morsecodemedia. This was reported in #253, and it looks like when there's a top-level package.json missing the `name` attribute, this error occurs. Can you check if this is indeed the problem for you?

**Comment by morsecodemedia** [comment]
Hi @brpowell.
Thanks for the response. So strange that you need to arbitrarily create a package.json file with the `name` attribute to run the "create project" command. You would think the package.json file would be created with the the command not prior.

**Comment by brpowell** [comment]
I actually think what might be happening is there _is_ a package.json present in a top level folder relative to where the command is being run. If you find one and remove it it might resolve the issue. It is really odd why this occurs though, might need to look into this some more.

**Comment by morsecodemedia** [comment]
No, there wasn't anything in the folder.
1. `mkdir <folder-name>`
2. `cd <folder-name>`
3. run the stuff as above.

But I did follow your direction and created a random package.json file in the top level folder with the `name` attribute matching was I was planning on calling the project and then it worked as expected.

**Comment by brpowell** [comment]
The culprit here is that if there is a package.json in any ancestor folder of the path you want to make the project in, if the file doesn't have the "name" property it, the generator will fail.

**Comment by Suga-Agustd** [comment]
If you have installed JDK 17, Salesforce CLI extension and VSCODE . Uninstall all of them . And reinstall in below manner 
Reinstall VScode 
Reinstall JDK and make sure variables are set in the variable path .
Reinstall the Salesforce CLI extension package .

It worked for me. Hope it helps you too
