### ISSUE TITLE
Error: spawn cmd ENOENT in VS code

### ISSUE THREAD

**Issue by mishra1207** [forcedotcom/salesforcedx-vscode#1818]
Hi,
I am getting following error while running command- SFDX: Authorize an Org in VS Code:
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [
    '/c',
    'start',
    '""',
    '/b',
    'https://login.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=13f03582c57b^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=0q6hC3VWjMYLBKGHzLGm8g-NkJORu5ASRMfbdxDRyT0'
  ]
}

Could you please help me on this?
I have checked my configs and seems to be good.

Regards.

**Comment by lcampos** [comment]
@mishra1207 can you provide the following details on your setup:
- Salesforce CLI version
- OS version (e.g. Windows 10)
- Salesforce extensions for vscode version

If you are running on a Windows system I've seen similar errors happening when the System Environment variable `PATH` does not include the CLI's path.

**Comment by mishra1207** [comment]
Hi @lcampos,

I was able to resolve the issue.
It was happening due to proxy settings in my company provided laptop. After removing them it started working.
Thank you for your response.

**Comment by baibalorenzo** [comment]
If you still got the same error, you can Goto > Control Panel\System and Security\System\Advance system setting\Enviroment variable and set system variables path C:\Windows\System32\ variable and restart your System. It will fix this error, and you will be able to Authorize an Org.

**Comment by vikasr8** [comment]
@mishra1207 i am facing the same issue but on my personal laptop while using broadband wifi. Could you help me with removing proxy settings.

**Comment by mishra1207** [comment]
@vikasr8 - Please make sure that in your network settings of broadband wifi no proxy setting is selected and auto selection of proxy setting is also disabled. Also make sure no proxy is enabled in your VS code setup.
It should resolve the issue.

**Comment by don08256** [comment]
@mishra1207 thank you! I've been fighting with this for a few months. Turning of auto select worked.

**Comment by Unityfiv** [comment]
I have same error ..alredy i tried all the way like .. added variable.also cleand cache and reinstalled all..but not worked for me... 
But. When i enterd "start expo" command in system32 then worked..but ..when i enter that commamd in my project folder then i have this error.. ..sp plz help me

**Comment by Benoit75** [comment]
Hello, 
Same problem here! I tried al of the above with no success... 
but now it works : i had a training whitespace in my project name (""HelloWorldLightningWebComponent ") instead of "HelloWorldLightningWebComponent"). I removed the project (with 7 Zip trick to delete this directory) and now it's working fine :-)

**Comment by Arulthas05** [comment]
at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by sarojpadhy123** [comment]
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [
    '/c',
    'start',
    '""',
    '/b',
    'https://api.sanity.io/v1/auth/login/github?type=listen^&uuid=c2ef07a4339f04b771a7c4ebe80ce9c8^&source=cli'
  ]


help me with this i am trying to fix it

**Comment by Siesta-7** [comment]
> Error: spawn cmd ENOENT at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19) at onErrorNT (node:internal/child_process:485:16) at processTicksAndRejections (node:internal/process/task_queues:83:21) Emitted 'error' event on ChildProcess instance at: at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) at onErrorNT (node:internal/child_process:485:16) at processTicksAndRejections (node:internal/process/task_queues:83:21) { errno: -4058, code: 'ENOENT', syscall: 'spawn cmd', path: 'cmd', spawnargs: [ '/c', 'start', '""', '/b', 'https://api.sanity.io/v1/auth/login/github?type=listen^&uuid=c2ef07a4339f04b771a7c4ebe80ce9c8^&source=cli' ]
> 
> help me with this i am trying to fix it

Did u solve it ?

**Comment by Arulthas05** [comment]
Path wrong
