### ISSUE TITLE
Documentation did not help in starting server.

### ISSUE THREAD

**Issue by preeti-lightful** [forcedotcom/salesforcedx-vscode#1819]
I was referring https://developer.salesforce.com/tools/vscode/en/lwc/localdev and the 
step 10 Start the server.

![image](https://user-images.githubusercontent.com/32099339/69893161-37ca7200-1305-11ea-9517-b9e244fed10e.png)

this did not work for me instead I had to use `sfdx force:lightning:lwc:start --u <default org Name>`
Please update the documentation. While typing this I understood its a formatting issue , but it looks like actual command, even command line allows it. 😅

**Comment by brpowell** [comment]
Docs have been updated for clarification.

**Comment by preeti-lightful** [comment]
Thanks 👍
