### ISSUE TITLE
"Org Browser: Metadata" adding retrieved metadata to the package.xml

### ISSUE THREAD

**Issue by MichaelPStimpson** [forcedotcom/salesforcedx-vscode#1820]
When downloading metadata via the org browser metadata view there is no option to add that metadata to the package.xml. If you make any changes to that metadata and forget to update your package you could miss the changes. (or have to manually deploy each bit you downloaded)

I'd like to request the option to add that metadata to the package.xml  (at the users discretion) letting us deploy changes easily and quickly.

**Comment by brpowell** [comment]
Hi @MichaelPStimpson, thank you for the suggestion. We are planning on expanding the org browser with this functionality as part of our next roadmap. The feature has been suggested in #1768, so I'm going to go ahead and close out this issue. Feel free to continue the discussion in that thread. Thanks!
