### ISSUE TITLE
SFDX: Retrieve from Source Org is removing namespace prefix

### ISSUE THREAD

**Issue by mikechayes** [forcedotcom/salesforcedx-vscode#1822]
### Summary
When using 'SFDX: Retrieve from Source Org' to pull a lightning component from the source org the namespace prefix is removed.
### Steps To Reproduce:

1.  From the Explorer right click and select  'SFDX: Retrieve from Source Org'

### Expected result
![image](https://user-images.githubusercontent.com/48055186/70086878-3fc63280-15e1-11ea-8a77-de9c4274ecfd.png)

### Actual result
![image](https://user-images.githubusercontent.com/48055186/70086953-62f0e200-15e1-11ea-9cfb-8e82c7c826d7.png)

### Additional information

When you view the code using the Developer Console the namespace prefix (AQBTest__) is there.  If you 'SFDX: Deploy Source to Org with the namespace prefix removed, it will be removed when viewing with Developer Console.

**VS Code Version**:
1.40.2
**SFDX CLI Version**:
47.6.0
**OS and version**:
Windows 10

**Comment by sfsholden** [comment]
@mikechayes Thank you for reaching out on this issue. I am going to be closing this WI. This is a known bug within the MDAPI. 

Please see [here](https://trailblazer.salesforce.com/issues_view?id=a1p4V000001pkykQAA&title=mdapi-retrieve-of-lightning-components-from-namespaced-org-is-removing-namespace-of-objects-defined-in-aura-attribute) for more details. Also please mark that this is issue is affecting you to help prioritize the resolution.
