### ISSUE TITLE
SFDX:Authorize an Org command no longer working as expected  in VS Code

### ISSUE THREAD

**Issue by dev-mks** [forcedotcom/salesforcedx-vscode#1843]
I am facing the issue while Authorize the org in Visual Studio Code editor for Salesforce project.
Error details are below - 

    Starting *AURA* language server at c:\Users\james
    Loading support library: browser
    Loading support library: browser
    Loading support library: ecmascript
    ... language server started in 2712.63 ms
    Loading support library: ecmascript
    [Info  - 3:27:05 PM] ... language server started in 2712.63 ms
    Error queuing up indexing of static resources. Error details:
    Error queuing up indexing of static resources. Error details: TypeError: Cannot read property '0' of undefined
        at Object.indexStaticResources (c:\Users\james\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\lwc-language-server\lib\metadata-utils\static-resources-util.js:55:85)
        at async Promise.all (index 2)
        at async Promise.all (index 0)
        at async Timeout._onTimeout (c:\Users\james\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-47.9.0\node_modules\aura-language-server\lib\server.js:39:9)

**VS Code Version**: 1.40.2

**SFDX CLI Version**: sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3

**OS and version**: Windows 10

**Comment by brpowell** [comment]
Hi @dev-mks, this output is related to an error with the lwc language server that was fixed in today's release 47.10.0. If you update to the latest version you should see this go away.

**Comment by dev-mks** [comment]
> Hi @dev-mks, this output is related to an error with the lwc language server that was fixed in today's release 47.10.0. If you update to the latest version you should see this go away.

Yes, thanks @brpowell
