### ISSUE TITLE
Continually Indexes Lightning Components on OSX

### ISSUE THREAD

**Issue by cleverlemming** [forcedotcom/salesforcedx-vscode#1845]
### Summary

"Indexing Lightning Components" message and spinner in status bar is always present. Restarting makes no difference.

### Steps To Reproduce:

1.  Start VSCode
1.  Restart VSCode

### Expected result

Indexing Lightning Component process should complete.

### Actual result

Indexing Lightning Component process never completes.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: Version: 1.40.2 Commit: f359dd69833dd8800b54d458f6d37ab7c78df520

**SFDX CLI Version**:sfdx-cli/7.33.2-045d48473e darwin-x64 node-v10.15.3

**OS and version**:  OS X 10.15.1

<img width="914" alt="Screen Shot 2019-12-12 at 12 41 36 PM" src="https://user-images.githubusercontent.com/165264/70736255-edba9680-1cdd-11ea-9c03-9cd37bbf3f84.png">

**Comment by AnanyaJha** [comment]
This should be addressed with our latest release (47.10.0).
