### ISSUE TITLE
Invalid attribute "name"

### ISSUE THREAD

**Issue by rexntb** [forcedotcom/salesforcedx-vscode#1855]
Issue Type: <b>Bug</b>

1) Create aura component.
2) Add aura:attribute with the attribute name defined.
3) Push manifest source to an org using the Salesforce CLI.
4) Deploy fails, with error message: Invalid attribute "name".

PS C:\Users\rex\Desktop\MyEverythingProject> sfdx force:source:deploy -u TP25 -x .\manifest\package.xml
PROJECT PATH                                           ERROR
─────────────────────────────────────────────────────  ───────────────────────────────────────────
force-app\main\default\aura\helloWorld\helloWorld.cmp  c:helloWorld:4,59: Invalid attribute "name"
ERROR running force:source:deploy:  Deploy failed.

Extension version: 47.10.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment]
Hi @rexntb I haven't been able to replicate this issue. I created a new component by running `SFDX: Create Lightning Component` and then modifying the `.cmp` file to have an attribute (example below). Can you share more info on the code you are adding to the component ?

Here's a sample of the component I'm using:
```
<aura:component>
    <aura:attribute name="data" type="String" description="Any data to be passed needed"/>
</aura:component>
```

**Comment by ganraj3010** [comment]
declare <aura:attribute> just  below <aura:component>
