### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by payodeleink** [forcedotcom/salesforcedx-vscode#1860]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lightning`
- Extension Version: `47.10.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ntotten** [comment]
We need the info that VS Code added to your clipboard to understand this.
