### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by payodeleink** [forcedotcom/salesforcedx-vscode#1861]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `47.10.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
This seems to have been created by mistake so I'll close it for now. If you want to report an issue or feature request please add more details and re-open.
