### ISSUE TITLE
Error occurred while VS code trying to access the Apex Replay Debugger extension in my local user folder due to a space in the folder name

### ISSUE THREAD

**Issue by VasileFana** [forcedotcom/salesforcedx-vscode#1874]
Due to a space in the folder name that the extension was located "C:\Users\FirstName LastName\..." this extension could not be run. An exception error message was displayed. 

To resolve this issue I had to rename the local folder and add an underscore instead of space. I think this issue could be resolved by escaping any spaces in the file path (route to extension). The other Apex extensions are working fine. 

### Steps To Reproduce:

1.  Install Salesforce Extension Pack (And restart VS code)
2. Create a Project (SFDX command)
3. Authenticate to an org. (SFDX command)
4. Deploy changes. (SFDX command)
5. Toggle Checkpoint. (SFDX: Toggle checkpoint )
6. Try to upload checkpoints to the org. (SFDX: Update checkpoints in org)

### Expected result

Checkpoints should be uploaded to the org

### Actual result

A failure message displayed indicating that the "C:\Users\FirstName " is not recognized as an internal or external command, operable program or batch file.

### Additional information

**VS Code Version**:
1.41.1
**SFDX CLI Version**:
sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3
**OS and version**:
Windows_NT x64 10.0.17134

**Comment by lcampos** [comment]
Hi @VasileFana thanks for logging this issue. I haven't been able to replicate this issue on a Windows 10 machine with the configuration and steps you've listed above. Did you get an error message/stack trace on VSCode's Output panel when running into this ? If so, could you share it here so we can try and figure out the code that's failing.

**Comment by rahulmalhotra** [comment]
Same is the case with me:- 

![image](https://user-images.githubusercontent.com/16497903/73603009-3c303700-45a3-11ea-8273-b09c48c61425.png)

This is also coming when I am trying to turn on apex replay debugger from vscode:-

![image](https://user-images.githubusercontent.com/16497903/73603023-67b32180-45a3-11ea-9b94-5b01d038d227.png)

@lcampos can you tell a quick fix for the same, I know that I need to update the username with space to a shortened username. For ex:- "Rahul Malhotra" to "RahulM~1" and it will work fine but don't know where to update the same.

**Comment by lcampos** [comment]
@rahulmalhotra could you share your setup to see if I can replicate this on my side ? Salesforce extensions version and CLI version should be enough.

I agree this should work regardless of the path having spaces or not but we haven't been able to replicate this issue on our side on a computer that does have a username with spaces on it.

As a quick workaround, you can try creating/moving your project to a filepath that doesn't have the space on it.

**Comment by rahulmalhotra** [comment]
Hi @lcampos ,

Thanks for the quick fix, I am using :-

1. Salesforce Extension Pack v47.17.1
2. sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3
3. VSCode Version:- 1.41.1 (user setup)

Let me know if you need any other info 👍

**Comment by gbockus-sf** [comment]
@rahulmalhotra could you verify this is still an issue for you on the latest version?  Thanks!
