### ISSUE TITLE
100% cpu usage after enabling Salesforce Extension Pack

### ISSUE THREAD

**Issue by jameskbw** [forcedotcom/salesforcedx-vscode#1875]
### Summary

I recently decided to setup the salesforce extension for vscode by following this trailhead - https://trailhead.salesforce.com/content/learn/projects/quickstart-vscode-salesforce/use-vscode-for-salesforce

After authenticating to my playground, I tried to create the class using SFDX: Create Apex Class.  It didn't work, so I tried the command a few more times.  Eventually, I got the prompt asking where to store the class.  I'm not sure if I issues too many commands, but now my CPU usage is @ 100%.  When I disable the Salesforce Extension Pack the cpu usage goes down to normal levels.  I don't see any obvious errors, but I'm new to VSCode so not sure where to look or how to kill any potential stuck processes that may be causing this issue.  

### Steps To Reproduce:

1.  Open VS Code w/ Salesforce Extension Pack running.

### Expected result

CPU Usage to be at reasonable level when not doing anything.

### Actual result

CPU immediately goes to 100% usage.

### Additional information

_Feel free to attach a screenshot_.
<img width="703" alt="process explorer vscode" src="https://user-images.githubusercontent.com/59923636/72442516-ac088a00-377a-11ea-9af1-330dd522e60e.png">

**VS Code Version**: 1.41.1

**SFDX CLI Version**: 47.10.0

**Windows 10 x64 1903 **:

**Comment by jameskbw** [comment]
Immediately after posting this, I noticed my google drive file stream had not stopped syncing since  yesterday.  I then noticed it was stuck syncing the apex.db file in tools folder.  

I killed file stream, made the main folder available offline, and restarted vscode.  All seems well now.  I'm going to go through some commands again and see if the issue pops up.

**Comment by jameskbw** [comment]
The issue continues to happen if the project and Apex.db is stored within Google drive file stream.  Is this expected behavior?  I.E. should this work fine?  I'd ideally like to be able to store projects in my google drive to easily access w/ different computers.

**Comment by lcampos** [comment]
@jameskbw we recommend storing projects in version control systems like github, gitlab, bitbucket, etc. This is because the extensions generate some files that need to be ignored since they are exclusively used to make the tool work around your code. One of this is apex.db, this provides the information required for features like code completion, code navigation, etc to work but you shouldn't have to back it up since it changes as you modify your code.
I'm not sure if Google Drive supports a way of ignoring files/folders.

**Comment by jameskbw** [comment]
It doesn't appear google drive file stream has an option to exclude files / extensions.  I will try and setup a version control system.

**Comment by ntotten** [comment]
Let us know if you are still seeing the issue outside of google and if so please reopen or file a new issue.
