### ISSUE TITLE
Apex unresponsive Performance Issue

### ISSUE THREAD

**Issue by Vandanalight** [forcedotcom/salesforcedx-vscode#1887]
When I am deploying HelloWorldProject Deploy Source to Org failed to run.
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4082400/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
Thanks for opening this issue @Vandanalight . Can you add more details so we can replicate this on our side and work on a fix if needed ?
Please add the following:
VSCode version
Salesforce extensions version
Salesforce CLI version
Steps you took e.g. Authenticate to an org, create an apex class, etc
