### ISSUE TITLE
Apex Language Server throws "Connection to server is erroring. Shutting down server"

### ISSUE THREAD

**Issue by DJudin** [forcedotcom/salesforcedx-vscode#1891]
### Summary

Hi,
Having problems with using Apex Intellisense. 
Salesforce Extension Pack is installed.
_Salesforcedx-vscode-apex › Java: Home - C:\Program Files\Java\jdk1.8.0_241_

- Other language servers are successfully working (Aura and LWC language servers)
- File **apex.db** couldn't be deleted, because is not created

What also can be a reason for this issue?
Thank you in advance!

### Expected result

Successful connection to Apex Language Server
Apex Auto-fill working 

### Actual result
Apex Language Server displays following under Output:
![image](https://user-images.githubusercontent.com/60175927/72882740-ca86fc00-3d0b-11ea-9f56-cfca17750bfc.png)
Can't use Apex intelisense.

### Additional information

Terminal says, that Java is visible:
![image](https://user-images.githubusercontent.com/60175927/72891665-64a37000-3d1d-11ea-9c88-1f7bcdf76df9.png)

**VS Code Version**:
1.41.1
**SFDX CLI Version**:
sfdx-cli 7.41.0
**OS and version**:
Windows 10

**Comment by lcampos** [comment]
Thanks for logging this @DJudin, I've seen this happen when the language server process is not assigned enough memory by the Java JVM. By default, Java would assign up to one quarter of the machine's physical memory (RAM). You could use the `salesforcedx-vscode-apex.java.memory` setting to assign more memory to the process and see if that's what's causing this issue. Here is the doc on how that setting works https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/#advanced-setup

**Comment by DJudin** [comment]
Thank you for suggestion @lcampos , but unfortunately this doesn't help. I tried different values for salesforcedx-vscode-apex.java.memory - 3072,4096,5120 (both, User and Workspace settings), but Output still is the same: "Connection to server is erroring. Shutting down server". However, at some point I had seen success, and server was working until I restarted VS Code.
Does it exist command to relaunch Apex Language Server from console, not by restarting VS Code? I would try to manually connect to server if it is possible. If you have any other suggestion, I am ready to try.
Thank you in advance!

**Comment by lcampos** [comment]
Hi @DJudin could you share the stack trace of when you experience this error ? I haven't been able to replicate this issue yet on my side.

**Comment by DJudin** [comment]
Hi @lcampos,
After multiple restarts, reinstalls turning on/off extensions it finally works, but I can't say what was the actual reason.

**Comment by lcampos** [comment]
@DJudin glad it's working for you now. I'll double check is there's something we can do to make the setup experience smoother. If you run into this issue again please let us know and we'll take a second look.

**Comment by DJudin** [comment]
Hi @lcampos, there was update for Salesforce Extension Pack and issue appeared again.

**Comment by lcampos** [comment]
@DJudin did the error happen right after updating to the new version of the extensions while VSCode was still running ? Or did this happen after updating to the new version of the extensions and restarting VSCode ? I want to know if this is related to VSCode not asking the user to restart after installing updates.

**Comment by DJudin** [comment]
This happened after it was prompted to restart VScode.

ср, 19 февр. 2020 г., 18:37 lcampos <notifications@github.com>:

**Comment by ilopez96** [comment]
I am also experiencing the issue.  I have tried reinstalling the extension pack and CLI multiple times to try and correct the issue.  I have also restarted my machine multiple times with no luck.  Has there been a solution to this yet?

**Comment by seanfisher** [comment]
This happened to me when my project folder had a space at the end of it. I used the VS Code "Create a Project" function to create a new project using the default template. The folder name was `FolderName ` with a space at the end. This crashed all of the Salesforce plugins when I opened the folder in VS code and was a pain to track down. What let me onto the secret was viewing the Developer Tools console (go to Help -> Toggle Developer Tools), which had some error messages that clued me in. So my two recommendations are:
1. Check your project's file path
2. Use the developer console to help debug

**Comment by ritukalsy** [comment]
@seanfisher Thank you so much. It works :D I had a similar issue and was trying to figure it out from past 10 hours by trying almost everything.

**Comment by DJudin** [comment]
@seanfisher This is not my case, I have checked paths - there are no empty spaces at the end in any of project folders. For me it can to don't work for some time, then suddenly after N relaunches it may connect Apex Language Server. 
I also was trying to check Developer Tools, here is what I usually get:
![image](https://user-images.githubusercontent.com/60175927/84241480-34ac0c00-ab08-11ea-8d6e-38d44f8cce16.png)
Looks like issue is related either to connection timeout or RAM resource

**Comment by KarolPiekarczykWaeg** [comment]
@DJudin did you manage to fix it?

**Comment by DJudin** [comment]
@KarolPiekarczykWaeg It mostly works now, but I didn't do anything except extension updates - the same machine, same RAM, etc.

**Comment by randi274** [comment]
@DJudin are you still facing this error regularly? We did make some performance updates last year, and hopefully this has resolved itself.

**Comment by DJudin** [comment]
No, didn't notice this error approximately since last summer. I regularly
did all vscode and extension updates,  installed Windows 11 as well.

пт, 1 апр. 2022 г., 19:41 Randi Wilson ***@***.***>:

**Comment by randi274** [comment]
Thanks for the quick update @DJudin! In that event, I'll go ahead and close this issue; if you face the same problem again feel free to pick up the conversation here, or with a new ticket + fresh steps to reproduce.
