### ISSUE TITLE
Source Deploy LWC JavaScript failing

### ISSUE THREAD

**Issue by SalesforceBobLightning** [forcedotcom/salesforcedx-vscode#1892]
### Summary

When I right click on an LWC javascript file and use the `SFDX: Deploy this Source to Org` is always fails.

But if I right click on the same LWC component, but on the html file is always works.

**Version info**:

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**SFDX CLI Version**:

sfdx-cli/7.41.0-2a5f766389 win32-x64 node-v10.15.3

**Comment by smaddox-sf** [comment]
Hi @SalesforceBobLightning - Can you provide a couple things to help us look into this?

- the code that you're trying to deploy 
- The terminal Output for the execution of the failures
