### ISSUE TITLE
Hey All,   I have also downloaded VSCode and when installing  Salesforce Extension Pack , it is giving me error like couldn't start Client Aura Language Server.  

### ISSUE THREAD

**Issue by Shrutika142** [forcedotcom/salesforcedx-vscode#1893]
below are the details -
VsCode version - x64 - 1.41.1
Salesforce CLI setup - https://developer.salesforce.com/tools/sfdxcli
![VScode issue](https://user-images.githubusercontent.com/60179467/72894327-0d16fb80-3d41-11ea-8f82-d3715aadce3e.png)
![VScode issue](https://user-images.githubusercontent.com/60179467/72894336-130cdc80-3d41-11ea-8624-5c9d52b10f24.png)

**Comment by lcampos** [comment]
Hi @Shrutika142 this looks like the extensions were not able to activate. If you open VSCode's Dev tools (Help > Toggle Developer Tools) and select the `Console` tab on it do you see any errors ? Could you add them here so we can try and figure out what's causing the extension to fail ?

**Comment by Shrutika142** [comment]
Hi Team,

I have attached screenshot of the console tab.Request you to please find
the same.


Thank You,
Shrutika Shinde
Software Engineer | Salesforce
+91-9067934384

**Comment by Shrutika142** [comment]
Hey  Team,

My problem is resolved now !!

**Comment by lcampos** [comment]
@Shrutika142 glad you're unblocked, can you let us know what was the configuration change you had to do ?

**Comment by Shrutika142** [comment]
Hi,

I have refer the attached screenshot.ran the disable extension cmd. And then reinstalled vs code.however It working good without any error.

**Comment by lcampos** [comment]
Closing since this was a setup/install issue.
