### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dkadam77** [forcedotcom/salesforcedx-vscode#1897]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `47.15.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
HI @dkadam77 - Please add the info that was written to your clipboard so we know what the issue was. We will reopen this issue if we get more info to investigate.
