### ISSUE TITLE
SFDX: Preview Component Locally failed error

### ISSUE THREAD

**Issue by dkadam77** [forcedotcom/salesforcedx-vscode#1903]
### Summary

When a Lightning Web Component is previewed by using a context menu - SFDX: Preview Component Locally  then it throws an error
### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

It should preview the Lightning web component using local development server

### Actual result

It is throwing an error - SFDX: Preview Component Locally failed to run. Can't find the Lightning Web Components module in. Check that the module exists.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Latest
**SFDX CLI Version**:
Latest
**OS and version**:

**Comment by rlancejohnson** [comment]
I am having this issue as well. Has there been a solution identified yet?

**Comment by mysticflute** [comment]
@dkadam77 what does your project structure look like? Are the components under `force-app/main/default/lwc`?

Also do you see this in the context menu for the component directory, or a specific file in the directory? If a specific file, please share the file type.

**Comment by dkadam77** [comment]
Hello,

Yes I am having the LWC component in the same path as you mentioned. I am
getting this context menu when right click on JS or HTML file and that
option of preview does not work anywhere.

See the screenshot below

[image: image.png]

**Comment by dkadam77** [comment]
![image](https://user-images.githubusercontent.com/8331780/80856144-ec761000-8c64-11ea-8a08-46c5149a177f.png)

**Comment by dkadam77** [comment]
is there any update??

**Comment by dkadam77** [comment]
I have tested this on Mac and it works perfectly. I assume this is the issue only with Windows and due to the absolute path being detected when u click on Preview component locally button.

**Comment by handlerda** [comment]
I am having issues with my windows machine as well. 
![sfdclwc-error](https://user-images.githubusercontent.com/48835180/80980955-4575ad80-8df7-11ea-86b7-fe5f5ce3f318.PNG)

**Comment by jonuday** [comment]
I was able to fix this error by reviewing and updating the jsconfig.json file paths in the lwc folder. 

I had updated a component name, refactored the class and file names, but not the path specified in the jsconfig.json file. 

I believe this error could have other causes, like if two components instantiate the same class or if you have the same file names in different folders.

**Comment by dkadam77** [comment]
can you please provide the configuration that u made in jsconfig.json???

**Comment by handlerda** [comment]
Hi @dkadam77 please see below:

```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "baseUrl": ".",
        "paths": {
            "c/forms": [
                "forms/forms.js"
            ]
        }
    },
    "include": [
        "**/*",
        "../../../../.sfdx/typings/lwc/**/*.d.ts"
    ],
    "typeAcquisition": {
        "include": [
            "jest"
        ]
    }
}

```

**Comment by dkadam77** [comment]
and what changes u have done on Windows (folder structure) to match this???
Appreciate ur response; Kindly briefly describe.

**Comment by vanglirajan** [comment]
sfdx force:lightning:lwc:start

**Comment by handlerda** [comment]
Hi, I have not changed anything. This was what was created when I created the lwc.
