### ISSUE TITLE
SFDX: Source push option don't appear as right click

### ISSUE THREAD

**Issue by oriolete** [forcedotcom/salesforcedx-vscode#1909]
### Summary

While I'm working in Scratchorg right click menu with "SFDX: Source push to srcatch org ..." doesn't appear but I can with command palette option.

### Steps To Reproduce:

1.  Creat project
2.  Authorize a devhub org
3. Create a scratch org
4. Create a lwc
5. Right click option over lwc not show "SFDX: Source push to scratch org"

### Expected result

Right click option to push source

### Actual result

Not showing option on right click menu

### Additional information

![image](https://user-images.githubusercontent.com/6986296/73114348-f5df3600-3f19-11ea-9203-17fd2b0709d7.png)

**VS Code Version**:
1.41.1

**SFDX CLI Version**:
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-diff 0.0.5
@salesforce/sfdx-trust 3.0.7 (core)
Workshop 0.0.0 (link) /Users/ofarras/Desktop/Workshop
analytics 1.4.1 (core)
export-plugin 0.0.1 (link) /Users/ofarras/Documents/Repositories/GitHub/export-plugin
generator 1.1.2 (core)
salesforcedx 47.16.0 (core)
├─ salesforcedx-templates 47.17.0 (core)
└─ salesforce-alm 47.15.0 (core)

sfdx-cli 7.43.1 (core)

**OS and version**:
Darwin x64 19.2.0

**Comment by smaddox-sf** [comment]
Hi @oriolete - We don't show the commands on the right-click menu because Push & Pull commands always push/pull ALL tracked changes.  You don't have the option to push/pull individual files or directories when working with an Org that has source tracking

**Comment by Utkarsh-Singh-360** [comment]
Create a user in scratch org and project with manifest in VS code.
Authorise the new user and do not initiliaze the git in this project.
You will now see the option on right click for deploy the particular source.
@oriolete
