### ISSUE TITLE
Authorize an Org command is not working in VS Code

### ISSUE THREAD

**Issue by dev-mks** [forcedotcom/salesforcedx-vscode#1911]
I have installed latest version of VS Code and Salesforce Extension Pack version is 47.16.0.

![](https://i.stack.imgur.com/SxYFe.png)

I was able to authorize an org first time. Then I tried to authorize another org but browser is not opening to authorize the org. After running the command, vs code is showing only showing the running notification.
![](https://i.stack.imgur.com/u0Il2.png)

I have checked the Problems and Debug Console tab but there is no error.

**Comment by lcampos** [comment]
Hi @dev-mks thanks for opening this issue. This seems to be the same as #1888 , can you confirm if you have Chrome configured as your default browser in the OS.

**Comment by dev-mks** [comment]
@lcampos thanks for the response!

Yes, my default browser is Chrome in the OS.

**Comment by lcampos** [comment]
Thanks for confirming @dev-mks, I'll close this issue and will continue to follow up on this in #1888
