### ISSUE TITLE
Unresponsive Performance Issue

### ISSUE THREAD

**Issue by kartheek7217** [forcedotcom/salesforcedx-vscode#1912]
Firing below errors every-time, When I open VS
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4118781/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4118785/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by smaddox-sf** [comment]
Hi @kartheek7217 - Are these errors happening right when you open VS Code?  or were you performing an action within VS Code?

Can you add the following info:
**VS Code Version:
SFDX CLI Version:
OS and version:**
