### ISSUE TITLE
Profile is not visible in Org Browser

### ISSUE THREAD

**Issue by lokeshguptag** [forcedotcom/salesforcedx-vscode#1914]
Details:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

<img width="461" alt="Screen Shot 2020-01-28 at 3 12 19 PM" src="https://user-images.githubusercontent.com/22685477/73252386-aed69680-41e0-11ea-9f1c-b28dcbf86f1c.png">

**Comment by lcampos** [comment]
Hi @lokeshguptag thanks for logging this. We decided not to support Profiles in the Org Browser since retrieving them with the correct content requires retrieving everything they might reference at once (Apex, Objects, Layouts, etc).

cc @smaddox-sf @ntotten

**Comment by abhishekmadhu** [comment]
Hey, this doesn't seem like a good response to situations like this. 
Can you please at least provide an alternative to retrieve all profiles from org to branch that is recommended?

**Comment by carlosglc** [comment]
Apparently they cannot.
