### ISSUE TITLE
Known Issue - Activating extension 'salesforce.salesforcedx-vscode-core' failed: Cannot find module '/Users/.../.vscode/extensions/salesforce.salesforcedx-vscode-core-47.17.0/out/src'

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/salesforcedx-vscode#1919]
### Summary
Receiving the following error after downloading the latest version of the Salesforce extensions (47.17.0).
`Activating extension 'salesforce.salesforcedx-vscode-core' failed: Cannot find module '/Users/.../.vscode/extensions/salesforce.salesforcedx-vscode-core-47.17.0/out/src'`

**Comment by sfsholden** [comment]
**Workaround**:
Delete the current .vsix files and redownload the extensions.

**Comment by sfsholden** [comment]
See below gif for instructions on how to uninstall the vsix files:
![uninstall](https://user-images.githubusercontent.com/45604118/73480284-d6e80600-4356-11ea-8934-0b06b8f2c6af.gif)

**Steps**:
1. Click Extensions on the toolbar.
2. Search for 'Salesforce'
3. Click 'Uninstall'
4. Click 'Install'
5. After the installation is complete, run 'Reload Window' from the Command Palette.

**Comment by lcampos** [comment]
I'm closing this since this got fixed on release `v47.17.1`
