### ISSUE TITLE
NaN instead of Pass Rate and Fail Rate when running tests.

### ISSUE THREAD

**Issue by saibimajdi** [forcedotcom/salesforcedx-vscode#1930]
### Summary

I'm not sure if this is a VSCode extension issue or SF CLI one.

### Additional information

![image](https://user-images.githubusercontent.com/8198978/73894121-b5948780-4838-11ea-8a55-d38864a4d77e.png)

**VS Code Version**: 1.41.1

**SFDX CLI Version**:  sfdx-cli/7.43.1-ef237e8b37

**OS and version**: Windows 10.

**Comment by lcampos** [comment]
Hi @saibimajdi, thanks for logging this. This issue is originated on the CLI, we're aware of it and working on some enhancements to the apex commands that will address this among other issues. I'll make sure to update this issue once the fix is out.

**Comment by klewis-sfdc** [comment]
Hi @saibimajdi, a number of improvements have been made to the VS Code Extensions and the CLI since this issue was opened.  If you are still seeing this issue, please let us know here.  Thank you.
