### ISSUE TITLE
Terrible memory and CPU usage with VS Code Extensions Enabled

### ISSUE THREAD

**Issue by lucianostraga** [forcedotcom/salesforcedx-vscode#1932]
It is insane how much resources this extension takes. Tested on many laptops, kills your battery in a couple of hours. This has to be fixed ASAP. I cannot work unplugged. 
This the exact example of how an extension adoption could be ruined by a bug like this. 

ONE SINGLE DX PROJECT OPENED!

![image](https://user-images.githubusercontent.com/2922784/73952027-41f88600-48dd-11ea-9624-4ccc6dcec1c6.png)

The Apex Language server takes more than 1GB. That it is insane!!! Please fix this. I have the latest version of everything.

**Comment by ntotten** [comment]
This is in line with what the Java language server uses when running a decent sized Java project (see screenshot) so I'm not going to consider it a bug necessarily. Additionally, you can use the setting `salesforcedx-vscode-apex.java.memory` to decrease the amount of memory the Apex LSP uses if you so desire. It may impact performance though. 

Please open a new bug with details on the project you are running as well as reproduction steps. Additionally, before opening future bugs, please review our [code of conduct](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/CODE_OF_CONDUCT.md).

![image](https://user-images.githubusercontent.com/282782/73955030-b547cb00-48d0-11ea-8c82-918de2cb3f5c.png)
