### ISSUE TITLE
Org Metadata Search

### ISSUE THREAD

**Issue by jmdohn** [forcedotcom/salesforcedx-vscode#1937]
**Is your feature request related to a problem? Please describe.**
When using the Org Metadata search in large orgs, it is difficult to find components and I have to scroll for days to find the appropriate metadata component.

**Describe the solution you'd like**
Search in Org Metadata explorer for affected metadata components.

**Describe alternatives you've considered**
I go to the org directly and use sfdx force:source:retrieve -m [metadataType]:[Component] or scroll in the explorer.

**Comment by brpowell** [comment]
Hi @jmdohn. VS Code has a built in feature for tree views where if you focus the view and start typing, it allows you to navigate between the nodes that match what you've typed using the arrow keys. Is something like this what you're talking about?

**Comment by jmdohn** [comment]
Ah yes! I just tried that and I was able to search just fine!  Thank you!
