### ISSUE TITLE
SFDX notification keeps running even when the process has completed.

### ISSUE THREAD

**Issue by hsoni** [forcedotcom/salesforcedx-vscode#1972]
<img width="570" alt="Capture" src="https://user-images.githubusercontent.com/1703025/74261998-154fce80-4d22-11ea-8a44-43013f9efdff.PNG">

SFDX notification keeps running even when the operation is complete .For example :
SFDX:authorize an org ran successfully but the notification keeps running due to which we dont know whether the process has ran

**Comment by lcampos** [comment]
Thanks for opening this @hsoni , can you let us know which version of the Salesforce CLI & Salesforce extensions for VSCode you're running ?

**Comment by Sarveshgithub** [comment]
Yeah same for me
