### ISSUE TITLE
VF - Inline javascript and CSS commenting uses <!-- --> erroneously 

### ISSUE THREAD

**Issue by gbutt** [forcedotcom/salesforcedx-vscode#198]
### Summary
_When editing a visualforce page, when I comment out a line of javascript, I expect the language service to use the // for javascript, however it is using \_.

### Steps To Reproduce:
1. Open a VF page
1. Add a script tag
1. Add some javascript
1. Use keyboard shortcut to comment out a line of javascript

### Expected result
_Javascript comments should use //_.

### Actual result
_Javascript is commented out with \_.

### Additional information

_Feel free to attach a screenshot_.

**Extension version**: 41.5.0

**VS Code Version**: 1.17.2

**SFDX CLI Version**: 6.0.9-3391781

**OS and version**: OSX 10.12.6

**Comment by vazexqi** [comment]
This is related to https://github.com/Microsoft/vscode/issues/11081 (which is fixed) I must have configured this wrongly when I converted the visualforce grammar.
