### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by himanshu371** [forcedotcom/salesforcedx-vscode#1982]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `47.17.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 18347,
		"activateCallTime": 8,
		"activateResolvedTime": 7743,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
Hi @himanshu371 - Can you add context on what you were trying to do and what happened?  From the info here, I'm not sure what the issue is
