### ISSUE TITLE
Cannot find module '@salesforce/salesforcedx-utils-vscode/out/src/i18n'

### ISSUE THREAD

**Issue by Deepak-K-Anand** [forcedotcom/salesforcedx-vscode#2004]
### Summary
After updating the VS Code to the latest release along with SFDX CLI update, the VS Code SFDX Extension no longer works due to a missing **i18n** module. (_Error Screenshot Attached_)

### Steps To Reproduce:

1.  Update **VS Code** to the latest release
2.  Update **SFDX CLI** to the latest release

_Note_: I have even tried uninstalling and re-installing the entire dev. stack (CLI, VS Code etc) with no luck.

### Expected result

Ability to develop against SF Orgs using SFDX / VS Code Extension.

### Actual result

The `salesforce.salesforcedx-vscode-core` failed to load hence prevented all the associated extensions/modules from being loaded.

### Additional information

![image](https://user-images.githubusercontent.com/3683725/74828176-ac291600-5334-11ea-88fd-d540ea6ca3a2.png)

**VS Code Version**: 
_Version_: `1.42.1 (user setup)`
_Node.js_: `12.4.0`

**SFDX CLI Version**:
`sfdx-cli/7.46.3-4cf515d568 win32-x64 node-v10.15.3`

**OS and version**:
`Windows_NT x64 10.0.18362`

**Comment by lcosta-II2S** [comment]
**(WORKAROUND)This worked for me after experiencing the same issue:**

1. Uninstall *Salesforce Extension Pack* from VS code extensions
2. Delete all salesforce related folders under the vs code extensions folder, you can find them in:
  > Windows %USERPROFILE%\.vscode\extensions
  > macOS ~/.vscode/extensions
  > Linux ~/.vscode/extensions
3. Install *Salesforce Extension Pack* back again
