### ISSUE TITLE
Missing/misconfigured label for Apex Interactive Debugger when user doesn't have right perm set

### ISSUE THREAD

**Issue by vazexqi** [forcedotcom/salesforcedx-vscode#2005]
### Summary

Missing/misconfigured label for Apex Interactive Debugger when user doesn't have right perm set

### Steps To Reproduce:

1.  Try to connect to an org that has the Interactive Apex Debugger enabled.
1.  But, do not assign or create a perm set to assign to the (per https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger/#set-up-apex-debugger)

### Expected result

A clear error telling me that the org/user doesn't have the right permissions.

### Actual result

![Screen Shot 2020-02-19 at 7 53 41 AM](https://user-images.githubusercontent.com/54414/74850797-3e0e3000-52ef-11ea-8dda-846188ede497.png)

### Other details

This seems similar to this comment: https://github.com/forcedotcom/salesforcedx-vscode/issues/722#issuecomment-438769699

**Comment by smaddox-sf** [comment]
Thanks for the feedback @vazexqi .  I agree it would be helpful to inform you of missing setup steps.  We'll consider this in the future as we work in this area.

**Comment by jerhewet** [comment]
The steps outlined at  https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger/#set-up-apex-debugger seem to be incorrect, as there is no "Debug Apex" checkbox (Step 9) available for me to select.  I'm logged in with a System Administrator account on a sandbox created from an Enterprise Salesforce Edition.

**Comment by lcampos** [comment]
@jerhewet the `Debug Apex` permission is only available when an additional license is provisioned to your org. If you don't see it you'll have to contact your Account Executive.

**Comment by lcampos** [comment]
Closing this since the fix was released as part of version 48.18.0. Thanks for providing feedback.
