### ISSUE TITLE
With the ISV Customer Debugger, at step 9, I receive an error: 'Cannot set property 'SFDX_TOOL' of undefined'

### ISSUE THREAD

**Issue by Vishalashah** [forcedotcom/salesforcedx-vscode#2013]
### Summary

_With the ISV Customer Debugger, at step 9, I receive an error: 'Cannot set property 'SFDX_TOOL' of undefined'_.

### Steps To Reproduce:

Follow the steps for ISV Customer Debugger: https://developer.salesforce.com/tools/vscode/en/apex/isv-debugger/

### Expected result

Able to launch the Apex Debugger in VS Code

### Actual result

Cannot set property 'SFDX_TOOL' of undefined

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.42.1

**SFDX CLI Version**: 48.1.0

**Apex Interactive Debugger Version**: 48.1.0

**OS and version**: macOS Catalina 10.15.4

**Comment by sfsholden** [comment]
Thank you for reaching out @Vishalashah 

Please try downgrading the Salesforce CLI to version 7.43.1 or below. Please let us know if that unblocks you.

Resource for Installing an Earlier Version of the CLI (using npm):
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm

**Comment by lcampos** [comment]
Hi @Vishalashah , the fix for this issue was released as part of version `48.3.0` of the extensions. Thanks for opening this issue and please keep logging your feedback in the future.
