### ISSUE TITLE
Unsupported Java Version Error when using Java 8

### ISSUE THREAD

**Issue by ChristianCoelho** [forcedotcom/salesforcedx-vscode#2030]
### Summary

Vscode/SF Extension is not finding my Java 8 even though path has been added.

### Steps To Reproduce:

1.  Cannot Run Tests Because Unsupported Version of Java is not installed
<img width="1205" alt="Screen Shot 2020-02-23 at 6 18 40 PM" src="https://user-images.githubusercontent.com/24259798/75125364-a94a6000-5669-11ea-8ad7-2829169896d4.png">
2. Path in vscode is set to my Java 8 Home Folder as seen below.
<img width="1101" alt="Screen Shot 2020-02-23 at 6 38 42 PM" src="https://user-images.githubusercontent.com/24259798/75125792-c718c480-566b-11ea-9717-cffe66c29a8c.png">

3. My computer matches the same path when in the folder
<img width="263" alt="Screen Shot 2020-02-23 at 6 22 59 PM" src="https://user-images.githubusercontent.com/24259798/75125393-c848f200-5669-11ea-911f-4c910bab3bf4.png">

### Expected result
For my Java 8 to be recognized and to be able to successfully run tests in VScode.

### Actual result

Receive error that I am using an unsupported version of Java and cannot run tests.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.42.1
**SFDX CLI Version**:
7.47
<img width="363" alt="Screen Shot 2020-02-23 at 6 31 36 PM" src="https://user-images.githubusercontent.com/24259798/75125612-c2074580-566a-11ea-988b-1b2777a19723.png">

**OS and version**:
MacOS Catalina Version 10.15.3

**Comment by vazexqi** [comment]
What happens if you include the "/Home" at the end as shown in https://github.com/forcedotcom/salesforcedx-vscode/blob/master/packages/salesforcedx-vscode-apex/package.nls.json#L10

" ... (for example, /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home)."

**Comment by ChristianCoelho** [comment]
Sorry I took a bad screen shot in the original post. Home is included and still causes that error to pop up.

**Comment by lcampos** [comment]
@ChristianCoelho that configuration looks good so I'm thinking there might be some other configuration issue. Can you tell me what's the output of running `/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/java -version` in your terminal ?

Also, do you see any error with the extensions activating when you go to VSCode > Help > Toggle Developer Tools and then focus on the Console tab ?

**Comment by ChristianCoelho** [comment]
Once I restarted my computer it then detected my java version.
