### ISSUE TITLE
Ability to specify a starting URL or path after clicking the open org button in VS code status bar

### ISSUE THREAD

**Issue by tylerclark** [forcedotcom/salesforcedx-vscode#2044]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open my org and I'm set to the setup menu which I never need to see. 

**Describe the solution you'd like**
Being able to specify a different route would be great so I can get right to work.

**Describe alternatives you've considered**
No alts

**Additional context**
You da man

**Comment by smaddox-sf** [comment]
Hi @tylerclark - Thanks for this suggestion.  I have a few follow-up questions to better understand your idea:  

Are you envisioning that you set a default path within the Org that it always opens to?  Or that the Org opens to where you were last working?  

What are the most common places you go to while working in the Org?
