### ISSUE TITLE
Warning While Calling Private @TestVisible Method from Apex Unit Test

### ISSUE THREAD

**Issue by NathanWenslaff** [forcedotcom/salesforcedx-vscode#2046]
# Summary
Calling a private method annotated with the TestVisible annotation from an Apex unit test gives a warning in VS Code:

"Method is not visible"

Note that this does not cause any compilation errors (the code deploys successfully), but it does give warnings in VS Code

### Steps To Reproduce:

`ApexClassWithPrivateTestVisibleMethod`

```
public with sharing class ApexClassWithPrivateTestVisibleMethod {
    @TestVisible
    private static void doWork() {
        // do work
    }
}
```

`ApexTestClass`

```
@isTest
public with sharing class ApexTestClass {
    @isTest
    static void callTestVisibleMethod() {
        ApexClassWithPrivateTestVisibleMethod.doWork();
    }
}
```

Note that the warning shows up on the `doWork()` call:

![image](https://user-images.githubusercontent.com/35071304/75691173-90453e80-5c69-11ea-8488-4763f65fef35.png)

### Expected result

There should not be a warning calling a private method annotated with TestVisible form an Apex unit test.

### Actual result

There is a warning.

**VS Code Version**:
1.42.1

**SFDX CLI Version**:
sfdx-cli/7.48.0-a71f8c6899 darwin-x64 node-v10.15.3

**OS and version**:
MacOS 10.15.3 (19D76)

**Comment by smaddox-sf** [comment]
Hi @NathanWenslaff - Thanks for raising this.  We already have an issue logged for this (#1835 ), so closing this one as a duplicate
