### ISSUE TITLE
Dashboards within folders are not retrieved from Dashboard node in Org Browser

### ISSUE THREAD

**Issue by aldoforce** [forcedotcom/salesforcedx-vscode#2047]
### Summary

_Short summary of what is going on or to provide context_.
I do have an org with different dashboards organized thru folders: Executive, Sales, Deployment, Adoption, etc. If I want to retrieve all of them using Org Browser's cloud-icon, I have to do it one by one (dashboard by dashboard) when ideally, I just want to click the cloud-icon at dashboard node level and retrieve all folders and dashboards.

I think the problem is related to an underlying cause with Org Browser when click over the dashboard node and it executes:

`sfdx force:source:retrieve -m Dashboard`

it returns:

`=== Retrieved Source
No results found`

However, if I open the folder nodes and click on the cloud icon on single items it retrieves correctly:

`sfdx force:source:retrieve -m Dashboard:EjecutivoNivel2/cIVVkXSlzqSBCKNXcUMXlSDkoqeBdW21`

returns: 

`DashboardSalesforce/FdYlfQCcdVGBpMrJSMhZROdVyvFMbd  Dashboard  force-app/main/default/dashboards/DashboardSalesforce/FdYlfQCcdVGBpMrJSMhZROdVyvFMbd.dashboard-meta.xml`

### Steps To Reproduce:

1. Using a DE org (or non scratch), create a Dashboard Folder: "sales"
1. Create different dashboards within the "sales" folder.
1. Connect VSCode to the org from first step
1. Open Org Browser and click on cloud icon at "Dashboards" node
1. No dashboard or folder is retrieved

### Expected result

_Describe what should have happened_.
The Org Browser should download the folder "sales" and all its dashboards to my local file system.

### Actual result

No files are retrieved to local file system. A "No results found" message is displayed

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.42.1 c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z

**SFDX CLI Version**: 7.48.0-a71f8c6899 

**OS and version**:
OSX Catalina 10.15.3

**Comment by aldoforce** [comment]
To add more information, the problem seems to be related to folders and folders within folders.
If you want to retrieve dashboard components from folders that are included within folders ie: Sales > West > sales_dashboard_west, the org browser only displays a single level hierarchy and not folders and sub-folders.

**Comment by aldoforce** [comment]
Similar issue can be reproduced with EmailTemplates.

**Comment by aldoforce** [comment]
Same behavior with Reports

**Comment by okeisu** [comment]
I'm having the same problem.

**Comment by marcopinder** [comment]
@smaddox-sf Is there an update on this issue please?

**Comment by RitamAgrawal** [comment]
@aldoforce @okeisu @marcopinder As of now for metadata types: Documents, Dashboards, Email templates and Records, we can retrieve the folders listed within each of them. We can see the components listed within the folders as well. We are working on making the components within folders retrievable.

**Comment by ScubaJimmE** [comment]
Still an issue for reports in folders. Only the report folders are retrieved, not the reports within. 
sfdx-cli/7.142.1 win32-x64 node-v16.14.0

**Comment by RitamAgrawal** [comment]
@ScubaJimmE Please verify if it has been fixed for you in the latest release. With our V54.6.0 components within folders are retrieved individually by clicking on 'retrieve source from org' icon. Here is the PR https://github.com/forcedotcom/salesforcedx-vscode/pull/3892
