### ISSUE TITLE
Cannot create project with manifest or authorize org

### ISSUE THREAD

**Issue by WhoStoleMyFries** [forcedotcom/salesforcedx-vscode#2048]
I cannot do anything at this point. 

Creating the Manifest creates a new folder, flashes an error that the process failed for a fraction of a second and then opens the new folder. I can't get any info from it. 

I copied over a project from another comp. Tried to retrieve from org, couldn't. Tried to authorize the org and got: " EPERM: operation not permitted, open 'c:\Users\Dan\Documents\sfdx Projects\For Work\Kulbersh\KHSS - Dev\.sfdx\sfdx-config.json' "

Using the latest version of VS Code, extensions and connected it to JDK 11.0.6 which I believe is the latest stable one from Java

Completely dead in the water at this point. Any quick fixes would be _greatly_ appreciated

**Comment by lcampos** [comment]
Hi @WhoStoleMyFries , that error (`EPERM`) is normally caused by the folder you are working with not giving your user permissions to access/modify it. Can you verify your user's access to the project, modify it if needed and try and run some of the commands again ?
