### ISSUE TITLE
Visual Studio Code 100%+ CPU Percentage

### ISSUE THREAD

**Issue by Bgallahue** [forcedotcom/salesforcedx-vscode#2050]
### Summary

Having issues with my computer sounding like a jet leaving the runway every 10/15 minutes while working in VSC (brand new Macbook Pro is the computer so this likely isnt the issue). I've identified what is causing it (with Activity Monitor) and it is Code Helper (Renderer) Process running at over 100% CPU for minutes at a time. I'm not doing anything i haven't done before, just coding some LWC. Diving a little deeper using "ps aux | grep XXX" in the terminal to return the specific extension causing the issue and i found it was:

lwc-language-server within the Salesforce DX extension. I have no idea how to disable this or whether it is possible but wondering if anyone else has had this issue, its driving me nuts

Full process name that is behind the 100% CPU

/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/USERNAME/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-48.1.0/node_modules/lwc-language-server/lib/server.js --node-ipc --clientProcessId=XXX

Note: XXX is the PID or Process Id # in case anyone else is having the issue

### Steps To Reproduce:

1.  Code a LWC

### Expected result

It should not use 105% CPU every 10 minutes for 2/3 minutes

### Actual result

Very high CPU usage, fan going full blast

### Additional information

Have completely installed Mac OS Catalina from scratch

**VS Code Version**:

Version: 1.42.1

**SFDX CLI Version**:

48.4.0

**OS and version**:

MacOS Catalina 10.15.3

**Comment by lcampos** [comment]
Closing this since a few weeks ago we released a new implementation of the LWC language server that addresses this issue. Thanks for the feedback.

**Comment by richardrmwd** [comment]
This issue is happening to me now

**Comment by zix66** [comment]
me too
