### ISSUE TITLE
Question - what happens when you 'cancel' an SFDX command?

### ISSUE THREAD

**Issue by lxmunro** [forcedotcom/salesforcedx-vscode#2051]
Hello,

I am wondering exactly what happens when you 'cancel' an SFDX command run in VSCode using the button in the UI, e.g.:

![Screen Shot 2020-03-04 at 2 42 31 PM](https://user-images.githubusercontent.com/55165142/75836940-4787b400-5e28-11ea-8eab-1287bae10306.png)

If it is DEPLOYING changes - will it revert any changes already made? Could it be possible that some of the changes may have already been applied to an Org?

Hoping someone can answer for me. Cheers

**Comment by smaddox-sf** [comment]
Hi @lxmunro - When you hit 'cancel', the command is aborted.  One caveat: If it is a deploy or retrieve and it's already been queued, it is not removed from the queue so it may still proceed.
