### ISSUE TITLE
Conflict Detection - false conflict detection on the latest updates

### ISSUE THREAD

**Issue by adnan8387** [forcedotcom/salesforcedx-vscode#2056]
### Summary

After retrieving an object from sandbox using a manifest files, any updates on the same are detected as a conflict when we try to deploy it although there wasn't any update done by anyone else on the same file on sandbox.

### Steps To Reproduce:

1.  Use a simple package.xml file with at least 1 class metadata file.
1.  Retrieve the metadata using 'Retrieve Source in Manifest from Org' command
1.  Update the retrieved class in local 
1.  Use 'Deploy Source in Manifest to Org'

### Expected result

A new update after initial retrieval or subsequent updates by same user where there hasn't been any change on the sandbox metadata should not be highlighted as a conflict.

### Actual result

We get a conflict message every time we try to deploy the file although there wasn't any update made by other users

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.42.1

**SFDX CLI Version**: 7.48.0

**OS and version**: Windows_NT x64 10.0.16299

**Comment by smaddox-sf** [comment]
Hi @adnan8387 - Currently it shows all files with differences.  If there are more files changed than you expected, you have a chance to investigate.  Otherwise, you can override and continue.

**Comment by smaddox-sf** [comment]
We released a new version of conflict detection.  Check it out and see the details in our doc - https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts
