### ISSUE TITLE
Apex Interactive Debugger Plugin - Empty Error Dialogs

### ISSUE THREAD

**Issue by rhobkirkffdc** [forcedotcom/salesforcedx-vscode#2058]
### Summary
When error / warning dialogs are displayed in VSC to the user, they are empty. This is a regression as these previously contained a message indicating the problem. 

I'm not certain if this applies to all dialogs or just the following ones:
- Dialog displayed to the user when no debug permission set is assigned and the user launches a new debug session
- Dialog displayed to the user when an existing debug session is active in the org

### Steps To Reproduce:
1. Create an org with debug apex feature enabled and push some debuggable code
1. Create a debug Permission Set, but don't assign it to your user
1. Create the standard `launch.json` debug config
1. Launch a debug session
1. NOTE - A dialog is displayed to the user, but it contains no message, just `Cancel` and `Open launch.json` buttons

1. Assign the debug permission set to your user in the org
1. Launch a debug session and watch the debug console
1. Stop the session when it gets to `Connected to Streaming API channel /systemTopic/ApexDebuggerEvent.` and before it has completed launching
1. Click to launch again
1. NOTE - A dialog is displayed to the user, but it contains no message, just `Cancel` and `Open launch.json` buttons
1. Login to the org and note that an existing session is running under the `Apex Debugger` tab. There are likely other ways to repro this scenario (terminating VSC while a session is running might do the same thing)

### Expected result
A dialog should be displayed containing a message indicating the problem

### Actual result
A dialog is displayed without any message

### Additional information

**VS Code Version**: 1.42.1

**SFDX CLI Version**: sfdx-cli/7.49.1 darwin-x64 node-v10.15.3

**OS and version**: macOS 10.15.3

**Comment by hemanshu-shah** [comment]
I am having same issue,

Apex Interactive Debugger Version : 48.11.0

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by lcampos** [comment]
Closing this since the fix was released as part of version 48.18.0. Thanks for providing feedback.
