### ISSUE TITLE
Load issue

### ISSUE THREAD

**Issue by Jayanth007** [forcedotcom/salesforcedx-vscode#2061]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @Jayanth007 - The issue doesn't have any info about what you were trying to do or what happened.  Can you please review and add details?
