### ISSUE TITLE
Class body hit character limit 10000

### ISSUE THREAD

**Issue by freddie1729** [forcedotcom/salesforcedx-vscode#2062]
### Summary

An error keeps popping up in the Output tab on VS Code whenever I type into a file. It happens very frequently. The error is in the Apex Language Server and says the character limit has been hit.

### Steps To Reproduce:

1.  Edit a line in a class
1.  See an error pop up in the Output tab: 

```
Mar 04, 2020 11:45:33 AM apex.jorje.semantic.compiler.CodeUnit traverse
INFO: unexpected error during apex MemberResolveVisitor:
Class body hit character limit 10000 global with sharing class
```

### Expected result

No error

### Actual result

Error

### Additional information

**SFDX CLI Version**: sfdx-cli/7.48.0-a71f8c6899 win32-x64 node-v10.15.3

**SFDX plugin Version**: sfdx-cli 7.48.0 (core)

**OS and version**: Windows 10

**Comment by lcampos** [comment]
Thanks for opening this issue @freddie1729 . Are you getting this issue when working on a big apex class or also with relatively small apex class in your project ?

**Comment by freddie1729** [comment]
It happens with small too.

I think it might be because I have duplicated the project to work with it on two monitors. I've stopped this now and no longer see the problem.
