### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by rajesh-k** [forcedotcom/salesforcedx-vscode#2065]
I see the "Cannot read property 'get' of undefined" in vscode output anytime a javascript or xml file is saved. Uninstalling the Salesforce CLI Integration extension gets rid of this error. I need the Salesforce CLI Integration package along with the extension pack. Let me know how I can get rid of this error.
The vscode console log is attached.

[1583945690803.log](https://github.com/forcedotcom/salesforcedx-vscode/files/4319588/1583945690803.log)

**Comment by lcampos** [comment]
Thanks for reporting this @rajesh-k . We've released a fix for this in version `48.6.0` of the extensions.

**Comment by lgomezgwt** [comment]
This error is happening again in version 49.5.0

**Comment by Lvkz** [comment]
This error is happening again in version 49.5.0

**Comment by lcampos** [comment]
Hi @Lvkz I've checked and even when you might be getting the same error message I couldn't find it being a regression on the original issue. Please open a new issue and add details on how to replicate the problem you are seeing so we can work on a fix.

**Comment by Eunix** [comment]
I also have the same error again now.

**Comment by lohit398** [comment]
I also have the error again in VS code for non-salesforce projects.

Thanks!

**Comment by alechko** [comment]
I'm having this issue as well on non-salesforce projects, even on non-react projects, this seems to be triggered simultaneously with saving a file.

Salesforce CLI - 49.9.0
Code - 1.49
