### ISSUE TITLE
Folders without sfdx-project.json files should see an option to "Initialize Salesforce DX Project"

### ISSUE THREAD

**Issue by abd3** [forcedotcom/salesforcedx-vscode#207]
### Summary
Currently, if a project folder is opened in VS Code that does not contain an sfdx-project.json file none of the SFDX commands are exposed in the Command Palette. This causes confusion for users (like me) who didn't read the instructions which explain this behavior. For example, see [this issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/117). At a minimum users should see an option in the Command Palette to "Initialize Salesforce DX Project" that runs force:project:create and queries the user for the project name. This will greatly reduce confusion and reassure users that the extension is working, but steps are required to use it fully.

### Steps To Reproduce:
1. Open a VS Code window pointing to a folder with no sfdx-project.json file
1. Open the command palette and search for "SFDX" commands

### Expected result
Users would expect there to be some options available if the SFDX extension is installed

### Actual result
'No commands matching' is shown in the Command Palette

### Additional information

**VS Code Version**:
1.17.2

**SFDX CLI Version**:
sfdx-cli/6.0.14-2af879b (darwin-x64) node-v8.6.0

**OS and version**:
Mac OS X 10.11.6

**Comment by vazexqi** [comment]
This would be partially addressed by #197 but in general we might want some way to help people migrate over from the old project format which might not have a sfdx-project.json.

**Comment by chowwinston** [comment]
#197 has been merged. This will be available with the next version.
