### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by maliuppal** [forcedotcom/salesforcedx-vscode#2071]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.5.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.43.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Hi @maliuppal  - We don't have enough information about what happened to look into this.  Please re-open this and add more info if you have it.
