### ISSUE TITLE
Update Documentation on Prettier Code Formatter

### ISSUE THREAD

**Issue by nickytorstensson** [forcedotcom/salesforcedx-vscode#2079]
I am reading the documentation on Prettier Code Formatter for apex etc.
https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/

I am reading the following parts of the documentation:

> To install the Prettier Apex plugin:
> 1. Check if your project contains the package.json file. If not, run: npm init and accept all the default options.
> 2. Run: npm install --save-dev --save-exact prettier prettier-plugin-apex.

It is not clear, where you want me to run "npm init". 

**Running command line in terminal of VS Code:**
_- npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._

**Running command line in Command Prompt:**
_- 'npm' is not recognized as an internal or external command, operable program or batch file.'npm' is not recognized as an internal or external command, operable program or batch file._

Please update your documentation so it is not ambiguous.

**Comment by lcampos** [comment]
Hi @nickytorstensson thanks for opening this suggestion. Are you looking for where in the project structure to run the command or which application (VSCode's terminal, Windows command line, etc) you should use to run this? Additionally, would explaining that this tooling relies in the use of NodeJS and its package manager (npm) provide enough clarity ?

**Comment by nickytorstensson** [comment]
Hi @lcampos 
In step 1 of the guide I should run `npm init`. I tried doing so in the terminal of VS Code and also Command Prompt without success. It is therefore unclear to be, which application I should use to run this.

I assume that NodeJS is installed with Salesforce CLI, and thus the npm program is recognized. But maybe I am mistaken, and the article has the underlying assumption, that the user following the guide has node package manager set to PATH in system environment variables. If that is an implicit assumption, then it would be great to have that made clear.

Finally, from your quote _"Are you looking for where in the project structure to run the command"_, if there is a specific location in the project structure from where to run `npm init` that would also be great to clarify explicitly.

**Comment by lcampos** [comment]
I'm closing this since we released updates to the docs last week. Thanks for your feedback @nickytorstensson .
