### ISSUE TITLE
Searching project crashing Macbook Pro

### ISSUE THREAD

**Issue by mtagler-relativity** [forcedotcom/salesforcedx-vscode#2082]
### Summary

For the last few months me and my teammates on Macbooks are unable to use the search feature in VS Code. I only use the Salesforce extensions and ForceCode. In either case, I can't finish typing my search term before the screen freezes. Eventually the fan kicks on and after a while the machine reboots. Search is the only thing I use VS Code for; the devs on my team don't seem to have issues with other aspects of VS Code.

### Steps To Reproduce:

1.  Open VS Code
1.  Open folder containing project
1.  Click on Search icon on left
1.  Type a search term
1.  Results start to load as text is typed
1.  About 4 characters in, machine locks up

### Expected result

Search results from the project should be returned, so I can examine them.

### Actual result

Cursor freezes, can't force quit or do anything. Cursor turns into rainbow pinwheel. Fan kicks on. After 5-10 minutes of fan running machine restarts.

### Additional information

Followed Trailhead instructions for installing; on my PC worked just fine. PC teammates have no issues, Mac teammates can't search either. Searching is the only thing I use this for.

**VS Code Version**: 1.43.1

**SFDX CLI Version**: 48.6.0

**OS and version**: Mac Mojave 10.14.6

**Comment by lcampos** [comment]
Hi @mtagler-relativity , the search feature is not something the extensions interact with and is provided by the editor. One thing that you can look into is excluding folders/files that should be ignored while searching. Here's a doc that provides more details around this https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

We also provide some exclusions when you scaffold a project (`SFDX: Create Project ...`) and I'm adding them below.

This can be added as part of your project's `.vscode/settings.json` file:
```
{
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.sfdx": true
  }
}
```

If this is not enough I suggest you open an issue with steps to reproduce the issue on the VSCode repository.

**Comment by mtagler-relativity** [comment]
Thanks. I'm going to have to open an issue on the VSCode repository. I already have all of those search.exclude settings in place.

**Comment by mtagler-relativity** [comment]
One thing I tried was disabling all extensions and I can search just fine.

**Comment by mohanraj-r** [comment]
@mtagler-relativity The issue is puzzling and unique. We are not sure what could be causing this issue as mentioned earlier  in this issue we don't customize/interact with VSCode's search feature. Is there anything specific about your project size, number of files, size of files etc that could be causing this issue with the extensions? Can you please check if the issue still exists with the latest version of the extensions and reopen this issue as necessary.
