### ISSUE TITLE
`runSingleTest` and `runClassTests` failed without any errors

### ISSUE THREAD

**Issue by vazexqi** [forcedotcom/salesforcedx-vscode#2088]
### Summary

The commands Run Tests and Run Single Test from the Command Palette fails.

### Steps To Reproduce:

1.  Create a new project and open it in VS Code.
1. Add some Apex test classes
1. Ensure that you have pushed the source and that everything compiles.
1. Open up a valid Apex test class.
1. Try to invoke Run Tests (there are two in the palette so be sure to invoke the one that runs the tests in the class). Notice that it will fail.
1. Try to invoke Run Single Test. Notice that it will fail.

### Expected result

Tests are run.
Or, these commands are *hidden* from the palette if they are meant to be hidden commands to enable other actions in the UI.

### Actual result

Error in the commands.

### Additional information

![ScreenFlow](https://user-images.githubusercontent.com/54414/77136485-89b81480-6a28-11ea-8aa6-4c78cf757c62.gif)

**Comment by vazexqi** [comment]
I suspect that this is because of https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/package.json#L117-L125 where the commands are showing up in the command palette too liberally.

**Comment by lcampos** [comment]
This is an issue with those commands being exclusive to the Apex Test side bar but not being explicitly hidden in the command palette. We'll take care of this in the following releases.

**Comment by lcampos** [comment]
Fixed in version 48.8.0
