### ISSUE TITLE
add a parameter for `sfdx force:org:open` to indicate whether it is lightning or classic to open

### ISSUE THREAD

**Issue by garychenming** [forcedotcom/salesforcedx-vscode#2089]
As a SFDC developer, my development scenario was limited to classic, with the default lightning experience every time I opened org, and I had to switch to classic, which was time wasting when the network was bad.

So I hope there is a parameter to specify the experience mode of opening org. like this:

```
$: sfdx force:org:open -u orgName -l // open an org with lightning experience
$: sfdx force:org:open -u orgName -c // open an org with classic mode
```

**Comment by jackTylerDurden** [comment]
What should be the default value of this parameter(i.e. if not specified)?

**Comment by garychenming** [comment]
> What should be the default value of this parameter(i.e. if not specified)?

Lightning is the current trend, so I think the default value should be lightning.

**Comment by jackTylerDurden** [comment]
Hi @garychenming,
Thanks for the quick reponse. 

I went through the documentation of Salesforce CLI Command Reference and found that there already exists a command which opens the org in lightning when a parameter is given.

The command I used is - 
sfdx force:org:open -u <username>  -p lightning

Please find the documentation [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_org.htm#cli_reference_force_org). Please look for '  $ sfdx force:org:open -r -p lightning' once you go to the documentation.

Please let me know if I'm missing anything.

Thanks, and Regards,
Tanmay

**Comment by gbockus-sf** [comment]
nope...long never'd. Thanks for the callout @AllanOricil
