### ISSUE TITLE
With default shell set to Git Bash, running Jest tests failed in Windows

### ISSUE THREAD

**Issue by xyc** [forcedotcom/salesforcedx-vscode#2097]
### Summary

With default shell set to Git Bash, running Jest tests failed in Windows

### Steps To Reproduce:

1. in Windows, Install Git
2. Open Command Palette: Terminal: Select Default Shell
3. Set default shell to Git Bash
4. Run a jest test from VS Code

### Expected result

Should successfully run

### Actual result

Fails with:
node_modules.binlwc-jest: command not found
The terminal process terminated with exit code: 127

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by mkd5329** [comment]
This is so true
