### ISSUE TITLE
Permission Set - System Permissions - Apex Debug not enabled by default

### ISSUE THREAD

**Issue by daveb-501commons** [forcedotcom/salesforcedx-vscode#210]
### Summary
https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/debugger_set_up_parent.htm

You have to contact support to get Apex Debug option enabled for your org.

### Steps To Reproduce:
Go to System Permissions and there is no Apex Debug option.

### Expected result
When you Enable DevHub or on any Scratch org to have Apex Debug option available without having to contact support.

### Actual result
Not showing and have to contact support

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by guw** [comment]
Hi @daveb-501commons, some services and subscriptions include the debugging feature for an extra cost.

@ruthemmanuelle I think we should add a statement to the "Prerequisites" section in the debugger readme that a contact is necessary for enabling the Apex Debugger. There is a [dedicated section to this in the Force.com IDE guide](https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/debugger_enable.htm).

**Comment by ruthemmanuelle** [comment]
@guw - Do customers with Performance Edition and Unlimited Edition orgs need to contact Salesforce to enable their one free Debugger session? We list this as a requirement in the Prerequisites section of the README currently:

At least one available Apex Debugger session in your Dev Hub org
  * One Apex Debugger session is included with Performance Edition and Unlimited Edition orgs.
  * To purchase Apex Debugger sessions for Enterprise Edition orgs, or to purchase more sessions for orgs that already have allocated sessions, contact Salesforce.

**Comment by guw** [comment]
@kaplanjosh Can answer that finally. As far as I remember the answer is yes, i.e. even they have a free license, they still need to contact Salesforce for activating it (as written in the Force.com IDE guide).

**Comment by kaplanjosh** [comment]
You do not need to call anyone to begin using the debugger in Performance Edition and Unlimited Edition. You will only need to contact Salesforce to purchase additional sessions beyond the included session.

**Comment by guw** [comment]
Thanks @kaplanjosh!

@ruthemmanuelle I think with the last statement from Josh we can leave the README as is.

**Comment by ruthemmanuelle** [comment]
Josh sent me an email with some suggested improvements to the Force.com IDE Dev Guide, and I've filed W-4487504 for that doc work.
