### ISSUE TITLE
Detect Conflict feature is not working

### ISSUE THREAD

**Issue by neelxkamal** [forcedotcom/salesforcedx-vscode#2106]
I just test the conflicting feature but alas it's still not working. I follow the same steps as it is given in links. File->Preferences->Setting Extension-> Salesforce Feature Preview.Checked the checkbox 'Detect conflict at sync. Please check the attached screenshot of the setting. Please let me know if I missed any steps. I updated one Apex class from Developer console and then try to update and deploy same file from VS code. It didn't detect the differences. Currently, we are using The Welkin Suite editor and conflict detection is working very well. 
![ss 2020-03-31 223024](https://user-images.githubusercontent.com/16945389/78093901-3be4ca00-73a1-11ea-8dbf-931889a451a1.png)

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1. File->Preferences->Setting Extension-> Salesforce Feature Preview
1.  This is step 2. Check the checkbox  Detect conflict at sync.
1. This is step 3. Update Apex class from Developer console and save.
1. This is step 4. Update the same Apex class using VS code without retrieving from the sandbox.
1. This is step 5. Save and Deploy.

### Expected result
It should not deploy and alert for conflict

### Actual result
Deployed successfully.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.43.2

**SFDX CLI Version**: 48.8.0

**OS and version**: Window 10

**Comment by lcampos** [comment]
Thanks for opening this issue @neelxkamal . Can you confirm you are deploying using the `SFDX: Deploy Source in Manifest to Org` on your `package.xml` ? Conflict detection is currently only enabled on Deploy and Retrive with Manifest.
