### ISSUE TITLE
default org not set from sandbox org:status

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#2107]
### Summary

When creating a sandbox from the CLI, you have to call org:status to get it connected.  When you set that as your default, the vscode tray doesn't pick up that change.

![Screen Shot 2020-04-01 at 3 57 31 PM](https://user-images.githubusercontent.com/4261788/78186139-d2f96280-7431-11ea-839c-33967d519c2b.png)

### Steps To Reproduce:

1.  create a sandbox (sfdx force:org:create -t sandbox etc)
2. auth to your sandbox by name and add the -s option `sfdx force:org:status -n RegCmp -s -u platformers`

It connects, and "open default org" is now available in the context menu

### Expected result
tray includes the username of your sandbox
org browser appears

### Actual result

"No default org set"
no cloud icon in the sidebar

### additional information
I can set the default org manually via cmd-p

**Comment by lcampos** [comment]
Thanks for opening this issue @mshanemc. The extensions pick up the default org by it being set as the global defaultusername or by the org being the default for that project. 

Can you confirm if you are setting it globally or at the project level ? If you are setting it at the project level can you check that you see the `defaultusername` being set in your project's `.sfdx/sfdx-config.json` file.
