### ISSUE TITLE
Broken relative link on Apex Tests page

### ISSUE THREAD

**Issue by randi274** [forcedotcom/salesforcedx-vscode#2108]
### Summary

The 'Java setup' link on the Apex Tests page is broken.

### Steps To Reproduce:

1.  Go to https://developer.salesforce.com/tools/vscode/en/apex/testing/
1.  Click on 'Java setup' link.
1.  Receive a 503 maintenance page

### Expected result

Should be redirected here: https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/

### Actual result

Link is broken.

### Additional information

Looks like https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/docs/_articles/en/apex/testing.md is retreating too far up the directory.

**Comment by smaddox-sf** [comment]
Hi @randi274 - Thanks for logging this!  We'll get it corrected.  (Feel free to send a pull request if you beat us to it.)

**Comment by lcampos** [comment]
Fixed on release 48.11.0, thanks for your feedback
