### ISSUE TITLE
Can't install Salesforce Lightning extension in VS Code

### ISSUE THREAD

**Issue by raJSN** [forcedotcom/salesforcedx-vscode#211]
### Summary
Can't install "Lightning Component Code Editor for Visual Studio Code" extension.

### Steps To Reproduce:
1. Download the latest VS code editor.
2. Install all extensions one by one as mentioned here "https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode#overview" 
3. All extensions are installed except "Lightning Component Code Editor for Visual Studio Code".
4. Received error is "end of central directory record signature not found".

### Expected result
Extension should be installed.

### Actual result
Received Error.

### Additional information
Screenshot attached.
![lightning extension installation error](https://user-images.githubusercontent.com/3901703/32688128-44fd1caa-c6f1-11e7-8f11-7d1e5994deb5.png)
**VS Code Version**:
1.18.0

**SFDX CLI Version**:
sfdx-cli/6.0.14-2af879b (windows-x64) node-v8.6.0

**OS and version**:
Windows 7 , Ulitmate, SP1

**Comment by raJSN** [comment]
Tried using cmd, but same issue.
C:\Users\lapworld tech>code --install-extension salesforce.salesforcedx-vscode-lightning
Found 'salesforce.salesforcedx-vscode-lightning' in the marketplace.
Installing...
Error: end of central directory record signature not found
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:183:14
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:618:5
    at C:\Program Files\Microsoft VS Code\resources\app\node_modules\fd-slicer\index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)

**Comment by guw** [comment]
@raJSN What happens if you install the full extension pack bundle? It should install all extensions at once. Does that work for you?

**Comment by raJSN** [comment]
Hmm... I tried that also. But it didn't worked out as well.

**Comment by guw** [comment]
Seems seems to be a common problem in VS Code. Can you review the information at https://github.com/Microsoft/vscode/issues/2384? It suggests that this may be a network/dns issue.

**Comment by raJSN** [comment]
Yes, I checked this too. But i am not behind any firewall.

However, we can close this issue as i am able to install the extension from local file.
