### ISSUE TITLE
Hi Team,  I am trying to create sfdx project in vs code but it is not creating the project showing the loading prompt from almost 1 hour. can anyone please help me

### ISSUE THREAD

**Issue by varunsalesforce** [forcedotcom/salesforcedx-vscode#2114]
Hi Team,

I am trying to create sfdx project in vs code but it is not creating the project showing the loading prompt from almost 1 hour.
can anyone please help me

![image](https://user-images.githubusercontent.com/60394074/78784540-2421cd00-79c3-11ea-8b29-6f30b5f350ac.png)

**Comment by lcampos** [comment]
Hi @varunsalesforce , can you provide more details on your setup to see if we can replicate your issue on our side ? What version of VSCode are you on, which OS, which version of the Salesforce extensions are you on and which Salesforce CLI version.
