### ISSUE TITLE
Hi,  I am able to create project but its not connect to the authorize the org.

### ISSUE THREAD

**Issue by AmitBhati07** [forcedotcom/salesforcedx-vscode#2118]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
HI @AmitBhati07 - We don't have enough info to try to help.  Can you complete the issue template with the steps you are using and what you are seeing?  The VS Code, CLI and OS version info is also helpful.
