### ISSUE TITLE
sfdx force:source:pull unexpected file found in package directory: package.xml

### ISSUE THREAD

**Issue by daveb-501commons** [forcedotcom/salesforcedx-vscode#212]
### Summary
running sfdx force:source:status or sfdx force:source:pull and getting error

ERROR:  Unexpected file found in package directory: C:\repo\salesforce-food-bank\src\package.xml.

### Steps To Reproduce:
1) clone https://github.com/groundwired/salesforce-food-bank
2) Use CumulusCI to deploy
3) Make a change in the scratch org
4) sfdx force:source:status or sfdx force:source:pull

### Expected result
to sync back the scratch org change

### Actual result
error - above

### Additional information
Added package.xml to the .forceignore and then sfdx:source:status works but sfdx force:source:pull generates a different error.

ERROR:  version.match is not a function.
 
looking at C:\Users\[myuser]\.sfdx\sfdx.log
 
{"name":"sfdx","hostname":"DESKTOP-GBTN6MU","pid":16608,"level":50,"msg":"version.match is not a function.","time":"2017-11-13T01:16:58.721Z","v":0}
{"name":"sfdx","hostname":"DESKTOP-GBTN6MU","pid":16608,"level":50,"msg":"[ false,\n  '{\"message\":\"version.match is not a function\",\"status\":1,\"stack\":\"TypeError: version.match is not a function\\\\n    at MdapiPackage.setVersion (C:\\\\\\\\Users\\\\\\\\dboyc\\\\\\\\AppData\\\\\\\\Local\\\\\\\\sfdx\\\\\\\\client\\\\\\\\node_modules\\\\\\\\salesforce-alm\\\\\\\\dist\\\\\\\\lib\\\\\\\\mdapiPackage.js:111:25)\\\\n    at new MdapiPackage
 
the code there is
 
/**
     * Set the package version
     * @param version the version intended to be included in package.xml
     */
    setVersion(version) {
        if (!util.isNullOrUndefined(version)) {
            if (version.match(/[0-9]*.0/)) {
                this.Package.version = version;
            }
            else {
                throw almError('invalidVersionString');
            }
        }
    }
 
There is where it is throwing the version.match is not a function I'm guessing because the version is coming in as null.

_Feel free to attach a screenshot_.

**VS Code Version**:
1.18

**SFDX CLI Version**:
sfdx-cli/6.0.14-2af879b (windows-x64) node-v8.6.0

** CCI Version**:
2.0.0-beta75

**OS and version**:
Windows 10

**Comment by guw** [comment]
Hi @daveb-501commons, thanks for reporting! This looks like a general CLI question. It's probably best to ask this over in the the Trailblazer Community in the [Salesforce DX](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1SAG) group.
