### ISSUE TITLE
Org Browser And Lightning Explorer Icons Not Visible

### ISSUE THREAD

**Issue by nikhil-sfdev** [forcedotcom/salesforcedx-vscode#2120]
Org Browser Icon And Lightning Explorer is not visible 

<img width="112" alt="Screenshot 2020-04-15 at 2 50 30 PM" src="https://user-images.githubusercontent.com/22937196/79321333-cd6b4480-7f28-11ea-9045-887dd17a4e74.png">

**VS Code Version**:
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z (4 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

**Salesforce Extension Pack Vesrion**:
48.10.0

**SFDX CLI Version**:
sfdx-cli/7.53.0-839fc82926 darwin-x64 node-v10.15.3

**OS and version**:
OS: Darwin x64 19.4.0

**Comment by nikhil-sfdev** [comment]
Reopen Vs Code will solve it !

**Comment by mjaggard** [comment]
@nikhil-sfdev and if it doesn't?!
