### ISSUE TITLE
Apex Language Server hangs on large(>3000 lines) Apex classes.

### ISSUE THREAD

**Issue by uBiWca** [forcedotcom/salesforcedx-vscode#2121]
### Summary

While working on large Apex *.cls files, with number of lines > 3000 Apex Language Server stops working. No more code completion, as a result. Restarting of VS Code is necessary in order to get language server back  to job.
### Steps To Reproduce:
Machine used:
Ryzen 5 1600, 8GB DDR4, Gigabyte SSD 240GB, Windows 10 Pro. VS Code 1.43.2
1. Open large *.cls
2. PROFIT!

This doesn't happens on Ubutnu 18.04, running on i3 with 16GB of DDR4.

Throws following logs:
`��� 15, 2020 3:11:52 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2441
��� 15, 2020 3:11:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2449
��� 15, 2020 3:11:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2450
��� 15, 2020 3:11:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2452
��� 15, 2020 3:12:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2455
��� 15, 2020 3:12:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2458
��� 15, 2020 3:12:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2457
��� 15, 2020 3:12:01 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2460
��� 15, 2020 3:12:01 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2464
��� 15, 2020 3:12:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2466
��� 15, 2020 3:13:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2492
��� 15, 2020 3:13:09 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2496
��� 15, 2020 3:13:11 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2497
��� 15, 2020 3:13:12 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2501
��� 15, 2020 3:13:15 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2507
��� 15, 2020 3:13:17 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2502
��� 15, 2020 3:13:20 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2518
��� 15, 2020 3:13:23 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2515
��� 15, 2020 3:13:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2523
��� 15, 2020 3:13:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2519
��� 15, 2020 3:13:37 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2524
��� 15, 2020 3:13:37 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2525
��� 15, 2020 3:13:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

[Error - 15:13:57] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

��� 15, 2020 3:14:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2532
��� 15, 2020 3:14:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2538
��� 15, 2020 3:15:03 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2546
��� 15, 2020 3:15:03 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2534
��� 15, 2020 3:15:07 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2548
��� 15, 2020 3:15:24 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2558
��� 15, 2020 3:15:37 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2550
`
Java heap space left by default.

**Comment by uBiWca** [comment]
Что такое, дорогие мои индусы? Это вам не девочек топить и не лойсы на стековерфлоу клянчить?

**Comment by az-oolloow** [comment]
@uBiWca it clearly says that your jvm is out of ram, just add more ram to the JVM config...

**Comment by smaddox-sf** [comment]
Hi @uBiWca - Here's the documentation on how to try @az-oolloow suggestion - You can use the salesforcedx-vscode-apex.java.memory setting to assign more memory to the process and see if that's what's causing this issue. Here is the doc on how that setting works https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/#advanced-setup.  Let us know if this doesn't solve it.

We've seen this type of error happen when the language server process is not assigned enough memory by the Java JVM. By default, Java would assign up to one quarter of the machine's physical memory (RAM).

**Comment by uBiWca** [comment]
Yeah, i already tried that. I tried 3072, 4096...
With 3072:
`[Info  - 10:04:15] Connection to server got closed. Server will restart.
[Info  - 10:04:15] Connection to server got closed. Server will restart.
[Info  - 10:04:15] Connection to server got closed. Server will restart.
[Info  - 10:04:15] Connection to server got closed. Server will restart.
[Error - 10:04:15] Connection to server got closed. Server will not be restarted.`
With 4096: 
`Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
[Info  - 10:09:16] Connection to server got closed. Server will restart.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
[Info  - 10:09:16] Connection to server got closed. Server will restart.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
[Info  - 10:09:16] Connection to server got closed. Server will restart.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
[Info  - 10:09:16] Connection to server got closed. Server will restart.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
[Error - 10:09:16] Connection to server got closed. Server will not be restarted.`

And, besides, dont you think, what requiring more than 2Gb of RAM to be able to edit file with size of 290Kb( 7231(!) times LESS in size)  is to much? Especially in case of IDE with set of features near basic notepad?  I have Android Studio also installed on this machine, and it runs like a rocket, while having much more features.

**Comment by uBiWca** [comment]
Ok, so i moved to Java 11, and set maximum java memory size to 4096 mb. Now Apex Language server works with this settings, but... When i was young, i was coding under ms-dos on a machine with 1 mb ram(yeah,  ONE MEGABYTE of RAM). And what do you think? It was very satisfying experience. ONE MEGABYTE of RAM. And now i need 4096mb to force IDE to work, while this IDE has almost the same functionality as Borland Pascal 7.0 had on 386 running 25 mhz with 1 MB of RAM. Maybe you need to do some optimizations, dont you think so?

**Comment by az-oolloow** [comment]
I used to work on a i-80286 machine with 384 KB Ram that could not handle MS-DOS 5.0 and had to be stuck on MS-DOS 3.22. GWBasic and line numbers. That means nothing.

None of these IDEs gave you any code completion.

Perhaps if you share a specific Apex file that causes the server to hang it can be analyzed to fix the issue.
Dealing in LOCs means nothing. You can have empty lines or lines so complex that a single line can't be easily broken down into lexems.

**Comment by uBiWca** [comment]
Im sorry - what? You saying you need 4 gb of java heap to provide really basic code completion for project of 1.5 Mb?
Can you , please, explain, why Android Studio gives much better experience with only 2 gb of java heap on same machine for projects >4mb? 
Or maybe - how Lazarus provides code completion on my old Asus EEPC with only 1 GB of RAM?
Answer is really simple - you dont need MORE RAM. You just need MORE EXPERIENCE in programming, because Salesforce pack for VS Code- just a bunch of dirty and badly optimized code. Which STILL requires standalone formatter.

**Comment by uBiWca** [comment]
And it broken. Again. After updating Vs Code to 1.45.1 Apex Language server working VERY slow, throwing ```
��� 20, 2020 12:00:36 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 359 
``` in its output.
Can somebody, please, tell me, how much RAM should i buy to work with your "cloud" system with minimal acceptable performance? 64gbs will be enough? Maybe 128? Maybe i need to switch to some supercomputer or cluster?

**Comment by smaddox-sf** [comment]
This is not a polite nor productive discussion. As such, I am closing it. Please see our code of conduct: https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/CODE_OF_CONDUCT.md

**Comment by uBiWca** [comment]
Sure its not productive. Issue was opened on 15 April. Nothing was done till 21 May,  when issue was closed, because "discussion is not polite and productive", except stupid suggestions to buy more RAM, because this notepad-like ide with similar functionality  feels bad  on 8 gigs.
Im sorry, i hurt you feelings? You know what? Im NOT SORRY for this.
