### ISSUE TITLE
Using beta feature Performance Enhancements, deploy shows success message, but it actually failed

### ISSUE THREAD

**Issue by EstebanRomero84** [forcedotcom/salesforcedx-vscode#2124]
### Summary

I have a DX project connected to a sandbox and I activated the Performance Enhancements beta feature.
After some changes in an Apex class, I saved it and used the Deploy This Source to Org option from mouse rigth click menu. After a couple of seconds a "Deploy (Beta) run seccessfully" message was displayed in the status bar.

Then I openend the same Apex class in the developer console but my last changes weren't there.

I repeated this process 2 more times but always got the same result.

After that, I deactivated this beta feature and run a new deploy from mouse rigth click menu. This time I got "SFDX: Deploy Source to Org failed to run" message and a list of sintax errors from my class.

### Expected result

Display an error message in the status bar.

### Actual result

Display a success message in the status bar.

### Additional information

I made a pretty obvious syntax error in last line, but I got an success message.

![image](https://user-images.githubusercontent.com/30849643/79498462-be0afa80-7fff-11ea-9118-274ccc1c1e41.png)

**VS Code Version**:
1.44.1
**SFDX CLI Version**:

sfdx-cli/7.53.0-839fc82926 win32-x64 node-v10.15.3

**OS and version**:
OS: Windows_NT x64 10.0.18362

**Comment by AnanyaJha** [comment]
Hi @EstebanRomero84 thanks for reporting this! We've noticed this error as well, but I wanted to confirm something else. When you attempt to deploy a class that should fail (but still shows the successful notification), do you see an error message printed in the output panel at the bottom of the window? It should look similar to this: 
<img width="1134" alt="Screen Shot 2020-04-16 at 3 06 07 PM" src="https://user-images.githubusercontent.com/21326913/79501632-fc9ab800-7ff3-11ea-913f-260f543d7589.png">

**Comment by EstebanRomero84** [comment]
Hi @AnanyaJha Yes, that's correct, the output panel displays proper error message.

**Comment by AnanyaJha** [comment]
@EstebanRomero84 Cool, it sounds like the same issue we've been seeing- I'll log a bug for it. Thanks for reporting this!

**Comment by lcampos** [comment]
Closing since this fix is out as part of v48.13.0. Thanks for providing feedback.
