### ISSUE TITLE
SFDX: Create Project failed to run

### ISSUE THREAD

**Issue by vipes14** [forcedotcom/salesforcedx-vscode#2126]
**Summary**

I am unable to create project in vs code after setting up salesforce dx and cli

**Steps To Reproduce:**

1.  Install VS Code and Salesforce Extension pack
2.  Install Salesforce CLI and sfdx.
3. ctrl+ shift+p -- > sfdx: create project ---> standard template --> TestSFDX

**Expected result**

Project is created successfully

**Actual result**

Ended with exit code 1 

 **Additional information**

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/8925006/79868637-ceefad80-83fd-11ea-9b15-dd138d0d5354.png)

![image](https://user-images.githubusercontent.com/8925006/79868851-2db52700-83fe-11ea-84da-d81432fa89f5.png)

**VS Code Version**: 
1.44.2 (User Setup)

**SFDX CLI Version**:
7.54.4

**OS and version**:
Windows 10 Enterprise

**Comment by garapath** [comment]
I have the same issue while creating  new project. can you share how you fixed it.

**Comment by carfi187** [comment]
I'm also having the same issue. I've tried uninstalling the SFDX extensions and re-installing, but no luck. 

Here's my version info:
sfdx-cli/7.56.1-2773b53bf5 linux-x64 node-v10.15.3
