### ISSUE TITLE
Extension issue, high CPU load

### ISSUE THREAD

**Issue by ScottFarrell** [forcedotcom/salesforcedx-vscode#2127]
[CPU-20200421T132941.082Z.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4510302/CPU-20200421T132941.082Z.cpuprofile.txt)
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `48.11.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.44.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 2440,
		"activateCallTime": 11,
		"activateResolvedTime": 342,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```
[CPU-20200421T132941.082Z.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4510312/CPU-20200421T132941.082Z.cpuprofile.txt)

**Comment by mrmicahcooper** [comment]
Hi @ScottFarrell I'm hoping you can provide a little bit more information to help reproduce this bug:

- Do you recall what you were doing? i.e. Just starting a new project? Or working in a large file?
- Had you been noticing this issue for a while or is this the first time you've seen it?
- What are your computer resources looking like? RAM, Processor, Hard Drive (SSD or HDD?)
- How large is your project - Rough number of files? Can you reproduce this in other projects?

Thanks a million for reporting this.

**Comment by ScottFarrell** [comment]
I opened Visual Studio code with no files open and the CPU usage jumped to 70%+ after a few seconds of running.  After a couple of minutes running, VSC is consuming 90%+ of CPU time, effectively crashing the operating system by making it completely non-responsive.  I had to hard-reboot by powering down to recover.  Couldn't even open task manager.

This is the first time I've used VSC.  The installation is fresh, the Java JDK is the current 11.x branch, and the Apex plugins were installed recently and updated to current.

My PC is an 8 core i7-6600U (4 physical, 4 HT) at 2.8 GHz  with 16 GB of RAM, Samsung SSD HDD (512 GB).

VSC is bogging down immediately upon opening (or nearly so) with no files open.  I have only one project, my development code for our Salesforce sandbox.  In that project we have approximately 1700 Apex classes and 1200 VF pages.

**Comment by ScottFarrell** [comment]
I should add, I disabled all extensions in VS code and the CPU hogging went away.  I selectively added back one extension at a time, restarting VSC between each change, and the CPU load began immediately after enabling "Apex" (which also enables "Salesforce CLI Integration".  The version # for Apex is 48.11.0 and CLI is 48.11.0 as well.

**Comment by ScottFarrell** [comment]
Here is what Process Explorer shows after VSC is running for approximately 20 seconds, consuming around 50% CPU.  This will continue to climb until it maxes out and crashes the computer.
![4-23-2020 11-26-50 AM](https://user-images.githubusercontent.com/64085131/80117705-7e8b6380-8555-11ea-928a-5284c3b210a3.png)

**Comment by zodel** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/41858581/80190552-1321be80-8647-11ea-970f-4f39748d74f1.png)

**Comment by lcampos** [comment]
@ScottFarrell this is a known issue we're working on in which the Apex language server has performance issues indexing large projects. You could try assigning more memory to the process (https://salesforcedx-vscode.netlify.app/tools/vscode/en/getting-started/java-setup/#advanced-setup) and see if that helps while we release a fix.
cc @smaddox-sf @ntotten

**Comment by smaddox-sf** [comment]
Duplicate #1149
