### ISSUE TITLE
Bulk deployment occurred when tried to deploy a single lwc component to an org

### ISSUE THREAD

**Issue by ashu16oct** [forcedotcom/salesforcedx-vscode#2129]
As I was using VSCode to work on LWC components.
In last week when tried to deploy a single LWC component to my SFDC org, I could found that,
1) Out of total 4007 of Apex Classes, 1522 classes have been updated.
2) Out of 1000 of Apex Pages(Visualforce Pages), 7 pages have been updated
3) Other than this no change in any component occurred.
Steps I followed,
  1) Took a retrieve of the LWC Component
  2) Made some changes  
  3) Cliked on "Deploy this to Source Org"
  4) Checked the Salesforce CLI logs, as updated.
For analyzing this issue, followed the below things,
  1) Queried all ApexClasse and ApexPages which has LastModifiedBy my user
  2) Validate the Audit trail from Salesforce
  3) Checked the VSCode logs
  4) Checked the VSCode and Extensions Setting
But, still I could not able to find the exact root cause.
This incident was happened on 16th April 2020 between 06.17 PM to 06.22 PM IST
Also, when I tried to reproduce this issue, followed above steps but this issue was not occurred again.
Please help us to understand the root cause of this issue and let us know how can we prevent it so that it would not happen again in future.

### Additional information

![image](https://user-images.githubusercontent.com/5506996/79967624-af638e00-84ac-11ea-9876-6198812788ea.png)

**Comment by smaddox-sf** [comment]
Hi @ashu16oct - When you clicked "Deploy this source to Org", were you using the Command palette or from the right-click menu?

**Comment by ashu16oct** [comment]
Hi @smaddox-sf, 
I was using right-click menu to deploy changes on org.

**Comment by ashu16oct** [comment]
Hi @smaddox-sf ,

any updates on it?

**Comment by smaddox-sf** [comment]
Thanks for the additional info @ashu16oct.  We are investigating this, but haven't seen any other repros of it

**Comment by ashu16oct** [comment]
Hi @smaddox-sf ,

any further updates on it?

**Comment by smaddox-sf** [comment]
Hi @ashu16oct - How frequently do you update the CLI?  

Have you seen this issue happen again?
