### ISSUE TITLE
Whenever I deploy any lwc component, it gets deploy but do not show the message of successful deployment  in the Vs Code editor.

### ISSUE THREAD

**Issue by Hiteshgarg98** [forcedotcom/salesforcedx-vscode#2130]
The below message is shown on the CLI in VS Code-> 

```19:08:15.413 sfdx force:source:deploy --sourcepath g:\Salesforce-MyORGs\practiceorg\FirstProject\force-app\main\default\lwc\lwcTodoParent\lwcTodoParent.html --json --loglevel fatal```

And when I cancel the deployment of the component

```ended with exit code 1```   is shown.

**Comment by lcampos** [comment]
Hi @Hiteshgarg98 can you provide more details on your setup ? Which vscode version are you on, which OS and which version of the Salesforce extensions are you running.
