### ISSUE TITLE
Saving file in VSCode results in: ended with error spawn sfdx

### ISSUE THREAD

**Issue by asanaEAzimzhanov** [forcedotcom/salesforcedx-vscode#2131]
### Summary

Executing any command using VSCode Salesforce Extension pack results in: **Salesforce CLI is not installed**

### Steps To Reproduce:

1.  Try to Save a file 

### Expected result

sfdx force:source:deploy ... is executed and the file is saved to org

### Actual result

sfdx force:source:deploy ... is executed, but "**ended with error spawn sfdx ENOENT**" is returned, the file is not saved

### Additional information

When I copy-paste the command from output to Terminal and execute it, it executes successfully.
The extensions worked before, but one day it just stopped.
Tried reinstalling extensions. Tried reinstalling SFDX CLI.  Nothing helped.

**VS Code Version**:
1.44.2
**SFDX CLI Version**:
sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3
**OS and version**:
macOS Catalina Version 10.15.4

**Comment by asanaEAzimzhanov** [comment]
Could anyone take a look at that please? I'm ready to provide more info or have a screensharing session if needed.

Thank you!

**Comment by lcampos** [comment]
@asanaEAzimzhanov can you clarify if by Terminal you mean VSCode's terminal or your machine's terminal client ? If the error happens by running the command in both VSCode's command palette and VSCode's terminal but not on your machines terminal client I think the issue is related to a misconfiguration where VSCode can't find the CLI's path. 

What do you get when you run `which sfdx` in VSCode's terminal vs your machine's terminal ?

**Comment by asanaEAzimzhanov** [comment]
@lcampos When I'm running a command from terminal in both - VS Code and my machine terminal, sfdx commands work. When I try to run a command form SFDX menu, i.e., "SFDX: Authorize an Org", it shows the error specified in first post in "Output" tab.
Result of command running `which sfdx` VSCode terminal
`/usr/local/bin/sfdx`
Same result running from Terminal on my machine.

**Comment by lcampos** [comment]
Ok, can you open VSCode's Developer Tools (VSCode > Help > Toggle Developer Tools ) go to the Console tab and see if you see any error being printed on it.

**Comment by asanaEAzimzhanov** [comment]
@lcampos yes, there're a couple of them. One of them says that unsupported Java installed. Will try to resolve this one and post the result here
![image](https://user-images.githubusercontent.com/63117002/80266517-02079a80-86a5-11ea-989d-d5959be29a6a.png)

**Comment by asanaEAzimzhanov** [comment]
@lcampos Looks like that's not the issue. I updated Java to 11 version, the error about Unsupported Java disappeared, but the initial issue remained. Tried to reinstall the plugins as well, didn't help. Tried to reboot the PC, didn't help as well.
At the start it also says that Salesforce CLI is not installed
![image](https://user-images.githubusercontent.com/63117002/80267273-81e33400-86a8-11ea-803a-aee6b9733021.png)
Console:
![image](https://user-images.githubusercontent.com/63117002/80267279-8d365f80-86a8-11ea-94fa-87d953169d1f.png)

**Comment by asanaEAzimzhanov** [comment]
Apparently, the issue is not related to the extension, but instead to the issue with VS Code itself. If the path to the project folder is too long, VS Code cannot spawn the process and results in the error described above.
https://github.com/microsoft/vscode/issues/85402
![image](https://user-images.githubusercontent.com/63117002/80268521-595f3800-86b0-11ea-9d2f-f0d9efc19509.png)
Shortening the path to the project has helped and resolved the issue.

**Comment by asanaEAzimzhanov** [comment]
I debugged further and it turned out that the issue is with the names of the folders - path contained a folder that had `_` in the name, i.e. `my_project` Renaming the folder resolved the issue.
