### ISSUE TITLE
SFDX: Create Project failed to run 

### ISSUE THREAD

**Issue by manaspatro** [forcedotcom/salesforcedx-vscode#2135]
Starting SFDX: Create Project

11:14:37.928 sfdx force:project:create --projectname Test --outputdir /Users/mpatro/Desktop/Per/Proj-Per --template standard
ERROR running force:project:create:  Command failed with ENOENT: npm root -g --prefix /Users/mpatro/Desktop/Per/Proj-Per/.yo-repository --loglevel error
spawnSync npm ENOENT
11:14:38.490 sfdx force:project:create --projectname Test --outputdir /Users/mpatro/Desktop/Per/Proj-Per --template standard
 ended with exit code 1

**Comment by manaspatro** [comment]
VERSION:
mpatro-ltm:~ mpatro$ sfdx --version
sfdx-cli/7.54.4-8ff9ba9cc5 darwin-x64 node-v10.15.3

PLUGINS
mpatro-ltm:~ mpatro$ sfdx plugins
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9

salesforcedx 48.10.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.8.0
└─ salesforce-alm 48.10.0

Please let me know if you need additional information.

**Comment by lcampos** [comment]
@manaspatro do you have any other yeoman configuration at the top-level of that file path you are using or globally in your machine ? The scaffolding commands of the CLI use yeoman and I think this might be caused by another yeoman config in your machine being picked up.

**Comment by ondreyn** [comment]
Hi manaspatro, I faced this issue too. Using Mac OS X 10.14 and bash as the main command interpreter. I solved this by running 'source ~/.bashrc' before creating a project. Hope this helps.
