### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by HemanthNeelapu** [forcedotcom/salesforcedx-vscode#2136]
When I'm trying to Create a project in the VS Code, I'm not able to create a project as it is running for a very long time.

When I'm trying to look into the Developer: Show Running extensions it is displaying the below error.

<img width="583" alt="CLI snap" src="https://user-images.githubusercontent.com/64067156/80129960-7c58f180-85b5-11ea-83e5-4ac2d7f1cca2.PNG">

- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.11.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
Thanks for opening this issue @HemanthNeelapu . Is this consistently happening ? Could you open VSCode's Developer Tools (VSCode > Help > Toggle Developer Tools) go to the Console tab and get the error stack trace so we can try and replicate on our side.

**Comment by HemanthNeelapu** [comment]
As requested by you, Please find the below details

<img width="958" alt="Console" src="https://user-images.githubusercontent.com/64067156/80276408-4ecf8d80-8706-11ea-8ee2-ae9a9c618b94.PNG">
<img width="494" alt="CLI Version" src="https://user-images.githubusercontent.com/64067156/80276414-568f3200-8706-11ea-8492-e8705e29e068.PNG">

**Comment by lcampos** [comment]
I'm still not able to replicate this issue on a Windows machine with the configuration you've provided. Is there any other step/configuration I should run ?

Also, is running the `sfdx force:project:create` directly in the terminal also failing/hanging ?
