### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by GargHitesh** [forcedotcom/salesforcedx-vscode#2137]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.11.0`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
I'm going to close this since there's no details on how to replicate it. Please reopen if you have the perf profile/report VSCode gives you or steps we can use to replicate the issue on our side.

**Comment by GargHitesh** [comment]
What more details you need?
Issue Type: Bug
Extension Name: salesforcedx-vscode-core
Extension Version: 48.11.0
OS Version: Windows_NT x64 10.0.10586
VSCode version: 1.44.2
I have added all the versions.

**Comment by GargHitesh** [comment]
I cannot be able to deploy my lightning we component to the org. Whenever I right-click and choose 'deploy this source to org' Vs Code continuously shows->
Running SFDX : Deploy Source to Org
![Screenshot (190)](https://user-images.githubusercontent.com/56029980/80276268-3ca11f80-8705-11ea-8edf-0737e461e83b.png)

I have to use '''sfdx force:source:deploy -p force-app -u practiceOrg'''
again and again to deploy the components to the org, which results into the bulk deployment.
