### ISSUE TITLE
SFXD Typo in forceAuthDevHub.test.ts

### ISSUE THREAD

**Issue by JosephAllen** [forcedotcom/salesforcedx-vscode#2139]
https://github.com/forcedotcom/salesforcedx-vscode/blob/2e0301489d7b91cd6036563a40a8433022285cb8/packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceAuthDevHub.test.ts#L137

Is the value `SFXD` correct? Should it be `SFDX`? It looks like the D and A are transposed.

**Comment by lcampos** [comment]
Closing since this was fixed in release 48.24.0, thanks for the feedback
