### ISSUE TITLE
SFDX command prompt to install packages using a installation URL

### ISSUE THREAD

**Issue by jriordan22849** [forcedotcom/salesforcedx-vscode#2140]
**Is your feature request related to a problem? Please describe.**
I am always frustrated that I have to open the org to install a package. It is just time consuming and I believe we should able to install the package via a command in VSCode. 
**Describe the solution you'd like**
I would like a SFDX command prompt where i can enter in the installation URL and package password(if it exists). After I hit enter in VSCode, the package will be installed into my scratch org.

**Describe alternatives you've considered**

**Additional context**

**Comment by smaddox-sf** [comment]
Thanks for providing feedback @jriordan22849.  Are you usually doing one-off package installs?  Or are you installing them as a part of mirroring the setup in a Sandbox or Production Org?  

We don't have this on our roadmap but will consider it in the future

**Comment by jriordan22849** [comment]
hi @smaddox-sf , for some packages, we have dependencies on other packages. These would be one-off installs into scratch orgs. It would be nice to pass the URL and/or password into a sfdx command prompt instead of performing the installation in the scratch org. Hope that helps.

Thanks

**Comment by gabrielbarker** [comment]
Yaaay! Thanks @smaddox-sf ! 🥳

**Comment by lcampos** [comment]
Closing since this was released on version `48.20.0`. Thanks for the contribution @gabrielbarker
