### ISSUE TITLE
No Apex Tests Found in VS Code despite tests existing

### ISSUE THREAD

**Issue by alexkadis** [forcedotcom/salesforcedx-vscode#2141]
## Summary 
Related: #1675, #1168
Visual Studio Code reports "No Apex Tests Found" despite Apex tests existing.

### Steps To Reproduce:

1.  Open the Test sidebar
2. No Tests found

![A screenshot showing the error in the left pane of VS Code](https://user-images.githubusercontent.com/4106499/80329455-63984800-8810-11ea-9e10-777f0910ca31.png)

### Expected result

1. Expected tests to be listed, they are not.

This _has_ worked previously for me. I'm not sure if the change is due to new versions of the extensions, a new version VS Code, or something else.

### Actual result
1. No test results found

#### Contents of debug window:
![A screenshot of the debug window for VS Code](https://user-images.githubusercontent.com/4106499/80329481-76128180-8810-11ea-8fd2-ef8a08a5c933.png) ([Gist of image contents](https://gist.github.com/alexkadis/d8585f4b5238627c54c7b4dd9560adec))

#### Contents of Apex Language Server Output
```log
22:32:25.556 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Apr 26, 2020 10:32:25 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075527 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 32 ms.
22:32:32.657 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
22:32:32.665 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
22:32:33.496 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
22:32:33.496 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 7940 ms.
22:32:34.794 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 1279 ms.

```

#### Contents of Log(Window):
[See this Gist](https://gist.github.com/alexkadis/d8585f4b5238627c54c7b4dd9560adec#file-vs-code-log-window-log)
The relevant lines contain: `[error] Running the contributed command: 'sfdx.force.test.view.showError' failed`

## Troubleshooting attempted:
1. Uninstalled Zulu Java 8, reinstalled Zulu Java 11 (latest - version # below).
2. Updated settings to 
```json
  "salesforcedx-vscode-core.retrieve-test-code-coverage": true,
  "salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home",
  "salesforcedx-vscode-apex.java.memory": 4096
```
3. Manually ran `sfdx force:apex:test:run --resultformat human --outputdir /Users/`_snip_`/.sfdx/tools/testresults/apex --loglevel error --codecoverage` <br /> After running all tests, code coverage in files works properly (lines are highlighted red/green depending on coverage), but the "No Apex Tests Found" error persists. <br /><img src="https://user-images.githubusercontent.com/4106499/80329884-9e4eb000-8811-11ea-8373-c6732069e69d.png" alt="A screen shot showing that code coverage detection works" height="300px" />
4. Disabled ["Detect Conflicts At Sync" (beta functionality)](https://salesforcedx-vscode.netlify.app/tools/vscode/en/user-guide/detect-conflicts/)
5. Opened the command palate (<kbd>CMD-SHIFT-P</kbd>) "SFDX: Invoke Apex Tests…" and all of the tests show up there. I am _able_ to run an individual test from that tool. They still do not show up in the side bar.

**VS Code Version**:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

**Extension Version**:
48.11.0 : April 16, 2020

**SFDX CLI Version**:
sfdx-cli/7.54.4-8ff9ba9cc5 darwin-x64 node-v10.15.3

**OS and version**:
macOS 10.15

**Java version**
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

**Comment by alexkadis** [comment]
My SObject definitions were incorrect and needed to be refreshed. Afterwards all tests were available and auto-completion worked as expected.

**SOLUTION:**
Command Pallet (CMD + Shift+ P) then select "SFDX:Refresh SObject Definitions"

**Comment by amitcomity** [comment]
I am facing the same issue, but above solution deosn't seem to working for me.

**Comment by bishwambharsen** [comment]
Same here. Kindly help.

**Comment by laszlo-foldi-attentioncrm** [comment]
I had the same issues, step2 solved it for me.

**Comment by kazunaok** [comment]
I solved this problem with the CLI update command below.
$ npm update --global @salesforce/cli
