### ISSUE TITLE
Unable to see customised managed package objects in the metadata org browser tab

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/salesforcedx-vscode#2145]
### Summary

If a user has customised an object shipped in Managed Package vscode metadata org browser should let them download that custom object.

### Steps To Reproduce:

1. Find a managed package that contains an object
2. Create a sandbox (e.g. dev sandbox off of production)
3. Install the managed package
4. Create a new field in the object in this package (such that the object has a prefix e.g. `myprefix__My_Object__c` but your NEW field does not (`myprefix__My_Object__c.Our_Field__c`)
5. Refresh 'custom objects' in metadata org browser in VS Code

### Expected result

`myprefix__My_Object__c` is listed

### Actual result

`myprefix__My_Object__c` is NOT listed

### Additional information

Workaround: create the `myprefix__My_Object__c` folder under `objects`, add the corresponding xml file (even empty), right-click -> `Retrieve source from org`.

The fact that the workaround works suggests that there is no API limitation on downloading this data, it's just the SFDX extension chooses not to show it to users.

**VS Code Version**: 
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**SFDX CLI Version**: 48.11.0

**OS and version**: macOS Catalina 10.15.3

**Comment by smaddox-sf** [comment]
Hi @az-oolloow - The org browser does not display metadata inside of managed packages because that metadata cannot be retrieved (metadata retrieve) by a subscriber.  We have an open issue on this - https://github.com/forcedotcom/salesforcedx-vscode/issues/1998.  If you get a chance, please add any other use cases you have to that issue.  I'm going to close this one as a duplicate to keep one place to track on this.

**Comment by az-oolloow** [comment]
@smaddox-sf That's very strange. How was i able to retrieve it then as described in my workaround?
