### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ajitkumar3012** [forcedotcom/salesforcedx-vscode#2146]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.11.0`
- OS Version: `Windows_NT x64 10.0.10240`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ajitkumar3012** [comment]
•Issue Type: Bug
•Extension Name: salesforcedx-vscode-core
•Extension Version: 48.11.0
•OS Version: Windows_NT x64 10.0.10240
•VSCode version:

**Comment by smaddox-sf** [comment]
Hi @ajitkumar3012 - Can you add the details of the issue you experienced along with the steps to replicate?  from the information logged, I can't tell what the problem is.
