### ISSUE TITLE
Create project Manifest failed to run 

### ISSUE THREAD

**Issue by paulineotge-31** [forcedotcom/salesforcedx-vscode#2149]
Hello everyone, 

I try to connect my Salesforce org with VS Code by starting to create a Project Manifest and move it to my desk in a empty folder created in my Desk.

I had an error message "path does not exist" 

Previously I installed the Salesforce Extension Pack and CLI Command (64bit on Windows). 

Could you help me to figure out the issue? 

Many thanks

**Comment by lcampos** [comment]
Hi @paulineotge-31 , could you provide more details on your setup (Salesforce CLI version, VSCode version, Salesforce extensions for VSCode version)?
Also, could you share the stack trace ? It would help to know the context in which you get the `path does not exist` so we can try and replicate the issue on our side.
