### ISSUE TITLE
Apex Language Server parsing order

### ISSUE THREAD

**Issue by nchursin** [forcedotcom/salesforcedx-vscode#2150]
I have a rather simple question on Apex Language Server, but I believe the community won't give me a trustworthy answer as it's related to LS behavior and roadmap.

I'm integrating to Apex LS and noticed that `documentSymbol` method always returns a result in a specific order. Let me show an example:
```
public class Test {
    public String stringVar;

    public Test(String a, Integer b) {
        
    }

    public class InnerClass {
        public String stringVar2;
        
    }

    public class InnerClass2 {
        public String stringVar3;
        
    }
    public Integer intVar;
}
```
For this class `documentSymbol` will first return symbol info in the following order:
1. Everything in `InnerClass`
2. `InnerClass` symbol info
3. Everything in `InnerClass2`
4. `InnerClass2` symbol info
5. Everything else...

I wonder can I rely on this order? Specifically, can I rely on that everything that is returned between `InnerClass2` symbol info and `InnerClass` symbol info belongs to `InnerClass2`?

**Comment by gbockus-sf** [comment]
Hi @nchursin Sorry it took so long for you to get a response on your issue.  I posted internally at Salesforce to the apex team requesting a response to your question.  I'll update when I hear back or they will update directly. Please let me know if you go the answer to your question else where.  Thanks!

**Comment by nchursin** [comment]
Hey,
I noticed this issue got closed, but I still need the answer :) any updates on this?

**Comment by gbockus-sf** [comment]
Hi @nchursin, 
Yeah sorry the issue got closed early.  I assumed it would stay open b/c you responded to my last comment.  Anyway I did some digging and believe you can depend on the ordering you called out in your original question.  The way that the classes are parsed it does each class one at a time parsing the contents of each class in a particular order (types -> (fields, methods) -> statements).  All the data structures used for this tracking are ordered so the ordering can be depended on AFAIK.  There is a sorting step but it uses the order in which the different pieces of the class are process as the comparator so I think we're good 👍 . 
Let me know if you need any more information.
