### ISSUE TITLE
Persistent 'Field does not exist' Problems When Fields Exist

### ISSUE THREAD

**Issue by mscholl67** [forcedotcom/salesforcedx-vscode#2154]
### Summary

I was trying to complete the Trailhead module "Find and Fix Bugs with Apex Replay Debugger".  When I create a new Apex class AccountService and copy the code from 'Set Up Apex Replay Debugger', I get '**Field does not exist**' for **Account.AccountNumber** and **Account.TickerSymbol**. 
I am connected to my dev org where I am a sysadmin. I have checked FLS. The fields are included in my package.xml and are in my project. I have deployed the class to my org and there are no errors in Developer Console. The only extensions I have installed in VSC are the ones that come with Salesforce Extension Pack (48.11.0) and ESLint (2.1.5). I am using jdk-11.0.7. 

### Expected result

There should be no 'Field does not exist' problems.

### Actual result

I get 'Field does not exist' problems for Account.AccountNumber and Account.TickerSymbol.

### Additional information

See attached.
![VSC Issue (2)](https://user-images.githubusercontent.com/64613905/80758758-24197680-8b04-11ea-953a-567659f9f9a0.png)
![VSC Issue (3)](https://user-images.githubusercontent.com/64613905/80758759-24b20d00-8b04-11ea-955c-94f3427ed531.png)
![VSC Issue](https://user-images.githubusercontent.com/64613905/80758760-24b20d00-8b04-11ea-8806-90473ff29df2.png)

**VS Code Version**: 1.44.2

**SFDX CLI Version**: 7.54.4-8ff9ba9cc5 Win32-x86 node-v10.15.3

**OS and version**: Windows_NT x64 10.0.18363

**Comment by mohanraj-r** [comment]
@mscholl67 Can you please check if you are able to reproduce this issue with the latest version of the extensions and the trailhead content. Are the reported issues causing any problems at runtime or with tests? If the problems please reopen the issue.
