### ISSUE TITLE
Add ToolTip to showOrg

### ISSUE THREAD

**Issue by JosephAllen** [forcedotcom/salesforcedx-vscode#2163]
The showOrg status bar item needs a tool tip. This will help developers know the purpose of the button.

`statusBarItem.tooltip = 'Open Org';`

https://github.com/forcedotcom/salesforcedx-vscode/blob/2a814ad566e2f83c22df14024802c7cb77cb3678/packages/salesforcedx-vscode-core/src/decorators/scratch-org-decorator.ts#L20

**Comment by lcampos** [comment]
Closing since this was addressed on release 48.24.0, thanks for providing feedback
