### ISSUE TITLE
Add ToolTip to SetDefaultOrg Status Bar Item

### ISSUE THREAD

**Issue by JosephAllen** [forcedotcom/salesforcedx-vscode#2164]
The constructor for OrgPicker.OrgList class needs to have a tooltip added to the SetDefaultOrg status bar item.

This would be helpful to communicate that clicking the current org name will render the org picker. This would reduce training time for new developers.

Something like: 

`this.statusBarItem.tooltip= 'Change Default Org'`;

https://github.com/forcedotcom/salesforcedx-vscode/blob/b8e23f62a869045c375b05de20827a238424e84d/packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts#L30

**Comment by lcampos** [comment]
Closing since this was addressed on release 48.24.0, thanks for providing feedback
