### ISSUE TITLE
creating lwc project in vs code

### ISSUE THREAD

**Issue by anusha-94** [forcedotcom/salesforcedx-vscode#2166]
Trying to create a project in vs code for lwc am facing this below issue.
error: 'npm' is not recognized as an internal or external command, and 
sfdx create project failed to run.

salesforce cli version currently which i have is updated version  7.56.1-2773b53bf5
and i have downloaded sfdx plugins
salesforcedx 48.0.9 (pre-release)
It would be great if i get help to solve this as i am beginner i would like to learn

**Comment by saakshig** [comment]
Check the resolution [here](https://github.com/forcedotcom/salesforcedx-vscode/issues/2175)

**Comment by lcampos** [comment]
This was fixed in the latest release of the Salesforce CLI `7.58.2`, you don't need to install node or npm.
