### ISSUE TITLE
lightning web component unresponsive

### ISSUE THREAD

**Issue by maheshbabu9999** [forcedotcom/salesforcedx-vscode#2171]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `48.13.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
I'm closing this since there's no details on how to replicate the issue. Please reopen it if you can provide steps to replicating the behavior so we can work on a fix.
