### ISSUE TITLE
Path does not exist any more on disk error while creating new project in VS code.

### ISSUE THREAD

**Issue by lkv123** [forcedotcom/salesforcedx-vscode#2187]
Hi,
I am trying to create new Salesforce project from VS code. After I select the folder, it gives me the following error. Please help me solve this issue.
![image](https://user-images.githubusercontent.com/19648086/81537329-a6b6f700-938a-11ea-8225-dbe74cb28824.png)

**Comment by lcampos** [comment]
Hi @lkv123 , does this happen when you run `SFDX: Create Project with Manifest` or `SFDX: Create Project` ? Can you provide steps we can use to replicate the issue on our side. Also, which VSCode version are using, which OS, which version of the Salesforce extensions for VSCode and Salesforce CLI.

**Comment by lkv123** [comment]
Hi @lcampos 
Yes. I am facing that issue when I create a project with `SFDX: Create Project with Manifest`. 
I am using VS code of Version 1.45 on Windows 10 and Salesforce extension Pack of version 48.15
![image](https://user-images.githubusercontent.com/19648086/82175505-ae7a1c80-98f1-11ea-8dc0-74c3bef5f6ec.png)

**Comment by mohanraj-r** [comment]
@lkv123 This could be related to https://github.com/forcedotcom/salesforcedx-vscode/issues/1874 
Can you please try this with the latest version and without any spaces in the dir path. Please reopen the issue if it still exists.
