### ISSUE TITLE
Update Language for Aura Component Commands

### ISSUE THREAD

**Issue by thombehrens** [forcedotcom/salesforcedx-vscode#2189]
**Is your feature request related to a problem? Please describe.**
The Command Palette options for creating Aura & Lightning Web Components are currently not as clear as they could be; Aura Components are referred to simply as "Lightning Components". In my opinion, this is confusing; it also means typing "Aura" into the Command Palette doesn't yield the result to create a new Aura Component.

![image](https://user-images.githubusercontent.com/16739543/81579810-9ac33900-937a-11ea-9397-1ec460266795.png)

**Describe the solution you'd like**
I'd like to submit a PR to update the language in the command labels to refer to framework elements either either as "Aura" or "Lightning Web"; never simply "Lightning". (I.e. Aura Component, Aura Interface, Aura Event, Aura App).

**Describe alternatives you've considered**
We could also update the language to refer to "Aura Lightning Components". I would love guidance from the team to see if others also consider this an intuitive update. 

**Additional context**
I've taken the guidance for referring either to "Lightning Web Components" or "Aura Components" but not "Lightning Components" from the "Coexistence and Interoperability" section of [this announcement blog post](https://developer.salesforce.com/blogs/2018/12/introducing-lightning-web-components.html).

**Comment by smaddox-sf** [comment]
Hi @thombehrens - Thanks for submitting this idea.  We'd welcome a PR on this, so feel free to submit it.  Thank you!  These names used to make sense, but a refresh would make it clearer.
