### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by VinodAnandhan** [forcedotcom/salesforcedx-vscode#2190]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.14.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
We don't have any info to understand the issue or check into it.  Please reopen this with more info if you have it.
