### ISSUE TITLE
Create Project with manifest causing error

### ISSUE THREAD

**Issue by santoshtalasu** [forcedotcom/salesforcedx-vscode#2192]
FOR BUGS RELATED TO THE SALEFORCE CLI, please use this repository: https://github.com/forcedotcom/cli
-->

### Summary

Error while Create Project with manifest

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

**SFDX CLI Version**:sfdx-cli/7.57.1-dbf54fc584 win32-x64 node-v10.15.3

**OS and version**:OS: Windows_NT x64 10.0.18363

**Comment by santoshtalasu** [comment]
Starting SFDX: Create Project

17:20:07.769 sfdx force:project:create --projectname DEVREP --outputdir d:\ --template standard --manifest
ERROR running force:project:create:  Command failed with exit code 1: npm root -g --prefix d:\.yo-repository --loglevel error
'npm' is not recognized as an internal or external command,
operable program or batch file.
17:20:09.575 sfdx force:project:create --projectname DEVREP --outputdir d:\ --template standard --manifest ended with exit code

**Comment by saakshig** [comment]
Check the resolution [here](https://github.com/forcedotcom/salesforcedx-vscode/issues/2175)

**Comment by smaddox-sf** [comment]
@saakshig and @santoshtalasu - Thanks for raising these issues.  I'm glad you have a workaround for now.  We are investigating this as you shouldn't have to install npm directly.  It is a valid workaround though.

**Comment by shinya-ochi** [comment]
@smaddox-sf @saakshig 
[vscode deprecated npm module 'vscode' in v1.45.](https://code.visualstudio.com/updates/v1_45#_deprecating-and-archiving-of-the-vscode-npm-module)
I suggest migrating 'vscode' to '@types/vscode'

**Comment by lcampos** [comment]
The fix for this was released as part of the Salesforce CLI version `7.58.2`.
