### ISSUE TITLE
Create project failed

### ISSUE THREAD

**Issue by Kanon-Jiang** [forcedotcom/salesforcedx-vscode#2194]
sfdx force:project:create --projectname Test --outputdir "D:\Work\VS Workspaces" --template standard
WARNING: apiVersion configuration overridden at "48.0"
ERROR running force:project:create:  Command failed with exit code 1: npm root -g --prefix C:\Users\Kanon\.yo-repository --loglevel error

My Salesforce CLI Version
sfdx-cli/7.57.1-dbf54fc584 win32-x64 node-v10.15.3

VS Code Version
Version: 1.44.1 (system setup)

I already re-install "VS Code" and "Salesforce CLI", but this issue still occurs.

**Comment by Kanon-Jiang** [comment]
resolved from Issue#2175

**Comment by AnanyaJha** [comment]
@Kanon-Jiang Thanks for reporting this and I'm glad you were able to find a workaround for this issue. We're actively working on this and wanted to get some more information- how did you install the Salesforce CLI, was it using this link? https://developer.salesforce.com/tools/sfdxcli

**Comment by Kanon-Jiang** [comment]
@AnanyaJha yes, 
I don't install Nodejs on my computer before yesterday. 
I did update Salesforce CLI in the day before yesterday, then I can't create a new project and occurs that error.

Yesterday, I found out the solution from the issue 2175 and installed Nodejs.
