### ISSUE TITLE
Show Output Channel for Auth Commands in Container

### ISSUE THREAD

**Issue by dehru** [forcedotcom/salesforcedx-vscode#2195]
# Summary
When the user is running vscode in a container ( like remote development with docker ), the commands for authorize a devhub and authorize an org need to display the channel output since the browser can't be launched by the CLI.  The output channel includes the information the user needs to complete their device flow login.

Currently, the output panel is there, but it is not focused like it used to be.

### Steps To Reproduce:

1.  Run vscode ( using remote development ) with the salesforce extensions installed.
1.  Use the command palette to launch Authorize a Dev Hub or Authorize an Org.

### Expected result

Salesforce CLI channel output should be focused for the user so they know there are steps they need to take.  ( copy TOKEN, Go to URL )

### Actual result
Salesforce CLI channel is not focused.  User has no idea they need to take action.

### Additional information

**VS Code Version**: Version: 1.46.0-insider
**SFDX CLI Version**: sfdx-cli/7.54.4-8ff9ba9cc5
**OS and version**: OS: Darwin x64 18.7.0

**Comment by dehru** [comment]
I'll be submitting a PR to fix this issue.

**Comment by lcampos** [comment]
Closing since this was fixed and released
