### ISSUE TITLE
Java 9 Support

### ISSUE THREAD

**Issue by fcathala** [forcedotcom/salesforcedx-vscode#220]
### Summary
_Cannot find the latest version of Java installed on my machine_.

### Steps To Reproduce:
1. Uninstall any version of Java
1. Navigate to http://www.oracle.com/technetwork/java/javase/downloads/index.html
1. Install the latest version for your OS
1. Launch VS Code

### Expected result
_VS Code opens without error message_.

### Actual result
_Receive error message: Java 8 is required to run. Download and install it from https://java.com/en/download/_.

### Additional information

_I need Java 9 and am not keen to run versions 8 and 9 side by side_.

**VS Code Version**:  1.18.1

**SFDX CLI Version**: 6.0.16-3780698

**OS and version**: macOS 10.13.1

**JRE version**: build 9+181

**Comment by guw** [comment]
dup of #139
