### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by umarTan** [forcedotcom/salesforcedx-vscode#2201]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.14.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.45.0`

:warning: ```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 9170,
		"activateCallTime": 31,
		"activateResolvedTime": 6072604,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
@umarTan - Please add info about the issue you experienced and steps to repro.  Closing this for now, but reopen if you have more info.
