### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Dmena3** [forcedotcom/salesforcedx-vscode#2202]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.15.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.45.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Dmena3** [comment]
When I open Visual Studio Code Starting SFDX: Refresh SObject Definitions automatically appears and it always runs and this commented error appears

**Comment by smaddox-sf** [comment]
@Dmena3 - Can you paste the error here that you are seeing?  

Also, when you open VS Code, do you already have a Salesforce project open?

**Comment by Dmena3** [comment]
Yes, All the commands (create, authorize ..) work but it always stays at the bottom right running Salesforce CLI without ending
![Capture](https://user-images.githubusercontent.com/54394405/82138780-5d9bf280-9823-11ea-83b2-ed68bd710ede.png)

**Comment by lcampos** [comment]
@Dmena3 if Refresh SObjects is automatically running once you open a Salesforce project I suggest you disable the `salesforcedx-vscode-apex.enable-sobject-refresh-on-startup` setting. 
The provide some context, this command will try and get the sobject definitions of most of the objects in your org, depending on your customizations it might take a bit longer.
