### ISSUE TITLE
Error on create project with manifest standard

### ISSUE THREAD

**Issue by diegohna** [forcedotcom/salesforcedx-vscode#2205]
### Summary
10:12:55.831 sfdx force:project:create --projectname SAPGEOSSA 05192020 --outputdir c:\Users\diego\Desktop\SAPGEOSSA 05192020 --template standard --manifest
ERROR running force:project:create:  Command failed with exit code 1: npm root -g --prefix c:\Users\diego\Desktop\SAPGEOSSA 05192020\.yo-repository --loglevel error
'npm' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
10:13:01.254 sfdx force:project:create --projectname SAPGEOSSA 05192020 --outputdir c:\Users\diego\Desktop\SAPGEOSSA 05192020 --template standard --manifest
 ended with exit code 1

Even when I install a pm extension the bug still happens 

### Steps To Reproduce:

1.  Create project with manifest
1.  select Standard'
1.  Create and select a new folder in any area (even desktop)

### Expected result

Creat a project with manifest 

### Actual result

ERROR running force:project:create:  Command failed with exit code 1: npm root -g --prefix 

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:1.45.1

**SFDX CLI Version**:48.15.0

**OS and version**: Win10 - 1909

**Comment by lcampos** [comment]
Hi @diegohna thanks for opening this. Looking at the stack trace you've provided I think this might be related to an issue we fixed last week in the CLI version 7.58.2. Can you verify you are using that version or above of the CLI ?

**Comment by diegohna** [comment]
![image](https://user-images.githubusercontent.com/15254999/82401597-95c45080-9a30-11ea-9b64-fd217ceb8858.png)
latest update from 5 days ago

**Comment by KodaiOrita** [comment]
Hi
I am facing a same error.
I can not make SFDC standard project and lightning component.
My version is 48.17.0.
Error message is the following.
Thank you.

16:10:56.388 sfdx force:lightning:component:create --type lwc --componentname bikeCard --outputdir force-app\main\default\lwc
ERROR running force:lightning:component:create:  Command failed with exit code 1: npm root -g --prefix c:\Users\korita\Desktop\非PJT関係\salesforcelocal\HelloWorldLightningWebComponent\.yo-repository --loglevel error
'npm' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B

**Comment by diegohna** [comment]
> Hi
> I am facing a same error.
> I can not make SFDC standard project and lightning component.
> My version is 48.17.0.
> Error message is the following.
> Thank you.
> 
> 16:10:56.388 sfdx force:lightning:component:create --type lwc --componentname bikeCard --outputdir force-app\main\default\lwc
> ERROR running force:lightning:component:create: Command failed with exit code 1: npm root -g --prefix c:\Users\korita\Desktop\非PJT関係\salesforcelocal\HelloWorldLightningWebComponent.yo-repository --loglevel error
> 'npm' �́A�����R�}���h�܂��͊O���R�}���h�A
> �����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B

I don't know if it can help you but try to update(reinstall) the Salesforce CLI.
When I have formated my pc and try to reinstall the Vscode he asked me for the latest issue and i haven't seen the error anymore.

**Comment by lcampos** [comment]
Hi @KodaiOrita , as mentioned above this was an error in the CLI and was fixed on release `7.58.2`.

**Comment by lcampos** [comment]
@diegohna thanks for confirming the fix addressed your issue, I'll go ahead and close this. Thanks again for the feedback and sorry for the disruption this caused.
