### ISSUE TITLE
SFDX commands not showing in Context menu, but only for Aura Components

### ISSUE THREAD

**Issue by saramorgan** [forcedotcom/salesforcedx-vscode#2213]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. Created a project in VS Code 
2. Have been adding Aura components and classes to it for several days.
3. This morning, I went to try and create a new Lightning Aura component, but there was no context menu. 
3. I have updated the CLI to the latest version and have NOT made any changes to VS Code, so this does not seem to match any of the other peoples issues I saw reported in bug 1196. Not sure if it is at all related.

### Expected result

I would have expected to see the context menu when right-clicking the Aura folder.

### Actual result

Even though nothing has changed with a new project I have created, I am suddenly not seeing the context commands for SFDX when trying to create an Aura component. I do still see it for creating a class or LWC though. 

### Additional information
I do have a new wrinkle to add to all this. Even though I did close and re-open VS Code twice, updated the CLI, the issue did not seem to resolve. I did however, just go to the command palette  and there were no SFDX commands there like there are normally. So, I did a search for the create lightning component and selected it. I created the component that way and now the context menu is re-appearing. Seems like a bug to me.

_Feel free to attach a screenshot_.

**VS Code Version**: Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**SFDX CLI Version**:
sfdx-cli/7.59.0-05e06e37e0 win32-x64 node-v10.15.3

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @saramorgan - Thank you for submitting this.  I'm glad you found a path that unblocked you.  We'll investigate this.

**Comment by AnanyaJha** [comment]
Hi @saramorgan! Thanks for reporting this, checking in to see if you've experienced this issue recently? We've made a number of improvements around the development experience that may have addressed this issue already. Let us know, thanks!

**Comment by saramorgan** [comment]
I have not noticed the problem in a long time, but then I honestly do not create Aura components very often any more. Thanks for checking in though.
