### ISSUE TITLE
VS Code Apex extension stops working with high CPU usage

### ISSUE THREAD

**Issue by yiliangx** [forcedotcom/salesforcedx-vscode#222]
### Summary
I have Salesforce Extensions for VS Code installed in my VS Code. Apparently whenever I start editing code (putting actual code into the class) the CPU usage for Code Helper and JAVA straight away increase to 100%, and everything in salesforcedx-vscode-apex such as code complete, check syntax, view outline stop working.

I tried disable the extension and the CPU usage became normal.

Could someone plz have a look what happened or maybe there is already a solution?

### Steps To Reproduce:
1. Open VSCode
2. Start editing code

### Expected result
CPU usage should be normal and vscode-apex functions should be able to run

### Actual result
CPU usage increased and  10 secs later all vscode-apex related function stop working

### Additional information
![image](https://user-images.githubusercontent.com/4036956/33300162-fd47cb4e-d442-11e7-86b0-31083e10cdca.png)

**VS Code Version**:
v1.18.1
**SFDX CLI Version**:
sfdx-cli/6.0.16-3780698 (darwin-x64) node-v8.6.0
**OS and version**:
macOS Sierra 10.12.6

**Comment by guw** [comment]
Is this happening to all SFDX related work you do or only with a particular project/code base?

Can you reproduce the issue with the following SFDX project on your machine?
https://github.com/forcedotcom/sfdx-simple

**Comment by guw** [comment]
I changed the title as I suspect it's Apex specific. @yiliangx Can you confirm that the SFDX commands still work in the command palette?

**Comment by yiliangx** [comment]
Hi Guys, Thanks for getting back to me so quickly.

Amazingly the issue seems gone for now (has been happening for weeks or so), however regarding the above three questions:

1. Medium size managed package with folder size 53mb . I tried dreamhouse project and it works as normal.
2. No, only one vscode instance opened
3. No, cannot replicate the issue now.

Since the issue no longer replicable Im happy to close this one, if I see the issue come back I will reopen it and provide further information.

Many thanks!!
