### ISSUE TITLE
Apex Code Coverage Updates for apex:test:run and apex:test:report commands

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/salesforcedx-vscode#2224]
### Posting this draft of planned changes for community input - 

When you run the force:apex:test:run or force:apex:test:report command, you see details about the updated code coverage in your Org.  The information displayed can be confusing - some examples of why:

* Dev Console displays the Overall Org-wide coverage along with the percent covered for each Apex class
* The CLI & VS Code, provide a granular view of the test - showing you each method and class being covered by the test you ran (not the whole org). Furthermore, the coverage percentage for specific classes in the CLI & VS Code does not always match the respective number in the Developer Console. We also calculate an aggregate “Test Run Coverage” number that has no relationship to the Overall Org-wide coverage.

We’re clarifying the code coverage info so you get consistent info no matter where you work.  We’re also simplifying so you have less info overall to process. 

Here’s our draft of the planned changes to the ***human readable*** format.  It contains 3 sections:

**SECTION 1**
![image](https://user-images.githubusercontent.com/59572234/83275769-7cd04380-a184-11ea-88ed-d7ba0af09578.png)

This shows a summary of the coverage by class:

* *Classes* - The name of the class in the Org
* *Percent* - Percentage of lines covered by tests for this class.  ApexCodeCoverageAggregate.Coverage (https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_apexcodecoverageaggregate.htm) 
* *Uncovered lines* - Lines of code in the class that aren’t covered by a test.  We will show a max of 5 and add“...“ after the 5th line number if there’s more.

**SECTION 2**
![image](https://user-images.githubusercontent.com/59572234/83275895-aa1cf180-a184-11ea-8eb9-a11a51be25b9.png)

The table provides a summary of *this* test run.  (or the last run executed if using  force:apex:test:report). Couple things to call out:

* Org Wide Coverage - [`ApexOrgWideCoverage.PercentCovered`](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_apexorgwidecoverage.htm).  This is the Overall Apex Coverage in your Org after this test has run. This is seen as the “Overall” code coverage percentage in Dev Console.
* We removed 7 values from table to streamline the view.  Goal is to reduce the clutter and give you what you need.  (Leave a comment and let us know if there’s anything you’ll miss!)

**SECTION 3**
![image](https://user-images.githubusercontent.com/59572234/83276031-dd5f8080-a184-11ea-9152-8d7196cb23bf.png)

This gives you a breakdown of all the elements in this test.  The “Class Coverage” is the percentage of the class covered by this test.  This value is from [`ApexCodeCoverage.Coverage`](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_apexcodecoverage.htm).  We’re adding this value to give you insight into how much work each test is doing.

**EXAMPLES:**
Here’s how these sections map to some example commands:

`sfdx force:apex:test:run —classnames MyTest —codecoverage —resultformat human`

* Shows sections 1 & 2

`sfdx force:apex:test:run —classnames MyTest —codecoverage --detailedcoverage —resultformat human `

* Shows sections 1, 2 & 3
* _Note: `—detailedcoverage` would be a new flag.  Name is not finalized._

`sfdx force:apex:test:report —i 707400000e4G -r human`

* Shows sections 1, 2 & 3

Related Github issues: #1630  & #1447

**Comment by jefersonchaves** [comment]
Hi @smaddox-sf: is this related to the release note [item](https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_sf_cli_code_coverage_apextests.htm) in Spring'20?

**Comment by smaddox-sf** [comment]
Hi @jefersonchaves - It's the same area.  With the update in Spring '20, we were attempting to have consistent info on Code Coverage no matter where you look.  However, we've found that it doesn't cover all cases because of the way the current Apex CLI commands work.  The spec here is to rework this area fully and close all gaps.  (and do some clean-up)

**Comment by asknet** [comment]
With this proposed changes, Do we still need to set this `SFDX_IMPROVED_CODE_COVERAGE` environment variable?

**Comment by smaddox-sf** [comment]
Hi @asknet - No, you will not need to set it.  We will be retiring that environment variable once we wrap these changes.

**Comment by suddeb** [comment]
Is this enhancement live now? my SFDX version: sfdx-cli/7.70.1-3d8a6229fc darwin-x64 node-v12.18.3. But when I am running `sfdx force:apex:test:report -i <Job#> -r human`, I am not seeing sections 1, 2 & 3. I am seeing only section 1 and 2 and  that also in different format.

**Comment by smaddox-sf** [comment]
Hi @suddeb - Thanks for reaching out!  No, these changes are not live yet.  We are working on them but it turned out to be more involved than we originally estimated.  If you have feedback on the spec above, please weigh in!

**Comment by smaddox-sf** [comment]
This has been delivered.  Check out the commands or [this recent blog](https://developer.salesforce.com/blogs/2021/04/clearer-apex-commands.html).
