### ISSUE TITLE
Command SFDX: Create Project resulted in error 'sfdx.force.projetc.create' not found

### ISSUE THREAD

**Issue by renato76** [forcedotcom/salesforcedx-vscode#2227]
Issue Type: <b>Feature Request</b>

Hi i am getting the following error when trying to create new project

Command SFDX: Create Project resulted in error 'sfdx.force.projetc.create' not found

Could you please help with this?

Many thanks

Extension version: 48.18.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

**Comment by smaddox-sf** [comment]
Have you installed the CLI?  If so, what version?  

If you haven't installed the CLI, you can find [the instructions here](https://developer.salesforce.com/tools/vscode/en/getting-started/install)

**Comment by renato76** [comment]
Good question, I really thought I had, but I shall double check, installing now. Will post an update shortly. Thank you!

**Comment by renato76** [comment]
Yes I have definitely installed thr CLI. Its still causing same errors. I think I might have to set a path somewhere, any help would be appreciated

**Comment by renato76** [comment]
I tried File - Preferences - Settings and then type "path" in search and scroll down. The settings.json seem to have incorrect paths in there for Java and Powershell


    "salesforcedx-vscode-apex.java.home": "C:\Program Files\Java",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",

}

**Comment by lcampos** [comment]
@renato76 can you verify if the CLI configuration is set like on this steps https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows ?
