### ISSUE TITLE
 I am facing some issues in integration between salesforce and VS code, sfdx commands are not showing

### ISSUE THREAD

**Issue by ashishy258** [forcedotcom/salesforcedx-vscode#2241]
### Summary

After installing the salesorce cli successfully, Vscode is still not showing the org picker in left lower bottom corner and also it didn't show the sfdx commands in command palette.

### Steps To Reproduce:

1.  installed the Vscode.
1.  installed the salesforce cli and it's extension pack.

### Expected result

The vs code should show me the org picker in lower left bottom corner and other sfdx commands in cammand pallete.

### Actual result

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/50999583/83969024-ea9a0f00-a8ea-11ea-81a4-8ef8abddac7d.PNG">
<img width="960" alt="Capture1" src="https://user-images.githubusercontent.com/50999583/83969037-02719300-a8eb-11ea-8332-152727368c2e.PNG">

### Additional information

This is the second time when this issue occured.
first time i remove vs code completely from my machine and installed it again and it worked but this time it is not working.

**VS Code Version**: 1.45.1(user setup)

**SFDX CLI Version**: 7.61.0

**OS and version**: Windows_NT x64 10.0.18363

**Comment by smaddox-sf** [comment]
Hi @ashishy258 - do you get any error message in the bottom-right corner of VSCode's footer or in the Dev Tools console (Help > Toggle Developer Tools and select the Console tab). If you do can you provide those details?

**Comment by ashishy258** [comment]
Yes, @smaddox-sf ,
These are the errors that showing in tab
![image](https://user-images.githubusercontent.com/50999583/87231687-cee8c380-c3d6-11ea-82a9-3cd50af69f87.png)
Thanks,
Ashish

**Comment by lcampos** [comment]
I haven't been able to replicate this issue. I'm thinking this could be either a configuration problem on your end or a bug on the extensions which is preventing them from getting activated. In order to check for a potential bug in the extensions, do you have a project which fails on your end that you can share with us to try and replicate the issue on our end ?
