### ISSUE TITLE
Setting to always force push

### ISSUE THREAD

**Issue by lukecotter** [forcedotcom/salesforcedx-vscode#2243]
Alot of the time we are never going to make changes directly in the org but sometimes there are still conflicts that occur. 

An option in settings to always force push via sfdx force:source:push -f (--forceoverwrite) would help avoid the prompt to retry the push with the override, saving time.

**Comment by smaddox-sf** [comment]
@lukecotter - Thanks for the taking the time to provide feedback.  Can you tell me more about the scenarios when you always want to overwrite?  

For example, do you always want to override for certain Orgs?  (such as a Scratch Org or a personal sandbox that you don't share with others)

**Comment by lukecotter** [comment]
The case I am thinking about only affect scratch orgs. I am a developer and each developer works in their own scratch org. There are a few cases where this can be helpful. 

### Always force push because local is true
Sometimes I do not care what changes I may have made in the org and for development of an entire feature, I consider only what is local to be true. If I wanted to make a change in the org and have it persist locally I would pull before pushing.

In that case I do no want to run the risk of a conflict and waste time having to push and then force push after, I would rather know it will always succeed and be the same as local.

### Issues with incorrect conflicts being reported
In the passed I seem to have had some cases where conflicts were reported when one was not expected. I can not remember specifics but I seem to remember this occurring on the second push after pushing a change to the admin profile.

Again in those cases I do not want to run the risk of hitting the conflict and I am happy the org is always overridden with what is in local.

### Sometimes on large repos the push fails
I have seen the push fail due to memory usage. In those cases force pushing has succeeded where the normal push failed. Something else that has solved this issues was deleting the org folder in the `.sfdx` folder but this takes longer on the second push than force pushing.

**Comment by lukecotter** [comment]
Generally normal push is fine there are just those few cases where I find my self going to the command line to use --forceoverwrite adding a setting to add --forceoverwrite when a file is saved would prevent me from having to go to the commandline.

**Comment by lukecotter** [comment]
closed because this has been merged and is available to use 👍🏻
