### ISSUE TITLE
Orphan java processes hanging around even after VS Code is quit

### ISSUE THREAD

**Issue by shillem** [forcedotcom/salesforcedx-vscode#2247]
### Summary

_It often happens that even after VS Code is quit a sfdx java process is left hanging around_.

### Steps To Reproduce:

_I don't have the specific steps to reproduce the issue. I have a sample of the process left behind attached_.

### Expected result

_No java processes should be left open once VS Code is quit_.

### Actual result

_One or multiple java processes pile up in the Activity Monitor_.

### Additional information:
[vscode-sfdx-java-sample.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4756366/vscode-sfdx-java-sample.txt)

**VS Code Version**: 1.45.1

**SFDX CLI Version**: 48.19.0

**OS and version**: macOS 10.15.5

**Comment by smaddox-sf** [comment]
Hi @shillem - Thanks for reaching out.  When the Apex language server starts, the Java processes are started.  The processes _should_ close when you close VS Code.  However, we have seen some cases where they linger.  The workaround for now is to kill the process manually when that happens.  We haven't been able to reliably reproduce this.  If you are able to find reproducible steps, please open a new issue!  We may look into ways that we can force better handling of these processes in the future, but it's not in our near-term roadmap.
