### ISSUE TITLE
Need clarifications

### ISSUE THREAD

**Issue by vpatryshev-sfdc** [forcedotcom/salesforcedx-vscode#2253]
**Is your feature request related to a problem? Please describe.**
Hi, I'm new to vscode, and I'm new to SFDX functionality. Now I'm reading this: [user guide](https://developer.salesforce.com/tools/vscode/en/user-guide/development-models) and I'm confused. I'm trying to create a project in package model. 

Now:
"run SFDX: Create Project. If you want to work on an existing project, choose File > Open" - what if I don't? What option do I choose? Or should I first run `sfdx force:project:create -n ...`?
Then, supose I created a project via `sfdx force:project:create -n geolocation` and opened it.
Then what? I read "In the Side Bar of the code editor, click Org Picker and this opens the Command Palette." I don't see any Org Picker. But I can of course open Command Palette via `⇧⌘P` - I actually just did it (having to google what is it, "Command Palette").

Then I see "Run SFDX: Authorize an Org." Ok, I click it. Silence, I have to enter something somewhere. And then I'm lost.

(And sorry about all this, I'd just have sent you a PR if I know how to resolve this.)

**Describe the solution you'd like**
Please address complete noobs like me.

**Describe alternatives you've considered**
Or just provide links to the documents that tell me what to do.

**Additional context**
I'm a new guy in work.com team. Came here from Einstein team, which was basically totally disconnected from SFDC dev process.

**Comment by smaddox-sf** [comment]
Hi @vpatryshev-sfdc - There's a couple other resources that can help you get started:

 - VS Code overview - VS Code itself has a lot of [great resources in their doc](https://code.visualstudio.com/docs#vscode).  We also recently released [this blog post that gives a good rundown](https://developer.salesforce.com/blogs/2020/05/productive-development-with-visual-studio-code.html).  

 - Check out [this Quickstart trail](https://trailhead.salesforce.com/content/learn/projects/quickstart-vscode-salesforce) to walk through the setup steps.   

Thanks for the feedback.  We'll look at ways we can better surface resources so they are easier to find.
