### ISSUE TITLE
Cannot run SFDX: Create Project command

### ISSUE THREAD

**Issue by HarshitRochiramani** [forcedotcom/salesforcedx-vscode#2254]
### Summary

I am trying to create a new project but when i click ctrl + Shift + P 
nothing happens

### Steps To Reproduce:

1.  Click ctrl + shift + P

### Expected result

popup for selecting project type should open

### Actual result

Activating Extension and nothing happened

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.46.0
**SFDX CLI Version**:
7.61.0-af69066d0d
**OS and version**:
Windows 10

**Comment by smaddox-sf** [comment]
Hi @HarshitRochiramani - Thanks for reaching out.  Does the Command Palette ever come up in VS Code?  Instead of the keystrokes, you can also go to View -> Command Palette.  The Command Palette is universal in VS Code so it should come up regardless of whether you are using Salesforce extensions, other extensions or even no extensions at all.  Do you see the command palette open in any cases?  Is this your first time using VS Code?

**Comment by HarshitRochiramani** [comment]
Hi, Actually I'am not talking about the command palette,
When I press ctrl + P -> Command Palette appears,
then I type >SFDX: Create Project and hit enter
After that it says Activating Extension and nothing happens. It is not creating project !

I have installed CLI and EXTENSION Pack as mentioned in the earlier comment.

**Comment by smaddox-sf** [comment]
Thanks for clarifying @HarshitRochiramani .  Do you get any error message in the bottom-right corner of VSCode's footer or in the Dev Tools console (Help > Toggle Developer Tools and select the Console tab).  If you do see an error, can you provide those details?

**Comment by HarshitRochiramani** [comment]
![image](https://user-images.githubusercontent.com/43925044/86561752-faa31e00-bf7e-11ea-9d78-dcb2eb8ce056.png)
Attached the screenshot.

**Comment by lcampos** [comment]
@HarshitRochiramani how did you install the CLI, using npm or the installers ? The error in that screenshot is saying the CLI can't be found/reached by VSCode. 
Also, have you seen this troubleshooting doc [Set Salesforce CLI Path](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)
