### ISSUE TITLE
Using SFDX : Deploy this Source to Org in Visual Studio Code opens node.exe window and doesn't return errors Output to 

### ISSUE THREAD

**Issue by taalgaard** [forcedotcom/salesforcedx-vscode#2256]
### Summary

Using SFDX : Deploy this Source to Org in Visual Studio Code opens node.exe window and doesn't return errors Output to 

### Steps To Reproduce:

Right click in the middle of a .cls file and select SFDX : Deploy this Source to Org

### Expected result

No node.exe window should appear.
OUTPUT should show errors and not just  "ended with exit code 1"

### Actual result

When SFDX : Deploy this Source to Org is selected on a file a new external command window opens with node.exe in the details.  It goes away but the error is not shown in the OUTPUT windows of Visual Studio Code like it used to.

### Additional information

Our sandbox instances were just switched to Summer 20 this past weekend.

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/10553973/84434077-f93b3b80-abf4-11ea-94e5-7c816e6bb066.png)

**VS Code Version**:

Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**SFDX CLI Version**:

sfdx-cli/7.60.0-e2bb2907cb win32-x64 node-v10.15.3

**OS and version**:

Windows 10
10.0.17134 Build 17134

**Comment by taalgaard** [comment]
I performed and upgrade of sfdx after submitting this bug and receive the same results of node.js creating a popup window that doesn't return the response back to Visual Studio Codes Output window/panel.

sfdx-cli: Updating CLI from 7.60.0-e2bb2907cb to 7.62.1-309fe6da17

**Comment by ravibarnwal** [comment]
I am also facing same type issue. for me nothing is showing. attached screenshot of about VS Code.
I tried with uninstall vscode, sfdc cli and installed again both but this issue still persists.

![image](https://user-images.githubusercontent.com/7465670/85312678-caff0b00-b4d4-11ea-8068-26b6c2ac2b5c.png)

**Comment by lcampos** [comment]
Thanks for opening this issue. I haven't been able to replicate this on my side with a similar setup so I'm wondering if you did any other configuration in the project or vscode which I'm missing.

Also, do you get a similar experience when you run the command directly in the command line ?

**Comment by taalgaard** [comment]
If I run from command prompt in Windows it does not open up another window.

On Jun 23, 2020, at 9:28 PM, lcampos <notifications@github.com> wrote:

﻿
Thanks for opening this issue. I haven't been able to replicate this on my side with a similar setup so I'm wondering if you did any other configuration in the project or vscode which I'm missing.

Also, do you get a similar experience when you run the command directly in the command line ?

**Comment by ravibarnwal** [comment]
I didn't change any configuration. VS Code got updated then problem occurred. After getting issue I have uninstall VS Code , SFDX CLI and again installed from scratch and created new project but error persist. I have tried with different version old and latest but issue does persist.  I tried on two different system and getting same. Please let me know if you need more information.


OS Name:	Microsoft Windows 10 Home
Version:   	10.0.18363 Build 18363
SFDX:               sfdx-cli/7.63.0-c897e8bb1a win32-x64 node-v10.20.1



![image](https://user-images.githubusercontent.com/7465670/85883032-eed88e80-b7fd-11ea-825a-d00e3d28b253.png)

**Comment by taalgaard** [comment]
I found the following in the Settings in Visual Studio and enabled it

Salesforcedx-vscode-core > Experimental: Deploy Retrieve

if editing the setting file outside in text mode

"salesforcedx-vscode-core.experimental.deployRetrieve": true

This is working for me and I am now getting the success and errors again from the code deployments.  I will use this until it no longer works.

**Comment by ravibarnwal** [comment]
I tried above setting but issue is still persist .

**Comment by mohanraj-r** [comment]
@ravibarnwal We are now using a different mechanism to deploy the source that doesn't spin up a node process. Can you please check with the latest version of the extensions and reopen this issue if it still exists.
