### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by lsateeshk** [forcedotcom/salesforcedx-vscode#2259]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `48.20.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lsateeshk** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 21211,
		"activateCallTime": 79,
		"activateResolvedTime": 11609,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex-replay-debugger",
				"_lower": "salesforce.salesforcedx-vscode-apex-replay-debugger"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
Hi @lsateeshk - From the info you posted, I'm not clear on what the issue was.  Can you add details of the steps you were taking and what results you saw?
