### ISSUE TITLE
More apex snippets

### ISSUE THREAD

**Issue by lukecotter** [forcedotcom/salesforcedx-vscode#2261]
More useful apex snippets.

| Snippet                 | Description                            |
| ----------------------- | -------------------------------------- |
| `foreach`               | For-each loop                          |
| `formap`                | For loop for entries in a map          |
| `ifelse`                | if/else statement                      |
| `ifnull`                | if statement null check                |
| `ifnotnull`             | if statement not null check            |
| `ter`                   | x ? y : z                              |
| `constructor`           | New constructor                        |
| `newobj`                | New Object                             |
| `field`                 | New field                              |
| `method`                | New method                             |
| `staticmethod`          | New static method                      |
| `setidsfromrecordlist`  | Set of Ids from List of records        |
| `mapfromrecordlist`     | Map from List of records               |
| `sobjecttype`           | SObjectType for SObject                |
| `describesobjectresult` | DescribeSObjectResult for SObjectType  |
| `sobjectfield`          | SObjectField for SObject Field         |
| `describefieldresult`   | DescribeFieldResult for SObject Field  |
| `sysdebug`              | Debug Statement                        |
| `sysassf`               | System.assert(false, message);         |
| `sysasseq`              | System.assertEquals(expected, actual); |
| `sysassnull`            | System.assertEquals(null, actual);     |
| `sysassnotnull`         | System.assertNotEqual(null, actual);   |
| `testmethod`            | Test method                            |

**Comment by lcampos** [comment]
Closing since this was released as part of 48.23.0

**Comment by sc5148** [comment]
@lukecotter Foreach, Sysdebug, sobjecttype, sobjectfield, describesobjectresult and describefieldresult doesn't show up for me.

**Comment by lukecotter** [comment]
> @lukecotter Foreach, Sysdebug, sobjecttype, sobjectfield, describesobjectresult and describefieldresult doesn't show up for me.

Yeah you're right. I ended up changing the syntax of the existing for loop and sysdebug existed as debug and I didn't end up adding the describe methods.

I'll update the table.
