### ISSUE TITLE
Running the VS Code Command "Authorize a Dev Hub" does not allow for naming an org alias

### ISSUE THREAD

**Issue by gmpmovies** [forcedotcom/salesforcedx-vscode#2278]
### Summary

_This has been happing somewhat recently, but before, when authorizing a DevHub, I've been prompted to add an org alias as well. Now as of a few days ago, it completely skips that prompt and goes straight to authorizing the Dev Hub._.

### Steps To Reproduce:

1.  (On a Mac) Click Cmd->Shift->P to pull up the SFDX commands
1.  Click on "Authorize a Dev Hub"

### Expected result

_It was expected that a prompt would be displayed to enter the org alias_.

### Actual result

_Instead I am automatically redirected to authorizing the Dev Hub and the alias is left blank_.

### Additional information

**VS Code Version**: 1.46.0

**SFDX CLI Version**: 7.62.1

**OS and version**: Mac OS Catalina 10.15.5

**Salesforce Extension Pack**: 48.20.0

**Comment by andruts** [comment]
I would like to do this if that's okay.

**Comment by gbockus-sf** [comment]
@AnanyaJha Are you good with us merging this change?

**Comment by AnanyaJha** [comment]
Hi @gbockus-sf - yup change looks good to me :shipit:
