### ISSUE TITLE
Deploy on Save fails with no Error Message!

### ISSUE THREAD

**Issue by reddydev2018** [forcedotcom/salesforcedx-vscode#2281]
Deploy on Save used to work all fine, until I started getting this issue where it says Deploy failed but with no Error message. This seems to be weird, not sure how to get through this as I can't edit the code from any other place except VS Code! Any help is much appreciated - Thanks!

<img width="1120" alt="Screen Shot 2020-06-20 at 5 01 38 PM" src="https://user-images.githubusercontent.com/39275926/85211511-18824900-b318-11ea-988c-a91b53f008a5.png">

**Comment by brpowell** [comment]
Hi @reddydev2018. Can you try disabling the deploy/retrieve enhancement setting and see if you get the errors for the component?

**Comment by reddydev2018** [comment]
Hi Bryan - Sorry for the delay in response. Yeah I tried with that option is well be I am still seeing the same issue (Attached the screenshot) and even with the RightClick-->Deploy This Source to Org I am getting same issue. I am currently using 'SFDX force:source:deploy -p path to file' to make my life easy but I personally don't like to use CLI and in this case I don't have any other options left to choose :)

<img width="1438" alt="Screen Shot 2020-06-23 at 1 59 07 AM" src="https://user-images.githubusercontent.com/39275926/85366944-5210ab00-b4f6-11ea-916f-6ccb4d44c006.png">

**Comment by lcampos** [comment]
Hi @reddydev2018, we found a scenario where the errors are not shown and have a fix for it but we're not sure it's the same issue you're running into. When you switched back to using the CLI were you able to get any details on the deploy error for that component ?

**Comment by reddydev2018** [comment]
Hi @lcampos - Yes when I tried using CLI I was able to view the detailed error for the Component that I am trying to deploy on save. Also I observed that its not common with all the Components, it is just happening on random ones and some of them are working fine with deploy on save and I have no clue why is it behaving like that!

**Comment by taalgaard** [comment]
@lcampos I wonder if your issue and my issue are the same?

https://github.com/forcedotcom/salesforcedx-vscode/issues/2256#issuecomment-648544065

**Comment by lcampos** [comment]
@reddydev2018 in version 48.23.0 we released a fix for showing error messages that we were missing in certain scenarios. If you are still able to replicate the deploy failure on your side can you let us know if the new version addresses the error messages not showing ?

**Comment by lcampos** [comment]
@taalgaard did you turn on the performance enhancements beta feature ?

**Comment by taalgaard** [comment]
@lcampos I enabled the following

Salesforcedx-vscode-core > Experimental: Deploy Retrieve
Enable performance enhancements to the deploy/retreive experience.

**Comment by lcampos** [comment]
The last set of fixes for this issue have been released as part of 48.24.0, thanks for the feedback @reddydev2018 .

@taalgaard let's keep the other conversation on issue 2256 in the other thread since it's unrelated to this one.
