### ISSUE TITLE
In VsCode while running "SFDX: Retrieve Source in Manifest from Org" command, running into error creating package.xml

### ISSUE THREAD

**Issue by coolsai81** [forcedotcom/salesforcedx-vscode#2282]
On package xml if i select "SFDX: Retrieve Source in Manifest from Org" command running into below error.

Error creating package.xml. ShellJSInternalError: EINVAL: invalid argument, mkdir 'C:\Users\skrishna\AppData\Local\Temp\.sfdx\tools\conflicts\https:'

But retrieving an individual file is working fine.
Can you please help me to fix this. I am not able to fetch new orgs because of this.

**Comment by lcampos** [comment]
Hi @coolsai81, thanks for opening this issue. Based on that stack trace you provided it looks like you are running into an issue with the [Detect Conflicts](https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts/) feature. Can you confirm if the error goes away when you disable that feature (uncheck Detect Conflicts At Sync under Salesforce Feature Previews).

I haven't been able to replicate the issue on my side yet so if you can provide more details about your setup we can work on the fix sooner.

**Comment by coolsai81** [comment]
Defect conflict feature was causing this issue. After disabling that feature. it has worked.
Thank you @lcampos .

**Comment by lcampos** [comment]
cc @rcoringrato-sfdc

**Comment by mohanraj-r** [comment]
@coolsai81 The conflict detection mechanism has been improved recently. Can you please check if this issue is still reproducible and reopen the issue if it does.
