### ISSUE TITLE
Starting Local Development Server in VSCode with Powershell on Windows 10 causes encoding issues

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/salesforcedx-vscode#2284]
### Summary

Starting Local Development Server in VSCode with Powershell on Windows 10 causes encoding issues. This doesn't happen using the power shell window on its own

### Steps To Reproduce:

Windows 10, use VSCode with power shell 7.0.2.

### Expected result

Dialog window to open correct localhost url

### Actual result

Tries to open http://localhost:3333[22m[39m/

### Additional information

_Feel free to attach a screenshot_.

![image](https://user-images.githubusercontent.com/37187888/85307212-3ca76c80-b475-11ea-8d02-e904e42bdcb9.png)

**VS Code Version**:

Latest

**SFDX CLI Version**:

Latest

**OS and version**:

Windows 10

**Comment by lcampos** [comment]
Thanks for opening this issue @MGarfOppLoans. We have a fix under review and will ship it in the next release of the extensions.

**Comment by MGarfOppLoans** [comment]
Great to hear!

**Comment by lcampos** [comment]
I'm closing this since the fix was released as part of version 48.23.0. @MGarfOppLoans thanks for providing feedback.
