### ISSUE TITLE
VS code codespace not able to authorize org

### ISSUE THREAD

**Issue by msreekm** [forcedotcom/salesforcedx-vscode#2289]
when youn run sfdx force:auth:web:login --setalias xxxx --instanceurl https://test.salesforce.com --setdefaultusername in vscode online/workspace, browser window does not open, how do you login in vscode codespace? anyone tried?

**Comment by praksb** [comment]
@msreekm you need to use device flow to authenticate in Codespaces.force:auth:device:login  https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_auth.htm.

**Comment by msreekm** [comment]
@praksb  ,thanks that worked!

**Comment by msreekm** [comment]
for sandbox , sfdx force:auth:device:login  -r https://test.salesforce.com

**Comment by praksb** [comment]
@msreekm Good to know that is resolved. I am closing this issue then.

**Comment by R0Wi** [comment]
If anyone else is facing this issue: for me it helped to set the env variable `SFDX_CONTAINER_MODE=true` in my Codespace. This will execute the login via [`ForceAuthWebLoginContainerExecutor`](https://github.com/forcedotcom/salesforcedx-vscode/blob/41a0986d2a1c195c3cdb5c77150258fca1babb65/packages/salesforcedx-vscode-core/src/commands/auth/forceAuthWebLogin.ts#L240C38-L240C38), which executes the login via [Device Login Flow](https://github.com/forcedotcom/salesforcedx-vscode/blob/41a0986d2a1c195c3cdb5c77150258fca1babb65/packages/salesforcedx-vscode-core/src/commands/auth/forceAuthWebLogin.ts#L59).

See also [this PR](https://github.com/forcedotcom/salesforcedx-vscode/pull/1448/files#diff-66aefb59f6ca41ea9bcf27a120721522737a4396299f6e64cb6299cb10646136R35).
