### ISSUE TITLE
Unexpected argument running Apex tests

### ISSUE THREAD

**Issue by Guitarbum722** [forcedotcom/salesforcedx-vscode#229]
### Summary
When executing `SFDX: Invoke Apex Tests` from the VSCode Command bar, the following command is invoked:
`sfdx force:apex:test:run --classnames ClassNameTest --resultformat human --synchronous`

There is an error ` !    Unexpected argument --synchronous` because --synchronous is not a valid argument.

### Steps To Reproduce:
1. Run "Invoke Apex Tests
2. Failure
3. Execute command in shell without `--synchronous` flag with success.

### Expected result
Test for single test class should run successfully.

### Actual result
Invalid Argument error.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.18.1

**SFDX CLI Version**: sfdx-cli/6.0.14-2af879b

**OS and version**: Windows 10 1703

**Comment by DatGuyJonathan** [comment]
@Guitarbum722 , could you show the output of `sfdx plugins --core`?

**Comment by vazexqi** [comment]
@Guitarbum722 - The command invokes the CLI directly. I think you have an older version of the CLI.

Here's what I have when I do `sfdx force:apex:test:run -h` and I see --synchronous there.

```

nchen@nchen-ltm3:~|⇒                      14:06:59
Usage: sfdx force:apex:test:run (-n <string>... | -s <string>...) [-c] [-d <directory>] [-l <string>] [-r <string>] [-y] [-u <string>] [--json] [--loglevel <string>] [--verbose]

invoke Apex tests

Flags:
 -n, --classnames CLASSNAMES          comma-separated list of Apex test class names to execute
 -c, --codecoverage                   retrieve code coverage results
 -d, --outputdir OUTPUTDIR            directory to store test run files
 -r, --resultformat RESULTFORMAT      test result format emitted to stdout; --json flag overrides this parameter (human*,tap,junit,json)
 -s, --suitenames SUITENAMES          comma-separated list of Apex test suite names to execute
 -y, --synchronous                    run tests from a single class synchronously
 -u, --targetusername TARGETUSERNAME  username or alias for the target org; overrides default target org
 -l, --testlevel TESTLEVEL            testlevel enum value (RunLocalTests,RunAllTestsInOrg,RunSpecifiedTests)
 --json                               format output as json
 --loglevel LOGLEVEL                  logging level for this command invocation (error*,trace,debug,info,warn,fatal)
 --verbose                            display Apex test processing details

By default, runs all Apex tests in the org’s namespace.
To run specific tests, specify the class names or suite names or set a --testlevel value.

Examples:
   $ sfdx force:apex:test:run
   $ sfdx force:apex:test:run -n MyClassTest,MyOtherClassTest -r human
   $ sfdx force:apex:test:run -s MySuite,MyOtherSuite -c --json
   $ sfdx force:apex:test:run -l RunLocalTests -d <path to outputdir> -u me@my.org
```

What version of the SFDX CLI do you have?

```
nchen@nchen-ltm3:~|⇒  sfdx -v                                         
sfdx-cli/6.0.16-3780698 alpha (darwin-x64) node-v8.6.0
nchen@nchen-ltm3:~|⇒  sfdx plugins --core
...
```

**Comment by Guitarbum722** [comment]
@vazexqi looks like I had a slightly older version of the CLI.  Thanks for the quick response.  All set!
