### ISSUE TITLE
Authorizing a Dev Org is redirecting me to 'localhost' and preventing authorization.

### ISSUE THREAD

**Issue by gmpmovies** [forcedotcom/salesforcedx-vscode#2292]
### Summary

I am trying to authorize a Dev org through VS code, every time I attempt to authorize, I am sent to the Salesforce login page like normal and I enter my username and password, however instead of authenticating I am sent to this localhost address: `http://localhost:1717/OauthRedirect?code=12345&state=12345` (the actual url parameters have been redacted).
### Steps To Reproduce:

1.  From VS Code I hit Command -> Shift -> P and Click "SFDX: Authorize an Org"
1.  I then click "Custom" for the url and input `https://na111.lightning.force.com/` as my dev org url
1.  I use the login and password for the org to login, and the oauth redirect begins to occur.
1.  Instead of authenticating successfully, it fails because I'm redirected to my localhost.

### Expected result

_I expected the dev org to fully authorize and login_.

### Actual result

_Instead I get redirected to my `localhost` and the authorization fails_.

### Additional information

**VS Code Version**: 1.46.1

**SFDX CLI Version**: 7.62.1

**OS and version**: Mac OS Catalina 10.15.5

**Salesforce Extension Pack**: 48.21.0

**Comment by smaddox-sf** [comment]
Hi @gmpmovies - Thanks for logging this.  Can you share what you see in the Output panel when this happen?  As a part of the login process, there is a redirect to the localhost so that isn't an issue per se.  Since it isn't authenticating you in, there's some error that should be reported.
