### ISSUE TITLE
Not able to retrieve profiles anymore.

### ISSUE THREAD

**Issue by lsandhu-deloitte** [forcedotcom/salesforcedx-vscode#2294]
### Summary
Problem with retrieving the profiles by retrieving full project.

Generally, if someone wants to download profile XMLs, one has to just click on the "force-app" folder (default project folder) and retrieve the full project source. This would also retrieve the profile in the correct format. It fetched the XML details related to only the components in the source. 
eg : If Account object is present and Case is not present in the source, only FLS and object permission related to Account was retrieved.

This makes handling profiles a breeze.
Now when one tries to retrieve the full project, the VS code doesn't do anything.

### Steps To Reproduce:

1.  Goto the main folder of the project.
2. Right click and click "SFDX -  Retrieve source from the org"

### Expected result

The VS code will show "Running Retrieve source from org".
Full source code along with profiles are retrieved with complete (depending upon the existing component in the source) XMLs

### Actual result

Nothing happens.

### Additional information

This was observed last working on 24 June 2020.
Retrieving individual components is working fine but this doesn't help with retrieving profiles.
The project in question was created without manifest.

**VS Code Version**:
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**SFDX CLI Version**:
sfdx-cli/7.63.0 darwin-x64 node-v12.18.0

**OS and version**:
macOS Catalina 10.15.5 (19F101)

**Comment by smaddox-sf** [comment]
Hi @lsandhu-deloitte - Thanks for reaching out.  Question on the profiles - when you were successfully retrieving them before, did you already have a version of the profile locally?  

To clarify the expected behavior, right clicking on the classes folder in your local project and selecting "Retrieve Source from Org" will not retrieve new classes or new profiles - it retrieves updated versions of the classes already in your local project under that folder. That was how it was designed but we acknowledge how that might be confusing.

**Comment by lsandhu-deloitte** [comment]
Hi @smaddox-sf 

Yes, the profiles were already present.
Use case is, if someone created a new custom objects and wants to add FLS, object permissions, tabs and layouts to the profiles.
Step 1. Add the metadata components like object etc to the project using "org browser" 
Step 2. Click on the force-app folder (top-most folders of the project) ""SFDX - Retrieve source from the org"

Expected result : 
VS Code refreshes the project including the profiles and XMLs changes related to the new object are present in the profile.
Actual result : 
Nothing happens.

It was working before but suddenly stopped recently.

**Comment by lsandhu-deloitte** [comment]
Hi 

It is working again.
Right clicking on the default source folder and retrieving source from org refresh profiles along with rest of the source which retrieve profiles with all the needed XMLs.
In the background following command is executed.
"sfdx force:source:retrieve --sourcepath force-app/main/default"
Someone can run the command manually in the terminal, if the right click and retrieving is not working.
