### ISSUE TITLE
New LWC not available in app/experience builder after experimental deploy

### ISSUE THREAD

**Issue by ringdal** [forcedotcom/salesforcedx-vscode#2302]
### Summary

New lightning web components deployed using the experimental deploy option are not listed in the lightning app builder component list or in experience builder. 

### Steps To Reproduce:

1. Enable Experimental: Deploy Retrieve option in vscode  
1. Create a new lightning web component locally
1. Right-click "deploy this source to org" and deploy to a sandbox or production org
1. Open the component tab in Lightning App Builder while editing a page referenced in targets.

### Expected result

The new component should be visible under Custom Components

### Actual result

The component is not visible 

### Additional information

By downloading the component from the sandbox to another development computer, and redeploying the exact code without the experimental flag, the component appears. Disabling the flag and redeploying also works. Editing existing components with the experimental flag works fine.

_Feel free to attach a screenshot_.

**VS Code Version**: 1.46.1

**SFDX CLI Version**: sfdx-cli/7.63.0

**OS and version**: Tested on both Windows 10 20.04 and Ubuntu 20.04 (wsl)

**Comment by smaddox-sf** [comment]
Hi @ringdal - Thanks for logging this.  I'm glad you are unblocked.  We'll investigate this to get it resolved.

And thank you for trying out the performance enhancements!

**Comment by sfsholden** [comment]
Closing - this no longer appears to be an issue.

1. Created a Lightning Web Component locally.
2. Added the following values to the `.js-meta.xml` file:
`    <isExposed>true</isExposed>
    <targets>
        <target>lightning__AppPage</target>
        <target>lightning__RecordPage</target>
        <target>lightning__HomePage</target>
    </targets>`
3. Deployed with `Experimental: Deploy Retrieve` enabled.
4. Confirmed that the new component was available within the Lightning App Builder.
![LightningAppBuilder_CustomComponents](https://user-images.githubusercontent.com/45604118/110667348-63364080-8187-11eb-9591-e758f7c6feea.png)

Please let us know if this issue persists. Thank you!
