### ISSUE TITLE
Unable to Retrieve all custom Objects

### ISSUE THREAD

**Issue by vishnusundar2607** [forcedotcom/salesforcedx-vscode#2307]
I tried Org Browser to retrieve all custom objects in my org . retrieve Failed and shows below error 

**The command line is too long.**

It could be better if we are able to download all custom Object from org browser itself
![image](https://user-images.githubusercontent.com/47806185/86194934-67787b80-bb6d-11ea-9c38-4adf037be349.png)

![image](https://user-images.githubusercontent.com/47806185/86194969-82e38680-bb6d-11ea-8782-e87eea17be77.png)

**Comment by lcampos** [comment]
Hi @vishnusundar2607 thanks for logging this. I think what you are running into is a limitation on the length of the arguments accepted by the CLI, the Org Browser currently uses that in the background. We're working on some changes that will address this limitation but for now I suggest you retrieve with a package.xml or try to download a lower number of files at once in the Org Browser.

**Comment by vishnusundar2607** [comment]
Yes i have used the package.xml to retrieve the source. Hope it will be fixed soon ..

**Comment by AnanyaJha** [comment]
Hi @vishnusundar2607. We've updated how we retrieve objects behind the scenes for the Org Browser - can you tell us if you're still running into this issue?
