### ISSUE TITLE
CLI extension doesn't detect DX project in current folder

### ISSUE THREAD

**Issue by sunandini01** [forcedotcom/salesforcedx-vscode#2308]
Issue Type: <b>Bug</b>

After working on a folder, when we move a level out in the directory and come back, even though the project is visible, it doesn't detect the DX project. Command pallette only suggests options related to creating new project, but nothing to reset default org or similar options.

Extension version: 48.21.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.93GB (7.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by smaddox-sf** [comment]
HI @sunandini01 - Thanks for reaching out.  Can you provide the steps to reproduce the issue you're seeing?  We aren't quite sure what you're describing.

**Comment by sunandini01** [comment]
Sorry. This issue is on and off. I don't see it happening today. I made sure my cli is updated always but at times, the plugins take longer in the IDE to load.
