### ISSUE TITLE
SFDX: Retrieve Source in Manifest from Org not available anymore

### ISSUE THREAD

**Issue by gavignon** [forcedotcom/salesforcedx-vscode#2311]
### Summary

The context menu SFDX: Retrieve Source in Manifest from Org is not available anymore when right-clicking on the package.xml file since VSCode upgrade (and Dev Org reauthorization)

### Steps To Reproduce:

1.  Right-click on Package.xml file
2.  The context menu SFDX: Retrieve Source in Manifest from Org  is not displayed

### Expected result

The context menu SFDX: Retrieve Source in Manifest from Org is displayed.

### Actual result

The context menu SFDX: Retrieve Source in Manifest from Org  is not displayed

### Additional information

![image](https://user-images.githubusercontent.com/15981196/86343365-28275900-bc59-11ea-9d72-44b51d951164.png)

**VS Code Version**: 1.46.1

**SFDX CLI Version**: sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**OS and version**: MacOS Catalina 10.15.3

**Comment by smaddox-sf** [comment]
Hi @gavignon - Thanks for logging this.  When you created this project, what command did you use?  `Create Project` or `Create Project with Manifest`?  We aren't able to reproduce this so any other context you can provide would be helpful.

**Comment by gavignon** [comment]
Hi @smaddox-sf 
I'm using the `Create Project with Manifest` command.
I can still reproduce on my side for every new project created: [You can find the video here](https://we.tl/t-uNkofvInfl)

Thanks for your help!

**Comment by amphro** [comment]
I also just ran into this issue. It seems like it disappears for me when I set a scratch org as the default. If I set a different org as the default (like the dev hub) it starts appearing again. If that really is the limitation, it should be removed since `source:retrieve` can technically be used with scratch orgs (although users beware, it will mess up source tracking information).

**Comment by AnanyaJha** [comment]
Hi @gavignon! Thanks for reporting this, checking in to see if you've experienced this issue recently? We've made a number of improvements around the retrieve experience that may have addressed this issue already. Let us know, thanks!

**Comment by gavignon** [comment]
Hi @AnanyaJha 
Since I changed my laptop and have a new setup (5 months), I didn’t have this issue yet so I think we can consider it as fixed for now! I’ll reopen it if I experience it again in the future.
Thanks for the update!
