### ISSUE TITLE
Support For Quick Suggestions Autocomplete/IntelliSense

### ISSUE THREAD

**Issue by Lukargo** [forcedotcom/salesforcedx-vscode#2322]
Currently when writing a LWC, to get autocompletion/IntelliSense to show up in the html file, you need to hit Control + Space. The IntelliSense is great once you hit that, but it'd be much faster (and an easier transition for our team from IntelliJ) if there was an option for that to just autotrigger as you type.

Researching this a bit, it seems like the VS Code setting of:

 `"editor.quickSuggestions": {
        "other": true
    },`

Is on the right track, but that doesn't seem to do anything for me in the html file. Curious if you have more insight into this and if support for this can be enabled for this plugin.

**Comment by lcampos** [comment]
A fix for this was released as part of version 50.1.0 of the extensions. Thanks for providing feedback @Lukargo
