### ISSUE TITLE
Stuck when creating Salesforce project

### ISSUE THREAD

**Issue by Debiprasad-Gyansys** [forcedotcom/salesforcedx-vscode#2326]
When I am trying to create a project with command "SFDX: create a project with manifest" it's stuck in loading and it does not show anything if it's completed or not. Please find this issue and let me know when it's fixed by your side.
 Salesforce Extension pack v48.23.0.
VS code version- 1.46.1

**Comment by smaddox-sf** [comment]
Duplicate #2332
