### ISSUE TITLE
Any plans to bring --usetoolingapi option to force:source:deploy command?

### ISSUE THREAD

**Issue by fcorvelo** [forcedotcom/salesforcedx-vscode#2335]
Hello,

I've been using the **force:source:deploy** command in vscode to deploy apex classes to a normal (non-scratch) sandbox. It works fine, but I would prefer to save the apex classes using the Tooling API rather than the Metadata API. 

The reason for this is that the Metadata API leaves a huge track of every little save that I do in the "Deployment Status" setup page, which makes it difficult to spot real deployments (other than the code saves done by the developers in vscode). And some times the deployments stay pending for a long time and I can't save anything else until that pending deployment finishes.

In the past I was using other non-official Salesforce extensions to save apex, which were using the Tooling API so save the code, and it felt much faster.

I see that there are already other commands in sfdx that support the option **--usetoolingapi**, so are there any plans to bring this option to the **force:source:deploy** command as well?

Thanks.

**Comment by lcampos** [comment]
Thanks for opening this @fcorvelo . We do not have any plans to support deploying with the Tooling API in the Salesforce CLI. However, we are working on deploys/retrieves in the extensions not going through the CLI and we currently do support deploying/retrieving via Tooling API. You can enable this beta feature by following [Performance Enhancements](https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements)
