### ISSUE TITLE
 Out of Memory when retrieving source in manifest with Conflict Detection

### ISSUE THREAD

**Issue by adityababbar** [forcedotcom/salesforcedx-vscode#2341]
VisualStudio : Salesforce CLI Extension : V8 engine Out of Memory when retrieving source in manifest (package.json) from org.

### Summary

Getting the following errors when I "Retrieve source in manifest from org".

13:03:52.531 sfdx force:mdapi:convert --rootdir C:\Users\*****~1.*****\AppData\Local\Temp\.sfdx\tools\conflicts\*********\unpackaged --outputdir C:\Users\*****~1.*****\AppData\Local\Temp\.sfdx\tools\conflicts\*********\converted
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF795AB87DA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF795A93246 node::MakeCallback+4534
 3: 00007FF795A93BC0 node_module_register+2032
 4: 00007FF795DB1A4E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF795DB197F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF795F98174 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF795F8F156 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF795F8D7AC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF795F964F7 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF795F96576 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF7960C0817 v8::internal::Factory::NewFillerObject+55
12: 00007FF79613DA06 v8::internal::operator<<+73494
13: 00000272F3DDC5C1 
13:15:06.580 sfdx force:mdapi:convert --rootdir C:\Users\*****~1.*****\AppData\Local\Temp\.sfdx\tools\conflicts\*********\unpackaged --outputdir C:\Users\*****~1.*****\AppData\Local\Temp\.sfdx\tools\conflicts\*********\converted
 ended with exit code 134

An error was encountered during conflict detection. FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF795AB87DA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF795A93246 node::MakeCallback+4534
 3: 00007FF795A93BC0 node_module_register+2032
 4: 00007FF795DB1A4E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF795DB197F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF795F98174 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF795F8F156 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF795F8D7AC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF795F964F7 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF795F96576 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF7960C0817 v8::internal::Factory::NewFillerObject+55
12: 00007FF79613DA06 v8::internal::operator<<+73494
13: 00000272F3DDC5C1 

### Steps To Reproduce:

1) In SFDC project in VS Code, right-click on package.xml and click "Retrieve Source in Manifest From Org"

### Expected result

The delta changes should be retrieved, to update workspace.

### Actual result

Getting V8 engine Out of Memory exception as listed in the description.
![image](https://user-images.githubusercontent.com/4994304/87347382-22ffbf00-c521-11ea-97ff-8e646580dbf7.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:48.24.0

**OS and version**:
![image](https://user-images.githubusercontent.com/4994304/87335478-613fb300-c50e-11ea-8e55-f4da0af37f7c.png)

**Comment by lcampos** [comment]
Thanks for opening this issue @adityababbar , this seem it could be related to [Detect Conflicts](https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts) feature that's on preview/beta. Can you confirm if the issue goes away when you disable this feature ?

cc @rcoringrato-sfdc

**Comment by adityababbar** [comment]
Yes, it's definitely related to the Detect Conflicts feature. Retrieve works fine when the feature is disabled or when package.xml is not very large.

**Comment by floralan** [comment]
@adityababbar This issue has been resolved in our latest version of extensions. I'm closing this issue and please open new issue if you have more questions.
