### ISSUE TITLE
Replay Debugger not working for Execute Anonymous created logs 

### ISSUE THREAD

**Issue by vishnusundar2607** [forcedotcom/salesforcedx-vscode#2346]
### Summary

Replay debugger did not run as expected for the Log files created from Execute Anonymous. inserted record from both Execute Anonymous and Data Loader. Replay debugger running properly for Data loader created log . but Execute Anonymous window created log did not work as expected. Step Into Button created new empty file with same log file name 

### Steps To Reproduce:

1.  Inserted a record using "SFDX: Execute Anonymous Apex with Currently Selected Text"
2. Downloaded the latest  Apex log Using "SFDX: Get Apex Debug Logs…"
3. Right Click on Downloaded Log and Clicked on "SFDX: Launch Apex Replay Debugger with Current File"
4. Clicked on "Step Into(F11)" Button.

### Expected result

Replay debugger should highlight the next executed line

### Actual result

Log file before Running "Step Into(F11)" Button. 

![image](https://user-images.githubusercontent.com/47806185/87437623-35a2f280-c60c-11ea-8c3c-87a2347fa2f4.png)

after Clicking "Step Into(F11)" Button. Replay debugger created new empty file with same log file name.

![image](https://user-images.githubusercontent.com/47806185/87437243-ae557f00-c60b-11ea-9f74-02c9b17d282e.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by gbockus-sf** [comment]
@vishnusundar2607 I just attempted to reproduce this issue and was unable to encounter the problem. Mine stepped into the class under test and navigated through the code. We've made some major enhancements to the replay debugger recently.  Could you verify this is still an issue for you?
