### ISSUE TITLE
SFDX Commands not working

### ISSUE THREAD

**Issue by shalvijohari** [forcedotcom/salesforcedx-vscode#2354]
Issue Type: <b>Bug</b>

Press -> Ctrl+Shift+p
Enter SFDX
Click on SFDX:Create Project

Getting error : Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)
In Output tab error is as below :
[Error - 1:01:11 PM] Connection to server is erroring. Shutting down server.

Extension version: 48.24.0
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.90GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by smaddox-sf** [comment]
HI @shalvijohari - Have you installed the CLI?  Can you share the version and verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?
