### ISSUE TITLE
JAVA unsupported extension error inspite if installing version

### ISSUE THREAD

**Issue by Samiyashaikh** [forcedotcom/salesforcedx-vscode#2359]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by smaddox-sf** [comment]
Hi @Samiyashaikh - Please use the bug template to open an issue with the steps to reproduce and what issue you're seeing.  We don't have enough info here to understand the problem you are reporting.  Please open a new issue with the template so we have enough info to investigate.
