### ISSUE TITLE
Extension issue : Taking Too long

### ISSUE THREAD

**Issue by jpoonam4** [forcedotcom/salesforcedx-vscode#2378]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.2.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.2`

**Comment by smaddox-sf** [comment]
There's not enough information here to understand the issue and steps to reproduce.  Please feel free to open a new issue with more info and we're happy to take a look
