### ISSUE TITLE
command 'extension.replay-debugger.getLogFileName' not found

### ISSUE THREAD

**Issue by mafiaazul** [forcedotcom/salesforcedx-vscode#2384]
### Summary

I can't get the the Apex Replay Debugger to work. Every time I try to run it a get the error "command 'extension.replay-debugger.getLogFileName' not found"

### Steps To Reproduce:

1.  Turn On Apex Debug Log for Replay Debugger
2.  Manually select a Test class to run
3. Get latest Apex Log
4. Try to run the Apex Replay Debugger on current file

### Expected result

Debug the code

### Actual result

command 'extension.replay-debugger.getLogFileName' not found

### Additional information
launch.json

  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Apex Replay Debugger",
      "type": "apex-replay",
      "request": "launch",
      "logFile": "${command:AskForLogFileName}",
      "stopOnEntry": true,
      "trace": true
    }
  ]
}

_Feel free to attach a screenshot_.

**VS Code Version**: 
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**SFDX CLI Version**: sfdx-cli/7.66.2-4f159a1d07 win32-x64 node-v12.13.0

**OS and version**: Win 10 Enterprise - 1803

Additional Info:
I have tried all the current support Java JDK's: Java 11, AdoptOpenJDK 11 and Zulu 11. I have also set my JAVA_HOME under my system variables to reflect the root folder for each JDK I installed.

Since I'm on a windows machine (it works on my Mac), I have set the "salesforcedx-vscode-apex.java.home" to the corresponding root folder for my JDK using "\", "\\" or "/".
I still can't get it to work.
Example:
"C:\Program Files\Java\jdk-11.0.8"
"C:\\\Program Files\\\Java\\\jdk-11.0.8" or
"C:/Program Files/Java/jdk-11.0.8"

It was working, just all the sudden it stopped working.

Any ideas?

**Comment by lcampos** [comment]
Thanks for opening this issue @mafiaazul . In order to run this command you need to have the [Salesforce Apex Replay Debugger](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-apex-replay-debugger) extension installed and active, can you confirm you do have in running in your VSCode ?
