### ISSUE TITLE
Refresh SObject Definitions only works after you have explicitly run 'Authorize an Org' and not with an authorized Dev Hub set as a default org 

### ISSUE THREAD

**Issue by abychat** [forcedotcom/salesforcedx-vscode#2406]
#2398 # Summary

After creating a workspace, I Authorize a Dev Hub and later assign it as the Default org as well using the 'Change Default Org' button on the Side Bar and selecting the Dev Hub username I just authorized. If I try to run 'Refresh SObject Definitions' either from the notification pop up or the command palette, I get an authorization error 'Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.'

If however, I 'Authorize an Org' either from the Command Palette or using the 'Change Default Org' button, and reauthorize the same org that I authorized in step 1, the 'Refresh SObject Definitions' command works.

### Steps To Reproduce:

1. Create a new workspace
2. Click on 'Change Default Org' in the Sidebar and click on '+ SFDX: Authorize a Dev Hub'. Complete the authorization process.
3. Click on 'Change Default Org' again and choose the username for the Dev Hub you just authorized as the default org. Notice name of default org updates to the username in the sidebar.
4. Run 'Refresh SObject Definitions' from the Command Palette or from the notification popup from the IDE.
5. See error message that contains this text 'Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.'
6. Click on 'Change Default Org' in the Sidebar and click on '+ SFDX: Authorize an Org'. Complete the authorization process for the same uname/pwd used in step 2. This time IDE also asks for an alias. Notice name of default org updates to the alias you provided.
7. Run 'Refresh SObject Definitions' from the Command Palette or notification if it is still available to click.
8. Command successfully runs.

### Expected result

Running 'Refresh SObject Definitions' with an authorized Dev Hub also set as a default org should execute successfully.

### Actual result
Running 'Refresh SObject Definitions' with an authorized Dev Hub also set as a default org does not execute successfully. Authorizing the same org again as described above works fine.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.47.2

**SFDX CLI Version**:
49.4.1

**OS and version**:
 Mac OS Catalina Version 10.15.6

**Comment by abychat** [comment]
Hi @smaddox-sf , 
> Does it always fail the first time & succeed the second time?
Yes, the first time when I use the 'Authorize a Dev Hub' command from the palette, and add it as a default org, it always fails.
> Do you have the same issue when authorizing against a sandbox or scratch org?
Not sure if this applies because the bug is related to the behavior with an org that is a Dev Hub and I also want to use it as my default org.

Essentially, the Refresh SObjects is only working when I explicitly use the 'Authorize an Org' command, and not if I Authorize a Dev Hub and choose it as the default org manually using the org selector.

**Comment by smaddox-sf** [comment]
Thanks for clarifying @abychat .  You do have to explicitly `Authorize an Org` even if you have a Dev Hub connected.  The Dev Hub acts as a management org to create & maintain scratch orgs.  If you want to push/pull or refresh SObject definitions, you have to explicitly `Authorize an Org`.  (For most users, they are using an org other than the Dev Hub for development)

**Comment by SoundedSquash** [comment]
Thanks for this! I was going crazy and spending hours trying to figure out why refresh wasn't working. Refresh should check to make sure the org is authorized and give an error instead of running indefinitely with no errors.
