### ISSUE TITLE
Salesforce cli Extension showning unresponsive

### ISSUE THREAD

**Issue by kishangupta032** [forcedotcom/salesforcedx-vscode#2408]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.4.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
Hi @kishangupta032 , this issue does not have enough details for us to replicate on our side and work on a fix. I'll close it for now but feel free to re-open it if you have more details on how to replicate it.
