### ISSUE TITLE
Extension issue: LWC Deployments take too much time.

### ISSUE THREAD

**Issue by platinumpmo-amigo** [forcedotcom/salesforcedx-vscode#2416]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `49.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
Hi @platinumpmo-amigo I'm closing this since there's not enough information for us to replicate what you're running into. Feel free to re-open this is you have more information.
