### ISSUE TITLE
Command 'CCDX: Deploy Source To Salesforce' resulted in an error (Cannot read property 'path' of undefined)

### ISSUE THREAD

**Issue by mohitdongare25** [forcedotcom/salesforcedx-vscode#2421]
Issue Type: <b>Bug</b>

1. Create LWC in Scratch Org.
2. Authorize Dev Hub.
3. Deploy LWC using "CCDX: Deploy Source To Salesforce" command.

Facing below error while deploying LWC to Salesforce:
Command 'CCDX: Deploy Source To Salesforce' resulted in an error (Cannot read property 'path' of undefined)

Extension version: 49.5.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by smaddox-sf** [comment]
Hi @mohitdongare25 - By the command name, I'm assuming you're using an additional companion extension.  What do you get if you run the SFDX command directly?

**Comment by mohitdongare25** [comment]
I am using SFDX: Deploy this Source to Org from the "Ctrl+Shift+P" Command Palette in VS Code to deploy LWC project files.

**Comment by smaddox-sf** [comment]
Thanks for clarifying that @mohitdongare25 - What version of the Salesforce CLI are you using?

**Comment by mohitdongare25** [comment]
Version: sfdx-cli/7.69.0-c7be45ae22 win32-x64 node-v12.18.3

Very sorry for late reply!

**Comment by smaddox-sf** [comment]
A few more questions to try to pin down the issue:

 - What is your project structure?  can you include a screenshot?

- when you run `SFDX: Deploy This Source to Org` what is the starting point?  Is it a single component you are trying to deploy?

- After running `SFDX: Deploy This Source to Org`, can you paste or screenshot what is printed in the output panel?

- Have you tried running the command directly in the CLI?  If so, what output do you get?
