### ISSUE TITLE
Repeatedly get "Cannot read property 'get' of undefined" for non Salesforce projects

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/salesforcedx-vscode#2429]
### Summary

VS Code repeatedly outputs "Cannot read property 'get' of undefined" in the Salesforce CLI window of the Output tab/pane

### Steps To Reproduce:

1.  Ensure Salesforce extension pack for VS Code is installed
1.  Open a non-Salesforce project - in my case, it's a HTML/JS/CSS project with WebGL/ThreeJS

### Expected result

Salesforce extensions should not produce any output

### Actual result

VS Code repeatedly outputs "Cannot read property 'get' of undefined" in the Salesforce CLI window of the Output tab/pane

### Additional information

**VS Code Version**: 1.47.3

**SFDX CLI Version**: sfdx-cli/7.68.6-d37008df83 win32-x64 node-v12.18.3

**OS and version**: Windows 10 Pro version 2004

**Comment by lohit398** [comment]
This is happening with 1.48.2 as well.

Thanks!

**Comment by lcampos** [comment]
Thanks for reporting this, the fix for it has been released as part of version 49.13.0.
