### ISSUE TITLE
LWC: Issue with Auto-Suggest

### ISSUE THREAD

**Issue by pedroprada** [forcedotcom/salesforcedx-vscode#2431]
I am new to LWC and was following a course online.

What I noticed is that in the HTML component once Salesforce Extension Pack (which includes Lightning Web Components) and Salesforce CLI is installed, is NOT auto-suggesting the LWC components from Salesforce.

For instance when I enter <light  it will NOT show ALL the lightning components from Salesforce.  However, when I type <li  and backspace 1 character it will autosuggest everything.....
Also when I try to add title, it requires first letter to be capitalized.

I have tried in 3 different computerd and cannot get Intellisense to work with Salesforce methods.  Its not autopopulating.  I already checked and have all the intellisense checkboxes marked as true.

Can you please help?

**Comment by smaddox-sf** [comment]
Hi @pedroprada - Is it the HTML file you're modifying?  In those files, you must hit Control + Space in order to get autocomplete suggestions to show up.

If that is not the issue, please post back with the steps to reproduce and version of the each of these: SF Extension, CLI and OS.
