### ISSUE TITLE
sfdx: create project comands are not working

### ISSUE THREAD

**Issue by bharadwajkura** [forcedotcom/salesforcedx-vscode#2434]
Issue Type: <b>Performance Issue</b>

When I try to create a new project using the command sfdx:create: project it showing me an error that the command does not exist. It worked me in the beginning but now it is not working

Extension version: 49.6.0
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (1.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	  8708	code main
    0	    13	  2792	   electron-crash-reporter
    0	    74	  2932	   shared-process
    0	    58	  6320	   window (undefined)
    0	   187	  8684	   window (Extension: Java Extension Pack - HelloWorldLightningWebComponent - Visual Studio Code)
    0	    13	  3740	     watcherService 
    0	    11	  8300	       console-window-host (Windows internal process)
    0	    34	  8096	     searchService
    0	   103	 14568	     extensionHost
    0	   115	  7368	       electron_node server.js 
    0	    28	 16044	       "C:\Users\Mahesh\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Mahesh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=14568
    0	    30	  8868	   utility
    0	   177	 11692	   gpu-process
    2	    66	 14688	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Java Extension Pack - HelloWorldLightningWebComponent - Visual Studio Code)
|    Folder (HelloWorldLightningWebComponent): 49 files
|      File types: json(9) ts(6) eslintignore(1) forceignore(1) gitignore(1)
|                  prettierignore(1) prettierrc(1) md(1) apex(1) soql(1)
|      Conf files: launch.json(1) settings.json(1) jsconfig.json(1)
|                  package.json(1)
|      Launch Configs: apex-replay;
```

</details>

**Comment by smaddox-sf** [comment]
Hi @bharadwajkura - It sounds like the Salesforce CLI is not installed or not setup properly.  You didn't mention a CLI version - have you installed it?  [Here's the install info in case that is needed](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm).

If it's already installed, can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?

**Comment by bharadwajkura** [comment]
[
![Screenshot (1408)](https://user-images.githubusercontent.com/70093426/91120079-72094a00-e6b2-11ea-8e22-1c9b2b89d1c9.png)
](url)

**Comment by smaddox-sf** [comment]
Hi @bharadwajkura - Thanks for the additional info and verifying the CLI is setup.  We see this error when VS Code can't find the path to the CLI.  Can you check [the details in this article](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows) and see if that fixes it?

**Comment by bharadwajkura** [comment]
Hi, @smaddox-sf  issue has been resolved with the above article you have provided. Thank you for your help
