### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bharadwajkura** [forcedotcom/salesforcedx-vscode#2436]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.6.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Mahesh\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
