### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Kashi4811** [forcedotcom/salesforcedx-vscode#2438]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lightning`
- Extension Version: `49.6.0`
- OS Version: `Linux x64 4.15.0-112-generic`
- VSCode version: `1.48.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not enough info to look into this.  Please open a new issue using the Bug template
