### ISSUE TITLE
Use of Deployment and Deletion Commands Should Have a Warning

### ISSUE THREAD

**Issue by RoadRunner88** [forcedotcom/salesforcedx-vscode#2441]
**Is your feature request related to a problem? Please describe.**

PROBLEM: I am in VS Code using the SFDC Extension. The "sfdx: deploy source in manifest to org" is RIGHT next to the retrieve command. An accidental selection or mishap of mouse will trigger a deployment (YIKES) when you meant to retrieve. This could be a catastrophic mistake at the manifest level. 

**Describe the solution you'd like**

SOLUTION 1: ANY of the deploy related SFDX commands should have a warning confirmation "You are requesting to DEPLOY, are you sure?" 

SOLUTION 2: ANY of the delete related SFDX commands should have a warning confirmation "You are requesting to DELETE, are you sure?" 

**Describe alternatives you've considered**

I looked for the ability to disable the command, but could not find one. 

**Additional context**

I have accidentally deleted a file, and wasn't aware I had done it. This was frustrating for all involved. I can't even image if it was a manifest of files, and not just a single file.  Thank goodness the deletion was on a sandbox.

**Comment by smaddox-sf** [comment]
Hi @RoadRunner88 - When using the Deploy or Retrieve commands, how are you accessing them?  From the description, it sounds like the right-click menu.  do you ever use the command palette instead?

**Comment by RoadRunner88** [comment]
Correct, I am (was) using the right mouse click, I have since moved to use the command palette and type out "retrieve". Not as handy, but I won't make the same mistake. 

I am concerned about others who haven't had the gut wrenching experience of OMG, what did I just do. 

The right click is much quicker and more convenient, people will use the path of least effort.

**Comment by smaddox-sf** [comment]
Thanks for the clarification @RoadRunner88.  The feedback we get from most users is the opposite - preference toward the Command Palette as it's faster to stay on the keyboard vs. having to use the mouse.  We've also received feedback that prompts are annoying and interrupt user's flow.  I understand the concern you raised, but this isn't a prompt we'll add at this time.  Using the command palette is a good way to alleviate the worry of clicking the wrong thing.  If we get further feedback from the community, we'll revisit this in the future.

**Comment by RoadRunner88** [comment]
Could you provide a configuration option to remove delete and deploy options from the right click menu in VS Code?
