### ISSUE TITLE
Configuration for path to specific `sfdx` executable

### ISSUE THREAD

**Issue by chexxor** [forcedotcom/salesforcedx-vscode#2446]
**Is your feature request related to a problem? Please describe.**
I get frustrated when a new installation of VS Code on a new system can't find the `sfdx` executable. It requires me to use admin permission on my Windows computer to run the `sfdx` installer, and it has incorrectly added `sfdx` to the PATH environment variable, for an unknown reason (though likely due to a user error). Rather than me simply proving to VS Code that I have it installed by showing it the absolute path to `sfdx`, I am required to modify an environment variable on my Windows system, which is awkward because I believe it only takes effect after logging out/rebooting the machine.

**Describe the solution you'd like**
Add a new configuration variable, "salesforcedx-vscode-apex.sfdx.path". When non-empty, this extension will use that specific `sfdx` executable instead of the one found on the `PATH` environment variable.

I was interested in configuring the PATH within this VS Code extension to ensure it uses a specific version of sfdx, leaving me free to use a different sfdx in different situations. This extension (or one in the greater umbrella project) already has a similar configuration variable named salesforcedx-vscode-apex for defining the location of the JVM, which also has a dedicated environment which you could use to accomplish the same thing.

**Describe alternatives you've considered**
I considered
- using a shell init script to define a custom PATH to use for that specific shell
- wrapping VS Code executable in a shell script which redefines the PATH before starting VS Code

**Additional context**

Looks like we would need to change [`sfdxCommandBuilder`](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-utils-vscode/src/cli/commandBuilder.ts#L77-L81) to get the 'sfdx' string from a configuration variable.

I imagine some people might want to set this value from an environment variable in the terminal which executes the sfdx commands, so we might want to abstract it out to a module of its own. I don't know if maintainers would prefer to avoid env vars, though, or would like to avoid a configuration class for this module. Looks like that "salesforcedx-utils-vscode" module doesn't have a configuration module yet, so we could make one.

**Comment by lcampos** [comment]
Thanks for providing feedback @chexxor . We are aware of the challenges with the current setup experience for the extension and this is a good suggestion. However, a few month ago we started rearchitecting our tools, including the VSCode extensions, and we're working on delivering a simplified experience where you'll only have to install VSCode, the Salesforce extensions for VSCode and you'll be able to authenticate to your orgs, deploy/retrieve code, scaffold metadata, run tests, etc. This means not having to install the Salesforce CLI or a Java JDK.

Some of these changes are already available and you're probably already using them without noticing. Things like scaffolding metadata (e.g. SFDX: Create Apex Class), downloading debug logs, executing anonymous apex and deploy/retrieve for a subset of metadata ([Performance Enhancements](https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements)) have been available for a few weeks or months depending on the feature being used.

We'll continue to release these changes to other areas in the extensions that interact with the Org like authentication, features like Org Browser, running tests, etc.

I'll close this issue for now but let us know if you have any other questions/feedback. Thanks again for providing feedback.

cc @smaddox-sf
