### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ruthirappan** [forcedotcom/salesforcedx-vscode#2448]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\A101436905\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
