### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SD30190** [forcedotcom/salesforcedx-vscode#2452]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7733,
		"activateCallTime": 46,
		"activateResolvedTime": 1156,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
There's not enough information here to understand what's going on.  Please open a new issue using the "Bug" template.
