### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SD30190** [forcedotcom/salesforcedx-vscode#2453]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 13491,
		"activateCallTime": 7,
		"activateResolvedTime": 3109,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "salesforce.salesforce-vscode-slds",
				"_lower": "salesforce.salesforce-vscode-slds"
			},
			"activationEvent": "onLanguage:javascript"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
There's not enough information here to understand what's going on.  Please open a new issue using the "Bug" template.
