### ISSUE TITLE
lightning language service support not working for LWC in vs Code 

### ISSUE THREAD

**Issue by aetto** [forcedotcom/salesforcedx-vscode#2455]
**Summary**
Code completion not working in vs code for LWC.

**Steps To Reproduce:**

1. execute command  `sfdx force:lightning:component:create --type lwc --componentname test --outputdir force-app/main/default/lwc`
2. Open test.html file.
3. Start typing <lightning-

**Expected result**
vs Code should suggest standard lightning elements/components

**Actual result**
Nothing happened! :(

**Additional information**
Getting auto-complete suggestions in .js file.
Have tried enabling language server for HTML in settings.
uninstalled and installed the extension pack.

Extension version:
Salesforce Extension pack: v49.6.0
Lightning Web components: v49.6.0

**Extension settings in vs Code**:
```
{
    "salesforcedx-vscode-lightning.activationMode": "always"
}
```

**VS Code Version**:
1.48.2

**SFDX CLI Version**:
sfdx-cli/7.71.0-4193fb4acc darwin-x64 node-v12.18.3

**OS and version**:
macOS Catalina version 10.15.6

https://www.loom.com/share/2f2961cc06254129a09af663d199151b

**Comment by smaddox-sf** [comment]
Hi @aetto - You have to hit Control + Space in order to get autocomplete suggestions to show up in those files.  We recognize that is confusing and not the most convenient.

**Comment by aetto** [comment]
Hi @smaddox-sf - Thanks for the quick response. control+space works. And as you said it is not convenient. It would be great if it works like any other language service.
Thanks.
