### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LatpateNarendra** [forcedotcom/salesforcedx-vscode#2461]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.7.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Narendra\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
