### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sparkplug-silverweb** [forcedotcom/salesforcedx-vscode#2474]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.7.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not info information to understand the issue
