### ISSUE TITLE
Lightning Web Components extension is not working properly

### ISSUE THREAD

**Issue by ashishy258** [forcedotcom/salesforcedx-vscode#2475]
### Summary

Lightning Web Components extension in salesforce extension pack is not making auto suggestions and auto completion by it self.

### Expected result

it should have show me the related tags in LWC whenever i start writing some tags.

### Actual result

But it is not showing any kind of code completion or auto suggestion

<img width="595" alt="Cap" src="https://user-images.githubusercontent.com/50999583/91953501-d1083800-ed1e-11ea-9ea2-9d9cebff9789.PNG">
 
### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @ashishy258  -  You have to hit Control + Space in order to get autocomplete suggestions to show up in those files. We recognize that is confusing and not the most convenient.

**Comment by tsalb** [comment]
Found this thread after encountering this as well. In previous versions of either VSCode or the Salesforce Extension pack, Intellisense for suggesting base component LWCs were working automatically.

In other words, we were not required to hit ctrl+space to get LWC autocomplete/intellisense to work.

Following [these settings](https://stackoverflow.com/questions/40839733/autocomplete-without-ctrlspace) for manually setting `editor.quickSuggestions` doesn't seem to work either.

@smaddox-sf any possible updates to VSCode or Extension pack that would cause these changes?
