### ISSUE TITLE
The extension 'Apex' took a very long time to complete its last operation and it has prevented other extensions from running.

### ISSUE THREAD

**Issue by jpoonam4** [forcedotcom/salesforcedx-vscode#2481]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.2`

![Capture](https://user-images.githubusercontent.com/22389139/92114269-2e2ee700-ee0e-11ea-8079-4ef9566b4431.PNG)

**Comment by lcampos** [comment]
There is not enough information for us to replicate the issue you are experiencing and try to address it. Feel free to re-open this if you have data we can use to replicate the issue on our side.
