### ISSUE TITLE
Flag expired Scratch Orgs in the OrgPicker

### ISSUE THREAD

**Issue by maaaaarco** [forcedotcom/salesforcedx-vscode#2484]
**Is your feature request related to a problem? Please describe.**
Org Picker lists all authenticated orgs stored in your `~/.sfdx/` folder, including expired Scratch Orgs.

**Describe the solution you'd like**
Org Picker should flag Scratch Orgs that have expired.

**Comment by smaddox-sf** [comment]
Duplicate #945
