### ISSUE TITLE
Unable to Deploy Source to Org and Unable to Authorize Org. If have Default org used we can Authorize that. But with command it keeps on running.

### ISSUE THREAD

**Issue by jpoonam4** [forcedotcom/salesforcedx-vscode#2487]
**Summary**
 SFDX commands are taking way to long to execute, infact I had to cancel them because they are just shown as running for infinite. 
SFDX: Create Project Working fine in  salesforce cli version 49.8.0 
For Ex:  1. SFDX: Authorize an Org command progress indicator keeps on running.

2. SFDX: Deploy Source to Org  command progress indicator keeps on running.

Steps To Reproduce:
After running  SFDX: Create Project is run trying to authorize org.

**1.** execute sfdx command : SFDX: Authorize an Org
Press Enter to accept the Project Default login URL option.
Press Enter to accept the default alias.

**Expected result**
We should get Output as
![expcted](https://user-images.githubusercontent.com/22389139/92219418-2cb9f900-eeb8-11ea-809f-9d59bebfb512.PNG)

**Actual result**
The command progress indicator keeps on running. Output i get
![Authorize](https://user-images.githubusercontent.com/22389139/92220686-f7160f80-eeb9-11ea-9bbc-ea10c63b8c8e.PNG)

Not getting 2nd Output on vsc which contains ended with exit code 0.

**2.** execute sfdx command :SFDX: Deploy Source to Org

**IF we have Default org** with which we logged in earlier using that we can authorize default org.
So after that trying to execute SFDX: Deploy Source to Org
![SettingsedaultOrg](https://user-images.githubusercontent.com/22389139/92220077-119bb900-eeb9-11ea-847d-685bc9ae245c.PNG)

**Expected result**
![OutputVal](https://user-images.githubusercontent.com/22389139/92219867-c7b2d300-eeb8-11ea-8a79-d34e3e5e2690.PNG)

**Actual result**
The command progress indicator keeps on running.
![deploy](https://user-images.githubusercontent.com/22389139/92219895-d26d6800-eeb8-11ea-86e5-083abe29aa7e.PNG)

**Additional information:**

VS Code Version:
1.48.2

Salesforce Cli  Integeration(Extension)
![Saliesforce](https://user-images.githubusercontent.com/22389139/92218630-05aef780-eeb7-11ea-83e0-093f414b99c3.PNG)

SFDX CLI Version:
sfdx-cli/7.72.0-697e9faee2 win32-x64 node-v12.18.3

Java Version:
1.8.0_261

System type :
64-bit Operating System,x64-based processor
Windows 10

**Comment by banderson5144** [comment]
I am getting the same issue as well. I think this may be a windows issue. I am not noticing this on my Mac

**Comment by lcampos** [comment]
Thanks for opening this issue @jpoonam4 . Could you or @banderson5144 try the new deploy enhancements and see if that helps with the deploys not working [Performance Enhancements](https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements)

**Comment by banderson5144** [comment]
So my issues is not with deployments. It has more to do with any SFDX action that opens a browser. The process just does open the browser, but it just seems to hang after wards. This also happens directly from the command line as well so I open up this ticket https://github.com/forcedotcom/cli/issues/650

**Comment by lcampos** [comment]
Thanks for opening that other issue in the CLI repo @banderson5144 . That is the right place for it since the VSCode extensions are just delegating the execution to the CLI.
