### ISSUE TITLE
Deploying LWC components is not working

### ISSUE THREAD

**Issue by mmsaikumar** [forcedotcom/salesforcedx-vscode#2489]
No error is showing and not getting deployed into salesforce while deploying LWC components through vs Code

**Comment by smaddox-sf** [comment]
Hi @mmsaikumar - We don't have enough information to try to help.  Please add the following details:

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2.

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:
