### ISSUE TITLE
SObject "Event" is not generated by the SFDX: Refresh SObject Definitions command

### ISSUE THREAD

**Issue by khjuan** [forcedotcom/salesforcedx-vscode#2490]
### Summary

After executing the SFDX: Refresh SObject Definitions command, the standard "Event" sobject was not created.

### Steps To Reproduce:

1.  In VSCode for windows, Ctrl-Shift P to bring up the command palette. Run the SFDX: Refresh SObject Definitions for the connected ORG
2. Check the .sfdx/tools/sobjects/standardObjects folder, and the Event.cls is not there. 

### Expected result

Expected Event.cls to be created as it is a standard SObject.

### Actual result

Event.cls cannot be located in .sfdx/tools/sobjects/standardObjects folder.

### Additional information

Executing the **sfdx force:schema:sobject:list -c standard** in the command line yielded the Event Sobject in the result.
Suspect the fauxClassGenerator.isRequiredSObject has inadvertedly excluded a legimate object name.

  public isRequiredSObject(sobject: string): boolean {
    // Ignore all sobjects that end with Share or History or Feed or Event
    return !/Share$|History$|Feed$|**Event$**/.test(sobject);
  }

**VS Code Version**: 1.48.2

**SFDX CLI Version**:  7.73.1

**OS and version**: Linux xxxxx 4.19.104-microsoft-standard #1 SMP

**Comment by mohanraj-r** [comment]
@khjuan This issue is now fixed. I tried (with v54.6.1) SFDX: Refresh SObject Definitions and verified that Event.cls is created under .sfdx/tools/sobjects/standardObjects folder.
