### ISSUE TITLE
Show Lightning Explorer Not working VS code

### ISSUE THREAD

**Issue by tellanad** [forcedotcom/salesforcedx-vscode#2491]
### As part of Beta I think the Lightning Explorer can be enabled or disabled in VS code, I am not able to see the option for enablement of the feature.

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Install salesforce Extension pack
1.  Go the Vs code preferences, search for lightning explorer 
### Expected result
Should see the Combobox for enabling/disable for the Lightning Explorer

<img width="915" alt="Screen Shot 2020-09-06 at 10 28 10 AM" src="https://user-images.githubusercontent.com/14303298/92328003-c35af700-f02b-11ea-9127-c729cadbd99a.png">

**VS Code Version**:
sfdx-cli/7.72.0-697e9faee2 darwin-x64 node-v12.18.3
**SFDX CLI Version**:

**OS and version**:Mac Sierra

**Comment by lcampos** [comment]
Hi @tellanad , after running this feature in beta we decided to remove it and not keep it around given the lack of use and benefits to users.

cc @smaddox-sf
