### ISSUE TITLE
Salesforce CLI Integration- Extension issue

### ISSUE THREAD

**Issue by gyadav4** [forcedotcom/salesforcedx-vscode#2492]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.48.2`

**Comment by smaddox-sf** [comment]
Hi @gyadav4 - There's not enough information here to understand what the issue is.  Please open a new issue using the 'bug' template.
