### ISSUE TITLE
Issue while "Retrieve Source in Manifest from Org".

### ISSUE THREAD

**Issue by vikash-ag** [forcedotcom/salesforcedx-vscode#2493]
After installing the latest update of Salesforce Extension Pack the retrieve from source command is not working and throwing error with the following message "ERROR running force:source:retrieve:  Cannot read property 'record' of undefined". 
This issue is stoping me to create any new project and working on those. Can someone please help me out her.

**Comment by vikash-ag** [comment]
Below is the Package.xml code that I'm using, but not sure what is incorrect with it.
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTestSuite</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>49.0</version>
</Package>`

**Comment by smaddox-sf** [comment]
Hi @vikash-ag - Can you please add the following details:

- Steps to reproduce.  For example, were you retrieving a single file?  using the Org Browser?  etc
- VS Code Version
- SFDX CLI Version
- OS and version

**Comment by vikash-ag** [comment]
Hi @smaddox-sf - I think the issue has been resolved on updating the Salesforce CLI version as it didn't had the latest updates in my system. I think that was causing the issue, but now its been resolved. But there should be a way to identify what needs to be updated in VS code itself.
