### ISSUE TITLE
Unable to install sfdx-diff plugin using Terminal

### ISSUE THREAD

**Issue by kushalbhalodia** [forcedotcom/salesforcedx-vscode#2499]
### Summary

When I tried installed sfdx-diff using command "sfdx plugins:install @salesforce/sfdx-diff" it throws an error "TypeError: Cannot read property 'dim' of undefined"

### Steps To Reproduce:

1.  Install VSCode
1.  Install Salesforce Extension Pack from extensions. 
1. From the VSCode Terminal, Type "sfdx plugins:install @salesforce/sfdx-diff" 

### Expected result

Plugin should have installed

### Actual result

Error: TypeError: Cannot read property 'dim' of undefined

### Additional information

![image](https://user-images.githubusercontent.com/3942456/92566156-6795a580-f299-11ea-83ad-02d8944af2de.png)

**VS Code Version**:
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**SFDX CLI Version**:
sfdx-cli/7.73.2-feef087df8 win32-x64 node-v12.18.3

**OS and version**:
Windows 10 version 2004

**Comment by ntotten** [comment]
Root cause: https://github.com/forcedotcom/cli/issues/592

**Comment by smaddox-sf** [comment]
As noted above, root cause is a CLI issue.  Please follow forcedotcom/cli#592 for status and updates
