### ISSUE TITLE
Error: Request textDocument/definition failed.

### ISSUE THREAD

**Issue by gonardfreeman** [forcedotcom/salesforcedx-vscode#2512]
**Is your feature request related to a problem? Please describe.**
Every time I hit CMD button (only button itself) at lwc js file latest macOS X (Catalina 10.15.6)
 I've got this error:
`[Error - 11:52:47 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot destructure property 'delimiter' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
  Code: -32603 ` and bottom panel is appeared.
VS Code dev tools shows this error:
`(node:14276) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

![error](https://user-images.githubusercontent.com/16113714/92898365-98571580-f426-11ea-9f90-b000b1c2b219.gif)

**Describe the solution you'd like**
No error or at least bottom panel does not appear on it

**Describe alternatives you've considered**
No alternatives were found.

**Comment by lcampos** [comment]
Hi @gonardfreeman , could you add which version of VSCode and which version of the Salesforce extensions for VSCode you are running ?
