### ISSUE TITLE
Extension stopped working after updating VS Code to latest version (1.49)

### ISSUE THREAD

**Issue by EstebanRomero84** [forcedotcom/salesforcedx-vscode#2518]
### Summary

After I updated VS Code to version 1.49.0, Salesforce DX extensions stopped working

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/30849643/92969879-23023980-f454-11ea-971e-82b00edfd958.png)

**VS Code Version**: 1.49.0

**SFDX CLI Version**: 7.72.0 win32-x64 node-v12.18.3

**OS and version**: Windows_NT x64 10.0.19041

**Comment by smaddox-sf** [comment]
Can you clarify what you mean by 'stopped working'?  Are you getting errors?  Or seeing no commands?  Or...?

Also, did you reload VS Code after the update?

**Comment by EstebanRomero84** [comment]
Hi @smaddox-sf - When I open any sfdx project that I was working on before VSC update, it doesn't show the Org Browser or the Org Picker. Also if a try to create a new project from the command palette I get following error:
"Command 'SFDX: Create Project with Manifest' resulted in an error (command 'sfdx.force.project.with.manifest.create' not found)"

Regards.

**Comment by smaddox-sf** [comment]
Thanks for clarifying.  It sounds like the extensions are not fully activating.  This can happen if somethings times out on startup.

do you get any error message in the bottom-right corner of VSCode's footer or in the Dev Tools console (Help > Toggle Developer Tools and select the Console tab). If you do can you provide those details ?

**Comment by EstebanRomero84** [comment]
Yes, I got following errors in console:

![image](https://user-images.githubusercontent.com/30849643/93215609-02303180-f73d-11ea-9df4-b3e3d3627d39.png)

Regards.

**Comment by EstebanRomero84** [comment]
I uninstalled Salesforce Extension Pack and re-installed. Now it's working ok.

**Comment by smaddox-sf** [comment]
@EstebanRomero84 - Great, so glad you are unblocked!
