### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jojoforce** [forcedotcom/salesforcedx-vscode#2519]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 24577,
		"activateCallTime": 8,
		"activateResolvedTime": 6373,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "salesforce.salesforce-vscode-slds",
				"_lower": "salesforce.salesforce-vscode-slds"
			},
			"activationEvent": "onLanguage:html"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  Please open a new issue using the 'bug' template
