### ISSUE TITLE
I'm formerly a mavensmate user and I don't get how to use this extension

### ISSUE THREAD

**Issue by noctufaber** [forcedotcom/salesforcedx-vscode#252]
### Summary
I need some guidance on how to use this tool.  Are there instructions somewhere on how I can use this tool like I used Mavensmate?  I'm looking for a place to put in my Salesforce sandbox credentials (ie. username, password, salesforce sandbox instance name).  Any help you can offer would be super helpful.

**Comment by vazexqi** [comment]
@noctufaber: Thanks for your interest in our extensions. This forum is more about filing bugs and feature requests. This is not the right forum for asking for user guidance. For that, we suggest going to the TrailBlazer community at https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1 

We have created a short guide at https://youtu.be/j9vsxMH7dH4 on how to install and use the extensions. The extensions are centered around the Salesforce DX flow with uses the CLI to do a lot of the heavy lifting of authentication.

Also, you can find the help embedded in the README for each extension. For example, see https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode
