### ISSUE TITLE
Getting error 'Can't read property'

### ISSUE THREAD

**Issue by prasoon-salesforce** [forcedotcom/salesforcedx-vscode#2521]
### Summary

_Short summary of what is going on or to provide context_.

Install Visual Studio Code > Create a New Project with Manifest > Authorize an Org > Right Click Package under Manifest > Choose 'SFDX: Retrive Source in Manifest from Org' and I am getting error continuously. Error is :

Cannot read property 'record' of undefined. And debug is redirecting to the package which has been created by VS Code in the Step : ' Create a Project with Manifest'.
_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @prasoon-salesforce - Can you update to the latest version of the SFDX CLI and retry?  I believe this is the same as [this CLI bug](https://github.com/forcedotcom/cli/issues/581), which was patched late last week.

**Comment by prasoon-salesforce** [comment]
Thanks @smaddox-sf for reply , but my CLI is up to date with latest Version.

**Comment by lcampos** [comment]
@prasoon-salesforce can you add which version of VSCode and which version of the Salesforce extensions for VSCode you are running ? Also, what OS are you using ?

**Comment by prasoon-salesforce** [comment]
Thanks for reply @lcampos . My VSCode version is : 

Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134

And My CLI Version is :  v49.7.0

OS : Miscrosoft Windows 10 Enterprise. 
Version : 10.0.17134 Build 17134

**Comment by smaddox-sf** [comment]
Can you run this command from the terminal: `sfdx -v`?
