### ISSUE TITLE
Authorize an Org failing when behind a firewall

### ISSUE THREAD

**Issue by ParulDua** [forcedotcom/salesforcedx-vscode#2522]
### Summary

When we try to authorize a Salesforce Sandbox in VS code, we get LocalHost:1717 error in the browser (refer attached screenshot) and below error in VS Code terminal:

------------------------------------------------------------------------------------------------------------------------------------------
Starting SFDX: Authorize an Org

14:19:18.380 sfdx force:auth:web:login --setalias OAT --instanceurl https://test.salesforce.com --setdefaultusername
ERROR running force:auth:web:login:  tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 10590 10590:80
14:21:05.164 sfdx force:auth:web:login --setalias OAT --instanceurl https://test.salesforce.com --setdefaultusername ended with exit code 1
--------------------------------------------------------------------------------------------------------------------------------------------

We have set the **https_proxy = http://<username:password>@165.225.26.39:10590**
and **SSL-verify = false**.

We are using the VS code as well as the browser via a VDI Citrix workspace arrangement.

Request you to help us identify the root us and let us know if we are missing any proxy settings.

### Expected result

Authentication is successful and Salesforce Org is connected to workspace.

### Actual result

 We get the LocalHost:1717 error (refer attached screenshot) and below w=error in VS code terminal :

Starting SFDX: Authorize an Org

14:19:18.380 sfdx force:auth:web:login --setalias OAT --instanceurl https://test.salesforce.com --setdefaultusername
ERROR running force:auth:web:login:  tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 10590 10590:80
14:21:05.164 sfdx force:auth:web:login --setalias OAT --instanceurl https://test.salesforce.com --setdefaultusername ended with exit code 1

![LocalHosterr](https://user-images.githubusercontent.com/66628966/93085844-d74dcb00-f6b3-11ea-99c7-0a4153d52346.PNG)

**VS Code Version**: 1.39.2

**SFDX CLI Version**: 47.16.0

**OS and version**: Windows_NT x64 6.1.7601

**Comment by smaddox-sf** [comment]
Hi @ParulDua - Are you behind a firewall or does your machine block the use of port 1717 ?
If not, this is due to the following known issue: https://trailblazer.salesforce.com/issues_view?id=a1p3A0000003dkDQAQ

**Comment by ParulDua** [comment]
Hi @smaddox-sf Yes the Citrix is behind a firewall.

Below are the few things that need to be clarified and would be helpful to proceed checking with this issue.
 
1) Need to understand the use of localhost:1717, how it is getting directed when accessing application and if firewall needs to be configured - need to know from which source to destination it has to be configured.
 
2) Is there any application logs that we can refer when the login attempts fails ?
 
3) What is the recommended application setup to be configured in the Citrix environment ?

Regards,
Parul

**Comment by ParulDua** [comment]
Hi Team,

Any update on the resolution/root causes for the issue.

Could you suggest some settings which might help solve the LocalHost:1717 not reachable issue?

Regards,
Parul Dua

**Comment by smaddox-sf** [comment]
Hi @ParulDua - This is likely a proxy issue since you're behind a firewall. Unfortunately, proxy issues are something you will have to work with your IT department on.  We do have some documentation that might be helpful:

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm
