### ISSUE TITLE
Extension issue_ `salesforcedx-vscode-apex`

### ISSUE THREAD

**Issue by alok1665** [forcedotcom/salesforcedx-vscode#2530]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.9.0`
- OS Version: `Windows_NT ia32 6.2.9200`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
There is not enough information here for us to replicate the issue you are experiencing and work on a fix. I'm going to close this but feel free to re-open it if you can provide steps for us to reproduce the error.
