### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by alok1665** [forcedotcom/salesforcedx-vscode#2531]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex-replay-debugger`
- Extension Version: `49.9.0`
- OS Version: `Windows_NT ia32 6.2.9200`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
There is not enough information for us to do something about what you are experiencing. I'll close this for now but feel free to re-open it if you have steps we can use to replicate the issue and work on a fix.
