### ISSUE TITLE
Not able to Deploy fields with  a package  into the higher Org using VS Code 

### ISSUE THREAD

**Issue by sayantadandapat** [forcedotcom/salesforcedx-vscode#2532]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Create a pkg like below.
<types>       
        <members>OCE__AskAQuestion__c.RCH_Indication__c</members>
        <members>OCE__AskAQuestion__c.OCE__Status__c</members>
        <members>Account.RCH_Primary_Responsible__c</members>
        <members>OCE__AskAQuestion__c.RCH_Primary_Responsible_for_Payer__c</members>
        <name>CustomField</name>
    </types>
1.  Please deploy the same using VS Code.

### Expected result

Fields needs to be deployed to the target Org

### Actual result

![image](https://user-images.githubusercontent.com/66197025/93332092-ea40d680-f83e-11ea-8f99-91ae4071e0da.png)

and fields are not deploying into the target org.

### Additional information

![image](https://user-images.githubusercontent.com/66197025/93332113-f2991180-f83e-11ea-9354-3bc5917d29b6.png)

**VS Code Version**:
1.49
**SFDX CLI Version**:
49.9
**OS and version**:
Windows

**Comment by lcampos** [comment]
Hi @sayantadandapat , looking at the output you've provided it looks like you are trying to deploy using a manifest file (package.xml) but you are feeding the CLI command a record type metadata file instead (RecordTypeReference_Account.xml).
Can you try deploying using your project's package.xml instead ?

**Comment by sayantadandapat** [comment]
@lcampos This issue is only with Fields,FieldSet.Others are good.
Changed the value as package.xml but same thing as below.
The problem is it says succesfull but no results found.
I downgraded the VS code version from 1.49 to 1.36 still same.
Also my other teammates are using 36 version but  they are able to deploy .
I am not sure which property is resisting to do this.
Please help if you have any clue.
![image](https://user-images.githubusercontent.com/66197025/93421540-3e939700-f8cf-11ea-841d-20d6fd33062d.png)

**Comment by sayantadandapat** [comment]
Now no one can deploy the fields or fieldSet only.
However if you try to deploy the full fields its good and deploying.
But asume i want to deploy only 5 account related fields ,its not deploying!!

Please helpout.

**Comment by gianmarcoelg** [comment]
Hello @sayantadandapat could you find a solution for this problem? I have the same problem but also with custom labels, listviews, fields. In my case after a lot of deploys one of them let me deploy the metadata to a sandbox but then the error persist

**Comment by lcampos** [comment]
@sayantadandapat @gianmarcoelg I haven't been able to replicate this issue with the several projects I normally use. Can any of you provide a sample project that consistently runs into this issue so we can debug it ? Thanks

**Comment by nicolas1bruno** [comment]
@lcampos I think is the same issue that this one
[https://github.com/forcedotcom/cli/issues/654](https://github.com/forcedotcom/cli/issues/654)

**Comment by lcampos** [comment]
@nicolas1bruno yes this is the same as that issue you linked, I'll close this as a duplicate.
