### ISSUE TITLE
Copy of theme folder being added to css folder instead of updating theme folder

### ISSUE THREAD

**Issue by wescoturf** [forcedotcom/salesforcedx-vscode#2535]
### Summary

This is a B2B Commerce sandbox. Issue started 9/14 afternoon. I did not change anything. When retrieving the theme folder, Visual Studio is adding a theme folder inside the css folder instead of updating the them folder and contents.

I have tried uninstalling VSC and the extensions twice. I'm only installing the extension pack and not the CLI extension alone.

### Steps To Reproduce:

1.  Right click on theme folder
1.2 Retrieve from org
1.3 Success message is shown
1.4 Open theme folder
1.5 go to css folder
1.6 downloaded theme folder is inside the css folder now

### Expected result

Theme folder and contents should be updated and no new copies of folder added inside existing folders

### Actual result

A new updated theme folder is being added to the css folder inside the theme folder

### Additional information

![VSCIssue](https://user-images.githubusercontent.com/62674463/93391179-c67c9100-f83c-11ea-87f6-ace1e5f83000.JPG)

CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: enabled rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.88GB (5.37GB free)
Process Argv | --crash-reporter-id 50e5ef9b-0212-419a-88a2-8ad58c71b076
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
vscode-eslint | dba | 2.1.8
prettier-vscode | esb | 5.6.0
vscode-xml | red | 0.13.0
salesforce-vscode-slds | sal | 1.2.1
salesforcedx-vscode | sal | 49.9.0
salesforcedx-vscode-apex | sal | 49.9.0
salesforcedx-vscode-apex-debugger | sal | 49.9.0
salesforcedx-vscode-apex-replay-debugger | sal | 49.9.0
salesforcedx-vscode-core | sal | 49.9.0
salesforcedx-vscode-lightning | sal | 49.9.0
salesforcedx-vscode-lwc | sal | 49.9.0
salesforcedx-vscode-visualforce | sal | 49.9.0

![VSCVersion](https://user-images.githubusercontent.com/62674463/93391617-79e58580-f83d-11ea-8ff9-b8ef6d05193f.JPG)

**VS Code Version**: 1.49.0

**SFDX CLI Version**: v49.9.0

**OS and version**: Win 10

**Comment by lcampos** [comment]
Hi @wescoturf , I think this might be a problem at the Salesforce CLI level and not specific to the VSCode extensions. Do you get the same results if you run the retrieve command from the terminal ?

**Comment by wescoturf** [comment]
I'm the web admin learning Salesforce. I work with a programmer who may be able to help me more, but we've never used the commands from the terminal. Can you point me where I would go to get the correct commands to try this?

Thank you

**Comment by yuki327** [comment]
Hi @wescoturf 
I am experiencing the same thing as you described. Please let me know if you found the solution. 
Thank you

**Comment by smaddox-sf** [comment]
Hi @wescoturf - [Here's a link to a trailhead about the CLI](https://trailhead.salesforce.com/en/content/learn/modules/cli-basics?trail_id=set-up-your-workspace-and-install-developer-tools).  You can access it from the Terminal within VS Code or natively on your machine.

Can you or @yuki327 try executing the commands via the CLI and share the output?  Do you get the same results?  We currently don't have enough information to try to investigate this.

Also, I wanted to surface another resource: This repository is owned by a team responsible for building & delivering Salesforce Developer Tools.  We engage regularly with the community for input on potential features, feedback on existing features and bug reports.  **When learning and ramping up, a better place to ask questions is our [Trailblazer Community](https://trailblazers.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1).**  The DX community group lets you tap into the knowledge of thousands of fellow Trailblazers and Salesforce experts.

We are happy to try to pin down this issue if either of you can share more info.

**Comment by yuki327** [comment]
Thank you@ smaddox-sf 
when I tried executing the commands via the CLI, I do get the same results.   I noticed on my machine, salesforce-alm is outside of salesforcedex directly.  does this matter?

**Comment by wescoturf** [comment]
This was closed yet yuki327 did provide the information asked for and asked a question. The update from 1.49 to 1.49.1 seems to have triggered this issue. My colleague allowed that update and then his install started having the issue. We both tried updating to 1.49.2 but it didn't help. We found a workaround for our needs for now - we use the org browser to retrieve and the explorer to deploy.

**Comment by yuki327** [comment]
Thank you for adding more info @ wescoturf!

**Comment by lcampos** [comment]
>I noticed on my machine, salesforce-alm is outside of salesforcedex directly. does this matter?
Yes, this means that you are overriding the code shipped as part of the salesforce-alm module in the Salesforce CLI. Can you try uninstalling that plugin and just having the normal up-to-date Salesforce CLI ?

**Comment by yuki327** [comment]
@lcampos  Thank you for your reply.  I tried with a different machine with a fresh install Salesforce CLI but I still see the same issue.. :(

**Comment by lcampos** [comment]
@yuki327 can you share the output of running `sfdx plugins --core` and which OS you're on ?

**Comment by yuki327** [comment]
@lcampos  I tried with both Mac and Window 
and several on my team is experiencing the same too

<img width="349" alt="Screen Shot 2020-10-01 at 10 33 45 PM" src="https://user-images.githubusercontent.com/6685906/94885705-85889d00-0436-11eb-8afa-e386ee4911d3.png">
