### ISSUE TITLE
Salesforce extension not work in Windows 10, not giving auto complete options, hover, and other productive items of VSCode

### ISSUE THREAD

**Issue by gyadav4** [forcedotcom/salesforcedx-vscode#2540]
# Summary

Salesforce Extension, doesn't use to give any productive features in Windows 10.
1. Auto Complete
2. Hovering definition 
3. Ctrl+Click, taking to variable definition  

### Expected result

All the Vs Code productivity feature should work

_Describe what should have happened_.

### Additional information

Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
![image](https://user-images.githubusercontent.com/29378942/93427422-6d176f00-f8db-11ea-877b-2b2f37ca5561.png)

Name: Salesforce Extension Pack
Id: salesforce.salesforcedx-vscode
Description: Extensions for developing on the Salesforce Platform
Version: 49.10.0
Publisher: Salesforce
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

**Comment by smaddox-sf** [comment]
Hi @gyadav4 - What metadata types are you working with?  have you refreshed SObject definitions as described [here](https://developer.salesforce.com/tools/vscode/en/apex/writing/#code-smartness-for-sobjects)?

Are the extensions fully activating upon start-up?

**Comment by gyadav4** [comment]
Hi,
It is happening for all type of metadata Apex, LWC, aura. Yes extensions
loading but sometimes crashing on startup.

**Comment by smaddox-sf** [comment]
Thanks for clarifying @gyadav4 .  It sounds like the extensions are not fully activating some of the time.  We have an issue logged as #2295 .  Can you check out that issue and confirm it's the same as you are experiencing?
