### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kashmira786** [forcedotcom/salesforcedx-vscode#2546]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.10.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\kanis\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jefersonchaves** [comment]
@Kashmira786 : please add the file from your machine `C:\Users\kanis\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`. This will help Salesforce team to figure out what is going on.

**Comment by snafuy** [comment]
I was directed here by a VS Code dialog.
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5247692/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by Kashmira786** [comment]
[Uploading salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt…]()
