### ISSUE TITLE
LWC language server errors

### ISSUE THREAD

**Issue by freddie1729** [forcedotcom/salesforcedx-vscode#2570]
### Summary

An error is thrown in the Output section of VS Code when editing a .js file.

`[Error - 12:13:16] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot destructure property 'delimiter' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
  Code: -32603 `

### Steps To Reproduce:

1. Install Salesforce Extension Pack
2. Go to an Aura Component
3. Edit the .js files
4. See this error in the Output: 

[Error - 12:13:16] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot destructure property 'delimiter' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
  Code: -32603 

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
Hi @freddie1729 thanks for opening this issue. I haven't been able to replicate this on our side, can you share the component you are using to run into this error or a sample project that consistently replicate this ?

**Comment by freddie1729** [comment]
Here is the js code that is causing it: 

`import { LightningElement, wire } from 'lwc';
import areRecordTypesBeingUsed from '@salesforce/apex/GISMetadataUpdateConfigCont.areRecordTypesBeingUsed';
import getExistingMetadataUpdateSettings from '@salesforce/apex/GISMetadataUpdateConfigCont.getExistingMetadataUpdateSettings';
import deleteSetting from '@salesforce/apex/GISMetadataUpdateConfigCont.deleteSetting';
import getAvailableGisObjects from '@salesforce/apex/GISMetadataUpdateConfigCont.getAvailableGisObjects';
import insertSetting from '@salesforce/apex/GISMetadataUpdateConfigCont.insertSetting';
import { refreshApex } from '@salesforce/apex';

const actions = [
    { label: 'Delete', name: 'delete' }
];

//TODO: get rid
const columns = [
    { label: 'Name', fieldName: 'objectName', hideDefaultActions: true },
    {
        iconName: 'utility:delete',
        type: 'action',
        typeAttributes: { rowActions: actions },
    }
];

export default class GisMetadataUpdateConfig extends LightningElement {
    columns = columns;
    record = {};
    showWarning = false;
    selectedObject = '';
    metadataUpdateSettings;
    settings = [];

    @wire(getExistingMetadataUpdateSettings)
    handleMetadataUpdateSettings(response) {
        if(response.data) {
            this.metadataUpdateSettings = response.data;
            for(let i = 0; i < response.data.length; i++) {
                const setting = response.data[i];
                this.settings.push({
                    id : setting.settingId,
                    objectName : setting.objectName,
                    handleDelete : event => {
                        const id = event.target.dataset.id;
                        this.deleteSetting(id);
                    }
                });
                this.settings = settings;
            }
        }
    }
    

    @wire(getAvailableGisObjects)
    options;

    @wire(areRecordTypesBeingUsed)
    showWarning;

    handleRowAction(event) {
        const actionName = event.detail.action.name;
        const row = event.detail.row;
        switch (actionName) {
            case 'delete':
                this.deleteRow(row);
                break;
            default:
        }
    }

    deleteSetting(settingId) {
        deleteSetting({ 
            settingId : settingId 
        }).then((result) => {
            this.refreshSettingList();
            this.refreshObjectOptions();
        }).catch((error) => {
            console.error(error);
        });
    }

    // deleteRow(row) {
    //     deleteSetting({ 
    //         settingId : row.settingId 
    //     }).then((result) => {
    //         this.refreshSettingList();
    //         this.refreshObjectOptions();
    //     }).catch((error) => {
    //         console.error(error);
    //     });
    // }

    handleAdd(event) {
        var objectName = this.selectedObject;
        insertSetting({
            objectName : objectName
        }).then((result) => {
            this.refreshSettingList();
            this.refreshObjectOptions();
            this.selectedObject = '';
        })
        .catch((error) => {
            console.error(error);
        });
    }

    handleObjectChange(event) {
        this.selectedObject = event.detail.value;
    }

    refreshSettingList() {
        refreshApex(this.metadataUpdateSettings);
    }

    refreshObjectOptions() {
        refreshApex(this.options);
    }

    get disableAddButton(){
        return this.selectedObject === '';
    }
}
`

**Comment by freddie1729** [comment]
It is happening on both LWC and Aura

**Comment by lcampos** [comment]
Thanks for providing feedback @freddie1729 , I'm closing this now since the fix is available on v50.7.0.
