### ISSUE TITLE
Request to update VScode's comparability with newer Java (JDK15)

### ISSUE THREAD

**Issue by TSGBrookfield** [forcedotcom/salesforcedx-vscode#2571]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by smaddox-sf** [comment]
This is not actionable for now, so closing. When there are updates to the version Apex runs on within the platform, we'll evaluate supporting more java versions
