### ISSUE TITLE
Unable to push changes to scratch org from VS code

### ISSUE THREAD

**Issue by amankr2626** [forcedotcom/salesforcedx-vscode#2576]
sfdx force:source:push 

ERROR running force:source:push:  This command can only be used on orgs that have source tracking enabled, such as sandboxes and scratch orgs.

Dev Hub >  Flag is enabled for source tracking
**VS Code Version**: 1.49.2

**SFDX CLI Version**: sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3

**OS and version**: Windows 10 

Unable to find sfdx: push changes to scratch org from the command palette

**Comment by lcampos** [comment]
Hi @amankr2626 , could you provide more details on your project setup. Have you already authenticated to the org using the CLI or VSCode ? Which command sequence are you using that we should follow so we can replicate this on our side ?
