### ISSUE TITLE
Extension does not respect VS Code settings for integrated terminal when executing CLI commands

### ISSUE THREAD

**Issue by cvinning1** [forcedotcom/salesforcedx-vscode#2577]
### Summary

VS Code allows various integrated terminal configurations in `settings.json`, when the extension executes Salesforce CLI commands (e.g., user clicks button or SFDX: Open Default Org), the process is forked as a child of VS Code directly, and bypasses any integrated terminal settings within VS Code.

_Short summary of what is going on or to provide context_.
This may or may not be intentional, but this configuration is important when developing in environments with overzealous security measures (if you've ever been a contractor for federal systems and forced to do development on a government-issued machine, you might be aware of these pains).

Developing in a system where the machine's execution policy is very strict, and the user profile does not have the permissions to override group policies on a system level--this includes system environment variables (PATH, HOME, etc) and must face vpn/proxies such as SSL inspection (yes, this proxy server even considers "localhost" as untrusted--this machine can't even _talk to itself_ over sockets) the only additional configuration we can achieve is on a running-user/session/process level.

A clever user can side-step this by using something like a git-bash terminal, and adding additional environment config inherited to all child-processes of the git-bash terminal process. If I add a new path to $PATH in .bash_profile, all child processes of the terminal will have the additional $PATH config attached to it.

VS Code adds options to its integrated terminal to achieve the same result. If VS Code is opened from the start menu, the parent process is the system and when you initialize an integrated terminal, the system is the parent process and profile of that terminal. The flag (Note: if gitbash is the default terminal, -l is not a valid option for cmd/powershell) `"terminal.integrated.shellArgs.windows": ["-l"]` to the integrated terminal shell args alleviates this. However, when the extension executes CLI commands on your behalf, the VS Code process is the parent and none of the integrated terminal config in settings is respected.

### Steps To Reproduce:
Environment: Windows 10
1.  Install Salesforce CLI, doesn't matter if it's the binary distributable or via npm, but for this example Salesforce CLI is installed via npm. `npm install -g sfdx-cli`
1.  The path to npm packages is typically `%appdata%\Roaming\npm`, make sure that is NOT in the system path. You are a user that cannot modify the system path.
1.  setup the necessary bash config files (.bashrc, .bash_history, .bash_profile) in $HOME, edit the .bash_profile file where you concatenate `%appdata%\Roaming\npm` (%appdata% is an alias for the actual path, copy and paste that path and add \Roaming\npm) to the end of the current path and save the file.
1.  verify sfdx is reachable. `which sfdx`
1.  Open vscode and open an integrated terminal. `sfdx` should not be reachable. If you edit VS Code's `settings.json` file and apply the following and save:
```
{
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "terminal.integrated.shellArgs.windows": ["-l"]
}
```
Killing the previous terminal and opening a new one, the `.bash_profile` is now respected by the integrated terminal. verify sfdx is reachable `which sfdx`

At this point, sfdx is a reachable command in the VS Code integrated terminal. However, it is not when the extension executes Salesforce CLI commands.

Try any command that executes `sfdx` with the CLI integration extension

### Expected result
Command invoked by the extension succeeds

### Actual result
Command invoked by the extension fails

_Describe what actually happened instead_.
'sfdx' is not a recognizable command. (the path to sfdx is not able to be resolved because the execution context is system-level--config that you as a user are pretending you cannot modify)

### Additional information
I am not at all experienced with developing extensions on VS Code. If I were, I'd probably submit a pull request myself. I don't know if VS Code supplies extension creators with an API that can hook into configurable items in VS Code's global `settings.json` or if this will take creating explicit extension settings reachable in the project root's `./.vscode/settings.json`.

The only way to get the extension to "respect" the user-profile execution's local config is to fork a VS Code process from the user's bash terminal with `code path/to/sfdx-project` which makes VS Code a child process of the terminal--implying that child-process inherits the parent-process environment. While this is fine for clever users, but unfortunately all users aren't lol

_Feel free to attach a screenshot_.

**VS Code Version**:
all
**SFDX CLI Version**:
all
**OS and version**:
Windows 10

**Comment by lcampos** [comment]
Thanks for opening this issue @cvinning1 . We've recently started moving away from depending on running the CLI in certain areas and will be expanding that in the upcoming releases. I wonder if these updates address the issues you are seeing. In the latest versions of the extensions the scaffolding commands do not use the Salesforce CLI (e.g. SFDX: Create Apex Class, SFDX: Create Project, etc). Could you tell us is you still run into those issues even with those changes ?
cc @smaddox-sf
