### ISSUE TITLE
SFDX commands are not working

### ISSUE THREAD

**Issue by rajthun** [forcedotcom/salesforcedx-vscode#2579]
Issue Type: <b>Bug</b>

Hi Team,

SFDX commands like Authorize org, retrieve & deploy are unresponsive and its keep on running for hours .  Also Salesforce extension pack is unresponsive and shows text as performance issues. Refer screenshot and Please do the needful.

![image](https://user-images.githubusercontent.com/71089507/94341166-f853db80-0024-11eb-9df0-6c9f3501c128.png)

Thanks

Extension version: 49.11.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.65GB free)|
|Process Argv|--crash-reporter-id d39c7481-d5bb-4584-a1e8-dc84328e7ec8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment]
Hi @rajthun thanks for logging this. I haven't been able to replicate this issue on my Windows machine. Could you provide more details on your setup e.g. how much RAM, which processor you are using. Also, is this something you are experiencing with any project or with a particular one.

**Comment by rajthun** [comment]
HI Campos,
Here are my system details. The issue is same for every Salesforce project that i have created in VS code.

![image](https://user-images.githubusercontent.com/71089507/94907355-a5af6f00-04bd-11eb-9d78-8eb98dc85b65.png)

Thanks

**Comment by mohanraj-r** [comment]
@rajthun This issue is being tracked in https://github.com/forcedotcom/salesforcedx-vscode/issues/3198
