### ISSUE TITLE
auto completion is not working in Lightning web component HTML file

### ISSUE THREAD

**Issue by leoraturi** [forcedotcom/salesforcedx-vscode#2584]
Auto completion is working in lightning component with HTML file , though auto completion is working fine in js file for wire function or property. 

1.Steps To Reproduce:
  enter foreach within template tag 

2.Expected result
  auto completion for each loop in. Just watched a video on trailhead live where auto completion is working on mac machine(https://trailhead.salesforce.com/live/videos/a2r3k000001n24P/simplified-development-with-modern-tools) for html file

3. Actual result
Not showing auto completion 

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.49.2

**SFDX CLI Version**: 7.74.1-32db2396ed
![NotworkingForhtmlfile](https://user-images.githubusercontent.com/26020270/94349499-1b8e8300-0045-11eb-8666-8cc87377130a.png)
![working for js file](https://user-images.githubusercontent.com/26020270/94349504-221cfa80-0045-11eb-96fd-520d0bcd1472.png)

**OS and version**: Windows 10 Pro :10.0.18362

**Comment by lcampos** [comment]
Thanks for logging this @leoraturi , this is a bug we recently fixed in the lightning language server and will be part of the following release.

**Comment by lcampos** [comment]
The fix for this was released as part of version 50.1.0 of the extensions. Thanks for providing feedback @leoraturi
