### ISSUE TITLE
Not able to deploy source to org

### ISSUE THREAD

**Issue by yangr0615** [forcedotcom/salesforcedx-vscode#2588]
Issue Type: <b>Bug</b>

when I tried to deploy one of the apex class to my salesforce sandbox, I got this error message UNKNOWN_EXCEPTION.  sf:UNKNOWN_EXCEPTION: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 508427120-81803 (1757138810)

Extension version: 49.11.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment]
Hi @yangr0615 this is an error thrown by the server because of potentially incorrect Apex code. Depending on what you are trying to do with Apex you might find some answers for this error in the forums.

I'll go ahead and close this since it's unrelated to an error with the tools provided.

**Comment by yangr0615** [comment]
Hi，

I retrieved the source from SFDC and then deploy it, so there shouldn't be
any issues with it, as it is already working in SFDC.

Please advise.

Thanks !
