### ISSUE TITLE
Apex Test runner error exit code 100

### ISSUE THREAD

**Issue by banderson5144** [forcedotcom/salesforcedx-vscode#2597]
### Summary

When running any Apex Tests, it errors out with an exit code 100

### Steps To Reproduce:

1. Select any Apex test to be ran from the Test Runner in VS Code

### Expected result

Run selected test(s) and run successfully.

### Actual result

Process errors out with an exit code 100

![image](https://user-images.githubusercontent.com/2395774/94879647-d399a280-042e-11eb-890a-ef858fa290dd.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.49.2

**SFDX CLI Version**: 7.75.0

![image](https://user-images.githubusercontent.com/2395774/94879616-be247880-042e-11eb-9ab0-8f9d8ed53ec0.png)

WIndows 7 64 Bit

**Comment by rajeshduggal** [comment]
@banderson5144 Try running the sfdx command without the --codecoverage argument.

**Comment by banderson5144** [comment]
@rajeshduggal While that does work, I want that option to remain so I can leverage the VS Code functionality of showing lines covered / not covered

**Comment by rajeshduggal** [comment]
@banderson5144 Yes, me too! I noticed the same exit 100 error today. And happened to notice it doesn't show when I exclude the codecoverage option.  I haven't had time to investigate it further yet.  If you happen to figure it out please post the solution. Much appreciated!

**Comment by pozil** [comment]
Sorry, no clue about that. The problem is likely on the server side, maybe a timeout?
The CLI team is best placed to investigate.

**Comment by AnanyaJha** [comment]
Hi @banderson5144 thanks for reporting this! Do you mind updating to the latest version of the extensions and the CLI and running the test again? We haven't been able to repro this issue yet, so let us know if you're still seeing the error and we'll keep digging!

**Comment by smaddox-sf** [comment]
Closed due to no updates.
