### ISSUE TITLE
Code Coverage Calculator fails after URL in multiline comment.

### ISSUE THREAD

**Issue by codefriar** [forcedotcom/salesforcedx-vscode#2599]
### Summary

When a multi-line comment includes a fully qualified hyperlink, code coverage calculation stops after the URL. I noticed this working on Apex-recipes (can provide access to the repo on request as it's not yet public) my `SOQLRecipes` class had a suspiciously low code coverage (47%) when I knew it had more. (Every method is tested). I noticed that the code coverage stopped showing after the comment with the URL in it.

### Steps To Reproduce:

1.  Use this example code of a class - truncated class to demonstrate issue.
```apex
public inherited sharing class SOQLRecipes {
    /**
     * @description Demonstrates how to loop over a SOQL query
     *
     * Note: This method has a false-positive PMD warning. Our Query
     * includes the keyword 'WITH SECURITY_ENFORCED' which prevents this
     * Query from accessing fields and objects that they don't have permission
     * to access. This is a form of inline CRUD/FLS Check.
     *
     * @return integer
     **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static integer queryMassiveNumberOfRecordsReturningCount() {
        Integer count = 0;
        /**
         * You'll see this pattern, called a SQOL for loop used
         * whenever you're iterating over a massive number of rows.
         * Doing a SOQL for loop like this helps you avoid hitting
         * Heap limits. Find out more here:
         * https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_loops_for_SOQL.htm
         */

        for (Account acct : [SELECT Name FROM Account WITH SECURITY_ENFORCED]) {
            count++;
        }
        return count;
    }
```

1. Use this test code:
```apex
@isTest
private class testTest {
  @isTest
    static void testCountOfLargeDataVolumesPositive() {
        /**
         * this next line is a feature of the trigger handler in use
         * it demonstrates the kinds of gotcha's you can hit when testing large data volumes
         * in this case we need 3k accounts - but inserting them means running two triggers
         * Creating those 3k accounts exceeds our CPU governor limit. By inserting after
         * setting the TriggerHandler bypass for accountTriggerHandler, the trigger framework will
         * skip that particular set of triggers.
         */
        TriggerHandler.bypass('AccountTriggerHandler');
        List<Account> testAccounts = (List<Account>) TestFactory.createSObjectList(
            new Account(),
            3000,
            true
        );

        System.assertEquals(
            [SELECT Id FROM Account].size(),
            3000,
            'expected to have created 3k records'
        );
        Test.startTest();
        Integer count = SOQLRecipes.queryMassiveNumberOfRecordsReturningCount();
        Test.stopTest(); // forces all asych work to complete
        System.assertEquals(count, 3000, 'Expected to find 3k records');
    }
}
```

In case this code doesn't express the bug, let me know, I can provide you full copies of both the class and test.

### Expected result

Code coverage should have been reported at 100%, not 46%

### Actual result

Code coverage reported 46%. Additionally, VSCode stopped showing code coverage after the URL.

### Additional information

**VS Code Version**:
1.49.3

**SFDX CLI Version**:
sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3

**OS and version**:
Mac os Catalina (10.15.7)

**Comment by randi274** [comment]
Hi @codefriar - thanks for reporting this! After running a quick test with the code you provided, it appears this issue has now been resolved (only 1.5 years too late!). Are you still finding this to be a problem?
<img width="1041" alt="Screen Shot 2022-04-01 at 11 06 56 AM" src="https://user-images.githubusercontent.com/9795193/161318428-ea30ee28-5a02-47a1-93fb-8a5b1bf22727.png">
