### ISSUE TITLE
Salesforcedx-vscode-core: Detect Conflicts At Sync NOT WORKING

### ISSUE THREAD

**Issue by DaniyelShchuritz** [forcedotcom/salesforcedx-vscode#2604]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. I've enabled the Detect Conflicts At Sync in my VS Code
![image](https://user-images.githubusercontent.com/12122190/95328583-a9683a80-089d-11eb-9a4f-10385d3118f4.png)
2. Changed the apex class directly on the org via developer console and saved it
3. Change the same class locally with my VS Code
4. Deployed the local version of the class by running the following command (sfdx force:source:deploy -x manifest/Sprint.xml -u myOrgAlias --verbose)

### Expected result

I was expecting for the VS Code to notify me that there is a different version of the file on the org and that I should retrieve the file first before deploying.

### Actual result

The command (sfdx force:source:deploy -x manifest/Sprint.xml -u myOrgAlias --verbose) was executed successfully without notifying me and my local version overwrote the version of the class in the org.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version: 1.49.3

**SFDX CLI Version**:
sfdx-cli/7.75.0-5521f40d11 darwin-x64 node-v12.18.3

**OS and version**:
macOS Catalina
Version: 10.15.7 (19H2)

**Comment by ralphcallaway** [comment]
@smaddox-sf any updates on this?

**Comment by smaddox-sf** [comment]
@ralphcallaway - Conflict Detection is an optional feature you can use in VS Code.  After turning on the setting as you indicated in the description, you must use the command palette or right-click options for the Deploy command.  If you execute a deploy directly from a command line, it does not try to do conflict detection.

**Comment by ralphcallaway** [comment]
@smaddox-sf this isn't my issue, i'm guessing you meant to flag that for @DaniyelShchuritz 

Fwiw, you might want to consider updating the documentation for the flag. It's saying that it will do it for "fource:source:deploy with manifest", which is exactly what daniel was doing. A simple "Enable conflict detection" would be better and avoid people expecting that they can use the sfdx client in a project folder and expect this behavior.

**Comment by smaddox-sf** [comment]
Whoops!  Thanks for correcting my mistake @ralphcallaway and for the feedback.  We have an update coming this week to update the setting description to make it clearer.
