### ISSUE TITLE
Push does not show error messsages - Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#2609]
### Summary

I ran push command using the extension and it did not work. It does not show the error message.

![image](https://user-images.githubusercontent.com/55927613/95449463-bac44c00-095c-11eb-9843-387cb057a2b7.png)

### Steps To Reproduce:

1.  Push some Objects and fields using Push command
2. Add a new field directly from vscode, without opening the salesforce UI. Copy one of the fields that already exists and was deployed on the step one, but change its API name so it can be a new field. Then run push again using the extension and verify it does not work and also does not show error messages.

### Expected result

The output should display what is wrong.

### Actual result

The output does not show what is wrong.

### Additional information

**VS Code Version**:  1.49.3

**SFDX CLI Version**:  sfdx-cli/7.75.0-5521f40d11 win32-x64 node-v12.18.3

**OS and version**: Windows 10

**Comment by lcampos** [comment]
Thanks for opening this issue @AllanOricil . Can you confirm if this is exclusive to sobject fields or does it also happen with other metadata types ? Also, is this exclusive to running the source:push command from VSCode or do you also see this problem when directly calling the command from the terminal (I'm trying to understand if the problem is with the extensions or the cli) ?

**Comment by AllanOricil** [comment]
@lcampos it was a mistake that I did. When I cloned one of the fields I forgot to properly set its name. Then, just because of that file, sfdx was not able to give me a proper output message. It would be good if at least it could tell the developer which files were with problems.
After I fixed that name of the file, everything worked as expected.
I just pushed with the extension. But in the terminal I can see that the extension only issued the sfdx push command. Which led me to conclude it was an sfdx problem.

**Comment by smaddox-sf** [comment]
Hi @AllanOricil - Thanks for the additional info and I'm glad you're unblocked.  We'll look at adding better error messaging

**Comment by lcampos** [comment]
I think this was related to issue https://github.com/forcedotcom/cli/issues/674 which has been fixed and I can't replicate it using the latest version of the CLI (7.78.1). Thanks for providing feedback.

**Comment by AllanOricil** [comment]
@smaddox-sf
