### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by viswanathSamuel** [forcedotcom/salesforcedx-vscode#2620]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex-replay-debugger`
- Extension Version: `49.13.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.50.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not enough info to troubleshoot
