### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AlluriKeerthi98** [forcedotcom/salesforcedx-vscode#2623]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lightning`
- Extension Version: `49.13.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.50.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
not enough info to investigate
