### ISSUE TITLE
Error re-indexing workspace: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mattmccafferty** [forcedotcom/salesforcedx-vscode#2624]
### Summary

Retrieve source from manifest for a package org. Aura Components v49.13.0 (salesforce.salesforcedx-vscode-lightning) returns an error:
Error re-indexing workspace: Cannot read property 'indexOf' of undefined

sfdx-cli/7.75.1-5585088c75 win32-x64 node-v12.18.3

@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-help 2.2.3  
└─ @oclif/plugin-update 1.3.9

![2020-10-13 10_51_30-Extension_ Aura Components - Axiom-PackageOrg - Visual Studio Code](https://user-images.githubusercontent.com/60145991/95884739-166a4d00-0d42-11eb-89db-4e9c48dae371.png)

**Comment by AnanyaJha** [comment]
Hi @mattmccafferty thanks for reporting this! Can you confirm whether you're seeing this issue with the latest versions of the Extensions and CLI? Run `sfdx update` to update your CLI and click on the Marketplace icon and update the Salesforce Extensions

**Comment by lcampos** [comment]
Closing this since the fix is available on v50.7.0, thanks @mattmccafferty for providing feedback.
