### ISSUE TITLE
LWC language server throws error "Cannot destructure property 'delimiter' of (intermediate value) as it is undefined"

### ISSUE THREAD

**Issue by lcampos** [forcedotcom/salesforcedx-vscode#2636]
### Summary

Highlighting elements of an Aura component causes the LWC language server to throw error "Cannot destructure property 'delimiter' of (intermediate value) as it is undefined"

### Steps To Reproduce:

1. Use project: https://github.com/alechko/sfdx-test.git
1.  Open an Aura component (.cmp file)
1.  Highlight some attributes on the aura:component tag
1. Open the Output terminal and select LWC Language Server

### Expected result

No errors to be thrown

### Actual result
The language server throws "Cannot destructure property 'delimiter' of (intermediate value) as it is undefined"

### Additional information

![repro-lwc-error](https://user-images.githubusercontent.com/1041842/96165000-e69d7f80-0ed0-11eb-9d1a-a9ba5d9b462c.gif)

**VS Code Version**: 1.49.1

**SFDX CLI Version**: 7.75.1

**OS and version**: Mac OS Catalina

**Comment by az-oolloow** [comment]
I am experiencing the same in LWC proper (not using Aura). It is especially annoying as it causes the Output pane to switch to the LWC Language Server when I totally don't care about that output

**Comment by gotstu** [comment]
Same here. Extremely annoying! Thanks:)

**Comment by Stassy** [comment]
Can confirm, very annoying!
Ready to test beta version if needed.

**Comment by lcampos** [comment]
Closing this since the fix is available on v50.7.0.
