### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ofloresmx** [forcedotcom/salesforcedx-vscode#2641]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.1.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not enough info to troubleshoot.  Feel free to [open a new issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?template=Bug_report.md) with more details.
