### ISSUE TITLE
Deploy process bar is stuck if deploy a class file without respective .cls-meta.xml file

### ISSUE THREAD

**Issue by gtiancai** [forcedotcom/salesforcedx-vscode#2646]
### Summary

Deploy process bar is stuck if deploy a class file without respective .cls-meta.xml file.
I know this should not be an correct scenario, but sometimes, we will hide .cls-meta.xml in VS Code so to limit the files to show.
If deploy with CLI directly, it will show errors that the XML file is missing.

### Steps To Reproduce:

1.  create a SFDX project and log into a Org
2.  create a class file manually(or delete the .cls-meta.xml file)
3. deploy it to org

### Expected result

Show some error

### Actual result

Deploy bar is always in-progress.

### Additional information

**VS Code Version**:
1.50.1
**SFDX CLI Version**:
7.56.1
**OS and version**:
Win 10

**Comment by sc5148** [comment]
@gtiancai As a workaround you can use the below JSON in your settings.json file to hide the meta files instead of deleting them. However this doesn't solve the other half of the issue (to be able to deploy a class file which is created manually).

`"files.exclude": {
        "**/*.cls-meta.xml": true,
        "**/*.cmp-meta.xml": true,
        "**/*.component-meta.xml": true,
        "**/*.page-meta.xml": true,
        "**/*.resource-meta.xml": true,
        "**/*.trigger-meta.xml": true
    }`

**Comment by gtiancai** [comment]
@sc5148 However, the point here is 'the other half'.

**Comment by floralan** [comment]
@gtiancai  Work item @W-8271243@ had been created for this issue. We will work on the fix shortly and please stay tuned.

**Comment by AnanyaJha** [comment]
Hi @gtiancai ! This issue should now be resolved. Please open a new issue if you're still facing any problems, thanks!
