### ISSUE TITLE
Publish .vsix file to open-vsx.org registry

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/salesforcedx-vscode#2650]
**Is your feature request related to a problem? Please describe.**
I would like to use the Salesforce Extension Pack (for VS Code) in other IDEs which support the VSX extension format (eg Gitpod).

**Describe the solution you'd like**
At each release, publish the .vsix file of the Salesforce Extension Pack (or its individual components) to open-vsx.org as described here : 
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Describe alternatives you've considered**
Manual work

**Additional context**
Open VSX is an initiative by the Eclipse Foundation : 
https://github.com/eclipse/openvsx
https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php

**Comment by AllanOricil** [comment]
It would be very cool to have them there. Im testing my extension in Gitpod and I could do the same for the Salesforce ones.

**Comment by carole-bennett-healthgrades** [comment]
We're looking at ways to improve and standardize our SF developer environments, and shorten ramp-up time; the ability to install these extensions in a a gitpod instance would help tremendously with that.

**Comment by AllanOricil** [comment]
Up

**Comment by alexdohmen** [comment]
Hey, would be cool if we could add the extensions also to open-vsx.org Any ideas on this?

**Comment by Clint-Chester** [comment]
Would be very beneficial 😄 is there an update on this?

**Comment by gbockus-sf** [comment]
Feature request tracked in https://github.com/forcedotcom/salesforcedx-vscode/discussions/3877
