### ISSUE TITLE
Salesforce CLI extension issue

### ISSUE THREAD

**Issue by sunidhar** [forcedotcom/salesforcedx-vscode#2652]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.1.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning: 

When running the CLI I'm facing below error

Error running command sfdx.force.source.retrieve.component: data.forEach is not a function. This is likely caused by the extension that contributes sfdx.force.source.retrieve.component.

**Comment by jakekarlibm** [comment]
I've been experiencing the same issue the past couple of days on Mac. You can download them individually but not all at once

**Comment by smaddox-sf** [comment]
I'm not clear on the steps to reproduce.  Can you [open an issue on the CLI repo](https://github.com/forcedotcom/cli/issues/new?assignees=&labels=&template=bug_report.md&title=) with the full details?
