### ISSUE TITLE
"SFDX: Open Default Org" shows "Salesforce CLI not installed", running the same command in terminal works

### ISSUE THREAD

**Issue by achere** [forcedotcom/salesforcedx-vscode#2654]
### Summary

"SFDX: Open Default Org" shows "Salesforce CLI not installed", running the same command in terminal works

### Steps To Reproduce:

1.  From an SF project run "SFDX: Open Default Org"

### Expected result

Default Org opens in the browser

### Actual result

Salesforce CLI shows the output:
```
4:46:52.668 sfdx force:org:open
14:46:52.700 sfdx force:org:open
 Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli
```

### Additional information
I ran into a similar problem, but when enabling a specific setting, it was gone #2653 

### Screenshots

<img width="363" alt="Screenshot 2020-10-22 at 14 50 59" src="https://user-images.githubusercontent.com/7329670/96868208-6352cf80-1476-11eb-8aa4-91786fbcf1a1.png">
<img width="376" alt="Screenshot 2020-10-22 at 14 51 16" src="https://user-images.githubusercontent.com/7329670/96868220-677eed00-1476-11eb-934f-914839f11806.png">

**VS Code Version**:  1.50.1

**SFDX CLI Version**: 7.76.1-f301d5641f darwin-x64 node-v12.18.3

**OS and version**: macOS Mojave 10.14.5 18F132 x86_64

**Comment by smaddox-sf** [comment]
Hi @achere - Thanks for reaching out.  Couple questions:
1.  Have you already authorized an org before you are executing the `Open Default Org` command?

2. Are you using the experimental deploy/retrieve?  You can opt in via this extension Preference from VS Code settings:
![image](https://user-images.githubusercontent.com/59572234/97335171-c196fe00-183a-11eb-8f3a-641448443a98.png)

**Comment by achere** [comment]
Hi @smaddox-sf !
1. Yes, I have. The command itself works if typed in the terminal.
2. Yes, this setting is enabled. It solved #2653, but not this one.

**Comment by DannyAllegrezza** [comment]
@achere I experienced a similar issue. The fix was to uninstall the Salesforce Extension Pack, close VS Code, re-open and re-install the extension pack. Once I did this, everything started working again 🤷‍♂️

**Comment by brpowell** [comment]
Hi @achere. The extensions check for the CLI presence by examining the system's PATH variable. It could be the case that after installing the CLI VS code needs to be fully exited and opened again to be able to pick up the presence, although you may have already tried this.

Also, which version of the extensions are you on?

**Comment by achere** [comment]
Hi @brpowell!
I mentioned in the original post that I'm on version 7.76.1-f301d5641f darwin-x64 node-v12.18.3. Sure I have tried re-starting VSCode, but alas to no avail.
You mentioned it is checking in PATH - but do you know how exactly and where exactly in the code is this check? Maybe I can replicate this check manually and get some insight into why it fails. I'm not really familiar with the API used in VSCode to execute the commands and how the extension codebase is organized.

**Comment by brpowell** [comment]
Ah sorry, I meant the version of the extensions not the CLI - you can check by opening the vscode marketplace and looking for the version under the extension pack. Here is a link to where the check happens in code:

https://github.com/forcedotcom/salesforcedx-vscode/blob/31729819d6440f69f9be68ad1221b58e0d1187ed/packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts#L22

Did you install the CLI with the installer [here](https://developer.salesforce.com/tools/sfdxcli), or did you install it via npm globally?

**Comment by godarapradeep** [comment]
I have the exact same issue for about a week now, it was working great before. Tried multiple restarts, uninstall install but no luck. Please help.

VSCode:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Salesforce Extension Pack 
Version: v50.5.0

Salesforce CLI version
VERSION sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3

**Comment by jehicks2** [comment]
I am experiencing the same issue. I can run the commands in terminal, but when I attempt to do **SFDX: Authorize an Org** I get an output of Salesforce CLI is not installed. This is so weird to me because I can run **SFDX: Create a Project** and it creates a project, but a few commands do not run. 

Result in Output after running 'SFDX: Authorize an Org':
<img width="910" alt="Results after running SFDX: Authorize an Org in command palette, error that says Salesforce CLI is not installed" src="https://user-images.githubusercontent.com/10644304/100285194-b3b5c500-2f2d-11eb-9b6d-a6fde9f36e05.png">
