### ISSUE TITLE
Apex LangServer/DB Crashes consistently

### ISSUE THREAD

**Issue by Confirm4Crit** [forcedotcom/salesforcedx-vscode#2659]
### Summary

Pretty consistently get the linked log on the Apex terminal, lose all Run Test/Code Lens-y annotations in vscode, along with any sort of autocomplete.

https://gist.github.com/Confirm4Crit/6494313b425b66dd87a734f58ed7dbe8

I can delete the apex.db and reproduce in next session.

I can also recreate in a workspace with *only* SF Vscode extensions.

### Steps To Reproduce:

1.  Go throw this into vscode <https://github.com/jongpie/ApexUuid/blob/master/src/classes/Uuid.cls>
2.  Note logs, they *should* look like this. <https://gist.github.com/Confirm4Crit/6494313b425b66dd87a734f58ed7dbe8>

### Expected result

Not....that.

### Actual result

Apex Lang sad :(.

### Additional information

**VS Code Version**:

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

Ver v50.1.0 of Salesforce Extensions.
**SFDX CLI Version**:
sfdx-cli/7.77.0 darwin-x64 node-v14.5.0 (I recently updated, but it was happening on older versions
**OS and version**:
OS: Darwin x64 19.6.0

**Comment by Confirm4Crit** [comment]
using `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`

**Comment by smaddox-sf** [comment]
Hi @Confirm4Crit - Thanks for reaching out on this and for all the great detail.  These issues are difficult to repro, so appreciate all the information you collected.  We will try to repro this and see if we can pin down the issue.

**Comment by Confirm4Crit** [comment]
Sounds good, when I get the chance, I'll fiddle with the newer extensions and see if it's changed result at all.

**Comment by brpowell** [comment]
Thanks for reporting @Confirm4Crit, I'm trying to repro this issue and have a couple questions:

- Does this happen in a completely new project where the provided class is the only one present?
- When do these errors get thrown? As soon as you launch a session and the indexing completes, or when trying to use language server features like autocomplete, go to definition, etc.

**Comment by Confirm4Crit** [comment]
So, tried a new scratch org, with that class, couldn't reproduce.
Tried a new manifest project with that class, couldn't reproduce.
Pulled down my company's repo to a new dir, couldn't reproduce *until* I assigned the project a connection, then I got those errors *only on that session*, opening any class, but UUID first.

So far, besides that, I haven't been able to reproduce this consistently.
![image](https://user-images.githubusercontent.com/3483618/98379992-fa428e80-2015-11eb-8e3e-575a2ffc7644.png)
One thing I noticed is all my test classes/methods ^ have this twice? Not sure if that's something odd on the extensions.

**Comment by Confirm4Crit** [comment]
I'm going to spend this week on a new, from scratch project, and just see if that old one was hosed for whatever reason.

**Comment by Confirm4Crit** [comment]
Started doing it on new project too. :/

**Comment by sfsholden** [comment]
@Confirm4Crit Thank you for again all the details here. I haven't been able to reproduce the issue with the code sample provided. In reading your comments above, would you please clarify the following?

> So, tried a new scratch org, with that class, couldn't reproduce.
> Tried a new manifest project with that class, couldn't reproduce.
> Pulled down my company's repo to a new dir, couldn't reproduce _until_ I assigned the project a connection, then I got those errors _only on that session_, opening any class, but UUID first.

When you say 'I assigned the project a connection', are you referring to authorizing an org? And if so, what type of org was it? And was it a namespaced org?

> ![image](https://user-images.githubusercontent.com/3483618/98379992-fa428e80-2015-11eb-8e3e-575a2ffc7644.png)
> One thing I noticed is all my test classes/methods ^ have this twice? Not sure if that's something odd on the extensions.

I am not seeing this issue either. It this still showing today?

**Comment by Confirm4Crit** [comment]
The Run Test will sometimes dupe, sometimes not, sometimes not show at all.

I'm referring to assigning a default org to the project when I say *assign the project a connection*. 

Usually full sandboxes, but it happens in dev too.

It *is* funny you mention namespace, I also use Illuminated Cloud, and the IC plugin suddenly thought my codebase was namespace'd against Nebula (https://github.com/jongpie/NebulaLogger).

We had to dig into some config files to make IC stop thinking it was a namespaced connection, but we couldn't really figure out *why* IC thought that.

So I know my orgs aren't namespaced, but I've def messed with namespacing in sandbox/scratch orgs for funsies.
Could that be lingering somewhere in the sfdx-cli global configs?

**Comment by sfsholden** [comment]
@Confirm4Crit For these connections to the full sandbox, have you tried refreshing sobject definitions? (i.e. `SFDX: Refresh SObject Definitions`) I'd also be interested in knowing how many sobject definitions look like they are being brought down from the org.

For the namespace question - we have seen some behavior where the apex LSP doesn't behave correctly when a namespace is involved, but haven't heard of it causing a corrupted db before.

Also do you happen to have an answer for these questions below mentioned by @brpowell?
> * When do these errors get thrown? As soon as you launch a session and the indexing completes, or when trying to use language server features like autocomplete, go to definition, etc.

**Comment by Confirm4Crit** [comment]
> For these connections to the full sandbox, have you tried refreshing sobject definitions? (i.e. SFDX: Refresh SObject Definitions) I'd also be interested in knowing how many sobject definitions look like they are being brought down from the org.

Yea, fairly regularly. 
```
15:38:00.380 sfdx sobject definitions refresh
Fetched 495 Standard sObjects from default org
Fetched 329 Custom sObjects from default org
15:39:56.627 sfdx sobject definitions refresh
 ended with exit code 0
```
---
> When do these errors get thrown? As soon as you launch a session and the indexing completes, or when trying to use language server features like autocomplete, go to definition, etc.

Mostly when I'm opening or scrolling through a file, possibly autocomplete in theory.
Eventually I'll just open some file, and it craters.
---
> For the namespace question - we have seen some behavior where the apex LSP doesn't behave correctly when a namespace is involved, but haven't heard of it causing a corrupted db before.

Anyway to make sureeee this isn't happening accidentally somehow? If one of my orgs had a namespace, 💣  ?

**Comment by Confirm4Crit** [comment]
Got a different error this time~
https://gist.github.com/Confirm4Crit/5c109862af36468f110d6a0aeb61b5da
After that error, I went from 2 `Run Test` lenses on every test method, to 1.
Seems to be a bit more consistently erroring.

**Comment by sfsholden** [comment]
@Confirm4Crit If the org did have a namespace, there are some known issues when it comes to autocompletion.

Thank you for all of this information. I'm going to be opening this up as a bug.

**Comment by Confirm4Crit** [comment]
Any update on this? Still occurs on my side.

**Comment by smaddox-sf** [comment]
Hi @Confirm4Crit - We have a bug open but haven't been able to repro.  We'll post any other questions or otherwise update the issue when we have a fix

**Comment by Confirm4Crit** [comment]
Sounds good, totally down for a screen share if it helps. 👍🏼

**Comment by randi274** [comment]
Hi @Confirm4Crit - we're going through our backlog, and wanted to check in on this. Is it still a reproducible issue for you?

**Comment by Confirm4Crit** [comment]
I'm no longer at the organization it was occurring at. So technically, no~.
