### ISSUE TITLE
Cannot retrieve files from installed package on Trailhead Playground

### ISSUE THREAD

**Issue by tkutler** [forcedotcom/salesforcedx-vscode#2662]
Summary
Retrieve Source from Org returns "No results found"

Steps To Reproduce:
Create a new project using Create Project with Manifest. I am unable to retrieve files from unlocked package "04t6g000008ateoAAA"

Right click package.xml -> Retrieve source from org and it fails with
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

Updated sfdx-project.json as follows

{
"packageDirectories": [
{
"path": "force-app",
"default": true
},
{
"path": "manifest"
}
],
"namespace": "",
"sfdcLoginUrl": "https://login.salesforce.com",
"sourceApiVersion": "47.0"
}

Right click package.xml -> Retrieve source in manifest from org
=== Retrieved Source
Only files I created and pushed
Expected result
Expecting all files including ones from unlocked package that I installed in Playground

Actual result
=== Retrieved Source
No results found

**Comment by lcampos** [comment]
Hi @tkutler , retrieve from manifest only retrieves the metadata specified on it. Have you added the unlocked package metadata to your package.xml ?

**Comment by tkutler** [comment]
I thought it would retrieve all my LWC and other types of files in the
package.xml from the org. How would I add the unlocked packages metadata to
the package.xml file? I have not done that.

**Comment by smaddox-sf** [comment]
Hi @tkutler - When using a manifest, only the metadata specified in the package.xml will be retrieved (or deployed).  This gives you full control. Here's a couple resources on building package manifests:
 - https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_package.htm
 - https://trailhead.salesforce.com/content/learn/modules/package-xml

When learning and ramping up, a better place to ask how-to questions is our [Trailblazer Community](https://trailblazers.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1).  The DX community group lets you tap into the knowledge of thousands of fellow Trailblazers and Salesforce experts.  In this repo, we are focused on feedback on the extensions and reports of bugs in the extensions.

**Comment by tkutler** [comment]
But shouldn't this code in my package.xml retrieve all LWC in my org?

<types>
<members>*</members>
<name>LightningComponentBundle</name>
</types>

It didn't pull any of the LWC created in the installed package only the LWC
I created myself

**Comment by lcampos** [comment]
@tkutler that's unfortunately not how the APIs work, when you are working with any type of package you need to explicitly add the name of the file/metadata to the package.xml. The * will not cover those pieces of metadata.

If my unlocked package is installed in my org and I want to retrieve an Apex Class or LWC component from it my package.xml will look like this:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>ExternalNlpDocumentEmotion</members>
        <name>ApexClass</name>
    </types>
    <version>50.0</version>
</Package>
```

**Comment by tkutler** [comment]
Thanks for the information. Why then does the manifest retrieve the LWC I
manually deployed to the org (using VS Code and SFDX) ?
