### ISSUE TITLE
Apex debugger session is not starting

### ISSUE THREAD

**Issue by rlankathil** [forcedotcom/salesforcedx-vscode#2666]
### Summary

 I have installed the latest version of VS code extension pack and trying to use the interactive debugger. However, the interactive debugger session Id is not starting as expected

### Steps To Reproduce:

1.  Launch apex interactive debugger after following the steps given in https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger
1.   Once launch it sows 
Connected to Streaming API channel /systemTopic/ApexDebuggerSystemEvent.
Connected to Streaming API channel /systemTopic/ApexDebuggerEvent.

But now show the Apex debug session stated with.....

### Expected result

Should starts debug session and continue interactive debugger

### Actual result

Does not start the debug session.

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/52041497/97103802-e40f0700-16d4-11eb-8db0-c0bd71d49bba.png)
![image](https://user-images.githubusercontent.com/52041497/97103811-f25d2300-16d4-11eb-9f5e-08977325dfb7.png)

**VS Code Version**: 1.36.1

**SFDX CLI Version**:  7.76.1

**OS and version**: Windows 10 Enterprise 18363.1082

**Comment by smaddox-sf** [comment]
Hi @rlankathil - Can you confirm you have a license for the Interactive Debugger?  If you don't, [the Replay Debugger](https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger) is a great alternative.
