### ISSUE TITLE
sfdx force:source:retrieve --manifest causing ERROR running force:source:retrieve:  path must not be empty

### ISSUE THREAD

**Issue by josepmathew1** [forcedotcom/salesforcedx-vscode#2667]
Hi,
I have been using VS Code version 1.50.1 with the Salesforce extension called "Salesforce Package.xml Generator Extension for VS Code:" for the last one year without any issues.
Since yesterday i am getting the below error when i run the command "SFDX: Retrieve Source in Manifest from Org".
The error i am getting is "ERROR running force:source:retrieve: path must not be empty".
This is a very urgent issue and i am not able to proceed with my Get DevOps process due to this . I am not able to retrieve data from Org into the local VS Code.
BTW I am using VS Code, Git and Salesforce Extension "Salesforce Package.xml Generator Extension for VS Code:"
i am using Salesforce Extension Pack version v50.2.0 in VS Code

**Comment by smaddox-sf** [comment]
Duplicate #2668
