### ISSUE TITLE
SAlesforce CLI Integration Extension issue

### ISSUE THREAD

**Issue by rahul123-tech** [forcedotcom/salesforcedx-vscode#2680]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.2.0`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not enough info to troubleshoot this.  Feel free to open a [new issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?template=Bug_report.md) with more info.
