### ISSUE TITLE
When using opening brace "{" in LWC js file autocomplete suggests component names as input.

### ISSUE THREAD

**Issue by cpgt-tpm-dev** [forcedotcom/salesforcedx-vscode#2681]
Screenshot:
![image](https://user-images.githubusercontent.com/63353363/97595917-7c262c80-1a04-11eb-8929-641a8d499283.png)

Doesn't happen without Lightning Web Components extension.

**Comment by smaddox-sf** [comment]
Thanks for reaching out on this @cpgt-tpm-dev .  We're working on a fix

**Comment by adrian-cg** [comment]
Was this issue supposed to be fixed in #2688? I uninstalled and reinstalled the extensions last night and I was still seeing this behavior.

Thanks for your help!

**Comment by lcampos** [comment]
@adrian-cg yes, that's the PR that fixes this issue but the change hasn't been released to the VSCode marketplace yet. It will be out as part of release 50.4.0 of the extensions.

**Comment by lcampos** [comment]
Closing since the fix has been released as part of version 50.4.0. Thanks for providing feedback.
