### ISSUE TITLE
Add ability to retrieve Profiles using Org-Browser

### ISSUE THREAD

**Issue by dvolk20** [forcedotcom/salesforcedx-vscode#2684]
We'd like the ability to retrieve profiles using the org browser feature in VS code. 

Without this ability, it is difficult pull in all the necessary dependencies to commit to GIT and deploy to additional environments with all items in tact (e.g., FLS).

**Comment by smaddox-sf** [comment]
Thanks for the feedback @dvolk20.  We don't have a performant way to support this today.  To expose profiles, we would have to retrieve every possible piece of metadata associated with it, which isn't feasible.  This is a limitation of the API and  I'll share this feedback with our API team. If there are changes in the API in the future, we'll consider it in VS Code down the road.
