### ISSUE TITLE
Anon Apex under VS Code not clearing error cache

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/salesforcedx-vscode#2689]
### Summary

Executing Anon Apex under VS Code reports errors that no longer exist

### Steps To Reproduce:

1.  Run a piece of Apex anonymously with an obvious error
1.  Fix that error, re-run the code

### Expected result

_Code should execute successfully_.

### Actual result

_Output panel shows an error still_.

### Additional information

_In this example, there is no longer a line 5, yet it is referenced by the error_.
![image](https://user-images.githubusercontent.com/2143167/97676745-fd270780-1a88-11eb-9cb4-2a4e7889e7c1.png)
Maybe related to https://github.com/forcedotcom/salesforcedx-vscode/issues/2608 ?

**VS Code Version**: 1.50.1

**SFDX CLI Version**: 7.77.0-112dd7d412

** VS Code Extensions version**: 50.3.0

**OS and version**:  Windows Server 2012 R2 Standard (long story...)

**Comment by robcowell** [comment]
Copy-pasting the exact same code to another VS Code tab and executing it works as expected.

**Comment by brpowell** [comment]
Fixed in v50.3.0
