### ISSUE TITLE
sfdx force:apex:log:get

### ISSUE THREAD

**Issue by monirkohi2006** [forcedotcom/salesforcedx-vscode#2696]
ERROR running force:apex:log:get:  
 Status from ApexLog Order By StartTimeDESC LIMIT 1
                              
ERROR at Row:1:Column:142
No such column 'StartTimeDESC' on entity 'ApexLog'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

Issue Type: Bug
Extension Name: sfdx-cli
Extension Version: 7.78.1-5a65d9dd2f
OS Version: macOS Catalina 10.15.6
VSCode version: 1.50.1

**Comment by lcampos** [comment]
Hi @monirkohi2006 , could you provide the steps needed to replicate this error you are running into ?

**Comment by monirkohi2006** [comment]
Type in "sfdx force:apex:log:get" in command line and hit enter. 

To learn more about the command type in " sfdx force:apex:log:get -h" and hit enter. 

![image](https://user-images.githubusercontent.com/32991357/98035805-ec023180-1dcd-11eb-9d56-fff818a71c02.png)

**Comment by monirkohi2006** [comment]
This issue should be reported in https://github.com/forcedotcom/cli. There is already a ticket open for this issue https://github.com/forcedotcom/cli/issues/715.
