### ISSUE TITLE
SFDX Vscode stopped working after update . Unable to find the issue . need help .

### ISSUE THREAD

**Issue by Tarunteja41** [forcedotcom/salesforcedx-vscode#2700]
Hi , I used to work on Vs code for lwc development . I am not aware of the previous version but  After Updating to version : 1.50.1 . I'm unable lo authorize to dev hub . I have uninstalled multiple times and Tried installing Previous versions but nothing worked . 

  Version : 
Vs code version : 1.50.1
Salesforce Extension pack : 50.3.0
Sfdc client in machine : 7.78.1-5a65d9dd2f win32-64 node-v.12.18.3
Windows 10 Home - 64 bit . 

Loading for so long : Running SFDX: Authorize an Org.  No response . 

Need urgent help , If any way to connect via google call or any sort that would be helpful . Any suggestion is apppreciated . Thank you

**Comment by smaddox-sf** [comment]
Hi @Tarunteja41 - Thanks for reaching out and sorry you're having trouble.  This is not an official support channel but rather a place to raise issues and collaborate on those as well as potential new features.

Can you share the steps you are executing and the results you are seeing?  Are you seeing an error?
