### ISSUE TITLE
sfdx force:source:diff stop working

### ISSUE THREAD

**Issue by Kxa422** [forcedotcom/salesforcedx-vscode#2702]
### Summary

When using sfdx force:source:diff, vscode return Error parsing diff result

### Steps To Reproduce:

1.  Use Diff file against org with any classes or component

### Expected result

The diff between the file and the org

### Actual result

Error parsing diff result

### Additional information

sfdx force:source:diff --sourcepath force-app\main\default\classes\myClass.cls --json --loglevel fatal
 ended with exit code 1

Error parsing diff result

**VS Code Version**:
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**SFDX CLI Version**:
7.78.1-5a65d9dd2f

**Comment by smaddox-sf** [comment]
Diff should be in good working order now.  Please try it again and [open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) if you are still seeing an issue
