### ISSUE TITLE
Links to LWC component library are broken

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/salesforcedx-vscode#2703]
### Summary

Editing LWC html when you hover over standard lwc componen popup window is show with description.
This popup contains a link to component library which is pointing to https://developer.salesforce.com/docs/component-library/bundle/undefined
checked on:
lightning-dual-listbox
lightning-button

### Steps To Reproduce:

1. Open LWC for edit
1. Hover over standard component name
1. Click on link inside description

### Expected result

Page with description for that component will be open.

### Actual result

Instead page https://developer.salesforce.com/docs/component-library/bundle/undefined is open
![2020-11-04_18h19_54](https://user-images.githubusercontent.com/5740564/98145754-619ff780-1ecb-11eb-99ef-f3a25d04e822.png)
### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.50.1, 

**SF plugins Version**: 50.3.0

**SFDX CLI Version**: 7.78.1

**OS and version**: Windows 10

**Comment by lcampos** [comment]
Thanks for opening this @PawelWozniak , I'm closing it since the fix is available on v50.7.0 of the extensions.

**Comment by PawelWozniak** [comment]
Good work. I have verified that and it is working :)
