### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sanjay1463** [forcedotcom/salesforcedx-vscode#2714]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.4.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\sanjay.makwane\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
