### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MounirBerrichi** [forcedotcom/salesforcedx-vscode#2715]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.3.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Mounir\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
