### ISSUE TITLE
push source always failed

### ISSUE THREAD

**Issue by Madhanmohan558** [forcedotcom/salesforcedx-vscode#2718]
Issue Type: <b>Bug</b>

when ever source code is pushed its always failed even correct code

Extension version: 50.4.0
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:06.060Z)
OS version: Windows_NT ia32 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU B830 @ 1.80GHz (2 x 1796)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.90GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Madhanmohan558** [comment]
please help me

**Comment by smaddox-sf** [comment]
Hi @Madhanmohan558 - Can you provide more context?  What types of files are you working with?  What type of org?  how are you executing the push command?  After you use that command, what result do you see?  (error, any changes to files in the org, etc...)
