### ISSUE TITLE
Deploy on Save/Deploy this Source to Org not working

### ISSUE THREAD

**Issue by tgentet-obrien** [forcedotcom/salesforcedx-vscode#2721]
### Summary

When developing LWCs in VS Code, if you have enabled "Push or Deploy on Save", when you save a JS file, it fails to deploy.

This was an issue previously and was fixed at some point, but recently has stopped working again.

Something I have noticed is when you save the JS file, the file name changes to Upper-Cammel Case, when it is usually Lower-Cammel Case.

### Steps To Reproduce:

1.  Create a Project
1. Connect an Org
1.  Create/Retrieve an LWC to modify
1. Modify the LWC's JS file and save (using CMD + S or by clicking File > Save)
OR
1. Open the VS Code Command Pallet, run `SFDX: Deploy This Source to Org`

### Expected result

The LWC should be deployed successfully to Salesforce

### Actual result

The output does not say that the deployment has failed, however, VS Code pops up with the following notification:
```
SFDX: Deploy Source to Org failed to run
```

### Additional information

![image](https://user-images.githubusercontent.com/6325514/98683342-d310f780-235c-11eb-8b1c-f013d6aa5393.png)

**VS Code Version**:
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:14:40.758Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**SFDX CLI Version**:
sfdx-cli/7.78.1 darwin-x64 node-v12.10.0

**OS and version**:
macOS Catalina 10.15.6

**Comment by wrone** [comment]
I have exactly the same issue. When I save the .js file, the error occurs, but if a save the html file, all files are deployed without issues

![image](https://user-images.githubusercontent.com/9321029/98808324-d4512b80-2413-11eb-8521-333f536ae33d.png)
![image](https://user-images.githubusercontent.com/9321029/98808410-f8147180-2413-11eb-95f0-e9d115866208.png)

**Comment by fodilo** [comment]
I have this issue in the JS file of LWC, when I click right and click deploy this source to org nothing happens.while in the html file it is deployed.


![image](https://user-images.githubusercontent.com/20880188/98918574-12ab2100-24ce-11eb-94aa-87ff2b26dd11.png)

**Comment by tgentet-obrien** [comment]
I have some additional debugging!

I just saved an LWC that does not have a UI (just using the JS as a Util) and it saved fine and then deployed....

I also double checked the force-app/main/default/lwc/jsconfig.json file to ensure both the deployable and non-deployable components are there and they are, including the correct syntax. I'm happy to share the repo with an engineer if it helps.

**Comment by wrone** [comment]
I have 4 LWC components but only 1 shows this error.

I was thinking that maybe when I was creating the failing component I entered the name with the capital letter, but when I was creating other 3, I didn't the capital letter. Maybe capital letter during creation messes this up. I haven't tested that though.

**Comment by tgentet-obrien** [comment]
An update of VS Code (only came up an hour ago) seems to have fixed this for the LWC I was having issues with.

@wrone @fodilo could you check if you have an update on VSCode? It may be an issue with that needing an update

**Comment by wrone** [comment]
I'm already on the last version, error is still there.

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by tgentet-obrien** [comment]
@wrone weird... are you using a VCS? It seems to be sporadically breaking now as opposed to just full stop not working like before.

I am using GitLab, I also just checked my jsconfig.json, this time is has NOT been updated with the relevant LWC in the compilerOptions Object and it seems to be deploying from the JS perfectly fine (only on the LWCs I am working on atm)

**Comment by wrone** [comment]
Hi @tgentet-obrien, I'm using BitBucket. Just checked, now it's deploying my component without any errors, lol, no idea what has changed

**Comment by wrone** [comment]
Hmm... just noticed that this file has changed, maybe this affects the deployment
![image](https://user-images.githubusercontent.com/9321029/99502504-0fec7800-2975-11eb-98ea-af4ffecf632c.png)

**Comment by fodilo** [comment]
Now the deploy in js file works but it generate an error while doing the same deploy but on clicking on the file in the tree it works fine.
![Capture d’écran 2020-11-18 à 9 58 36 AM](https://user-images.githubusercontent.com/20880188/99508772-45995d00-2985-11eb-990f-ef17d26ae12a.png)
![Capture d’écran 2020-11-18 à 9 58 29 AM](https://user-images.githubusercontent.com/20880188/99508793-49c57a80-2985-11eb-9d17-0d167c6acc1e.png)
![Capture d’écran 2020-11-18 à 9 58 46 AM](https://user-images.githubusercontent.com/20880188/99508800-4af6a780-2985-11eb-8f9a-b30828dfb689.png)
![Capture d’écran 2020-11-18 à 9 58 58 AM](https://user-images.githubusercontent.com/20880188/99508808-4cc06b00-2985-11eb-8233-a9abbaa9919e.png)


Thanks

**Comment by AnanyaJha** [comment]
Hi @tgentet-obrien thanks for reporting this! It looks like your problem was resolved, but please let us know if you run into this error again.
@fodilo If you're still running into this issue, could you please tell us which version of the Extensions and Salesforce CLI you're on? Run `sfdx --version` to find the version of the CLI and click on the Marketplace icon to see the version of the Extensions

**Comment by fodilo** [comment]
@AnanyaJha  here is my version
`sfdx-cli/7.80.0-b979aae708 darwin-x64 node-v12.18.3`

**Comment by AnanyaJha** [comment]
@fodilo thanks! Could you also share the version of the Extensions you're on? Click on the Marketplace icon and search for the Salesforce Extensions

**Comment by fodilo** [comment]
@AnanyaJha 
it is 50.5.0
I think it is the lastest
<img width="711" alt="Capture d’écran 2020-11-19 à 8 26 29 PM" src="https://user-images.githubusercontent.com/20880188/99714682-2cd49880-2aa6-11eb-89e5-3c182d79ed06.png">

**Comment by tgentet-obrien** [comment]
This has just started failing for me again!

Well I say started, I haven't used it since before Christmas, but I have the same behaviour as before;

1. I save the file (using CMD + S)
2. The file name updates from lower-cammel/pascal case to upper
3. The message appears to say it's deploying
4. Error appears

Starting SFDX: Deploy Source to Org

This is what is appearing in the Output Panel:
```
14:48:31.238 sfdx force:source:deploy --sourcepath /Users/USERNAME/Work/CLIENT/force-app/main/default/lwc/FlowComponent/FlowComponent.js --json --loglevel fatal
14:48:34.806 sfdx force:source:deploy --sourcepath /Users/USERNAME/Work/CLIENT/force-app/main/default/lwc/FlowComponent/FlowComponent.js --json --loglevel fatal
 ended with exit code 1
```

Is there any updates on what is going on here? the MOST frustrating part about it is just the instability and the fact that sometimes it works and others it does not. I'd rather it just not work at all 😂

**Comment by tgentet-obrien** [comment]
@AnanyaJha apologies, for some weird reason my email alerts have been off... I haven't seen any comments 🤦 

The Extension Pack versionis: v50.13.0
sfdx --version: sfdx-cli/7.85.0 darwin-x64 node-v12.10.0

It's still not working, or was, now isn't again.

**Comment by jeffb-sfdc** [comment]
@tgentet-obrien This is an issue with VS Code.  We raised the issue with them but they don't feel it is a bug - https://github.com/microsoft/vscode/issues/141190#issuecomment-1020883350
