### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gumarques-git** [forcedotcom/salesforcedx-vscode#2723]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.4.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\gumar\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate of #2410
