### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kshitijlawate** [forcedotcom/salesforcedx-vscode#2729]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.5.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/46/k9v_v26517995k20sx57qnpc0000gq/T/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kshitijlawate** [comment]
[Uploading salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt…]()

**Comment by kshitijlawate** [comment]
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5532382/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by smaddox-sf** [comment]
Thanks @kshitijlawate - I'm adding this to #2410 which is where we are tracking & working on this issue
