### ISSUE TITLE
Experimental Deploy incorrectly reports failure if action times out but deploy is queued

### ISSUE THREAD

**Issue by klouf-threshold** [forcedotcom/salesforcedx-vscode#2730]
### Summary

When the Experimental Deploy/Retrieve setting is enabled and some metadata (e.g. an Apex class or a Visualforce page) is deployed, if the action takes longer than ~10 seconds and the deployment is in queue/hasn't yet finished, the action shows an error notification stating "Deploy (Beta) failed to run" and the Output panel shows the messages:
"The deploy is still in the Queue
(timestamp) Finished Deploy (Beta)"

### Steps To Reproduce:

1.  Enable Experimental Deploy/Retrieve setting
2.  Deploy some metadata that takes more than ~10 seconds to complete

### Expected result

Command waits for the deploy to finish and displays the appropriate failure/success message depending on the actual result of the deployment.

### Actual result

Command does not wait for the deployment to finish, the user is presented with mixed messaging as to the status of the deployment, and the actual result of the finished deployment is never presented.

### Additional information

I'll also add that It would be nice to see which file/metadata is being deployed as part of the output to the Output Panel during a deploy using the Experimental setting -- for non-experimental deploys this is part of the sfdx command that is displayed, but the experimental deploy just outputs "(timestamp) Starting Deploy (Beta)".

**VS Code Version**: 1.51.0
**SFDX CLI Version**: sfdx-cli/7.78.1-5a65d9dd2f darwin-x64 node-v12.18.3 (salesforcedx plugin v50.3.1)
**OS and version**: macOS Catalina 10.15.7

**Comment by smaddox-sf** [comment]
Hi @klouf-mp - Thanks for trying out the new experience and for providing feedback!  We are currently working on a better experience for deploys that take more than a few seconds.  We'll address this feedback as a part of that work and keep you posted.

**Comment by cgb-76** [comment]
Just tagging myself on this, reporting the same thing.

**Comment by floralan** [comment]
@cgb-76 We removed Experimental Deploy/Retrieve flag in setting, please checkout out our new deploy/retrieve commands that should fix this issue.
