### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by raghudeep77** [forcedotcom/salesforcedx-vscode#2736]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lightning`
- Extension Version: `50.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\raghu\AppData\Local\Temp\salesforce.salesforcedx-vscode-lightning-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
We're tracking CPU load issues on #2410
