### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GomuNingen** [forcedotcom/salesforcedx-vscode#2739]
[salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5548984/salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `49.11.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Luffy\AppData\Local\Temp\salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Tracking this work and fixes on #2410
