### ISSUE TITLE
Detecting Conflicts When Feature is Disabled

### ISSUE THREAD

**Issue by jvolkov** [forcedotcom/salesforcedx-vscode#2741]
### Summary

Cannot run a normal retrieve source command.  Conflict detection runs instead and for the wrong target directory.

### Steps To Reproduce:

1.  In sfdx-project.json verify path is force-app
![image](https://user-images.githubusercontent.com/1066119/99299411-0988bf80-2800-11eb-982b-80b96b722f02.png)

2.  In Settings > Detect Conflict At Sync verify this feature is disabled
![image](https://user-images.githubusercontent.com/1066119/99299351-faa20d00-27ff-11eb-9a16-b5d105d0ab99.png)

3.  project folder > manifest > package.xml > right click and choose retrieve source in manifest from org
![image](https://user-images.githubusercontent.com/1066119/99299470-1ad1cc00-2800-11eb-8ad7-4eb01b10b1f7.png)

### Expected result

Normal `sfdx force:source:retrieve` runs without conflict detection, for force-app as the target directory.

### Actual result

Conflict detection runs instead and for the wrong target directory.  No idea how this directory was set.

Command that runs upon clicking retrieve source in manifest from org:
`sfdx force:mdapi:retrieve --retrievetargetdir C:\Users\[user]\AppData\Local\Temp\.sfdx\tools\conflicts\[defaultorgname]`

**VS Code Version**:  1.51.1

**SFDX CLI Version**:  7.80.0-b979aae708

**OS and version**:  Windows_NT x64 10.0.17763

**salesforcedx**: 50.5.0 (core)

**Comment by jvolkov** [comment]
Maybe relevant.  
run `sfdx force:source:retrieve -m ApexClass:TestDataFactory` 
returns `ERROR running force:source:retrieve:  WARNING: Infinite loop detected.`

![image](https://user-images.githubusercontent.com/1066119/99301127-566d9580-2802-11eb-8980-ce17c10ff212.png)

**Comment by smaddox-sf** [comment]
Hi @jvolkov - Thanks for reaching out with feedback.  What result do you get if you run the retrieve command directly in the CLI?

**Comment by rcoringrato-sfdc** [comment]
Hi @jvolkov - The conflict detection feature is still enabled for your **workspace** based on the image you posted in step 2. If you disable the setting for the workspace, too, you should be able to run the retrieve without conflict detection.

**Comment by jvolkov** [comment]
@rcoringrato-sfdc Ah looks like it was still active.  I assumed because the checkbox in the image above was unchecked it was disabled.

![image](https://user-images.githubusercontent.com/1066119/99457667-2eecfa80-28e0-11eb-9357-0b98a4f762e0.png)

After disabling it I'm still getting that odd `"message": "WARNING: Infinite loop detected."` problem but that seems to caused by some other problem.

**Comment by jvolkov** [comment]
I was able to workaround the `Infinite loop detected` issue by creating a new project.  Then it came back.  So created a new project.  Then it came back.  Should I open a new issue?

`ERROR running force:source:retrieve:  WARNING: Infinite loop detected.`

**Comment by smaddox-sf** [comment]
Thanks for the additional information @jvolkov .  Yes, please create a new issue for this since the original one was solved.    We aim to keep 1 topic per issue to keep conversations focused and discoverable.  [lick here to start a new issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?template=Bug_report.md).

**Comment by jvolkov** [comment]
Thanks opened a [new issue here](https://github.com/forcedotcom/cli/issues/749)
