### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by deStMathieu** [forcedotcom/salesforcedx-vscode#2747]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.5.0`
- OS Version: `Linux x64 5.4.0-53-generic`
- VSCode version: `1.51.1`

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5558772/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Dup #2410
