### ISSUE TITLE
LWC XML files not retrieving

### ISSUE THREAD

**Issue by dvon88** [forcedotcom/salesforcedx-vscode#2748]
Not sure if this belongs in CLI repo, so I'll post it in both...
### Summary

force:source:retrieve is not retrieving .xml metadata for some LWC components. It worked fine previously, but has broken today for some reason. When running the command currently, 5 LWC components are being retrieved without their xml files. The HTML, JS, and CSS are all retrieved, but not the XML. To then deploy to a higher org, I need to copy the XML file from the original project directory, and paste it into the directory from where I deploy to a higher org.

### Steps To Reproduce:

1.  Create LWC component
1.  Retrieve using sfdx force:source:retrieve -u SOURCE_ORG -x /path/to/package.xml

### Expected result
Retrieval of all files associated to the LWC component.

### Actual result
Retrieval of HTML, CSS, JS, but not XML.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64

**SFDX CLI Version**:
sfdx-cli/7.80.0-b979aae708 linux-x64 node-v12.18.3

**OS and version**:
Ubuntu 18.04

**Comment by smaddox-sf** [comment]
Hi @dvon88 - Thanks for submitting feedback.  Couple questions: 
1. Are you running that command in the terminal?
1. Do you have the `Experimental: Deploy Retrieve` setting enabled in VS Code?
