### ISSUE TITLE
SFDX: Authorize an Org failed to run

### ISSUE THREAD

**Issue by Rajinicp** [forcedotcom/salesforcedx-vscode#2758]
Every time when I give Authorize an Org command , I m getting SFDX: Authorize an Org failed to run Error .
I installed every packages then also same message. Please resolve it.

Regards,
Rajini
![Screenshot (41)](https://user-images.githubusercontent.com/74948581/100052061-27c76e80-2e43-11eb-9861-c890754a90ca.png)

**Comment by smaddox-sf** [comment]
Hi @Rajinicp - From the error message shown in the output panel, looks like the CLI is not installed.  (You need both the extension pack and the CLI.). You can find the setup details here: https://developer.salesforce.com/tools/vscode/en/getting-started/install
