### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sourabh42** [forcedotcom/salesforcedx-vscode#2761]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.5.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\hp\AppData\Local\Temp\salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Dupe of #2410
