### ISSUE TITLE
Illegal assignment from List<AggregateResult> to List<AggregateResult>

### ISSUE THREAD

**Issue by eq-dsolari** [forcedotcom/salesforcedx-vscode#2763]
### Summary

The Apex Language server shows an AggregateResult type returned by a SOQL statement and then assigned to a List<AggregateResult> as an illegal assignment.

### Steps To Reproduce:

1. Create a new project, link to your org
2. Pull Apex class from the org or create new one
3. Author any SOQL statement with return type AggregateResult and assign it to a List<AggregateResult>.

### Expected result

From the Apex Developer documentation this is the intended use. An AggregateResult returned from a SOQL statement can be assigned to a collection of type: AggregateResult.

### Actual result

I receive a warning in the Problems output in Visual Studio Code
![image](https://user-images.githubusercontent.com/75048501/100292033-60536f00-2f4d-11eb-8b2c-e3e44e040621.png)

![image](https://user-images.githubusercontent.com/75048501/100292285-03a48400-2f4e-11eb-98e3-1c83c337b7d0.png)

**VS Code Version**: 1.51.1

**SFDX CLI Version**: 50.5.0

**OS and version**: Windows 10 Pro x64 1909

**Comment by lcampos** [comment]
Thanks for logging this issue @eq-dsolari . I haven't been able to repro it using the code sample you provided (screenshot below). Can you provide a sample class/trigger where you are consistently seeing this behavior ? I think it might be an issue that's specific to a certain pattern I haven't been using while trying to repro this. 

Also, could you copy/paste the stack traces from the Output panel for `Apex Language Server` ?

<img width="1127" alt="aggregate-result-sample" src="https://user-images.githubusercontent.com/1041842/100671006-9493aa80-3314-11eb-9cad-f1e72e7d4f66.png">
