### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sai-karthik9** [forcedotcom/salesforcedx-vscode#2765]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.5.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not enough info to troubleshoot
