### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dhpawar-lwc** [forcedotcom/salesforcedx-vscode#2767]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lightning`
- Extension Version: `50.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
Not enough info to troubleshoot
