### ISSUE TITLE
Unable to Open the Text Editor, SOQL Editor, and the Results Tab All at Once

### ISSUE THREAD

**Issue by rlancejohnson** [forcedotcom/salesforcedx-vscode#2782]
### Summary

When I try to open with text editor and soql editor, the soql editor overwrites the text editor tab (regardless of what the default is). You then have to re-open the file in the text editor format. Then the problem is that the minute you move that tab it converts back to the soql editor format if you have that format open anywhere else in vscode. This means that you either have to spend a bunch of time working around these bugs to get everything just right or you have to toggle back and forth between the text editor, soql editor, and results tabs.

### Steps To Reproduce:

1.  Open .soql file with text editor
1.  Open the same .soql file with the soql editor
1.  Open the same .soql file with the text editor
1.  Snap that text editor tab to another position in VS Code
1.  Repeat the same steps above for a new .soql file while keeping the existing tabs open

### Expected result

1.  The .soql file opens in a tab with the text editor format
1.  The .soql file opens a new tab with the soql editor format
1.  The .soql file opens a new tab with the text editor format
1.  The text editor format tab should snap into position and remain in the text editor format
1. The above should happen for the new .soql file tabs

### Actual result

1.  The .soql file opens in a tab with the text editor format
1.  The .soql file opens in the existing text editor format tab and converts to the soql editor format (even if the tab is pinned/saved)
1.  The .soql file opens a new tab with the text editor format
1.  The text editor format tab snaps into position and converts to the soql editor format (even if the tab is pinned/saved)
1. The above happens for the new .soql files that are opened as well

**VS Code Version**: 1.51

**SFDX CLI Version**: 7.75.0

**OS and version**: Chrome OS - 86.0.4240.198

**Comment by lcampos** [comment]
Thanks for the detailed feedback @rlancejohnson . This is something that we'll definitely get fixed.
cc @clairebianchi @praksb

**Comment by jonnyhork** [comment]
@rlancejohnson Thanks again for creating this issue, we really appreciate your feedback. We are going to look into this more but I want to make sure I understand your use case. Would it be possible to include some screenshots, a video or gif to demonstrate what it is you're looking to do?

If you would like to have the text editor and the SOQL Builder UI open at the same time you can try this workflow:
![View Text, Builder and Results Panels](https://user-images.githubusercontent.com/25188632/101410182-3464b180-389c-11eb-9060-ad23618de4aa.gif)

We are still looking to make this process smoother and identify any bugs in our extension or with the use of Custom Editors in VS Code, hopefully the workaround in the gif above will help you in the meantime.

**Comment by jonnyhork** [comment]
I opened an issue with VS Code to get more information: https://github.com/microsoft/vscode/issues/112100

**Comment by rlancejohnson** [comment]
@jonnyhork Here is a video showing the main issues that I described earlier. It seems to be that the two editor types cannot co-exist in the same grid space or the text formatted tab will be converted to the soql editor format or become unclickable. Hope this helps.

Also, I test the sequence you describe and that works, so that will help in the meantime. Thanks!

https://vimeo.com/489158402/011e0b27cc

**Comment by jonnyhork** [comment]
As best we can tell this is a known issue with the custom editor API in VS Code. The issue can be followed in the link above and other issues referenced there. I am going to close this and follow the conversation on the VS Code repo.

**Comment by praksb** [comment]
@rlancejohnson Can you update to the latest version of VS Code and try your original scenario. I believe Microsoft now fixed the bug on the custom editor that was causing the issue that you reported in their latest release: Version: 1.53.0

**Comment by rlancejohnson** [comment]
@praksb Thanks!
