### ISSUE TITLE
The SF extension pack effectively disables emmet in vscode. What am I supposed to do? To clarify, I'm not using sfdx.  Just writing plain html

### ISSUE THREAD

**Issue by peterminetree** [forcedotcom/salesforcedx-vscode#2793]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Duplicate of #2479.  We'll post on that issue as we have a fix ready
