### ISSUE TITLE
VSCode - Unable to create default Scratch Org. 

### ISSUE THREAD

**Issue by BhavaniV-98** [forcedotcom/salesforcedx-vscode#2797]
VS Output Text:

Starting SFDX: Create a Default Scratch Org...

10:57:01.987 sfdx force:org:create -f config\project-scratch-def.json --setalias trailhead --durationdays 7 --setdefaultusername --json --loglevel fatal
10:57:15.304 sfdx force:org:create -f config\project-scratch-def.json --setalias trailhead --durationdays 7 --setdefaultusername --json --loglevel fatal
 ended with exit code 1

You do not have access to the [ScratchOrgInfo] object

![Screenshot (96)](https://user-images.githubusercontent.com/75414720/101444617-e0aea280-3945-11eb-8d10-710b3d05c1e3.png)

**Comment by lcampos** [comment]
Hi @BhavaniV-98 , I've seen this happen when the Dev Hub is not enabled in the org. Can you confirm that the org you've set as your Dev Hub is in fact enabled as a Dev Hub ? You can find some info about it in [SFDX Setup Next Steps](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_next_steps.htm)

**Comment by HansUXdev** [comment]
I have a similar issue and this seems close enough that I don't want to create a duplicate.
The option to "create a default scratch org" doesn't show up. I've install the extension pack and followed the instructions (https://trailhead.salesforce.com/content/learn/projects/quick-start-lightning-web-components/set-up-visual-studio-code).

So many issue isn't the command failing but just not showing up.
I've disabled other extensions, etc and reset vscode as standard troubleshooting protocol and created a project to see if it was just bad instructions.
