### ISSUE TITLE
Can't  install the extension on macos 

### ISSUE THREAD

**Issue by melmoussaoui** [forcedotcom/salesforcedx-vscode#280]
### Summary
I have this error when I try to install the extension:
<img width="1219" alt="screen shot 2018-01-30 at 14 26 40" src="https://user-images.githubusercontent.com/1318881/35568881-bd82f2e0-05ca-11e8-93bd-19c8f6cd1dfd.png">
I narrowed it down by checking the dependencies and try to install them first. it seems the problem is related to the **Apex Debugger for Visual Studio Code**
I'm not behind any proxy
I had to download the extension and install it manually
### Steps To Reproduce:
1. Install the extension from VS Code 1.19.3 on mac os

**VS Code Version**:
 1.19.3
**SFDX CLI Version**:
6.1.19-4341549
**OS and version**:
OS X 10.13.3

**Comment by vazexqi** [comment]
@melmoussaoui - Hmmm, I just tried this (see attached gif). 

![install_salesforcedx_vscode](https://user-images.githubusercontent.com/54414/35574756-81d753a2-058f-11e8-9872-38cd5950d983.gif)

Notice that in the gif, it will go ahead and install all the dependencies for me. Does that happen for you too?

I see that we are on the same version of VS Code and OS X (I'm actually on 10.13.2, but not sure if that is the issue).

Do you have more details on the repro steps?

**Comment by melmoussaoui** [comment]
@vazexqi Unfortunately no. I tried to reproduce this on my colleague mac but no success.
I don't have any other plugins beside a theme/syntaxe color.
I'll close it, maybe it was just my bad luck 😄
