### ISSUE TITLE
Hover Text Fail

### ISSUE THREAD

**Issue by robertStrunk** [forcedotcom/salesforcedx-vscode#2800]
### Summary

When I hover over markup in an LWC or Aura component the language server (lwc or aura depending on what markup was hovered over) prints an error to the output panel. In the error message it references a folder that does not exist. 
`[Error - 10:14:44 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: UNKNOWN: unknown error, stat 'c:\Users\myUSer\OneDrive\Clients\clientA\clientA (Terminals)\code\preprod repo\clientA-sfdc-dev\force-app\main\default\objects\Pricing_Model__c\fields'
  Code: -32603 `

the "...\Pricing_Model__c\fields" folder does not exist so I created it thinking it would have the error go away. Instead, the folder is behaving oddly (windows file explorer cannot rename it or delete it and instead of the typical message that says the folder is in use, it says unknown error)

**VS Code Version**:
VSCode Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

**SFDX CLI Version**:
sfdx-cli/7.76.1-f301d5641f win32-x64 node-v12.18.3

**OS and version**:
OS: Windows_NT x64 10.0.17763

**Comment by lcampos** [comment]
Hi @robertStrunk , thanks for opening this issue. I've tried using components in aura & lwc that reference SObjects in their templates directly (and their controllers too) but haven't been able to replicate the issue. Could you provide a project or component sample that consistently causes this issue ? Can you also add which version of the Salesforce extensions for VSCode you are using ? I've been testing with version 50.7.0.

**Comment by robertStrunk** [comment]
@lcampos I ended up having to completely delete the project and all of its contents so am not able to provide any further details. I suppose it was a one-off. Thanks for taking the time to check.

**Comment by shridharpuntambekar-okta** [comment]
Hello, request you to keep this bug open. Similar bug: #1265 
Facing the same issue: [Linked comment](https://github.com/forcedotcom/salesforcedx-vscode/issues/1265#issuecomment-1059797587)

**Comment by sacsha30** [comment]
getting similar error:

Could not create Tag from <my_lwc_comp.js>.
[object Object]
[Error - 12:09:20 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'forEach' of undefined
  Code: -32603 
[Error - 12:09:59 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'forEach' of undefined
  Code: -32603 
[Error - 12:10:57 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'forEach' of undefined
  Code: -32603 
[Error - 12:15:54 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'forEach' of undefined
  Code: -32603

**Comment by ajfm-forte** [comment]
same issue... any fix or something?
