### ISSUE TITLE
Refresh SObjects has stopped working

### ISSUE THREAD

**Issue by Bash404** [forcedotcom/salesforcedx-vscode#2802]
### Summary

Error message:
Command 'SFDX: Refresh SObject Definitions' resulted in an error (command 'sfdx.force.internal.refreshsobjects' not found)

Have set the environment path variable and reinstalled the CLI and updated it.

### Steps To Reproduce:

1.  Simply select SFDX:  Refresh SObject Definition Objects from the command palette.

### Expected result

Should give the option to refresh custom or standard objects.

### Actual result

Presented with:

Command 'SFDX: Refresh SObject Definitions' resulted in an error (command 'sfdx.force.internal.refreshsobjects' not found)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.51.1

**SFDX CLI Version**:  sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3

**OS and version**: Windows 10 10.0.18363

**Comment by lcampos** [comment]
Hi @Bash404 , thanks for opening this issue. This usually means that the VSCode extension cannot find the CLI, have you gone through the [Set Salesforce CLI path (Windows)](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows) troubleshooting steps to see if that fixes the issue ?

**Comment by Bash404** [comment]
Hi @lcampos , thanks for the reply. Unfortunately, I have already done that double-checked my path and it is definitely there.

**Comment by Bash404** [comment]
Okay not sure why but it's fixed and working now. I ran:

sfdx force:schema:sobject:list -c all

from the terminal within VS Code and then the command suddenly began to work again from the GUI menu. No idea whats happened or why that would fix it. Maybe someone can shed light on this and it may help someone else in the future.

**Comment by Bash404** [comment]
See comment. Seems to be working now.
