### ISSUE TITLE
Salesforce CLI Extension Why Not Installing? In Visual Studio

### ISSUE THREAD

**Issue by junaidyounus** [forcedotcom/salesforcedx-vscode#2805]
![cli](https://user-images.githubusercontent.com/75748178/101662992-f4ecbf80-3a6b-11eb-948c-358ca07a77fe.PNG)

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
There's no details on the repro steps here.  Feel free to open a new issue with the details
