### ISSUE TITLE
SFDX Vscode hangs and keeps on loading after update . Unable to find the issue . need help . 

### ISSUE THREAD

**Issue by Tarunteja41** [forcedotcom/salesforcedx-vscode#2811]
Hi , I used to work on Vs code for lwc development . I am not aware of the previous version but After Updating to version : 1.50.1 . I'm unable lo authorize to dev hub . I have uninstalled multiple times and Tried installing Previous versions but nothing worked .

Version :
Vs code version : 1.50.1
Salesforce Extension pack : 50.3.0
Sfdc client in machine : 7.78.1-5a65d9dd2f win32-64 node-v.12.18.3
Windows 10 Home - 64 bit .

Loading for so long : Running SFDX: Authorize an Org. No response .

Need urgent help , If any way to connect via google call or any sort that would be helpful . Any suggestion is apppreciated . Thank you

**Comment by smaddox-sf** [comment]
Hi @tariqrafique - Thanks for reaching out.  This repo is a place to surface issues and collaborate.  If you require immediate assistance, please use official support channels.

Can you clarify the steps you are executing when you hit the issue?  The exact steps aren't clear from your description.

Based on the version numbers, it looks like there is a newer update of both the Salesforce CLI and the Salesforce Extension pack.  You might try updating both to the latest as a starting point.

**Comment by tariqrafique** [comment]
@smaddox-sf you've mentioned the wrong person. I didn't open this issue.
