### ISSUE TITLE
Org Browser retrieval of StandardValueSet failing

### ISSUE THREAD

**Issue by leahkennedy** [forcedotcom/salesforcedx-vscode#2812]
We are seeing Org Browser retrieval of StandardValueSet failing. This is occurring while connected to multiple sandboxes. We were previously able to do this successfully. The error we get is:

sfdx.force.source.retrieve.component: Node of type empty does not have a parent metadata type node. This is likely caused by the extension that contributes sfdx.force.source.retrieve.component.

**Comment by lcampos** [comment]
@leahkennedy can you add the following information :
- VSCode version
- OS version
- Salesforce extensions for VSCode version
- Salesforce CLI version
