### ISSUE TITLE
Authorize an org not appearing in VSCode and CLI Commands are not working 

### ISSUE THREAD

**Issue by ShivamS3011** [forcedotcom/salesforcedx-vscode#2813]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result  - While using VSCode, Authorize an org should come after pressing Ctrl+Shft+P and  SFDX:Create Project should work

_Describe what should have happened_.

### Actual result - Authorize an org is not coming after pressing Ctrl+Shft+P and after selecting SFDX: Create Project, it is showing - Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.51.1

**SFDX CLI Version**: 

**OS and version**: Windows 10

**Comment by smaddox-sf** [comment]
HI @ShivamS3011 - I notice that you didn't include the SFDX CLI version.  From the issue, it sounds like it's not installed.  Have you installed it?  Steps can be found here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm

**Comment by ShivamS3011** [comment]
> HI @ShivamS3011 - I notice that you didn't include the SFDX CLI version. From the issue, it sounds like it's not installed. Have you installed it? Steps can be found here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm

Hi @smaddox-sf I have already installed sfdx-cli - version -  sfdx-cli/7.81.0-7b953c80d1

**Comment by lcampos** [comment]
@ShivamS3011 which version of the Salesforce extensions for VSCode are you using ? The latest versions of `SFDX: Create Project` do not use the CLI so I wonder if you are running into a different issue.
