### ISSUE TITLE
Variable is not visible warning ignore @testVisible

### ISSUE THREAD

**Issue by CorpitalFDP** [forcedotcom/salesforcedx-vscode#2814]
### Summary

Variable is not visible warning ignore @testVisible

### Steps To Reproduce:

1.  Create this class:
public with sharing class TestVisible {
    @testVisible
	private static String DummyString{
        get{
             return DummyString;
        }
        private set;
    }
}
1.  Create this class:
@isTest 
public class TestVisibleTestClass {
    public TestVisibleTestClass() {
        TestVisible.DummyString = 'test';
    }
}

### Expected result

No warnings

### Actual result

Warning: Variable is not visible: TestVisible.DummyString
![image](https://user-images.githubusercontent.com/40599682/102196518-4cea5280-3ec0-11eb-8032-125583e22cfb.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version: 1.52.0 (system setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
**SFDX CLI Version**: 
salesforce.salesforcedx-vscode-apex v50.8.0
sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3
**OS and version**:
Microsoft Windows [Version 10.0.18363.1256]

**Comment by smaddox-sf** [comment]
Duplicate #1835
