### ISSUE TITLE
Retrieve With Manifest (beta) failed to run

### ISSUE THREAD

**Issue by zix66** [forcedotcom/salesforcedx-vscode#2815]
![Screenshot_1](https://user-images.githubusercontent.com/44432865/102219007-8aaea180-3ee7-11eb-878e-75e4447214d2.jpg)

### Summary
Retrieve With Manifest (beta) failed to run

From today .. was impossible to retrieve whole bundle .. single items - yes.
Totally reinstalled project .. all steps positive + Authorise an Org .. up to retrieve source from package.xml
► raised error [picture attached]

![Screenshot_13](https://user-images.githubusercontent.com/44432865/102219792-9fd80000-3ee8-11eb-8b4e-6ea281920f3c.jpg)

**OS and version**:
Win10 64

**Comment by AnanyaJha** [comment]
Hi @zix66 thanks for reporting this! A few questions so we can figure out what might be going on: 
does retrieving this bundle work with the `Experimental Deploy/Retrieve` setting turned off? You can turn the setting off by going into your `Preferences (Open Settings UI)` via the command palette and searching for `Experimental: Deploy Retrieve`.
Are any errors reported in the output window when the command fails? If not, could you click `Help` at the top of the screen and then click `Toggle Developer Tools` and paste the output here.

**Comment by zix66** [comment]
My another one pc failed in same issue too.
So problem starting after upgrading VS to latest version.
![Screenshot_1](https://user-images.githubusercontent.com/44432865/102303390-ba9b8a80-3f63-11eb-8348-0ac2606049a4.jpg)

♦ after switching off "beta retrieve" all working correct
♦ after switching back "beta retrieve" process failed

![Screenshot_2](https://user-images.githubusercontent.com/44432865/102303743-8e343e00-3f64-11eb-90ee-49c0552aec8c.jpg)

Finally .. DevTools log fulfilled with errors .. noone was exists before upgrading VS Code version. Log attached.

[-1608091379619.log](https://github.com/forcedotcom/salesforcedx-vscode/files/5700248/-1608091379619.log)

**Comment by zix66** [comment]
That's my manifest package content
![Screenshot_3](https://user-images.githubusercontent.com/44432865/102304267-bbcdb700-3f65-11eb-9b2b-88ac0100614a.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/44432865/102304274-c0926b00-3f65-11eb-84e7-2109fdbd91c8.jpg)

**Comment by zix66** [comment]
Still .. beta-retrieve for single item working correct ..

**Comment by lcampos** [comment]
@zix66 can you provide more information on the metadata you are trying to retrieve ? Either by sharing your manifest file or listing the metadata types you are working with.

Also, are there any errors in the Output panel or on the Developer Console (Help > Toggle Developer Tools > Console) ? If so, please add those errors here.

**Comment by BlackFoc91** [comment]
I have the same problem here : either when trying to refresh an existing project or while creating a new one.

The output log is the following : 

```
Starting Conflict Detection: retrieving org source

10:16:40.437 sfdx force:mdapi:retrieve --retrievetargetdir C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject --unpackaged C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\package.xml --targetusername MyClientProject
Retrieving source...

=== Status
Status:  Pending
jobid:  09S1j000001DeZtEAK


=== Result
Status:  Succeeded
jobid:  09S1j000001DeZtEAK

Wrote retrieve zip to C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\unpackaged.zip.
10:17:35.131 sfdx force:mdapi:retrieve --retrievetargetdir C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject --unpackaged C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\package.xml --targetusername MyClientProject
 ended with exit code 0

Starting Conflict Detection: converting org source

10:17:35.914 sfdx force:mdapi:convert --rootdir C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\unpackaged --outputdir C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\converted
(node:10796) UnhandledPromiseRejectionWarning: Error: EINVAL: invalid argument, mkdir 'g:\Toto\Documents\Workspace VScode\MyClientProject\C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\converted\main\default\classes'
    at Object.mkdirSync (fs.js:921:3)
    at Proxy.sync (C:\Users\Toto\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\mkdirp\index.js:72:13)
    at Object.ensureDirectoryExistsSync (C:\Users\Toto\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\core\srcDevUtil.js:217:20)
    at FineGrainTrackingCommitStrategy.commit (C:\Users\Toto\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\decompositionStrategy\fineGrainTrackingCommitStrategy.js:54:24)
(node:10796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10:17:39.737 sfdx force:mdapi:convert --rootdir C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\unpackaged --outputdir C:\Users\Toto\AppData\Local\Temp\.sfdx\tools\conflicts\MyClientProject\converted
 ended with exit code 0

10:17:39.959 Starting Retrieve With Manifest (beta)


10:17:50.459 Finished Retrieve With Manifest (beta)
```

**Comment by AnanyaJha** [comment]
@BlackFoc91 Thanks for reporting this issue as well! Can you give us some more information on what metadata you're trying to retrieve? You can paste the contents of your manifest file here or share the metadata types.

**Comment by BlackFoc91** [comment]
Sure, the manifest is pretty classic

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTestSuite</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>48.0</version>
</Package>`

Like  @zix66 , i can refresh elements individualy (for exemple one specific trigger) or a group of elements (the trigger node for exemple), but not the whole project

**Comment by lcampos** [comment]
@BlackFoc91 looks like you have two different beta's enabled. Looking at the stack trace it seems like the errors are exclusive to conflict detection code. Could you disable [Conflict Detection](https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts) and just keep the [Performance Enhancements](https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements) enabled. In case you are not using source control (git, svn, etc), keep in mind that this retrieve could overwrite local changes.

**Comment by BlackFoc91** [comment]
Thanks for your response, i was in holldays sorry. I have disabled Conflist Detection but it still not working. Disabling both Conflict Detection and Performance Enhancements solve the problem. Thanks !

**Comment by ajayfadealership** [comment]
Just disabled the **Performance Enhancements** and it worked. 
Thanks

**Comment by riyazy** [comment]
Disabling the **Performance Enhancements** did the trick.

Thanks
