### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by NicolasBaak** [forcedotcom/salesforcedx-vscode#2823]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.8.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
There's not enough information here to replicate and debug the issue. I'll close this for now but feel free to re-open it if you can provide more information.
