### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by suruthi-rs** [forcedotcom/salesforcedx-vscode#2826]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.8.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.52.1`
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 24289,
		"activateCallTime": 192,
		"activateResolvedTime": 5,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-lwc",
				"_lower": "salesforce.salesforcedx-vscode-lwc"
			},
			"activationEvent": "workspaceContainsTimeout:**/workspace-user.xml"
		}
	},
	"runtimeErrors": []
}
```

![image](https://user-images.githubusercontent.com/60875638/102770384-1160f400-43aa-11eb-96c2-9d4fb4b4a10a.png)

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by VartikaPandey1303** [comment]
Did it get resolved? I am facing the same issue

**Comment by smaddox-sf** [comment]
Hi @suruthi-rs and @VartikaPandey1303 - Can you share some context on when you hit this error?  Please share:
 - Steps to reproduce
 - Expected outcome
 - Actual outcome
