### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by VartikaPandey1303** [forcedotcom/salesforcedx-vscode#2835]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.8.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by VartikaPandey1303** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 38198,
		"activateCallTime": 6,
		"activateResolvedTime": 781,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
Hi @VartikaPandey1303 - Can you share some context on when you hit this error? Please share:

 - Steps to reproduce
 - Expected outcome
 - Actual outcome
