### ISSUE TITLE
First time user, can't execute commands

### ISSUE THREAD

**Issue by VartikaPandey1303** [forcedotcom/salesforcedx-vscode#2836]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.8.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by VartikaPandey1303** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 14581,
		"activateCallTime": 9,
		"activateResolvedTime": 1545,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
Hi @VartikaPandey1303 - Can you share some context on when you hit this error? Please share:

 - Steps to reproduce
 - Expected outcome
 - Actual outcome

**Comment by VartikaPandey1303** [comment]
I was trying to run VS code for t he e first time.. I downloaded the
Salesforce extensions and checked my path settings too. but everytime I
tried to execute any sfdx command, I'd get an error.

**Comment by smaddox-sf** [comment]
Thanks for the context @VartikaPandey1303 .  Have you installed the CLI?  
[Here's the install info](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm).  If it's already installed, can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?
