### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by prerna7** [forcedotcom/salesforcedx-vscode#2850]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  Please open a new issue using the 'bug' template
