### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by DevTM-F** [forcedotcom/salesforcedx-vscode#2852]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.8.0`
- OS Version: `Linux x64 5.3.0-59-generic`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  Please open a new issue using the 'bug' template
