### ISSUE TITLE
Ability to diff a directory with org

### ISSUE THREAD

**Issue by mintotsai** [forcedotcom/salesforcedx-vscode#2861]
**Is your feature request related to a problem? Please describe.**

I often find myself working on multiple features in an org and wanting to see changes between my org and vscode before pulling the code down.

**Describe the solution you'd like**

The ability to diff a directory in VSCode with org. 

The Eclipse plugin did this nicely.

**Comment by smaddox-sf** [comment]
HI @mintotsai - Thanks for reaching out with this suggestion!  I'd like to get more of your thoughts on this, so let me ask a few questions:  When you think about diffing your local files to the org, what would you do after the diff?  Just look through the new/changed/deleted files?  (perhaps seeing a diff on each individual file?)

Or are you seeking to see the diff and then deploy or retrieve?  (or perhaps build a package?). I'd love to hear more about how the diff against the org would fit into your workflow and the things you are seeking to accomplish after the diff.

**Comment by mintotsai** [comment]
Hi @smaddox-sf : Good questions. 

One workflow I have is I could be working on multiple features at a time in my dev org.

When I'm done with a feature (and not yet the others), in Eclipse, I would do a Synchronize (diff) to see and individually pull only the changes or changed files for that one feature locally to be check into Git.

After that, I would push to the packaging org and build a package for customers.

This feature helps when the work can only be done in the dev org like editing objects, custom fields, etc.

Let me know if I can explain any of this better.

**Comment by smaddox-sf** [comment]
Hi @mintotsai - You can now use the Diff command for directories!  When you execute the command, it is doing a file comparison to surface diffs, so any file that is not present either locally or in the Org will **not** show up as a Diff.

**Comment by mintotsai** [comment]
That is so cool! I just tried it. Thank you and the team!
