### ISSUE TITLE
Authorize An Org failed because force:auth:web:login is not a sfdx command

### ISSUE THREAD

**Issue by MrFatt** [forcedotcom/salesforcedx-vscode#2869]
### Summary

When I was following the instruction in this tutorial: https://trailhead.salesforce.com/content/learn/projects/quickstart-vscode-salesforce/use-vscode-for-salesforce, the `Authenticate to Your Playground` step failed. And in the output console I saw

```
Starting SFDX: Authorize an Org

15:23:41.710 sfdx force:auth:web:login --setalias VSCodePlayground --instanceurl https://login.salesforce.com --setdefaultusername
 ›   Warning: force:auth:web:login is not a sfdx command.
Did you mean auth:web:login? [y/n]: 
 ›   Error: Run sfdx help force for a list of available commands.
15:23:47.396 sfdx force:auth:web:login --setalias VSCodePlayground --instanceurl https://login.salesforce.com --setdefaultusername
 ended with exit code 127
```

I believe it's caused by the new version sfdx cli deprecates the force versions of these commands

### Steps To Reproduce:

1.  Install the latest sfdx cli
2. Install the Salesforce Extension in VSCode
3. Run `SFDX: Authorize an Org` in VSCode

### Expected result

The org is authorized successfully

### Actual result

authorization failed with the error `Run sfdx help force for a list of available commands.`

### Additional information

![image](https://user-images.githubusercontent.com/9215719/104806307-8ab8fe80-5811-11eb-827c-644c7c4ea2d7.png)

**VS Code Version**: Version: 1.51.1

**SFDX CLI Version**: sfdx-cli/7.83.0-eba9c6a927 darwin-x64 node-v12.18.3

**OS and version**: v50.13.0

**Comment by 4388331** [comment]
I have the same issue

**Comment by 4388331** [comment]
I resolved the same issue with the plugin
Run this in CMD "sfdx plugin:install @salesforce/plugin-auth@1.4.3"

Got solution here  https://github.com/forcedotcom/cli/issues/757#issuecomment-741885504

**Comment by KuljitSinghTomar** [comment]
Running `sfdx update` on my mac terminal fixed this issue for me. Thank you @4388331 for the pointer!

**Comment by roshani22495** [comment]
Thank you @4388331. I was also facing the error while running the command 'Authorize dev hub' .  After running command "sfdx plugin:install @salesforce/plugin-auth@1.4.3" on CMD, it worked fine for me.

**Comment by CosplayCoder** [comment]
> I resolved the same issue with the plugin
> Run this in CMD "sfdx plugin:install @salesforce/plugin-auth@1.4.3"
> 
> Got solution here [forcedotcom/cli#757 (comment)](https://github.com/forcedotcom/cli/issues/757#issuecomment-741885504)

This fixed the issue for me as well! Thanks for sharing!

**Comment by JohnnySalesforce** [comment]
Thanks @4388331 - worked for me as well!

**Comment by smaddox-sf** [comment]
as noted above, latest CLI resolved this.

**Comment by ElvisPlatini** [comment]
Thanks @4388331.
You solved my problem.

**Comment by jeansgan** [comment]
> I resolved the same issue with the plugin
> Run this in CMD "sfdx plugin:install @salesforce/plugin-auth@1.4.3"
> 
> Got solution here [forcedotcom/cli#757 (comment)](https://github.com/forcedotcom/cli/issues/757#issuecomment-741885504)

Thank you @4388331 ... It works for me :D

**Comment by hussain1901** [comment]
> I resolved the same issue with the plugin
> Run this in CMD "sfdx plugin:install @salesforce/plugin-auth@1.4.3"
> 
> Got solution here [forcedotcom/cli#757 (comment)](https://github.com/forcedotcom/cli/issues/757#issuecomment-741885504)

Thanks for the solution. It worked for me.

**Comment by LineeshNeel** [comment]
I had also got the same issue. 
First ran  "sfdx update" in cmd.

Then ran "sfdx plugin:install @salesforce/plugin-auth@1.4.3"
Got the following warning: " Warning: plugin:install is not a sfdx command".

Gave 'y' for the question "Did you mean plugins:install? [y/n]".
And then it worked.

**Comment by srivardhan1607** [comment]
Ran "sfdx plugin:install @salesforce/plugin-auth@1.4.3"
Thanks for the solution.

**Comment by naheedtn** [comment]
I was having the same issue, for me, just "sfdc update" in cmd worked.
Thank you to all who contributed.

**Comment by anika-shirolkar** [comment]
For me the issue was fixed when I ran "sfd**x** update". Please note it worked when I used x in sfdx and not c!

**Comment by naheedtn** [comment]
Yes correct "sfdx update" indeed.

**Comment by kimbersHolland** [comment]
"sfdx update" worked even in 11/2023 on version 7.209.6

**Comment by harshinichowdary1357** [comment]
sfdx update worked for me Thank you..!

**Comment by zaferaydinosf** [comment]
worked for me as well.

**Comment by Praneeth-L** [comment]
I got this error in Macbook, I tried Bothe the commands 
sfdx update
sfdx plugin:install @salesforce/plugin-auth@1.4.3
it did not worked for me 
can you tell me If I should set path for 'sfdx cli' in Mac if yes please tell me how

**Comment by GulT1** [comment]
worked for me too, thank you for the solutions!
