### ISSUE TITLE
Retrieve with Manifest (beta) fails

### ISSUE THREAD

**Issue by sc5148** [forcedotcom/salesforcedx-vscode#2871]
I am getting an error when clicking on  "SFDX: retrieve source in manifest from org".  
This is the error - Component conversion failed: unexpected end of file
<img width="582" alt="Screen Shot 2021-01-18 at 09 45 39 AM" src="https://user-images.githubusercontent.com/19307757/104892041-fd40f000-5971-11eb-8a46-fc80c795062a.png">

CLI version - 7.84.2
OS - Mac OS 11.1
VS Code version - 1.52.1
Salesforce Extension Pack version - 50.13.0

**Comment by brpowell** [comment]
Hi @sc5148 - I think this might occur when retrieving a StaticResource component that has a contentType of application/octet-stream and is not an archive. Do you have StaticResources in your manifest file to be retrieved? Can you try removing those and seeing if it works?

**Comment by sc5148** [comment]
@brpowell Yes commenting out static resources in the package.xml file helped. But what would be the other way to fix it if I want to retrieve static resources as well?

**Comment by lcampos** [comment]
Issue logged as W-8115028

**Comment by brpowell** [comment]
This issue with StaticResources has been fixed in a previous release.
