### ISSUE TITLE
apex test code coverage not highlighted in vs code editor.

### ISSUE THREAD

**Issue by sravani-gadaputi** [forcedotcom/salesforcedx-vscode#2872]
I set "salesforcedx-vscode-core.retrieve-test-code-coverage": true  in user and workspace settings.but even it is showing the following exception.

No code coverage information was found for this file. Set "salesforcedx-vscode-core.retrieve-test-code-coverage": true in your user or workspace settings. Then, run Apex tests that include methods in this file. You can run tests from the Apex Tests sidebar or using the Run Tests or Run All Tests code lens within the file.

it was working fine till today.Today it is showing this exception.Can you please help me on this.

**Comment by ctchipps** [comment]
I am experiencing this same behavior. I have verified that my CLI is updated to the most recent version, as well as my plugins updated to the most recent version.

I did a basic test, and it seems that if the class being tested has no inner or nested classes, then the coverage information comes back correctly in VSCode. However, if the class being tested has inner or nested classes, the the coverage is calculated seemingly randomly for one of the inner/nested classes, and no data is retrieved for the parent class.

**Comment by ctchipps** [comment]
@sravani-gadaputi This has indirectly been addressed in #2863, and the workaround is the following.

> As a workaround, since this feature is still in Beta, you can go back to the old behavior by going into your Preferences and turning off the Salesforcedx-vscode-core › Experimental: Use Apex Library setting.

**Comment by AnanyaJha** [comment]
Hi @sravani-gadaputi thanks for reporting this! As @ctchipps mentioned, the workaround is to disable the setting. There is a known issue where tests that cover multiple classes do not report coverage information for _all_ the tested classes, just one. Are you seeing the "No coverage found" behavior after running a test that covers multiple classes/files?

**Comment by AnanyaJha** [comment]
Thanks for the detailed explanation @ctchipps, we'll investigate further and let you know when a fix has been released.

**Comment by AnanyaJha** [comment]
@sravani-gadaputi @ctchipps This issue was addressed with the latest release of the VS Code Extensions. Please update to version 50.14.0 and turn the setting back on to see the changes. Let us know if you have any other feedback, thanks!

**Comment by ctchipps** [comment]
@AnanyaJha This was resolved for me
