### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hengpete** [forcedotcom/salesforcedx-vscode#2875]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.13.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
The Salesforce Cli integration extension is unresponsive. This also causes the apex extension to be unresponsive due to dependancy.

![image](https://user-images.githubusercontent.com/25019076/105195048-33b07380-5b08-11eb-8d97-809be2f87248.png)

**Comment by smaddox-sf** [comment]
Do you have the info from the clipboard?  

Can you share some context on when you hit this error? Please share:

Steps to reproduce
Expected outcome
Actual outcome
