### ISSUE TITLE
VS Code Not authorized to org 

### ISSUE THREAD

**Issue by awneeshpandey** [forcedotcom/salesforcedx-vscode#2879]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  [Please open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md)
