### ISSUE TITLE
Run All Tests & Run Test error: No default org is set. Run "SFDX: Create a Default Scratch Org" or "SFDX: Authorize an Org" to set one.

### ISSUE THREAD

**Issue by jjTorrent** [forcedotcom/salesforcedx-vscode#2883]
### Summary
When using the **Run All Tests** or **Run Test** overlay in the editor of a test class, I receive the message _No default org is set. Run "SFDX: Create a Default Scratch Org" or "SFDX: Authorize an Org" to set on._, within an already authorized org. If I reset the default org to the already authed org, then these commands start to work again. However, the same message/behavior reappears after restarting VS Code. Strangely, running tests from the command palette works normally under all circumstances.

### Steps To Reproduce:

1. Restart VS Code.
1. Open an already authed project that contains test classes. I'm using the manifest model in this scenario. 
1. Open a test class.
1. Click **Run All Tests** -- should see error.
1. Set a default org or auth a new one.
1. Click **Run All Tests** -- should work this time.
1. Restart VS Code.
1. Reopen the same project.
1. Click the same **Run All Tests** -- should see error again.

### Expected result
The test run should complete with the test results.

### Actual result
Receive the error message:
_No default org is set. Run "SFDX: Create a Default Scratch Org" or "SFDX: Authorize an Org" to set one._

### Additional information
![Screen Shot 2021-01-21 at 1 34 43 PM](https://user-images.githubusercontent.com/15893115/105402765-7304c000-5bed-11eb-8753-2cb898b0e0f6.png)

**VS Code Version**: 1.52.1

**SFDX CLI Version**: 7.84.2-a2868a68d5 darwin-x64 node-v12.18.3

**OS and version**: macOS Big Sur, v11.1

**Comment by BrotherZach** [comment]
I'm also experiencing this issue on macOS Big Sur 11.1

**Comment by AnanyaJha** [comment]
Hi @jjTorrent thanks for reporting this! We are aware of this issue and the next release of the extensions will contain a fix to address it. For now, the workaround is to go into your Preferences and turn off the `Salesforcedx-vscode-core › Experimental: Use Apex Library` setting

**Comment by AnanyaJha** [comment]
@jjTorrent @BrotherZach This issue was addressed with the latest release of the VS Code Extensions. Please update to version `50.14.0` and turn the setting back on to see the changes. Let us know if you have any other feedback, thanks!

**Comment by jjTorrent** [comment]
@AnanyaJha this worked for me

**Comment by PreddyCR** [comment]
I experienced this issue and the settings workaround resolved it. However I have just installed version 50.14.0 and the behavior is the same; it will fail unless I disable the experimental setting.

**Comment by AnanyaJha** [comment]
@PreddyCR What version of VS Code are you on and what version of the Salesforce CLI extension and Apex extension are you using?

**Comment by PreddyCR** [comment]
VSCode 1.52.1, SF CLI Integration Extension v50.14.0, installed sfdx version sfdx-cli/7.82.1-0 darwin-x64 node-v12.19.0 ; macbook pro

**Comment by AnanyaJha** [comment]
@PreddyCR I'd recommend uninstalling and re-installing the Extension Pack, it's possible all the changes were not picked up immediately because of some delays in the publishing process today.

**Comment by BrotherZach** [comment]
@AnanyaJha This is working for me as well. Thanks!

**Comment by PreddyCR** [comment]
@AnanyaJha I followed your recommendations - clearing all the extensions and reinstalling - now the symptom is different. It works as expected with Use Apex Library = off; when enabled the immediate error message is "Include the class name SCMIOC only once.". The acronym is the alias/username of my dev org. Perhaps I corrupted my config trying to resolve the actual issue?
