### ISSUE TITLE
Apex Commands - Shows as successful when there was an issue and missing line numbers on error

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/salesforcedx-vscode#2890]
Reported from customers here:
- https://twitter.com/brianmfear/status/1352680280859971584
- https://salesforce.stackexchange.com/questions/332122/vs-code-extension-no-longer-including-line-number-in-apex-test-failure-output

**Details of the issue:**. 2 problems
1 - When I run Apex tests from VS Code (leveraging Salesforce CLI), I'm accustomed to the output telling me what line my tests failed on in the event of failure.

 2 - The plugin now reports the test as "ran successfully" instead of an error, no Problems appear in the Problems tab

**Comment by ryu-727** [comment]
I'm facing same issue.

**Comment by fredrikstaahl** [comment]
Same issue here.

**Comment by pavantiruppur** [comment]
Same issue here.

**Comment by lcampos** [comment]
This issue has been fixed in release v51.2.0 of the Salesforce extensions for VSCode. Thanks for providing feedback.

<img width="1560" alt="Screen Shot 2021-02-24 at 5 41 42 PM" src="https://user-images.githubusercontent.com/1041842/109090352-aee8e480-76c7-11eb-9700-ca07b84ab6ae.png">
