### ISSUE TITLE
Impossible to diff js static resource

### ISSUE THREAD

**Issue by Bartheleway** [forcedotcom/salesforcedx-vscode#2898]
### Summary

Impossible to make a diff of a js file in the static resource folder

### Steps To Reproduce:

1.  Right click on a js file in the static resource folder
1.  Select `SFDX: Diff File Against Org`

### Expected result

Get the file diff as before.

### Actual result

Source diffing isn't supported for the file: ...\force-app\main\default\staticresources\file.js. Metadata type 'js' must be in a parent folder named 'lwc\<BundleName>'

### Additional information

This was working on 50.8.0 and probably also 50.13.0.

**VS Code Version**: 1.52.1

**SFDX CLI Version**: 7.82.0 & 7.84.2

**OS and version**: Windows 10 (Windows_NT x64 10.0.18363)

**Comment by smaddox-sf** [comment]
Hi @Bartheleway - Thanks for the feedback.  You're correct that you can't diff static resources currently.  We support a limited set today.  [See our doc for the list of metadata types this feature supports.](https://developer.salesforce.com/tools/vscode/en/user-guide/source-diff). We have work on our [roadmap](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Roadmap) to enable diff for all types.

**Comment by smaddox-sf** [comment]
@Bartheleway - We have expanded the Diff and it now includes this file type.
