### ISSUE TITLE
Unable to retriev source from org

### ISSUE THREAD

**Issue by karuny** [forcedotcom/salesforcedx-vscode#2902]
Issue Type: <b>Bug</b>

Cant retrieve source from org. I am only  able to deploy.

Extension version: 50.14.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.63GB free)|
|Process Argv|--crash-reporter-id 267acb2a-5ec7-45dc-95d0-23f29efc80b7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by smaddox-sf** [comment]
Hi @karuny - Thanks for reaching out.  We need more information to try to help.  Couple questions to start:

1. Do you have the 'Experimental: Deploy Retrieve' option enabled in VS Code settings?
2. What version of the SFDX CLI are you using?  You can see the version by using this command from the terminal window: `sfdx --version`

**Comment by karuny** [comment]
1.this option is disabled
2. sfdx-cli/7.84.2-a2868a68d5 win32-x86 node-v12.18.3


Karunya V
DC Analyst|C&M
Deloitte Consulting India Pvt. Ltd

**Comment by lcampos** [comment]
Hi @karuny, can you confirm if you're able to successfully run the retrieve command from the terminal ?

**Comment by karuny** [comment]
Pls tell me what’s the command to type in the terminal window for retrieve


Karunya V
DC Analyst|C&M
Deloitte Consulting India Pvt. Ltd

**Comment by smaddox-sf** [comment]
hi @karuny - you should see the full command in the Output panel.  the command `sfdx force:source:retrieve` and the output panel should show you the full command with the options you are using.

**Comment by karuny** [comment]
ERROR running force:source:retrieve:  Missing one of the following parameters: manifest metadata sourcepath packagenames.

The above output I received in terminal window.

Karunya V
DC Analyst|C&M
Deloitte Consulting India Pvt. Ltd

**Comment by lcampos** [comment]
@karuny looks like you are not providing the correct inputs for the command to run successfully. Here are the docs on how to run the command https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm depending on what you want to achieve. Let us know if you still get an error after providing the correct inputs.

**Comment by karuny** [comment]
ERROR running force:source:retrieve:  The specified manifest file [path/to/package.xml] does not exist, or you don't have access to it.
ERROR running force:source:retrieve:  Unexpected file found in package directory:

I kep getting errors for any of the commands listed in the document


Karunya V
DC Analyst|C&M
Deloitte Consulting India Pvt. Ltd

**Comment by lcampos** [comment]
@karuny It looks like your project is not correctly configured. I suggest you look at some of these trailheads that explain how to set a project and use the existing tools:
[Quick Start: Salesforce DX](https://trailhead.salesforce.com/en/content/learn/projects/quick-start-salesforce-dx)
[Quick Start: Visual Studio Code for Salesforce Development](https://trailhead.salesforce.com/en/content/learn/projects/quickstart-vscode-salesforce?trail_id=set-up-your-workspace-and-install-developer-tools)

I'll close this issue since it's not related to a bug in the tools but a misconfiguration of the project. Feel free to open an issue if you do run into a bug or feature request.

**Comment by karuny** [comment]
It was working earlier since I created this project , suddenly for some days back it is not retrieving


Karunya V
DC Analyst|C&M
Deloitte Consulting India Pvt. Ltd
