### ISSUE TITLE
"Running SFDX: Authorize an Org " is keeping on running

### ISSUE THREAD

**Issue by himagopi** [forcedotcom/salesforcedx-vscode#2906]
"Running SFDX: Authorize an Org " is keeping on running.
I have updated the cli,but still the issue is not resolved.
Sometimes its authorizing the org,but that pop up of authorise an org is keeping on running until we manually cancel it

**Comment by lcampos** [comment]
Hi @himagopi can you provide more information on how to replicate this issue. Things like which OS, CLI version, VSCode extension version, etc.

**Comment by himagopi** [comment]
Thank you for the response

Windows 10,64 bit
Visual force code:1.52.1
CLI version: sfdx-cli/7.83.0-eba9c6a927 win32-x64 node-v12.18.3

Please let me know if you need any other information

**Comment by himagopi** [comment]
![image](https://user-images.githubusercontent.com/69029217/106594527-3b483180-6578-11eb-9c29-8a91cfa52e2c.png)


Please check the above

**Comment by himagopi** [comment]
The Running SFDX:Authorize an org is not getting closed

**Comment by tednesseth** [comment]
was this ever get addressed?

**Comment by anupam081** [comment]
Hi
Me too facing the same issue. When i try to authorize by cmd or vscode, the process keeps on running.

After login to the instance it get stuck at below URL.
https://cunning-badger-52498-dev-ed.my.salesforce.com/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAXf3fMNxMDAwMDAwMDAwMDAwMDAwAAAA5jnBcyjwkbjo1h2DNfU1mDKD6w8eLJ1JjN6wR_-uHLOXNAv_pLw9b02b7ICBGQ6-dGTf3NIX46z0zFjC-ypdVPrZ73vs4O48HiqwCiiiNWvwB9CRfEbLWDFtI2-_E6hCh8ocHqqj8VU9ohE98Eki0o0aQUnDAMURGsQLc04JiQTNcWKSjOG-pVwEvGdLJp4ZKE1ioID3xbLucOj3ZGHHoBITzinh7NikImfj5XEdZrBzTbFRv_KO2UA42puXhpogBq3M6ZzGbeoFtLjXzulHv-9wgyCbxwT8beOnxPEB7Zl6-VlO2O4nDiXV_DEfhua6ohxZH_6-IqenU-A15U10zfuMSCPhft4FGpvx-Y4Xv3HzTuc_8qSmvC0ahtZg_NHX5bAV-2VJK5fNiza0WvUUMQx6QDxlipUOsnpmGozqH-ml-OS4RexygZriO2swcciY65yt_yBOmk2A6VeBgBNqTj3FzeCBwE70cefGOixMOek-XQoIwMPH0GHiNZZl-oDNTrcpUhZGfpGMcqo016clACE1TCUtWNhIrKzxGNwXEmc4tD7uFjgFCeDOBZc-FxpB9Q4YVBIcBIUagjkZldVjz0-_autTRa9mvxdh1Zb2QXM9lqcV8C91TU3y9tZH6ET50A%3D%3D

**Comment by simonjensenkell** [comment]
Yup am having lots of issues with the oAuth flow back to VS. after updating .
  
Oauth seems to be failing on the postback to localhost and eventually times out with a generic error.

**Comment by lcampos** [comment]
Hi everyone, the root cause of the issue was a problem at the Salesforce CLI level (VSCode is currently delegating authentication to it). You can follow the steps in this comment (https://github.com/forcedotcom/cli/issues/890#issuecomment-790062421) to get the fix that was released a couple of days ago.
