### ISSUE TITLE
Error running command sfdx.force.source.retrieve.component: undefined. This is likely caused by the extension that contributes sfdx.force.source.retrieve.component?

### ISSUE THREAD

**Issue by avulasanyasisfdc** [forcedotcom/salesforcedx-vscode#2921]
Hi Team,

I am unable to retrieve the Components from cloud from VS Code.

While clicking the download data from cloud ,Getting the issue!

Error running command sfdx.force.source.retrieve.component: undefined. This is likely caused by the extension that contributes sfdx.force.source.retrieve.component.

Can you please help on this.

Salesforce extension pack version 50.14.0
Salesforce CLI 50.14.0

Stacktrace :

Retrieve Source from Org

09:21:50.219 sfdx force:source:retrieve --json --loglevel fatal -m LightningComponentBundle:hello
{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'fileName' of undefined",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "TypeError: Cannot read property 'fileName' of undefined\n    at Function.getMetadataFileNameFromBundleFileProperties (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\bundlePathHelper.js:42:48)\n    at Function.getPathFromBundleTypeFileProperties (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\bundlePathHelper.js:36:43)\n    at LightningComponentBundleMetadataType.getDefaultAggregateMetadataPath (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\bundleMetadataType.js:31:52)\n    at SourceWorkspaceAdapter.processMdapiFileProperty (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:286:59)\n    at C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:166:22\n    at Array.forEach (<anonymous>)\n    at MdapiPullApi._syncDownSource (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:158:31)\n    at SourceRetrieve.retrieveFromManifest (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieve.js:177:64)\n    at async SourceRetrieve.retrieve (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieve.js:65:27)\n    at async SourceRetrieveCommand.execute (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieveCommand.js:32:16)\n    at async SourceRetrieveCommand.execLegacyCommand (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:149:29)\n    at async SourceRetrieveCommand.run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\commands\\force\\source\\retrieve.js:32:16)\n    at async SourceRetrieveCommand._run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:93:40)\n    at async Config.runCommand (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\nOuter stack:\n    at Function.wrap (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at SourceRetrieveCommand.catch (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:248:46)\n    at async SourceRetrieveCommand._run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:97:13)\n    at async Config.runCommand (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Program Files\\Salesforce CLI\\client\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Program Files\\Salesforce CLI\\client\\dist\\cli.js:32:20)",
  "warnings": []
}
09:22:21.746 sfdx force:source:retrieve --json --loglevel fatal -m LightningComponentBundle:hello
 ended with exit code 1

**Comment by lcampos** [comment]
Hi @avulasanyasisfdc , the stack trace you posted suggests that the error is at the CLI level. Can you post which CLI version you are using (run `sfdx version` on the terminal) ?
