### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by CristopherBenavides** [forcedotcom/salesforcedx-vscode#2925]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.16.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
I'll close this since there's not enough information for us to look into it. Feel free to re-open the issue if you can provide steps to replicate the issue you ran into.
