### ISSUE TITLE
Getting Error: Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)

### ISSUE THREAD

**Issue by GWCLPLfacilitator** [forcedotcom/salesforcedx-vscode#2938]
### Summary

_Short summary of what is going on or to provide context_.  In VS Code I'm getting this error Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)
I ran sfdx update from CMD and it says I'm up to date but it does give a weird warning

sfdx-cli: Updating CLI... already on latest version: 7.85.1-2fb9e41053
warning "salesforcedx > @salesforce/plugin-apex > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
sfdx-cli: Updating plugins... done

am able to create project directly via CMD but not via VSCode and unable to run any other SFDX commands in VSCode (but I was able to when I last used it on Tuesday - 2 days ago).

### Steps To Reproduce:

1.  Open VS Code
2.  Type Ctrl-Ship-P, then start typing SFDX and select SFDX: Create Project
3.  then I get error message

### Expected result

_Describe what should have happened_. It should have taken me to the next step and let me put in my project name.

### Actual result

_Describe what actually happened instead_. Error message as already indicated

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/32439283/107706730-c4edb280-6c8e-11eb-9fee-cee0616936c3.png)

**VS Code Version**:1.53.2

**SFDX CLI Version**:7.85.1-2fb9e41053

**OS and version**: Windows 10

**Comment by smaddox-sf** [comment]
Hi @GWCLPLfacilitator - Thanks for reaching out.  What version of the Salesforce extensions are you running?  Here's where you can see that:

![image](https://user-images.githubusercontent.com/59572234/107802331-0b3a2480-6d16-11eb-96d3-e9ad4f3e5b11.png)

**Comment by GWCLPLfacilitator** [comment]
50.17.0

**Comment by lcampos** [comment]
Hi @GWCLPLfacilitator , in the latest release (v51.2.0) there's a fix to the scaffolding commands which addresses this issue. Can you update to that version and run the command on your side ?

**Comment by GWCLPLfacilitator** [comment]
@lcampos Updated and its working now!  Thank you!

**Comment by lcampos** [comment]
Glad this fixed your problem @GWCLPLfacilitator. I'll close this issue now, thanks for your feedback.
