### ISSUE TITLE
SFDX: Set a Default Org doesn't escape spaces nor uses quotation marks

### ISSUE THREAD

**Issue by gvgramazio** [forcedotcom/salesforcedx-vscode#2939]
The command `SFDX: Set a Default Org` is a shortcut for the salesforce cli command `sfdx force:config:set defaultusername=<org-alias>`.
Suppose that the org alias is "Awesome Alias". When you run the above command, it is converted to `sfdx force:config:set defaultusername=Awesome` instead of `sfdx force:config:set defaultusername=Awesome\ Alias` or `sfdx force:config:set defaultusername="Awesome Alias"`

**VS Code Version**:
1.53.1

**SFDX CLI Version**:
7.84.2

**OS and version**:
macOS Catalina 10.15.7

**Comment by smaddox-sf** [comment]
Thanks for the feedback @gvgramazio

**Comment by randi274** [comment]
Hi @gvgramazio - we've made some recent changes, and this appears to be working for me today! With that in mind, I'm going to close this issue, but let us know if you're still seeing this one and we can troubleshoot further.
<img width="753" alt="Screen Shot 2022-11-08 at 4 36 54 PM" src="https://user-images.githubusercontent.com/9795193/200680893-95227a7f-e6fb-4568-aa1b-7fbbcce2dcb4.png">
