### ISSUE TITLE
Retrieve With Manifest (beta) failed to run "Missing metadata type definition in registry for id 'sharingguestrule'"

### ISSUE THREAD

**Issue by peternoges** [forcedotcom/salesforcedx-vscode#2940]
Hello, 

I've enabled beta retrieval (https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements/), and i restarted vscode.   My manifest/package.xml retrieval fails rather immediately and gives the following errors:

Missing metadata type definition in registry for id 'sharingguestrule'
06:38:02.203 Starting Retrieve With Manifest (beta)

Missing metadata type definition in registry for id 'sharingterritoryrule'
06:38:12.736 Starting Retrieve With Manifest (beta)

Missing metadata type definition in registry for id 'workflowknowledgepublish'

I made small progress by removing workflowknowledgepublish,sharingterritoryrule,sharingguestrule from package.xml.  Small progress because it not longer immediately fails, but now it fails without any error message.  Same when i change package version from 50.0 to 49.0.  **So the question here is how can we obtain more verbose logging around the Retrieve With Manifest (beta) command?**     

My workaround (untested) is to turnoff the beta retrieval.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by lcampos** [comment]
Hi @peternoges , are you using the latest version of the extensions (v50.17.0) ? Also, can you share a snippet on how you are adding those types in the package.xml ? Would like to know if this happens when providing specific names, using `*` character or both.

**Comment by peternoges** [comment]
Hi @lcampos 
I'm using salesforce.salesforcedx-vscode v50.17.0 confirmed via the extensions listing:
![image](https://user-images.githubusercontent.com/7834562/107823731-19e40400-6d35-11eb-9d19-0bcfb9b2e023.png)

The seemingly relevant parts of my package.xml are below;  

...
```
  <types>
    <name>SharingTerritoryRule</name>
    <members>*</members>
  </types>
    <types>
    <name>SharingGuestRule</name>
    <members>*</members>
  </types>
    <types>
    <name>WorkflowKnowledgePublish</name>
    <members>*</members>
  </types>
...
```

My workstream to generate the package.xml is below:
basically i call a bunch of sfdx force:source:retrieve commands to build a large force-app directory,  then for my own reasons I like to have a package.xml of the same so i simply run sfdx force:source:convert -r ./force-app/ -d convertedToMdapiForItsPackageXML

The package.xml is then given to me within my convertedToMdapiForItsPackageXML folder.  I then copy the package.xml from convertedToMdapiForItsPackageXML into my root's force-app folder and that's where the issue with manifest retrieval occurs.

**Comment by smaddox-sf** [comment]
This has been fixed

**Comment by AltiusRupert** [comment]
@smaddox-sf 

I am having this issue again with salesforce.salesforcedx-vscode v51.11.0

In the CLI, it is working well with sfdx force:source:retrieve -x manifest/package-map.xml with plugin salesforcedx v 51.1.7

**Comment by bhushanon** [comment]
@smaddox-sf
I am having this issue again with salesforce.salesforcedx-vscode v52.1.0

Missing metadata type definition in registry for id '_actionplantemplate_', my package contain below entry 
```
        <type>
		<members>Schedule_client_meeting_f5a3d039_b9fd_1122_2222_1bb6e23a45c6</members>
		<name>ActionPlanTemplate</name>
	</types>
```

**Comment by FabienTaillon** [comment]
Same here with latest extensions (v53.8.1): `Missing metadata type definition in registry for id 'fieldrestrictionrule'`

**Comment by MillerYA** [comment]
Having this issue with Salesforce CLI 63.12.0

Missing metadata type definition in registry for id 'WorkflowFlowAutomation'.
09:46:50.552 Starting SFDX: Retrieve This Source from Org

**Comment by pnoges-northeastern** [comment]
> [@MillerYA](https://github.com/MillerYA) Do you have a fix yet? I'm having the same issue.

Try `sf update`.  Does the issue still happen after?

**Comment by peternoges** [comment]
> [@MillerYA](https://github.com/MillerYA) Do you have a fix yet? I'm having the same issue.

Have you tried `sf update` then try again? Does the problem still happen?
