### ISSUE TITLE
Execute Anonymous Apex with Currently Selected Text stopped working

### ISSUE THREAD

**Issue by willeg** [forcedotcom/salesforcedx-vscode#2947]
### Summary

The command _SFDX: Execute Anonymous Apex with Currently Selected Text_ has stopped working some time between Thursday Feb 11, 10 PM Swiss time, and Friday Feb 12, 10 PM Swiss time.

### Steps To Reproduce:

1.  step 1: open hello.apex
1.  step 2: clear the OUTPUT window
1.  step 3: on a new line enter the code `System.debug('Hello!');`
1.  step 4: ctrl-P and select SFDX: Execute Anonymous Apex with Currently Selected Text

### Expected result

the OUTPUT window contains the log output of the code execution.
a success or failure message appears in the lower right corner.

### Actual result

the OUTPUT window stays empty.
a success or failure message, depending on whether or not the code compiles, appears in the lower right corner.
sometimes (not with certainty reproducible) there is a failure message with the text: 
- Command 'SFDX: Execute Anonymous Apex with Currently Selected Text' resulted in an error (command 'sfdx.force.apex.execute.selection' not found)'

### Additional information

My Visual Studio Code displays the following in Help > About:
> Version: 1.53.2 (user setup)
> Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Date: 2021-02-11T11:48:04.245Z
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042

**VS Code Version**: 1.53.2 (user setup)

**SFDX CLI Version**: sfdx-cli/7.85.1-2fb9e41053 win32-x64 node-v12.18.3

**OS and version**: Windows_NT x64 10.0.19042

**Comment by sfsholden** [comment]
@willeg Thank you for reporting this issue. Last week we made some changes to where the output of this text is presented. From the `Output` view it should now be available in the drop down `Apex`. Please let us know if the results are not presented in this view and we'd be happy to follow up.

**Comment by sfsholden** [comment]
@willeg We are going to be logging a bug for this issue with `SFDX: Execute Anonymous Apex with Currently Selected Text `. Thank you again for reporting it!

**Comment by lcampos** [comment]
@willeg can you confirm if you are using a setting called `salesforcedx-vscode-core.experimental.useApexLibrary` ? If so, what's the value you've set on it ?

**Comment by willeg** [comment]
@lcampos: yes, the setting is checked; must have been introduced by the latest release (?!)

**Comment by willeg** [comment]
@sfsholden: I do see the output when I select `Apex Extension` in the output window's dropdown (oughtn't this to get selected automatically?)

**Comment by lcampos** [comment]
@willeg thanks for confirming. We introduced that setting a few releases ago to enable a more performant way to run Apex commands. However, in the last release the auto-focus on the correct Output channel stopped working and that's why you are experiencing the current behavior. We have a fix for this and it will go out in the next release. Thanks for opening this issue and providing feedback.

**Comment by sfsholden** [comment]
Closing.

This issue should now be fixed as of release version 51.2.0. Thank you for reporting this issue @willeg

**Comment by willeg** [comment]
Thank you all.

**Comment by willeg** [comment]
thank you for acting so quickly on my issue report
Georg Wille
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 25/02/2021 - 00:14 (CEST)
An : salesforcedx-vscode@noreply.github.com
Cc : g.wille@bluewin.ch, mention@noreply.github.com
Betreff : Re: [forcedotcom/salesforcedx-vscode] Execute Anonymous Apex with Currently Selected Text stopped working (#2947)
Closing.
This issue should now be fixed as of release version 51.2.0. Thank you for reporting this issue @willeg
