### ISSUE TITLE
Retrieve says successful but not retrieving the latest

### ISSUE THREAD

**Issue by karuny** [forcedotcom/salesforcedx-vscode#2948]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  [Please open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md)
