### ISSUE TITLE
Execute Anonymous Apex with Editor Contents - is not showing output vs code 

### ISSUE THREAD

**Issue by vikashmnk** [forcedotcom/salesforcedx-vscode#2951]
### Summary

Execute Anonymous Apex with Editor Contents using vs code not working. Not showing any output in output pane. 

### Steps To Reproduce:

1.  write System.debug('config'); in scripts --> apex ---> hello.apex
2.  Save it and try to execute SFDX:Execute Anonymous Apex with Editor Contents
3. 

### Expected result

Ideally it should show something in output pane .

### Actual result

Nothing showing in out pane.

### Additional information

_Feel free to attach a screenshot_.

![image](https://user-images.githubusercontent.com/3623601/107954918-1d8cba80-6fc3-11eb-9768-4132417455fc.png)

**VS Code Version**:
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z (4 days ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**SFDX CLI Version**:
v50.17.0

**OS and version**:
MacOs Catalina

**Comment by AnanyaJha** [comment]
Hi @vikashmnk thanks for reporting this! With the last release we moved the output for the Apex commands over to the Apex output channel. In the bottom panel, could you click on the drop down menu where it says `Salesforce CLI`? Scroll down to where it says `Apex` and select that option. The output window should switch to show the output from the `Execute Anonymous Apex` command

**Comment by sfsholden** [comment]
Closing issue - this is working as designed with the latest changes. Thanks!

**Comment by vikashmnk** [comment]
Thanks @AnanyaJha, Now I can see the output but still if I am clicking on Show button on progress bar then it should show the apex extension. Please refer the second screen shot
![Uploading Screenshot 2021-02-16 at 10.32.55 PM.png…]()

![image](https://user-images.githubusercontent.com/3623601/108096858-76ce1a00-70a7-11eb-8bd6-a71757573c4e.png)
