### ISSUE TITLE
Setting to change to pull/push operations in context menu for source-tracked Sandboxes

### ISSUE THREAD

**Issue by dschibster** [forcedotcom/salesforcedx-vscode#2952]
I am currently finding my way around source-tracking on Sandboxes, which I think is an amazing feature, however I am finding it hard currently to change the workflow that I (and many others) have gotten used to: Deploying / Pushing on Save and using the Command Palette for everything else.

If I am not mistaken, Auth with a Sandbox will always give you Deploy and Retrieve commands, both in the Command Palette and the context menu currently. Does not matter if the Sandbox is source-tracked or not. That means in order to get to the push/pull commands, I always have to go to the Terminal and type in what I want to do. That is definitely possible, will however hamper acceptance among colleagues. 

Is it feasible to detect a source-tracked Sandbox and enable push/pull accordingly in the command palette? If not that, maybe a setting that we could use on the workspace-level would help.

In the fear of repeating something everyone already knows: I have updated the CLI and checked everywhere I thought logical, didn't find anything regarding this issue however.

Thanks in advance.

**Comment by smaddox-sf** [comment]
Hi @dschibster - Thanks for providing this feedback.  You are correct that push/pull is not currently exposed in the VS Code Extensions for source-tracked sandboxes.  The PM of source-tracked Sandboxes is considering exposing this and I will pass this feedback along to her for consideration.

**Comment by jdgirald** [comment]
Hi @smaddox-sf, any updates on this. Thanks

**Comment by JSaterdalen** [comment]
@smaddox-sf Would love to see this addressed, as it is actively causing issues in my source-tracked sandboxes. When the VS Code setting "Salesforcedx-vscode-core › Push-or-deploy-on-save" is enabled, VS Code incorrectly runs a source:deploy on save—instead of source:push—when saving a file against a source-tracked sandbox.

This messes with source tracking, due to source tracking [not supporting source:deploy and source:retrieve](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_tracking_best_practices.htm).

**Comment by FabienTaillon** [comment]
Any update on this one ? What's the point of having to manually type the source:push/pull manually on a source tracked sandbox ?

**Comment by jag-sfdc** [comment]
@FabienTaillon @JSaterdalen - We have created a bug to take care of this. Thank you so much for reporting this.

**Comment by jeffb-sfdc** [comment]
@dschibster we are working at this at the moment.

**Comment by ulistaerk** [comment]
There is no owner on this issue. Is there any update so far? @jeffb-sfdc @FabienTaillon

**Comment by jdgirald** [comment]
this should be simpler now that the sfdx deploy and retrieve command support source tracking since version 7.139.0

> --tracksource : Enable source-tracking for a single command run.

**Comment by AnanyaJha** [comment]
Hi all! Thanks for the patience on this issue - we've had limited bandwidth but the team will be working on this change before the end of the year. We'll post an update once it's out!

**Comment by jefersonchaves** [comment]
Hello @AnanyaJha - It's awesome to hear it. Is there something we can do to help out get source-tracking-enabled sandboxes over the line in VsCode?

**Comment by AnanyaJha** [comment]
Hi @jefersonchaves - thanks for checking in on this issue. Unfortunately, the team's been stretched thin so we'll be addressing this item post holidays. We're always open to customer contributions so feel free to check out our [contributing docs ](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/CONTRIBUTING.md) to get started :D

**Comment by dustinrediess-sikich** [comment]
Hello @AnanyaJha - Is there any update on this particular issue?

**Comment by FabienTaillon** [comment]
@AnanyaJha I've added a draft PR for it, I just have one question that I've asked on my PR thread. Once I have the answer I'll finish it.

**Comment by AnanyaJha** [comment]
@FabienTaillon Thanks for the contribution as always Fabien!

**Comment by dustinrediess-sikich** [comment]
Thank you @FabienTaillon and @AnanyaJha! This is already helping my team a great deal!
