### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by shahrozbeig** [forcedotcom/salesforcedx-vscode#2964]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.17.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: 
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11785,
		"activateCallTime": 6,
		"activateResolvedTime": 3,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-lwc",
				"_lower": "salesforce.salesforcedx-vscode-lwc"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```
:warning:

**Comment by lcampos** [comment]
Hi, there's not enough information here for us to replicate the problem you are experiencing and work on a fix. I'll close this for now but feel free to re-open if you can provide the needed information.
