### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by utkarshsoni1996** [forcedotcom/salesforcedx-vscode#2968]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.17.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
Hi, there's not enough information here for us to replicate the problem you are experiencing and work on a fix. I'll close this for now but feel free to re-open if you can provide the needed information.
