### ISSUE TITLE
Active Scratch Org can't be set as the default org

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#2970]
### Summary

Active Scratch Org is not visible to be set as default when using the extension

![image](https://user-images.githubusercontent.com/55927613/108715073-43a9e180-7512-11eb-877b-9599f0971c9e.png)

### Steps To Reproduce:

1. No idea. I'm pretty sure it was being displayed last week.

### Expected result

Any Scratch Org connected to sfdx should be visible

### Actual result

A Scratch Org is not present

**VS Code Version**:
![image](https://user-images.githubusercontent.com/55927613/108715235-7b188e00-7512-11eb-94d6-1824df2303ce.png)

**SFDX CLI Version**:
![image](https://user-images.githubusercontent.com/55927613/108715273-8b306d80-7512-11eb-840c-5ab3cf01e1a2.png)

**OS and version**: Windows 10

**Comment by AllanOricil** [comment]
This could be caused by the same problem as in this one https://github.com/forcedotcom/salesforcedx-vscode/issues/2738
But this is the first time I'm seeing it with a Scratch Org I created.

**Comment by brpowell** [comment]
Hi @AllanOricil, I think I've seen this if the dev hub used to create the scratch org was disconnected or unset. Can you try reauthorizing with the dev hub associated with the scratch org?

**Comment by AllanOricil** [comment]
@brpowell in the image above you can see that the devhub is Connected. This SO was created using the `pro_dev_hub_2`.

But today, after restarting, the computer the Scratch Org appeared in the list. I did not do anything else. Maybe VSCode had to be restarted?

![image](https://user-images.githubusercontent.com/55927613/108823288-1fa0db80-75b8-11eb-83ea-22b788096bd2.png)

**Comment by lcampos** [comment]
That's weird, I've seen similar behavior happen when there's some update to VSCode or an extension and VSCode attempts to "hot-swap" the code so you avoid restarting it. Do you remember if there were any updates like this happening on your machine ? We haven't touched that area of the code in the extensions lately so I'm curious if there's something else we're missing here.

**Comment by AllanOricil** [comment]
@lcampos today again a SO I created is not showing up :/ Could it be related to the new auth plugin? Because this started to happen after I installed it. 

In the image below I have a SO selected as the default one, but I can't select it using the vscode extension

![image](https://user-images.githubusercontent.com/55927613/109149705-d8ede580-775f-11eb-89a8-4761b4e93277.png)

**Comment by AllanOricil** [comment]
Ohhhhh my bad. The extension shows the SOs for the default devhub.  After setting the defaultdevhub everything worked as expected.

Could you guys add another little button in the status bar to quickly select the devhub?

![image](https://user-images.githubusercontent.com/55927613/109150390-ba3c1e80-7760-11eb-86fd-3a3b32e8d6b5.png)

**Comment by lcampos** [comment]
@AllanOricil glad this was only a misunderstanding and not a bug. Specific to your last comment, we've started talking about adding new features to manage environments from VSCode. It's early tho but we'll make sure to post a spec on the repo once we have a proposal so we can get feedback.
cc @smaddox-sf

**Comment by baslu93** [comment]
@AllanOricil @lcampos 

In my case I create the Scartch Orgs from form a remote pipeline, which is caring about different configs;
when they're ready, I share the credentials with the devs, who don't have access to DevHub.

Why the Scratch Orgs displayed are dependent from the DevHub?

**Comment by dgonch5** [comment]
This was very useful. In summary, for the scratch org to appear in VS Code when connecting to a scratch org, must have a default dev hub specified. 

To specify a default dev hub, run:
`sf config set target-dev-hub=NAME_OF_DEVHUB`

**Comment by AllanOricil** [comment]
I can't believe 3y have passed 😐
Good that this was helpful
