### ISSUE TITLE
Unable to Authorize an org

### ISSUE THREAD

**Issue by ahujaba** [forcedotcom/salesforcedx-vscode#2982]
Hello from two days I am trying to authorize my org but I am unable to do so. I killed my port 1717 but still not working.

**Comment by mxalfrod** [comment]
Having the same issue try using force:auth:device:login instead it works for now.

**Comment by mxalfrod** [comment]
Update just by uninstalling and reinstalling Salesforce CLI from my windows computer fixed the issue.

**Comment by smaddox-sf** [comment]
Duplicate #2931
