### ISSUE TITLE
Deploy Retrieve (Beta) does not focus on the output panel

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/salesforcedx-vscode#2987]
### Summary
When running deploy/retrieve with `Experimental: Deploy Retrieve` enabled, the 'Show' button does not jump to the output results.

### Steps To Reproduce:
1.  Enable `Experimental: Deploy Retrieve`
1.  Run a Deploy or Retrieve
1. Click the 'Show' button after the command has finished.

### Expected result
When I click the `Show` Button, I should be taken to the output of the command.

### Actual result
Nothing happens.

![Deploy (Beta) successfully ran output](https://user-images.githubusercontent.com/45604118/109187625-4e9d8580-774f-11eb-9a5d-cdadc5ea09f4.png)

**Comment by floralan** [comment]
@sfsholden We have removed the Experimental: Deploy Retrieve flag. Please checkout our newest version to find the new Deploy/Retrieve command.
