### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by marriola-acumensolutions** [forcedotcom/salesforcedx-vscode#2990]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.2.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lcampos** [comment]
Hi, this issue does not have enough information for us to replicate it and work on a fix. I'll close this for now but feel free to re-open it when you can provide steps for us to replicate it.
