### ISSUE TITLE
Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by KarolPiekarczykWaeg** [forcedotcom/salesforcedx-vscode#2992]
Hello,
I installed Visual Studio Code and Salesforce Extension Pack on a new computer. Intelisense and unit testing are not working. I've already tried installing other versions, removed the cache, installed different versions of jdk. Please help. 
![image](https://user-images.githubusercontent.com/78802005/109298983-acf06400-7834-11eb-9822-ef620eb0a883.png)

**Comment by smaddox-sf** [comment]
Hi @KarolPiekarczykWaeg - Can you share more information so we can try to troubleshoot this?
1. What steps are you executing to see these errors?  Just opening VS Code and attempting to open an existing project? 
2. What version of things are you running?  Please include:
**VS Code Salesforce Extension Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by KarolPiekarczykBmx** [comment]
Hi @smaddox-sf,
VS Code Salesforce Extension Version: v51.2.0
SFDX CLI Version: 7.81.0.0
OS and version: Windows 10 Home, 20H2 19042.804

**Comment by KarolPiekarczykWaeg** [comment]
Hi @smaddox-sf,
VS Code Salesforce Extension Version: v51.2.0
SFDX CLI Version: 7.81.0.0
OS and version: Windows 10 Home, 20H2 19042.804

**Comment by KarolPiekarczykWaeg** [comment]
Hi @smaddox-sf ,
today it started working. If you fixed it, thank you.

**Comment by smaddox-sf** [comment]
@KarolPiekarczykWaeg - Happy you are unblocked!
