### ISSUE TITLE
sfdx extension is removing the '\' from the filepaths downstream of operating dir when attempting to reference specific files

### ISSUE THREAD

**Issue by aotolbert** [forcedotcom/salesforcedx-vscode#2994]
I am currently unable to deploy anything to the org despite the UI returning a success message. I am able to authorize, and open the org without any issues but there appears to be a bug when the app attempts to interpret the provided file location but is returning an object that VSCode interprets as a success:

The code that is executed when attempting to deploy to SFDC via the 'SFDX: Deploy Source To Org' function:

sfdx force:source:deploy --sourcepath c:\**Users\adam.tolbert\Documents\Code_Repo\SalesForceRepo\Full_Sandbox\force-app\main\default\classes\TestUtilityClasses.cls** --json --loglevel

And the program IMMEDIATELY (typically takes 5-10 sec for a successful deploy attempt) returns a success message (see image of multiple attempts that were 'successful' but didnt actually alter the org data:

![image](https://user-images.githubusercontent.com/40216064/109339224-533c6980-7835-11eb-9dae-ac42270b82cb.png)

When running the exact same code block except with a tracer on the output I see that it is returning a formatted JSON object and the error is quite clearly the removal of the \ characters in the filepath.

adam.tolbert@THSCRWS52 MINGW64 ~/Documents/Code_Repo/SalesForceRepo/Full_Sandbox (Adams)
$ sfdx force:source:deploy --sourcepath c:\**Users\adam.tolbert\Documents\Code_Repo\SalesForceRepo\Full_Sandbox\force-app\main\default\classes\TestUtilityClasses.cls** --json --loglevel trace
```
{
  "status": 1,
  "name": "SourcePathInvalid",
  "message": "The sourcepath \"c:\\Users\\adam.tolbert\\Documents\\Code_Repo\\SalesForceRepo\\Full_Sandbox\\Usersadam.tolbertDocumentsCode_RepoSalesForceRepoFull_Sandboxforce-appmaindefaultclassesTestUtilityClasses.cls\" is not a valid source file path.",
  "exitCode": 1,
  "commandName": "SourceDeployCommand",
  "stack": "SourcePathInvalid: The sourcepath \"c:\\Users\\adam.tolbert\\Documents\\Code_Repo\\SalesForceRepo\\Full_Sandbox\\Usersadam.tolbertDocumentsCode_RepoSalesForceRepoFull_Sandboxforce-appmaindefaultclassesTestUtilityClasses.cls\" is not a valid source file path.\n    at Function.create (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:160:16)\n    at Object.exports.getSourceElementsFromSourcePath (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:145:36)\n    at async SourceDeployApi.doDeploy (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceDeployApi.js:58:43)\n    at async SourceDeployCommand.execLegacyCommand (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:149:29)\n    at async SourceDeployCommand.run (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\salesforce-alm\\dist\\commands\\force\\source\\deploy.js:32:16)\n    at async SourceDeployCommand._run (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\n    at async Config.runCommand (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\adam.tolbert\\AppData\\Local\\sfdx\\client\\7.88.4-3b2e55c3f1\\dist\\cli.js:121:21)",
  "warnings": []
}
```

The interesting thing is that by altering the sourcepath to something really invalid (adding a trailing \) it will throw the same error but in an actual error format that VSCode interprets.

```
adam.tolbert@THSCRWS52 MINGW64 ~/Documents/Code_Repo/SalesForceRepo/Full_Sandbox (Adams)
$ sfdx force:source:deploy --sourcepath c:\Users\adam.tolbert\Documents\Code_Repo\SalesForceRepo\Full_Sandbox\force-app\main\default\classes\TestUtilityClasses.cls\ --json --loglevel trace
ERROR running force:source:deploy:  The sourcepath "c:\Users\adam.tolbert\Documents\Code_Repo\SalesForceRepo\Full_Sandbox\Usersadam.tolbertDocumentsCode_RepoSalesForceRepoFull_Sandboxforce-appmaindefaultclassesTestUtilityClasses.cls --json" is not a valid source file path.

```

This is really hampering my development as I am forced to use the IDE in the Developer Console built into SF........ not a great experience.

**Comment by aotolbert** [comment]
UPDATE: I appear to have been able to resolve this issue by opting into the Experimental/Beta (Deploy/Retrieve) in theVSCode 
 Salesforce CLI Integrations -> Extension Settings -> Salesforcedx-vscode-core › Experimental: Deploy Retrieve but turning that off causes the bug to return.

**Comment by aotolbert** [comment]
FURTHER UPDATE:

This filepath rewriting appears to be affecting all of the sfdx commands that involve referencing a file:

This is my attempt to delete a different file in the same org using the 'SFDX Delete This from Project and Org'  feature and received the following error (when tracing the logs of the autogenerated execution command)


```

$ sfdx force:source:delete --sourcepath c:\Users\adam.tolbert\Documents\Code_Repo\SalesForceRepo\Full_Sandbox\force-app\main\default\classes\SelectorTests.cls --noprompt --loglevel trace
ERROR running force:source:delete:  The sourcepath "c:\Users\adam.tolbert\Documents\Code_Repo\SalesForceRepo\Full_Sandbox\Usersadam.tolbertDocumentsCode_RepoSalesForceRepoFull_Sandboxforce-appmaindefaultclassesSelectorTests.cls" is not a valid source file path.

```

**Comment by lcampos** [comment]
Hi @aotolbert thanks for logging this issue. You've covered different areas of the product here so I'll do a break-down of the info so far since they require different answers.

**Issues with force:source:delete**
I've seen issues reported around that specific command. I'm not sure this is part of the know issues around it but I suggest you follow/post on this gh issue https://github.com/forcedotcom/cli/issues/829 .

**Issue with CLI deploy**
Based on the info you've provided it looks like this happens when you call the `force:source:deploy` command from VSCode and also if directly executing the command through a terminal. Can you post which Salesforce CLI version you are currently using (e.g. $ sfdx version) ?

**Using the experimental deploy retrieve setting**
I want to shed some light on this setting which will explain why that fixes your current issue with the CLI. This is a new/more performant implementation of the deploy/retrieve logic which does not use the Salesforce CLI at all. It is currently in beta because we are finalizing some small gaps on it. This will become the default option for deploying/retrieving metadata and I suggest you start using it if possible.
