### ISSUE TITLE
Running Apex Test from command palette is not showing in Output

### ISSUE THREAD

**Issue by quangxvu** [forcedotcom/salesforcedx-vscode#2995]
If I run a deploy command, the output window will show something like 
`Starting SFDX: Deploy Source to Org

15:10:21.816 sfdx force:source:deploy --sourcepath [filepath]`

If I execute an apex test command, either by clicking the Run Test link or from the command palette, the output window doesn't show anything. Normally the output window would show the result of the command and the test coverage results, but it simply doesn't display anything.

**Comment by smaddox-sf** [comment]
Hi @quangxvu - Recently we made some changes to where the output of this text is presented. From the Output view it should now be available in the drop down Apex. Please let us know if the results are not presented in this view and we'd be happy to follow up.

**Comment by robcowell** [comment]
@smaddox-sf - I too experienced this issue until I read your comment above, so it's not self evident unless one religiously reads release notes (most folks don't, including myself).  What's the reasoning behind this change?  When executing the test, is it possible  to automatically switch to that output view if you're not already on it?  I feel that would be a better Dev UX if you're moving it elsewhere

**Comment by AnanyaJha** [comment]
@robcowell Thanks for raising those points, we'll log a bug to switch to the appropriate output view if you're not already on it. This change was part of an ongoing effort to separate the roles & responsibilities of each extension - so the output for Apex test runs, anonymous Apex executions, etc. were all moved to the Apex output channel.

**Comment by MirandaJanell** [comment]
> This change was part of an ongoing effort to separate the roles & responsibilities of each extension - so the output for Apex test runs, anonymous Apex executions, etc. were all moved to the Apex output channel.

This is good to know, thank you for the context.

**Comment by AnanyaJha** [comment]
Closing this issue in favor of #3009. Feel free to add more information there
