### ISSUE TITLE
VSC SFDX: Eternal loading after authorize

### ISSUE THREAD

**Issue by Koslan** [forcedotcom/salesforcedx-vscode#2998]
### Summary

When authorizing after specifying a username and password -> eternal loading

### Steps To Reproduce:

1.  Run SFDX: Authorize an Org in VSCode
2. Set login and password

### Expected result

Authorize an org

### Actual result

eternal loading

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/13339190/109464651-aa2d8300-7a6f-11eb-9364-ad970dd0ec2d.png)

browser -> Microsoft Edge
**VS Code Version**:
1.53.2

**SFDX CLI Version**:
sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4

**OS and version**:
 Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042

**Comment by smaddox-sf** [comment]
Duplicate #2931
