### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Himansh-singh** [forcedotcom/salesforcedx-vscode#3006]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.2.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\HP\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
