### ISSUE TITLE
Switch to Apex output channel automatically after running Apex tests

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#3009]
### Summary

After running Apex tests from the sidebar, command palette, or code action, the output should automatically be displayed via the `Apex` output channel. Currently to display the output, the user needs to manually select the `Apex` output channel from the drop down list provided. VS Code should automatically switch to the appropriate output channel as needed.

### Steps To Reproduce:
Select a test to run via the sidebar
Run test
Look for results in output window at the bottom of the screen

### Expected result
When the command finishes running, user should immediately see the results in the output window below - regardless of what channel the window was originally on.

Actual result
Nothing happens.

**VS Code Version**: 50.17.0 and up

**Comment by robcowell** [comment]
I think this may be a broader change than just Apex tests - example scenario :-

- Ran tests, now watching in the Apex view
- Tests fail, requiring code change
- Edit code, save it - push on save enabled in VS Code
-     Expected : switch to Salesforce CLI view automatically so I can see confirmation of save/compile cycle to Org
-     Actual : it stayed on the Apex tab

So while I understand the "separation of concerns" for the plugin pack, following context and moving to appropriate views would greatly support this change

**Comment by smaddox-sf** [comment]
Thanks for the input @robcowell.  You're right that it should consistently handle the output view based on the action.  We'll get this addressed in an upcoming release.

**Comment by AnanyaJha** [comment]
Displaying the Apex output channel automatically was addressed by release v51.4.0, closing this issue now. Feel free to open a new issue if there are any other inconsistencies.
