### ISSUE TITLE
Outline (cmd-shift-o) complains "no symbol information for the file"

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/salesforcedx-vscode#302]
The documentation reads that on my mac I should be able to press cmd-shift-o to open an outline of my apex class.  Whenever I try that I get the message above.

I installed "salesforce extensions for vs code" as the documentation suggested, and it appears to be active.

**Comment by vazexqi** [comment]
@tggagne Could you go through the troubleshooting steps at https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server#troubleshooting and see if you can help provide more information to help us diagnose the issue? 

Also, if possible, sharing the code of the file could help. There are certain cases of a malformed class/trigger that prevents the parser from fully understanding the code. For instance if you have a top-level `class` keyword that is not complete.

**Comment by tggagne** [comment]
Here's an example class that doesn't show anything:
`public class TomTest {
    public string xyzzy() 
    {
        return 'Nothing happens.';
    }
}`

I've verified the extension is loaded and there's nothing in the output log complaining about the language server.

I'm unsure how to answer the sfdx-project.json question.  I'm working with a traditional sandbox.  So thought I've connected the directory (theoretically) with oauth to my sandbox, it's possible that part simply doesn't want to work yet.

Why not use scratch orgs?  Our development is for our production org, and has 500 class, 190 custom objects, multiple installed packages, etc.  We'd rather create sandboxes from other sandboxes with data ready-to-go.  

Hopefully, scratch orgs aren't required for the code outliner to work, but if it is, then I'll accept my fate. ;-)

**Comment by vazexqi** [comment]
![tomtest](https://user-images.githubusercontent.com/54414/36174622-b1b3226c-10c1-11e8-885d-9aa7a2cf515e.gif)

@tggagne - Thanks for the repro. I am able to get the outline with it.

Could you show me the output of your Apex Language Server (as shown in the bottom of the gif).

I suspect that you might not have a valid sfdx-project.json (given that it's a traditional sandbox). We use that file as a token to tell us what directory to analyze.

You can try the following _fake_ one, which will tell it to analyze the src folder.

```
{
  "packageDirectories": [
    {
      "path": "src",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "40.0"
}
```

**Comment by tggagne** [comment]
Well, now I'm unable to reproduce it.  I hadn't noticed when it began appearing, but the only thing I've changed to the config was disabling preview mode.  Probably unrelated, but I can't reproduce it now.
