### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by Zosoled** [forcedotcom/salesforcedx-vscode#3025]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `51.3.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 16713,
		"activateCallTime": 12,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-lwc",
				"_lower": "salesforce.salesforcedx-vscode-lwc"
			},
			"activationEvent": "workspaceContainsTimeout:**/workspace-user.xml"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment]
I believe this is related to #2803 with extensions taking a long time to load upon start-up.  Closing this as a duplicate, but feel free to weigh in or create a new issue if you have more details.
