### ISSUE TITLE
Unable to Debug a Single Test

### ISSUE THREAD

**Issue by bmosca** [forcedotcom/salesforcedx-vscode#3026]
### Steps To Reproduce:

1. Open Test tab;
2. Select any valid single test on the inner tree;
3. Click "Debug Single Test"

### Expected result

Test is run in debug mode allowing me it to stop on the predefined breakpoints.

### Actual result

2 errors come up: 
![debug test error vscode](https://user-images.githubusercontent.com/1205040/110163086-85c30500-7de7-11eb-8667-ac4c50d0a584.PNG)

### Additional information

Working on a Sandbox:
- This work fine if I click "Run Single Test" (without debugging);
- This works fine if I click "Debug Tests" or "Run Tests" on the root node;

**Comment by AnanyaJha** [comment]
Hi @bmosca thanks for reporting this! We were able to repro the issue and will work on releasing a fix

**Comment by smaddox-sf** [comment]
Internal work tracking #: W-8977004

**Comment by bmosca** [comment]
Tested today and works perfectly,
Thanks all!
