### ISSUE TITLE
Error: spawn ENOTDIR running any SFDX command in VS Code Salesforce extension

### ISSUE THREAD

**Issue by DougGrimwade** [forcedotcom/salesforcedx-vscode#3029]
### Summary

After working perfectly forever, my vscode / salesforce extensions are no longer playing nicely on my macbook pro (running Big Sur). As of yesterday morning I cannot run any sfdx command from the extension. I have wiped and reinstalled the latest versions of java, sfdx CLI, vscode and the saleforce extensions but I still get the same error. I am getting desperate! 

### Steps To Reproduce:

1.  Launch vscode
2. Load an sfdx project
3. Hit Shift-Cmd P and select SFDX: Authorize and Org
4. Select Sandbox / vscodeOrg  and hit Enter

Note: that this fails for all SFDX command invoked through the extension not just the SFDX: Authorize and Org command

### Expected result

The SFDX command is invoked

### Actual result

I get the following error :

Command 'SFDX: Authorize an Org' resulted in an error (Running the contributed command: 'sfdx.force.auth.web.login' failed.)

The output panel shows

[2021-03-06 14:24:54.408] [exthost] [error] Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at Object.spawn (child_process.js:557:9)
	at s (/Users/douggrimwade/.vscode/extensions/salesforce.salesforcedx-vscode-core-51.3.0/node_modules/@salesforce/salesforcedx-utils-vscode/out/src/cli/index.js:1:67625)
	at l.execute (/Users/douggrimwade/.vscode/extensions/salesforce.salesforcedx-vscode-core-51.3.0/node_modules/@salesforce/salesforcedx-utils-vscode/out/src/cli/index.js:1:11872)
	at ForceAuthWebLoginExecutor.execute (/Users/douggrimwade/.vscode/extensions/salesforce.salesforcedx-vscode-core-51.3.0/out/src/commands/util/sfdxCommandlet.js:47:12)
	at SfdxCommandlet.<anonymous> (/Users/douggrimwade/.vscode/extensions/salesforce.salesforcedx-vscode-core-51.3.0/out/src/commands/util/sfdxCommandlet.js:87:46)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/douggrimwade/.vscode/extensions/salesforce.salesforcedx-vscode-core-51.3.0/out/src/commands/util/sfdxCommandlet.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:97:5) sfdx.force.auth.web.login

### Additional information

I can run sfdx commands fine in both terminal and the vscode terminal

**VS Code Version**

Version: 1.54.1 (Universal)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**SFDX CLI Version**:
sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3
CLI Integration: v51.3.0

**OS and version**:
MacOS Big Sur 11.2.2

**Java**:
openjdk version "11.0.10" 2021-01-19
jdk setting in vscode: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home

**Comment by HugoDellinger** [comment]
I'm getting the exact same problem !

**Comment by lcampos** [comment]
Hi @DougGrimwade thanks for opening this issue. I haven't been able to replicate this issue yet but did notice your Salesforce CLI version is not the latest one (7.90.2). Do you get the same behavior in the latest version of the cli ?

**Comment by DougGrimwade** [comment]
Hi, thanks for investigating.
Yes i get exactly the same behaviour with sfdx-cli/7.90.2-b8f9206a5c darwin-x64 node-v14.15.4
Any suggestions on how I can troubleshoot the issue further?
Is there anyway of finding out what file / dir its trying to access that is causing the error?

**Comment by DougGrimwade** [comment]
Hi again - I know the problem - heroku in PATH!

I get the failure if my path is 

/usr/local/bin/heroku:/Users/Doug/SalesforceTools/apache-ant-1.9.7/bin:/Applications/apache-maven-3.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/heroku:/Users/Doug/SalesforceTools/apache-ant-1.9.7/bin:/Applications/apache-maven-3.1.1/bin:/Users/Doug/brightmediatools:/Users/Doug/brightmediatools

And it works if I remove heroku and my path is 

/Users/Doug/SalesforceTools/apache-ant-1.9.7/bin:/Applications/apache-maven-3.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Doug/SalesforceTools/apache-ant-1.9.7/bin:/Applications/apache-maven-3.1.1/bin:/Users/Doug/brightmediatools:/Users/Doug/brightmediatools

in both cases 'which sfdx' reports '/usr/local/bin/sfdx'

I think the cause is illustrated by the following commands

Dougs-Work-MacBook-Pro:bin douggrimwade$ pwd
/usr/local/bin
Dougs-Work-MacBook-Pro:bin douggrimwade$ ls -l heroku
lrwxr-xr-x  1 douggrimwade  admin  34  4 Jul  2020 heroku -> ../Cellar/heroku/7.42.2/bin/heroku
Dougs-Work-MacBook-Pro:bin douggrimwade$ cd heroku
-bash: cd: heroku: Not a directory

So when the extension is setting up the environment does it wander the path and check that each entry is a directory whilst looking for sfdx - then fails on the first one in my case? If I move the heroku entry to the end of the path it also works fine.

@HugoDellinger can you check your path - see if that is your issue too?

**Comment by HugoDellinger** [comment]
I don't have Heroku installed at all on my setup

**Comment by DougGrimwade** [comment]
@HugoDellinger it doesn't have to be heroku. It looks like if there is ANY entry in the PATH prior to /usr/local/bin that is not a directory then you will get the error. In my case heroku was in there but is an executable rather than a directory hence I got the error. One test you could try is putting / usr/local/bin at the very start of your PATH. If that does not fix your issue then I think it is different to mine.

For those that stumble on this thread in the future I also found that its ok to have /usr/local/bin/heroku in the path provided heroku is not actually installed (weird setup I know - but just to illustrate the point). I think this means that when the sfdx extension code is setting up the environment for the command to be run it walks the PATH variable and checks the path exists (skipping it if it doesn't) but does not check if it is a directory. 

@lcampos Lots of guesswork here so it would be good to get the official line on all this.

**Comment by jeffb-sfdc** [comment]
@DougGrimwade this was an issue with our v54.4.0, and was fixed in v54.4.1, which was release the next day.  I'm going to close this ticket, but if you still experience this issue, please reopen the ticket, and let us know which version of the Salesforce Extension for VS Code you are using, and let us know the repro steps you are performing.
