### ISSUE TITLE
Deployment issue after latest update

### ISSUE THREAD

**Issue by adarshashu96** [forcedotcom/salesforcedx-vscode#3031]
Issue Type: <b>Bug</b>

Step 1: Create project with manifest
Step 2: Retrieve source from org
Step 3: Edit some LWC code and deploy to org, it will work fine
Step 4: Make some more changes to the same LWC, nothing will be deployed
Changes will not reflect in Org, It will show that source is deployed successfully but nothing will happen, after tracing the issue I found that FilePath is becoming null after first deployment

Extension version: 51.3.0
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.08GB free)|
|Process Argv|--crash-reporter-id ccd9f00f-6169-481e-8790-8185f203faa1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by lcampos** [comment]
hi @adarshashu96 thanks for logging this. Can you explain a bit more what you mean by `I found that FilePath is becoming null after first deployment` ? Where are you seeing this e.g. CLI result, VSCode command build, etc ?

**Comment by jbeauchamp715** [comment]
I to am having an issue with deploying code to my Org. When I save my changes, it will say it is deploying and comes back with a exit code of 0, but nothing is deployed. Then I have to make a change to the file and save it again. Sometimes it deploys sometimes it does not and I have to make another change to make it deploy.

Deployment logs: 
Starting SFDX: Deploy Source to Org

07:52:52.352 sfdx force:source:deploy --sourcepath c:\Salesforce\VSCode\McConxJB\force-app\main\default\classes\MSLUpdateEventServiceTest.cls --json --loglevel fatal
07:53:04.993 sfdx force:source:deploy --sourcepath c:\Salesforce\VSCode\McConxJB\force-app\main\default\classes\MSLUpdateEventServiceTest.cls --json --loglevel fatal
 ended with exit code 0

**At this point, the code it says was deployed really is not deployed.**

Starting SFDX: Deploy Source to Org

07:53:22.536 sfdx force:source:deploy --sourcepath c:\Salesforce\VSCode\McConxJB\force-app\main\default\classes\MSLUpdateEventServiceTest.cls --json --loglevel fatal
07:53:39.654 sfdx force:source:deploy --sourcepath c:\Salesforce\VSCode\McConxJB\force-app\main\default\classes\MSLUpdateEventServiceTest.cls --json --loglevel fatal
 ended with exit code 0

=== Deployed Source
STATE  FULL NAME                  TYPE       PROJECT PATH                                                         
─────  ─────────────────────────  ─────────  ─────────────────────────────────────────────────────────────────────
Add    MSLUpdateEventServiceTest  ApexClass  force-app\main\default\classes\MSLUpdateEventServiceTest.cls         
Add    MSLUpdateEventServiceTest  ApexClass  force-app\main\default\classes\MSLUpdateEventServiceTest.cls-meta.xml

**Now the code is actually deployed**

**Comment by adarshashu96** [comment]
This issue is still there, I saw the file path is becoming null in the output of VS code. I created a new project with manifest and from package.xml, tried retrieving the project but it showed 0 results, and nothing was retrieved. Then I used the org browser and specifically retrieved the components I had to make changes to. I got my work done but the issue is still there while deploying and retreiving.

**Comment by goldwinVonage** [comment]
I am also facing the same issue.  how to fix this?

**Comment by smaddox-sf** [comment]
Hi All - Are you using the 'Experimental: Deploy Retrieve' setting?  (Found in the VS Code preferences).   If not, can you toggle that option on and retry?  I believe the issue may be related to a recent CLI bug.  Changing this setting will use the business logic library for deploys directly vs. calling that logic via the CLI.
