### ISSUE TITLE
RealTimeEventSettings

### ISSUE THREAD

**Issue by golsayhappy** [forcedotcom/salesforcedx-vscode#3032]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment]
I'm closing this since there's not enough information to know what this is about. Feel free to re-open it once you can provide information on the issue/feature request.
