### ISSUE TITLE
Test progress not updating correctly for large test runs

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#3034]
### Summary

With large test runs, sometimes the test progress doesn't properly update. The tests show that they run indefinitely in VS Code even though they've finished running and passed in the org

### Steps To Reproduce:

1.  Open a project with a large number of tests
1. Run all tests in VS Code
https://twitter.com/RobSalesforce/status/1367954770611339270

### Expected result

Tests should display results when they've finished running

### Actual result

Progress bar shows tests running indefinitely

**Comment by robcowell** [comment]
In my case, wasn't even run all tests in the org - was a run all tests on a single class, with one or two test methods only.  The classes in question fire batch apex, the implementation of which in turns fires batch apex.  The Apex Test Execution screen in the Org confirmed the tests had successfully passed, this information just never made it back to VS Code.

This happened a couple days back, but if I get a fresh recurrence, I'll post some detailed repro

**Comment by lcampos** [comment]
I haven't been able to repro this using 3 chained apex batch classes/jobs which implement Database.Batchable and Database.Stateful. @robcowell which interface(s) is your code implementing ? I want to see if there's something I'm missing in the code.

Also, can you confirm if you are using the `salesforcedx-vscode-core.experimental.useApexLibrary` setting ?

**Comment by robcowell** [comment]
Yup, both Batchable<Sobject> and Stateful used - one of them also AllowsCallouts, but of course in a test context, this just defers to a HttpMock implementation.

UseApexLibrary is set to true - not something I recall explicitly setting, but my memory ain't what it once was

**Comment by robcowell** [comment]
Version info in case it is a factor

sfdx-cli/7.90.2-b8f9206a5c win32-x64 node-v14.15.4

@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-update 1.3.10
└─ @oclif/plugin-help 2.2.3   
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-scanner 2.6.0
salesforcedx 51.2.2
├─ limits 1.0.4
├─ schema 1.0.4
├─ user 1.1.2
├─ apex 0.1.4
├─ custom-metadata 1.0.11
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 51.3.0
└─ salesforce-alm 51.2.1
