### ISSUE TITLE
Unable to open file with Apex Interactive Debugger when the path to the file contains spaces (%20)

### ISSUE THREAD

**Issue by kristualdandamudi** [forcedotcom/salesforcedx-vscode#304]
### Summary
I got "Path must be string.  Received undefined" error when attempting to start debugger (green Play button)

### Steps To Reproduce:
i followed all the steps  using below link
https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-apex-debugger

here is my Launch.json file:
`{
        "version": "0.2.0",
        "configurations": [
        {
            "name": "Launch Apex Debugger",
            "type": "apex",
            "request": "launch",            
            "sfdxProject": "${workspaceRoot}"            
        }
        ]
    }`
### Expected result
Debugg session should be start

### Actual result
"TypeError:Path must be string. Received undefined" error

### Additional information

![apex debugger issue](https://user-images.githubusercontent.com/28848782/36173207-3271b4ae-10d6-11e8-98cf-c174ad5bd761.jpg)

**VS Code Version**:
1.20
**SFDX CLI Version**:
CLI version --- sfdx-cli/6.2.1-9477838 (windows-x64) node-v8.9.4
Apex debugger vscode extension version --- 42.2.0
sfdx force version --- v42.0

**OS and version**:
Windows 7 enterprise SP1

**Comment by DatGuyJonathan** [comment]
@kristualdandamudi , did you also install this extension? https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-debug

If yes, could you disable that extension while using Salesforce's official Apex Debugger extension?

**Comment by kristualdandamudi** [comment]
Thank you @DatGuyJonathan after Disable the Apex-debugger Extension, launch.json file make the Apex debug session. but my break point doesn't hit. Here is my steps:
 after click start Debugging(green Play) button, Apex debugger session started with Id "07a5B00000000ClQAI"
![start apex debug session](https://user-images.githubusercontent.com/28848782/36195536-c6c9ce38-113b-11e8-8044-8909284e1c31.JPG)
2) i entered VF page url in Browser then i expect to hit Break point but it didn't happened.
![load the page in browser](https://user-images.githubusercontent.com/28848782/36195605-058843de-113c-11e8-8525-242153b4159d.JPG)
3)i saw Disconnected From Streaming API channel /systemTopic/ApexDebuggerEvent message in Debug Console. i didn't understand why it happens.
![disconnect the apex debugger event](https://user-images.githubusercontent.com/28848782/36195708-6395247e-113c-11e8-98f1-f498aa54f25d.JPG)
4) then my VF loads with out hitting Break Point.
![wo hitting bp redirect vf page](https://user-images.githubusercontent.com/28848782/36195762-8fa595ee-113c-11e8-9500-ea967811329e.JPG)

Note: if try to reproduce the same issue immediate after kill the Apex debugger session in scratch org.
Some time shows File not found  error  of Vf page custom controller which i put the break point class.
please figure out where i did wrong.

Thanks
Dandamudi

**Comment by vazexqi** [comment]
@kristualdandamudi - Are you behind any proxy/firewall? In the past, we noticed some issues with the streaming API when it's used behind proxies.

**Comment by kristualdandamudi** [comment]
@vazexqi 
1.Are you behind any proxy/firewall? In the past, we noticed some issues with the streaming API when it's used behind proxies. I noticed that you don't see that issue anymore in your "Update today" section above.
**Ans:**  today updates only i did in behind the firewall.  what ever i tried in before today updates at home network. so home network also it didn't hit the break point.
2. now i commit all other changes except my debugger project, even though still i am facing same issue.
![file not found2](https://user-images.githubusercontent.com/28848782/36220836-09b75690-118a-11e8-8c82-4a7c3447879e.JPG)

can you please have look and find where i did wrong.
Thanks
Dandamudi

**Comment by vazexqi** [comment]
@kristualdandamudi - What happens if you did this again, but don't put spaces in your file path? From your screenshot, it seems like your path contains spaces (Apex%20Debugger%20Sample). Could you try this again in a project that doesn't have spaces in the name?

I think the connection is all working is just it is not able to open that file. I am not in front of a windows box to try this.

**Comment by kristualdandamudi** [comment]
Thank you @vazexqi  after i remove the spaces in Path, it's  working fine, now it's hit the Break Point.  Appreciate for your Prompt response.
![hit the break point](https://user-images.githubusercontent.com/28848782/36227586-820c03ec-119f-11e8-9ecf-252e7a2edb96.JPG)

**Comment by amphro** [comment]
Looking at the CLI code, I'm not entirely sure the lightning domain check supports proxies... I would need to manually test. If so, I'll file a bug and work on getting it resolved. 

In the meantime, if you set SFDX_DOMAIN_RETRY=0, then it will skip the domain check and go straight to the browser. If you get the page saying "domain not found" then you will have to keep refreshing until the domain is resolved.

**Comment by vazexqi** [comment]
Just to close the loop on this 

>@kristualdandamudi , did you also install this extension? https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-debug
> If yes, could you disable that extension while using Salesforce's official Apex Debugger extension?

VS Code itself doesn't allow for multiple extensions to be registered for the same type. Both ours and chuckjonas.apex-debug define it using type:apex. See https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex-debugger/package.json#L79 and https://github.com/ChuckJonas/vscode-apex-debug/blob/master/package.json#L61

 If you have two, the one that it picks is somewhat random. That's why we recommend that you disable the other one.

**Comment by kristualdandamudi** [comment]
Thank you @amphro  after set SFDX_DOMAIN_RETRY=0 , i tried sfdx force:org:open  all orgs launched in browser successfully at corporation firewall.
Question: if i add SFDX_DOMAIN_RETRY=0  as environment variable in my system, i don't need to run always "set SFDX_DOMAIN_RETRY=0"  command in windows cmd when ever i entered in to corporation firewall is it right?

**Comment by amphro** [comment]
Correct.

**Comment by vazexqi** [comment]
Thank you @amphro. Also, @kristualdandamudi, if you set `SFDX_DOMAIN_RETRY=0` in a terminal, command prompt, etc, and *then* launch VS Code, it should pick it up so that all the commands also inherit that parameter.

On Windows and Linux, you can already just launch `code` from the terminal. On the Mac, you can follow https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by vazexqi** [comment]
Opened https://github.com/Microsoft/vscode-debugadapter-node/issues/159 since it might be an issue on the adapter.

**Comment by vazexqi** [comment]
@DatGuyJonathan - I believe that we have actually fixed this (using our own method and also waiting for the next version of the debug-protocol-adapter from Microsoft). If that is so, could you close this issue? If it is not so, what else do we need to do on our side to fix this?

**Comment by vazexqi** [comment]
@DatGuyJonathan - Is this still relevant or has already been fixed? If so, could you close this?

**Comment by DatGuyJonathan** [comment]
My bad, fell under my radar. The space issue on Windows path has been fixed in https://github.com/forcedotcom/salesforcedx-vscode/pull/359.
