### ISSUE TITLE
Unable to Deploy LWC component to Default org

### ISSUE THREAD

**Issue by Doddva** [forcedotcom/salesforcedx-vscode#3050]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  I am trying to deploy lwc component. but getting an error.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @Doddva - Closing this as there's not enough information here for us to try to investigate this.  Feel free to post a comment back with the information from the bug template and happy to re-open this.  (Info needed: Steps to reproduce, Expected Result, Actual Result, version info for VS Code extensions, SFDX CLI and OS)
