### ISSUE TITLE
SFDX: Refresh SObject Definitions fails with "Cannot read property 'forEach' of undefined" on newest plugin version

### ISSUE THREAD

**Issue by jardorr** [forcedotcom/salesforcedx-vscode#3056]
### Summary

Everytime the SFDX: Refresh SObject Definitions command is run, it fails with the message "ended with error Failure performing sObject describe Cannot read property 'forEach' of undefined".
This has been testet on multiple devices, and is happening on all refresh types (All, Custom and Standard SObjects).

### Steps To Reproduce:

1.  Open command palette
1.  Select command SFDX: Refresh SObject Definitions
1.  Choose one of the three options

### Expected result

Expected SObject definitions to be fetched

### Actual result

The command fails with error "ended with error Failure performing sObject describe Cannot read property 'forEach' of undefined"

### Additional information

**Salesforce CLI console output**
![image](https://user-images.githubusercontent.com/50980241/110776443-5b969a80-8260-11eb-88b1-b907e7ede3f6.png)

**VSCode console output**
![image](https://user-images.githubusercontent.com/50980241/110776589-87198500-8260-11eb-8f9d-f117bb41491c.png)

**VS Code Version**: 1.54.1

**SFDX CLI Version**: 7.90.2-b8f9206a5c

**SFDX CLI Integration Plugin Version**: v51.4.0

**OS and version**: Windows 10 20H2

**Comment by lcampos** [comment]
Hi @jardorr thanks for opening this issue. I haven't been able to replicate this on any of my orgs but I created a tests that could replicate the error on the area I think it might be happening for you. I'm thinking the problem is that the describe calls the feature does against your org are returning no results, can you confirm if you have access to sobjects in the org you are using ?

**Comment by jardorr** [comment]
Hi @lcampos.
I have the System Administrator profile in the org, and I have full sObject access in the Org Browser.
I do believe the you are correct that the org is returning no results. I suspect this to be due to company policy network restrictions (VPN connection due to WFH). Curiously enough, everything else (Org browser, deploy/retrieve from org, authorize org etc.) works as expected.

**Comment by jeffb-sfdc** [comment]
@jardorr I wasn't able to reproduce this.  We've made a number of enhancements to the Org Browser, so I suspect this issue was fixed.  If you are able to reproduce this, please reopen this ticket and let us know what steps you are taking to reproduce it.

**Comment by harshaldhage97** [comment]
nable to process sObjects when not in a SFDX Project c:\Users\ADMIN\OneDrive - astreca.com\Desktop\Astreca In-House\Daily Backup\InHouse 5 sept 2024\.sfdx
09:44:45.427 sf sobject definitions refresh
 ended with error Unable to process sObjects when not in a SFDX Project c:\Users\ADMIN\OneDrive - astreca.com\Desktop\Astreca In-House\Daily Backup\InHouse 5 sept 2024\.sfdx

09:44:45.427 sf sobject definitions refresh
 ended with exit code 1
 
 
 facing this issue
