### ISSUE TITLE
Cannot delete file

### ISSUE THREAD

**Issue by Bidou44** [forcedotcom/salesforcedx-vscode#3071]
In Visual Studio Code with version 51.4.0 of Salesforce Extension Pack:

- Selecting a class or trigger in the tree
- Then right click, _SFDX: Delete from projet and org_
- In the Console I see

Starting SFDX: Delete from Project and Org

sfdx force:source:delete --sourcepath XXX.trigger --noprompt
ERROR running force:source:delete:  INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations
sfdx force:source:delete --sourcepath XXX --noprompt
 ended with exit code 1

**Comment by lcampos** [comment]
Hi @Bidou44 , can you provide more details on why this is an issue ? The output on the command execution is clear in that those operations are not supported in production orgs.

**Comment by Bidou44** [comment]
Hi @lcampos 

1 - If that's currently not supported, then this feature is missing. How can I delete files on my PROD then?
2 - Your extension should be able to see that I'm bound to a prod environment and in this case the option to delete the file should not be shown if this action is not possible (or grayed out or something similar...)

**Comment by smaddox-sf** [comment]
Hi @Bidou44 - Thanks for the feedback.  Over time, we've gotten feedback that it is more confusing to hide commands or features within a context.  The preference from the community is to see options and have clear messaging so you aren't left searching for things.  That is the approach we've taken on this one.  We'll consider your feedback in future iterations.

To delete metadata from production, you can use the Metadata API or the Ant migration tool.  We'll consider adding support for this in the future, but it is not a near-term priority.
