### ISSUE TITLE
apex Extension issue unresponsive

### ISSUE THREAD

**Issue by judeeinjapan** [forcedotcom/salesforcedx-vscode#3077]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

![image](https://user-images.githubusercontent.com/26101796/111721872-1992d780-88a4-11eb-9287-6cd3722211ed.png)

![image](https://user-images.githubusercontent.com/26101796/111721913-2a434d80-88a4-11eb-823d-9ea0f1d6fcd0.png)

`{
	"resource": "/c:/Users/ishu/Documents/workspace/PJFolder/PJName/force-app/main/default/classes/ClassName.cls",
	"owner": "deploy-errors",
	"severity": 8,
	"message": "\n<html>\n<body>\n\n<table cellspacing=10>\n    <tr>\n        <td><span style=\"font-weight: bold; font-size: 12pt;\">Illegal Request</span></td>\n    </tr>\n    <tr>\n        <td>You have sent us an Illegal URL or an improperly formatted request. \n        </td>\n    </tr>\n    <tr>\n        <td>\n            \n        </td>\n    </tr>\n</table>\n\n\n\n\n<script type=\"text/javascript\">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken=\"null\";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>\n\t\t\t\n</body>\n</html>\n\n\n\n",
	"source": "SfdxError",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
`

**Comment by ag-nhs** [comment]
I am receiving this as well On Deploy to my sandbox:

```
SfdxError: 
<html>
<body>

<table cellspacing=10>
    <tr>
        <td><span style="font-weight: bold; font-size: 12pt;">Illegal Request</span></td>
    </tr>
    <tr>
        <td>You have sent us an Illegal URL or an improperly formatted request. 
        </td>
    </tr>
    <tr>
        <td>
            
        </td>
    </tr>
</table>



<!-- Body events -->
<script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>
			
</body>
</html>
```

**Comment by smaddox-sf** [comment]
Thanks for reporting this.  We are working to improve performance and tracking it on #2410.  Closing this as a duplicate
