### ISSUE TITLE
Code Completion in anonymous apex

### ISSUE THREAD

**Issue by fenixjke** [forcedotcom/salesforcedx-vscode#3086]
### Summary

_Code completion doesn't work in anonymous apex_.

### Steps To Reproduce:

1.  Create an sfdx project.
2.  Connect the project to an org.
3. Do Refresh SObject Definitions.
4. Open scripts -> apex -> hello.apex
5. Try to use the fields suggests or any other apex code completion

### Expected result

_Suggestions should be shown_.
![image](https://user-images.githubusercontent.com/20062691/112307296-d5437500-8cb1-11eb-9b00-6d5efeccdde2.png)

### Actual result

_Suggestions aren't shown_.
![image](https://user-images.githubusercontent.com/20062691/112307619-379c7580-8cb2-11eb-8483-156a395fc93e.png)

### Additional information

**VS Code Version**: 1.54.3

**Comment by randi274** [comment]
This has now been delivered! 🎉 Code Completion is available in versions as early as v53.3.0.
