### ISSUE TITLE
Unable to deploy to org 

### ISSUE THREAD

**Issue by Sourabh824015** [forcedotcom/salesforcedx-vscode#3090]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
@Sourabh824015 - There's no details in this issue to be able to investigate.  It could be related to this [current CLI issue](https://github.com/forcedotcom/cli/issues/942).  You can workaround that in VS Code by checking the box for the 'Experimental Deploy Retrieve' option in VS Code settings.  
Feel free to  [open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) anytime with more info if you are still having trouble.
