### ISSUE TITLE
Right click deploy for LWC Javascript file failing

### ISSUE THREAD

**Issue by thisguyjacob** [forcedotcom/salesforcedx-vscode#3094]
### Summary

When attempting to deploy LWC source to org, SFDX: Deploy Source to Org fails when right clicking and deploying from open JavaScript file. Works for all other component files.

### Steps To Reproduce:

1.  Open LWC JavaScript file in editor.
1.  Right click in editor and select 'SFDX Deploy Source to Org.
![image](https://user-images.githubusercontent.com/43553159/112862477-6aac8380-907b-11eb-8c10-ab927186055d.png)

### Expected result

LWC source should be deployed to org.
![image](https://user-images.githubusercontent.com/43553159/112862012-f5d94980-907a-11eb-8ba6-567d01ca2ca4.png)

### Actual result

SFDX: Deploy Source to Org failed to run.
![image](https://user-images.githubusercontent.com/43553159/112862247-2f11b980-907b-11eb-99da-3178ddd45ebc.png)

### Additional information

Success scenario when deploying from another component file (html):
![image](https://user-images.githubusercontent.com/43553159/112862646-99c2f500-907b-11eb-9f09-59fa97fc1672.png)
![image](https://user-images.githubusercontent.com/43553159/112862746-afd0b580-907b-11eb-83b6-797abb9f2915.png)

Code for the JavaScript file was not changed and does not throw any errors within the org.

**VS Code Version**:
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**SFDX CLI Version**:
sfdx-cli/7.93.1-762bca056d win32-x64 node-v14.15.4

**OS and version**:
![image](https://user-images.githubusercontent.com/43553159/112863507-8bc1a400-907c-11eb-918d-784d0b3b3fbb.png)

**Comment by smaddox-sf** [comment]
Hi @thisguyjacob - Do you have the 'Experimental Deploy Retrieve' setting in VS Code preferences set to true?  If not, can you turn that on and retry?  I think this might be related to a recent bug in the CLI.  The setting I mentioned using a library directly for deploys instead of the CLI.

**Comment by thisguyjacob** [comment]
@smaddox-sf I enabled the 'Experimental Deploy Retrieve' setting. This is the new output when deploying from the JavaScript file:
![image](https://user-images.githubusercontent.com/43553159/113176056-b5f89a80-9211-11eb-9561-2361bb05caee.png)

Component structure:
![image](https://user-images.githubusercontent.com/43553159/113176208-d9234a00-9211-11eb-8709-2f65713b4c0f.png)

testFieldLables.js:
`import { LightningElement, api, wire } from 'lwc';
import getContact from '@salesforce/apex/LWCHelper.getContact'
import getScorecardFields from '@salesforce/apex/LWCHelper.getScorecardFields'

const CIRCLE_CSS_CLASS = 'circle';
const LOW_SCORE_CSS_CLASS = 'low';
const MID_SCORE_CSS_CLASS = 'mid';
const HIGH_SCORE_CSS_CLASS = 'high';

export default class TestFieldLables extends LightningElement {
    @api recordId;
    contact;
    scorecardFields;

    @wire(getContact, { recordId: '$recordId' })
    wiredContact({error, data}) {
        if (data) {
            this.contact = data;
            this.error = undefined;
            getScorecardFields({ rTypeId: this.contact.RecordTypeId })
                .then(result => {
                    this.scorecardFields = result;
                    console.log('scorecard result:::', this.scorecardFields);
                    this.error = undefined;
                })
                .catch(error => {
                    this.error = error;
                    console.error(error);
                    this.scorecardFields = undefined;
                });
        } else if (error) {
            this.error = error;
            this.contact = undefined;
            console.error(error);
        }
    }

    renderedCallback() {
        console.log(this.recordId);
        console.log('contact data:::', this.contact);
        console.log('scorecard fields:::', this.scorecardFields);
        console.log('Testing...');
    }

    get contactFields() {
        if (this.scorecardFields != undefined) {
            return this.scorecardFields.map((field) => {
                const apiName = field.Field_API_Name__c;
                const label = field.MasterLabel;
                const value = this.contact[apiName];
                const cssClass = this.getCSSClass(apiName);
                return {
                    apiName,
                    label,
                    value,
                    cssClass,
                };
            });
        }
    }

    getCSSClass(apiName) {
        if (apiName == 'Name') {
            return CIRCLE_CSS_CLASS + ' ' + HIGH_SCORE_CSS_CLASS;
        }
        else if (apiName == 'Title') {
            return CIRCLE_CSS_CLASS + ' ' + MID_SCORE_CSS_CLASS;
        }
        return CIRCLE_CSS_CLASS + ' ' + LOW_SCORE_CSS_CLASS;
    }


}`

**Comment by xyc** [comment]
@thisguyjacob LWC component names must begin with a lower case letter:
https://developer.salesforce.com/docs/component-library/documentation/en/lwc/create_components_folder

**Comment by thisguyjacob** [comment]
@xyc understood. If you refer to the screenshot of the component structure in the above comment, the naming conventions are followed, yet the problem persists.

**Comment by brpowell** [comment]
@thisguyjacob I have been able to reproduce this. From what I can tell at the moment, It seems a bit like a quirk of VS Code. When right clicking the editor window and selecting deploy, the URI VS Code returns to the extensions capitalizes the file name of the LWC javascript file. This causes problems because the deploy logic parses paths to figure out the structure of a metadata component, including its name when generating a package.xml file behind the scenes.

Interestingly I don't see this problem in [VS Code Insiders](https://code.visualstudio.com/insiders/). It could be that it will be fixed in the API in their next release. I'll keep looking to see if they have a specific issue filed about this, or if there's something on our end we can change. I'll tag this as a bug, but I'm curious to see if next week's (hopefully) release of VS Code will address this issue.

**Comment by brpowell** [comment]
@thisguyjacob I updated to the latest version of VS Code (April 2021) and am not seeing this behavior anymore. Let us know if updating your VS Code solves this issue for you.

**Comment by thisguyjacob** [comment]
@brpowell It appears to be working as expected after the update. Thanks for the follow up. Closing this issue.
