### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Grigiory** [forcedotcom/salesforcedx-vscode#3115]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `51.7.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.55.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Trust\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6248603/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by Grigiory** [comment]
Hi everyone. I'm so sorry, but I do not understand in any way what does not work that way!

**Comment by Grigiory** [comment]
I apologize, I wrote some nonsense, I will solve the problem myself.

**Comment by smaddox-sf** [comment]
Hi @Grigiory - Feel free to [open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) anytime.
