### ISSUE TITLE
Unable to retrieve package.xml

### ISSUE THREAD

**Issue by jayashreep7019** [forcedotcom/salesforcedx-vscode#3121]
Issue Type: <b>Bug</b>

**Summary:**
While trying to retrieve package.xml , I am getting below error :

**Error Message**
undefined' is not valid for the type xsd:double

I am not exactly sure due to which file the error is popping up as there is no explicit mention in VS code terminal

**More Details**
Salesforce Extension version: 51.7.0
VS Code version: Code 1.55.0 
OS version: Windows_NT x64 10.0.18363

**Comment by smaddox-sf** [comment]
Hi @jayashreep7019 - Thanks for reaching out.  I have a few questions:
 - What version of the SFDX CLI are you using?
 - Is this your first time retrieving using a manifest?  Or is this a common workflow for you that is suddenly throwing an error?
 - Can you include the package.xml that you are using?

**Comment by jayashreep7019** [comment]
Hello,

Please find the details :
**What version of the SFDX CLI are you using?** -- sfdx-cli/7.93.1-762bca056d win32-x64 node-v14.15.4
**Is this your first time retrieving using a manifest? Or is this a common workflow for you that is suddenly throwing an error?** -- This is the common workflow and the error came up suddenly
**Can you include the package.xml that you are using?**-- 

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
 <types>
        <members>Object1__c</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>Object1__c.Field1</members>
        <members>Object1__c.Field2</members>
        <members>Object1__c.Field1.Field3</members>
        <members>Object1__c.Field4</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Object1-Layout1</members>
        <name>Layout</name>
    </types>
    <types>
        <members>Trigger1</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>Class1</members>
        <members>Class2</members>
        <name>ApexClass</name>
    </types>
	<types>
        <members>PermName</members>
        <name>Permissionset</name>
    </types>
	
</Package>

**Comment by sfsholden** [comment]
@jayashreep7019 Thank you for reporting this issue. I'll see if I can reproduce the issue you mentioned above.

For now, I'm hoping we can get some additional information. Do you see any additional error details from the following information sources?

1) Click `Help` from the top menu pane -> `Toggle Developer Tools` -> `Console`

2) From `Output` -> select `Salesforce CLI` from the dropdown


Thank you in advance for your help.

**Comment by brpowell** [comment]
Hi @jayashreep7019. I noticed in the manifest file you pasted the custom fields do not have an `__c` suffix - can you try adding that to each of the fields? e.g.

```
<types>
        <members>Object1__c.Field1__c</members>
        <members>Object1__c.Field2__c</members>
        <members>Object1__c.Field3__c</members>
        <members>Object1__c.Field4__c</members>
        <name>CustomField</name>
</types>
```
