### ISSUE TITLE
Failed to authorize Salesforce org

### ISSUE THREAD

**Issue by rautinst** [forcedotcom/salesforcedx-vscode#3122]
While authorizing org using the command "Authorize an org" I get redirected to Salesforce login on browser and can successfully login but the command still keeps on running in VScode for a very long time and when the "Authorize an org" command is canceled authorization fails with exit code 1.
![E1](https://user-images.githubusercontent.com/81916556/113575292-446a8300-963b-11eb-8725-5b8aeecff216.png)
![E2](https://user-images.githubusercontent.com/81916556/113575296-46344680-963b-11eb-8a82-ee4fefff3d55.png)
![E3](https://user-images.githubusercontent.com/81916556/113575301-46ccdd00-963b-11eb-9ccd-a22b03adb5a0.png)
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6258192/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6258198/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by smaddox-sf** [comment]
Hi @rautinst - Thanks for reaching out.  After you login, is the Org actually authorized?  I'm curious if the authorization completes, even though the status isn't telling you that.

Can you tell us what version of things you are running:

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

Also, can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?
