### ISSUE TITLE
Xml file content is missing label tag with the new Experimental Deploy Retrieve

### ISSUE THREAD

**Issue by dan9khoa** [forcedotcom/salesforcedx-vscode#3124]
### Summary

With the 2 Experimental Deploy Retrieve and Use Apex Library settings enabled, the content of meta xml file is changed and causes error on deploy.

### Steps To Reproduce:

1.  Enable the 2 settings above
1.  Retrieve a file (say, a visualforce page)
1.  Deploy the file
1.  Get deploy error

### Expected result

File is deployed normally. The meta xml file content usually looks like this
```<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>51.0</apiVersion>
    <availableInTouch>false</availableInTouch>
    <confirmationTokenRequired>false</confirmationTokenRequired>
    <label>CaseWorkQueue</label>
</ApexPage>
```

### Actual result

```=== Deploy Errors
PROJECT PATH                                     ERRORS                          
───────────────────────────────────────────────  ────────────────────────────────
force-app/main/default/pages/CaseWorkQueue.page  Required field is missing: label
```

The xml content is now like this
```<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
	<apiVersion>51.0</apiVersion>
</ApexPage>
```

**VS Code Version**: 1.55.0

**SFDX CLI Version**: sfdx-cli/7.93.0 darwin-x64 node-v15.12.0

**OS and version**: Mac 10.15.7

**Comment by brpowell** [comment]
This issue was addressed in v51.11.0 of the extensions.
