### ISSUE TITLE
SFDX: Retreive Manifest from Org keeps on running Endlessly #120694

### ISSUE THREAD

**Issue by HarshPreeti** [forcedotcom/salesforcedx-vscode#3128]
1.Create a Project with Manifest
2. Authorize Salesforce Org.
3.Manifest>>Pacakage.xml>>SFDX:Retrieve Manifest From Org
4.It doesn't retrive anything just keeps running, no errors.

**Comment by sfsholden** [comment]
Hi @HarshPreeti,

This could be a known issue where the retrieve is getting stuck in the queue. 

As a workaround, we've seen that stopping and restarting the retrieve usually resolves the problem. Please let us know if this doesn't solve the issue for you.

If this approach does not resolve the problem, we will need additional information...
VS Code Version:

SFDX CLI Version:

OS and version:
