### ISSUE TITLE
Show debug log when executing tests via 'Run Test'/'Run all Tests'

### ISSUE THREAD

**Issue by sc5148** [forcedotcom/salesforcedx-vscode#3140]
Executing tests from a single test class should show debug logs automatically in addition to the test coverage.

**Current behavior** - Executing tests from a single test class shows only the code coverage details.
**Desired behavior** - Executing tests from a single test class should show debug logs automatically in the output panel in addition to the test coverage details.

**Comment by smaddox-sf** [comment]
Hi @sc5148 - Thanks for sharing this feedback!  We have [work in flight](https://github.com/forcedotcom/salesforcedx-vscode/issues/946) to add another CodeLens to let you run the tests, setup the debugger & launch it - all with one click.  You can see the details here.  Closing this one as a duplicate.
