### ISSUE TITLE
Problem when I Create A Default Scratch Org

### ISSUE THREAD

**Issue by GabrielBurgosLopez** [forcedotcom/salesforcedx-vscode#3141]
14:23:43.614 sfdx force:org:create -f config\project-scratch-def.json --setalias examen --durationdays 3 --setdefaultusername --json --loglevel fatal
14:23:52.45 sfdx force:org:create -f config\project-scratch-def.json --setalias examen --durationdays 3 --setdefaultusername --json --loglevel fatal
 ended with exit code 1

You do not have access to the [ScratchOrgInfo] object

**Comment by smaddox-sf** [comment]
Hi @GabrielBurgosLopez - Thanks for reaching out.  We need a bit more info to try to investigate this. Can you share some context on when you hit this error? Please share:

**1 - Steps to reproduce**:

**2 - Expected outcome**:

**3 - Actual outcome**:

Version info:

**4 - VS Code Version**:

**5 - SFDX CLI Version**:

**6 - OS and version**:
