### ISSUE TITLE
API version in manifest or sfdx-project.json has no impact on retrieve and org explorer

### ISSUE THREAD

**Issue by fishygeek91** [forcedotcom/salesforcedx-vscode#3151]
### Summary

When retrieving object metadata via the Org Explorer or right clicking on a file, the returned results differ from using force:source:retrieve -x “path/to/package.xml”. This is causing issues for developers who are diffing meta files from production with source control, and is dependent on the way the source is retrieved. 

### Steps To Reproduce:

1. Used force:source:retrieve -x “path/to/package.xml” to pull test object
2. Next I used the Org Explorer to pull down same object
3. Diff'ed meta. Metadata for object differs
4. Changed API version is package.xml
5. Used force:source:retrieve -x “path/to/package.xml” and source differs from step 1
6. Used Org explorer and received same metadata as step 2.

### Expected result

force:source:retrieve -x “path/to/package.xml” returns same metadata as Org Explorer or right clicking on file to retrieve source

### Actual result

force:source:retrieve -x “path/to/package.xml” returns different metadata as Org Explorer or right clicking on file to retrieve source

### Additional information

[https://github.com/forcedotcom/cli/issues/528](url)

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by fishygeek91** [comment]
![Screen Shot 2021-04-22 at 9 00 33 AM](https://user-images.githubusercontent.com/62761381/115738610-6f96e700-a34a-11eb-8c53-a4b4831c797a.png)

Unchecking this box seems to have fixed the issue for me. At least for a test object I have been working with to come up with a solution for our source control.

**Comment by smaddox-sf** [comment]
Hi @fishygeek91 - Thanks for reaching out.  We are working on a fix for this.  You are correct on the workaround to uncheck that setting for now.  With the setting unchecked, these commands use the CLI directly for these commands vs. the new library for deploy/retrieve.  You will see better performance with the library, so I suggest turning this setting back on once we have this fixed.  We'll update the issue once we merge a fix.

**Comment by ChuckJonas** [comment]
@smaddox-sf could you give us a sense of the timeline for this fix?

We are trying to decide if we should invest in upgrading all of our projects to use the Experimental flag or just waiting for the fix to come out.

Thanks

**Comment by brpowell** [comment]
Hi @fishygeek91, what are the differences you are seeing in the CustomObject XML? Are they formatting differences, or are actual values in the CustomObject different? If you or @ChuckJonas could provide a screenshot or code snippet example that highlights the difference that would be great. Appreciate it!

**Comment by fishygeek91** [comment]
@brpowell 
 Using the CLI might produce:

```
<actionOverrides>
    <actionName>Accept</actionName>
    <type>Default</type>
</actionOverrides>
```
but pulling down from the org browser

```
<actionOverrides>
    <actionName>Accept</actionName>
    <type>Default</type>
</actionOverrides>
<actionOverrides>
    <actionName>Accept</actionName>
    <formFactor>Large</formFactor>
    <type>Default</type>
</actionOverrides>
<actionOverrides>
    <actionName>Accept</actionName>
    <formFactor>Small</formFactor>
    <type>Default</type>
</actionOverrides>
```

**Comment by brpowell** [comment]
Looks like the new deploy/retrieve logic does need to respect the SFDX project api version, whether that's resolved from a local or global config when going the source path or org browser route. If you use the manifest deploy/retrieve commands, it respects the version defined in the manifest currently.

@ChuckJonas this should be a relatively easy fix, might be able to get this in for next week's release or the week after.
