### ISSUE TITLE
"Could not infer a metadata type" error with "Experimental: Deploy Retrieve" on for Wave Types

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/salesforcedx-vscode#3157]
### Summary
With "Experimental: Deploy Retrieve" on, retrieving wave objects results in the error "Could not infer metadata type".

### Steps To Reproduce:
1. Enable "salesforcedx-vscode-core>Experimental: Deploy Retrieve".
2. Click on the Org Browser.
3. Attempt to retrieve metadata for Wave components.

### Expected result
Retrieves metadata for wave components.

### Actual result
Receive error "Could not infer metadata type". This appears to be due to an extra "-meta.xml" suffix.

### Additional information
![VS_code1](https://user-images.githubusercontent.com/45604118/115425634-0766ca80-a1bd-11eb-8cda-4e8c709f2e96.png)

### Workaround
Disable the setting "salesforcedx-vscode-core>Experimental: Deploy Retrieve".

**Comment by sfsholden** [comment]
This issue will be resolved with W-9156885.

**Comment by brpowell** [comment]
This should be fixed in the latest version (v51.10.0) of the extensions
