### ISSUE TITLE
Warning messages in output panel after running commands like deploy/retrieve/open org etc.

### ISSUE THREAD

**Issue by sc5148** [forcedotcom/salesforcedx-vscode#3160]
sfdx --version
sfdx-cli/7.94.3-a4e7c7955b darwin-x64 node-v14.15.4

I am pasting the list of warning messages here- 

(node:11014) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11014) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:11014) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

**Comment by smaddox-sf** [comment]
Hi @sc5148 - Thanks for sharing feedback.  I have a few questions:

1. Which output channel do you see these warnings on?  
2. What version of the extensions you are running?
3. Is this a new project where you are seeing these issues?  Or did you start seeing them suddenly for code you've worked with for awhile?
