### ISSUE TITLE
sfdx force:apex:test:run always produces exit code 0 even on test failure

### ISSUE THREAD

**Issue by waterfif** [forcedotcom/salesforcedx-vscode#3163]
### Summary

There appear to be some changes around what exit codes are produced after running sfdx force:apex:test:run between sfdx-cli/7.93.1-762bca056d and sfdx-cli/7.97.0. Version 7.93.1 would exit with code 100 if sfdx force:apex:test:run encounters test failures. Version 7.97.0 exits with 0 regardless of any test failures encountered. In our CI we have a workaround that involves scraping result files however it would be more convenient to rely on exit codes

### Steps To Reproduce:

1. Create a failing test class called BadTest containing a single test that asserts false
2. Run  sfdx force:apex:test:run -u <your org> -c -r human -d test-results --tests=BadTest --wait 2
3. echo $? to get the exit code

### Expected result

In version 7.93.1 the exit code is 100

### Actual result

In version 7.97.0 the exit code is 0

### Additional information

**SFDX CLI Version:** sfdx-cli/7.97.0 win32-x64 node-v15.14.0

**SFDX plugin Version:** 

sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-scanner 2.8.0
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.4.3 (1.4.3)
config 1.2.8 (core)
generator 1.1.5 (core)
org 1.6.1 (1.6.1)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ limits 1.0.5 (core)
├─ apex 0.1.21 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.12 (core)
├─ schema 1.0.5 (core)
├─ user 1.2.8 (core)
├─ templates 51.3.0 (core)
└─ salesforce-alm 51.6.11 (core)
sfdx-cli 7.97.0 (core)
source 0.0.9
telemetry 1.1.2 (core)

OS and version: windows 10

**Comment by AnanyaJha** [comment]
Thanks for reporting this @waterfif! We can confirm we were able to reproduce this issue and will work on addressing it. I'll post on this thread once we've released a new version of the plugin with the fix, thanks!

**Comment by AnanyaJha** [comment]
Hi @waterfif ! Thank you for the patience as we worked on getting this fix out, it has now been released with the newest version of the Apex plugin v0.2.0. Run sfdx plugins:install apex to update to the new version - it should be bundled with the new version of the cli in 2 weeks. If you find any other issues, please don't hesitate to reach out or open a new issue!

**Comment by waterfif** [comment]
Hi @AnanyaJha, many thanks. I'll try this out today.

**Comment by waterfif** [comment]
Just tried apex plugin version 0.2.0 and can confirm that an exit code of 100 is returned. Thanks @AnanyaJha
