### ISSUE TITLE
Extension causes  VSCode to not load any extension and spike to CPU

### ISSUE THREAD

**Issue by docebo-it** [forcedotcom/salesforcedx-vscode#3169]
### Summary

I've recently updated to OSX Big Sur and I'm no more able to run Salesforce Extension Pack. As soon as I try to install it, VS Code becomes unrensponsive and it cannot load anything, not even git. I've tried to update to latest VS Code and latest Salesforce Extenstion as well as trying to downgrade both of them, but with no luck. I cannot use the tools to develop

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.55.2 (but I've tried down to 1.51.1)

**SFDX CLI Version**: sfdx-cli/7.97.0 darwin-x64 node-v15.14.0

**OS and version**: OSX Big Sur 11.2.3 (20D91)

**Comment by docebo-it** [comment]
To add more context I've tried a fresh install of all the extensions. As soon as I install Salesforce Extension Pack VS Code becomes unresponsive and CPU spikes to 100% by solely opening up VS Code

**Comment by sfsholden** [comment]
@docebo-it Thank you for reaching out.

It's interesting that this issue happened after upgrading to Big Sur. Would you mind sharing what you upgraded from?

Also please attach a cpu profile report - see here for more information:
https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions
