### ISSUE TITLE
"Get Apex Debug Logs" returns no log

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/salesforcedx-vscode#3170]
### Summary

Running `SFDX: Get Apex Debug Logs` returns `No Apex debug logs were found`, but `sfdx force:apex:log:list` returns a list of them.

### Steps To Reproduce:

1.  Run `SFDX: Get Apex Debug Logs`
2. Wait for response.

### Expected result

List of logs returned, so I can pull a particular log.

### Actual result

Error message at the bottom right of VSCode.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: Version: 1.55.2

**SFDX CLI Version**: sfdx-cli/7.97.0 darwin-x64 node-v15.14.0

**OS and version**: Darwin x64 19.6.0

**Comment by xyc** [comment]
@jpmonette Not able to reproduce this yet. Could you check if you have the latest version of extensions: 51.11.0?
