### ISSUE TITLE
ERROR running force:apex:test:run:  Specify a test class or test methods when running tests synchronously

### ISSUE THREAD

**Issue by gsbasso** [forcedotcom/salesforcedx-vscode#3171]
### Summary

Unable to run all tests synchronously.

This seems to have been introduced with release `sfdx-cli/7.97.0 win32-x64 node-v15.14.0` (literally it was working on our Jenkins server in the morning and then suddenly began to fail in the afternoon, so I can only assume that the CLI version was automatically updated in between).

In the past we have had issues where tests would fail when run asynchronously so we added the -y option to our Jenkins script. Plus it has been our understanding that tests are run synchronously in production.

### Steps To Reproduce:

1. Upgrade to CLI release: `sfdx-cli/7.97.0 win32-x64 node-v15.14.0`
2. Run the sfdx command:  `force:apex:test:run -u <alias> -r junit -c -y -w 90`

### Expected result

Tests are run

### Actual result

ERROR running force:apex:test:run:  Specify a test class or test methods when running tests synchronously

### Additional information

**SFDX CLI Version**: sfdx-cli/7.97.0 win32-x64 node-v15.14.0

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.1 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
    - data 0.4.3 (core)
    - custom-metadata 1.0.12 (core)
    - apex 0.1.21 (core)
    - user 1.2.8 (core)
    - org 1.6.2 (core)
    - templates 51.3.0 (core)
    - limits 1.0.5 (core)
    - salesforce-alm 51.6.11 (core)
    - @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
    - schema 1.0.5 (core)
sfdx-cli 7.97.0 (core)
telemetry 1.1.2 (core)

**OS and version**: Windows 10

**Comment by AnanyaJha** [comment]
Hi @gsbasso thanks for reporting this! We will be reverting the behavior that caused that change with our next release, more info here as to why it was updated: https://github.com/forcedotcom/salesforcedx-vscode/issues/3154. We'll update this thread once a new version of the plugin has been released.

**Comment by AnanyaJha** [comment]
Closing this issue in favor of #3154.
