### ISSUE TITLE
Detect conflicts feature when using 'SFDX: Retrieve This Source from Org' or 'SFDX: Deploy This Source to Org'

### ISSUE THREAD

**Issue by deekshant-okta** [forcedotcom/salesforcedx-vscode#3186]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I have to update my Manifest file each and every time I am saving a class/trigger I am working on in order to detect conflicts

**Describe the solution you'd like**
Would love if SFDX checks for conflicts when using 'SFDX: Retrieve This Source from Org' or 'SFDX: Deploy This Source to Org' options that we get when we right click on a file in VSC.

**Describe alternatives you've considered**
I started to use IlluminatedCloud plugin of IntelliJ code

**Comment by smaddox-sf** [comment]
Hi @deekshant-okta - We have some work planned in this area and it's described on #2034.  Please check out the details of what we're building and comment there if you have any feedback!
