### ISSUE TITLE
VS Code seems to loose connection to SFDX after command has been fired

### ISSUE THREAD

**Issue by staujade** [forcedotcom/salesforcedx-vscode#3187]
### Summary

When commands like retrieve or deploy are fired the only feedback in Salesforce CLI Output is "Starting SFDX: Retrieve Source from Org" or "Starting SFDX: Deploy Source to Org", but the response seems not to be received. A deploy already was successful after some minutes, but the status indicated it was running for more then an hour.
When executing the commands via terminal everything works fine.

### Steps To Reproduce:

1.  Start a deploy or a retrieve by VS Code right-click on an element.

### Expected result

After action is finished the follow-on actions are performed (e.g. user is informed that action was finished in case of deploy or updating files in case of retrieve)

### Actual result

Infinite loading.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.55.2

**SFDX CLI Version**: 51.10.0 / 7.98.0-e361fce

**OS and version**: Windows 10 x64 1709 (OS Build 16299.2166)

**Comment by xyc** [comment]
Thanks for reporting @staujade As I understand the deploy is successful, just the progress indicator is not dismissed. And is this happening every time on deploy / retrieve or occasionally?

**Comment by staujade** [comment]
Hi @xyc,
Correct.
First I was only facing the issue on retrieving a lot of source by manifest file, so I thought it is somehow timeout-related. Now I am facing it every time on deploy retrieve - even for very small amount of data.

**Comment by xyc** [comment]
We haven't been able to reproduce this. Can you try toggling "Experimental: Deploy Retrieve" setting in VS code? Also please provide "Salesforce CLI" output log in the output panel if applicable.

**Comment by staujade** [comment]
I found "Experimental: Deploy Retrieve" setting was already set and is now unset - correct? Seems to resolve my issue.
Before output looked like:
`Starting SFDX: Retrieve Source from Org`
Now it says:
`Starting SFDX: Retrieve Source from Org

12:06:51.379 sfdx force:source:retrieve --sourcepath d:\Code\Visual Studio Code\ServiceMax Global\src\main\default\triggers\ContentDocumentLinkTrigger.trigger
WARNING: apiVersion configuration overridden at "50.0"
=== Retrieved Source
FULL NAME                   TYPE         PROJECT PATH
──────────────────────────  ───────────  ────────────────────────────────────────────────────────────
ContentDocumentLinkTrigger  ApexTrigger  src\main\default\triggers\ContentDocumentLinkTrigger.trigger
ContentDocumentLinkTrigger  ApexTrigger  src\main\default\triggers\ContentDocumentLinkTrigger.trigger
12:07:06.227 sfdx force:source:retrieve --sourcepath d:\Code\Visual Studio Code\ServiceMax Global\src\main\default\triggers\ContentDocumentLinkTrigger.trigger
 ended with exit code 0`

... and the retrieve is successful.

**Comment by floralan** [comment]
According to the previous discussions, this issue has been resolved.
