### ISSUE TITLE
Retrieve Source from Manifest in Org is not pulling data when * members is set

### ISSUE THREAD

**Issue by jriffe** [forcedotcom/salesforcedx-vscode#3197]
### Summary
I create a new project with Manifest in VSCode, but when trying to receive code from the manifest, I receive no error, but no files are retrieved.

Output was:
10:37:06.764 Starting SFDX: Retrieve Source from Org

10:37:07.943 ended SFDX: Retrieve Source from Org

Package.xml file was the default given when project was created.

### Steps To Reproduce:

1.  Utilize the SFDX: Create Project with Manifest command, and created from Production (Trailhead Playground)
1.  Utilized SFDX: Authorize an Org.  Org Authorized with no issues
1.  Right click on the package.xml file under the Manifest folder
     - Extension acts normally as though it is retrieving the source from the org
     - Nothing is retrieved and no error is given.

### Expected result

Files should have been retrieved from Org

### Actual result
No files were retrieved

10:37:06.764 Starting SFDX: Retrieve Source from Org

10:37:07.943 ended SFDX: Retrieve Source from Org

### Additional information

I was able to pull the files by explicitly setting them in the package.xml.  Once I set this, files were pulled into VS Code as expected.  It just would not honor the '*' to pull all files of the given type.

**VS Code Version**:
1.55.2

**SFDX CLI Version**:
sfdx-cli/7.99.0 win32-x64 node-v15.14.0

**OS and version**:
Windows 10 Pro
19041.928

**Comment by smaddox-sf** [comment]
Hi @jriffe - Thanks for reaching out.  Couple questions to help us triage this:

1) Can you confirm the version of the extension pack?  You can see this by going to the 'Extensions' view from VS Code code and checking out the version next to the 'Salesforce Extension Pack'.  it should be something along the lines of 51.11.0

2) If you go to VS Code settings and uncheck the 'Deploy Retrieve' option and then retry, do you still hit the issue?

**Comment by jriffe** [comment]
The version is: v51.11.0
When I was having issues, I pulled latest on everything and still had the
same issues.  I'm not sure what version it was before.

I unchecked Deploy Retrieve and here are my results:

The extension seemed to only pull for the LWC folder.

Package.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTestSuite</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>51.0</version>
</Package>


Response:
Starting SFDX: Retrieve Source from Org

10:53:13.102 sfdx force:source:retrieve --manifest g:\Salesforce
Projects\LWCSpecialist\LWCSpecialist\manifest\package.xml
=== Retrieved Source
FULL NAME                           TYPE                      PROJECT PATH
──────────────────────────────────  ────────────────────────
────────────────────────────────────────────────────────────────────
boatSearch\boatSearch.js            LightningComponentBundle
force-app\main\default\lwc\boatSearch\boatSearch.js-meta.xml
boatSearch\boatSearch.html          LightningComponentBundle
force-app\main\default\lwc\boatSearch\boatSearch.html
boatSearch\boatSearch.js            LightningComponentBundle
force-app\main\default\lwc\boatSearch\boatSearch.js
boatsNearMe\boatsNearMe.js          LightningComponentBundle
force-app\main\default\lwc\boatsNearMe\boatsNearMe.js-meta.xml
boatsNearMe\boatsNearMe.html        LightningComponentBundle
force-app\main\default\lwc\boatsNearMe\boatsNearMe.html
boatsNearMe\boatsNearMe.js          LightningComponentBundle
force-app\main\default\lwc\boatsNearMe\boatsNearMe.js
boatTile\boatTile.js                LightningComponentBundle
force-app\main\default\lwc\boatTile\boatTile.js-meta.xml
boatTile\boatTile.js                LightningComponentBundle
force-app\main\default\lwc\boatTile\boatTile.js
boatTile\boatTile.html              LightningComponentBundle
force-app\main\default\lwc\boatTile\boatTile.html
boatTile\boatTile.css               LightningComponentBundle
force-app\main\default\lwc\boatTile\boatTile.css
boatSearchForm\boatSearchForm.js    LightningComponentBundle
force-app\main\default\lwc\boatSearchForm\boatSearchForm.js-meta.xml
boatSearchForm\boatSearchForm.html  LightningComponentBundle
force-app\main\default\lwc\boatSearchForm\boatSearchForm.html
boatSearchForm\boatSearchForm.js    LightningComponentBundle
force-app\main\default\lwc\boatSearchForm\boatSearchForm.js
10:53:51.280 sfdx force:source:retrieve --manifest g:\Salesforce
Projects\LWCSpecialist\LWCSpecialist\manifest\package.xml
 ended with exit code 0


Something interesting to note here.  I am working on a trailhead
superbadge.  There is code from an unlocked package in the org, which is
the code that I am working on.  Since I created a new project to try again,
I have 2 folders (projects) connected to the same org.  The one I pulled
latest on in the example is first one that wasn't working before.  The 2nd
folder (project) is the one I pulled down the files by explicitly stating
them in the package xml.

What I find interesting to note here is that all the files that pulled from
the manifest in the org after turning off deploy retrieve only pulled the
new LWC's that I created myself.  I do not know if the setting made a
difference here since those files form the unlocked package still didn't
come through.

Pasted below is the file structure from the 2nd working project that I
pulled the manifest files explicitly so you can see exactly what files are
missing from the project tested above.  And you can also see the lwc folder
that has the pulled files above, but is also missing 2 component bundles
(that came from the unlocked package)  Anoter observation is that once the
files are there, it is saving and retrieving as expected.  It just isn't
pulling from the manifest.  As far as I know, there isn't a namespace here
either since the package is unlocked.

[image: VSCodeScreenshot.png]

**Comment by xyc** [comment]
Have you tried specify the package name and retrieve? See https://salesforce.stackexchange.com/a/310902

**Comment by RoadRunner88** [comment]
I am having the same issue. 

When I commented out StaticResources it worked! 

When I include StaticResources, I get the first Starting message: 
18:59:20.788 Starting SFDX: Retrieve Source from Org 
*** but then never see the ended message ***
19:01:08.612 ended SFDX: Retrieve Source from Org

**_Worse_** yet, the VS Code Output will clear automatically and I am left without any trace that I even ran the command. Argghhhh!!!!

**Comment by abhishekmehta04** [comment]
> I am having the same issue.
> 
> When I commented out StaticResources it worked!
> 
> When I include StaticResources, I get the first Starting message: 18:59:20.788 Starting SFDX: Retrieve Source from Org *** but then never see the ended message *** 19:01:08.612 ended SFDX: Retrieve Source from Org
> 
> **_Worse_** yet, the VS Code Output will clear automatically and I am left without any trace that I even ran the command. Argghhhh!!!!

Thanks! Removing static resource really worked. Weird !

**Comment by alex2lv** [comment]
> I am having the same issue.
> 
> When I commented out StaticResources it worked!
> 
> When I include StaticResources, I get the first Starting message: 18:59:20.788 Starting SFDX: Retrieve Source from Org *** but then never see the ended message *** 19:01:08.612 ended SFDX: Retrieve Source from Org
> 
> **_Worse_** yet, the VS Code Output will clear automatically and I am left without any trace that I even ran the command. Argghhhh!!!!

Works for me too. Thanks.

**Comment by heybethfrench** [comment]
I'm working on the same super badge, and commenting out static resources didn't work for me, but when I was specific about which LWC I wanted, I was able to pull it down from my dev environment

For example:

` <types>
        <members>boatMap</members>
        <name>LightningComponentBundle</name>
    </types>`

**Comment by anupshastri96** [comment]
@jriffe and @RoadRunner88 
Thank you guys, I have been looking for a solution to this for a long time. I thought it was happening because of some update issue. I installed and reinstalled the extensions multiple times.
