### ISSUE TITLE
Core Extension start up time - High CPU usage

### ISSUE THREAD

**Issue by robertStrunk** [forcedotcom/salesforcedx-vscode#3198]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `51.10.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VS Code version: `1.55.2`

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6407006/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robertStrunk** [comment]
I used the Javascript profiler to review the CPU profile and it appears that a large amount of time is used just loading code for the extension. Issues like these are a bit outside of my skillset but the VSCODE dev team suggests these issues can be resolved using webpack or rollupJS to bundle extension scripts together.

**Comment by smaddox-sf** [comment]
Hi @robertStrunk - Thanks for reaching out and sharing the details.  The CPU profile is useful to help us pinpoint the bottlenecks.  How much RAM do you have on your computer?

**Comment by robertStrunk** [comment]
8gb

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by robertStrunk** [comment]
It's also noteworthy to mention that my personal computer has 64gb of ram and I get this issue on it as well. Not nearly as blocking on my personal one though. (The 8gb is my work laptop)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by abhishekKapoor14** [comment]
Facing same issue on creating the salesforce project on the VS code as above mentioned. My System has 8GB RAM

**Comment by ppadishala** [comment]
Apex Extension start-up time - High CPU usage
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/7603243/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by AlexHamburgGER** [comment]
My VSCode is taking long time, like 3minutes to become ready for salesforce coding. I have 8GB Ram and SSD as HDD.

**Comment by rafmauriello** [comment]
> My VSCode is taking long time, like 3minutes to become ready for salesforce coding. I have 8GB Ram and SSD as HDD.
It's the same for me and i've also 8GB of RMA and SSD.

**Comment by RupertBarrow** [comment]
Same issue this morning : MacBook Pro 2016, SSD, 16Gb RAM

I got this message at the same time Github was saying something like "cannot show all changes, there are more than 10 000" in the "Source Control" tab.

**Comment by rkamble22** [comment]
The VSCode takes a lot of time, around 3-4 minutes, to run all the Salesforce extensions. I have a Dell Precision 5530, running Windows 10 64 bit with Intel i7-8850H, 32 GB RAM, and 512 GB SSD.

**Comment by brountre** [comment]
I have a Dell Latitude running Windows 10 with 16 GB of memory.  I have two issues with Salesforce VSCode extension.  One it stores huge log files on the disk and it will cause my machine to run out of disk space.  I have to go in every day or so and delete the log file to restore storage.  Also (and the most annoying) is that it takes some times up to 4 to 5 minutes to become useable and allow connectivity also causes other extensions to pause until it is ready.  This needs to be fixed.

This is after 2 hours:
![Screenshot 2022-08-24 100029](https://user-images.githubusercontent.com/1190978/186438276-f8000501-e7f2-4770-b5e8-b3ba46f4483c.png)

**Comment by andy-fitch** [comment]
Having the same issue with 16GB of RAM - this is totally blocking new development for us right now - really hope Salescrap can this fixed.

**Comment by benjaminloerincz** [comment]
I removed all installed sfdx plugins (the lwc local development server plugin slows down some things) and I still got the same issue on a MacBook M1 Pro, 16 GB RAM, sfdx-cli/7.182.1 darwin-x64 node-v18.12.1, vscode 1.74.2 e8a3071ea4344d9d48ef8a4df2c097372b0c5161 arm64.

It takes really a lot of time to load all extensions. Especially since the latest updates last month:
| Running Extension          | Time    |
| -------------------------- | ------- |
| Salesforce CLI Integration | 21932ms |
| SQOL                       | 8072ms  |
| Aura Components            | 7971ms  |
| Lightning Web Components   | 7291ms  |
| Apex                       | 7198ms  |
| Apex Replay Debugger       | 6502ms  |
| Apex Interactive Debugger  | 5660ms  |

**Comment by reszkaj** [comment]
Are there any updates on this thread? For me the extensions are working even slower, some of them require approx. 3 minutes to load. My machine is lattitude 5420 with 16gb of ram.

**Comment by kklauke** [comment]
@smaddox-sf I wanted to see if this is something that is still in the queue to be addressed, its taking a terribly long time to load up VSCode and switching Projects.  let us know if you have any insights.

![image](https://user-images.githubusercontent.com/59401346/233184037-989b9116-25a9-4527-bc53-ccbfd0739c08.png)

**Comment by benjaminloerincz** [comment]
This is still a big issue. I tried to debug in vscode to see what is happening, wasn't successful, uninstalling vscode, sf, sfdx using brew, clearing cache, adjusting .zshrc back to default, removing sf/sfdx using this approach here https://salesforce.stackexchange.com/a/348020 and removing .sf and .sfdx in /Users/myusername/ as well did not work (in vscode debugging I saw that there was a bigger file loading having all sf orgs listed from a vscode cache folder).
I also tried to compare multiple different files with another macbook which has nearly the same specs but has not the issue, but I had no luck. Interestingly, the problem does not occur when I installed the oldest available version for all Salesforce extensions for fun.

**Comment by brountre** [comment]
Have the same issue. Windows 10 16GB of memory.  Very annoying to be sure.

**Comment by robcowell** [comment]
Same here. Machine spec: AMD Rynzen 3950X @3.49GHz, 32gb RAM, all drives fast SSD

(I'd previously raised #3831 and it got redirected here)

**Comment by SW4GK1NG** [comment]
My work laptop ASUS UX533F running on I5-8265U and 8 GBs of rams, it takes such a long time from opening VSCode to being able to actually deploy/retrieve the code

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/24899097/2d48fead-3dc1-4957-8a81-51d9e934f1bb)

**Comment by Green-Thread** [comment]
Also having this problem. 

I've tried reinstalling everything from node to jdk, different versions, installation methods etc. but none fixed or substantially mitigated it. I thought it might be related to full disk encryption, but disabling that didn't help. 

The startup time varies wildly; anywhere from two to ten minutes, and it maxes out all threads until it's done.
It's also worth noting that the improved startup times that rafaelgbo presents are still unacceptable by the standards of VS Code extensions. 

It seems like every command has at least a noticeable delay. I added a comment to an apex class and it took over a minute and a half to deploy.

**Comment by imKewal** [comment]
Hi Team,

Any luck resolving this issue? 
This issue has been open for the past 2.5+ years, and it still takes a long time to load SFDX projects in VS Code.

**Comment by eestradarodriguepaypal** [comment]
Wondering if this is related to the size of the org.

**Comment by DC-ICT** [comment]
> Wondering if this is related to the size of the org.

It takes the same amount of time whether I've authorised an org or not.

**Comment by diyer** [comment]
Hey all, we're excited to let you know the latest version of our extensions 59.5.1 is released! Please give this version a try and let us know if you see any improvements in load times with this fix. Your feedback is valuable to us. Thank you for being part of our journey!

cc: @AnanyaJha @gbockus-sf

**Comment by benjaminloerincz** [comment]
@diyer: Many thanks to you and the team! The update solves the problem on my Mac! Many, many, many thanks!

**Comment by bloerinczCBS-CX** [comment]
@diyer: I must have rejoiced too soon...

On an existing project:

|Extension|Extension Version|Activation Time|
|-|-|-|
|Lightning Web Components | 59.5.1 | Startup Activation: 17277ms|
|SOQL | 59.5.1 | Startup Activation: 16637ms|
|Aura Components | 59.5.1 | Startup Activation: 15152ms|
|Apex Replay Debugger | 59.5.1 | Startup Activation: 14121ms|
|Apex Interactive Debugger | 59.5.1 | Startup Activation: 8777ms|
|Apex | 59.5.1 | Startup Activation: 7181ms|
|Salesforce Mobile Extensions for Visual Studio Cod | 0.1.0 | Activation: 2674ms|
|Einstein for Developers | 0.26.3 | Startup Activation: 2031ms|
|Salesforce CLI Integration | 59.5.1 | Startup Activation: 1127ms|

On a new project:

|Extension|Extension Version|Activation Time|
|-|-|-|
|Salesforce CLI Integration | 59.5.1 | Startup Activation: 16820ms|
|Apex Replay Debugger | 59.5.1 | Startup Activation: 13798ms|
|SOQL | 59.5.1 | Startup Activation: 13333ms|
|Aura Components | 59.5.1 | Startup Activation: 12241ms|
|Lightning Web Components | 59.5.1 | Startup Activation: 10766ms|
|Арех | 59.5.1 | Startup Activation: 10183ms|
|Apex Interactive Debugger | 59.5.1 | Startup Activation: 7923ms|
|Salesforce Mobile Extensions for Visual Studio Cod | 0.1.0 | Activation: 2616ms|
|Einstein for Developers | 0.26.3 | Startup Activation: 1382ms|

After loading the project once, executing npm install, and restarting vscode:

|Extension|Extension Version|Activation Time|
|-|-|-|
|Salesforce CLI Integration | 59.5.1| Startup Activation: 16212ms |
|SOQL | 59.5.1| Startup Activation: 16129ms |
|Aura Components | 59.5.1| Startup Activation: 16095ms |
|Apex | 59.5.1| Startup Activation: 14043ms |
|Apex Replay Debugger | 59.5.1| Startup Activation: 11824ms |
|Lightning Web Components | 59.5.1| Startup Activation: 11689ms |
|Apex Interactive Debugger | 59.5.1| Startup Activation: 7715ms |
|Salesforce Mobile Extensions for Visual Studio Cod | 0.1.0| Activation: 2347ms |
|Einstein for Developers | 0.26.3| Startup Activation: 1332ms |

**Comment by AnanyaJha** [comment]
Hi @bloerinczCBS-CX - thanks for sharing the above stats. Our team is still actively investigating this issue so we'll pass this along to them! We'll post back here with an update cc @peternhale @gbockus-sf

**Comment by diyer** [comment]
@bloerinczCBS-CX Our team has made some more changes that impacts the order in which extensions get loaded Some of our users have seen great improvement in their load times with this change. Can you please try our latest extensions and give us your feedback?

**Comment by bloerinczCBS-CX** [comment]
Open vscode project [lwc-recipes](https://github.com/trailheadapps/lwc-recipes) after git clone on company MacBook (M1 Pro, 14", 16 GB):
| Extension | Extension Version | Startup Activation Time |
|-|-|-|
| Lightning Web Components | 59.8.0 | 11714ms |
| Salesforce CLI Integration | 59.8.0 | 10870ms |
| SOQL | 59.8.0 | 9894ms |
| Aura Components | 59.8.0 | 9581ms |
| Apex Replay Debugger | 59.8.0 | 9056ms |
| Apex Interactive Debugger | 59.8.0 | 7963ms |
| Apex | 59.8.0 | 7638ms |
| Einstein for Developers | 0.27.1 | 549ms |

Open vscode project [lwc-recipes](https://github.com/trailheadapps/lwc-recipes) after git clone on personal MacBook (M1 Max, 14", 32 GB):
| Extension | Extension Version | Startup Activation Time |
|-|-|-|
| Salesforce CLI Integration | 59.8.0 | 1577ms |
| Lightning Web Components | 59.8.0 | 917ms |
| Aura Components | 59.8.0 | 876ms |
| SOQL | 59.8.0 | 850ms |
| Арех | 59.8.0 | 803ms |
| Apex Interactive Debugger | 59.8.0 | 722ms |
| Apex Replay Debugger | 59.8.0 | 687ms |
| Einstein for Developers | 0.27.1 | 98ms |

**Comment by diyer** [comment]
We have made lot of improvements to startup time with our latest VS Code version (
61.10.0 or later). Please use our latest version and open a new issue if you are still seeing this behavior.
