### ISSUE TITLE
While using switch statement in the Apex Code the color coding of the code fails.

### ISSUE THREAD

**Issue by GitUsername0923** [forcedotcom/salesforcedx-vscode#3211]
switch on codeStr {
                                            when 'employer-verified' {		
                                                modi.Company_Name_Matches_Public_Records_p__c = 'Yes';
                                                verifyEmployerDataAvailable = true;
                                            }	
                                            when 'employer-changed' {		
                                                modi.Company_Name_Matches_Public_Records_p__c = 'No';
                                                verifyEmployerDataAvailable = true;
                                            }
                                        }

you can use the above code in any apex class

**Comment by GitUsername0923** [comment]
switch on codeStr {
when 'employer-verified' {

}
when 'employer-changed' {

}
}

you can use the above code in any apex class

**Comment by randi274** [comment]
Hi @GitUsername0923, I'm seeing issues with the dashes, is this the same issue that you're facing?
<img width="315" alt="Screen Shot 2022-04-01 at 10 38 51 AM" src="https://user-images.githubusercontent.com/9795193/161314379-87e4f08f-cf2c-46ed-b0db-ecf8d1a7f841.png">
