### ISSUE TITLE
Unable to Retrieve package.xml from Source Manifest after a couple of successful attempts using Package generator

### ISSUE THREAD

**Issue by hanzo56** [forcedotcom/salesforcedx-vscode#3218]
Unable to Retrieve package.xml from Source Manifest after a couple of successful attempts using Package generator. 

### Steps To Reproduce:
Visual Studio

1.  Step 1 | Create New Project with Manifest

1.  Step 2 | Authorize to Production

1.  Step 3 | Install/enable Salesforce Package.xml Generator Extension for VS Code" extension   

1.  Step 4 | Open Package.xml Generator Extension and Use "Salesforce Package.xml Generator Extension for VS Code" extension to pull meta-data components to VS Code
![Screen Shot 2021-05-06 at 3 03 12 PM](https://user-images.githubusercontent.com/31016742/117371098-3303d900-ae7c-11eb-89f6-c9ba1698b8dc.png)

1.  Step 5 | Add a few Meta-Data Types (5 at a time)
![Screen Shot 2021-05-06 at 3 04 26 PM](https://user-images.githubusercontent.com/31016742/117371242-66defe80-ae7c-11eb-9546-239a7018fefd.png)

1.  Step 6 | Check each of the metadata types and then click Update Package.xml
![Screen Shot 2021-05-06 at 3 05 47 PM](https://user-images.githubusercontent.com/31016742/117371356-97bf3380-ae7c-11eb-979f-aeecfda07206.png)

1.  Step 7  | Right click package.xml in Explorer under Manifest folder and click SFDX: Retrieve Source in Manifest from Org
![Screen Shot 2021-05-06 at 2 44 50 PM](https://user-images.githubusercontent.com/31016742/117369325-9f310d80-ae79-11eb-834b-3f11c036f1e6.png)

1. Step 8 | Check in changes to Git
![Screen Shot 2021-05-06 at 3 11 30 PM](https://user-images.githubusercontent.com/31016742/117371793-58451700-ae7d-11eb-9482-8e9d37cda826.png)

When retrieve is successful repeat step 5  (2-3 times) 

After the 2nd or 3rd time we run into the "Actual result".

### Expected result

Retrieve package.xml content from Production.
Should receive message similar to when manually typing in command
sfdx force:source:retrieve --manifest ./manifest/package.xml

![Screen Shot 2021-05-06 at 2 59 02 PM](https://user-images.githubusercontent.com/31016742/117370806-c983ca80-ae7b-11eb-8184-00d3ae6aeaf3.png)

### Actual result
Output states : Cannot read property 'split' of undefined
![Screen Shot 2021-05-06 at 3 00 45 PM](https://user-images.githubusercontent.com/31016742/117370845-d7d1e680-ae7b-11eb-8e99-3d48fe22daf8.png)

### Additional information

_Feel free to attach a screenshot_.

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.10.0 (core)
├─ apex 0.1.21 (core)
├─ data 0.4.6 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.0.6 (core)
├─ org 1.6.3 (core)
├─ schema 1.0.6 (core)
├─ templates 51.3.1 (core)
├─ user 1.2.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.16 (core)
sfdx-cli 7.99.0 (core)
sfdx-git-delta 4.5.0
telemetry 1.1.2 (core)

MAC OS 11.2.3

Visual Studio
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by hanzo56** [comment]
Step 7 has the wrong image apologies.

Step 7 | Right click package.xml in Explorer under Manifest folder and click SFDX: Retrieve Source in Manifest from Org
![Screen Shot 2021-05-06 at 3 22 38 PM](https://user-images.githubusercontent.com/31016742/117372754-e53ca000-ae7e-11eb-9af8-e8f4b9cf10a7.png)

**Comment by chrisgMackay** [comment]
@AnanyaJha I am having the exact same issue as explained by @hanzo56 . If I run 
`sfdx force:source:retrieve --manifest`
All metadata is pulled in from the manifest package as expected. (It take forever but it will pull in)

Steps that I have taken 

1. uninstalled all extensions
2. uninstalled cli
3. uninstalled vscode 
4. Rebooted 
5. Then reinstalled all with the same result

My final try was following steps 1-4 and then when reinstalling I installed the npm sfdx-cli but still same error. Also I am on windows.

**Comment by brpowell** [comment]
We believe we have a fix for this issue which is being tracked here #3210, working on rolling it out no later than next week.

**Comment by brpowell** [comment]
This issue should be resolved with version 51.15.0 of the extensions
