### ISSUE TITLE
Auth into other org from command palette switches default user of current org.

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/salesforcedx-vscode#3220]
### Summary

In VS Code, using SFDX, when you are working in a  Salesforce orgA with userA, and you wish to prepare a deploy to orgB with userB, I sometimes need to auth into that org before deplying (when it's a new org).

If I use command palette SFDX command to auth into another org, it switches the default user in VS Code of my current orgA from userA to userB.

### Steps To Reproduce:

1.  Open VS-Code with usual Salesforce DX Extension Pack
2.  Open orgA as userA
3. With command palette "SFDX: Authorize an org", authorize userB in orgB
4. Notice in the footer of the VS Code window that the default user is now userB

### Expected result

Authenticating into another org should not change the default user of the current org.
Default org user should stay userA

### Actual result

Notice in the footer of the VS Code window that the default user is now userB

### Additional information

**VS Code Version**:
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 18.7.0

**SFDX CLI Version**:
sfdx-cli/7.94.3-a4e7c7955b darwin-x64 node-v14.15.4

**OS and version**:
MacOS 10.14.6

**Comment by smaddox-sf** [comment]
Hi @AltiusRupert - Thanks for reaching out on this.  When you `Authorize an Org` we set the newly authorized org as the Default org.  (which means that the default org and corresponding user are set to the org you just authorized). If you want to change the default Org to one you have already authorized, you can use `Set a Default Org` command or click the org Alias in status bar (aka footer) to bring up the Org Picker.   From the Org Picker, you can click on the org you want to be default.

**Comment by AltiusRupert** [comment]
Well, may I say, then, that the "Authorize an Org" label is misleading. Because of this, I found my self in a dangerous situation, working in production and deleting 80% of a customer's accounts in prod.

How ?
I had my VS Code open on a SFDX project in a sandbox.
From that environment, I asked to "Authorize an Org" (production) to download some account data to copy to my sandbox.  Trying then to load that data into my sandbox, I could see no result [of course, because my default org had been switched to production].  At some moment, I think, I decided to delete all account data from my sandbox and strat clean : unfortunately, that command was sent to production.

Command labels are important : "Authorize an Org" does not imply that it is authorizing AND switching the default user to that new org.

Please at least change the label or, better, provide a new command to authorize WITHOUT changing the default org.

**Comment by smaddox-sf** [comment]
Hi @AltiusRupert - Thanks for the feedback.  The command palette generally mirrors the name of CLI commands to give consistency.  "Authorize an Org" from VS Code includes the flag to set the default org.  ([Here's the CLI command syntax if you are curious](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_web.htm#cli_reference_force_web).).  After you run the command, you see the alias change in the status bar at the bottom of VS Code to indicate that your default org has changed.  We'll consider more verbose messaging on the command output in the future.

**Comment by AltiusRupert** [comment]
Thanks for your answer.
I think your interpretation of the auth command is incorrect : 

```
-s | --setdefaultusername
Optional
Set the authenticated org as the default username that all commands run against.

Type: boolean

```

This says that -s is optional, so in its absence, the command does NOT change the default username.
