### ISSUE TITLE
Apex: Unit test results show only 2,000 results when more results exist

### ISSUE THREAD

**Issue by jwalke** [forcedotcom/salesforcedx-vscode#3224]
### Summary

When an org has over 2,000 local test methods, and all local tests are run, only 2,000 results will be included in the test output file. 

### Steps To Reproduce:

**Repository to reproduce:** 
[dreamhouse-lwc-unit-test-issue.zip](https://github.com/forcedotcom/cli/files/6443005/dreamhouse-lwc-unit-test-issue.zip)

1.  Run the `bin/install-scratch.sh` script
1. Run `sfdx force:apex:test:run --resultformat human --wait 60 --outputdir ./tests/apex`

### Expected result

The results file in `/tests/apex` will contain 2157 results

### Actual result

The results file in `/tests/apex` will contain 2000 results

### Additional information

The sample project is the vanilla lwc dreamhouse project with the addition of one test class that contains over 2k test methods. 

Navigating to the test execution history in the Setup UI in the scratch org will show the correct number of test results:

<img width="824" alt="Screen Shot 2021-05-07 at 10 10 11 AM" src="https://user-images.githubusercontent.com/4999865/117478531-8594d200-af1c-11eb-8146-f13791b30f2e.png">

We believe this issue started with the `51.7.1 (April 8, 2021) - CLI 7.96.1` release

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

7.99.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

51.12.0

**OS and version**:

macOS 10.15.7 (19H524)

**Comment by AnanyaJha** [comment]
Hi @jwalke thanks for reporting this! We've been able to repro this issue and will work on getting a fix out there- we'll update this thread once we do.

**Comment by NVandenBossche** [comment]
Workaround is to revert back to v96 of sfdx-cli.

**Comment by AnanyaJha** [comment]
Hi @jwalke! This issue has been addressed by release `v0.2.1` of the Apex plugin. To access these changes, please run `sfdx plugins:install apex@0.2.1`. The plugin version can be verified by running `sfdx plugins`.

**Comment by brpowell** [comment]
This was also addressed in v51.15.0 of the extensions

**Comment by jwalke** [comment]
Thank you! I was able to confirm that the issue appears to be resolved for us now.
