### ISSUE TITLE
Starting SFDX: Run Apex Tests  Cannot read property 'Name' of null

### ISSUE THREAD

**Issue by alinmocanuwork** [forcedotcom/salesforcedx-vscode#3235]
### Summary

We cloned a sandbox on the summer preview. I try to run apex tests and for any test it fails

### Steps To Reproduce:

1.  Run any apex test

### Expected result

Show test coverage or failure reasons

### Actual result

![image](https://user-images.githubusercontent.com/58775864/118110981-c0e74300-b3eb-11eb-95b3-5110ba0916a1.png)

### Additional information

**VS Code Version**:

![image](https://user-images.githubusercontent.com/58775864/118111292-29cebb00-b3ec-11eb-93f3-3c4ef920b888.png)

**SFDX CLI Version**:

sfdx version
sfdx-cli/7.100.0 win32-x64 node-v16.0.0

![image](https://user-images.githubusercontent.com/58775864/118111146-f855ef80-b3eb-11eb-9599-328f57832715.png)

**OS and version**:
Windows 10

**Comment by AnanyaJha** [comment]
Hi @alinmocanuwork thanks for reporting this! Have all the tests been deployed to the org already? And is this occurring when you run the test through the test sidebar, command palette commands, from the inline code actions, or all three?

**Comment by alinmocanu** [comment]
Hi, @AnanyaJha. This is happening for every test. In developer console it's fine. I tried all the options, me and other colleague and we have the same issue.
This is happening only on the cloned org with the summer release preview enabled. In my older orgs with the same setup it's fine. So, clone a sandbox, try to connect to it with vs code and run some tests (which you know for sure are fine deployed).

**Comment by AnanyaJha** [comment]
Thanks @alinmocanu, we'll try repro-ing this with an org with the summer release preview enabled. If you all are familiar with the [Salesforce CLI](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm), could you try running your Apex tests via the CLI and post the output and the version of your CLI below?

```
$ sfdx plugins --core
$ sfdx force:apex:test:run --tests YourTests,YourTestsAgain --resultformat human --codecoverage
```

**Comment by alinmocanu** [comment]
First one
![image](https://user-images.githubusercontent.com/17476289/118861399-1ee0c280-b8e5-11eb-8c1a-aa2a35997504.png)
Second one
![image](https://user-images.githubusercontent.com/17476289/118861475-361fb000-b8e5-11eb-8471-8eda5de8e39a.png)

**Comment by AnanyaJha** [comment]
Thank you @alinmocanu ! It looks like you're actually on a much older version of the CLI, if possible, could you update your plugins and run the same command again? 
```
$ sfdx plugins:install salesforcedx
$ sfdx plugins --core
$ sfdx force:apex:test:run --tests YourTests,YourTestsAgain --resultformat human --codecoverage
```

**Comment by alinmocanu** [comment]
I tried 2 times, with sfdx update also, and it's not working.
![image](https://user-images.githubusercontent.com/17476289/119328882-4214c480-bc8d-11eb-9a41-0c15358cd551.png)

![image](https://user-images.githubusercontent.com/17476289/119329003-6a042800-bc8d-11eb-9b9e-4567f56af0a2.png)

**Comment by AnanyaJha** [comment]
Hi @alinmocanu, sorry about all the set up changes, but do you mind updating to this specific version? We detected an unrelated issue with the last two versions so I'd like to confirm the behavior with a "clean" version.

```
$ sfdx plugins:install salesforcedx@51.11.0
$ sfdx plugins --core
$ sfdx force:apex:test:run --tests YourTests,YourTestsAgain --resultformat human --codecoverage
```

**Comment by AnanyaJha** [comment]
Hi @alinmocanuwork sorry about the delay! I wanted to check in and see if you were still experiencing this issue?

**Comment by alinmocanuwork** [comment]
Hello @AnanyaJha Since then I worked on new sandboxes and I don't have that problem there. I think this was a bug on the salesforce environment, because of the release. It doesn't impact me anymore.
