### ISSUE TITLE
force:apex:test:run only reports on the first 2000 test methods

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/salesforcedx-vscode#3257]
### Summary

When running force:apex:test:run and attempting to view the test run file. The file only contains information on the first 2000 tests.

### Steps To Reproduce:

Run the following in an org with more than 2000 test methods.

sfdx force:apex:test:run -l RunLocalTests -d testoutcome -w 240

### Expected result

Creation of test-result-<id>.json with summary.testsRan > 2000.

### Actual result

Creation of test-result-<id>.json with summary.testsRan = 2000.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

7.102.0-dd7aac3

**OS and version**:
Ubuntu 16

**Comment by AnanyaJha** [comment]
Thanks for reporting this @MGarfOppLoans ! Closing this as a duplicate for #3224
