### ISSUE TITLE
Deploying in continuosly running not showing error and not deploying

### ISSUE THREAD

**Issue by prajwal1511** [forcedotcom/salesforcedx-vscode#3275]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Hi @prajwal1511 - We don't have enough information to try to help with the issue you raised.  Can you update it with more information?  Here's what is needed:

1. Steps to reproduce
2. Expected result
3. Actual Result
4. Salesforce Extension version
5. SFDX CLI version
6. OS and version
