### ISSUE TITLE
java

### ISSUE THREAD

**Issue by Shmuli2015** [forcedotcom/salesforcedx-vscode#3281]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
This issue contains no details.  Closing.  Feel free to open a new bug with details of what's going on.
