### ISSUE TITLE
Cannot set up Apex Replay debugger from VS Code

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/salesforcedx-vscode#3288]
### Summary

_Cannot set up Apex Replay debugger from VS Code due to claims entity already traced_.

### Steps To Reproduce:

1.  With an open Salesforce project in VS Code, select 'SFDX: Turn on Apex Debug Log for Replay Debugger.

### Expected result

_A new trace flag for the current user should be created with sufficient detail levels for the replay debugger_.

### Actual result

_Fails, claiming the a trace already exists for that entity.  Manual checks don't support this assertion_.

### Additional information

Manually running the SOQL it uses (via Dev console) and deleting the rows still doesn't solve this one.

![image](https://user-images.githubusercontent.com/2143167/120831513-850d4c80-c557-11eb-8219-8429b84f8dc0.png)

**VS Code Version**: 1.56.2

**SFDX CLI Version**: sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

**OS and version**: Win 10 Pro 64-Bit

**Comment by robcowell** [comment]
![image](https://user-images.githubusercontent.com/2143167/120832017-167cbe80-c558-11eb-8370-4d85ef516a25.png)

**Comment by robcowell** [comment]
Not sure if relevant - looking at those logs, it creates the start/expiry dates in GMT (we're currently daylight savings, so GMT+1).  It creates a new record in TraceFlag object, with GMT timezone, where end time = start time + 5 mins :-
![image](https://user-images.githubusercontent.com/2143167/120832409-8ab76200-c558-11eb-88d6-8e3759ab3bdd.png)

**Comment by randi274** [comment]
Just following up on this one since it looks like Roy had linked a PR for this that was merged a while back - @robcowell does this work for you now?

**Comment by klivian** [comment]
yes, this works correctly now, thank you

**Comment by robcowell** [comment]
wrong account lol - yes, this works correctly now, thank you

**Comment by randi274** [comment]
Perfect, thanks for confirming! I'll go ahead and close it out.
