### ISSUE TITLE
SFDX CLI integration extension  not working 

### ISSUE THREAD

**Issue by Rsagarraut** [forcedotcom/salesforcedx-vscode#3296]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 

**SFDX CLI Version**: 

VERSION
  sfdx-cli/7.104.0 win32-x64 node-v14.15.4

**Java version**:
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

**Comment by smaddox-sf** [comment]
Hi @Rsagarraut - Thanks for reaching out.  Can you share some further information so we can investigate?  We need:

1.  VS Code extensions version (can be the Salesforce Extension pack or the CLI integration extension)
2. OS type & version
3. Steps to reproduce - You mention in the title that the extension is not working, but can you tell us what actions you took and what result you are seeing?
