### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by manjunathtj** [forcedotcom/salesforcedx-vscode#3308]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.16.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MANJUN~1.J\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by manjunathtj** [comment]
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6628487/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by smaddox-sf** [comment]
Hi @manjunathtj - Thank you for reporting this AND including the CPU profile.  I have added this to our open issue on this topic - #2410.  Closing this duplicate but feel free to add any other comments on #2410
