### ISSUE TITLE
Husky ignores eslint

### ISSUE THREAD

**Issue by JorneVL** [forcedotcom/salesforcedx-vscode#3312]
### Summary

Whe started from a project that is created from the standard template.
Husky doesn't prevent commit lwc code with eslint errors in it.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Create new project with default template, `npm install` with the default package.json
1.  Change Aura component 'auraPropertyListMapHelper' with wrong if check (ex `if (state == 'SUCCESS') {`
2. eslint adds error warning
3. Commit file

### Expected result

Husky should prevent the commit and gives warning about the eslint error

### Actual result

Commits without any issue

### Additional information

The package.json contains an error (if I understand correctly)
Line 39 is now `"**/{aura|lwc}/**": [` but should be `"**/{aura,lwc}/**": [`
Then Husky prevents to commit this file.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.103.0 win32-x64 node-v14.17.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
auth 1.6.0 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.14.0 (core)
├─ data 0.4.8 (core)
├─ limits 1.2.1 (core)
├─ custom-metadata 1.0.12 (core)
├─ apex 0.2.0 (core)
├─ schema 1.0.7 (core)
├─ user 1.3.0 (core)
├─ org 1.6.6 (core)
├─ templates 51.4.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.26 (core)
sfdx-cli 7.103.0 (core)
telemetry 1.2.1 (core)

**OS and version**:
Windows 10

**Comment by pozil** [comment]
Hi @JorneVL this is an issue in the Dreamhouse project configuration, not on the Salesforce CLI.

It appears that our pre-commit hook configuration for sample apps is not compatible with Windows.
I've created an issue on the right repo to track this:
https://github.com/trailheadapps/dreamhouse-lwc/issues/309

**Comment by pozil** [comment]
There's this issue and you're right: the `lint-staged` config from the default project should be `**/{aura,lwc}/*`.

**Comment by JorneVL** [comment]
Thank you for the udpate
