### ISSUE TITLE
LWC autocomplete/Intellisense isn't working in .html files for JS expressions

### ISSUE THREAD

**Issue by Razlond-dev** [forcedotcom/salesforcedx-vscode#3313]
LWC Intellisense/autocomplete works fine except on expressions within the HTML markup. Any properties or functions added in the JavaScript file do not become available in the HTML template file. How can I get this fixed as it is a huge time saver?

### Expected result

When functions/properties created in .js file, you get autocomplete for them within .html file. Screenshot from Trailhead project 
"Set Up Your Lightning Web Components Developer Tools"

![image](https://user-images.githubusercontent.com/71280433/121575177-bb533c00-ca2f-11eb-96c8-a5287850b463.png)

### Actual result

No autocomplete/Intellisense for .js expressions after ctrl + space pressed.

![image](https://user-images.githubusercontent.com/71280433/121574965-77f8cd80-ca2f-11eb-82f5-167f4cc5a3c9.png)

**VS Code Version**: 1.56.2

**SFDX CLI Version**: sfdx-cli/7.103.0 win32-x64 node-v14.17.0

**OS and version**: Windows 10 version 2004

**Comment by floralan** [comment]
Hi @Razlond-dev, we updated our autocompletion for HTML here in [this PR](https://github.com/forcedotcom/lightning-language-server/pull/487). You should see the autocompletion list of JS properties or methods when you type {} in HTML file.
