### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by abhineshtiwari991** [forcedotcom/salesforcedx-vscode#3318]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.17.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.57.0`

:not able to authorize an org it showing  apex unresponsive.

Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by abhineshtiwari991** [comment]
not able to authorize an org showing apex is unresponsive.

**Comment by smaddox-sf** [comment]
Hi @abhineshtiwari991 - We don't have enough information to try to reproduce this.  Can you comment with the following information:

- Steps to reproduce
- Expected result
- actual result
- Salesforce Extension version

**Comment by nevas7** [comment]
@abhineshtiwari991  Can you try some lower version of the extension say 51.15.0 and then try again. I think I have the same issue but it worked for me when I moved to older version of the extension.
