### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ramesh-Lumen** [forcedotcom/salesforcedx-vscode#3322]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `51.17.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VS Code version: `1.57.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Ramesh-Lumen** [comment]
Issue Type: Bug
Extension Name: salesforcedx-vscode-lwc
Extension Version: 51.17.0
OS Version: Windows_NT x64 10.0.17763
VS Code version: 1.57.0

**Comment by smaddox-sf** [comment]
In order to diagnose this issue, we need more information.  [Please open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md)
