### ISSUE TITLE
Org Browser - Error when trying to retrieve all Apex classes

### ISSUE THREAD

**Issue by dineshkm06** [forcedotcom/salesforcedx-vscode#3335]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Connect to org
1. after connection success click org browser and click retrieve source from org under Apex classes

### Expected result

all apex classes from the org needs to be displayed in VS code

### Actual result

Error running command sfdx.force.source.retrieve.component: Running the contributed command: 'sfdx.force.source.retrieve.component' failed.. This is likely caused by the extension that contributes sfdx.force.source.retrieve.component.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.57.0

**SFDX CLI Version**: v52.1.0

**OS and version**: windoes 10

**Comment by smaddox-sf** [comment]
Hi @dineshkm06 - Do you see anything in the output panel when you hit this error?  If so, can you paste that here in a comment?

also, what version of the Salesforce Extensions are you using?
