### ISSUE TITLE
Output panel behavior: Deploy Retrieve should not open the output window when the deploy is successful

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [forcedotcom/salesforcedx-vscode#3340]
### Summary

With "Salesforcedx-vscode-core › Experimental: Deploy Retrieve" enabled the output window is unneccessarily shown on every deploy

### Steps To Reproduce:

1.  Uncheck "Salesforcedx-vscode-core › Experimental: Deploy Retrieve"  
1.  deploy a valid piece of code
1. Notification or status bar success message is shown according to  "Salesforcedx-vscode-core: Show-cli-success-msg", but the output window stayes closed.
1. check "Salesforcedx-vscode-core › Experimental: Deploy Retrieve"  
1. deploy the same piece of code

### Expected result

1. The same notification or status bar success message should get shown and the output window should stay closed

### Actual result

1. success message get shown and the output window opens.

**VS Code Version**:
1.57

**SFDX CLI Version**:
sfdx-cli/7.106.3 win32-x64 node-v16.3.0

**OS and version**:
Windows 10

**Comment by CristiCanizales** [comment]
Closing this to keep track of this issue with #4971
