### ISSUE TITLE
Experiences Deployment is behaving strange. 

### ISSUE THREAD

**Issue by saicharanreddyk** [forcedotcom/salesforcedx-vscode#3345]
### Summary
When deploying the experiences using the VSCode it is failing with error and the same gets deployed successful when run the deployment using the commend. 

### Steps To Reproduce:

1. Have an Org with at least one Active community 
2. Create an empty project with manifest and Authenticate the DevHub Org
3. Retrieve the ExperienceBundle using the command: sfdx force:source:retrieve -m ExperienceBundle
4. Now from the force-app right click on the experiences and use SFDX: Deploy Source to Org

![image](https://user-images.githubusercontent.com/15872676/122918455-c5a0fe80-d37c-11eb-9948-3dd51ae141c1.png)

5. Please Observe the error in the output. 

`force-app\main\default\experiences\Rookie_Developer1.site-meta.xml  The service-not-available route in Rookie_Developer1/routes/serviceNotAvailable.json isn’t supported for this template in API version 51.0. Either remove the route file and its corresponding view file or update the API version.`

![image](https://user-images.githubusercontent.com/15872676/122918481-ccc80c80-d37c-11eb-8669-6d68bd03568a.png)

6. Now deploy using the command: sfdx force:source:deploy -p force-app/main/default/experiences All goes good. 

### Expected result

Right-click on the folder and deploy also should work

### Actual result

Deployment failed with error mentioned above. 

### Additional information

 sfdx plugins --core 

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.2 (core)
auth 1.6.1 (core)
config 1.2.8 (core)
custom-metadata 1.0.12 (core)
data 0.4.12 (core)
generator 1.1.8 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.0.2 (core)
schema 1.0.7 (core)
sfdx-cli 7.107.0 (core)
telemetry 1.2.2 (core)
templates 52.0.0 (core)
user 1.3.0 (core)

**Comment by dmrx** [comment]
Adding similar issue for **Analytics Dashboards**. Text Widgets within Wave Dashboards using API 52 have similar issue. Wave Dashboards using v52 attributes will deploy via SFDX CLI but will not recognize the v52 attributes when  using the VSCODE 'Deploy Source To Org' action.


Problem deserializing 'setterless' property 'richTextContent': get method returned null (through reference chain: sfdc.insights.connect.api.input.DashboardStateInputRepresentation["widgets"]->sfdc.insights.connect.api.input.dashboard.widgets.parameters.TextWidgetParametersInputRepresentation["content"]->sfdc.insights.connect.api.input.dashboard.widgets.parameters.DynamicDataInputRepresentation["richTextContent"])

**Comment by smaddox-sf** [comment]
Hi @saicharanreddyk - From the details of the issue, it sounds like you are using a feature that was in the Summer release.  Soon we will have the default API version updated in the VS Code extensions.  In the meantime, you can explicitly set the `sourceApiVersion` in your sfdx-poject.json to match the API version in your Org.  I'm guessing you will want 52.0 but you can confirm the right version in the Org.  Please try updating the API version and let us know if that doesn't solve your issue.
