### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by balamanideep** [forcedotcom/salesforcedx-vscode#3386]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.3.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\924867\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
