### ISSUE TITLE
sfdx force:source:retrieve failed when StaticResource has zip files

### ISSUE THREAD

**Issue by cjfcqnu** [forcedotcom/salesforcedx-vscode#3388]
When StaticResource has zip files, execute SFDX:Retrieve Source in Manifest from Org in VS Code failed
![111](https://user-images.githubusercontent.com/19373325/124440048-c0947400-ddac-11eb-9d39-e1ff1365e901.png)

**Comment by smaddox-sf** [comment]
Hi @cjfcqnu - Thanks for reaching out.  We need a bit more info and context to try to reproduce this: Please share:

1. Steps to reproduce
2. Salesforce extension pack version
3. SFDX CLI version
