### ISSUE TITLE
Org Browser - Error When retrieving any type of metadata

### ISSUE THREAD

**Issue by adrian-cg** [forcedotcom/salesforcedx-vscode#3392]
### Summary

When using the OrgBrowser to retrieve any type of metadata I get the following error:

```
14:30:28.733 Starting SFDX: Retrieve Source from Org
Cannot read property 'id' of undefined
```

### Steps To Reproduce:

1. Go to OrgBrowser while in a Repo in VS Code
2. Go to any Metadata type and click Retrieve Source from Org

### Expected result

OrgBrowser should have pulled the data from my org

### Actual result

Cannot read property 'id' of undefined.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: 52.3.0

**SFDX CLI Version**:  sfdx-cli/7.94.3-a4e7c7955b linux-x64 node-v14.15.4

**OS and version**:
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

This seems similar to #3210, the workaround of disabling 'Experimental: Deploy Retrieve' setting also makes it work but the retrieves are pretty slow (big org). If I open the console I get this stack trace:

![image](https://user-images.githubusercontent.com/5215585/124797834-5862a100-df18-11eb-83ed-ddeb5897dd7d.png)

Last thing here is that I'm running a remote setup so the extensions are installed in the ~/.vscode-server/extensions folder in the target machine and I'm connecting through the SSH remote extensions on macOS.

Any help further debugging this?

Thanks!

**Comment by AnanyaJha** [comment]
Hi @adrian-cg! Thanks for reporting this, checking in to see if you've experienced this issue recently? We've made a number of improvements around the Org Browser experience that may have addressed this issue already. Let us know, thanks!
