### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by karth1983** [forcedotcom/salesforcedx-vscode#3403]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.17.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.57.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\KARTHI~1\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate of #2410.  @karth1983 - if you have the CPU profile file, please add to #2410.  Thank you!
