### ISSUE TITLE
Detect Conflict doesn't complete / prevents deployment

### ISSUE THREAD

**Issue by savage25** [forcedotcom/salesforcedx-vscode#3404]
### Summary

Click on "SFDX: Deploy Source to Org" on Class; output shows "Starting Conflict Detection"; nothing happens

### Steps To Reproduce:

1.  Click on "SFDX: Deploy Source to Org" on Class
2. output shows "Starting Conflict Detection"
3. nothing happens

### Expected result

Code should deploy

### Actual result

nothing; process seems to halt

### Additional information

I turned off "Conflict Detection" and my deployments work without issue.

**Salesforce Extension Version in VS Code**:
52.4.0

**SFDX CLI Version**:
sfdx-cli/7.101.0 win32-x64 node-v16.0.0

**OS and version**:
Version: 1.58.0 (system setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by cardinjm** [comment]
I am also getting this error, but it seems like I only get it after changing the default org for a project. I have also turned off conflict detection and deployments are now working as expected.

**Comment by good-ghost** [comment]
I am also experiencing this issue. But I got problem only following condition.

If I am trying to deploy a file(class, component...etc) which is already in the ORG. It will be deployed. No problem.
But, if I add a new file to project and am trying to deploy to the ORG, it will be stop at 'Starting Conflict Detection'.

Thanks,

**Comment by floralan** [comment]
@savage25 Hi, we have fixed this issue here [#3376](https://github.com/forcedotcom/salesforcedx-vscode/pull/3376). Please check out our latest version and open an issue if you still have questions.
