### ISSUE TITLE
VS Code fails to create new Apex Class stub on Windows 11 insider preview version

### ISSUE THREAD

**Issue by jarodwsams** [forcedotcom/salesforcedx-vscode#3405]
Longtime VS Code user and been using VS Code / SFDX on multiple computers for over a year.
I've just installed VS Code and the SFDX CLI on a new computer, and now I cannot use the VS Code command palette to create a new Apex Class.

The output I get is:
```Trying to copy from a source that does not exist: c:\Users\xxxxxxxxxx\.vscode\extensions\salesforce.salesforcedx-vscode-core-52.4.0\node_modules\@salesforce\templates\lib\templates\apexclass\DefaultApexClass.cls```

But what's funny is that the files do exist (screenshot)
![image](https://user-images.githubusercontent.com/22972834/125141966-1c783900-e0dc-11eb-93a0-c2c263e5a963.png)

Operating System: Windows 11 (Insider Preview, build 22000.65)

Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by jarodwsams** [comment]
I confirmed the base sfdx commands work to create the new apex class:
```sfdx force:apex:class:create --classname=<name> --outputdir=<outputdir> --json```

**Comment by xyc** [comment]
This might be related to the Windows 11 insider preview version. Could not repro on a stable windows version.

**Comment by jarodwsams** [comment]
> This might be related to the Windows 11 insider preview version. Could not repro on a stable windows version.

I actually assume that it is. I reported it anyway because it's something that will need to be addressed before Windows 11 reaches Release status.

**Comment by jarodwsams** [comment]
I'm also seeing other SFDX cli command stubs fail. Today it's failing to run "SFDX: Create Project". Unlike my original issue, however, the base cli command also fails.

**Comment by randi274** [comment]
Hi @jarodwsams, was this issue safely resolved for you?

**Comment by jarodwsams** [comment]
It was. It ended up being an issue with having a space in the name of the user folder that was part of the path. Moving everything to a location that did not have any spaces in the path resolved the issue.

It seems like everything should be capable of handling a space in a path, but I'm not sure if that would be a different issue ticket or not.

**Comment by randi274** [comment]
Thanks for confirming @jarodwsams - we actually have one open item to trim spaces at the end of new projects (#3950), but this does seem to be a recurring theme for us resulting in certain mysterious issues 👻 . I'll bring this up to the dev/docs team and see if there's anything we can do to prevent these going forward. Cheers!
