### ISSUE TITLE
Unable to install Extensions in VS Code

### ISSUE THREAD

**Issue by abha2rajawat** [forcedotcom/salesforcedx-vscode#3417]
I am unable to install extensions in VS code .
Reference : Attached screenshot of error logs.
![Screenshot (5)](https://user-images.githubusercontent.com/87436820/125649776-5ed1aa32-0f3f-44a0-9824-1f51788421a7.png)

**Comment by randi274** [comment]
@abha2rajawat it looks like this might be an issue with your proxy setup: https://github.com/microsoft/vscode-remote-release/issues/231
