### ISSUE TITLE
ERROR running force:source:push:  Push failed.

### ISSUE THREAD

**Issue by sravani-gadaputi** [forcedotcom/salesforcedx-vscode#3421]
{
  "status": 1,
  "result": [
    {
      "error": "Unknown"
    }
  ],
  "name": "DeployFailed",
  "message": "Push failed.",
  "exitCode": 1,
  "actions": [],
  "commandName": "SourcePushCommand",
  "data": [
    {
      "error": "Unknown"
    }
  ],

**Comment by randi274** [comment]
@sravani-gadaputi can you provide us any additional information about what happened when the command failed?
