### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by ravibarnwal** [forcedotcom/salesforcedx-vscode#3425]
I have setup my developer edition org using SFDX: Create Project with manifest and authorized org. 
When I am trying to retrieve source from manifest org using right click on package.xml, getting error  **Extension host terminated unexpectedly.**

Developer console screenshot

![image](https://user-images.githubusercontent.com/7465670/125992309-8faf59d8-7bd7-4184-bdd2-2b78972c3133.png)

**Comment by ravibarnwal** [comment]
I have tried with disabled all extensions and uninstall salesforce extension pack and again installed but didn't work.

**Comment by randi274** [comment]
@ravibarnwal is this your first time running the command for the project? Have you made any changes to the manifest file?

**Comment by ravibarnwal** [comment]
Yes. I was running first time to retrieve the source code using manifest file. No I haven't made change to manifest file.

**Comment by randi274** [comment]
@ravibarnwal did you also receive the error with only the vscode extension installed? I wanted to confirm since the screenshot shows a lot of other extensions working at the same time, and stackoverflow suggests it could be other extensions, like git: https://stackoverflow.com/questions/46457994/receiving-error-message-extension-host-terminated-unexpectedly-in-visual-stud

About how large is the code source in the org that you're trying to retrieve from?

**Comment by ravibarnwal** [comment]
@randi274 I have only Salesforce development related plugin installed see attached screenshot.  

About how large is the code source in the org that you're trying to retrieve from?
-- This is my developer org so not much source code.

I am not sure how git extension is showing in developer console.

![installed_extension](https://user-images.githubusercontent.com/7465670/126517102-00b9a5c6-1ff3-41ca-857b-ccdff62b4514.png)
![Developerconsole](https://user-images.githubusercontent.com/7465670/126517085-f48080e2-6381-49f3-b610-d2d92450adb9.png)

**Comment by randi274** [comment]
It's weird since it does look like git is running somehow! Could you check your extensions folder to see if git is included, then remove that folder (at least temporarily)? This isn't an error we've logged before, so my thinking is it might be another extension, especially since you don't have much code in the org.

**Comment by ravibarnwal** [comment]
I don't have other extension installed. You can see screenshot. Also I tried with deleting cached files under these folder.

![image](https://user-images.githubusercontent.com/7465670/126799924-64d1d458-d186-4148-a385-63ac4740ba46.png)
![image](https://user-images.githubusercontent.com/7465670/126800001-ce15f46b-a750-4981-b6fe-a880d850a710.png)

**Comment by rcoringrato-sfdc** [comment]
@ravibarnwal  Can you post the messages that appear in the **Salesforce CLI OUTPUT** panel when you run the retrieve operation?

**Comment by ravibarnwal** [comment]
There is no error in this output section and also Salesforce CLI option getting hidden after getting error. See screenshot.


![image](https://user-images.githubusercontent.com/7465670/128406371-3a06a907-186a-4459-b264-ebc79880a83f.png)

**Comment by rcoringrato-sfdc** [comment]
@ravibarnwal Can you try closing and then reopening VSCode to see if the extension will activate?

**Comment by ravibarnwal** [comment]
Yes, after closing and reopening vscoder extension is getting activated
again but again error is coming up.

**Comment by xyc** [comment]
@ravibarnwal Could you let us know what the Windows version you are using is?

**Comment by ravibarnwal** [comment]
Sorry for late response. I am using windows 10.

**Comment by ravibarnwal** [comment]
![image](https://user-images.githubusercontent.com/7465670/133925849-b99f83cf-6091-4d2c-8c22-bf3342206b5b.png)

**Comment by AnanyaJha** [comment]
Hi @ravibarnwal are you still running into this issue consistently locally? Does it happen every time you retrieve?

**Comment by ravibarnwal** [comment]
Hi @AnanyaJha Yes I am still facing this issue. It is happening whenever I am retrieving code from org by package.xml in manifest folder.  Now sometime it is only showing **running SFDX: Retrieve Source from Org** in notification popup and keep running.
This is my package.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>52.0</version>
</Package>

**Comment by RitamAgrawal** [comment]
@ravibarnwal Are you still facing the same issue? If yes, then which version of salesforce extension are you using?
