### ISSUE TITLE
Add extension to Open VSIX

### ISSUE THREAD

**Issue by clin1234** [forcedotcom/salesforcedx-vscode#3430]
**Is your feature request related to a problem? Please describe.**
Extension not available for VSCodium, which uses Open VSIX Repo be default.

**Describe the solution you'd like**
Add the extension to Open VSIX.

**Describe alternatives you've considered**
I cannot use VS Code, because of the license of the installers, and I could not be bothered compiling VS Code from scratch.

**Comment by smaddox-sf** [comment]
Duplicate #2650
