### ISSUE TITLE
Detect Conflict feature is not working

### ISSUE THREAD

**Issue by puchini104** [forcedotcom/salesforcedx-vscode#3438]
### Summary
I was using without problems the funtionality of "Detect Conflict at sync" till last week, but from now on each time that I retrieve something it does not work. 

### Steps To Reproduce:
This is step 1. File->Preferences->Setting Extension-> Salesforce Feature Preview
This is step 2. Check the checkbox Detect conflict at sync.
This is step 3. Retrieve from package.xml

### Expected result
It should not retrieve without showing conflict first

### Actual result
Retrieve all components

### Additional information

Version: 1.58.0 (system setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by maxcamp** [comment]
Hi @puchini104, closing this issue because there was a response from @smaddox-sf here https://github.com/forcedotcom/salesforcedx-vscode/issues/3414.
