### ISSUE TITLE
'debug test' code lens fails to execute

### ISSUE THREAD

**Issue by Weasel012** [forcedotcom/salesforcedx-vscode#3442]
After clicking on 'debug test' code lens I get the following error in the output panel-

This entity is already being traced by a trace flag with a start and expiration date that overlap this trace flag's start and expiration date.: Traced Entity ID

**Comment by randi274** [comment]
Can you send us a screenshot of the active trace flags in the org that you're working in?

**Comment by Weasel012** [comment]
Do you mean the list of users and the timestamps, who has active debug logs?

**Comment by randi274** [comment]
Yes, particularly the ones for the user that you're trying to work with.

**Comment by Weasel012** [comment]
<img width="829" alt="Screen Shot 2021-07-29 at 17 35 00 PM" src="https://user-images.githubusercontent.com/83374707/127522986-b0ef8b95-eee4-49ac-8093-48629d4a344e.png">

I had the same error just now. This is the screenshot of the debug logs with my user right now.

**Comment by Weasel012** [comment]
Just an update. I deleted each one of the 12 tracedEntity records from the debug log page. Now the 'debug test' executed as expected. Not sure what the problem was
