### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by comaringram** [forcedotcom/salesforcedx-vscode#3445]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `52.5.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\CHRIST~1.ING\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #3198.  @comaringram - If you have it, please attach the CPU profile to that issue as a comment.  Thank you!
