### ISSUE TITLE
"Execute Anonymous Apex with Editor Contents" executes what's saved in the file, not the actual (unsaved) editor contents

### ISSUE THREAD

**Issue by jamesmanningrapidscale** [forcedotcom/salesforcedx-vscode#3448]
### Summary

Command says it executes editor contents, but it runs what's in the file saved on disk instead.

### Steps To Reproduce:

1.  Create foo.apex under scripts/apex in a project with one line of system.debug('foo'); and save file
1.  change contents of file to system.debug('bar'); without saving
2. Ctrl+Shift+P and choose "SFDX: Execute Anonymous Apex with Editor Contents"

### Expected result

debug line of 'bar' since that's what's in the editor contents

### Actual result

debug line of 'foo' since that's what was saved on disk

### Additional information

potentially related to https://github.com/forcedotcom/salesforcedx-vscode/issues/2369 which seemed to have a similar problem and was fixed in 49.2.0

![image](https://user-images.githubusercontent.com/82121503/126907203-30826ddf-0158-46f3-b321-dbe8cf6f5c34.png)

**Salesforce Extension Version in VS Code**: Extension Pack 52.5.0

**SFDX CLI Version**: sfdx-cli/7.106.3 win32-x64 node-v14.17.0

**OS and version**: WIn10 version 21H1 / 19043.1110

**Comment by smaddox-sf** [comment]
Hi @jamesmanningrapidscale  - Thanks for sharing this feedback.  There are two commands to help with executing anonymous Apex:
 - `SFDX: Execute Anonymous Apex with Editor Contents` - This command will execute the saved file OR execute the editor's contents if you have never saved this file.  The command name is misleading and I can see the confusion.  We will evaluate a different command name that reduces confusion.
 - `SFDX: Execute Anonymous Apex with Currently Selected Text` - This command will execute the Apex you have highlighted.  This is useful to execute a piece of Apex within a file.

We'll [update our documentation](https://developer.salesforce.com/tools/vscode/en/apex/writing/#anonymous-apex) to clarify the `...with Editor Contents` command and also evaluate an adjustment to this command name in VS Code to avoid the confusion in the future.

CC @sbudhirajadoc
