### ISSUE TITLE
Java runtime

### ISSUE THREAD

**Issue by mcs4uweb** [forcedotcom/salesforcedx-vscode#345]
### Summary
I'm using visual studio code, v 1.21.0, I added all SFDX extensions,
I can connect to SF, push code to SF, just can't debug. 

I attached the "Launch Apex Debugger 

Error - dialog box

Apex language server could not provide information about valid breadpoints

		button --> Open launch.json  button--> Cancel

### Steps To Reproduce:
1. Went to debugger tools, and it show multiple JS errors
2. Activating extension failed to load

### Expected result
_Describe what should have happened_.

### Actual result
_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by vazexqi** [comment]
@mcs4uweb - See https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server 
and also please provide more information on the bug or else we won't be able to act on this.

**Comment by vazexqi** [comment]
@mcs4uweb - Could you share the JS errors that you are seeing in the debugger tools?

**Comment by vazexqi** [comment]
@mcs4uweb - I'm closing this issue since we are not getting enough information to proceed with the investigation. Feel free to re-open/create a new one when you can provide us with more information on the errors.
