### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Purushapuru** [forcedotcom/salesforcedx-vscode#3454]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.6.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\pbl\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Purushapuru** [comment]
Apex Extension is taking too long to load.

**Comment by xyc** [comment]
Thanks for reporting this issue @Purushapuru . Can you provide the following information?
- System specs: CPU, Memory. You can find out from [dxdiag](https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85) tool.
- What's the information on the output panel (View -> Output) of “Apex Language Server” (Dropdown)?
- Is this occasional or constant?

If you are working with a large project, it's recommended to use a larger heap memory for Apex. Here's the [instructions](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/#advanced-setup) to set it. For example the setting below set the heap memory to 4096 megabytes.
```
{
  "salesforcedx-vscode-apex.java.memory": 4096
}
```
