### ISSUE TITLE
Cant Run CLI commands with SUDO

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/salesforcedx-vscode#346]
### Summary
Can't run SFDX commands in VSCode terminal on Mac OS

### Expected result
Creates Apex Class

### Actual result
```
sfdx force:apex:class:create --classname testCLITool --template DefaultApexClass --outputdir src/classes ended with exit code 1

Starting SFDX: Create Apex Class

sfdx force:apex:class:create --classname testCLITool --template DefaultApexClass --outputdir src/classes
 ▸    autoupdate:: 'EACCES': EACCES: permission denied, mkdir
 ▸    '/Users/michaelgarfinkel/Library/Caches/sfdx/update.lock.readers.lock'
 ▸    'EACCES': EACCES: permission denied, mkdir
 ▸    '/Users/michaelgarfinkel/Library/Caches/sfdx/update.lock.readers.lock'
sfdx force:apex:class:create --classname testCLITool --template DefaultApexClass --outputdir src/classes ended with exit code 1
```

### Additional information

**VS Code Version**: 1.21.0

**SFDX CLI Version**: 6.5.0

**OS and version**: MacOS High Sierra

**Comment by vazexqi** [comment]
@amphro - This seems to be more of a SFDX CLI issue and not directly related to the VS Code Extensions. Is there a place I can redirect @MGarfOppLoans for such questions?

**Comment by amphro** [comment]
The CLI needs permission to the cache directory. @MGarfOppLoans can you ensure your user has write access to `/Users/michaelgarfinkel/Library/Caches/sfdx`?

You could also [disable the auto-updater](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm?search_text=environment), but that's not recommended as future updates the vscode extensions may rely on CLI updates.

**Comment by vazexqi** [comment]
@MGarfOppLoans - Any updates on this?

**Comment by MGarfOppLoans** [comment]
@vazexqi was a permission issue
