### ISSUE TITLE
Apex Extension is Unresponsive.

### ISSUE THREAD

**Issue by FatalError402** [forcedotcom/salesforcedx-vscode#3461]
Issue Type: <b>Bug</b>

I was working on a salesforce project and it was working fine. Suddenly when I resumed back and started to push the code to org it caused an error cannot push the code. When I restarted the vs code, it showed a notification that some extension is not responding and when I see the issue it says Apex extension is unresponsive. Please help

Extension version: 52.7.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.92GB free)|
|Process Argv|--crash-reporter-id 4b62c5a5-2c6b-445a-9985-aaabaa8a69f7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by FatalError402** [comment]
When I enable it , it says  - The salesforcedx-vscode-apex.java.home setting defined in VS Code settings points to a missing folder. But I have given the correct path in vs code as well as my system variable path.

**Comment by FatalError402** [comment]
![image](https://user-images.githubusercontent.com/88276250/127771505-da50f3b3-5813-420a-9996-0606e02c3388.png)

**Comment by FatalError402** [comment]
![image](https://user-images.githubusercontent.com/88276250/127815041-2a590e61-e02d-4db3-9571-fb5902a0df39.png)

**Comment by FatalError402** [comment]
Issue is resolved partially. I reinstalled the CLI and while installing I unchecked the checkbox about creating a path to obstruct Windows defender. Still waiting for the jdk folder issue to get resolved.

**Comment by smaddox-sf** [comment]
Hi @FatalError402 - Thanks for reaching out.  [Can you check your Java setup against these instructions](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup)?  Check the path set in VS Code in both the 'User' and 'Workspace' settings.  If one is correct, but the other is incorrect, that could be causing the problem.

**Comment by FatalError402** [comment]
Hi @smaddox-sf . I have crosschecked for the path for both User and Workspace. Both are correctly given. But still the issue is coming up. Can you help me here ?

**Comment by mohanraj-r** [comment]
@FatalError402 This issue is being tracked in #3198
