### ISSUE TITLE
ExperienceBundle Deployment Issue

### ISSUE THREAD

**Issue by sfarhatSFDC** [forcedotcom/salesforcedx-vscode#3462]
My SFDX project is configured as v52.0 but every time I deploy experience builder metadata from the VSCode  I am receiving the following error:

"The service-not-available route in Community1/routes/serviceNotAvailable.json isn’t supported for this template in API version 51.0. Either remove the route file and its corresponding view file or update the API version."

I have also tried to set the default API version to the 52 in the sfdx-config.json but this doesn't help either.

### Steps To Reproduce:

1. Try to deploy the lightning experience metadata which has v52.0 pages such as "serviceNotAvailable.json"
2. Configure the VSCode project to Salesforce v52.0
3. Deploy the experiences folder to the source (sandbox/dev) org
4. You sill see the error message

### Expected result

The experience bundle should have deployed, I have no issue deploying the same metadata using the Illuminated Cloud (IntelliJ Idea) 

### Actual result

The deployment is failing, see the above error message.

### Additional information

**Salesforce Extension Version in VS Code**: v52.7.0

**SFDX CLI Version**: sfdx-cli/7.110.0 darwin-x64 node-v14.17.3

**OS and version**: MacOS Big Sur 11.5

**Comment by jcarmignani** [comment]
I am experimenting the same issue with v53.0. Have you been able to find a solution to this problem?

**Comment by floralan** [comment]
@sfarhatSFDC I have this serviceNotAvailable.json file in [Ebike](https://github.com/trailheadapps/ebikes-lwc) project as well  , but I can't find the api version in it. Could you provide more information about how the file looks like? I can't reproduce your issue with version 54.0. Or could you try to update your API to the newest version to see if it fix this issue.
