### ISSUE TITLE
Deploy source to org not cancelled when clicking on cancel

### ISSUE THREAD

**Issue by Bartheleway** [forcedotcom/salesforcedx-vscode#3466]
### Summary
Using the "SFDX: Deploy source to org" command from the VS extension, it displays a notification with a cancel button.
When clicking on that cancel button, it doesn't cancel the deployment itself but only the task in VS Code.

### Steps To Reproduce:
1. Take an apex file
2. Update it locally
3. Use the right click > "SFDX: Deploy source to org"
4. Click on the cancel button on the VS Code notification
5. Check the deploy status in the production org

### Expected result
Deployment cancelled

### Actual result
Only the VS Code task is cancelled not the deployment on the org.

### System Information
{
"cliVersion": "sfdx-cli/7.110.0",
"architecture": "win32-x64",
"nodeVersion": "node-v14.17.3",
"pluginVersions": [
"@oclif/plugin-autocomplete 0.3.0 (core)",
"@oclif/plugin-commands 1.3.0 (core)",
"@oclif/plugin-help 3.2.2 (core)",
"@oclif/plugin-not-found 1.2.4 (core)",
"@oclif/plugin-plugins 1.10.0 (core)",
"@oclif/plugin-update 1.4.0-3 (core)",
"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
"@oclif/plugin-which 1.0.3 (core)",
"@salesforce/sfdx-diff 0.0.6",
"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
"@salesforce/sfdx-trust 3.6.0 (core)",
"alias 1.1.10 (core)",
"apex 0.2.2 (core)",
"auth 1.7.1 (core)",
"config 1.2.13 (core)",
"custom-metadata 1.0.12 (core)",
"data 0.5.2 (core)",
"generator 1.1.7 (core)",
"limits 1.2.1 (core)",
"org 1.6.7 (core)",
"salesforce-alm 52.1.0 (core)",
"schema 1.0.8 (core)",
"sfdx-cli 7.110.0 (core)",
"telemetry 1.2.2 (core)",
"templates 52.1.0 (core)",
"user 1.3.1 (core)"
],
"osVersion": "Windows_NT 10.0.19042"
}

### Additional information

This is really dangerous when miss clicking or deploying to production (especially since the command now runs the tests).

**Comment by smaddox-sf** [comment]
Note: The last note in this issue is a duplicate of #3470 - "This is really dangerous when miss clicking or deploying to production (especially since the command now runs the tests)."

**Comment by xyc** [comment]
@Bartheleway do you have the VS Code setting "Experimental: Deploy Retrieve" turned off? If yes can you try turning it on?

**Comment by Bartheleway** [comment]
Hi @xyc, indeed I can now cancel the deployment from VS Code directly. Must appreciated !
