### ISSUE TITLE
switch sandbox

### ISSUE THREAD

**Issue by arjunRao1204** [forcedotcom/salesforcedx-vscode#3474]
Issue Type: <b>Bug</b>

While opening the vscode under the extensions of sfdc i am unable to switch to any other sfdc org and giving error message as failed to connect

Extension version: 51.3.0
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.44GB free)|
|Process Argv|--crash-reporter-id 3678ff42-ae2c-45d3-916b-62c9820f59ff|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by arjunRao1204** [comment]
I created from new repo and removed the extensions that are not used but the problem remains same, how and when i can solve the issue
![image](https://user-images.githubusercontent.com/84308741/128506046-de84614a-b5ff-4733-852d-7cf3835eecda.png)

**Comment by smaddox-sf** [comment]
Hi @arjunRao1204 - In the output panel of your screenshot, it looks like the sfdx CLI isn't installed.  (I see the message "...is not recognized as an internal or external command."  Here's the setup instructions, including CLI - https://developer.salesforce.com/tools/vscode/en/getting-started/install.

**Comment by arjunRao1204** [comment]
Hi,
I have installed saleforce CLI.
***@***.***

**Comment by smaddox-sf** [comment]
What output do you see when you execute `sfdx version` from your terminal?  If you get an error from the integrated terminal in VS Code, I'd be curious if you see an error when executing from your computer terminal.

If the CLI is installed, the error may be indicating that VS Code doesn't know where to find the CLI.  Can you check the path setup?  You can see the details here: https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows

**Comment by arjunRao1204** [comment]
Earlier i was able to make the deploy and retrieve but now it is not allowing me to connect to SFDC org but i am able to connect the vlocity org and do the things as earlier. And i am unable to uninstall or disable the salesforce CLI extension and i cannot access the ennvironment mentioned above

**Comment by arjunRao1204** [comment]
can anyone connect and solve the issue still i am not able to authorize salesforce org

**Comment by smaddox-sf** [comment]
Hi @arjunRao1204 - [Please check out this CLI issue and the workaround ](https://github.com/forcedotcom/cli/issues/1104#issuecomment-892827077) to see if this unblocks you.   There's not a lot of repro detail in this issue, but from what you've described, I think you might be impacted by that issue.  Please check it out and let us know.

If not, please go to the terminal window in VS Code and type `sfdx version` and paste the output you see.  Here's a visual on the terminal and command:  

![image](https://user-images.githubusercontent.com/59572234/128736105-4b0ff277-35fb-4b36-8867-8ea8523532ea.png)
