### ISSUE TITLE
\bin\sfdx.cmd"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by pradykris** [forcedotcom/salesforcedx-vscode#3477]
### Summary
Getting error while clicking the open org icon
\bin\sfdx.cmd"' is not recognized as an internal or external command. 

But pushing and retrieve from org seem to work.

### Steps To Reproduce:

1.  Open VSCode CLI project. click on the Open org icon or run the command sfdx force:org:open
1.  

### Expected result

Should have opened up the org in the browser

### Actual result

"C:\Users\HP\AppData\Local\sfdx\client\bin\..\7.110.0-85b006b\bin\sfdx.cmd"' is not recognized as an internal or external command, operable program or batch file.

### Additional information

I have been using VSCode and CLi for over year on this machine but this issue started a week back.
I have tried reinstalling VScode and CLI. Paths are there on the environment variables. Saving the code does push the code into the org successfully. Retrieve also works fine. While looking at Help->Toggle Developer Tools shows following errors

[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
======================================================

workbench.desktop.main.js:62 [Extension Host] Cannot find en-us, defaulting to en
S @ workbench.desktop.main.js:62
=====================================================

(node:5176) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
=======================================================

'"C:\Users\HP\AppData\Local\sfdx\client\bin\..\7.110.0-85b006b\bin\sfdx.cmd"' is not recognized as an internal or external command,
operable program or batch file.
=========================================================

**Salesforce Extension Version in VS Code**: v52.8.0

**SFDX CLI Version**: Unable to find the version as the SFDX command on the terminal and cmd doesnt work. Extension says  v52.8.0

**OS and version**: windows 10

**Comment by smaddox-sf** [comment]
Hi @pradykris  - Thanks for reaching out.  You mention that you have installed the CLI and have been using it.  The description of what's going on sounds like the CLI is no longer installed or that VS Code can't find the path to the CLI.  Even without the CLI some commands will work, such as deploy & retrieve and Apex.  Under the hood, we've been working to use business logic libraries that the CLI & VS Code share, which makes VS Code setup simpler and the commands faster.  Some commands still use the CLI directly though.


In your terminal (either in VS Code or just on your computer), can you try `sfdx version` and post back what output you get?

Also, here's one tip that might help regarding the path on Windows for the CLI: https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows

**Comment by mpuri18** [comment]
@smaddox-sf  i am also getting the same issue since past 2 days. I am able to deploy,retreive,diff from org but some functions such as switching between sandboxes ,authorizing an org stopped working suddenly. I get the same error explained above. I tried running the sfd version command in both computer and vs code terminal but got the same error of unrecognized sfdx command.

**Comment by smaddox-sf** [comment]
Thanks for the additional details @mpuri18 .  There is an open issue on the CLI that is in the process of being fixed.  Can you check out this issue and the workaround to see if it unblocks you?

[Here's the link directly to the comment with the workaround within the issue.](https://github.com/forcedotcom/cli/issues/1104#issuecomment-892827077)
