### ISSUE TITLE
Unable to authorise Salesforce Org

### ISSUE THREAD

**Issue by Jmahony92** [forcedotcom/salesforcedx-vscode#3478]
Hi,

I am unable to authorise a Salesforce Org on VScode despite having Salesforce extension pack installed and the latest instance of Salesforce CLI installed. 

Any help would be great

Issue Type: <b>Bug</b>

10:31:48.170 sfdx force:auth:web:login --setalias Prod --instanceurl https://login.salesforce.com --setdefaultusername
'sfdx' is not recognized as an internal or external command,
operable program or batch file.
10:31:48.461 sfdx force:auth:web:login --setalias Prod --instanceurl https://login.salesforce.com --setdefaultusername
 Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli

Extension version: 52.8.0
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (6.12GB free)|
|Process Argv|--crash-reporter-id b5afd8de-bf19-48e4-9d1b-4643a2a24ec0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by smaddox-sf** [comment]
Hi @Jmahony92 - Thanks for reaching out.  Can you post the version of the CLI that you are on? (You can see that by using the command `sfdx version` in the terminal.  If you get an error from the integrated terminal in VS Code, I'm curious if you get a different result when executing the command on your default terminal.)

From the error you posted, it looks like either the CLI is not installed properly or perhaps VS Code doesn't have the right path to the CLI.  

Just to double check, did you [install using these instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm)?

Here's how to resolve the path issue, if that is the source of the issue: https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows
