### ISSUE TITLE
"Detect Conflict At Sync" doesn't work

### ISSUE THREAD

**Issue by darioms21** [forcedotcom/salesforcedx-vscode#3479]
**Summary**

Click on "SFDX: Deploy Source in Manifest to Org" or "SFDX: Retrieve Source in Manifest to Org" on Packaged ("salesforcedx-vscode-core.detectConflictsAtSync": true); The conflict start aleatory and only in the Deploy case.

**Steps To Reproduce**

	1. Enable "Salesforcedx-vscode-core: Detect Conflicts At Sync"
	2. Click "SFDX: Deploy Source in Manifest to Org" or "SFDX: Retrieve Source in Manifest to Org" on Packaged.
	3. In case of "SFDX: Deploy Source in Manifest to Org" occasionally run the conflict in the output, but does not always work correctly. In case of "SFDX: Retrieve Source in Manifest to Org" never run the conflict in the output.
	
**Expected result**

Always that Enable "Salesforcedx-vscode-core: Detect Conflicts At Sync". Should run the conflict and when there are conflicts show a alert to view the conflict or override the source.

**Actual result**

The confict never correctly executed. Only occasionally in action Deploy but not always.

**Salesforce Extension Version in VS Code:**
v52.8.0

**SFDX CLI Version:**
sfdx-cli/7.110.0 win32-x64 node-v14.17.3

**OS and version:**
OS: Windows 10 Enterprise
Version: 1909

**Comment by smaddox-sf** [comment]
Hi @darioms21 - Thanks for sharing this feedback.  Conflict Detection only applies to `Deploy` commands.  ([See more details in the documentation](https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts).).  A conflict for deploy is defined as: _A conflict occurs when the metadata file in the org was last modified more recently than the last successful deployment or retrieval of this file to your local project._ 

Can you share the steps to reproduce when you are executing a `Deploy` and not seeing the conflict you expect?
