### ISSUE TITLE
Error when retrieving Tableau CRM dashboards via retrieve/deploy library in VS Code

### ISSUE THREAD

**Issue by thobenberlin** [forcedotcom/salesforcedx-vscode#3483]
### Summary

Retrieving and deploying Tableau CRM dashboards, which include a text or a richText widget fails with an error due to bad meta data.

### Steps To Reproduce:

1.  Create a dashboard in Tableau CRM with a text widget.
2. Retrieve the dashboard via retrieve source code in VS Code.
3. Try to deploy the dashboard on another org.

### Expected result

Meta data for the text widget should look like this (it does with sfdx and api version 52):
`"text_1": {
                "parameters": {
                    "content": {
                        "richTextContent": [
                            {
                                "attributes": {
                                    "size": "16px",
                                    "color": "#091a3e"
                                },
                                "insert": "Products"
                            },
                            {
                                "insert": "\n\n"
                            },
                            {
                                "attributes": {
                                    "align": "left"
                                },
                                "insert": "\n"
                            }
                        ]
                    },
                    "showActionMenu": false
                },
                "type": "text"
            },`

### Actual result

Meta data retrieved via VS Code library looks like this and throws error, when trying to deploy:
`"text_1": {
    "parameters":{
    "content":{
        "displayTemplate":"Products\n\n"},
    "fontSize":16,
    "showActionMenu":false,
    "textAlignment":"left",
    "textColor":"#091A3E"},
  "type":"text"
}`

### Additional information

richText widget was introduced with api version 52.

**Salesforce Extension Version in VS Code**: 
v52.8.0

**SFDX CLI Version**:
7.112.1
**OS and version**:

**Comment by randi274** [comment]
@thobenberlin can you try setting the sourceApiVersion to 52 in your sfdx-project.json and try again? We recently made an update so the API Version should be respected with regards to new features. If that doesn't work, can you tell us if you are using the setting 'Experimental: Deploy Retrieve'?

**Comment by thobenberlin** [comment]
Hi, problem for me was the 'Experimental: Deploy Retrieve'. Switching it of, fixed the issue for me.

**Comment by randi274** [comment]
Glad to hear it was resolved for you! I'll go ahead and close this for now, but do let us know if you have any additional concerns on this.
