### ISSUE TITLE
Cannot set an org to new proyect

### ISSUE THREAD

**Issue by agvazquezId** [forcedotcom/salesforcedx-vscode#3486]
### Summary

Hi! When i tried to set up a new project with a new org, when authorizing the org it returned the following error: 
20:26:52.595 sfdx force:auth:web:login --setalias DEV --instanceurl https://test.salesforce.com --setdefaultusername
/Users/macair/.local/share/sfdx/client/bin/sfdx: line 16: /Users/macair/.local/share/sfdx/client/bin/../7.110.0-85b006b/bin/sfdx: No such file or directory
20:26:52.621 sfdx force:auth:web:login --setalias DEV --instanceurl https://test.salesforce.com --setdefaultusername
 ended with exit code 1

### Steps To Reproduce:

1. Create new project
2. Authorize an org
3. Fill the fields

### Expected result

The org is authorized and data is retrieved
### Actual result

Error: 
20:26:52.595 sfdx force:auth:web:login --setalias DEV --instanceurl https://test.salesforce.com --setdefaultusername
/Users/macair/.local/share/sfdx/client/bin/sfdx: line 16: /Users/macair/.local/share/sfdx/client/bin/../7.110.0-85b006b/bin/sfdx: No such file or directory
20:26:52.621 sfdx force:auth:web:login --setalias DEV --instanceurl https://test.salesforce.com --setdefaultusername
 ended with exit code 1
### Additional information

_Feel free to attach a screenshot_.

Salesforce Extension Version in VS Code: v52.8.0

SFDX CLI Version: v52.8.0

OS and version: MacOS Big Sur 11.4

**Comment by AnanyaJha** [comment]
Thanks for reporting this @agvazquezId . There is an open issue on the CLI that is in the process of being fixed. Can you check out this issue and the workaround to see if it unblocks you?

[Here's the link directly to the comment with the workaround within the issue.](https://github.com/forcedotcom/cli/issues/1104#issuecomment-892827077)

**Comment by agvazquezId** [comment]
Thanks a lot it worked!!  I deleted the folder and installed again SalesforceCLI with the npm command
`npm install sfdx-cli --global --force`. 

Thank you so much!
