### ISSUE TITLE
No longer reports deployment errors to VSCode - Problems tab is not showing errors from a failed deploy

### ISSUE THREAD

**Issue by austinsholmes** [forcedotcom/salesforcedx-vscode#3488]
### Summary

When deploying a new class (that contains invalid code) via the UI in VS Code, the problematic line/column is not reported in the "Problems" tab.

### Steps To Reproduce:

1.  Create a new non-existent class in either an existing project or a new project.
1.  Be sure to have a default org set.
1.  The following code can be used as an example which contains a non-existent type "badType": 
`public with sharing class Junk
{
    public Junk()
    {
        badType i = 1;
    }
 }`

1.  Right-click the file  in the VS Code Explorer and select "SFDX: Deploy Source to Org"
1.  Observe results.

### Expected result

Deployment fails. Error highlighting line/column and reason for error is in the "Problems" tab.

### Actual result

Deployment fails. Problems tab continues to show "no problem" and no indication is reporting why it failed.

### Additional information

![image](https://user-images.githubusercontent.com/52339905/128933995-74199fca-0039-4eb9-93b7-d41abe8d2eff.png)

**Salesforce Extension Version in VS Code**:  v52.8.0

**SFDX CLI Version**: sfdx-cli/7.112.1 win32-x64 node-v14.17.4

**OS and version**: Windows 10 Enterprise 2004

**Comment by xyc** [comment]
Do you have `salesforcedx-vscode-apex.enable-semantic-errors` VS Code setting on?

**Comment by austinsholmes** [comment]
Thanks for the quick response @xyc, unfortunately I have tried that as well, it does provide me with errors (and sometimes too many lol) prior to deployment, but I’ve been using VS Code without this enabled for quite some time and the Problems tab had always showed the true errors after a failed deployment until recently.

**Comment by tschroedertn** [comment]
@xyc and @austinsholmes  - this is happening for me too.  Whenever I have compile errors and deploy my Apex class to my sandbox, it returns "exit code 1" rather than showing the errors in the Output tab.  I then have to manually run the command (without JSON option) to see what the actual error is.  I am hoping maybe this can be corrected because it really cuts down on productivity.  I think this error started this week.

**Comment by xyc** [comment]
@austinsholmes @tschroedertn This seems to be an issue with the latest version (7.113.0) of SDFX CLI. Could you try turn on the VS Code setting` "salesforcedx-vscode-core>Experimental: Deploy Retrieve"`? That will allow you to deploy with the SDR library instead of CLI.

**Comment by austinsholmes** [comment]
@xyc that experimental feature seems to do the trick, thanks for the quick work around!

**Comment by tschroedertn** [comment]
@xyc that feature works for me as well.  Thanks!
