### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sf-tyrone** [forcedotcom/salesforcedx-vscode#3493]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.9.0`
- OS Version: `Darwin x64 19.3.0`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/s4/yqcg_c1j1hs_n2w1q_jdvtdm0000gn/T/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
