### ISSUE TITLE
Metadata API request failed: INVALID_LOCATOR: Retrieve result has been deleted.

### ISSUE THREAD

**Issue by venturec** [forcedotcom/salesforcedx-vscode#3495]
### Summary

After the updates to the Salesforce packages on 8/11/2021, when I right click package.xml and select SFDX: Retrieve Source in Manifest from Org, it returns the error in the subject.

I can use the Terminal window to run **sfdx force:source:retrieve -m ApexClass** successfully, but can't retrieve all of the metadata referenced in the package.xml in one retrieve.

### Steps To Reproduce:

1.  Open VS Code with an already authorized / active org
2. Allow VS Code to update the Salesforce CLI packages 
3. After restarting VS Code, right click package.xml in the Manifest folder and select SFDX: Retrieve Source in Manifest from Org,

### Expected result

After right clicking package.xml and selecting SFDX: Retrieve Source in Manifest from Org, all metadata referenced in the package.xml file should be retrieved with no errors.

### Actual result
Metadata API request failed: INVALID_LOCATOR: Retrieve result has been deleted.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:
v 52.9.0

**SFDX CLI Version**:
v 52.9.0

**Package XML API**:
52.0

**OS and version**:
Windows 10

**Comment by goldwinVonage** [comment]
I get the same issue in mac 11.4

**Comment by NerdtureUs** [comment]
I started seeing this today too, but it isn't isolated to the package.xml retrieval.  If you right click on any of the folders in the explorer bar, and try to retrieve, you get the same error.

Rolling back the "Salesforce CLI Integration" to v52.8.0 made it so I could keep working.

Hopefully this gets resolved quickly.

**Comment by goldwinVonage** [comment]
@NerdtureUs Rolling back the "Salesforce CLI Integration" to v52.8.0 is removing the retrieve option from the IDE

**Comment by goldwinVonage** [comment]
@NerdtureUs  it works. thank you.

**Comment by RyanGougler** [comment]
Same issue here. Current workaround is either rolling back versions as @NerdtureUs stated, or manually using the terminal to run `sfdx force:source:retrieve --manifest `

**Comment by matthewcoolidge** [comment]
@NerdtureUs Can you give steps on how you accomplished:

"Rolling back the "Salesforce CLI Integration" to v52.8.0 made it so I could keep working."

TYVM!

**Comment by goldwinVonage** [comment]
> @NerdtureUs Can you give steps on how you accomplished:
> 
> "Rolling back the "Salesforce CLI Integration" to v52.8.0 made it so I could keep working."
> 
> TYVM!

Go to "extenstions" -> find "Salesforce CLI Integration"  -> click gear icon -> install another version -> select  v52.8.0

**Comment by NerdtureUs** [comment]
@matthewcoolidge from within vs code, go to your list of installed extensions, an find and access "Salesforce CLI Integration" under the arrow, pick  "Install Another Version"

![image](https://user-images.githubusercontent.com/44677195/129265879-45ad83b6-a061-461d-af77-a15e89556c9a.png)

In the interface that opens up, pick the v52.8.0 version.

![image](https://user-images.githubusercontent.com/44677195/129266084-3127b41e-fc90-4731-bd09-e2b28e311b4b.png)

Then reload VS Code.

**Comment by xyc** [comment]
Thanks for reporting this issue  @venturec. We have release a patch version 52.9.1 that addresses this issue. Please update your Salesforce extension pack and Salesforce CLI Integration extension to 52.9.1 and let us know if this issue persists.

**Comment by goldwinVonage** [comment]
> Thanks for reporting this issue @venturec. We have release a patch version 52.9.1 that addresses this issue. Please update your Salesforce extension pack and Salesforce CLI Integration extension to 52.9.1 and let us know if this issue persists.

it works now. Thanks

**Comment by smaddox-sf** [comment]
Thanks for confirming @goldwinVonage .  @venturec - are you unblocked as well if you upgrade to the latest version?  (We released a patch version yesterday.). I wanted to check back with you as well before we close this issue.

**Comment by JagoPeeters** [comment]
I managed to get it fixed by just reloading the CLI extension (so without downgrading).
