### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Chinmaya-Git-account** [forcedotcom/salesforcedx-vscode#3501]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `52.9.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.59.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ro0204\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #3198
