### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by mail2mukeshkrsaini** [forcedotcom/salesforcedx-vscode#3502]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
There's no actionable info on this issue.  Closing this one, but feel free to open a new issue and fill out the info in the template so we can investigate.
