### ISSUE TITLE
VSCode - Unable to create default Scratch Org. #2797

### ISSUE THREAD

**Issue by SapirShira** [forcedotcom/salesforcedx-vscode#3505]
VS Output Text:

Starting SFDX: Create a Default Scratch Org...

10:01:58.887 sfdx force:org:create -f config\project-scratch-def.json --setalias trailhead --durationdays 7 --setdefaultusername --json --loglevel fatal
10:02:04.490 sfdx force:org:create -f config\project-scratch-def.json --setalias trailhead --durationdays 7 --setdefaultusername --json --loglevel fatal
 ended with exit code 1

The requested resource does not exist
![Screenshot 2021-08-17 101002](https://user-images.githubusercontent.com/65864272/129680223-41fa0f9b-2015-480f-8b80-1dd705ccf1f0.png)

**Comment by smaddox-sf** [comment]
Hi @SapirShira - Can you add more details on the steps to reproduce?  As an example, here's a few questions on info needed to troubleshoot: how are you executing the command to create the scratch org?  Are you within an SFDX project in VS Code?  Have you already authorized a Dev Hub?

Also, what version of the SFDX CLI are you running?

And which version of the Salesforce Extensions?

Which OS?

**Comment by SapirShira** [comment]
I succeeded
Thank you very much 
There was a problem with some lines of code
I deleted them and it worked
