### ISSUE TITLE
Debugger does not hit breakpoints

### ISSUE THREAD

**Issue by PhilipAnkers** [forcedotcom/salesforcedx-vscode#3508]
### Summary

Debugger does not hit breakpoints.  I'm sure this has worked in previous versions of the Saelsforce Extension Pack.

### Steps To Reproduce:

Debug any unit test.

### Expected result

Execution should be stopped at any breakpoint on a line of code being executed by the test.

### Actual result

Whilst you can step through the log using f11, the relevant line of code is not highlighted and the replay does not halt at lines of code on which breakpoints have been set.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: v52.9.1

**SFDX CLI Version**: v52.9.1

**OS and version**: Windows 10

**Comment by vhanson222** [comment]
I'm having this same issue.

**Comment by randi274** [comment]
@PhilipAnkers does reverting to the previous version work for you as well?
