### ISSUE TITLE
When ScratchOrg is set as default org VSCode menu is missing commands and org browser.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/salesforcedx-vscode#3521]
### Summary

When my default org is set to standard sandbox I can see org browser and commands in context menu for retrieving and uploading changes.
When default org is set to scratch org those options are missing.

### Steps To Reproduce:

1.  In status bar set default org as sandbox.
2. Check that you see 
- Org Browser
<img width="99" alt="2021-08-30_10h51_45" src="https://user-images.githubusercontent.com/5740564/131313353-a0d8e392-6f51-462c-88a0-0826ffc78177.png">
- Command when clicked on class folder:
<img width="299" alt="2021-08-30_10h52_50" src="https://user-images.githubusercontent.com/5740564/131313626-7597bbf2-9948-49a5-9962-82f101f040c8.png">
- Comand visible when clicked of class file:
<img width="382" alt="2021-08-30_10h56_56" src="https://user-images.githubusercontent.com/5740564/131314180-b932fa0b-4772-4d9a-9ea9-b1c113d3168c.png">

3.  Change org to Scratch org
4. Options visible before are missing:
- Org Browser
<img width="32" alt="2021-08-30_10h55_27" src="https://user-images.githubusercontent.com/5740564/131313840-4130b865-ccf8-4720-b247-3946a351eb67.png">
- Command when clicked on class folder:
<img width="301" alt="2021-08-30_10h55_48" src="https://user-images.githubusercontent.com/5740564/131313953-c3b2f67a-5a8f-4942-8ab5-e7c45a68cafb.png">
- Comand visible when clicked of class file:
<img width="347" alt="2021-08-30_10h58_02" src="https://user-images.githubusercontent.com/5740564/131314282-d7c6cc8d-093f-494b-bd2d-25fb9450f29e.png">

### Expected result

I see the same context menu no matter if I am working on Sandbox or Scratch Org

### Actual result

Context menu is missing commands

### Additional information

**Salesforce Extension Version in VS Code**: v52.11.0

**SFDX CLI Version**: 7.115.1

**OS and version**: Windows 10 21H2

**Comment by jag-sfdc** [comment]
@PawelWozniak - Thanks for reporting this. Due to certain restrictions in scratch orgs, 'Org Browser' and a few command are not available. We are working on addressing these in future releases. Thank you !
