### ISSUE TITLE
Unable to retrieve components from Salesforce orgs using VS Code 

### ISSUE THREAD

**Issue by debnatht** [forcedotcom/salesforcedx-vscode#3523]
### Summary

Unable to retrieve components from Salesforce orgs as well as unable to deploy any component using visual studio code clicks. Able to authorize orgs but retrieve is going in loop. Where using sfdx command able to retrieve and deploy.

### Steps To Reproduce:

1.  Open Visual studio code 
2.  Click on Org Browser
3.  Select any metadata and click on retrieve source from Org 

### Expected result

It should retrieve the selected component from org

### Actual result

Starting SFDX: Retrieve Source from Org

### Additional information

attached a screenshot.

**Salesforce Extension Version in VS Code**: v52.11.0

**SFDX CLI Version**: sfdx-cli/7.114.0 win32-x64 node-v14.17.5

**OS and version**:Windows 10 
![vs Retrieve](https://user-images.githubusercontent.com/80810399/131669874-f26c3288-0f42-417d-b3df-e5ec34b2b10f.PNG)

**Comment by jag-sfdc** [comment]
@debnatht - I'm not able to repro this locally. Can you check if you have 'Experimental: Deploy Retrieve' turned off in your settings? Is it a problem only on the Org Browser? What if you right-click and run 'SFDX: Retrieve Source from Org' from the explorer?

**Comment by debnatht** [comment]
Hi Team,

We are facing this issue inside vdi. And 'Experimental: Deploy Retrieve' turned on.

And this problem is not only with Org Browser. And if I  right-click and run 'SFDX: Retrieve Source from Org' from the explorer it gives the same result.

***@***.***


Thanks,
Tanusree Debnath

From: Jag Jayaprakash ***@***.***>
Sent: Thursday, 2 September 2021 3:21 AM
To: forcedotcom/salesforcedx-vscode ***@***.***>
Cc: Tanusree Debnath (SYD) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [forcedotcom/salesforcedx-vscode] Unable to retrieve components from Salesforce orgs using VS Code (#3523)


@debnatht<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdebnatht&data=04%7C01%7Ctanusree.debnath%40foxtel.com.au%7C69a4e48063874529178108d96d6ce0d5%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C637661136668754913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QTh0vHKI5inJvSVh4c02t7ao7eIvK6EPklcsmKbQ2Zc%3D&reserved=0> - I'm not able to repro this locally. Can you check if you have 'Experimental: Deploy Retrieve' turned off in your settings? Is it a problem only on the Org Browser? What if you right-click and run 'SFDX: Retrieve Source from Org' from the explorer?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforcedotcom%2Fsalesforcedx-vscode%2Fissues%2F3523%23issuecomment-910492297&data=04%7C01%7Ctanusree.debnath%40foxtel.com.au%7C69a4e48063874529178108d96d6ce0d5%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C637661136668764864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ht%2FqrZiiplolo5vOw4U7Zu9zmBHJge1ml0nmod%2BXycw%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATIRDH7IYZOAPEPYHMI4GQDT7ZOH5ANCNFSM5DGLD6EA&data=04%7C01%7Ctanusree.debnath%40foxtel.com.au%7C69a4e48063874529178108d96d6ce0d5%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C637661136668764864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CdKUQXhrcr3SUAubOeQjg1TX%2BXKq%2BqquNZ0rNKE1ep4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctanusree.debnath%40foxtel.com.au%7C69a4e48063874529178108d96d6ce0d5%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C637661136668764864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O9r8PtvRv3986hvy12gwsXQXs66UFAygoP%2BTahkeTi0%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctanusree.debnath%40foxtel.com.au%7C69a4e48063874529178108d96d6ce0d5%7C55e0963ce2f2477cad98ba2d1be5ae2b%7C1%7C0%7C637661136668774820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3i7dgCLNSLXQ4ODLBeZjzQcf%2F6mQVY7UcYwQMEgdSKw%3D&reserved=0>.

This e-mail, and any attachment, is confidential. If you are not the intended recipient, please delete it from your system, do not use or disclose the information in any way, and notify the sender immediately. Any views expressed in this message are those of the individual sender and may not be the views of Foxtel, unless specifically stated. No warranty is made that the e-mail or attachment (s) are free from computer viruses or other defects.
