### ISSUE TITLE
Salesforce Extension Pack blocks ESLint's Quick Fix suggestion

### ISSUE THREAD

**Issue by JulianOstmo** [forcedotcom/salesforcedx-vscode#3527]
### Summary
The ESLint quick fix suggestions get stuck at `Checking for quick fixes...`. 
![Screenshot 2021-09-02 at 18 08 57](https://user-images.githubusercontent.com/12764364/131887952-fac4c368-d6d0-4bbc-bd26-2b03768c070a.png)

When I uninstall the [Salesforce Extension Pack](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) the Quick Fix option is correctly displayed:
![Screenshot 2021-09-02 at 18 14 21](https://user-images.githubusercontent.com/12764364/131888185-d24a8a73-83c3-46bc-bccf-589c1c89197b.png)

### Steps To Reproduce:

1.  VS Code with ESLint and Salesforce Extension Pack (see versions below)
2.  Write some code that should cause an ESLint error, e.g:
```js
const request = require('supertest');
const mockConfig = require('./config/superagent-mock-config');
const mocks = require('superagent-mock')(request, mockConfig);
``` 
3. Hover over red line and see Quick Fixes sections stuck on `Checking for quick fixes...`

### Expected result
![Screenshot 2021-09-02 at 18 14 21](https://user-images.githubusercontent.com/12764364/131888185-d24a8a73-83c3-46bc-bccf-589c1c89197b.png)

### Actual result

![Screenshot 2021-09-02 at 18 08 57](https://user-images.githubusercontent.com/12764364/131887952-fac4c368-d6d0-4bbc-bd26-2b03768c070a.png)

**Salesforce Extension Version in VS Code**: v52.12.0
**SFDX CLI Version**: 7.94.3-a4e7c7955b
**ESLint version**: v2.1.23
**node**:v14.15.4
**OS and version**: Mac 10.15.7

**Comment by xyc** [comment]
This doesn't seem to relate to Salesforce extension pack. Can you try the something similar to this stackoverflow question? https://stackoverflow.com/a/67805303
> Same was happening to me as well and after trying multiple things what worked for me was a clean reinstall of Code which meant uninstalling Code, deleting the extension folder and and installing the code followed by extensions. And quick fix is back.
