### ISSUE TITLE
i have download the updated version both java jdk and sfdx (cli) and when i am trying to install salesforce extension pack in the vs code facing below errors

### ISSUE THREAD

**Issue by vai12** [forcedotcom/salesforcedx-vscode#3531]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
<img width="956" alt="Screenshot 2021-09-03 104027" src="https://user-images.githubusercontent.com/55106242/132013017-ba52f103-5d01-442e-824d-cc8602fdd35d.png">

**Comment by smaddox-sf** [comment]
Duplicate #3530
