### ISSUE TITLE
Error on retrieve source in manifest from org

### ISSUE THREAD

**Issue by acemccloud123** [forcedotcom/salesforcedx-vscode#3536]
Getting the following error when I do retrieve source
Starting SFDX: Retrieve Source from Org

 

Metadata API request failed: Client network socket disconnected before secure TLS connection was established

**Comment by smaddox-sf** [comment]
Hi @acemccloud123 - We need a bit more info to investigate this.  Please share:

- Steps to reproduce (For example, are you trying to retrieve from Org Browser, command palette, CLI command, etc)
- Expected outcome
- Actual outcome
- Version # of the Salesforce VS Code extension
- SFDX CLI Version
-  OS and version
