### ISSUE TITLE
Conflict Detection Firing Everytime if I don't retrieve first

### ISSUE THREAD

**Issue by ralphcallaway** [forcedotcom/salesforcedx-vscode#3542]
### Summary

Conflict detection is firing on every save.

### Steps To Reproduce:

1.  Open SomeClass.cls
2. Run the "SFDX: Retrieve this Source from Org" command
3. Make a change to SomeClass.cls and save
5. Make a second change and save

### Expected result

Both saves should go through since the version of the class prior to the change is up to date.

### Actual result

The first change after doing a retrieve goes through without throwing a conflict error. The second change throws a conflict error.

### Additional information

**VS Code Version**: 1.60.0 x64

**Salesforce Extension Version in VS Code**: Salesforce Extension Pack v52.13.0

**SFDX CLI Version**: sfdx-cli/7.117.0 darwin-x64 node-v14.17.6

**OS and version**: OS X 10.15.7 (19H1323)

**Comment by ralphcallaway** [comment]
looks like the cache might be updating the last modified date for the component at the start of the save instead of at the end so after a save you might have a local timestamp that's a couple seconds before the remote last modified which incorrectly implies there is a conflict
- remote: 1:00:23
- local: 1:00:21

if you're using the file system for the local last modified date you'll want to "touch" the modified components upon completion of any save/deploy operation, or if you're using a cache, you'll want to update that after completion save operation. note that this should happen regardless of whether the save actually succeeds (since a compile failure would still advanced the local version timesamp), but NOT when a user cancels at conflict detection

**Comment by smaddox-sf** [comment]
Thank you for all the detail @ralphcallaway !  We will investigate

**Comment by ralphcallaway** [comment]
same issue as #3522

**Comment by AnanyaJha** [comment]
Hi Ralph! I'm going to close this issue in favor of #3522
