### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KartheekL** [forcedotcom/salesforcedx-vscode#3547]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.13.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.58.2`

[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/7166787/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #2410
