### ISSUE TITLE
Apex auto formatting 

### ISSUE THREAD

**Issue by Xixiao007** [forcedotcom/salesforcedx-vscode#355]
### Summary
There seems no feature to auto format Apex code nor linting warnings.
I have looked at this thread: https://github.com/forcedotcom/salesforcedx-vscode/issues/95 but not sure if it talks exactly the same problem

### Steps To Reproduce:
1. Right click on the file content window, there is no `format document` option. 
2. In javascript file, this option is available.

### Additional information
Should I manually remove all unnecessary space and make the code aligned?

**Comment by vazexqi** [comment]
@Xixiao007 - Unfortunately, the Apex code formatter has not been completed yet :-(

#95 is about the same issue. Let's take the discussion there since there is more context there. I'll reply there. If could subscribe to that thread to receive updates that would be good.
