### ISSUE TITLE
Automatically rename all files of a LWC when the parent folder name is changed

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#3554]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it will improve DX on VS Code reducing waste of time while renaming files.

**Describe the solution you'd like**
When working with LWC we always have a parent folder with the name of the component followed by files that have the same name of the component. Sometimes, while developing, we change our mind about the name of the component and we want to change it. In order to do so, we have to rename at least 3 things by hand:  the parent folder name, the .xml file and .js file. The .css and .html might not exist, but if they do, we would also have to change them. So the idea is to create a new VS Code command that would rename the children files if the parent folder name is changed. You can also investigate if you can hook a handler to the standard vscode rename button, instead of creating a new command.

![image](https://user-images.githubusercontent.com/55927613/134359923-a407555f-1ded-44a9-82ce-5a9e94d9f230.png)

**Describe alternatives you've considered**
At the moment I have to do it manually

**Additional context**
N/A

**Comment by randi274** [comment]
Thanks for logging this @AllanOricil- @smaddox-sf and I were just discussing this the other day! We're currently considering what gaps our products have for LWC compatibility in the ecosystem, so it's great to hear what our users are looking for as we prioritize future work.

**Comment by AllanOricil** [comment]
@randi274 cool. If you need help to identify more improvements to make the product better, and also hands to work on vscode customizations, I'm available to do business with Salesforce.

**Comment by AnanyaJha** [comment]
Thanks @AllanOricil! We'll be looking at prioritizing this issue during our next iteration. Let us know if there are any other improvements you've discovered while developing with LWC (or otherwise) and our Extensions!

**Comment by randi274** [comment]
@floralan heads up on connecting your WIP to this issue!

**Comment by floralan** [comment]
@AllanOricil Hi! We added the "SFDX: Rename Component" command recently in [#3923](https://github.com/forcedotcom/salesforcedx-vscode/pull/3923), It will be shipped in this week's release. Please check out our latest version later this week!

**Comment by AllanOricil** [comment]
Hope people use it. I will give it a try

**Comment by AllanOricil** [comment]
@floralan I have the latest vscode extension pack but this command does not show up

**Comment by randi274** [comment]
@AllanOricil are you right clicking the bundle, or one of the files underneath? It doesn't work on the __test__ directory just yet, but it should appear for the others!
