### ISSUE TITLE
Retrieve source from org fails due to (bad?) static resource

### ISSUE THREAD

**Issue by eclarke12** [forcedotcom/salesforcedx-vscode#3557]
### Summary

Trying to retrieve metadata from a full sandbox gives an error. I believe this is related to static resources.

> 14:49:48.193 Starting SFDX: Retrieve Source from Org
Metadata API request failed: Component conversion failed: FILE_ENDED

### Steps To Reproduce:

1. Initialise a standard project
2. Authorise an org
3. Attempt to retrieve metadata using manifest

### Expected result

Metadata retrieved

### Actual result

Retrieval fails.
Workaround: remove `StaticResource` MD type from manifest

### Additional information

Seems similar to #2871

**Salesforce Extension Version in VS Code**: v52.13.0

**SFDX CLI Version**: 7.118.1-6fd25cc

**OS and version**: W10 20H2 Build 19042.1237

**Visual Studio Code version:** 1.60.2
```
Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by xyc** [comment]
@eclarke12 Thanks for reporting! Do you mind provide more information about the MIME type of the static resource?
