### ISSUE TITLE
SFDX Right Click to Deploy/Retrieve is lost after switching to sandbox and switching back to scratch org

### ISSUE THREAD

**Issue by uvaiskomathsfdc** [forcedotcom/salesforcedx-vscode#3558]
Summary

Right-clicking a metadata file shows SFDX Deploy as an option when i create a scratch org and is connected to it. If i switch to a sandbox this is still retained. if i come back to scratch org then the deploy options are gone.

Steps To Reproduce:

$ sfdx force:org:create -f config/project-scratch-def.json --setalias **myScratchOrgAlias** --setdefaultusername

right click on a a resource in the package directory (let's say on force-app/main/default/classes/MyClass.cls)
options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" are **SHOWN**

$ sfdx force:config:set defaultusername=mySandboxAlias
right click on a a resource in the package directory (let's say on force-app/main/default/classes/MyClass.cls)
options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" are **SHOWN**

$ sfdx force:config:set defaultusername=myScratchOrgAlias
right click on a a resource in the package directory (let's say on force-app/main/default/classes/MyClass.cls)
options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" are **MISSING**

$ sfdx force:config:set defaultusername=mySandboxAlias
right click on a a resource in the package directory (let's say on force-app/main/default/classes/MyClass.cls)
options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" are **SHOWN AGAIN**

Expected result
See the options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" when right-clicking a resource when connected to a scratch org - even if we switch between sandbox and scratch org

Actual result
We do not see the options "SFDX: Deploy Source to Org" and "SFDX: Retrieve Source from Org" when right-clicking a resource when connected to a scratch org if a sandbox was connected before

Additional information
![image](https://user-images.githubusercontent.com/53842192/134835964-18ff2c4a-2532-4d9c-94bb-21000ed6cc90.png)

VS Code Version:
1.60.2

SFDX CLI Version:
sfdx-cli/7.119.2 darwin-x64 node-v14.17.6

Salesforce Extension Pack Extended Version:
52.13.0

OS and version:
macOs Catalina 10.15.7

**Comment by smaddox-sf** [comment]
Hi @uvaiskomathsfdc - When working with a source-tracked org (like scratch orgs), we hide the deploy/retrieve commands and instead expose push/pull.  The reason is that historically, mixing a push & deploy on a source-tracked org can have some unexpected consequences.  We have some foundational work ongoing to make these commands more interoperable.  As they are, we will look to loosen what we expose in VS Code for source-tracked orgs.

**Comment by uvaiskomathsfdc** [comment]
> Hi @uvaiskomathsfdc - When working with a source-tracked org (like scratch orgs), we hide the deploy/retrieve commands and instead expose push/pull. The reason is that historically, mixing a push & deploy on a source-tracked org can have some unexpected consequences. We have some foundational work ongoing to make these commands more interoperable. As they are, we will look to loosen what we expose in VS Code for source-tracked orgs.

Hello there. the issue is that the behaviour is inconsistent. it works when a scratch org is created but that functionality disappears after i connect to a sandbox and then come back to my scratch org.

Hiding this has made development difficult because it pulls changes that i don't want to commit (for eg:- page layout modifications made to help testing). previously i could cherry pick the changes i want. but now i have to pull everything and remove anything i dont want from git tracked changes.

**Comment by smaddox-sf** [comment]
Ah, thanks for clarifying @uvaiskomathsfdc .  I misunderstood the original information.  The inconsistency sounds like a bug.  We'll try to repro this and may reach out with questions if we can't replicate it.

Thanks for the feedback also on wanting to have access to both sets of commands.  As I mentioned, this is something on our roadmap.  In the meantime, you can use the CLI (perhaps with a manifest.xml file to limit the scope).  I realize the CLI might not be quite as convenient as the command palette/right-click options.

**Comment by Schuchie** [comment]
@randi274 I can see only the SFDX: Diff Folder Against Org in the context menu. When I set my default org to a sandbox its appears again. Switching back to a scratch and these actions as describe above disappearing again.

I think it happened after a broken .forceignore.

**Comment by swdcworld** [comment]
Have a great vs code extension to work same. It has 7kb of size only. 
https://marketplace.visualstudio.com/items?itemName=Nagarjuna.sfdevtools
