### ISSUE TITLE
Lightning namespace's components completion

### ISSUE THREAD

**Issue by splacentino** [forcedotcom/salesforcedx-vscode#356]
### Summary
There is not any completion for standard components (from lightning namespace) in `.cmp` file.

### Steps To Reproduce:
1. sfdx force:lightning:component:create -n mylightningcomp
2. Open mylightningcomp.cmp file
3. Start typing `<lightning:` then CTRL+SPACE

### Expected result
> List of components available in `lightning` namespace

### Actual result
> Nothing is proposed

### Additional information

![Completion](http://pix.toile-libre.org/upload/original/1522307633.png)

I do not find any documentation about this completion, maybe this is just not implemented (yet ?)

**VS Code Version**:

1.21.1

**SFDX CLI Version**:

6.8.2

**OS and version**:

Windows 7

**Comment by vazexqi** [comment]
@splacentino - This has not been implemented _yet_. Safe harbor withstanding, this should be in the works for this release.

**Comment by victorabraham** [comment]
I still do not see this working. Do we need Java 8 for this to work?

**Comment by htanguturi** [comment]
@vazexqi  Is this implemented? Can I know is there any other issue to follow as this is closed?

**Comment by Neezen** [comment]
Hi - this is still not working. Has there been an update on whether this has been implemented? Thanks

**Comment by magesh28** [comment]
@vazexqi  Is this still open? Let us know when this feature will available for use.

**Comment by rohanshenoy96** [comment]
@vazexqi This is still not working. Please update us if any changes

**Comment by vazexqi** [comment]
![demo](https://user-images.githubusercontent.com/54414/97115441-fa589b00-16b3-11eb-871d-19da27e3e095.gif)

@rohanshenoy96 - This is working for as the gif above demos. Do you have the right extensions installed?

CC: @lcampos @smaddox-sf

**Comment by rohanshenoy96** [comment]
Hi @vazexqi. I'm pretty sure that I've installed the right extension. Also I've fixed it to partial working (fix was installed java jdk, I think extension requires this). Still I have to press command + space everytime, which is really annoying.

**Comment by vazexqi** [comment]
> Also I've fixed it to partial working (fix was installed java jdk, I think extension requires this)

We do require Java for other portions but I don't think we need it for the Aura code completion. We require it for the SLDS completion. Let's have Luis and Stephanie reply.

> Still I have to press command + space everytime

Is that the main issue? This might be deep in the framework on VS Code completion. I remember there is a setting for completion that have a _long_ list that it doesn't auto-suggest until about X characters have been entered. I suspect that this is the behavior you are seeing. Could you try https://stackoverflow.com/a/41036596 and configure it to be more aggressive in suggesting? Personally, I don't like aggressive auto-suggestions but it's a personal taste.

**Comment by lcampos** [comment]
We fixed a few things related to automatically surfacing completions/suggestions in both aura and lwc in release 50.1.0 of the Salesforce extensions for VSCode. As Nick already mentioned, Java configurations are unrelated to aura and lwc.

If you are on version 50.1.0 or higher and still have issues I suggest you open a new issue and provide us with a way to replicate the problem so we can work on it.
