### ISSUE TITLE
Infinite Loop when we are retriving the code in VS Code using sfdx latest extension

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/salesforcedx-vscode#3566]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce: Create VS Code for a non-scratch Org. Try Retrieving the entire org it does not end at all.

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened_.

### System Information

Run `sfdx version --verbose --json` and paste the output here.

### Additional information

_Feel free to attach a screenshot_.

**Comment by xyc** [comment]
Are you retrieving from manifest - "Retrieve Source in Manifest from Org"? Also could you provide more information about the project / org you have this issue on? Is it reproducible from dreamhouse-lwc? We haven't been able to reproduce this issue.

**Comment by xyc** [comment]
@ratnesh76 Could you let us know what version of Salesforce extension pack you are using? Also, could you provide some information about the metadata type of the code you are deploying (Like Apex/LWC/etc.)? Does it happen with a specific metadata type or any types?

It's also helpful if anything on the "Salesforce CLI" channel of VS Code Output Panel shows up as well.
<img width="585" alt="Screen Shot 2021-10-13 at 2 39 40 PM" src="https://user-images.githubusercontent.com/679275/137216335-5a001341-fe77-422a-ae9d-72a2b69a8dcf.png">

**Comment by ratnesh76** [comment]
Yes I am behind the firewall and using the VPN.
