### ISSUE TITLE
Org Browser Metadata search function

### ISSUE THREAD

**Issue by RadekMichna** [forcedotcom/salesforcedx-vscode#3569]
**Description of what the problem is**
It is quite time consuming task to find individual metadata in the org browser metadata as the list can be very long.

**Describe the solution you'd like**
Add simple search/filter functionality 

**Additional context**
<img width="691" alt="136229162-8c815f64-097d-40c2-9802-769ba60cfe6c" src="https://user-images.githubusercontent.com/1104043/136231632-73d2d4c7-0d0a-45d9-bb41-4a2b3e3449ce.png">

**Comment by AllanOricil** [comment]
If this view is using a "WebviewView view", then it is possible to do what you suggested. But if it is using the standard list api they won't be able to render an Input where you want. That region can only contain buttons and these buttons can be bound to Commands.
