### ISSUE TITLE
sfdx-apex-test-run-coverage-issue with the SonarQube code analysis

### ISSUE THREAD

**Issue by balanandam** [forcedotcom/salesforcedx-vscode#3571]
Hello Team,

Is above issue resolved, if yes could you pls provide the solution as we are also facing similar issue.

Here is my issue details:
sfdx-apex-test-run-coverage-issue

![sfdx-apex-test-run-coverage-issue](https://user-images.githubusercontent.com/29630122/136395489-d297d129-a583-40c7-905d-a8e335c72a2f.jpg)

Current sfdx version: sfdx-cli/7.120.0 win32-x64 node-v14.18.0

As per image shows above, getting wrong output in the test summary results(100%) as actually, the main required class is having only 72%. I am not sure why test results summary shows wrongly and also several other test classes are considered and showing in the detailed report while running command
sfdx force:apex:test:run --testlevel RunSpecifiedTests --tests "XXXXXXImageTriggerHandlerTest" --outputdir testReport --codecoverage -r human -y -w 20

How can we get absolute test class result only for the required test class which is passed in the command. Could anyone pls share your inputs to move forward on this issue.
Finally we want to integrate this test results report to the sonarqube code analysis tool for the code coverage through SonarQube.
sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.apex.coverage.reportPath=**/testReport/test-result-codecoverage.json
How can we consider the SFDC test code coverage into the SonarQube code coverage for the lines of code as SonarQube covers either new lines of code or Overall code in a project. But Is there any possibility of checking the codecoverage at Overall class level like how it considers in the SFDC code coverage instead of Overall code in application

Pls let me know your suggestions and Thanks for your time and appreciate your support.

-----
Bala.

**Comment by smaddox-sf** [comment]
Hi @balanandam - The 100% in the test summary refers to the rate of tests passing.  In this case, you have 1 test (listed in the 'Test Results' section).  That test passed so the pass rate is shown at 100%.  In the Test Summary section, you will also see 'Org Wide Coverage', which is the overall test coverage for the org.  In the screenshot, this is 50%.

To integrate with other systems, you should not use the human readable output from the command.  You could use json or another format.  Alternatively, you could call the API directly for specific inquiries (such as getting the coverage for a particular class.)
