### ISSUE TITLE
Sfdx create apex class button does not appear on nested folders

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#3572]
### Summary

If I click with the right mouse button on the classes directory, the command is available. If I click on a nested directory the command is missing. The command should appear on any nested folder within the classes directory.

### Steps To Reproduce:

1.  Create a folder inside the classes directory
2.  click with the right mouse button on this folder
3.  verify you cant see the create Apex class command

### Expected result

sfdx create Apex class command should appear when clicking on any nested directories that are inside the classes directory

### Actual results

Sfdx create Apex class command does not appear when clicking on a nested folder inside the classes directory

### Additional information

**Salesforce Extension Version in VS Code**:  

**SFDX CLI Version**:

**OS and version**:

**Comment by PawelWozniak** [comment]
I see a menu item but when I click it and provide the name then it still creates apex class in main directory as there is no other choice. In such case I would expect even skipping this choice menu and direct file create under a subdirectory.
<img width="264" alt="2022-07-04_08h35_21" src="https://user-images.githubusercontent.com/5740564/177095872-51f92dcf-75fc-471d-871c-9c1caae12d08.png">

**Comment by randi274** [comment]
@PawelWozniak are you finding that even if you chose another directory, the extensions still create the Apex class under the default `classes` directory? That sounds like it might be a different 🐛 worth logging separately.

**Comment by randi274** [comment]
Also, closing this one as @dehru [delivered](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode/CHANGELOG.md#5530---june-29-2022) it for us last month 🎉
