### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ravikanth8mallu** [forcedotcom/salesforcedx-vscode#3577]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.17.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.0`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-loa
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/7317213/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
d

**Comment by smaddox-sf** [comment]
Duplicate #2410
