### ISSUE TITLE
"Set a Default Org" command fails with a username with more than one alias

### ISSUE THREAD

**Issue by DanielCalle** [forcedotcom/salesforcedx-vscode#3579]
### Summary

Sometimes multiple aliases are created for the same username of an org. But this doesn't work well when selecting these aliases from vscode.

### Steps To Reproduce:

1.  Create more than one alias for a username of an org.
1.  Use "SFDX: Set a Default Org" command from vscode for the previous username with more than one alias.

### Expected result

Should select the username or one of the aliases as default org.

### Actual result

An error occurs when trying to set the concatenation of the different aliases with commas as the default user of an org.
`ERROR running config:set:  No AuthInfo found for name DevHub test,DevHub test2`

### Additional information

![image](https://user-images.githubusercontent.com/11243437/136858462-99620c02-37ab-4901-b564-dec192b9c1fe.png)

**Salesforce Extension Version in VS Code**: 52.17.0

**SFDX CLI Version**: sfdx-cli/7.121.8 linux-x64 node-v16.7.0

**OS and version**: Ubuntu 20.04.2 LTS

**Comment by ChuckJonas** [comment]
This is still broken...  If you have two orgs with the same username, they show up in the list as `user1,user`.

This effectively makes it so you cannot select the target org
