### ISSUE TITLE
Running a test with `--outputdir` returns an `ERROR running force:apex:test:run:  Invalid time value`

### ISSUE THREAD

**Issue by ipavlic** [forcedotcom/salesforcedx-vscode#3606]
### Summary

Running a test with `--outputdir` returns an `ERROR running force:apex:test:run:  Invalid time value`

### Steps To Reproduce:

`sfdx force:apex:test:run --codecoverage --resultformat json` runs normally.
`sfdx force:apex:test:run --codecoverage --resultformat json --outputdir test-output` or  `sfdx force:apex:test:run --codecoverage --resultformat json --outputdir .` or `sfdx force:apex:test:run --codecoverage --resultformat json --outputdir ./test-output` returns an `ERROR running force:apex:test:run:  Invalid time value`

### Expected result

Test outcome files should be generated

### Actual result

`ERROR running force:apex:test:run:  Invalid time value`

### System Information

```
{
	"cliVersion": "sfdx-cli/7.122.1",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v14.17.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.1.21 (core)",
		"apex 0.3.0 (core)",
		"auth 1.7.2 (core)",
		"config 1.2.40 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.2 (core)",
		"generator 1.2.1 (core)",
		"limits 1.2.2 (core)",
		"org 1.8.1 (core)",
		"salesforce-alm 52.6.0 (core)",
		"schema 1.0.8 (core)",
		"sfdx-cli 7.122.1 (core)",
		"source 1.2.2 (core)",
		"telemetry 1.2.6 (core)",
		"templates 52.4.0 (core)",
		"trust 1.0.10 (core)",
		"user 1.5.0 (core)"
	],
	"osVersion": "Darwin 20.3.0"
}
```

**Comment by cristiand391** [comment]
@ipavlic Sorry, this should be moved to https://github.com/forcedotcom/salesforcedx-apex/issues

The `force:apex*` commands are owned by another team, you can see in which plugin a command is with the `which` command:

```bash
sfdx which force:apex:test:run
=== force:apex:test:run
plugin: @salesforce/plugin-apex
```

Then you can find the repos here: https://github.com/salesforcecli/status

@WillieRuemmele can you transfer this issue to salesforcedx-apex? I don't have write access to that repo, thx!

**Comment by randi274** [comment]
@ipavlic we've had a [similar](https://github.com/forcedotcom/salesforcedx-apex/issues/213) issue logged in our Apex repo, and I'm wondering if it might be related. Can you share the full output that you're receiving when you encounter this error?

**Comment by ipavlic** [comment]
@randi274 Sure, here it is.

```
WARNING: WARNING: In the Summer ’21 release, we'll rename or remove some of the output files that are created when you run force:apex:test:run or force:apex:test:report with the --outputdir (-d) parameter.  This breaking change could impact your CI/CD scripts if they reference specific filenames. See https://sfdc.co/apex-test-updates for details

ERROR running force:apex:test:run:  Invalid time value
```

**Comment by randi274** [comment]
Thanks for the quick response! We're certainly not giving you much to work with there. Would it be possible to share a small json output from a singular test when it's not writing to a directory, but would otherwise fail if you were to write the output? Since we're not able to reproduce it, I'm hoping I could at least try to stub out the results locally using the output that you're getting back.

**Comment by jeffb-sfdc** [comment]
Hi @ipavlic , just checking in.  it's been 12 days and was wondering if this still happens.  If it does, could you share a small json output from a singular test when it's not writing to a directory, but would otherwise fail if you were to write the output?
