### ISSUE TITLE
Enable Salesforce Extensions for the Web version of VSCode

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#3609]
**Is your feature request related to a problem? Please describe.**
Currently Salesforce extensions are not ready for running in the Web version of [VSCode](https://vscode.dev/)

![image](https://user-images.githubusercontent.com/55927613/138449465-226b688a-f01b-42a9-9b21-8c4fcf74165c.png)

![image](https://user-images.githubusercontent.com/55927613/138449512-b11cd8b3-fa64-486e-aa6a-61f69d85959b.png)

You can do it following this https://code.visualstudio.com/api/extension-guides/web-extensions

Im not just sure how it would work with CLI's. Will it work with the binaries installed in the client? You need to ask VSCode team or do experiments.

**Comment by randi274** [comment]
Since Code Builder is now in Beta, I'll go ahead and close this 🎉
