### ISSUE TITLE
Created classes from command palette are in v52.0

### ISSUE THREAD

**Issue by tprouvot** [forcedotcom/salesforcedx-vscode#3611]
### Summary

When creating class from command palette, the api version is in version 52.0

### Steps To Reproduce:

1.  Open command palette (Ctrl+Shift+P for windows)
2.  Select SFDX: Create Apex Class
3. Enter name

### Expected result
Created class should be in the version mentionned in sfdx-project.json ("sourceApiVersion": "53.0")

Api version is set in class meta file:
ClassName.cls-meta.xml
<apiVersion>53.0</apiVersion>

### Actual result

<apiVersion>52.0</apiVersion>

### Additional information

![image](https://user-images.githubusercontent.com/35368290/138666158-8020431c-3369-493e-931e-791254db02b4.png)

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**: 7.123.0

**OS and version**:Windows 10

**Comment by jonnypetraglia** [comment]
Bump on this as it's still occurring.

**Comment by tprouvot** [comment]
> Hi @tprouvot, I see this as well, and also agree that it should be pulling from that config value. We've made some changes regarding the sourceApiVersion elsewhere in the extensions recently, and this is an active area of improvement for us. Was this something you recall was working differently before? Also, are you working with the new custom templates [feature](https://developer.salesforce.com/tools/vscode/en/user-guide/byotemplate)? That should allow you to add the convenience that you need while we look into what needs to change on our end.

Hi @randi274 this issue is non critical because I can create class in v53 with sfdx command or update the api version manually.

**Comment by randi274** [comment]
I'm changing this to feedback since the request is to use start using the sourceApiVersion to create classes. We do have a fix coming up to correct the out of date versioning, but this would be new functionality to respect the sourceApiVersion.

**Comment by tprouvot** [comment]
Hi,
The issue is solved with version 7.142.1 !
Thanks for your help
