### ISSUE TITLE
Even for packages without spaces or single quotes, ISV Debugger doesn't work

### ISSUE THREAD

**Issue by bdovh** [forcedotcom/salesforcedx-vscode#3619]
### Summary
When following the steps of https://developer.salesforce.com/tools/vscode/en/apex/isv-debugger, I apex my package content to be loaded so that I could set a breakpoint and start a debugging session

### Steps To Reproduce:

1. Create a package
2. Release a package version
3. Install package version to subscriber org
4. As subscriber, grant login access to the package publisher
5. As package publisher, login to subscriber org
6. Go to Apex Debugger and click a button to start ISV Debugger Session
7. Copy the link, go to VS Code and press CMD-Shift-P combination and select "SFDX: Create and Setup Project for ISV Debugging"
8. Select project destination folder and click Enter
9. Find out that there is an error for a package with spaces or single quotes
10. Update the package name to avoid using spaces or single quotes
11. Release a new package version
12. Install a new package version to subscriber org
13. As package publisher, login to subscriber org
14. Go to Apex Debugger and click a button to start ISV Debugger Session
15. Copy the link, go to VS Code and press CMD-Shift-P combination and select "SFDX: Create and Setup Project for ISV Debugging"
16. Select project destination folder and click Enter

### Expected result

The package content will be loaded into the force-app folder so that I could set breakpoint and start a debugging session

### Actual result

The force-app folder is empty and doesn't contain the package content even though permission set with "View and Debug Managed Apex" (View the Apex code in your packages, and debug code with Apex Debugger, when logged in to subscriber orgs. Limited to code in Managed - Released packages) is assigned to the PBO user and the package version is released.

### Additional information

**Salesforce Extension Version in VS Code**:
v53.0.1
**SFDX CLI Version**:
sfdx-cli/7.123.0 darwin-x64 node-v14.18.1
**OS and version**:
MacOS BigSur 11.4, also doesn't work on Windows as well

**Comment by jag-sfdc** [comment]
@bdovh - This appears to be a regression in CLI and we are working on a fix. Workaround is to downgrade your local CLI to version 115.1 (You can download the installer from https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.115.1/a6551a9/sfdx-v7.115.1-a6551a9.pkg. Before you do that, uninstall the existing CLI by following steps here https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm) Please let us know if this works. Thank you!

**Comment by bdovh** [comment]
Hi @jag-sfdc , thanks for update. I am working on other projects right now. May check later

**Comment by bdovh** [comment]
How do I install this file with pkg extension?

**Comment by gbockus-sf** [comment]
@bdovh This has been fixed in the CLI so you should be good to go if you update to the latest cli.  Thanks!

**Comment by mohanraj-r** [comment]
While dealing with a customer case (W-10891222) and trying to setup "ISV Customer Debugger"  errors
 
```
Command 'SFDX: Create and Set Up Project for ISV Debugging' resulted in an error (ERROR running force:mdapi:retrieve: The metadata retrieve operation failed: INVALID_CROSS_REFERENCE_KEY: No package named 'Reset Password' found 
```

@WillieRuemmele  notes
> The bug is how the ISV Debugger is calling the CLI. It seems like it's calling it with an invalid package name ""Reset Password" User Field". I'm not sure how the ISV Debugger generates the list of packages to retrieve, but it seems like there's multiple errors. For instance, the "FinancialForce Consultant Tools" will need to be quoted, or the whole list of packagenames will require quotes around them. Just quickly running a command like that results in a failure

```
 ➜  sfdx force:mdapi:retrieve --packagenames=FinancialForce Consultant Tools                           
ERROR running force:mdapi:retrieve:  Unexpected arguments: Consultant, Tools
```

> it should be `--packagenames="FinancialForce Consultant Tools"`

**Comment by mohanraj-r** [comment]
Re-opening #3618 as it is more relevant to the current issue

**Comment by wsampson-sf** [comment]
Hi team, I spoke about this with @randi274 in [this Slack thread](https://salesforce-internal.slack.com/archives/CEL0K4FRU/p1635869013064100) already, but my teammate and I have still been observing this issue over the past year, and using the workaround provided above (of downgrading to SFDX CLI 7.115.1) in order to avoid the issue. This still appears in the latest SFDX CLI version, running the latest VS Code version and extensions as well.

As before, the main symptom is that package content doesn't appear at all, and we see an error "Apex language server could not provide information about valid breakpoints." when trying to start a debugging session.

![Screen Shot 2022-11-14 at 3 22 27 PM](https://user-images.githubusercontent.com/977092
![Screen Shot 2022-11-14 at 4 02 37 PM](https://user-images.githubusercontent.com/97709283/202050608-f60279bb-9396-47b4-9f6c-54b47b01384a.png)
83/202050598-2330e936-4fd6-470c-9a1b-b5cf7884c1b6.png)

**Comment by daphne-sfdc** [comment]
I tested this in April 2024. I was able to create 2GP managed packages with spaces and single quotes in their names. I was also able to install them into subscriber sandboxes and run the ISV debugger on Salesforce projects created using those packages.

This is no longer a bug, as it cannot be reproduced.
