### ISSUE TITLE
SFDX: Retrieve or Deploy Source in Manifest to Org is missing when I right click the package.xml

### ISSUE THREAD

**Issue by isaac0310** [forcedotcom/salesforcedx-vscode#3629]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by smaddox-sf** [comment]
Please add system info, steps to reproduce and the expected vs. actual outcome.  Closing this issue as we don't have enough info to try to repro it.  Feel free to add the necessary info and reopen this issue and we'd be happy to look into it.
