### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chandraveersinghEcho** [forcedotcom/salesforcedx-vscode#3638]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `53.2.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.62.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\CHANDR~1.SIN\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment]
Duplicate #3198

**Comment by Kulotht** [comment]
<html>
<body>


/flow/Assign_POF
--



</body>
</html>

**Comment by gbockus-sf** [comment]
closing in favor of #3198
