### ISSUE TITLE
SFDX commands not found 

### ISSUE THREAD

**Issue by sarden11037** [forcedotcom/salesforcedx-vscode#3649]
I had a refresh done on our dev org. The refresh cause my token to expire so I needed to do a fresh 'authorize an org'. i logged out of all orgs. Authorized the new org and from there everything broke. All SFDX commands from the palette will show the error display " command xxxx not found). this is for all SFDX commands. If I run the commands from the terminal it just wont work. Tried uninstalling/re-installing the extensions, cli, and vscode itself and still getting the same errors. Tried moving to a different project folder, creating a new project, same problem. Check the environment PATH for Java and apex and those all work.

At this point I am going to have to do a hard windows reinstall to get things working again.

**Comment by sarden11037** [comment]
leaving a screen shot with dev tools errors. maybe someone can make sense of it.
![vscode error](https://user-images.githubusercontent.com/24573854/141911443-ec86775b-26d1-407d-9f60-c2884644a4a7.PNG)

**Comment by jeffb-sfdc** [comment]
@sarden11037 I'll need some more information to go on:
* What version of the Salesforce extension for VisualStudio Code are you running?
* When you run (in a terminal) `sfdx --version`, what do you get?
* When you run (also in a terminal) `sfdx plugins`, what do you get?
