### ISSUE TITLE
SFDX Invoke Function Command not visible on Command Palette

### ISSUE THREAD

**Issue by msaxena8188** [forcedotcom/salesforcedx-vscode#3651]
The SFDX Create/Start/Stop Functions commands are visible however the other commands are not.

**Comment by msaxena8188** [comment]
![image](https://user-images.githubusercontent.com/53609295/142255762-aa655941-6b22-43ff-b767-a06e8cb5859a.png)

**Comment by joshwlewis** [comment]
If you have the function source (`index.js`) open, they will be available in the command pallette. It took me a bit to figure this out. I'd rather have these commands available and throw an error rather than have them hidden. As it is, these commands are not discoverable without deep knowledge.

**Comment by daphne-sfdc** [comment]
Closing this issue as Functions is no longer supported.
