### ISSUE TITLE
Deploy on save fails - %s: File or folder not found

### ISSUE THREAD

**Issue by wrone** [forcedotcom/salesforcedx-vscode#3657]
### Summary

When I press ctrl+s the automatic deployment of a file fails. The terminal shows this error - %s: File or folder not found.

When I click the "SFDX: Deploy This Source to Org" - the file is deployed without errors.

The below both commands also work:
sfdx force:source:deploy -p "force-app\main\default\classes\MyApexClass.cls"
sfdx force:source:deploy -m ApexClass:MyApexClass

![image](https://user-images.githubusercontent.com/9321029/142455176-b6445a41-51a8-41e1-b0c3-3c52be4a3a10.png)

### System Information
$ sfdx version --verbose --json
{
"cliVersion": "sfdx-cli/7.126.0",
"architecture": "win32-x64",
"nodeVersion": "node-v16.13.0",
"pluginVersions": [
"@oclif/plugin-autocomplete 0.3.0 (core)",
"@oclif/plugin-commands 1.3.0 (core)",
"@oclif/plugin-help 3.2.3 (core)",
"@oclif/plugin-not-found 1.2.4 (core)",
"@oclif/plugin-plugins 1.10.1 (core)",
"@oclif/plugin-update 1.5.0 (core)",
"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
"@oclif/plugin-which 1.0.3 (core)",
"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
"alias 1.1.22 (core)",
"apex 0.3.0 (core)",
"auth 1.7.5 (core)",
"config 1.2.46 (core)",
"custom-metadata 1.0.12 (core)",
"data 0.6.4 (core)",
"generator 1.2.1 (core)",
"limits 1.2.3 (core)",
"org 1.9.0 (core)",
"salesforce-alm 53.4.1 (core)",
"schema 1.0.10 (core)",
"sfdx-cli 7.126.0 (core)",
"source 1.3.1 (core)",
"telemetry 1.2.8 (core)",
"templates 52.6.0 (core)",
"trust 1.0.10 (core)",
"user 1.5.2 (core)"
],
"osVersion": "Windows_NT 10.0.19043"
}

**Comment by wrone** [comment]
This is the duplicate of https://github.com/forcedotcom/cli/issues/1283. Not sure where it should be created

**Comment by AnanyaJha** [comment]
Hi @wrone thanks for reporting this - this repo is the correct one for the issue! We have a similar issue open with #3655, can you share whether you're deploying to a sandbox or scratch org?

**Comment by wrone** [comment]
Hi @AnanyaJha,

I'm deploying to a sandbox

**Comment by AnanyaJha** [comment]
Thanks @wrone. Closing this issue out in favor of #3655, duplicate issue
