### ISSUE TITLE
push or deploy on save inop

### ISSUE THREAD

**Issue by Dre2300** [forcedotcom/salesforcedx-vscode#3659]
The Salesforcedx-vscode-core › Push-or-deploy-on-save Setting is giving me the "File or Folder not found" error every time I try to save my source code.  However, I do not receive an error when pushing my source code to my org by right-clicking the class and clicking "sfdx: deploy source to org".

**Comment by rcoringrato-sfdc** [comment]
Duplicate of #3655

**Comment by randi274** [comment]
Thanks for logging this! Closing as a dupe.
