### ISSUE TITLE
Salesforce CLI View does not print sfdx Command for Deploying and Retrieving a Source File

### ISSUE THREAD

**Issue by roger-rivas15** [forcedotcom/salesforcedx-vscode#3662]
### Summary

When we select either "Deploy Source to Org" or "Retrieve a Source from Org" the output window for Salesforce CLI does not print the associated `sfdx` command that is executed.

For other commands the output window for Salesforce CLI does show the associated `sfdx` command.

### Steps To Reproduce:

1.  Select a LWC folder or a file.
2. Right click on the selected item.
3. Choose option: `Deploy Source to Org`

### Expected result

The output window for Salesforce CLI should display the associated `sfdx` command with other info messages.

### Actual result

The output window only display the info of the files that are deployed.

### Additional information

Screenshot: Output Window - Deploy Source to Org
![image](https://user-images.githubusercontent.com/94825028/142824399-8e70aecd-c5a2-454f-bd14-44eeb2a92c44.png)

Screenshot: Output Window - Authorize an Org
![image](https://user-images.githubusercontent.com/94825028/142824694-739636ee-51d6-46b7-8ccf-38775b7dfb1d.png)

**Salesforce Extension Version in VS Code**: v53.4.2

**SFDX CLI Version**: sfdx-cli/7.126.0 win32-x64 node-v16.13.0

**Visual Studio Code Version**: 1.62.2

**OS and version**: Microsoft Windows 10 Enterprise 10.0.18362

**Comment by AnanyaJha** [comment]
Hi @roger-rivas15 thanks for reporting this! The CLI command used to be displayed as part of the output because the Salesforce Extensions were actually running the command in the background. We've recently moved over to a new architecture to calling the APIs directly, so the CLI commands are not directly run anymore. The output now just displays the results of the operation instead of the CLI command. Were you looking for an additional piece of information as part of the output?

**Comment by roger-rivas15** [comment]
Hi Ananya. I have recently started working with Salesforce Platform and was learning to interact with Salesforce CLI. The commands in the output view were helping me out with the learning process. This way I could understand what commands were executed in background and I would get more details of that command from the documentation.

I understand now that the extensions are calling the API directly. But as a beginner the commands did help me a lot with learning salesforce cli. And I assume this may be the case with lot of other programmers.

So, will it be possible to print the predicted command in the output?
