### ISSUE TITLE
Update URL for lwc-dev-server documentation

### ISSUE THREAD

**Issue by banderson5144** [forcedotcom/salesforcedx-vscode#3664]
https://github.com/forcedotcom/salesforcedx-vscode/blob/b805ae040f9c50ebdcaefa719830c884dc6d90d2/packages/salesforcedx-vscode-lwc/src/messages/i18n.ts#L23

Just wanted to let you know this link is broken and I think it should be updated to:

`https://developer.salesforce.com/tools/vscode/en/localdev/set-up-lwc-local-dev`

**Comment by ekapner** [comment]
FYI @sbudhirajadoc

**Comment by randi274** [comment]
Thanks for logging this @banderson5144! 

@sbudhirajadoc when I was looking for the link, I found two more broken links for our Functions docs. Could we fix those in the same PR? 
1. [force_function_start_warning_plugin_not_installed](https://github.com/forcedotcom/salesforcedx-vscode/blob/b805ae040f9c50ebdcaefa719830c884dc6d90d2/packages/salesforcedx-vscode-core/src/messages/i18n.ts#L156)
2. [Developing Salesforce Functions using VSCode](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/docs/_articles/ja/functions/overview.md#resources)

**Comment by sbudhirajadoc** [comment]
Fixed links in PR https://github.com/forcedotcom/salesforcedx-vscode/pull/3665 @ekapner @randi274 Thanks!

**Comment by banderson5144** [comment]
Thanks @sbudhirajadoc when will see this get deployed to the actual cli plugin?

**Comment by randi274** [comment]
Hi @banderson5144 we're on a code freeze this week with the US holiday, so changes won't be available until next week. Cheers!
