### ISSUE TITLE
Facing same issue on creating the salesforce project on the VS code as above mentioned. My System has 8GB RAM

### ISSUE THREAD

**Issue by ppadishala** [forcedotcom/salesforcedx-vscode#3672]
Facing the same issue on creating the salesforce project on the VS code as above mentioned. My System has 12 GB RAM

_Originally posted by @abhishekKapoor14 in https://github.com/forcedotcom/salesforcedx-vscode/issues/3198#issuecomment-850841879_

**Comment by ppadishala** [comment]
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/7603270/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
 Here is the file which is asked by vs code to share while rising the issue

**Comment by AnanyaJha** [comment]
Duplicate #3198
