### ISSUE TITLE
When I try to connect on a Org Receveid this message: Error authenticating with auth code due to: connect ETIMEDOUT

### ISSUE THREAD

**Issue by rnisti** [forcedotcom/salesforcedx-vscode#3673]
When I try to connect on a SandBox, I receive this message: Error authenticating with auth code due to: connect ETIMEDOUT.

And I receive a lot of timeout error messages has a couple of weeks.

**Comment by jeffb-sfdc** [comment]
Hi @rnisti , I don't think this is enough to go on.  Could you provide detailed steps you are doing (explicit step-by-step)?
