### ISSUE TITLE
Invoke and Debug Invoke for functions hidden

### ISSUE THREAD

**Issue by joshwlewis** [forcedotcom/salesforcedx-vscode#3676]
**Is your feature request related to a problem? Please describe.**
As a new user to functions and/or these extensions, the function debug and function debug invoke features are very hard to find. Currently, you have to know to create a `payload.json` (these don't exist by default), then know to look at the top of that file for small text.

**Describe the solution you'd like**
Maybe a command palette option for `SFDX: Function Invoke` and `SFDX: Function Debug Invoke` or similar.

**Describe alternatives you've considered**
- Maybe a command palette option to generate a `payload.json`?
- Perhaps `payload.json` could be scaffolded in to a function repo

**Additional context**
<img width="714" alt="Screen Shot 2021-11-30 at 1 47 30 PM" src="https://user-images.githubusercontent.com/917672/144117634-92144162-4ad3-45f9-9f2e-af374aaaf604.png">

**Comment by jag-sfdc** [comment]
Thanks @joshwlewis. This is good feedback. I'll take it to the team and see if we can prioritize this.

**Comment by diyer** [comment]
Functions is no longer a supported extension. Closing this issue.
