### ISSUE TITLE
Refresh SObject Definitions process doesn't work with scratch org

### ISSUE THREAD

**Issue by k010c1232** [forcedotcom/salesforcedx-vscode#3679]
### Summary

Refresh SObject definitions process doesn't work in my scratch org.

### Steps To Reproduce:

1.  Run SFDX: Refresh SObject Definitions

### Expected result
Get SObjects Definitions correctly.

### Actual result
```error
Command 'SFDX: Refresh SObject Definitions' resulted in an error (Cannot convert undefined or null to object)
```
### Additional information

Screenshot: (https://a.cl.ly/DOuogJzv)

**SFDX CLI :sfdx-cli/7.81.0 darwin-x64 node-v14.2.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-mobile 0.4.1
@salesforce/lwc-dev-server 2.7.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.3 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.6.0 (core)
├─ schema 1.0.1 (core)
├─ templates 50.1.0 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 50.6.0 (core)
sfdx-cli 7.81.0 (core)

**OS and version**:
OS: macOS
version: 11.0.1 (20B29)

**Comment by jag-sfdc** [comment]
@k010c1232 @troveryor - Do you still see this issue? We have made several fixes in this area with our recent releases and I'm not able to repro this issue. Thanks!
