### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by patrikfedor** [forcedotcom/salesforcedx-vscode#3686]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `53.4.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 21049,
		"activateCallTime": 21,
		"activateResolvedTime": 32113,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by patrikfedor** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 21049,
		"activateCallTime": 21,
		"activateResolvedTime": 32113,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by AnanyaJha** [comment]
Duplicate #2410
