### ISSUE TITLE
TSLint is deprecated

### ISSUE THREAD

**Issue by dschach** [forcedotcom/salesforcedx-vscode#3687]
https://github.com/forcedotcom/salesforcedx-vscode/blob/8d521684064739029dc64d2939ee843c5797a669/.vscode/extensions.json#L10

https://marketplace.visualstudio.com/items?itemName=eg2.tslint

**Comment by jeffb-sfdc** [comment]
This is known issue, and we have a work item in our backlog for this.

**Comment by diyer** [comment]
Closing this as this is done. Thank you @peternhale
