### ISSUE TITLE
not stopping on breakpoint for javascript function

### ISSUE THREAD

**Issue by jjsfdc** [forcedotcom/salesforcedx-vscode#3693]
### Summary

"Debug Invoke" of my sample JSON payload invokes locally running JS Function, but doesn't stop on my breakpoint.

### Steps To Reproduce:

1.  sf generate project -n SomeProject
2. cd SomeProject
3. sf generate function -l javascript -n somefn
4. code .
5. edit index.js so function body is just one line: return "hello world";
6. click in left edge of editor to set a breakpoint on this return line
7. right click and choose "SFDX: Start Function"
8. upon launch, create a json file within the "functions/somefn" directory and save
9. click "debug invoke" link at top of editor page

### Expected result

debugger would pause on the breakpoint I set

### Actual result

function is invoked, but execution does not stop on the breakpoint.

### Additional information

**Salesforce Extension Version in VS Code**: 53.7.0

**SFDX CLI Version**: node-v16.13.1

**OS and version**: Mac OS Big Sur version 11.6.1

**Comment by randi274** [comment]
I don't believe this was in the scope of the original add-on for functions, but is something we should consider adding going forward.

**Comment by gbockus-sf** [comment]
Associated Work Item: [W-10738230](https://gus.lightning.force.com/a07EE00000rEzczYAC)
