### ISSUE TITLE
Missing support for collections in type field

### ISSUE THREAD

**Issue by h-nguyen-star** [forcedotcom/salesforcedx-vscode#3694]
### Summary

Trying to configure LWC screen for a flow:
https://developer.salesforce.com/docs/component-library/bundle/lightning-flow-support/documentation

I was able to push the LWC component successfully to the org but in VScode is complaining about the following errors:
(1) cvc-datatype-valid.1.2.3: 'String[]' is not a valid value of union type 'propertyTypeAttr'.xml(cvc-datatype-valid.1.2.3)
(2) cvc-attribute.3: The value 'String[]' of attribute 'type' on element 'property' is not valid with respect to its type, 'propertyTypeAttr'.xml(cvc-attribute.3)

I am not seeing the collection as a supported type under the documentation
https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_configuration_tags

### Steps To Reproduce:

Here is my current xml:
`<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>52.0</apiVersion>
    <isExposed>true</isExposed>
    <masterLabel>List View</masterLabel>
    <description>List View</description>
    <targets>
        <target>lightning__FlowScreen</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightning__FlowScreen">
            <property name="recordIds" type="String[]" label="Ids" description="list of ids"/>
        </targetConfig>
    </targetConfigs>
</LightningComponentBundle>`

I can push to org successfully but am getting incorrect validation errors.

I believe xml schema validation coming from the below resource needs to be expanded to support []’s in the type field.
https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-lwc/resources/static/js-meta.xsd#L240

### Expected result

Successful push without any validation errors

### Actual result

Successful push but have validation errors

### Additional information

![Screen Shot 2021-12-10 at 10 24 25 AM](https://user-images.githubusercontent.com/77340557/145623417-05d40253-bf8b-49e6-937d-c285a79462f4.png)

**Salesforce Extension Version in VS Code**:
v53.7.0
**SFDX CLI Version**:
sfdx-cli/7.130.1 darwin-x64 node-v17.0.1
**OS and version**:
macOS Catalina 10.15.7

**Comment by randi274** [comment]
Hi @h-nguyen-star thanks for logging this! What's the use case that you're hoping to achieve with the String collection? Salesforce doesn't officially support this type yet, as you've noted here, but I was also able to deploy the collection. However, it doesn't seem to behave properly for me in the Flow UI.

**Comment by kartik571995** [comment]
Hi Salesforce Team, I also face the same issue. My use case is to create the "Display Flow Stages By Adding a Progress Indicator to a Flow Screen"[https://developer.salesforce.com/docs/atlas.en-us.236.0.lightning.meta/lightning/components_config_for_flow_screens_stages.htm] in LWC.
Here I have to pass the stages as array "stages[]" but I can't use it.
