### ISSUE TITLE
Unable to download CustomObject source after update to v53.7.0

### ISSUE THREAD

**Issue by MooseAteJack** [forcedotcom/salesforcedx-vscode#3695]
### Summary

I updated to v53.7.0 and now in the Org Browser there are only icons to refresh Custom Objects folder and each object in that folder. The icon/button to view or download any individual object is missing. I checked on one of my teams devices and they could download individually but were on a previous version. Once they had updated they had the same issue I do.

I not that there is a new ability to browse fields in objects - so cool.

### Steps To Reproduce:

1.  Update extension to 53.7.0
1.  Set a default org
1.  Navigate to Org Browser/Custom Objects
1.  Hover mouse over a custom object

### Expected result

I am able to click a link/button to download that objects source

### Actual result

There is no button

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: 53.7.0

**SFDX CLI Version**: sfdx-cli/7.130.1 win32-x64 node-v16.13.1

**OS and version**: Win10

**Comment by MooseAteJack** [comment]
![2021-12-13 11_40_48-moe-taku-bau - Visual Studio Code](https://user-images.githubusercontent.com/6495954/145732543-fc340331-559a-49aa-b546-a8d4f5abc934.png)

**Comment by AnanyaJha** [comment]
Hi @MooseAteJack thanks for reporting this! Our team was able to reproduce this behavior, so we've filed a bug for it and will get started on it soon. We'll post all updates on this thread, thanks!

**Comment by MooseAteJack** [comment]
Brillo, thank you.
Not sure if it is related but also having an issue with Layouts. I can't see any at all in the browser:
![2021-12-15 09_36_26-moe-taku-bau - Visual Studio Code](https://user-images.githubusercontent.com/6495954/146075797-b24beba2-7a85-4b4a-ba7c-81de4f2d1795.jpg)
.

**Comment by DT-Forcology** [comment]
That issue occurs in the later versions of SFDX. We found reverting to 7.124 fixed the above issue

**Comment by RitamAgrawal** [comment]
Hi @MooseAteJack  thank you for reporting this! It's a different issue and we will be filing a bug for this one.

**Comment by RitamAgrawal** [comment]
@MooseAteJack Fix for the Layout bug: https://github.com/forcedotcom/salesforcedx-vscode/pull/3701

**Comment by RitamAgrawal** [comment]
@MooseAteJack This issue has been resolved with https://github.com/forcedotcom/salesforcedx-vscode/pull/3697
