### ISSUE TITLE
SFDX: Start Function containerless/local support

### ISSUE THREAD

**Issue by joshwlewis** [forcedotcom/salesforcedx-vscode#3696]
**Is your feature request related to a problem? Please describe.**
Docker Desktop will require a paid subscription on January 31, 2022. The existing `SFDX: Start Function` requires Docker Desktop to run on Windows and Mac. 

**Describe the solution you'd like**
The `@heroku/functions-core` package provides an API for invoking functions on the user's system. Docker Desktop is not leveraged with this API, but it has nearly identical experience. I'd suggest a new command palette entry, something like `SFDX: Start Function Local` that leverages the containerless API. This would basically mirror the approach taken by the CLI with `sf run function start local`.

**Describe alternatives you've considered**
`SFDX: Start Function` switches from using containers to containerless. However the container version of the command is useful for a number of people.

**Additional context**
The transition plan from container to local for the CLI is [here](https://salesforce.quip.com/CnpKAFNnfZBC), it may make sense to mirror this approach if possible.

**Comment by AnanyaJha** [comment]
Hi @joshwlewis - we've added support for `SFDX: Start Function` in the containerless version. Please let us know if you see otherwise.
