### ISSUE TITLE
Can not retrieve the email templates from the org browser. 

### ISSUE THREAD

**Issue by anshumishra07sstk** [forcedotcom/salesforcedx-vscode#3702]
### Summary

Clicking on an email template from the org browser doesn't give an option to retrieve the code.

### Steps To Reproduce:

1.  Connect to Default org (My SF sandbox)
1.  Go to Org Browser and look for Email Templates Metadata.
1. Choose the correct folder. It shows the email template name.

### Expected result

_After right clicking the email template name, there should be an option to retrieve the code.
_And selected email should be added to the branch.

### Actual result

_Email Template name doesn't show an option to retrieve the code.
_Nothing gets added to the branch. There is no option to pull the email template into the branch for deployment.

### Additional information

_Feel free to attach a [screenshot_.](url)

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by anshumishra07sstk** [comment]
https://www.loom.com/share/61ebc6b3ca9b46a08edb725bd2349e1f 

The org browser doesn't retrieve the email templates and the explorer just shows email template folders but not the actual templates under "email" metadata.

Please take a look and if possible schedule a call to fix this issue. Thank you!

**Comment by AnanyaJha** [comment]
Hi @anshumishra07sstk thanks for reporting this! Are you seeing this behavior with any other metadata types in the org browser? Could you also share what version of the Salesforce Extensions for VS Code you're using? This can be found in the Extensions Marketplace, thanks!

**Comment by anshumishra07sstk** [comment]
Hi Ananya,

Sorry I couldn't reply earlier.

I see this problem with other data types too.
Today I added a new field in an object and when I opened VS Code Org
Browser, I saw that field but after doing the right click, there was no
option to retrieve that field so I retrieved the object itself. That adds
all the changes to my new branch.

However, to add all those changes in the branch, choose mine and discard
others; makes the whole process too time consuming.
But at least that option works for other metadata but there is nothing for
email templates deployment.


[image: image.png]

I will appreciate it if you can schedule a call and help me fix this issue.
I will be available from 3:00-5:00 PM EST today. If that doesn't work for
you, please let me know.

Thank you!

Regards,
Anshu Mishra
CRM Administrator, Global Contact Center Operations


Empire State Building
350 Fifth Avenue, 21st Floor
New York, NY 10118
www.shutterstock.com

**Comment by RitamAgrawal** [comment]
@anshumishra07sstk This issue is consistent with components under folders of metdatatypes like Email Templates, Dashboards, Documents and Records. If you come across any other metadata types please let us know. Thank you.

**Comment by anshumishra07sstk** [comment]
Hi Ritam,

Thank you for your response. I have a few questions though:

- What do you recommend to deploy email templates and other metadata
types that can not be retrieved from the org browser?
- Can we deploy the Salesforce Support Process through VS Code? I couldn't
find anything for that.
- Like I said in my previous email, I don't see the option to retrieve the
source when I right click on any metadata.
- ex:
- Created a new field in opportunity Object.
a.) It is visible in the org browser but does not go to the branch when I
retrieve the whole object (I don't have the option to retrieve just a
field).
b.) It's visible in the explorer too but there is no option to stage it.
C.) I am stuck here as there is no option to add this new field to add to
the branch for deployment.

Please let me know if we can schedule a call tomorrow. It will be quicker
than having lots of emails going back and forth.
Thank you!

[image: image.png]
-


Regards,
Anshu Mishra
CRM Administrator, Global Contact Center Operations


Empire State Building
350 Fifth Avenue, 21st Floor
New York, NY 10118
www.shutterstock.com

**Comment by randi274** [comment]
This has been fixed with the latest release of the extensions, 54.6.1 - let us know if you encounter any additional issues!
