### ISSUE TITLE
Be able to configure the path to the SFDX CLI as a VS Code setting

### ISSUE THREAD

**Issue by mcartoixa** [forcedotcom/salesforcedx-vscode#374]
### Summary
Right now the path to the SFDX CLI **must** be added to the *%PATH%* (I'm on Windows) before starting VS Code. I like to isolate my development environments as much as possible and thus refrain from doing that as much as possible.

I think it would be nice if the path to the SFDX CLI **could** be specified as a setting, like the path to Java already is (*salesforcedx-vscode-apex.java.home*).

**Comment by vazexqi** [comment]
@mcartoixa - What about the case of the embedded terminal in VS Code. Do you use that? And do you currently seed that with the proper %PATH%?, perhaps using `terminal.integrated.env.windows` with https://code.visualstudio.com/docs/getstarted/settings#_default-settings?

If we make it a setting, we should also somehow propagate that over to the embedded terminal.

**Comment by mcartoixa** [comment]
@vazexqi Yes, I usually use the `terminal.integrated.shellArgs.windows` in each project settings to launch a custom batch file that takes care of the environment variables. There is a confirmation popup the first time but I can live with that.

Automatic addition to the terminal would be great, or maybe create a specific terminal dedicated to SFDX (something like https://stackoverflow.com/a/44592824/8696).

**Comment by ntotten** [comment]
This seems to be an edge case. I am not saying it isn't valuable, but I haven't heard other asking for it. This is something we would be happy to accept a pull request for.
