### ISSUE TITLE
SFDX: Update Checkpoints in Org fails with error Unable to retrieve OrgInfo : undefined

### ISSUE THREAD

**Issue by pierrepost** [forcedotcom/salesforcedx-vscode#3745]
After toggling a checkpoint in vscode, I try to update checkpoint in the connected org, but it fails : 
_SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
Unable to retrieve OrgInfo : undefined
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again._

Same error with latest version of sfdx : sfdx-cli/7.132.0 win32-x64 node-v16.13.1
VSCode version 1.63
Salesforce Extension Pack v53.8.1
openjdk version "11.0.13" 2021-10-19

**Comment by AnanyaJha** [comment]
Thanks for reporting this @pierrepost! Is this the error from the output window? 
`SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
Unable to retrieve OrgInfo : undefined
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again.`

Could you paste any other error messages you see in the output window?

**Comment by pierrepost** [comment]
Yes, this is the full message displayed in the output window.

**Comment by pierrepost** [comment]
This problem may be a consequence of an other problem, loged in [https://github.com/forcedotcom/salesforcedx-vscode/issues/3681](issue 3681)

When I try to connect to my playground org ("SFDX authorize an org" palette command), the output shows that the CLI does the job, but still it ends up with an error. This may prevent the update of checkpoints (despite the fact that the push code to org works).
_Starting SFDX: Authorize an Org
11:04:29.483 sfdx force:auth:web:login --setalias VSCodePlayground --instanceurl https://login.salesforce.com --setdefaultusername
Successfully authorized xxx@yyy.com with org ID zzz
11:05:16.91 sfdx force:auth:web:login --setalias VSCodePlayground --instanceurl https://login.salesforce.com --setdefaultusername
ended with exit code 1_

**Comment by randi274** [comment]
I agree, it looks like this all stems from the other problem you have logged with 3681. If you run the command `SFDX: Open Default Org`, does the org open, and do you receive the same error?

**Comment by pierrepost** [comment]
Yes, the org opens

**Comment by julianperezpesce** [comment]
I have this same problem, any solution?

**Comment by randi274** [comment]
@pierrepost are you still facing this issue? If so, I wanted to ask what error you get when you run `sfdx force:org:display -u xxx@yyy`, as I believe we're calling out to the CLI to get this information.

**Comment by prash34** [comment]
Yes I have experiencing the same issue
