### ISSUE TITLE
SFDC: Execute Anonymous Apex with Editor Contents command not found

### ISSUE THREAD

**Issue by pogilvie** [forcedotcom/salesforcedx-vscode#3753]
### Summary

The following command runs fine.

```
sfdx force:apex:execute -f scripts/apex/character.apex -u dev
```

But attempting to run `character.apex` from vscode with the extension pack installed results in the following error.

<img width="262" alt="vscode-error" src="https://user-images.githubusercontent.com/628688/148786690-4232fd32-e53f-45b7-a9f1-39bbf20e7596.png">

This has been working.  I recently updated the cli to latest.  Perhaps it's related to that?

### Steps To Reproduce:

1.  command-shift-p .SFDX: Execute Anonymous Apex with Editor Contacts

### Expected result

attempts to run anonymous apex on currently connected org
### Actual result

error displayed above.   (looks like command is missing?)
### Additional information

see screen shot

See above 
**Salesforce Extension Version in VS Code**:
v53.12.0

**SFDX CLI Version**:
sfdx-cli: Updating CLI... already on latest version: 7.132.0-6621068

**OS and version**:
Darwin falcon.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:05 PST 2021; root:xnu-7195.141.14~1/RELEASE_ARM64_T8101 arm64

**Comment by randi274** [comment]
@pogilvie are you able to use the Codelens in VS Code to run the command as well? (New feature as of a few releases ago). I updated the CLI and was able to run the command ok from there. Can you also try a full reboot of VS Code?
<img width="317" alt="Screen Shot 2022-01-10 at 10 27 50 AM" src="https://user-images.githubusercontent.com/9795193/148793584-d5df2c27-6fae-4b13-a75a-4cd52ed44533.png">

**Comment by pogilvie** [comment]
I would love to try the new button if it ever appears for me.

**Comment by randi274** [comment]
The new button is pretty great! It does the same as running the command, including executing only a highlighted portion of the code - hopefully we can get it working for you soon! Is the Apex Language Language server running correctly? You should be able to see errors for that under Output > Apex Language Server in the picklist, or under Help > Toggle Developer Tools, and also can tell if you're not getting any hover or completion assistance (also recently added to anon apex files).

**Comment by pogilvie** [comment]
@randi274 I'm missing the language server from my menu
<img width="374" alt="menu" src="https://user-images.githubusercontent.com/628688/148854490-301c0459-fbfb-403c-bbb7-9c7956d4017d.png">

**Comment by pogilvie** [comment]
<img width="528" alt="java" src="https://user-images.githubusercontent.com/628688/148854759-45b49967-3f9b-488e-9f06-30f2f03f7d25.png">

my Java is here:
```
peter::~-> which java
/opt/homebrew/opt/openjdk@11/bin/java
```

Would setting $JAVA_HOME help?

```
peter::~-> echo $JAVA_HOME

```

**Comment by pogilvie** [comment]
Thank you very much.  Seems like the language server not running it probably the problem.   I'm attached to my current homebrew java because it's ARM native

```
peter::~-> file /opt/homebrew/opt/openjdk@11/bin/java
/opt/homebrew/opt/openjdk@11/bin/java: Mach-O 64-bit executable arm64
```

**Comment by pogilvie** [comment]
Thank you for pointing me on the right path @randi274!  Everyone was solve with a setting update.  I'm so glad that I don't need to maintain two java installations.

This documentation is clear:  https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup#:~:text=It%20requires%20an%20installation%20of,environment%20variable%20on%20your%20computer.
<img width="408" alt="working" src="https://user-images.githubusercontent.com/628688/148973656-f807bf78-bd8f-43ee-8a7e-ed47719fa8aa.png">

**Comment by pogilvie** [comment]
<img width="768" alt="settings" src="https://user-images.githubusercontent.com/628688/148973753-a865e5bd-18a6-419f-9cb0-c39321551521.png">

**Comment by randi274** [comment]
Glad the docs were able to resolve the issue, and thanks for adding your fix! Enjoy the new Execute Anonymous Apex button 😄

**Comment by pogilvie** [comment]
I really am enjoying the execute anonymous apex button!
