### ISSUE TITLE
Trailhead issues

### ISSUE THREAD

**Issue by tanveer263** [forcedotcom/salesforcedx-vscode#3757]
### Summary
[https://trailhead.salesforce.com/content/learn/projects/quick-start-lightning-web-components/create-a-hello-world-lightning-web-component](url)
_Short summary of what is going on or to provide context_.
![image](https://user-images.githubusercontent.com/65210787/148902184-ae2fecc0-f703-4d0b-ae06-69b7b93531b6.png)
 
I already added "helloWorld" to my home page but It's not completing.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result
_successful completion_.

### Actual result

_Make sure you add the 'helloWorld' Lightning web component to the default Home page._.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by tanveer263** [comment]
Hi @AnanyaJha,  Can you please help me regarding this issue.
thanks

**Comment by AnanyaJha** [comment]
Hi @tanveer263 could you provide more details on what version of the Extensions you're using? This can be found by searching for Salesforce in the Extension Marketplace on the left sidebar.

**Comment by tanveer263** [comment]
Hi @AnanyaJha I am using this version of Salesforce Extension Pack ( v53.12.0 ) and Salesforce CLI Integration (v53.12.0).
anything else you need know please let me know.

**Comment by AnanyaJha** [comment]
Thanks @tanveer263 can you share what specific issue you're facing? You mentioned you added 'Hello World' to the home page but it's not completing. What exactly are you having trouble completing?

**Comment by tanveer263** [comment]
Hi @AnanyaJha whenever I  click on deploy the org got this errors : SFDX: Deploy Source to Org failed to run and error authenticating with the refresh token due to: expired access/refresh token.
by the way thanks for your quick response and help. I will trying some other ways to fix it.

**Comment by tanveer263** [comment]
Thanks @AnanyaJha, You have been so supportive. I am very much looking forward to work with you on new issues and currently working on Plateform Developer 2 trailhead modules.

**Comment by AnanyaJha** [comment]
Of course no problem @tanveer263. Let us know if you face any other issues and feel free to [leave a review for our Extensions](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode&ssr=false#review-details) on the VS Code Marketplace!
