### ISSUE TITLE
Salesforce SOQL Builder Toggling Issue

### ISSUE THREAD

**Issue by RugerSR762** [forcedotcom/salesforcedx-vscode#3762]
### Summary

The SOQL Builder stopped working.  I can no longer toggle between the builder and the code viewer.

### Steps To Reproduce:

1. Open .soql file within VSCode
2. File opens in code view
3. When clicking on the toggle to open the builder there is an error:

<img width="204" alt="vscode_soql1" src="https://user-images.githubusercontent.com/48356164/149404679-59e7ad4e-9e2f-4db3-b3b0-3d653ec8c14c.png">

### Expected result

Able to toggle between code viewer and builder.

**Salesforce Extension Version in VS Code**:  v53.13

**SFDX CLI Version**: v53.13

**OS and version**: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎9/‎30/‎2021
OS build	19042.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by randi274** [comment]
@RugerSR762 do you see any errors in the Output panel with 'SOQL Language Server' selected?
<img width="1264" alt="Screen Shot 2022-01-14 at 11 39 40 AM" src="https://user-images.githubusercontent.com/9795193/149551966-80a4b9a3-2ad8-4f48-a6da-1386d818d0db.png">
