### ISSUE TITLE
@TestVisible properties erroneously reports as "not visible." 

### ISSUE THREAD

**Issue by brianmfear** [forcedotcom/salesforcedx-vscode#3768]
### Summary

We have a unit test data factory that has a bunch of `@TestVisible` properties, which appear as warnings in the problems tab, even though the code successfully deploys. While this bug does not stop developing, it clogs up the problems tab with warnings that are incorrect. It would be nice if this bug was fixed.

### Steps To Reproduce:

1. Create a class called TestDataFactory, with a `@TestVisible` private property.
1. Create a class called UnitTest, with a method that attempts to access the private property from step 1.
1. The code should deploy, but a severity 4 warning will appear in the problems tab. 

### Expected result

No error/warning should be produced when a `@TestVisible` property is accessed from a unit test.

### Actual result

```json
[{
  "resource": "...UnitTest.cls",
  "owner": "_generated_diagnostic_collection_name_#X",
  "severity": 4,
  "message": "Method is not visible: void TestDataFactory.loadData()",
  "startLineNumber": 6,
  "startColumn": 21,
  "endLineNumber": 6,
  "endColumn": 36
}]
```

### Additional information

N/A

**Salesforce Extension Version in VS Code**:

Id: salesforce.salsforcedx-vscode
Version: 53.13.0

**SFDX CLI Version**:

sfdx-cli/7.132.0 win32-x64 node-v16.13.1

**OS and version**:

Microsoft Windows [Version 10.0.19042.1466]

**Comment by randi274** [comment]
Thanks for the feedback - we're also tracking this on #1835, so I'm going to close this one to keep the conversation there.
