### ISSUE TITLE
SFDX: Retrieve Source from Org not retrieving any data - no response even after 30 min

### ISSUE THREAD

**Issue by nkundeti** [forcedotcom/salesforcedx-vscode#3774]
### Summary

"SFDX: Create Project with Manifest" failed to retrieve from  source - no response even after 30 min.

### Steps To Reproduce:

Step 1:  opened Visual Studio Code and  create project with manifest ( SFDX: Create Project with Manifest)
Step 2:  changed login URL to https://test.salesforce.com in sfdx-project.json file
Step 3:  set the environment variables http_proxy and https_proxy also in setting.json file
Step 4: Authorize the sandbox by using 'SFDX: Authorize an Org'  - ( successfully authorized).
Step 5: right clicked on package.xml under manifest folder and selected 'SFDX: Retrieve Source in Manifest from Org"
 Nothing gets retrieved event after 30 min, also tried with only one apex class in  package.xml file.

### Expected result
apex classes should be retrieved from the source

### Actual result
 Nothing gets retrieved event after 30 min, also tried with only one apex class in  package.xml file.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: v53.13.0

**SFDX CLI Version**: sfdx-cli/7.133.0 win32-x64 node-v16.13.1

**OS and version**: Windows 10 Enterprise

**Comment by AnanyaJha** [comment]
Hi @nkundeti! Unfortunately, there isn't a lot we can do here to help out. If you have already followed the [instructions here,](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm) which it sounds like you have. Generally, the issue is something that you will have to work out with your IT department.

**Comment by jeffb-sfdc** [comment]
@nkundeti are you able to login and authenticate using the command line interface (`sfdx auth:web:login`)?
