### ISSUE TITLE
Extension using 100% CPU for no reason

### ISSUE THREAD

**Issue by tiagoshadow** [forcedotcom/salesforcedx-vscode#3775]
- Hi, So I've been using Salesforce DX extension for a while, and yesterday I've noticed that my computer is very slow, my PC as top-notch specs, so never seen him this slow... When I open my Task Manager there it was one process from VSCode was taking all the CPU, I terminated it to check what was happening and the output said that this extension was closed or stopped working.
- I am a Salesforce Developer currently working with only LWC, this is affecting my work as I cannot do anything like this, please help

Steps To Reproduce:

1.  Open any Salesforce Project Folder
2. Wait until it gets synced
3. Notice the CPU usage is 100%

Additional information:

![Screenshot_1](https://user-images.githubusercontent.com/45994793/150315299-b9d4f122-79b3-474b-8e4d-5ad5d1479fc8.png)
![Screenshot_2](https://user-images.githubusercontent.com/45994793/150315302-f698090c-55e0-4095-99fb-8309191a5b66.png)

Salesforce Extension Version in VS Code: v53.14.1

SFDX CLI Version: sfdx-cli/7.133.0 win32-x64 node-v16.13.1

OS and version: Windows 11

**Comment by tiagoshadow** [comment]
Hi, bit disappointed that no one seems to respond to the issue, I've identified that the problem is from 'SLDS Validator' after disabling it CPU is back to normal usages. If anyone has the same problem you can either disable it or terminate process, the rest of the extensions will work fine

**Comment by AnanyaJha** [comment]
Hi @tiagoshadow sorry about the delay getting to your issue! Are you seeing this usage spike every time the extensions are launched?

**Comment by tiagoshadow** [comment]
Hi @AnanyaJha, yes I had to disable the 'SLDS Validator' extension today so I don't have to terminate the process every time I launch the VS Code in a sfdx project folder

**Comment by jeffb-sfdc** [comment]
@tiagoshadow When you run:
`sfdx --version`
...what is reported?

And when you run:
`sfdx plugins`
...what is reported?

Also, which version of Java are you running?

**Comment by NicholasHolly** [comment]
Running into the same issue with SLDS validator creating a java process that pushes CPU usage to 100%. I spent a couple hours trying to find the root cause and even went nuclear with a fresh OS install.

Terminating the process resolves the issue but must be done on every VS Code instance launch unless you disable the extension.

Using sfdx-cli vers. 7.136.2, tested with Azul JDK version 11 and 8 with the same results. No sfdx plugins installed after the OS wipe.

**Comment by lirondco** [comment]
Also running into the same issue. It's running Java several times in the process and I have to terminate them each time.
It hasn't happened until recently. Not sure if it's related to the recent VSCode update. I had to deactivate SLDS Validator for now.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/60845154/153523797-de8d9866-f3d8-43bd-a141-e07cf0dd960e.png">

**Comment by mohanraj-r** [comment]
This issue will be tracked in https://github.com/forcedotcom/salesforcedx-vscode/issues/3198
