### ISSUE TITLE
Unable to debug lightning-language-server extensions.

### ISSUE THREAD

**Issue by dbreese** [forcedotcom/salesforcedx-vscode#3777]
### Summary

Checked out and followed directions to build and link both https://github.com/forcedotcom/lightning-language-server.git and https://github.com/forcedotcom/salesforcedx-vscode.

After building successfully and launching the app with extension, I can't set any breakpoints - any breakpoints I add are shown as “Unbound breakpoint” in VSCode as in the following image.

<img width="911" alt="Screen Shot 2022-01-12 at 12 10 20 PM" src="https://user-images.githubusercontent.com/2682021/150402321-edd7bdcd-ee08-4a02-b650-cf5235b609f3.png">

### Steps To Reproduce:

1. Checkout and follow directions in README.md here https://github.com/forcedotcom/lightning-language-server.git
1. Attempt to launch the app and extensions.
2. Attempt to set a breakpoint in any code in the lwc-language-server package code.

### Expected result

Breakpoints should work.

### Actual result

"Unbound breakpoint" is shown in VSCode, so it is not possible to use debugger and have to resort to console.logs().

**Comment by randi274** [comment]
lightning-language-server is now debuggable!
