### ISSUE TITLE
sfdx cli ENOENT error issue

### ISSUE THREAD

**Issue by samirkumar75** [forcedotcom/salesforcedx-vscode#3781]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by samirkumar75** [comment]
SFDX cli error ENOENT issue in my laptop....
how can resolve ENOENT issue

**Comment by AnanyaJha** [comment]
Hi @samirkumar75 thanks for reporting this. Can you give us some more information on what extensions version you're currently on? This can be found by clicking on the marketplace icon on the left sidebar. Thanks!
