### ISSUE TITLE
SFDX: Get Apex Debug Logs not working

### ISSUE THREAD

**Issue by prateekamana** [forcedotcom/salesforcedx-vscode#3783]
### Summary

I tried running SFDX: Get Apex Debug Logs but it says command not found, it has been so for a few months, I have been on the latest version of the extensions. I tried it with Apex Replay Debugger on, and off, neither worked.

### Steps To Reproduce:

1. Ctrl + Shift + P
1. SFDX: Get Apex Debug Logs
1. The error attached in the screenshot appears

### Expected result

A menu like this should have been visible
![image](https://user-images.githubusercontent.com/41776584/151342195-23a6074d-949f-44d0-a385-fa044711cd61.png)

### Actual result

Command not found error appears
![image](https://user-images.githubusercontent.com/41776584/151341388-72c5c750-ff17-49b6-b702-92be734a2b43.png)

### Additional information

**Salesforce Extension Version in VS Code**: 53.14.1

**SFDX CLI Version**: sfdx-cli/7.134.0 linux-x64 node-v16.13.2

**OS and version**: Linux Mint 20 x86_64

**Comment by prateekamana** [comment]
Additional Information: All other commands such as open org, authorize orgs etc. are working fine.

**Comment by randi274** [comment]
Hi @prateekamana are you able to run Apex tests from VS Code? Also, can you go to the Output section and Select 'Apex' from the dropdown menu, to see if you see any particular errors? (That panel should open automatically when you run a test too).

**Comment by prateekamana** [comment]
Hi @randi274 I can't run Apex Tests from VSCode either and as you can see, the output section shows nothing upon trying to run it
![image](https://user-images.githubusercontent.com/41776584/151390864-e0d70c27-0b30-40ce-acaa-cc05951a6297.png)

**Comment by prateekamana** [comment]
One of my friends is facing this issue even on a windows machine.

**Comment by randi274** [comment]
Thanks for details on this - let me get this set up on my windows box and see if I can reproduce there.

**Comment by prateekamana** [comment]
bump

**Comment by randi274** [comment]
Thanks for your patience (my windows testing machine is truly terrible; a great testing environment to test older machine functionality, but awful for quick responses). I did a [fresh install](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup#adoptopenjdk) of the AdoptOpenJdk/now-Adoptium jdk 11, added it to my path, did a reboot of VS Code, and the run test button appears and runs the test successfully. Can you share the path that you're using in the VS Code java.home setting, both for Linux and perhaps the path your friend is using for Windows? The path I used was the default suggested by the installer: C:\\Program Files\\Eclipse Adoptium\jdk-11.0.14.9-hotspot

**Comment by prateekamana** [comment]
My jdk version is: openjdk 17.0.1 2021-10-19
I had not set the java.home in setting.json previously but I tried doing it and after restarting vscode, I still couldn't use the get apex debug logs command. 
![image](https://user-images.githubusercontent.com/41776584/153135441-9da3b6ee-185d-4c93-b664-35fe50f24e16.png)
(I also tried using java.home instead of xml.java.home for the setting key)

**Comment by prateekamana** [comment]
Ah, my bad, I opened your link and set the java.home according to the instructions provided there as shown in the image, and now I can get apex logs. So I just had to set the JDK path for these to work. Thanks @randi274
