### ISSUE TITLE
Running SFDX: Authorize an Org -> it's keep loading not opening browser to authorize, i have tried checking default browser as well but not working.

### ISSUE THREAD

**Issue by kranthireddy338** [forcedotcom/salesforcedx-vscode#3787]
Running SFDX: Authorize an Org ==> it's keep loading not opening a browser to authorize, I have tried checking the default browser as well but not working.
![Capture](https://user-images.githubusercontent.com/40160491/151704223-505dd1fd-cd23-438f-a9ee-9b4154c8c1b5.JPG)

**Comment by prateekamana** [comment]
What are the OS, vscode extension version, sfdx-cli version?
