### ISSUE TITLE
Generating a manifest file in Org Browser results in an error

### ISSUE THREAD

**Issue by jeffb-sfdc** [forcedotcom/salesforcedx-vscode#3801]
### Summary

Generating a manifest file in Org Browser results in an error

### Steps To Reproduce:

1. Switch to the Org Browser
2. Navigate to Apex Classes
3. Selected a few classes
4. Right-click, and select “SFDX: Generate Manifest File”

### Expected result

If the new Generate Manifest File command supports the Org Browser, I'd expect it to run

If it's not support, I'd expect the command to not be available.

### Actual result

“Error running command sfdx.create.manifest: %s: File or folder not found. This is likely caused by the extension that contributes sfdx.create.manifest.”

**Comment by jeffb-sfdc** [comment]
Git2Bot didn't automatically run.  The ticket I created to track this is https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000kuvcUYAQ/view

**Comment by gbockus-sf** [comment]
Fixed
