### ISSUE TITLE
Support for newer Java version

### ISSUE THREAD

**Issue by hadkins0617** [forcedotcom/salesforcedx-vscode#3804]
**Is your feature request related to a problem? Please describe.**
My company is requiring the latest version of Java (via Zulu 17) as a result of a security scan (I assume the Log4J security issue). As a result, I get the following error message related to the Apex plugin in the Salesforce Extension Pack - An unsupported Java version was detected. Download and install [Java 8](https://java.com/en/download/) or [Java 11](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html) to run the extensions. For more information, see [Set Your Java Version](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup).

**Describe the solution you'd like**
Update the Extension pack to support newer versions of Java.

**Describe alternatives you've considered**
At this point I have no alternatives in using this specific piece of the Extension pack.

**Comment by mohanraj-r** [comment]
@hadkins0617 Thank you for reporting the issue. We are prioritizing it in our upcoming sprint and aiming to get it done by end of March.

**Comment by randi274** [comment]
Version 17 is now supported 🎉
