### ISSUE TITLE
Unable to retrieve Metadata of sub folder with extension

### ISSUE THREAD

**Issue by ronika-das** [forcedotcom/salesforcedx-vscode#3806]
### Summary

If the metadata is available inside another folder(i.e. it is under a sub folder), the Org Browser, doesn;t have the option to retrieve it

### Steps To Reproduce:

1.  Open Org Browser-> Open Report. Lets say we a Report folder called ABC and inside that we have few reports. It doesnt retrieve the reports within the sub folder
2. In the attached screenshot, There is a report Folder named work_order_reports. Inside that we have 10-15 reports. We are not able to retrieve that with the org browser

### Expected result

It should allow us to retrieve the metadata files within sub folders

### Actual result

It is not allowing to retrieve

### Additional information

![image](https://user-images.githubusercontent.com/32714099/152559453-957df2c2-cf43-4727-9d18-85e4e00d3d23.png)

**Salesforce Extension Version in VS Code**: 53.16.0

**SFDX CLI Version**:sfdx-cli/7.122.1 win32-x64 node-v14.18.0

**OS and version**: Windows OS , 10.0.19042 Build  19042

**Comment by jorgemontalvao** [comment]
the same for me

**Comment by AnanyaJha** [comment]
Hi @ronika-das thanks for reporting this issue! The team is aware of this and we'll be addressing this bug in the current iteration. We'll post here with updates

**Comment by ronika-das** [comment]
Thank you @AnanyaJha  :)

**Comment by trinasfdx** [comment]
@W-10541413@

**Comment by randi274** [comment]
This has now been delivered with the latest version of the extensions (v54.6.1), with the exception of custom fields. We're tracking that separately with #2711, so we'll close this one for now.

**Comment by jorgemontalvao** [comment]
> This has now been delivered with the latest version of the extensions (v54.6.1), with the exception of custom fields. We're tracking that separately with #2711, so we'll close this one for now.

@randi274 @AnanyaJha @ronika-das 
It works perfectly now! Thank you very much for all your effort here!

**Comment by AnanyaJha** [comment]
No problem, hope you enjoy using the Extensions! Feel free to leave a review or rating here - https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode&ssr=false#review-details
