### ISSUE TITLE
Extension indicates that the CLI is not installed, but only for some commands

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/salesforcedx-vscode#3816]
### Summary

A couple of weeks ago some commands stopped working when run through the editor's command palette. The ones I can remember to have tested this are the "set default org", "push" and "pull" and "open default org". Some other commands, such as "deploy" and "retrieve" still work as expected.

![image](https://user-images.githubusercontent.com/6956403/153381893-84ddc375-0a7c-4e1d-8152-8f01b0c04566.png)

Meanwhile, executing the same command through the integrated terminal works just fine:

![image](https://user-images.githubusercontent.com/6956403/153382298-c2a57157-d65d-427e-a55a-002b0d36c4a9.png)

Raised after comment on a similar issue (#3582).

### Steps To Reproduce:

Unavailable at this time.

### Expected result

Commands should execute as usual, as the CLI is installed.

### Actual result

Commands mentioned before do not work.

### Additional information

OS/VScode info:
```
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:17:47.733Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.7-arch1-1
```
CLI version: `sfdx-cli/7.136.2 linux-x64 node-v17.3.0`

Extension Version: `v53.16.0`

**Comment by randi274** [comment]
Thanks for moving this to a separate issue @renatoliveira! Do you recall roughly when this stopped working? Also, how have you installed the Salesforce CLI?

**Comment by renatoliveira** [comment]
This has been happening for one week or so now. `VScode` is installed through my distro's package manager, also used for `yarn` and Node.js. The CLI is installed globally using `yarn`.

**Comment by gbockus-sf** [comment]
HI @renatoliveira 
I just tested locally on my Ubuntu box with a fresh install of VSCode and the extensions and things seemed to work as expected for the 'SFDX: Open Default Org' so I'm guessing it has something to do with the user or env running VSCode.  
Did you start vscode from the app launcher or from the terminal? 

Could you try opening it from the terminal where you were able to successfully run `sfdx` and see if the 'Open Default Org' works as expected? Execute `code .` from the directory where your salesforce project is located. 
Thanks

**Comment by gbockus-sf** [comment]
Yeah I'm not sure why sometime vscode launches with the environment not quite right.  I'll mark this as a bug so we can investigate.

**Comment by jorgesolebur** [comment]
I am having the same issue !

**Comment by aggartman** [comment]
Is there any update on this?
I can't get my Playground to Authorize. Even using the terminal "code ." workaround mentioned above. The terminal shows up just fine. But any commands that call the CLI directly in the command palette give me the error message of "Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli"

**Comment by renatoliveira** [comment]
> Is there any update on this? I can't get my Playground to Authorize. Even using the terminal "code ." workaround mentioned above. The terminal shows up just fine. But any commands that call the CLI directly in the command palette give me the error message of "Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli"

There is a workaround. Open your terminal and launch VS Code with `code` instead. It is annoying? Yes. But at least it works.

**Comment by aggartman** [comment]
Yeah, I tried that, but it doesn't work. `code` and `code .`, I have the same result, unfortunately.  I've checked the versions for java and node. Double checked my path variable, and restarted multiple times. No luck.

**Comment by aggartman** [comment]
> > Is there any update on this? I can't get my Playground to Authorize. Even using the terminal "code ." workaround mentioned above. The terminal shows up just fine. But any commands that call the CLI directly in the command palette give me the error message of "Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli"
> 
> There is a workaround. Open your terminal and launch VS Code with `code` instead. It is annoying? Yes. But at least it works.

Yeah, I tried that, but it doesn't work. `code` and `code .`, I have the same result, unfortunately.  I've checked the versions for java and node. Double checked my path variable, and restarted multiple times. No luck.

**Comment by aggartman** [comment]
Resolved. Clean install of Node and NPM with a reinstall of SFDX plus a restart seemed to fix it.

**Comment by renatoliveira** [comment]
Oh, so that explains why reinstalling my OS worked too then. :rofl:

**Comment by gbockus-sf** [comment]
@aggartman Thanks for the follow up.  Did you have any node/npm or OS changes that could have resulted in the issue (upgrades)? 
Mostly just checking in case this shows up for anyone else. 

Thanks

**Comment by aggartman** [comment]
> @aggartman Thanks for the follow up.  Did you have any node/npm or OS changes that could have resulted in the issue (upgrades)? 
> Mostly just checking in case this shows up for anyone else. 
> 
> Thanks

No changes, but I did a fresh install and made sure to install the cli through NPM rather than individually. The versions are all the same.

**Comment by eofferma** [comment]
Reinstalling all Salesforce Extensions solves the problem for me.
