### ISSUE TITLE
Getting a Java Bind issue on launch of VS code

### ISSUE THREAD

**Issue by CSTufts** [forcedotcom/salesforcedx-vscode#383]
### Summary
_Short summary of what is going on or to provide context_.
Getting a Java Bind issue on launch of VS code

Ha da lot of trouble getting this going when I run any of the sfdx commands from the command palate I get this:
" 
Starting SFDX: Push Source to Default Scratch Org

sfdx force:source:push
sfdx force:source:push ended with error spawn sfdx ENOENT
The SFDX CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli
"

was running into a lot of java issues up front, have reinstalled the apps  quite a few times. I think i worked through that by changing the key in my user settigns to this:
"salesforcedx-vscode-apex.java.home": "/Program Files/Java/jre1.8.0_171"

if this isn't your issue please point me in the right direction

thanks!

### Steps To Reproduce:
1. Launch VS code
1. open debugger

### Expected result
_Describe what should have happened_.
No Java biding Issue

### Actual result
_Describe what actually happened instead_.
Seeing a java bind issue (screen shot attached)

![java bind error](https://user-images.githubusercontent.com/5683200/38898312-9d1026e8-4262-11e8-8b47-2d88993a3168.PNG)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.22.2
**SFDX CLI Version**:
sfdx-cli/6.11.0-9a1ef8794d (windows-x64) node-v8.9.4
**OS and version**:
Windows 10
Version	10.0.16299 Build 16299

**Comment by vazexqi** [comment]
@CSTufts - I think that error is actually from a different extension that doesn't below to us.

Could you show me what you get from running the following `code --list-extensions` in your terminal.

![screen shot 2018-04-17 at 4 05 42 pm](https://user-images.githubusercontent.com/54414/38903370-4be9bc06-4259-11e8-85fa-ed565b79a9db.png)

You can try to disable the extensions and enable only the ones that I have listed above. You can identify official salesforce extensions by the first part. Our official extensions will always have the name salesforce.some_extension_name.

**Comment by CSTufts** [comment]
Thanks for the response I will try that first thing tomorrow and report back. Do you think that this could be causing the issue that vs doesn’t seem to think that the Salesforce clip is installed? Which is obviously the crux of the issue...

Do you have any idea what port it’s complaining about, so I can try to shut it down if it happens to be interfering?

Thanks!

**Comment by vazexqi** [comment]
@CSTufts - 

1. It looks to be the extension that uses the neowit package. We do not own that package and we are not familiar with what it is doing, so I can't advise on which port(s) it is using.
1. As for the Salesforce CLI not being detected, let me get back to you on that. Are you using https://developer.salesforce.com/media/salesforce-cli/sfdx-windows-amd64.exe? Or are you installing it a different way?

**Comment by CSTufts** [comment]
I have installed it the standard way for windows

**Comment by CSTufts** [comment]
after disabling all other extensions (and figuring out that the java issue happened to be because the author of another mod didn't gracefully shut down when vs code exists...) the issue that I am getting still persists: 
Starting SFDX: Push Source to Default Scratch Org

sfdx force:source:push
sfdx force:source:push ended with error spawn sfdx ENOENT
The SFDX CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli

even after re-installing the extensions
here is the workspace settings
{
    "terminal.integrated.env.osx": {
        "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
    },
    "terminal.integrated.env.linux": {
        "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
    },
    "terminal.integrated.env.windows": {
        "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
    }
}

I can share my whole settings file if you wish.

thanks!

**Comment by vazexqi** [comment]
@CSTufts - We have figured out the issue about `sfdx force:source:push ended with error spawn sfdx ENOENT` on our side. The _new_ installers for Windows (which is what you are using) have a different form that we need to handle through VS Code. We are working toward a fix as we speak. I'll update this work item when one is available.

**Comment by vazexqi** [comment]
@CSTufts - The new extensions (42.12.0) have been published to https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode. A new version of the Salesforce CLI has also been released (be sure to do a `sfdx update`).

Please give them a try (be sure to update all of the ones that you are using since this is a fundamental change in the guts of the extensions).

Please reopen if this doesn't solve your `... error spawn sfdx ENOENT` error.
