### ISSUE TITLE
Code coverage from Debug Logs

### ISSUE THREAD

**Issue by anshul360** [forcedotcom/salesforcedx-vscode#3832]
**Is your feature request related to a problem? Please describe.**
Many times the test classes fail to produce the code coverage if the code base is huge on the org. This leads to problems during 
 prod release.

**Describe the solution you'd like**
A new extension which can tell/highlight the code coverage of a class using debug logs. Can the Replay debugger be used to calculate approximate code coverage for a class. This can come in handy in case test classes fail to calculate code coverage due to huge code base.  

**Describe alternatives you've considered**
To my knowledge there is no  alternative currently to get code coverage apart from test coverage results from test run.

**Additional context**

**Comment by diyer** [comment]
@anshul360 the issue with missing code coverage has been addressed. Please verify on your end and let us know. Given that we are closing this issue. thank you for filing this issue!
cc: @AnanyaJha
