### ISSUE TITLE
 SFDX: Update Checkpoints in Org fails with error

### ISSUE THREAD

**Issue by julianperezpesce** [forcedotcom/salesforcedx-vscode#3835]
### Summary

After the trail Salesforce DX in wich I had to create a scratch org. I'm having problems with Org Authorize and Update checkpoints. 
![imagen](https://user-images.githubusercontent.com/46091490/153875438-f8b009cc-aef4-470d-ac7d-5df6da54d277.png)

The same happens with Authorize an Org, I can deploy or retrieve Apex classes but doesn't work properly. 

![imagen](https://user-images.githubusercontent.com/46091490/153875809-01407bf4-5f11-4653-a172-ab9c8540991d.png)

I already try, installing/uninstalling, creating new Playgrounds, new Projects with manifest, nothing works!!!

I read, the could be json file, but all json files looks normal. tried setting my user again and gives some problem

**Comment by jag-sfdc** [comment]
@julianperezpesce - I see "SFDX: Update Checkpoints in Org" works as expected. How are you authorizing to the org? If you want to use a scratch org, you first authorize a devhub org using "SFDX: Authorize a Dev Hub".

**Comment by gbockus-sf** [comment]
@julianperezpesce did the above guidance from Jag fix your issue?
