### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ghoshdipan-ck** [forcedotcom/salesforcedx-vscode#3853]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `54.0.0`
- OS Version: `Darwin arm64 21.3.0`
- VS Code version: `1.64.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by gbockus-sf** [comment]
Please reopen if you are still having issues.
