### ISSUE TITLE
RunTest button does not show up for test classes in vscode

### ISSUE THREAD

**Issue by mbajwa2** [forcedotcom/salesforcedx-vscode#3874]
### Summary
When I navigate to a test class, I am not able to see the 'RunTest' button or 'Run All Test' button .

WHEN
### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened_.

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`

{
        "cliVersion": "sfdx-cli/7.136.2",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "config 1.3.15 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.7.6 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.136.2 (core)",
                "source 1.8.9 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.3.0"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by tehnrd** [comment]
If anyone comes across this issue, make sure your java home directory is set correct...AND the setting is not set to sync. I had sync settings on, but the two computers I use have different java directories and this was causing it to be incorrect on one of them.
<img width="684" alt="Screenshot 2023-07-05 at 12 34 45 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/1007085/2fd70891-3dfb-4c4f-ba3a-09b2de19ddde">
