### ISSUE TITLE
StandardValueSet cannot be retrieved with the Salesforce extension

### ISSUE THREAD

**Issue by remifoyard** [forcedotcom/salesforcedx-vscode#3889]
### Summary

StandardValueSet cannot be retrieved with the Salesforce extension.

### Steps To Reproduce:

1.  Go to the extension to retrieve StandardValueSet 
2. Nothing appears in it...

### Expected result

StandardValueSet must appears

### Actual result

None StandardValueSet appears

### Additional information

![image](https://user-images.githubusercontent.com/32206827/157212481-14836382-2cbb-433c-9de6-9deac0977b9f.png)

**Salesforce Extension Version in VS Code**: v54.3.0

**SFDX CLI Version**: v54.3.0

**OS and version**: Windows 10

**Comment by mohanraj-r** [comment]
@RitamAgrawal Could this be related to #3806 ?

**Comment by RitamAgrawal** [comment]
@mohanraj-r This isn't related to #3806. In OB we call metadata API to list all metadataTypes. @remifoyard What all Standard Value Set do you expect to be listed here?

**Comment by mohanraj-r** [comment]
Thanks @RitamAgrawal 
@remifoyard Can you also post output of the equivalent sfdx cli command (that Ritam pointed to me) to rule out permission issues etc

`sfdx force:mdapi:listmetadata --json -m  StandardValueSet --folder ${folder} -u ${username}`

**Comment by saurabh-deep** [comment]
Hello @RitamAgrawal and @mohanraj-r,

We are running into a situation where the following command is not returning any StandardValueSet at all, but Org Browser is correctly showing all of them. I am unable to figure out what is it that I am doing incorrectly which is different from what Org Browser is doing. One thing I am almost sure of is that StandardValueSet is not a folder type metadata, so passing --folder is not required. Below command is 

`sfdx force:mdapi:listmetadata --json -m StandardValueSet -u <username>`

All I get is - `No metadata found for type: StandardValueSet in org: <username>`

Would please be able to point me in the right direction? It will be a great help. Thank you!

Best
Saurabh

**Comment by 1ktribble** [comment]
Keeping this open as there's been no resolution and we've been able to reproduce the error.
