### ISSUE TITLE
communication protocol

### ISSUE THREAD

**Issue by ymdymdymd** [forcedotcom/salesforcedx-vscode#3893]
The salesforce help asked me to ask here.
What is the communication protocol of salesforcedx-vscode?

**Comment by AnanyaJha** [comment]
Hi @ymdymdymd thanks for reaching out! We typically communicate new changes to our users via our weekly [changelogs](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode/CHANGELOG.md) and announcements posted on our issues here. Is there any other type of information you're looking to find?

**Comment by ymdymdymd** [comment]
Thank you for your reply.
I use VS Code to develop salesforce in my company.
To do this, you need to know the communication protocol information and add it to the whitelist.

**Comment by ymdymdymd** [comment]
I need the destination IP and port number used in salesforcedx-vscode.

**Comment by mohanraj-r** [comment]
@ymdymdymd Is this question related to https://github.com/microsoft/vscode-languageserver-node/issues/907?

**Comment by mohanraj-r** [comment]
@ymdymdymd The Language server communication is localhost. There shouldn't be any ports that you need to whitelist. If you find any functionality lacking or run into any issues, please provide details.

**Comment by ymdymdymd** [comment]
thank you.
