### ISSUE TITLE
GitHub Pages for this project redirects to ads and possible malware

### ISSUE THREAD

**Issue by eburtness** [forcedotcom/salesforcedx-vscode#3897]
### Summary

GitHub Pages at `https://forcedotcom.github.io/salesforcedx-vscode/` is serving a redirect to `salesforcedx-vscode.com` which now hosts ads and tries to install a suspicious browser search extension.

Based on #3590 it sounds like `salesforcedx-vscode.com` once hosted the docs but was abandoned and has now been registered by someone unrelated to the project. I see that #3605 updated several links in this project, but there are links elsewhere on the web (including `developer.salesforce.com`) pointing to this project, and it's not great that this project redirects visitors to a potentially dangerous site.

Can the redirects be removed or the GitHub Pages site for this project disabled altogether? Landing on a GitHub 404 error would be much better than getting redirected to `salesforcedx-vscode.com` as it is now.

### Steps To Reproduce:
1. Visit https://developer.salesforce.com/tools/vscode/en/user-guide/prettier
2. Follow "Prettier Apex plugin" link to https://github.com/dangmai/prettier-plugin-apex
3. Follow "this tutorial" link to `https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/prettier`

Or just visit `https://forcedotcom.github.io/salesforcedx-vscode/`

### Expected result

Documentation site maintained by this project

### Actual result

Suspicious site prompting me to install browser search extension

### Additional information

![image](https://user-images.githubusercontent.com/39753627/157485137-fd3e3c97-f856-485b-8233-bfc93cdd7431.png)

**Comment by AnanyaJha** [comment]
Thanks for reporting this @eburtness, we'll take care of this ASAP.

**Comment by mohanraj-r** [comment]
https://forcedotcom.github.io/salesforcedx-vscode/ has been unlinked from `salesforcedx-vscode.com`

**Comment by eburtness** [comment]
Looks good! Thanks!
