### ISSUE TITLE
It does not work on MacOS Monterey 12.2.1

### ISSUE THREAD

**Issue by LidiaGHerrerias** [forcedotcom/salesforcedx-vscode#3898]
### Summary

Salesforce Mobile App Emulator for Android does not work on MacOS Monterey 12.2.1

### Steps To Reproduce:

1.  I installed xcode previosly in my mac and Simulator for IOS.
2.  I installed Android Studio (It never opens). I can click to open it as many times as I can and It does not work.
3.  When I try to reproduce the steps of opening an app from VSCode clicking the option of SFDX: Preview Component Locally choosing Desktop or Android options, do not work.

### Expected result

The Android Simulator should start the app and if I click to SFDX: Preview Component Locally and I chose view on browser then my browser should open it.

### Actual result
It does not work.

It does nothing, it does not open a window or show errors.

### Additional information

**Salesforce Extension Version in VS Code**:
Salesforce CLI Integration v54.3.0

**OS and version**:
macOS Monterey 12.2.1

**Comment by marcbourlon** [comment]
Sounds related to https://github.com/forcedotcom/salesforcedx-vscode/issues/3903

**Comment by randi274** [comment]
@LidiaGHerrerias is this working for you now? We released a second update last week to address #3903 among others, and the latest version is now 54.4.1 for all of our extension packages.
