### ISSUE TITLE
Reply to #3894

### ISSUE THREAD

**Issue by NayanaGupta-Git** [forcedotcom/salesforcedx-vscode#3899]
The OS in my system is  - Windows 10
<img width="758" alt="Error in VS" src="https://user-images.githubusercontent.com/64770166/157502426-907fc47a-c58e-4ecc-bd2a-6481128e20f4.PNG">

and the issue is 
When I create a new project in LWC the Default path goes to that Project and their are no files in lwc folder(.html,.js ,.metaxml).
I have attached the screenshot of the same
I have created Project Test and the lwc folder has no files.

Also Even if i set the default org on creating a new project it says 'No Default org Set'.
<img width="936" alt="Error" src="https://user-images.githubusercontent.com/64770166/157502901-4013a212-cc3e-4c09-b059-5796454db014.PNG">

**Comment by AnanyaJha** [comment]
> The OS in my system is - Windows 10 <img alt="Error in VS" width="758" src="https://user-images.githubusercontent.com/64770166/157502426-907fc47a-c58e-4ecc-bd2a-6481128e20f4.PNG">
> 
> and the issue is When I create a new project in LWC the Default path goes to that Project and their are no files in lwc folder(.html,.js ,.metaxml). I have attached the screenshot of the same I have created Project Test and the lwc folder has no files.
> 
> Also Even if i set the default org on creating a new project it says 'No Default org Set'. <img alt="Error" width="936" src="https://user-images.githubusercontent.com/64770166/157502901-4013a212-cc3e-4c09-b059-5796454db014.PNG">

**Comment by mohanraj-r** [comment]
Moving further conversations to #3894
