### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by nfranco94** [forcedotcom/salesforcedx-vscode#3906]
Issue Type: <b>Bug</b>

missing commands like, auth dev to hub, remove org, list of active and deletes orgs, etc.

Extension version: 54.4.0
VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:04.372Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 1eea1369-3f7e-4e24-bb16-c6da2d50823c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc008:30440022
pythonvspyt640:30450904
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30447480
helix:30440343
pynewfile477:30450038

```

</details>

**Comment by marcbourlon** [comment]
Please check https://github.com/forcedotcom/salesforcedx-vscode/issues/3903

**Comment by AnanyaJha** [comment]
Hi everyone! Thanks for reporting this and sorry about the issues you're facing. This is due to a known problem with the latest release of the Salesforce Extensions v54.4.0. This issue is being tracked by #3901 and the team is working on a fix. In the meantime, please downgrade to version v54.3.0 - let us know if you see any other issues or have any questions!
