### ISSUE TITLE
sfdx cli integration extension for VSCode GUI commands not working

### ISSUE THREAD

**Issue by TrevorAGill** [forcedotcom/salesforcedx-vscode#3907]
### Summary

Salesforce CLI Integration extension for VSCode suddenly stopped working. I am able to use sfdx commands via the terminal and they work, but none of the GUI options are available to me anymore. When I use Command + Shift + P I only see 3 SFDX Command options: Create Project with a Manifest, Create Project, and Create and Setup Project for ISV Debugging. When I try to actually use any of these commands I get this error:  "Command 'SFDX: Create Project with Manifest' resulted in an error (command 'sfdx.force.project.with.manifest.create' not found)". 

In attempting to remedy the issue I have followed all advice around this issue I have found on online forums by uninstalling and reinstalling (multiple times and in various sequences): 
- VSCode
- Salesforce CLI (via installed package and via NPM)
- Salesforce CLI Integration VS Code Extension
- Java JDK

### Steps To Reproduce:

1.  Open VSCode
2. Confirm SFDX CLI is installed
3. Confirm Salesforce CLI Integration VS Code Extension is installed and enabled
4. Confirm SFDX is updated
5. Try to use any SFDX command through the extension GUI.

### Expected result

Able to see all the various SFDX commands available in the GUI. 

### Actual result

Only see the 3 options listed above, and none of them work. Error msg: "(command 'sfdx.force.project.with.manifest.create' not found)"

### Additional information

![image](https://user-images.githubusercontent.com/1494545/157712804-a61bbb93-8e2c-4204-8214-f384888dae79.png)

**Salesforce Extension Version in VS Code**:
v54.4.0

**SFDX CLI Version**:
sfdx-cli/7.141.1 darwin-x64 node-v16.13.1

**OS and version**:
MacOS Monterey vr 12.1

**Comment by JoshNicholasHunter** [comment]
Same here - absolutely no idea what's caused this!

Re-installed the CLI multiple times along with doing the same with Salesforce Extension, tried downgrading both, but no luck.

Salesforce Extension:
v54.4.0

SFDX CLI:
sfdx-cli/7.141.1 darwin-x64 node-v16.14.0

OS:
MacOS Monterey 12.2.1


Developer Tools is showing this:

![image](https://user-images.githubusercontent.com/98747830/157716856-845db3c6-4d0c-406f-82a2-c0c8d90ee213.png)

**Comment by AnanyaJha** [comment]
Hi all! Thanks for reporting this and sorry about the issues you're facing. This is due to a known problem with the latest release of the Salesforce Extensions v54.4.0. This issue is being tracked by #3901 and the team is working on a fix. In the meantime, please downgrade to version v54.3.0 - let us know if you see any other issues or have any questions!

**Comment by TrevorAGill** [comment]
That did the trick. Thanks @AnanyaJha!
