### ISSUE TITLE
Unable to Create a Project 

### ISSUE THREAD

**Issue by marieniekamp** [forcedotcom/salesforcedx-vscode#3911]
### Summary

I am trying to create a project and am unable to. Here is the error. 

Command 'SFDX: Create Project with Manifest' resulted in an error (command 'sfdx.force.project.with.manifest.create' not found)

### Steps To Reproduce:

1. Command 'SFDX: Create Project with Manifest'
1. Received an error 

### Expected result

Should be able to create a project 

### Actual result

Receive the above error

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**: v54.4.0

**OS and version**: Monterey 12.2.1

**Comment by AnanyaJha** [comment]
Hi @marieniekamp! Thanks for reporting this and sorry about the issues you're facing. This is due to a known problem with the latest release of the Salesforce Extensions v54.4.0. This issue is being tracked by https://github.com/forcedotcom/salesforcedx-vscode/issues/3901 and the team is working on a fix. In the meantime, please downgrade to version v54.3.0 - let us know if you see any other issues or have any questions!

**Comment by marieniekamp** [comment]
Thanks Ananya for the quick reply. I tried v54.3.0 but encountered the same issue. I actually tried every version from v53.12.0 to 54.4.0 and get the same error every version.
I aslo wanted to note that when I type in SFDX: the only option I get are:

- SFDX: Create Project with Manifest
- SFDX: Create Project 
- SFDX: Create and Setup Project fro ISV Debugging

**Comment by AnanyaJha** [comment]
Hi @marieniekamp is there a chance that the extensions are getting cached? In your Finder window navigate to the Go > Home > .vscode folder. If you don't see the hidden folder, press Command+Shift+`.` . In that folder, please delete all the extensions that end with the suffix `54.4.0`. Then, try rerunning the commands on an older version of the extension

**Comment by marieniekamp** [comment]
I reviewed the comments in the other case and setting the version of
"Salesforce CLI Integration" to v54.3.0 worked for me.
