### ISSUE TITLE
Error: aborted at connResetException

### ISSUE THREAD

**Issue by yusuframadhan26** [forcedotcom/salesforcedx-vscode#3952]
Hi there,
I got this errror:

(node:internal/errors:691:14) at TLSSocket.socketCloseListener (node:_http_client:402:19) at TLSSocket.emit (node:events:532:35) at node:net:687:12 at TCP.done (node:_tls_wrap:580:7) { code: 'ECONNRESET' }

![image](https://user-images.githubusercontent.com/45062544/160029018-5ca31b3e-bb5d-4dfa-af01-f6771f1da54a.png)

**Comment by floralan** [comment]
Hi @yusuframadhan26, could you provide more information on the steps that we can reproduce this issue and what version of extensions you are using?
