### ISSUE TITLE
Deployment Error For Lightning Web Components

### ISSUE THREAD

**Issue by biswajit-salesforce** [forcedotcom/salesforcedx-vscode#3988]
While deploying of the LWC component via User interface using "mouse Right Click -> SFDX: Deploy this source to org", facing the error "duplicate value found: <unknown> duplicates value on record with id: <unknown>
              Cannot find Lightning Component Bundle StandardRequestFlow.                   
              Cannot find Lightning Component Bundle StandardRequestFlow.",
 if the LWC's Javascript ".js" file is open/selected.
 This error does not happen if ".js-meta.xml" or ".html" file is open/selected.

**Comment by klewis-sfdc** [comment]
Hi @biswajit-salesforce - thanks for opening the issue.  I have tried to reproduce the issue in a Developer Edition org but have not been able to get the error to surface.  Are you still seeing this issue, and if so, do you have any additional repro steps that could help to reproduce?

**Comment by biswajit-salesforce** [comment]
Hi Ken, lately I have switched over back to Aura components, so haven't
tackled it anymore.

Yours sincerely,
Biswajit Samantaray

**Comment by AnanyaJha** [comment]
Thanks @biswajit-salesforce. Feel free to open a new issue if you run into anymore problems, thanks!
