### ISSUE TITLE
Clicking ctrl+space within curly brackets from HTML file should not trigger a different autocomplete list

### ISSUE THREAD

**Issue by floralan** [forcedotcom/salesforcedx-vscode#3989]
**Describe the bug**
We currently have a autocomplete list when trigger {} in HTML file (see the PR here https://github.com/forcedotcom/lightning-language-server/pull/487). Clicking ctrl+space within {} in HTML file triggers a different autocomplete list. We want to disable this different autocomplete list within {}.

**To Reproduce**
1, Go to any HTML file in a SFDX project
2, Type curly bracket: {}, here we get the autocomplete list that we implemented
3, Select any item from the autocompletion list
4, Backspace to delete the item
5, Click ctrl+space

**Expected Result**
Nothing shows up by clicking ctrl+space.

**Actual Result**
Screenshots
We get a list of autocomplete items by clicking ctrl+space.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/42667832/160915625-86237778-1fa0-4be8-bf94-a078f46131cf.png">

The list of autocomplete list triggered by {}:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/42667832/160915765-172fb8c8-8d09-4b61-a131-df3e77da468a.png">

**Desktop (please complete the following information):**

OS: Mac OS Big Sur
Version: v54.6.1

**Comment by randi274** [comment]
This has been fixed and is now available with v54.15.0 🎉
