### ISSUE TITLE
Intellisense fires inside of String literals.

### ISSUE THREAD

**Issue by cceremuga** [forcedotcom/salesforcedx-vscode#399]
When typing inside of a String literal, if I complete a sentence with a ".", it pulls up the intellisense dropdown, which I have to press escape on in order to continue typing.

![screen shot 2018-04-25 at 4 01 24 pm](https://user-images.githubusercontent.com/525742/39269864-128fc8ac-48a2-11e8-9c88-03a00b3fd599.png)

**Comment by ntotten** [comment]
Closing in favor of #575
