### ISSUE TITLE
VSCode problems tab doesnt redirect to error line when clicked for deploy errors

### ISSUE THREAD

**Issue by CanYavuzkurtOSF** [forcedotcom/salesforcedx-vscode#3990]
### Summary

Apex File deploys with errors creates Problems in Problems tab in VSCode. But when I click the individual problems it shows 'Unable to open file' error.

### Steps To Reproduce:

1.  Create an Apex class that will show an error when trying to deploy to org
1.  Deploy the file

### Expected result

Errors should be shown on Problems tab and should redirect to the error line when clicked

### Actual result

Errors are shown on Problems tab and but instead of redirecting to the error line when clicked, it shows an error.

### Additional information
My guess would be the file path in the problems. It starts with /force-app/... which forces it to be an absolute path.
It should be force-app/...

![image](https://user-images.githubusercontent.com/91070026/160917800-58463ac4-37d2-42f1-bc6c-4598983005ab.png)

**Salesforce Extension Version in VS Code**:v54.6.1

**SFDX CLI Version**:sfdx-cli/7.143.0 win32-x64 node-v16.14.0

**OS and version**: Windows 10 Pro 10.0.19044 Build 19044

**Comment by alexey-holovko-synebo-io** [comment]
Have same issue on macOS

**Comment by kfcpub** [comment]
Having the same issue

Salesforce CLI

VERSION
  sfdx-cli/7.144.2 win32-x64 node-v16.14.2

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎8/‎17/‎2021
OS build	19042.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by AngelMtz97** [comment]
I have the same issue 

VS Code version: 1.66.2

Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Salesforce Extension Pack: 54.9.0 - April 21, 2022

sfdx-cli/7.147.1 win32-x64 node-v16.14.2:

Windows 10 Pro 21H2

**Comment by tjofr** [comment]
I have the same issue.
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042

 sfdx-cli/7.151.1 win32-x64 node-v14.15.1
 
 It seems that the links in Problens Pane is broken. 
We have :
[{
	"resource": "/force-app/main/default/classes/SendCase_WSO_TST.cls",
	"owner": "deploy-errors",
	"severity": 8,
	"message": "Invalid type: SendCase_WSO.Data (150:35)",
	"source": "ApexClass",
	"startLineNumber": 150,
	"startColumn": 35,
	"endLineNumber": 150,
	"endColumn": 35
}]

instead of "resource":"<full path to the apex class>"

**Comment by worktowindsurf** [comment]
Same problem for me
Is there any workaround?
Can you go back to an older version?
And if so, which version works?

This is a real productivity issue…

**Comment by meilingkuan** [comment]
I having issue with the problem tab too. It doesn't seem to refresh now once the code file is deploy successfully. it still show the old errors. how do we remove this?

**Comment by worktowindsurf** [comment]
I've had errors remaining on the 'Problem' tab even after successful deployment.
Quit VSCode and re-enter seems to fix the problem
(But is takes ages to load all the extension now...)
