### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by shubhamOpt** [forcedotcom/salesforcedx-vscode#3994]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `54.6.1`
- OS Version: `Darwin x64 20.1.0`
- VS Code version: `1.66.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/mg/7s00171j5v33tct155rtpdjw0000gn/T/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jag-sfdc** [comment]
Duplicate https://github.com/forcedotcom/salesforcedx-vscode/issues/3198
