### ISSUE TITLE
Error retrieving code with Salesforce Cli Integration

### ISSUE THREAD

**Issue by JsalvaJ** [forcedotcom/salesforcedx-vscode#3997]
Issue Type: <b>Bug</b>

With the new version of march I have an issue making the "retrieve source in manifest from org" command.
When I did it, it starts thinking and the extension give me an error. In the output window nothing appears and the right picklists moves from "salesforce cli" to "task" automatically.
I can see the error going to the extension "Salesforce Cli Integration" > Runtime Status. The error is  "array buffer allocation failed" . I reinstalled all the things (extensions and VSC last version) with new version and it doesn't work. 
Now I download the version of february of VSC 1.65.2 and all is working fine.

There is something in the new version that doesn't work with salesforce cli integration extension.

Hope this helps.
Thanks.

Extension version: 54.6.1
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.42GB free)|
|Process Argv|--crash-reporter-id b4eb6d0f-cad4-4d66-8b29-c7c64fc50dc8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by floralan** [comment]
Hi @JsalvaJ, I tried to reproduce the bug you were seeing. Did you use extensions v54.6.1 with the VSC last version v1.66.0 and saw the error, but the error disappeared when you use extensions v54.6.1 with VSC v1.65.2? I couldn't reproduce the error since both situations work fine on my end. Could you please try to update to our latest version v54.8.0 to see if it works?

**Comment by manentea** [comment]
@floralan This issue is still occurring on VSC v1.66 and with v54.80 of the extension. Rolling back to VSC 1.65.2 resolved the issue (same extension version).

**Comment by jigyasujoshi1997** [comment]
Yes facing the same issue "array buffer allocation failed" while trying to Retreive source in Manifest from Org. Rolled back to VSC 1.65.2 resolving the issue.

**Comment by chillday** [comment]
Experiencing the same issue

**Comment by kateluu-comdev** [comment]
Thank for sharing, I got the same issue with VSCode version 1.67.2. 
I had roll back to version v.65.2 as suggestion and it works for me. Issue is clear. Cheers

**Comment by JsalvaJ** [comment]
This issue is still occurring. I have installed the new version of VSC and I have the same issue. Trying to "retrieve source from org" and it spends a lot of time trying to do that and finally it stoped with a message that say that it's an error.
VSC versión. 1.73.1
and Salesforce Cli version. v56.5.1.

I cannot update the version of VSC because it fails. Do you have some info about it?

![image](https://user-images.githubusercontent.com/39059753/201614765-6a40777c-a4dc-4a1d-8b4b-43bba2d7542e.png)
![image](https://user-images.githubusercontent.com/39059753/201615107-66a9cb77-dbd7-4729-8d3d-3f800196ef4d.png)

**Comment by manentea** [comment]
This is still occurring. On the latest versions of VS Code and SFDX. We're still using the Feb '22 release of VS Code (1.65.2) in order to workaround this. Is there any chance this would be resolved? The issue is not intermittent, it's 100% reproducable on multiple machines.
