### ISSUE TITLE
Error when mouse-over on HTML file

### ISSUE THREAD

**Issue by simonhyphen8** [forcedotcom/salesforcedx-vscode#3999]
Issue Type: <b>Bug</b>

When mousing over on the .HTML file of an LWC, I receive the following error:
[Error - 7:53:32 AM] Request textDocument/hover failed.
Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'forEach')
Code: -32603

Confirmed as this extension causing the issue by using the Start Extension Bisect command.

Previous logged issue (now closed) 
https://github.com/microsoft/vscode/issues/146703

Today (04/04/2022) I have updated to the latest CLI

Extension version: 54.6.1
VS Code version: Code - Insiders 1.67.0-insider (Universal) (5467c8c4413be3a69960fe418d2c345bfbdf2b55, 2022-04-04T05:16:19.025Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 6c3f7368-0cd9-4122-842b-2d548ce8e88d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by randi274** [comment]
Hi @simonhyphen8, thanks for reporting this! We're tracking this on #3929, so I'll close this as a duplicate. The fix for this is currently pending, and will hopefully be out next week.
