### ISSUE TITLE
Provide non-socket-based access to the language server

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/salesforcedx-vscode#4]
As we just discussed, it would be great if I could interact with the language server without having to spin up a separate process and communicate over the network.  It looks like I should be able to instantiate the server process in-memory and hand it non-socket-based streams, so that might work, albeit unsupported.  It would be great, though, if I could just instantiate the server and then perform direct request/response interactions with it, e.g.:

```javascript
String diagnosticsRequest = createPublicDiagnosticsRequest();
String diagnosticsResponse = languageServer.sendRequest(diagnosticsRequest);
PublicDiagnostics diagnostics = PublicDiagnostics.create(diagnosticsResponse);
addEditorAnnotations(diagnostics);
```

**Comment by vazexqi** [comment]
Forgot to update this: this was closed via #53
