### ISSUE TITLE
Deploy doesn't work after Update

### ISSUE THREAD

**Issue by mshermanNuAge** [forcedotcom/salesforcedx-vscode#4002]
Issue Type: <b>Bug</b>

I just updated VS Code and now I can no longer deploy. I can still retrieve the source but get this error when I try to deploy changes: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 912190463-794265 (4555982)

Extension version: 54.6.1
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (1.81GB free)|
|Process Argv|--crash-reporter-id d74fd3cf-b16f-4104-8b57-5daa5b126cdc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by floralan** [comment]
Hi @mshermanNuAge, I tried to use extensions version v54.6.1 and VSC v1.66.0 to reproduce this issue but the deploy command works fine on my end. Could you please update the exemptions to the latest version v54.8.0 to see if you are still seeing the error?
