### ISSUE TITLE
Can't retrieve test coverage

### ISSUE THREAD

**Issue by domonique-ncino** [forcedotcom/salesforcedx-vscode#4017]
### Summary

I set "salesforcedx-vscode-core.retrieve-test-code-coverage": true in user and workspace settings.but even it is showing the following exception.

No code coverage information was found for this file. Set "salesforcedx-vscode-core.retrieve-test-code-coverage": true in your user or workspace settings. Then, run Apex tests that include methods in this file. You can run tests from the Apex Tests sidebar or using the Run Tests or Run All Tests code lens within the file.

### Steps To Reproduce:

1.  Installed the Extension Pack
1.  Installed Java 17
1. Retrieve test code coverage = true
1. Run All Tests in test file
1. Click the hamburger to show test coverage  

### Expected result

View the color coded code coverage

### Actual result

Warning message described above
### Additional information

**Salesforce Extension Version in VS Code**: 54.7.0

**SFDX CLI Version**: 7.143

**OS and version**: macOS Monterey version 12.1

**Comment by floralan** [comment]
Hi Domonique, thanks for the issue logging. I'm not able to reproduce the issue you described. For clarification, is the warning message saying: "No code coverage information was found for this file. "? Could you please provide a screenshot of the output after running all tests for apex classes?
