### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by roy-galve** [forcedotcom/salesforcedx-vscode#4018]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `54.7.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.66.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/0z/mb7rqybj4hncf8r6nb6ntwj40000gn/T/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by diyer** [comment]
Closing this as we have addressed a lot of performance issues in our lates VS Code extension. Please get the lates version as of 08-30-2024 and see if you still see this issue. Thank you!
