### ISSUE TITLE
Display Code Coverage on the Testing "webview view" panel

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#4019]
**Is your feature request related to a problem? Please describe.**

Most of the time I see myself clicking on this "play" button to run tests for a particular component instead of typing a cli command because it is faster.

![image](https://user-images.githubusercontent.com/55927613/162407190-2ecf9b6e-31e4-47d9-9553-b409a6e95d07.png)

Doing this way I can't retrieve code coverage for lwc components.

**Describe the solution you'd like**
I would like  to have code coverage displayed somewhere in the "Testing" panel for lwc components. It could be placed somewhere close to the debug and run test buttons

![image](https://user-images.githubusercontent.com/55927613/162407898-311e28a3-5421-4a8b-8c2a-e988163c359f.png)

**Describe alternatives you've considered**
Have to run jest with --coverage in the terminal

**Additional context**
N/A

**Comment by gbockus-sf** [comment]
Thanks for the suggestion @AllanOricil.  I added the feedback label so this can be consider for future feature work on the extensions.

**Comment by AllanOricil** [comment]
This is useful
