### ISSUE TITLE
I can't do Org Authorization (windows 11) to salesforce.

### ISSUE THREAD

**Issue by rgBentec** [forcedotcom/salesforcedx-vscode#4022]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by AnanyaJha** [comment]
Hi @rgBentec could you share the exact error message you're seeing?
