### ISSUE TITLE
 Activating extension 'salesforce.salesforcedx-vscode-core' failed: Invalid or unexpected token.

### ISSUE THREAD

**Issue by prasad-bathula-ukg** [forcedotcom/salesforcedx-vscode#4027]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:
Vs code was working fine, but suddenly I see the error message like as
salesforce.salesforcedx-vscode-core' failed: Invalid or unexpected token.

### Expected result

I'm not able to SFDX commands in vscode

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by AnanyaJha** [comment]
Hi @prasad-bathula-ukg can you share what version of the Salesforce Extensions you're using? This can be found by searching for 'Salesforce' from the Marketplace tab on the left sidebar.

**Comment by prasad-bathula-ukg** [comment]
issue is resolved after uninstalling and installing the Salesforce CLI extension
