### ISSUE TITLE
SFDX:組織へソースをデプロイが機能しない

### ISSUE THREAD

**Issue by sbttakahashi** [forcedotcom/salesforcedx-vscode#4044]
Issue Type: <b>Bug</b>

1. エクスプローラーでメタデータを右クリック
2. SFDX:組織へソースをデプロイを実行
3. successfully ranが表示されるはず
 =>以下のエラーとなりデプロイできない
  UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this 
  ErrorId if you contact support: 1363491765-1494 (455598289)

なお、ターミナルで、sfdx force:source:deployを利用するとdeployできる。

Extension version: 54.8.0
VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

**Comment by floralan** [comment]
Hi @sbttakahashi, this is a duplicate issue to #4002, please post in that issue if you have follow-up questions or more information you want to share to us.
