### ISSUE TITLE
Not able to push to default org, getting this error, Please help

### ISSUE THREAD

**Issue by pchandra2000** [forcedotcom/salesforcedx-vscode#4064]
Starting SFDX: Push Source to Default Scratch Org

14:11:10.560 sfdx force:source:push --json --loglevel fatal
14:11:13.991 sfdx force:source:push --json --loglevel fatal
 ended with exit code 1

TypeError: Cannot read properties of undefined (reading 'split')

I have salesforce cli version 7.147.1 installed, I am using VS Code. 

I don't have any code in the application that uses split.

Here is the debug info:

C:\LWC sessions
λ sfdx force:source:push --json --loglevel debug
{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'split')",
  "exitCode": 1,
  "commandName": "Push",
  "stack": "TypeError: Cannot read properties of undefined (reading 'split')\n    at C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\resolve\\treeContainers.js:166:37\n    at Array.map (<anonymous>)\n    at Function.fromFilePaths (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\resolve\\treeContainers.js:164:15)\n    at PushResultFormatter.componentsFromFilenames (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\formatters\\source\\pushResultFormatter.js:169:129)\n    at PushResultFormatter.correctFileResponses (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\formatters\\source\\pushResultFormatter.js:81:57)\n    at new PushResultFormatter (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\formatters\\source\\pushResultFormatter.js:25:35)\n    at Push.formatResult (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\push.js:153:27)\n    at Push.run (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\push.js:32:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Push._run (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\nOuter stack:\n    at Function.wrap (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at Push.catch (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:248:67)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Push._run (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n    at async Config.runCommand (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async SfdxMain.run (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async SfdxMain._run (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\User\\AppData\\Local\\sfdx\\client\\7.147.1-1633b17\\dist\\cli.js:162:47)",
  "warnings": []
}

**Comment by leslchan** [comment]
I'm receiving the same error as well, on sfdx version: `sfdx-cli/7.147.1 darwin-x64 node-v16.14.2`

 "TypeError: Cannot read properties of undefined (reading 'split')\n    at /Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/treeContainers.js:166:37\n    at Array.map (<anonymous>)\n    at Function.fromFilePaths (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/treeContainers.js:164:15)\n    at PushResultFormatter.componentsFromFilenames (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/plugin-source/lib/formatters/source/pushResultFormatter.js:169:129)\n    at PushResultFormatter.correctFileResponses (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/plugin-source/lib/formatters/source/pushResultFormatter.js:81:57)\n    at new PushResultFormatter (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/plugin-source/lib/formatters/source/pushResultFormatter.js:25:35)\n    at Push.formatResult (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/plugin-source/lib/commands/force/source/push.js:153:27)\n    at Push.run (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/plugin-source/lib/commands/force/source/push.js:32:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Push._run (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\nOuter stack:\n    at Function.wrap (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at Push.catch (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Push._run (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/lesliechan/.local/share/sfdx/client/7.147.1-1633b17/dist/cli.js:162:47)",
  "warnings": []

**Comment by leslchan** [comment]
Fortunately, I was able to get a more specific error message by pushing small sets of files (successful) until encountering a push that led to a more useful error message.

It could be the generic error `TypeError: Cannot read properties of undefined (reading 'split')` is being thrown and the specific error is lost.

**Comment by pchandra2000** [comment]
Yes

**Comment by randi274** [comment]
Is this happening when you try to push all files, or specific files? If there are specific files, are you able to share them? Also, are you using a new scratch org?

I tried to reproduce with a new scratch org and the ebikes-lwc [project](https://github.com/trailheadapps/ebikes-lwc), but everything is looking ok for me (though I did need to create a new scratch org once I caught up my CLI version due to some recent changes). I was able to push the whole project and a single class. I'm now using the extensions v54.9.0, and the rest is: `sfdx-cli/7.148.3 darwin-x64 node-v17.1.0`.

**Comment by pchandra2000** [comment]
I have matched all your setting and still get the same issue. It's on a
blank project, there is no added code. And yes using a new scratch org.

Please tell me something, I am new to salesforce, but I do angular very
well. Is there any way to clean out a salesforce project and rebuild it
from scratch? We do this in angular by deleting the node_modules folder and
running yarn install again? Is it possible to do something similar in
salesforce?

**Comment by paustint** [comment]
I had the same issue and the problem for me was that I had accidentally renamed a metadata file in an lwc

e.x. `amendContractAction.xml` should have been `amendContractAction.js-meta.xml`

**Comment by user851** [comment]
I was getting this error after renaming a LWC component. Changed it back and it pushed ok.

**Comment by randi274** [comment]
Is anyone still encountering this error who found that renaming the component/file wasn't able to fix it for you?

**Comment by slaght** [comment]
I am encountering this error. Running `sfdx force:source:push -f --loglevel fatal`. I removed almost everything from my `force-app` folder to see if a specific piece of metadata was causing this failure, but even pushing one piece of Application metadata that I know is well-formed causes this. For reference this is a new scratch org that I recently pushed a codebase to. One thing I notice is that when I run the command with a subset of the metadata, the deployment progress correctly shows the number of components being pushed, but the process takes a very long time, and then finally updates to several hundred components as it completes. How can I pull specific debug information like the original poster? Nothing else is shown in my terminal other than `ERROR running force:source:push:  Cannot read properties of undefined (reading 'split')`

**Comment by randi274** [comment]
@slaght if you go to Help > Developer Tools in VS Code, you usually can see additional information on the source of an error. You can also try running the command with `--json` to get a fuller output. Is there any chance you can provide us with a repo that's experiencing the issue so that we might be able to reproduce it?

**Comment by LKozakewycz** [comment]
I've been getting this error when pushing as well.

`{                                                                                                                                                                                                       
  "status": 1,
  "name": "Type",
  "message": "Cannot read properties of undefined (reading 'split')",
  "exitCode": 1,
  "context": "Push",
  "stack": "Type: Cannot read properties of undefined (reading 'split')\n    at Function.wrap (C:\\Users\\Luke\\AppData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\node_modules\\@salesforce\\core\\lib\\sfError.js:61:25)\n    at Push.catch (C:\\Users\\Luke\\AppData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\node_module
s\\@salesforce\\command\\lib\\sfdxCommand.js:267:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Push._run (C:\\Users\\Luke\\AppData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:93:13)\n    at async Config.runComman
d (C:\\Users\\Luke\\AppData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async SfdxMain.run (C:\\Users\\Luke\\AppData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async SfdxMain._run (C:\\Users\\Luke\\Ap
pData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\Luke\\AppData\\Local\\sfdx\\client\\7.161.0-7a9b98c\\dist\\cli.js:162:47)",
  "warnings": [],
  "commandName": "Push"
}
`

**Comment by randi274** [comment]
@LKozakewycz are you seeing this issue when running the command with the CLI directly too? If you can reproduce with the CLI, we recommend opening an issue [here](https://github.com/forcedotcom/cli/issues). Also, [this one](https://github.com/forcedotcom/cli/issues/1647) looks to have a similar root cause.

**Comment by LKozakewycz** [comment]
@randi274 I don't use VSCode - I use Illuminated Cloud but I also gave it a shot using the CLI alone with the json flag to get that response above.

The only way for me to fix the issue is by creating a new org and pushing the entire source in to that instead.

**Comment by klewis-sfdc** [comment]
Thank you for confirming the behavior when running via the CLI @LKozakewycz.  Would you mind opening an Issue with the JSON response you received above against the CLI repo? (https://github.com/forcedotcom/cli/issues)

Thank you!

**Comment by paustint** [comment]
Every time I have received this error it was because some file in the project was not setup correctly (e..x missing metadata file, invalid metadata file contents, invalid folder structure, etc..).

Unfortunately I was never able to figure out a way to how to get any additional information in the error to pinpoint what might be the cause.

**Comment by LKozakewycz** [comment]
Thanks guys posted a new issue: 
https://github.com/forcedotcom/cli/issues/1668


@paustint I have seen the error being thrown due to missing metadata file previously. My issue has not been the result of that unfortunately so I can't work it out. It would be nice to get through the CLI error so we could be given a meaningful error we can work with.

**Comment by slaght** [comment]
> @slaght if you go to Help > Developer Tools in VS Code, you usually can see additional information on the source of an error. You can also try running the command with `--json` to get a fuller output. Is there any chance you can provide us with a repo that's experiencing the issue so that we might be able to reproduce it?

Sorry for the super long delay, missed some notifications. Unfortunately this occurred in a private project repo that I can't share, but I found the resolution was just recreating my project and scratch org, so I imagine this was actually on me for getting my local sfdx source tracking screwed up somehow.
