### ISSUE TITLE
Error message when VS Code is loading a SFDX project

### ISSUE THREAD

**Issue by AngelMtz97** [forcedotcom/salesforcedx-vscode#4068]
### Summary

When I open a sfdx project folder in vscode I am getting the following error message

"No sfdx-project.json found in the root directory of your open project. Open a Salesforce DX project in VS Code."

### Steps To Reproduce:

1.  Open a sfdx project in vscode
2. The Salesforce CLI extension is not loading
3. Open the Command Palette
4. Select: SFDX: Create Project with manifest
5. "Activating extension" message appears
6. You will se an error notification window

### Expected result

I should not be seeing any error message if the opened folder is a SFDX project folder.

### Actual result

I get an error message and the salesforce CLI integration is not working

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/51268614/165686243-6cc57b82-2292-4637-9eaa-5ac0a11fe647.png)

![image](https://user-images.githubusercontent.com/51268614/165686337-cb31cc6b-7567-4c12-8985-7158db6c147e.png)

![image](https://user-images.githubusercontent.com/51268614/165686475-da468dc1-da33-4f66-8d40-39167db817cd.png)

![image](https://user-images.githubusercontent.com/51268614/165686635-bee31c6e-a789-41b3-8ac4-1bc7d0e2c0e8.png)

**VS Code version:** 1.66.2

**Commit:** dfd34e8260c270da74b5c2d86d61aee4b6d56977
**Date:** 2022-04-11T07:46:01.075Z
**Electron:** 17.2.0
**Chromium:** 98.0.4758.109
**Node.js:** 16.13.0
**V8:** 9.8.177.11-electron.0
**OS:** Windows_NT x64 10.0.19044

**Salesforce Extension Pack:** 54.9.0 - April 21, 2022

**sfdx-cli/7.147.1 win32-x64 node-v16.14.2**:

**Windows 10 Pro 21H2**:

**Comment by AnanyaJha** [comment]
Hi @AngelMtz97 are you still experiencing this issue?

**Comment by AngelMtz97** [comment]
> Hi @AngelMtz97 are you still experiencing this issue?

Hello @AnanyaJha I changed my laptop for another one, because was too difficult find the cause, I try reinstalling VS Code, Salesforce CLI, Salesforce Extension Pack, but it didn't work. As an aside, my co-worker also ran into the same problem shortly after, while we were working on the same project. Thank you for your reply.

**Comment by gbockus-sf** [comment]
@AngelMtz97 Sorry for the long delay.  I've assigned this issue to myself so we can get it to resolution.  

As a test if you clone a sample repo (like [ebikes](https://github.com/trailheadapps/ebikes-lwc)) Do you experience the same issue?  

Is there a `.sfdx` directory present in your project?

**Comment by AngelMtz97** [comment]
Hello, @gbockus-sf thanks for your response, and I am very sorry, but actually I am not working with the same project mentioned in my reported issue, and I am not able to reproduce the error anymore, how can we handle this situation?.

**Comment by gbockus-sf** [comment]
No worries.  I'll just close this issue for now and if it ever reappears just let us know.  I suspect it was either something about how the cli was configured or a permissions issue with project. Thanks for the quick response.
