### ISSUE TITLE
I am not anle to connect with my Org

### ISSUE THREAD

**Issue by ranjithg1203** [forcedotcom/salesforcedx-vscode#4085]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by AnanyaJha** [comment]
Hi @ranjithg1203 please provide more information about the issue you're experiencing and what version of the Salesforce Extensions you're working with. Thanks!
