### ISSUE TITLE
How to run vs code site to other device.....

### ISSUE THREAD

**Issue by Saquib-azmi** [forcedotcom/salesforcedx-vscode#4089]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by gbockus-sf** [comment]
HI @Saquib-azmi could you expand on your question?   I'm not sure what you are asking. Please reopen if you still need help.
