### ISSUE TITLE
Refresh SObject Definitions in Trailhead org

### ISSUE THREAD

**Issue by anthonygiuliano** [forcedotcom/salesforcedx-vscode#4093]
### Summary

Refresh SObject Definitions failing for Standard Objects when running against a Trailhead org

### Steps To Reproduce:

1.  Create trailhead playground
1.  Create vscode project
1.  Authorize via CLI and set new trailhead playground as default for project
1.  SFDX: Refresh SObject Definitions
1.  Choose Standard Objects (or All Objects)

### Expected result

Successfully refresh object definitions

### Actual result

```
Starting SFDX: Refresh SObject Definitions

10:22:12.962 sfdx sobject definitions refresh
Failure performing sObject describe aborted
10:22:22.828 sfdx sobject definitions refresh
 ended with error Failure performing sObject describe aborted
```

### Additional information

Refresh SObject Definitions for Custom Objects works as expected.

**Salesforce Extension Version in VS Code**:

Name: Salesforce Extension Pack
Id: salesforce.salesforcedx-vscode
Description: Extensions for developing on the Salesforce Platform
Version: 54.11.0
Publisher: Salesforce
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

**SFDX CLI Version**:

sfdx-cli/7.149.1 darwin-arm64 node-v16.15.0

**OS and version**:

MacOS 12.3.1 (21E258)

**Comment by klewis-sfdc** [comment]
Hi @anthonygiuliano - thanks for submitting the issue.  I have been unable to repro so far, as I have been able to successfully connect to a Trailhead Playground org and refresh Standard Objects.  Do you see anything downloaded to .sfdx/tools/sobjects/standardObjects?  Or is that directory empty after getting the "Failure performing sObject describe aborted" error?
