### ISSUE TITLE
SFDX : Diff File Against Org - Never stop running

### ISSUE THREAD

**Issue by floperrin** [forcedotcom/salesforcedx-vscode#4117]
### Summary

I'm trying to compara my apex class in local with the one on the Saelsforce org.
When I use the functionnality "SFDX : Diff File Against Org", the process never ends and I have no result.

### Steps To Reproduce:

1. Open VisualStudio Code
2. Connect to an Org
3. Retrieve all Apex classes
4. Open one of them (in your local) with VS.
5. Right clic : SFDX : Diff File Against Org

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

### Expected result

A comparaison between the apex class in my local and the one in the connected Salesforce Org.

### Actual result

Nothing happens. The process is still running without ending.

### System Information

sfdx-cli/7.101.0 win32-x64 node-v16.0.0

### Additional information
![bug-VS-CLI](https://user-images.githubusercontent.com/83406271/168092872-2be1010c-cb0d-41bb-83aa-91ac81d3ebb8.png)

See the screenshot

**Comment by klewis-sfdc** [comment]
Hi @floperrin, thanks for submitting the issue.  I am so far unable to reproduce.  It does look like you are on an older version of the sfdx cli.  Are you able to update to the latest (`sfdx update`) and see if you encounter the same issue?
