### ISSUE TITLE
Apex Replay Debugger displays List variables as strings

### ISSUE THREAD

**Issue by jdgirald** [forcedotcom/salesforcedx-vscode#4131]
### Summary

Apex Replay Debugger sometimes displays List variables as strings, making it difficult to inspect the items inside the List.

### Steps To Reproduce:

1.  Open a test class
2.  Set a checkpoint and Click `Debug Test`
3.  The *Run and debug* panel display the Local variables information

### Expected result

Local variables of type `List` should be displayed as tree

![image](https://user-images.githubusercontent.com/45671148/168194263-00d9d7bd-f76f-4924-9b1c-bbe3a7bd08e7.png)

### Actual result

Sometimes the variable is formatted as a string

![image](https://user-images.githubusercontent.com/45671148/168194752-a2a2b731-a505-4c9f-9eba-969d34af31cd.png)

**Salesforce Extension Version in VS Code**: v54.12.0

**SFDX CLI Version**: 7.149.1

**OS and version**: Ubuntu 20.04

**Comment by jeffb-sfdc** [comment]
I verified that this is what we get.  This may be due to a limitation of what we get back from the Apex debugger, but it's worth looking into.  This appears to be an issue with arrays, List<>, and Map<>:

```
        Account[] oldAccountsArray = [SELECT Id, Description FROM Account ORDER BY CreatedDate ASC LIMIT 5];
        List<Account> oldAccountsList = [SELECT Id, Description FROM Account ORDER BY CreatedDate ASC LIMIT 5];
        Map<Id,Account> mapOfOldAccounts = new Map<Id,Account>(oldAccounts);
```

**Comment by randi274** [comment]
@jdgirald have you tried using the Checkpoint feature? That might help you get the information that you're looking for: https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger

**Comment by jdgirald** [comment]
> @jdgirald have you tried using the Checkpoint feature? That might help you get the information that you're looking for: https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger#set-breakpoints-and-checkpoints

thanks @randi274, yes I am aware of that feature. It was more related to the fact that sometimes we see the List variable formatted as a string and sometimes it is shown as a tree, it is random and it happens when setting a breakpoint or stepping over
