### ISSUE TITLE
Problem Matcher has leading backslash in path

### ISSUE THREAD

**Issue by jamesprevallet** [forcedotcom/salesforcedx-vscode#4132]
Issue Type: <b>Bug</b>

1.  Deploy an APEX class with an error
2.  Note the path in the Output tab
3.  Compare the path to the Problems tab
Expected:  Path is the same
Actual:  Path in Problems tab has a leading backslash
Result:  Clicking the link on the problem matcher does not open the source file with the problem.

Extension version: 54.12.0
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.59GB (7.92GB free)|
|Process Argv|--crash-reporter-id 3749d332-ba64-4ea0-8a79-394675086b06|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by klewis-sfdc** [comment]
Closing as fixed by https://github.com/forcedotcom/salesforcedx-vscode/pull/4241. Please feel free to re-open if this issue persists after the next release. Thank you!
