### ISSUE TITLE
Org Browser (VS Code) Retrieve CustomSite Source From Org Not Working

### ISSUE THREAD

**Issue by Richman7** [forcedotcom/salesforcedx-vscode#4138]
When using the Org Browser in VS Code to retrieve CustomSite metadata from the org (clicking the cloud with downward arrow), it won't do anything. The output looks like this (nothing in between the following two lines):
_timestamp_ Starting SFDX: Retrieve Source from Org

_timestamp_ ended SFDX: Retrieve Source from Org

When using the terminal with this command: 'sfdx force:source:retrieve -m CustomSite', the metadata does get retrieved.

**Comment by klewis-sfdc** [comment]
Hi @Richman7,

The VS Code Extensions are now using a more up-to-date version of the library that retrieves these components.  When I try this operation now I am able to successfully download custom sites.  

<img width="800" alt="2022-09-08_14-28-42" src="https://user-images.githubusercontent.com/46458081/189229586-a15ab937-bb12-4a83-a7d1-660914768738.png">

I am going to close this issue now as fixed, but please feel free to comment/re-open if you are still encountering this issue.  Thanks!
