### ISSUE TITLE
I have installed the extension but still the aura component tags are not highlighted

### ISSUE THREAD

**Issue by AkhileshHN** [forcedotcom/salesforcedx-vscode#4160]
![image](https://user-images.githubusercontent.com/60725930/170238806-5eedb2a8-39ad-4b46-abfe-39ebd3905696.png)

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

Aura component file syntax is not highlighted

### Actual result

.cmp file contents is not recognised

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by AnanyaJha** [comment]
Hi @AkhileshHN can you share what version of the Salesforce Extensions you're currently using? This can be found by navigating to the Marketplace tab via the icon on the left side panel. Once you're in the marketplace, search for `Salesforce Extensions` and take a look at the version specified on the Extension homepage. Thanks!

**Comment by AkhileshHN** [comment]
Thank you for the response, Ananya Jha,
The issue is resolved and everything is working fine.

Regards Akhilesh HN
