### ISSUE TITLE
Bug due to Apex Interactive Debugger (Extension)

### ISSUE THREAD

**Issue by epincas** [forcedotcom/salesforcedx-vscode#4166]
### Summary

I am unable to use sfdx any more with my personal MacOS Catalina 10.15.7.
It's been working fantastically well until a week ago. I am not sure of the root cause.

From Terminal, **when attempting to run sfdx commands, these are not recognised**. Example, ...
... when running sfdx --version
... I am getting this **error message:** /Users/myUsername/.local/share/sfdx/client/bin/sfdx: line 16: /Users/myUsername/.local/share/sfdx/client/bin/../7.132.0-6621068/bin/sfdx: **No such file or directory**

From VSC, when opening the folder where my Salesforce Project is stored, VSC is displaying the error shown below on the screen-shot (Source: Apex Interactive Debugger(Extension)).

Also, when trying to give the project access to the environment by running SFDX: Authorize an Org, I am getting an error "Authorize an Org failed to run" (see second screen-shot below).

I have uninstalled Salesforce Extensions Pack and VSC.
I have reinstalled Salesforce CLI for Mac and have tried to run a command such as 'sfdx' but the Salesforce CLI is not recognised.

### Steps To Reproduce:

1.  Start/Open Visual Studio Code for Mac and open a folder where my salesforce project is stored.
(normally, VSC would automatically connect to the environment, but now, it has recently stopped doing so)

### Expected result

Visual Studio Code should load the extension without issues.

### Actual result

The following error is displayed by VSC: "Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log."

Source: Apex Interactive Debugger (Extension)

### Additional information

<img width="463" alt="image" src="https://user-images.githubusercontent.com/4534431/170727883-e9151e2e-73fc-48bc-882a-095f5e1fe88e.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/4534431/170831178-70e70375-cc38-440d-84cd-2d850182d934.png">

**Salesforce Extension Version in VS Code**:
Apex Interactive Debugger v54.12.0

**SFDX CLI Version**:
Salesforce CLI Integration v54.12.0

**OS and version**:
MacOS Catalina 10.15.7

**Laptop specs**:
MacBook Pro (Retina, Mid 2012)
Processor: 2,6 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1 GB
Intel HD Graphics 4000 1536 MB

**Comment by epincas** [comment]
Hello,

I have searched for folders "sfdx" in my Mac in order to cleans/delete potential garbage CLI prior installations.
After that, I have reinstalled Salesforce CLI for Mac and am now getting this error when running sfdx from Terminal:

/Users/myUserName/.local/share/sfdx/client/bin/sfdx: line 16: /Users/myUserName/.local/share/sfdx/client/bin/../7.132.0-6621068/bin/sfdx: No such file or directory 

It would be great if you could help with this issue.

Thank you very much.

**Comment by klewis-sfdc** [comment]
Hi @epincas, 
Are you still having these same issues getting VSC Extensions and SFDX CLI to work?  If so, do the issues still occur after updating the VSC Extensions to the latest version (55.8)?
