### ISSUE TITLE
SFDX Retrieve/Deploy doesn't use SF CLI?

### ISSUE THREAD

**Issue by perryton** [forcedotcom/salesforcedx-vscode#4168]
If I recall correctly, years ago, the SF CLI Integration extension used to use/run SF CLI command when right-clicking on a file and selecting SFDX: Retrieve Source from Org in VS Code.  What does the current version do/use now when retrieving?  Can I configure it to use SF CLI again?

**Comment by floralan** [comment]
Hi @perryton, up to now, we are still using SFDX CLI commands for retrieving and deploying source data. If you find any issues with it, we'd appreciate your feedback.

**Comment by floralan** [comment]
Hi @perryton, deploy and retrieve now are calling the library instead of CLI. We had removed the experimental setting [#3580](https://github.com/forcedotcom/salesforcedx-vscode/pull/3580). If you find any perform regression related to the current deploy and retrieve, we'd appreciate your feedback.

**Comment by prateekamana** [comment]
I'm sorry but what exactly is "Library" and how is it a substitute to the CLI? 🤔

**Comment by gbockus-sf** [comment]
We've been moving to using shared libraries instead of utilizing the cli directly in the vscode extensions for a while as there is a performance cost to starting the cli process (also we hope to one day make the extensions install not depend on having the cli installed).  

The shared library in this case is the [source-deploy-retrieve library](https://github.com/forcedotcom/source-deploy-retrieve).  It is used by both the vscode extensions and cli to do the deploy/retrieve operations.  

There is currently no option to use the CLI for doing sync operations.  
Is there functionality that is impacted for you b/c of this decision?
  What's missing that you'd like to get from using the CLI under the hood instead of the shared lib code?

**Comment by perryton** [comment]
Hi @floralan.  I also would like to understand what "the library" is and how it can be configured.

My issue is I don't know how to configure the latest extension to trust/use my internal organization's CA certificates on Windows 10.

I am able to configure SF CLI to trust/use our CA certs by creating a system variable, NODE_EXTRA_CA_CERTS, and pointing it to a file containing the certs in PEM format.  So, when downgrading the extension to 53.0.1 and unchecking that experimental setting, a retrieve works through the VS Code GUI (right-clicking on a file and selecting SFDX: Retrieve Source from Org).

However, with the experimental setting checked on, it doesn't work.  I get an "unable to verify first certificate" error.

Please advise.  Thanks.

**Comment by perryton** [comment]
Thanks for the responses. @gbockus-sf and @jeffb-sfdc 

So, I guess I'm wondering now, why it appears that the NODE_EXTRA_CA_CERTS variable doesn't work with the latest extension, when it works with the SF CLI?

Is there a different method of extending the list of trusted CA certs that I need to use with the latest extension?

**Comment by gbockus-sf** [comment]
@perryton my apologies on the slow response.  This is not something we were tracking on the vscode side.  I'll mark this as a bug so it's raised up internally as something we need to address. FYI @AnanyaJha

**Comment by danacoder** [comment]
@floralan, I just updated to the latest version after using an older version for a while. My "Diff File Against Org" in a sandbox is incredibly slow now. I just ran a test retrieve command

sfdx force:source:retrieve --sourcepath force-app/main/default/classes/MyClassName.cls --dev-debug --loglevel=trace

I see a lot of the following:

  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +628ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +601ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +579ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +666ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +859ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +607ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +598ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +602ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +673ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +638ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +581ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +598ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +635ms
  sf:MetadataApiRetrieve DEBUG MDAPI status update: Pending +588ms
  ...

We just refreshed our sandbox from production as well. Prior to the refresh things were fast in our sandbox.

**Comment by CristiCanizales** [comment]
Hi @perryton, sorry for the long waiting. Could you please install these vsixes [`VS Code Extensions`](https://github.com/forcedotcom/salesforcedx-vscode/suites/18570183539/artifacts/1078689514), open vscode settings, set the new setting salesforcedx-vscode-core: NODE_EXTRA_CA_CERTS and check if it works for you? 
<img width="590" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/7bf19b1c-73ef-4a84-ab03-9a7a3602e611">
Thanks in advance!
