### ISSUE TITLE
Release .vsix files as part of your releases

### ISSUE THREAD

**Issue by LeviticusNelson** [forcedotcom/salesforcedx-vscode#4184]
**Is your feature request related to a problem? Please describe.**
https://github.com/williamboman/nvim-lsp-installer/issues/701#issuecomment-1145082322
**Describe the solution you'd like**
This file in particular would help create an LSP for the neovim plugin lsp-config

**Comment by williamboman** [comment]
Even better would be to publish the language server packages as standalone npm packages!

**Comment by randi274** [comment]
We've gotten a lot of requests for this, and actually did make this possible recently with #3900 - let us know if that's what you're looking for.

**Comment by williamboman** [comment]
Ah interesting! I couldn't find any release assets for the [latest release](https://github.com/forcedotcom/salesforcedx-vscode/releases/tag/v54.15.0), and so I assumed assets weren't uploaded. It does seem like the [previous release](https://github.com/forcedotcom/salesforcedx-vscode/releases/tag/v54.12.0) have assets. Shouldn't the latest release have some assets or am I missing something?

**Comment by randi274** [comment]
I would take the assets from the v54.12.0 release in that case - we're working to add them in every time, but we've been having some issues with our release automation recently. That should improve soon though, so the vsix files should be available more consistently!

**Comment by gbockus-sf** [comment]
vsixes should be included in releases now.  We had an issue with our release process but it has been resolved.
