### ISSUE TITLE
Deployments for even a single file taking longer than 10 minutes

### ISSUE THREAD

**Issue by adityababbar** [forcedotcom/salesforcedx-vscode#4185]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Right-click on the file to be deployed and click "SFDX:Deploy This Source to Org"

### Expected result

The deployment should not take more than a couple of minutes

### Actual result
The actual deployment time is around 10 mins as can be seen from below logs

10:59:02.806 Starting SFDX: Deploy Source to Org
=== Deployed Source
STATE    FULL NAME   TYPE      PROJECT PATH                                         
───────  ──────────  ────────  ─────────────────────────────────────────────────────
Changed  XYZPage ApexPage  force-app\main\default\pages\XYZPage.page         
Changed  XYZPage  ApexPage  force-app\main\default\pages\XYZPage.page-meta.xml

11:09:41.891 ended SFDX: Deploy Source to Org

### Additional information
As per https://github.com/forcedotcom/salesforcedx-vscode/issues/917, I did not find the option to enable performance enhancement to deploy/release process
![image](https://user-images.githubusercontent.com/4994304/171718703-3c79752f-ff0d-47cf-a447-fce31b613504.png)

**Salesforce Extension Version in VS Code**:
 v54.15.0

**SFDX CLI Version**:
sfdx-cli/7.153.1 win32-x64 node-v16.15.0

**OS and version**:
Windows 10 Pro 
Version 20H2

**Comment by randi274** [comment]
Hi @adityababbar - can you confirm for us if this is happening in any particular org? (Also I wanted to note, the experimental deploy/retrieve setting was removed, as that's enabled by default now!)

**Comment by ekongmmg** [comment]
I'm currently running into this issue with a sandbox.

![image](https://user-images.githubusercontent.com/40400869/200887924-55759c8c-1bf6-4db0-bbe9-c97bf917d848.png)


**Salesforce Extension Version in VS Code:**
vv56.4.1

**SFDX CLI Version:**
sfdx-cli/7.175.0 win32-x64 node-v18.12.0

**OS and version:**
Windows 10 Home
Version 21H2

**SFDC Sandbox**
CS216

**Comment by randi274** [comment]
@adityababbar - can you also confirm if it takes just as long to deploy using the CLI?

**Comment by ekongmmg** [comment]
@randi274 I was able to work with Salesforce Support and it turns out the issue was caused by the "Compile on Deploy" setting being enabled by a 3rd party vendor in the sandbox.

**Comment by adityababbar** [comment]
This issue was resolved though whether it was some update in
VSCode/extension, can't jog my memory.
