### ISSUE TITLE
Problem's are returning errors linking to incorrect file locations giving "The editor could not be opened because the file was not found"

### ISSUE THREAD

**Issue by qwikag** [forcedotcom/salesforcedx-vscode#4194]
### Summary

I recently did a new install of VSCode and SFDX CLI on a new Macbook. So versions are recent. I have updated SFDX since this error but it still exists.

sfdx-cli/7.152.0 darwin-x64 node-v16.15.0
&
sfdx-cli/7.153.1 darwin-x64 node-v16.15.0

**What I am doing:**
I am deploying an Apex Class by Right Clicking on the file in the editor and choosing "Deploy this source to org", I have also used a terminal command to deploy source.

**What is happening:**
Typical errors are being returned into the Problem Log.

**What is the issue:**
However clicking on those errors I get taken to a file that does not exist and get this error (see pics) -

**Due to the forward slash in the file path making the file look like it is at ROOT**

### Steps To Reproduce:

All I did was install VSCode and CLI on MACOS (M1 chip)
create a Project and I get this error
put an error in your code
do a right click deploy
when the Problem returns to the Problem panel
click on the error line and it tries to open a file at the wrong location.

### Expected result

Problem returned by the bad deployed code
returns a line in the Problems panel
but when you click on it it should take you to the annotated line in the file.

### Actual result

click on the error line in the problems panel and it tries to open a file at the wrong location.

**Due to the forward slash in the file path making the file look like it is at ROOT**

### System Information

{
        "cliVersion": "sfdx-cli/7.152.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.0 (core)",
                "apex 0.12.0 (core)",
                "auth 2.0.2 (core)",
                "community 1.1.4 (core)",
                "config 1.4.6 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 2.0.0 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.0 (core)",
                "limits 2.0.0 (core)",
                "org 1.13.1 (core)",
                "salesforce-alm 54.4.0 (core)",
                "schema 2.1.0 (core)",
                "sfdx-cli 7.152.0 (core)",
                "sfdx-git-delta 5.2.0",
                "signups 1.1.1 (core)",
                "source 1.9.9 (core)",
                "telemetry 2.0.0 (core)",
                "templates 54.7.0 (core)",
                "trust 1.1.0 (core)",
                "user 2.0.0 (core)"
        ],
        "osVersion": "Darwin 21.5.0"
}

### Additional information

opens the wrong file due to the extra forward slash in the files path
**Due to the forward slash in the file path making the file look like it is at ROOT**

this image shows sfdx on top and PMD below
PMD is working ok

![](https://i.stack.imgur.com/F3xxe.png)

Next I will upgrade to the latest>
but I saw nothing about this error to suggest this is fixed>
is there is a published fix I would love to be pointed at the published fix.

![](https://i.stack.imgur.com/ez350.png)

I have also written it up in stackexchange if someone wants to answer it there too.
[https://salesforce.stackexchange.com/q/377152/38277](https://salesforce.stackexchange.com/q/377152/38277)

**Comment by qwikag** [comment]
I have seen this error around other extensions, the VSCode extensions seems to transfer back again so transferring it could be a merry go round.
My understand is the issue is with the specific extension.
hence my picture shows PMD working just fine.

But hey I am not the expert. Collaboration with them would surely help in some way.
So thanks!

**Comment by qwikag** [comment]
I updated sfdx:
problem still exists
{
        "cliVersion": "sfdx-cli/7.153.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.1 (core)",
                "apex 0.13.0 (core)",
                "auth 2.0.3 (core)",
                "community 1.1.5 (core)",
                "config 1.4.7 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 2.0.2 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.4.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.153.1 (core)",
                "sfdx-git-delta 5.2.0",
                "signups 1.1.2 (core)",
                "source 1.10.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 54.8.0 (core)",
                "trust 1.1.0 (core)",
                "user 2.0.2 (core)"
        ],
        "osVersion": "Darwin 21.5.0"
}

**Comment by klewis-sfdc** [comment]
Closing as fixed by #4241.  Please feel free to re-open if this issue persists after the next release.  Thank you!
