### ISSUE TITLE
Enable developers to quickly bump apiVersion in vscode and sfdx

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#4198]
**Is your feature request related to a problem? Please describe.**
From time to time developers have to bump apiVersion in multiple metadata files in a folder/project. Depending on the amount of files, this can take some time. 

**Describe the solution you'd like**
It would be nice to have a command that bump api version in multiple files at once. This command could accept a directory path, then iterate recursively over that directory tree to update any apVersion key to a given api version. This command could be added to sfdx so we could also automate this in our CICD pipelines. For instance, I could open a PR with a certain title and description that would automatically bump certain files in a path to a particular apiVersion.

**Describe alternatives you've considered**
- bump each file within a particular folder/project one by one by hand. 
- bump each file within a particular folder/project with a script.

**Additional context**
N/A

**Comment by AnanyaJha** [comment]
Thanks for sharing @AllanOricil! We'll keep this in mind for a future iteration. Would it be useful to have this available via the command palette - as something like "Update API Version across Project" that allows you to enter in the API version to upgrade to? Or would it be more useful via the CLI for CI/CD pipelines as you mentioned

**Comment by AllanOricil** [comment]
I believe you guys should create an sfdx plugin first. And after that you could also create a new vscode command. The only inputs I see are: 

- desired api version => you should allow any possible api value here.
- path => any metadata within this path would be updated to a desired api version. For instance, I can have a mono repo with multiple projects inside the same src folder. Then inside the classes folder I can have multiple folders to separate each set of apex classes of a particular project. And maybe I just want to update the api version of one of these projects rather than every file inside the classes folder.  So, for this use case, I would pass "/src/default/main/classes/project_1" to the path flag. When no value is passed to this flag, every metadata file in the current working dir should be updated.
- exclude | include_metada_types | _files => maybe I don't want to update a certain type of metadata or specific set of files? Not really sure if this would be useful. You would have to add telemetry on this.

And when this sfdx plugin is ready, you could start thinking about how the vscode command would look like. You should also try to telemetry how many people are actually using this command, and how often it is used. Maybe people prefer to bump metadata files by hand.

**Comment by AllanOricil** [comment]
This can be done with regex and replaceAll

**Comment by gbockus-sf** [comment]
@AllanOricil thanks for the follow up.  Would you mind providing a more detailed work around that you used to accomplish this task?   Did you do the find/replace in VSCode or on the command line?  Do you have the regex handy that you used to find all the occurrences that you care about? Thanks!

**Comment by aheber** [comment]
Here is the instructions we have, includes regex and find scopes. Hope it helps.

### Update Project API Version
`./sfdx-project.json` increment API version

To list all items not on the target API version you can search in VS Code with `<apiVersion>(?![NEW VERSION])\d+.\d</apiVersion>`

### Apex Classes and Triggers
Find:`<apiVersion>.*</apiVersion>`
Replace:`<apiVersion>[NEW VERSION]</apiVersion>`
Files to include: `*.{cls,trigger}-meta.xml`

### VisualForce Pages
Find:`<apiVersion>.*</apiVersion>`
Replace:`<apiVersion>[NEW VERSION]</apiVersion>`
Files to include: `*.page-meta.xml`

### VisualForce Components
Find:`<apiVersion>.*</apiVersion>`
Replace:`<apiVersion>[NEW VERSION]</apiVersion>`
Files to include: `*.component-meta.xml`

### Lightning Web Components
Find:`<apiVersion>.*</apiVersion>`
Replace:`<apiVersion>[NEW VERSION]</apiVersion>`
Files to include: `*.js-meta.xml`

### Aura Components
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_ls_disable.htm

> Disable Lightning Locker for an Aura component by setting the Salesforce API version to 39.0 or lower for the component. If a component is set to at least API version 40.0, Lightning Locker is enabled.

This causes us to exclude anything whose version is lower than 40 in our RegEx matching expression.

Find:`<apiVersion>[4-9].*</apiVersion>`
Replace:`<apiVersion>[NEW VERSION]</apiVersion>`
Files to include: `*.cmp-meta.xml`

### Flows & Bots
Source Retrieve Flows & Bots from Prod to automatically update the API Version and to bring in any new features/lines with the new version.

**Comment by AllanOricil** [comment]
![image](https://user-images.githubusercontent.com/55927613/172949779-34fe963a-f525-4c26-9695-b62dc49692e3.png)
