### ISSUE TITLE
when open the vs code application some times default org not be opened, sometimes it will take too much of time around 30 min.

### ISSUE THREAD

**Issue by salesforcekumar** [forcedotcom/salesforcedx-vscode#4200]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by AnanyaJha** [comment]
Hi @salesforcekumar please share more details about the type of problem you're facing. What version of VS Code and the Salesforce Extensions are you using? Please open a new issue with all the information, thank you!
