### ISSUE TITLE
Create a Lightning Web Component(Create a scratch Org)  In this I am getting this type of error

### ISSUE THREAD

**Issue by Prasad-jii** [forcedotcom/salesforcedx-vscode#4201]
18:00:21.109 sfdx force:org:create -f config\project-scratch-def.json --setalias trailhead --durationdays 7 --setdefaultusername --json --loglevel fatal
18:00:28.936 sfdx force:org:create -f config\project-scratch-def.json --setalias trailhead --durationdays 7 --setdefaultusername --json --loglevel fatal
 ended with exit code 1

The requested resource does not exist

**Comment by AnanyaJha** [comment]
Hi @Prasad-jii can you share what version of the Salesforce Extensions you're facing this issue with? This can be found by clicking on the Marketplace icon on the left activity bar in VS Code. Search for 'Salesforce Extensions' and take a look at the version number listed on the extensions homepage. Thank you!

**Comment by randi274** [comment]
Hi @Prasad-jii, as we haven't heard from you yet on this issue, I'll go ahead and close it for now. If you're still facing problems, please let us know your answer to the question above. Thanks!
