### ISSUE TITLE
Salesforce CLI extension causing issue even after updating

### ISSUE THREAD

**Issue by samiksha2512** [forcedotcom/salesforcedx-vscode#4209]
### Summary
Salesforce CLI extension causing issue even after updating

### Steps To Reproduce:

Open Visual Studio Code.
create a new lightning component and save it.
right click and select deploy to source org.
Actual : The deployment popup keeps loading without showing any success or failure message.
Expected : The component should deploy

### Additional information
For more info- https://github.com/microsoft/vscode/issues/152065

**Salesforce Extension Version in VS Code**: V55.0.0

**SFDX CLI Version**: 7.154.0-1c265b4

**OS and version**: Windows 10

**Comment by randi274** [comment]
Hi @samiksha2512 are you able to deploy other components to the org? What type of org are you using?
