### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by luisbarajascharly** [forcedotcom/salesforcedx-vscode#4217]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.0.0`
- OS Version: `Windows_NT ia32 10.0.19043`
- VS Code version: `1.68.1`

SFDX: Retrieve Source from Org failed to run

**Comment by gbockus-sf** [comment]
HI @luisbarajascharly 
Could you provide the error message that is displayed in the Output panel when you attempt the retrieve? 

What version of sfdx do you currently have installed on your system? `sfdx -v` from the command line. 
Thanks!
