### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rahulreddykothapally** [forcedotcom/salesforcedx-vscode#4226]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `55.0.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by gbockus-sf** [comment]
@rahulreddykothapally Closing due to lack of info.  Please reopen and provide the details if you continue to have an issue. Thanks.
