### ISSUE TITLE
Error message when clicking on Apex error : 'The editor could not be opened because the file was not found.'

### ISSUE THREAD

**Issue by warlockdthpunch** [forcedotcom/salesforcedx-vscode#4228]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Create a project with manifest.
2. Authorize and Org
3. Write an Apex code that has a few errors in it and save it.
4. Right click on the file and select SFDX: Deploy Source to Org
5. Click on any of the issues that show in the VS Code PROBLEMS tab.

### Expected result

It should have opened the file with the error and taken me to the row number that had the error.

### Actual result

Error message pops up on a different tab showing the message : 'The editor could not be opened because the file was not found.'

### Additional information

![VS Code error](https://user-images.githubusercontent.com/23403403/175095631-6f5b2005-411e-4e72-a6e4-b4743811341f.jpg)free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:   sfdx-cli/7.155.1 win32-x86 node-v16.15.1

**OS and version**:  
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22000 N/A Build 22000

**Comment by klewis-sfdc** [comment]
Closing as fixed by https://github.com/forcedotcom/salesforcedx-vscode/pull/4241. Please feel free to re-open if this issue persists after the next release. Thank you!
