### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by JesusAGS** [forcedotcom/salesforcedx-vscode#4237]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.2.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 10380,
		"activateCallTime": 37,
		"activateResolvedTime": 11597,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by gbockus-sf** [comment]
HI @JesusAGS 
Could you provide more information on the bug you are seeing? Thanks

**Comment by AnanyaJha** [comment]
Hi @JesusAGS feel free to open a new issue with more details on the problem you're facing. Closing this for now, thanks!
