### ISSUE TITLE
force:config:set is not a SFDX command

### ISSUE THREAD

**Issue by JoshBeeHome** [forcedotcom/salesforcedx-vscode#4256]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by gbockus-sf** [comment]
@JoshBeeHome typically the "is not a command" error occurs when the extension fails to load properly.

You can check the output panel (Log (Extension Host), Salesforce CLI) to see if there are any startup errors reported.  
![Screen Shot 2022-07-09 at 12 07 43 AM](https://user-images.githubusercontent.com/76090802/178092461-f2d7c5df-1547-476c-a146-7365a6ceff11.png)

Also it'd be interesting to see what processes are present in the process explorer (Command Pallet -> Developer: Open Process Explorer
![Screen Shot 2022-07-09 at 12 10 48 AM](https://user-images.githubusercontent.com/76090802/178092533-e2bfc12e-4754-4e99-94ee-205f42fd26c7.png)
