### ISSUE TITLE
SFDX: Deploy to Org not working anymore

### ISSUE THREAD

**Issue by dvanlooy** [forcedotcom/salesforcedx-vscode#4262]
When working in a package.xml project, having apexclass wildcard in use, we cannot deploy to org anymore by selecting a single file to deploy (SFDX:Deploy to Org). We get following error: 

> Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

This error makes no sense as the sfdx-project.json file hasn't changed and mentions the default package location (force-app) and all files are located in child folders in force-app as per default.

**Comment by doug-hynes-salesforce** [comment]
I have the identical issue in two different environments.

**Comment by mayank-1-2** [comment]
I am also having same issue after I have reloaded the VS code
![image](https://user-images.githubusercontent.com/60282634/177995765-af4d5c33-f5e7-4699-8ee4-5a7edb7ceae3.png)

**Comment by prakash-concret** [comment]
I have the same issue after updating to CLI and VS Code Extensions.

**Comment by randi274** [comment]
Thanks y'all for the input here! It looks like we have a few issues opened with the same. Please track #4261 for updates.
