### ISSUE TITLE
Deployment Issue with v55.4.0

### ISSUE THREAD

**Issue by mattjpovey** [forcedotcom/salesforcedx-vscode#4263]
### Summary

The latest version (55.4.0) seems to have broken the right click 'deploy source to org' function.  Now, if I right click an Apex Class (for example) and select 'SFDX: Deploy Source to Org' I get this error:

Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

This was working yesterday.  When I checked extensions, I saw that the version updated 15 hours ago.  I reinstalled version 55.3.0 and now the function is working again.

### Steps To Reproduce:

1.  Right click any metadata item in explorer
2.  Select 'SFDX: Deploy Source to Org'

### Expected result

Source file gets deployed to the authorised Org.

### Actual result

The following error displays

Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

### Additional information

Tried creating a brand new project, authorised an org and tried deploying a class.  Same issue.

**Salesforce Extension Version in VS Code**: 55.4.0

**SFDX CLI Version**: 7.158.1

**OS and version**: Windows 10 64-bit

**Comment by Crysis2015** [comment]
Facing same issue

**Comment by randi274** [comment]
@Crysis2015 are you also working on a Windows machine? This is currently working on my Mac with v55.4.0, but I'm going to retry shortly on Windows.

**Comment by ClemABT** [comment]
Same issue here on a Windows 10 machine.

**Comment by randi274** [comment]
I'm seeing now we have a few issues opened with the same. Please track #4261 for updates.
