### ISSUE TITLE
Erro sfdx command line "Parse error in file unknown on line 2"

### ISSUE THREAD

**Issue by WesleiOliveira** [forcedotcom/salesforcedx-vscode#4275]
Prezados(as), estou encontrando o erro abaixo em todos os comandos do SFDX

PS C:\Salesforce\Salesforce> sfdx force:source:retrieve -m ApexClass:CaseRepository
(node:3276) JsonParseError Plugin: sfdx-cli: Parse error in file unknown on line 2
{
<<<<<<< HEAD
  "tar
module: @oclif/config@1.18.3
task: runHook prerun
plugin: sfdx-cli
root: C:\Program Files\sfdx\client
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR running force:source:retrieve:  Parse error in file unknown on line 2
{
<<<<<<< HEAD
  "tar

**Comment by randi274** [comment]
@WesleiOliveira você também vê esse erro na CLI, fora do VS Code?

**Comment by klewis-sfdc** [comment]
Closing this as it was reported 20+ days ago.  @WesleiOliveira if you are still experiencing the issue please feel free to re-open with specific repro steps.  Thank you!
