### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by RiteshDamco** [forcedotcom/salesforcedx-vscode#4278]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `55.4.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by AnanyaJha** [comment]
Hi @RiteshDamco! Thanks for opening this issue, we need some more information to help you triage what's going on. I'm going to close this for now but please feel free to open a new issue if you are still encountering a problem.
