### ISSUE TITLE
long running command /process SFDX: Deploy Source to Org

### ISSUE THREAD

**Issue by mkulshershtha** [forcedotcom/salesforcedx-vscode#4284]
Hi,
Is there any way to debug the long running Running SFDX: Deploy Source to Org from VS code editor?
I am trying to upload one APEX class to my sandbox but it is not completing. more than 2 hours and it is still executing .

Running SFDX: Deploy Source to Org

![image](https://user-images.githubusercontent.com/106309306/179386111-308fa8ae-e6b4-4605-b185-ba99aa4b721b.png)

**Comment by randi274** [comment]
@mkulshershtha are you able to run the command to deploy using the CLI?
