### ISSUE TITLE
Running SFDX: Deploy Source To Org

### ISSUE THREAD

**Issue by pledbetter-cvet** [forcedotcom/salesforcedx-vscode#4285]
Even in a cloud environment, this takes way too long. Salesforce changed something about a year ago and now even the smallest change to code that has to be pushed to a sandbox takes so long, you can run out for coffee while it executes the command.

**Comment by gbockus-sf** [comment]
HI @pledbetter-cvet 
Can you provide a specific case where it's taking a long time to deploy? 
Attempt a single file deploy and keep track of the amount of time it takes to deploy?  Also If you could copy and paste the output in the Output panel after execution? I just want to try and reproduce the issue. Thanks.

**Comment by pledbetter-cvet** [comment]
10:18:09.22 Starting SFDX: Deploy Source to Org

=== Deployed Source
STATE    FULL NAME                     TYPE       PROJECT PATH                                                            
───────  ────────────────────────────  ─────────  ────────────────────────────────────────────────────────────────────────
Changed  AccountSummaryControllerTest  ApexClass  force-app/main/default/classes/AccountSummaryControllerTest.cls         
Changed  AccountSummaryControllerTest  ApexClass  force-app/main/default/classes/AccountSummaryControllerTest.cls-meta.xml

10:23:37.377 ended SFDX: Deploy Source to Org

This is in VS Code; just a simple change to ONE apex class. Almost 6 minutes. It's like this for everything, regardless of the changes in the class.

**Comment by pledbetter-cvet** [comment]
This issue hasn't happened again since about a day after I first reported it. I haven't changed anything; not sure why it stopped.
