### ISSUE TITLE
Visualforce Page returns status 'Unchanged' when updated via SFDX extension Deploy

### ISSUE THREAD

**Issue by qwikag** [forcedotcom/salesforcedx-vscode#4299]
### Summary
'Unchanged' is an incorrect status

00:12:51.773 Starting SFDX: Deploy Source to Org

=== Deployed Source
STATE      FULL NAME                     TYPE       PROJECT PATH                                                            
─────────  ────────────────────────────  ─────────  ────────────────────────────────────────────────────────────────────────
Created    caseExtensionController       ApexClass  force-app/main/default/classes/caseExtensionController.cls              
Created    caseExtensionController       ApexClass  force-app/main/default/classes/caseExtensionController.cls-meta.xml     
Created    caseExtensionController_Test  ApexClass  force-app/main/default/classes/caseExtensionController_Test.cls         
Created    caseExtensionController_Test  ApexClass  force-app/main/default/classes/caseExtensionController_Test.cls-meta.xml
**Unchanged**  newUserRequest                ApexPage   force-app/main/default/pages/newUserRequest.page                        
**Unchanged**  newUserRequest                ApexPage   force-app/main/default/pages/newUserRequest.page-meta.xml               

00:17:00.377 ended SFDX: Deploy Source to Org

### Steps To Reproduce:

1. in Package.xml 
1. Right Click --> SFDX : Deploy Source in Manifest to Org
1. Success response returned
Visualforce updated but came back with status 'Unchanged'.

### Expected result

Status should be  'Updated' or the like

### Actual result

Status is  'Unchanged' 

### Additional information

sfdx-cli/7.158.1 darwin-x64 node-v16.15.1

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)
alias 2.1.0 (core)
apex 0.13.0 (core)
auth 2.2.2 (core)
community 2.0.0 (core)
config 1.4.12 (core)
custom-metadata 2.0.0 (core)
data 2.0.4 (core)
generator 2.0.2 (core)
info 2.0.1 (core)
limits 2.0.1 (core)
org 2.0.1 (core)
salesforce-alm 54.6.2 (core)
schema 2.1.1 (core)
sfdx-cli 7.158.1 (core)
sfdx-git-delta 5.3.0
signups 1.2.0 (core)
source 2.0.3 (core)
telemetry 2.0.0 (core)
templates 55.0.0 (core)
trust 2.0.1 (core)
user 2.1.0 (core)

MacOS 12.4

**Comment by randi274** [comment]
Hi @qwikag - I tested this just now on a Mac, and was able to see the 'Changed' status set correctly, either deploying individually or with Visualforce pages and other metadata.

Are you seeing the same result when you run the CLI command? Something like `sfdx force:source:deploy -x manifest/package.xml`, where the manifest/package.xml is the path to wherever your manifest file is.
