### ISSUE TITLE
Generate Manifest File command unavailable for source directories not at force-app/**

### ISSUE THREAD

**Issue by marshallvaughn** [forcedotcom/salesforcedx-vscode#4310]
### Summary

Changes introduced in PR #4208 appear to have broken functionality for manifest generation at paths which are not contained in the default `force-app` source directory.

### Steps To Reproduce:

1.  Create a new project with sfdx, with the default source directory at `src`, rather than `force-app`.
1.  Right-click on `src`, and look for the command `SFDX: Generate Manifest File`

### Expected result

`SFDX: Generate Manifest File` is available on any directories containing source, as defined in `sfdx-project.json` — not only subdirectories of `force-app`.

### Actual result

`SFDX: Generate Manifest File` command is only available within the `force-app` directory.

### Additional information

![Screen Shot 2022-07-22 at 11 12 27 AM](https://user-images.githubusercontent.com/5757870/180469764-14abf68a-80c1-429c-8d8f-ff5adb92f8f9.png)

![Screen Shot 2022-07-22 at 11 12 46 AM](https://user-images.githubusercontent.com/5757870/180469793-c8755de6-a9fb-4693-8f79-3ea575b3eda7.png)

**Salesforce Extension Version in VS Code**: v55.6.0

**SFDX CLI Version**: sfdx-cli/7.160.0 darwin-x64 node-v16.16.0

**OS and version**: macOS 12.4 (Monterey)

**Comment by AnanyaJha** [comment]
Hi @marshallvaughn thanks for filing this issue! Can you confirm that you also have the default package directory set as `src` in your `sfdx-project.json`? And to confirm, you'd like the behavior to display the `SFDX: Generate Manifest File` command across all folders within your **default** package directory, as defined in the `sfdx-project.json` file?

**Comment by jdgirald** [comment]
@AnanyaJha I have the same issue. BTW The path (`src/`) is set in the `packageDirectories` in sfdx-project.json. I think the option should be available in any folder and not only in the default path

**Comment by jdgirald** [comment]
seems this was fixed with https://github.com/forcedotcom/salesforcedx-vscode/pull/4411

**Comment by AnanyaJha** [comment]
Addressed with https://github.com/forcedotcom/salesforcedx-vscode/pull/4411
