### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by krishnapradeepgumma-bib** [forcedotcom/salesforcedx-vscode#4314]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `55.6.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.69.2`

MetadataTransferError: Metadata API request failed: Component conversion failed: Method not implemented

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by randi274** [comment]
Hi @krishnapradeepgumma-bib do you have more information around what was happening when you received this error?

**Comment by krishnapradeepgumma-bib** [comment]
> Hi @krishnapradeepgumma-bib do you have more information around what was happening when you received this error?

No other information
