### ISSUE TITLE
Getting Error on running Salesforce Apex Debugger in a log file/apex class.

### ISSUE THREAD

**Issue by abhirup03** [forcedotcom/salesforcedx-vscode#4328]
### Summary

Getting Error on running Salesforce Apex Debugger in a log file/apex class.

### Steps To Reproduce:

1.  Authenticate with a Saleforce Scratch Org which has apex classes. 
2. Debug the apex classes after placing debug points and invoke "Apex Interactive Debugger" for the apex class.
3. Following error is thrown (please refer screenshot) - 

![image002](https://user-images.githubusercontent.com/33601838/181839576-4cdc0d3b-5c59-4449-96c9-2e8227159872.jpg)

### Expected result

Should open the interactive logging and show details of the breakpoint. 

### Actual result

Error is thrown.

### Additional information

NA

**Salesforce Extension Version in VS Code**: NA

**SFDX CLI Version**:  sfdx-cli/7.153.1 win32-x64 node-v16.15.0

**OS and version**: Windows 10

**Comment by randi274** [comment]
Hi @abhirup03 were you able to complete all of the setup steps for the interactive debugger, detailed [here](https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger)?

We also offer our Apex Replay Debugger, which is much easier to work with, and fits a large number of use cases. You can invoke that process through Apex tests or from a log file. It also doesn't require a license to work with. Details on that one [here](https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger).

**Comment by abhirup03** [comment]
Hi @randi274 the customer is using Apex Replay debugger. Sorry for the confusion - I mistakenly wrote it as interactive debugger. The customer tried to debug a log file/test class and experienced the same issue as discussed above. 

The customer is using - Apex Replay Debugger.

**Comment by randi274** [comment]
Sounds good! Are you able to reproduce the issue as well @abhirup03? If you can provide us some steps to reproduce the issue, that will help us be able to troubleshoot and get the issue resolved 👍

**Comment by abhirup03** [comment]
The issue is reproducible on the customers end. @randi274 
And the customer has confirmed that they are using - Apex Interactive Debugger. 

Per your suggestion, I've suggested the customer to use Apex Replay Debugger, but at this point of time they want to move forward with Apex Interactive Debugger. 

I've shared a meeting recording with you internally over Slack which demonstrates the issue.

**Comment by abhirup03** [comment]
The customer decided to go ahead with - Replay Debugger as Interactive Debugger was causing problems. With that being said, I think we are good to close this issue. Thank you @randi274 and @AnanyaJha appreciate all the help on this!

**Comment by randi274** [comment]
Glad to hear they were able to proceed past the issue! If they have any further issues with the replay debugger, they are also welcome to log here directly, as we're an open source project 🎉
