### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by misritush** [forcedotcom/salesforcedx-vscode#4345]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.7.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by AnanyaJha** [comment]
Hi @omkar02032000 thanks for reporting this! Please leave a comment with more details on the problem you're facing. Thanks
