### ISSUE TITLE
Missing error message label for SFDX: Refresh SObject Definitions called twice

### ISSUE THREAD

**Issue by JackVeromeev** [forcedotcom/salesforcedx-vscode#4351]
### Summary

If you call Refresh SObject Definitions before previous finished, an error notification pops up, but is has the next message:

```
!!! MISSING LABEL !!! force_sobjects_no_refresh_if_already_active_error_text
```

It seems that this label was tried to called but is missing in the registry

### Steps To Reproduce:

1.  Use a vscode connected to an org
2. Run SFDX: Refresh SObject Definitions command from a command palette. 
3. During the command is in progress, run it another time from a command palette.

### Expected result

An informative error notification pops up saying that you should wait before previous process of getting SObject definitions finishes or abort it and start a new one.

### Actual result

An error notification pops up with
```
!!! MISSING LABEL !!! force_sobjects_no_refresh_if_already_active_error_text
```

### Additional information

![Screenshot 2022-08-05 at 11 41 20](https://user-images.githubusercontent.com/15068679/183040404-48be5d51-6516-4324-87ba-e7f2f6ac33e9.png)

**Salesforce Extension Version in VS Code**:
v55.8.0

**SFDX CLI Version**:
sfdx-cli/7.162.0 darwin-x64 node-v16.16.0

**OS and version**:
MacOS BigSur version 11.4 (20F71)

**Comment by angela-young** [comment]
Hello @JackVeromeev, I was able to reproduce this bug, and I will have a fix for this soon

**Comment by angela-young** [comment]
Closing as fixed by https://github.com/forcedotcom/salesforcedx-vscode/pull/4353. Let us know if this is still happening after the next release. Thank you!
