### ISSUE TITLE
Not able to deploy source to Org

### ISSUE THREAD

**Issue by TiruvaipatiS1** [forcedotcom/salesforcedx-vscode#4355]
We have written the needed data into <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/A479416/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/A479416/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

--

</body>

</html>

**Comment by TiruvaipatiS1** [comment]
tried change the version to older one, but no luck.

**Comment by AnanyaJha** [comment]
Hi @TiruvaipatiS1 thanks for reporting this! Can you please share more info about the problem you're facing and what version of the Salesforce Extensions you're working with? Thanks!

**Comment by AnanyaJha** [comment]
Closing this issue in favor of your other one with extensions info!
