### ISSUE TITLE
Not able to deploy source to Org

### ISSUE THREAD

**Issue by TiruvaipatiS1** [forcedotcom/salesforcedx-vscode#4356]
Issue Type: <b>Bug</b>

11:13:55.483 Starting SFDX: Deploy Source to Org

write EPROTO 28308744:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Extension version: 55.8.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.56GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/A479416/Source%20Code/Dev1/SalesForceDevelopment/SFDevCode --crash-reporter-id cb644ce9-06b6-4a45-9cc7-3f6c3582ca1a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252

```

</details>

**Comment by randi274** [comment]
Hi @TiruvaipatiS1 a few questions for you:
- Is this error still happening?
- Do you get this error when you try to deploy using the SFDX CLI?
- Do you happen to have any proxy information set for deployment?

**Comment by randi274** [comment]
Realized this was a duplicate, so closing this in favor of #4357
