### ISSUE TITLE
New Setting to Prevent Output Panel from Opening

### ISSUE THREAD

**Issue by robertStrunk** [forcedotcom/salesforcedx-vscode#4365]
**Is your feature request related to a problem? Please describe.**
It is very annoying to me when a successful deploy/retrieve causes the output panel to pop open. It covers up part of my code and I have to manually remove the panel to regain visibility into my code. I have the "deploy on save" functionality enabled so I perform a lot of deployments while coding. We already get a dialog box that says whether or not the deploy/retrieve is a success or failure so opening the intrusive output panel is a little overkill imo. The only time I care about the details of the deploy/retrieve is if there is an error. Undocking that panel helps but it would still be nice to prevent the issue altogether. 

**Describe the solution you'd like**
Create a new setting that allows the user to decide if they want the output panel to display after deploy/retrieve operations are completed. Or maybe even make it smart enough to only show if the operation is unsuccessful. 

**Describe alternatives you've considered**
I've tried resizing the output panel to be very short (vertically) so that when it gets opened it doesn't cover up my file. 

I've also tried undocking the panel that contains the output tab so that it doesn't cover the file anymore. That's the best solution I have found but It would be nice to not have to resort to that. 

**Additional context**
![panel 1](https://user-images.githubusercontent.com/47643610/184408750-4075423e-7bed-44ea-a3bc-5408c320192b.png)

**Comment by CristiCanizales** [comment]
Closing this to keep track of the issue with #4971.
