### ISSUE TITLE
Slack classes do not autocomplete in vscode

### ISSUE THREAD

**Issue by ngawor** [forcedotcom/salesforcedx-vscode#4381]
### Summary

Slack classes do not autocomplete in vscode

### Steps To Reproduce:

1.  Start typing Sla... no autocomplete.
1.  Type Slack... no autocomplete.

### Expected result

There should be an autocomplete of the Slack namespace and underlying file-based classes.

### Actual result

Autocomplete doesn't work

### Additional information

![image](https://user-images.githubusercontent.com/8984824/186009216-38782c54-bc91-4659-a52e-6189588b586c.png)
![image](https://user-images.githubusercontent.com/8984824/186009244-dcf24d56-dfc8-48e5-bc76-87494913c6e8.png)

Dev console: 

![image](https://user-images.githubusercontent.com/8984824/186011383-ffe96171-bfd6-4d11-a87c-876781325787.png)

**Salesforce Extension Version in VS Code**:  Salesforce Extension Pack v55.8.0

**SFDX CLI Version**: sfdx-cli/7.163.0 darwin-x64 node-v16.16.0

**OS and version**: macOS Monterey 12.5

**Comment by csutterlinSFDC** [comment]
We have some devs eager for this, and would be happy to test/assist (or just cheer you on from here).
