### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Nova1392** [forcedotcom/salesforcedx-vscode#4384]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Linux x64 5.4.0-104-generic`
- VS Code version: `1.70.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 17772,
		"activateCallTime": 57,
		"activateResolvedTime": 43667,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by RitamAgrawal** [comment]
@Nova1392 What's the error here? and will you please provide us with the steps to reproduce the error/ bug?
