### ISSUE TITLE
<filterFomula> tag inside <start> tag is missing in .flow-meta.xml file

### ISSUE THREAD

**Issue by Smegal** [forcedotcom/salesforcedx-vscode#4405]
When retrieving flow from sandbox, the file is missing the Entry Condition of Formula type,
![image](https://user-images.githubusercontent.com/20765501/188074211-e8bc4f35-6228-4dbd-ab65-6fbed8bbb154.png)

**Comment by Smegal** [comment]
![image](https://user-images.githubusercontent.com/20765501/188074706-06a66e74-69b2-4a69-bc98-4a12f1b9d3ae.png)

**Comment by jkranz-rk** [comment]
I've seen this happen in the past, and each time it was due to the sfdx-project.json file's apiVersion being outdated and set to a version prior to the release of formulaFilter on start/entry conditions. 

@Smegal, could you check and/or share which apiVersion you're using to retrieve?

**Comment by randi274** [comment]
@Smegal were you able to try @jkranz-rk's suggestion?
