### ISSUE TITLE
Problem with Apex - Salesforce Extension Pack VS Code

### ISSUE THREAD

**Issue by RaffaeleGranato** [forcedotcom/salesforcedx-vscode#4406]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: HELP ME :warning:

For a couple of days, even restarting VS Code I always get the Apex extension in error. I get this notification "The extension 'Apex' took a very long time to complete its last operation and it has prevented other extensions from running."
I attach the .cpuprofile file if it could help.
[exthost-97db32.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/9506602/exthost-97db32.zip)

**Comment by gbockus-sf** [comment]
Tracking this apex resource usage in https://github.com/forcedotcom/salesforcedx-vscode/discussions/4440
