### ISSUE TITLE
apex Extension issue unresponsive startup activation : 1061153

### ISSUE THREAD

**Issue by Nova1392** [forcedotcom/salesforcedx-vscode#4409]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by AnanyaJha** [comment]
Hi @Nova1392! Thank you for opening up an issue with your system info - could you please provide some more information about the issue you're facing?

**Comment by gbockus-sf** [comment]
Tracking this issue in a github discussion https://github.com/forcedotcom/salesforcedx-vscode/discussions/4440
