### ISSUE TITLE
Org Browser unable to retrieve GlobalValueSet

### ISSUE THREAD

**Issue by 49FD7E1E1F** [forcedotcom/salesforcedx-vscode#4415]
### Summary

Org Browser can't retrieve any GlobalValueSets.

### Steps To Reproduce:

1. Have/create a Picklist Value Set
1. Connect to Org in VSCode
2. Open Org Browser
3. Go to GlobalValueSet category
4. Press any of the two buttons to retrieve it

### Expected result

Retrieve the selected GlobalValueSet metadata.

### Actual result
Fails to retrieve.
VSCode "Salesforce CLI" Output panel shows:
```
Starting SFDX: Retrieve Source from Org

=== Retrieve Warnings
FULL NAME               TYPE            MESSAGE                                                                       
──────────────────────  ──────────────  ──────────────────────────────────────────────────────────────────────────────
Review_Root_Cause__gvs  GlobalValueSet  Entity of type 'GlobalValueSet' named 'Review_Root_Cause__gvs' cannot be found

ended SFDX: Retrieve Source from Org
```

### Additional information

The problem is probably from the `__gvs` suffix being included in the request fired by the Org Browser.
I say this because attempting to retrieve using the CLI is successful when omitting the suffix:

```
PS > sfdx force:source:retrieve -m GlobalValueSet:Review_Root_Cause__gvs
Preparing retrieve request... done
=== Retrieved Source

No results found
=== Retrieved Source Warnings

 FILE NAME              PROBLEM
 ────────────────────── ──────────────────────────────────────────────────────────────────────────────
 unpackaged/package.xml Entity of type 'GlobalValueSet' named 'Review_Root_Cause__gvs' cannot be found

PS > sfdx force:source:retrieve -m GlobalValueSet:Review_Root_Cause
Preparing retrieve request... done
=== Retrieved Source

 FULL NAME         TYPE           PROJECT PATH
 ───────────────── ────────────── ────────────────────────────────────────────────────────────────────────────────
 Review_Root_Cause GlobalValueSet force-app\main\default\globalValueSets\Review_Root_Cause.globalValueSet-meta.xml
PS > 
```

**Salesforce Extension Version in VS Code**: 55.8.0

**SFDX CLI Version**: 7.165.0

**OS and version**: Windows 11 Pro, Version 21H2, Build 22000.856

<details><summary>Screenshots</summary>

### How it shows up in the Org Browser:
![org browser](https://user-images.githubusercontent.com/110409973/190094942-24f06c01-bd18-40cb-a9e9-2c32e78fa9c2.png)

### How the Picklist Value Set looks in the org:
![the GVS](https://user-images.githubusercontent.com/110409973/190095160-1819cc0b-63e8-4f84-978b-01cc769125dc.png)

### Demonstrating `__gvs` can't be something named by the user:
![__gvs cant be part of name](https://user-images.githubusercontent.com/110409973/190095179-2eb19721-7de6-4669-ad5d-7b7b4369b636.png)

</details>

**Comment by klewis-sfdc** [comment]
Hi @49FD7E1E1F,

Thanks for reporting the issue.  When I create a global value set and retrieve it via Org Browser on a machine running macOS it works right now.  

Is the value set being retrieved named with a double underscore on the server?  Does the retrieval work if the name of the global value set is modified to remove the double underscore?  The CLI might be splitting on the double underscore, interpreting it as a delimiter for the namespace.

**Comment by klewis-sfdc** [comment]
@49FD7E1E1F Thank you for the additional detail and screenshots!  Very helpful.  It looks like this issue might be caused by [this change](https://help.salesforce.com/s/articleView?id=release-notes.rn_api_global_value_set_suffix.htm&type=5&release=240) in the Winter '23 release.  I am working on reproducing the issue locally and will provide an update when I am able to repro.

**Comment by klewis-sfdc** [comment]
Hi @49FD7E1E1F,
Thanks again for providing the additional information.  I have been able to spin up a pre-release org on Winter '23 and I am still unable to reproduce this error.  When I create a new GlobalValueSet in the org, it does not get a suffix appended and it is successfully retrieved by OrgBrowser.  Can you confirm for me that you are still seeing the same issue when creating a brand new GlobalValueSet?   Thank you for your patience as I work to repro the issue.

**Comment by klewis-sfdc** [comment]
Yes, let's re-open if this change gets added back into the next release in the same way and the issue re-appears.  Thanks again for all of the additional info while investigating this one.
