### ISSUE TITLE
Running Execute Anonymous shows "Success" even if Execute Anonymous script fails

### ISSUE THREAD

**Issue by AziEI** [forcedotcom/salesforcedx-vscode#4436]
### Summary

Execute Anonymous always shows success, even when code doesn't compile or throws an exception

### Steps To Reproduce:

1.  Run "Execute Anonymous" with any code that doesn't compile or throws an exception. I.e. `System.debug(12345 / 0);`

### Expected result

Notification bar shows an error because Execute Anonymous returns error

### Actual result

Notification bar shows success of running the command

### Additional information

![image](https://user-images.githubusercontent.com/8708643/190717760-ce234595-8064-448b-b22f-9fb5a49fc106.png)

**Salesforce Extension Version in VS Code**:  55.8.0

**SFDX CLI Version**: sfdx-cli/7.164.2

**OS and version**: MacOS Monterey 12.4

**Comment by gbockus-sf** [comment]
Hi @AziEI 
Thanks for the feedback.  I think this is just a failure to communicate :).  The anon apex did execute successfully, but encountered compile errors.  The pop up will show a problem we were unable to execute the apex at all (like a network error).  

When errors are encountered in the anon apex you will find those errors listed in the problems tab (see attached screenshot). 

![Screen Shot 2022-09-20 at 12 36 26 PM](https://user-images.githubusercontent.com/76090802/191326310-ddc22f88-26b2-4d10-a3f9-d0fbd119d94f.png)

So this is working as intended.  If you have a feature request to make working with Anon apex friendly please open a feature request and we'd be glad to take a look.
