### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by lynx8989** [forcedotcom/salesforcedx-vscode#4444]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Darwin arm64 21.6.0`
- VS Code version: `1.71.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 938,
		"activateCallTime": 6,
		"activateResolvedTime": 1936,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by lynx8989** [comment]
The Apex v 55.8.0 is just showing as Unresponsive and sometimes showing # uncaught errors. I am unable to run Apex Tests.

**Comment by gbockus-sf** [comment]
Hi @lynx8989 
Are you seeing any error in the developer console specific to the apex extension? 
You can show the developer tools via the command pallet: Developer: Toggle Developer Tools
Then reload vscode via: Developer: Reload Window 

If you right click on the console and select 'Save As' you can save the logs from the console and attach it here I can take a look at what happening.

**Comment by randi274** [comment]
Hi @lynx8989 we're currently aware of issues with the Apex extension causing a slow-down, and are tracking that conversation with #4440 . Feel free to add any additional details there!
