### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by MarkusLewandowski** [forcedotcom/salesforcedx-vscode#4450]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

Getting an "unresponsive" flag on the Extension for 2 full days now. (multiple devices affected)

**Comment by AnanyaJha** [comment]
@MarkusLewandowski Thanks for reporting this! A member of our engineering time will look into this issue.
@gbockus-sf Any chance this is related to #4444?

**Comment by kaustubhdapurkar** [comment]
I am also facing this same issue. Earlier I had commented on an issue (#4267 ) about the same but at the time only my work laptop was affected (8GB RAM). Now I am facing the same issue on my personal laptop (16GB RAM, also other specs better than an avg PC).

**Comment by randi274** [comment]
Hey y'all - we're currently aware of issues with the Apex extension causing a slow-down, and are tracking that conversation with #4440 . Feel free to add any additional details there!
