### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by stylishbharath** [forcedotcom/salesforcedx-vscode#4451]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.2`

Extension is unresponsive.

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 13067,
		"activateCallTime": 20,
		"activateResolvedTime": 18921,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by randi274** [comment]
Hi @stylishbharath it looks like this issue was auto-generated, and we don't have enough information to troubleshoot. If you need additional assistance, please comment on this issue with additional context or steps to reproduce the issue you're facing.
