### ISSUE TITLE
Problem with Apex Language Server

### ISSUE THREAD

**Issue by Kali98** [forcedotcom/salesforcedx-vscode#4459]
### Summary

When coding in Apex in VS code I realized that I don't get any code completion suggestions at all. Upon launching of VS Code I receive these logs for the Apex Language server:

Error: Could not find or load main class apex.jorje.lsp.ApexLanguageServerLauncher
Caused by: java.lang.ClassNotFoundException: apex.jorje.lsp.ApexLanguageServerLauncher
[Info  - 19:34:02] Connection to server got closed. Server will restart.
Error: Could not find or load main class apex.jorje.lsp.ApexLanguageServerLauncher
Caused by: java.lang.ClassNotFoundException: apex.jorje.lsp.ApexLanguageServerLauncher
[Info  - 19:34:04] Connection to server got closed. Server will restart.
Error: Could not find or load main class apex.jorje.lsp.ApexLanguageServerLauncher
Caused by: java.lang.ClassNotFoundException: apex.jorje.lsp.ApexLanguageServerLauncher
[Info  - 19:34:04] Connection to server got closed. Server will restart.
Error: Could not find or load main class apex.jorje.lsp.ApexLanguageServerLauncher
Caused by: java.lang.ClassNotFoundException: apex.jorje.lsp.ApexLanguageServerLauncher
[Info  - 19:34:04] Connection to server got closed. Server will restart.
Error: Could not find or load main class apex.jorje.lsp.ApexLanguageServerLauncher
Caused by: java.lang.ClassNotFoundException: apex.jorje.lsp.ApexLanguageServerLauncher
[Error - 19:34:05] Connection to server got closed. Server will not be restarted.

Afterwards I get an error prompt on the bottom right of VS code displaying a message 'The Apex Language server has crashed 5 times in the last 3 minutes. The server will not be restarted.' 

I tried installing Java jdk 17, jdk8 and open jdk 17 and the problem still persists.

Apex Salesforce Extention version: v55.8.0

SFDX CLI version: 7.169.1 win32-x64 node-v16.17.0

OS: Windows 10 Pro (21H2) 
OS build: 19044.2006
Experience: Windows Feature Experience Pack 120.2212.4180.0

**Comment by randi274** [comment]
Hi @Kali98 - can you check and see if there's a stale Apex Language Server? It usually gets cleaned up when you reboot your machine, but for windows I think you can also check it with:

```
tasklist -> find something like [A]pexLanguageServerLauncher
taskkill /PID PID /F
```
