### ISSUE TITLE
Invalid warning displayed for Functions feature in scratch org definition

### ISSUE THREAD

**Issue by pozil** [forcedotcom/salesforcedx-vscode#4462]
### Summary

When working with a scratch org definition file that contains the `Functions` feature, the extensions displays the following warning:
> String does not match the pattern of "^AddCustomApps:[0-9]+$)".

### Steps To Reproduce:

Clone the [Functions Recipes](https://github.com/trailheadapps/functions-recipes) sample app or create a new DX project with the following scratch org definition:

```json
{
    "orgName": "s3demo",
    "edition": "Developer",
    "features": ["Functions", "EnableSetPasswordInApi"],
    "settings": {
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "mobileSettings": {
            "enableS1EncryptedStoragePref2": false
        }
    }
}
```

### Expected result

No warnings are displayed.

### Actual result

![Screen Shot 2022-09-29 at 17 06 40](https://user-images.githubusercontent.com/5071767/193070081-1ac51cb8-9c1f-4c2f-8ef2-add7b7267183.png)

### Additional information

**Salesforce Extension Version in VS Code**:
Salesforce Extension Pack v55.8.0

**SFDX CLI Version**:
sfdx-cli/7.170.0 darwin-x64 node-v16.17.0

**OS and version**:
macOS latest

**Comment by randi274** [comment]
We actually have an internal fix pending for this one over in our schemas repo! Waiting on some feedback to be addressed, and then this should be set: https://github.com/forcedotcom/schemas/pull/57/files

**Comment by daphne-sfdc** [comment]
Closing this issue as Functions is no longer supported.
