### ISSUE TITLE
Error when creating a new project when VS Code is empty and doesn't have any folders

### ISSUE THREAD

**Issue by jeffb-sfdc** [forcedotcom/salesforcedx-vscode#4465]
In the develop branch, if you:
1. start with an empty window in VS Code (no files or folders opened)
2. run SFDX: Create Project
…this is now failing (develop branch).

This is b/c getRootWorkspacePath(), getRootWorkspace(), and hasRootWorkspace() is getting called.  When called and no folders exists, ws is empty and getRootWorkspacePath() returns an empty string, which has ramifications further downstream.

Some other thoughts:
1. if getRootWorkspacePath(), if getRootWorkspace() doesn’t return anything, maybe it should throw instead of returning an empty string.

2. in getRootWorkspacePath(), getRootWorkspace() is being called twice:
```
export function getRootWorkspacePath(): string {
  return getRootWorkspace().uri ? getRootWorkspace().uri.fsPath : '';
}
```
…calling getRootWorkspace() just once would be better:

```
export function getRootWorkspacePath(): string {
  const rootWorkspace = getRootWorkspace();
  return rootWorkspace.uri ? rootWorkspace.uri.fsPath : '';
}
```

3. There are two copies of rootWorkspace.ts:
packages/salesforcedx-utils-vscode/src/workspaces/rootWorkspace.ts
packages/salesforcedx-vscode-core/src/util/rootWorkspace.ts

**Comment by gbockus-sf** [comment]
Fixed and release!
