### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ayushjain7870** [forcedotcom/salesforcedx-vscode#4484]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

Startup time is very high: 31088ms average.

**Comment by Ayushjain7870** [comment]
It is showing notification like below:
![image](https://user-images.githubusercontent.com/69713567/195546160-b581f88e-2397-4a06-911a-27050a212a19.png)

**Comment by randi274** [comment]
Hi @Ayushjain7870 we're currently aware of issues with the Apex extension causing a slow-down, and are tracking that conversation with #4440 . Feel free to add any additional details there!
