### ISSUE TITLE
```json  { 	"messages": [], 	"activationTimes": { 		"codeLoadingTime": 9127, 		"activateCallTime": 58, 		"activateResolvedTime": 27137, 		"activationReason": { 			"startup": true, 			"extensionId": { 				"value": "salesforce.salesforcedx-vscode-apex", 				"_lower": "salesforce.salesforcedx-vscode-apex" 			}, 			"activationEvent": "workspaceContains:sfdx-project.json" 		} 	}, 	"runtimeErrors": [], 	"runningLocation": { 		"affinity": 0, 		"kind": 1 	} } ```Extension issue

### ISSUE THREAD

**Issue by utkarshnarad-opus** [forcedotcom/salesforcedx-vscode#4485]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by randi274** [comment]
Hi @utkarshnarad-opus do you have any more information about what was happening when you received the error? Was this an Apex Extension unresponsive error?
