### ISSUE TITLE
CssSyntaxError: LWC1009: postcss-plugin-lwc: 2:3: Invalid definition of custom property

### ISSUE THREAD

**Issue by erocheleau** [forcedotcom/salesforcedx-vscode#4493]
### Summary

LWC Local Development does not support the use of styling hooks as documented here [Lightning Design System Styling Hooks](https://www.lightningdesignsystem.com/platforms/lightning/styling-hooks/).

A variation of this screen and this error will be displayed instead

![image](https://user-images.githubusercontent.com/2488155/195108980-842ae063-b53e-4392-9b74-625569c0e299.png)

"CssSyntaxError: LWC1009: postcss-plugin-lwc: 2:3: Invalid definition of custom property "--slds-c-checkbox-color-border"."

### Steps To Reproduce:

1.  Attempt to override a LWC styling hooks in your component:

```
:host {
  --slds-c-checkbox-color-border: var(#747474);
}
```

2. Open the component in the LWC Local Dev Server.

### Expected result

Expected the component to render correctly with the style override.

### Actual result

A variation of this screen and this error will be displayed instead

![image](https://user-images.githubusercontent.com/2488155/195108980-842ae063-b53e-4392-9b74-625569c0e299.png)

"CssSyntaxError: LWC1009: postcss-plugin-lwc: 2:3: Invalid definition of custom property "--slds-c-checkbox-color-border"."

### Additional information

```
sfdx plugins

>>> @salesforce/lwc-dev-server 2.11.0
```

This had also been reported a long time ago in a different repository: https://github.com/forcedotcom/lwc-dev-server-feedback/issues/76

**SFDX CLI Version**:

```
sfdx version

>>> sfdx-cli/7.171.0 wsl-x64 node-v16.13.2
```

**Comment by AnanyaJha** [comment]
Hi @erocheleau thanks for reporting this! Unfortunately our team will not be able to pick up any changes related to Local Dev Server this year, but we're happy to hear your feedback. If you have any further issues or feedback for the product, feel free to leave a comment - https://github.com/forcedotcom/lwc-dev-server-feedback/issues/143. Thank you for the patience
