### ISSUE TITLE
package.xml file not retrieve the metadata from the Dev Org

### ISSUE THREAD

**Issue by Rohit496** [forcedotcom/salesforcedx-vscode#4496]
### Summary

package.xml  file did not retrieve the metadata from the org.,

### Actual result

I have already connected Salesforce Dev Environment and I have created a project with the manifest file when I am trying to retrieve all the metadata of the org using the package.xml file right click in vs code. I am facing this issue previously It has not happened to me but now it is showing again and again as an error

### Additional information

**Salesforce Extension Version in VS Code**:
  v55.8.0
**SFDX CLI Version**:
sfdx-cli/7.171.0 win32-x64 node-v16.17.0
**OS and version**:
Win 11 Pro 64bit
![image](https://user-images.githubusercontent.com/73574366/195426906-74dc1893-1b4e-4d8a-a46f-a197ea0ab5b9.png)

**Comment by randi274** [comment]
Hi @Rohit496 - do you see the command `SFDX: Retrieve Source in Manifest from Org`? That's the command you'll need to use to pull down metadata using a manifest file. This command should also be available you right click in the file, or from the Command Palette. 
<img width="495" alt="Screen Shot 2022-11-07 at 2 54 43 PM" src="https://user-images.githubusercontent.com/9795193/200402259-228a2716-a4e0-4c24-90aa-3130495c7e01.png">

**Comment by Rohit496** [comment]
Hello Randi Wilson,

I have tried so many times using  this option as well but not work for me

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
