### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AissaDev** [forcedotcom/salesforcedx-vscode#4497]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `55.8.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by AissaDev** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 42791,
		"activateCallTime": 123,
		"activateResolvedTime": 64732,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by AnanyaJha** [comment]
Hi @AissaDev thanks for sharing this information! Could you tell us a bit more about exactly what issue you ran into ?
