### ISSUE TITLE
Missing metadata type definition in registry for id 'externalcredential'.

### ISSUE THREAD

**Issue by gmpmovies** [forcedotcom/salesforcedx-vscode#4498]
### Summary

I am trying to retrieve the Metadata file for an External Credential which is a new feature in Winter '23. I am using the Metadata Org Browser in VS Code. I can see the external credentials inside of the org browser but when I try to download the metadata file I get this error: Missing metadata type definition in registry for id 'externalcredential'.

### Additional information
<img width="331" alt="Screen Shot 2022-10-12 at 2 54 16 PM" src="https://user-images.githubusercontent.com/43527569/195445787-1078a17b-7970-40c9-b94f-41f5f49913c1.png">

**Salesforce Extension Version in VS Code**: v55.8.0

**SFDX CLI Version**: sfdx-cli/7.171.0 darwin-x64 node-v16.17.0

**Comment by klewis-sfdc** [comment]
Hi @gmpmovies,

Thanks for submitting the issue.  I have confirmed that the Salesforce Extensions need to update to a newer version of the source-deploy-retrieve library (to the latest, 7, from version 6, which is used currently) where External Credential is included [in the metadata registry](https://github.com/forcedotcom/source-deploy-retrieve/commit/c031034cf847c15a195acac797c83844c8a4e270) for this to work.  

We have a work item in our backlog currently to upgrade this library soon, so you should see this begin to work correctly once we can get that lib updated.

**Comment by anthony1293** [comment]
@klewis-sfdc when I try to "retrieve source from org" I'm getting the following error:

Entity of type 'EmailServicesFunction' named 'my_external_credential' cannot be found.

when I try a "deploy source to org" I get:
```
=== Deploy Errors
18:34:26.522 ended SFDX: Deploy Source to Org
```
with no errors listed.  I do receive the same error as @gmpmovies when using the org browser (vscode) to retrieve

**Comment by diyer** [comment]
The SDR library has been updated several times after this bug was logged. please create a new issue if you still see this problem occurs. Thank you!
