### ISSUE TITLE
Debug Test in LWC tests improperly escaping --testNamePattern value

### ISSUE THREAD

**Issue by Russman12** [forcedotcom/salesforcedx-vscode#4499]
### Summary

The _Debug Test_ functionality is not running as expected for individual tests in LWC. It appears the `testNamePattern` flag is incorrectly escaping characters. This causes the execution to skip all tests as nothing can be found matching the string.

### Steps To Reproduce:

1.  Create a LWC test.
1.  Attempt to debug a test individually.

### Expected result

Selected test should execute and stop at breakpoints.

### Actual result

Selected test is skipped

### Additional information

The following is the task executed by the _Run Test_ button on a individual test. Notice the testNamePattern option at the end is not escaped. After the tests are complete the output indicates that 1 test passed and 5 tests were skipped. This is working as expected. 
```
/home/russell/projects/SFUSA/node_modules/.bin/lwc-jest -- --json --outputFile /home/russell/projects/SFUSA/.sfdx/tools/testresults/lwc/test-result-beb510d1-59f8-465d-9749-0b031d79df4c.json --testLocationInResults --runTestsByPath /home/russell/projects/SFUSA/force-app/main/default/lwc/supporterStatements/__tests__/supporterStatements.test.js --testNamePattern "Should render component with Tax Receipts and Statements" 
```

The following is an example of the command being executed when pressing _Debug Test_. Notice that the testNamePattern at the end has `\` characters before spaces and quotes. After the tests are complete the output indicates that 6 tests were skipped. This is not working as expected.

```
/usr/bin/env 'NODE_OPTIONS=--require /home/russell/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.20883-23.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/russell/.nvm/versions/node/v16.18.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","mandatePortTracking":true,"fileCallback":"/tmp/node-debug-callback-3df287434e74a180"}' /home/russell/projects/SFUSA/node_modules/.bin/lwc-jest -- --json --outputFile /home/russell/projects/SFUSA/.sfdx/tools/testresults/lwc/test-result-6af4d30b-dacb-4152-87e8-51542869dcfc.json --testLocationInResults --runTestsByPath /home/russell/projects/SFUSA/force-app/main/default/lwc/supporterStatements/__tests__/supporterStatements.test.js --testNamePattern \"Should\ render\ component\ with\ Tax\ Receipts\ and\ Statements\" 
```

**Salesforce Extension Version in VS Code**:
v55.8.0

**SFDX CLI Version**:
7.172.0

**OS and version**:
Windows 10 WSL 2 Ubuntu 20.04
Same bug presented in windows 10

**Comment by Russman12** [comment]
To clarify, this bug does not seem to occur when running an entire LWC test file. It only occurs when running an individual test case, "it" block.

**Comment by joeythomaschaske** [comment]
Is there a work around for this?

**Comment by joeythomaschaske** [comment]
FWIW the OS and version I am facing this on is

Debian GNU/Linux 11 (bullseye)
Linux 5.10.147-20158-g0a75306e5639 x86_64
