### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by Harshi76** [forcedotcom/salesforcedx-vscode#4504]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by gbockus-sf** [comment]
@Harshi76 can you expend further on what you are trying to accomplish? Is this happening only for a specific command or is it an overall issue installing/running the extensions?
