### ISSUE TITLE
Please Support Zulu JDK

### ISSUE THREAD

**Issue by hujiafan123** [forcedotcom/salesforcedx-vscode#4512]
Zulu JDK works fine before.But a few days ago,vscode show up some error message

An unsupported Java version was detected. Download and install [Java 8](https://java.com/en/download/), [Java 11](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html), or [Java 17](https://www.oracle.com/java/technologies/downloads/#java17) to run the extensions. For more information, see [Set Your Java Version](https://developer.salesforce.com/tools/vscode/en/vscode-desktop/java-setup).

I'm using company's laptop.Cannot install unauthorized software like java 8.Please update apex language server to support Zulu jdk like it was before.

Thank you

**Comment by hujiafan123** [comment]
Currently,I'm using zulu 11

**Comment by gbockus-sf** [comment]
Hi @hujiafan123 
Did your version of vscode or the salesforce extensions change?  Can you post the following information: 

**Salesforce Extension Version in VS Code**: (found in the extensions tab on the left sidebar) 

**OS and version**: (laptop)

There was an update earlier this year to support JDK 17 (54.6.0).  If you are using that version or newer could you check if using version (54.5.0) resolves the issue? 

![Screen Shot 2022-10-25 at 10 16 18 AM](https://user-images.githubusercontent.com/76090802/197813431-9472b1d1-b4d5-4fba-b2cf-91a1de444574.png)
