### ISSUE TITLE
Announcement: No release to Salesforce Extensions since August 8th due to Infra Work

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/salesforcedx-vscode#4513]
### Summary
VSCode is has not received any updates for these extensions since August 8th

### Steps To Reproduce:

1.  Install Extension pack

### Expected result

The installed version reflects the latest release and CLI

### Actual result

Installed version is 55.8.0

### Additional information
https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode
Shows 55.8.0 as being the latest release. As does https://github.com/forcedotcom/salesforcedx-vscode/releases

Winter 23 was released on the 5th of October and is API version 56. It seems weird the extension is not keeping pace with the CLI or API.

Furthermore no documented release policy can be obviously found in the wiki to explain the disparity.

**Salesforce Extension Version in VS Code**: 55.8.0

**SFDX CLI Version**: N/A

**OS and version**: MacOS 13

**Comment by gbockus-sf** [comment]
@mgetzbw Publish of v56.3.1 just completed. Might take a few minutes to propagate in the VSCode marketplace, but should be available for install shortly 🚀

**Comment by gbockus-sf** [comment]
Closing this issue with the release today.  Thanks again for calling out the lack of info @mgetzbw
