### ISSUE TITLE
Error in vscode download extension

### ISSUE THREAD

**Issue by Last-Order-Wsk** [forcedotcom/salesforcedx-vscode#4518]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/73875874/198206554-a5ec9942-aa26-4f34-836f-059589475d2f.png">

I don't know what happened. The first download shows this error

**Comment by gbockus-sf** [comment]
Hi @Last-Order-Wsk 
This is likely a temporary issue with the VSCode marketplace. Can you try again and see if the issue has been resolved?   If no could you share the info in the Log from the link in the notification? 

Thanks

**Comment by Last-Order-Wsk** [comment]
@gbockus-sf  Since I am a user in Chinese Mainland, I need scientific online tools to link to the download address. It has been solved. Thank you!
