### ISSUE TITLE
Unable to Authorize to any Salesforce Environment from VSCode

### ISSUE THREAD

**Issue by KellyGatling** [forcedotcom/salesforcedx-vscode#4520]
Type: <b>Bug</b>

Unable to Authorize to any Salesforce environment. Steps:
1. Ctrl + Shift + P to SFDX:Authorize an Org
2. Accept default location
3. Give it a name of 'ApexToolkitDevOrg'
4. It runs but quickly ends with exit code 1. Nothing pops up for me to log into salesforce. 

Output Salesforce CLI Message: Starting SFDX: Set a Default Org
10:08:46.806 sfdx force:config:set defaultusername=ApexToolkitDevOrg
10:08:50.109 sfdx force:config:set defaultusername=ApexToolkitDevOrg
 ended with exit code 1

I have the Salesforce CLI installed. Version 7.174.0
Using VS Code Version: 1.72.2

Receiving pop up error: "Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log."

Extension version: 56.3.1
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.12GB free)|
|Process Argv|--crash-reporter-id 451da223-5072-4f62-9c07-d46a4fd480f4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by KellyGatling** [comment]
@randi274 You know what I tried one more time totally uninstalling Salesforce CLI from my machine and then reinstalling and restarting. Now it seems to be working as expected. Thank you anyways!!

**Comment by randi274** [comment]
Thanks for the update and what worked to resolve it - we're glad everything is back up and running for you now! 🚀
