### ISSUE TITLE
Salesforce Extensions for VS Code encountered a problem while configuring your environment.

### ISSUE THREAD

**Issue by kranthiparamata** [forcedotcom/salesforcedx-vscode#4524]
Full error: Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log.

**Comment by kranthiparamata** [comment]
When i try to Authorize org It shows Authorize Org successfully but it not redirecting to Browser to login.
VSCode version:1.72.2
d045a5eda657f4d7b676dedbfa7aab8207f8a075
x64
Salesforce Extensions for VSCode version: 56.3.1
OS:Windows

**Comment by kranthiparamata** [comment]
OS: Windows 10 Enterprise

**Comment by randi274** [comment]
hi @kranthiparamata would be able to record the issue in a gif or video to add to the issue so we can see what's going wrong?

**Comment by kranthiparamata** [comment]
https://user-images.githubusercontent.com/91527073/200766435-9615f28e-78e8-4ea5-8f24-c1478f453834.mp4
