### ISSUE TITLE
Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by PrateekTyagiForce** [forcedotcom/salesforcedx-vscode#4527]
### Summary

I am running a simple command SFDX: Retrieve Source from Org but it taking too much time.

### Steps To Reproduce:

Go to any file, example a apex class file, right click and run "SFDX: Retrieve Source from Org", it will take too much time and when click on cancel, will show you an error "Cannot read properties of undefined (reading 'type')"

### Expected result

I Should be able to retrieve the source from Org

### Actual result

Taking too much time and when click on cancel button Cannot read properties of undefined (reading 'type')
### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
IDE - VS Code, terminal - powershell  
- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
### Additional information
I recently updated my salesforce CLI to version sfdx-cli/7.174.0 
_Feel free to attach a screenshot_.
![Screenshot (152)](https://user-images.githubusercontent.com/117173695/199232155-fc1152eb-81de-4bff-9829-13c65f96a5cf.png)

**Comment by klouf-threshold** [comment]
Also experiencing this with a manifest file. Reverting to the previous version of the extension resolves the issue. No error messages other than eventual timeout. CPU usage goes through the roof at some point. Confirmed on multiple machines. I will note that the manifest includes a lot of metadata types and I am retrieving from a long-standing org. I WAS able to retrieve using a manifest from a much newer org with a smaller metadata footprint. Happy to elaborate further and/or provide any additional details as needed!

**Comment by randi274** [comment]
@klouf-threshold were you receiving the same error `Cannot read properties of undefined (reading 'type')`? Also, which version was successful for you?

**Comment by klouf-threshold** [comment]
I have seen that error, but I don't believe it's happening when retrieving source using the manifest, although I can't say for sure as I haven't paid enough attention and I don't perform this action on a regular basis (a quick test didn't produce it). The version that works is 55.8.0.

**Comment by klouf-threshold** [comment]
Update regarding not being able to retrieve source via manifest: I have the same issue using the CLI when I use the `sfdx force:source:retrieve` command. HOWEVER, I AM able to use the `sf metadata retrieve` command.
