### ISSUE TITLE
Test tab somehow broken: missing indicators, shifted names

### ISSUE THREAD

**Issue by danikar208** [forcedotcom/salesforcedx-vscode#4534]
### Summary

_After some time the testing tab does not seem to be working properly. The indicators are missing at all times, after running tests the method names are shifted in a weird manner._.

### Steps To Reproduce:

1.  Run some tests
1.  Check the "Testing" tab for the ran tests

### Expected result

_We all know how should it look like_.

![2](https://user-images.githubusercontent.com/56158777/199737667-132fa24b-1bcc-493f-afe1-a6b5c60baa6f.PNG)

### Actual result

![1](https://user-images.githubusercontent.com/56158777/199737556-c904ff62-bd06-4179-8ca1-1f1c67060683.PNG)

**Salesforce Extension Version in VS Code**:
v56.3.1

**SFDX CLI Version**:
sfdx-cli/7.174.0 win32-x64 node-v16.17.1

**OS and version**:
Windows 10 21H2

**Comment by mihailTr-19** [comment]
I have the same issue.

**Comment by danikar208** [comment]
> Hi @danikar208 - I've seen this issue occasionally as well. Do you find that rebooting VS Code addresses the issue for you?

Hey, at first when the issues appeared, a reboot would had sufficed. Right now it never goes away, rebooting does not work of course, neither do reinstallation of extensions.

**Comment by jbelloperezSFDC** [comment]
This issue happened from version 56.3.1 on to me. I've installed 55.8.0 and that works fine, but any version after that will hide the pass/fail icon

**Comment by danikar208** [comment]
@jbelloperezSFDC How'd you install a later version?

**Comment by danikar208** [comment]
Oh well, I loved the screaming red error diodes. I'll stick with an older version until something major comes out.

Won't close this issue, until we get a definite answer, if it's a feature now or not and the shifted faulty method names still feel really wonky.

**Comment by randi274** [comment]
Thanks for your patience on this one - I'm seeing it consistently as well. We'll add to our backlog and get this one addressed soon as we can!

**Comment by gbockus-sf** [comment]
Fix coming in the next release 👍

**Comment by randi274** [comment]
Closing this one as it was fixed a few weeks ago, and should be available in the latest and great version of the extensions 🙌
