### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by acmedinaa** [forcedotcom/salesforcedx-vscode#4537]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `56.4.1`
- OS Version: `Darwin arm64 21.4.0`
- VS Code version: `1.66.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8429,
		"activateCallTime": 4,
		"activateResolvedTime": 5609,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.analyticsdx-vscode-core",
				"_lower": "salesforce.analyticsdx-vscode-core"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by randi274** [comment]
Hi! This looks like an auto-generated issue, and we don't have enough information to troubleshoot. If you can provide us with more detail about the issue, please respond and let us know how we can help!
