### ISSUE TITLE
SVCode SFDX: Diff File Against Org Broken

### ISSUE THREAD

**Issue by KevinGossentCap** [forcedotcom/salesforcedx-vscode#4544]
### Summary

I don't know since when, but with actual VSCode version, actual extensions and sfdx-cli latest or latest-rc this feature is broken.
It invokes but nothing happens, nothing is shown.

### Expected result

Diff between ORG and local to be shown as it did previously.

### Actual result

Output tells
- Starting SFDX: Diff File Against Org
- ended SFDX: Diff File Against Org
But nothing is shown anywhere, even though we know for sure that there are diferencies.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: 56.5.1

**SFDX CLI Version**: 7.177.0

**OS and version**: Windows 10

**Comment by randi274** [comment]
Hi @KevinGossentCap - are you seeing this with any specific metadata, or with everything?

**Comment by KevinGossentCap** [comment]
Hi @randi274  I'd have to test for more metadata types, but definitely happening with layouts.

**Comment by gbockus-sf** [comment]
Just another piece of info for this issue.  I tested this functionality yesterday as part of QE'ing PR https://github.com/forcedotcom/salesforcedx-vscode/pull/4543 and it was working as expected.  I was testing on a mac with sfdx-cli/7.175.0.  I'll check it for the latest release and see if I can repo the issue.

**Comment by gbockus-sf** [comment]
@KevinGossentCap 
Tested with the previous release and I can't repo the issue (tested using an LWC component file and a layout file).  

One note.  Here we aren't using any cli functionality so it the installed version of the sfdx should have zero impact for this particular issue.

There may be an error occurring.  To see any errors that we aren't handling you can toggle the Developer console via the command pallet: 'Developer: Toggle Developer Tools'.  That will open the dev tools where you can view the console for any errors being thrown.  Please copy any that show up after running a diff and share them here. 

A couple of things to sanity check: 
1. Where you are you right clicking to select the 'Diff File against Org'? 
2. If you attempt to diff something that isn't a SF file does it show the error dialog? (I ran the diff by right clicking the `sfdx-config.json` file and selecting the diff from the context menu.
![Screen Shot 2022-11-11 at 3 38 31 PM](https://user-images.githubusercontent.com/76090802/201434533-cfda3e6d-9599-4e63-aad1-91019b2f05c6.png)

3. If you select a folder does it behave any differently? 
![Screen Shot 2022-11-11 at 3 34 11 PM](https://user-images.githubusercontent.com/76090802/201434051-6816dfcb-aa56-47d5-82ed-1b6a2a7bc653.png)

I took a quick pass at the source for this command and didn't see any obvious places where it would swallow errors.

**Comment by randi274** [comment]
Also gave this a test on my Windows box with the latest extensions (v56.5.1), and I'm able to see a clean diff when there's no changes, and highlights when I make changes both locally and in the org. Hopefully @gbockus-sf's thoughts give us some better insight into what might be happening for you 🤞 

Clean diff:
![image](https://user-images.githubusercontent.com/9795193/201437339-235f35e9-5c23-42d9-9523-27be162c0668.png)

Diff with changes (local and in the org):
![image](https://user-images.githubusercontent.com/9795193/201437352-df4a4abc-925c-4904-af9a-5b8eab24c710.png)

**Comment by KevinGossentCap** [comment]
Hi,
I've just tested more.
It's really strange
- reverting sfdx-cli to 7.175 doesn't change a thing
- folder works fine
- component not existing in OR gives normal comprehensive error
- class works
- any layout just outputs "ended SFDX: Diff File Against Org" and nothing happens

**Comment by gbockus-sf** [comment]
Thanks for the update @KevinGossentCap.  
Can you toggle the developer tools: `Developer: Toggle Developer Tools` and see if any errors are thrown when you attempt to run the diff? 

I ran a trace back a few days through our analytics and didn't find any diff calls that resulted in an error so I won't be too surprised if nothing shows up. 

Another thing we could check is if the request to get the file is making it to the org.  You can verify this by first navigating to your Org -> Setup -> Company Information.  On that page there is an entry under Company Information -> API Requests, Last 24 Hours.  Note the current value then run the diff command in vscode.  After it completes refresh the company information page and see if the Api requests value increases.  It's not a perfect test in that there could be a lot of things making API requests, but if you're working on a org without lots of activity you can see the API request value increase by 1.

**Comment by KevinGossentCap** [comment]
Hi @gbockus-sf , I've just tested both and

- toggle developer tools open a chrome like debug and running the diff outputs nothing more at all in it
- running the diff increases the API call but more like by 9 (even though nothing else happens on this org, seems like the screen update makes calls in itself...)

**Comment by gbockus-sf** [comment]
@KevinGossentCap Thanks for the update. 

Ok so the only route I could think of to track this down is to add a bunch of debug logging to see where in the flow the diff is failing.  I added this logging and generated a vsix file that I attached to a release on my fork of this repo. 
https://github.com/gbockus-sf/salesforcedx-vscode/releases/tag/v56.5.1-test
![Screen Shot 2022-11-22 at 5 42 43 PM](https://user-images.githubusercontent.com/76090802/203443184-7df1926e-7d34-4bc2-a02f-63df2b19176e.png)

I included instructions for how to install and see the debug logging on the release notes. Please give it a try when you get a chance and provide back the debug logging output. 

Thanks for your patience on this!

**Comment by KevinGossentCap** [comment]
Here is the log
[vscode-app-1669203078106.log](https://github.com/forcedotcom/salesforcedx-vscode/files/10075028/vscode-app-1669203078106.log)

**Comment by KevinGossentCap** [comment]
dummy message just to maintain it open

**Comment by gbockus-sf** [comment]
Thanks for the bump and the log.  I'm taking a look now.

**Comment by AprilShenk** [comment]
I'm having a similar issue except with Deploy Source to Org. It seems to happen after the second or third Deployment. I followed the steps here and don't see anything in my console either. After pushing once or twice the third will never complete. Cancelling the deploy and deploying again sometimes works along with reloading the window. The only thing that is consistent is if I completely close VS code and open it again. 

I have the most up to date version of sfdx, vs code, and the extension pack.

**Comment by gbockus-sf** [comment]
@KevinGossentCap I tracked down the issue.  The root of the problem is your local layout file doesn't look like it was retrieved from the org using the cli or vscode.  The file name is `Opportunity-Opportunity Layout.layout`.  When it gets pulled via the cli or vscode it will include `-meta.xml` at the end of the file name.  

To verify this can you try the following: 
1. rename a layout file adding the `-meta.xml` to the end of the file name.  (or just do a retrieve of the layout via the Org Browser <see image at bottom of this message>)
2. Verify the diff command shows the diff viewer. 

Adding the extension is a function of the tooling SF source-deploy-retrieve node library used by vscode and the cli. If you pull the source through one of those tools it should be correctly named to work with the SF vscode extensions. 



<img width="402" alt="Screen Shot 2022-12-01 at 4 09 31 PM" src="https://user-images.githubusercontent.com/76090802/205169603-35f870c8-fb04-4c8f-8352-451e02a31fba.png">

**Comment by gbockus-sf** [comment]
> I'm having a similar issue except with Deploy Source to Org. It seems to happen after the second or third Deployment. I followed the steps here and don't see anything in my console either. After pushing once or twice the third will never complete. Cancelling the deploy and deploying again sometimes works along with reloading the window. The only thing that is consistent is if I completely close VS code and open it again.
> 
> I have the most up to date version of sfdx, vs code, and the extension pack.

Hi @AprilShenk 
Would you mind opening a new issue for the deploy issues you are experiencing. I think it's a related but separate path from this diff issue.

Thanks

**Comment by KevinGossentCap** [comment]
Hi @gbockus-sf , simple CLI command : ```sfdx force:mdapi:retrieve```
Most parameters are the same as the ```sfdx force:source:retrieve```, main difference is that you have to build a package.xml file (where with source you can specify the targeted metadata by other means)

**Comment by diyer** [comment]
Closing this old issue. Please create a new one if the problem persists with our lates VS Code Extensions. Thank you!
