### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Mado97** [forcedotcom/salesforcedx-vscode#4545]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `56.5.1`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7977,
		"activateCallTime": 2,
		"activateResolvedTime": 5911,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by AnanyaJha** [comment]
Hi @Mado97 thanks for sharing this information! Could you tell us a bit more about exactly what issue you ran into ?
