### ISSUE TITLE
Salesforce extension host unresponsive

### ISSUE THREAD

**Issue by DennisD540** [forcedotcom/salesforcedx-vscode#4547]
### Summary

When opening VS Code and pressing ctrl+shift+p to try and create and SFDX project, we receive an unresponsive host

### Steps To Reproduce:

1.  This is step 1. Try creating a project with manifest
1.  This is step 2. times out

### Expected result

Vs Code responds asking for what type of project, Standard, etc

### Actual result

[renderer1] [warning] UNRESPONSIVE extension host, 'salesforce.salesforcedx-vscode-core' took 100% of 5665.841ms, saved PROFILE here: 'c:\Users\LO1D04~1\Temp\exthost-92849b.cpuprofile' [{"id":"gc","total":3623,"percentage":0},{"id":"salesforce.salesforcedx-vscode-core","total":5661530,"percentage":100}]

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:
56.3.1
**SFDX CLI Version**:
sfdx-cli/7.112.1 win32-x64 node-v14.17.4

**OS and version**:
Windows 11 - Version 1.53.2 of Visual Studio Code

**Comment by gbockus-sf** [comment]
Hi @DennisD540 Thanks for the feedback.  The upside is that the unresponsive host warning doesn't impact the functionality of the extension, it's just letting you know that it's taking longer then it should to come online.  You can verify that the extension eventually loads by executing 'Developer: Show Running Extensions' from the command palette. 

We're aware there are some performance issues with the extensions currently (esp on windows) and are looking at how we can resolve those issues.  We're tracking the issue in a [discussion](https://github.com/forcedotcom/salesforcedx-vscode/discussions/4440).  Please feel free to add to that discussion.  I'll add  this issue there for now and close it out as there's no immediate resolution. 

Thanks.

**Comment by gbockus-sf** [comment]
closing in favor of the discussion for tracking the performance issues. https://github.com/forcedotcom/salesforcedx-vscode/discussions/4440
