### ISSUE TITLE
SFDX: Diff File Against Org failed to run

### ISSUE THREAD

**Issue by KIJones** [forcedotcom/salesforcedx-vscode#4550]
I keep seeing this pop up in the forums and the issues never seem to actually get resolved. The requests just seem to get closed out due to no response. I've been having this issue on and off for over a year now. I always make sure I've the latest version of the CLI installed. Some days it works, others it doesn't. Some times restarting VSC solves the problem for a few diffs, other times it doesn't.  Generally I also get told "Selected components are not available in the org" when the definitely are. Any assistance would be appreciated, I have constant issues trying to diff or retrieve with SFDX using the right click options. retrieving with a package.xml will work but it means creating a new local copy of the remote file and comparing to see any diffs. Extremely frustrating and a huge waste of time.

Thanks

**Comment by gbockus-sf** [comment]
Hi @KIJones 
Thanks for your feedback.  I'm currently tracking a diff issue in https://github.com/forcedotcom/salesforcedx-vscode/issues/4544. When it fails for you is it typically the same behavior where it just silently returns, or does it always give you the 'not available in the org' message? 

Also could you provide your OS, VSCode version, and Salesforce Extensions for VSCode version? 

Thanks

**Comment by KIJones** [comment]
Hey, It generally says 'not available in the org'
I'm using Windows 10, VSC 1.73.1 and 56.5.1 for the extension pack.

Thanks

**Comment by KIJones** [comment]
So just to add to this. I've today completely removed the CLI and the SFDX plugins and reinstalled them. (that was fun)  I can right click on a file select SFDX: Retrieve Sourse From Org and that works fine. But if I right click the same file and select SFDX: Diff File against org and retrieve it from my org. I get an error saying "SFDX: Diff File Against Org Failed to Run". The output says "Selected components are not available in the org"

**Comment by KIJones** [comment]
So it will work for a .cls file but not for an object or field file. (e.g. Account.object-meta.xml, AnnualRevenue.field-meta.xml)

**Comment by diyer** [comment]
@KIJones Please create a new issue if the problem persists with our lates VS Code extensions with proper repro steps as required by our template. Thank you!
