### ISSUE TITLE
Diff against org just loads forever.  Can not complete command

### ISSUE THREAD

**Issue by SvHuyssteen** [forcedotcom/salesforcedx-vscode#4557]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by gbockus-sf** [comment]
@SvHuyssteen Thanks for reporting this issue.  I'm currently working a similar issue in https://github.com/forcedotcom/salesforcedx-vscode/issues/4544.  Can you verify your OS, VSCode version, and SFDX  Extension Versions? 

Also do you see the same behavior as reported in that issue (basically just never returns anything) or is it hanging indefinitely?
