### ISSUE TITLE
Local Development Design Tokens

### ISSUE THREAD

**Issue by bfeldatwilio** [forcedotcom/salesforcedx-vscode#4567]
**Is your feature request related to a problem? Please describe.**
Currently standard design tokens are not supported when running local development.  Using local development speeds up the development process but not being able to see changes when using design tokens makes this a difficult experience.

**Describe the solution you'd like**
Support for standard design tokens, or at least a common subset that hits 75% of use cases.

**Describe alternatives you've considered**
Not using design tokens but using the static values instead

**Additional context**
One of the biggest advantages of having live reloads is to see css changes and I am encouraging my team to use design tokens.  Not being able to visualize changes realtime makes local development not useful for designers.

**Comment by AnanyaJha** [comment]
Hi @bfeldatwilio thanks for sharing! We'll keep this request in mind as we plan for the upcoming year. Out of curiosity, have you ended up using static values as an alternative to continue using local development?

**Comment by bfeldatwilio** [comment]
Thank you for the response AnanyaJha!
We started out using static values and then updated them before deployment
to the tokens, but that ended up being too tedious so yes, we are not using
tokens anymore and using the static values.
