### ISSUE TITLE
New Assert class unresolved

### ISSUE THREAD

**Issue by camisotro** [forcedotcom/salesforcedx-vscode#4586]
### Summary
The new Assert class (https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Assert.htm) always comes up as Unresolved.

### Steps To Reproduce:

1.  Create a unit test class in VSCode, API version 56.
2.  Create a test method, and in it, try typing `Assert.` and note that code completion is not functional
3. Try typing `Assert.areEqual(1,1);` and then mouse-over `Assert`. It comes up `!Unresolved!`
 
### Expected result

Code completion should function for the new `Assert` class.

### Actual result

Code completion does not function for the new `Assert` class.

**Salesforce Extension Version in VS Code**: v56.5.1

**SFDX CLI Version**: 7.177.1

**OS and version**: Windows 11

**Comment by zerkz** [comment]
Pretty sure this is due to the new `Assert` class not being provided to/implemented in the Apex Jorje Jar (particularly the ApexStandardLibrary folder). By unzipping the jar (`jar xf apex-jorje-lsp.jar`), you can see what is available.

**Comment by zerkz** [comment]
By unzipping the jar, adding a stub for the [new Assert.cls](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Assert.htm) in the `StandardApexLibrary/System` folder. After that, one needs to add the 256 SHA digest of the new file to the JAR's manifest. Unfortunately, I also had to remove the signing files: `SFDC.SF` and `SFDC.RSA`; before the rezipped JAR worked properly. 

Result was working auto-completion for Assert! 
![image](https://user-images.githubusercontent.com/1448099/214774812-0218f9b3-984d-4966-b0af-286d25740c4b.png) 

If it's supported, I can post detailed instructions on how to patch the JAR yourself (I will not provide a patched JAR). 

@camisotro @AnanyaJha

**Comment by camisotro** [comment]
I have no interest in going that route, this should be up to SFDC to fix with each new release :)

**Comment by AnanyaJha** [comment]
Hi @zerkz you've got it - and we have a task this iteration to build a new JAR and get this updated. Have to agree with @camisotro, we'll get this resolved for y'all soon.
