### ISSUE TITLE
Retrieve With Manifest (beta) failed to run "Missing metadata type definition in registry for id 'marketingappextension'"

### ISSUE THREAD

**Issue by hreethwan** [forcedotcom/salesforcedx-vscode#4589]
### Summary

Hello,

I have prepared a package.xml and am using vscode to retrieve metadata from an org. My manifest/package.xml retrieval fails rather immediately and gives the following errors:

Missing metadata type definition in registry for id 'marketingappextension'.

### Steps To Reproduce:

1.  Right click on package.xml and click on the option "SFDX: Retrieve Source in Manifest from Org"
1.  Error message occurs in output section

### Expected result

Should have been able to retrieve the metadata from the org without any issues

### Actual result

Metadata retrieval failed immediately

### Additional information

![image](https://user-images.githubusercontent.com/58544101/207519113-f461cd49-05b4-4dd9-ab15-3065e2d6963d.png)

![image](https://user-images.githubusercontent.com/58544101/207519146-bbc08fde-cf21-4d09-b71f-bdf63389639e.png)

**Salesforce Extension Version in VS Code**:

v56.5.1

**SFDX CLI Version**:

sfdx-cli/7.180.0 darwin-x64 node-v18.12.1

**OS and version**:

macOS Monterey Version 12.6.1

**Comment by AnanyaJha** [comment]
Hi @hreethwan thanks for reporting this! Are you getting this error if you try to retrieve the `MarketingAppExtension` outside directly rather than through the `package.xml`?

@gbockus-sf Potentially a missing type from SDR?

**Comment by hreethwan** [comment]
Hi @AnanyaJha I was able to use another tool to retrieve the MarketingAppExtension metadata successfully, which is a package.xml builder built by another source

**Comment by randi274** [comment]
@hreethwan were you able to use the SFDX CLI to retrieve the data? 

I'm not seeing MarketingAppExtension in our shared library's [registry](https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/metadataRegistry.json), but I wanted to check that if that tool worked for you before moving forward with a change for this.
