### ISSUE TITLE
VS Code: Show Lightning Explorer doesn't appear in settings

### ISSUE THREAD

**Issue by SeriousIgor** [forcedotcom/salesforcedx-vscode#4601]
### Summary

I decided to turn on the Lightning Explorer feature, but I can't find it in settings now/

### Steps To Reproduce:

1.  Go to Settings.
1.  Write down command "Salesforcedx-vscode-lightning: Show Lightning Explorer"

### Expected result

A corresponding setting with a checkbox should appear.

### Actual result

Nothing appears in the settings tab.

### Additional information

Screenshot:
![image](https://user-images.githubusercontent.com/58520428/208394022-2e8994eb-1bfd-4f08-a52d-e68c18e7981e.png)

**Salesforce Extension Version in VS Code**: v56.5.1

**SFDX CLI Version**: v7.174.0

**OS and version**: macOS Monterey v12.3.1

**Comment by randi274** [comment]
Hi @SeriousIgor - the 'Show Lightning Explorer' setting is one that we actually removed back in 2020 as we concluded a beta feature run with it, so its absence is expected! Are you seeing a reference to it anywhere in our official documentation? If so we can log a doc bug for it and make sure that reference gets cleaned up. Thanks!

**Comment by SeriousIgor** [comment]
@randi274 Thanks for your answer.
No, I haven't seen this in any official documentation. I only saw some old videos and seen comments from the Salesforce Help website.
So, are there any alternatives to this feature, because it seems to be very comfortable to use it while developing, with no need to open a documentation page in a browser?

**Comment by randi274** [comment]
Hi @SeriousIgor - sorry this one was auto-closed (the tag should've been removed with your response). We are making some updates to include more helpful links to release notes from the extensions, but nothing that previews LWCs quite like the Lightning Explorer did, unfortunately.
