### ISSUE TITLE
Error deploying or retrieving source

### ISSUE THREAD

**Issue by ivannapanchenkoseequent** [forcedotcom/salesforcedx-vscode#4602]
Type: <b>Bug</b>

When I tried to retrieve or deploy file using the UI, visual studio code for windows through this exception
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

Step to reproduce

1) Click right on the package.xml and select retrieve source from Org

This issue come from the last few days as week before it was working perfectly

Configuration

1) Vs Code :
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

2) Java version 17
3) Salesforce CLI version : sfdx-cli/7.181.1 win32-x64 node-v18.12.1
4) Salesforce Extension Pack : v56.5.1

Extension version: 56.5.1
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.76GB free)|
|Process Argv|--crash-reporter-id 6ae20942-0669-43b9-bc6b-992b705d31ab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by randi274** [comment]
@ivannapanchenkos - did you upgrade in the last few days? We've skipped a few releases but this was a previously known issue for us. If you revert back to v56.4.1 or even 55.8.0, does that work again for you? 

The known issue + notes on downgrading: https://github.com/forcedotcom/salesforcedx-vscode/issues/4261

**Comment by ivannapanchenkos** [comment]
@randi274  thanks for your answer I will have a look now and let you know :)

**Comment by ivannapanchenkos** [comment]
@randi274  I have join to this company 3 weeks ago and it was perfect working so I get the last version not the version from 4 months ago. Anyway, I double checked by installing the version 55.8.0 and I know about the issue so at the beginning I installed the version v56.4.1 and it still doesn't work. 
What it is weird, 2 weeks ago it was working and from last week it doesn't work anymore. 
I was doing my budget with Salesforce and pushing and retrieving for my devs org. Right now I am not able to do it

**Comment by tallytsabary** [comment]
I am facing the same issue with the exact same details as above.

**Comment by ivannapanchenkoseequent** [comment]
@tallytsabary  please comment on this new issue https://github.com/forcedotcom/cli/issues/1864 
I don't know why they closed this issue

**Comment by randi274** [comment]
Hi @ivannapanchenkoseequent - our Stale bot seems to be malfunctioning! Sorry this one was auto-closed for you. Are you still facing this issue with the latest version of the Salesforce Extensions?

**Comment by tallytsabary** [comment]
Hi @randi274 and @ivannapanchenkoseequent 
I think the issue was that the visibility of the fields was not set.
In order to bypass this, I had to add the Admin Profile to the package.xml 
That works fine if the target org is simple dev org, but if it is from DevHub that caused allot of troubles as the Admin profile was not matching.

I am still trying to find the best way for my team to handle it.

Thank you

**Comment by gbockus-sf** [comment]
@ivannapanchenkoseequent 
I recently dug into an issue exactly like this one where the user had updated the xml file association away from the `forcesourcemanifest` to `xml` which alters what commands we should for manifest files.  You can verify this is your issue if you right click on the manifest file... you should see commands like `SFDX: Retrieve Source in Manifest from Org` including the string Manifest.  If you see the non-manifest commands then there is an issue with how vscode is configured to handle xml files in the manifests directory.  
Also you can check the file association in the bottom toolbar of vscode when you have the manifest file selected: 
![Screenshot 2023-02-01 at 4 53 47 PM](https://user-images.githubusercontent.com/76090802/216184203-2cc7c76c-0fe5-485f-aa5a-467796bc2312.png)

**Comment by azielin4** [comment]
I have the same issue.

VSC 1.76.1
sfdx-cli/7.191.1 win32-x64 node-v18.14.2
Salesforce CLI Integration v55.4.1

**Comment by CristiCanizales** [comment]
Closing this to keep track of the issue with #4626
