### ISSUE TITLE
Org Browser fails with SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jdority** [forcedotcom/salesforcedx-vscode#4607]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

Authorize an Org, then try to use Org Browser

### Expected result

**Org Browser allows you to see org contents**

### Actual result
SyntaxError: Unexpected end of JSON input

### Additional information
json file in .sfdx directory does indeed have INVALID JSON syntax

Error: Parse error on line 14:
..."isDevHub": false} {	"accessToken": "3
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'

**Salesforce Extension Version in VS Code**:  v56.5.1

**SFDX CLI Version**:  sfdx-cli/7.181.1 darwin-x64 node-v18.12.1

**OS and version**: macOS 12.3 (21E230)

**Comment by jdority** [comment]
New machine, JAVA not installed - installed v17 and tried again ... no error.    Maybe I will hide under my desk now.

**Comment by randi274** [comment]
@jdority no worries, it totally happens 😄 FWIW I have seen this same error randomly before as well! Did you happen to reboot VS Code in that time too? We can keep this one open for a bit just in case it pops up again for you - let us know if you see it again and we'll get some repro steps to try and narrow this one down!
