### ISSUE TITLE
Aura Extension error:

### ISSUE THREAD

**Issue by NagarjunaParala** [forcedotcom/salesforcedx-vscode#4608]
Aura Extension causing the following every time VS loaded.  Hence, Not able to retrieve the salesforce metadata

**The Aura Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.**

![image](https://user-images.githubusercontent.com/96948254/209620342-eb427335-e4bc-4000-8ea6-ef19689d1d98.png)

**Comment by klewis-sfdc** [comment]
Hi @NagarjunaParala, thanks for reporting the issue.  We have seen this issue in the past also (#1267). Can you let us know what operating system you are on and which version of the extensions you are running?

**Comment by klewis-sfdc** [comment]
OK, I see that you provided more information about your environment on issue #4609.  I will follow up there.

**Comment by klewis-sfdc** [comment]
See issue #4609.
