### ISSUE TITLE
"SFDX: Set a Default Org failed to run" even though the output shows it has true

### ISSUE THREAD

**Issue by raksh36** [forcedotcom/salesforcedx-vscode#4610]
### Summary

After the project loads, the default org shows an error
### Steps To Reproduce:

1. Authenticate against a sandbox using SFDX : Authorize an org
2. After the credentials are entered we see the org value is set but the extension throws an error stating 'SFDX: Set a Default Org failed to run'. The output tab shows the result as 
Starting SFDX: Set a Default Org.

16:50:22.144 sfdx force:config:set defaultusername=dev4c
=== Set Config

 Name            Value Success 
 ─────────────── ───── ─────── 
 defaultusername dev4c true    
16:50:54.78 sfdx force:config:set defaultusername=dev4c
 ended with exit code 1
3. When I try to check the Org contents on the org browser, it throws this error- 'SyntaxError: Unexpected end of JSON input' and metadata does not load.

### Expected result
Default org should show as success and Org browser should display org metadata
.

### Actual result

Output tab throws the exit code as 1 when we set a default org. Org browser does not display any metadata and throws SyntaxError: Unexpected end of JSON input

### Additional information
![SyntaxError_UnexpectedEndOfJSONinput](https://user-images.githubusercontent.com/14123952/209819426-f15056a8-2328-47d7-a877-a0deb0dc466f.png)
![SFDX_Set a Default Org failed to run](https://user-images.githubusercontent.com/14123952/209819429-cf14d3f8-0374-479f-9a76-b27f3b112eb0.png)

**Salesforce Extension Version in VS Code**: 

**SFDX CLI Version**: sfdx-cli/7.182.1 win32-x64 node-v18.12.1

**OS and version**: Windows 10 Enterprise. Version - 10.0.19044 Build 19044

**Comment by raksh36** [comment]
Salesforce CLI Integration Extension version: v56.5.1

**Comment by CristiCanizales** [comment]
Hello! Could you please try updating to v56.14.0 and check if this is still an issue?

**Comment by raksh36** [comment]
CLI Integration extension upgraded to v56.14.0 and the problem still exists
![image](https://user-images.githubusercontent.com/14123952/214869750-a259bca4-6925-4cb3-b277-e4b5be93b11c.png)
![image](https://user-images.githubusercontent.com/14123952/214869921-ff0a8f14-c58c-4dbc-88b1-8d664b5f9f37.png)
![image](https://user-images.githubusercontent.com/14123952/214870174-fa7e19f0-d168-4ab9-890f-549e295fbbf8.png)

**Comment by CristiCanizales** [comment]
Hello! 🙂 Could you please tell me the type of the org? (Profesional, Enterprise, etc)

**Comment by raksh36** [comment]
Org type - Unlimited Edition

**Comment by raksh36** [comment]
> Hello! 🙂 Could you please tell me the type of the org? (Profesional, Enterprise, etc)

Org type - Unlimited Edition

**Comment by gbockus-sf** [comment]
Hi @raksh36 
Sorry for the delay.  So many issue so little time :)  I've seen reports in the past where this kind of error occurs if there is an invalid zero byte json file in the the sfdx configuration directory.  Can you check if there are any empty json files under the .sfdx dir? [Ref](https://salesforce.stackexchange.com/questions/391686/vs-code-unexpected-end-of-json-input-error-when-changing-the-default-org/391687#391687)

There are local configs for the project found in the .sfdx directory of your project and global configs found under ~/.sfdx

**Comment by raksh36** [comment]
Hi @gbockus-sf
Running the above command listed as a sanity check throws a non-zero exit code error (Exit-code 1). But the output is shown as success - true
![Non-zero error](https://user-images.githubusercontent.com/14123952/219048351-72a303c8-8261-4d96-b205-735384568aad.png)

**Comment by raksh36** [comment]
Hi @gbockus-sf is there a way where we can connect and try to debug this?
For an existing project created an year ago, it manages to work fine when i switch the org to a particular instance (in this case stgbeta). This works only when i switch the org (which throws 'Unexpected end of JSON input' error) and restart VSCode.
Strange behavior.

**Comment by gbockus-sf** [comment]
Howdy @raksh36 
You can join our slack channel [here](https://join.slack.com/share/enQtNDgzNjM5NTg3ODU3Ny03YmRkNjhkM2I1NDExYzM4ZGRlOWFlMGFhYzlhNzdmYjU1YTY3NThlNDdhYjA5ZjBhYmI4ZDc2OTdlNWRlMjgz)

I def suspect there is something going on with your configuration files. [ref](https://github.com/forcedotcom/cli/issues/726)

**Comment by diyer** [comment]
Closing this old issue. Please create a new issue if the problem persists with our latest VS Code extensions. Thank you!
