### ISSUE TITLE
Cannot add breakpoint to anonymous apex

### ISSUE THREAD

**Issue by benji1304** [forcedotcom/salesforcedx-vscode#4618]
### Summary
Following the instructions [here](https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger) to use the Apex Replay Debugger. 

I cannot add a breakpoint or checkpoint to a file that is either saved as anonymous apex (.apex) or the language is set as anonymous apex. It works if i save as anonymous apex, then change the language to apex (ctrl+k,m, apex) 

some more flavour from the docs above
> Easy Debugging[#](https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger/#easy-debugging)
Quickly debug your Apex development work without explicitly setting trace flags:

> Open your Apex test class or Anonymous Apex class with checkpoints or breakpoints set up.

Is this my misunderstanding here? This says i can open anonymous apex with breakpoint setup but I cannot add them. 

### Steps To Reproduce:

1.  Create file
2. Enter some apex
```
List<String> colors = new List<String>();
colors.add('blue');
colors.add('red');
colors.add('green');
colors.add('yellow');

for (integer i = 0; i < colors.size(); i++) {
    String curentColor = colors[i];
    Integer currentIndex = i;
}
```
3. Save as test.apex
4. Try to add a checkpoint or breakpoint in the row 

### Expected result

Breakpoint is created

### Actual result

Nothing happens.

### Additional information

file type .apex and language set as anonymous apex - no breakpoint
![image](https://user-images.githubusercontent.com/7213889/210905771-0b4f7ac8-949f-4fd4-a81c-1f8301d48671.png)

file type .apex and language set as apex - breakpoint added
![image](https://user-images.githubusercontent.com/7213889/210905838-9a69f4de-e57b-4ff2-8719-b8790c32d772.png)

**Salesforce Extension Version in VS Code**:
v56.5.1

**SFDX CLI Version**:
sfdx-cli v7.182.1

**OS and version**:
Win 11

**Comment by AnanyaJha** [comment]
Hi @benji1304 ! Thanks for sharing this issue - this is a known limitation of the Replay Debugger experience. Currently, we can not set breakpoints in Anonymous Apex files. Instead, breakpoints can be set within any of the methods/files referenced by the Anonymous Apex file.

**Comment by benji1304** [comment]
Thanks @AnanyaJha - my misunderstanding from the docs!
