### ISSUE TITLE
sobject definitions refresh fails with Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by NH1922** [forcedotcom/salesforcedx-vscode#4630]
I have created a new SFDX project with Manifest and authorized a sandbox using Vscode palette command

I then retrieved the metadata using force:retrieve command and tried running refresh Sobject definitions using VScode palette command. It gives me an error 

>Command 'SFDX: Refresh SObject Definitions' resulted in an error (An unknown error occurred. Please consult the log for more details.)

In the console, I see 

```
13:17:23.98 sfdx sobject definitions refresh
Unexpected token N in JSON at position 0
13:17:24.435 sfdx sobject definitions refresh
 ended with error Unexpected token N in JSON at position 0
```

This is a fresh project I've created. I am running into the same issue with existing projects too. 

VS Code Information: 
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:05:47.808Z (6 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

I have installed SFDX using npm
sfdx-cli/7.179.0 darwin-arm64 node-v19.4.0

**Comment by gbockus-sf** [comment]
Hi @NH1922 
A couple of clarifying questions for you. 
1. What version of the SF Extensions for VSCode are you currently running (v56.14.0 is the latest as of last week). 
2. When you say `retrieved the metadata using force:retrieve command` was that via the sfdx cli or did you execute the retrieve via a VSCode command? 
Thanks

**Comment by gbockus-sf** [comment]
@NH1922 please reopen if still an issue for you.
