### ISSUE TITLE
Component conversion failed: This directory does not contain a valid Salesforce DX project.

### ISSUE THREAD

**Issue by jonny-harte** [forcedotcom/salesforcedx-vscode#4636]
### Summary
Randomly started getting this error when saving files or right clicking and selecting Deploy Source to Org

`Component conversion failed: This directory does not contain a valid Salesforce DX project.`

running `sfdx force:source:push -f` from the cli works fine

### Steps To Reproduce:
Save file with Salesforcedx-vscode-core › Push-or-deploy-on-save: Enabled

### Expected result.
file deploys successfully

### Actual result
Component conversion failed: This directory does not contain a valid Salesforce DX project.

### Additional information
I haven't made any changes to the project files recently and the project has been working fine for over a year. Other members of the team haven't reported any issues.

**Salesforce Extension Version in VS Code**:
v56.14.0

**SFDX CLI Version**:
sfdx-cli/7.183.1 darwin-x64 node-v18.12.1

**OS and version**:
MacOS 13.1

**Comment by CristiCanizales** [comment]
Hello!🙂 Are you still having this issue? We've been trying to reproduce the error but have not been able to do so, but have had several reports and are trying to track down the problem

**Comment by jonny-harte** [comment]
Hi @CristiCanizales yes. I believe the issue is releated to some subfolders I created inside the main>default>flow folder to help organise them. The issue appears to start after I move a flow into one of the folders. If I close and reopen vscode the issue appearing be resolved until another flow is moved into a subfolder.

**Comment by wrone** [comment]
Downgrade of "Salesforce CLI Integration" extension to 56.16.0 helped

**Comment by CristiCanizales** [comment]
Closing this to keep track of the issue with #4775
