### ISSUE TITLE
SFDX: Retrieve source in Manifest from Org failed when retrieving CustomLabels

### ISSUE THREAD

**Issue by naritsan** [forcedotcom/salesforcedx-vscode#4641]
### Summary

when I try to execute [SFDX: Retrieve source in Manifest from Org ], it always fail if package.xml
contains CustomLabels type.

### Steps To Reproduce:

1.  create sfdx project with manifest in Vscode
2. authorize an org
3. add types below in package.xml
```
    <types>
      <members>*</members>
      <name>CustomLabels</name>
    </types>
```
4. execute SFDX: Retrieve Source in Manifest from Org

### Expected result
CustomLabels components is retrieved correctly

### Actual result
error occured.
Metadata API request failed: Component conversion failed: This directory does not contain a valid Salesforce DX project

### Additional information

Retrieving metadata using Salesforce CLI directly from cmd successed.

**Salesforce Extension Version in VS Code**:
v56.14.0

**SFDX CLI Version**:
7.183.1 win32-x64 node-v18.12.1
**OS and version**:
Windows10 Pro 22H2

**Comment by gbockus-sf** [comment]
thanks for the update @naritsan
