### ISSUE TITLE
Missing Org Browser Icon on Side Bar

### ISSUE THREAD

**Issue by Bnezes** [forcedotcom/salesforcedx-vscode#4654]
<Hi Team,

I am missing my ORG Browser ICON on my side bar of visual studio code. 
Everything works fine I can connect to org and retrieve/deploy code using the 'Retrieve/deploy from source command' but I cannot see the ORG Browser Icon anywhere.
 I did right click on the side bar and I can select other icons(extension, file explorer..etc) but not the ORG Browser cloud icon.

Please advise
Thanks in advance

!--
NOTICE: While GitHub is the preferred channel for reporting issues/feedback, this is not a mechanism for receiving support under any agreement or SLA. If you require immediate assistance, please use official support channels.
-->

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by AnanyaJha** [comment]
Hi @Bnezes thanks for reporting this issue. Could you give us some more information on what version of the Salesforce Extensions you're using? You can find this info by navigating to the Marketplace icon on the left side panel and searching for "Salesforce Extensions"

**Comment by Bnezes** [comment]
Hi AnanyaJhaMy current salesforce cli extention is version: 56.16.0. My VS code version is 1.74.2. This a working machine the runs from a VPN. I already uninstalled and installed the software but still same is happening.. see bellow pictures for reference. No org browser icon or option for it on the left activity bar. Image from the web bellow: 1 shows the org browser.  Thank you in advanceBruno almeidaOn 2 Feb 2023, at 03:03, AnanyaJha ***@***.***> wrote:﻿
Hi @Bnezes thanks for reporting this issue. Could you give us some more information on what version of the Salesforce Extensions you're using? You can find this info by navigating to the Marketplace icon on the left side panel and searching for "Salesforce Extensions"

**Comment by AnanyaJha** [comment]
Thanks @Bnezes Can you also share what type of org you're connected to? Ie. a scratch org, sandbox, Dev Hub etc. Currently, the [Org Browser is not available from source-tracked orgs](https://developer.salesforce.com/tools/vscode/en/user-guide/org-browser).

**Comment by Bnezes** [comment]
Its a sandbox. I had the icon before. But dragged it out of the sidebar and never managed to get it back..my other colleagues have the icon on their vs code with same versions of cli and vs codeSent from my iPhoneOn 8 Feb 2023, at 18:54, AnanyaJha ***@***.***> wrote:﻿
Thanks @Bnezes Can you also share what type of org you're connected to? Ie. a scratch org, sandbox, Dev Hub etc. Currently, the Org Browser is not available from source-tracked orgs.

**Comment by gbockus-sf** [comment]
I'm gonna close this for now as it's not an issue that needs any kind of attention.  Feel free to reopen if you disagree.
