### ISSUE TITLE
Retrieving Source and Deploying to Source running endlessly 

### ISSUE THREAD

**Issue by snps-praky** [forcedotcom/salesforcedx-vscode#4657]
Hello,
I am unable to retrieve or deploy source components from my sandbox org even after successful org authorization. 
SFDX CLI version:
sfdx-cli/7.185.0 darwin-x64 node-v18.12.1
Java version:
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.361-b09, mixed mode)

**Comment by gbockus-sf** [comment]
Howdy @snps-praky 
What version of the VSCode extensions are you running? 

![Screenshot 2023-02-01 at 4 46 02 PM](https://user-images.githubusercontent.com/76090802/216181863-b6e14e9c-4c13-430f-af1d-6f54cd1ecbd1.png)

Just to clarify... no error messages at all right? The deploy or retrieve just hangs forever?   We have had reports in the past that performance on sandboxes can be really bad.  Lemme see if I can find that information.  You might start a retrieve and just let it sit and see if it ever finishes.

**Comment by snps-praky** [comment]
> Howdy @snps-praky What version of the VSCode extensions are you running?
> 
> ![Screenshot 2023-02-01 at 4 46 02 PM](https://user-images.githubusercontent.com/76090802/216181863-b6e14e9c-4c13-430f-af1d-6f54cd1ecbd1.png)
> 
> Just to clarify... no error messages at all right? The deploy or retrieve just hangs forever? We have had reports in the past that performance on sandboxes can be really bad. Lemme see if I can find that information. You might start a retrieve and just let it sit and see if it ever finishes.

Hello @gbockus-sf - I am on V56.
<img width="667" alt="Screen Shot 2023-02-01 at 2 48 55 PM" src="https://user-images.githubusercontent.com/112983154/216183140-60ac2089-3800-4c93-b028-55d41ac05ec5.png">

Also, Yes no error message. On production and UAT, orgs retrieve I got the "The Org cannot be found" error while doing the same operation. But that's once or twice.

**Comment by gbockus-sf** [comment]
Thanks for the follow up @snps-praky.
