### ISSUE TITLE
Takes too much time to load

### ISSUE THREAD

**Issue by Nabeelkhan98** [forcedotcom/salesforcedx-vscode#4660]
When I open VSCode, Salesforce CLI extension taken more than 5 minutes to load

**Comment by AnanyaJha** [comment]
Hi @Nabeelkhan98 thanks for posting! Can you share what version of the Salesforce Extensions you're working with? You can find this info by navigating to the Marketplace tab on the left side panel and searching for "Salesforce Extensions". Thanks!

**Comment by Nabeelkhan98** [comment]
Hi Ananya,
Thanks for your reply.
I'm using Salesforce Extension Pack,  Version : v56.16.0

**Comment by mkeats** [comment]
I'm also experiencing very slow start-up times for the Salesforce CLI extension.

Salesforce CLI Extension v56.16.0
Activation Time: 25068ms (although I have seen over 30000ms many times.)

**Machine**
OS: Windows 10 Enterprise
CPU: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz   2.50 GHz
RAM: 32.0 GB

**Comment by jejmacbeth** [comment]
Same issues as above. 

Also Salesforce CLI Extension v56.16.0
Load times in excess of 20000s all the time.

Specs:
Windows 10 Enterprise
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
16.0 GB RAM

**Comment by randi274** [comment]
Thanks for the feedback! We're currently tracking this under the open issue #4529. I'm going to close this one to keep the information all together, but feel free to add any additional context there as well. Other helpful things for us to know - how large are the projects you're working with? Is there are number of Apex, LWCs, or custom objects, for instance? Or does this also happen with a new project for you?
