### ISSUE TITLE
Local Java runtime is unsupported

### ISSUE THREAD

**Issue by chiragpaliwal-toast** [forcedotcom/salesforcedx-vscode#4667]
### Summary

Opening VSCode greets an error. 
`Local Java runtime ("/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home") is unsupported. Set the salesforcedx-vscode-apex.java.home VS Code setting to a runtime outside of the current project. For more information, go to [Set Your Java Version](https://developer.salesforce.com/tools/vscode/en/vscode-desktop/java-setup).`

I have tried reinstalling VSCode, multiple versions of JAVA (11, 17), and Salesforce CLI, but nothing seems to resolve the issue.

A lot of extension features don't work, Apex language suggestion, Apex Replay Debugger, etc.

### Steps To Reproduce:

1.  Open VSCode to any SFDX project.

### Expected result

The error shouldn't be thrown, Apex language suggestion, Apex Replay Debugger, etc, should work.

### Actual result

Opening VSCode throws an error and none of the above features work.

### Additional information

<img width="864" alt="image" src="https://user-images.githubusercontent.com/122250011/217465306-7bda1824-57ce-4fa8-bee6-fc51a3cbf90b.png">

When starting Apex Replay Debugger
<img width="696" alt="image" src="https://user-images.githubusercontent.com/122250011/217465533-b54ac5cb-1c15-4735-af45-5c642090175f.png">

**Salesforce Extension Version in VS Code**: `v56.16.0`

**SFDX CLI Version**:  `sfdx-cli/7.186.2 darwin-arm64 node-v18.13.0`

**OS and version**: `MacOS Ventura 13.2 (22D49)`

**JAVA version**: 
`openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)`

**Device**: `Macbook Pro M1 (Apple Silicon)`

**VSCode Version**: 
`Version: 1.75.0
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:26:31.005Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No`

**Comment by jeffb-sfdc** [comment]
@chiragpaliwal-toast I attempted to reproduce the issue you reported but wasn't able to reproduce it.  My first question for you is, does the path `/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home` exist in your machine?

The location in the code where this check is taking place is packages/salesforcedx-vscode-apex/src/requirements.ts, in `checkJavaRuntime()`

The value of `filePath` for you is `/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home`.

On line 67 there is:
```
      if (isLocal(javaHome)) {
        // prevent injecting malicious code from unknown repositories
        return reject(
          nls.localize('java_runtime_local_text', javaHome, SET_JAVA_DOC_LINK)
        );
      }
```

The "java_runtime_local_text" string here is the "Local Java runtime..." message.

`isLocal(javaHome)` is essentially `!path.isAbsolute(javaHome)`

https://www.w3schools.com/nodejs/met_path_isabsolute.asp



Your path is not a local path (`/Library/...`) so you should not be seeing this message.

OK, I hate to say this, but if this path exists and you are still seeing this issue, please shut down VS Code and reboot your machine.  This is an environment variable, and so maybe rebooting your machine will flush out something that's either being cached or not being updated.  Please try this and let us know if you still get this issue.

**Comment by chiragpaliwal-toast** [comment]
The path existed on my machine, and I had tried shutting down VSCode and rebooting my machine as well. 
The issue finally got resolved after I removed the java path from the extensions settings and set the JAVA_HOME environment variable. 
Thank you for taking a look into this! Cheers! ✌🏻
