### ISSUE TITLE
 SFDX: Deploy Source to Org - sometimes it is very slow (over 5 minutes)

### ISSUE THREAD

**Issue by isimantov99** [forcedotcom/salesforcedx-vscode#4668]
### Summary

This ticket is opened upon @Randi Wilson's request after a discussion in #platform-dev-tools slack channel.
Link to the discussion: https://salesforce-internal.slack.com/archives/C4LRHH0AD/p1674635641763439

The issue
---------
While developing LWC, code deployment from VSCode to the Org gets stuck and may take 5 to 10 minutes every once in awhile.
It gets stuck once or twice an hour while usually deployment takes 10-15 seconds.

### Steps To Reproduce:
1.  create a standard n46 org
1.  deploy lwc to the org
1.  if you cannot reproduce, I can provide you one of my orgs.

### Expected result
Deployment should take 10-15 seconds and not minutes.

### Actual result
Code deployment takes 5-10 minutes sometimes.

### Additional information

Code was developed on Mac using VSCode.
After changing to new Orgs a few times, and updating to latest CLI, I thought that maybe it is something on my machine.
So I installed VSCode on a windows machine, installed the latest CLI and I still have the same problem.
It can still be many things on the machine. From VScode itself, thru security, thru network resource maybe. It is hard to say.
And of course it can be in the way the N46 Org is defined.

Another input: A teammate said that when it gets stuck, she cancels the deployment and then it is usually fast again.
Sadly, this trick does not work for me.

To my question in #platform-dev-tools whether this is a know issue I've got the following reply from @Randi Wilson:
this one isn’t a known issue for us, but it is one that’s popped up before, and we haven’t had enough consistent engagement to be able to track it down and solve.

I assume this is a subtle problem.
However, a solution will be much appreciated.

**Salesforce Extension Version in VS Code**:
Salesforce Extension Pack v56.16.0

**SFDX CLI Version**:
v56.16.0

**OS and version**:
Microsoft Windows [Version 10.0.14393]

**Comment by jlehrkind** [comment]
We area also experiencing slowness on deployment. over 8 minutes.

**Comment by randi274** [comment]
Hi @isimantov99 are you still experiencing intermittent slowness during deploys? We have another issue open recently #4865 that may share some overlap. Have you noticed it happens more during certain weeks/months than others? During release previews and other times when orgs are undergoing active change, we've seen that the deployment queues can get backed up, but there's unfortunately not an easy way to poll the status of the queue. 

If this is still happening, on the next occurrence can you can check to see if your deployment has actually succeeded, but you're just not getting notified in the org? More information on deployments generally here: https://developer.salesforce.com/blogs/2018/06/lets-talk-deployment-and-reasons-why-they-succeed-or-fail

**Comment by isimantov99** [comment]
Hi, @randi274.

I haven't use LWC in the lately but I am about to get back to it in a few weeks.
I read in the other bug that the problem may be related to source tracking.

I will report my finding, good or bad, once I'll get back to development.
