### ISSUE TITLE
Checkpoints don't update correctly in the Interactive Checkpoint Side Panel Window

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#4673]
### Summary

The Checkpoint Window in the side panel only displays the most recent checkpoint that was enabled. If you toggle multiple checkpoints on and off, whether through the Command Palette or Right Click Context Menus, the window will only show the most recent checkpoint.

### Steps To Reproduce:

1. Enable a checkpoint in your file through the CP or right click context menu
2. Click on the "Debug" tab and look at the "Checkpoint" window. It should display your recently enabled checkpoint.
3. Enable another checkpoint in your file.

### Expected result

Both checkpoints are shown in the Checkpoint window

### Actual result

Only the last checkpoint is displayed in the window.

### Additional information

<img width="459" alt="Screen Shot 2023-02-08 at 5 32 29 PM" src="https://user-images.githubusercontent.com/21326913/217693068-f4ba5ad2-ef44-42eb-8b51-eda8dc662bd3.png">

**Salesforce Extension Version in VS Code**: 56.16.0

**SFDX CLI Version**: sfdx-cli/7.186.2

**Comment by gbockus-sf** [comment]
Looking into this issue I found that there has been a change to how we can id breakpoints for tracking the existence of the checkpoint in the side panel. 

Repo steps:
- Add a checkpoint on a line (say 7) via the CP.
- Add another checkpoint via the context menu on the next line (add a breakpoint, then edit it setting the expression to checkpoint)
