### ISSUE TITLE
Syntax Highlight does not work

### ISSUE THREAD

**Issue by Shokhan** [forcedotcom/salesforcedx-vscode#470]
![screenshot_1](https://user-images.githubusercontent.com/22928752/41148266-42aa5a16-6b11-11e8-8cde-5e5119b369ff.png)

**Comment by vazexqi** [comment]
![syntaxhiglightingapex](https://user-images.githubusercontent.com/54414/41163479-9d91fd7c-6aed-11e8-8840-d4235782d1e8.gif)

@Shokhan - The colors depend on your choice of themes. See the attached gif where I cycle through the default themes in VS Code. Some themes have color nuances between the different categories. Try selecting a theme that has more nuance if you prefer that.

**Comment by vazexqi** [comment]
Closing this since there hasn't been any response and things seem to be working as expected. Please reopen if you feel otherwise. Thanks!

**Comment by Shokhan** [comment]
Thanks for clarifications! It's working
