### ISSUE TITLE
Refresh SObject Definitions get an error

### ISSUE THREAD

**Issue by mostafaghonem** [forcedotcom/salesforcedx-vscode#4713]
### Summary

when running SFDX: Refresh sObject Definitions I get an error 

### Steps To Reproduce:
1. Sign in to Developer Org
2. Check that the connection works by selecting "SFDX: Deploy This Source to Org" for example
3. Select "SFDX: Refresh SObject Definitions"

### Expected result
The SObject definitions should be refreshed

### Actual result
get an error

### Additional information
the output log :
sfdx sobject definitions refresh
Failure performing sObject describe request to https://mostafaghonem-dev-ed.my.salesforce.com/services/data/v46.0/composite/batch failed, reason: connect ETIMEDOUT

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**: 7.176.1

**Salesforce extension pack version**: v57.3.0

<img width="431" alt="err" src="https://user-images.githubusercontent.com/39755843/221535540-455c617e-9443-4da4-942c-23d22ec389f8.PNG">

**Comment by jeffb-sfdc** [comment]
@mostafaghonem I attempted to reproduce the issue you reported but I wasn't able to reproduce it.  I was running:
v57.7.0 of the extension
v7.193.2 of SFDX

Could you please update both the Salesforce extension, and SFDX to the latest version, and try to reproduce the issue.

If you see the issue still happen, please run the `Developer: Show Running Extensions` command within VSCode, and reply back which Salesforce extensions are running, and what their version numbers are
