### ISSUE TITLE
Add Setting for Including Code Coverage when Running Tests

### ISSUE THREAD

**Issue by dylanribb** [forcedotcom/salesforcedx-vscode#473]
In the most recent update of the Salesforce DX CLI (Summer '18), the default setting was changed when running `sfdx force:apex:test:run` so that the `--codecoverage` flag is required to return code coverage when running tests. There doesn't appear to currently be a way to override this setting either in the VS Code extension or via a setting in the `sfdx-project.json` or `sfdx-config.json` files. 

Right now when the VS Code command for "Run All Tests" from an editor is invoked, it doesn't include coverage by default and I see no way to make it run with coverage included short of copy-and-pasting the commands into a terminal which significantly slows down the testing workflow.

It would be nice if this were a configurable option either via one of the configuration files or in the User and Workspace Settings sections of VS Code.

**Comment by vazexqi** [comment]
Closed in #482. 

We will revisit this again when we provide a dedicated pane for testing. See https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar that's available in Version 1.23+.
