### ISSUE TITLE
Support for big sibling Visual Studio IDE

### ISSUE THREAD

**Issue by softwarecraft** [forcedotcom/salesforcedx-vscode#475]
**Is your feature request related to a problem? Please describe.**
I have a client where dev tools are locked down and Visual Studio IDE is approved but VS Code is not (yet, waiting on request, could be months).

**Describe the solution you'd like**
Would it be practical to adapt the Salesforce Extension to work in the big sibling Visual Studio IDE?

Has anyone consider or looked at that?

**Describe alternatives you've considered**
According to these references it is possible with very little code changes to support certain VS Code extensions in Visual Studio IDE, I don't know if that applies to Salesforce Extensions:

- [Visual Studio IDE Tracks VS Code Extension Model](https://visualstudiomagazine.com/articles/2018/03/27/debug-adapters.aspx)
- [Adding support for Debug Adapters to Visual Studio IDE](https://blogs.msdn.microsoft.com/visualstudio/2018/03/26/adding-support-for-debug-adapters-to-visual-studio-ide/)

**Additional context**
None

**Comment by ntotten** [comment]
While it is true that Visual Studio provides the same extensibility for the Language Server Protocol and the Debugger protocol there are still significant differences in building, publishing, and maintaining extensions. It is something we certainly could consider for the future, but realistically its not going to happen any time soon.

That being said, everything you would need to do it is available. The full apex LSP isn't open source, but the extension is so it could be adapted. Additionally, the other extensions are fully open source. It would be a lot of work, but its possible.

For now though, hopefully, you can get VS Code approved.
