### ISSUE TITLE
Go to Definition displays error for built-in Apex classes

### ISSUE THREAD

**Issue by randi274** [forcedotcom/salesforcedx-vscode#4762]
### Summary

Go to Definition support works for user-created Apex classes, but is displaying an error when I try to use this command on built-in Apex classes (like `Database`).

### Steps To Reproduce:

1.  Reference a built-in Apex class in your IDE, like `Database.insert()`
1.  Right click the `Database` class, and select `Go to Definition`.
1.  An error will appear as it tries to navigate to jar:/StandardApexLibrary/System/Database.cls

### Expected result

Either no error will appear and we'll say "No definition found" (this is what happens if I use Go to Definition on the `insert` method), or we'll redirect the user to a faux class that they can use to examine all of the Database methods.

<img width="663" alt="Screenshot 2023-03-30 at 11 25 18 AM" src="https://user-images.githubusercontent.com/9795193/228889187-8385d407-af3b-4c12-83fc-c3645cd6defb.png">

### Actual result

<img width="979" alt="Screenshot 2023-03-30 at 11 24 03 AM" src="https://user-images.githubusercontent.com/9795193/228887441-5e0707cb-e63b-480a-b152-16a53fb6d749.png">

### Additional information

From examining our LSP, it is the path we're getting back from the Jar. I went back to v47.1.0 (~3 years ago), and we used to just say "No definition found for Database" as well. Then I went back to v52.1.0 (~2 years ago), and this same error pops up, so it's been this way for quite a while. For a bigger lift, we could see about adding these faux classes into our `.sfdx` directory so the user could examine the methods that we say we support, or redirect the user to our external documentation.

<img width="628" alt="Screenshot 2023-03-30 at 11 35 04 AM" src="https://user-images.githubusercontent.com/9795193/228889261-8bb0bfef-6448-40a7-ba03-aa3edff6d488.png">

**Salesforce Extension Version in VS Code**:
v57.7.0 comparing v47.1.0

**SFDX CLI Version**: 7.183.1

**OS and version**:
Mac Ventura 13.2.1

**Comment by lukeis** [comment]
fixed with commit 62f081328672d34f227a32ea725e085ee970c88c
