### ISSUE TITLE
Issue with VSCode Conflict Detection for Salesforce LWCs

### ISSUE THREAD

**Issue by jlnatarajan** [forcedotcom/salesforcedx-vscode#4765]
**Summary:** 

Conflicts are not being detected as expected for Lightning Web Components (LWCs) during VSCode conflict detection. 

**Steps To Reproduce:**

1.  Video attached: https://user-images.githubusercontent.com/85702580/228947617-76352ca0-14bd-469b-9296-ca6f8d15ca2a.mov

**Expected result:**

Conflict detected when test is run. 

**Actual result:**

No conflict detection messages displayed. 

**Additional information:**
*please see video above*

VS Code: Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
Salesforce CLI: sfdx-cli/7.193.2 darwin-x64 node-v18.14.2

**Comment by randi274** [comment]
Related info for trust or @AnanyaJha : https://sfdc.co/testConflictThread

**Comment by randi274** [comment]
Hey @jlnatarajan - is this actually an issue with Apex Triggers (or other metadata than LWCs not working correctly with conflict detection)? What I see in the attached video is:
- Have a Apex Trigger that's also been modified in the org
- Try to deploy with conflict detection turned on 
- Get conflict detection message -> choose to override
- Deploy again
- Get the same conflict detection message

I have seen this issue before, but not consistently, and am unable to reproduce it today. We also recently made a number of changes to our deploy/retrieve logic - can you retest and see if that's still an issue for you?
