### ISSUE TITLE
The "force data soql query" command has been deprecated

### ISSUE THREAD

**Issue by randi274** [forcedotcom/salesforcedx-vscode#4766]
### Summary

The CLI has deprecated the command `sfdx force:data:soql:query` and displays a warning: "The `force data soql query` command has been deprecated. Use "data query" instead."

### Steps To Reproduce:

1.  Use the command `SFDX: Execute SOQL Query`
1.  Just under where the query is executed, the warning message will appear.

### Expected result

No warning appears.

### Actual result

We upgrade to use "data query" as well. Also ensure backwards compatibility remains for older versions of the CLI.

### Additional information

**Salesforce Extension Version in VS Code**: v57.7.0

**SFDX CLI Version**: seen on version 7.185.0

**OS and version**: Windows

**Comment by kaustubhdapurkar** [comment]
Hi @randi274 , is this issue being actively worked upon by anyone in the team? If not, I would like to try to fix this bug.

**Comment by kaustubhdapurkar** [comment]
Hi @randi274 , I made a few changes to some files to add this new command (just replaced some lines of code in the existing command builder files to understand how this is working). When I build and run the command with the changes, I get this error

![image](https://user-images.githubusercontent.com/48684659/236665629-3b291fed-d6fa-471a-974e-a48451be2448.png)

I have the latest sf version installed and I also tried running the same command manually from the terminal and it works. Could you please help me with this issue?

![image](https://user-images.githubusercontent.com/48684659/236665749-3bf92106-17ee-4f8b-83e9-352fc7f4ad39.png)

Following are my changes -
![image](https://user-images.githubusercontent.com/48684659/236665808-9408f2c3-619b-453a-83b2-143c2c658b91.png)

![image](https://user-images.githubusercontent.com/48684659/236665841-a470dd53-0c06-4bd9-a12b-50f3a37f9f3a.png)

![image](https://user-images.githubusercontent.com/48684659/236665824-db9dd1ca-7320-422a-811c-82f0f3138360.png)

![image](https://user-images.githubusercontent.com/48684659/236665861-a53d4899-a3ca-4d05-a184-1a00683c20d1.png)

![image](https://user-images.githubusercontent.com/48684659/236665893-68292017-1f64-407f-8c64-83c2ad1f2199.png)

**Comment by randi274** [comment]
Hey @kaustubhdapurkar - we have not had a chance to look at this one, and we always welcome contributions! We haven't switched over any of our commands yet to use `sf` instead of `sfdx`, so I'm expecting this is actually a larger issue that we'll need to address (and also we'll need to ensure backwards compatibility while we can). If you're able to put up a draft branch for review, I'd be happy to take a look and see what issues you might be running into 👍

**Comment by daphne-sfdc** [comment]
Closing this issue as it was fixed in https://github.com/forcedotcom/salesforcedx-vscode/pull/5072.
