### ISSUE TITLE
Unable to build extensions locally

### ISSUE THREAD

**Issue by kaustubhdapurkar** [forcedotcom/salesforcedx-vscode#4769]
### Summary

I am trying to build a functionality with which you can specifically select the apex tests that you want to run. Currently you either run all the locally available tests at once or one test at a time.
To do the above, I am trying to build the extensions locally but am unable to do so. When I launch the extensions form the VSCode debugger with the "Launch Extensions" launch configuration, it opens a new VSCode window and throws an error saying -
>Activating extension 'salesforce.system-tests' failed: Cannot find module 'd:\Dev\OSS\salesforcedx-vscode\packages\system-tests\out\src' Require stack: - c:\Users\kaust\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js - c:\Users\kaust\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js - c:\Users\kaust\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js - .

The issue is most probably due to me not setting up the development environment correctly with all the dependencies and other pre-requisites. Your help will be greatly appreciated.

### Steps To Reproduce:

I am following all the steps mentioned in the `developing.md` file. Also, I am using git bash as my terminal and VSCode Insiders as my IDE
1.  Install nvm (windows machine)
2.  Install node
3. Install lerna and tslint globally
4. Clone the repo
5.  run `npm install`

    **note**: this gives me a warning saying,
>lerna WARN EWORKSPACES Workspaces exist in the root package.json, but Lerna is not configured to use them.
lerna WARN EWORKSPACES To fix this and have Lerna use workspaces to resolve packages, set `useWorkspaces: true` in lerna.json.)

    so I tried running the whole flow with and without setting `useWorkspaces: true`, still doesn't work

6. Open VSCode and and then Command Palette > Tasks: Run Task > Bootstrap
7. Invoke Command Palette > Build Task
8. In the docs it says open Command Palette and type "debug " but when I do this, I don't see any option that only says "debug ", so I launch extensions by navigating the debug tab of VSCode and then selecting the "Launch Extensions" configuration and the hitting the play button. Maybe the docs are outdated or I am missing an extension.

![image](https://user-images.githubusercontent.com/48684659/229372761-d4b445df-a9ef-4f39-8f3f-30be751ce928.png)

9. It opens a new VSCode window (insiders) and gives me this error,
>Activating extension 'salesforce.system-tests' failed: Cannot find module 'd:\Dev\OSS\salesforcedx-vscode\packages\system-tests\out\src' Require stack: - c:\Users\kaust\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js - c:\Users\kaust\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js - c:\Users\kaust\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js - .

![image](https://user-images.githubusercontent.com/48684659/229373249-f3e3c6b8-ba63-491e-b99a-d1fea4e9039a.png)

### Expected result

Extensions should build and run successfully.

### Actual result

Extensions are not running in the new window

### Additional information

**Salesforce Extension Version in VS Code**:
v57.7.0

**SFDX CLI Version**:
sfdx-cli/7.193.2 win32-x64 node-v18.14.2

**OS and version**: 
Edition	Windows 11 Home Single Language
Version	22H2
Installed on	‎05-‎10-‎2022
OS build	22621.1485
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by CristiCanizales** [comment]
Hello @kaustubhdapurkar ! Hope you're great 🙂 Sorry for delay. Did you try just using the extensions in a sfdx project? Like ignoring the `Activating extension 'salesforce.system-tests' failed:` error. You would just have to open a sfdx project in that new window you get after launching extensions, wait a few seconds to let them load, open Command Palette > Developer: Show Running Extensions and check if the extensions are indeed running

**Comment by CristiCanizales** [comment]
I'm asking because I actually have been getting the same every time but then the extensions work just fine 🙂  So let me know if it's the same for you!

**Comment by kaustubhdapurkar** [comment]
Hi @CristiCanizales , thank you so much for the info 😄, the extensions do work after the build even with that error.

**Comment by CristiCanizales** [comment]
Hello @kaustubhdapurkar, Awesome! I'm sorry it took us so long to give you an answer. I hope you don't run into any new issues but if you do, feel free to file a new one! Happy weekend 🙂
