### ISSUE TITLE
Unable to add error to standard page layout 

### ISSUE THREAD

**Issue by kolliramu546** [forcedotcom/salesforcedx-vscode#477]
Hi, I have a formula field which has hyperlink. On click of hyperlink, I am invoking apex which has PageReference return type. which may return to a website in a success case... In case of failed case it needs to return to the same page layout with an error message... I am able to navigate to the layout but I am unable to add error message...I am not using any vf page in between... Any help ? Thanks in advance..

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via GitHub issues. Please post your question on the [Trailblazer Community](https://success.salesforce.com), [Stackoverflow](https://salesforce.stackexchange.com/), or through other official support channels.
