### ISSUE TITLE
connect ETIMMED

### ISSUE THREAD

**Issue by Auraan1** [forcedotcom/salesforcedx-vscode#4774]
request to mysandboxorg.com failed, reason: connect ETIMEDOUT 13.110.45.70:443
I have updated my Salesforce CLI Integration but error is still showing on deploy changes to org then tried reinstall another version also but getting same error .

Salesforce CLI Integration install version - v57.7.0

**Comment by Auraan1** [comment]
Yes, when deploying changes to org

**Comment by randi274** [comment]
Hey @Auraan1 - are you still seeing this issue today? Does the issue happen with any other orgs, or just this one particular org? If it's just this org, can you try logging out from the org, reauthorizing, and restarting VS Code?
