### ISSUE TITLE
Issue with sfdx-cli/7.194.1 - Unable to deploy code after upgrade

### ISSUE THREAD

**Issue by briancodey** [forcedotcom/salesforcedx-vscode#4786]
Using Visual Studio Code for Windows, after upgrading CLI 7.194.1, I was unable to deploy code to Salesforce Org.  I got error "Component conversion failed: This directory does not contain a valid Salesforce DX project."

It is sfdc project folder that I had been working on, and it was functioning fine.  I checked the folder root and the sfdx-project.json was there.

Anyone running into similar issue?

**System:**  
- win32-x64 node-v18.15.0 
- Windows Windows 10 Enterprise 22H2, 
- Visual Studio Code (VSCode): Version: 1.77.1 (user setup)
     Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
     Date: 2023-04-04T23:21:11.906Z
     Electron: 19.1.11
     Chromium: 102.0.5005.196
     Node.js: 16.14.2
     V8: 10.2.154.26-electron.0
     OS: Windows_NT x64 10.0.19045
     Sandboxed: Yes

**Comment by randi274** [comment]
Hey @briancodey - is this still an issue for you? If so, can you try reopening the project by going to File > Open Folder > (Select Folder)? We've seen this issue come up when there's a bit of confusion between Windows & VS Code with out of date project paths.
