### ISSUE TITLE
SFDX：組織へのソースデプロイができない

### ISSUE THREAD

**Issue by satoeri510** [forcedotcom/salesforcedx-vscode#4814]
Type: <b>Bug</b>

1.エクスプローラーでメタデータを右クリック
2.SFDX:組織へソースをデプロイを実行
3.successfully ranが表示されるはず
=>以下のエラーとなりデプロイできない
Component conversion failed: This directory does not contain a valid Salesforce DX project.

このバージョンアップしてからできなくなった。
バージョン: 1.77.3 (user setup)
コミット: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
 日付: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Extension version: 57.10.2
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.78GB (0.19GB free)|
|Process Argv|--crash-reporter-id b95a743b-0ae1-4905-af6b-6823508d39f3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
functionswalk:30687959
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30713944

```

</details>

**Comment by randi274** [comment]
こんにちは @satoeri510. この問題についてお問い合わせいただきありがとうございます。

We are currently troubleshooting this issue with #4775. Please log any further details you may have there. In the meantime, if this is blocking your development we recommend installing the previous version of the extensions (specifically the Salesforce CLI Extension). 
![Screenshot 2023-04-20 at 6 46 35 PM](https://user-images.githubusercontent.com/9795193/233503431-7c1a4ee7-a313-4b65-a62e-9101a6a58b8c.png)
