### ISSUE TITLE
Error debugging anonymous apex for the first time

### ISSUE THREAD

**Issue by randi274** [forcedotcom/salesforcedx-vscode#4818]
### Summary

If a user has not yet debugged anonymous apex (or used any of our debugging functionality really), then they will see an error that the directory does not exist, although the log file will print out.

### Steps To Reproduce:

1.  Delete the `debug/logs` directory under `.sfdx/tools`
1.  Create an anonymous apex file
1. Run the command `SFDX: Launch Apex Replay Debugger with Current File`

### Expected result

The error is shown and debugging doesn't work: "ENOENT: no such file or directory, open '/Users/user1/myProjects/ebikes-lwc/.sfdx/tools/debug/logs/20230420185835.log'"

### Actual result

Debugging works as it does for subsequent runs.

### Additional information

As a workaround, debug a test first, and then debug anonymous apex. This works when running a test because when we debug tests, we pass the log ID to our apex-node library, which [ensures the directory exists](https://github.com/forcedotcom/salesforcedx-apex/blob/41855998caae1ff8533c9327e9d7aa9e1d4ce6f0/src/logs/logService.ts#L74) before querying for and saving the log. We haven't implemented that with the anonymous replay debugger (and we also don't have a log or test ID readily available that we could use to call the apex-node library).

<img width="1154" alt="Screenshot 2023-04-20 at 6 58 41 PM" src="https://user-images.githubusercontent.com/9795193/233504064-5a07e7db-fea5-4f53-a7dc-c5754fd43705.png">

**Salesforce Extension Version in VS Code**:
v57.11.0

**Comment by diyer** [comment]
Closing this issue as this has been fixed
