### ISSUE TITLE
Large repository - Very slow start up for Lightning Web Components extension

### ISSUE THREAD

**Issue by mwaddoupffdc** [forcedotcom/salesforcedx-vscode#4829]
### Summary

Depending on repo size, the LWC extension is taking a very long time to initialise. During this initialisation, all of the useful features such as code navigation etc. are not available. 

The issue becomes more apparent when working on larger repos. The repository I'm currently working with is a very large with thousands of files and the extension is taking **several hours** to start up.

### Probable Cause:

I've done some investigation and believe that the main culprit is `component-indexer` in the lwc-language-server. Specifically, the `componentEntries` getter is doing a sync file system read (which is taking roughly 20 seconds for me) and is **being called in a loop** from the `staleTags` getter.  In our setup, this results in the file system read being done more than 600 times. Obviously 600 times 20 seconds is not ideal!

Simply reworking the `staleTags` getter to avoid getting the componentEntries in a loop should yield a massive performance improvement.

### Steps To Reproduce:

This can be reproduced simply by using the extension in a suitable large SFDX project, but I've attached a video showing:

- the file system read taking > 20 seconds on our project
- LWC code navigation not working in our project while this is happening
- the file system read being triggered from within a loop that will execute 603 times 

Hopefully this is helpful.

### Expected result

The extension should be able to support large codebases.

### Actual result

The extension effectively doesn't work on large codebases since it takes so long to initialise.

https://user-images.githubusercontent.com/62286710/235180460-29f65a5c-a5ab-4c82-9f00-27de182156ec.mp4

**SFDX CLI Version**:
7.183.1

**OS and version**:
macOS Ventura 13.1.1

**Comment by randi274** [comment]
Thanks for all of your investigation done on this one so far! We'll have someone from our team take a look at this soon. In the meantime, if you'd like to have a go at fixing the issue yourself already having a sizable project accessible for testing, we welcome open source contributions in the language server as well: https://github.com/forcedotcom/lightning-language-server
