### ISSUE TITLE
Deployment status in org uses 15 char ids, CLI uses 18.

### ISSUE THREAD

**Issue by frackham** [forcedotcom/salesforcedx-vscode#483]
**Is your feature request related to a problem? Please describe.**
When deploying through CLI / VS Code, ids in CLI returns use 18 character ids, whereas Deployment Status page in Org uses 15. 
So when comparing, it's easy to believe that a deployment has not gone through (though most of us know how to match these) or not find the correct one, especially in particularly busy orgs.

**Describe the solution you'd like**
Either use 15 or 18 character ids throughout. Probably 18, though I suspect that the deployment status screen is out of your scope somewhat.

**Describe alternatives you've considered**
Alternative would be no change, really. Not sure if anyone else would consider this an issue to be honest, but consistency is helpful.

**Additional context**
See screenshot for example:
![capture](https://user-images.githubusercontent.com/2105204/41347036-019eeb00-6ef8-11e8-9850-48a9aaa12f22.PNG)

**Comment by vazexqi** [comment]
@amphro, @kbierbaum - Is this something that falls more under the Salesforce CLI?

**Comment by amphro** [comment]
In general, UI returns 15 char IDs so I think the deployment page is correct. APIs *should* return 18 char IDs. The CLI decided early on not to convert IDs (unless required) and to be consistent with the API. Which means CLI output will always be 18 char IDs unless the API mistakingly returns a 15 char ID. So this is something we won't change, unless there is an exceptional drive by the community for it that product gets behind.

**Comment by frackham** [comment]
That makes sense, thanks.
