### ISSUE TITLE
Java home setting should be more helpful

### ISSUE THREAD

**Issue by randi274** [forcedotcom/salesforcedx-vscode#4833]
### Summary

If a user provides a mostly valid Java path, but directs too far down along the path (such as to the `/bin/java`), the LSP will quietly fail to start up, but we won't provide any messaging to assist users other than to make the Apex experience nonfunctional. Our documentation is also unclear on this point.

### Steps To Reproduce:

1.  Set the `salesforcedx-vscode-apex.java.home` to include the `/bin/java` at the end of the path
1.  Reload Window
1.  The LSP won't start, but no error will be displayed to the user

### Expected result

A user receives an error that the LSP couldn't start up, or that the Java Home path was invalid.

### Actual result

In the Developer Tools there is an error message that the LSP didn't start up, but that's it.

### Additional information

![Screenshot 2023-05-01 at 6 50 25 PM](https://user-images.githubusercontent.com/9795193/235544973-db49e234-6ce8-450f-912b-61fc8f3603b8.png)

**Salesforce Extension Version in VS Code**: v57.11.0

**SFDX CLI Version**: 7.183.1

**OS and version**: Mac 13.3.1

**Comment by diyer** [comment]
Closing this as we have made some improvements since in guiding the users about setting java home. thank you for filing this!
