### ISSUE TITLE
Unabled to deploy/retrieve manifest file with default settings after creation

### ISSUE THREAD

**Issue by gbockus-sf** [forcedotcom/salesforcedx-vscode#4837]
### Summary

Found during smoke testing for v57.12.0 release.  Also verified as existing on v57.10.2

After creating new apex classes and adding them to the manifest file I am unable to deploy or retrieve using the `SFDX: Deploy Source in Manifest to Org` command.  It fails with the following error: 

Conflict detection on: 
```15:52:27.465 Starting Conflict Detection

An error was encountered during conflict detection. ExpectedSourceFilesError: /Users/gbockus/Desktop/whyOhWhy/force-app/main/default/classes/Testv57120Impl.cls-meta.xml: Expected source files for type 'ApexClass'
```

Conflict Detection Off: 
```
16:07:46.278 Starting SFDX: Deploy Source to Org

/force-app/main/default/classes/Testv57120Impl.cls-meta.xml: Expected source files for type 'ApexClass'
```

### Steps To Reproduce:

1.  Create a new SF project.
1.  Create a new apex cls (x2) 
2. select the two newly created classes and select the `Generate Manifest File` option
3. Right click the newly created manifest file and select `Deploy Source in Manifest to org`

### Expected result

Should deploy the file successfully

### Actual result

Fails with the error listed above. 

### Workaround
The version of the api in the manifest file is 58.  To get around the issue update to v57. 

**Salesforce Extension Version in VS Code**: 57.12.0 (also verified on 57.10.2)

**OS and version**: Mac

**Comment by CristiCanizales** [comment]
Closing this as it's not reproducible anymore 🙂
