### ISSUE TITLE
push-or-deploy-on-save gives Error "File or folder not found" when project folder include whitespace

### ISSUE THREAD

**Issue by Oren-Perion** [forcedotcom/salesforcedx-vscode#4852]
### Summary

When the projects path include whitespace, saving a file invokes the sfdx: force:source:deploy with --sourcepath argument and an error is shown that "File or folder not found" and the path looks to be cut off where the whitespace is located.

### Steps To Reproduce:

1.  Put the project under a folder with a whitespace in it's name (in my case "G:\My Drive\Workspace\salesforce-ut")
2.  Save a file (in my case an APEX class file)
3. The sfdx deploy command is invoked (in my case sfdx force:source:deploy --sourcepath 'g:\My Drive\Workspace\salesforce-ut\force-app\main\default\classes\AsyncExecution.cls')

### Expected result

The deploy command should work successfully.

### Actual result

An error is thrown:
Error (1): 'g:\My: File or folder not found

### Additional information

When running the same command manually (with the whitespace) - it works successfully.
When doing right click "SFDX: Deploy This Source to Org" - it works successfully.
When moving the project to a folder without whitespace and saving a file - it works successfully.

**Salesforce Extension Version in VS Code**: 57.13.1

**SFDX CLI Version**: 7.200.7

**OS and version**: Windows 11 Enterprise

**Comment by CristiCanizales** [comment]
Hello @Oren-Perion, sorry for the delay! I've been trying to reproduce the error but the deploy is working just fine for me. We released a new version last week, can you update the extensions and check if this is still an issue for you?

**Comment by Oren-Perion** [comment]
Hi
Looks like it is ok now. Thanks!
