### ISSUE TITLE
Folders in org not showing up Salesforce Explorer 

### ISSUE THREAD

**Issue by asohail12** [forcedotcom/salesforcedx-vscode#4856]
I am trying to access the flows folder but nothing comes up in salesforce explorer despite being authenticated using terminal command. 
<img width="1242" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/117377373/d82ff89b-6684-4f81-a029-d1f88056abef">

**Salesforce Extension Version in VS Code**: v0.10.0

**SFDX CLI Version**: sfdx-cli/7.200.7 darwin-x64 node-v18.15.0

**OS and version**: MacOS ventura 13.3.1

**Comment by randi274** [comment]
Hey @asohail12 - do you have the full Salesforce extension pack installed? https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

If so, can you try giving the IDE a full reboot? You should be able to connect to an org and then work with the org browser: https://developer.salesforce.com/tools/vscode/en/user-guide/default-org
