### ISSUE TITLE
Retrieve fails to find salesforce.salesforcedx-vscode-core-57.13.1\messages

### ISSUE THREAD

**Issue by dt-snyder** [forcedotcom/salesforcedx-vscode#4863]
### Summary

When trying to retrieve using right-click + "SFDX: Retrieve Source From Org" option in VS Code or when using the Org Browser to pull source I receive the following error: 

`ENOENT: no such file or directory, scandir 'c:\Users\drewt\.vscode\extensions\salesforce.salesforcedx-vscode-core-57.13.1\messages'`

### Steps To Reproduce:

1.  Create new sfdx project, and connect to a default org (dev sandbox)
1. navigate to Org Browser, click download icon to start retrieve 
or 
1.  Create new sfdx project, and connect to a default org (dev sandbox)
1. Create new apex class and deploy to org using, right-click + "SFDX: Deploy Source to Org" option
1. Right-click deployed apex file, choose "SFDX: Retrieve Source From Org"

### Expected result

The selected source file is retrieved from the default org (dev sandbox).

### Actual result

`ENOENT: no such file or directory, scandir 'c:\Users\drewt\.vscode\extensions\salesforce.salesforcedx-vscode-core-57.13.1\messages'`

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/fd4a1bf0-0627-44aa-b9b6-4a3404d54495)

"versionDetail": {
    "cliVersion": "sfdx-cli/7.194.1",
    "architecture": "win32-x64",
    "nodeVersion": "node-v18.14.0",
    "osVersion": "Windows_NT 10.0.19045",
    "shell": "cmd.exe",
    "rootPath": "C:\\Users\\drewt\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli",
    "pluginVersions": [
      "@oclif/plugin-autocomplete 2.1.6 (core)",
      "@oclif/plugin-commands 2.2.11 (core)",
      "@oclif/plugin-help 5.2.8 (core)",
      "@oclif/plugin-not-found 2.3.22 (core)",
      "@oclif/plugin-plugins 2.4.3 (core)",
      "@oclif/plugin-search 0.0.14 (core)",
      "@oclif/plugin-update 3.1.8 (core)",
      "@oclif/plugin-version 1.3.1 (core)",
      "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
      "@oclif/plugin-which 2.2.17 (core)",
      "apex 2.2.7 (core)",
      "auth 2.7.10 (core)",
      "community 2.2.8 (core)",
      "custom-metadata 2.1.9 (core)",
      "data 2.3.8 (core)",
      "info 2.6.2 (core)",
      "limits 2.3.9 (core)",
      "org 2.6.2 (core)",
      "packaging 1.16.2 (core)",
      "schema 2.3.4 (core)",
      "settings 1.4.2 (core)",
      "signups 1.4.8 (core)",
      "source 2.8.0 (core)",
      "telemetry 2.1.3 (core)",
      "templates 55.4.4 (core)",
      "trust 2.4.5 (core)",
      "user 2.3.5 (core)",
      "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
      "@salesforce/sfdx-scanner 3.9.0 (user)",
      "sfdx-affirm 3.0.0 (link) C:\\Users\\drewt\\hunterDouglasDev\\repos\\sfdx-affirm",
      "sfdx-cli 7.194.1 (core)"
    ]
  },
Salesforce Extension Pack Version: v57.13.1
Vs Code Details: 
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

Edit: Added Salesforce Extension Pack Version + VS Code Deatils

**Comment by randi274** [comment]
Hey @dt-snyder - we're seeing a few reports from different users who are also experiencing this, but I'm not able to reproduce this on Mac or Windows with the latest marketplace release (57.13.1). If you go to Help > Toggle Developer Tools, do you see anything related to this error in there?

**Comment by dt-snyder** [comment]
@randi274 Thanks for the response. 

Using the new project I tested this in and had the error earlier I opened the Dev tools, cleared the console then back in vs code normal window I opened the command pallet and ran `Developer: Reload Window`. The following screenshot is the result of that reload. 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/b0156bc2-89d8-46de-84ac-c597a2327ea7)

I then cleared the console again and tried to use the right-click "SFDX: Retrieve Source From Org" option. Here is the resulting console log:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/6c3e16fb-4655-4269-aca4-868ebd60fd42)


hope this helps!

**Comment by randi274** [comment]
Thanks for the screenshots, that's good to compare! Are you seeing the `Retrieve from Source` command fail in an existing project as well?

**Comment by dt-snyder** [comment]
So that's interesting....
 I opened a new vs code window to an existing project and tried to `retrieve from source` and it worked but only against instances other than the default I was using in the new project. When I switched the default org to the one that is failing in the new project it also failed, switching around to other instances seemed to work as well. Below is the Salesforce CLI output window showing me switching back and forth in the existing project and it working then not working. Below that is the console output from dev tools for those same extension commands. 
 
The `HDQA` instance is a full copy, all the others are dev sandboxes. 
 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/ea387844-0bda-480e-bff9-b906117eaca0)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/c9c3470b-ea1f-4ef7-98f7-74fd9c0c9ae8)

**Comment by dt-snyder** [comment]
Also, I tested those other instances in my new project and they worked as well. It seems that my `drewDev3` sandbox will not allow me to use the `SFDX: Retrieve Source From Org` but all the other orgs I'm authorized to work fine regardless of what project I'm in.

**Comment by gbockus-sf** [comment]
Thanks for the info @dt-snyder. Would you mind trying to retrieve the same file using the CLI for the drewDev3 org ? https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_project_commands_unified.htm#cli_reference_project_retrieve_start_unified

**Comment by dt-snyder** [comment]
@gbockus-sf the `sf` commands do not work, the `sfdx` commands do. 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/4b0ce129-cc48-4b22-9d7d-af9315884d98)

**Comment by randi274** [comment]
Hey @dt-snyder - @gbockus-sf noticed there's an interesting API difference in the CLI messages that you're seeing (57 VS 58). What apiVersion are you using for your project?

**Comment by kishorementa** [comment]
Hey @dt-snyder, I was facing the same issue from yesterday afternoon.
The below solution worked for me: 
- logout from org 
- authorize with the same org
- Restart VS Code
I was able to retrieve the code from the org.

**Comment by randi274** [comment]
@kishorementa our version of "Have you tried turning it off and turning it on again" 😄  I'm hopeful this resolves it for you as well @dt-snyder!

**Comment by stevemarinelli** [comment]
@randi274 Yesterday I started experiencing the same `ENOENT: no such file or directory, scandir 'c:\Users\steve.marinelli\extensions\salesforce.salesforcedx-vscode-core-57.13.1\messages` as @dt-snyder. After attempting the fix that @kishorementa suggested, I am now getting a different error message:

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/34689228/16d65359-1fd1-4a3e-a90b-9aff2ee37310)

This error only occurs when targeting a sandbox environment. Retrieving from my prod environment continues to work properly.

Here is the diagnostic info when the default org is set to my dev environment:

> {
  "versionDetail": {
    "cliVersion": "sfdx-cli/7.200.7",
    "architecture": "win32-x64",
    "nodeVersion": "node-v16.14.0",
    "osVersion": "Windows_NT 10.0.19045",
    "shell": "cmd.exe",
    "rootPath": "C:\\Program Files\\nodejs\\node_modules\\sfdx-cli",
    "pluginVersions": [
      "@oclif/plugin-autocomplete 2.1.9 (core)",
      "@oclif/plugin-commands 2.2.14 (core)",
      "@oclif/plugin-help 5.2.9 (core)",
      "@oclif/plugin-not-found 2.3.23 (core)",
      "@oclif/plugin-plugins 3.0.1 (core)",
      "@oclif/plugin-search 0.0.17 (core)",
      "@oclif/plugin-update 3.1.13 (core)",
      "@oclif/plugin-version 1.3.3 (core)",
      "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
      "@oclif/plugin-which 2.2.19 (core)",
      "apex 2.2.15 (core)",
      "auth 2.7.14 (core)",
      "community 2.2.11 (core)",
      "custom-metadata 2.1.19 (core)",
      "data 2.3.14 (core)",
      "deploy-retrieve 1.8.18 (core)",
      "info 2.6.10 (core)",
      "limits 2.3.13 (core)",
      "org 2.8.1 (core)",
      "packaging 1.16.11 (core)",
      "schema 2.3.10 (core)",
      "settings 1.4.6 (core)",
      "signups 1.4.14 (core)",
      "source 2.10.7 (core)",
      "telemetry 2.2.0 (core)",
      "templates 55.4.13 (core)",
      "trust 2.4.14 (core)",
      "user 2.3.10 (core)",
      "sfdx-cli 7.200.7 (core)"
    ]
  },
  "sfdxEnvVars": [
    [
      "SFDX_UPDATE_INSTRUCTIONS",
      "Use \"npm update --global sfdx-cli\" to update npm-based installations."
    ]
  ],
  "sfEnvVars": [
    [
      "SF_AUTOUPDATE_DISABLE",
      "true"
    ],
    [
      "SF_DISABLE_AUTOUPDATE",
      "true"
    ]
  ],
  "cliConfig": {
    "_base": "@oclif/core@2.8.5",
    "debug": 0,
    "topicSeparator": " ",
    "warned": false,
    "commandPermutations": {
      "validPermutations": {}
    },
    "topicPermutations": {
      "validPermutations": {}
    },
    "_commands": {},
    "_topics": {},
    "root": "C:\\Program Files\\nodejs\\node_modules\\sfdx-cli",
    "name": "sfdx-cli",
    "version": "7.200.7",
    "channel": "stable",
    "valid": true,
    "arch": "x64",
    "platform": "win32",
    "windows": true,
    "bin": "sfdx",
    "dirname": "sfdx",
    "flexibleTaxonomy": true,
    "userAgent": "sfdx-cli/7.200.7 win32-x64 node-v16.14.0",
    "shell": "cmd.exe",
    "home": "C:\\Users\\steve.marinelli",
    "cacheDir": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx",
    "configDir": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx",
    "dataDir": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx",
    "errlog": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx\\error.log",
    "nodeEngine": ">=14.0.0"
  },
  "pluginSpecificData": {
    "@salesforce/plugin-source": [
      {
        "sourceApiVersion": "56.0",
        "targetDevHubApiVersion": "57.0",
        "targetOrgApiVersion": "58.0"
      }
    ]
  },
  "diagnosticResults": [
    {
      "testName": "salesforcedx plugin not installed",
      "status": "pass"
    },
    {
      "testName": "no linked plugins",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches apiVersion",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] default target DevHub max apiVersion matches default target org max apiVersion",
      "status": "warn"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches default target org max apiVersion",
      "status": "warn"
    },
    {
      "testName": "using latest or latest-rc CLI version",
      "status": "pass"
    }
  ],
  "suggestions": [
    "Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.",
    "Check http://status.salesforce.com for general Salesforce availability and performance.",
    "The max apiVersion of the default DevHub org doesn't match the max apiVersion of the default target org. This mismatch means that the default target orgs are running different API versions. Be sure you explicitly set the apiVersion when you deploy or retrieve source, or you will likely run into problems.",
    "The sourceApiVersion in sfdx-project.json doesn't match the max apiVersion of the default target org. As a result, you're not using the latest features available in API version 58.0. The version mismatch isn't a problem, as long as it's the behavior you actually want."
  ],
  "logFilePaths": [],
  "commandExitCode": 0
}

And here is the diagnostic info when the default org is set to production:

> {
  "versionDetail": {
    "cliVersion": "sfdx-cli/7.200.7",
    "architecture": "win32-x64",
    "nodeVersion": "node-v16.14.0",
    "osVersion": "Windows_NT 10.0.19045",
    "shell": "cmd.exe",
    "rootPath": "C:\\Program Files\\nodejs\\node_modules\\sfdx-cli",
    "pluginVersions": [
      "@oclif/plugin-autocomplete 2.1.9 (core)",
      "@oclif/plugin-commands 2.2.14 (core)",
      "@oclif/plugin-help 5.2.9 (core)",
      "@oclif/plugin-not-found 2.3.23 (core)",
      "@oclif/plugin-plugins 3.0.1 (core)",
      "@oclif/plugin-search 0.0.17 (core)",
      "@oclif/plugin-update 3.1.13 (core)",
      "@oclif/plugin-version 1.3.3 (core)",
      "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
      "@oclif/plugin-which 2.2.19 (core)",
      "apex 2.2.15 (core)",
      "auth 2.7.14 (core)",
      "community 2.2.11 (core)",
      "custom-metadata 2.1.19 (core)",
      "data 2.3.14 (core)",
      "deploy-retrieve 1.8.18 (core)",
      "info 2.6.10 (core)",
      "limits 2.3.13 (core)",
      "org 2.8.1 (core)",
      "packaging 1.16.11 (core)",
      "schema 2.3.10 (core)",
      "settings 1.4.6 (core)",
      "signups 1.4.14 (core)",
      "source 2.10.7 (core)",
      "telemetry 2.2.0 (core)",
      "templates 55.4.13 (core)",
      "trust 2.4.14 (core)",
      "user 2.3.10 (core)",
      "sfdx-cli 7.200.7 (core)"
    ]
  },
  "sfdxEnvVars": [
    [
      "SFDX_UPDATE_INSTRUCTIONS",
      "Use \"npm update --global sfdx-cli\" to update npm-based installations."
    ]
  ],
  "sfEnvVars": [
    [
      "SF_AUTOUPDATE_DISABLE",
      "true"
    ],
    [
      "SF_DISABLE_AUTOUPDATE",
      "true"
    ]
  ],
  "cliConfig": {
    "_base": "@oclif/core@2.8.5",
    "debug": 0,
    "topicSeparator": " ",
    "warned": false,
    "commandPermutations": {
      "validPermutations": {}
    },
    "topicPermutations": {
      "validPermutations": {}
    },
    "_commands": {},
    "_topics": {},
    "root": "C:\\Program Files\\nodejs\\node_modules\\sfdx-cli",
    "name": "sfdx-cli",
    "version": "7.200.7",
    "channel": "stable",
    "valid": true,
    "arch": "x64",
    "platform": "win32",
    "windows": true,
    "bin": "sfdx",
    "dirname": "sfdx",
    "flexibleTaxonomy": true,
    "userAgent": "sfdx-cli/7.200.7 win32-x64 node-v16.14.0",
    "shell": "cmd.exe",
    "home": "C:\\Users\\steve.marinelli",
    "cacheDir": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx",
    "configDir": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx",
    "dataDir": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx",
    "errlog": "C:\\Users\\steve.marinelli\\AppData\\Local\\sfdx\\error.log",
    "nodeEngine": ">=14.0.0"
  },
  "pluginSpecificData": {
    "@salesforce/plugin-source": [
      {
        "sourceApiVersion": "56.0",
        "targetDevHubApiVersion": "57.0",
        "targetOrgApiVersion": "57.0"
      }
    ]
  },
  "diagnosticResults": [
    {
      "testName": "salesforcedx plugin not installed",
      "status": "pass"
    },
    {
      "testName": "no linked plugins",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches apiVersion",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] default target DevHub max apiVersion matches default target org max apiVersion",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches default target org max apiVersion",
      "status": "warn"
    },
    {
      "testName": "using latest or latest-rc CLI version",
      "status": "pass"
    }
  ],
  "suggestions": [
    "Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.",
    "Check http://status.salesforce.com for general Salesforce availability and performance.",
    "The sourceApiVersion in sfdx-project.json doesn't match the max apiVersion of the default target org. As a result, you're not using the latest features available in API version 57.0. The version mismatch isn't a problem, as long as it's the behavior you actually want."
  ],
  "logFilePaths": [],
  "commandExitCode": 0
}

**Comment by randi274** [comment]
@stevemarinelli for your issue, can you run the same [retrieve](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_retrieve) command using the CLI? We've seen that issue come up [a few times](https://github.com/forcedotcom/cli/issues?q=is%3Aissue+reading+split+is%3Aclosed) from our shared libraries with the CLI (though typically with push/pull instead of retrieve). If you get the same error, I'd redirect you to their issue repository, otherwise would request that you log another issue for us to look into so it doesn't get lost on this thread 👍

**Comment by dt-snyder** [comment]
@randi274 I'll try to remove and readd the org as you suggest and see if that works. To answer your question about the API version:
in `sfdx-project.json`: `"sourceApiVersion": "57.0"`
No API version set globally for sfdx. 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/15711475/498cf097-f900-4398-a589-1d09d243da80)

**Comment by randi274** [comment]
Excellent, I'm glad that reset did the trick! Since your issue has been resolved, I'll go ahead and close this one now.

**Comment by BenedyktDuch** [comment]
> @randi274 removing the org, reauthorizing it, then restarting or reloading vs code fixed my issue.

For all people who are looking for solution. In my case the step for removing the already authorized org was crucial. Reauthorizing the same org is not enough. You should use sfdx force:auth:logout -u <hub alias> command to firstly remove the org and then you can add it again. After performing those steps I had to reset PC to make it working :)

**Comment by randi274** [comment]
Good clarification @BenedyktDuch! Running the command `SFDX: Log Out from Default Org` should also do the trick.
