### ISSUE TITLE
Missing bundle @salesforce/source-tracking:source for locale en_US

### ISSUE THREAD

**Issue by Npenso** [forcedotcom/salesforcedx-vscode#4867]
Trying to run SFDX: Retrieve this source from org or SFDX: Retrieve manifest from org

When I type the command into the terminal (sfdx force:source:retrieve -x manifest/package.xml) it works. When I try to use the command palette for the same commends I get an error 'Missing bundle @salesforce/source-tracking:source for locale en_US'. 

I can **deploy** manifest or individual components using either the terminal or the command palette commands, but the **retrieve** via command palette doesn't work, only the terminal command.

I tried downgrading to  57.10.2, same issues.

**Comment by randi274** [comment]
Hey @Npenso - can you try logging out from that org, reauthorizing the org, and restarting VS Code? 

Also, what type of machine are you using?

**Comment by Npenso** [comment]
I tried that, got the ENOENT: no such file or directory, scandir 'c:\Users\nrpenso\.vscode\extensions\salesforce.salesforcedx-vscode-core-57.13.1\messages' error that other people are seeing.

I'm on an HP government-furnished laptop.

Also, the command works via command palette for other sandboxes, but not this particular one. Weird.

**Comment by mast0r** [comment]
I was able to solve that by downgrading the Salesforce CLI extension from version 57.14.1 to **57.10.2**

**Comment by gribis** [comment]
Seeing same issue in v57.15.0

**Comment by mandypayne** [comment]
I'm also seeing this issue with both v57.14.1 and v57.15.0. I was getting the "ENOENT: no such file or directory, scandir 'c:\Users\..\extensions\salesforce.salesforcedx-vscode-core-57.13.1\messages'" error, manually created the "messages" directory,  then started getting this error.

**Comment by aaronmattern** [comment]
I'm having the same trouble.

**Comment by matthew-clark-1800accountant** [comment]
Getting this error after trying to fix the other one as @mandypayne outlined. Any updates @randi274? 

As @svittalahhs mentioned, the retrieval still seems to happen despite the error. My sfdx-cli is on v7.204 and my plugins are on v58.2.

**Comment by aaronmattern** [comment]
Downgrading solved it temporarily... but it seems like now I can't deploy anything using API 58 features, which isn't really a long term solution.

**Comment by asomaniq2** [comment]
which is a stable version and how to downgrade everything? which extension in VS code do we have to downgrade
I tried downgrading then many new issues appeared.

**Comment by herison** [comment]
> Downgrading solved it temporarily... but it seems like now I can't deploy anything using API 58 features, which isn't really a long term solution.

Humm, for me, it's working good. 
I'm not sure about I said : did you check if your sandbox is still under API version 58? A version of installed package may be affect ot

**Comment by asomaniq2** [comment]
sfdx team keep on changing the vs code version and upgrade it automatically. They shouldn't unless it is stable.
Instead of being dev productivity tool, it consume the productivity.
