### ISSUE TITLE
Context Menu -> Deploy Source to Org is extremely slow. sfdx force:source:deploy terminal command is fast

### ISSUE THREAD

**Issue by 3brover005** [forcedotcom/salesforcedx-vscode#4869]
### Summary

One of our computers experiences extremely slow deploys when a file is right clicked and SFDX: Deploy Source to Org is selected from the context menu. When invoked, we get the toast at the bottom right reporting "Running SFDX: Deploy Source to Org", however there is nothing registering in the org under Deployment Status.

Furthermore, if we run sfdx force:source:deploy --sourcepath force-app/main/default/lwc/toasts/toasts.js in terminal, this completes in under a second (which is what we would expect from the context menu deploy as well)

Other workspaces seem to work just fine. A different computer seems to resolve this. 

Things we have tried:
- Re-install CLI
- Re-install VS Code
- Delete local files and git clone again
- Update Java environment
- Downgrade Salesforce Extensions to a previous build
- Delete VS Code cache files
- Tried deploying from different Git branches to isolate environment conifguration
### Steps To Reproduce:

1. Go to LWC file 
2. Right click -> SFDX: Deploy this source to org

### Expected result

Should deploy in under 10 seconds

### Actual result

Taks 70+ seconds to deploy

### Additional information

We are failing to localize the issue. This started happening out of the blue, without any project configurations taking place. The other computer that we tested the deploy on is a Windows machine whereas the one experiencing the issues is a Mac (M1 Pro).

We keep on getting the following errors in window output:

UNRESPONSIVE extension host: 'salesforce.salesforcedx-vscode-core' took 88.5167762510335% of 2810.297ms, saved PROFILE here: 'file:///var/folders/4s/pk1ryx654_7dw6xp4t1f06z80000gn/T/exthost-12b469.cpuprofile'

UPDATE: We downgraded the Salesforce CLI Integration extension in VS Code to 57.10.2 (down from 57.14.1) and this seems to have resolved the issue. So, finally we localized the issue to be from that extension (latest release).

**Salesforce Extension Version in VS Code**:

57.14.1 - May 17, 2023

**SFDX CLI Version**:
sfdx-cli/7.200.7 darwin-arm64 node-v18.15.0

**OS and version**:

MacOS Ventura Version 13.1 (22C65)

**Comment by randi274** [comment]
Hey @3brover005 - thanks for the feedback, and I'm glad you were able to narrow it down to the jump between 57.10.2 and 57.14.1 as well! We're currently tracking this issue under #4865, so I'm going to close this item for now. Feel free to add any additional notes or questions over on that issue too.
