### ISSUE TITLE
Getting "Metadata API request failed: Cannot read properties of null (reading 'split') " When Trying to Deploy

### ISSUE THREAD

**Issue by skostojohn** [forcedotcom/salesforcedx-vscode#4871]
### Summary

Started happening this morning. When I go to deploy a file, I get this message in the OUTPUT window of VS Code.

### Steps To Reproduce:

1.  Open an Apex class file
1.  Right click and choose deploy

### Expected result

File should be deployed to the server

### Actual result

Get this error message:  Metadata API request failed: Cannot read properties of null (reading 'split')

### Additional information

**Salesforce Extension Version in VS Code**:
Salesforce Extension Pack v 57.14.1
**SFDX CLI Version**:
sf 1.78.6
sfdx 7.200.7

**OS and version**:  
Linux - PopOS 22

**Comment by randi274** [comment]
Hey @skostojohn - two questions to start! 

- Can you run the same [retrieve](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_retrieve) command using the CLI?
- Can you try logging out from the org, reauthorizing that same org, and restarting VS Code?

**Comment by skostojohn** [comment]
> Hey @skostojohn - two questions to start!
> 
> * Can you run the same [retrieve](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_retrieve) command using the CLI?
> * Can you try logging out from the org, reauthorizing that same org, and restarting VS Code?

Hi @randi274 -
Thanks for your suggestions!

I get the error when I am trying to deploy - so should I try a deploy command in the CLI or retrieve, as you suggested?
I will try re-authorizing the org and see if that helps.

**Comment by skostojohn** [comment]
Before I had a chance to re-authorize the org, I had to switch to another org and deploy some changes, and then when I came back to the original (problem) org, deploy was working again.

Strange!  Will close out this issue as it does not appear to be presenting any longer.

**Comment by takumaCeo** [comment]
I am getting the same error in multiple orgs from multiple workstations

**Comment by dornaldski2** [comment]
I too am getting the same error - this needs to be reopened or at least a fix suggested.

**Comment by takumaCeo** [comment]
I get the same error when trying to retrieve.
CLI version 1.78.6-b9a1d26
VS Code Salesforce Extension Pack 57.14.1

**Comment by takumaCeo** [comment]
I tried logging out, logging back in. I tried uninstalling and reinstalling the CLI and the extensions. Still getting the same errors and my team is reporting the same.

**Comment by randi274** [comment]
Hey all - we've got two issues running on this one, so we'll keep the conversation going on #4873
