### ISSUE TITLE
unable to authorize an org

### ISSUE THREAD

**Issue by zashoaib** [forcedotcom/salesforcedx-vscode#4876]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by randi274** [comment]
Hey @zashoaib it looks like this might have been an auto-generated issue. Can you help us troubleshoot by filling in the rest of the templated information above? Thanks!
