### ISSUE TITLE
Unable to change the default org

### ISSUE THREAD

**Issue by weber-almeida-nobre** [forcedotcom/salesforcedx-vscode#4878]
### Summary

When i change the default org the command return a success message but the used default org isn't updated as showed in the print below:
<img width="838" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/130100160/1bd7d429-6b39-4ebb-aa27-f6e571e4de11">

### Steps To Reproduce:

1.  Authorize 2 orgs
1.  Switch between the orgs and check if the proper org its showed as default

### Expected result

Default org successfully changed and deploy retrieve working on the right org

### Actual result

The default org name isn't updated and if I try to deploy/retrieve it point to the wrong org, if I close and reopen the vscode the right org appears

### Additional information

**Salesforce Extension Version in VS Code**: v57.14.1

**SFDX CLI Version**: v57.14.1

**OS and version**: MacOS 13.3.1 (a) (22E772610a)

**Comment by CristiCanizales** [comment]
Hi @weber-almeida-nobre ! I haven't been able to reproduce this error; it's working as expected for me. We released a new version of the extensions last week (v58.0.1) though, could you then please update and check if you're still having issues?

**Comment by weber-almeida-nobre** [comment]
Hi Cristi, I've updated my extensions and same behavior still happening

**Comment by weber-almeida-nobre** [comment]
<img width="1726" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/130100160/66e46faf-3862-4e78-9d29-c72e0f7f4b6a">
As you can see in the image, change default org show success, the org name in the bar didn't change it and when I do a diff file against org it point to the wrong org

**Comment by CristiCanizales** [comment]
Hi @weber-almeida-nobre, sorry for the delay. Could you please specify the SFDX CLI Version? To get it you need to run `sfdx version` in your terminal

**Comment by weber-almeida-nobre** [comment]
Hi Cristina, that's the response of the command
sfdx-cli/7.205.6 darwin-x64 node-v18.15.0
i was doing some additional tests and realized that the error only happens in one of my folders
another folder with another config and different orgs its working fine maybe some config file have some problem

**Comment by CristiCanizales** [comment]
Maybe, do you want to share those different configs so we can check?

**Comment by weber-almeida-nobre** [comment]
That's the point, idk what's different, one folder came from a git branch (the one that works), the other one I created from scratch through the vs code

**Comment by CristiCanizales** [comment]
hi @smaier-sf, can you create a new issue and provide us with all the requested details? Thanks!
