### ISSUE TITLE
Unable to connect to CLI

### ISSUE THREAD

**Issue by brittany-bettencourt-ukg** [forcedotcom/salesforcedx-vscode#4882]
Hello I was able to connect and create a pull request and as of yesterday morning I am no longer able to. 

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

Connect to CLI 

### Actual result

Not able to connect 

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:
salesforce.salesforcedx-vscode-core

**OS and version**:

**Comment by randi274** [comment]
Hi @brittany-bettencourt-ukg are you having issues with the Salesforce CLI, or with the VS Code Extensions for Salesforce Developers?
