### ISSUE TITLE
VS code doesn't know about Apex classes on the current Org.

### ISSUE THREAD

**Issue by mihailTr-19** [forcedotcom/salesforcedx-vscode#4884]
### Summary

VS code doesn't know about Apex classes on the current Org. I have the core_BFJobBase apex class from an unclocked package. But VS doesn't know about it, so I don't have an autocomplite for it and it's methods are marked as unexistant.
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/53862745/1fbde45f-ae72-457d-afbe-5b58108706f3)

### Expected result

VS Code will know about the classes on the org.
I have an autocomplite for variables, methods from extended class.
I don't have a warning.

### Actual result

VS Code doesn't know abou the classes on the org.
I don't have an autocomplite for variables, methods from extended class.
I have a warning near all methods and variables from the parent class.

**Salesforce Extension Version in VS Code**:
v57.15.0

**SFDX CLI Version**:
sfdx-cli/7.200.7 win32-x64 node-v18.15.0

**OS and version**:
Windows 10 22H2

**Comment by CristiCanizales** [comment]
Hello @mihailTr-19 ! Can you please verify you have the extensions running? (Open the command palette with `Ctrl + Shift + P` and run `Developer: Show Running Extensions`)

**Comment by mihailTr-19** [comment]
Hello @CristiCanizales . Yes of course.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/53862745/e5171c55-7126-4d49-b40b-a5b5cc0a413f)
