### ISSUE TITLE
Remove requirement for sfdx-project.json

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/salesforcedx-vscode#489]
**Is your feature request related to a problem? Please describe.**
Most of the SFDX commands aren’t available without this.

**Describe the solution you'd like**
To be able to (eg) create an Apex class without requiring the project file.

**Describe alternatives you've considered**
I create a very simple one, which makes the need for it seem a bit pointless.

**Additional context**

**Comment by keirbowden** [comment]
I’m rarely working on scratch orgs so typically don’t use a project Jason file.

**Comment by vazexqi** [comment]
Dupe of https://github.com/forcedotcom/salesforcedx-vscode/issues/123.

We will _always_ require a sfdx-project.json. There are important metadata information in there that we rely on. But we will have a new way to at least _generate_ it for you when you connect to an existing non-scratch org. More details to come soon.
