### ISSUE TITLE
SFDX Commands are not showing up.

### ISSUE THREAD

**Issue by incentivate** [forcedotcom/salesforcedx-vscode#4890]
### Summary

SFDX Commands are not showing up when pressing ctrl + shift + p.

I've installed Visual Studio Code, then installed the Salesforce CLI, both from the official sites.

When pressing  ctrl + shift + p and typing SFDX no commands are showing up, so I cannot create a Project.

### System Information

I am using the Visual Studio Code terminal

### Additional information
Im using Windows NT 10

I've unistalled and reinstalled everything. Even formatted windows again to be a brand new copy of it.

Still nothing working.

Strange thing is that when typing sfdx in the terminal it does work. It shows the version installed and updated perfectly. But commands still not showing up. Super weird.
Checked the system variables and they are all OK

**Comment by randi274** [comment]
Hi @incentivate are you seeing any specific errors in the output panel if you select Salesforce CLI? Likewise, do you see any errors if you open the developer tools (Command Palette > Developer: Toggle Developer Tools)? Finally, which version of VS Code are you working with - is it insiders or the stable VS Code?

**Comment by incentivate** [comment]
Hey @randi274 
Thank you so much for answering.
Nothing shows up in the Output panel either.
The visual studio code version was downloaded from here https://code.visualstudio.com/download ... I just clicked in the donwload button and install. Its the same I usually use.

This is the debug from the Command Paletter, toggleing Developer tools:

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/36016427/360a2781-df4e-49f6-993b-39e34f7e443d)

**Comment by randi274** [comment]
Hmmm does it seem like the extensions are running? If you run the command `Show Running Extensions` do you see the Salesforce extensions?

**Comment by incentivate** [comment]
Hi @randi274
The extensions are running fine I believe

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/36016427/0571f304-23cb-4292-ad4f-8b290eca7ebe)


Its a very odd problem.

I also recognizes the sfdx installation in the console, but no commands appear to be used.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/36016427/cf1df280-79cc-4f61-89da-2d3205bc0145)

**Comment by randi274** [comment]
Do you see the Salesforce extensions as well?
<img width="1705" alt="Screenshot 2023-05-26 at 3 38 12 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/9795193/44171be5-557c-4cd6-b635-5d337a278d1a">

If not, I'd double check that they're installed correctly in Extensions tab - either the regular or the Expanded extension pack will work.

**Comment by incentivate** [comment]
@randi274 That fixed it. Thank you SO much !!!!
