### ISSUE TITLE
Can't go to failed test.

### ISSUE THREAD

**Issue by mihailTr-19** [forcedotcom/salesforcedx-vscode#4900]
### Summary
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/53862745/e2a56e6c-e28e-4e0f-866f-d7a1467e3e20)

When I run tests for a class and some of them are failed I want to press on a test name and navigate to it. It works only for the succesed tests, but when I click on a failed nofing is happening.

Also in the code I can see an error only for one test.

### Steps To Reproduce:

1. Run tests for an Apex class.
2. Press on a name of a failed one.

### Expected result

Go to the test.

### Actual result

Nofing is happening.

**Salesforce Extension Version in VS Code**:

v57.15.0

**SFDX CLI Version**:

sfdx-cli/7.202.7 win32-x64 node-v18.15.0

**OS and version**:
Windows 10 22H2

**Comment by jeffb-sfdc** [comment]
@mihailTr-19 , OK, since it is working for you again, I'm going to close this ticket.  If you see this issue again:
1. Please re-open this ticket
2. If possible, try to look into what causes the issue to reproduce, and narrow the steps down
3. report back the steps to reproduce
