### ISSUE TITLE
Issue on problem panel not get clear after successful deployment

### ISSUE THREAD

**Issue by vikaskumar171020** [forcedotcom/salesforcedx-vscode#4904]
Hi i the latest release there is issue i found sometime after deploying code it show error for unsuccessfully code deployment and the error show even after the code deployed successfully which is not clear the problem in the file.

FOR BUGS RELATED TO THE SALEFORCE CLI, please use this repository: https://github.com/forcedotcom/cli

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

problem need to clear after successful deployment 
### Actual result

problem still appear after successful deployment 

**Salesforce Extension Version in VS Code**:
Salesforce CLI Integration version "v58.0.1"

**SFDX CLI Version**:
sfdx-cli/7.203.6 win32-x64 node-v18.15.0

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/67593607/0e5c0ca7-1fea-4afd-b6ac-cf24ccc877e3)

**Comment by YukiOkumura** [comment]
downgrading following extensions from 58.0.1 to 57.15.0 worked for me:

Apex
Apex Replay Debugger
Aura Components
Lightning Web Components
Salesforce CLI Integration
Salesforce Extension Pack

how you can choose a previous version:
https://github.com/forcedotcom/salesforcedx-vscode/issues/3901#issuecomment-1064188043

**Comment by vikaskumar171020** [comment]
yeah already did that but due to auto update feature all extension gets updated which cause this issue come over and over again

**Comment by yuki18886** [comment]
@vikaskumar171020 
You may consider to trun off auto update settings, in case you are in the situation where you can manage a personal settings.

see also: 
[Extension auto-update](https://code.visualstudio.com/docs/editor/extension-marketplace#_extension-autoupdate)
[Update an extension manually](https://code.visualstudio.com/docs/editor/extension-marketplace#_update-an-extension-manually)

**Comment by akalatksy** [comment]
➕  Also affected by this. 
Downgrade of extensions mentioned by @yuki18886 helped. Thanks @yuki18886 ! 👍

**Comment by vikaskumar171020** [comment]
yeah thanks that work for me @yuki18886

**Comment by bobalicious** [comment]
Any update on this? This is a major obstacle for development - it gets in the way constantly - big downgrade in functionality.

**Comment by AndrewStopchenko-SO** [comment]
> downgrading following extensions from 58.0.1 to 57.15.0 worked for me:
> 
> Apex Apex Replay Debugger Aura Components Lightning Web Components Salesforce CLI Integration Salesforce Extension Pack
> 
> how you can choose a previous version: [#3901 (comment)](https://github.com/forcedotcom/salesforcedx-vscode/issues/3901#issuecomment-1064188043)

Please note that it could be enough to downgrade only the _"Salesforce CLI Integration"_ extension to _v57.15.0_. Thanks!

**Comment by vikaskumar171020** [comment]
yes i figured out that as well but it's important to resolve the issue so extension can maintain according to sfdx cli 
thanks for all your support

**Comment by clint-rosetree** [comment]
Also affected by this bug. It's a real time and focus waster to double-check for non-existent problems while coding.

**Comment by willvoyle** [comment]
Workaround steps are below:

1. Open VS Code
2. Extensions Tab
3. Search for 'Salesforce CLI Integration'
4. Click the down arrow next to 'Uninstall'
5. Click 'Install Another Version...'
6. Select '57.15'
7. Reload VS Code

**Comment by PedroPTavaresJr** [comment]
Also got affected by this.
downgrading the Salesforce CLI Integration extension, to 57.15.0 works like a charm.
as of today, 206/26/2023, we are on 58.3.1 - 5 updates later, no fix.

**Comment by ccalvomartinez** [comment]
Also affected by this.
Please, we need this to be resolved as soon as possible.

**Comment by evakwright** [comment]
Also affected. I found it easier for me to ctrl-shift-p reload window than downgrading the CLI.

**Comment by CristiCanizales** [comment]
Hello everyone! We're definitely aware of this and are sorry for the delay. This is next in the top of my todo's list. I'll let you all know once the fix is in.

**Comment by CristiCanizales** [comment]
Hello everyone!
I just wanted to let you know that we already have the fix for this (⬆️) that will likely go out in our next release, next week ~Wednesday. Thank you all for your patience. I'll announce here when it's all done ✅

**Comment by bobalicious** [comment]
Have upgraded to this version and the issue still exists.

I notice on the pull request there's the comment:
"Changes have been made in DeployExecutor and jest tests is a heavy lift for the code change at this point in time. So we will cover the test as a separate [W-13736554](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001VpH55YAF/view)"

I understand the desire to get changes out quickly, but it does feel like the fix would have benefitted from having the unit tests written.  That *may* have avoided the release being made with the fix not working.

**Comment by AndrewStopchenko-SO** [comment]
Hi, I have just upgraded to `v58.6.2` and tried two ways of deploying broken/working Apex code, with results below:
1. When using the _"SFDX: Deploy This Source To Org"_ command, the issue seems to be fixed:
    1.1. attempts to deploy **broken** Apex code clears the Problems panel's items on each re-deployment
    1.2. thus, when successfully deploying **working** Apex code, th eProblems panel gets cleared out, as desired.

2. When using the _"SFDX: Push Source to Default Org"_ command, **the issue persists**:
    2.1. pushing the **broken** Apex code keeps adding new errors to the Problems panel; a new error entry is added _for each unsuccessful source push attempt_;
    2.2. pushing the **working** Apex code does not clear errors added by unsuccessful source push attempts above.
    2.3. trying to run the _"SFDX: De;py This Source To Org"_ command with **working** Apex code, code is being deployed successfully, but the problem items added by the `push source` command (2.1.) are not removed from the Problems panel.

So, it looks like the _"SFDX: Deploy This Source To Org"_ command is fixed, but the _"SFDX: Push Source to Default Org"_ command still has the issue.

**Comment by CristiCanizales** [comment]
Hello @AndrewStopchenko-SO, yes, we just found out about the same issue with push yesterday in the afternoon while doing the testing for the release, and already have a [PR open](https://github.com/forcedotcom/salesforcedx-vscode/pull/4975) for that, but we need to work on the tests first.

**Comment by bobalicious** [comment]
Can this ticket be re-opened then please

**Comment by bobalicious** [comment]
Yes, it is.

**Comment by CristiCanizales** [comment]
Thanks for your reply @bobalicious. What I'd suggest then as a workaround while the fix for that other issue goes out, to avoid having to reload the window every time you have errors that should not be there, is to stick to the 1st way mentioned in the previous comment, like prefer deploy from the beginning, as that flow is working ok.

**Comment by bobalicious** [comment]
Thanks, but I don't need help with a workaround - I have that - lock the version to an earlier one (FYI - using deploy instead of push is not an acceptable work-around because it breaks my workflow too much)

What I need is a way of finding out when I no longer need to use the workaround - previously I had been tracking this bug report.  Can you please re-open this issue or direct me to the one you are using to track your fix.

**Comment by CristiCanizales** [comment]
@bobalicious I'm using this: #4942. It is connected to the PR I have open with the fix, but it needs the tests before going in, which will go along with the tests for this fix.

**Comment by bobalicious** [comment]
Thanks, will track that one

**Comment by vikaskumar171020** [comment]
the issue is resolved in deploy code however it still exist in source push command
