### ISSUE TITLE
SFDX: Authorize an Org field to run

### ISSUE THREAD

**Issue by saikiranmadugula** [forcedotcom/salesforcedx-vscode#4910]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:
sfdx force:auth:web:login --setalias dd --instanceurl https://login.salesforce.com --setdefaultusername
(node:41260) Warning: Deprecated environment variable: SFDX_JSON_TO_STDOUT. Please use SF_JSON_TO_STDOUT instead.
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: The "force auth web login" command has been deprecated. Use "org login web" instead.
Warning: The "--setalias" flag has been deprecated. Use "--alias | -a" instead.
Warning: The "--instanceurl" flag has been deprecated. Use "--instance-url | -r" instead.
Warning: The "--setdefaultusername" flag has been deprecated. Use "--set-default | -s" instead.
Error (1): spawn UNKNOWN
15:20:33.913 sfdx force:auth:web:login --setalias dd --instanceurl https://login.salesforce.com --setdefaultusername
 ended with exit code 1

**Comment by pedroweb3** [comment]
Hello. I've this issue too

For me, When I try to authorize with valid credentials, and after login screen the success oauth login is showed, but  in VSCode appear a same error reported by @saikiranmadugula 

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/20981375/56ce0d28-9f02-46e4-bc3e-00a2dece35f8)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/20981375/5a6d75f5-4952-4bc2-99d2-4a08877f4a52)


sfdx version --verbose --json 
{
  "cliVersion": "sfdx-cli/7.204.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\xxxx\\AppData\\Local\\sfdx\\client\\7.204.6-fbe290c",  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "org 2.9.3 (core)",
    "packaging 1.18.0 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.10 (core)",
    "signups 1.4.20 (core)",
    "source 2.10.12 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.18 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.14 (core)",
    "@salesforce/sfdx-diff 0.0.6 (user)",
    "muenzpraeger-sfdx-plugin 0.2.0 (user)",
    "sfdx-cli 7.204.6 (core)",
    "sfdx-ext 0.1.4 (user)"
  ]
}

**Comment by srinivasrvanam** [comment]
I got this issue as well.
All I did was run sfdx update in VS Code Terminal to update CLI to latest version
Closed VS Code and started it again and it worked fine without any issues.
