### ISSUE TITLE
not able to authorize an org

### ISSUE THREAD

**Issue by brittany-bettencourt-ukg** [forcedotcom/salesforcedx-vscode#4918]
I was able to create a PR just last week now I cannot.
I am not able to authorize and ord. No SFDX command come up

**Comment by brittany-bettencourt-ukg** [comment]
version v58.1.1

**Comment by brittany-bettencourt-ukg** [comment]
<img width="815" alt="cli - sfdx" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/118369044/3e606cec-78bd-4808-aabe-5b5c91a624ae">

**Comment by CristiCanizales** [comment]
Hello @brittany-bettencourt-ukg1!
It seems like you're trying to open a file, not run a command. 
You first need to have a sfdx project open, then open the Command Palette `Cmd/Ctrl + Shift + P` (or go to View > Command Palette) and run "SFDX: Authorize an Org"
or you can also follow the steps shown in the image below:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/1c242c29-acfa-4b68-a1db-efe0add5b47e)
Let me know if that works!

PS: if you only do `Cmd/Ctrl + P`, you need to type ">" to turn that prompt into the Command Palette.

**Comment by jeffb-sfdc** [comment]
Hello @brittany-bettencourt-ukg1, are you still experiencing this issue?  If not we'd like to close this ticket.
