### ISSUE TITLE
Incredibly Slow Startup

### ISSUE THREAD

**Issue by Llnski** [forcedotcom/salesforcedx-vscode#4919]
### Summary

Incredibly long plugin load time, my computer is more than capable of of running the plugin.

### Steps To Reproduce:

1.  Install Plugin
1.  Start Vscode

### Expected result

Reasonable start-up time, Vscode developers [have acknowledged](https://github.com/microsoft/vscode/issues/46846#issuecomment-377229568) that a plugin with _2400 ms_ start-up time is ridiculous, Salesforce takes _more than a minute_ to start-up.

### Actual result

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/58711251/27d551bd-fcfe-442e-8b34-4cb128994f8c)

**Salesforce Extension Version in VS Code**: Most Recent

**SFDX CLI Version**: 1.82.0

**OS and version**: Windows 10, 10.0.19045

**Comment by CristiCanizales** [comment]
Hello @Llnski! Can you specify which version of the extensions you're running?

**Comment by Llnski** [comment]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/58711251/8b22e9fd-8ee6-429e-9925-369cccfa1c34)
v58.2.0 @CristiCanizales

**Comment by anantagarwal2002** [comment]
For me, it always takes more than 4 min to load this extension(latest version) in vscode. I can see in extension log that it tries to load couple of extensions in background every min which started after 2 min.
It would be good to get basic work started so that we can start the activity.

**Comment by ctinghino** [comment]
Can we kindly have an official response to this issue? 
many of us are facing daily performance issues, slow startups and unresponsiveness

**Comment by Llnski** [comment]
The reviews for this extension on the Vscode marketplace are littered with more reports of this issue.

**Comment by Llnski** [comment]
bump

**Comment by laszlo-foldi-attentioncrm** [comment]
I can back this up. This really slows down my development time when trying to jump right on a problem and have to wait minutes for my full environment to load.
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/47455710/2a199f40-da17-4a1a-8a9e-436a7f192136)

**Comment by Llnski** [comment]
Bump

**Comment by laszlo-foldi-attentioncrm** [comment]
This is getting ridiculous... Can anyone from the project team respond to this issue?

**Comment by laszlo-foldi-attentioncrm** [comment]
Bump

**Comment by SFDX-Sam** [comment]
Painfully slow for me too

**Comment by DC-ICT** [comment]
Good 5-10 minutes to load all SFDX extensions for me.

**Comment by laszlo-foldi-attentioncrm** [comment]
Still no update on this issue.

**Comment by tneuburger** [comment]
This affects me as well @lukeis .  Thanks for watching it on my laptop here at Dreamforce '23.

**Comment by SFDX-Sam** [comment]
This is on a 32 core 13th Gen Intel(R) Core(TM) i9-13900K with 32GB of RAM, I can't imagine the average laptop


![Just some more info](https://github.com/forcedotcom/salesforcedx-vscode/assets/137908312/e4025e24-2e71-4371-9a31-3f3e1675adf6)

**Comment by DC-ICT** [comment]
> This is on a 32 core 13th Gen Intel(R) Core(TM) i9-13900K with 32GB of RAM, I can't imagine the average laptop

My average company laptop took 83094ms this morning. That's on the quick end.

**Comment by balderm** [comment]
Having the same issue, extremely slow startup time, and i got an high end 2018 laptop for work.

VSCode version: 1.82
Extension version: 58.14.2

![Screenshot 2023-09-13 125252](https://github.com/forcedotcom/salesforcedx-vscode/assets/6721489/adfc4226-8898-4318-9e91-c9c051298eca)

**Comment by BobSeu** [comment]
Same thing here.

**Comment by ytiq** [comment]
Same thing here. It takes more than 5 minutes to boot up all Salesforce extension until I can't do basically anything, can't even check Git status most of the time and need to use terminal for SFDX and Git.

Can you please improve it?

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/6833632/9a60785c-95da-4764-a103-e46c51b4f6c9)

**Comment by chrisabralse** [comment]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/43811143/f64d1de4-3b55-4a6c-9d71-8b96aee755f7)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/43811143/e782e504-8de7-414b-957f-0dd0e397c306)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/43811143/a2d6fcde-8de4-49b4-9ce7-a8770ec0f7f7)

Still hitting this issue months later. 
Crazy long load times

**Comment by laszlo-foldi-attentioncrm** [comment]
I may bump this issue again.

**Comment by AnanyaJha** [comment]
Hi all! Thank you so much for reporting your issues here, we'll be pulling this into the work for our upcoming iteration. A member of our engineering team will reach out with more updates once we've begun investigating. Appreciate your patience!

**Comment by zxmarcos** [comment]
Upgrading from JDK17 to JDK21 solved this issue for me.

**Comment by DC-ICT** [comment]
No difference for me with JDK21 (also can't activate Apex Language Server on 21).

**Comment by Llnski** [comment]
No difference for me with JDK21 either

**Comment by shetzel** [comment]
Linking with related GH issue: https://github.com/forcedotcom/salesforcedx-vscode/issues/3198

**Comment by melissaklein68** [comment]
When it starts up it's incredibly slow. But it doesn't always start up - I had to close the app to reboot my computer yesterday and haven't yet been able to authorize an org. I've uninstalled and reinstalled the extension twice and it still isn't recognizing it. I can't do my work with it like this.

Running @salesforce/cli/2.13.9 win32-x64 node-v18.15.0 and Salesforce Extension Pack v59.4.0

**Comment by AnanyaJha** [comment]
Hi all, appreciate the patience for the long-running issue you've been experiencing. There will be an initial fix going out in next week's release that should address this problem. We'll post an update once the release has gone out, thanks!

cc @gbockus-sf

**Comment by diyer** [comment]
Hello all, we're excited to let you know the latest version of our extensions **59.5.1** is released! We encourage you to try it out and let us know if you see any improvement with this fix and if possible with some data. Your feedback is valuable to us. Thank you for being part of our journey!!

**Comment by DC-ICT** [comment]
I'm clocking 74000ms on the latest version, so no improvement at all.

**Comment by fabiobarcelona** [comment]
Same for me after the extension update. Startup time is around 25-50k ms using Oracle Java 11 and latest CLI version

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/43356571/2f1a931f-c98d-4182-9e42-a25144309ef4)

**Comment by gbockus-sf** [comment]
@fabiobarcelona @DC-ICT @reignman5 And all :) Thanks for the feedback.  This was step one which should improve the startup time.  Telemetry so far is telling me there's small improvement to avg startup time for the CLI Integration extension, but not everyone has updated to the latest yet so it will be interesting to see what happens to that number as the day goes on.  

This def should have improved the end-to-end time for when an update drops as it reduced the size of the CLI extension by a good amount. 

We also have another change that will hopefully make the next release that should further improve the activation time number (altering the load order of the extensions to allow the base extension to activate first).

**Comment by diyer** [comment]
@fabiobarcelona @DC-ICT @reignman5 Thank you for your feedback! Do you mind comparing the start up time for your core extension on previous version with the latest one and let us know? The fix we have in our latest version impacts only the core extension and as @gbockus-sf said there are further improvements in the pipeline.

**Comment by ytiq** [comment]
I think it improved maybe by 10 sec per plugin since my Sep 22 comment, but still it's slow and results vary between starts
![Screenshot 2023-11-18 120455](https://github.com/forcedotcom/salesforcedx-vscode/assets/6833632/eb5801f2-d08a-4e1d-9009-337d86495b9a)
![Screenshot 2023-11-18 101738](https://github.com/forcedotcom/salesforcedx-vscode/assets/6833632/2fd59aef-859b-4795-a06d-8a69c6b1e889)

**Comment by DC-ICT** [comment]
> @fabiobarcelona @DC-ICT @reignman5 Thank you for your feedback! Do you mind comparing the start up time for your core extension on previous version with the latest one and let us know? The fix we have in our latest version impacts only the core extension and as @gbockus-sf said there are further improvements in the pipeline.

It would vary anywhere from 55k to over 100k ms with each startup on previous.

**Comment by diyer** [comment]
Thank you @ytiq @DC-ICT for providing us with that information. We will continue to look into this.

**Comment by pnoges-launchpad** [comment]
FWIW my powerful desktops load vscode and sf extensions quickly, however my work laptop takes several minutes.   It's a large 
 amount of trouble for me multiple times each day.

**Comment by AnanyaJha** [comment]
Thanks @pnoges-launchpad! We're actively investigating this and will share this info with our eng team. cc @peternhale @gbockus-sf

**Comment by daveseidman-aspca** [comment]
For me, this has been going on for a year now. Doesn't matter if it's work laptop or personal laptop that's a little more powerful. Sometimes, the Salesforce extensions never load. When they do, it looks like this.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/121049250/0e7e35f0-c99c-4824-a145-69ba609153b8)

I upgrade the CLI often. I upgrade the JDK. I uninstall, reinstall. Etc. No difference. There doesn't seem to be acknowledgement in these discussions from devs that this is, indeed, a pervasive, unresolved, ongoing issue. I've accepted it as normal behavior at this point.

**Comment by fabiobarcelona** [comment]
Hi everyone, after installing all latest updates, the load times are considerably faster, especially the second+ time you open VS Code. Here are my Java and SF CLI versions and load times:

![versions](https://github.com/forcedotcom/salesforcedx-vscode/assets/43356571/5067852b-272d-4882-9140-7b6717b5e3c1)



These are the load times the first time I open VS Code, still slow but it improved a lot:

![first_loadtime](https://github.com/forcedotcom/salesforcedx-vscode/assets/43356571/56beb53b-8c21-4084-92c9-2ab10fbb9cf7)



After closing and reopening VS Code, I get the perfect load times:😄

![reload_loadtime](https://github.com/forcedotcom/salesforcedx-vscode/assets/43356571/2af8908d-400a-4577-9555-3686a31b65c3)

**Comment by diyer** [comment]
Thank you @ytiq @fabiobarcelona for your feedback!
@DC-ICT . @daveseidman-aspca  @pnoges-launchpad As we continue to make improvements on our end, we would like to get feedback on this issue. Can you try our latest version and let us know if this has made any improvements in your end please?

**Comment by pnoges-launchpad** [comment]
hello diyer,
It is noticeably faster, and from cold pc bootup loads the salesforce
extension in about 45 seconds. By that i really mean the org browser
appears.
Thank you all very much,

sf —version
@salesforce/cli/2.20.6 win32-x64 node-v20.9.0

**Comment by DC-ICT** [comment]
> Thank you @ytiq @fabiobarcelona for your feedback! @DC-ICT . @daveseidman-aspca @pnoges-launchpad As we continue to make improvements on our end, we would like to get feedback on this issue. Can you try our latest version and let us know if this has made any improvements in your end please?

Hi diyer,

It's a mixed bag but definitely an improvement.
Can be as high as 45s on first startup after boot, but then anywhere from 5s to up to 45s again.
If we can get it consistently to that 5s it would be a huge win. Thanks for your support.

**Comment by paullinder-ctl** [comment]
Bump. 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/73713997/6a7b3724-7763-46c7-9bef-de3a7df1775f)

**Comment by gbickel-nuage** [comment]
Hey diyer - 

Are there any plans to release any new builds soon?  Like most here I've seen improvements, but still takes about 2-3 minutes to fully load all of the extensions.

Thanks!

**Comment by paullinder-ctl** [comment]
@diyer startup is still requires > 30 seconds of latency

**Comment by diyer** [comment]
Hi all, we very much have this on our radar. We do not have any fix related to perf in our next release unfortunately, however we have the team is actively working on it. We will make an announcement once we release these changes. Please bear with us and thank you for your patience!

**Comment by peternhale** [comment]
bump

**Comment by peternhale** [comment]
bump

**Comment by gbickel-nuage** [comment]
@diyer - any updates - it's been about a month since the last update here.  Should the community be the ones having to keep this issue alive?  Seems like this would have more focus from the Salesforce development team.

**Comment by paullinder-ctl** [comment]
I've always known startup was slower than it should be. Today, I finally took time to measure this using a stopwatch. I measured how long to do something which is fundamental to programming: retrieving the org's code before making any modifications.

From startup to the moment when the retrieval process actually began, here is the number:

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/73713997/eb6e4812-b856-4212-916d-9eabeaa346bb)

Shocking right? Over 7 minutes. I've included my (powerful) pc specs above to prove pc performance is not an issue.

**Comment by diyer** [comment]
@gbickel-nuage We are very much working on improving the load times. Next update will be sometime around March if things go as planned. Please bear with us,  this issue is important to us and we are actively working on it.

**Comment by diyer** [comment]
@paullinder-ctl the issue you are seeing is with runtime performance. Can you please create a new issue with some more data like your org shape, OS, version of cli and extension?
We are aware of slow deploy/retrieve, but we need help from the community to be able to repro it steadily.

**Comment by plinderman** [comment]
@diyer my previous comment was describing the latency from starting up the extension until it is ready to be used to retrieve. I was not measuring how long retrieval takes.

**Comment by paullinder-ctl** [comment]
@diyer my previous comment was describing the latency from starting up the extension until it is ready to be used to retrieve. I was not measuring how long retrieval takes.

**Comment by paullinder-ctl** [comment]
Bump.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Coordona-Admin** [comment]
Scootch...

**Comment by diyer** [comment]
@gbickel-nuage @paullinder-ctl @laszlo-foldi-attentioncrm @Llnski @anantagarwal2002 @ctinghino @SFDX-Sam @DC-ICT @reignman5 @tneuburger @balderm @BobSeu @ytiq @chrisabralse @msriver @jongpie @melissaklein68 @fabiobarcelona @ytiq @pnoges-launchpad @daveseidman-aspca May I ask you all to provide performance data on this [open issue ](https://github.com/forcedotcom/salesforcedx-vscode/issues/5488)
It has been a challenge to get data for startup times as there is no easy way to get these numbers. Instructions are on that issue.

**Comment by paullinder-ctl** [comment]
All, this is a great chance for us to work toward what we've been asking for. I encourage us all to take the few minutes required to contribute.

**Comment by diyer** [comment]
We are closing this issue and will be tracking the startup load time performance issue as part of [this](https://github.com/forcedotcom/salesforcedx-vscode/issues/5488) . 
cc: @AnanyaJha
