### ISSUE TITLE
Unable to retrieve code from Salesforce using CLI in VS code

### ISSUE THREAD

**Issue by sailysuvin** [forcedotcom/salesforcedx-vscode#4935]
Type: <b>Bug</b>

1.Right click on package.xml generated 
2.Click Retrive source from org
The error shows : Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 61756c742f6f626a6563745472616e736c617469 but saw 5c82e193b312ea64e65b6fe5d6783cf32f9e8277

PLease help.

Extension version: 58.2.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (4.41GB free)|
|Process Argv|--crash-reporter-id 35f59394-dfa5-4b85-8e2e-e9835b51bc87|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000
pythonidxptcf:30772540
pythondjangotscf:30772537

```

</details>

**Comment by jonny-harte** [comment]
Any progress on this? I'm getting the same error when trying to deploy to a sandbox. 

I've tried deleting tracking, reauthorising the sandbox and git reset.

> 11:49:16.743 Starting SFDX: Deploy Source to Org
> 
> An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709
> 11:51:19.382 Starting SFDX: Deploy Source to Org

**Comment by RitamAgrawal** [comment]
I am not able to repro the issue. Steps which I have followed are:-
1. Select `AccountController.cls` and `ApexTypesController.cls` from force-app/main/classes folder Ran `SFDX: Generate Manifest`
2. Created `meni.xml`
3. Right click on `meni.xml` & Ran `SFDX: Retrieve Source in Manifest from Org`
4. It retrieves the source successfully.

@sailysuvin & @jonny-harte Is there anything else you are doing differently?

**Comment by tibeal** [comment]
@RitamAgrawal 
If you cancel (cmd+c / ctrl+c) the deployment in the step "updating tracking information" after a push to the org the same issue happens.

For the push issue, a possible workaround is to delete the org info in <project folder>/.sf/orgs/<orgId folder>

**Comment by rileySFDEV** [comment]
Almost every issue i get that mentions isomorphic can be fixed by deleting the .sf and .sfdx files from the project and then re-authorising the org

**Comment by jakekarl** [comment]
Just came across this thread with the same issue and @rileySFDEV's suggestion fixed it for me. Thanks!

**Comment by nileshndethe** [comment]
I also faced the similar issues (reported it here as well - https://github.com/isomorphic-git/isomorphic-git/issues/1828) however the  workaround provided by @rileySFDEV  worked like miracle for me too.. Thanks!
