### ISSUE TITLE
Retrieve Source from Org failed to run

### ISSUE THREAD

**Issue by bmathew83** [forcedotcom/salesforcedx-vscode#4936]
Type: <b>Bug</b>

1. Created new sfdx project, and connected to an org by Authorizing Org (SFDX: Authorize An Org)

2. Right-Clicked on package.xml and chose "SFDX: Retrieve Source From Org" 

3. Error : Retrieve Source from Org failed to run

Details of error = exports.getOrgApiVersion is not a function

Extension version: 58.3.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (16.85GB free)|
|Process Argv|--crash-reporter-id 6bf9a6a2-27ec-4c2e-ba65-9457b5e49a7e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythonidxptcf:30772540
pythondjangotscf:30772537

```
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/88213348/7a4c6966-85ac-42eb-956b-530089f721e2)

</details>

**Comment by bconners1005** [comment]
It's happening on anything directly going to the org.

It impacts:

- Diff
- Deploy
- Retrieve
- etc.

**Comment by bmathew83** [comment]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/88213348/a74561b0-a587-43bd-b036-2a05c7437d21)

@bconners1005 -Thanks for your quick reply. This is how I've been retrieving all this while. Nothing has changed from my end.

**Comment by bconners1005** [comment]
@bmathew83 Me either.  It was the update something is wrong.  If you downgrade the Salesforce Extension to v57.14.1 (making sure the Salesforce CLI Integration is also the same version) it worked again after reloading.

**Comment by bmathew83** [comment]
@bconners1005 - You just made my day!!! It worked!!! Thank u so so much. God Bless you !!!

**Comment by bconners1005** [comment]
> @bconners1005 - You just made my day!!! It worked!!! Thank u so so much. God Bless you !!!

lol No worries.  Hopefully they'll be able to get a quick patch so I can get back up to the most recent, but it at least gets us to working status again.

**Comment by bmathew83** [comment]
Closing ticket. Hopefully this helps someone.
