### ISSUE TITLE
Error: exports.getOrgApiVersion is not a function

### ISSUE THREAD

**Issue by Deepak-K-Anand** [forcedotcom/salesforcedx-vscode#4938]
### Summary

Unable to deploy code after the recent extension update (58.3.0 - June 21, 2023). Error: `exports.getOrgApiVersion is not a function`

### Steps To Reproduce:

1.  Open any Metadata (Apex, VF Page, LWC etc.)
2.  Right-click and run **SFDX: Deploy This Source to Org**

### Expected result

The metadata should be deployed to the Salesforce org.

### Actual result

Presented with an error in the console that says: `exports.getOrgApiVersion is not a function`

### Additional information

**Observation**: This most likely started appearing after the recent release of 58.3.0 - https://github.com/forcedotcom/salesforcedx-vscode/pull/4917

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/3683725/c3caac8c-c02e-48b5-9964-905bcf3fe427)

**Salesforce Extension Version in VS Code**:
`v58.3.0`

**SFDX CLI Version**:
```
{
  "cliVersion": "@salesforce/cli/1.77.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/deepakkanand/.local/share/sfdx/client/7.199.7-cc56357/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.7 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "@salesforce/cli 1.77.1 (core)",
    "apex 2.2.14 (core)",
    "auth 2.7.14 (core)",
    "data 2.3.12 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "info 2.6.8 (core)",
    "limits 2.3.13 (core)",
    "login 1.2.7 (core)",
    "org 2.7.2 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.5 (core)",
    "sobject 0.1.18 (core)",
    "source 2.10.5 (core)",
    "telemetry 2.1.6 (core)",
    "templates 55.4.11 (core)",
    "trust 2.4.12 (core)",
    "user 2.3.9 (core)"
  ]
}
```
**OS and version**:
```
Chip: Apple M1 Pro
macOS: 13.4 (22F66)
```

**Comment by Deepak-K-Anand** [comment]
Downgraded the version to `v58.1.1` on the following:

1. Salesforce CLI Integration
2. Salesforce Extension Pack
3. Salesforce Extension Pack (Expanded)

**Observation**: The Extension started working again and I was able to deploy the metadata. So this certainly validates that it was the recent release that has caused this issue.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/3683725/62ba5edc-3f12-4893-8a3e-ac5599c0da17)

**Comment by lkaneTAG** [comment]
I'm having this issue as well.  Had to downgrade the Salesforce Extension Pack and the Salesforce CLI Integrations to v58.2.0 to get my retrieves and deploys to work again

**Comment by lexcraw4d** [comment]
Downgraded, same issue  -- it will via command cli e.g. ```sfdx force:source:deploy -p pathHere```

**Comment by AllanOricil** [comment]
@gbockus-sf @klewis-sfdc  line 57 has an exports that isn't needed
https://github.com/forcedotcom/salesforcedx-vscode/blob/b317be6f496bda8c6a89982dc1085e1a90201056/packages/salesforcedx-vscode-core/src/services/sdr/componentSetUtils.ts#L57

**Comment by jeffb-sfdc** [comment]
@Deepak-K-Anand thanks for reporting this!  We looked into the issue and we will be publishing a patch release in a few hours.

**Comment by jeffb-sfdc** [comment]
@Deepak-K-Anand thanks agin for reporting this issue.  We've built and published a hotfix which resolved and fixes the issue.  I'm going to close this ticket.  If you encounter any other issues, please let us know.
