### ISSUE TITLE
Unnecessary exports keyword

### ISSUE THREAD

**Issue by kevinseguin** [forcedotcom/salesforcedx-vscode#4939]
Re: #4917 issues coming in, I don't think exports. is required here  

https://github.com/forcedotcom/salesforcedx-vscode/blob/b317be6f496bda8c6a89982dc1085e1a90201056/packages/salesforcedx-vscode-core/src/services/sdr/componentSetUtils.ts#LL57C60-L57C60

**Comment by CristiCanizales** [comment]
Hi @kevinseguin! Thanks for letting us know. We'll update about this on #4938
