### ISSUE TITLE
Push or deploy on save not working as expected

### ISSUE THREAD

**Issue by rohledermarc** [forcedotcom/salesforcedx-vscode#4942]
### Summary

The salesforcedx-vscode extension setting push-or-deploy-on-save is enabled, but not working as expected. Since a few days or weeks (hard to tell) on a save the source is pushed once, but on all next saves the push of the source is not triggered again. It is still possible to push it manually through the command pallete. 

### Steps To Reproduce:
 
1. Open a folder with a salesforce project
2. Enable the push-or-deploy-on-save setting
3. Go to a class and click on save (will trigger the push)
4. Click again on save (will not trigger the push) 

(Optional)
5. Close the window and reopen it
6. Go to a class and click on save (will trigger the push)
7. Click again on save (will not trigger the push)

### Expected result

Each save should trigger the push or deploy of the source to the default org. 

### Actual result

Only the first save (in a fresh opened window) triggers the push, all the next saves are not triggering the push anymore.

### Additional information

**Salesforce Extension Version in VS Code**: v58.3.1

**SFDX CLI Version**: 7.205.6

**OS and version**: macOS Ventura 13.4.1

**Comment by gulshan006** [comment]
I am facing the same issue.

**Comment by Najimalden** [comment]
the same here.

**Comment by brandbarr** [comment]
Count me in.

**Comment by tehnrd** [comment]
I thought I was going crazy, and this was something I did. I completely uninstalled all sf/sfdx cli stuff, same for VSCode Extensions, re-installed everything and still not working. 

It will work once the first time I open VSCode but then not after. I am seeing this warning after the first success. It think it is related.
<img width="524" alt="Screenshot 2023-06-30 at 11 37 58 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/1007085/bdff3e30-9e31-4ad5-8947-685b8e606fb9">

`@salesforce/cli/1.84.0 darwin-arm64 node-v18.15.0`
`sfdx-cli/7.206.6 darwin-arm64 node-v18.15.0`
`VSCode Extention Pack v58.4.1`

**Comment by tehnrd** [comment]
Rolling back to VSCode Extension v58.3.1 fixed this for me.

<img width="707" alt="Screenshot 2023-06-30 at 11 44 53 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/1007085/c3411b63-e9a6-4a51-b1bf-36d23b9782f8">

**Comment by RitamAgrawal** [comment]
Hello Everyone! I tried to repro the issue but it's working fine for me. We have two settings around `Push & Deploy on Save`
I am running with these two settings on. Please cross check and confirm your behavior with same settings.
![Untitled 19](https://github.com/forcedotcom/salesforcedx-vscode/assets/72183558/d43ebf6b-f1e3-4047-a30f-39dc85391866)

**Comment by brandbarr** [comment]
If you turn off `Prefer-Deploy-on-Save` while having `Push-or-deploy-on-save` enabled, you should be able to replicate it. That's I have replicated it locally. If you try to enable `Prefer-Deploy-on-Save` once the bahavior has started, it will require a restart of VS Code to get it to work correctly again.

**Comment by rohledermarc** [comment]
As @brandbarr described I have `Prefer-Deploy-on-Save` turned off and I am still facing the issue.

**Comment by CristiCanizales** [comment]
Hello everyone! I'm looking at this now and I think I've found a fix that could go in in next week's release 🙂 I'll keep updating here if anything comes up. Thanks for your patience 🙌

**Comment by CristiCanizales** [comment]
Hello @bobalicious! I'll do the release testing later today and if everything is ok it would be released tonight. I'll announce here. Thanks for your patience.

**Comment by CristiCanizales** [comment]
Hello everyone! 🚀  v58.7.1 of the Salesforce Extensions for VS Code has been published. Please see the release notes [here](https://github.com/forcedotcom/salesforcedx-vscode/releases) for a list of changes in this week’s release. In addition to the Visual Studio Marketplace, Salesforce extensions are also available on [Open VSX Registry](https://open-vsx.org/extension/salesforce/salesforcedx-vscode). Featured in this week’s release:
- Now you can run the Apex iInteractive Debugger without getting blocked by CLI warnings 🥳 
**- Problems tab will reflect your local dev environment issues correctly 🎉 
- Push-on-save works every time you save irrespective of the changes 😃**

**Comment by rohledermarc** [comment]
Thank you :) it is working again for me!

**Comment by mplaaguilera** [comment]
I dont know whether this issue was actually fixed at some point, but I can confirm that as of May 2025 and version 63.14.1 of the Salesforce Extension Pack (May 2025) the output panel keeps popping up after every deploy or retrieve operation.

The value of the `salesforcedx-vscode-core.push-or-deploy-on-save.showOutputPanel` setting seems to be irrelevant.
