### ISSUE TITLE
Org Brower Fails to "Retrieve Source from Org"

### ISSUE THREAD

**Issue by dturkelSalesforce** [forcedotcom/salesforcedx-vscode#4951]
### Summary
Within the same SFDX Project:

- When attempting to use Org Browser component to "Retrieve Source from Org" for any specific component or overarching type (e.g. "Custom Objects/Account", "Custom Objects/Asset", "Apex Test Suites", consistently receiving `ENOENT: no such file or directory, stat 'c:\.forceignore'` error message.  No metadata is downloaded.  Also note: The Project does not live at C:\; it is in a nested directory under my Documents.  The reference to files in the drive's root folder is "weird".

- The same requests for metadata can be successfully executed from the "normal" VSCode Explorer view, right-clicking the metadata component and choosing the "SFDX: Retrieve Source from Org" option.

### Steps To Reproduce:

See Summary above.  Further, if manually copying/creating the complained about missing file (in this case "`c:\.forceignore`"), it complains about another file -- in my particular case "`c:\.git`".  It is as if it's reading known files using a relative path, then trying to use an absolute path w/o the correct prefix value.  I realize this is stretching.  It's strange that these files being complained about have anything to do with retrieving and placing the metadata.

### Expected result

Component metadata should be retrieved and be available in the SFDX project.

### Actual result

 `ENOENT: no such file or directory, stat 'c:\.forceignore'` error message.

### Additional information

None.

**Salesforce Extension Version in VS Code**:
Salesforce CLI Integration: 58.3.1

**SFDX CLI Version**: 
sfdx-cli/7.205.6 win32-x64 node-v18.15.0

**OS and version**:
Windows 10 Enterprise, Version 22H2, OS Build 19045.3086

**Comment by av4213** [comment]
I am facing the same issue.. but only for new components. What is the solution for this.. And this error is happening for few branches only not all the branches.
