### ISSUE TITLE
Takes long time to activate (> 5 mins)

### ISSUE THREAD

**Issue by rayguy81** [forcedotcom/salesforcedx-vscode#4955]
Type: <b>Bug</b>

Salesforce CLI Integration says "Activitating...." for well over 5 mins, closer to 10 mins.   Happens everytime starting up VS Code.

Extension version: 58.3.1
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.04GB free)|
|Process Argv|C:\\Users\\ray\\OneDrive\\Documents\\Clients\\Verex\\Dev\\verex-dev\\VerexSalesforce --crash-reporter-id 72dd42b8-2052-406f-a14f-7124aec704fe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
gsof1:30774496
e440d664:30776459
pythonidxptcf:30772540
pythondjangots:30772535
pythonnoceb:30776495

```

</details>

**Comment by RitamAgrawal** [comment]
@rayguy81 Are you experiencing the same issue with our latest version 58.4.1 also?

**Comment by rayguy81** [comment]
@RitamAgrawal issue occurs with 58.6.2 and also on a different machine.    when i started up VS Code just now I end up with the attached activation times (31227ms)

![Screenshot 2023-07-14 095011](https://github.com/forcedotcom/salesforcedx-vscode/assets/36929426/d386ac09-80d9-4e9a-8063-0a7d34cffd58)

**Comment by CristiCanizales** [comment]
Hi @rayguy81! I'll close this issue as a duplicated of #4919 and we'll continue tracking the problem there.
