### ISSUE TITLE
Clarify format/contents of .soql files

### ISSUE THREAD

**Issue by theperiscope** [forcedotcom/salesforcedx-vscode#4958]
### Summary

I get problem warnings when using .soql files to store multiple queries in them. The documentation provided at https://developer.salesforce.com/tools/vscode/en/soql/writing is conflicting:

> the .soql file is to provide a way to build and test a SOQL query

The "a SOQL query" phrase implies one query.

> Execute SOQL Text

The screenshot in the section reads _Use .soql files to store SOQL queries_ -- this implies multiple queries per file.

### Steps To Reproduce:

1.  Create .soql code in VS Code Salesforce project with two queries

### Expected result

Consistency -- whether single or multiple queries are allowed (I'd prefer multiple queries for .soql files)

### Actual result

```
mismatched input 'SELECT' expecting {<EOF>, 'and', 'or', 'with', 'offset', 'for', 'limit', 'group', 'order', 'update', 'bind'}
```

As of 2023-07-03, multiple queries generates a problem when using VS Code and documentation is unclear as to what is correct.

**Comment by CristiCanizales** [comment]
Hi @theperiscope! Thank you for reaching out 🙂 

So it feels like we're talking about 2 things here, which actually belong to two different sections:
[1. SOQL Files](https://developer.salesforce.com/tools/vscode/en/soql/writing#soql-files)
[2. Execute SOQL Text](https://developer.salesforce.com/tools/vscode/en/soql/writing#execute-soql-text)

In one hand, you do can **store** multiple queries in only one .soql file, that's perfectly fine, but to run them you need to select the query (as the screenshot mentions) and run the command `SFDX: Execute SOQL Query with Currently Selected Text`.  In the other hand, the error you mention is related to the [SOQL Builder](https://developer.salesforce.com/tools/vscode/en/soql/soql-builder/#build-a-query), as it supports one query at the time. e.g: ⬇️ 
<img width="655" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/aeff7f48-7a70-42f7-aca7-119ba6635f5e">

Let me know if that helps.
Have a good day! 🌞
