### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Hani2808** [forcedotcom/salesforcedx-vscode#4977]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `58.6.2`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by CristiCanizales** [comment]
Hello @Hani2808! Could you please give us some details about the issue you're experiencing? Thanks 🙂
