### ISSUE TITLE
Retrieving or Deploying shows 'Could not find CODE_NUMBER'

### ISSUE THREAD

**Issue by sergiopedrazaj** [forcedotcom/salesforcedx-vscode#4979]
### Summary

Currently trying to retrieve or deploy anything using the context menu (secondary click on any component), but getting an error message saying

`Could not find 0934dea23bda7ad712c900c8c9ca0eb49850160f.`

### Steps To Reproduce:

1. Right click on any apex class and select SFDX: Retrieve Source from Org.

### Expected result

The class should be retrieved, but it is not. 

### Actual result

The output console reads after a couple of seconds: `Could not find 0934dea23bda7ad712c900c8c9ca0eb49850160f.`

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/67609027/f3341722-db44-49e1-a891-1a341766e794)

**Salesforce Extension Version in VS Code**: 58.6.2.

**SFDX CLI Version**: 2.0.2 Win32-x64 node-v18.15.0

**OS and version**: Windows 10 Enterprise, Version 21H2

**Comment by AnanyaJha** [comment]
Hi @sergiopedrazaj thanks for reporting this! Are you seeing this every time you attempt to deploy or retrieve?

**Comment by sergiopedrazaj** [comment]
Hi, @AnanyaJha, yes, every single time. If I click something else like "SFDX: Diff file against org", the system compares both properly. The problem is with deploy and retrieve. I have already uninstalled and reinstalled everything, and authorized the org again, but still showing the same message.

**Comment by CristiCanizales** [comment]
Hi @sergiopedrazaj. Did you try updating your cli too? I have 7.208.10 and it's working fine for me

**Comment by sergiopedrazaj** [comment]
Hi, @CristiCanizales. Thanks for your suggestion. I have updated the CLI. 

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/67609027/eeea3357-9f98-4472-9ef5-6f77f3ff87c5)

Reauthorized the org successfully, but now getting the error "This command can only be used on orgs that have source tracking enabled, such as sandboxes and scratch orgs." The org is a partial sandbox, so this error does not seem to have sense.

**Comment by sergiopedrazaj** [comment]
Hi, @CristiCanizales, thanks for taking a look at this. Yes, I have always had the sfdx cli installed (right from the link you sent me). I can execute anonymous code and SOQL queries through Vs Code. I can even run apex tests. What I cannot do is retrieve or deploy.

**Comment by CristiCanizales** [comment]
Hi @sergiopedrazaj. We released a new version of the extensions yesterday night. Could you please update en check if the problem persists? And also try through the command palette

**Comment by RitamAgrawal** [comment]
@sergiopedrazaj Will you please run `Show running extension` from CP and post a screenshot here. I wanna check if you have Salesforce CLI Integration up and running.
