### ISSUE TITLE
Yes I am experiencing the same issue

### ISSUE THREAD

**Issue by prash34** [forcedotcom/salesforcedx-vscode#4984]
Yes I am experiencing the same issue

_Originally posted by @prash34 in https://github.com/forcedotcom/salesforcedx-vscode/issues/3745#issuecomment-1637976684_

**Comment by CristiCanizales** [comment]
@prash34 hello! Could you please provide us with (more) details about the error you're facing? (Salesforce Extension Version in VS Code, SFDX CLI Version, OS and version, steps to reproduce, actual and expected behavior)
