### ISSUE TITLE
SFDX Retrieve Problem - Only absolute URLs are supported

### ISSUE THREAD

**Issue by willianmatheus98** [forcedotcom/salesforcedx-vscode#4989]
### Summary

_Every retrieve/deploy/authentication is failing by the extension_.

### Steps To Reproduce:

1.  Goes to an Apex class
1.  Right-click, "SFDX: Retrieve This Source from Org"

### Expected result

_Retrieve the updated metadata file_.

### Actual result

08:47:39.155 Starting SFDX: Retrieve Source from Org

Only absolute URLs are supported.

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/17804531/92333738-5e05-4ccf-8bca-b70c4c9d80a2)

**Salesforce Extension Version in VS Code**:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/17804531/c83714cc-8722-4671-940d-763be2e485be)
58.7.1

**SFDX CLI Version**:
@salesforce/cli/2.0.2 win32-x64 node-v18.15.0

**OS and version**:
Windows 11 Enterprise

**Comment by CristiCanizales** [comment]
Hello @willianmatheus98! Can you try authorizing your org again, reload VS code, verify it says `Connected` under "Connected Status" when running `sfdx org list` in your terminal and then try again?

**Comment by willianmatheus98** [comment]
> Hello @willianmatheus98! Can you try authorizing your org again, reload VS code, verify it says `Connected` under "Connected Status" when running `sfdx org list` in your terminal and then try again?

Hi @CristiCanizales , yes, I re-authenticated and it says connected, but the problem persists
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/17804531/da0c4c71-84a0-4efd-9cb2-437438a816f9)

**Comment by willianmatheus98** [comment]
I'm still having the problem, as a workaround I downgraded the version of my SFDX extensions to version 57.10.2.
