### ISSUE TITLE
Keep getting errors when trying to deploy anything to my sandboxes

### ISSUE THREAD

**Issue by bbrissette96** [forcedotcom/salesforcedx-vscode#5000]
### Summary

I keep recieving the following errors when trying to deploy anything from the whole project to single files.

09:26:37.895 Starting SFDX: Deploy Source to Org
Metadata API request failed: Cannot read properties of null (reading 'split')

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/21249109/395e8da4-3c75-455f-a633-8d4e9f2c9ada)

i have installed and reinstalled vs code, sfdx cli, and all the extensions 3 times and im still getting the same errors. 
**Salesforce Extension Version in VS Code**
{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.17.0",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\DJ33859\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.31 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.5 (core)",
    "trust 2.4.32 (core)",
    "user 2.3.24 (core)"
  ]
}

**Comment by CristiCanizales** [comment]
Hi @bbrissette96! Can you specify which version of the extensions and sfdx you have?

**Comment by bbrissette96** [comment]
cli is Salesforce 2.1.7, i recently switched over from sfdx
extension pack is 58.7.1, ive tried switching to older versions of the extensions already with no luck

**Comment by CristiCanizales** [comment]
Hi @bbrissette96! Sorry for the delay. Could you try [this](https://github.com/forcedotcom/salesforcedx-vscode/issues/4873#issuecomment-1565042473)? And make sure you're up to date in both extensions and CLI, as well as reauthorizing your org
