### ISSUE TITLE
VSCode extension "SFDX: Authorize an Org" fails in a container

### ISSUE THREAD

**Issue by eburtness** [forcedotcom/salesforcedx-vscode#5003]
### Summary
[Dockerfiles](https://github.com/salesforcecli/cli/tree/main/dockerfiles) now include `SF_CONTAINER_MODE` instead of `SFDX_CONTAINER_MODE`, but VSCode extension seems to still be checking `SFDX_CONTAINER_MODE`. In VSCode, "SFDX: Authorize an Org" tries to use force:auth:web:login, which doesn't work in a container.

Not sure if this is considered a CLI issue or an extension issue, but the Dockerfiles are in the CLI repo and it's an easy fix.

**Suggested fix:** Add `ENV SFDX_CONTAINER_MODE true` to the Dockerfiles.

### Steps To Reproduce
- Open a Codespace from https://github.com/eburtness/container-mode-demo
- From command palette, run **SFDX: Authorize an Org**
- Look at Output pane for Salesforce CLI and note that the command run is `sfdx force:auth:web:login`

### Expected result
- Extension should run `sfdx force:auth:device:login` (or current equivalent, but that one still works)
- Browser shows success message, command succeeds, and org shows as Connected in `sf org list`

### Actual result
- Browser shows green check that login succeeded, but then redirects to a url with no response
- VS Code shows "Running SFDX: Authorize an Org" for a long time and never receives the authorization

### System Information
Using bash in a GitHub Codespace based on the [CLI docker image](https://hub.docker.com/r/salesforce/cli)

```json
{
  "cliVersion": "@salesforce/cli/2.2.7",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Linux 5.15.0-1042-azure",
  "shell": "bash",
  "rootPath": "/usr/local/lib/nodejs/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.3 (core)",
    "@oclif/plugin-commands 2.2.20 (core)",
    "@oclif/plugin-help 5.2.14 (core)",
    "@oclif/plugin-not-found 2.3.34 (core)",
    "@oclif/plugin-plugins 3.1.8 (core)",
    "@oclif/plugin-search 0.0.21 (core)",
    "@oclif/plugin-update 3.1.28 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.45 (core)",
    "@oclif/plugin-which 2.2.27 (core)",
    "@salesforce/cli 2.2.7 (core)",
    "apex 2.3.8 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.3 (core)",
    "deploy-retrieve 1.16.3 (core)",
    "info 2.6.32 (core)",
    "limits 2.3.27 (core)",
    "login 1.2.22 (core)",
    "org 2.9.27 (core)",
    "schema 2.3.21 (core)",
    "settings 1.4.21 (core)",
    "sobject 0.1.40 (core)",
    "source 2.10.27 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.7 (core)",
    "trust 2.4.34 (core)",
    "user 2.3.27 (core)"
  ]
}
```

### Additional information
If anyone else is running into this, the workaround is to just add `ENV SFDX_CONTAINER_MODE true` to your Dockerfile and rebuild the container.

**Comment by mshanemc** [comment]
@eburtness we can put the old one back from the CLI side (pr https://github.com/salesforcecli/cli/pull/1025)
but I transferred the issue to vscode so they can update their envs

**Comment by eburtness** [comment]
Rock on; thanks @mshanemc and @cristiand391!
