### ISSUE TITLE
Missing metadata type definition in registry for id 'messagingchannel' error when trying to retrieve MessagingChannel

### ISSUE THREAD

**Issue by khanisz** [forcedotcom/salesforcedx-vscode#5004]
### Summary

I am trying to retrieve MessaginChannel metadata from my org

### Steps To Reproduce:

1.  Go to Org Browser
2. Go to MessagingChannel
3. Try retrieving any of the MessagingChannels

### Expected result

MessagingChannel metadata should be retrieved

### Actual result
Error:
Missing metadata type definition in registry for id 'messagingchannel'.

### Additional information

**Salesforce Extension Version in VS Code**: 58.7.1

**SFDX CLI Version**: 7.209.6

**OS and version**: macOs Ventura 13.5

**Comment by CristiCanizales** [comment]
Hi @khanisz! Could you tell me from which kind of org you're trying to retrieve? Thanks!

**Comment by khanisz** [comment]
Hi @CristiCanizales
a developer sandbox.

**Comment by khanisz** [comment]
I replied

czw., 10 sie 2023 o 03:53 github-actions[bot] ***@***.***>
napisał(a):
