### ISSUE TITLE
Deploy and Retrieve times 

### ISSUE THREAD

**Issue by Finniusday** [forcedotcom/salesforcedx-vscode#5008]
### Summary

When we are using the Deploy and Retrieve options through VSC, the response times are over a minute. This is causing many issues when trying to code and test anything in our orgs.

### Steps To Reproduce:

1.  Authorize a development org and pull down the code base.
2.  Make a change in a class, VF Page, LWC, or any other component and try to deploy to org.  

### Expected result

A quick response in less than 20 seconds

### Actual result

Waiting for VSC to show us the deploy is finished for (in some cases) more than 4 minutes. 

### Additional information

Version v58.7.1 on all systems with the issue. 
One developer has version 58.6.2 and does not have the issue.
sfdx-cli/7.209.6 win32-x64 node-v18.15.0
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎5/‎4/‎2023
OS build	19044.3208
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by CristiCanizales** [comment]
Hello @Finniusday! Can you check if you have this setting enabled? And if so try disabling it
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/e846a10b-14b8-4cc1-9d6d-b795dc55b74b)

**Comment by Finniusday** [comment]
Thank you. That seems to have worked.

**Comment by CristiCanizales** [comment]
@Finniusday Awesome! I'll be closing this then. Feel free to create a new one if a something else arises. Thanks!
