### ISSUE TITLE
Please move "SFDX: Delete from Project and Org" to bottom

### ISSUE THREAD

**Issue by jmatos-sfdc** [forcedotcom/salesforcedx-vscode#5027]
**Is your feature request related to a problem? Please describe.**
I sometimes click on "SFDX: Delete from Project and Org" because its right next to "SFDX: Deploy Source to Org"

![Screenshot 2023-08-10 at 3 08 11 PM](https://github.com/forcedotcom/salesforcedx-vscode/assets/123118019/222d105a-be0e-4173-8b93-7444021e8a5c)

**Describe the solution you'd like**
Can we move "SFDX: Delete from Project and Org" to the bottom? 

**Describe alternatives you've considered**
Using command line "sf" commands

**Additional context**
This is low priority but thought you'd appreciate the feedback.

**Comment by CristiCanizales** [comment]
Hi @jmatos-sfdc! Thanks for bringing this into our attention. Another alternative could be to use the command palette (Open with `Cmd + Shift + P`) and run **SFDX: Deploy this Source to Org** while having the file you want to deploy open.

**Comment by CristiCanizales** [comment]
Closing this issue as it's very similar to #5132.
