### ISSUE TITLE
The VS Code extension Salesforce Extension Pack's Salesforce CLI Integration is not working, as It is throwing error 'Only absolute URLs are supported',  while retrieving and deploying to salesforce orgs. 

### ISSUE THREAD

**Issue by surbhitomar** [forcedotcom/salesforcedx-vscode#5029]
The VS Code extension Salesforce Extension Pack's Salesforce CLI Integration is not working properly, as It is throwing error 'Only absolute URLs are supported',  while retrieving and deploying to salesforce orgs.  Always throwing 'SFDX: Retrieve source from org failed to run. '

<img width="481" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/73522964/6607d477-7d93-4046-a13c-d0442bdb7d75">

**Comment by CristiCanizales** [comment]
Hi @surbhitomar! That usually happens when you're org is not connected. Can you try first re-authorizing your org, 
then reloading VSCode and finally try to deploy/retrieve again?

**Comment by surbhitomar** [comment]
Hi @CristiCanizales, 

I tried reauthorization, org connection and restarted vs code many times with different environment and didn't work anything and my team is also getting the same issue.
I saw the same issue logged here last month,
**https://github.com/forcedotcom/salesforcedx-vscode/issues/4989**
Nothing worked, I think the issue is coming due to new updates in the Salesforce CLI extension, because when I reinstalled it to last 3 month older version then it is working fine. I had to downgrade it to the 'v57.10.2'.

<img width="955" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/73522964/e8d0c8a7-b355-4f79-b053-6e1bbb62c15a">

**Comment by daphne-sfdc** [comment]
Hi @surbhitomar,

Can you please provide these details to help us reproduce the error?

SFDX CLI Version:
OS and version:

**Comment by surbhitomar** [comment]
Hi @daphne-sfdc,

**The SFDX CLI version**
<img width="346" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/73522964/29ed4840-25f4-4654-b444-ae2e2f4167ab">


**OS and version**
<img width="401" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/73522964/404a45ee-99d5-4eb3-8524-8e58ae56f276">

Also, My whole team is getting same issues.

**Comment by junners** [comment]
This is related to my case https://github.com/forcedotcom/salesforcedx-vscode/issues/5049 
Under the hood the plugin clears out the sfdx auth json which is why it's saying only absolute urls are supported

**Comment by surbhitomar** [comment]
Hi 

> This is related to my case #5049 Under the hood, something in the plugin clears out the sfdx auth json. Which is why the command output section is saying `only absolute urls are supported`

It could be the same issue and I logged this issue 3 weeks ago, I am still waiting for the replies from Support Team.

**Comment by surbhitomar** [comment]
Hi @daphne-sfdc  @CristiCanizales 

Please provide the update on this ticket as I am still waiting how this issue will be resolved.

**Comment by Hazelfire** [comment]
This is still an issue, and I am currently facing it too, but if you are looking for a workaround:

 - Log out of all existing organizations
 - Delete ~/.sfdx
 - Reconnect to your environment
 
The error should go away even on the newest version (or at least it did to me)

It does appear to be the same issue as https://github.com/forcedotcom/salesforcedx-vscode/issues/5049. I'm probably not going to spend much time debugging this unless it comes up again and annoys me.

**Comment by CristiCanizales** [comment]
Hi @Hazelfire, thank you for sharing the workaround.

@surbhitomar, did it work for you or are you still facing the same issue consistently after following the steps mentioned in the previous comment?

**Comment by surbhitomar** [comment]
Hi @CristiCanizales @Hazelfire , This did not work for me properly as it's not throwing that error but it's retrieving the components  very slow and when I degrade the SFDX CLI extension to 57.10.2 version then it works fast.

**Comment by CristiCanizales** [comment]
Hi @surbhitomar, what if you try disabling our setting`Salesforcedx-vscode-core › Experimental: Enable Source Tracking For Deploy And Retrieve`? And then reload vscode window. Is the retrieving faster?
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/98aeec38-0eda-4177-ab2a-0b4c3313ab0c)
