### ISSUE TITLE
This Is The VS Code..!!

### ISSUE THREAD

**Issue by 9040803199** [forcedotcom/salesforcedx-vscode#5037]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 9040803199** [comment]
_Want to Connect the Vs studio With my Salesforce Org._

**Comment by daphne-sfdc** [comment]
Hi, glad you're here and working with our extensions!  To help you get started, please check out our documentation here: https://developer.salesforce.com/tools/vscode

As for your question, if you have installed our extensions correctly, you should be able to Authorize an Org by selecting 'SFDX: Authorize an Org' from the command palette and following the instructions from there.  (Command palette is Cmd + Shift + P for Mac and Ctrl + Shift + P for Windows.)

Good luck!
