### ISSUE TITLE
Conflict Detection takes a very long time to start during save

### ISSUE THREAD

**Issue by simonhyphen8** [forcedotcom/salesforcedx-vscode#5039]
### Summary

With Salesforce Core Configuration > Salesforcedx-vscode-core: Detect Conflicts At Sync enabled, it takes a very long time for the conflict detection to start when saving a file.

### Steps To Reproduce:

1.  Enable Salesforce Core Configuration > Salesforcedx-vscode-core: Detect Conflicts At Sync in either Workspace or User context
2.  Enable Salesforcedx-vscode-core › Push-or-deploy-on-save in either Workspace or User context
3.  Make a change to a file that is already deployed to Salesforce org.
4. Save the file

### Expected result

Conflict detection should start _in a reasonable time_ - within a few seconds, as it used to do and then report on any conflicts, if found

### Actual result

The Terminal displays the message "Starting Conflict Detection" and it hangs there for up to twenty minutes before even attempting the conflict detection
Example of output from today (changing one file):
14:05:24.305 Starting Conflict Detection

14:14:31.213 ended Conflict Detection

14:14:31.216 Starting SFDX: Deploy Source to Org

### Additional information

**Salesforce Extension Version in VS Code**:
Salesforce CLI Extension = 58.11.0

**SFDX CLI Version**: = 7.209.6

**OS and version**: MacOS Ventura 13.4.1

**Comment by daphne-sfdc** [comment]
I'm wondering if this is related to your authorization.  Can you try logging out of all authorized orgs?  Also, if you have any scratch orgs, delete all expired scratch orgs.  The re-authorize to your dev hub and org.  Let me know if that works!

**Comment by simonhyphen8** [comment]
@daphne-sfdc Apologies for the delay.  I have tried this and still get the same results.

**Comment by simonhyphen8** [comment]
@daphne-sfdc I have tried what you suggested and done the following:
Cleared out all expired scratch orgs (sf org list --clear)
Logged out of all unauthorized / unused orgs
Initial tests show that the response times for conflict detection seems to have come down.  I'll do some more testing today, and update here as appropriate.  Please leave this issue open for another 24 hours while I test further. Thanks.
