### ISSUE TITLE
Config Collision with Emmet

### ISSUE THREAD

**Issue by justin-lyon** [forcedotcom/salesforcedx-vscode#5045]
### Summary

Emmet Tab Auto Complete no longer works. Something new in the SF Extension Pack recent updates is colliding with my config on the tab key.

### Steps To Reproduce:

1. Deactivate SF Extension Pack in the workspace
2. Open an xml file and on a new line enter the following keystrokes
    `types[tab]`
3. Confirm that Emmet expands this to a pair of tags `<types></types>`.
4. Activate the SF Extension Pack in the workspace
5. Repeat Step 2
6. VSCode adds whitespace when you press tab instead of respecting the emmet config to expand on tab. 

### Expected result

When SF Extension Pack is active, it should not cause a collision with the following emmet config
```json
"emmet.triggerExpansionOnTab": true,
```

### Actual result

When pressing the tab key, my emmet config is ignored.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:
v58.13.1

**SFDX CLI Version**:
@salesforce/cli/2.1.7 darwin-arm64 node-v18.1.0

**OS and version**:
macOS Ventura 13.3.1 (a)

**Comment by daphne-sfdc** [comment]
Hi @justin-lyon, 

Can you try adding the following right below '"emmet.triggerExpansionOnTab": true,'?

"files.associations": {
        "*.xml": "xml"
}

This is used to associate "emmet.triggerExpansionOnTab" with xml files.  Please let me know if that works for you.

**Comment by daphne-sfdc** [comment]
Glad to know I was able to help!  Closing this issue.
