### ISSUE TITLE
Apex Language Server not terminating on VSCode exit

### ISSUE THREAD

**Issue by kjonescertinia** [forcedotcom/salesforcedx-vscode#5051]
### Summary

If I start VSCode and wait for the language server to complete indexing and then close VSCode the language server continues to run in the background.  

### Steps To Reproduce:

1. Update to latest Apex extension, v58.13.1 in my case.
1. Check no Java processes are running in OS X Activity Monitor
1. Remove workspace .sfdx folder just in case current state is impacting
1. Open VSCode on workspace
1. Check output windows to see indexer has finished 
1. Close VSCode window & also quit from taskbar
1. Observe Java process is still running
1. Open VisualVM to confirm it's the language server 

### Expected result

Java language server should quit when you close VSCode workspace

### Actual result

Multiple language servers can be seen running after opening/closing VSCode a few times

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: v58.13.1

**SFDX CLI Version**:  sfdx-cli/7.183.1 darwin-arm64 node-v16.19.1

**OS and version**: OS X 13.4.1 

**JVM**:
openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment Homebrew (build 11.0.20+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.20+0, mixed mode)

**Comment by peternhale** [comment]
@kjonescertinia I am not currently able to reproduce this behavior on x64 or arm64 mac os 13.5. I have tried with java 17 and home brew versions of java 11.

When looking at the java processes that remain, could you share the results of `ps -ef | grep jorje-lsp`. Please redact any information you find sensitive.

**Comment by gbockus-sf** [comment]
@bloerinczCBS-CX The above behaviour is new functionality we added in this release for detecting orphaned Apex LSP process and terminating them if you click the button.  See [PR](https://github.com/forcedotcom/salesforcedx-vscode/pull/5160). This doesn't resolve the issue which we are still tracking and working towards resolving, but does make the process of ensuring there aren't orphaned process holding on to resources on your system a better experience.

**Comment by daphne-sfdc** [comment]
This issue was fixed in https://github.com/forcedotcom/salesforcedx-vscode/pull/5217, which has already been merged and released.  Closing this issue as completed. ✅
