### ISSUE TITLE
Apex Intellisense not populating sobjects or classes/methods

### ISSUE THREAD

**Issue by andrewaaguilar** [forcedotcom/salesforcedx-vscode#5057]
### Summary

Intellisense used to suggest class/method signatures in addition to sobjects. Workspace settings have been unchanged, and Intellisense is checked. Additionally using the command >SFDX: Refresh SObject Definitions does not bring SObjects into the context menu when pressing ctl + space to load suggestions.

### Steps To Reproduce:

1.  Enter any apex class
1.  Start typing to get intellisense suggestions or pressing ctl + space

### Expected result

Intellisense should be suggesting SObject and methods retrieved from class

### Actual result

No suggestions by intellisense and instead only suggestions from previously typed words

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52968854/609a6396-923b-45dd-9470-c18b87472f7d)

**Salesforce Extension Version in VS Code**:
58.13.1

**SFDX CLI Version**
58.13.1

**OS and version**:
macOS Ventura Version 13.5.1 (22G90)

**Comment by CristiCanizales** [comment]
Hello @andrewaaguilar! I'm sorry for the delay.

Can you update to v.58.14.2 and then verify:
- the Apex extension is running? `(Command Palette > Developer: Show Running Extensions)`
- the Apex LSP has completed indexing:

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/2a2c4879-713d-4f5e-88e9-2989104435d7)
- output tab for Apex Language Server content and send it to me?
<img width="1447" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/96fa4213-0e0d-45fd-a685-0f6395b62493">

**Comment by andrewaaguilar** [comment]
@CristiCanizales All good, I was actually able to resolve this by updating my JDK on my machine. Thanks for reaching out though - I will keep this in mind if this happens again!
