### ISSUE TITLE
Push errors

### ISSUE THREAD

**Issue by Shokhan** [forcedotcom/salesforcedx-vscode#506]
Push errors does not show path to file anymore(
![project-path](https://user-images.githubusercontent.com/22928752/42078695-206b02b8-7b86-11e8-993b-49a10d97075f.png)

**Comment by dcarroll** [comment]
Thanks @Shokhan for the posting.  This is actually an issue with the Salesforce CLI.  We have identified the problem and the fix. We are targeting a patch release to the CLI for early next week.
