### ISSUE TITLE
An Error Occurred While Saving a Visualforce File with the Style Tag in the File

### ISSUE THREAD

**Issue by garychenming** [forcedotcom/salesforcedx-vscode#5062]
### Summary

When I added some styles to the Visualforce page, an error occurred every time while saved the file.

### Steps To Reproduce:

1.  Create a Visualforce page.
2.  Add `<style>` `</style>` tag
3. Save current file.

### Expected result

No error occurred.

### Actual result

Got this error 
```
[Error - 10:55:40 AM] Request textDocument/rangeFormatting failed.
  Message: Request textDocument/rangeFormatting failed with message: js_source_text is not defined
  Code: -32603 
```

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/22324484/39ecd66d-d979-43ad-899f-708d88c50d36)

**Salesforce Extension Version in VS Code**: `v58.13.1`

**SFDX CLI Version**: `sfdx-cli/7.209.6 darwin-x64 node-v18.15.0`

**OS and version**: `masOS v13.5`

**Comment by daphne-sfdc** [comment]
Hi @garychenming, Can you send me a screenshot of your Visualforce page?  I'd like to see the contents to see where in the file you put the <style></style> tag.
