### ISSUE TITLE
not able to authorize with salesforce org

### ISSUE THREAD

**Issue by krushnaaiwale77699** [forcedotcom/salesforcedx-vscode#5064]
Type: <b>Performance Issue</b>

16:38:50.712 sfdx force:auth:web:login --setalias sas --instanceurl https://login.salesforce.com --setdefaultusername
'"C:\Users\krushna_aiwale\AppData\Local\sfdx\client\bin\..\7.209.6-8ba3197\bin\sfdx.cmd"' is not recognized as an internal or external command,
operable program or batch file.
16:38:51.70 sfdx force:auth:web:login --setalias sas --instanceurl https://login.salesforce.com --setdefaultusername
 ended with exit code 1

Extension version: 58.13.1
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:33:49.930Z)
OS version: Windows_NT ia32 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (18.42GB free)|
|Process Argv|--crash-reporter-id f99344dd-6c2b-47a5-83fe-b7f5fe9a6eeb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	  6076	code main
    0	    76	 10048	fileWatcher [1]
    0	    81	 11688	   window
    0	    53	 15200	   utility-process
    0	    31	 22492	   crashpad-handler
    0	   374	 22672	extensionHost [1]
    0	   102	 10172	     electron-nodejs ("C:\Program Files (x86)\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\krushna_aiwale\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.13.1\node_modules\@salesforce\lwc-language-server\lib\server.js --node-ipc --clientProcessId=22672)
    0	   102	 11776	     electron-nodejs ("C:\Program Files (x86)\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\krushna_aiwale\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-58.13.1\node_modules\@salesforce\aura-language-server\lib\server.js --node-ipc --clientProcessId=22672)
    0	    83	 17968	     electron-nodejs ("C:\Program Files (x86)\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\krushna_aiwale\.vscode\extensions\salesforce.salesforcedx-vscode-soql-58.13.1\node_modules\@salesforce\soql-language-server\lib\server.js --node-ipc --clientProcessId=22672)
    0	    67	 25676	     
    0	    10	 19584	       
    0	   104	 23668	shared-process
    0	   219	 24216	window [1] (Extension: Salesforce CLI Integration - Bajaj_SME_UAT_C - Visual Studio Code)
    0	    98	 28524	   gpu-process
    0	    84	 30124	window [2] (Issue Reporter)
    0	    46	 30256	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Salesforce CLI Integration - Bajaj_SME_UAT_C - Visual Studio Code)
|    Folder (Bajaj_SME_UAT_C): 11776 files
|      File types: xml(6772) cls(2051) js(804) html(376) css(327) cmp(209)
|                  page(157) trigger(119) auradoc(47) design(47)
|      Conf files: launch.json(1) settings.json(1) jsconfig.json(1)
|                  package.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
962ge761:30823813
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by CristiCanizales** [comment]
Hello @krushnaaiwale77699! Could you please share steps to repro? It seems like an issue with the cli itself. Can you try deleting this folder `C:\Users\krushna_aiwale\AppData\Local\sfdx`,  reinstall CLI and reload VS Code?

**Comment by krushnaaiwale77699** [comment]
working fine now
