### ISSUE TITLE
Authorize an Org

### ISSUE THREAD

**Issue by RajeshwarWadje** [forcedotcom/salesforcedx-vscode#5065]
Type: <b>Performance Issue</b>

Starting SFDX: Authorize an Org

16:51:25.794 sfdx force:auth:web:login --setalias SalesConfigOrg --instanceurl https://test.salesforce.com --setdefaultusername
'sfdx' is not recognized as an internal or external command,
operable program or batch file.
16:51:25.986 sfdx force:auth:web:login --setalias SalesConfigOrg --instanceurl https://test.salesforce.com --setdefaultusername
 Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli

Extension version: 58.13.1
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (19.29GB free)|
|Process Argv|--crash-reporter-id dc19db70-d5c7-4572-89ce-d6b433fd1aa4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   100	 30360	code main
    0	    94	  1120	window [2] (Issue Reporter)
    0	    87	  1188	fileWatcher [1]
    0	    47	  9928	   utility-network-service
    0	    32	 10660	   crashpad-handler
    0	    97	 11136	shared-process
    0	   144	 11440	   gpu-process
    0	    48	 23928	   utility-process
    0	   402	 24676	extensionHost [1]
    0	    36	 17964	     c:\Users\rajeshwar_wadje\.vscode\extensions\redhat.vscode-xml-0.26.1-win32-x64\server\lemminx-win32.exe ""
    0	    10	 12556	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   106	 21044	     electron-nodejs ("C:\Users\rajeshwar_wadje\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rajeshwar_wadje\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-58.13.1\node_modules\@salesforce\aura-language-server\lib\server.js --node-ipc --clientProcessId=24676)
    0	   106	 26404	     electron-nodejs ("C:\Users\rajeshwar_wadje\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rajeshwar_wadje\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.13.1\node_modules\@salesforce\lwc-language-server\lib\server.js --node-ipc --clientProcessId=24676)
    0	    96	 30876	     electron-nodejs ("C:\Users\rajeshwar_wadje\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rajeshwar_wadje\.vscode\extensions\salesforce.salesforcedx-vscode-visualforce-58.13.1\dist\visualforceServer.js --node-ipc --clientProcessId=24676)
    0	    90	 31396	     electron-nodejs ("C:\Users\rajeshwar_wadje\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rajeshwar_wadje\.vscode\extensions\salesforce.salesforcedx-vscode-soql-58.13.1\node_modules\@salesforce\soql-language-server\lib\server.js --node-ipc --clientProcessId=24676)
    0	   160	 31012	window [1] (Welcome - salesconfgOrg - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - salesconfgOrg - Visual Studio Code)
|    Folder (salesconfgOrg): 112 files
|      File types: json(27) ts(22) cls(16) eslintignore(1) forceignore(1)
|                  gitignore(1) prettierignore(1) prettierrc(1) js(1)
|                  xml(1)
|      Conf files: launch.json(1) settings.json(1) jsconfig.json(1)
|                  package.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by daphne-sfdc** [comment]
Hi @RajeshwarWadje,
As stated in the error message, you need to install the Salesforce CLI because the VSCode extensions depend on it.  Please follow the instructions at this link (https://developer.salesforce.com/tools/salesforcecli) to install the CLI.  You should be able to authorize an org once the Salesforce CLI is installed.
