### ISSUE TITLE
Apex Replay Debugger: The local source is out of sync with the server

### ISSUE THREAD

**Issue by wJavierPonce** [forcedotcom/salesforcedx-vscode#5068]
### Summary

When trying to _'Update checkpoints in org'_ I receive the following error:
`The local source is out of sync with the server. Push any changes you've made locally to your org, and pull any changes you've made in the org into your local project.`

Just to clarify, there is nothing pending on push or pull.

It only happens for a specific project/repository, and it doesn't seem to be related to the Apex Classes as if I move them to another project it works properly.

I have also tried:
- remove .sf and .sfdx folders
- create a new scratch org

I have been trying to find a way to enable debug logs for the Apex Replay Debugger, but I didn't find anyway. Is it possible?

### Steps To Reproduce:

1.  Set a checkpoint in a valid line by executing 'Toggle Checkpoint' command.
2. Execute 'Update Checkpoints in Org' command.

### Expected result

Checkpoints successfully updated.

### Actual result

`Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
SFDX: Update Checkpoints in Org, Step 4 of 6: Clearing existing checkpoints
SFDX: Update Checkpoints in Org, Step 5 of 6: Uploading checkpoints
The local source is out of sync with the server. Push any changes you've made locally to your org, and pull any changes you've made in the org into your local project.
SFDX: Update Checkpoints in Org, Step 6 of 6: Confirming successful checkpoint creation
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again.`
### Additional information

**Salesforce Extension Version in VS Code**:
v58.13.1

**SFDX CLI Version**:
sfdx-cli/7.209.6 darwin-arm64 node-v18.15.0

**OS and version**:
macOs Ventura 13.0 (22A380)

**Comment by wJavierPonce** [comment]
Thanks for your support in advance :) If you can tell me how I could enable the logs for the extension output I could add more detail, but as I said I found no way to do it. Thanks!

**Comment by CristiCanizales** [comment]
Hello @wJavierPonce. There's a similar issue #5063 for which the fix was to re-clone the repo, delete sf folder and try again. As you said, it seems to be something specific with your project too, so could you try that in order to have a very clean state and let us know if it works? Thanks!
