### ISSUE TITLE
Open Default Org Command in VS Code broken after SFDX to SF CLI Update

### ISSUE THREAD

**Issue by sl-tarvin** [forcedotcom/salesforcedx-vscode#5083]
### Summary

The move from `SFDX` to `SF` has broken the Salesforce CLI Integration plugin in VS Code. The Open Default Org command still leverages `sfdx` which now throws an error instead of navigating to the org.

### Steps To Reproduce:

Within VS Code:
1.  Press `CTRL SHIFT P`.
1.  Select command `SFDX: Open Default Org`
### Expected result

VS Code should launch the default browser navigating to an authenticated session in the Salesforce org selected.

### Actual result

```
11:14:59.935 sfdx force:org:open
(node:18344) Warning: Deprecated environment variable: SFDX_JSON_TO_STDOUT. Please use SF_JSON_TO_STDOUT instead.
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: The "force org open" command has been deprecated. Use "org open" instead.
Error (1): Only absolute URLs are supported
11:15:02.323 sfdx force:org:open
 ended with exit code 1
```

### Additional information

**Salesforce Extension Version in VS Code**:
Salesforce CLI Integration
v58.14.1
**SFDX CLI Version**:
sfdx-cli/7.209.6 win32-x86 node-v18.15.0
**OS and version**:
Windows 10 Enterprise Version 22H2

**Comment by CristiCanizales** [comment]
Hi @sl-tarvin! The issue here is not the move from **SFDX** to **SF**, that is only the cause for the warnings. When we get the error `Only absolute URLs are supported` it's usually because the org's not authorized. Could you then verify first if it's still authed?
