### ISSUE TITLE
VSCode gives me error "Salesforce CLI is not installed" when trying to Authorize Org, even though it is installed.

### ISSUE THREAD

**Issue by rafaelbrjf** [forcedotcom/salesforcedx-vscode#5084]
### Summary

VSCode gives me error "Salesforce CLI is not installed" when trying to Authorize Org, even though it is installed. I've tried installing the CLI using both npm or the .tar.xz installer and have the error with both installations. I can run sf and sfdx commands fine on terminal, I could even authorize my org though a command line on VSCode terminal, but for some reason I can't do it on the command pallete. Another thing that is weird about this is that I can use Salesforce CLI in VSCode for some other commands like creating the project, I could even set my organization as default (after i authorized it using the terminal) but the Authorizate an Org thing always gives me this error.

### Steps To Reproduce:

1. Install VSCode
2. Install salesforce-cli using npm or the installer
3. Install the Salesforce Extension Pack
4. Create a SFDX project
5. Try to authorize an org

### Expected result

The browser should have opened for me to authorize my organization

### Actual result

Got error "Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli"

### Additional information

I'm running Java 17, Visual Studio Code 1.82
![Salesforce CLI not installed](https://github.com/forcedotcom/salesforcedx-vscode/assets/31705748/82cd43e9-2f01-4ce8-ab28-9eeb5fad51ec)

**Salesforce Extension Version in VS Code**: 58.14.2

**SFDX CLI Version**: @salesforce/cli/2.7.11 linux-x64 node-v18.15.0

**OS and version**: Linux x64 6.5.0-1-MANJARO

**Comment by CristiCanizales** [comment]
Hello @rafaelbrjf! What do you get when you run `sfdx version` on your terminal?

**Comment by rafaelbrjf** [comment]
Hello Cristi! When running sf version or sfdx version I get the version prompt. "@salesforce/cli/2.7.11 linux-x64 node-v18.15.0"

I tried to install everything again in a brand new Manjaro system and ran into the same problem, then I tried in Ubuntu and it worked, so I figured the problem was on my old distro.

**Comment by CristiCanizales** [comment]
oh well, so now you're not facing this issue anymore right?

**Comment by rafaelbrjf** [comment]
Correct! Problem solved for me after changing my Linux distribution. Thank you :)
