### ISSUE TITLE
Unable to Retrieve / Deploy source to org Via UI

### ISSUE THREAD

**Issue by rileySFDEV** [forcedotcom/salesforcedx-vscode#5085]
### Summary

Unable to retrieve / deploy metadata via the UI using sf vscode package

This was working prior to uninstalling sfdx and installing sf but now just continuously loads. It DOES work if you use the CLI commands, however.

### Steps To Reproduce:

1.  Rightclick and click "Retrieve source from org
1.  wait....

### Expected result

After some time, hopefully it would retrieve the source

### Actual result

Nothing, infinite loading

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: 58.11.0
**SFDX CLI Version**:  @salesforce/cli/2.6.7 win32-x64 node-v18.15.0

**OS and version**: 22h2 22621.2215

**Comment by CristiCanizales** [comment]
Hi @rileySFDEV! Did you follow [these steps](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm) to install sf cli?

**Comment by rileySFDEV** [comment]
yes



​Kind Regards
​
Riley
Riley Hyde-Green
Salesforce Developer
Tel: 01959 534 082
Web: www.grove-pensions.co.uk
We proudly support:
Grove Pension Solutions Ltd
 ​
​​Authorised and Regulated by the Financial Conduct Authority - 465051 
 Registered in England and Wales at New Grove House, Murray Rd, Orpington BR5 3QY
 ​Company Number: 06045836
 ​
 ​If you have received this email in error, please notify the sender and delete the email and all ​attachments immediately. This email (including any attachments) may contain confidential and/or ​privileged information. If you are not the intended recipient, any reliance on, use, disclosure, ​distribution or copying of this email or attachments are strictly prohibited. ​​​Email transmission cannot be guaranteed to be secure or error free. ​
 ​
 ​This email is not intended, nor should it be taken to create any legal relations, contractual or otherwise.

**Comment by CristiCanizales** [comment]
In that case, I'm gonna ask you to try a couple of things:

1. Update to our latest version of the extensions **v58.14.2**
2. Open Command Palette and run `SFDX: Log Out from All Authorized Orgs`
3. Delete `.sf` and `.sfdx` folders from your project
4. Open Command Palette and run `Developer: Reload Window`
5. Authorize to your org
6. Retrieve source from org again

**Comment by rileySFDEV** [comment]
That worked, thank you



​Kind Regards
​
Riley
Riley Hyde-Green
Salesforce Developer
Tel: 01959 534 082
Web: www.grove-pensions.co.uk
We proudly support:
Grove Pension Solutions Ltd
 ​
​​Authorised and Regulated by the Financial Conduct Authority - 465051 
 Registered in England and Wales at New Grove House, Murray Rd, Orpington BR5 3QY
 ​Company Number: 06045836
 ​
 ​If you have received this email in error, please notify the sender and delete the email and all ​attachments immediately. This email (including any attachments) may contain confidential and/or ​privileged information. If you are not the intended recipient, any reliance on, use, disclosure, ​distribution or copying of this email or attachments are strictly prohibited. ​​​Email transmission cannot be guaranteed to be secure or error free. ​
 ​
 ​This email is not intended, nor should it be taken to create any legal relations, contractual or otherwise.

**Comment by daphne-sfdc** [comment]
Thank you for the confirmation!  Closing this issue.
