### ISSUE TITLE
VS Code does not recognize static class variable and virtual methods from parent class when extended from an inner class of a test method

### ISSUE THREAD

**Issue by tiemannf** [forcedotcom/salesforcedx-vscode#5090]
### Summary

I was testing out the lightweight trigger framework outlined from James Simone - https://www.jamessimone.net/blog/joys-of-apex/lightweight-trigger-handler/
Everything deploys successfully to a salesforce org but VS Code shows problems claiming that
- Variable does not exist
- Method does not exist or incorrect signature: void execute()
Those items are coming from virtual parent class. The variable is a static class variable. The methods are standard virtual methods overriden in the extending subclass.

### Steps To Reproduce:

1.  Create a new sfdx project in VS Code
1.  Unzip the attached zip file and add the included two APEX classes into the salesforce project
1. Deploy the two files to an org - this works fine
1. Go back to Visual Code, make sure that APEX indexing is complete and then open file TriggerHandlerBaseTest.cls
1. You should get problems reported in TriggerHandlerBaseTest.cls - review the problems

### Expected result

VS Code should NOT highlight any problems in the class TriggerHandlerBaseTest.cls

### Actual result

VS Code reports several problems on the class (28 on my machine):
- Variable does not exist: triggerContext
- Method does not exist or incorrect signature: void execute() from the type TriggerHandlerBaseTest.TestTriggerHandler
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.beforeInsert(List<SObject>)
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.beforeUpdate(List<SObject>, List<SObject>, Map<Id,SObject>, Map<Id,SObject>)
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.beforeDelete(List<SObject>, Map<Id,SObject>)
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.afterInsert(List<SObject>, Map<Id,SObject>)
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.afterUpdate(List<SObject>, List<SObject>, Map<Id,SObject>, Map<Id,SObject>)
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.afterDelete(List<SObject>, Map<Id,SObject>)
- TriggerHandlerBaseTest.TestTriggerHandler: Overriding implementations of global or public interface methods must be global or public: void TriggerHandler.afterUndelete(List<SObject>, Map<Id,SObject>)
TriggerHandlerBaseTest.TestTriggerHandler

### Additional information

**Salesforce Extension Version in VS Code**:
Salesforce Extension Pack v58.14.2
Salesforce Extension Pack (Expanded) v58.14.2

**SFDX CLI Version**:
@salesforce/cli/2.7.11 win32-x64 node-v18.15.0
(2.7.11-5a5b1de)

**OS and version**:
Windows 11

[ApexClasses.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/12600710/ApexClasses.zip)
![VSCOde-ReportedProblems](https://github.com/forcedotcom/salesforcedx-vscode/assets/45035140/f04a6be9-f92a-49fd-bb6a-10ac400bcbf5)

**Comment by CristiCanizales** [comment]
Hello @tiemannf!
I was not able to reproduce this issue, for me the deploy of the 2 Apex Classes worked just fine and the problems tab behavior was the expected, there was nothing there.

I have a question though... how did you deploy? step 4 seems unclear to me

Also, if you just reload vscode the problems should go away (Open Command Palette > Developer: Reload Window)

**Comment by tiemannf** [comment]
Hello @CristiCanizales,
thanks a lot for looking into this. I deployed using the VSCode (Salesforece Extensions) context menu on the classes directly.

For me whenever opening up VSCode and going to this project. When I look at the test class the problem tab shows the errors above.

Step 4 means go back to VSCOde and open the class file TriggerHandlerBaseTest.cls. The problem tab will then show all the errors shown in the screenshot.

Important: Make sure that APEX indexing is complete. Otherwise the problem tab remains empty. For me this indexing takes quite some time. Reloading the windows does not help either. Again wait for APEX indexing to be complete. Then go to the class file and the problem tab gets populated.
Thank you.

**Comment by tiemannf** [comment]
Hello @CristiCanizales ,
I now isolated the two classes into a new from scratch created empty sfdx project. Now it looks better but still 7 problems remain. Those are actually one and the same problem that the virtual class static variable TriggerHandlerBase.triggerContext is not visible.
![VSCode-ReportedProblems-After-Class-Isolation](https://github.com/forcedotcom/salesforcedx-vscode/assets/45035140/3acbc2e9-f696-4f70-a8bb-e3f4c2df9026)
