### ISSUE TITLE
Einstein for Developers - Example Prompts and Responses - SOQL in FOR Loop

### ISSUE THREAD

**Issue by ThomasSmithIRE** [forcedotcom/salesforcedx-vscode#5097]
### Summary

[Einstein for Developers - Example Prompts and Responses](https://developer.salesforce.com/tools/vscode/en/einstein/einstein-example-prompts) documents a prompt response which includes a SOQL in FOR loop.

### Steps To Reproduce:

1.  Navigate to https://developer.salesforce.com/tools/vscode/en/einstein/einstein-example-prompts.
2. Scroll to section _Prompt: Write an Apex trigger to add the number of contacts associated with an account._
3. Copy and paste the documented code.
4. Deploy code to a Developer sandbox.
5. Run anonymous Apex
```
List<Account> accounts = new List<Account>();

for (Integer i = 0; i < 200; i++) {
	Account account = new Account(Name = 'Test Account ' + i);
	accounts.add(account);
}
insert accounts;
```

### Expected result

Recommended Einstein response is efficient to handle bulk DML on Account.

### Actual result

```
System.LimitException: Too many SOQL queries: 101  
Trigger.gptcontacttrigger: line 5, column 1  
```

**Comment by gbockus-sf** [comment]
Thanks for reporting @ThomasSmithIRE! 
@sbudhirajadoc An update we should make to the documentation.
