### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by thierrytrouin** [forcedotcom/salesforcedx-vscode#5102]
Hi Team,

I have an error with a VS Code Projet.

The message is :
Metadata API request failed: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

This message occurred when I "Retrieve Source from Org" or "Deploy Source to Org" but "Diff File Against Org" command is working.

My sytem configuration is the following :
OS : Windows 10 64bits
VS Code : 1.82.2
sfdx : 7.193.2
Salesforce Extension plugin : v58.14.2

The project has a local repository only

Many thanks for your help,
Thierry

**Comment by daphne-sfdc** [comment]
Have you already tried the provided solution?  It was delete the .sfdx and .sf folders, then run "Developer: Reload Window" from the command palette.  Then authorize your org again and try to deploy/retrieve your file.

**Comment by thierrytrouin** [comment]
Ok, sorry, I made a translation error.
It's done
Many thanks
