### ISSUE TITLE
error "C:\Users\*\*\Local\sfdx\client\bin\..\7.209.6-8ba3197\bin\sfdx.cmd"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mpuri18** [forcedotcom/salesforcedx-vscode#5105]
### Summary

Since 2 days, whenever i try to authorize a new org, i get error "C:\Users\*\*\Local\sfdx\client\bin\..\7.209.6-8ba3197\bin\sfdx.cmd"' is not recognized as an internal or external command, operable program or batch file. I am able to switch between orgs, deploy as well as retrieve. I am also able to diff. when i run sfdx --version , i get the same error. In my system variables, i have the bin path set up as C:\Program Files\sfdx\bin. What might be the issue? The CLI version is latest

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by CristiCanizales** [comment]
hi @mpuri18, can you please provide us with the all the details requested in the issue template?
- Salesforce Extension Version in VS Code:
- SFDX CLI Version:
- OS and version:

**Comment by Dancli** [comment]
I'm experiencing the exact same issue as @mpuri18 since yesterday. 

I'm using the latest version of Salesforce CLI Integration (v58.14.2). Downgrading to v57.15.0 didn't fixed the issue. I replaced my version of sfdx with sf v2.8.11, didn't fixed my problem.

I'm using Windows 10 22H2.

**Comment by mpuri18** [comment]
i had to move from Java8 to Java11 as i started getting some java version error regarding apex language server as well. Also i had to move from  sfdx(v7) to sfdx(v2) in order to fix the cmd issue. This fixed the issue.

**Comment by BryanLL** [comment]
I had to re-install sf (aka sfdx) and then edit my system path environment variable to remove the obsolete sfdx/bin reference in favor of the sf/bin one.
