### ISSUE TITLE
VS Code : Lightning Web Components  Extension Error :  Cannot read properties of undefined reading ('location')

### ISSUE THREAD

**Issue by pavan00089** [forcedotcom/salesforcedx-vscode#5113]
Hello Team,

When I load the VS code  then I see the error on the screen ' Cannot read properties of undefined reading ('location')'.

Below steps I have followed but still I see the error.

1) I have updated vs code to latest version.
2) Updated sfdx to latest version
3) Uninstalled the extension pack and re-installed again.
4) Updated Jdk to latest version.

Let me know How can this be fixed. I have tried all the ways but no luck on my side.
![VS_Error](https://github.com/forcedotcom/salesforcedx-vscode/assets/104124504/36d171e1-d18a-43a1-b4ba-af169112cc4a)

Thanks,
Pavan   @@Thammali.

**Comment by CristiCanizales** [comment]
Hello! I'm closing this as we're keeping track of this issue in #5069.
