### ISSUE TITLE
Why not update sfdx to sf command?

### ISSUE THREAD

**Issue by shylockWu** [forcedotcom/salesforcedx-vscode#5116]
## Question
There are always some warnings when causing the VsCode plug-in to be used ⚠️. Salesforce has officially abandoned the maintenance of sfdx command, why the plugin has not been updated?

**Comment by CristiCanizales** [comment]
Hi @shylockWu! We'll get rid of some of those warnings in our next release, but it's a big effort that will take some time to accomplish
