### ISSUE TITLE
Not able to authorize salesforce org

### ISSUE THREAD

**Issue by amolkgirme87** [forcedotcom/salesforcedx-vscode#5122]
Hi Team, I am not able to authorize the Salesforce org in the latest version of salesforce CLI integration. Please help.

**Comment by CristiCanizales** [comment]
Hello @amolkgirme87, could you please share all the details asked in the issue template to have some context? versions, steps to reproduce, etc

**Comment by dtrotta1** [comment]
@CristiCanizales , vs code , run auth an org is producing a message. »   Warning: org:login:web is not a sfdx command.
Did you mean plugins? [y/n]: 
Then it fails , this needs high priority. 
Sfdx update errors says its missing S3 ? 

Having to manually move stuff with copy and paste, please fix.

**Comment by CristiCanizales** [comment]
Hi @dtrotta1, as I mentioned in the comment above, I need your system details to have some context. VSCode version, extensions version, sfdx-cli version. I'm guessing it has something to do with your cli version so could you please try updating first?

**Comment by dtrotta1** [comment]
@CristiCanizales  I tried downloading the msi and installed. Same Error. 

I also tried running: sfdx update
 »   Warning: Attempting to contact update site...
sfdx-cli: Updating CLI... !
 »   Error: S3 host is not reachable.
 
 As you can see s3 host error ? 
 
 What other command can I run to give you more information ?

**Comment by CristiCanizales** [comment]
@dtrotta1 I still need your system details to have some context. VSCode version, extensions version, sfdx-cli version. Could you please share those??

**Comment by dtrotta1** [comment]
@CristiCanizales 
Vscode - 1.82.2
Salesforce extension pack : v58.15.0

**Comment by hungrypipo** [comment]
I have the same problem my sfdx-cli version is 7.161
Auth org was working before update to this 58.15.0 version, unfortunately I don't know what version it was I was on

**Comment by dtrotta1** [comment]
I got it to work @CristiCanizales  and @hungrypipo . I had the same problem. sfdx --version was showing 7.81.0 but npm uninstall was not working. Neither was sfdx update. All of this worked fine yesterday .... Anyhow I ran all uninstallers I could find. Then I located the saleforce cli in programfiles and under user/appdata/local and removed them. I then tried the command in vs and it said sfdx was missing and provided a link to the installer. https://developer.salesforce.com/tools/salesforcecli# After I installed that sfdx and vs code is working again. sfdx --version is now showing. @salesforce/cli/2.9.8 win32-x64 node-v18.15.0

**Comment by hungrypipo** [comment]
Unfortunately I have to say on sfdx-cli@7.161 and can't upgrade to the new @salesforce/cli so I need the extension pack to work with sfdx-cli@7.161
@CristiCanizales Looking at others looks like Salesforce extension pack 58.4.1 works for my use case, how do I install that version?

**Comment by CristiCanizales** [comment]
Hi @hungrypipo, do you have to stay on sfdx-cli in general or specifically sfdx-cli@7.161? I'm asking to check if maybe you can update to sfdx-cli@7.209.6 (not new @salesforce/cli). If not, to go back to a previous version of the extension you just need to go to the extensions section, select the extension you want to downgrade and click the dropdown right next to uninstall:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/e60180a3-11ed-4a4f-9732-445f1a5fa583)
and then you'll get a prompt to select the desired version

**Comment by hungrypipo** [comment]
It's a long story and unfortunately I have to stay at 7.161 can't go past that version.
I see the dialog but when I pick it it brings me to the command pallet and I it only has 58.15.0 and I can type but it doesn't seem to take 58.4.1

**Comment by CristiCanizales** [comment]
@hungrypipo Please download [this extension](https://github.com/forcedotcom/salesforcedx-vscode/releases?q=58.14.1&expanded=true#:~:text=salesforcedx%2Dvscode%2Dcore%2D58.14.1.vsix) (salesforcedx-vscode-core..) and then install from VSIX
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/fa3a22fc-1b78-4201-bc22-fc5b328184fe)

**Comment by hungrypipo** [comment]
@CristiCanizales I don't seem to get a .vsix from that link it takes me to the release versions page

**Comment by CristiCanizales** [comment]
@hungrypipo uh it's not keeping that section in the url. If you scroll down until the release of your desired version, and open the Assets section of that release, you'll find the vsixes there
<img width="1123" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/69223946-ac92-49f4-a738-076d8f29fd3f">

**Comment by hungrypipo** [comment]
Thanks! Found it, the assets section :)

**Comment by hungrypipo** [comment]
So weird using VSIX makes the Salesforce Extension Park component that version but all the actual components are 58.15.0!

**Comment by hungrypipo** [comment]
And uploading pics is not working

**Comment by CristiCanizales** [comment]
@hungrypipo you only needed to downgrade `salesforcedx-vscode-core` extension :)

**Comment by hungrypipo** [comment]
Ok so I just installed the old core 58.4.1 and rest are 58.15.0
now when I try to Auth an Org I'm getting
ERROR running auth:web:login:  Cannot start the OAuth redirect server on port 1717. 

Try this: 
Kill the process running on port 1717 or use a custom connected app and update OauthLocalPort in the sfdx-project.json file.
14:52:43.34 sfdx force:auth:web:login --setalias QA --instanceurl https://test.salesforce.com --setdefaultusername
 ended with exit code 1

**Comment by CristiCanizales** [comment]
@hungrypipo can you log out of all authorized orgs, delete .sfdx/.sf folders, reload vscode and try auth again?

**Comment by hungrypipo** [comment]
Had to reboot in addition to that but it works now!

**Comment by christopmj** [comment]
This is a constant nightmare for me, I dread any sandbox refresh or new sandbox setup, wondering if I will be able to develop or spend the day troubleshooting VS Code / SFDX issues. Today, I am both unable to update SFDX and unable to authorize an org, but this is a new error.

PS C:\(PATH REMOVED)> sfdx update
 !    Attempting to contact update site...
 !    S3 host is not reachable.

(Tried disconnecting VPN's, changing networks to fix the above error, did not work) 

After doing a windows uninstall of SFDX, and re-installing from current .exe, I am still seeing the same error. After reinstall, sfdx version returns:
sfdx-cli/6.48.0-bfccc40118 (windows-x64) node-v8.9.4

With new SFDX, I am seeing this error with "Authorize an Org", note this is the same error I saw before re-installing:

10:10:35.549 sfdx org:login:web --alias (REMOVED) --instance-url https://test.salesforce.com --set-defaultorg:login:web 
 !    org:login:web is not a sfdx command.
 !    Perhaps you meant force:auth:web:login
 !    Run sfdx help for a list of available topics.
10:10:36.672 sfdx org:login:web --alias (REMOVED)--instance-url https://test.salesforce.com --set-default
 ended with exit code 1

**Comment by christopmj** [comment]
I was able to authorize my org, but the VS Code plugin was broken, getting the following error when using the "SFDX: Authorize an Org" option in VSC:
_10:28:30.875 sfdx org:login:web --alias Development --instance-url https://test.salesforce.com --set-default
 !    org:login:web is not a sfdx command.
 !    Perhaps you meant force:auth:web:login
 !    Run sfdx help for a list of available topics._
 
I was able to web authorize by manually using the force:auth:web:login command directly in terminal in VS code, need to give it switches "-a" (alias) and "-r" (login url, e.g. https://test.salesforce.com).

Here is a working example:
sfdx force:auth:web:login -a Development -r https://test.salesforce.com

Reference documentation (hopefully they don't move this in the next week or two):
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

**Comment by daphne-sfdc** [comment]
@christopmj What you're seeing is the result of our upgrades from SFDX to SF style variables to remove warnings.  I see that you're on SFDX version 6, which only supports the old SFDX style variables.  To support the SF style variables, I would ask you to update to the latest version of SFDX (version 7), but as you said, you were not able to update SFDX.

In that case, I have two options for you:
1. The CLI team has already rolled out SF v2, and you can make the conversion from SFDX -> SF CLI. (https://developer.salesforce.com/tools/salesforcecli)
2. If you must stay on SFDX (which is currently in maintenance mode), you can remove your existing SFDX version 6 from your computer and install SFDX version 7. (https://www.npmjs.com/package/sfdx-cli?activeTab=code)

Sorry for the inconvenience, and I hope one of these options to move forward can work for you.

**Comment by peternhale** [comment]
@christopmj were you able to resolve this issue with the options provided by daphne-sfdc?

**Comment by christopmj** [comment]
So I uninstalled SFDX again using appwiz.cpl, and re-installed using the SV v2 link given by @daphne-sfdc (https://developer.salesforce.com/tools/salesforcecli), re-ran version and get the following from command line:
_C:\Users\REDACTED>sfdx version
sfdx-cli/6.48.0-bfccc40118 (windows-x64) node-v8.9.4

C:\Users\REDACTED>sf version
@salesforce/cli/0.0.41 win32-x64 node-v12.13.0_

Not sure if relevant, but I have the following PATH variables on my user:
_C:\Program Files\sfdx\bin; 
C:\Program Files\sf\bin_

In my C:\Program FIles, I have "Salesforce CLI" and "sf", but NOT "sfdx".

In VSC, I am still seeing the same problem, and require the same workaround I gave above:
_09:25:58.495 sfdx org:login:web --alias TestCLI --instance-url https://test.salesforce.com --set-default
 !    org:login:web is not a sfdx command.
 !    Perhaps you meant force:auth:web:login
 !    Run sfdx help for a list of available topics.
09:26:05.522 sfdx org:login:web --alias TestCLI --instance-url https://test.salesforce.com --set-default
 ended with exit code 1_

cc: @peternhale

**Comment by peternhale** [comment]
@christopmj Please remove `C:\Program Files\sfdx\bin` from your path, that appears to be from sfdx installer of the past.

cd to `C:\Program Files\sf\bin` in command prompt and run `.\sfdx version`

I just installed the most recent version of SF V2 from https://developer.salesforce.com/tools/salesforcecli and my results for the version command are `@salesforce/cli/2.11.8 win32-x64 node-18.15.0`

Then open vscode and in a terminal run `sfdx version`

The result should be same as when running from bin dir.

**Comment by christopmj** [comment]
@peternhale So a plain "sfdx version" is returning the 6. path. Force-running ".\sfdx version" from "C:\Program Files\sfdx\bin" is returning the (correct) version you specify @salesforce/cli/2.11.8 ... .
Looking at my system path variables, I am seeing only c:\Program Files\sf", but when I run echo %PATH%, I'm also seeing this (which I cannot find in the windows gui sysdm.cpl tool):
c:\Program Files\Salesforce CLI\bin. Force running THAT sfdx returns the incorrect/old 6.x version.

I know that this path is causing the issue, but am at a loss as to how it got there or how to remove it if I can't find it in the sysdm.cpl gui (it is not in system or in my user's path, but from the order it appears, the bad path comes before any of my user path variables). Not sure if some VSC extension command file or something else is injecting that path, or what is going on.

BTW, help is much appreciated!

**Comment by peternhale** [comment]
@christopmj It seems to me that we need to get your computer back to a clean state with all CLI related artifacts remove. I know you have done this already, but are you willing to do this again? I would go so far as removing vscode, as well.

* remove sf ([instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm))
* cleanup and PATH env vars
* ensure the "Program Files" directories for sfdx, sf and "Salesforce CLI" are removed
* uninstall vscode

* Download and install sf v2
* Using the steps from previous post verify installation from a command prompt
* Verify that PATH is correct

* install and configure vscode
* verify sf install via vsocde terminal to ensure it is referencing correct version

**Comment by christopmj** [comment]
So it appears that much of my pain was that the SFDX installer was not cleaning up my path variables, in particular, the following two user path entries (not system) were causing me issues:
C:\Program Files\sfdx\bin
C:\Program Files\Salesforce CLI\bin

If anybody else runs into the issue I was seeing (old SFDX is being called when you have SF v2 installed), run "sysdm.cpl" from a windows-r prompt, in the window that opens, click on "Advanced" => "Environment Variables". From there, in the listview in the next window (will be labeled "User variables for <YOUR_LOCAL_USERNAME>", find "Path", click the "Edit" button, and find the variables I listed above and remove them.

**Comment by peternhale** [comment]
@christopmj glad you got this ironed out! I will pass along the uninstall not cleaning up env vars to the CLI team to see if something can be done to properly remove the envs.
