### ISSUE TITLE
We have to restart VS Code to update the default setting for packageDirectories.

### ISSUE THREAD

**Issue by oalexandrino** [forcedotcom/salesforcedx-vscode#5130]
### Summary

I have 2 directories configured in the `packageDirectories`, and I want to switch the default setting in `packageDirectories`, but it only works if I restart the VS Code.

### Steps To Reproduce

- Open the sfdx-project.json file.
- Set an entry as the default.
- Go to the manifest/package.xml file and provide the command in the menu for retrieving the metadata.

### Expected result
- The metadata should be downloaded in the file folder of the configuration item that is pointing to default.

### Actual result
- The metadata are downloaded to the previous configuration
- When I restart the VS Code, it gets the updated setting and everything is okay

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.10.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\olavo\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.7.1 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.10.2 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "data 2.5.9 (core)",
    "deploy-retrieve 1.18.0 (core)",
    "info 2.6.43 (core)",
    "limits 2.3.34 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "schema 2.3.26 (core)",
    "settings 1.4.29 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.34 (core)",
    "telemetry 2.3.3 (core)",
    "templates 55.5.12 (core)",
    "trust 2.6.13 (core)",
    "user 2.3.32 (core)"
  ]
}
```

**Comment by daphne-sfdc** [comment]
Hi @oalexandrino,
In this repo, there are three files called "sfdx-project.json".  Which one are you referring to?

<img width="1728" alt="Screenshot 2023-10-02 at 5 07 49 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/139700604/5e965c47-1a34-4a89-89b1-fd8cd1ca55c7">

**Comment by peternhale** [comment]
@oalexandrino are you still experiencing this issue?

**Comment by oalexandrino** [comment]
Hello! Should I have one sfdx-project.json for each package? I have just one in the root directory. Inside it, I have set the the entries for packageDirectories.

**Comment by peternhale** [comment]
@oalexandrino You are correct, one sfdx-project.json with a set of packageDirectories.

**Comment by peternhale** [comment]
@oalexandrino are you able to share your sfdx-project.json file?
