### ISSUE TITLE
Unable to run Salesforce CLI in Visual Studio Code

### ISSUE THREAD

**Issue by NovaMachina** [forcedotcom/salesforcedx-vscode#5131]
### Summary

I have installed the Salesforce Extension Pack (Extended) on Visual Studio Code and installed the Salesforce CLI via NPM (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm). After creating a project from the command pallet, I am unable to authorize an org via the command pallet. I receive the following error:
```
Starting SFDX: Authorize an Org

16:58:04.317 sfdx org:login:web --alias lwc_and_salesforce_data --instance-url https://login.salesforce.com --set-default
16:58:04.319 sfdx org:login:web --alias lwc_and_salesforce_data --instance-url https://login.salesforce.com --set-default
 Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli
```

### Steps To Reproduce:

1. Create project via the command pallet command: `SFDX: Create Project`. Completes as expected.
2. Execute `SFDX: Authorize an Org` via the command pallet. See error

### Expected result

I would expect the command to execute correctly.

### Actual result

Receive the following error:
```
Starting SFDX: Authorize an Org

16:58:04.317 sfdx org:login:web --alias lwc_and_salesforce_data --instance-url https://login.salesforce.com --set-default
16:58:04.319 sfdx org:login:web --alias lwc_and_salesforce_data --instance-url https://login.salesforce.com --set-default
 Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli
```

### Additional information

Salesforce CLI installed via npm:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/5257148/d622ea84-1e56-4999-8f69-d0ca3bcf59b8)
Salesforce CLI is executable from terminal:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/5257148/9b31540f-3a8a-49aa-8b1e-6d2c2fe8656e)

**Salesforce Extension Version in VS Code**:
v58.15.0

**SFDX CLI Version**:
v2.5.7

**OS and version**:
Fedora Linux 37

**VS Code version**:
v1.82.2

**Comment by daphne-sfdc** [comment]
Hi @NovaMachina, Can you try updating the Salesforce CLI to the latest version?  Go to Terminal and run "sf update".

**Comment by NovaMachina** [comment]
@daphne-sfdc Running `sf update` resulted in:
```
sf update
@salesforce/cli: Updating CLI...
@salesforce/cli: Updating CLI... not updatable
```

However, running `npm update -g` did upgrade SFDX to 2.10.2.

Unfortunately, the issue still exists.

**Comment by daphne-sfdc** [comment]
Is there any particular reason you installed the Salesforce CLI using NPM?  What if you uninstall the Salesforce CLI and reinstall it using this link instead? https://developer.salesforce.com/tools/salesforcecli

**Comment by NovaMachina** [comment]
Uninstalled CLI installed by NPM. Reinstalled following directions for .tar install. Same issue.

**Comment by daphne-sfdc** [comment]
I'm curious - are you able to get around the issue by running commands directly from the Terminal?  Open a new Terminal window and type "sf org login web".  Are you able to authorize your org from there?  If yes, you can then run "SFDX: Set a Default Org" from the command palette and select the org you just authorized from the list that pops up.

**Comment by daphne-sfdc** [comment]
Another thing - In your original post, under "Additional Information" you provided a screenshot of "whereis sfdx".  Were you running that (and your other commands) in your VSCode terminal or a separate Terminal?

**Comment by NovaMachina** [comment]
> I'm curious - are you able to get around the issue by running commands directly from the Terminal? Open a new Terminal window and type "sf org login web". Are you able to authorize your org from there? If yes, you can then run "SFDX: Set a Default Org" from the command palette and select the org you just authorized from the list that pops up.

Doing this works. I was able to set the default org. It appears that for whatever reason, the login command doesn't work from the VSCode CLI extension.

> Another thing - In your original post, under "Additional Information" you provided a screenshot of "whereis sfdx". Were you running that (and your other commands) in your VSCode terminal or a separate Terminal?

I ran the `whereis` command in both the VSCode terminal and a stand alone terminal.

**Comment by daphne-sfdc** [comment]
Are you seeing any other commands that are not working in VSCode, or is it just "SFDX: Authorize an Org"?  After you did the workaround by logging in using the CLI, did you get errors while running anything else?

**Comment by daphne-sfdc** [comment]
Hi @NovaMachina,
UPDATE: This is actually a known issue - please see https://github.com/forcedotcom/salesforcedx-vscode/issues/3816.

We're not sure why users are seeing this issue, but we suspect that it is caused by the VSCode instance not having the same PATH as the Terminal and being out of sync.  The identified workaround is to open VSCode using the command line by running "code ." instead of opening it from the app launcher.

If you currently do not have "code ." setup, you can do so by running "Shell Command: Install 'code' command in PATH" from the command palette.  Then try quitting VSCode and reopening it using "code ." and retry "SFDX: Authorize an Org".

**Comment by NovaMachina** [comment]
> Are you seeing any other commands that are not working in VSCode, or is it just "SFDX: Authorize an Org"? After you did the workaround by logging in using the CLI, did you get errors while running anything else?

> Are you seeing any other commands that are not working in VSCode, or is it just "SFDX: Authorize an Org"? After you did the workaround by logging in using the CLI, did you get errors while running anything else?

This was the only command that I cam across that was having issues.

> Hi @NovaMachina, UPDATE: This is actually a known issue - please see #3816.
> 
> We're not sure why users are seeing this issue, but we suspect that it is caused by the VSCode instance not having the same PATH as the Terminal and being out of sync. The identified workaround is to open VSCode using the command line by running "code ." instead of opening it from the app launcher.
> 
> If you currently do not have "code ." setup, you can do so by running "Shell Command: Install 'code' command in PATH" from the command palette. Then try quitting VSCode and reopening it using "code ." and retry "SFDX: Authorize an Org".

This is good to know. I appreciate the update and the info on how to work around the issue!

I will go ahead and close this as solved since it appears to be a duplicate.

**Comment by daphne-sfdc** [comment]
Thank you for the update @NovaMachina.  We will let you know if we find a fix for this issue.
