### ISSUE TITLE
Apex auto complete and suggestion is not working.

### ISSUE THREAD

**Issue by yazuminsu** [forcedotcom/salesforcedx-vscode#5134]
got this error for Apex Language Server
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/102346166/fdbc192e-a9be-4463-888d-75196d3f54bd)

**Comment by daphne-sfdc** [comment]
Hi @yazuminsu,

This looks like a corrupted index file.  Please do the following steps:
1. quit vscode
2. remove folder .sfdx/tools/246
3. open vscode for the same workspace

**Comment by yazuminsu** [comment]
oh great it worked, thank youu
