### ISSUE TITLE
Org Open shortcut results in an error

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/salesforcedx-vscode#5137]
If you click the icon in the bottom status bar that opens the current default org, the org doesn't open.  See screenshot for the error shown.  This happens from VS Code and from Code Builder.

**To reproduce:**

1. From VS Code or Code Builder, be sure you have an org connected
2. Click the org-open icon in the bottom status bar

**Expected result:** Org opens in a new tab

**Actual result:** Error in the toast message & output panel.  The org does not open.

See screenshot for visual.  Here's the error:

```
Starting SFDX: Open Default Org

09:04:22.323 sfdx org:open
/Users/smaddox/.local/share/sfdx/client/bin/sfdx: line 16: /Users/smaddox/.local/share/sfdx/client/bin/../7.209.6-8ba3197/bin/sfdx: No such file or directory
09:04:22.646 sfdx org:open
 ended with exit code 1
```

**Salesforce Extension Version in VS Code**:  58.16.0

**OS and version**: Mac ventura 13.5.2

<img width="1894" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/59572234/de6097fa-bbb1-4818-9652-620dd324257f">

**Comment by gbockus-sf** [comment]
Possibly related? https://github.com/forcedotcom/cli/issues/2447

**Comment by peternhale** [comment]
@smaddox-sf I tried this locally and I am not seeing this error when the default org icon is present in vscode.

Could you provide the version of sfdx you are using by running `sfdx --version` in a vscode terminal.

Given that your vscode session is detecting a default org could you run `sfdx org:list` and `sfdx config:list` and share the results. Please redact any sensitive information from org:list and config:list.

**Comment by peternhale** [comment]
Seems that sfdx had been removed from the file system, so a reinstall fixed the failure seen. The error presented to the user is not useful, as the runtime env should better detect and report that sfdx is not present.

**Comment by peternhale** [comment]
Thanks @gbockus-sf, yes it is the same issue [forcedotcom/cli#2447](https://github.com/forcedotcom/cli/issues/2447)
