### ISSUE TITLE
I recently installed the latest version and I am no longer able to Authorize an Org. I

### ISSUE THREAD

**Issue by brandon-cypress** [forcedotcom/salesforcedx-vscode#5158]
### Summary

I recently installed the latest version and I am no longer able to Authorize an Org. 

### Steps To Reproduce:

1.  Open Visual Code Studio.
2.  Install Salesforce Extension Pack
3. Create a New Project
4. Open the Command Palette
5. Type SFDX: Authorize an Org

### Expected result

A window should open to verify login and authenticate an org with my project in Visual Studio.

### Actual result

It appears the command is no longer recognized, and causing an error.  here is the output:

Starting SFDX: Authorize an Org

20:04:21.966 sfdx org:login:web --alias vscodeOrg --instance-url https://test.salesforce.com --set-default
 ›   Warning: org:login:web is not a sfdx command.
Did you mean plugins? [y/n]: 
 ›   Error: Run sfdx help for a list of available commands.
20:04:28.647 sfdx org:login:web --alias vscodeOrg --instance-url https://test.salesforce.com --set-default
 ended with exit code 127
 
### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: v59.0.0

**SFDX CLI Version**: v59.0.0

**OS and version**: MAC os 14.0 (23A344

**VS Code version**: Version: 1.82.2

**Comment by gbockus-sf** [comment]
Hi @brandon-cypress 
This may be an issue with the version of the SF CLI you are running.  Can you run the following from the terminal in VSCode and let me know what it tells you? 
```
sfdx --version
sfdx-cli/7.209.6 darwin-x64 node-v18.15.0
sf --version
@salesforce/cli/1.86.7-legacy.0 darwin-x64 node-v18.15.0
```

I just verified on my local install and it executed the associated command without issue. 
`sfdx org:login:web --alias vscodeOrg --instance-url https://test.salesforce.com --set-default`

**Comment by brandon-cypress** [comment]
Thank you,

I just ran sfdx --version

sfdx-cli/7.19.0-c5be43915c darwin-x64 node-v10.15.3

I notice I have node-v10 and yours is 18, would that be causing the issue?

Also, when I attempt to run sf --version I received the following:

bash: sf: command not found

Is there a different sf package that I am missing as well?

Thank you for the prompt response

*Brandon Walton*

**Comment by gbockus-sf** [comment]
ah.  You are running into the cli issue where it will delete itself if not updated.  See https://github.com/forcedotcom/cli/issues/2447

This is the root problem for you.  Basically the CLI is out of sorts so when you try to use it in vscode nothing works as expected.  
There are workarounds/fixes in that issue.  Please let me know if it doesn't resolve the issue for you.

**Comment by brandon-cypress** [comment]
Awesome, I believe this is resolved and I am off and to the races.  Thank
you so much for the help :)

**Comment by gbockus-sf** [comment]
👍
