### ISSUE TITLE
Local Dev Server – @AuraEnabled methods don't work in Lightning Web Components

### ISSUE THREAD

**Issue by kovdmm** [forcedotcom/salesforcedx-vscode#5165]
### Summary

Using the Local Dev Server with a Scratch Org, LWC cannot load data from the remote controller.

This issue also discussed:

* https://github.com/forcedotcom/lwc-dev-server-feedback/issues/155
* https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000PfDgUSAV

### Steps To Reproduce:

1. Create an empty project, empty scratch org.
2. Create an Apex class with the `@AuraEnabled` method, which allows retrieving some data from the org.
3. Create a Lightning Web Component, that uses this aura-enabled method.
4. Deploy created metadata.
5. Run the local dev server, and open this component.

### Expected result

The component retrieves the data from the org.

### Actual result

An error occurred.

**Dev Server output log:**

```
Error: Uncaught [Error: Unable to read the Aura token from the response.]
```

**Response:**

```json
{
    "error": [
        {
            "message": "error parsing or finding aura config: window.Aura not found"
        }
    ]
}
```

### Additional information

**Dev Server output log:**

![Local Dev Server output](https://github.com/forcedotcom/salesforcedx-vscode/assets/30024615/bf587180-84fd-4774-a4f1-59e634aa353e)

**Response:**

![Chrome Dev Tools – Local Dev Server – Console Error ](https://github.com/forcedotcom/salesforcedx-vscode/assets/30024615/43e8bea0-44c9-4170-9aa0-1afee03bfc17)

![Chrome Dev Tools – Local Dev Server – Apex Execute Response](https://github.com/forcedotcom/salesforcedx-vscode/assets/30024615/08b1383c-593c-4539-8110-ebb03dd91d3f)

### Environment information

**Salesforce Extension Version in VS Code**: `v59.0.0` (`salesforce.salesforcedx-vscode-lwc`)

**SFDX CLI Version**: `@salesforce/cli/2.10.2 win32-x64 node-v16.17.0`

**Plugin version**: `@salesforce/lwc-dev-server 2.11.0`

**OS and version**: `Microsoft Windows [Version 10.0.19045.3570]`

**VS Code version**: `1.83.1 f1b07bd25dfad64b0167beb15359ae573aecd2cc x64`

**Comment by bilal-elchami** [comment]
Thanks @kovdmm for this issue.
The functionality of running Lightning Web Components (LWC) locally had been seamless until Salesforce introduced the `Security Enhancements for CSRF Tokens for Lightning Apps` release update! It has had an adverse impact on the interactions with Apex endpoints from the local development server.
It is of paramount importance that this issue is addressed promptly to enhance our team's productivity and efficiency.

**Comment by pilivpp** [comment]
Same problem here... Thanks for adding this issue.

**Comment by zac-barton-apprisers** [comment]
I'm facing the same issue also. This has only just started happening in the last few days from what I can see and we need a fix asap.

**Comment by crist1114** [comment]
facing the same error please helppppppppppppppp

**Comment by zac-barton-apprisers** [comment]
I managed to create a patch to fix this issue that I'm using.

Download the below **patch** and save as `apexMiddleware.js.patch`. Next open a terminal and run the below (edit paths as required);

```
cd ~/.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/dist/server/extensions/
patch -p1 < ~/Downloads/apexMiddleware.js.patch
```

To reverse the patch run:
```
cd ~/.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/dist/server/extensions/
patch -p1 --reverse < ~/Downloads/apexMiddleware.js.patch
```


### Patch
```
--- apexMiddleware.original.js	2023-10-19 15:51:03
+++ apexMiddleware.js	2023-10-20 08:52:14
@@ -35,9 +35,15 @@
       return this.orgRequest
         .get({
           url: `${parsedUrl.pathname}${parsedUrl.search}${parsedUrl.hash}`,
+          // Include headers so we can set cookies.
+          resolveWithFullResponse: true,
         })
         .then((res) => {
-          return Buffer.from(res);
+          // Inject cookies into JSDOM cookie jar.
+          res.headers["set-cookie"]?.map(jsdom_1.toughCookie.parse).map((c) => {
+            this.cookieJar.setCookieSync(c, url);
+          });
+          return Buffer.from(res.body);
         });
     }
     log(`skipped external url: ${url}`);
@@ -189,6 +195,8 @@
   if (response.indexOf("window.location.replace(") != -1) {
     throw new Error("error retrieving aura config: unauthenticated");
   }
+  // Create a cookie jar.
+  const cookieJar = new jsdom_1.CookieJar();
   const resourceLoader = new ApexResourceLoader(
     orgRequest,
     connectionParams.instanceUrl
@@ -197,7 +205,14 @@
     let config = null;
     const Aura = {};
     const oneApp = new jsdom_1.JSDOM(response, {
-      resources: resourceLoader,
+      // Hack to include a reference to the cookie jar when fetching resources
+      // which needs to set cookies.
+      resources: (() => {
+        resourceLoader.cookieJar = cookieJar;
+        return resourceLoader;
+      })(),
+      // Set shared cookie jar.
+      cookieJar: cookieJar,
       runScripts: "dangerously",
       url: connectionParams.instanceUrl + ONE_APP_URL,
       referrer: connectionParams.instanceUrl + ONE_APP_URL,
```

**Comment by UkonGOTO** [comment]
Thanks for the fix/workaround

**Comment by bilal-elchami** [comment]
Hello guys. I just checked my vscode extension pack, it is indeed up to date but the issue is still there. I updated the CLI and the LDS plugin as well. Can anyone confirm that this issue was resolved?

**Comment by andrewwhitten** [comment]
I've updated to @salesforce/cli/2.51.6 darwin-arm64 node-v20.15.0 and still getting the "error retrieving aura config: unauthenticated" message when trying to invoke Apex methods from the Local Dev Server. They seem to work fine when the LWC control is deployed to an org.

I noticed that this issue has been closed, but it seems the only fix made was to the documentation.

Is there any intention to allow LWC components in the Local Dev Server to use Apex methods again in the future?

**Comment by bilal-elchami** [comment]
> future?

I dont think so unfortunately no. I opened a case with the Salesforce support and they were clear about that the local development server is still in Beta and it's not their priority. I lost hope tbh...

**Comment by CristiCanizales** [comment]
Hello everyone, this issue was closed because the current lwc dev server is no longer in maintenance while we wait for the new one that was mentioned in [🔜 Update: Local Development Server Deprecation Notice & Announcement](https://github.com/forcedotcom/salesforcedx-vscode/issues/5501#top). As you can see in the [documentation](https://developer.salesforce.com/docs/platform/sfvscode-extensions/guide/lwclocaldev.html), @AuraEnabled is just not supported in the current one.

**Comment by andrewwhitten** [comment]
Thanks @CristiCanizales - I was actually unaware that the Local Development Server had been deprecated - I think some of us only do LWC development once or twice a year and might miss big changes such as this. Looking forward to whatever is coming in Spring '25!
