### ISSUE TITLE
Experimental Enable Source Tracking  doesn't work after sandbox refresh

### ISSUE THREAD

**Issue by davidchengIC** [forcedotcom/salesforcedx-vscode#5172]
### Summary

I have had the the Experimental Enable Source Tracking setting for many months now.  I refreshed a Developer sandbox on October 9, and now when I use Org Browser to retrieve any object, I get an error "This command can only be used on orgs that have source tracking enabled, such as sandboxes and scratch orgs."

However, the production org has Source Tracking enabled.  The original sandbox had source tracking and the experimental setting worked fine.

I created a new sandbox and I'm able to retrieve items while the Experimental setting is enabled.

### Additional information

_Feel free to attach a screenshot_.

sf version @salesforce/cli/2.13.9 darwin-x64 node-v18.15.0

VS Code CLI extension V 59.0.0

VS Code v 1.83.1

OS X 12.7

**Comment by CristiCanizales** [comment]
Hi @davidchengIC, can you verify that the refreshed sandbox has Source Tracking enabled as well? Or maybe try disabling and re-[enabling in the org](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_setup_enable_source_tracking_sandboxes.htm).

**Comment by davidchengIC** [comment]
I can't refresh the sandbox again because we are working in it.  As I mentioned, when I refreshed it originally, the production instance definitely had Source Tracking enabled.

**Comment by davidchengIC** [comment]
It seems to be working now, I'm not sure what happened.  The SF CLI extension is now at v 59.1.2, so perhaps that was it?
