### ISSUE TITLE
SFDX: Authorize an Org failed to run

### ISSUE THREAD

**Issue by Florent330** [forcedotcom/salesforcedx-vscode#5194]
Hi, 
I'm Windows user and i can no longer deploy with vs code using the "SFDX: Authorize an Org" command. Other commands are also affected, such as "SFDX: Log Out from All Authorized Orgs".
I've tried uninstalling the extensions, then reinstalling them and downgrading, but to no avail. 

I did modify the path : C:\Program Files\Salesforce CLI\bin
It used to work and started to bug about a week or two ago.

Could you please help me? 

My version :

@salesforce/cli/2.14.6 win32-x64 node-v18.15.0

I currently have the following versions: 

@oclif/plugin-autocomplete 2.3.10 (core)
@oclif/plugin-commands 3.0.3 (core)
@oclif/plugin-help 6.0.3 (core)
@oclif/plugin-not-found 3.0.2 (core)
@oclif/plugin-plugins 3.9.2 (core)
@oclif/plugin-search 1.0.3 (core)
@oclif/plugin-update 4.1.2 (core)
@oclif/plugin-version 2.0.3 (core)
@oclif/plugin-warn-if-update-available 3.0.1 (core)
@oclif/plugin-which 3.0.5 (core)
@salesforce/cli 2.14.6 (core)
apex 2.3.20 (core)
auth 2.8.22 (core)
data 2.5.19 (core)
deploy-retrieve 1.19.2 (core)
info 2.6.49 (core)
limits 2.3.39 (core)
login 1.2.37 (core)
marketplace 0.3.0 (core)
org 2.11.4 (core)
schema 2.3.30 (core)
settings 1.4.35 (core)
sobject 0.2.13 (core)
source 2.10.43 (core)
telemetry 2.3.6 (core)
templates 55.5.14 (core)
trust 2.6.20 (core)
user 2.3.37 (core)

Uninstalled JIT Plugins:
community 2.4.6
custom-metadata 2.2.8
dev 1.2.1
devops-center 1.2.3
env 2.2.7
functions 1.22.3
packaging 1.26.4
signups 1.5.5
@salesforce/sfdx-plugin-lwc-test 1.1.0
@salesforce/sfdx-scanner 3.17.0

![logVsCode](https://github.com/forcedotcom/cli/assets/26437397/a4ba72b4-bcfe-4dfc-a601-4841bb779948)

**Comment by cristiand391** [comment]
looks like the extensions are failing to call the CLI, transferred to the vscode extensions repo.

**Comment by AnanyaJha** [comment]
Thanks for reporting this @Florent330 ! Looks like it might be similar to https://github.com/forcedotcom/salesforcedx-vscode/issues/5186 - what do you think @CristiCanizales ?

**Comment by daphne-sfdc** [comment]
Hi @Florent330,
Can you try the following steps?

1. Open up a new Terminal window and type **cd .vscode/extensions**
2. Delete all the previous versions of the Salesforce extensions by running **rm -rf salesforce.salesforcedx-vscode***
3. Reinstall the Salesforce extensions.
4. Clean your cache by deleting the .sfdx and .sf folders from your project, then running "Developer: Reload Window" from the command palette.
5. Try to reauthorize your org.

Let me know if this solves your issue.

**Comment by Florent330** [comment]
Hi @daphne-sfdc , thanks for your help. 
I have this error : 
rm -rf salesforce.salesforcedx-vscode
'rm' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Should I delete extensions directly via vs code rather than using a command?

Best regards

**Comment by daphne-sfdc** [comment]
Hi @Florent330,
Sorry, I forgot that `rm -rf` is a bash-specific command.  Since you're on Windows, use `rmdir /s salesforce.salesforcedx-vscode*` instead.  (Note: I had trouble doing a mass delete using Command Prompt and ended up deleting them one by one, hope your Command Prompt understands mass deletion syntax)

**Comment by Florent330** [comment]
Hi @daphne-sfdc  , 
I followed the steps (except for the mass delete which didn't work, but I found the files to delete them manually).
The problem is still the same.
![errorVsCode1](https://github.com/forcedotcom/salesforcedx-vscode/assets/26437397/63f32f9c-3d38-40c4-8b8c-6903d0c0f9c7)
](url)

**Comment by Florent330** [comment]
Could it be due to an incorrect registration variable, for example? Normally I'd check, but now I'm desperate ^^

**Comment by daphne-sfdc** [comment]
@Florent330
I have several questions for you:
1. Are there any problems in your Problems tab in the bottom panel?
2. What is your VSCode version?
3. Go to your Output tab and select **Salesforce CLI** from the dropdown.  Can you send me what is there?
<img width="641" alt="Screenshot 2023-11-02 at 11 43 22 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/139700604/de604e4a-f376-481d-8d18-92909ce1492a">

**Comment by Florent330** [comment]
@daphne-sfdc :
1 : no problem detected in problem tab 
![VSCodeError4](https://github.com/forcedotcom/salesforcedx-vscode/assets/26437397/40c5c6e2-959b-4132-8a96-0a0cf9ad67e0)

2 : 
![VSCodeError5](https://github.com/forcedotcom/salesforcedx-vscode/assets/26437397/6f7866e9-bf3c-4f1f-9379-a197d9a01ebe)

3 : 
![VSCodeError3](https://github.com/forcedotcom/salesforcedx-vscode/assets/26437397/e6a2905b-e06d-483d-8aa2-b7319ecd8db8)

**Comment by daphne-sfdc** [comment]
What's interesting is that you said you were using SF v2.14.6 CLI, but your screenshot says you are using SFDX v7.209.6 CLI.  It seems like you didn't uninstall SFDX before installing SF.  I would uninstall both CLI versions and reinstall only SF v2, either 2.14.6 or whichever is the latest version.

**Comment by Florent330** [comment]
OMG it works! In fact it was blocking because it seems I had two versions if I understood correctly. I don't know how to thank you, but thank you very much! Have good day ! You're the best !

**Comment by daphne-sfdc** [comment]
@Florent330 I'm so glad I was able to unblock you.  Yes, it was blocking because you had two versions - during the migration from SFDX v7 to SF v2, users are supposed to first uninstall SFDX v7 because SF v2 maps the `sf` command to `sfdx` and covers both. 🙂
