### ISSUE TITLE
Error running command sfdx.force.test.view.refresh: command 'sfdx.force.test.view.refresh' not found. This is likely caused by the extension that contributes sfdx.force.test.view.refresh.

### ISSUE THREAD

**Issue by bishwambharsen** [forcedotcom/salesforcedx-vscode#5198]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. Open an sfdx project in VS Code. 
2. Click on the tests menu on the left hand side.
3. Apex test should be visible

### Expected result

Tests should be visible and you should be able to run tests

### Actual result

Tests NOT visible. Upon hitting the refresh button we get this error 
Error running command sfdx.force.test.view.refresh: command 'sfdx.force.test.view.refresh' not found. This is likely caused by the extension that contributes sfdx.force.test.view.refresh.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:v59.1.2

**SFDX CLI Version**:@salesforce/cli/2.14.6 win32-x64 node-v21.1.0

**OS and version**: Windows 10 Enterprise OS Build 19044.3570

**VS Code version**:1.83.1

java version 
openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Microsoft-6841604 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-6841604 (build 17.0.5+8-LTS, mixed mode, sharing)

**Comment by daphne-sfdc** [comment]
Hi @bishwambharsen,
It looks like something is wrong with your Apex extension, given this error message and the one you commented on in #5192.  I would try getting the Apex extension in a very clean state using the same steps that I posted in that issue.

I copied the steps over:
1. Open up a new Terminal window and type **cd .vscode/extensions**
2. Delete all the previous versions of the Salesforce extensions by running **rm -rf salesforce.salesforcedx-vscode***
3. Reinstall the Salesforce extensions.
4. Clean your cache by deleting the .sfdx and .sf folders from your project, then running "Developer: Reload Window" from the command palette.
5. Try to reauthorize your org.

Let me know if you're still facing this issue after doing the extension reset.

**Comment by bishwambharsen** [comment]
@daphne-sfdc you are a life saver. I followed your instructions to the dot and it fixed my problem. The Testing panel is now loaded with the apex tests. Thank you so much. I was struggling since the last 2 days but finally I have it working all thanks to you (y)

**Comment by daphne-sfdc** [comment]
@bishwambharsen Thanks for confirming!  I'm very happy I was able to help. 🙂

**Comment by shabbanishaik** [comment]
Excellent.Resolved my issue.Thanks a lot  :-)
