### ISSUE TITLE
Apex class can't be compiled using sfdx 

### ISSUE THREAD

**Issue by Shokhan** [forcedotcom/salesforcedx-vscode#520]
When working with this extension and sfdx I get an "An unexpected error occurred. Please include this ErrorId if you contact support: 654765986-26458 (-1629536643)" with different error codes. But when I open Developer console and save changes there everything is OK. Helps only creation of new scratch org, but after several saves happens again.

Is it some VS code configuration issue?

**Comment by ntotten** [comment]
@Shokhan I think we will need a bit more information on this. Can you please provide the following:

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:
