### ISSUE TITLE
VS Code Salesforce CLI taking too long to retrieve/deploy metadata

### ISSUE THREAD

**Issue by TejaswiniIncap** [forcedotcom/salesforcedx-vscode#5211]
VS Code Salesforce CLI taking too long to retrieve/deploy metadata. Retrieving one class takes around 15-20mins. We have been observing this issue for past 2-2.5 weeks now. This probably started happening after the new Salesforce extension release was published. It worked alright for some 30mins after the update but then it started to behave in the same manner after 30mins.  THIS IS A MAJOR BLOCKER FOR US. Not sure if the issue is with the Salesforce CLI extension or VS Code itself.

### Steps To Reproduce:

1.  set a default salesforce org in VS Code
2.  Retrieve any metadata from the org.

**### Expected result**

The metadata should get retrieved within few seconds

**### Actual result**

It takes more than 20-30mins to retrieve couple of component metadata from the Org

**### Additional information**

I am currently on the below Salesforce CLI version-

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/90377637/d2f90c8b-711b-4085-9467-e26c866a610d)

**Salesforce Extension Version in VS Code**: v59.3.1

**SFDX CLI Version**: v59.3.1

**OS and version**: Windows i7 Core

**VS Code version**: 1.86

**Comment by daphne-sfdc** [comment]
Hi @TejaswiniIncap, We are aware of this issue and have been tracking it at https://github.com/forcedotcom/salesforcedx-vscode/issues/4865.  I'll close this issue as a duplicate.  Please try the workarounds we provided in that thread and let us know if you're still experiencing any problems.  Thanks.

**Comment by diyer** [comment]
Hi @TejaswiniIncap, we're excited to let you know the latest version of our extensions 59.5.1 is released and we have attempted to fix this issue in our latest release. Please give the latest version a try and let us know if this addresses your concerns. We appreciate your feedback and patience! Happy exploring!

cc: @AnanyaJha @gbockus-sf
