### ISSUE TITLE
Missing dependency on `jest-environment-jsdom` in default generated `package.json`

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/salesforcedx-vscode#5239]
I'm not sure if this is a valid bug to open, but since it's a change in behavior I figured I'd log it and you all can decide how to disposition it (if at all).

In the past, the Jest dependencies in the `package.json` for a newly-created project have been sufficient to run Jest tests. However, now I'm seeing an issue where evidently `jest-environment-jsdom` is no longer bundled. I've seen this manifest in a couple of ways:

```
TypeError: Cannot read properties of undefined (reading 'html') at new JSDOMEnvironment
```

and:

```
Test environment jest-environment-jsdom cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

Configuration Documentation:
https://jestjs.io/docs/configuration

As of Jest 28 "jest-environment-jsdom" is no longer shipped by default, make sure to install it separately.
```

This problem is resolved for me by adding an explicit dependency on `jest-environment-jsdom` alongside the other Jest `devDependencies` in the project's `package.json` file.

It's possible(/likely?) that the scaffolding added around test execution via the CLI and/or VS Code takes care of this, but I ran into it when trying to execute Jest tests via a commercial JetBrains IDE and its native Jest test framework support.

Again, this seems to be a behavioral change vs. the (recent?) past. If it's not something that should be fixed in the default `package.json` for a newly-created project for some reason, just let me know that and I'll have IC2 update the that file as needed to ensure that things work without requiring a manual edit. Thanks!

**Comment by peternhale** [comment]
@SCWells72 would you mind providing the requested information listed above, including the commands you are using to create your project and the version of vscode  and Salesforce extensions being used.

**Comment by peternhale** [comment]
@SCWells72 This is a bug with deps in project generation.

As a workaround you can bump dev dep @salesforce/sfdx-lwc-jest to latest, which will pull in jest 29 and the missing jdom jest module.

**Comment by daphne-sfdc** [comment]
Closing this issue as completed as the PR has already been merged and released.
