### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by aminerochdi1** [forcedotcom/salesforcedx-vscode#5242]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `59.5.1`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.71.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by peternhale** [comment]
@aminerochdi1 Would you mind describing the issue you are reporting?

**Comment by daphne-sfdc** [comment]
Hi @aminerochdi1, We have not received your response to this issue in the past week, so I'm going to assume it has been resolved and close it as completed.  Feel free to reopen if not the case.

**Comment by aminerochdi1** [comment]
Hello ,  sorry for late answer , the issue was my salesforce cli wasn't communicating with the salesforcedx-vscode-core , I linked the cli api with my salesforce account but the commands wasn't working

**Comment by daphne-sfdc** [comment]
@aminerochdi1 So the problem is resolved and this issue can be kept in the Closed state, correct?  Just want to make sure I understood your message correctly.

**Comment by aminerochdi1** [comment]
yes absolutely , Thanks for the assistance
