### ISSUE TITLE
Errors returned from Force Source Deploy are set with root in front of the path

### ISSUE THREAD

**Issue by qwikag** [forcedotcom/salesforcedx-vscode#5249]
### Summary

Force:Source:Deploy is returning problems to the problem log of VSCode
but the path of the errored file has an extra Slash "/" causing it to be located at root and not within the project folder.
Other extensions experience the same issue but VSCode refers everyone back to the extension provider.
PMD does not cause this error its problem are just fine

### Steps To Reproduce:

1.  Deploy using right click deploy to org, a piece of code with purposeful apex errors.
1.  Problem is logged in the problems section
1.  Click on any of the issues
1.  The file tries to open but because of the extra forward slash it cannot and returns this error
1.  [The editor could not be opened because the file was not found](https://salesforce.stackexchange.com/questions/377152/problems-are-returning-errors-linking-to-incorrect-file-locations-giving-the-e)

### Expected result

File is already open but the editor moves the the row in question, and /or the file opens.

### Actual result

Just get the above error as seen here
[The editor could not be opened because the file was not found](https://salesforce.stackexchange.com/questions/377152/problems-are-returning-errors-linking-to-incorrect-file-locations-giving-the-e)

### Additional information
![image](https://user-images.githubusercontent.com/5670636/170822640-02b1da85-3642-417d-8168-cad002700dc6.png)
![image](https://user-images.githubusercontent.com/5670636/170822657-13caf5bd-d7b6-45ac-a561-bdd4de09bed7.png)
![image](https://user-images.githubusercontent.com/5670636/170822663-c3810766-75e8-445e-bc8b-3a9c365c9d3b.png)

**SFDX CLI Version**
sfdx-cli/7.152.0 darwin-x64 node-v16.15.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.0 (core)
apex 0.12.0 (core)
auth 2.0.2 (core)
community 1.1.4 (core)
config 1.4.6 (core)
custom-metadata 1.1.0 (core)
data 2.0.0 (core)
generator 2.0.1 (core)
info 2.0.0 (core)
limits 2.0.0 (core)
org 1.13.1 (core)
salesforce-alm 54.4.0 (core)
schema 2.1.0 (core)
sfdx-cli 7.152.0 (core)
signups 1.1.1 (core)
source 1.9.9 (core)
telemetry 2.0.0 (core)
templates 54.7.0 (core)
trust 1.1.0 (core)
user 2.0.0 (core)

**OS and version**:
MACOS
12.3.1 (21E258)

**Comment by diyer** [comment]
Closing this old bug. Please use our latest vs code extension version and open a new issue if it still persists. Thank you
