### ISSUE TITLE
SFDX unable to authorize org Warning: org:login:web is not a sfdx command.

### ISSUE THREAD

**Issue by rhennen1023** [forcedotcom/salesforcedx-vscode#5259]
Type: <b>Performance Issue</b>

After reinstalling the full Salesforce Extension Pack (Expanded), went to run SFDX: Authorize an Org and still received the same message I was getting beforehand...
Warning: org:login:web is not a sfdx command.

Extension version: 59.7.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (3.93GB free)|
|Process Argv|--crash-reporter-id 24fed0a3-eedb-48b1-a76a-a62d2364c00e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	 22172	code main
    0	    41	  3196	   utility-network-service
    0	    28	  5180	   crashpad-handler
    0	   207	  6020	window [1] (Extension: Salesforce Extension Pack (Expanded) - QueryMetadataSTFull2 - Visual Studio Code)
    0	   341	 12788	extensionHost [1]
    0	    95	  8980	     electron-nodejs ("C:\Users\rhennen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rhennen\.vscode\extensions\salesforce.salesforcedx-vscode-visualforce-59.7.0\dist\visualforceServer.js --node-ipc --clientProcessId=12788)
    0	    87	 12332	     electron-nodejs ("C:\Users\rhennen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rhennen\.vscode\extensions\gitlab.gitlab-workflow-3.90.1\assets\language-server\node\main-bundle.js --stdio --clientProcessId=12788)
    0	   104	 19172	     electron-nodejs ("C:\Users\rhennen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rhennen\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-59.7.0\node_modules\@salesforce\lwc-language-server\lib\server.js --node-ipc --clientProcessId=12788)
    0	   106	 21260	     electron-nodejs ("C:\Users\rhennen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rhennen\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-59.7.0\node_modules\@salesforce\aura-language-server\lib\server.js --node-ipc --clientProcessId=12788)
    0	    31	 21888	     c:\Users\rhennen\.vscode\extensions\redhat.vscode-xml-0.26.1-win32-x64\server\lemminx-win32.exe ""
    0	    11	 16728	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    94	 17024	window [2] (Issue Reporter)
    0	    74	 19108	fileWatcher [1]
    0	    95	 20628	shared-process
    0	    88	 20880	   window
    2	   167	 22248	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Salesforce Extension Pack (Expanded) - QueryMetadataSTFull2 - Visual Studio Code)
|    Folder (QueryMetadataSTFull2): 164 files
|      File types: json(42) ts(25) xml(25) cls(19) eslintignore(1)
|                  forceignore(1) gitignore(1) prettierignore(1)
|                  prettierrc(1) js(1)
|      Conf files: launch.json(1) settings.json(1) jsconfig.json(1)
|                  package.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by CristiCanizales** [comment]
Hello @rhennen1023, can you tell me what's your CLI version? I believe you have an old one. If so, can you try updating and tell me if it works?

**Comment by rhennen1023** [comment]
I'm on CLI version 59.7.0

**Comment by rhennen1023** [comment]
I'm a total newbie to this tool, can you direct me to instructions on how to run this?

**Comment by CristiCanizales** [comment]
@rhennen1023 sure! 
First, just open your terminal on vscode (You can use the command palette for that: `Command + Shift + P > Type Terminal: Focus on Terminal View`) 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/b7960d6c-80a5-4045-a1d6-4f1c0315b18a)
Then, type '`sf version`' and hit enter and type '`sfdx version`' and hit enter again as shown below
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/b794735f-7204-4f69-b0cc-89d6bec7e186)

Then just send me what you get 🙂

**Comment by rhennen1023** [comment]
for sf version: @salesforce/cli/1.54.1 win32-x64 node-v18.12.0

for sfdx version: sfdx-cli/7.177.1 win32-x64 node-v18.12.0

**Comment by CristiCanizales** [comment]
@rhennen1023 Thanks! can you try updating now?
Just run `sfdx update` on your terminal

**Comment by rhennen1023** [comment]
Thank you @CristiCanizales, that solved it!
