### ISSUE TITLE
ORG Browser is not working although the authorisation works correctly

### ISSUE THREAD

**Issue by mateus-os** [forcedotcom/salesforcedx-vscode#5261]
Type: <b>Bug</b>

I already have a proper connection to the org without errors, but the ORG browser extension shows an error message: 'Error fetching metadata for the org. Run "SFDX: Authorize an Org" to authorize your org again.'

![image_7](https://github.com/forcedotcom/salesforcedx-vscode/assets/52670742/a2eb4022-3983-4446-b09e-dfaf46c034f6)

![image_9](https://github.com/forcedotcom/salesforcedx-vscode/assets/52670742/46a1f357-11dd-47fe-b735-a769cd95a8d3)

PS: For security reasons, my organisation blocks PowerShell

Extension version: 59.7.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22631
CLI: @salesforce/cli/2.19.8 win32-x64 node-v20.9.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (2.93GB free)|
|Process Argv|--crash-reporter-id 4128a013-fa1c-488c-b850-73f11ec9f16b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
![image_8](https://github.com/forcedotcom/salesforcedx-vscode/assets/52670742/d2f7de23-ecc6-418f-b9d4-1796d29366d5)

vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by CristiCanizales** [comment]
hi @mateus-os, can you try deleting `.sf`/`.sfdx `folders, reload VS Code, authorize again, refresh Org Browser and check if the issue persists?

**Comment by mateus-os** [comment]
Hi @CristiCanizales, 
I deleted the folders, reopened VS Code, reauthorized the ORG, and refreshed the ORG Browser again. It still displays the same error message
 
![WhatsApp Image 2023-12-06 at 18 09 34_43d35200](https://github.com/forcedotcom/salesforcedx-vscode/assets/52670742/0421cc46-ff61-4980-89ce-fc13b1d96187)

**Comment by CristiCanizales** [comment]
Hi @mateus-os, could you check if it's working now? There was a change in the metadata api and we'd like to verify if it was related to this

**Comment by mingxuanzhangsfdx** [comment]
Hi @mateus-os , could you try to 

1. Open up a new Terminal window and type cd .vscode/extensions (or cd %USERPROFILE%\.vscode\extensions in Windows)
2. Delete all the previous versions of the Salesforce extensions by running rm -rf salesforce.salesforcedx-vscode* (or equivalent command in windows - rmdir /s /q salesforce.salesforcedx-vscode*)
3. Reinstall the Salesforce extensions.
4. Clean your cache by deleting the .sfdx and .sf folders from your project, then running "Developer: Reload Window" from the command palette.
5. Try to reauthorize your org.

And let us know if there is any info in the output panel and developer tools. Thank you!

**Comment by mateus-os** [comment]
Hi @mingxuanzhangsfdx I followed all the steps. When I reauthorized, it showed me an error message `SFDX: Authorize an Org failed to run`. However, the connection was established correctly and worked with CMD CLI commands. Additionally, VSCode commands such as Retrieve and Deploy work well too

Console error:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52670742/a22ccbe9-aba5-4d93-ae06-a262e45884b9)

Code snippet:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52670742/6d6d2620-6d03-468f-a737-9ac650eabe1e)

PS: The ORG Browser is still not working and is displaying the same message.

**Comment by mingxuanzhangsfdx** [comment]
Hi @mateus-os thanks for the try. I doubt this could be something wrong with the authorization. could you try to use sf to log in instead by following the instruction [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_flow.htm)? And tell us the results and any errors. Thank you!
