### ISSUE TITLE
SFDX: Open Default Org failed to run

### ISSUE THREAD

**Issue by Trump2020forE** [forcedotcom/salesforcedx-vscode#5265]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

![Screenshot 2023-12-08 085043](https://github.com/forcedotcom/salesforcedx-vscode/assets/75489985/73fbc958-a331-439c-a7f9-9545f2e8386a)

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by CristiCanizales** [comment]
Hi @Trump2020forE, can you try going to `C:\Users\antor\AppData\Local` and delete that `sfdx` folder? Then just try again

**Comment by CristiCanizales** [comment]
Related issue https://github.com/forcedotcom/cli/issues/2447
