### ISSUE TITLE
Unable to install Extension pack

### ISSUE THREAD

**Issue by sfsagar** [forcedotcom/salesforcedx-vscode#5296]
Installed VS code,Salseforce CLI,then extension pack but not able to install extension
![Screenshot 2023-12-27 031443](https://github.com/forcedotcom/salesforcedx-vscode/assets/97340699/fec41a7e-b273-483f-b077-ed0ac1a82b55)
![Screenshot 2023-12-27 034204](https://github.com/forcedotcom/salesforcedx-vscode/assets/97340699/17e2691c-48c9-476f-8e78-b5a7517cc7a4)

**Comment by CristiCanizales** [comment]
Hi @sfsagar, do you get the same error when installing the expanded version? (`Salesforce Extension Pack (Expanded)`).
Also, can you try restarting VS Code and then installing again?
And please provide all the details asked in the issue template:
- **SFDX CLI Version**
- **OS and version**
- **VS Code version**

**Comment by sfsagar** [comment]
Thank you for your response.
