### ISSUE TITLE
sfdx

### ISSUE THREAD

**Issue by ANJALK11** [forcedotcom/salesforcedx-vscode#5306]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by ANJALK11** [comment]
how to run in vscode in salesforce company sfdx

**Comment by daphne-sfdc** [comment]
Hi @ANJALK11,
VSCode is not bundled with Salesforce's CRM product - you need to install it yourself.  Please refer to https://developer.salesforce.com/tools/vscode for our documentation.

**Comment by daphne-sfdc** [comment]
Hi @ANJALK11,
I'm going to close this issue.  Feel free to reopen if you have more questions.
