### ISSUE TITLE
Apex Language Server does not support methods in anon-apex

### ISSUE THREAD

**Issue by przemekrcloudity** [forcedotcom/salesforcedx-vscode#5312]
### Summary

_Short summary of what is going on or to provide context_.

In anonymous apex scripts, defined functions aren't auto-completed. For example in code
```apex
String key(Integer x, Integer y) {
    return x + '  ' + y;
}

System.debug(key(10, 10));
```
method `key` is not autocompleted.

Whats more, parameters are not visible inside function, which means that autocompletion for both these parameters and theirs methods and properties is not working.
Variables defined inside method are visible though.

| Parameters autocompletion | Variables autocompletion |
| :-- | :-- |
| ![issue_with_anon_apex_1](https://github.com/forcedotcom/salesforcedx-vscode/assets/95613238/a7e9ee99-0e55-43ae-9359-8c87d950b9cf)  | ![issue_with_anon_apex_2](https://github.com/forcedotcom/salesforcedx-vscode/assets/95613238/51829f38-d5af-4554-b5f5-0af86039c0b4) |

### Steps To Reproduce:

1. Create apex script file
1. Define any method in said script
1. Start typing defined method name
1. See that method is not on autocompletion list

### Expected result

In annonymous apex scripts, I would like to have methods that were defined to be inculded in autocompletion.
In anonymous apex script, I would also like to have parameters included in autocompletion inside method.

### Actual result

Methods defined in apex scripts are not visibible for autocompletion mechanism.
Whats more, in method definition parameters are not inculded in autocompletion list

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:
```
74th.monokai-charcoal-high-contrast@3.4.0
atlassian.atlascode@3.0.3
bierner.markdown-mermaid@1.21.0
chuckjonas.apex-pmd@0.5.9
dbaeumer.vscode-eslint@2.4.0
eamodio.gitlens@13.6.0
esbenp.prettier-vscode@9.12.0
FinancialForce.lana@1.5.2
GrapeCity.gc-excelviewer@4.2.58
Gruntfuggly.todo-tree@0.0.226
mechatroner.rainbow-csv@3.7.0
mhutchie.git-graph@1.30.0
ms-azuretools.vscode-docker@1.25.1
ms-python.isort@2022.8.0
ms-python.python@2023.8.0
ms-python.vscode-pylance@2023.5.20
ms-vscode.live-server@0.4.8
NicolasVuillamy.vscode-sfdx-hardis@1.33.0
redhat.vscode-xml@0.25.2023051704
redhat.vscode-yaml@1.12.2
salesforce.salesforce-vscode-slds@1.4.8
salesforce.salesforcedx-vscode@56.16.0
salesforce.salesforcedx-vscode-apex@57.13.1
salesforce.salesforcedx-vscode-apex-debugger@57.13.1
salesforce.salesforcedx-vscode-apex-replay-debugger@57.13.1
salesforce.salesforcedx-vscode-core@57.6.0
salesforce.salesforcedx-vscode-expanded@57.13.1
salesforce.salesforcedx-vscode-lightning@57.13.1
salesforce.salesforcedx-vscode-lwc@54.5.0
salesforce.salesforcedx-vscode-soql@57.13.1
salesforce.salesforcedx-vscode-visualforce@58.6.2
SmithChayse92.dark-colored-theme@1.0.7
SonarSource.sonarlint-vscode@3.18.0
streetsidesoftware.code-spell-checker@2.20.4
ToddHalfpenny.sfflowvisualiser@0.2.2
VignaeshRamA.sfdx-package-xml-generator@2.0.10
vscodevim.vim@1.25.2
zhuangtongfa.material-theme@3.15.13
Zignd.html-css-class-completion@1.20.0
```

**SFDX CLI Version**: @salesforce/cli/2.11.8 linux-x64 node-v16.16.0

**OS and version**: Linux 20.04.1-Ubuntu UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**VS Code version**: 1.85.1

**Comment by daphne-sfdc** [comment]
Hi @przemekrcloudity, I see that you're on a very old version of the Salesforce extensions.  Our latest available version is v59.9.0.  Is it possible for you to update your extensions to the latest version?

Here are the steps to update the extensions:
1. In your Terminal, go to your home directory and `cd .vscode/extensions`
2. `rmdir salesforce.salesforcedx-vscode*` to remove all Salesforce extensions
4. Quit VSCode and restart
5. Reinstall the Salesforce Extension Pack and confirm you have v59.9.0

After doing the update, please try the autocompletion again and let me know if the issue is resolved.

**Comment by przemekrcloudity** [comment]
Issue was not resolved after updating extension pack to `salesforce.salesforcedx-vscode-expanded` to version `v59.9.0`

![anon-apex-problems](https://github.com/forcedotcom/salesforcedx-vscode/assets/95613238/5d94f10d-6a71-4954-b013-824b276bebc7)

**Comment by mingxuanzhangsfdx** [comment]
Hi @przemekrcloudity , thank you for taking the time to report this issue. We greatly appreciate your engagement and effort to improve our project.

After reviewing the details you've provided above, it appears that the behavior you encountered has actually been what it was for a long time.

However, we understand that this feature might not meet everyone's needs or expectations. If you believe that this feature could be enhanced or if you have suggestions for new functionality that would better suit your use case, we warmly encourage you to submit a feature request.

To submit a feature request, please:

1. Go to our GitHub repository's 'Issues' section.
2. Click on 'New Issue' to create a new issue.
3. Choose the 'Feature Request' template (if available) or simply title your issue as 'Feature Request: [Brief Description of Feature]'.
4. Provide a detailed description of the feature you'd like to see, including any specific functionality and use cases it would address.

Your insights and suggestions are valuable to us, and we are always looking for ways to improve our project to better serve the needs of our users.

Again, thank you for your contribution, and we look forward to your continued involvement in our project.

**Comment by przemekrcloudity** [comment]
Thanks for the response! I don't think that it is possible for me to fix this ticket myself as apex language server is in binary form (#305).

> After reviewing the details you've provided above, it appears that the behavior you encountered has actually been what it was for a long time.
> 
> However, we understand that this feature might not meet everyone's needs or expectations. 

Does this mean that the way autocompletion works now is how it should work and this ticket wont be worked on and this issue should be closed?
