### ISSUE TITLE
Unable to Deploy or retrieve data/files from the org through entension or command.

### ISSUE THREAD

**Issue by tanmayythakur** [forcedotcom/salesforcedx-vscode#5314]
### Summary

* This is happening from 3rd January.
* For my authorized org for a given project, when I right click on my project/lwc/apex class, and select Deploy source to org, a pop up comes up stating that the command is running but it keeps running forever but nothing gets deployed. 

### Steps To Reproduce:

1.  Authorize an org.
1.  Right click any component/project that you wish to deploy and click `SFDX : Deploy source to org`. 
1. The pop up comes us saying `Running SFDX: Deploy Source to Org` and it run forever.
1. In the command-line output as well, it doesn't indicates that the deployment has started but it is in pending state for a long time.

### Expected result

It should deploy my selected changes to my authorized org.

### Actual result

The command/action hangs and runs forever and nothing gets deployed.

### Additional i
![Screenshot 2024-01-04 at 2 07 05 PM](https://github.com/forcedotcom/salesforcedx-vscode/assets/152280816/5c011707-131f-4025-b2ef-a6f254b7f12e)
nformation

**Salesforce Extension Version in VS Code**: `v59.9.0`

**SFDX CLI Version**: `@salesforce/cli/2.22.7`

**OS and version**: macOS and 14.2.1 (23C71)

**VS Code version**: 1.85.1 (Universal)

**Comment by diyer** [comment]
@tanmayythakur were you able to try the workarounds? Please let us know!

**Comment by tanmayythakur** [comment]
@diyer   the issue got fixed for me and I'm unblocked on this.

**Comment by HariChandana972** [comment]
Hello Team, I'm also facing the same issue. Could anyone suggest the workaround?

**Comment by daphne-sfdc** [comment]
Hi @HariChandana972, Please take a look at https://github.com/forcedotcom/salesforcedx-vscode/issues/4865 for a list of workarounds.
