### ISSUE TITLE
unable to activate Apex language Server 

### ISSUE THREAD

**Issue by naik0069** [forcedotcom/salesforcedx-vscode#5322]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/108566555/f3319a6c-1904-4238-bcee-04aa6f036680)

getting error as unable to activate apex language server even updated Java using. Please assist

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/108566555/d5db41e0-1fe0-4ace-86a1-ba4e58ad9f45)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/108566555/21659fa0-4878-4809-afba-69c70f38bd9a)

**Comment by daphne-sfdc** [comment]
Hi @naik0069,
Set the value in the box to just `C:\Program Files\Java\jdk-17`.  What you currently put is the value that should automatically be populated in `settings.json` when you do that.

**Comment by naik0069** [comment]
Thank you
