### ISSUE TITLE
ISV Debugger throws error 'Your project configuration is invalid or incomplete for ISV debugging'

### ISSUE THREAD

**Issue by aljaz823** [forcedotcom/salesforcedx-vscode#5324]
### Summary

After following the instructions on setting up the [ISV Apex Debugger](https://developer.salesforce.com/tools/vscode/en/apex/isv-debugger#isv-customer-debugger-considerations), running the Apex Debugger throws an error saying:
```
Your project configuration is invalid or incomplete for ISV debugging.
Return to the Apex Debugger page in Setup, start a new partner debugging session, and try again.
```

### Steps To Reproduce:

1. Grant login access from the subscriber sandbox
1. Login to the subscriber org from the ISV org
1. Go to Setup -> Apex Debugger -> Start Partner Debugging Session and copy the url
1. Go to VS Code -> SFDX: Create and Set Up Project for ISV Debugging and paste the above url
1. On completion, new VS Code window opens
1. Run the default launch configuration from launch.json to run the Apex Debugger

### Expected result

Successful and active Apex Debugger session.

### Actual result

An error is thrown saying:
```
Your project configuration is invalid or incomplete for ISV debugging.
Return to the Apex Debugger page in Setup, start a new partner debugging session, and try again.
```

### Additional information

<img width="1031" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/17474533/31baa76f-7924-464e-a50e-5629f38f4dca">

**Salesforce Extension Version in VS Code**: v59.9.0

**SFDX CLI Version**: @salesforce/cli/2.21.8 darwin-arm64 node-v20.10.0

**OS and version**: macOS Sonoma 14.1.2 (23B92)

**VS Code version**: 1.85.1

**Comment by mingxuanzhangsfdx** [comment]
HI @aljaz823 , thanks for reporting this issue. We are aware of this issue and actively looking into this. We will let you know when we have an update.

**Comment by JanuszWdowka** [comment]
Hi any updates about this bug? ISV Debugger is very usefull

**Comment by daphne-sfdc** [comment]
Hi @JanuszWdowka, You asked for and update just in time - we actually have a PR open with a fix for this issue now! https://github.com/forcedotcom/salesforcedx-vscode/pull/5522 😁

**Comment by daphne-sfdc** [comment]
Closing this issue because https://github.com/forcedotcom/salesforcedx-vscode/pull/5522 has been merged and released.
