### ISSUE TITLE
Package xml generator extn ends up in error

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/salesforcedx-vscode#5330]
### Summary

Opening Package xml generator extn ends in error 'The system cannot find the path specified.'

### Steps To Reproduce:

1.  Open Package xml generator extn in VS Code

### Expected result

When I type metadata type, it will be automatically listed
### Actual result

Nothing happened

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/10748642/04dbe4d1-3a73-4553-9dcc-4f5384068ddb)

**Salesforce Extension Version in VS Code**: v59.9.0

**Comment by peternhale** [comment]
@shabu74 the [Salesforce package.xml Generator](https://marketplace.visualstudio.com/items?itemName=VignaeshRamA.sfdx-package-xml-generator) is owned by Salesforce. Please direct your issue to the extension's [issues](https://github.com/vignaesh01/sfdx-package-generator/issues) page.
