### ISSUE TITLE
You have both SFDX(v7) and SF(v2) of Salesforce CLI installed

### ISSUE THREAD

**Issue by pogilvieCB** [forcedotcom/salesforcedx-vscode#5333]
### Summary

After updating to version: v59.13.0
of extension: Salesforce CLI Integration for Visual Studio Code

I'm getting the following error:

```
You have both SFDX(v7) and SF(v2) of Salesforce CLI installed. Uninstall SFDX(v7) by running `npm uninstall sfdx-cli --global` in your terminal.
```

I've run the suggested command and deleted every trace of sfdx that I can find.

### Steps To Reproduce:

1.  remove all local installations of sfdx
1.  start vscode in a salesforce project
### Expected result

Salesforce extensions should start up with vscode in a salesforce project

_Describe what should have happened_.

### Actual result

I get the error 

```
You have both SFDX(v7) and SF(v2) of Salesforce CLI installed. Uninstall SFDX(v7) by running `npm uninstall sfdx-cli --global` in your terminal.
```

Even after I delete sfdx.    I've deleted the the npm global installed, the local install in /usr/local.   I've deleted ~/.sfdx and my project ~/.sfdx direcotires.

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:
none I have sf installed
sf --version
@salesforce/cli/2.23.20 darwin-arm64 node-v20.10.0

**OS and version**:
Macos
Darwin T9RXD334KM 23.2.0 Darwin Kernel Version 23.2.0
**VS Code version**:
Version: 1.85.1

**Comment by daphne-sfdc** [comment]
Can you run `sfdx --version` and send me the result?  The term `sfdx` is supposed to map to the term `sf` if your CLI is configured correctly, so I'd like to confirm that `sfdx --version` and `sf --version` produce the same result.

**Comment by pogilvieCB** [comment]
Oh I deleted sfdx thinking that would help.  Thank you for the suggestion!

**Comment by daphne-sfdc** [comment]
Good to know that I was able to help resolve your issue, and you now have a good configuration of Salesforce CLI 🙂 

Closing this issue as completed ✅

**Comment by pogilvieCB** [comment]
Thank you! I'll try it out!

**Comment by diyer** [comment]
Hi @pogilvieCB, are you able to run with the latest version of extensions without this error now?
