### ISSUE TITLE
Error in File Paths with `sf project deploy validate --coverage-formatters`

### ISSUE THREAD

**Issue by Alfystar** [forcedotcom/salesforcedx-vscode#5337]
While using the `sf project deploy validate command --coverage-formatters <any formatter>` option, I observed unexpected behavior in the file path reported in the code coverage results.
Specifically, all paths are in the form of *"no-map/Apex Class Name"* instead of following the expected complete path structure like *"path/to/apexClass.cls"*

**Environment:**

Salesforce CLI version: 2.17.14
Operating system: Mac OS
Development environment: sandbox

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.23.20",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 23.2.0",
  "rootPath": "/Users/ea_enel/.local/share/sf/client/2.23.20-50cd2d8",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.4 (core)",
    "@oclif/plugin-commands 3.1.0 (core)",
    "@oclif/plugin-help 6.0.9 (core)",
    "@oclif/plugin-not-found 3.0.7 (core)",
    "@oclif/plugin-plugins 4.1.14 (core)",
    "@oclif/plugin-search 1.0.10 (core)",
    "@oclif/plugin-update 4.1.7 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.8 (core)",
    "@oclif/plugin-which 3.0.14 (core)",
    "@salesforce/cli 2.23.20 (core)",
    "apex 3.0.14 (core)",
    "auth 3.1.0 (core)",
    "data 3.0.13 (core)",
    "deploy-retrieve 2.2.12 (core)",
    "info 3.0.13 (core)",
    "limits 3.1.0 (core)",
    "marketplace 1.0.15 (core)",
    "org 3.2.0 (core)",
    "packaging 2.0.1 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.14 (core)",
    "sobject 1.0.7 (core)",
    "source 3.0.10 (core)",
    "telemetry 3.1.8 (core)",
    "templates 56.0.8 (core)",
    "trust 3.2.5 (core)",
    "user 3.2.0 (core)",
    "sfdx-plugin-source-read 1.2.0 (user)"
  ]
}
```

**Steps to Reproduce:**

Execute the sf project deploy validate command with the --coverage-formatters option.
Analyze the code coverage results.
Expected Behavior:
I would expect the file path in the code coverage results to follow the complete path structure of the apexClass, for example, "path/to/apexClass.cls."

**Observed Behavior:**
The file path reported in the code coverage results is in the form of "no-map/Apex Class Name."
```json
"no-map/Constants": {
    "lines": {
        "total": 36,
        "covered": 36,
        "skipped": 0,
        "pct": 100
    },
    "functions": {
        "total": 0,
        "covered": 0,
        "skipped": 0,
        "pct": 100
    },
    "statements": {
        "total": 36,
        "covered": 36,
        "skipped": 0,
        "pct": 100
    },
    "branches": {
        "total": 0,
        "covered": 0,
        "skipped": 0,
        "pct": 100
    }
}
```

**Project Configuration:**

Project directory: `"src/main/default/classes/Constants.cls"`

**Request for Clarification on Coverage Metrics:**

Additionally, I would like to seek clarification on the meaning of the following keys within the`coverage-summary.json` file:

- "functions"
- "statements"
- "branches"

I would like a better understanding of the specific meaning of each of these metrics and how they are calculated in the context of code coverage. What are the definitions of "functions," "statements," and "branches" in this context? How do they impact the overall evaluation of code coverage?

Thank you for your cooperation.
I hope to receive a response soon
Emanuele

**Comment by peternhale** [comment]
@Alfystar The presence of the properties `functions`, `statements` and `branches` is an artifact of producing well known report formats, which typically have these sections, plus `lines`. Unfortunately, Apex coverage data only includes line coverage data. In filling out the above sections, we chose to set `functions` and `branches` to the values you see, basically no coverage, but with percentage at 100%, so not to upset any external reporting system, such as clover or codecov.io.

We also chose to make `lines` and `statements` equivalent.

I hope this helps your understanding of that data present when using coverage from tests run during deploy.

**Comment by Alfystar** [comment]
Yes, very clear! 
Thanks for the info!

**Comment by mcarvin8** [comment]
@Alfystar - You can use my Salesforce CLI plugin to create code coverage reports with correct file-paths.

See https://github.com/mcarvin8/apex-code-coverage-transformer

**Comment by Alfystar** [comment]
Hi @mcarvin8 
Thanks for the update, in this year i crate a code to do what i need, but in these days we start to talk about sonarCube.

I will keep your work in mind and thank you for sharing it here
