### ISSUE TITLE
Problems with long lines in Lightning component files

### ISSUE THREAD

**Issue by TuurDutoit** [forcedotcom/salesforcedx-vscode#534]
### Summary
When saving a Lightning component file containing a long line, the extension seems to crash, spiking the process to 100% and halting all SalesforceDX functionality 

### Steps To Reproduce:
1. Create a Lightning component
2. Put a long line somewhere, e.g. `<lightning:buttonIcon iconName="utility:arrowdown" variant="bare" size="small" alternativeText="{!v.sortAscending ? 'Ascending' : 'Descending'}" class="{!'sort-button sort-button--' + (v.sortAscending ? 'ascending' : 'descending')}" onclick="{!c.reverseSort}" />`
3. Save the file

### Expected result
Everything just keeps working.

### Actual result
The Extension Host process spikes to 100% and stays there. All Salesforce functionality in VS Code stops working.

### Additional information
Important to note: putting the HTML properties on individual lines solves the problem.

#### Screenshots
<img width="805" alt="screen shot 2018-07-23 at 16 32 05" src="https://user-images.githubusercontent.com/4077287/43085108-66345ee4-8e9a-11e8-8a21-3fe39ed92f08.png">
<img width="803" alt="screen shot 2018-07-23 at 16 32 17" src="https://user-images.githubusercontent.com/4077287/43085113-6b27b072-8e9a-11e8-9204-534ca5a901ed.png">

**VS Code Version**:
1.25.1
**SFDX CLI Version**:
sfdx-cli/6.25.0-085abe54b0 (darwin-x64) node-v8.9.4
**OS and version**:
Mac OS High Sierra 10.13.6 (17G65)
**Internal Work Item**: [W-5411470](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005VFbNIAW/view)

**Comment by ntotten** [comment]
@vazexqi Who can we loop in here from LWC?

**Comment by TuurDutoit** [comment]
Any updates on this? It's quite annoying having to restart my code editor a few times per day...

**Comment by AnanyaJha** [comment]
@TuurDutoit Hi! I was not able to replicate this issue with the steps provided- I tried to repro on `1.28.2 ` and `1.29.0-insider`, while creating a new Lightning component and adding a line to an existing Lightning component. If you're still seeing this issue, could you provide us with more information?
