### ISSUE TITLE
 After updating Salesforce CLI to 59.13.0, receive this error 'Your installed Salesforce CLI version is no longer supported. Uninstall Salesforce CLI and install the latest version'

### ISSUE THREAD

**Issue by jcochran67** [forcedotcom/salesforcedx-vscode#5348]
![Annotation 2024-01-19 103923](https://github.com/forcedotcom/salesforcedx-vscode/assets/22800420/7284d0b7-85c5-45d4-bb77-36a33b17c6dc)

### Summary
After Update Salesforce CLI to the latest version (59.13.0) restart VS Code. 
receive this error 'Your installed Salesforce CLI version is no longer supported. Uninstall Salesforce CLI and install the latest version'

### Steps To Reproduce
Update Salesforce CLI to the latest version (59.13.0) restart VS Code. 

### Expected result
Expected no error and still able to use the CLI commands

### Actual result
Error is received 'Your installed Salesforce CLI version is no longer supported. Uninstall Salesforce CLI and install the latest version' and can not use the CLI commands

**Salesforce Extension Version in VS Code**:
v59.13.0

**SFDX CLI Version**:
v59.13.0

**OS and version**:
Windows 10 Enterprise

**VS Code version**:
v1.85.1

**Comment by peternhale** [comment]
@jcochran67 you provided `v59.13.0` as the sfdx version.

In a command prompt could you run `sfdx --version` and supply that value.

**Comment by jcochran67** [comment]
sfdx-cli/7.172.0 win32-x64 node-v16.17.1

**Comment by peternhale** [comment]
@jcochran67 The version of sfdx you have installed is not longer support in the vscode extension.

We recommend remove the old version of sfdx and installing the latest version of the Salesforce CLI. Please see this [page](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm) for instructions on how to proceed.

**Comment by daphne-sfdc** [comment]
@jcochran67 Follow up - have you gotten a chance to try what @peternhale suggested yet?

**Comment by CristiCanizales** [comment]
Closing this issue as the feature that generated it was reverted.
