### ISSUE TITLE
I downgraded my salesforce CLI, and it is still taking 30 minutes (and counting) to run apex tests. I have 3 methods in this test class. It should take a minute to run, tops.

### ISSUE THREAD

**Issue by peternhale** [forcedotcom/salesforcedx-vscode#5349]
I downgraded my salesforce CLI, and it is still taking 30 minutes (and counting) to run apex tests. I have 3 methods in this test class. It should take a minute to run, tops.

_Originally posted by @kenny-buckles in https://github.com/forcedotcom/salesforcedx-vscode/issues/4865#issuecomment-1890141907_

I have 17 total triggers and 101 total classes (this includes managed packages).

Versions:

@salesforce/cli/2.23.20 darwin-x64 node-v20.10.0
Salesforce Extension Pack (Expanded) v59.13.0
The commands I am using are what is built into vscode. I am just clicking on the "Run All Tests" link in the test class:

**Comment by peternhale** [comment]
Comments from original thread

Thanks for the additional information. It you wouldn't mind running a simple experiment, I would like to get a notion on the time difference it takes to run the above test via Run All Test and then running the same test using the CLI.

Run the test using vscode and share the starting and ending timestamps from the results
Run sf apex run test --code-coverage -d <somedir here> -n GetConfigJonTest --wait 5

If the sf command times out, please increase wait value until it runs to completion.

@[kenny-buckles](https://github.com/kenny-buckles)
kenny-buckles commented [5 days ago](https://github.com/forcedotcom/salesforcedx-vscode/issues/4865#issuecomment-1896270336)
@peternhale

I have run that command. It completes, but it took about 45 minutes to complete.

@peternhale
Member
[peternhale](https://github.com/peternhale) commented [5 days ago](https://github.com/forcedotcom/salesforcedx-vscode/issues/4865#issuecomment-1896274393)
@kenny-buckles how does that compare to running Run All Tests in vscode?

Also, could you run the command again, but omit --code-coverage?

@[kenny-buckles](https://github.com/kenny-buckles)
kenny-buckles commented [5 days ago](https://github.com/forcedotcom/salesforcedx-vscode/issues/4865#issuecomment-1896276684)
@peternhale

It takes about the same amount of time. I will rerun without the --code-coverage.

@[kenny-buckles](https://github.com/kenny-buckles)
kenny-buckles commented [5 days ago](https://github.com/forcedotcom/salesforcedx-vscode/issues/4865#issuecomment-1896439178)
@peternhale

Without --code-coverage it took 39m

**Comment by kenny-buckles** [comment]
@peternhale 

The totaled time was 31425 ms. Which only comes out to like 31 seconds. But the whole thing ran for the 39 minutes.

**Comment by peternhale** [comment]
Thanks @kenny-buckles yuck.

Could you run `sf data query -q "select createddate, completeddate, status from AsyncApexJob where id = '707......'" -t` and share the results?

**Comment by kenny-buckles** [comment]
@peternhale 

kenny@computer sfdc-org % sf data query -q "select createddate, completeddate, status from AsyncApexJob where id = '707E200000FRxDB'"
 CREATEDDATE                  COMPLETEDDATE STATUS    
 ──────────────────────────── ───────────── ───────── 
 2024-01-17T17:32:13.000+0000 null          Completed 
Total number of records retrieved: 1.
Querying Data... done

**Comment by peternhale** [comment]
Thanks @kenny-buckles One more if you don't mind.

`sf data get record -s ApexTestRunResult --where AsyncApexJobId='707.....'`

**Comment by kenny-buckles** [comment]
@peternhale 

kenny@computer sfdc-org % sf data get record -s ApexTestRunResult --where AsyncApexJobId='707E200000FRxDB'                            
attributes:
  type: ApexTestRunResult
  url: /services/data/v59.0/sobjects/ApexTestRunResult/05mE2000000CGU1IAO
Id: 05mE2000000CGU1IAO
IsDeleted: false
CreatedDate: 2024-01-17T17:32:14.000+0000
CreatedById: 0055G000006R9d5QAC
LastModifiedDate: 2024-01-17T18:11:43.000+0000
LastModifiedById: 0055G000006R9d5QAC
SystemModstamp: 2024-01-17T18:11:43.000+0000
AsyncApexJobId: 707E200000FRxDBIA1
UserId: 0055G000006R9d5QAC
JobName: null
IsAllTests: false
Source: sfdx toolbelt:
StartTime: 2024-01-17T17:32:13.000+0000
EndTime: 2024-01-17T18:11:43.000+0000
TestTime: 31425
Status: Completed
ClassesEnqueued: 1
ClassesCompleted: 1
MethodsEnqueued: 3
MethodsCompleted: 3
MethodsFailed: 0
Getting Record... done

**Comment by peternhale** [comment]
@kenny-buckles One more ask if you have time.

In the org used to run tests, I would like to try run the tests sequentially.

On the org goto Setup->Apex Test Execution
Click on Options button.
In the popup check "Disable Parallel Apex Testing"
Click "Ok" button

From CLI run `sf apex run test -d -n GetConfigJonTest --wait 40 --synchronous`

Let me know if runtime improves.

**Comment by kenny-buckles** [comment]
@peternhale 

Nevermind. I had to re-authenticate my default org. It is running now.

**Comment by kenny-buckles** [comment]
@peternhale 

When I run the command:

`sf apex run test -d /Users/kenny/Desktop/Test -n ACRTriggerHandlerTestClass --wait 40 --synchronous`

it finishes very quickly now: Test Execution Time  29883 ms

**Comment by peternhale** [comment]
@kenny-buckles thanks for trying all this for me and I think I have a much better idea as to what is going on.

**Comment by kenny-buckles** [comment]
Thank you. Is there anything else you need me to do? I did try running the "Run all tests" from the UI, and it seemed to still take quite a while.

**Comment by peternhale** [comment]
With parallel tests turned off, then each test method is run sequentially across the selected set of classes. So I would expect that to take some time.

The experiments you did isolated a Platform Events subscription for test complete messages. By disabling parallel and using `--sequential` flag guaranteed that platform events would not be used.

This "long wait" has occurred before, but not as persistent as it has been for you.

**Comment by kenny-buckles** [comment]
I see. Is there anything else you need me to do? Or just wait for your reply? Thanks for your help.

**Comment by peternhale** [comment]
@kenny-buckles I have logged an bug for this issue.It does require some additional investigation from the dev team. This issue will remain open until a fix is provided.

**Comment by peternhale** [comment]
@kenny-buckles I have been having a difficult to reproducing this. The one area I did not talk with about is the org your are running your tests in.

Would it be possible to get the type of org (scratch, sandbox or prod). If it is a scratch org could you provide the contents of the scratch org definition file you are using.

If possible could I get the orgId.

Thanks in advance.

**Comment by kenny-buckles** [comment]
@peternhale 

It is a partial sandbox. The org id is 00DE2000000iEAX

**Comment by kenny-buckles** [comment]
@peternhale Hello - any update on this?

**Comment by kenny-buckles** [comment]
@peternhale Hello - any update on this?

**Comment by kenny-buckles** [comment]
@peternhale It's also taking a long time for LWC components to be deployed to sandbox as well.

**Comment by peternhale** [comment]
Hi @kenny-buckles, I have added some additional debugging to the @salesforce/apex-node module and those changes are now available in @salesfprce/plugin-apex.

If the one test is still taking way to long run could you give this a try:

* `sf plugins install apex` - will install the latest version of the apex plugin
* remove the current log file for sf `$HOME/.sf/sf-YYYY-MM-DD.log` for current date
* cd to your project root dir
* run `SF_LOG_LEVEL=debug sf apex run test -c -d <outputdir> -w 60 -n <your test class>`

After the run is complete you should see log file entries with the string `elapsedTime`, lots of them.

Please post the log file to this issue.

**Comment by peternhale** [comment]
> @peternhale It's also taking a long time for LWC components to be deployed to sandbox as well.

I am also trying to get some additional debug info from vscode for the deploy commands. Please see issue #5496

**Comment by diyer** [comment]
@kenny-buckles We are going to close this one as we did not hear back from you. Please file a new issue if you are still seeing this and we can help you with it. Thank you!
