### ISSUE TITLE
22:40:37.239 sfdx org:login:web --alias dev --instance-url https://login.salesforce.com --set-default  ended with exit code 1

### ISSUE THREAD

**Issue by saurabh-gujar** [forcedotcom/salesforcedx-vscode#5365]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by saurabh-gujar** [comment]
22:40:37.239 sfdx org:login:web --alias dev --instance-url https://login.salesforce.com --set-default
 ended with exit code 1

**Comment by daphne-sfdc** [comment]
@saurabh-gujar 
Can you provide the following info?

**Salesforce Extension Version in VS Code:
SFDX CLI Version:
OS and version:
VS Code version:**

Also, what did you do to get this error?  Did you run `SFDX: Authorize an Org` from the command palette?  If yes, how far did you manage to get in that command before seeing that error?
