### ISSUE TITLE
Cannot deploy anything using right click on file - shows "Could not find 6b630..." error

### ISSUE THREAD

**Issue by yuliyakisliuk** [forcedotcom/salesforcedx-vscode#5366]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Try to deploy component using 'Deploy to org':
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/135986662/c7113d9e-5445-46f7-b0ef-dd4ba8890408)

1.  Wait

### Expected result

"Deployed successfully"

### Actual result

"Deploy failed"

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/135986662/74451dd1-1801-428c-b18e-6f20c03530b6)

**Salesforce Extension Version in VS Code**:
59.13.0
and all earlier produce the same error

**SFDX CLI Version**:
@salesforce/cli/2.24.4 win32-x64 node-v20.10.0

**OS and version**:
Windows 10

**VS Code version**: 
November 2023 (version 1.85)

**Comment by daphne-sfdc** [comment]
Hi @yuliyakisliuk,

Can you please try the following steps?
1. Delete the `.sfdx` and `.sf` folders
2. Reload the VSCode window
3. Re-authorize to your org
4. Try to deploy again

If the above doesn't solve the problem, try the following to clean your extensions:
1. Open a new Terminal window
2. `cd .vscode/extensions`
3. Delete all the Salesforce extensions (`rmdir salesforce.salesforcedx*`)
4. Go back to VSCode and reload the VSCode window
5. Reinstall the Salesforce Extension pack

**Comment by yuliyakisliuk** [comment]
Hello @daphne-sfdc, 
Deletion of .sfdx and .sf folders helped, thanks!
