### ISSUE TITLE
SFDX: Authorize an Org failed to run

### ISSUE THREAD

**Issue by marcosgleick** [forcedotcom/salesforcedx-vscode#5367]
Resumo
Attempting to connect my VS Code to an organization created in Trailhead for the beginner developer track, I am encountering an error.

![Captura de Tela 2024-01-25 às 22 16 38](https://github.com/forcedotcom/salesforcedx-vscode/assets/111712207/fcea00ad-6bc5-4c72-a534-3ab793741fc1)

Steps to reproduce:

Download VS Code.
Download Java JDK version 17.
Download Salesforce CLI.
Install the extension: Salesforce Extension Pack.
Execute SFDX: Create Project.
Execute SFDX: Authorize an Org.
Expected Result:
Successfully connect VS Code to my Org.

Current Result:

![Captura de Tela 2024-01-25 às 22 16 38](https://github.com/forcedotcom/salesforcedx-vscode/assets/111712207/fcea00ad-6bc5-4c72-a534-3ab793741fc1)

Additional Information:
Feel free to attach a screenshot.

Salesforce Extension version in VS Code: v59.15.0

SFDX CLI Version: @salesforce/cli/2.25.7 darwin-x64 node-v20.10.0

OS and version: macOS Sonoma 14.3

VS Code Version: 1.85.2

**Comment by CristiCanizales** [comment]
Hi @marcosgleick, please create provide us with **all the details** requested in the template of the issue. We ask for them precisely to have some context on the issue, without them is almost impossible to help users. Thanks in advance!

**Comment by marcosgleick** [comment]
@CristiCanizales hi, I updated with the pending information.

**Comment by CristiCanizales** [comment]
@marcosgleick Thanks!! If you try to auth with the CLI and not with `SFDX: Authorize an Org` command, does it work?
(`sfdx org:login:web --alias <trailheadOrg> --instance-url https://login.salesforce.com`)

**Comment by marcosgleick** [comment]
@CristiCanizales Result: zsh: no such file or directory: trailheadOrg

**Comment by marcosgleick** [comment]
No, its not working. =/

**Comment by CristiCanizales** [comment]
Hi @marcosgleick, what I meant with "<trailheadOrg>" was for you to replace it with your org alias

**Comment by marcosgleick** [comment]
hi @CristiCanizales. I tried again, but I couldn't.

**Comment by CristiCanizales** [comment]
@marcosgleick can you send screenshots of what you tried through the CLI and what you got? If you can't neither with the extensions nor the CLI, it looks like it's something with your org. Maybe wrong creds?
Can you also share the options you're selecting after running `SFDX: Authorize an Org`?

**Comment by marcosgleick** [comment]
Erro : 14:13:53.639 sfdx org:login:web --alias myDevOrg --instance-url https://login.salesforce.com --set-default
 ended with exit code 1

**Comment by CristiCanizales** [comment]
@marcosgleick Thanks for the screenshots. Can you try with the 3rd option after running `SFDX: Authorize an Org`? (Custom - Enter a custom login URL) and use your trailhead org URL

**Comment by marcosgleick** [comment]
Tentei, mas não consegui.

**Comment by CristiCanizales** [comment]
Glad it works now!
