### ISSUE TITLE
that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see:

### ISSUE THREAD

**Issue by Ajbun** [forcedotcom/salesforcedx-vscode#5368]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by CristiCanizales** [comment]
hi @Ajbun, please create a new issue and provide us with all the details requested in the template of the issue. We ask for them precisely to have some context on the issue, without them is almost impossible to help users. Thanks in advance!
