### ISSUE TITLE
Cannot get html lightning language support for aura

### ISSUE THREAD

**Issue by sim9805** [forcedotcom/salesforcedx-vscode#5377]
Summary
There is no code completion for aura components (cmp)

Steps To Reproduce:
sfdx force:lightning:component:create -n mylightningcomp
Open mylightningcomp.cmp file
Start typing <lightning: then CTRL+SPACE
Expected result
vs Code should suggest lightning elements

Actual result
Nothing is suggested :(

Additional information
In the javascript controllers, LWC elements are suggested.
And in apex classes, language suggestions are working.
But aura.cmp its not working

**Comment by CristiCanizales** [comment]
hi @sim9805, can you send a screenshot of what you see when you select Aura Language Server in the Output Tab? 
<img width="1332" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/304a9e79-8d25-4918-9d42-86fcc934aca9">

**Comment by sim9805** [comment]
Hi @CristiCanizales , this is the screenshot of Aura Language Server tab
![Screenshot 2024-01-30 004611](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/3caaa9b7-8db1-4d71-b224-4db3973251d8)

And this is the issue when I press ctrl+space only in cmp file am not getting any suggestions but am getting autosuggestions in LWC, APEX and in aura- controller.js file as well

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/1d5582bb-e517-4276-9af8-fd4579ad9cd0)

Getting auto suggestions in auracontroller js file, LWC, apex
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/04a400bf-2646-4700-b8d4-f5b5ed489035)

**Comment by CristiCanizales** [comment]
@sim9805 can you try creating a new aura component running `SFDX: Create Aura Component` through the command palette (Ctrl + Shift + P) and checking again?

**Comment by sim9805** [comment]
@CristiCanizales have created another new aura component, but still facing same 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/6082901e-9bb1-4a81-a5f3-c69eb4e4bfb2)

**Comment by daphne-sfdc** [comment]
Hi @sim9805, Can you please run `Developer: Show Running Extensions` and send us a screenshot of that page?  I want to make sure you have all the Salesforce extensions installed, activated, and on the latest version.

**Comment by sim9805** [comment]
Hi @daphne-sfdc , here is the screenshot of extensions that i have in VS. Thanks

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/f7df46c3-7906-4696-84bc-5ab0e2472885)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/a34a9ea4-18ed-4e6c-a7ca-b92a6d687cfe)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/391cadaa-4c53-4b04-97ba-7805e48bfca0)

**Comment by daphne-sfdc** [comment]
@sim9805 Ok, good to know that you are using the latest version of the extensions and everything is activated properly 👍 

Can you run `Developer: Toggle Developer Tools` and show me what's in the logs?

**Comment by sim9805** [comment]
@daphne-sfdc , please find the screenshot of logs , and pls let me know if I need to share any other tab view in this screenshot am attaching console error logs 
![Uploading image.png…]()

**Comment by daphne-sfdc** [comment]
The image file doesn't work.  Can you re-upload it?

**Comment by sim9805** [comment]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/452da27e-ca63-42e4-95f4-20688d1af5d9)

**Comment by daphne-sfdc** [comment]
The error message about MaxListenersExceededWarning is a typical one and does not interfere with the Aura extension activating.  In this case, it looks like your logs are not showing anything unusual.

The screenshot of the Aura Language Server tab that you provided earlier also has only regular logs.

What is your VSCode version?  If you are not on the latest version (1.85.2) can you upgrade your VSCode?

**Comment by sim9805** [comment]
@daphne-sfdc , Hi  am using the latest version of VS, please advise how can I enable auto suggestions of aura.cmp file?
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/07b28bac-1185-4f71-b2a2-cffc1a4450d0)

**Comment by daphne-sfdc** [comment]
I do wonder if one of your other non-Salesforce extensions has something that conflicts with the Aura extension... have you ever seen autocompletions for Aura before, or is this your first time using the extension?

I would try disabling all the other non-Salesforce extensions and seeing if the Aura autocompletions appear.  Then if they do appear, start adding the extensions back one by one to figure out the conflicting one.

**Comment by sim9805** [comment]
@daphne-sfdc I have not try Auto sugggestion for aura earlier..but have been using for Apex, LWC

**Comment by daphne-sfdc** [comment]
What were your results of disabling all the non-Salesforce extensions?  Did you start seeing autocompletions for Aura?

**Comment by sim9805** [comment]
@daphne-sfdc, I have  disabled all non-Salesforce extensions, still am not getting auto suggestion, please advise 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/27f7be04-3831-4b53-a493-58b7adf05e14)

**Comment by daphne-sfdc** [comment]
You did remember to reload the VSCode window after disabling those extensions, right?

**Comment by CristiCanizales** [comment]
Hi @sim9805, can you also check what you have selected for the setting `Salesforcedx-vscode-lightning: Activation Mode`? Both for User and Workspace, and also in the JSON file.
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/adf5de63-402c-4e05-a83c-37d0df2fae6c)

**Comment by sim9805** [comment]
@daphne-sfdc yes I restarted it but it was not working.
@CristiCanizales Hi, I have updated my user and workspace to autodetect then restart it still am not getting. Also could you please advise in whihc json file I need to check further maybe it will help

**Comment by CristiCanizales** [comment]
@sim9805 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/eb6fd026-e1b0-422d-a4d2-fa3589e9eeaf)

**Comment by sim9805** [comment]
@CristiCanizales this is my workspace json setting: 
{
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.sfdx": true
  }
}

This is my user json setting :
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/34b4312e-9154-4c78-bb86-5c1320dc0ca6)

**Comment by sim9805** [comment]
@CristiCanizales 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/101207881/71d071a4-6b05-47d0-94a4-de8b239c0634)

**Comment by mingxuanzhangsfdx** [comment]
Hi @sim9805 , thanks for sharing the config. In my config there is no "*.cmp" config specified. So I think you should remove that. Also, could you try to

1. Open up a new Terminal window and type cd .vscode/extensions (or cd %USERPROFILE%.vscode\extensions in Windows)
2. Delete all the previous versions of the Salesforce extensions by running rm -rf salesforce.salesforcedx-vscode* (or equivalent command in windows - rmdir /s /q salesforce.salesforcedx-vscode*)
3. Reinstall the Salesforce extensions.
4. Clean your cache by deleting the .sfdx and .sf folders from your project, then running "Developer: Reload Window" from the command palette.

Please let me know if there is any error output in the Developer Tools and consoles.

**Comment by sim9805** [comment]
Hi @mingxuanzhangsfdx , after removing the .cmp config, it starts working, thanks !!

**Comment by CristiCanizales** [comment]
Glad it's working again!
