### ISSUE TITLE
After updating SF extension pack in VSCode, everything is broken.

### ISSUE THREAD

**Issue by dvon88** [forcedotcom/salesforcedx-vscode#5378]
### Summary

After updating the Salesforce Extension pack in VSCode, nothing works anymore. I cannot retrieve, deploy, or diff files. I can only open my default org and authorize an org. I have tried re-authorizing my org, but that has not fixed the issue. When I try to diff a file, I get the error in screenshot 1.
![CleanShot 2024-01-29 at 11 21 54](https://github.com/forcedotcom/salesforcedx-vscode/assets/35981904/17b9496a-9022-4f95-9d8d-ae9837dd4ba5)

When I try to deploy a file, I get this error "structuredClone" is not defined.
![CleanShot 2024-01-29 at 11 24 26](https://github.com/forcedotcom/salesforcedx-vscode/assets/35981904/6258f448-5d6c-4cef-9529-833e8a096e54)

### Steps To Reproduce:

1.  Try to deploy, diff, or retrieve anything.

### Expected result

Deploy, retrieve, or diff code.

### Actual result

Errors, including "We cannot query your org"

**Salesforce Extension Version in VS Code**: 59.15.0

**SFDX CLI Version**: @salesforce/cli/2.25.7 darwin-arm64 node-v20.10.0

**OS and version**: Sonoma 14.2.1

**VS Code version**: 1.77.0

**Comment by Bartheleway** [comment]
It comes from the latest VS Code version. You can safely rollback to 59.13.0 (59.14.0 do not exist) and it will solve the situation.

Additionally, when you try to use the right click / deploy to org, you get a `structuredClone is not defined` in the output panel.

**Comment by dvon88** [comment]
> It comes from the latest VS Code version. You can safely rollback to 59.13.0 (59.14.0 do not exist) and it will solve the situation.
> 
> Additionally, when you try to use the right click / deploy to org, you get a `structuredClone is not defined` in the output panel.

Hi, I rolled back to 59.13.0 and it did not fix the issue.

**Comment by Bartheleway** [comment]
My collegues and I are in VS Code version 1.85.2 and NodeJs 18.12.1 if it helps. Have you reloaded your VS Code after downgrading all VS Code extensions ? We wiped out the existing config in `{homeUserFolder}/.sfdx` also.

**Comment by dvon88** [comment]
> My colleagues and I are in VS Code version 1.85.2 and NodeJs 18.12.1 if it helps. Have you reloaded your VS Code after downgrading all VS Code extensions ? We wiped out the existing config in `{homeUserFolder}/.sfdx` also.

Yes, I restarted VSCode completely, did not fix the issue.

**Comment by masoodtamboli** [comment]
Hi I'm too getting the same issue, I guess its because of the new release of Salesforce CLI Integration, because before 27th Jan 2024 everything was working fine and when the extension got auto update on 27th then started facing this issue.

<img width="454" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/45930017/3c6d5012-adad-4cdc-be16-e249672f211a">

**Comment by juansonder** [comment]
Was anyone able to fix this? I've tried changing the versions for the Salesforce CLI and the VS Code extension without any results.

**Comment by Bartheleway** [comment]
When downgrading, make sure to disable auto update of extensions (in case it re-updates extensions) before closing/reopening VS Code.

**Comment by diyer** [comment]
@dvon88 @juansonder Thank you for bringing this to our attention. The team is aware of the issue and is most likely linked to the recent library upgrades we made. Some initial testing shows that vscode version 1.82.0 and higher do not have this issue. We're actively working on a resolution. We are sorry for the inconvenience 🙏 

@dvon88 @juansonder Can you try upgrading your vscode version and let us know?

**Comment by neilhohmann** [comment]
I can confirm that **updating to VS Code version 1.82.0 resolved my issue**. All good now.

**Comment by prahladbhadani** [comment]
Rolling the extension pack to v59.13.0 doesn't automatically rollback all the related extensions to 59.13.0. You will need to roll back each extension to 59.13.0, disable extension auto update and reload all the extensions. That did the trick for me.

**Comment by mitesh00005** [comment]
> Rolling back the extension pack to v59.13.0 doesn't automatically rollback all the related extensions to 59.13.0. You will need to roll back each extension to 59.13.0, disable extension auto update and reload all the extensions. That did the trick for me.

It worked for me

**Comment by diyer** [comment]
@dvon88 Can you please confirm if upgrading vscode to a version greater than 1.82.0 has fixed the issue on your end or not?

**Comment by masoodtamboli** [comment]
@diyer updated vs code to latest version and it fixed this issue.
Thank you!

**Comment by dvon88** [comment]
> @dvon88 Can you please confirm if upgrading vscode to a version greater than 1.82.0 has fixed the issue on your end or not?

HI yes I upgraded VSCode to 1.85.2 and it works now.

**Comment by Fernando-Fernandez** [comment]
> Hi! Thanks! You were right. I'm using a Mac, and it appears that leaving the installer (I'm not certain if it's specifically the installer or another component, as I'm not a regular Mac user) in the Download folder prevent VS Code from updating properly. After moving it, I was able to update VS Code, and now everything is working smoothly.

I have seen the same error and when we've verified from where VS Code was running, it was from the Download folder in Mac. Force quitting VS Code and moving the file to the Application folder resolved the issue.

**Comment by sfscgjohnson** [comment]
I am still getting this after updating to Version 1.86.1 of Vscode.  CLI Version 59.17.
I have many dependent extensions.  Reverting to 59.13 did not work.  
Any other tips or steps I can take?  Is there an outline of the steps with full instructions?  I don't do these steps often.

**Comment by sfscgjohnson** [comment]
I was still getting this error and had to reinstall the CLI from https://developer.salesforce.com/tools/salesforcecli
Instead of npm.  Likely I installed it from installer first and then the update from npm didn't configure something correctly.

**Comment by Conner1341** [comment]
I am running VSCode 1.86.2, node 18.7.1, and salesforce cli version 2.28.6. I have uninstalled, reinstalled, and reverted versions in all of the aforementioned apps and am still hitting the `structuredClone is not defined` error when trying to authorize an org through vscode. Is there anything else I can try?

**Comment by afandre** [comment]
@Conner1341 I completely uninstalled the Salesforce Extension Pack and all sub extensions. Uninstalled the CLI. Removed all profiles under c:\Users\[yourUserid]\.sf and c:\Users\[yourUserid]\.sfdx. Restarted and then installed the CLI from the Salesforce installation here https://developer.salesforce.com/tools/salesforcecli and all issues were resolved.
