### ISSUE TITLE
Null coalesce operator

### ISSUE THREAD

**Issue by gian-ribo** [forcedotcom/salesforcedx-vscode#5384]
### Summary

VS Code can't recognise "??" operator. The deploy works.
In "Problems" tab I see:
- Unexpected token '?'.
- Expecting ':' but was: ';'

### Steps To Reproduce:

1. Write some code with ?? operator.
Example: Account[] accList = maybeEmptyAccountList ?? new Account[]{};

### Expected result

No problems appeares

### Actual result

In "Problems" tab I see:
- Unexpected token '?'.
- Expecting ':' but was: ';'

**Salesforce Extension Version in VS Code**: v59.15.0

**SFDX CLI Version**: 7.209.6

**OS and version**: MacOS Sonoma 14.2.1

**VS Code version**: 1.85.2 (Universal)

**Comment by peternhale** [comment]
@gian-ribo The apex language server will be updated when major release 248 is deployed to all customers.

**Comment by diyer** [comment]
@gian-ribo As Peter said, this will be supported with the next major version of extensions which is 60.0 which will likely be released in the coming weeks of February. Hope this helps.

**Comment by diyer** [comment]
This is now available as part of version 60.0 of Salesforce extension

**Comment by diyer** [comment]
@gian-ribo Please test this and let us know if this is working as expected.
