### ISSUE TITLE
Not able to change between Multiple Orgs.

### ISSUE THREAD

**Issue by kowshik8032** [forcedotcom/salesforcedx-vscode#5386]
### Summary

I'm salesforce CLI Integration extension. And i'm using multiple orgs in my vscode. but now its now showing any other org rather than current one. It worked fine past week.

### Expected result
After the SFDX command. appropriate org should pop up.

### Actual result

No org populating. only SFDX commands populating.

### Additional information

<img width="451" alt="Screenshot 2024-01-30 194346" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/55626263/4414b980-e0a4-4e33-aaee-faf4566ca97e">

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**: v59.15.0

**OS and version**: windows 11  Windows_NT x64 10.0.22621

**VS Code version**: 1.70.2

**Comment by CristiCanizales** [comment]
hi @kowshik8032, can you confirm you are connected to those orgs? Please run `sf org list` in your terminal and send me a screenshot of what you get

**Comment by peternhale** [comment]
I am closing this issue for now. If the issue reoccurs, feel free to reopen the issue.

**Comment by peternhale** [comment]
Closing
