### ISSUE TITLE
"SFDX: Create Apex class" is not click context aware and is still asking for choice of location for new file.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/salesforcedx-vscode#5391]
### Summary

When I right click on the "classes" folder or any subfolder and choose "SFDX: Create Apex Class"
<img width="338" alt="2024-02-01_13h39_50" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5740564/a5bfc86f-ae01-460e-89a6-32ee24ec576b">
 it is not aware from where it was called as in the next step I am asked about the location where to save the file
<img width="527" alt="2024-02-01_13h39_19" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5740564/5f7fe485-b287-43e8-aab9-3676739d40f7">

It is even worse if I want to create a class in a subfolder like "classes/TriggerHandlers" because there is no such option to choose. It will be always created in classes folder

### Steps To Reproduce:

1.  Right click on the folder where you want to create an Apex class.
2.  Choose "SFDX: Create Apex Class"
3. You will be asked where to save a file

### Expected result

I am not asked about a location, it should be known from click context.

### Actual result

I am asked about additional details that should not be needed. Class is always created in the classes folder even if I start from a subfolder. 

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:
v59.16.0

**SFDX CLI Version**:
@salesforce/cli/2.26.10 win32-x64 node-v20.10.0

**OS and version**:
Windows 11

**VS Code version**:
1.86.0

**Comment by daphne-sfdc** [comment]
Hi @PawelWozniak, Thank you for reporting this issue.  A bug has been logged in our backlog.

**Comment by CristiCanizales** [comment]
Closing this duplicate issue to keep track with #4294.
