### ISSUE TITLE
Getting ENOENT: no such file or directory, stat 'c:\.eslintignore' when downloading class from org browser extensions only

### ISSUE THREAD

**Issue by lacheporter** [forcedotcom/salesforcedx-vscode#5395]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by CristiCanizales** [comment]
Hi @lacheporter, please update this issue and provide us with all the details requested in the template. We ask for them precisely to have some context on the issue, without them is almost impossible to help users. Thanks in advance!

**Comment by CristiCanizales** [comment]
Closing this issue as there's no answer after 4 days and there are no details to diagnose problem.
