### ISSUE TITLE
Spring 24 release has introduced a regression while trying to create a scratch org

### ISSUE THREAD

**Issue by peternhale** [forcedotcom/salesforcedx-vscode#5415]
Customers have been reporting an error while creating a scratch org and other commands that require a new org, such as package install.

The problem manifests with an error containing the error code `C-9999`.

This issue is known and is being investigated.

Please see "[Package version & scratch org creation is failing with the error - ‘C-9999' after Spring'24 release](https://issues.salesforce.com/issue/a028c00000yx0wjAAA/)" for additional details and current status of this issue.

**Comment by diyer** [comment]
The issue has been fixed and released now.
