### ISSUE TITLE
📢 📢 Command name changes in major release v60.0.0

### ISSUE THREAD

**Issue by daphne-sfdc** [forcedotcom/salesforcedx-vscode#5436]
Hello Customers,

In the major release v60.0.0 that came out this morning, we made two command name changes as part of our ongoing migration from SFDX-style to SF-style commands.  In order to be consistent with the CLI commands, we have made the following changes:
1. `SFDX: Push Source to Default Org and *Override* Conflicts` -> `SFDX: Push Source to Default Org and *Ignore* Conflicts`
2. `SFDX: Pull Source from Default Org and *Override* Conflicts` -> `SFDX: Pull Source from Default Org and *Ignore* Conflicts`

There is no functionality change – the two commands still work as they have before.

**Comment by diyer** [comment]
Official docs have been updated. Closing this
