### ISSUE TITLE
🔜 SFDX Commands will be transitioning to SF by April 1st

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#5448]
Hello all Salesforce Developers! As you might have seen, the new Salesforce CLI sf (v2) went GA last July 🎉 

Much of the functionality within the Salesforce Extension Pack relies on shared functionality with the Salesforce CLI. To support this transition, we'll be migrating the Salesforce Extension Pack SFDX commands over to SF as well. We'll start giving you warnings on activation if we see that you don't have the correct version of the CLI installed. **You'll have until **April 1st** to complete this migration**. After that date, you'll start seeing errors for the following commands.

**We recommend you migrate to the new version of the Salesforce CLI, sf (v2), ASAP to avoid running into issues with our SFDX->SF command migration on April 1st**. Here's [the guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm) to get started.

Here's a list of all our commands and where they currently are in the migration process:

✅ DONE
**Orgs**
- `SFDX: Authorize an Org`
- `SFDX: Authorize an Org using Session ID`
- `SFDX: Log Out from All Authorized Orgs`
- `SFDX: Log Out from Default Org`
- `SFDX: Open Default Org`
- `SFDX: Display Org Details`
- `SFDX: Display Org Details for Default Org`
- `SFDX: List all Aliases`
- `SFDX: Delete Source from Default Org`
- `SFDX: List all Config Variables`
- `SFDX: Create a Default Scratch Org`
- `SFDX: Delete Default Org`
- `SFDX: Delete Org`

**Project**
- `SFDX: Create Project`
- `SFDX: Create Project with Manifest`
- `SFDX: Diff File Against Org`
- `SFDX: Diff Folder Against Org`
- `SFDX: Refresh SObject Definitions`
- `SFDX: View All Changes (Local and in Default Org)`
- `SFDX: View Local Changes`
- `SFDX: View Changes in Default Org`
- `SFDX: Generate Manifest File`
- `SFDX: Push Source to Default Org`
- `SFDX: Push Source to Default Org and Ignore Conflicts`
- `SFDX: Pull Source from Default Org`
- `SFDX: Pull Source from Default Org and Ignore Conflicts`
- `SFDX: Install Package`

**Apex**
- `SFDX: Launch Apex Replay Debugger with Current File`
- `SFDX: Execute Anonymous Apex with Editor Contents`
- `SFDX: Execute Anonymous Apex with Currently Selected Text`
- `SFDX: Get Apex Debug Logs`
- `SFDX: Run Apex Test Method`
- `SFDX: Run Apex Tests`
- `SFDX: Re-Run Last Run Apex Test Class`
- `SFDX: Re-Run Last Run Apex Test Method`
- `SFDX: Run Apex Test Suite`
- `SFDX: Create Apex Test Suite`
- `SFDX: Add Tests to Apex Test Suite`
- `SFDX: Create Apex Class`
- `SFDX: Create Apex Unit Test Class`

**LWC**
- `SFDX: Run All Lightning Web Component Tests`
- `SFDX: Run Lightning Web Component Test Case`
- `SFDX: Run Lightning Web Component Test File`
- `SFDX: Run Current Lightning Web Component Test File`
- `SFDX: Debug Lightning Web Component Test File`
- `SFDX: Debug Lightning Web Component Test Case`
- `SFDX: Debug Current Lightning Web Component Test File`
- `SFDX: Rename Component`
- `SFDX: Create Lightning Web Component`
- `SFDX: Create Lightning Web Component Test`

**Visualforce**
- `SFDX: Create Visualforce Component`
- `SFDX: Create Visualforce Page`

**Aura**
- `SFDX: Create Aura App`
- `SFDX: Create Aura Component`
- `SFDX: Create Aura Event`
- `SFDX: Create Aura Interface`

**General**
- `SFDX: Cancel Active Command`
- `SFDX: Open Documentation`

⏭️ UP NEXT

**LWC**
- `SFDX: Start Watching Lightning Web Component Test`
- `SFDX: Stop Watching Lightning Web Component Test`
- `SFDX: Stop Watching All Lightning Web Component Tests`
- `SFDX: Refresh Lightning Web Component Test Explorer`
- `SFDX: Navigate to Lightning Web Component Test`

All commands will be migrated by April 1st. Stay up to date with the current state by following this post. Happy migrating!

NOTE: 
If you haven't upgraded your CLI yet, you'll see an error like the following:

```
Starting SFDX: Authorize an Org
15:23:41.710 sfdx force:auth:web:login —setalias vscodeOrg --instanceurl https://login.salesforce.com/ —setdefaultusername
› Warning: force:auth:web:login is not a sfdx command.
Did you mean auth:web:login? [y/n]:
› Error: Run sfdx help force for a list of available commands.
15:23:47.396 sfdx force:auth:web:login —setalias vscodeOrg --instanceurl https://login.salesforce.com/ —setdefaultusername
ended with exit code 127
```

**Comment by paustint** [comment]
I noticed that after the push commands were upgraded, error messages are (usually) no longer shown un the extension output.

I have to copy the command into my terminal and run it to see the table of component errors (this might only happen when there is more than one error being reported)

**Comment by AnanyaJha** [comment]
Thanks for sharing @paustint ! @CristiCanizales could you see if this is something you're able to repro?

**Comment by CristiCanizales** [comment]
Hi @paustint! Is that still happening for you with v60.1.2? Because with #5441 we addressed that issue (#5450)!

**Comment by paustint** [comment]
I'll let you know if I still encounter the issue - thanks for the reply!

**Comment by diyer** [comment]
This is now complete.
