### ISSUE TITLE
Instability in using Apex Interactive Debugger

### ISSUE THREAD

**Issue by angielaz** [forcedotcom/salesforcedx-vscode#5454]
I'm trying to use Apex Interactive debugger for the first time (the first time I have a license) and on a developer sandbox, and it's very unstable. Could only inspect the vars on the first breakpoint but usually not even start. 
I can see the session is open and active from the debug console in VS Code and also in the org but when I execute the code it does not show the line of the breakpoint nor load the vars in the debug. Constantly shows me the following error: "An unknown error occurred. Please consult the logs for more details"

Added "trace": "all" in launch.json file to have more details in VS Code’s Debug Console and couldn’t conclude much.

I disabled all other extensions in VS Code but the problem remains. Could this behaviour be because I'm using it in a developer sandbox and not on a scratch org? 

command _sf version --verbose --json_ returns
```
{
  "cliVersion": "@salesforce/cli/2.6.9",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Program Files\\sf\\client",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.23 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.7 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.31 (core)",
    "@salesforce/cli 2.6.9 (core)",
    "apex 2.3.11 (core)",
    "auth 2.8.13 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.31 (core)",
    "login 1.2.28 (core)",
    "org 2.10.3 (core)",
    "schema 2.3.23 (core)",
    "settings 1.4.26 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.3 (core)",
    "user 2.3.29 (core)"
  ]
}
```

### Steps To Reproduce:

1.  Launch Apex debugger.
2.  Set a breakpoint
3. Execute code 

### Expected result

Debugger should stop and show the line of code with the first breakpoint and let me inspect variables. Debugger should be functional. 

### Actual result

Vars can't be inspected. The debugger can't be used. Error message appears: "An unknown error occurred. Please consult the logs for more details"

### Additional information

<img width="761" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/fd050b81-b8ba-44c2-886d-25c7b566ab54">

<img width="959" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/07ec06fc-0eee-4861-8b85-0b28a5046d14">

**Salesforce Extension Version in VS Code**: v60.1.2

**SFDX CLI Version**: 2.6.9

**OS and version**: Windows_NT 10.0.19045

**VS Code version**: 1.86.2

Thanks for your attention.

**Comment by CristiCanizales** [comment]
Hi @angielaz, did you follow [these](https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger#set-up-apex-debugger) steps to set up the debugger?

**Comment by angielaz** [comment]
> Hi @angielaz, did you follow [these](https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger#set-up-apex-debugger) steps to set up the debugger?

Hey @CristiCanizales, yes I did. All sub steps of step number 4 of that page. Since I'm not using a scratch org, I'm using a developer sandbox, I jumped the steps to create a scratch org. Is this a correct assumption?

Let me know and thanks!

**Comment by CristiCanizales** [comment]
I believe you're missing the DebugApex permission, since you started in step 4.
Can you check that?? There's related info in #2737

**Comment by angielaz** [comment]
Hi @CristiCanizales, step 1-3 is related to create scratch orgs and yes.. I skipped those steps. I'm using a developer sandbox instead.
Step 4 is all about creating the Debug Apex permission set and yes.. I did that.
Here are some screen shots. 
Debug Apex permission set details,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/89082322-8097-47cc-b4d0-1cabb6275bd3)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/3f5d94c3-4f36-4cbd-9657-df738e3ab451)

I can also guarantee that I have just been upgraded to a Salesforce Unlimited, so, I should be able to use Apex Interactive Debugger. Right?

**Comment by diyer** [comment]
@angielaz can you provide the org id of the sandbox org you are trying to debug?

**Comment by angielaz** [comment]
> @angielaz can you provide the org id of the sandbox org you are trying to debug?

Hi @diyer, thanks for your attention.
My sandbox org Id is: 00DTA000000fVgN

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/d66a88b7-f205-4a55-9d8d-6841ac65dec6)

Let me know if anything else is needed.

**Comment by diyer** [comment]
@angielaz could not find anything suspicious in the logs. Are you consistently seeing this? Did you retry debugging?

**Comment by diyer** [comment]
Thanks @angielaz, while we continue to look into this, do you see anything in logs on your end?
F1 -> Show logs

**Comment by angielaz** [comment]
Sure @diyer, those were the only ones throwing errors,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/61c7eb12-56e8-4414-9a54-e245728f14cf)

Let me know if other logs are needed.. and if that explains something. Thanks!

**Comment by diyer** [comment]
Can you check if there is something in Extension Host logs?

**Comment by angielaz** [comment]
have a few warnings,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/7b451bcf-5ccf-4433-b79f-3f7bf67e6498)

**Comment by angielaz** [comment]
so, not sure I got it, but I've started the debugger from vs code and this was the only message that appeared on the Extension Host logs (the last line)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/b492417a-5d6b-401a-89e0-478e99e54fc8)

let me know if this corresponds with what you asked

**Comment by diyer** [comment]
This is very helpful @angielaz ! Our team will continue to dig into this and get back to you. The information you provided will be helpful to dig deeper. We will reach out to you if we need more information.

**Comment by CristiCanizales** [comment]
Hi @angielaz could you share the code you're trying to debug? We're trying to replicate issue with a very similar context than yours 🙌

**Comment by diyer** [comment]
@angielaz As Cristi said, it will be good if you could provide us the triggerHandler and the code that calls it (atleast the snippet where it is gets blocked) so we can reproduce it.

**Comment by angielaz** [comment]
Hey @diyer @CristiCanizales, don't think is specific of that code since even a simple unit tests fail do work.
If I run the unit test from VS code I get the error: "You cannot debug async requests".
If I run the unit test from the org, I get the same behaviour reported so far. See things in the debug console that seems to indicate that the debugger should be showing something but it doesn't and the error appears: "An unknown error occurred. Please consult the log for more details".
So, created a simple Unit Test, here is the code:
`@isTest
public with sharing class ApexDebuggerTest {
    
    @isTest
    private static void someTest() {

        Account acc = new Account(Name = 'Apex Debugger test');
        insert acc;

        Account accRetrieved = [SELECT Id, Name FROM Account WHERE Name = 'Apex Debugger test'];

        Assert.isNotNull(acc, 'An account should have been retrieved');
    }

}`

Run the tests from the developer console, since from VS Code I only get the error:  "You cannot debug async requests".

And the same behaviour happens. Stops on the first line but doesn't go further than that and the error appears: "An unknown error occurred. Please consult the log for more details"

Debug console shows this (I've "trace": "all" on my launch.json file): 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/23293c27-d619-41a6-a0f9-06b1e6e8d04b)

And this is what I see in the Extension Host Logs:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/4657d568-288a-41a3-9654-56a456f77adc)
 
The ones at 9h23 was using that test class.

Let me know and thanks.

**Comment by diyer** [comment]
@angielaz you mentioned you get the same error from Developer Console. Can you please attach a screenshot of that error?

**Comment by angielaz** [comment]
Hi @diyer, I might not have been very clear here. When I say I get the same error, I mean I get the same error I've reported since I opened this issue in VS Code (first image from my previous comment) also when I run the unit tests from developer console.
Why I had to do that? Because if I run the test from VS Code I get the "You cannot debug async requests" error instead (and in VS Code). 

Hope this clarifies.

**Comment by CristiCanizales** [comment]
@angielaz so having the debugging session in VSCode, you run the tests from the Developer Console and you get the same old error IN VSCode?

**Comment by angielaz** [comment]
> @angielaz so having the debugging session in VSCode, you run the tests from the Developer Console and you get the same old error IN VSCode?

@CristiCanizales Yes, exactly. Because if I run the test from VSCode I get "You cannot debug async requests" error instead (and in VSCode). like a pop up on the bottom corner in the right.

**Comment by angielaz** [comment]
@diyer @CristiCanizales We have just been upgraded to Salesforce Unlimited (which comes with the Apex interactive Debugger among other things) and we never use it before. I'm the first one in my team trying to use it. Could it be that we are missing some configuration? Something else? I don't know... it's weird... just a thought.

**Comment by diyer** [comment]
@angielaz  Can you take a look at this doc and make sure you have followed all the required steps. https://code.visualstudio.com/docs/editor/debugging

**Comment by angielaz** [comment]
@diyer Can't see anything there that I should have done and didn't. I've the Salesforce Extension Pack installed. Can see the Apex Interactive Debugger extension that came with the Pack. Created a launch.json file like it's mentioned here: https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger#set-up-apex-debugger

Here is my launch.json generated:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Apex Debugger",
            "type": "apex",
            "request": "launch",
            "userIdFilter": [],
            "requestTypeFilter": [],
            "entryPointFilter": "",
            "sfdxProject": "${workspaceRoot}",
            "trace": "all"
        }
    ]
}

I just changed sfdxProject to "${workspaceRoot}" as it's mentioned on salesforce apex debugger official site and add the trace:"all" because this debugger never worked for me and always retrieving the same old error and thought it could help me understand the problem. 

Any other step that you think I might have missed from that page?

**Comment by angielaz** [comment]
@diyer and @CristiCanizales don't know what else I can provide you in order to get this working, so, I made a video.

[Video 3-01 at 21.09 (1).webm](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/86854c76-7710-45e6-8f8c-d6981532097b)

**Comment by angielaz** [comment]
@diyer and @CristiCanizales don't know what else I can provide you so, I made a short video

https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/41969522-2028-459a-bb7e-8cc810cb0e93

**Comment by CristiCanizales** [comment]
Hi @angielaz, we're waiting for confirmation from owners but we think it actually has to do with the fact that you're not using a Scratch Org. Could you please try just following **all** steps [here](https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger#set-up-apex-debugger) and let us know if it works?
If you run into issues with steps 4.13, go to **Home > Setup > Users** and add the Permission Set there 
<img width="576" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/978f702e-a34f-4236-b15f-9266c917c198">

**Comment by diyer** [comment]
@angielaz Just noticed that in the screenshot you attached here https://github.com/forcedotcom/salesforcedx-vscode/issues/5454#issuecomment-1971732762 , the debugger seems to have hit the breakpoint you set at line 35 and has also loaded the variables. From what I understand you were not able to do that before?

**Comment by CristiCanizales** [comment]
hi @angielaz, just following up to check if you were able to successfully use the apex debugger with a scratch org?

**Comment by diyer** [comment]
@angielaz did you get a chance to take a look at above questions and suggestions?
1. try to use this on a scratch org following the steps here https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger#set-up-apex-debugger
2. In the screenshot you attached here https://github.com/forcedotcom/salesforcedx-vscode/issues/5454#issuecomment-1971732762 , the debugger seems to have hit the breakpoint you set at line 35 and has also loaded the variables. From what I understand you were not able to do that before?

**Comment by angielaz** [comment]
Hi @diyer @CristiCanizales I haven’t got the chance to try with a scratch org yet. Sorry. Will let you know once I do. Regarding suggestion/question 2 sometimes I can see all the bars etc but it’s just once and when I try to go further the same error appears. That’s is why I mention instanbility in this issue. But I could never fully debug a simple method. Hope this clarifies

**Comment by diyer** [comment]
Thanks for getting back @angielaz . I was looking for telemetry data fro your org but did not find any. Can you please ensure telemetry is turned on and run debugger again? that way we can get more information.

**Comment by angielaz** [comment]
Hi @diyer and @CristiCanizales I've tried with a scratch org and running the unit tests from VS Code returns this error:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/58b954b6-6caf-4ee4-b8c8-e43ec2ac6f79)

If I run the unit tests from the scratch org I get the same old error,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/90a090e1-909b-49a1-8935-6089a826ea88)

If I go back to my sandbox and turn Telemetry on, I tried:
1) to run the unit tests from VS Code and got the same,
I get the same error (You cannot debug async requests).
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/9ea54066-7198-4fc6-87c3-9eecb555c11c)

2) then I tried to run the unit test from the developer console and I got the same old error
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/4913dc2a-f8e8-4350-a505-9b52f25f9952)

let me know what you were able to see on the metrics. Thanks!

**Comment by diyer** [comment]
@angielaz Thank you for trying the suggested things! Can you provide the orgid of your scratch org please?

**Comment by angielaz** [comment]
Hi @diyer,
Scratch Org Id: 00DTA000000xIdd

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/5a6d9996-151e-4fa0-bcf2-7ec4853bcc03)

**Comment by diyer** [comment]
@angielaz Continuing to debug on this one, can you please try one thing. To see any errors that we aren't handling you can toggle the Developer console via the command pallet: 'Developer: Toggle Developer Tools'. That will open the dev tools where you can view the console for any errors being thrown. Can you please run apex debugger and copy paste this error that you see on Dev Tools Console?

**Comment by angielaz** [comment]
Hi @diyer, this was all I saw,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/a4f93b6c-6b76-4ac9-965d-07ae5ca23818)

Looking at the entire log on the Dev Tools Console since I open VS Code, starter the debugger session and run the unit test, if I  filter by that error appears nothing.

The only thing I saw was this error when I stop the debug session from vscode,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/31f9e462-dace-44fe-a4d8-95d025f374dc)

`ERR Invalid debug adapter: Error: Invalid debug adapter`

**Comment by CristiCanizales** [comment]
Hi @angielaz, could you try the following steps:
1. Log out from all authorized orgs
2. Delete .sf/.sfdx folders
3. Clone [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) repo
4. Open dreamhouse-lwc in VS Code and set up debugger in launch.json (with "trace": true)
5. Re-auth to your org
6. Launch debugger and try again
7. Share logs

**Comment by angielaz** [comment]
Hey @diyer  @CristiCanizales,
I'm using the scratch org that does not contain any of the code in my repository and deployed the code from the dreamhouse-lwc repository
I did what you requested and if I try to run a unit test in that code from vs code I get the same error "You cannot debug async requests"
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/85f05353-b7f0-4baa-a9fa-204bc297bf57)

If I run the unit test from the dev console I get the same old error,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/287e4458-8a14-43fa-864e-d2c1979f7a06)

I ran it again at the same happens.. it seems it's stuck but shows nothing on the debugger 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/81f7e402-8217-4352-904c-35cbc8481e29)

and when I click step over it shows the old error again.

This is the logs,
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/66647133/17182341-fca3-445f-a541-539b92873fde)

The latest error appears when I stop the debugger from vscode.

Don't think this is related to the project and I really appreciate your efforts, but maybe this is something on the org. If this is something over you reach, I'm happy to open a case directly with salesforce.

Let me know and thanks!

**Comment by diyer** [comment]
@angielaz thank you for trying this with the project we suggested that helps us eliminate the possibility that this is project specific issue. Since you are seeing this on a scratch org as well (in addition to your sandbox org), we doubt if this is a org specific issue. And with all the experiments done, it alludes to more of an environment issue. Has any one on your team been able to use the debugger?

**Comment by angielaz** [comment]
Hi @diyer, no, another colleague tried and got the same error.

**Comment by CristiCanizales** [comment]
hi @angielaz, did the other colleague use the same org to try?

**Comment by angielaz** [comment]
Hi @CristiCanizales, no, he use his sandbox and laptop and vscode etc

**Comment by CristiCanizales** [comment]
Hi once more @angielaz! Thanks for working with us to debug your issue. We need to dig into your situation a bit more deeper, so we’d like to add you to our IDE Friends Slack channel to collaborate more efficiently. Email our team at [svc_idee_bot@salesforce.com](mailto:svc_idee_bot@salesforce.com) and we’ll get you added to our customer channel.
If you’d like to continue working with us via GH instead, feel free to continue the conversation here. Thanks!

**Comment by angielaz** [comment]
Hey @CristiCanizales, email sent. Thanks!

**Comment by CristiCanizales** [comment]
As discussed with @angielaz, After a lot of debugging and tests, we came up with the conclusion that the issue is server side and suggested to file an investigation on Apex Team. Thank you again for your patience!
