### ISSUE TITLE
The execute code lens stopped working for apex files with .apex suffix after latest update v60.1.2

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/salesforcedx-vscode#5467]
### Summary

The execute code lens stopped working for apex files with .apex suffix. 

### Steps To Reproduce:

1.  Create a hello.apex in Script folder for any project
2.  Click on the execute or debug and an error pops "command 'sfdx.anon.apex.run.delegate' not found"

### Expected result

Able to click codeLens and execute the anonymous apex in a .apex file

### Actual result

error pops "`command 'sfdx.anon.apex.run.delegate`' not found"

### Additional information

Screenshot attacyed
<img width="1336" alt="Screenshot 2024-02-26 at 1 26 13 AM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/2276156/678564d4-fc54-4624-ac26-c5a85067cb71">

**Salesforce Extension Version in VS Code**:  v60.1.2

**SFDX CLI Version**: 2.25.7

**OS and version**: MACOSX, Using Code Builder

**VS Code version**:

**Comment by diyer** [comment]
This has been fixed in version 60.2.3
