### ISSUE TITLE
❓ Ask: Help Us Gather Slow Startup Performance Data

### ISSUE THREAD

**Issue by diyer** [forcedotcom/salesforcedx-vscode#5488]
We've spent the past few months investigating issues with startup performance and identified a few areas of change. While we've started to make some improvements, we need some more information from you!

In order to collect startup performance numbers, we want you to do the following -
1. In your VSCode, Hit F1/Open command Palette and select "Startup Performance." This will open an editor with all Startup Performance details like this -
 
<img width="1082" alt="Screenshot 2024-02-28 at 4 08 03 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/2521007/5a1f18f3-bf44-4131-98b4-4b4b06f568b7">

Please share cold activation vs non cold activation startup numbers. (The cold activation time is the first run of the extension after you install it. It tends to be slower than other times.)

2. Save the contents of Startup Performance to a file and attach the file to this issue.  Also attach a screenshot of Salesforce extension startup numbers from this tab.

3.  In addition, also provide us the following details -
**Salesforce Extension Version in VS Code**:
**OS and version**:
**VS Code version**:

Thanks again - your participation here will help us improve those Extension Pack load times for YOU!

**Comment by Coordona-Admin** [comment]
[Startup Performance - gbickel-nuage.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/14441283/Startup.Performance.-.gbickel-nuage.txt)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/156009544/8f3fa65b-b399-4654-aee4-7f248df29a46)

Running v60.2.3

**Comment by gbickel-nuage** [comment]
[Startup Performance - gbickel-nuage.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/14441312/Startup.Performance.-.gbickel-nuage.txt)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/61874251/371ec8f6-8324-473b-a1d6-c1958a94717f)

v60.2.3

**Comment by diyer** [comment]
@gbickel-nuage thank you! Appreciate the feedback. Can you also provide other details 
OS and version:
VS Code version:

**Comment by gbickel-nuage** [comment]
Sorry - missed that request:

Windows 11

VS Code About info:
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by diyer** [comment]
Thank you @jongpie! Looks like you are seeing very high load times , We will definitely reach out to you to test out few things when we have them ready to test.
cc: @mingxuanzhangsfdx

**Comment by paullinder-ctl** [comment]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/73713997/f0737514-ee29-45aa-869c-177d44e98909)

Salesforce Extension Version in VS Code: Salesforce Extension Pack (Expanded) v60.2.3

-------------- OS and version ---------------------------------------
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/73713997/c50db5e0-e4ae-4b93-85dd-5b6ea9f98f74)

-------VS Code version---------------
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/73713997/db8a9b2a-45a4-44f8-9842-cd2654f99f87)

**Comment by wharlen** [comment]
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/6704711/cf6c84e1-93ea-4d2e-bb53-0ecc47aced99)

**Log file**

[StartupPerformanceLog.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/14528826/StartupPerformanceLog.txt)

**VS Code Version**

Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by kaustubhdapurkar** [comment]
[vscode startup performance (non cold) - kaustubhdapurkar.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/14551268/vscode.startup.performance.non.cold.-.kaustubhdapurkar.txt)

[vscode startup performance (cold) - kaustubhdapurkar.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/14551323/vscode.startup.performance.cold.-.kaustubhdapurkar.txt)

non - cold
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/48684659/78b131d3-7a70-43b8-a44c-f7dc5ecf532f)


cold
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/48684659/914fafff-ac57-4536-a339-b29337c41ccd)


![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/48684659/9ab224e7-766d-48d1-ba1e-ab5438a34b0c)

**Comment by salesforcekorea** [comment]
[Startup Performance_20240418.log](https://github.com/forcedotcom/salesforcedx-vscode/files/15023437/Startup.Performance_20240418.log)


**Salesforce Extension Version in VS Code**
 v60.8.0

**OS and version: Edition:** 
Windows 11 Pro (x64)
Installed Date: 2023-‎03-‎19
OS Build: 22631.3447
Experience: Windows Feature Experience Pack 1000.22688.1000.0

**VS Code version**
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/133630120/4e48f864-cd08-4ef4-8265-4be105031c17)

**Comment by diyer** [comment]
Hi all, the latest version of our Salesforce extensions [60.12.0](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode&ssr=false#version-history) has gone through significant decrease in its size due to major upgrade to the version of @salesforce/core library. We would appreciate if you could take some time to compare this version and let us know how this impacts your startup time performance (hopefully in a good way:))!

@gbickel-nuage @jongpie @paullinder-ctl @wharlen @kaustubhdapurkar @melissajhansen @salesforcekorea

**Comment by kaustubhdapurkar** [comment]
Hey @diyer,

Below are the startup performance details after updating the extensions.

[cold.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/15273219/cold.txt)

[non-cold.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/15273221/non-cold.txt)

Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by tbugbee** [comment]
Hi @diyer, here are the stats from my machine. I collected 3 logs - warm with no SFDX, cold start w/ SFDX, warm start w/ SFDX.

## Logs
- Warm start (no SFDX installed): 
[Startup Performance_20240529_NoSFDX.md](https://github.com/forcedotcom/salesforcedx-vscode/files/15500002/Startup.Performance_20240529_NoSFDX.md)
- Cold start (SFDX installed): 
[Startup Performance_20240529_SFDX_Cold.md](https://github.com/forcedotcom/salesforcedx-vscode/files/15500009/Startup.Performance_20240529_SFDX_Cold.md)
- Warm start (SFDX installed): 
[Startup Performance_20240530_SFDX_Warm.md](https://github.com/forcedotcom/salesforcedx-vscode/files/15500023/Startup.Performance_20240530_SFDX_Warm.md)

## Screenshots
- Cold start screenshot (SFDX installed):
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/95641852/9c4af690-6855-46d6-8974-fbc00d243c48)
- Warm start screenshot (SFDX installed):
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/95641852/70cd15e8-ccee-4d8d-9287-76121dedb9e9)

## System Info
- Code: 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685)
- OS: win32(10.0.22631)
- CPUs: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz(8 x 2995)
- Memory(System): 31.69 GB(15.77GB free)
- Memory(Process): 349.94 MB working set(311.16MB private, 1.64MB shared)

## VSCode Info
- Version: 1.89.1 (user setup)
- Electron: 28.2.8
- ElectronBuildId: 27744544
- Chromium: 120.0.6099.291
- Node.js: 18.18.2
- V8: 12.0.267.19-electron.0
- OS: Windows_NT x64 10.0.22631

## Remarks
I'm glad the team is looking into performance, and it's great the team is engaging with the community for crowdsourced information. In its current state, the Salesforce extension pack is extremely inefficient, particularly the Apex extension. Every day begins with a 15-20 minute delay waiting for the extensions to load on a modern i7 machine with 32 GB RAM. This is totally unreasonable.

The performance issues are not limited to startup. At times, the greedy memory usage causes other extensions, such as source control, to hang and enter an unrecoverable state. I frequently disable most SFDX extensions if I know I'll be doing a lot of search + replace or git tasks. This is unfortunate because I then lose intellisense and reference/definition links.

Lastly, I think performance (mainly memory) issues are a likely root cause for other observed issues such as failed/hung starts for the Apex Language Server - see #1581, #5268 - not totally convinced, but I'm sure some of these would at least be less frequent for your user base if performance is improved.

**Comment by diyer** [comment]
@tbugbee Thank you for providing us with the performance details. I believe this result is with our latest extensions. 
Our team will engage with you soon to understand your use case better.

**Comment by tbugbee** [comment]
Thank you @diyer, I concur - I keep extensions and VSCode up to date as soon as they're released. I do not install any pre-release or beta channel updates, although I do have the Einstein For Developers (Beta) extension installed.

Would love to engage further, so please reach out!

**Comment by mingxuanzhangsfdx** [comment]
Hi folks @gbickel-nuage @jongpie @paullinder-ctl @wharlen @kaustubhdapurkar @melissajhansen @salesforcekorea @tbugbee Thank you so much for providing your valuable feedbacks. 

Recently we released a beta version v60.15.202405302148 of extensions available on [Github Tags](https://github.com/forcedotcom/salesforcedx-vscode/releases/tag/v60.15.202405302148). It contains the same functions as the latest version, but the total size of the extensions reduces by ~30% compared to v60.15.0 by bundling several dependencies of extensions. We encourage you to try out the beta version and provide your experience with us ☺️. 

## Installation Steps:
1. Download the zip file on [github](https://github.com/forcedotcom/salesforcedx-vscode/releases/tag/v60.15.202405302148).
2. Unzip the file and you will be able to see a list of vsix files in the folder like this
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/132491513/5090010c-32a7-4483-ae22-c97774cedfb6)
3. Open up your VS Code, click the `Extensions` sidebar and click `Install from VSIX` from the drop-down menu of `...`
<img width="814" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/132491513/f08a1355-5297-472b-85c0-c5ad8d8ac359">
4. Select all VSIX files from the folder you have in Step 2 to install, and make sure you have all beta extensions installed. You can check the versions on the detail tab of a extension (where you can tell from the version number).
<img width="1515" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/132491513/72cd64be-e5fc-4907-b951-490dfdf9861d"> 
5. Then you can open an sf project and start to use the beta extensions! 😊 

**Note**: We also do the beta release weekly, so please stay tuned on [Github Tags](https://github.com/forcedotcom/salesforcedx-vscode/tags) for the latest beta extensions. We will finally make the beta into general release after a couple of weeks.

## We Value Your Feedbacks
### Slack Channel Collaboration
Please reach out to me at mingxuanzhang@salesforce.com, so I can invite you to our team's collaboration channel for further discussion. 
### Share Your Metrics with Beta Extensions
Please also share the startup performance data of Beta Extensions on this thread as you did to help us make sense of the difference. 

We are looking forward to hearing from you!

**Comment by tbugbee** [comment]
Hi @diyer, here are the stats from my machine for the beta version.

## Logs
- Cold start: 
[Startup Performance_20240611_SFDX_Cold.md](https://github.com/user-attachments/files/15796289/Startup.Performance_20240611_SFDX_Cold.md)
- Warm start (SFDX installed): 
[Startup Performance_20240611_SFDX_Warm.md](https://github.com/user-attachments/files/15796292/Startup.Performance_20240611_SFDX_Warm.md)

## Screenshots
- Cold start screenshot:: 
![Startup Performance_20240611_Cold](https://github.com/forcedotcom/salesforcedx-vscode/assets/95641852/c95b2acf-442a-4ead-9d70-22e060a5e187)
- Warm start screenshot (SFDX installed): 
![Startup Performance_20240611_Warm](https://github.com/forcedotcom/salesforcedx-vscode/assets/95641852/4565c5ec-4451-47d4-aaec-7c673d01d6e8)

## System Info
- Code: 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573)
- OS: win32(10.0.22631)
- CPUs: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz(8 x 2995)
- Memory(System): 31.69 GB(11.32GB free)
- Memory(Process): 367.44 MB working set(344.44MB private, 1.64MB shared)

## VSCode Info
- Version: 1.90.0 (user setup)
- Electron: 29.4.0
- ElectronBuildId: 9593362
- Chromium: 122.0.6261.156
- Node.js: 20.9.0
- V8: 12.2.281.27-electron.0
- OS: Windows_NT x64 10.0.22631

## Remarks
This version seems to be a massive performance improvement. My observations are mainly qualitative, but with this beta version the extensions started in a reasonable timeframe. The slowest one is the CLI, which makes sense, but none of the extensions stick out compared to other startups, such as source control or gitlens.

This is a huge step in the right direction - thanks to the team for this update! Hope to see it on the main branch soon.

**Comment by paullinder-ctl** [comment]
@mingxuanzhangsfdx,

I've installed the beta extensions and immediately noticed improved responsiveness.

**Comment by diyer** [comment]
With almost 50 - 75% improvements seen in load time for our extensions, I am closing this thread. Please feel free to open a new issue for anything related to performance or continue to share your experience on this thread:) We would like to hear good things from our customers!
