### ISSUE TITLE
Error "There is no line breakpoint information for the current project" encountered when running command "SFDX: Update Checkpoints in Org"

### ISSUE THREAD

**Issue by Rossco236** [forcedotcom/salesforcedx-vscode#5491]
### Summary

Hi there,

I'm trying to use Apex Reply Debugger extension in VScode - i'm following the steps documented here for setting a breakpoint/checkpoint;

Set Breakpoints and Checkpoints
https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger#set-breakpoints-and-checkpoints

When I run the command "SFDX: Update Checkpoints in Org" after setting a breakpoint, I get the following output;

***********************************

Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
There is no line breakpoint information for the current project
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
SFDX: Update Checkpoints in Org, Step 4 of 6: Clearing existing checkpoints
SFDX: Update Checkpoints in Org, Step 5 of 6: Uploading checkpoints
SFDX: Update Checkpoints in Org, Step 6 of 6: Confirming successful checkpoint creation
Ending SFDX: Update Checkpoints in Org

***********************************

This only seems to occur after I **retrieve all apex class metadata** - the command works if I create a brand new project file and retrieve an individual class from the org + set & upload the breakpoint. 

Can you assist with this? Thanks.

### Steps To Reproduce:

1.  Retrieve all apex class metadata in an org with a sufficient amount of apex classes
1.  Set a breakpoint in any class + run the "SFDX: Update Checkpoints in Org" command 

### Expected result

Breakpoint should upload successfully 

### Actual result

Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
There is no line breakpoint information for the current project
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
SFDX: Update Checkpoints in Org, Step 4 of 6: Clearing existing checkpoints
SFDX: Update Checkpoints in Org, Step 5 of 6: Uploading checkpoints
SFDX: Update Checkpoints in Org, Step 6 of 6: Confirming successful checkpoint creation
Ending SFDX: Update Checkpoints in Org

### Additional information

_Feel free to attach a screenshot_.

![breakerror](https://github.com/forcedotcom/salesforcedx-vscode/assets/12642869/362c3347-900d-4634-8f62-364f2e6fecfc)

**Salesforce Extension Version in VS Code**: 60.2.3

**SFDX CLI Version**: @salesforce/cli/2.29.5 win32-x64 node-v20.11.0

**OS and version**: Windows 10 Enterprise

**VS Code version**: 1.87.0

Similar error is seen when attempting to set a checkpoint aswell: 

Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
There is no line breakpoint information for the current project
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
Checkpoints can be set on a valid line of Apex source. Invalid checkpoint location: URI=file:///c:/Users/ORiordanR/Desktop/Test/force-app/main/default/classes/AccountService.cls, Line=8
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again.

**Comment by peternhale** [comment]
@Rossco236 Looking at the screenshot of your source the line marked with a breakpoint does not appear to be a checkpoint. If you right click on the breakpoint symbol and change the expression to `checkpoint` set the cursor on the line where you want a checkpoint and open command palette and run `SFDX: Toggle Checkpoint`

Once set then update the checkpoints in your org.

<img width="885" alt="Screenshot 2024-03-05 at 11 22 06 AM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/17622511/a12f2d04-1d69-435e-95dc-a3212a2c4b20">

**Comment by Rossco236** [comment]
@peternhale thanks for looking into this.

Yes I also get a similar error when setting a checkpoint too which I noted in the additional information section - this is the error I get with checkpoint:

Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
There is no line breakpoint information for the current project
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
Checkpoints can be set on a valid line of Apex source. Invalid checkpoint location: URI=file:///c:/Users/ORiordanR/Desktop/Test/force-app/main/default/classes/AccountService.cls, Line=8
Ending SFDX: Update Checkpoints in Org
Your checkpoints have errors. Fix the errors listed in the output, then run SFDX: Update Checkpoints in Org again.


As I said the error isn't seen when setting a checkpoint at the same line of code after creating a new project and retrieving the class by itself initially - it's only seen after retrieving all apex classes within the org.

Thanks!

**Comment by peternhale** [comment]
@Rossco236 my attempt was on a project that exists and against an org (scratch org) where I have pushed the source.  I did not run into the same issue as you did. What kind of org are you working with?

**Comment by Rossco236** [comment]
@peternhale It's a Developer sandbox linked to an Unlimited edition production org. How many apex classes are within your project file may I ask? Thanks

**Comment by peternhale** [comment]
@Rossco236 I used [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) for testing.

**Comment by peternhale** [comment]
@Rossco236 We haven't heard from you since March. I am going to close this issue for now. Please file a new issue if you are still having difficuly.
