### ISSUE TITLE
Deploying from VS code to an org is extremely extremely slow. Takes 5+ minute for some small classes

### ISSUE THREAD

**Issue by UshaKiranSurapaneni** [forcedotcom/salesforcedx-vscode#5494]
### Summary

Deploying from VS code to an org is extremely extremely slow. Takes 5+ minutes for some small classes (Some as small as 5 constants and logic in apex class). Sometimes it takes even up to 20 minutes. 

### Steps To Reproduce:

1) Authorize an org in VS code
2) Open any apex class
3) Right-click --> SFDX: Deploy this Source to Org

The deployment starts and it takes 5+ minutes

### Expected result

The deployment should be done in very little time as there is not much in the class. 

### Actual result

The deployment is taking a lot of time for smaller classes

### Additional information

**Salesforce Extension Version in VS Code**: Using the latest version(60.2.3). Also tried  downgrading to 58.7.1, no luck

**SFDX CLI Version**: @salesforce/cli/2.30.8 darwin-×64 node-v20.11.1

**OS and version**: macOS Monterey 12.7.3

**VS Code version**: VS version 1.87.0

**Comment by peternhale** [comment]
@UshaKiranSurapaneni Could you lease share the type of org you are using for the deploy.

I would also as that you enable debug logging and try the deploy again.

In vs code
* open workspace settings 
* search for `SF_LOG_LEVEL`
* select `debug` from the pulldown
* exit vscode
* remove the existing log file from $HOME/.sf The log file names are timestamped with the current date. Remove the one for today
* start vscode

Run the the deploy again, waiting for it to complete
Exit vscode
post the log file on this issue.

**Comment by peternhale** [comment]
@UshaKiranSurapaneni I would also ask that you try the same operation with the cli in this way, to see if there is a significant difference in time to complete.

For example, to deploy a single class you can run `sf project deploy start --metadata ApexClass:<your class name here>`

**Comment by UshaKiranSurapaneni** [comment]
@peternhale Thank you for looking into this. I have requested the above info and I will also pass this workaround to see if it helps. Thanks again.

**Comment by UshaKiranSurapaneni** [comment]
@peternhale Attached is the log with both attempts as requested.
[sf-2024-03-08.log](https://github.com/forcedotcom/salesforcedx-vscode/files/14541812/sf-2024-03-08.log)

**Comment by peternhale** [comment]
@UshaKiranSurapaneni I only see one md deploy present in the log file.

Was the env var `SF_LOG-LEVEL` set properly?

**Comment by UshaKiranSurapaneni** [comment]
Looks like it is timing out 
{"level":40,"time":1709926249399,"name":"sf:TelemetryReporter","msg":"Connection to https://dc.services.visualstudio.com timed out after 1000 ms"}

**Comment by UshaKiranSurapaneni** [comment]
The log file shared by the customer has only that line in it
[sf-2024-03-08 (1).log](https://github.com/forcedotcom/salesforcedx-vscode/files/14542539/sf-2024-03-08.1.log)

**Comment by peternhale** [comment]
@UshaKiranSurapaneni let's have the customer try the command this way.

`sf doctor -c "sf project deploy start ...rest of the command"` The double quotes are required.

This will produce three files. Please attach to issue once complete.

**Comment by UshaKiranSurapaneni** [comment]
@peternhale please find the requested logs
[1709929450259-command-debug.log](https://github.com/forcedotcom/salesforcedx-vscode/files/14542963/1709929450259-command-debug.log)
[1709929450259-command-stdout.log](https://github.com/forcedotcom/salesforcedx-vscode/files/14542964/1709929450259-command-stdout.log)
[1709929450259-diagnosis.json](https://github.com/forcedotcom/salesforcedx-vscode/files/14542965/1709929450259-diagnosis.json)

**Comment by peternhale** [comment]
@UshaKiranSurapaneni thank you. So this shows that vscode and CLI are seeing approximately the same amount of time in the deploy, so I suspect this might be a server side issue.

**Comment by peternhale** [comment]
@UshaKiranSurapaneni I have one more thing I would like to try, via vscode.

* open vscode
* On the file being used for previous attempts, right click and choose `SFDX: Generate Manifest File`. The command will ask for a name (any name will do) and then create a package xml file with one entry. The file will be written to the `manifests` folder at the project root
* Locate the manifest, right-click and choose `SFDX: Deploy Source in Manifest to Org`
Provide the time taken to complete the command.

**Comment by UshaKiranSurapaneni** [comment]
Sure, Will do that. Thank you

**Comment by UshaKiranSurapaneni** [comment]
@peternhale please find the requested info

14:33:03.793 Starting SFDX: Deploy Source to Org === Deployed Source STATE FULL NAME TYPE PROJECT PATH ───────── ───────────────── ───────── ─────────────────────────────────────────────────────── Unchanged EmailAPIConstants ApexClass src/main/default/classes/EmailAPIConstants.cls Unchanged EmailAPIConstants ApexClass src/main/default/classes/EmailAPIConstants.cls-meta.xml 
14:39:36.289 ended SFDX: Deploy Source to Org

**Comment by peternhale** [comment]
@UshaKiranSurapaneni since this does seem to be a server side issue, I am going to close this. If further investigation points back to client side processes, please feel free to reopen.
