### ISSUE TITLE
Extension nt issue

### ISSUE THREAD

**Issue by kowshik8032** [forcedotcom/salesforcedx-vscode#5497]
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `60.1.2`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.70.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
Extension is not populating the already authorized orgs. and its being unresponsive for too long.
<img width="760" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/55626263/e4f434d0-4148-462f-90c5-868df260f733"> - unresponsive
<img width="489" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/55626263/113bbc50-3fd0-4572-ac72-b81354dadd66"> - No Org Available

**Comment by daphne-sfdc** [comment]
Hi @kowshik8032, This is happening because your VSCode version is no longer supported.  The Salesforce Extensions support VSCode version 1.82.0 and above.  Can you update your VSCode and try again?

**Comment by daphne-sfdc** [comment]
@kowshik8032 Follow up to my original post - did updating VSCode solve the issue for you?

**Comment by daphne-sfdc** [comment]
Closing this issue as we have received no response from the customer in 2 weeks.
