### ISSUE TITLE
SFDC Retrieve doesn't work on an Indvidual component or folder. 

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [forcedotcom/salesforcedx-vscode#5509]
Steps to Reproduce 
----------------------
1. Create Project with manifest 
2. Authorize a Dev Org & retrieve components using package.xml
3. Now right click on any particular component from the extracted metadata & Select " SFDC Retrieve Source from Org"

Expected Result 
----------------
Metadata should be refreshed from the org & success message should appear. 

Actual Result
-------------
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/44530191/cb646bae-ba58-4386-8b66-0b839e76c842)

Note : Able to do the same operation using Salesforce CLI on CMD.

**Comment by Yuvarajsfcloud** [comment]
Any update on this ?

**Comment by daphne-sfdc** [comment]
Hi @Yuvarajsfcloud,
I wasn't able to replicate your issue using dreamhouse-lwc on the latest version of the Salesforce extensions.  Can I get some info and logs from you?

1. Version of Salesforce Extensions
2. Version of Salesforce CLI (run `sfdx --version` in Terminal)
3. Version of VSCode
4. OS and version of computer
5. Contents of **sfdx-project.json**
6. Contents of **package.xml** manifest file in your project
7. Contents of Problems tab
8. Contents of Output tab (select **Salesforce CLI** from the dropdown)
9. Contents of logs from running `Developer: Toggle Developer Tools` in the command palette

**Comment by daphne-sfdc** [comment]
What I find unusual is that your **package.xml** manifest file contains minimal content.  When I ran `SFDX: Create Project with Manifest` this is the manifest file that got automatically generated:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTestSuite</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>59.0</version>
</Package>
```

I suspect that caused your initial retrieve to not contain all the files you needed, which led to that error message on subsequent retrieves.

Can you try replacing your **package.xml** manifest file with what I gave you, retrieve all the contents from the manifest, and then try retrieving one component again?

**Comment by daphne-sfdc** [comment]
@Yuvarajsfcloud Follow up message - did the provided solution solve the problem for you?

**Comment by debprotim** [comment]
@Yuvarajsfcloud this was the exact error I was getting and it was because of the mapped location where the project files are located. I raised a case for the same and it just got resolved in the last release. So please update Salesforce Integration CLI extension on VSCode to latest version(v60.5.1). For all the details follow this case:
https://github.com/forcedotcom/salesforcedx-vscode/pull/5507
