### ISSUE TITLE
❗️❗️SFDX: Authorize an Org commands will fail with Chromedriver v123 -> incompatible with Salesforce CLI

### ISSUE THREAD

**Issue by daphne-sfdc** [forcedotcom/salesforcedx-vscode#5514]
Hello Customers,

We found out today that Chromedriver v123 is incompatible with Salesforce CLI.  Users with Google Chrome as their default browser and Chromedriver v123 will see an `Error (1): Invalid request method: OPTIONS` error when they try to authorize to an org, both via the CLI and via the Salesforce Extension Pack in VSCode.
![Screenshot 2024-03-21 at 11 19 19 AM](https://github.com/forcedotcom/salesforcedx-vscode/assets/139700604/61836251-3d8f-45d9-a9af-6fd262809ade)

The CLI Team is currently investigating this issue.  As a workaround, users who did yesterday's Google Chrome update to v123 can temporarily switch to a different browser, or if possible, downgrade Google Chrome back to v122.

Sorry for the inconvenience!

**Comment by cristiand391** [comment]
Quick update: we got a fix for this in latest-rc of the CLI:
https://github.com/forcedotcom/cli/issues/2785#issuecomment-2016028989
