### ISSUE TITLE
Add setting to change the StatusBar color when working in a production org

### ISSUE THREAD

**Issue by PierreVanobbergen** [forcedotcom/salesforcedx-vscode#5517]
**Is your feature request related to a problem? Please describe.**

When developing in VS Code, we often switch between the dev org and the production org to retrieve and compare files.
It sometime happens that we push code by mistake to the wrong org. It's okay with Apex classes as it launch the test classes automatically in production, but with Visualforce components or LWC it uploads it right away.

**Describe the solution you'd like**

A setting that changes the StatusBar color if the default org is the production one (Checkbox).
Another setting to choose what color is used (Hexadecimal input) 

**Describe alternatives you've considered**

I've considered changing the ActivityBar into another color, or the StatusBarItem that displays the current org, but I think it would be too big and too subtle respectively.

**Additional context**

The idea comes from this extension: https://chromewebstore.google.com/detail/org-header-for-salesforce/bhnfbnhpmnfacebccnjjoeecgmnbhjam

I already implemented it to test if it could be done, I came up with this:

https://github.com/forcedotcom/salesforcedx-vscode/assets/37369168/9313f325-6b4b-4221-a212-7c129d6c11e1

Let me know if you would be interested by.a PR!

**Comment by daphne-sfdc** [comment]
Hi @PierreVanobbergen, This is a great improvement that can prevent many unintentional deploys.  Yes, we are interested in this and will be happy to review your PR! 😁

**Comment by diyer** [comment]
Hi @PierreVanobbergen, thank you for your contribution! Please read our [contributing guide](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/CONTRIBUTING.md) and submit this PR again with all the required information.
