### ISSUE TITLE
Apex extension stopped working in big repos

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/salesforcedx-vscode#5529]
### Summary

Since a couple of weeks / maybe days, most of the functionality of the apex extension stopped working in our main repo.

We have a big organization with a lot of apex classes (7000 apex classes), I think this has something to do, because in a smaller org that we have, it works as always

I'm unable to:

- Use the lightning replay debugger
- Use the get debug logs
- Autocompletion
- Execute anonymous apex
- Run tests from file, as the option does not appear under the decorators
- List test classes

Deployment / retrieval, seems to be working, soql is also working

### Steps To Reproduce:

1.  Run any of those commands

### Expected result

The commans to work

### Actual result

The commands not working, it appears the activating extensions bottom bar action for a couple of seconds and the disappear

### Additional information

working repo

![WORKING](https://github.com/forcedotcom/salesforcedx-vscode/assets/10410852/cbe9b07b-90e2-4f24-8bd9-a9a3f47cbf31)

not working repo

![Grabación de pantalla 2024-04-05 a las 17 23 36](https://github.com/forcedotcom/salesforcedx-vscode/assets/10410852/b1b1df7b-abbf-4fed-b78c-391d0bf0fcfc)

![execute anonymous](https://github.com/forcedotcom/salesforcedx-vscode/assets/10410852/4fd1dd02-81ed-45a1-a5cf-171e6aa1604c)

**Salesforce Extension Version in VS Code**: v60.7.0

**SFDX CLI Version**: @salesforce/cli/2.35.6 darwin-arm64 node-v20.11.1

**OS and version**: mac os sonoma 14.4.1

**VS Code version**: 1.88.0

**Comment by mingxuanzhangsfdx** [comment]
Hi @mnunezdm , could you pop up command palette (cmd+ shift + p), choose `Developer: Show Running Extensions` and see if all salesforce extensions have been loaded (from you info, it looks like Apex, Apex Replay Debugger are failing)?

Then could you pop up command palette (cmd+ shift + p), choose `Developer: Toggle Developer Tools` and see if there are any errors?

Also, could you check the output of Apex Language Server (pop up with cmd + shift + u) and any other extensions and see if there are errors?

**Comment by mnunezdm** [comment]
Hello!

Apex is in activating state

<img width="1149" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/10410852/8ae8252c-98b0-4e61-aa2c-5497f958e367">

I cannot find the apex replay debugger, but I think that extension is launched after the Apex one

The only warning I could find related to this is in the developer toots is this one

```
 WARN [mainThreadStorage] large extension state detected (extensionId: salesforce.salesforcedx-vscode-core, global: true): 1348.978515625kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.
```

**Comment by mnunezdm** [comment]
I tried renaming the .sfdx folder in my workpsace and automatically the get apex debug logs started working

**Comment by daphne-sfdc** [comment]
What is your Java version?  We currently support Java 11 and 17.  If you have a supported Java version, try the below:

Since this is looks like a project-specific issue, can you do the following to get your project into a very clean state?

1. In the Explorer view of the sidebar, delete the `.sfdx` and `.sf` folders.
2. Run `Developer: Reload Window` from the command palette.
3. Re-authorize to your org.

Then check again to see if your Apex extension is able to activate.

**Comment by mnunezdm** [comment]
Hello!

I have found what was causing the plugin to stop working after a while

This has something to do with the SOBject refresh, I had this setting active in my project `salesforcedx-vscode-core.enable-sobject-refresh-on-startup` and some minutes after deleting the .sfdx/.sf folder and reloading window the plugin stopped working again

Disabling that check makes the plugin to stop failing

**Comment by peternhale** [comment]
@mnunezdm I was wondering in you could enumerate the exact steps you are taking to get the vscode session into a bad state.
