### ISSUE TITLE
SFDX: Authorize an Org failed to runv

### ISSUE THREAD

**Issue by Tanishagodha** [forcedotcom/salesforcedx-vscode#5536]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by daphne-sfdc** [comment]
Hi @Tanishagodha,

Please update this issue and provide us with all the details requested in the template of the issue. We ask for them precisely to have some context, because otherwise it is almost impossible to help users. Thanks in advance!

**Comment by EEDAG** [comment]
Hi everyone,

I am getting below error when i try to connect my org. Any helps would welcome

11:55:47.420 sf org:login:web --alias VSCodePlayground --instance-url https://login.salesforce.com --set-default
'sf' is not recognized as an internal or external command,

**Comment by peternhale** [comment]
@EEDAG this error indicates that the Salesforce CLI is either not installed or on the path.

We have recently dropped support for the previous cli, `sfdx`, which requires all customers to move to the the `sf` cli. Please see [Move from sfdx (v7) to sf (v2)](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm) for instructions on how to migrate.

**Comment by EEDAG** [comment]
Hi @peternhale Salesforce CLI installed only in Visual Studio Code. Should it have been installed in computer as well?

**Comment by EEDAG** [comment]
@peternhale actually now I have different issue regards of Java version needs to be at least version 11.

**Comment by peternhale** [comment]
@EEDAG I am going to close this issue. Please reopen or file a new issue if you continue having difficulty.
