### ISSUE TITLE
sfdx apex:test:run command in CI passes run with lower test coverage

### ISSUE THREAD

**Issue by kamilkhalid123** [forcedotcom/salesforcedx-vscode#5545]
Hi,

I am using sfdx apex:test:run -y -r human \-w 160 \-c command for running apex tests, My code coverage falls below 70 and the test run step passes. I want it to fail when the test coverage falls below 75%. Can someone help in this?

**Comment by peternhale** [comment]
@kamilkhalid123 We would be happy to help, but to better assist you, please provide the information requested in the template used for raising a new bug.

**Comment by CristiCanizales** [comment]
Closing this as a new issue (#5547) was created with the details requested.
