### ISSUE TITLE
The unpackaged Apex tests execution after unit tests execution should fail when the code coverage is less than 75%

### ISSUE THREAD

**Issue by kamilkhalid123** [forcedotcom/salesforcedx-vscode#5547]
### Summary

I am using sfdx apex:test:run -y -r human -w 160 -c command for running apex tests, My code coverage falls below 70 and the test run step passes. I want it to fail when the test coverage falls below 75%. Can someone help in this?

### Steps To Reproduce:

1. Perform Code commit
2. Unit tests trigger
3. Check the unpackaged Apex tests execution step in the unit test step results

### Expected result

The step: unpackaged Apex tests execution after unit tests execution should fail when the coverage is less than **75%**

### Actual result

The coverage is 73% and the step is passing.

The command for this in config.yaml is  sfdx apex:test:run -y -r human -w 160 -c 
### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by peternhale** [comment]
@kamilkhalid123 thank you, but we will also need the following
Additional information
Feel free to attach a screenshot.

Salesforce Extension Version in VS Code:

SFDX CLI Version:

OS and version:

VS Code version:

**Comment by CristiCanizales** [comment]
Hi @kamilkhalid123, again, we need all the details asked in the template to be able to contextualize your issue. Please provide the following:
- Salesforce Extension Version in VS Code:
- SFDX CLI Version:
- OS and version:
- VS Code version:
