### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by gamatibrightcove** [forcedotcom/salesforcedx-vscode#5558]
Hi Team,

In Visual Studio Code, since installing the latest version of the package: V60.10.0 I noticed that the 'Saving' process which also includes finding conflicts with the version of the APEX class in the Salesofrce Full Sandbox is very very slow. This is my environment:

VSCode Version: 
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

I don't know why VSCode says I'm on the OS Darwin, I'm on SONOMA os M1 MacBook pro.

This is becoming and issue impacting my productivity.

Thank you,
GC

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by diyer** [comment]
@gamatibrightcove is this still an issue? Can you please give us proper repro steps and more details to look into the issue?
Attach a video if you.

**Comment by gamatibrightcove** [comment]
Saving to the Salsesforce sandbox seems improved since I disabled the 'Conflict detection'. My Salesforce extension are now on Version 60.15.0
The only issue still persist is with the Apex Debugger which I don't think it's working correctly.
GC

**Comment by diyer** [comment]
Thank you @gamatibrightcove . We are aware of Apex Debugger issues and we are actively working towards its resolution. This is a link to our known issue https://issues.salesforce.com/issue/a028c00000zI0Q6AAK/apex-debugger-fails-with-unknown-error-when-debugging-certain-orgs

We will close this issue given you are not seeing the performance issue with Save.
