### ISSUE TITLE
The test class runs very slowly

### ISSUE THREAD

**Issue by zt15242** [forcedotcom/salesforcedx-vscode#5559]
Recently, we found that the test class is running very slowly and even fails to compile. Has anyone encountered the same situation? Please guide us on how to solve it.
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/74717483/e8c78e3d-9135-4c31-93c1-b100cc6a9ccd)

**Comment by zt15242** [comment]
Hi Team,
Salesforce Extension Version in VS Code: 60.10.0
Salesforce CLI Version: 60.10.0
OS and version:Windows10
VS Code version:1.88.0(system setup)

I checked the system and found that disabling parallel vertex testing is checked

**Comment by mingxuanzhangsfdx** [comment]
Hi @zt15242 - 

Where do you run the apex tests from? Developer console or the VS Code extensions?

Also please let us know what the exact compilation errors are.

**Comment by zt15242** [comment]
Hi @mingxuanzhangsfdx 
We can reproduce this issue when running test classes in the developer console or VS code extension.
At present, it only operates slowly with a long cycle.

**Comment by peternhale** [comment]
@zt15242 Given you are seeing the slow runs in both dev console and vscode, I would suggest contacting Salesforce Support as this appears to be a server side issue.
