### ISSUE TITLE
Error when the command npm i @salesforce/lwc-dev-server

### ISSUE THREAD

**Issue by olmalambo** [forcedotcom/salesforcedx-vscode#5564]
### Summary
 when i try to execute the command this message appear 
Error :

npm ERR! code 1
npm ERR! path C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node build.js || nodejs build.js
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   fibers.cc
npm ERR! C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(27,65): error C2838: 'kFinalizer': illegal qualified name in member declaration [C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
npm ERR! C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(454): message : see reference to function template instantiation 'void uni::MakeWeak<void Fiber::WeakCallback(void *),v8::Object,void>(v8::Isolate *,v8::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>> &,P *)' being compiled [C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
npm ERR!           with
npm ERR!           [
npm ERR!               T=v8::Object,
npm ERR!               P=void
npm ERR!           ]
npm ERR! C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers\src\fibers.cc(27,1): error C2065: 'kFinalizer': undeclared identifier [C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers\build\fibers.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@19.9.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "C:\Users\OlgaM\AppData\Local\Programs\Python\Python311\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.34729.46) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\OlgaM\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\OlgaM\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\OlgaM\\node_modules\\@wdio\\sync\\node_modules\\fibers\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\OlgaM\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\OlgaM\\AppData\\Local\\node-gyp\\Cache\\19.9.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\OlgaM\\AppData\\Local\\node-gyp\\Cache\\19.9.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\OlgaM\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\OlgaM\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\19.9.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\OlgaM\\node_modules\\@wdio\\sync\\node_modules\\fibers',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\OlgaM\\node_modules\\@wdio\\sync\\node_modules\\fibers\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\OlgaM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\OlgaM\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd C:\Users\OlgaM\node_modules\@wdio\sync\node_modules\fibers
npm ERR! gyp ERR! node -v v19.9.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! 'nodejs' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\OlgaM\AppData\Local\npm-cache\_logs\2024-04-30T21_19_40_787Z-debug-0.log
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**Salesforce CLI Version**: In the command Line

**OS and version**:

**VS Code version**:

**Most recent version of the extensions where this was working**:

**Comment by mingxuanzhangsfdx** [comment]
Hi @olmalambo Please refer to https://developer.salesforce.com/tools/vscode/en/localdev/set-up-lwc-local-dev and let me know the result

**Comment by peternhale** [comment]
@olmalambo Would you also provide the answers to the questions posed in the issues template.
