### ISSUE TITLE
Not getting Autocomplete of Aura Component

### ISSUE THREAD

**Issue by khushbu167** [forcedotcom/salesforcedx-vscode#5573]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

Not getting extension for Aura

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**Salesforce CLI Version**:

**OS and version**:

**VS Code version**:

**Most recent version of the extensions where this was working**:

**Comment by khushbu167** [comment]
While writing a code of Aura i am not getting auto complete for Aura component.I have already installed Salesforce CLI & under that Aura component also seems installed.

**Comment by mingxuanzhangsfdx** [comment]
Hi @khushbu167 - 

Please first check if the extension has been loaded successfully
1. Pop up the command palette 
2. Type in `> Developer: Show Running Extensions`
3. Check if Aura Components activates successfully

If it is activated - 
Can you send us any error messages you see in the following places?

1. Problems tab
5. Output tab under the Aura Language Server dropdown option
6. Run Developer: Toggle Developer Tools from the command palette

Also please elaborate the steps to reproduce the issue for us to help you.

**Comment by peternhale** [comment]
@khushbu167 In addition to the information @mingxuanzhangsfdx requested, could you also provide the information requested in the issue template.

**Comment by khushbu167** [comment]
Hi @mingxuanzhangsfdx  : I have verified the extension in the pallet, and it seems to be activated. I downloaded it using Salesforce CLI. 

The auto-complete feature is functioning for all extensions such as LWC and APEX. However, I'm encountering problems with the Aur extension only. Please see the attached screenshots for further details.

![VsCodeScreenShot](https://github.com/forcedotcom/salesforcedx-vscode/assets/165386930/a9563b86-0e72-4f8f-8089-d5eee5e156ff)
![Aura enabled](https://github.com/forcedotcom/salesforcedx-vscode/assets/165386930/fe16c08a-9368-424a-8e23-c278a0d411bb)

**Comment by daphne-sfdc** [comment]
Hi @khushbu167, What other extensions do you have installed?  We don't have the `aura-layout` snippet defined in the code of our extensions, so I suspect you're getting that snippet from another extension.

**Comment by khushbu167** [comment]
Hi @daphne-sfdc  : i have installed all packs available under Salesforce Extension pack.i.e. Visualforce , Lightning web coomponent , Aura etc...

**Comment by daphne-sfdc** [comment]
@khushbu167 Those are the only extensions you have installed?  No other non-Salesforce extensions?

**Comment by khushbu167** [comment]
@daphne-sfdc : I have only alesforce extension pack & java extension pack installed.

**Comment by CristiCanizales** [comment]
Hi @khushbu167, does this happen with previous versions of the extensions as well? You can try downgrading here 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/d854336f-ea4b-4b95-9f21-e69c98041ea7)
