### ISSUE TITLE
Sandbox authentication from vs code

### ISSUE THREAD

**Issue by sfsagar** [forcedotcom/salesforcedx-vscode#5577]
Hi All,

I am trying to connect vs code to Salesforce Dev sandbox but i enter custom domain and org name details click enter
 Then in browser the login page open but then suddenly the below error appears in my screen 
![17150147430847062026430879856187](https://github.com/forcedotcom/salesforcedx-vscode/assets/97340699/3e81c1ce-9d04-4f84-b2e2-6ca86adb81bb)
![IMG_20240506_223339](https://github.com/forcedotcom/salesforcedx-vscode/assets/97340699/8f337b21-d7e5-4c7e-8f36-1367cd2e63bf)

Intresting thing is if I try to connect with my other sandbox like INT,QA,UAT they get authenticate properly and able to connect vs code.
Only facing issues while connecting to Dev sandbox, what could be the reason. Really appreciate someone input to resolve the issue

**Comment by peternhale** [comment]
@sfsagar would you mind providing the information requested in the issue template? I will be happy to help once I have the needed information.

**Comment by sfsagar** [comment]
@peternhale 
Steps to produce-
1. Authorize an org command--> Entered Domain -->enter name in vs code--> in edge browser login page open gained used custom domain --> sso log in user, 
2. It should able me to open the Dev sandbox --> but getting the above error attached in question 

Soon will share the required version of all app requested.But just FYI I can able to authorise othe sandbox but not dev

**Comment by peternhale** [comment]
@sfsagar I would suggest trying again but use -r https://test.salesforce.com instead of instance URL. Could you provide the org id of the org you are trying to auth to?

**Comment by peternhale** [comment]
@sfsagar were you able to try the suggestion?

**Comment by sfsagar** [comment]
On Monday will check and confirm.

Thank you
