### ISSUE TITLE
Retrieve source results are two times bigger because of "xml" shifted to next line (see picture inside)

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/salesforcedx-vscode#5580]
### Summary

When I retrieve the source based on package.xml using SFDX: Retrieve Source in Manifest from Org
<img width="245" alt="2024-05-07_13h14_07" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5740564/9b1cb63c-9676-47be-96f0-52f81cb72e1f">
then despite of window being wide enough (as I am using 4k display with 150% scaling factor) "xml" file extension is moved to next line which results in additional lines added which is not needed.
<img width="1555" alt="2024-05-07_13h08_36" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5740564/23b20415-a0e1-41d9-879d-73b15e5031ed">

### Steps To Reproduce:

1.  Retrive source from Package.xml using the context menu SFDX: Retrieve Source in Manifest from Org
1.  Check results window 

### Expected result

"xml" is at the end of the line as there is enough space:
CustomLabels                                                                             CustomLabels              force-app\main\default\labels\CustomLabels.labels-meta.xml     

### Actual result

Text is wrapped at last dot (.) and "xml" is in new line:
CustomLabels                                                                             CustomLabels              force-app\main\default\labels\CustomLabels.labels-meta.
xml     

### Additional information

**Salesforce Extension Version in VS Code**:v60.11.0

**Salesforce CLI Version**:@salesforce/cli/2.39.6 win32-x64 node-v20.12.2

**OS and version**:Widnows 11

**VS Code version**:1.89.0

**Comment by peternhale** [comment]
@PawelWozniak Would you mind sending the full text of the results instead of a screenshot?

**Comment by PawelWozniak** [comment]
@peternhale Here is a short example as full log contains too much confident names that describes system configuration. 
`11:20:48.278 Starting SFDX: Retrieve Source from Org

=== Retrieved Source
FULL NAME                                                                                TYPE                      PROJECT PATH                                                                                                                                
───────────────────────────────────────────────────────────────────────────────────────  ────────────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────                                                                   
NewContractButtonOverride                                                                ApexPage                  force-OppsAndContracts\main\default\pages\NewContractButtonOverride.page                                                                    
NewContractButtonOverride                                                                ApexPage                  force-OppsAndContracts\main\default\pages\NewContractButtonOverride.page-meta.xml                                                                                                                                                    
Account_Status_Path                                                                      PathAssistant             force-app\main\default\pathAssistants\Account_Status_Path.pathAssistant-meta.xml                                                            
Lead_Path                                                                                PathAssistant             force-Leads\main\default\pathAssistants\Lead_Path.pathAssistant-meta.xml                                                                    
Opportunity_Path                                                                         PathAssistant             force-OppsAndContracts\main\default\pathAssistants\Opportunity_Path.pathAssistant-meta.xml                                                  
LeadConvertSettings                                                                      LeadConvertSettings       force-app\main\default\LeadConvertSettings\LeadConvertSettings.LeadConvertSetting-meta.xml                                                  
CustomLabels                                                                             CustomLabels              force-app\main\default\labels\CustomLabels.labels-meta.xml                                                                                  

11:22:53.982 ended SFDX: Retrieve Source from Org
`

I spotted something that can help.
When the terminal window is too small then the last bar ( _______________ ) for PROJECT PATH is moved to a new line and XML extensions too. Also, PROJECT PATH is splitter to PROJECT <new line> PATH
<img width="1535" alt="2024-05-08_11h37_56" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5740564/d10903aa-6ccd-4d32-9ca0-e4790b2780ad">

When I make it very wide then all is fine
<img width="1623" alt="2024-05-08_11h40_16" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5740564/a613ab2b-36fe-491a-9d23-d5f65e5e8543">

**Comment by peternhale** [comment]
@PawelWozniak as you discovered, the table output will wrap when the maximum row length exceeds the terminal's width and when the terminal's width is wide enough the lines are not wrapped.

There are only a few choices here to "fit" a row into and given width; truncation (not desirable) or some sort of column reduction that attempts to retain enough information to properly communicate the data w/o loss of understanding. A typical version of this would be to retain the beginning and ending text and replace the center with "...".

I would like to close this issue given your discovery. If you would like us to entertain a feature request or create a PR to provide a "fitting" solution, we always welcome contributions.

**Comment by PawelWozniak** [comment]
@peternhale I think that making this bar shorter would help. If you don't want to spend time on this issue I will experiment with that at some time later.

**Comment by peternhale** [comment]
I believe the bar length for each column is the same length as the max length of the column data, so not sure that changing the bar length itself will solve the wrapping issue. If you would like to submit a PR we would be happy to accept the contribution.
