### ISSUE TITLE
Internal error wit Replay Debugger

### ISSUE THREAD

**Issue by rssrys03** [forcedotcom/salesforcedx-vscode#5601]
Type: <b>Bug</b>

Try to run the Salesforce Apex Replay debugger and get an internal error warning

Extension version: 60.10.0
VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|18.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 19052945-3527-4577-8394-707fc08df6a3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31049070
fchga941:31046352
pythonprc:31047982
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by daphne-sfdc** [comment]
Hi @rssrys03, 
I have some questions for you:
1. What is the internal error warning that you are seeing?  Can you send us a screenshot of that?
2. How are you running the Apex Replay Debugger?
3. What kind of org are you using?  (Sandbox, scratch org, production, or Trailhead Playground?)
4. What is your Salesforce CLI version?  (Run `sf --version` in your Terminal)
5. What do you see when you run `Developer: Toggle Developer Tools`?
6. Do you have any errors in your Problems tab?
7. What is in the Output tab when you select "Apex Replay Debugger" from the dropdown?

Also, we released v60.13.0 of our extensions yesterday.  Please update your extensions to the latest version.

**Comment by rssrys03** [comment]
Hello! I am just getting a warning saying "Internal Error" and nothing more than that message. It happened when clicking the "Launch Replay Apex Debugger" option in a debug log file.

After some research it was a problem with java memory. I had to update the sfdx java memory to 4096

**Comment by daphne-sfdc** [comment]
Hi @rssrys03, Thank you for the update, and I'm glad to hear you have resolved the problem.  I'm going to close this issue.
