### ISSUE TITLE
`<style>` tag breaks VF Language Server

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#5602]
### Summary

Adding a `<style>` tag to a VF page breaks the VF language Server in vscode.

### Steps To Reproduce:

1.  Create a new VF page
1.  Add this content

```
<apex:page applyHtmlTag="false"  showHeader="false" sidebar="false" standardStylesheets="false">
    <html>
        <head>
            <style> body { font-family: 'Arial Unicode MS'; } </style>
        </head>
    </html>
</apex:page>
```
3. Save 

### Expected result

There should be no issues and the language server should continue to work

### Actual result

The end of the style tag gets marked with a red syntax error (but no "problem").  After saving, the following error when be output:
```
[Error - 2:02:13 PM] Request textDocument/rangeFormatting failed.
  Message: Request textDocument/rangeFormatting failed with message: js_source_text is not defined
  Code: -32603  
```

When this happens, prettier formatting no longer works.

### Additional information
<img width="738" alt="QuoteContract_page_—_realself" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5217568/aec0bb02-627b-47af-818d-15ba3c13477a">

**Salesforce Extension Version in VS Code**: v60.13.0

**Salesforce CLI Version**:  @salesforce/cli/2.41.8 darwin-arm64 node-v20.12.

**OS and version**: OSX

**VS Code version**: 1.87

**Most recent version of the extensions where this was working**: No idea

**Comment by daphne-sfdc** [comment]
Hi @ChuckJonas, We are aware of this issue - it's the same one as https://github.com/forcedotcom/salesforcedx-vscode/issues/5593 which was also filed this week.  We have filed a bug for this in our backlog from the previous issue and will add this occurrence to our bug.

Closing this issue, as it is a duplicate issue.
