### ISSUE TITLE
Debug test(s) failed to run

### ISSUE THREAD

**Issue by cpaafd** [forcedotcom/salesforcedx-vscode#5608]
**Is your feature request related to a problem? Please describe.**
When trying to launch Debug for any test method on Full sandbox org - I get "Debug test(s) failed to run message, no logs are saved in project folder. 
The tests run normally. Happens for org refreshed last November, other old (2022) and new development orgs are fine, PROD is fine. Happens for other sf admins as well on the org. Happens for all test methods.
Apex Interactive Debugger: v60.13.0
Salesforce Extension Pack v59.9.0
VS Code: 1.89.1

The problem seems to be there for last two months. I do not recall performing any updates to extensions or vs code manually.

**Describe the solution you'd like**
 Please help or at least let me know where I can go with the problem or where I can find any logs on VS debug functionality to debug by myself at least.

**Describe alternatives you've considered**
There are really no alternatives except from putting every variable in assert to find out what it is but this obviously no long-term solution.

**Additional context**

**Comment by daphne-sfdc** [comment]
@cpaafd Please update the entire Salesforce Extension Pack to the latest version (v60.13.0).  The Apex Interactive Debugger extension has dependencies on the Apex and CLI Integration extensions, both of which are out of date and possibly incompatible with the current version of Apex Interactive Debugger.

Let us know if the problem still persists after upgrading.

**Comment by daphne-sfdc** [comment]
What is your CLI version?  Run `sf --version` in your Terminal and send us the results of the command.

**Comment by daphne-sfdc** [comment]
@cpaafd Can we also get the org ID of your full sandbox org and the org ID of the production org where the sandbox was created?

**Comment by cpaafd** [comment]
Hello,
thank You:

UAT Org id: 00D8F0000006nVE
PROD Org id: 00Di0000000fiJD

**Comment by diyer** [comment]
@cpaafd , can you please use our bug template to log a bug and fill out all the required details. Looks like you have used the feature template. I am closing this one, please file a bug with all the required details so our team can look into it. Thank you!
