### ISSUE TITLE
Unable to Update CustomField Metadata. SFDX: Deploy Providing False Success Message

### ISSUE THREAD

**Issue by achalon-salesforce** [forcedotcom/salesforcedx-vscode#5611]
### Summary

Unable to modify field metadata. When using Salesforce CLI GUI provided by the extension pack and I click "SFDX: Deploy this source to org" either from within a modified and saved CustomField xml file or the package.xml (With custom fields included) a successful deployment will go through but none of the changes will be displayed in Salesforce.

### Steps To Reproduce:

1.  Create a package.xml which includes a CustomField (Standard field or custom field, not a system field).
1.  Retrieve this field by right-clicking the file and selecting "SFDX: Retrieve this source from org" 
1.  Go to the CustomField file, modify it (change the value between <description></description> or something), and save changes
1.  Go to the package.xml (or stay on the CustomField file), right-click and select "SFDX: Deploy this source to org"
1.  Login to Salesforce Org to validate field metadata changes

### Expected result

The changes will be reflected from the Object Manager in setup.

### Actual result

The changes are not reflected from the Object Manager in setup.

### Additional information

**Salesforce Extension Version in VS Code**:

**Salesforce CLI Version**:

**OS and version**:

**VS Code version**:

**Most recent version of the extensions where this was working**:

**Comment by CristiCanizales** [comment]
Hi @achalon-salesforce, please create a new issue from [here](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&projects=&template=Bug_report.md&title=) and provide **all** the details requested. We require them to have some context and be able to triage your issue. I'll close this one and wait for the new one. Thanks!
