### ISSUE TITLE
Unable to Update CustomField Metadata. SFDX: Deploy Providing False Success Message

### ISSUE THREAD

**Issue by achalon-salesforce** [forcedotcom/salesforcedx-vscode#5612]
### Summary

Unable to modify field metadata. When using Salesforce CLI GUI provided by the extension pack and I click "SFDX: Deploy this source to org" either from within a modified and saved CustomField xml file or the package.xml (With custom fields included) a successful deployment will go through but none of the changes will be displayed in Salesforce.

### Steps To Reproduce:

1.  Create a package.xml which includes a CustomField (Standard field or custom field, not a system field).
1.  Retrieve this field by right-clicking the file and selecting "SFDX: Retrieve this source from org" 
1.  Go to the CustomField file, modify it (change the value between <description></description> or something), and save changes
1.  Go to the package.xml (or stay on the CustomField file), right-click and select "SFDX: Deploy this source to org"
1.  Login to Salesforce Org to validate field metadata changes

### Expected result

The changes will be reflected from the Object Manager in setup.

### Actual result

The changes are not reflected from the Object Manager in setup.

### Additional information

**Salesforce Extension Version in VS Code**: v60.13.0

**Salesforce CLI Version**:  2.42.6

**OS and version**:  Sonoma 14.5

**VS Code version**: 1.85.1

**Most recent version of the extensions where this was working**: no idea

**Comment by CristiCanizales** [comment]
Hi @achalon-salesforce, thanks for creating the new issue. I tried to reproduce it but it's working for me. Would you mind sending me a recording of what you see? It can be through slack if you prefer. Thanks in advance!

**Comment by achalon-salesforce** [comment]
Slacking you now :)

**Comment by sahilgoyal28799** [comment]
Hello @CristiCanizales @achalon-salesforce ,

We are able to reproduce the issue with the below, We are unable to deploy a label change to a custom field via the latest vs code extension - v60.15.0

The label is changing on the first deploy attempt but not being changed on subsequent deploy attempts, Please reopen the issue and let me know If there is anything needed from my end,

Below is XML for the field: 

<?xml version="1.0" encoding="UTF-8"?>
<CustomField xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>NumberofLocations__c</fullName>
    <externalId>false</externalId>
    <label>Number of Locations12</label>
    <precision>16</precision>
    <required>false</required>
    <scale>2</scale>
    <type>Number</type>
    <unique>false</unique>
</CustomField>

<img width="1220" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/59553217/7afecff4-67c7-4723-aebf-08bf707f356f">

Thank you

**Comment by diyer** [comment]
@achalon-salesforce @sahilgoyal28799 Can you please verify if this issue has been fixed for you by using our latest version of Salesforce extensions?

**Comment by diyer** [comment]
Fix has been released in version 61.2.1
