### ISSUE TITLE
unable to connect org

### ISSUE THREAD

**Issue by RukeshChowdary** [forcedotcom/salesforcedx-vscode#5619]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mingxuanzhangsfdx** [comment]
Hi @RukeshChowdary , looks like you were reporting an issue but turned out to be a feature request. Please select `Issue: Bug report` to report your issue and fill out the details in the template. I will close this issue.
