### ISSUE TITLE
Apex debugger not showin Variables

### ISSUE THREAD

**Issue by gamatibrightcove** [forcedotcom/salesforcedx-vscode#5625]
### Summary

the Apex debugger doesn't highlight anymore the APEX line I placed the breakpoint, and also the 'Step Over' button doesn't seem to move forward. 
The Variable section too is empty which infact was really helpful for debugging (see attached Screenshot)

<img width="1812" alt="Screenshot 2024-06-05 at 14 43 34" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/113022237/d20a00ef-f028-4b52-b519-8ba1e9c20938">

 This is my Launch.Json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    
    {
      "name": "Launch Apex Debugger",
      "type": "apex",
      "request": "launch",
      "salesforceProject": "${workspaceRoot}"
    }
  ]
}


```
### Steps To Reproduce:

1.  Use my Launch.json if you like
1.  Have the v60.15.0 of the interactive debugger
2. open an APEX class with different methods 
3. have Salesforce also open in a sandbox or production
4. place the breakpoint over an SOQL query (for example) or on a line statement that builds a List<xxx> for example. 
### Expected result

I would like to see all the members of the Apex class in the 'Variable' section as soon as I reach an breakpoint. Also the indication of the breakpoint changes depending on the line of code (see screenshots). 
Whenever a LIST<xxxx> gets created on the code level, it looks empty in the 'Variable' section.

### Actual result

I don't see the 'Variable' section populated anymore, whenever I place a stop within a method of the apex class.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: V60.15.0

**Salesforce CLI Version**:  salesforce/cli/2.43.7 darwin-arm64 node-v20.13.1

**OS and version**: SONOMA 14.5

**VS Code version**: 1.89.1d

**Most recent version of the extensions where this was working**: I can't remember but definitely before the version 60 of the Salesforce Extention Pack.

**Comment by peternhale** [comment]
@gamatibrightcove would you provide the org Id you are using at the moment?

**Comment by peternhale** [comment]
Same as #5557 closing
