### ISSUE TITLE
Support for newer Java version

### ISSUE THREAD

**Issue by hadkins0617** [forcedotcom/salesforcedx-vscode#5636]
### Summary
My company is requiring the latest version of Java (via Zulu 21) as a result of a security finding. As a result, I get the following error message related to the Apex plugin in the Salesforce Extension Pack - An unsupported Java version was detected. Download and install [Java 11](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html) or [Java 17](https://www.oracle.com/java/technologies/downloads/#java17) to run the extensions. For more information, see [Set Your Java Version](https://developer.salesforce.com/tools/vscode/en/vscode-desktop/java-setup).

### Describe the solution you'd like
Update the Extension pack to support newer versions of Java.

### Describe alternatives you've considered
At this point I have no alternatives in using this specific piece of the Extension pack.

**Comment by diyer** [comment]
@hadkins0617 The team has been working on adding java 21 support and the. good news is that this will be available from our next release. Stay tuned.

**Comment by hadkins0617** [comment]
Salesforce Extension Version in VS Code: v60.15.0
Salesforce CLI Version: @salesforce/cli/2.16.8 win32-x64 node-v18.18.2
OS and version: Windows 10 Enterprise 10.0.19045
VS Code version: 1.90.0
Most recent version of the extensions where this was working: n/a

**Comment by diyer** [comment]
We will be releasing this on Friday of this week. Thanks to @peternhale our awesome engineer adding support for this.

**Comment by daphne-sfdc** [comment]
Hello @hadkins0617, We have released v61.0.1 of the Salesforce Extensions for VSCode, which includes support for Java 21.  Please update your extensions to the latest version and you should be able to use this new feature. 🎉
