### ISSUE TITLE
📣Important Notice: Errors Caused by Recent Upgrade of ESLint Extension

### ISSUE THREAD

**Issue by CristiCanizales** [forcedotcom/salesforcedx-vscode#5658]
There was a major version bump of ESLint Extension from **v2** to **v3** last week that requires VS Code version `1.90` or higher. Please upgrade your VS Code version to `1.90` or else the LWC extension will not work as expected.

**Comment by diyer** [comment]
This issue has been fixed. LWC extension no longer depends on ESLint
