### ISSUE TITLE
Quick Start LWC development article out of date

### ISSUE THREAD

**Issue by readeral** [forcedotcom/salesforcedx-vscode#5659]
### Summary

[Quick Start LWC development](https://developer.salesforce.com/tools/vscode/en/lwc/lwc-get-started) needs updating given the changes to the Sales app in Spring 24.

Since Spring 24, the Sales app now uses 'Seller Home' as its homepage, and this is not editable as per the article. Either the Quick Start should suggest a different app to use for adding your new component, or should direct users to turn off 'Advanced Seller Home' in Setup > Feature Settings > Home before proceeding to step 2.

### Steps To Reproduce:

1. Create a scratch org
2. Open the Sales app
3. Click the setup cog
4. there is no 'Edit page' option visible

### Expected result

'Edit page' would be an option

### Actual result

No Edit page available, so you're unable to edit the page to add your newly developed component

### Suggested fix

Either the Quick Start should suggest a different app to use for adding your new component, or should direct users to turn off 'Advanced Seller Home' in Setup > Feature Settings > Home before proceeding to step 2.

Salesforce Extension Version in VS Code: 61.1.2
Salesforce CLI Version: @salesforce/cli/2.46.6 darwin-arm64 node-v18.16.0
OS and version: MacOS Sonoma 14.5
VS Code version: 1.90.2
Most recent version of the extensions where this was working: n/a

**Comment by readeral** [comment]
added unnecessary validation info

**Comment by daphne-sfdc** [comment]
Hi @readeral, Thank you for informing us about the issue.  We have made the necessary updates to our docs to reflect the new state of the Sales app.  The updated page is now live here: https://developer.salesforce.com/docs/platform/sfvscode-extensions/guide/lwc-get-started.html
