### ISSUE TITLE
Cannot read properties of undefined (reading 'entries')

### ISSUE THREAD

**Issue by 01001101011000010111010001110100** [forcedotcom/salesforcedx-vscode#5662]
### Summary

When using cli in vs code, "Cannot read properties of undefined (reading 'entries')"

### Steps To Reproduce:

1.  Get 
1.  SFDX: Retrieve Source in Manifest from Org

### Expected result

Get source w/ success prompt

### Actual result

Error: Cannot read properties of undefined (reading 'entries')

### Additional information

**Salesforce Extension Version in VS Code**:  61.2.1

**Salesforce CLI Version**: @salesforce/cli/2.30.8 win32-x64 node-v20.11.1

**OS and version**: 
Edition	Windows 11 Home
Version	23H2
OS build	22631.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0

**VS Code version**:
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Most recent version of the extensions where this was working**: 61.1.2

**Comment by ventas-consulting** [comment]
seriously? every single item is showing exactly how the reply-example shows.

**Comment by daphne-sfdc** [comment]
Hi @01001101011000010111010001110100, Two questions:
1. Can you try updating your CLI to the latest version and see if the error still exists?
2. What are the contents of your manifest that you are trying to retrieve?

**Comment by 01001101011000010111010001110100** [comment]
> Hi @01001101011000010111010001110100, Two questions:
> 
> 1. Can you try updating your CLI to the latest version and see if the error still exists?
> 2. What are the contents of your manifest that you are trying to retrieve?

1. tried that. the error went away, but it just sits there like its pulling the source down, but does nothing and is hung.
2. i tried a couple different manifest, even just one page.

I am now uninstalling the cli and installing a latest that way....

earlier I rolled back all vs code extensions that updated while I was at lunch to the previous version, the error went away, but pulling source is hung. tries rebooting, reauthenticating to the sfdc instance, etc.

**Comment by daphne-sfdc** [comment]
Hmm (1) sounds like the slow deployment issue that a lot of users are facing.  Can you please provide the org id of your current org, and if it's a scratch org or sandbox, the org id of the production org that created it?  Also, can we get an idea of your org shape?  For example, number of Apex classes, number of LWC components, number of custom objects, etc.

**Comment by 01001101011000010111010001110100** [comment]
Hello again, I guess its working now after full download and uninstall/reinstall of the main cli latest windows version and I updated the vs-code extensions back to latest.

New issue-- it takes a LONG time (21+ minutes) to pull a manifest that normally takes a minute or two, but that's usually a sfdc issue that creeps up now and then so this appears normal...

The original error "Cannot read properties of undefined (reading 'entries')" is no longer an issue, so I will close this.

Thanks for the help.

**Comment by daphne-sfdc** [comment]
Thanks for the update, and glad to hear that you're able to resolve the issue! 🙌
