### ISSUE TITLE
Salesforce Extension Activation fails after 61.2 release

### ISSUE THREAD

**Issue by dattakale86** [forcedotcom/salesforcedx-vscode#5671]
### Summary
After recent update of 61.2, salesforce extensions fails to activate properly on macos.

### Additional information

Salesforce Extension Version in VS Code: 61.2.1
Salesforce CLI Version: @salesforce/cli/2.47.6 darwin-arm64 node-v20.15.0
OS and version: MacOS Sonoma 14.5
VS Code version: 1.90
Most recent version of the extensions where this was working: 61.1.2

Error from vscode extension host:

> 2024-07-03 12:23:10.327 [error] TypeError: Cannot read properties of undefined (reading 'entries')
    at cloneUniqueListeners (/Users/dk/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/lib/index.js:12451:88)
    at Function.getInstance (/Users/dk/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/lib/index.js:12331:123)
    at detectCryptoVersion (/Users/dk/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/lib/index.js:13171:43)
    at /Users/dk/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/lib/index.js:13204:13
    at Object.onGetCommandClose (/Users/dk/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/lib/index.js:12768:13)
    at ChildProcess.<anonymous> (/Users/dk/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/lib/index.js:12631:38)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)

**Comment by dattakale86** [comment]
Added missing required information.

**Comment by peternhale** [comment]
@dattakale86 Thank for reporting this issue. Try these steps:
- Open folder `.sfdx/tools` in your workspace
- Remove folder `250`
- Reload the workspace

**Comment by dattakale86** [comment]
Hey @peternhale, I already tried that but it didn't help.

**Comment by peternhale** [comment]
@dattakale86 while we investigate this issue, I would recommend installing v61.1.2 of the extensions. I apologize for the inconvenience.

**Comment by diyer** [comment]
@dattakale86 Our sincere apologies for the inconvenience. can you please confirm if downgrading the version of extensions has unblocked you?

**Comment by peternhale** [comment]
@dattakale86 The bug has been identified in one of dependencies and is being fixed. We hope to have this issue wrapped up by middle of next week. 

Would you mind providing the list of vscode extensions you are using and those that are active in your project workspace?

**Comment by peternhale** [comment]
One more ask

In a terminal

- cd ~/.vscode/extensions
- find . -name package.json -type f | xargs egrep -e '"@salesforce\/core' 2>/dev/null
Return the results if you can.

**Comment by dattakale86** [comment]
@diyer yes downgrading salesforce cli integration plugin to previous version helped.

@peternhale I have Salesforce Extension Pack (Expanded) in my project worrkspace and output of command you asked to run:

> ./salesforce.salesforcedx-vscode-apex-61.1.2/node_modules/@salesforce/core/package.json:  "name": "@salesforce/core",
./salesforce.salesforcedx-vscode-apex-61.1.2/node_modules/@salesforce/source-deploy-retrieve/node_modules/@salesforce/core/package.json:  "name": "@salesforce/core",
./salesforce.salesforcedx-vscode-apex-61.1.2/node_modules/@salesforce/source-deploy-retrieve/package.json:    "@salesforce/core": "^7.4.1",
./salesforce.salesforcedx-vscode-apex-61.1.2/node_modules/@salesforce/source-tracking/package.json:    "@salesforce/core": "^7.3.9",
./salesforce.salesforcedx-vscode-apex-61.1.2/package.json:		"@salesforce/core": "7.3.10",
./salesforce.salesforcedx-vscode-core-61.1.2/node_modules/@salesforce/core/package.json:  "name": "@salesforce/core",
./salesforce.salesforcedx-vscode-core-61.1.2/node_modules/@salesforce/source-deploy-retrieve/package.json:    "@salesforce/core": "^7.3.9",
./salesforce.salesforcedx-vscode-core-61.1.2/node_modules/@salesforce/source-tracking/package.json:    "@salesforce/core": "^7.3.9",
./salesforce.salesforcedx-vscode-core-61.1.2/node_modules/@salesforce/templates/package.json:    "@salesforce/core": "^7.3.10",
./salesforce.salesforcedx-vscode-core-61.1.2/package.json:		"@salesforce/core": "7.3.10",
./salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/templates-bundle/package.json:    "@salesforce/core-bundle": "^7.3.10"
./salesforce.salesforcedx-vscode-core-61.2.1/node_modules/@salesforce/core-bundle/package.json:  "name": "@salesforce/core-bundle",


Thanks!

**Comment by dvon88** [comment]
I have this same issue, downgrading does not work. My system and installation specs are the same as OP

**Comment by peternhale** [comment]
@dattakale86 @dvon88 We have identified the issue with a dependency and are working to resolve it.

**Comment by islimane** [comment]
@peternhale How is this going? I have the same issue here

**Comment by daphne-sfdc** [comment]
Hi @islimane, This issue has been fixed and will be published in this week's release.  If you would like to access the bug fix before the release is officially available, please download the VSIXs via the below link and directly install them into VSCode. https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9869169327

**Comment by daphne-sfdc** [comment]
Closing this issue as v61.4.0 of the Salesforce Extensions for VSCode has been released.
