### ISSUE TITLE
We found that after upgrading to the latest version, we encountered an error when uploading a newly created apex class

### ISSUE THREAD

**Issue by zt15242** [forcedotcom/salesforcedx-vscode#5675]
We found that after upgrading to the latest version, we encountered an error when uploading a newly created apex class。
We manually set the apiVersion in the xml of the newly created class from 61 to 59 to deploy normally
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/74717483/b9e73d88-ee19-436b-8dd6-e12ff20c4d48)

**Comment by zt15242** [comment]
@svc-idee-bot
Salesforce Extension Version in VS Code: 61.2.1
Salesforce CLI Version:@salesforce/cli/2.13.9 win32-x64 node-v18.15.0
VS Code version: 1.89.1
Most recent version of the extensions where this was working: 60.13.0

**Comment by peternhale** [comment]
@zt15242 would you run this command from the vscode terminal and return the results?

`sf project deploy start`

**Comment by peternhale** [comment]
I also see that the CLI version is ~34 weeks old. Would it be possible to upgrade the CLI to the latest and try again?
