### ISSUE TITLE
Missing metadata type definition ExpressionSetDefinitionVersion and unable to retrieve DecisionMatrixDefinitionVersion in VS Code

### ISSUE THREAD

**Issue by twardegaSFDC** [forcedotcom/salesforcedx-vscode#5678]
### Summary

Salesforce CLI v 2.49.7 reports a fix to support metadata types DecisionMatrixDefinitionVersion and ExpressionSetDefinitionVersion based on the output of 'sf whatsnew' command:
...
    * FIX: You can now correctly deploy and retrieve the DecisionMatrixDefinition, DecisionMatrixDefinitionVersion, and ExpressionSetDefinitionVersion metadata types. (GitHub issue #2823 (https://github.com/forcedotcom/cli/issues/2823), source-deploy-retrieve PR #1357 (https://github.com/forcedotcom/source-deploy-retrieve/pull/1357))
...

However, when trying to retrieve these metadata types from source org and deploying to the target org using package.xml VS Code does not recognize these metadata types.

### Steps To Reproduce:

1. Prepare a sample package.xml to retrieve and then deploy sample metadata of type DecisionMatrixDefinitionVersion and ExpressionSetDefinitionVersion as in the example below:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>DAWSON_Event_Code_Mapping</members>
        <name>DecisionMatrixDefinitionVersion</name>
    </types>
    <types>
        <members>OCC_Dawson_Practitioner_ES_V1</members>
        <name>ExpressionSetDefinitionVersion</name>
    </types>
	<version>61.0</version>
</Package>

2. Retrieve metadata from the source org by right-clicking on the sample package.xml and choosing SFDX: Retrieve Source in Manifest from Org

At this point the following error is reported: Missing metadata type definition in registry for id 'expressionsetdefinitionversion'.
NOTE: a similar error is not reported for DecisionMatrixDefinitionVersion at this time, but the corresponding metadata is not retrieved

### Expected result

Metadata for DecisionMatrixDefinitionVersion and ExpressionSetDefinitionVersion should be retrieved using SFDX: Retrieve Source in Manifest from Org function in VS Code.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**Salesforce CLI Version**:

**OS and version**:

**VS Code version**:

**Most recent version of the extensions where this was working**:

**Comment by daphne-sfdc** [comment]
Hi @twardegaSFDC, This issue has been resolved and will be included in this week's release.  If you would like this feature earlier, please install our VSIX files here directly into VSCode: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9834523342

**Comment by daphne-sfdc** [comment]
Closing this issue as v61.4.0 of the Salesforce Extensions for VSCode has been released.
