### ISSUE TITLE
Problem Window is not cleared event when there are no errors in the file and its compiled successfully.

### ISSUE THREAD

**Issue by amitkumarj1979** [forcedotcom/salesforcedx-vscode#570]
### Summary

Earlier errors not getting cleared, Every time the problems in the PROBLEM window are accumulated. Even though the file was successfully compiled it still shows lot of issues.

### Steps To Reproduce:

1.  Create an Apex Class. Write some code which does not compile may be syntax error.
2.  You would see the errors correctly in the Problem window.
3. Fix the errors and compile.
4. Even though the file compiles the errors from the Problem window do not go away.

### Expected result

The Problem window should clear out.

### Actual result

The Problem window does not clear out and problems are accumulating.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.26.1

**SFDX CLI Version**: 6.19

**OS and version**: Mac OS High Sierra - 10.13.6

**Comment by vazexqi** [comment]
@amitkumarj1979 - I'm not able to repro this with the https://github.com/forcedotcom/sfdx-dreamhouse repo. 

Here's a gif of it working for me. I introduced a syntax error (missing ;) and the problems show up. When I fix the error, the problems disappear.

![apex_syntax_errors](https://user-images.githubusercontent.com/54414/44316167-116a1700-a3df-11e8-9c1e-b6c67f8bbb57.gif)


Could you provide more details about your project?

**Comment by amitkumarj1979** [comment]
I tried on another machine and it worked correctly. It might be something specific to my machine. Will monitor and let u know if there is anything i find.
Thanks
