### ISSUE TITLE
Stop showing output panel after diff/retrieve/deploy/create is success

### ISSUE THREAD

**Issue by prabormukherjee** [forcedotcom/salesforcedx-vscode#5706]
### Summary

_when using any sfdx command like **retrieve from org** or **deploy source to org**, cli should only open a popup if show only in status is set to false. but it's opening both_.

### Steps To Reproduce:

1.  Open any salesforce project in vscode
2.  authorize an org
3.  find any existing code (apex/lwc/vf...)
4.  run diff check or retrieve from org

### Expected result

_it should show only success as pop up with 2 buttons (show and show only in status bar)_.

### Actual result

_it's showing in the popup as well as the output panel is opening everytime_.

### Additional information

_as per this PR it was fixed 4 years ago: https://github.com/forcedotcom/salesforcedx-vscode/pull/1865_.

**Salesforce Extension Version in VS Code**: 61.7

**Salesforce CLI Version**: @salesforce/cli/2.40.7

**OS and version**: Windows11 23H2

**VS Code version**: 1.92

**Most recent version of the extensions where this was working**: Not sure

**Comment by prabormukherjee** [comment]
hey, @svc-idee-bot updated now.

**Comment by peternhale** [comment]
@prabormukherjee Thanks for making aware of this issue. We will be looking at a design that will provide a more uniform behavior of how commands interact with the output channel with regard what circumstances will cause focus to shift to a given channel.

**Comment by prabormukherjee** [comment]
Hi @peternhale thanks. We'd love a feature to config whether to auto focus on the output channel or not (just like the one we already have to show pop-up **show-cli-success-msg**)

**Comment by tehnrd** [comment]
Adding a vote for this. This behavior is so annoying...and I've put up with it for years.

Tools like pmd, es-lint, and the [Salesforce Code Analyzer](https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/security_review_code_analyzer_scan.htm) will display errors/warnings in the Problems tab. There could be 10s of errors in a large file. The workflow is atrocious when trying to fix issues.

- Fix the issue and save.
- Vscode pops over to Output tab
- Have to go back to the Problems tab.
- Fix the issue and save.
- Vscode pops over to Output tab
- Have to go back to the Problems tab.
- Fix the issue and save.
- Vscode pops over to Output tab
- Have to go back to the Problems tab.

...you get the idea.

I'll even do the PR if someone can point em to the code that is changing the pane on save.

**Comment by trevSmart** [comment]
This has become ridiculous. Could you please prioritize fixing this?
