### ISSUE TITLE
JDK 10

### ISSUE THREAD

**Issue by ad1969** [forcedotcom/salesforcedx-vscode#572]
### Summary

I installed JDK 10 and all the features stopped working.

### Steps To Reproduce:

1.  Installed JDK 10
2. Updated environment variables
3. Updated settings: "salesforcedx-vscode-apex.java.home": "C:\\Program Files\\Java\\jdk-10.0.2",

### Expected result

All features such as preview definition, go to definition etc should still work.

### Actual result

Features no longer working.

### Additional information

![image](https://user-images.githubusercontent.com/5445582/44362713-6d887600-a487-11e8-8e62-84f4b1c0a28f.png)

**Comment by vazexqi** [comment]
See https://github.com/forcedotcom/salesforcedx-vscode/issues/398
