### ISSUE TITLE
Apex - Prettier error spawnSync EINVAL when formatting Apex classes 

### ISSUE THREAD

**Issue by naveensimplify** [forcedotcom/salesforcedx-vscode#5732]
Type: <b>Bug</b>

Open Apex Class
Try to use command format document

Extension version: 61.10.0
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by naveensimplify** [comment]
More Info
https://github.com/prettier/prettier-vscode/issues/3495

**Comment by naveensimplify** [comment]
Below you can find the information requested. 

Salesforce Extension Version in VS Code:v61.10.0
Salesforce CLI Version:@salesforce/cli/2.55.6
OS and version:Windows_NT x64 10.0.19045
VS Code version:61.10.0
Most recent version of the extensions where this was working: Not Sure
Java version: "17.0.6" 2023-01-17 LTS

**Comment by CristiCanizales** [comment]
hi @naveensimplify, please edit your issue and provide **all** the details we ask (repro steps, actual behavior, expected behavior, versions info, etc). We need them to have some context on the issue to be able to triage it.
