### ISSUE TITLE
Unable to authenticate into Salesforce Org - issue with SF CLI

### ISSUE THREAD

**Issue by harrismarmon** [forcedotcom/salesforcedx-vscode#5734]
### Summary

_I'm unable to authenticate into a Salesforce Org on Using the SF CLI, after having already authenticated my default org previously 

### Steps To Reproduce:

1.  From VS Code, click CTRL + Shift + P and Select SFDX: Authorize an Org
2. Select either the Sandbox option or Custom domain methods for authenticating into a sandbox
3. Enter any Alias for the org
4. Wait for command to run, then it provides the popup "SFDX: Authorize an Org failed to run" and the error code from the Output console "17:17:10.798 sf org:login:web --alias tetprod --instance-url https://test.salesforce.com --set-default
 »   Warning: org login web is not a sf command.
Did you mean login org? [y/n]: 
 »   Error: Run sf help org for a list of available commands.
17:17:18.366 sf org:login:web --alias tetprod --instance-url https://test.salesforce.com --set-default
 ended with exit code 127"

Note that as this is the output console, you cannot type in a y or n to the question because it's a read-only message

### Expected result

Should have been able to auth into another testorg

### Actual result

Errored out and did not open the popup to enter login credentials

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: v61.10.0

**Salesforce CLI Version**: v61.10.0

**OS and version**: Windows 11 Enterprise

**VS Code version**: 2.55.6-648ad30

**Most recent version of the extensions where this was working**: Not sure

**Comment by mingxuanzhangsfdx** [comment]
Hi @harrismarmon - 

Can you try to run the cli command directly to auth an org instead by following the instruction [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_flow.htm)?

Also please make sure you are using the latest version of cli. You can get the version by running `sf -v` in command line.
