### ISSUE TITLE
js linting on LC not working correctly

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#574]
### Summary

js linting in Lightning components just got much less strict

### Steps To Reproduce:

1. create a typical controller.js function
```
 vehicleSelect : function(component, event, handler) {
        console.log(event);
        console.log(event.getSource());

        var vehicle = event.getSource().get('v.value');
        console.log(vehicle);
        component.set('v.selectedVehicle', vehicle);
        component.set('v.vehicles', component.get('v.vehicles').find(item => item.label === vehicle));
    },
```
2. remove event, handler from the functional arguments
3.  remove other normal things, like EOL semicolons, etc.

[fyi, flagrant js violations like not closing parens or brackets do get flagged]

### Expected result

linting would catch event being used without defining
### Actual result

no errors linted
### Additional information

VS Code Version: 1.26.1

SFDX CLI Version: sfdx-cli/6.29.0-0a2482692c (darwin-x64) node-v8.9.4

OS and version: macos 10.13.6

**Comment by vazexqi** [comment]
@mshanemc - Did you mean to include a different screenshot?

**Comment by mshanemc** [comment]
no screenshot necessary...there's code.  Sorry, I didn't keep the original screenshot. @vazexqi

**Comment by ntotten** [comment]
I am not able to reproduce this. In fact, there isn't actually any special about what the salesforce extensions do with Javascript - it is entirely normal VS Code. Have you continued to see this issue?

**Comment by mshanemc** [comment]
It's working for me now, all week.  I'm closing it.
