### ISSUE TITLE
Unable to connect to Apex LSP 

### ISSUE THREAD

**Issue by jbenge1** [forcedotcom/salesforcedx-vscode#5787]
### Summary

I am trying to write an ide extension for apex, and have been unable to get the language server to work. When I start the command to check for errors in the terminal there is no output, maybe I'm missing a step of how to connect a client to the server? The extension is able to start up the server with no errors but there are no functions lsp features

### Steps To Reproduce:

1.  Run: `java -cp apex-jorje-lsp.jar -Ddebug.internal.errors=true -Ddebug.semantic.errors=true apex.jorje.lsp.ApexLanguageServerLauncher`
1.  Open folder with `sfdx-project.json/.sfdx`
1.  Open any apex class

### Additional information
For context this is the startup code for the extension: 
```
impl zed::Extension for ApexExtension {
    fn new() -> Self {
        Self
    }

    fn language_server_command(
        &mut self,
        _language_server_id: &LanguageServerId,
        worktree: &zed::Worktree,
    ) -> Result<zed::Command> {
        let Some(uber_jar) = worktree.which("apex-jorje-lsp.jar") else {
            return Err("Apex JAR not found".into());
        };
        let Some(java_path) = worktree.which("java") else {
            return Err("java not in path".into());
        };
        const APEX_LANGUAGE_SERVER_MAIN: &str = "apex.jorje.lsp.ApexLanguageServerLauncher";

        Ok(zed::Command {
            command: java_path,
            args: vec![
                "-cp".to_string(),
                uber_jar,
                "-Ddebug.internal.errors=true".to_string(),
                "-Ddebug.semantic.errors=false".to_string(),
                APEX_LANGUAGE_SERVER_MAIN.to_string(),
            ],
            env: Default::default(),
        })
    }
}

zed::register_extension!(ApexExtension);
```

**OS and version**:
macOS Sonoma 14.5

**Comment by peternhale** [comment]
@jbenge1 The Apex LS is using the [Microsoft Language Server Protocol](https://microsoft.github.io/language-server-protocol/), which means you will need a language client implementation. I would recommend finding an Rust implementation to use in your extension.
