### ISSUE TITLE
Automatically push changes when you save your local files

### ISSUE THREAD

**Issue by gitmatheus** [forcedotcom/salesforcedx-vscode#579]
You guys recently introduced a new feature to [Develop Against Any Org in Visual Studio Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code), which is amazing. 

Another great improvement would be to be able to **push the changes to the current org when saving the file locally**, a feature that exists in other extensions such as MavensMate and ForceCode. Both are no longer being actively developed or supported.  

Currently we have a workaround that consists of [using Nodemon to automatically push](https://ntotten.com/2018/01/17/using-nodemon-to-autopush-sfdx-project-changes/) the project changes. 

Still, that would be awesome to have this option built in, out of the box.

Thanks for the hard work!

**Comment by ChuckJonas** [comment]
Same as #577
