### ISSUE TITLE
Latest (v61.12.0) VSCode Salesforce CLI Integration extension failed to execute when decomposeCustomLabelsBeta2 added to sourceBehaviorOptions

### ISSUE THREAD

**Issue by RayHWLau** [forcedotcom/salesforcedx-vscode#5836]
### Summary

The CLI has introduced decomposeCustomLabelsBeta2, while the command working properly through CLI, it failed to execute via CLI integration extension in VSCode

### Steps To Reproduce:

1.  Install Latest Salesforce CLI version (v2.57.7)
1.  Install all plugins in Salesforce Extension Pack
1.  Connect to any org
1.  Create an apex class with any name
1.  Right click on the apex class, then select "SFDX: Deploy this source to org"
1.  Error message "Failed to load preset "decomposeCustomLabelsBeta2"

### Expected result

The component / metadata should be deployed successfully

### Actual result

Received error message  "Failed to load preset "decomposeCustomLabelsBeta2" in VS Code terminal

### Additional information

<img width="405" alt="clierrorsh" src="https://github.com/user-attachments/assets/4792c55e-b7bd-4d33-b0c0-3afd9bf20c7d">

**Salesforce Extension Version in VS Code**: 61.12.0

**Salesforce CLI Version**: @salesforce/cli/2.57.7 win32-x64 node-v20.16.0

**OS and version**: Microsoft Windows 10 Enterprise (10.0.19045 Build 19045)

**VS Code version**: 1.92.2

**Most recent version of the extensions where this was working**: N/A

**Comment by RayHWLau** [comment]
Revised additional information to fit the format

**Comment by CristiCanizales** [comment]
Hi @RayHWLau. I verified and it's just that we're using a bit older version of the SDR library (the one that contains the changes for decomposeCustomLabelsBeta2). It was out on 12.3.0 and we're in 12.1.5). I'll log the bug and add it to our backlog. Thank you for bringing this up to our attentio!

**Comment by CristiCanizales** [comment]
Hi @RayHWLau! Could you please install [these](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10841328483?pr=5844#:~:text=Size-,VS%20Code%20Extensions,-47.9%20MB) vsixes and let me know if the issue is still happening? Thanks in advance!

**Comment by CristiCanizales** [comment]
Hi @RayHWLau, thanks for confirming with all those use cases! This fix will be officially out the week after Dreamforce, so not next week but the following one, but meanwhile you can use the vsixes I shared with you. Thanks for your patience😄
