### ISSUE TITLE
Apex Replay Debugger Fails to Start Debugging From "Debug Test" link in Unit Test Class.

### ISSUE THREAD

**Issue by rvanaken** [forcedotcom/salesforcedx-vscode#5839]
### Summary

Using the "Debug Test" link on a specific test method of a Test class fails to stat the debugging session.

Two errors are displayed:
```
Cannot read properties of null (reading 'Id')
Debug Test(s) failed to run
```
Just updated to the current version of the Apex Replay Debugger: v61.12.0

Other observations:
- Test method in question runs correctly and passes (when not trying to debug).
- Checkpoints vs Breakpoints seem to be displayed differently on the "Run and Debug" panel in this version.  Checkpoints now display properties: Type:None, Script:"", Iterations:1.  Previously (I recall) Breakpoints and Checkpoints both showed checkbox lists.  Breakpoints can still be toggled by clicking the margin, and Checkpoints still need a "SFDX: Toggle Checkpoint" command.

### Steps To Reproduce:

1. Open Salesforce project containing unit tests.
2. Locate a test in the test class (use source below)
3. Place cursor on a valid code line
4. F1: SDFX: Toggle Checkpoint
5. (Observe: red Checkpoint icon in the margin)
6. Click the "Debug Test" link just above one of the test methods
7. (Observe: SFDX: Update Checkpoints in Org seems to work)
8. (Observe: Two errors)

### Expected result

A debug session should have started and "broke" with the debug cursor at the Checkpoint line.

### Actual result

Two errors are displayed:
```
Cannot read properties of null (reading 'Id')
Debug Test(s) failed to run
```
### Additional information

**Salesforce Extension Version in VS Code**: v61.12.0
**Salesforce CLI Version**: @salesforce/cli/2.29.5 win32-x64 node-v20.11.0
**OS and version**: Windows 10 22H2, OS Build: 19045.4894
**VS Code version**: 1.93.0
**Most recent version of the extensions where this was working**: 59.1.2

### Example Test Class

```
@isTest(isParallel=false)
private class ExampleTestClass 
{
    @TestSetup static void makeData()
    {
        User portalUser = new User();
        insert portalUser;				// Should throw a DMLException
    }

    @isTest static void test0DebugTest()
    {
        String testString = 'This is a string';
        System.debug(testString);
        System.assert(testString == 'This is a string', 'Expected success, but it failed');
    }
}
```

**Comment by diyer** [comment]
@rvanaken looks like you are using an older version of cli. Can you upgrade your cli version and give this a try?

**Comment by rvanaken** [comment]
@diyer,
I updated CLI:
`@salesforce/cli/2.58.7 win32-x64 node-v20.9.0`

**Comment by rvanaken** [comment]
I previously turned off automatic updates for extensions because I was spending too much time churning  with issues after the extensions updated.  I'd been running stable for a couple months without updating.  I decided it was time to update extensions as good preventative maintenance.  I updated the Salesforce Extension Pack to v61.12.0 last week, and have been down ever since.

Maybe installing a dot-zero release was overly optimistic.

Can anyone recommend a previous stable version of the Salesforce Extension Pack?

**Comment by CristiCanizales** [comment]
Hi @rvanaken, I'm on `v61.12.0` and `@salesforce/cli/2.58.7 darwin-arm64 node-v18.18.2` and that same test and all the others run perfectly fine and can be debugged as well.

Can you verify you're connected to the org that has the tests? And that it's active?

If that's not it, can you delete .sf and .sfdx folders, quit and reopen vscode, reauth to your org and try again?

**Comment by rvanaken** [comment]
Hi @CristiCanizales ,

Thank you for the suggestions!

I'm glad to hear that you are able to run tests, etc without issues (that means there is hope).  I downgraded to a couple earlier extension versions and got the exact same error.

Yes, I'm authed on the sandbox I'm using.  I can Deploy, Diff, etc.  I just can run or debug tests.  I can run all tests without issue from Salesforce Setup.  I can also run them with "sf run test..." commands.

I exited VSCode, deleted the .sf and .sfdx folders, and started VSCode.  I still get the error.

I suspect there are some leftovers that didn't get cleaned up in recent updates: VSCode, CLI, and the extensions.  The issue is about getting test feedback from Salesforce to VSCode after the tests complete.  The tests are getting invoked, and they run on the sandbox correctly.  The issue doesn't happen until the "sf apex get test..." is done waiting and attempts to display the test results the output panel.

I'm going back to v61.12.0.  If that doesn't work, I'm going to reinstall VSCode and the extensions.  Since the CLI is a separate installation, that seems unrelated.

By the way, I installed the (expanded) extensions on a previous update, but I kept getting the non-expanded extensions as an extension recommendation.  So I went back to the non-expanded extensions.

**Comment by CristiCanizales** [comment]
@rvanaken sure, please let me know if reinstallation works. Also make sure `.vscode/extensions/` global folder has no sf extension before you reinstall them.

**Comment by rvanaken** [comment]
@CristiCanizales ,

I made the following changes:
- Uninstalled all extensions
- Deleted: ...\.vscode\extensions
- Deleted: ...\AppData\Roaming\Code
- Installed Salesforce Extension Pack
- Uninstalled Zulu JDK 11
- Installed Zulu JDF 21
- Configured Java in VSCode

All seems to be working again.  Unfortunately, we did not learn how this issue started.  Given that deleting, uninstalling, and installing is so easy, I'm not sure the analytical approach is cost-effective.  I'll probably start with that next time.

Thank you for your encouragement and suggestions!

**Comment by CristiCanizales** [comment]
Hi @rvanaken, I'm glad everything is working fine again! Thanks for all the details and patience.

**Comment by rvanaken** [comment]
@CristiCanizales 

I spoke too soon.

Unit testing seems to be working fine, but "Debug Test" is still not working.

Can we reopen?  Or should I create another issue?

**Comment by rvanaken** [comment]
Additionally, Checkpoints in the makeData() method are ignored.  I'm certain I have debugged makeData() in a past version.

I updated the original description to include my current understanding and the example code that demonstrates the issue.

**Comment by CristiCanizales** [comment]
Hi @rvanaken, I still can't repro your issue and debugger is working fine for me with makeData(). Could you share a video of what you're doing?

Also, is it still working for you in v59.1.2 or even more recent versions? We want to discard it's version specific

**Comment by CristiCanizales** [comment]
Could you also try right clicking on the apex test class and selecting "SFDX: Launch Apex Replay Debugger from Current File"?
![image](https://github.com/user-attachments/assets/7f02b70b-fdba-4a2d-bb07-93c03a2c39b5)

**Comment by aboyinthebox** [comment]
i tried above but getting this error 

P.S i have the same issue as @rvanaken 

<img width="514" alt="image" src="https://github.com/user-attachments/assets/b1029b54-6f09-45d9-bfea-01d7e96f5535">

**Comment by daphne-sfdc** [comment]
@rvanaken @aboyinthebox I have also tried the above example and was unable to reproduce the issue.  Like @CristiCanizales suggested above, can you please provide a short video of what you're doing to get the error?

**Comment by rvanaken** [comment]
For anyone who was not able to reproduce this issue...

Please look at the original issue description.  There is a sample test class at the bottom.  To reproduce the issue, the makeData() method must throw an exception.  If attempting to insert a blank User does not throw an exception, then you will not be able to reproduce the issue with this sample code.  You are welcome to find another way to throw a DML exception in your makeData() method.

Please verify that **you are throwing a DML Exception in your makeData() method** before certifying that you are not seeing the issue.

**Comment by daphne-sfdc** [comment]
@rvanaken I used the sample test class that you provided and clicked the "Debug All Tests" code lens.
![Image](https://github.com/user-attachments/assets/820d15e2-de22-4d62-909f-e8fc0bc4d001)

I am getting the DMLException in the debug log but not seeing the error.  Here is my debug log:
[07LDM00000v1mcs2AA.log](https://github.com/user-attachments/files/17192468/07LDM00000v1mcs2AA.log)

**Comment by daphne-sfdc** [comment]
@rvanaken Here is a video of me executing that debug log and stepping through the checkpoints.  I do not get any errors, both in notifications and Toggle Developer Tools.  What are you doing differently to get the error?
https://github.com/user-attachments/assets/2926eb5c-5095-4de0-9f04-e2e02f6798ec

**Comment by rvanaken** [comment]
@daphne-sfdc ,

Thank you for your time and effort.

I watched your video.  You are starting the debug session from a log file, which is not what I'm reporting in this issue.  I have no opinion about that.

To see if you can reproduce the issue, click "Debug Test" above the test0DebugTest() method definition.  In my environment, the checkpoints seems to get verified correctly, but instead of breaking in the makeData() method, VSCode issues a seemingly unrelated error.

I tried again.  I still get the error, instead of breaking in makeData().

Here is my screen before clicking Debug Test:
![image](https://github.com/user-attachments/assets/3b840c30-aea9-41d9-939d-7ac7c3f7178e)

Here are the 2 errors:
![image](https://github.com/user-attachments/assets/a0263924-b26f-4283-9875-cce11b013cf5)

**Comment by tggagne** [comment]
I get the same problem using the [SF docker image](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_docker.htm) just running a unit test from the cli:

`sf apex run test --target-org "$1" --tests "$2" --result-format=human --code-coverage -w=5`

where $1 is an org alias and $2 is a unit test class with two failing methods.  The unit test completes in the org, it's just the command throwing the error, "Error (10): Cannot read properties of null (reading 'Id')"

```
root@bba4d096375f:/# uname -a
Linux bba4d096375f 6.6.16-linuxkit #1 SMP Fri Feb 16 11:54:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@bba4d096375f:/# sf --version
@salesforce/cli/2.59.6 linux-x64 node-v20.17.0
```

**Comment by daphne-sfdc** [comment]
@rvanaken Thank you for the instructions.  You're right that the issue is regarding checkpoints - for me the "Debug Test" code lens works fine when I don't have any checkpoints enabled but fails once I add checkpoints to my code.  However, I see a different error message, and I'm not getting past the checkpoint verification stage... Let me investigate the code and get back to you once I have more info.
https://github.com/user-attachments/assets/4e9a3cf8-5227-40a5-bec6-272a61ba9137

**Comment by daphne-sfdc** [comment]
@rvanaken Hmm I set checkpoints in the Apex unit test class and clicked the "Debug Test" code lens, and my Apex Replay Debugger session still completed successfully.  Is there anything else that you're doing differently?

https://github.com/user-attachments/assets/84b0b07f-0e44-4e6a-9497-d9d45161f09b

**Comment by rvanaken** [comment]
@daphne-sfdc @CristiCanizales 
Are we going to let the bot auto-close this one?

Multiple people have seen it.

**Comment by daphne-sfdc** [comment]
> @rvanaken Hmm I set checkpoints in the Apex unit test class and clicked the "Debug Test" code lens, and my Apex Replay Debugger session still completed successfully. Is there anything else that you're doing differently?
> 
>  Screen.Recording.2024-09-30.at.3.43.13.PM.mov

@rvanaken Is there anything that you're doing differently from my video in the above message?  If yes, please let me know and I'll continue to try to reproduce the issue.

**Comment by rvanaken** [comment]
@daphne-sfdc ,

You're video looks reasonably similar to the steps I take.  I don't think I deployed the checkpoints like you did, but I do not think that is necessary/relevant.  You might try without that step, which was not in my instructions by the way.

I can't tell from your debug console if you are getting a DMLException.  I can see the debug session ends like it should.  In my case, the debug attempt ends in an error instead of breaking at the checkpoint.

**Comment by daphne-sfdc** [comment]
@rvanaken The Apex Replay Debugger still completes successfully when I do not deploy the checkpoints.

https://github.com/user-attachments/assets/e0eeec34-bc1e-4022-82b3-ba936f47c91e

Here is my debug log from that run - it does contain the DMLException.
[07LDM00000v1w1b2AA.log](https://github.com/user-attachments/files/17329349/07LDM00000v1w1b2AA.log)
