### ISSUE TITLE
Unexpected argument --manifest

### ISSUE THREAD

**Issue by ajayyearup** [forcedotcom/salesforcedx-vscode#584]
### Summary

I have installed the salesforcedx@pre-release plugin successfully. However I am trying to create a project with "sfdx force:project:create --projectname myproject --manifest". I am getting the error "Unexpected argument --manifest"

### Steps To Reproduce:

1. VS Code.
2.  SFDX: Create Project with Manifest

### Expected result

SFDX project has to be created.

### Actual result

"Unexpected argument --manifest"

### Additional information

![image](https://user-images.githubusercontent.com/42325509/44405832-35853f80-a528-11e8-9536-cf4562831d44.png)

**VS Code Version**:

1.26.1

**SFDX CLI Version**:
sfdx-cli/6.29.0-0a2482692c (windows-x64) node-v8.9.4

**OS and version**:
Windows 10

**Comment by vazexqi** [comment]
@ajayyearup  Please show me the output of running each of the following commands:

1. `sfdx plugins`
1. `sfdx force:project:create --help`

**Comment by ajayyearup** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/42325509/44415019-47bda880-a53d-11e8-92cd-2919f242f862.png)

**Comment by vazexqi** [comment]
@ajayyearup - It seems that you haven't installed the pre-release version of the CLI properly. If the installation were successful, it would look like the following:

<img width="997" alt="screen shot 2018-08-21 at 9 31 47 am" src="https://user-images.githubusercontent.com/54414/44415345-13d68900-a525-11e8-9a45-4cea1c967d8e.png">

This seems like an installation issue so I'm closing this. Feel free to seek help at the trailblazer community for such issues.
