### ISSUE TITLE
Getting "Cannot read properties of null (reading 'capabilities')" Error when using Einstein for Developers

### ISSUE THREAD

**Issue by klewis-sfdc** [forcedotcom/salesforcedx-vscode#5846]
### Summary

I am using Einstein for Developers v0.60.0, and I keep getting the following error on startup:

> Cannot read properties of null (reading 'capabilities')

<img width="451" alt="2024-09-03_09-52-59" src="https://github.com/user-attachments/assets/102e7795-c4ce-41c5-842f-2ce5475d1983">

 Screenshot from the console:
<img width="644" alt="2024-09-03_10-59-14" src="https://github.com/user-attachments/assets/ca8b0504-b8c0-4af5-97e3-522d34a72add">

### Steps To Reproduce:

1.  Install Einstein for Developers
2. Open my Salesforce Project in VS Code (ebikes-lwc)
3. See the message about Orphaned processes
4. See "Apex Language Server client: couldn't create connection to server."
5. See "Cannot read properties of null (reading 'capabilities')"

### Expected result

E4D and Apex both startup fine.

### Actual result

Apex doesnt start, so E4D doesn't start

### Additional information

https://github.com/user-attachments/assets/f3e2e1a4-55be-4b09-a183-3bd5725c9cb6

**Apex library Version**: v61.11.0

**OS and version**: Sonoma 14.6.1

my java home setting value is pointed at the Java version that is installed with core: "...Darwin/jdk/openjdk_11.0.18_11.62.18_x64"
This has been working fine for me for a long time before this error started occurring frequently for me toward the end of last week.

**Comment by CristiCanizales** [comment]
#5251

**Comment by daphne-sfdc** [comment]
Released in v62.0.0
