### ISSUE TITLE
Manifest doesn't influence deployment from folder

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/salesforcedx-vscode#586]
**Is your feature request related to a problem? Please describe.**
In order to carry out change set based deployment we create a project with a manifest. I updated the default manifest to reflect what I wanted to deploy to the org, then right clicked on the force-app directory and selected 'SFDX: deploy source to org'. I guess I was expecting that the manifest file would be taken into account when deploying this directory, and it would only take elements that I had detailed in the manifest, but everything went.

**Describe the solution you'd like**
I'd like the package.xml that I've defined to be taken into account regardless of where I kick off the deployment. For example, if I remove the ApexClass type from the manifest, I'd expect that to be skipped when deploying from the force-app directory.  

**Describe alternatives you've considered**
Remembering the right place to kick off the deployment from.

**Additional context**
It seems incongruous that we have to create a manifest file but it isn't taken into account unless we deploy from it, and I fear that devs will forget and deploy everything from the force-app folder even if it's not supposed to go to every org.

**Comment by ntotten** [comment]
> I fear that devs will forget and deploy everything from the force-app folder even if it's not supposed to go to every org.

I am not exactly understanding the issue. Why would you have files that don't go to every org in the same project? Would it not be better to create different projects for different orgs if they have different metadata?
