### ISSUE TITLE
Unable to activate Apex Language Server

### ISSUE THREAD

**Issue by superwomananmol** [forcedotcom/salesforcedx-vscode#5872]
### Summary

As soon as i open my VS Code im flooded with error msgs: Apex Language server couldnt create connection to server; Unable to activate apex language server.
on the output tab the error says: Exception in thread "main" java.lang.InternalError: Failed to load default.policy Caused by: java.nio.file.NoSuchFileException: C:\Program Files\Java\jdk-17\lib\security\default.policy
my system does not contain default.policy file, instead it contains java.policy file located at C:\Program Files\Java\jdk-17\conf\security\java.policy
I have added the path correctly for for java directory in the salesforcedx-vscode-apex>Java:Home property in VScode
It is automatically searching in the wrong directory
### Steps To Reproduce:

1.  Ensure VsCode is connected to salesforce.
2.  open VScode, you should see the error

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.
![image](https://github.com/user-attachments/assets/13305139-1d5d-49dc-b735-5806e4d4aab9)

**Salesforce Extension Version in VS Code**: v61.12.0

**Salesforce CLI Version**:2 .14.6 

**OS and version**: Microsoft Windows 11 Enterprise 10.0.22621 N/A Build 22621

**VS Code version**:Version: 1.93.1 (system setup)

**Most recent version of the extensions where this was working**: earlier i didnt use to receive this error and one day suddenly i am getting this issue. I dont remember the exact timeline

**Comment by peternhale** [comment]
@superwomananmol Who is the vendor for the version of java you have installed? 

This is my java version
```
java --version
openjdk 17.0.9 2023-10-17 LTS
OpenJDK Runtime Environment Microsoft-8552009 (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-8552009 (build 17.0.9+8-LTS, mixed mode, sharing)
```
and the contents of C:\Program Files\Microsoft\jdk-17.0.9.8-hotspot\lib\
```
blocked.certs
cacerts
default.policy
public_suffix_list.dat
```

**Comment by superwomananmol** [comment]
@peternhale When i try to run the java --version command in terminal, it gives me this error: java : The term 'java' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.

Im not sure what the problem is or how to approach this

**Comment by superwomananmol** [comment]
Also i can find the default_local.policy file at this path: C:\Program Files\Java\jdk-17\conf\security\policy\limited
But the vscode it searching it in the lib folder, theres no 'security' sub directory in the lib folder

**Comment by daphne-sfdc** [comment]
@superwomananmol
I have 2 questions for you:
1. What is the value of `echo %JAVA_HOME%` in your Command Prompt?
2. What is your value of the **Salesforcedx-vscode-apex › Java: Home** setting in VSCode?

Also, can you try updating your Salesforce CLI to the latest version?  (It should be 2.58.7 today.)

**Comment by superwomananmol** [comment]
Hi @daphne-sfdc 
pls see answers to your questions below:
![image](https://github.com/user-attachments/assets/8af7dd53-5457-4d72-ad11-6f394de73616)
![image](https://github.com/user-attachments/assets/d29d33ec-b7d3-4393-a7da-64c8ac45578b)

**Comment by superwomananmol** [comment]
@daphne-sfdc Also ive update the cli 
![image](https://github.com/user-attachments/assets/bb16f12b-e34a-4033-8c55-36b22ee6f073)

**Comment by superwomananmol** [comment]
its still not activating

**Comment by daphne-sfdc** [comment]
@superwomananmol Regarding the issue that `java --version` was not working: In your computer's environment variables, do you have a `Path` that contains `%JAVA_HOME%\bin`?  (see screenshots below)
![Screenshot 2024-10-02 at 12 06 44 PM](https://github.com/user-attachments/assets/7c3b029d-485a-48bd-b79b-43e0329d309a)
![Screenshot 2024-10-02 at 12 07 18 PM](https://github.com/user-attachments/assets/18231f64-8950-49ff-83d7-72a11b57b3df)

If not, can you add that, quit Command Prompt, and try running `java --version` again in a new Command Prompt window?  If the `java --version` issue is resolved, then quit and restart VSCode and see if the Apex Language Server is activated.

**Comment by superwomananmol** [comment]
Hi @daphne-sfdc the java --version issue is resolved, Thanks! However Apex LSP is still erroring with the same error. tried restarting VSCode- nothing changed

**Comment by daphne-sfdc** [comment]
@superwomananmol Great to hear!  Now that `java --version` is working, can you give us the result of that command?

**Comment by daphne-sfdc** [comment]
@superwomananmol Your Java version is supposed to come with a `lib/security/default.policy` file.  I have multiple versions of Java installed on my computer and have confirmed that all of my versions contain that file.

The `conf/security/java.policy` file that you referred to in your original message is a completely different file - all of my Java versions also contain that file, and the contents are different than `default.policy`.

Can you please try uninstalling and reinstalling your Java?  After you reinstall, please go check if your Java now contains the `default.policy` file.
