### ISSUE TITLE
V.62.0.0 APEX interactive Debugger not working

### ISSUE THREAD

**Issue by gamatibrightcove** [forcedotcom/salesforcedx-vscode#5896]
### Summary

I reported this multiple times, but all the newer versions seems not working. The APEX interactive debugger doesn't show anything. it looks completely broken. It doesn't show the variables, the call stack sections and even less the APEX statement with the breakpoint. 

### Steps To Reproduce:

1.  Create a Project with Manifest from one of your Salesforce Sandbox
2.  Create any trigger on any of the object, In my case a BEFORE_UPDATE trigger on CONTACT
3.  Set a breakpoint on your code and make sure you have assigned yourself the APEX Debug permission set in your sandbox
4. Configure the LAUNCH.Json as per the following: 

"version": "0.2.0",
  "configurations": [
    

    {
      "name": "Launch Apex Launch Debugger",
      "type": "apex",
      "request": "launch",
      "sfdxProject": "${workspaceRoot}"
    }
  ]
}

Then run start the debugging  and do something on your record that triggers the APEX.
### Expected result

The Variable, Watch and Call Stack panels on the left side of VSCode are totally empty

### Actual result

I expect to see the list of Variables of the APEX code based on their scope visibility, and evaluated with the correct values. 

### Additional information

<img width="1646" alt="Screenshot 2024-10-14 at 16 02 50" src="https://github.com/user-attachments/assets/3d3e6dfe-a629-42b9-b637-1f8abfe57d0f">
<img width="1487" alt="Screenshot 2024-10-14 at 16 03 13" src="https://github.com/user-attachments/assets/3e282065-598a-4f2e-8bfa-500e9c12f5d5">

**Salesforce Extension Version in VS Code**:
V.62.0.0 Apex Interactive Debugger
V.62.0.0 Salesforce CLI Intergration
V.62.0.0 Salesforce Extension Pack

**Salesforce CLI Version**:
 2.61.8 darwin-arm64 node-v20.17.0

**OS and version**:
Ventura 13.2.1 (22D68)

**VS Code version**:
Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.3.0

**Most recent version of the extensions where this was working**: 
I DON'T KNOW!

**Comment by AnanyaJha** [comment]
Hi @gamatibrightcove- thanks for sharing this info. Based on the information you've provided, it looks like you're running into a known issue with the Interactive Debugger not working in Hyperforce. At this point, we don't have a workaround but we'll let you know as soon as we have any further information. 

fyi - @rsensharma

**Comment by gamatibrightcove** [comment]
Hi @AnanyaJha @rsensharma
Thank you for getting back to me. I am just curious now :) is it because SFDC sandbox and orgs are on Hyperforce (whatever that is) that the interactive debugger stopped working for all the versions? 
I'm really just curious here if anyone has a hint of what it could be. 

Aren't all the Salesforce Extensions and Packages for VSCode developed by Salesforce too? 

Thank you for the information. 
GC
