### ISSUE TITLE
Apex Interactive Debugger - Too many concurrent debugged requests

### ISSUE THREAD

**Issue by soliogra** [forcedotcom/salesforcedx-vscode#5899]
When debugging apex I get the following error in VS Code

"Too many concurrent debugged requests. This request will not be debugged"

This issue started occurring recently and likely coincides with the upgrade of the extension pack.

I am using the following versions:
CLI = salesforce/cli/2.61.8 win32-x64 node-v19.8.1
Apex Interactive Debugger = v62.0
Salesforce Org Source API version = 62.0

**Comment by peternhale** [comment]
@soliogra would you mind sharing the details of the org you are using for debugging. Is it a sandbox, the org Id, etc? Thank you!

**Comment by peternhale** [comment]
@soliogra Just some additional information. The error you are seeing is issued from the org on which you are trying to use the interactive debugger. It indicates that there is a problem acquiring a "permit" that allows the debugger to continue. The permit is controlled via an org setting.

If you get the org id to me, I can see what the next steps might be for you to take. More than likely, via Salesforce Support.

**Comment by soliogra** [comment]
hi @peternhale, its is a sandbox and the Org Id is 00D3S00000092hx.

**Comment by peternhale** [comment]
@soliogra I cannot find an org with this Id.  Can you tell me which instance it is located?

**Comment by soliogra** [comment]
Hyperforce USA9018S

**Comment by peternhale** [comment]
@soliogra Thanks for the instance name. Unfortunately, I do not have access to the particular instance. I would suggestion that you reach out to Salesforce Support for further assistance. Also review #5896, as it also involved Apex debugger in an Hyperforce instance.
