### ISSUE TITLE
Do not switch to the Output panel when deploy on save is enabled

### ISSUE THREAD

**Issue by tehnrd** [forcedotcom/salesforcedx-vscode#5903]
**Is your feature request related to a problem? Please describe.**
When the "Push-or-deploy-on-save" setting is enabled, I’m always frustrated when I save a file, and VSCode changes the panel to the Output panel when saving the record. This completely disrupted the development experiences.

**Describe the solution you'd like**
By default, when "Push-or-deploy-on-save" is enabled, the UI should not switch to the Output panel when the files are saved. A setting can override this default behavior and show the Output panel if the user wants this behavior.

**Describe alternatives you've considered**
I am unaware of any alternatives to changing the output panel behavior when “Push-or-deploy-on-save” is enabled.

**Additional context**
This feature has been requested in some form many times and has attempted to be addressed in PRs.
Issue: https://github.com/forcedotcom/salesforcedx-vscode/issues/1429
Issue: https://github.com/forcedotcom/salesforcedx-vscode/issues/1110
PR: https://github.com/forcedotcom/salesforcedx-vscode/pull/4337
PR: https://github.com/forcedotcom/salesforcedx-vscode/pull/4971
PR: https://github.com/forcedotcom/salesforcedx-vscode/pull/1865
PR: https://github.com/forcedotcom/salesforcedx-vscode/pull/1181

The PRs to address this issue have had regressions, which no longer work. Some of the feedback on other PRs was that a global setting for suppressing output panel switching was too aggressive, so this suggestion is for Push-or-deploy-on-save only.

Here is a video showing the before and after functionality:
https://www.loom.com/share/a59adaa191474e64a835e9d52121f6c3?sid=7d8250d5-8e2d-4904-afda-6f0d05888f79

**Comment by tehnrd** [comment]
I think there is an argument to be made in which there should be no setting at all, and by default, the UI simply does not change to the Output panel at all with Deploy on save enabled.

**Comment by mingxuanzhangsfdx** [comment]
Hi @tehnrd thanks for putting up the PR. it has been merged and will get into next week's release. I know there are some discussions still around. If you are still interested in further enhancement, please let us know so we could specify the requirements. Due to business need, we do not have enough bandwidth developing this area for now. We really appreciate your contributions.
