### ISSUE TITLE
Autocomplete does not include the sustom SObject suffix (__c)

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/salesforcedx-vscode#592]
### Summary

Autocomplete displays custom SObject API name without the `__c` suffix.

### Steps To Reproduce:

1.  Using change set-based tools, connect to an organization that has at least one custom SObject.
1.  Edit any class and start typing the name of the SObject, as you would when instancing a new one.
1.  When typing the SObject API name, autocomplete shows the name but without the suffix.

### Expected result

Autocomplete should show the SObject API name with the suffix.

### Actual result

Autocomplete displayed the SObject API name without the suffix.

### Additional information

Considering a custom object called "Lightning Test", with `LightningTest__c` as its API name:

![](https://i.imgur.com/w8zGCyr.png)

This could be related to #575.

**VS Code Version**:

Version 1.26.1 (1.26.1)

**SFDX CLI Version**:

sfdx-cli/6.29.0-0a2482692c (darwin-x64) node-v8.9.4

**OS and version**:

MacOS High Sierra - 10.13.6 (17G65)

**Comment by vazexqi** [comment]
@renatoliveira - Did you do this step (https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex#enable-code-smartness-for-sobjects) to bring in the SObject definitions?

**Comment by renatoliveira** [comment]
@vazexqi I didn't. Now that I did, it really shows the correct API name. Sorry for the trouble! 

I think I might have used this if I were working on a DX project previously. This could be linked on the wiki entry about the change set-based tool.

**Comment by vazexqi** [comment]
@ntotten - We might need to make this step more transparent. Or make the sobject language server completely more _offline_ as wlel.
