### ISSUE TITLE
Getting UNSUPPORTED_API_VERSION error when retrieving source from a sandbox

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/salesforcedx-vscode#593]
### Summary

After changing the endpoint from `login.salesforce.com` to `test.salesforce.com` on the JSON file, I tried to authenticate to a sandbox organization. Authorization is successful, but when retrieving the source code, as described in the instructions on the wiki, the operation fails with an `UNSUPPORTED_API_VERSION` error.

### Steps To Reproduce:

1. Create an empty project.
2. Change login endpoint to `test.salesforce.com` on the `sfdx-project.json` file.
3. Authorize the tool and try to retrieve the source using the `SFDX: Retrieve Source from Org` command on the `package.xml` file.
4. Error is shown in VSCode notification popup.

_Note: sandbox does have a custom domain specified._

### Expected result

Expected the source files to be retrieved successfully.

### Actual result

Source isn't retrieved at all. The command that is used by the tool, when appended with `--json`, throws up the following:

```
{
  "message": "UNSUPPORTED_API_VERSION: Invalid Api version specified on URL",
  "status": 1,
  "stack": "sf:UNSUPPORTED_API_VERSION: UNSUPPORTED_API_VERSION: Invalid Api version specified on URL\n    at module.exports.HttpApi.getError (/Users/renatoliveira/.local/share/sfdx/plugins/node_modules/jsforce/lib/http-api.js:250:13)\n    at /Users/renatoliveira/.local/share/sfdx/plugins/node_modules/jsforce/lib/http-api.js:95:22\n    at tryCallOne (/Users/renatoliveira/.local/share/sfdx/plugins/node_modules/promise/lib/core.js:37:12)\n    at /Users/renatoliveira/.local/share/sfdx/plugins/node_modules/promise/lib/core.js:123:15\n    at flush (/Users/renatoliveira/.local/share/sfdx/plugins/node_modules/asap/raw.js:50:29)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)",
  "name": "sf:UNSUPPORTED_API_VERSION",
  "warnings": []
}
```

**VS Code Version**: Version 1.26.1 (1.26.1)
**SFDX CLI Version**: sfdx-cli/6.29.0-0a2482692c (darwin-x64) node-v8.9.4
**OS and version**: macOS High Sierra

**Comment by vazexqi** [comment]
I suspect you are using the pre-release version of the Salesforce CLI (installed via `sfdx plugins:install salesforcedx@pre-release`) and you are connecting to an org that still doesn't have that version yet.

See https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code#getting-started and how you need to tweak your API version.

**Comment by renatoliveira** [comment]
Jesus christ, I completely forgot that step (and I even created another project yesterday). Sorry for the trouble (again) :)
