### ISSUE TITLE
Unverified breakpoint in multi-package repo

### ISSUE THREAD

**Issue by nkskaare** [forcedotcom/salesforcedx-vscode#5951]
### Summary

Unable to stop at breakpoints with Apex Replay Debugger in a repo with multiple packages defined in sfdx-project.json.

### Steps To Reproduce:

1.  Set breakpoint for a class which is not on the default path "force-app/main/default/classes"
2. Start debugging session
3. See that breakpoint is greyed out

Update: Tried reproducing the issue with a simpler project structure than I have in the repo where it is failing, I am currently unable to reproduce, even though I am running in the same devcontainer environment. Any insight into how to further debug this is appreciated.

### Expected result

Regular breakpoint, which debugger can be stopped at.

### Actual result

Breakpoint is greyed out, saying unverified breakpoint.

### Additional information

![Screenshot 2024-11-19 at 14 34 46](https://github.com/user-attachments/assets/5cbcce1a-379f-467d-85a7-14b0c7b1d9b4)

**Salesforce Extension Version in VS Code**: v62.5.1

**Salesforce CLI Version**: @salesforce/cli/2.46.6 linux-x64 node-v18.20.4

**OS and version**: Ubuntu 22.04.5 LTS (Docker devcontainer)

**VS Code version**: 1.95.3

**Most recent version of the extensions where this was working**: v62.5.1 (Unsure. Tried reproducing the issue in the same type of container with a simpler project structure and it worked.)

**Comment by nkskaare** [comment]
Developer tools logs no error when trying to set the breakpoint, but the following error message is displayed when debugging session is finished.

![Screenshot 2024-11-19 at 15 34 13](https://github.com/user-attachments/assets/46f7fc41-5db4-4ee0-98b6-210838e23112)

**Comment by daphne-sfdc** [comment]
Hi @nkskaare, After you switch to debugging a different project and then switch back to your original project, are you still seeing this issue, or is this a one-time thing?  We'll be happy to help you debug this issue if it's consistently failing.

**Comment by nkskaare** [comment]
Yes, this is consistently failing in our project. I also experienced a colleague facing the same issue on a different computer. I am usually working in a remote development container, however he is not.

**Comment by nkskaare** [comment]
From what I could investigate further. The debug console reports the following:

```
3157: launchRequest: args={"name":"Launch Apex Replay Debugger","type":"apex-replay","request":"launch","logFile":"/workspaces/breakpoint-reproduce/.sfdx/tools/debug/logs/07LKI000000swRS2AY.log","stopOnEntry":true,"trace":true,"projectPath":"/workspaces/breakpoint-reproduce","__sessionId":"ba312233-64f3-44c3-b4af-64fd4c21c99b"}
Apex Replay Debugger session started for log file 07LKI000000swRS2AY.log.
62.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,FINER;WAVE,INFO;WORKFLOW,INFO
3157: setBreakPointsRequest: path=/workspaces/breakpoint-reproduce/src/core/package1/classes/TestBreakpoint.cls uri=file:///workspaces/breakpoint-reproduce/src/core/package1/classes/TestBreakpoint.cls lines=4
3157: setBreakPointsRequest: path=/workspaces/breakpoint-reproduce/src/core/package1/classes/TestBreakpoint.cls verified lines=
```

**Comment by nkskaare** [comment]
I was actually able to solve it...

If the `"path"` is given with a `./` prefix it causes the debugger to not return verified breakpoint lines. Removing the `./` solved the issue, also in my original project. 

```json
{
  "packageDirectories": [
    {
      "path": "./src/core/package1",
      "package": "package1",
      "default": true,
      "ignoreOnStage": ["validate"],
      "versionNumber": "0.1.0.NEXT"
    },

```
