### ISSUE TITLE
The docs link in the main README.md is invalid

### ISSUE THREAD

**Issue by priandsf** [forcedotcom/salesforcedx-vscode#5957]
### Summary

The home page references a folder in `forcedotcom` but the link leads to a 404.

> more information about developing Salesforce Extensions for VS Code in the [docs](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/docs) folder.

**Comment by priandsf** [comment]
Thanks bot, but the information you request above is irrelevant for this issue :-)

**Comment by daphne-sfdc** [comment]
Hi @priandsf, The README is now updated with the correct link to our public documentation.  Thank you.
