### ISSUE TITLE
Auto Suggest feature of SLDS Validator Extension on VS Code is not working

### ISSUE THREAD

**Issue by Luffy3315** [forcedotcom/salesforcedx-vscode#5985]
### Summary

I have my vs code on latest version and salesforce SLDS validator extension on 2.0.12 and salesforce cli is also up to date.
When clicked on Ctrl + Space the auto suggest is not popping up the suggested slds classes.
This work with version 1.4.11 but not with version starting with 2.0.XX

### Steps To Reproduce:

1) Update SLDS Validator to any version starting with 2.0.XX.
2) Create LWC cmp and include class attribute in any html tag and type "slds-" and ctrl + space'

### Expected result

List of relevant suggested SLDS classes.

### Actual result

Showing "No Suggestion".

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**: 62.9.1

**Salesforce CLI Version**: @salesforce/cli/2.69.14

**OS and version**:  Windows 11 Home Single Language, 23H2

**VS Code version**:  version 1.96

**Most recent version of the extensions where this was working**: 61.10.0 , SLDS Validator 1.4.11

**Comment by daphne-sfdc** [comment]
Hi @Luffy3315, I see that you have already filed [Issue #138](https://github.com/forcedotcom/salesforcedx-vscode-slds/issues/138) in the SLDS repo.  That is the correct repo to reach the SLDS Team.  As this is a duplicate issue, I am going to close it.
