### ISSUE TITLE
Providing the Apex Parser to SonarQube to support static analysis

### ISSUE THREAD

**Issue by abd3** [forcedotcom/salesforcedx-vscode#612]
**Is your feature request related to a problem? Please describe.**
There is an ongoing need to provide static code analysis tools for Apex (and other Salesforce languages). There are numerous efforts to do this such as [ApexPMD](https://github.com/pmd/pmd/issues/677), [SonarQube Enforce](https://github.com/fundacionjala/enforce-sonarqube-plugin), and VillageChief CodeScan. However, it is difficult for any of these projects to keep up with evolutions to the Apex language unless they can use the underlying parser. For example, there are numerous parsing issues in the Enforce tool.

**Describe the solution you'd like**
Please provide a way for these tools to use an officially maintained version of the Apex parser. Either enable LSP support so that they could run an Apex parsing service and delegate parsing to that, or make an official version of the Apex JAR available that can be used for parsing.

**Describe alternatives you've considered**
There is an [Apex parser that was written for Enforce](https://github.com/fundacionjala/enforce-sonarqube-plugin/tree/master/apex-squid/src/main/java/org/fundacionjala/enforce/sonarqube/apex). ApexPMD has also worked with you to get access to the Jorje JAR. Not sure if VillageChief wrote their own or not.
Any option other than plugging into a Salesforce official jar will always lag behind, require complex maintenance, and yield bugs with new releases of Apex.

**Additional context**
The SonarQube team wants to build an official Apex plugin for their product. It's [on their roadmap here](https://jira.sonarsource.com/browse/MMF-1416?jql=text%20~%20%22apex%22). We should connect the relevant teams.

**Comment by ntotten** [comment]
I have passed this request on to the Apex team. It is unlikely something they can get to soon, but its something they are considering. For now I am going to close this issue as it isn't directly related to VSCode extensions.
