### ISSUE TITLE
Not able to see sfdx force:source:retrieve 

### ISSUE THREAD

**Issue by kamipatel** [forcedotcom/salesforcedx-vscode#636]
### Summary

I do not see command sfdx force:source:retrieve. I have updated VS Code extension

### Steps To Reproduce:

In project searched for "sfdx force:source:retrieve "

### Expected result

Ability to retrieve regular org source code

### Actual result

I do not see command sfdx force:source:retrieve. I have updated VS Code extension

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: Latest

**SFDX CLI Version**:Latest

**OS and version**:

**Comment by ntotten** [comment]
The feature is in preview: https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code
