### ISSUE TITLE
Generate Apex from WSDL

### ISSUE THREAD

**Issue by SalesforceBobLightning** [forcedotcom/salesforcedx-vscode#644]
Please, could the Salesforce DX Extension for VS Code generate Apex classes based on WSDL?

I'd imagine being able to provide a WSDL URL or file, and the Apex being generated and added to local Salesforce DX project.

**Comment by vazexqi** [comment]
@SalesforceBobLightning For the time being, you could try running https://github.com/forcedotcom/WSDL2Apex locally and using that to generate the Apex stubs.

**Comment by SalesforceBobLightning** [comment]
Thanks @vazexqi - I am aware of WSDL2Apex.

Are you planning on adding this as a feature to the Salesforce DX Extension for VS Code?

**Comment by vazexqi** [comment]
We are tracking this as feedback (hence, the label) for now.

**Comment by ntotten** [comment]
I am closing this as it is unlikely to happen any time soon.
