### ISSUE TITLE
Issue while binding key to deploy source to org

### ISSUE THREAD

**Issue by prabhat1894** [forcedotcom/salesforcedx-vscode#647]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Provide any key binding for deploy this source file to org

### Expected result

sfdx command to deploy the current file to the server must have run
### Actual result

got an error:-

 Cannot read property 'fsPath' of null

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:  1.24.1

**SFDX CLI Version**: sfdx-cli/6.34.0-6fec0d751a (darwin-x64) node-v8.9.4

**OS and version**: macOS 10.13.6 (17G65)

**Comment by lcampos** [comment]
Thanks for reporting this @prabhat1894 & @cyberjus. This and #662 are duplicates and I'll close this in favor of that one given the thread contains more details.
