### ISSUE TITLE
Support SOQL queries via SFDX

### ISSUE THREAD

**Issue by muenzpraeger** [forcedotcom/salesforcedx-vscode#65]
### Functionality
A common use case when developing with the Platform is to query existing data. For that the sfdx command to query data via SOQL and output that data should be implemented.

### Implementation
* A new menu binding "SFDX: Execute SOQL query" will be implemented.
* User enters the wanted SOQL query into a VScode inputBox.
* SOQL query will be run against the project scratch org, output in JSON format.
* Rendering of the output JSON as HTML in preview side pane (maybe using mustache/handlebars).

**Comment by muenzpraeger** [comment]
Initial implementation

https://github.com/muenzpraeger/salesforcedx-vscode/tree/sfdx-soql-query/packages/salesforcedx-vscode-apex

**Comment by muenzpraeger** [comment]
@vazexqi I'm wondering what in your opinion the preferred option would be to fetch the json output of a sfdx command from the ChannelService. Any thoughts on that before I add something would be welcome.

**Comment by muenzpraeger** [comment]
I played a bit around with that over the weekend. Generating a simple HTML doc works just fine. I used a custom URI scheme (sfdx://...) for that.

**Comment by vazexqi** [comment]
> I'm wondering what in your opinion the preferred option would be to fetch the json output of a sfdx command from the ChannelService. Any thoughts on that before I add something would be welcome.

We have an example of this in https://github.com/forcedotcom/salesforcedx-vscode/blob/9e44a54603d454c4e8e44809d591586c5d487f83/packages/salesforcedx-apex-debugger/src/core/sessionService.ts#L63 that @DatGuyJonathan added.

For the display of the of the SOQL results, I was thinking of something like https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

I think as a first pass we can display the raw STDOUT results (not the JSON). I think the STDOUT results is actually more human readable than the JSON output. JSON is meant for processing by a downstream consumer.

In the long term, I am thinking of something like the table/grid display of https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

**Comment by muenzpraeger** [comment]
Agreeing on the long term.

Having said that - once develop has been merged I'm ready to rebase and push the soql query action. ;-)
