### ISSUE TITLE
How to begin contributing?

### ISSUE THREAD

**Issue by d0th3do** [forcedotcom/salesforcedx-vscode#650]
I would like to be begin contributing to this project. Can someone guide me to the necessary documentation I need to read to get started?

**Comment by vazexqi** [comment]
Good taking to you yesterday at Dreamforce! We have a folder of docs at https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/docs that should give you some ideas. Also the CONTRIBUTING guide would be useful — https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/CONTRIBUTING.md
