### ISSUE TITLE
Develop Against Any Org in Visual Studio Code failing

### ISSUE THREAD

**Issue by kamipatel** [forcedotcom/salesforcedx-vscode#651]
### Summary

_Short summary of what is going on or to provide context_.
I followed this in order to develop against my dev sandbox. 
I am getting error with this command and not able to create project.
sfdx force:project:create --projectname kamtest --outputdir /Users/kamlesh.patel/lwc --manifest
 ▸    Unexpected argument --manifest

### Steps To Reproduce:
Follow https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code
1.  This is step 1.
Run 
sfdx force:project:create --projectname kamtest --outputdir /Users/kamlesh.patel/lwc --manifest
 ▸    Unexpected argument --manifest

### Expected result
Should create a project

_Describe what should have happened_.

### Actual result

sfdx force:project:create --projectname kamtest --outputdir /Users/kamlesh.patel/lwc --manifest ended with exit code 1

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by vazexqi** [comment]
I suspect you don’t have the right version of the CLI. 

What are the output of the following in the terminal: 

`sfdx version` 
and
`sfdx plugins`

**Comment by kamipatel** [comment]
Looks like I had to reinstall plugin. It works now. Thanks!

**Comment by rickschmidtsfdc** [comment]
> I suspect you don’t have the right version of the CLI.
> 
> What are the output of the following in the terminal:
> 
> `sfdx version`
> and
> `sfdx plugins`

What are the correct versions? I've tried reinstalling the pre release plugin several times and the pre release commands don't appear in vs code. 

I'm running sfdx-cli/6.34.0-6fec0d751a (darwin-x64) node-v8.9.4
and 
salesforcedx 44.0.25 (pre-release)

The appropriate user setting has also been applied.

**Comment by rickschmidtsfdc** [comment]
The issue I was having in particular was VS Code was out of date. "Check for updates" said I was current which was not the case. After downloading the latest it worked correctly.
