### ISSUE TITLE
Don't see all available commands

### ISSUE THREAD

**Issue by domonique-ncino** [forcedotcom/salesforcedx-vscode#672]
### Summary

I'm trying to use the extension and push my code up to my scratch org but I don't see the command in the commandPalette

### Steps To Reproduce:

1.  Installed the Extension
1.  Reloaded
1. Pulled command palette up
1. Searched for 'Push'
1. No results

### Expected result

Show come up with the push command

### Actual result

No results

### Additional information

**VS Code Version**:
1.28.0
**SFDX CLI Version**:
43.19.0
**OS and version**:
High Sierra 10.13.6

**Comment by lcampos** [comment]
@domonique-ncino thanks for reporting this, did you get any error on the Output panel for vscode ? Did you try searching for `SFDX: Push` on the command palette ? 

It would be helpful if you could attach an image of what you get on the command palette.

**Comment by domonique-ncino** [comment]
<img width="618" alt="screen shot 2018-10-12 at 9 05 07 am" src="https://user-images.githubusercontent.com/27729325/46871068-5ff3ca80-cdfe-11e8-89d9-aac515d39aa2.png">
<img width="615" alt="screen shot 2018-10-12 at 9 08 57 am" src="https://user-images.githubusercontent.com/27729325/46871105-7a2da880-cdfe-11e8-95ca-cdc1d4a2c979.png">

**Comment by vazexqi** [comment]
@domonique-ncino - Push works with a scratch org. Have you authenticated against a scratch org yet? You can check by doing SFDX: Open Default Org. If there is nothing associated then that means that the commands won't show up.

The technical reasons for this is that the push commands are gated on having an org associated. See https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-core/package.json#L204. In particular, the `sfdx:default_username_has_change_tracking` gate.

**Comment by domonique-ncino** [comment]
I authenticated against a scratch org successfully and then tried to run Open Default Org and got this.

<img width="901" alt="screen shot 2018-10-12 at 11 16 38 am" src="https://user-images.githubusercontent.com/27729325/46878132-7b67d100-ce10-11e8-9dfe-c5df1209948b.png">

I ran the sfdx force:config:set defaultusername=<username> to set the default username and it worked. Open Default Org now opens my org but I still don't see any new commands for pushing to my default org.

**Comment by vazexqi** [comment]
![screenflow](https://user-images.githubusercontent.com/54414/46879336-9d565900-cdfa-11e8-9b64-aea76aefe37a.gif)

This is how it works on my end.

What does your .sfdx/sfdx-config.json look like? There should be an entry for `defaultusername`. This is automatically set when you associate a default scratch org. The SFDX: Create Default Scratch Org... does this for you automatically.

**Comment by domonique-ncino** [comment]
Works now. Thanks guys for all your help!
