### ISSUE TITLE
How do we install a beta version of this extension in vscode

### ISSUE THREAD

**Issue by venkatpolisetti** [forcedotcom/salesforcedx-vscode#673]
I have installed sfdx pre-release but could not find any salesforcedx-vscode beta version (44) to install to go along with the cli pre-release version. The current salesforcedx-vscode version 43.19.0 does not bring up force:source:retrieve or force:source:deploy.

**Comment by lcampos** [comment]
Hi @venkatpolisetti, we normally ship preview features behind feature flags so there is no need to install a different version of the extensions. If you follow the [Develop Against any Org](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code) wiki article you should be able to use those commands.

**Comment by venkatpolisetti** [comment]
Thank you, that worked.
