### ISSUE TITLE
Error Retrieve Source from Org 

### ISSUE THREAD

**Issue by hbwilly54** [forcedotcom/salesforcedx-vscode#686]
Starting SFDX: Authorize an Org

sfdx force:auth:web:login --setalias TestBP --setdefaultusername
Successfully authorized support.sf@willysolutions.com.testbp with org ID 00DM0000000FsO0MAK
You may now close the browser
sfdx force:auth:web:login --setalias TestBP --setdefaultusername ended with exit code 0

Starting SFDX: Retrieve Source from Org

sfdx force:source:retrieve --manifest c:\Source\SproutFin\BPAPIfix\manifest
ERROR:  EISDIR: illegal operation on a directory, read.
sfdx force:source:retrieve --manifest c:\Source\SproutFin\BPAPIfix\manifest ended with exit code 1

**Comment by vazexqi** [comment]
Duplicate of #678. Let's consolidate discussions there.

**Comment by ntotten** [comment]
Related to #690
