### ISSUE TITLE
Error while converting force.com IDE format src to sfdx format

### ISSUE THREAD

**Issue by manujCLI** [forcedotcom/salesforcedx-vscode#701]
--
Receiving this error while converting src
**This directory does not contain a valid Salesforce DX project.**

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  First command :  sfdx force:project:create -n tempproj
2.  command ran from outside the git repo folder where git repo folder name is 'common'.
sfdx force:mdapi:convert --rootdir ./common/src --outputdir ./tempproj

### Expected result

Source code should have been converted.

### Actual result

Following error received : 
This directory does not contain a valid Salesforce DX project.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:v 1.28.2

**SFDX CLI Version**: sfdx-cli/6.37.0-2d5d7e1522 (windows-x64) node-v8.9.4

**OS and version**: Windows 10

**Comment by ntotten** [comment]
See this guide for conversion. I think you missed step 3. https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code#migrate-by-conversion-advanced

Please reopen if this doesn't solve the problem.

**Comment by manujCLI** [comment]
Thanks, I was referring to this documentation https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code
