### ISSUE TITLE
Turn On Apex Debug Log for Replay Debugger not setting correct debug level

### ISSUE THREAD

**Issue by matthewjcavalier** [forcedotcom/salesforcedx-vscode#710]
When I run the command 'SFDX: Turn On Apex Debug Log for Replay Debugger' everything looks to be fine. Then I run a single test that fails, run the command 'SFDX: Get Apex Debug Logs...' and select the last log like normal. The issue is though that when the file is downloaded the APEX_CODE log level is DEBUG and the VISUALFORCE log level is INFO, both of which is incorrect for debugging.

### Additional information
**Internal Work Item**: [W-5540032](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005X5ceIAC/view)

**Comment by lcampos** [comment]
@matthewjcavalier I'm closing this issue since the fix is out as part of version 44.8.0 of the extensions. Thanks for reporting this and let us know if there's anything else we can help with.
