### ISSUE TITLE
JAVA 8 required to run... Yet it is available

### ISSUE THREAD

**Issue by gribis** [forcedotcom/salesforcedx-vscode#714]
Issue Type: <b>Bug</b>

Apex code editor exclaims that JAVA 8 needs to be installed. Jave 8 SE JDK is installed on the system. I suspect a configuration telling this extension where to find JDE is missing. Could you provide insight/documentation for this issue on Windows (7)?

Extension version: 44.4.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.41GB (2.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by veritascs** [comment]
Have you verified your JAVA_HOME env variables in Windows? https://docs.opsgenie.com/docs/setting-java_home

**Comment by lcampos** [comment]
@gribis can you try these steps https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server#how-do-i-configure-the-version-of-java-that-the-apex-language-server-uses and see if that addresses the issue.

In the meantime I'll make sure we surface a more meaningful error/link when this happens in the extensions.
