### ISSUE TITLE
apex-jorje-lsp.jar inconsistencies when parsing mixed-cased Apex keywords

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [forcedotcom/salesforcedx-vscode#718]
### Summary

Hi,

We are using the Apex Language Server library (apex-jorje-lsp.jar) in order to parse Apex code.

In practice, we have noticed that the Apex language is case insensitive and keywords such as "if" and "else" can be written like "IF" and "ELSE". Thus the following code runs successfully on the Salesforce platform:

        IF (lastName != null) {
            // logic...
        } ELSE {
            // logic...
        }

However, for the "if" keyword, the ApexLexer identifies the token as being an IF (ANTLR CommonToken type 82) only when the text is lowercase. When it is uppercase ("IF") or mixed-case ("iF"), it marks the token as identifier (ANTLR CommonToken type 79). It is the same for other keywords, as well.

Our question is: is this the desired behavior? This brings inconsistencies between how the Apex language gets parsed and how it eventually gets executed.

Do you have some advice on how we could overcome this inconsistency, and be able to parse correctly valid Apex code even when keywords are not lowercased?

Thank you,
Andrei

### Additional information

**VS Code Version**: 1.28.2

**SFDX CLI Version**: sfdx-cli/6.38.0-0d66175ccf (linux-x64) node-v8.9.4

**OS and version**: Ubuntu 18.04.1 LTS

**apex-jorje-lsp.jar version**: 44.2.0

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support for direct use of the jorje library. However, I will pass the issue on to the apex team.
