### ISSUE TITLE
Support for multiple src folders

### ISSUE THREAD

**Issue by julesx** [forcedotcom/salesforcedx-vscode#721]
**Is your feature request related to a problem? Please describe.**
I have a core library, as well multiple products.  These live in different sub folders under the project root.  Currently I specify my product as the `src` value, which works great until I need to do code coverage of the core code.

**Describe the solution you'd like**
The ability to specify multiple `src` folders so that code coverage works properly across my entire vs code workspace.

**Describe alternatives you've considered**
Only alternative I can think of is a seperate vs code workspace of the same project with a different src path.

**Comment by ntotten** [comment]
I don't exactly understand what you mean. Can you give me an example of what you would like your directory structure to look like?
