### ISSUE TITLE
Unable to launch Apex Debugger

### ISSUE THREAD

**Issue by jhuizenga** [forcedotcom/salesforcedx-vscode#722]
When trying to launch the Apex Debugger from vscode, is does not launch. 

I have used the standard configuration as found in the documentation, but is does nothing. I dit create a permissionset en assign it. In our production org I cannot find any information about a session being started/used.

```
{
	"configurations": [
		{
			"name": "Launch Apex Debugger",
			"type": "apex",
			"request": "launch",
			"sfdxProject": "${workspaceRoot}"
		}
	]
}
```

I have used the debugger succesfully a number of times with vscode, but in the past months I have not been able to use it anymore. 

### Steps To Reproduce:

1. Push the ' Start debugging' button in VSCode

### Expected result

Apex debugger should have been started.

### Actual result

The little blue line underneath the button keeps running around:

![image](https://user-images.githubusercontent.com/19267591/47999398-ca004680-e102-11e8-8f64-e13e9e88e739.png)

<details>
<summary>Details</summary>

**VS Code Version**:
1.28.2 (user setup)

**SFDX CLI Version**:
sfdx-cli/6.38.0-0d66175ccf (windows-x64) node-v8.9.4

**OS and version**:
Windows 10 Enterprise

**Internal Work Item**: 
[W-5622038](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005oRQbIAM/view)
</details>

**Comment by lcampos** [comment]
@jhuizenga thanks for reporting this. We are aware of it and currently working on a fix. I'll make sure to update this issue to let you know when the fix is going out.

**Comment by lcampos** [comment]
@jhuizenga could you confirm the following. You're able to deploy and run other commands that interact with the org. Do you get any error message in vscode's Output view or Debug Console view ? I want to make sure the fix we're working on is in fact the same as what you're experiencing. Thanks.

**Comment by nlrisbell** [comment]
The same issue is occurring for us in VSCode 1.29.0.  Other commands seem to work fine in the scratch org and we have been using Interactive Debugger for a long time without errors.  I upgraded VSCode and have re-installed the SF Extension Pack with the Interactive and Replay debuggers (v. 44.6.1) and no luck.  I do get a popup on launch that has no info. 
![screen shot 2018-11-14 at 11 33 33 am](https://user-images.githubusercontent.com/26878478/48504107-31a04b00-e801-11e8-8ebf-3026fa059c54.png)

**Comment by lcampos** [comment]
Thanks for the info @nlrisbell, we were able to find a way to replicate the issue and we're working on getting a fix out. Apologies for the problems this has caused, we'll keep this thread up to date.

**Comment by lcampos** [comment]
@jhuizenga @nlrisbell we've release the fix for this as part of version 44.7.0 of the extensions. Thanks for being patient and let us know if you run into any other issues.

**Comment by nlrisbell** [comment]
That is delightful, @lcampos - thanks for your quick fix!!  I am surprised there is not more discussion of this - isn't the Apex Debugger in high use?  What is the timeline for the 44.7.0 extension release?

**Comment by lcampos** [comment]
Awesome, thanks for confirming it's working for you now.

We see more people using the Apex Replay Debugger since Apex Debugger requires a license, so that could be it but please keep opening issues for bugs or feature requests.

**Comment by lcampos** [comment]
hi @lflorezcyberark please open a new issue for that since it's unrelated to this one; this was an issue with Apex Debugger and the issue you are experiencing is with Apex Replay Debugger. 

As part of the new issue add the details you have here and include which version of vscode you are on and operative system you are working with. Thanks.

**Comment by jhuizenga** [comment]
@lcampos thnx for fixing this issues. I'm sorry for not replying on this issue earlier.. notifications went to my spam folder without me noticing it. I'll give it a try again today to see if my issue disappeared!

**Comment by jhuizenga** [comment]
I can confirm it is working again! 👍

**Comment by maimoona-shahid** [comment]
Same Launching error appearing in Version 1.54.1 , it keeps loading but nothing happens.

**Comment by SidTrailhead** [comment]
> Awesome, thanks for confirming it's working for you now.
> 
> We see more people using the Apex Replay Debugger since Apex Debugger requires a license, so that could be it but please keep opening issues for bugs or feature requests.

Hi ,
I am still facing the issue.

![image](https://user-images.githubusercontent.com/67403883/115109043-37318a80-9f91-11eb-99a8-a1fcf2346038.png)

When I click on Launch Apex Replay debugger, nothing really happens.
Please suggest what to do.
I am using version v51.8.0
