### ISSUE TITLE
 SFDX Deploy This Source to Org error, CLI not installed

### ISSUE THREAD

**Issue by Lafexlos** [forcedotcom/salesforcedx-vscode#734]
### Summary

When using SFDX Deploy This Source to Org command for deploying my changes to a sandbox I am getting an error saying 

> The Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli

### Steps To Reproduce:

1.  Create SFDX project with manifest
1.  Authorize an org and retrieve using package.xml
1. Make some changes and use SFDX: Deploy Source to Org (sfdx force:source:deploy)

### Expected result

Changes pushed to org successfully.

### Actual result

<pre>Starting SFDX: Deploy Source to Org

sfdx force:source:deploy --json --loglevel fatal --sourcepath c:\Projects\MyPathToFile.cls
sfdx force:source:deploy --json --loglevel fatal --sourcepath c:\Projects\MyPathToFile.cls ended with error spawn sfdx ENOENT
The Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli
</pre>

### Additional information

Starting to happen after the extension update.

**VS Code Version**: 

1.28.2
7f3ce96ff4729c91352ae6def877e59c561f4850
x64

**SFDX CLI Version**:
sfdx-cli/6.38.0-0d66175ccf (windows-x64) node-v8.9.4

**Salesforce CLI Integration Extension Version**:
44.6.0

**OS and version**:
Windows 10

![image](https://user-images.githubusercontent.com/11299148/48254097-1062e780-e41a-11e8-81c3-2863b8b85b56.png)

**Comment by skygiven** [comment]
Hello. I have the similar issue when try to deploy:  
ended with error spawn C:\WINDOWS\system32\cmd.exe ENOENT

**Comment by ericrsmith35** [comment]
I have the same error when trying to deploy

**Comment by arodriguez-cvent** [comment]
I am getting same issue as skygiven and taalgaard and ericrsmith35.

When I right click an Apex class , when I select "SFDX: Deploy Source to Org", I get:

C:\WINDOWS\system32\cmd.exe ENOENT

however if I select "SFDX: Retrieve Source from Org", it completes successfully

If I copy the sfdx force:source:deploy --sourcepath command from the output into the terminal, it completes successfully.

In other words I am able to successfully push the code to my sandbox from VS Code from the CLI, however when running the command directly from VS Code using the "SFDX: Deploy Source to Org", it fails and says that the path to my cmd.exe does not exist.

Please help!

**Comment by arodriguez-cvent** [comment]
@ntotten I tried closing/restarting, deploying, running sfdx update, restarting, and deploying again. still not working. running the sfdx force:source:deploy command directly from the terminal or from command prompt still works and successfully pushes the code.

still getting:

C:\WINDOWS\system32\cmd.exe ENOENT

**Comment by ntotten** [comment]
Okay, thanks. We are looking into this urgently. It seems there might be an issue with Windows 10 in the release yesterday. We will try to get a fix out ASAP.

**Comment by lcampos** [comment]
Posting here as well to keep the threads updated. The issue was the same as the one reported in #737. 
The fix is out now in the marketplace as part of version 44.6.1. 

Again, apologies to everyone impacted and thanks for your patience.
