### ISSUE TITLE
Trying to deploy and getting "ended with error spawn C:\WINDOWS\system32\cmd.exe ENOENT"

### ISSUE THREAD

**Issue by taalgaard** [forcedotcom/salesforcedx-vscode#737]
Trying to deploy and getting "ended with error spawn C:\WINDOWS\system32\cmd.exe ENOENT"  

Started occurring yesterday after the new update.

I am on Windows 10

_Originally posted by @skygiven in https://github.com/forcedotcom/salesforcedx-vscode/issues/734#issuecomment-437352235_

**Comment by ericrsmith35** [comment]
I am having this same issue on Windows 10

**Comment by ntotten** [comment]
Can you provide more information on how _HOW_ you are deploying? Are you right-clicking a folder, is it deploying to a scatch org or sandbox? Are you using a package.xml file? Exact repro steps will be helpful.

Thanks!

**Comment by taalgaard** [comment]
Exact same scenario and test results as ntotten.  Wednesday it worked fine.  Now I cannot right click and deploy the file.  I can retrieve files by right clicking.  I did notice that there was an extension upgrade yesterday.  Wonder if that had anything to do with it?

For those who are also experiencing the issue was it working for you before yesterdays update?

**Comment by matthewjcavalier** [comment]
I am experiencing the same issue, and I am pretty sure that the deploy source to org was working yesterday.

**Comment by arodriguez-cvent** [comment]
My first attempts to deploy from VS Code were made yesterday 8 PM EST and I was getting this same error from the start.

**Comment by lcampos** [comment]
Hi, sorry for the problems you're experiencing. We're currently working on a fix and will release it as soon as possible. We'll keep this thread up to date.

**Comment by protivakid** [comment]
Same issue on Windows 7. I wasted my time trying to debug. Is there someplace that lists issues so I don't spend my time thinking it was just my machine. Guess i'll have to check here

**Comment by ntotten** [comment]
@protivakid This is the place that lists issues.

We will have the fix released soon. Apologies for the problems.

**Comment by lcampos** [comment]
We have a fix for this now, it's currently going through our test/release pipeline and should be available soon in the marketplace.

**Comment by lcampos** [comment]
The fix is out now in the marketplace as part of version 44.6.1. Again, apologies to everyone impacted and thanks for your patience.

**Comment by arodriguez-cvent** [comment]
Thanks @lcampos ... both the deploy and retrieve commands are working from VS Code for me now

**Comment by Tanisha123** [comment]
getting same error on authorizing the org. Please help

**Comment by Vru70** [comment]
If you still got the same error, you can Goto > Control Panel\System and Security\System\Advance system setting\Enviroment variable and set system variables path C:\Windows\System32\ variable and restart your System. It will fix this error, and you will be able to Authorize an Org.

**Comment by Vru70** [comment]
Also verify the following
Please try and kill the taks running parallel in the task manager, relaunch cmd/visual studio and try again (If you see any node.exe file, kill it) 
Once we create the SFDX project , there will be an attribute called: oauth local port - please update it with any combination 4 digit number and retry.
{
"packageDirectories": [
{
"path": "force-app",
"default": true
}
],
"namespace": "",
"sfdcLoginUrl": "https://login.salesforce.com",
"oauthLocalPort": "7717",
"sourceApiVersion": "45.0"
}

**Comment by generalmad** [comment]
@Vru70 

I'm having the same problem. Just downloaded and updated yesterday. Followed your advice on changing the system32 path, but it still won't let update the organization. I'm working off of [trailhead](https://trailhead.salesforce.com/en/content/learn/projects/quick-start-lightning-web-components/set-up-visual-studio-code). I am unfamiliar with what you mean by

> (If you see any node.exe file, kill it)

Also, I don't see the OAuth Local Port anywhere in the workspace.

> Once we create the SFDX project , there will be an attribute called: oauth local port - please update it with any combination 4 digit number and retry.


Please send help.

**Comment by mohanraj-r** [comment]
@generalmad This issue should be fixed now. Can you please check with the latest version of the extension.
