### ISSUE TITLE
force:source:push Stopped working after adding manifest file to work with SFDX: Deploy Source to Org

### ISSUE THREAD

**Issue by sserif** [forcedotcom/salesforcedx-vscode#741]
After trying "Develop Against Any Org in Visual Studio Code (Beta)" provided here:
[Click Here](https://releasenotes.docs.salesforce.com/en-us/winter19/release-notes/rn_vscode_any_org.htm)
Salesforce DX force:source:push command keeps failing with the following error:
`force-app/manifest/package.xml-meta.xml        Error parsing file: Element 
                                                                                {http://soap.sforce.com/2006/04/metadata}types 
                                                                                invalid at this location in type EmailServicesFunction (3:12)`

Package xml used:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>44.0</version>
</Package>
```

### Steps To Reproduce:

1. Follow steps in the link provided above

### Expected result

Should work as it would with any DX Project.

### Actual result

Getting the error above

**VS Code Version**:
Version 1.28.2 (1.28.2)

**SFDX CLI Version**:
sfdx-cli/6.38.0-0d66175ccf (darwin-x64) node-v8.9.4

**OS and version**:
macOS High Sierra 10.13.6

**Comment by kbierbaum** [comment]
@sserif can you confirm you're using sfdx force:source:push instead of sfdx force:source:deploy? Deploy should be the command used during development against non-scratch orgs. Thanks!
