### ISSUE TITLE
when i try SFDX:retrieve source from org , error after 2 min with !  'ECONNRESET': read ECONNRESET

### ISSUE THREAD

**Issue by kristualdandamudi** [forcedotcom/salesforcedx-vscode#745]
step : 1 Create project with manifest
 SFDX: Create Project with Manifest
step :2  change the login URL to test.salesforce.com in  sfdx-project.json file
Step :3 Authorize the Sandbox by using " SFDX: Authorize an Org "  then after run sfdx force:org:list
 it gives    ────────────────
(U)  hf-sb          sdandxxxx@xxx.xxx.xxfix  00D3F0000000h8YUAQ  Connected 
step:4 then i tried "SFDX: Retrieve Source from Org" from package.xml file

       after 2 min running cli later it gives error like below
    sfdx force:source:retrieve --manifest c:\Users\sdaxxxx\Desktop\xxxx\hfsb\manifest\package.xml
 !    'ECONNRESET': read ECONNRESET

i expect the source in to local

**Comment by ntotten** [comment]
Can you tell me if you are behind a corporate proxy?

**Comment by kristualdandamudi** [comment]
yes @ntotten  i am working behind firewall, but it works if i used retrieve command from terminal instead of right click on package.xml file for source in to local.
i don't know what is the reason.

**Comment by renatoliveira** [comment]
I'd check the proxy settings first. I too get this error sometimes when I'm behind the proxy at the customer I'm working with at the moment. The solution is to issue the retrieve command again one or two more times.

**Comment by VeenaChowdaryGudapati** [comment]
Hi,
I would like to reopen this issue. I have performed all necessary installations as in documentation. When i try to get the Source to local from Org. I get the error.

sfdx force:source:retrieve --manifest c:\Users\xxx\Desktop\SFDX Test Project\SFDX Test Project\manifest\package.xml
ERROR:  Cannot read property 'endsWith' of undefined.
fdx force:source:retrieve --manifest c:\Users\xxx\Desktop\SFDX Test Project\SFDX Test Project\manifest\package.xml ended with exit code 1
