### ISSUE TITLE
Extensions fail to Activate, Undefined, Parse error in file, etc.

### ISSUE THREAD

**Issue by dbarrett24** [forcedotcom/salesforcedx-vscode#746]
### Summary
I've installed the CLI, Java 8, and the extensions on other Windows 10 computers with no issues. On my current computer: I've been able to use the CLI to create a Project with Manifest with no issues. But when I load VScode now (same day), I get a notification in the bottom right corner: 

> "Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log"
> 

Also any SFDX command in VS Code will fail, both in the Terminal or the Command Palette : "command ______ not found".

When I open Developer Tools the console shows the following:
![image](https://user-images.githubusercontent.com/24259143/48429496-8ae97b00-e72a-11e8-8636-8c844b9e9d04.png)

 followed by many Extension Activation Errors.

I've tried uninstalling extensions and reinstalling, uninstalling the CLI and reinstalling, uninstalling VSCode and reinstalling, deleting the Code folder found in _Users/[UserName]/AppData/Roaming/Code_ and starting VSCode. I'm at a complete loss here, and I'm unsure where to start.

### Steps To Reproduce:

1.  Launch VSCode
2.  Wait for Extensions to activate....then get the failure message.

### Expected result

The extensions should activate and I should use the command palette with no issues.

### Actual result
Extensions fail to activate, I get errors every time I use a SFDX command.

### Additional information

**VS Code Version**:
Latest Version 1.29.0
**SFDX CLI Version**:
Latest Version 6.38.0
**OS and version**:
Windows 10 version: 1803
**Internal Work Item**: [W-5616247](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07B0000005xiZ0IAI)

**Comment by lcampos** [comment]
Hi @dbarrett24, I think this might be caused by a json file having invalid json in it. Can you open the project you are trying to work with then go to `.sfdx/sfdx-config.json` and confirm the json in it is correct ?

**Comment by dbarrett24** [comment]
It seems to be correct. Let me know if I'm wrong!

See here:
![image](https://user-images.githubusercontent.com/24259143/48436375-c6d90c00-e73b-11e8-97aa-183c86a77e75.png)

**Comment by lcampos** [comment]
hi @dbarrett24 that's the wrong file, can you open `.sfdx` folder and search for `sfdx-config.json` and verify that file contains valid json ?

**Comment by dbarrett24** [comment]
It seems that the .sfdx folder is empty in this project, though I used SFDX Create Project with Manifest to create this project and that file was never created.

**Comment by lcampos** [comment]
That's interesting, let me see if I can replicate that on my side.

**Comment by lcampos** [comment]
I've been able to replicate your issue, which seems to be with a corrupted file in the cli. @dbarrett24 , based on your error log, can you go to `c:/Users/db2448/.sfdx/` and delete `acknowledgedUsageCollection.json`, then reload your VSCode and confirm this fixes the issue ?

**Comment by dbarrett24** [comment]
It seems to have fixed the issue! Thank you so much!
