### ISSUE TITLE
ERR_ASSERTION: A name parameter is required to create a storage

### ISSUE THREAD

**Issue by pramodht** [forcedotcom/salesforcedx-vscode#749]
I am trying to get started with Eclipse to VSCode conversion.

I am getting this error when creating manifest
sfdx force:project:create --projectname metadata --outputdir /Users/pthammishetty/Documents --manifest
 ▸    ERR_ASSERTION: A name parameter is required to create a storage

**Comment by ntotten** [comment]
FYI: @forcedotcom/platform-cli

**Comment by kbierbaum** [comment]
Hi @pramodht what version of the CLI/Vs Code extensions were you using? Can you sfdx update and attempt with the latest? Thanks

**Comment by vazexqi** [comment]
Duplicate of #253

**Comment by vazexqi** [comment]
See #253 for a workaround.

**Comment by pramodht** [comment]
> See #253 for a workaround.

I don't understand the workaround at all. I am switching from Eclipse. The documentation says use the **sfdx force:project:create --projectname metadata --outputdir /Users/pthammishetty/Documents --manifest**
and once the project is created then copy all the packake.xml to the manifest folder... here it is giving me an error on step 1
