### ISSUE TITLE
Need a more descriptive error needed SFDX : Deploy this Source to Org is ran and test are running that prevents changes

### ISSUE THREAD

**Issue by taalgaard** [forcedotcom/salesforcedx-vscode#753]
If I try and use  SFDX : Deploy this Source to Org while someone is running tests (which lock changes to metadata, etc) I would like to see a more descriptive error other than the following.  Maybe use the same error message that you receive that the Developer Console throws.

`sfdx force:source:deploy --json --loglevel fatal --sourcepath c:\salesforce\DEVQA\force-app\main\default\classes\TriggerAccessRequestTest.cls
{"message":"Deploy failed.","status":1,"stack":"DeployFailed: Deploy failed.\n    at ALMError (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\salesforce-alm\\dist\\lib\\almError.js:44:19)\n    at MetadataRegistry.initializeMetadataTypeInfos.then.catch.e (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceApiCommand.js:67:35)\n    at tryCatcher (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Immediate.Async.drainQueues (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)","name":"DeployFailed","result":[{"error":"Unknown"}],"warnings":["All --json output, including on error, is moving to stdout. Use the SFDX_JSON_TO_STDOUT environment variable to move over to the new functionality. This will become the default in version 45."]}
sfdx force:source:deploy --json --loglevel fatal --sourcepath c:\salesforce\DEVQA\force-app\main\default\aura\accessRequestForm\accessRequestForm.cmp ended with exit code 1

{"message":"Deploy failed.","status":1,"stack":"DeployFailed: Deploy failed.\n    at ALMError (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\salesforce-alm\\dist\\lib\\almError.js:44:19)\n    at MetadataRegistry.initializeMetadataTypeInfos.then.catch.e (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceApiCommand.js:67:35)\n    at tryCatcher (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n    at Promise._settlePromise (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n    at Promise._settlePromise0 (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:612:10)\n    at Promise._settlePromises (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\promise.js:687:18)\n    at Async._drainQueue (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Immediate.Async.drainQueues (C:\\Users\\aalgaat\\AppData\\Local\\sfdx\\client\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)","name":"DeployFailed","result":[{"error":"Unknown"}],"warnings":["All --json output, including on error, is moving to stdout. Use the SFDX_JSON_TO_STDOUT environment variable to move over to the new functionality. This will become the default in version 45."]}
sfdx force:source:deploy --json --loglevel fatal --sourcepath c:\salesforce\DEVQA\force-app\main\default\classes\TriggerAccessRequestTest.cls ended with exit code 1
`

**Comment by esscott1** [comment]
I have the same issue.

**Comment by sfdcvenkata2014** [comment]
sfdx force:source:deploy --sourcepath c:\Users\vvellank\Documents\Testing SFDX Project\vwDev\force-app\main\default\triggers --json --loglevel fatal
{"message":"getaddrinfo ENOTFOUND cs9.salesforce.com cs9.salesforce.com:443","status":1,"stack":"Error: getaddrinfo ENOTFOUND cs9.salesforce.com cs9.salesforce.com:443\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)","name":"Error","warnings":["All --json output, including on error, is moving to stdout. Use the SFDX_JSON_TO_STDOUT environment variable to move over to the new functionality. This will become the default in version 45."]}
18:09:24.189 sfdx force:source:deploy --sourcepath c:\Users\vvellank\Documents\Testing SFDX Project\vwDev\force-app\main\default\triggers --json --loglevel fatal ended with exit code 1

**Comment by Radhikaba** [comment]
I am also facing the same error. It has started happening after I reinstalled my VScode. Any clue on how to resolve this. I even deleted the folder mentioned in the path but then also the same error is coming, even though the path shown in error doesn't even exist anymore.

**Comment by floralan** [comment]
@taalgaard @Radhikaba Could you please check out our latest version of extensions since Deploy/Retrieve commands have changed a lot. We may already solve this issue in the previous implementations.
