### ISSUE TITLE
Commands are split with dividers on VS Code 1.29

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#755]
SFDX commands now have a divider between each one on the menu starting with VS Code version 1.29

![image](https://user-images.githubusercontent.com/282782/48572527-af368a80-e8d7-11e8-9018-f82fe43f7c45.png)

**Comment by lcampos** [comment]
Closing this since it was fixed by Microsoft and ported to vscode 1.29 (https://github.com/Microsoft/vscode/pull/62963)
