### ISSUE TITLE
Time Stamp on SFDX commands in the VSCode Output tab. 

### ISSUE THREAD

**Issue by dannybusiness** [forcedotcom/salesforcedx-vscode#759]
**Is your feature request related to a problem? Please describe.**
I often will be editing multiple files and changing windows between a browser, VSCode and other apps. Sometimes I will have made several different code edits and not know when was the last time I pushed and if the server has the latest version of my code. 

**Describe the solution you'd like**
It would be helpful in the output to have a timestamp for each operation. 

**Describe alternatives you've considered**
I haven't thought of any other alternatives. This isn't critical but a nice to have.

**Comment by lcampos** [comment]
This was delivered in release `44.11.0` of the extensions, thanks for posting the idea @dannybusiness.

**Comment by dannybusiness** [comment]
Thank you! I'm so happy to have this feature generally available.
