### ISSUE TITLE
Set the Duration of a Scratch Org

### ISSUE THREAD

**Issue by jriordan22849** [forcedotcom/salesforcedx-vscode#768]
**Is your feature request related to a problem? Please describe.**
I don't want to be spinning up a scratch org every 7 days. The default scratch org duration in days is 7. I want to be able to configure this so I do not have to reproduce test data within the org every week.

**Describe the solution you'd like**
A configuration in which I can specify the duration in days for the Scratch Org. When creating a Scratch org In the Salesforce Cli, I can specify the duration in days. I would like to have something similar in vscode. A configuration to set the -d flag(durationdays) and is appended to the sfdx force:org:create.

**Describe alternatives you've considered**

**Additional context**

**Comment by lcampos** [comment]
This was delivered in release `44.11.0` of the extensions, thanks for posting this @jriordan22849
