### ISSUE TITLE
Keep Errors in Problem until next Deploy

### ISSUE THREAD

**Issue by JorneVL** [forcedotcom/salesforcedx-vscode#771]
### Summary

When you deploy and receive multiple errors, you must remember them or deploy multiple times because they disappear every time when you type in the file.

### Steps To Reproduce:

1. Save a file with deploy errors
2. Type something in the same file.
3. The errors disappear

### Expected result

The errors should stay until the file closes or until the next deploy

### Actual result

Hide after editing the file

### Additional information

**VS Code Version**: 1.29.1

**SFDX CLI Version**: 44.8.0

**OS and version**: W10

**Comment by ntotten** [comment]
This one might be something we could add as a user preference. The problem with not clearing them is that you don't know what you have addressed (or at least potentially addressed). The way we were looking at is that if you have 5 issues you would go through them and solve them. If we didnt clear them you wouldn't know what you edited.

Let me know more about why you don't like this behavior. We're certainly open to changing it.

**Comment by JorneVL** [comment]
If you have 5 issues, after the first thing you type, they all disappear. So you can't go through them, you need to remember them and then go through. This is something user dependant indeed.

The way I look into this is that the Salesforce version isn't the same as the local if there are problems.
If this is possible, please add a user preference.

There is a related 'bug' now.

1. Save class who references a Custom Label that doesn't exist, deploy.
2. Receive the error and create the label, deploy.
3. Deploy is successful, but the error isn't removed.

**Comment by ntotten** [comment]
I agree with your statement. I am going to change this to a bug and schedule the work.

**Comment by SalesforceBobLightning** [comment]
@ntotten please could we get an update on a fix for this?

**Comment by ntotten** [comment]
It is scheduled, no exact ETA though.

**Comment by SalesforceBobLightning** [comment]
@ntotten this bug combined with the fact we have to deploy the apex code to the Salesforce servers for it to be checked is creating a slow development process. It would be great if this fix could be expedited :)

**Comment by lcampos** [comment]
Fixed as part of version `45.1.0`
