### ISSUE TITLE
BUG - Missing update of static resource after retrieve

### ISSUE THREAD

**Issue by DarkSkull91** [forcedotcom/salesforcedx-vscode#772]
Issue Type: <b>Bug</b>

Hi,

I noticed that the plugin can't work when you try to update through retrieve a Javascript Static Resource. I click on retrieve and I don't see the update.
This is very dangerous if more than one people work on the same resource.

Thanks,
A

Extension version: 44.8.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.66GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ntotten** [comment]
I don't quite understand what the issue is. Could you provide more of a step by step of this issue?

**Comment by DarkSkull91** [comment]
Just do a retrieve of a static resource, say to someone to edit that resource than do the retrieve again. The resource will not be update.

**Comment by ntotten** [comment]
I really need to know a step by step of how you do this. Please provide us something like:

1. Deploy changes to scratch org
2. Edit using Dev Console
3. ...

**Comment by dan9khoa** [comment]
I'm having same issue as this.

1. Using non scratch org
2. Developer A edits a .js (javascript) file and saves the file in VSCode
3. Confirm the change appears in Salesforce website
4. Developer B right-clicks on the same .js file and select "Retrieve Source from Org"
5. Developer B can NOT see the change in the file in VSCode

Our workaround:

1. Developer B deletes .js file in VSCode
2. Developer B does "Retrieve Source from Org" on the .resource-meta.xml
3. The .js file gets re-downloaded and change shows up in VSCode for developer B

Please take a look. Thank you.
