### ISSUE TITLE
Ability to view static resource

### ISSUE THREAD

**Issue by MukundKoirala** [forcedotcom/salesforcedx-vscode#779]
Is there a way I could see all the static resource files in the vs code editor, today just a  .bin file is shown and not the real files in it.

Do we have this limitation today ? Or Do I need to add some extension to support the same. ?

I have seen the same files show up while using Welkins suite, but  it does not show up neither in VScode nor in Eclipse Force.com IDE

**Comment by ntotten** [comment]
If you are using the Salesforce CLI, to retrieve or pull files the resources are automatically expanded. Alternatively, you can convert your source from metadata format to source format. Salesforce Extensions for VS Code only support source format so you can't just open the same folder you opened with Welkins or Force.com IDE directly. See: https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code
