### ISSUE TITLE
I am trying to figure out a way to retrieve or pull an existing specific apex class and component to make some edits from my sandbox to my local machine. Is there a command for that?

### ISSUE THREAD

**Issue by pratima320** [forcedotcom/salesforcedx-vscode#781]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ntotten** [comment]
Unfortunately, we don’t have that command ready yet. We’re working on that functionality now. For now you need to use a manifest (package.xml) to retrieve specific metadata.
