### ISSUE TITLE
Custom Salesforce Templates

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#784]
Today, all templates are stored in the main source for the CLI and they ship with the CLI. This means that there is but a single set of snippets and templates for all developers.

The problem is that it is very common for developers, teams, and companies to have their own custom set of templates. Currently, the only way a deveoper can create custom salesforce templates is to write a tool from scratch - there really is no extensibility of templates in either the CLI or VS Code.

MavensMate actually had a very nice solution to this problem. The default templates for MavensMate were stored in a [github repo](https://github.com/joeferraro/MavensMate-Templates). There was a setting inside of MavensMate where you could point to the Github repo where templates were stored. The default setting was the master repository, but developers and teams could **fork** the main template repo and change a single setting in MavensMate to point to their own fork with their custom templates.

This proposal is to enable the same experience in the CLI and VS Code. Currently, our templates are a plugin that ships with CLI (they are not open source yet). We can extract that plugin into two components - the yeoman tool that executes the templates and the actual template source. We can then enable a setting (for the CLI it would be an environmental variable, for VS Code it would be a setting on the extension) that points to a github repo with the template source.

When a developer wants to customize their own templates they can fork our template source and change the setting to point to their own custom templates.

This would enable developers to create a rich exosystem of templates and share them with others. Currently, there are 115 forks of the MavensMate templates - many of them are owned by companies that have standards for all teams.

**Comment by idanblich** [comment]
Hi @ntotten 
Any update about this ? 🌶

**Comment by xyc** [comment]
Addressed by https://github.com/forcedotcom/salesforcedx-vscode/pull/3563
