### ISSUE TITLE
After setting ""Set Audit Fields upon Record Creation" the cli will pull the wrong setting

### ISSUE THREAD

**Issue by gdoenlen** [forcedotcom/salesforcedx-vscode#797]
### Summary

When you enable the `"Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners" User Permissions` setting under user interface and then pull the change into source it pulls the Name settings file instead of the one pertaining to this setting.

### Steps To Reproduce:

1.  Create a new scratch
2. Settings -> Navigate to User Interface -> User Interface
3. Enable the "Set Audit Fields upon Record Creation" and "Update Records with Inactive Owners" User Permissions checkbox.
4. Click save.
5. Run `sfdx force:source:pull`

You will receive the settings/Name.settings-meta.xml file containing:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<NameSettings xmlns="http://soap.sforce.com/2006/04/metadata">
    <enableMiddleName>true</enableMiddleName>
    <enableNameSuffix>true</enableNameSuffix>
</NameSettings
```

### Expected result

You should receive the settings file that pertains to the Enable Set Audit Fields Upon Creation setting.

### Actual result

You will receive the settings/Name.settings-meta.xml file containing:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<NameSettings xmlns="http://soap.sforce.com/2006/04/metadata">
    <enableMiddleName>true</enableMiddleName>
    <enableNameSuffix>true</enableNameSuffix>
</NameSettings
```
**SFDX CLI Version**:
sfdx-cli/6.42.0 (windows-x64) node-v11.3.0
**OS and version**:
Occurs in both windows 10 and linux (ubuntu budgie 18.04)

**Comment by ntotten** [comment]
I have asked the team about this issue. They have it recorded as a known bug and will be working on fixing it. I don't have a timeline to share though. I am going to close this issue here as it is unrelated to VS Code.
