### ISSUE TITLE
Generate package.xml with option(All components or Specified components)

### ISSUE THREAD

**Issue by k010c1232** [forcedotcom/salesforcedx-vscode#807]
**Problem**
I'm using sfdx plugin when developing salesforce org. This plugin is a good tool for me, but I have a problem when I want to retrieve all meta components or specified components(I can't remember components name). I need to add manually components what I want to retreive components. 

**Solution**
Please make it possible to select all meta components or specified components when generating package.xml.

**Comment by savjain** [comment]
A UI like Mavenmate to visualise all components in the org and select the required components to generate the package.xml would be a great feature.

**Comment by ntotten** [comment]
This will be provided via this feature: https://github.com/forcedotcom/salesforcedx-vscode/issues/688
