### ISSUE TITLE
Execute SOQL Query With Selected Text... doesn't work for queries on multiple lines of file

### ISSUE THREAD

**Issue by boxfoot** [forcedotcom/salesforcedx-vscode#816]
### Summary

"Execute SOQL query with selected text" does not work for multiline queries

### Steps To Reproduce:

1.  Type this in editor:
        `SELECT Id FROM Contact LIMIT 10`
1.  Select it and run "Execute SOQL Query with selected text..."
1. Works as expected
1. Now repeat with this text:

        SELECT Id 
        FROM Contact
        LIMIT 10

### Expected result

Query executes successfully

### Actual result

ERROR at Row:1:Column:XX
unexpected token: '<EOF>'.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.26.0

**SFDX CLI Version**: sfdx-cli/6.43.1 (windows-x64) node-v11.0.0

**OS and version**: Windows 10

**Comment by boxfoot** [comment]
Note, however, that you can do this without VS Code --

Save this as `query.soql`:

        SELECT Id
        FROM Contact
        LIMIT 10

Then run this command: `sfdx force:data:soql:query --query "$(<query.soql)"`

So the SFDX CLI can handle the multiline query, but the VSCode extension is getting confused by the input...

Thanks for looking into this.

**Comment by lcampos** [comment]
@boxfoot this was released today as part of version `44.15.0` of the extensions. Thanks again for the contribution.

**Comment by boxfoot** [comment]
@lcampos thanks for the update, and for making it easy to contribute.
