### ISSUE TITLE
This documentation is not useful to install sfdx on the VSCODE

### ISSUE THREAD

**Issue by pramodht** [forcedotcom/salesforcedx-vscode#828]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by pramodht** [comment]
#749 Please help to resolve this issue..

**Comment by ruthemmanuelle** [comment]
I chatted with Pramodh via internal GChat. The Prerequisites section of https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode had the info that was needed here. I'll reach out to the Lightning Web Components writers about adding info about project creation to https://trailhead.salesforce.com/content/learn/projects/quick-start-lightning-web-components/set-up-visual-studio-code .
