### ISSUE TITLE
Add LogUser Name to Apex debug log entires

### ISSUE THREAD

**Issue by maaaaarco** [forcedotcom/salesforcedx-vscode#834]
**Describe the solution you'd like**
I'd like to see the LogUser Name in the Apex Debug Log entries. 

**Additional context**
Now that we have the possibility to deploy to any Org., is usually the case that many developers are working in the same Org. It is crucial to see who generated the debug log.

**Comment by maaaaarco** [comment]
I'd also like to see the Status of the Debug Log in case I'm searching for a specific Exception

**Comment by lcampos** [comment]
Thanks for the feedback @maaaaarco. Can you clarify where do you want the username to be present ? We are already adding it at the top of each debug log.
![debug_log](https://user-images.githubusercontent.com/1041842/50239698-bee23c80-0377-11e9-8550-0af07baddbd9.png)

**Comment by lcampos** [comment]
Just saw your PR, I see what you mean now. I'll go through the code 👍

**Comment by maaaaarco** [comment]
Thanks, man ;) I just did the CLA and amend the author on a couple of commits... I forgot to config the repo in the beginning... Sorry for that.

**Comment by lcampos** [comment]
This was released as part of `v44.16.0` of the extensions. Thanks for the PR.
