### ISSUE TITLE
UNSUPPORTED_API_VERSION: Retrieving from Sandbox

### ISSUE THREAD

**Issue by borkya** [forcedotcom/salesforcedx-vscode#836]
Using instruction from this guide to setup VS Code with a Sandbox Org.

https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code#getting-started
### Steps To Reproduce:

Created a project
Authorized the Org
When tried to Retrieve metadata from Org using  SFDX: Retrieve Source from Org 
Getting error :
15:14:32.122 sfdx force:source:retrieve --manifest c:\VSCODE\RDev\RDEV1\manifest\package.xml
ERROR:  UNSUPPORTED_API_VERSION: Invalid Api version specified on URL.
15:14:38.163 sfdx force:source:retrieve --manifest c:\VSCODE\RDev\RDEV1\manifest\package.xml ended with exit code 1

Additional Info:
Version details :
sfdc-project.json 
"sourceApiVersion": "44.0"
package.xml
 <version>44.0</version>

Tried using 43.0 and 42.0 as well with same results. 

**VS Code Version**:
![image](https://user-images.githubusercontent.com/9142096/50245885-b0a91600-03a1-11e9-8fe8-0c98451a757a.png)

**SFDX CLI Version**:
44.11.0
**OS and version**:
Windows 10, Version	10.0.17134 Build 17134

**Comment by lcampos** [comment]
Hi @borkya, can you confirm you do not have the pre-release version of the sfdx cli installed by running `sfdx plugins`? The pre-release version of the cli by default uses the next version of the api so you either need to use it for orgs that are already in Spring 19 or set the cli to use api version 44.

**Comment by borkya** [comment]
Hi @lcampos
I followed instructions on the url, https://github.com/forcedotcom/salesforcedx-vscode/wiki/Getting-Started-with-Visual-Studio-Code-for-Salesforce-Developers to install the sfdx cli . the version is 44.11.0 .
1.How can I find if I have pre - release version of the sfdx cli ? I tried running sfdx plugins , but its not a valid command. I tried other commands , none are working for me.
sfdx --version           // CLI version
sfdx plugins             // SalesforceDX plugin version
sfdx force --version     // Salesforce API version used by the CLI 

2. How can I set the cli to use api version to 44 ?

**Comment by vmarasow** [comment]
@borkya you can find the api version by going to the sfdx-project.json in the root of your project directory, it should look something like this: `{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "45.0"
}`
Update the sourceApiVersion to "44.0" to fix the issue.

**Comment by borkya** [comment]
Hi @vmarasow 
I have already tried that before opening the bug, see Steps to reproduce. 

Swapnil

**Comment by BoonPlus** [comment]
I ran into the same error, see below for how I resolved the problem...
**1. Check if you're running the pre-release Cli**
PS C:\Users\BoonPlus\Documents\SFDX Projects\DX> sfdx plugins
salesforcedx 45.0.12 (pre-release)
**2. Downgrade to the latest release**
PS C:\Users\BoonPlus\Documents\SFDX Projects\DX> sfdx plugins:install salesforcedx@latest
Installing plugin salesforcedx...
Installing plugin salesforcedx... Checking for digital signature.
Successfully validated digital signature for salesforcedx.
Finished digital signature check. Installing... done
PS C:\Users\BoonPlus\Documents\SFDX Projects\DX> sfdx plugins
salesforcedx 44.11.0
**3. SFDX: Retrieve Source from Manifest from Org**
Starting SFDX: Retrieve Source from Org

15:04:52.978 sfdx force:source:retrieve --manifest c:\Users\BoonPlus\Documents\SFDX Projects\DX\manifest\package.xml
=== Retrieved Source
FULL NAME....

**Comment by borkya** [comment]
Hi @BoonPlus 

That fixed it , thanks for your help!

**Comment by BoonPlus** [comment]
@borkya Glad that it worked for you.

**Comment by lcampos** [comment]
I'm closing this since the configuration changes addressed the original issue/question.

**Comment by vijaykumar96** [comment]
Hi @BoonPlus 
It worked for me as well 
Thanks.
