### ISSUE TITLE
Missing method completions within object initialization 

### ISSUE THREAD

**Issue by vmarasow** [forcedotcom/salesforcedx-vscode#837]
### Summary

The methods are missing from the code completion drop-down when ctrl-space is clicked from within an object initialization, ex. `new Object(Name= System.)` the subclasses from System show up but the methods don't.
I tested this outside the scope of an object initialization and the methods are showing up in the drop down. 

### Steps To Reproduce:

1.  Define and initialize a new Object, any object.
2.  Within initialization, set a property to the result of a method call, ex. `System.today()`.
3. Use code completion to populate the today() method.

### Expected result

![image](https://user-images.githubusercontent.com/2812195/50449723-0e37e800-08f7-11e9-80ba-de959dfb12c8.png)

### Actual result

![image](https://user-images.githubusercontent.com/2812195/50449762-49d2b200-08f7-11e9-90b8-cf793a11c88d.png)

### Additional information

**VS Code Version**: 1.30.1

**SFDX CLI Version**: sfdx-cli/6.44.0-dead729fb5 (windows-x64) node-v8.9.4

**OS and version**: Windows 10

**Comment by ruthemmanuelle** [comment]
Hi @vmarasow . Can you check out the "Enable Code Smartness for SObjects" section of this documentation and see if it solves your problem? https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-apex

**Comment by vmarasow** [comment]
I tried that and it didn't fix this issue

**Comment by allileong** [comment]
Hi @vmarasow, thanks for bringing this to our attention. I was able to reproduce this locally, and it seems that the special syntax available for sobject initialization is an edge case that is not currently supported by our  language server. A new work item has been filed to implement support for this case.
