### ISSUE TITLE
Getting error requirePackage is not a function

### ISSUE THREAD

**Issue by tusharBM** [forcedotcom/salesforcedx-vscode#840]
I'm recently started getting this error. This all started when I restart my pc. I'm not able to use LWC and many other commands,

Error parsing plugin C:\Users\\AppData\Local\sfdx\plugins\node_modules\salesforcedx
 !    require(...).requirePackage is not a function

I'm on windows 10 with latest CLI

**Comment by vazexqi** [comment]
@tusharBM - This seems to be an issue with the Salesforce CLI potentially getting corrupted from the restart.

Could you try *reinstalling* the Salesforce CLi and any extensions that you have? 

Also, if the issue persists after that, could you tell me the output of the following:

* `sfdx version`
* `sfdx plugins`

**Comment by tusharBM** [comment]
@vazexqi fresh restart solves the problem for now. Thanks
