### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rajesh-k** [forcedotcom/salesforcedx-vscode#841]
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `44.11.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/rajeshkr/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by vazexqi** [comment]
Per the instructions, could you be sure to attach `Users/rajeshkr/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` after ensuring that it doesn't contain any sensitive information.

**Comment by rajesh-k** [comment]
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2717707/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)
File attached.

**Comment by ntotten** [comment]
Duplicate of #641

**Comment by smaddox-sf** [comment]
Duplicate #1149
