### ISSUE TITLE
Ability to retrieve specific object components

### ISSUE THREAD

**Issue by sdhoddusamy** [forcedotcom/salesforcedx-vscode#847]
**Is your feature request related to a problem? Please describe.**
Its annoying that I can't specify what I want to retrieve within an object (eg: specific fields, web links, etc)

**Describe the solution you'd like**
I would like to be able to choose specific components within each object to retrieve from the org.

**Comment by sdhoddusamy** [comment]
Just figured everything can be specified directly in package.xml

**Comment by ntotten** [comment]
Thanks for the update. We do have more features coming to make this scenario easier.
