### ISSUE TITLE
ts_types_1.definiteEntriesOf is not a function

### ISSUE THREAD

**Issue by TonyRenHK** [forcedotcom/salesforcedx-vscode#848]
### Summary

Got following error 

1) I want to create Scratch Orgs

 sfdx force:org:create -s -f config/project-scratch-def.json -a GeoAppScratch

2) but got following error:

ts_types_1.definiteEntriesOf is not a function.

**SFDX CLI Version**:
$ sfdx force
** v44.0**

**OS and version**:
$ sfdx --version
sfdx-cli/6.44.0-dead729fb5 (windows-x64) node-v8.9.4

**Comment by brpowell** [comment]
Hi @TonyRenHK. Do you get the same error when trying to run the scratch org create command in a different sfdx project folder?

**Comment by Raspikabek** [comment]
I've been getting this error in Windows 10, in different project folders, new projects and projects from github. Connected to a DevHub org with Dev Hub enabled, v44.

**Solved** uninstalling Salesforce CLI 100%, following this steps: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

Make sure you remove everything. Once Salesforce CLI is uninstalled, try any command (sfdx -h) and make sure your machine doesn't recognise the 'sfdx' command. 

Restart your PC and install again the last version available for your machine.
