### ISSUE TITLE
Unable to run test classes: command 'sfdx.force.test.view.run' not found

### ISSUE THREAD

**Issue by chelseastrong** [forcedotcom/salesforcedx-vscode#849]
### Summary

When trying to use the integrated test side bar, no tests are being displayed. When clicking on "Run Tests" an error message is displayed saying "command 'sfdx.force.test.view.run' not found". When clicking on "refresh" an error message is displayed saying "command 'sfdx.force.test.view.refresh' not found".
Also, test classes do not show the "run test" commands.

### Steps To Reproduce:

1.  Open project in VSCode and open a test class.
1. Open the Test side bar and there is text that says "There is no data provider registered that can provide view data."
1. Click on the "Run Tests" button and error comes up.

### Expected result

Test class should have run.

### Actual result

Nothing happened, only received error message: command 'sfdx.force.test.view.run' not found

### Additional information

Refresh button does not work either. When clicking that button there is the error: command 'sfdx.force.test.view.refresh' not found

![image](https://user-images.githubusercontent.com/46440967/50759704-9765ed80-121a-11e9-8fe2-d72c3b70e8af.png)

**VS Code Version**: 1.30.1

**SFDX CLI Version**: 44.11.0

**OS and version**: Windows 10

**Comment by brpowell** [comment]
Hi chelseastrong. The symptoms sound like the extension might be failing to activate, do you have Java 8 installed? If you do and you're still running into the issue, you may have to specify the Java runtime path with the salesforcedx-vscode-apex.java.home in your vscode settings.

**Comment by chelseastrong** [comment]
Specifying the path did the trick, thank you!
