### ISSUE TITLE
Unexpected Apex syntax errors for valid apex code

### ISSUE THREAD

**Issue by jonathanrico** [forcedotcom/salesforcedx-vscode#867]
### Summary

I'm getting syntax errors for the following valid Apex class:

```
public with sharing class TrustInstanceStatusService {

    @InvocableMethod(label='Get Instance Status Summary' description='Get status summary for the specified instance')
    public static List<String> getInstanceStatus(List<String> instance) {
        List<String> result = new List<String>();
        for(String instanceName : instance){
            TrustInstanceStatusResult trustStatsResult = TrustAPI.getInstanceStatus(instanceName);
            if(trustStatsResult == null){ continue; }
            result.add(trustStatsResult.getSummary());
        }
        return result;
    }

}
```
This class seems valid and i'm able to deploy without any errors but VS code reports a problem and this class is highlighted in the sidebar.

### Steps To Reproduce:

1.  Create an apex class with the code sample provided above
1.  You'll see the error in the code editor.

### Expected result

No errors should be reported as this is a valid apex class

### Actual result

There is a syntax problem reported by the extension

### Additional information

![screen shot 2019-01-13 at 2 35 01 pm](https://user-images.githubusercontent.com/4454509/51091522-6e74b980-1740-11e9-89f1-8f3e951d5c9b.png)

**VS Code Version**:

1.30.2 (1.30.2)

**SFDX CLI Version**:

sfdx-cli/6.48.0-bfccc40118 (darwin-x64) node-v8.9.4

**OS and version**:

macOS Mojave 10.14.2

**Comment by praksb** [comment]
@jonathanrico Do you see this error consistently? Does it go away when you edit the file or restart the extension?
