### ISSUE TITLE
Create defaultTokens.tokens using SFDX and VS Code

### ISSUE THREAD

**Issue by SalesforceBobLightning** [forcedotcom/salesforcedx-vscode#869]
It would be great if the SFDX command line and VS Code extension supported the creation of tokens files.

Is this on the roadmap?

**Comment by lcampos** [comment]
Hi @SalesforceBobLightning , could you clarify what you mean by this. Are you talking about tokens used by lightning components or is this about tokens used for syntax highlighting ?

**Comment by SalesforceBobLightning** [comment]
I was recently unable to use [Salesforce Lightning Design System tokens](https://www.lightningdesignsystem.com/design-tokens/) and discovered that my project needed a `defaultTokens` folder in the `aura` folder with a `defaultTokens.tokens` file and `defaultTokens.tokens-meta.xml` to enable the use of design tokens.

As a user of VS Code and the SFDX VS Code Extension, I looked at the different commands available and found there wasn't a command for creating a `.tokens` file.

Therefore, I was wondering when SFDX and the SFDX VS Code Extension will support the creation of tokens files?

**Comment by lcampos** [comment]
I see. I'm not aware of us working on anything related to Lightning Design System soon but we're about to define our priorities for the following couple of months.
cc @ntotten

**Comment by SalesforceBobLightning** [comment]
Related links:

- [Using Standard Design Tokens](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/tokens_bundles.htm)
- [Create a Tokens Bundle](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/tokens_create_bundle.htm)

**Comment by SalesforceBobLightning** [comment]
Is that Closed implemented? or Closed ignored?

**Comment by ntotten** [comment]
I will pass it along to the lighting tooling team. I am not sure if this is something we will do any time soon or ever though.
