### ISSUE TITLE
CLI commands executed from VS Code using --json

### ISSUE THREAD

**Issue by simonfoden** [forcedotcom/salesforcedx-vscode#871]
CLI commands issued from VS Code appear to be using the --json parameter giving less readable results in the Output window. This change appears to have been introduced a few releases back. 

Example : SFDX: Deploy This Source to Org  
sfdx force:source:deploy --sourcepath CLASSNAME&PATH --json --loglevel fatal

Please revert back to the previous behaviour by removing --json or failing that provide a setting option to switch this on or off. Thanks.

**Comment by ntotten** [comment]
Unfortunately, we can't simply revert the change directly because we are using the output of the JSON to drive other UI in VS Code. We will be fixing this though very soon.

**Comment by ntotten** [comment]
We are fixing this in a different way.

**Comment by AndrewRayCode** [comment]
Why is log level fatal set? I don't get any results back at all. I have to run the command in a local shell without the loglevel to see my actual deployment error. Why do you lock developers into a format that they can't use? Or is there a way to configure this I'm not aware of? I don't see any relevant settings containing the word "deploy"

**Comment by lcampos** [comment]
@AndrewRayCode I think you're running into the CLI issue mentioned in issue #1411. We're currently working on the fix and will update that thread once it's released.

**Comment by tnoonan-salesforce** [comment]
This issue is fixed in 7.12.3 of the toolbelt. Just run sfdx update...

**Comment by jafer143** [comment]
Hi All,
I have been facing this issue while deploying from source to org.
Can anyone help me to fix this issue?
