### ISSUE TITLE
Test Panel should use start icon

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#874]
The test panel should use the VS Code start icon: https://github.com/Microsoft/vscode/blob/314cc521d8ce0c55773850ef520095afde33a62c/src/vs/workbench/parts/debug/browser/media/start.svg

Right now the icon is an incorrectly sized blue icon. The icon should be the green VS Code icon and not change color based on the status of the tests.

**Comment by lcampos** [comment]
FIxed as part of version `45.1.0`
