### ISSUE TITLE
In VSCode, Adding new component (i.e. SFDX: Create Visualforce Page) not automatically adding to package.xml

### ISSUE THREAD

**Issue by JohnMcCarvill** [forcedotcom/salesforcedx-vscode#884]
Adding new components from the project menu should add to the package.xml.  It is not practical to load all metadata for typical projects.  It would be better to always specify components in package.xml and have VSCode add or remove from the package.xml as components are added or removed.

This behavior exists in Eclipse force.com IDE and greatly simplifies managing and deploying discreet project components.

**Comment by lcampos** [comment]
Thanks for the feedback @JohnMcCarvill, I'm closing this since this scenario should be covered by the Org Browser & Working Sets feature (specs in #862 ).
