### ISSUE TITLE
Migrate from Mavens Mate to VS Code link is broken

### ISSUE THREAD

**Issue by sfdcnoob** [forcedotcom/salesforcedx-vscode#888]
Under [Migration Guides](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migration-Guides), Migrate from **Mavens Mate to VS Code** link is broken and it takes to Wiki page again. Thanks

**Comment by ntotten** [comment]
The guide hasn't been written yet. Apologies for the confusion.
