### ISSUE TITLE
Incorrect local variable display

### ISSUE THREAD

**Issue by bolaurent** [forcedotcom/salesforcedx-vscode#898]
### Summary

_Replay debugger displays incorrect value for local variable_.

### Steps To Reproduce:

1. Enable debug log.
1.  Run the following test.
1.  Fetch log.
1.  Launch Apex Replay Debugger.
1.  Set a breakpoint at line 136.
1.  Press Continue.
1.  Examine local variables. oppIds should contain one Id. Instead it is empty.

### Expected result

_oppIds should contain one Id, see log system.debug output below_.

### Actual result

_oppIds is displayed as empty_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version 1.30.2 (1.30.2)**:

**SFDX CLI Version**:
Bo-MBP: opp-team-notification % sfdx version
sfdx-cli/6.49.0-8edc6e0f5d (darwin-x64) node-v8.9.4

**OS and version**:
OSX 10.14.2

**Comment by bolaurent** [comment]
<img width="1017" alt="debugger" src="https://user-images.githubusercontent.com/1839790/51701521-7812e280-1fc6-11e9-8774-aa795606acb3.png">

**Comment by bolaurent** [comment]
[07L0E00000DWX9bUAH_20190124103622.log](https://github.com/forcedotcom/salesforcedx-vscode/files/2793143/07L0E00000DWX9bUAH_20190124103622.log)

**Comment by bolaurent** [comment]
Code:

    @istest private static void apex_replay_debugger_bug() {
        Set<Id> oppIds = new Set<Id>();
        Id opportunityId = '0060E00000AfCRxQAN';
        oppIds.add(opportunityId);

        system.debug(opportunityId);
        system.debug(oppIds);
    }

**Comment by bolaurent** [comment]
Relevant part of log:

    10:36:27.789 (5790779956)|USER_DEBUG|[136]|DEBUG|0060E00000AfCRxQAN
    10:36:27.789 (5790789391)|SYSTEM_METHOD_EXIT|[136]|System.debug(ANY)
    10:36:27.789 (5790795397)|STATEMENT_EXECUTE|[137]
    10:36:27.789 (5790803435)|SYSTEM_METHOD_ENTRY|[137]|System.debug(ANY)
    10:36:27.789 (5790820495)|USER_DEBUG|[137]|DEBUG|{0060E00000AfCRxQAN}

**Comment by vazexqi** [comment]
Due to amount of information that we capture in the logs, this is working as designed.
To see the output of the set, you need to use a HeapDump feature.

@DatGuyJonathan and I illustrated this case at our Dreamforce '18 talk. See https://www.youtube.com/watch?v=JivDTfYvZ50 where I explain the limitation and how we get around it.

**Comment by bolaurent** [comment]
Thank you @vazexqi
