### ISSUE TITLE
command 'extension.replay-debugger.getLogFileName' not found

### ISSUE THREAD

**Issue by andykallio** [forcedotcom/salesforcedx-vscode#903]
### Summary

_I am developing against a sandbox and I have downloaded a log that was created with the replay debugger turned on. When I try to start the replay debugger by right clicking on a line within the log nothing happens. Nothing is printed in the Output either. I also tried clicking the 'play' button at the top of the debug window the 'replay debugger' selected and it is upon doing this that I get the following error as a popup and still nothing in the output: `command extension.replay-debugger.getLogFileName not found`_.

Here is my launch file

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Apex Replay Debugger",
            "type": "apex-replay",
            "request": "launch",
            "logFile": "${command:AskForLogFileName}",
            "stopOnEntry": true,
            "trace": true
        }
    ]    

    
}
```

**VS Code Version**:
1.30.2
**SFDX CLI Version**:
sfdx-cli/6.50.0-9817aece8a (darwin-x64) node-v8.9.4
**OS and version**:
mac  10.14

**Comment by Brian-Triplett** [comment]
I'm getting this issue as well.

**Comment by ntotten** [comment]
After discussing this, it seems the issue is that the Replay debugger extension may not have been activated on your machine. Can you confirm that the Apex Replay Debugger extension is installed and enabled?

**Comment by andykallio** [comment]
Thanks for this feedback.  I can see 'Apex Replay Debugger' in my list of enabled extensions in vscode. Is that enough confirmation or is there something else I should do?
