### ISSUE TITLE
GOTO definition on SObject should take you to the xml file

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#919]
**Is your feature request related to a problem? Please describe.**
Navigating to a particular object/field `.xml` definition requires lots of folder structure traversing.  

**Describe the solution you'd like**

`goto-definition` & `peak-definition` would be perfect for quickly navigating to object/field definitions from apex code.

- if you right click on an SObject and select `goto definition`, it should take you to that objects .xml file.  (eg `objects/Account/Account.object-meta.xml`)
- if you right click on an object field and select `goto definition`, it should take you to that fields `.xml` file (eg `objects/Account/fields/AccountNumber.field-meta.xml`)

**Comment by AnanyaJha** [comment]
Hi @ChuckJonas - doing a refresh of our older feature requests and wanted to see if this is still something you're looking for? Thanks!
