### ISSUE TITLE
Using /**/ comment without space lead to incorrect color highlighting

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/salesforcedx-vscode#921]
### Summary

Using /**/ comment without space lead to incorrect color highlighting

### Steps To Reproduce:

1.  Create an Apex Class
2.  Somewhere, add a comment like /****/

### Expected result

Commented line is green, other lines below are correctly highlighted

### Actual result

All code below is green

### Additional information

**VS Code Version**:
![comment](https://user-images.githubusercontent.com/2465122/42585518-23818bf2-8536-11e8-9a88-018b2ef4ba41.png)

**Work Item**: [W-5294674](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005VFbNIAW/view)

**Comment by DallasDeuce** [comment]
Hi @lcampos just checking to see if an update on this one, and if target release for fix?  One of our developers just noticed same thing.  Thanks!

CC: @ntotten

**Comment by lcampos** [comment]
This got fixed in version `46.13.0` of the extensions.
