### ISSUE TITLE
When viewing an Apex Test Class and clicking the inline Run Test link the output shows an error saying that <Namespace>.<Namespace> is not a valid class

### ISSUE THREAD

**Issue by manwe651** [forcedotcom/salesforcedx-vscode#923]
### Summary

When viewing an Apex Test Class and clicking the inline Run Test link the output shows an error saying that <Namespace>.<Namespace> is not a valid class.

![image](https://user-images.githubusercontent.com/5975059/42412717-36edfa70-81d7-11e8-8a08-163ccd616b38.png)

![image](https://user-images.githubusercontent.com/5975059/42412708-07ee0864-81d7-11e8-8381-81d578c372e5.png)

### Steps To Reproduce:

Have a namespaced dx project and click Run All Tests on a class.

### Expected result

It should successfully run the tests for that class.

### Actual result

It has an error

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:  Version 1.24.1 (1.24.1)

**SFDX CLI Version**: sfdx-cli/6.23.0-40d6abfa8d (darwin-x64) node-v8.9.4

**OS and version**: MacOSX

**Internal Work Item**: [W-5171332](https://gus.my.salesforce.com/a07B0000005PDf6IAG)

**Comment by robertbwatson** [comment]
My team is also experiencing this issue. We sometimes create non-namespaced orgs - it's only happening in that environment for us. The command is assuming the org is namespaced and adding the namespace to the class name when it is not. For our namespaced orgs, these run successfully. @shillem's workaround works for us.

(I added these details as a comment in the linked WI as well)

**Comment by Julian88Tex** [comment]
@robertbwatson same here. The only workaround I see now is to delete the namespace from the example dx command presented in output:

`19:59:37.362 sfdx force:apex:test:run --tests <namespace>.<classyName>.<testname> --resultformat human --outputdir /Users/julian.joseph/Documents/Repos/spc-integration/.sfdx/tools/testresults/apex --loglevel error
ERROR running force:apex:test:run:  Unable to invoke any tests. Ensure the tests are loaded into the org or valid inputs are supplied. This class name's value is invalid: ccsi01.DataLakeApiService_TEST. Provide the name of an Apex class that has test methods.`

Change: `sfdx force:apex:test:run --tests <namespace>.<classyName>.<testname> --resultformat human --outputdir /Users/julian.joseph/Documents/Repos/spc-integration/.sfdx/tools/testresults/apex --loglevel error`

to

`sfdx force:apex:test:run --tests <classyName>.<testname> --resultformat human --outputdir /Users/julian.joseph/Documents/Repos/spc-integration/.sfdx/tools/testresults/apex --loglevel error`

and rerun in terminal

**Comment by rodrigoreyes79** [comment]
As of today, this issue is still happening. Thanks for the workarounds.

**Comment by renatoliveira** [comment]
Created an org with a namespace today and I'm now facing this issue as well. It is really weird, it seems the extension is trying to add the namespace twice...

>This class name's value is invalid: <namespace>.<namespace>. Provide the name of an Apex class that has test methods.

**Comment by aaronmorris** [comment]
I'm also experiencing this issue, but not on all test methods.  Some of them still continue to work.

**Comment by aaronmorris** [comment]
A workaround that looks to be working for me is:
In the settings there is a new feature that needs to be disabled and that appears to have fixed it for me.

In Settings: Salesforcedx-vscode-core > Experimental: Use Apex Library
Disable - Use Apex Library for Apex CLI Commands
![Screen Shot 2021-01-19 at 11 21 16 AM](https://user-images.githubusercontent.com/4790725/105082458-7448b800-5a48-11eb-9a84-4447e711880f.png)

**Comment by ertanosf** [comment]
I could fix it after deploying test classes to my org.

**Comment by lcampos** [comment]
Closing since this was fixed in release 51.2.0 of the Salesforce Extensions for VSCode. Thanks for providing feedback.

**Comment by jerhewet** [comment]
Apparently broken again in version 51.10.0, and there is no "Use Apex Library for Apex CLI commands" option anywhere in the VSCode settings.

**Comment by rodrigoreyes79** [comment]
It looks as if this is happening again on v52.6.0.

![image](https://user-images.githubusercontent.com/3924426/127211209-569c6f59-6d93-4df0-810e-4520e4b79348.png)

**Comment by galmeidasilva** [comment]
I tried to run Apex tests in the same way as reported and got the same error (v7.110.0)

![image](https://user-images.githubusercontent.com/84526652/128767006-9b7899b3-0d3b-4116-b77a-26b35ab842a7.png)

**Comment by polkhovsky** [comment]
This issue should be reopened. I am receiving the same error.

**Comment by BobHatcher** [comment]
I'm with @polkhovsky .. +1 for reopening. I am unable to run tests.

**Comment by IndustrialDonut** [comment]
+1 to reopen, I am getting exactly the same error as galmeidasilva posted a screenshot of.

**Comment by Sunbrith** [comment]
+1 
![image](https://user-images.githubusercontent.com/77020569/130505040-f089fe8f-136d-40af-98ee-b2198dc21937.png)

**Comment by trevshum20** [comment]
My issue was I was running my tests without having deployed any of my classes to my org first. Try running "Deploy Source to Org" on all the classes you are testing and the classes you are using to test.

**Comment by randi274** [comment]
@trevshum20 thanks for reporting - can you log that as a separate issue? Sounds like we might have too large of a catch somewhere that needs to be cleaned up. 

Anybody else still seeing the original issue on this one? 🤚

**Comment by AVISHEKHAR** [comment]
Did we get any final result to resolve this issue?
![image](https://user-images.githubusercontent.com/53835065/183280361-0c1a4bf8-cb1c-4372-b60b-0fa1c12e4130.png)

**Comment by Dorgaldir** [comment]
I'm running into this issue when trying to run tests in a namespaced org while creating a 2GP package.
<img width="575" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/6475713/ea90ee16-e783-435e-9ebb-9e11a9691b20">

Can't seem to find a workaround for this problem and it prevents me from creating a package version with code coverage. Any tips?

**Comment by NoahCardoza** [comment]
I'm new to SFDX and my issue was that I had **not deployed my test yet**. 

Once I deployed it I was then able to run it, which makes total sense in hindsight. When I saw that button, it wasn't clear it needed to be deployed, and I thought I could "test the test" before I deployed it.
