### ISSUE TITLE
Make a copy of the production instance's settings to a scratch org definition file.

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/salesforcedx-vscode#925]
By far, the most frustrating thing I've faced with DX up to date is that there's no method to automatically retrieve the org definition of the production environment. It would be really awesome if we could get the exact same definition as the production instance, so we avoid the creation of scratch orgs with missing features.

For example, if our org has quotes enabled, then there would be a command to automatically retrieve the production settings, and it would contain the `IsQuoteEnabled` setting.

A command like `sfdx force:org:getdefinition:`, or something like that. 😃

**Comment by ntotten** [comment]
I have passed this feature request to the proper team. Closing here as it is unrelated to VS Code.
