### ISSUE TITLE
Overzealous SLDS warnings

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/salesforcedx-vscode#926]
**Is your feature request related to a problem? Please describe.**
I use a static resource with an earlier version of SLDS than the latest release. I get loads of warnings on every lightning component as the code extensions assume I’m using the latest and warn about deprecated styles etc

**Describe the solution you'd like**
A simple way to turn off this checking.

**Describe alternatives you've considered**
I just ignore them at the moment, but sometimes there are real issues buried in there.

**Additional context**

**Comment by ntotten** [comment]
We have removed this implementation of SLDS. A newer, improved one will be released soon.
