### ISSUE TITLE
'Invoke Apex Tests' VS error message states that failed to run when tests have actually failed instead

### ISSUE THREAD

**Issue by frackham** [forcedotcom/salesforcedx-vscode#931]
### Summary
When running apex tests through the VS code command palette, any failing tests will throw a misleading error message.

### Steps To Reproduce:
1. Run a test class (Palette, Invoke Apex Tests) with at least 1 failing test.
1. Review error message

### Expected result
'Successfully ran with failing tests'  (warning symbol?)

### Actual result
'SFDX: Invoke Apex Tests... failed to run'

Output shows 'sfdx force:apex:test:run --resultformat human --loglevel error ended with exit code 100'

### Additional information
![image](https://user-images.githubusercontent.com/2105204/39237291-f34a88a8-4872-11e8-8fb3-0d242f53952c.png)

**VS Code Version**:
1.22.2
SF Extensions: 42.12.0

**SFDX CLI Version**:
v42.0

**OS and version**:
Windows 10

**Internal Work Item**: [W-5171290](https://gus.my.salesforce.com/a07B0000005PDdjIAG)

**Comment by lcampos** [comment]
This was addressed by PR #683

**Comment by raghujayjunk** [comment]
I am running this command: sfdx force:apex:test:run -l RunLocalTests -d Release\Test_Results -u %DEP_USER% --resultformat junit --codecoverage -w 200

sfdx version: 7.23.1-ced0ec4940.

I get an exit code of 100.

Can you please help?

**Comment by banderson5144** [comment]
I am getting this issue as well:

sfdx-cli/7.74.1 win32-x64 node-v10.15.3

VS Code 1.49.2
