### ISSUE TITLE
Working with Static Resources

### ISSUE THREAD

**Issue by islimane** [forcedotcom/salesforcedx-vscode#933]
### Summary
Hello, I wonder if there is way to open and work with static resources.
Let's say we have a zip static resource with the following structure:
--> my_static_resource
------->css
-----------> my_styles.css
-------> js
-----------> my_app.js
How can I see the actual files and work with them?

### Steps To Reproduce:
1. Create a static resource with the structure above.
2. Retrieve the static resource into your project.
3. Try opening the static resource.

### Expected result
Unziped static resource.

### Actual result
Message: "The file will not be displayed in the editor because it is either binary, very large or uses an unsupported text encoding."

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.21.1

**SFDX CLI Version**: 42.7.0

**OS and version**: El Capitan 10.11.6

**Comment by ntotten** [comment]
VS code supports static resources when you are using source format. It sounds like you are trying to open the project with metadata format which is not supported. See: https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/source-format
