### ISSUE TITLE
Go To Definition only works for very limited use cases

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#937]
### Summary
I would expect to be able to use go-to-definition/peak definition on pretty much any symbol (Class Type, class instance methods, variable).  However, as far as I can tell it only works on top level class properties and methods when you are inside of the class file.

### Steps To Reproduce:
1: Class Types don't work
- Find a reference to a class type eg `MyClass myClassInstance = new MyClass();`
- Right click on `MyClass` then select "go-to definition"

2: Instance methods don't work
- Find a method call on an instance method. EG: `myClassInstance.fooBar()`
- Right click on `fooBar` then select "go-to definition"

3: Static references don't work
- Find a static property or method reference call on an instance method. EG: `MyClass.MY_CONSTANT`
- Right click on `MY_CONSTANT` then select "go-to definition"

### Expected result
1: The `MyClass` file would be opened and the cursor would be put on the class declaration.

2: The `MyClass` file would be opened and the cursor taken to the declaration of the `fooBar` method

3: The `MyClass` file would be opened and the cursor taken to the declaration of `MY_CONSTANT`

### Actual result
No Definition found

### Additional information

**VS Code Version**:
All
**SFDX CLI Version**:
All
**OS and version**:
All

**Comment by tet3** [comment]
@vazexqi @ntotten Would also like to see this work for `controller` and `extensions` attributes of VF Pages & Components, and Aura Components. And if they're not yet supported, then LWC-to-Apex calls, at least from the `import` line, if not other references.

**Comment by diyer** [comment]
Verified all the use cases filed originally in the issue work. Please file a new issue if something does not work still.
cc: @AnanyaJha
