### ISSUE TITLE
Does not show even basic semantic errors until source is pushed to server

### ISSUE THREAD

**Issue by sfdcale** [forcedotcom/salesforcedx-vscode#939]
### Summary
If there is any invalid syntax in the code, it does not show errors on the save but shows errors only when I push the code to the server, using the command "sfdx force:source:push". I was expecting plugin to show at least basic syntax errors on local save.

### Steps To Reproduce:
1. Have VScode setup with latest sfdx plugins and pointing to a scratch org.
2. Open any Visualforce and add an invalid attribute. Please see the below screenshot. 

### Expected result
I was expecting that it would show some kind of alert/error to the user showing the invalid syntax.

### Actual result
File saved successfully and no error shown to the user.

### Additional information
![selection_228](https://user-images.githubusercontent.com/11079913/32177462-cc61d4fa-bd60-11e7-996b-ee85af920795.png)

**VS Code Version**:
Version 1.17.2

**SFDX CLI Version**:
sfdx-cli/6.0.13-a52f73c (linux-x64) node-v8.6.0

**OS and version**:
Ubuntu 16.04 LTS

**Comment by jjTorrent** [comment]
Any updates on roadmap for this now, @ntotten? bump!

**Comment by ntotten** [comment]
We will be releasing a significant update to the Aura tooling in the next few weeks that will help with some of this. However, we don't have immediate plans on improvements to Visualforce tooling at this time.

**Comment by AnanyaJha** [comment]
Hi @sfdcale , thanks for sharing this feedback. At this point, we have no further improvements planned for Visualforce tooling support. Please open a new issue if you're looking for additional support - thanks!
