### ISSUE TITLE
Org Picker UI

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#944]
A developer will be working with two different orgs for development. This means that they will have to switch the org they are running commands against. In the CLI this is already easily done by specifying the `targetUsername` argument, however, there is no such capability in VS Code. As such, we should allow a developer to specify a default org to run commands against, similar to the above proposal about default package directory.

The bottom toolbar would show the currently selected org that operations are performed against.

![image](https://user-images.githubusercontent.com/282782/45221383-371c6a80-b27f-11e8-97e6-1a9118bcd586.png)

Clicking on the org name would bring up a selection dialog that would present the user with the following options:

* Authorize new Org
* Create new Scratch Org
* List of the rest of the authorized orgs...

![image](https://user-images.githubusercontent.com/282782/45234855-f59eb600-b2a4-11e8-8b92-8ae04b7aa23d.png)

They could then either select an org they have already authorized or authorize a new org or create a scratch org. The results of all of these operations would change the currently selected org.

Similar to the default package directory setting for VS Code, we would not want to store this in a file that is stored in source control (i.e. sfdx-project.json). This is a setting specific to the local developer and as such, the currently selected org would be stored in the .sfdx directory.

**VS Code Command**
In addition to allowing users to set the current org via UI we should expose the same functionality via the command “SFDX: Set Default Org”

**Doc Impact**
Current functionality opens the org in the browser. Make sure to alert the user of the new functionality & properly deprecate/remove current behavior from docs.

**Comment by lcampos** [comment]
Delivered in version`45.1.0`

**Comment by eltoroit** [comment]
So is there a way to easily open the scratch org? I think this is a loss of functionality. What about putting back the opening of an org, possibly with a right click?

**Comment by eltoroit** [comment]
So is there a way to easily open the scratch org?

I think this is a loss of functionality. Right now, getting a list of the orgs to display in the command palette takes few seconds (>5) so it looks like the button is broken. I keep clicking the button and nothing happens, few seconds later, a whole buch of menus show up on the command palette. I do not change Orgs often, but I do have to open them frequently so for me this is loss of behaviour.

I know it's hard to make everybody happy, but I think we can get to a happy middle. Some ideas to
put back the opening of an org could be...

- Possibly with a right click / Shift + click?

- Have a pop-up sub-menu that pops up and allows you to select between opening or changing the default org.

- Can we have a small button next to the existing one to open the Org? I believe there is a new icon for the connector, so what if clicking on the name opens the org but clicking on the connector allows you to change the default org?

- Could we at least have a setting that allows you to configure if you want to open or change the Org?

**Comment by ntotten** [comment]
The delay is something we are fixing.

The ability to open an org is still there. The icon is the same. We just removed the text. See: https://twitter.com/ch_sz_knapp/status/1095600887094018048?s=21

**Comment by eltoroit** [comment]
Thanks @ntotten
