### ISSUE TITLE
SOQL Query Results View

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/salesforcedx-vscode#974]
Today, in VS Code you can execute SOQL queries against selected text. The results of the query are shown in the integrated terminal. We could improve upon this experience by providing a more powerful UI for viewing query results.

The results view should also allow exporting of results in CSV and JSON format.

This UI would be similar (or identical) to what the MS SQL team has built for SQL Server.

![mssql-demo 1](https://user-images.githubusercontent.com/282782/45228089-350ed780-b290-11e8-896b-e2fb56250286.gif)

**Comment by matteobosc** [comment]
This would be a very great feature when working with large queries. Thanks!

**Comment by sgoley** [comment]
In the interim is it at least possible to set the `--resultformat` flag and possibly a result destination? 
Currently possible in the sfdx command line like:

get results:
`sfdx force:data:soql:query --query "SELECT Id, Name FROM Account" --resultformat csv`

get results and write to csv:
`sfdx force:data:soql:query --query "SELECT Id, Name FROM Account" --resultformat csv > output.csv`

**Comment by smaddox-sf** [comment]
A new SOQL Builder tool is now in beta.  Download the extension to try it out https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-soql
