### ISSUE TITLE
Preview Button for Lightning Apps / VF Pages

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/salesforcedx-vscode#983]
**Is your feature request related to a problem? Please describe.**
When im developing a new component I normally want to preview it, now I have to memorize the URL, which is normally quite simple /namespace/appName.app, but it would be great to have a button that does this job for me

**Describe the solution you'd like**
I would like a button in the IDE to open the application/visualforce I'm viewing in the default org, just like the developer console and the force code plugin has

**Describe alternatives you've considered**
N/A

**Additional context**
Maybe this could also apply to, open for example an object setup panel, or any other metadata type, or the creation/edit/view of records for that object

**Comment by idanblich** [comment]
inspired by @douglascayers [ great post](https://douglascayers.com/2019/02/17/develop-against-any-org-with-visual-studio-code-tasks/) i was manage to accomplish opening of a VF page using code tasks feature.
Here is the code for the tasks.json file
```
    "version": "2.0.0",
    "tasks": [
        {
            "label": "SFDX: Open Path ",
            "type": "shell",
            "command": "sfdx",
            "args": [
                "force:org:open",
                "--path",
                "/apex/${fileBasenameNoExtension}",
            ],
            "group": "build",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "problemMatcher": []
        }
    ]
}
```
