### ISSUE TITLE
Go To Symbol not working

### ISSUE THREAD

**Issue by melissajhansen** [forcedotcom/salesforcedx-vscode#990]
### Summary

"Go to Symbol in File" not working in Apex classes

### Steps To Reproduce:

1.  From an Apex Class file, use the "Go to Symbol in File" command.  I don't see any method names or other symbols.  
1.  If I use the same command from an Aura .js file, I DO see method names, other symbols.
### Expected result

Should see a list of methods and symbols

### Actual result

None

### Additional information

I'm using the Salesforce Extension back for VSCode, Version: 44.17.0.  

![image](https://user-images.githubusercontent.com/5881820/52006805-e3a2f700-2481-11e9-83b4-c3d887bab486.png)
![image](https://user-images.githubusercontent.com/5881820/52006833-f1587c80-2481-11e9-8244-075c5ec20108.png)

**VS Code Version**:
Version 1.30.2 (1.30.2)

**SFDX CLI Version**:
sfdx-cli/6.50.0-9817aece8a (darwin-x64) node-v8.9.4

**OS and version**:
macOS Mojave 10.14.2

**Comment by ntotten** [comment]
@melissajhansen Are you working against a sandbox/etc or scratch org?

**Comment by ntotten** [comment]
Also, try running the command `SFDX: Refresh SObject Definitions` and see if that makes any difference.

**Comment by melissajhansen** [comment]
I got it!.  VSCode was defaulting to Java as the language on my .cls files.  I needed to change the File Association for .cls to Apex instead of Java.  Thank you!!

**Comment by melissajhansen** [comment]
![image](https://user-images.githubusercontent.com/5881820/52007761-09c99680-2484-11e9-9a6f-4573c736c8a6.png)
