### ISSUE TITLE
Error opening VSCode

### ISSUE THREAD

**Issue by oriolete** [forcedotcom/salesforcedx-vscode#992]
### Summary

Everty time VS Code is opened appears this message:
Request initialize failed with message: LWC Language Server initialization unsuccessful. Error message: Cannot read property 'forEach' of undefined

### Steps To Reproduce:

1.  Open VS-Code

### Expected result

N/A 

### Actual result

N/A

### Additional information

![image](https://user-images.githubusercontent.com/6986296/52044712-14973080-2543-11e9-8596-b12b5923cc16.png)

**VS Code Version**: 1.30.2

**SFDX CLI Version**:6.50.0-9817aece8a

**OS and version**: Mac OSX 10.14.2

**Comment by ntotten** [comment]
Does this happen when you create a new project or are you opening an existing project?

**Comment by oriolete** [comment]
Hi Nathan,

this occurs with projects managed with ForceCode extension perhaps I think this bug could be passed to they.

Best regards

**Comment by ntotten** [comment]
Can you try disabling the forcecode extension and seeing if the error still happens?

**Comment by oriolete** [comment]
Nathan, disabled is working properly and not showing that error.
