### ISSUE TITLE
Replay Debugger: Restart doesn't restart current session

### ISSUE THREAD

**Issue by BrettMN** [forcedotcom/salesforcedx-vscode#993]
### Summary

While using the apex Replay Debugger pressing "Restart" closes the current debug replay and brings user to the log file.  

### Steps To Reproduce:

1.  Start a debug replay
1.  Step through a few lines
1. Press "Restart"

### Expected result

Restart is expected to restart the current debug session not cancel it.

### Actual result

Restart cancels the current debug session

### Additional information

![2019-01-31_09-59-24 1](https://user-images.githubusercontent.com/3488212/52067074-70f85100-253f-11e9-9a67-271ec044b68d.gif)

**VS Code Version**:
Version 1.31.0-insider (1.31.0-insider)

**SFDX CLI Version**:
sfdx-cli/6.50.0-9817aece8a (darwin-x64) node-v8.9.4

**OS and version**:
macOS 10.14.3

**Comment by gbockus-sf** [comment]
Was able to reproduce this issue.  I'm going to remove the bug label and add it back so we get a tracking Work item.

**Comment by CristiCanizales** [comment]
Closing this issue as this is now working as expected and issue can't be reproduced.

**Comment by diyer** [comment]
Uploading Screen Recording 2024-08-14 at 2.56.36 PM.mov…
