### ISSUE TITLE
shortcut to open component library

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#994]
I forget the url for the component library, and have to cut and paste my domain to go find it.  So I wrote a cli command for that `sfdx shane:org:componentlibrary` that opens the library for the current org (or any org via -u) 

**Describe the solution you'd like**
that command, in the command pallette

**Describe alternatives you've considered**
typing it out on the cli each time

https://github.com/mshanemc/shane-sfdx-plugins#sfdx-shaneorgcomponentlibrary

**Comment by ntotten** [comment]
The LWC team has plans to integrate the component library into VS Code. I will share with them.
