### ISSUE TITLE
mdapi coverage report

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#995]
I forget the url for the metadata coverage report, and have to cut and paste my domain to go find it. So I wrote a cli command for that `sfdx shane:org:metadatacoverage` that opens the library for the current org (or any org via -u)

Describe the solution you'd like
that command, in the command pallette

Describe alternatives you've considered
typing it out on the cli each time

https://github.com/mshanemc/shane-sfdx-plugins#sfdx-shaneorgmetadatacoverage

**Comment by lcampos** [comment]
Can you explain why you need to constantly check this report ?

**Comment by brpowell** [comment]
Hi @mshanemc. Your plugin targets the current instance url with /mdcoverage/report.jsp. It used to be the case that the coverage report lived here and the information was dependent on the version of the instance you were viewing it on. This has been replaced by https://developer.salesforce.com/docs/metadata-coverage where you can now select versions and is org independent. /mdcoverage/report.jsp redirects to this URL now.
