### ISSUE TITLE
When will the "develop against any org" feature be GA?

### ISSUE THREAD

**Issue by sunnymatharuuk** [forcedotcom/salesforcedx-vscode#999]
Hi @ntotten , can you advise on roughly when the "develop against any org" feature will be GA?

I recently saw that the eclipse IDE will no longer receive any support as of October 2019.

Though this is not a problem for me or my clients (nobody here is the biggest Eclipse fan), their security team(s) are not willing to let our devs use VS Code + the "any org" feature while it is still in open beta.

Apologies I wasn't sure of the best channel to ask this question.

**Comment by ntotten** [comment]
It will be GA in the next few months. No exact ETA though.
